### ISSUE TITLE
[BUG] <brief bug description> Loading video takes a bit long time 

### ISSUE THREAD

**Issue by sushantbhagat02** [libre-tube/LibreTube#100]
**Describe the bug**
The video loading takes a bit long time . My internet is also fine. Am using a strong wifi connection. Overall the app is really fantastic ✌️✌️

**To Reproduce**

**Smartphone (please complete the following information):**
 - Device:  Redmi note 4
 - Android version: 11

**Additional context**

**Comment by lilcheti** [comment]
It surely needs more work but that's the best we could do rn.

**Comment by sushantbhagat02** [comment]
> It surely needs more work but that's the best we could do rn.

Ya i understand u guys work hard but hope it can get better in future 🙂 ✌️✌️

**Comment by alefvanoon** [comment]
There was probably a problem with the server(piped instance).
