### ISSUE TITLE
Watching specific video from a playlist causes LibreTube to crash

### ISSUE THREAD

**Issue by candroid-man** [libre-tube/LibreTube#1003]
### Steps to reproduce

1. Add this [video](https://piped.kavin.rocks/watch?v=wQLOGroZjBg?t=0) to a playlist
2. Try to play it from playlist
3. See error

### Expected behavior

Not crash

### Actual behavior

Crashes

### LibreTube version

0.4.2

### Android version

12

### Other details

Logs:
```
java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.ArrayList.get(ArrayList.java:437)
	at g4.b0.k0(SourceFile:5)
	at g4.g0.m(SourceFile:6)
	at j8.a.h(Unknown Source:8)
	at y8.i0.run(Unknown Source:86)
	at d9.g.run(Unknown Source:12)
	at e9.j.run(Unknown Source:2)
	at e9.a$a.run(SourceFile:9)
	Suppressed: y8.g0: [o1{Cancelling}@164a6e7, Dispatchers.IO]
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't reproduce, can you retry with the latest CI builds and resend the error log then? It's obfuscated in the normal release builds so debug builds there aren't helpful.

**Comment by candroid-man** [comment]
Sure! How do I do that? Lol

**Comment by Bnyro** [comment]
You can just download and install the "app" [here](https://github.com/libre-tube/LibreTube/actions/runs/2819309769) :p 
It won't override your current installation of LibreTube, it will be a separate app called LibreTube Debug :)

**Comment by candroid-man** [comment]
On the debug version it works fine.

I can't figure out what the problem is, I have even removed it from the playlist and added it again and it still won't work.

**Comment by Bnyro** [comment]
Hmm, maybe I have fixed it unintendedly yesterday already while I changed some stuff there, not sure.

**Comment by Bnyro** [comment]
I was able to reproduce it in the release build now too, but it's working fine in the debug builds as you said.

**Comment by candroid-man** [comment]
Well is there any reason why I shouldn't use the debug version for now?

**Comment by Bnyro** [comment]
It is a bit slower/less performant than the normal release but apart from it there is no reason to not use it

**Comment by Bnyro** [comment]
In your case it's probably not a bad idea to use it until the next release

**Comment by candroid-man** [comment]
I think I may know what is going on.

I just added another video from LibreTube to the same playlist and it too is no longer working. So I think it may happen to any video you add from the LibreTube app

**Comment by Bnyro** [comment]
Yeah, looks like the last video you added always crashes

**Comment by Bnyro** [comment]
But not sure why it doesn't happen in the debug builds anymore
