### ISSUE TITLE
Crash when only have one subscription

### ISSUE THREAD

**Issue by wahyuwiyoko** [libre-tube/LibreTube#1006]
### Steps to reproduce

1. Subscribe only one YouTube channel
2. Open the subscriptions tab
3. App suddenly crash.

### Expected behavior

1. Subscribe only one YouTube channel.
2. Open the subscriptions tab
3. Shows the list of subscriptions and videos

### Actual behavior

It's crash when only have one channel on subscriptions. 
After the crash happen, I try to force stop and then open the app again and go to subscriptions tab, it's crash again.
Same behavior when I try clear data, still crash.

But it's normal when I have two or more subscription.

### LibreTube version

0.4.2 

### Android version

Android 12

### Other details

Here is the error log when I open the app after the crash happen:
https://privatebin.net/?4b522cf722f45c95#V9N4FM5338xNn4jnhxYRtz8wDiQHxExQEBPHNJUPf3s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thank you for reporting the issue, it has been caused when users had less than 10 videos in their subscriptions feed.
It is back to normal in the latest CI builds and therefore will be fixed in the next update :)
