### ISSUE TITLE
Comment translation feature

### ISSUE THREAD

**Issue by clbclby** [libre-tube/LibreTube#1007]
### Describe your suggested feature

It would be nice if the comments section could be translated into other languages.Really need this feature, thanks from the bottom of my heart

### Other details

I found that the titles of many videos are in the language they originally selected, but they are all displayed in English in the app. I hope this can be improved. thank you very much

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We get the video titles from the API, we can't influence that.

Concerning the translation of the comments, we would have to use an external API like LibreTranslate to make that possible.
I don't think it would be a good idea to add this, LibreTube is a app for streaming YouTube videos, not a Translator app.

**Comment by clbclby** [comment]
> We get the video titles from the API, we can't influence that.
> 
> Concerning the translation of the comments, we would have to use an external API like LibreTranslate to make that possible. I don't think it would be a good idea to add this, LibreTube is a app for streaming YouTube videos, not a Translator app.


Thank you for your answer. I hope you can consider it if you think about it. It feels like a more practical function. Thank you very much!
