### ISSUE TITLE
Resume playing

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#1017]
### Describe your suggested feature

Continue playing after interruptions (e.g phonecalls)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't influence, should be handled automatically by the audio focus of exoplayer.
