### ISSUE TITLE
Limit resolution when using mobile data

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#1019]
### Describe your suggested feature

![Screenshot_20220812-100727_NewPipe](https://user-images.githubusercontent.com/104249296/184294601-c92161f7-469a-447e-920d-0304dc23b8a7.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You'll have to set the default resolution for it, that will just result in the same behavior.
