### ISSUE TITLE
Show age restricted content

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#1020]
### Describe your suggested feature

![Screenshot_20220812-101501_NewPipe](https://user-images.githubusercontent.com/104249296/184295468-96dff6ce-f218-492b-8110-0bcf240e11af.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
can't influence, API thing
