### ISSUE TITLE
Improve audio and video format.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#1021]
### Describe your suggested feature

![Screenshot_20220812-101926_NewPipe](https://user-images.githubusercontent.com/104249296/184296094-260a7213-42df-49f6-9a57-97d40a4ad705.jpg)
![Screenshot_20220812-101905_NewPipe](https://user-images.githubusercontent.com/104249296/184296098-16f34b60-7835-494a-ba36-c2ca64924798.jpg)
The formats I marked are not available on LibreTube.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not API-supported
