### ISSUE TITLE
Improved the Save button.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#1027]
### Describe your suggested feature

Icon to add a playlist when you click the save button.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You mean a button to create a new playlist?

**Comment by Nizami20052022** [comment]
![Screenshot_20220812-175903](https://user-images.githubusercontent.com/104249296/184369081-1061d601-c468-4628-9da4-1b7a3bcfc907.jpg)

**Comment by Bnyro** [comment]
I don't see a way to make this possible by keeping our current dialog design.

**Comment by Nizami20052022** [comment]
Then add a button to add a playlist when you hit the save button.
