### ISSUE TITLE
Watch the video later.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#1037]
### Describe your suggested feature

Playlist selection by the app to watch videos later.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You can just make a playlist and call it "Watch later", any in-app solution would have the same issue as #969
