### ISSUE TITLE
Make it easy to delete browsing history.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#1039]
### Describe your suggested feature

Option to delete all viewing history in section with watched videos.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Removed due to #902, no plans to readd it
