### ISSUE TITLE
[FEATURE] Setting up a linter

### ISSUE THREAD

**Issue by AbduAmeen** [libre-tube/LibreTube#104]
**Describe the feature you'd like to see added**
Adding a linter will help to keep the code clean and will help any future commits from adding unnecessary syntax additions.

**Comment by lilcheti** [comment]
Good idea

**Comment by lilcheti** [comment]
Good idea

**Comment by FireMasterK** [comment]
Can we setup/use https://github.com/ScaCap/action-ktlint?
