### ISSUE TITLE
There is no sound from the downloaded video.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#1040]
### Describe your suggested feature

There is no sound from the downloaded video, even though we have selected the audio format during the download.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You only have the choice between downloading audio or video, both at the same time is not possible.

**Comment by Nizami20052022** [comment]
Why download the video if there is no sound when we download the video.

**Comment by Nizami20052022** [comment]
Previously, the application did not have this problem.

**Comment by Broniy** [comment]
This problem must be solved.Because if there is no sound from the video, it makes no sense to download it.
