### ISSUE TITLE
Multiple Profiles

### ISSUE THREAD

**Issue by Generator** [libre-tube/LibreTube#1041]
### Describe your suggested feature

Support multiple profiles on same or other instances without the need to logout/login.
Additional, profiles could set different settings.
This way profiles could have different feeds, playlists, watch history and quickly switch between then.

**Examples:**
* Profile1: 
  * Instance: piped.domain.tld
  * User: John
* Profile2:
  * Instance: piped.site.xyz
  * User: Jack
* Profile3:
  * No login/localonly 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
There's no real way to setup different profiles because we can't modify where the settings you change are stored (it's hard coded by Android).
Next update will include making a backup and restoring the preferences which might help in your case, but it won't include the watch history!
