### ISSUE TITLE
The video is not displayed in full screen with a cutout

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [libre-tube/LibreTube#1042]
### Steps to reproduce

When I press the zoom button, the video still appears on one side with a black bar due to the camera notch on modern devices

### Expected behavior

The video player should ignore cutouts and display in full screen

### Actual behavior

black bar

### LibreTube version

0.4.2

### Android version

android 12

### Other details

![Screenshot_2022-08-13-19-04-07-686_com github libretube](https://user-images.githubusercontent.com/52075465/184501859-c7999f6b-d594-4e3b-8b80-ac4577ed6468.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
fixed in #981

**Comment by d4f5409d** [comment]
This is very problematic when seeking a video.
![Screenshot_2022-11-20-21-44-56-70_54f92cd6866f5233ab0db4392b806878.jpg](https://user-images.githubusercontent.com/76624594/202925263-56c4b538-1d4f-4cac-8494-e58cd4dd1421.jpg)
 Comparison to NewPipe:
![Screenshot_2022-11-20-21-46-52-69_d7d328def685d290e891d05b54a6e164.jpg](https://user-images.githubusercontent.com/76624594/202925312-4e6f19fe-0a67-4e54-8662-e4bdd2be6abc.jpg)
