### ISSUE TITLE
Automatically scale video to full screen

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [libre-tube/LibreTube#1043]
### Describe your suggested feature

An item in the settings that allows to automatically scale (zoom) the video to full screen without pressing the inconvenient button in the player each time in each video.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
There's an option called auto-fullscreen that automatically goes to fullscreen mode when your device is in landscape mode.
I don't think we need an extra option for it.

**Comment by Envel-Nikita-Gutsenkov** [comment]
> There's an option called auto-fullscreen that automatically goes to fullscreen mode when your device is in landscape mode. I don't think we need an extra option for it.

see #1059
