### ISSUE TITLE
Import from NewPipe not working

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [libre-tube/LibreTube#1044]
### Steps to reproduce

1. export from newpipe
2. import in libretube

The app says everything is fine, but the list of subscriptions is still empty

### Expected behavior

not an empty list of subscriptions?

### Actual behavior

empty list of subscriptions

### LibreTube version

0.4.2

### Android version

android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
fixed with #982

**Comment by Envel-Nikita-Gutsenkov** [comment]
> fixed with #982

same in dev build 1660464109
CI #1733: Commit d055ca3

**Comment by Donkey-Doug** [comment]
Does not work in latest version.

**Comment by Bnyro** [comment]
Weird, it worked without problems when I tested it

**Comment by hornyjailfish** [comment]
v0.5.0 from fdroid 
got "Something went wrong" message
