### ISSUE TITLE
The button for importing subscriptions without authentication does not work (locally)

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [libre-tube/LibreTube#1045]
### Steps to reproduce

If I do not log in, but try to import subscriptions locally, this will not work.

### Expected behavior

work locally?

### Actual behavior

not working locally

### LibreTube version

0.4.2

### Android version

android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
changed in #982
