### ISSUE TITLE
Icon blur on small screen phone.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#1051]
### Steps to reproduce

.

### Expected behavior

The Icon should look clean.

### Actual behavior

![IMG-20220813-WA0004](https://user-images.githubusercontent.com/104249296/184506574-9ca75957-fcbd-4127-814b-529dc1574fd5.jpg)
![IMG-20220813-WA0003](https://user-images.githubusercontent.com/104249296/184506575-38ab4407-d75c-418a-9d87-3f37db788553.jpg)
![IMG-20220813-WA0005](https://user-images.githubusercontent.com/104249296/184506637-f2cedc7f-09d9-4f91-9c02-647be37cda7b.jpg)

### LibreTube version

0.4.2

### Android version

Android 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Android automatically uses the best resolution for your phone, we can't influence that behavior.
