### ISSUE TITLE
Download Notifications.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#1052]
### Describe your suggested feature

Notification when download is finished and in progress.Manage these notifications.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We already have these notifications.
