### ISSUE TITLE
Option to share the app.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#1054]
### Describe your suggested feature

Option to share the app with more people.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You can just share the app via the F-Droid or the Github URL, sth like this inside the app reminds me on annoying pop-ups in proprietary apps.
