### ISSUE TITLE
fullscreen mode not working

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [libre-tube/LibreTube#1059]
### Steps to reproduce

1. enable fullscreen mode
2. open any video

### Expected behavior

![Screenshot_2022-08-14-11-38-18-648_com github libretube](https://user-images.githubusercontent.com/52075465/184529230-9b032392-1848-4101-afc5-c96ea1caa20a.jpg)

### Actual behavior

does not scale to fit the screen and has to press the button manually each time
![Screenshot_2022-08-14-11-35-25-566_com github libretube](https://user-images.githubusercontent.com/52075465/184529233-f80d771e-8852-44c4-94e0-2380347ce63d.jpg)
![Screenshot_2022-08-14-11-35-41-135_com github libretube](https://user-images.githubusercontent.com/52075465/184529236-ee092571-ca85-42ee-b5a3-b12a2f1bd183.jpg)

### LibreTube version

0.4.2

### Android version

android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not what auto-fullscreen means. You can control that behavior by clicking the arrow on the top right and clicking the aspect ratio button.

**Comment by Envel-Nikita-Gutsenkov** [comment]
> 
yes, what I'm talking about, I have to click on each video, it's more convenient when it's done automatically

**Comment by Bnyro** [comment]
Oh, now I got it, I will add such an option, sorry for the inconvenience
