### ISSUE TITLE
Sharper Thumbnails maybe

### ISSUE THREAD

**Issue by Jomyy** [libre-tube/LibreTube#1061]
### Describe your suggested feature

maybe we can use https://i.ytimg.com/vi/$id/hqdefault.jpg
to get higher quality thumbnails 
though I don't know the data collection 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't want to add something 3rd party, we should rather wait for [NewPipeExtractor#889](https://github.com/TeamNewPipe/NewPipeExtractor/pull/889)
