### ISSUE TITLE
Background player does not work

### ISSUE THREAD

**Issue by KurozyOS** [libre-tube/LibreTube#1063]
### Steps to reproduce

1. Start a video
2. Click to turn off screen(lock)
3. Wait for buffer to end 

### Expected behavior

Continue playing selected video 

### Actual behavior

Stops playing video

### LibreTube version

0.4.2

### Android version

Android 11

### Other details

Auto start enabled and there is no battery saver resistance 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
When it stops to play when the screen is turned off, Android sends the app to sleep which we can't influence. You can disable battery optimization for the app and remove other system restrictions to remove the behavior a bit but it won't resolve the issue.

That's what we have the background mode for. It runs as a foreground service on your device so that Android won't stop it, therefore you should use it instead.

**Comment by Nephys222** [comment]
@Bnyro Background mode made app crash on Android 7.0. Might it does not support lower versions?:

`java.lang.NoSuchMethodError: No virtual method startForegroundService(Landroid/content/Intent;)Landroid/content/ComponentName; in class Landroid/content/Context; or its super classes (declaration of 'android.content.Context' appears in /system/framework/framework.jar) at com.github.libretube.util.BackgroundHelper.playOnBackground(BackgroundHelper.kt:24) at com.github.libretube.util.BackgroundHelper.playOnBackground$default(BackgroundHelper.kt:11) at com.github.libretube.dialogs.VideoOptionsDialog.onCreateDialog$lambda-1(VideoOptionsDialog.kt:66) at com.github.libretube.dialogs.VideoOptionsDialog.$r8$lambda$ZQg9AqL8WzlxH51svNA4_py-AIM(VideoOptionsDialog.kt) at com.github.libretube.dialogs.VideoOptionsDialog$$ExternalSyntheticLambda0.onClick(D8$$SyntheticClass) at androidx.appcompat.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1068) at android.widget.AdapterView.performItemClick(AdapterView.java:310) at android.widget.AbsListView.performItemClick(AbsListView.java:1229) at android.widget.AbsListView$PerformClick.run(AbsListView.java:3234) at android.widget.AbsListView$3.run(AbsListView.java:4153) at android.os.Handler.handleCallback(Handler.java:751) at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:173) at android.app.ActivityThread.main(ActivityThread.java:6523) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)`

**Comment by Bnyro** [comment]
True, looks like it's not supported on low APIs

**Comment by Nephys222** [comment]
I tested on my device and fixed and opened pull request #1111.
