### ISSUE TITLE
Turn on/off autoplay from the player

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#1066]
### Describe your suggested feature

Turning autoplay on/off from player doesn't work. Turning it on/off from player doesn't affect the video. Adjust it with autoplay in settings.No problem turning autoplay on/off in settings.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It should be fixed now
