### ISSUE TITLE
Remind me when it's time to sleep.

### ISSUE THREAD

**Issue by Broniy** [libre-tube/LibreTube#1071]
### Describe your suggested feature

Remind me when it's time to sleep.Please add I use this feature a lot on youtube.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You already opened an issue for it and I added it?!

**Comment by Broniy** [comment]
Please add.
