### ISSUE TITLE
M4A with 320 kbps

### ISSUE THREAD

**Issue by imashar7** [libre-tube/LibreTube#1073]
### Describe your suggested feature

Please add option to download m4a and mp3 file in different bitrate like 320 kbps, 256 kbps and 128 kbps

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We already support all qualities for download that Piped supports. Supporting better qualities would require changes in the NewPipeExtractor.

**Comment by FireMasterK** [comment]
YouTube provides m4a only at 40/50 kbps iirc
