### ISSUE TITLE
Replace the word Trending with the word Home

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#1075]
### Describe your suggested feature

Change the word Trending to Home in the sentence "Hide Trending page".Because the word in this sentence must be the same as the name of the tab.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Then you would change the default home page to "home", which doesn't make sense either.
