### ISSUE TITLE
Remove watched videos from playlist.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#1076]
### Describe your suggested feature

Videos that have been watched before and after being added to the playlist will be removed.Including in partially watched videos.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Don't think many people would use it, playlists are rather for stuff like music that you want to listen to multiple times.

**Comment by rozari0** [comment]
> Don't think many people would use it, playlists are rather for stuff like music that you want to listen to multiple times.

It's not something that I would use daily, but sometime I us this for removing watched video for watch later playlist in newpipe. That would be great if you reconsider this.
