### ISSUE TITLE
Mark videos as watched.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#1077]
### Describe your suggested feature

Option to mark videos as watched.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's what's done with the red line on the thumbnail of the video. Marking it as watched doesn't make sense since you didn't see the video then?!
