### ISSUE TITLE
Icon not in app.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#1078]
### Describe your suggested feature

![Screenshot_20220816-174946_NewPipe](https://user-images.githubusercontent.com/104249296/184896499-1a11b8e6-7697-4c45-b55c-33a7d0d77d8e.jpg)
The arrow icon was missing from the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
?
