### ISSUE TITLE
[Bug] Download failed

### ISSUE THREAD

**Issue by CasuallyOrange** [libre-tube/LibreTube#108]
When trying to download a video it starts the download and after starting it just says download failed

To reproduce click download on a video.

On Android 9

**Comment by lilcheti** [comment]
So I had this problem on lower versions too but seems like it works but fails when there is not enough storage on your device or on bad network connections.

**Comment by CasuallyOrange** [comment]
> So I had this problem on lower versions too but seems like it works but fails when there is not enough storage on your device or on bad network connections.

My network connection is fine and I have 20 gb of free storage but an 87 mb file won't download

**Comment by lilcheti** [comment]
Downloadmanager problem then could u provide me some logs?

**Comment by CasuallyOrange** [comment]
> Downloadmanager problem then could u provide me some logs?

How?
