### ISSUE TITLE
Show how many answeres a comment has 

### ISSUE THREAD

**Issue by Jomyy** [libre-tube/LibreTube#1082]
### Describe your suggested feature

Its kind of weird to always have to click on a vomment to know if it has answeres

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We can't figure it out, it requires changes in the NewPipeExtractor, we can only determine whether any replies are available.
I already thought about adding a button called "show replies" that is only visible if there are replies but I couldn't find a way to make it fit the UI.
