### ISSUE TITLE
Full-Screen Mode when Phone Rotated to Landscape Mode

### ISSUE THREAD

**Issue by bell-kevin** [libre-tube/LibreTube#1083]
### Describe your suggested feature

Full-Screen Mode when Phone Rotated to Landscape Mode

So right now all I can see is something like this:
![th-2486286628 (1)](https://user-images.githubusercontent.com/8269880/185242991-cac613d7-c249-48e7-9afc-3f594b1d7e90.png)

What I want to see is something like this:

![th-1975121898](https://user-images.githubusercontent.com/8269880/185242975-0a3785f1-f445-4077-bf68-240e03e39f79.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by bell-kevin** [comment]
I see I can use VLC app to open the video via LibreTube and then watch the video in landscape mode using VLC app. So I am partially appeased. I will close this ticket now.

**Comment by bell-kevin** [comment]
But I would still like to see this feature as a real feature.

**Comment by Bnyro** [comment]
Isn't there already an option called Auto-fullscreen though?

**Comment by bell-kevin** [comment]
I want to turn my phone sideways and have the app. automatically go full screen.

**Comment by Bnyro** [comment]
When being at the miniplayer?

**Comment by bell-kevin** [comment]
No. I know I can hit the full screen icon in the bottom right hand corner on the screen in order to make it full screen, but I was wondering if it could happen automatically by detecting the orientation of my phone.

**Comment by Bnyro** [comment]
Yes, there is an option called Auto fullscreen in the player settings, that should in fsct exactly be what you're looking for, please try that one!

**Comment by bell-kevin** [comment]
Oh! Awesome! I had no idea! Thank you so much!

**Comment by Bnyro** [comment]
Sorry that I didn't mention that earlier, I just didn't really get what the issue was about because I thought you would have been aware of the option. But anyways, you're welcome :)
