### ISSUE TITLE
Add playlist playback function.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#1089]
### Describe your suggested feature

You have added the function to play the playlist in the background.Add the function to play the playlist.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
When selecting a video inside a playlist, it just plays the playlist in the background :)
