### ISSUE TITLE
[FEATURE] Stretch videos

### ISSUE THREAD

**Issue by CasuallyOrange** [libre-tube/LibreTube#109]
Since most mobiles come with an aspect ratio or 18:9 or higher but yt videos are usually posted in 16:9 it would be nice to have an option to stretch the video to fill the whole screen.
I don't mean zooming in on a video like the option in YouTube since that makes you lose some of the top and bottom parts of the video.

**Comment by lilcheti** [comment]
It makes the video looks bad if we stretch it. The pinch to zoom like YouTube is better.

**Comment by CasuallyOrange** [comment]
> It makes the video looks bad if we stretch it. The pinch to zoom like YouTube is better.

I mean, just adding the option won't hurt would it?
Those that want to stretch it for full screen will use it and those that don't want to won't..
I have an 18:9 aspect ratio phone and videos don't look bad when stretched.. so I use that option whenever available

**Comment by novocaiin** [comment]
> It makes the video looks bad if we stretch it. The pinch to zoom like YouTube is better.

Is pinch zoom like YouTube planned?
Would be divine.
