### ISSUE TITLE
Auto-queue.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#1090]
### Describe your suggested feature

Continue the playback sequence by adding the next related stream.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We already have a playback queue and autoplay.

**Comment by Nizami20052022** [comment]
This feature is different from Autoplay.Because Auto-queue continues the playback order by adding the related stream (non-repeat).
