### ISSUE TITLE
Material You Theme doesn't work

### ISSUE THREAD

**Issue by Radical4ever** [libre-tube/LibreTube#1095]
### Describe your suggested feature

Before the update the coloring was working, but since this one is no longer working. Its possible to make an option for this?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's how it should be in theory, it's most likely a bug.

**Comment by xIUPITERx** [comment]
I lost the Material You Theme with the last update.
