### ISSUE TITLE
Subtitles cut off when zoomed

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [libre-tube/LibreTube#1100]
### Steps to reproduce

1. enable zoom mode (20:9 display)
2. enable subtitles

### Expected behavior

make subtitles a little higher or dynamically changing position, depending on the display and mode

### Actual behavior

![Screenshot_2022-08-20-12-12-01-991_com github libretube](https://user-images.githubusercontent.com/52075465/185738522-5ba1a087-392b-49b9-bf6e-404fb7c69d7b.jpg)

### LibreTube version

0.5

### Android version

android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
These are the default settings by the exoPlayer, they are immutable in terms of position so we can't really do anything here.

**Comment by Envel-Nikita-Gutsenkov** [comment]
> These are the default settings by the exoPlayer, they are immutable in terms of position so we can't really do anything here.

in NewPipe (exoplayer) works fine...
