### ISSUE TITLE
Possibility to disable autoplay when clicking a video

### ISSUE THREAD

**Issue by rene-coty** [libre-tube/LibreTube#1102]
### Describe your suggested feature

The app settings allow to disable autoplay but only to avoid playing another video at the end of a first one. That would be good to have the possibility to disable autoplay simply when a video is clicked.
Indeed, when a video is clicked, it is played automatically. This can be annoying when you are trying to avoid consuming too much data and have opened the video just to download it and watch it later.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FireMasterK** [comment]
What I would rather suggest would be able to download a video by simply tapping and holding in the menu.

**Comment by rene-coty** [comment]
Yes good idea, that would make downloading easier
