### ISSUE TITLE
Instant opening of some functions in the player

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#1104]
### Describe your suggested feature

It is not possible to apply functions related to the player immediately. It is necessary to close the video and play it again.
![Screenshot_20220820-185719_LibreTube](https://user-images.githubusercontent.com/104249296/185752818-fd840d52-3296-4290-8050-cebf2038fc41.jpg)
![Screenshot_20220820-185629_LibreTube](https://user-images.githubusercontent.com/104249296/185752819-bc6794ba-1b43-4e90-a686-6e547b46b0e5.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Most of them can be changed by clicking the arrow on the top right.
