### ISSUE TITLE
Hide larger quality options.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#1105]
### Describe your suggested feature

Hide larger quality options. Because some devices can play 2K/4K videos.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Envel-Nikita-Gutsenkov** [comment]
if your device does not support 2k, it does not mean that others do not.  the more high quality will still give the best visual effect, although it will not be 4k
