### ISSUE TITLE
Pop-up button in the player section

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#1106]
### Describe your suggested feature

![Screenshot_20220820-193602_NewPipe](https://user-images.githubusercontent.com/104249296/185754938-c2c727d8-2821-45fe-845a-1367309e11d0.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
1. We don't have space for it there
2. It feels more native to achieve it by going to the homescreen as most other apps do it
