### ISSUE TITLE
[BUG] HDR Content displayed with wrong colors

### ISSUE THREAD

**Issue by FireMasterK** [libre-tube/LibreTube#112]
**Describe the bug**
HDR av1 streams seem to display the colors incorrectly

**To Reproduce**
Play https://piped.kavin.rocks/watch?v=linlz7-Pnvw

HDR:
![Screenshot_20220330-201116_LibreTube.png](https://user-images.githubusercontent.com/20838718/160913075-6557728d-095e-402a-8959-bd5021cb340e.png)

Non HDR:
![Screenshot_20220330-201203_LibreTube.png](https://user-images.githubusercontent.com/20838718/160913085-395cf8ba-ba13-42eb-8582-71bd61931815.png)

**Smartphone (please complete the following information):**
 - Device: Poco F3
 - Android version: 12

**Additional context**

**Comment by lilcheti** [comment]
Is this an exoplayer bug?

**Comment by Bnyro** [comment]
It works fine for me (A12L) with your link. Is it still an issue for you?

**Comment by archroid** [comment]
I didn't get the first image. Is it a filter that makes the content HDR?

**Comment by FireMasterK** [comment]
This no longer happens.
