### ISSUE TITLE
Allow import of subscriptions without account

### ISSUE THREAD

**Issue by ph00lt0** [libre-tube/LibreTube#1122]
### Describe your suggested feature

Very happy to see you can now have subscriptions without piped, but they cannot be imported yet

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I assume you use version 0.4.2, it works since 0.5.0 :)
