### ISSUE TITLE
Background playback does not work properly.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#1123]
### Describe your suggested feature

Background playback is enabled on the device by clicking Home and Recents button.(PIP mode must be disabled to play background when tapping home button,).So there should be an option in settings to disable background playback generally.The background button on the player does not work properly.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It works properly, I think an option for it is unnecessary.
