### ISSUE TITLE
Allow manual refresh of subscriptions or in the background

### ISSUE THREAD

**Issue by ph00lt0** [libre-tube/LibreTube#1124]
### Describe your suggested feature

I have a lot of subscriptions so loading them takes for ever, this blocks me from opening a video after which tabs as it immediately starts reloading. 

It would be great if you could manually refresh the subscriptions instead or if the app just updates them in the background and than prepends the new video's on top. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's nothing I'm in favor of, sorry. I have no idea how that should be placed in the user interface and how this should be done performance wise.
I would recommend either getting rid of some subscriptions or splitting them into multiple accounts.

**Comment by Bnyro** [comment]
@ph00lt0 I found a way to implement this now with #1176:
When navigating to the subscriptions page, it will now continue to load them in the background. When navigating back afterwards, it won't reload the feed again, it will then show the one previously loaded in the background.

I hope this will improve your experience with the feed :D
