### ISSUE TITLE
Some videos are not played if a specific resolution is set, but only with auto

### ISSUE THREAD

**Issue by lucamp** [libre-tube/LibreTube#1132]
### Steps to reproduce

1. Choose a fixed resolution under LibreTube's setting, it doesn't matter which one or webm / mpeg
2. Play these videos
- https://www.youtube.com/watch?v=Q5ESzNFQEqg
- https://www.youtube.com/watch?v=lx3Zc0hibXI

### Expected behavior

Play starts with no issue

### Actual behavior

After hitting play button, the pause button appears and it seems that the video is being downloaded, but it doesn't start and stops after few seconds

# workaround
Choose "auto" as resolution in the video page

### LibreTube version

0.5.0

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by KurozyOS** [comment]
Same goes for me when resolution is not set to auto. android 11

**Comment by lucamp** [comment]
> Could anyone please test it with an older version to determine whether it's related to any in-app changes? Thanks in advance!

previous version 0.4.2 was also affected, I waited the new 0.5.0 to open the bug

**Comment by lucamp** [comment]
0.3.3 and 0.3.2 from github are also affected.

Those videos are played with no issue in piped using a browser

**Comment by Bnyro** [comment]
That's really weird, the issue wasn't there when they were the latest releases back then and I don't think anything API related changed in terms of video sources...

**Comment by Bnyro** [comment]
I think it is related to some recent YouTube-changes and not to the way the app itself works, therefore closing it for now.

**Comment by lucamp** [comment]
> I think it is related to some recent YouTube-changes

In Firefox I have a fixed resolution of 480 saved with cookies and those videos have not this issue if I play them with piped.mha.fi. I also tried piped.kavin.rocks and it's fine.

If youtube has changed something they will not play on piped web version, am I wrong?

**Comment by Bnyro** [comment]
@lucamp No, as far as I know Piped uses HLS for all resolutions instead of WEBM or MPEG as we currently do 🤔

**Comment by lucamp** [comment]
With release 0.5.1 those videos crash after trying to load, so it's no longer possible to choose auto in their page as a workaround; but auto have to be enable all the time in the settings.

Meanwhile I found others videos with the same issue

**Comment by Bnyro** [comment]
Hmm, that's very unfortunate. Could you find any error logs?

**Comment by lucamp** [comment]
I am not sure if it's ok but I used matlog filtering "exop" since exoplayer had errors

[2022-09-16-23-38-19.txt](https://github.com/libre-tube/LibreTube/files/9588307/2022-09-16-23-38-19.txt)

**Comment by lucamp** [comment]
More videos are having this issue.

Is it worth switching entirely to HLS for every resolution and not only for auto?

**Comment by Bnyro** [comment]
> More videos are having this issue.
> 
> Is it worth switching entirely to HLS for every resolution and not only for auto?

Yes, it looks like YouTube is currently removing support for these formats, using Auto/HLS is recommended for now!

It might  be a good idea to replace the current quality settings and always use HLS and just limit the quality of it!

**Comment by lucamp** [comment]
>It might be a good idea to replace the current quality settings and always use HLS and just limit the quality of it!

Actually hls limit is only at 1080p, other resolutions should be available (360, 480, 720)
