### ISSUE TITLE
share with time should have an option to enable or disable it

### ISSUE THREAD

**Issue by lucamp** [libre-tube/LibreTube#1137]
### Describe your suggested feature

share a video with its time has been implemented with https://github.com/libre-tube/LibreTube/issues/955

please make it optional:
1. new option under Libretube setting
2. ask for it after clicking sharing button; for instance adding a checkbox near the actual menu where the user can choose to share piped or youtube link. This checkbox should be checked or not as default according to LibreTube setting choice

Thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by lucamp** [comment]
Sorry I just found that the option 1 already exist in the advanced section.

If you would like to consider the checkbox maybe it would help others

**Comment by Bnyro** [comment]
I didn't notice the option was gone, it does remember it now :)
