### ISSUE TITLE
[FEATURE] Audio only mode

### ISSUE THREAD

**Issue by IceDBorn** [libre-tube/LibreTube#114]
An audio only mode, useful for music and podcasts. Currently I have to use the browser to listen to podcasts.

**Comment by lilcheti** [comment]
why? it won't play those in the app?

**Comment by IceDBorn** [comment]
You can't play a video in audio only mode, there is not such an option.

**Comment by lilcheti** [comment]
Oh yes there is not thought those videos won't play.

**Comment by IceDBorn** [comment]
![image](https://user-images.githubusercontent.com/51162078/161384333-3d0a6d0d-1833-492d-982a-80fe96680ff3.png)
I'm talking about the functionality of this button, turning videos into sound only.

**Comment by Relwi** [comment]
I see this feature useful too, like NewPipe does, we can implement a background mode, then people like me could listen a music without loading the video.

I was watching this issue and was thinking on implement it, but I'm still waiting to this pr https://github.com/libre-tube/LibreTube/pull/98 to generate the code with a nice structure.

So, +1 to this feature.

**Comment by lilcheti** [comment]
We waited for his pr for so long but he didn't finish it hope he does someday.

**Comment by Relwi** [comment]
I'm gonna try to implement this then, when I have time

**Comment by martin-desktops** [comment]
My suggestion about it - audio mode should be accessible even before playing video. It allows user to not wasting his data plan and time on loading first fragments of video that he won't watch anyway.
In NewPipe it is possible to play audio alone just by holding the video thumbnail and title for a short time and pressing "Start playing in the background"

**Comment by Relwi** [comment]
> In NewPipe it is possible to play audio alone just by holding the video thumbnail and title for a short time and pressing "Start playing in the background"

This is the idea, now, pray that is gonna work 🙏
