### ISSUE TITLE
Language doesn't change the settings page

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#1151]
### Steps to reproduce

If I change the language setting from German to English, the language of the app changes except for the language of the settings page, that is still in German.

### Expected behavior

The language of the settings page should change to English with the rest of the app.

### Actual behavior

The settings page stays German.

### LibreTube version

0.5.0

### Android version

Android 12 with One UI 4.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Tested with multiple languages including German and it always worked. Could you please provide a screen recording?

**Comment by xIUPITERx** [comment]
![signal-2022-08-25-113409_002](https://user-images.githubusercontent.com/97352673/186630674-cb09dc5d-334b-4e77-97eb-e1be669540dd.jpeg)

**Comment by Bnyro** [comment]
You're sure that you restarted the app?

**Comment by xIUPITERx** [comment]
https://user-images.githubusercontent.com/97352673/186632442-a0a08f84-e553-4a01-afae-36b063e2ee17.mp4

Yes, I am sure.

**Comment by xIUPITERx** [comment]
Yes, but I have never done something like that.

**Comment by Bnyro** [comment]
No worries, it's not hard :)

**Comment by Bnyro** [comment]
Please download the "app" file [here](https://github.com/libre-tube/LibreTube/actions/runs/2925586418), unzip and install it.
Then you're good to test whether it works now :)

**Comment by xIUPITERx** [comment]
In the "test"-app the settings page is now displayed in the correct language

**Comment by Bnyro** [comment]
Great to hear, thank you for testing it <3

PS: Wünsche dir noch nen schönen restlichen Tag, genieß das Wetter ;)

**Comment by xIUPITERx** [comment]
you're welcome, glad I could help

Danke, dir auch einen schönen Tag :)
