### ISSUE TITLE
Blank Screen after minimizing Video Player

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#1154]
### Steps to reproduce

When you watch a video for a while and then reduce the video player by dragging it down, a blank page appears

https://user-images.githubusercontent.com/97352673/186649314-d71e7aa4-794f-4677-bdef-dd2a17090cbe.mp4

.

### Expected behavior

Your subscription feed should appear.

### Actual behavior

A blank page appears.

### LibreTube version

0.5.0

### Android version

Android 12 One UI 4.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not able to reproduce, I guess that Android removed the previous fragment from RAM maybe, not sure 🤔

**Comment by xIUPITERx** [comment]
Maybe you have to hide the trending page and set the default tab to subscriptions.

**Comment by KurozyOS** [comment]
I have the same problem, it occurs very often. Default tab is set to sub.
![Screenshot_2022-08-28-00-06-20-842_com github libretube](https://user-images.githubusercontent.com/81830783/187049674-5118b78b-6258-4c5c-b5bd-2ed04f0096d4.jpg)

**Comment by xIUPITERx** [comment]
Could you just force the app to open the homescreen if you minimize the exoplayer after maybe 15 minutes of watchtime?

**Comment by xIUPITERx** [comment]
I think this issue is solved, as I didn't had it in some time. 
Has the problem been solved for others? @KurozyOS

**Comment by KurozyOS** [comment]
Didn't had it since the update of 0.6.0
