### ISSUE TITLE
Save the last subscription feed

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#1156]
### Describe your suggested feature

Save the last subscription feed so that it doesn't have to be completely reloaded every time you press the subscription button.
Maybe only have the last 10 videos saved so it is never empty when you go back to the subscription feed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Donkey-Doug** [comment]
Somewhat related to #1166

**Comment by xIUPITERx** [comment]
I have no problem with the loading speed but it should not always have to be reloaded from scratch.

**Comment by Bnyro** [comment]
related: #1124 
I'll have a look since it seems to be a real problem due multiple people asking for a work around for the feed loading times.

**Comment by Donkey-Doug** [comment]
> related: #1124 I'll have a look since it seems to be a real problem due multiple people asking for a work around for the feed loading times.

Keep in mind some people might have many subscriptions. Perhaps only load the 3 most recent entries per subscription and only reveal more when people scroll down.

**Comment by xIUPITERx** [comment]
How exactly is this feature implemented?
