### ISSUE TITLE
New "audio only" interface

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#1157]
### Describe your suggested feature

1. Show the thumbnail of the video and indicate that it's just an audio player 
2. Sync the progress bar with the media controls 
3. (maybe also support the new android 13 media controls)
4. If "audio only" is turned on, change the button with which you activated "audio only" to return to the normal video mode. (e.g. show a video icon)
5. Use timestamps to go to the position there you stopped the "audio only" mode so you don't lose any  progress

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
3. Will be automatically supported afaik (at least we can't influence it)

2, 4, 5. Requires communication between the player fragment (what you see) and the background mode service which is responsible for the background playback. As far as I know, communication between the fragment and the background mode running as foreground service is not possible iirc. Apart from that communication with normal services is a mess, so I doubt these things are possible.

1. Might be a good idea but would completely remove responsiveness from the player view and wouldn't allow switching back.

**Comment by xIUPITERx** [comment]
2. But how do music players like Spotify do it?
I know Deezer has problems with it, but maybe there are some open source music players who have implemented this feature.

**Comment by xIUPITERx** [comment]
3. I thought you have to actively implement the Android api 33 sdk

**Comment by Bnyro** [comment]
> 2. But how do music players like Spotify do it?
>        I know Deezer has problems with it, but maybe there are some open source music players who have implemented this feature.

I don't know how they do it, but it's probably a very complex work-around I guess.



> 3. I thought you have to actively implement the Android api 33 sdk

No, I already have the new notification UI in my Android 13 emulator, normal devices do behave the same way. I even got a screenshot of someone who is already on Android 13 using LibreTube with the new notification design ;)

**Comment by xIUPITERx** [comment]
> Might be a good idea but would completely remove responsiveness from the player view and wouldn't allow switching back.

Couldn't you just save the Youtube link and timestamp to go back to the normal video mode?

**Comment by Donkey-Doug** [comment]
Alternatively, maybe use a local media player to handle the audio stream?

**Comment by oldxiao6481** [comment]
> ### Describe your suggested feature
> 
>     1. Show the thumbnail of the video and indicate that it's just an audio player
> 
>     2. Sync the progress bar with the media controls
> 
>     3. (maybe also support the new android 13 media controls)
> 
>     4. If "audio only" is turned on, change the button with which you activated "audio only" to return to the normal video mode. (e.g. show a video icon)
> 
>     5. Use timestamps to go to the position there you stopped the "audio only" mode so you don't lose any  progress
> 
> 
> ### Other details
> 
> _No response_
> ### Acknowledgements
> 
>     * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> 
>     * [x]  I have written a short but informative title.
> 
>     * [x]  I will fill out all of the requested information in this form.

**Comment by Theoldnation** [comment]
i think the sync between player and background mode is already possible in newpipe if i'm not wrong

**Comment by karioki** [comment]
Seems like very good idea!
