### ISSUE TITLE
Autorotation does not work

### ISSUE THREAD

**Issue by KurozyOS** [libre-tube/LibreTube#1161]
### Steps to reproduce

I turned on the toggle in settings for autorotation, but when I'm watching a video, nothing I seem to do will make the video fullscreen besides clicking the button in the bottom right of the player.

### Expected behavior

Enters the full screen and exits on rotation

### Actual behavior

Only enters when clicked on fullscreen button

### LibreTube version

0.5.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You need to turn on Auto-fullscreen in the audio and video settings for that, normal auto rotation is for anything but the player.
