### ISSUE TITLE
Crash Reports logger 

### ISSUE THREAD

**Issue by UnknownElen** [libre-tube/LibreTube#1164]
### Crash logger

I think it would be easier just to add a crash logger or tracker for a while to fix all bugs and crashes

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We already have an in-app crash-handler...
