### ISSUE TITLE
Loading subscriptions is slow

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#1166]
### Steps to reproduce

1. Go to subscriptions tab
2. Waiting until the list is updated takes long

### Expected behavior

Faster loading

### Actual behavior

Slow loading

### LibreTube version

0.5.0

### Android version

Android 10

### Other details

I have many subscriptions (~70), but newpipe still loads them much faster than libretube.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
see https://github.com/TeamPiped/Piped/issues/1046

**Comment by Bnyro** [comment]
The official instance is down at the moment so it might have trouble trying to connect to the servers.
