### ISSUE TITLE
Video pause 5 minutes after screen lock in adnroid 

### ISSUE THREAD

**Issue by lefterisALEX** [libre-tube/LibreTube#1171]
### Steps to reproduce

1. Install LibreTube
2. under apps -> LibreTube -> Battery and set to be "Unrestricted".
3. Play a video and lock the screen
4. Wait for 5-7 minutes. Video will pause and will resume after unlocking the screen  

### Expected behavior

"Video should keep playing"

### Actual behavior

Video pause 

### LibreTube version

0.5.0

### Android version

Andoid 12

### Other details

Device Samsung S20 FE 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by KurozyOS** [comment]
You have to open the video by holding on it and select play in background. Explained by the dev why is this happening here #1063

**Comment by lefterisALEX** [comment]
Works, thanks. But this plays only the sound not the video.

**Comment by KurozyOS** [comment]
Seems that it isn't implemented yet #1113
