### ISSUE TITLE
Block/Allow list channel

### ISSUE THREAD

**Issue by KurozyOS** [libre-tube/LibreTube#1173]
### Describe your suggested feature

User can add a list of blocked channels and they do not appear while searching for them and can't play those videos.

Same goes for allowed, but blocks everything that is not on a list.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Blocking channels might be possible with some work spent in it, but I don't think that allowing only a list of channels
1. really makes sense
2. is a good idea since trending page, search, ... would be almost empty if not empty all the time

**Comment by KurozyOS** [comment]
Well I thought as a parental control feature, there is no way to limit what kids can watch on the YT. 

Maybe user can choose one option or another, this way they know what they are getting if they just allow certain channels.

**Comment by xIUPITERx** [comment]
But then the parents would also have to be able to secure the settings and all the lists with a password or pin, which would actually not be a bad idea.

**Comment by Bnyro** [comment]
I doubt that there are many parents using the app for their kids to be honest.
That feature probably wouldn't be used a lot while being a lot of work.

A easier solution for parents would probably just be to allow using the subscriptions tab only without a password, but I still doubt that this would really be used.

**Comment by Bnyro** [comment]
I decided to not add this feature to LibreTube for now because I don't really think it would be that useful.

I made a PR to add the feature to Piped because it's way easier to implement there, we'll see whether Kavin wants it in or not.

Regards

**Comment by paisano117** [comment]
Pretty disappointed in this decision as being able to hide specific channels, greatly improves the user experience by filtering out spam/scam and obnoxious content, YouTube itself has this feature with the "do not recommend videos from this channel" button, but the issue is that it doesn't hide blocked channesl from search results.

**Comment by flexxxxer** [comment]
Everyone is welcome to use [FlexTube](https://github.com/flexxxxer/FlexTube) where ability to dismiss specific channels is available. FlexTube is LibreTube with few changes, so user experience pretty close.

Notice: Bnyro [allowed](https://github.com/libre-tube/LibreTube/discussions/8168#discussioncomment-16308171) to mention FlexTube in issues being addressed by FlexTube

**Comment by code-IM-perfect** [comment]
With the amount of spammy and clickbait channels out there, this feature is more like a necessity. This is such an important feature that YouTube themselves give an option to do this on every platform they support.

As a more featureful client, I think it makes sense for LibreTube to at least support the level of blocking that YouTube does.
