### ISSUE TITLE
show fullscreen toggle button even if in "auto fullscreen" mode

### ISSUE THREAD

**Issue by ydqsbfsyi** [libre-tube/LibreTube#1179]
### Describe your suggested feature

Currently, in "auto fullscreen" mode, there's no fullscreen toggle button, so when I switch to some other app then switch back (or I just click back button, but find no better video and decide to continue watch that video), the video I was watching is not in fullscreen mode any more (in Android phone, rotate the phone to portrait then to landscape will probably fail to get back fullscreen, either). To get back fullscreen, I have to close the video and find that video in history and resume playing.  

This may be complicated, maybe also related to auto rotation function. But I guess the easiest solution is to show fullscreen toggle button even if in "auto fullscreen" mode. Nobody will bother to look at it if auto fullscreen works, unless they need to get back fullscreen.

Please consider this in future version. Thanks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We can't unfortunately:
When you tap the fullscreen button manually, the app has to force itself into landscape mode although your phone isn't even in landscape mode. From that point, auto rotation won't work anymore because you forced the app to be in landscape.

If you need the fullscreen button you should consider turning off the settings completely.

Regards

**Comment by ydqsbfsyi** [comment]
> We can't unfortunately: When you tap the fullscreen button manually, the app has to force itself into landscape mode although your phone isn't even in landscape mode. From that point, auto rotation won't work anymore because you forced the app to be in landscape.
> 
> If you need the fullscreen button you should consider turning off the settings completely.
> 
> Regards

Thanks.
