### ISSUE TITLE
Just a question! Please delete after reply!

### ISSUE THREAD

**Issue by voxrie** [libre-tube/LibreTube#118]
Piped is used as base, which is really great. What I'm wondering is, will be local api support in future like a Newpipe or Freetube? Sorry if this has been asked before, I didn't see it!

**Comment by m77e4t** [comment]
Unlikely (not from dev team)

**Comment by FireMasterK** [comment]
What would this achieve? You should use NewPipe if that's what you're looking for. Piped uses NewPipeExtractor but proxies all content so you never connect to a Google server and gives you instantly generated feeds.

**Comment by voxrie** [comment]
thanks guys
