### ISSUE TITLE
Bottom sheet for sorting options

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#1183]
### Describe your suggested feature

Change the sorting menu to a bottom sheet.

### Other details

This is what the menu currently looks like:

![Screenshot_20220827-152432_LibreTube](https://user-images.githubusercontent.com/50382414/187032235-5ee7ac75-6c97-4fc2-9d07-7e8447d8cd90.png)

This is what a bottom sheet looks like in the app:
![Screenshot_20220827-152515_LibreTube](https://user-images.githubusercontent.com/50382414/187032253-6ca6d06e-77e3-4721-a873-ab6bda35cabe.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We would probably need proper icons for all the available sorting options then, any suggestions?
