### ISSUE TITLE
Bottom sheet for action menu

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#1184]
### Describe your suggested feature

Change the action menu to a bottom sheet.

### Other details

This is what the action menu looks like right now:

![Screenshot_20220827-152949_LibreTube](https://user-images.githubusercontent.com/50382414/187032401-ddeb4777-6560-49a3-9d17-0a99af2a7fe7.png)

This is what a bottom sheet looks like in the app:
![187032253-6ca6d06e-77e3-4721-a873-ab6bda35cabe](https://user-images.githubusercontent.com/50382414/187032404-319cf108-f89e-4554-8b54-9b3e538751fd.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
In my opinion, the normal dialog fits better here.
Would be glad to hear the opinion of others about that too :)

**Comment by xIUPITERx** [comment]
I'm not a 100% fan of the bottom sheet, but since almost all Material You apps from Google use this design language, it would fit in well.
In any case, the menu should be left-aligned and have small icons.
