### ISSUE TITLE
Search option for settings

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#1185]
### Describe your suggested feature

Make it possible to search the settings

### Other details

-

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
There's no official way to this in Android, adding this is a lot of work that's not worth it in my opinion.
