### ISSUE TITLE
[BUG] <import subscription greyed out>

### ISSUE THREAD

**Issue by Xellerate005** [libre-tube/LibreTube#119]
When I press the import subscription button, it goes into my internal storage, but the csv cannot be clicked

**To Reproduce**
1. Go to 'import subscriptions from youtube, go to directory containing subscriptions.csv'
2. Click on '.csv file'

**Smartphone (please complete the following information):**
 - Device: [samsung galaxy s8 snapdragon us varient]
 - Android version: [e.g. 10]

**Additional context**

**Comment by dh3lix** [comment]
Confirfmed here.

**Comment by lilcheti** [comment]
Please try the latest version and close the issue if it's solved.
