### ISSUE TITLE
Video dont Start to play

### ISSUE THREAD

**Issue by Kenji-1984** [libre-tube/LibreTube#1199]
### Steps to reproduce

On some Videos the Video Does Not Start.
It says 0:00 lenght.

An Video sample is :

https://youtu.be/LJX_WAo1YYk
![Screenshot_20220829-111928_LibreTube](https://user-images.githubusercontent.com/104366703/187168826-779c2ce0-a6ed-4251-955a-214a1f00df4b.jpg)

### Expected behavior

The Video should played

### Actual behavior

The Video Does Not start

### LibreTube version

0.5.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Joao-Ex-Machina** [comment]
> ### Steps to reproduce
> 
> On some Videos the Video Does Not Start.
> It says 0:00 lenght.
> 
> An Video sample is :
> 
> https://youtu.be/LJX_WAo1YYk
> ![Screenshot_20220829-111928_LibreTube](https://user-images.githubusercontent.com/104366703/187168826-779c2ce0-a6ed-4251-955a-214a1f00df4b.jpg)
> 
> 
> ### Expected behavior
> 
> The Video should played
> 
> ### Actual behavior
> 
> The Video Does Not start
> 
> ### LibreTube version
> 
> 0.5.0
> 
> ### Android version
> 
> Android 12
> 
> ### Other details
> 
> _No response_
> 
> ### Acknowledgements
> 
> - [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> - [X] I have written a short but informative title.
> - [X] I will fill out all of the requested information in this form.

I had the same issue, changing the instance(at least to garudalinux.org) seems to solve it.

**Comment by Kenji-1984** [comment]
> I had the same issue, changing the instance (at least to garudalinux.org) seems to solve it.

Changed the instance to garadalinux...  Now it works

**Comment by Bnyro** [comment]
Closing since it appears to be Piped instance related.
