### ISSUE TITLE
Background play or Only Audio + Queue option

### ISSUE THREAD

**Issue by fossimprove** [libre-tube/LibreTube#12]
This helps to play music and stuffs to just hear.

Also, I would prefer Audio to be opus or highest quality, since its just audio.

This project looks very promising and Im happy for it being developed.

Thank you and Definitely it will shine in near future

**Comment by rimthekid** [comment]
I just pushed a commit for playing sound in the background it should do the job.
The queue though needs some time since the player still needs a lot of work.

**Comment by rimthekid** [comment]
Audio is the highest quality for 480p and up

**Comment by rimthekid** [comment]
Should I close this issue?
