### ISSUE TITLE
No Content in Home

### ISSUE THREAD

**Issue by rahaaatul** [libre-tube/LibreTube#1202]
### Steps to reproduce

1. Open app.
2. Wait for content to load.

### Expected behavior

Should show trending contents.

### Actual behavior

Doesn't show any content, completely blank.

### LibreTube version

0.5.0

### Android version

Android 8.1.0

### Other details

Screen Resolution: 480×854
DPI: 240
GPU: Mali-400MP
OpenGL: 2.0
RAM: 1 GB

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
NewPipeExtractor issue

**Comment by rahaaatul** [comment]
> NewPipeExtractor issue

I don't get it, the issue isn't solved yet. Why did you close it as completed?

**Comment by Bnyro** [comment]
Because it's not the issue of the app, the NPE already has a PR that fixes it...

**Comment by rahaaatul** [comment]
> Because it's not the issue of the app, the NPE already has a PR that fixes it...

I apologize if I'm annoying you but what can I do about this issue?

**Comment by Bnyro** [comment]
Nothing, just be patient :)

**Comment by FireMasterK** [comment]
> I apologize if I'm annoying you but what can I do about this issue?

Wait for your instance to update.

**Comment by rahaaatul** [comment]
> 
> > I apologize if I'm annoying you but what can I do about this issue?
> 
> Wait for your instance to update. 

I was using your Instance I think, `kavin.rocks`. And in my phone there's no issue with it, it's with the other phone.
