### ISSUE TITLE
Mini player missing icons

### ISSUE THREAD

**Issue by rahaaatul** [libre-tube/LibreTube#1203]
### Steps to reproduce

1. Play a video
2. Minimize the video.

### Expected behavior

Should show icons.

### Actual behavior

Doesn't show icons, but boxes.
![Screenshot_20220831-104023_2](https://user-images.githubusercontent.com/86149861/187594753-48df0e22-880e-4b17-8d39-66de6418dbf5.png)

### LibreTube version

0.5.0

### Android version

Android 8.1.0

### Other details

Screen Resolution: 480×854
DPI: 240
GPU: Mali-400MP
OpenGL: 2.0
RAM: 1 GB

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Seems to be a device specific issue 🤔

I already tested the App with different Android versions from Android 5 to Android 13 and never experienced something similar.
