### ISSUE TITLE
Vertical videos

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#1209]
### Describe your suggested feature

Please add support for showing vertically filmed videos in full screen.

### Other details

Here is an example video that is vertical: https://www.youtube.com/watch?v=hhDq_OGOlpg

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You can achieve that by disabling auto-fullscreen in the audio and video settings and then changing the fullscreen orientation preference.

**Comment by Donkey-Doug** [comment]
Would it be possible to have an implementation in which both work? Like newpipe?
