### ISSUE TITLE
Fail to play live videos 

### ISSUE THREAD

**Issue by sushantbhagat02** [libre-tube/LibreTube#121]
Live videos can't be played says can not stream

**Comment by lilcheti** [comment]
Yes it's a back end issue

**Comment by FireMasterK** [comment]
What's wrong in the backend? It works fine in the web frontend

**Comment by IceDBorn** [comment]
It does work in the web.

**Comment by lilcheti** [comment]
Oh it didn't worked for me when I tested it on the web
