### ISSUE TITLE
Deleting a playlist.(It's a left drive.)

### ISSUE THREAD

**Issue by Fertanima** [libre-tube/LibreTube#1219]
### Describe your suggested feature

Deleting a playlist by swiping left.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't think it's a good idea, that could result in accidental playlist deletions which can't be restored!

**Comment by Fertanima** [comment]
Swiping to the left may display a warning that it will be deleted.
