### ISSUE TITLE
Search history is deleted (Swipe left).

### ISSUE THREAD

**Issue by Fertanima** [libre-tube/LibreTube#1220]
### Describe your suggested feature

Swiping to the left clears the search history.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not planned, the rows aren't really large enough for it to be really useful.
