### ISSUE TITLE
Force stop required to get rid of notification

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#1222]
### Steps to reproduce

1. Play any video in audio only mode
2. Whatever I do, notification of the audio player remains

### Expected behavior

When I switch back to video, press the stop button or remove the app from recents the notification should be gone.

### Actual behavior

Notification remains until force quitting the app.

### LibreTube version

0.5.0

### Android version

10

### Other details

This might be an android 10 thing, because I have the same issue with newpipe (for over 2 years)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
![Screenshot_20220907-084821_Settings.png](https://user-images.githubusercontent.com/82752168/188808461-ecead3bf-eafa-4638-bd0c-42af51dab471.png)

I was able to fix it on my device by turning off the "Pin media player" setting, someone told me that he resolved it by changing another notification setting inside the Android settings (forgot which one), but it's most likely depending on your Android settings and not LibreTube itself.
