### ISSUE TITLE
A completed video from watch history doesn't restart

### ISSUE THREAD

**Issue by XelXen** [libre-tube/LibreTube#1224]
### Steps to reproduce

1. Watch a complete video
2. Go to watch history
3. Tap on the completed video

### Expected behavior

If a video is completed and it is clicked from the watch history then it should have restarted

### Actual behavior

Once u tap on the completed video, it will take you to the end and won't restart the video

### LibreTube version

0.5.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That should be fixed with the coming update :)
In theory, it should have been working before too but it got ripped by the database migration unfortunately :/
