### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by KalpanaChetan** [libre-tube/LibreTube#1227]
### Steps to reproduce

How change video resolution 

No video size for download 

### Expected behavior

![Screenshot_20220908-093854_LibreTube](https://user-images.githubusercontent.com/112402936/189034691-b75c2fae-164a-497a-9c5e-60fe2a5d4dd6.jpg)

![Screenshot_20220908-094016_LibreTube](https://user-images.githubusercontent.com/112402936/189034725-eff9fb8a-f89d-4c30-af59-540d6a976ca6.jpg)

### Actual behavior

![Screenshot_2022-09-08_09-58-12](https://user-images.githubusercontent.com/112402936/189034847-4b049b60-fea8-4a44-ad34-03e7438f3b90.png)

![Screenshot_2022-09-08_09-58-32](https://user-images.githubusercontent.com/112402936/189034870-42e91715-74ab-4b28-82d5-220e260143c3.png)

### LibreTube version

0.5.0

### Android version

8

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [ ] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It works as exactly as you tried to, some videos just don't have multiple resolutions available, therefore it doesn't work for all videos.

**Comment by KalpanaChetan** [comment]
you did not understand.
Video link
https://www.youtube.com/watch?v=HhjHYkPQ8F0



I want the video to always play in resolution 144 p


New pipe app screnshot 

![Screenshot_20220908-104938_NewPipe](https://user-images.githubusercontent.com/112402936/189045040-70f80f9d-f053-4c54-bf7f-780f78ccd153.jpg)



![Screenshot_2022-09-08_11-24-21](https://user-images.githubusercontent.com/112402936/189045181-66b415ec-bdf5-49ae-afa3-adb82aeeca9d.png)
