### ISSUE TITLE
Shorts Implementation with Piped API

### ISSUE THREAD

**Issue by XelXen** [libre-tube/LibreTube#1228]
### Describe your suggested feature

Whenever a video is clicked, Height and Width can be compared and if the width is 30% smaller than the height and the duration of the video is less than 60 seconds then the video plays in the shorts mode

For Example: If the Height is 1000 and the width is 2000 or the duration is longer than 60 seconds then the video plays normally

but

If the height is 1000, the width is 700 and the duration is less than 60 seconds then the video plays in shorts mode

### Other details

We can do background checks for the duration of the videos available on the searched topic or home and only do width and height checks on the videos with less than 60 seconds duration for an efficient implementation.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Fertanima** [comment]
I think you should open this issue in Piped.

**Comment by xIUPITERx** [comment]
Are shorts not fully implemented now (except that the status bar is still shown)?

**Comment by Bnyro** [comment]
The feature request is about adding a dedicated tab for shorts (which I'm not a fan of without support by Piped/ the NewPipe Extractor for it). We could search #shorts in the background and follow related videos to get some sort of working algorithm but it's probably going to end up with lots of issues.

**Comment by xIUPITERx** [comment]
Didn't you write in #1345 that they are supported now?

**Comment by Bnyro** [comment]
Not as a tab for itself, we can only determine whether a video is a short but we can't get a list of shorts videos that could be used to create a dedicated tab for it.

**Comment by Bnyro** [comment]
No plans for that for now, we'll be awaiting API support for a shorts tab if there ever will be some, a dedicated shorts tab won't be working properly without unfortunately.
