### ISSUE TITLE
Please allow to subscribe without signing in to Piped

### ISSUE THREAD

**Issue by Raj2032** [libre-tube/LibreTube#1229]
### Describe your suggested feature

I have been using [NewPipe](https://newpipe.net/) and coming from NewPipe to LibreTube one disappointment is the fact that it does not allow you to subscribe offline / without signing into some kind of account, in this case piped.

Even on [piped](https://piped.kavin.rocks/watch?v=FT3ODSg1GFE)'s own website allows you to subscribe without signing in.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I added it to LibreTube as well as to Piped, it works the same way for both since version 0.4.2. Just make sure you are running the latest version (0.5.0), then there should be nothing that hinders you from subscribing without an account!

**Comment by Raj2032** [comment]
@Bnyro Hi mate.

According to my settings on the button it shows `V 0.5.0`

I am not signed in and I go to any video and I press the `Subscribe` button but it literally does nothing, it shows the animation of you pressing the button but it doesn't subscribe me to anything.

**Comment by Bnyro** [comment]
Yes, that was a bug, it'll be resolved in the next update :)

**Comment by Raj2032** [comment]
@Bnyro Cool thanks mate :)
