### ISSUE TITLE
Load the video player first

### ISSUE THREAD

**Issue by Fertanima** [libre-tube/LibreTube#1231]
### Describe your suggested feature

When you have clicked on a video in the feed or search list, make the video load before the comments and the channel widget.

### Other details

If you are in rather bad network conditions you can see that the channel info widget and comments load before the video player "visually initialises" and starts playing the video.
This could speed up the time between clicking on a video and the video being played.I think that the video id and other ids, if necessary, to load the video directly are loaded in the feed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
ExoPlayer loads the video asynchronously so we can't influence that behavior.
