### ISSUE TITLE
I want the video to always play in resolution 144 p

### ISSUE THREAD

**Issue by KalpanaChetan** [libre-tube/LibreTube#1232]
### Describe your suggested feature

I want the video to always play in resolution 144 p

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [ ] I will fill out all of the requested information in this form.

**Comment by KalpanaChetan** [comment]
> = Default resolution in settings

Default resolution 144p

**Comment by Fertanima** [comment]
> > = Parametrlərdə defolt ayırdetmə
> 
> Defolt qətnamə 144p

It doesn't make sense, because Auto video quality is available.

**Comment by KalpanaChetan** [comment]
Forgive me libre tube team 
i will never comment
i uploaded the screenshot    but no one paid attention

i am very simple user and even english is not my language i use google translate

so i uploaded the screenshot


you don't need to reply


Thanks you libre team
