### ISSUE TITLE
Control playback with volume buttons

### ISSUE THREAD

**Issue by Sgubela** [libre-tube/LibreTube#1240]
### Steps to reproduce

1. Start a playlist
2. Turn off the display
3. Try to seek with long pressing volume buttons

### Expected behavior

Long pressing up should seek next song, while volume down should seek to previouss.

### Actual behavior

Nothing happens.

### LibreTube version

0.5.1

### Android version

Android 11

### Other details

Control playback feature is enabled system wide. If there's no such feature in LibreTube at least it should behave as configured in system. This is the reason why I labeled this as bug and not feature request, although this feature would be great as well.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It requires additional work to make it work and doesn't work by default, therefore it's rather a feature request than a bug.
In my opinion long pressing volume buttons is also for changing the volume and not any other stuff, at least I use it like that.
There are no plans to add such a feature.
