### ISSUE TITLE
Android 4.4.4 compatibility

### ISSUE THREAD

**Issue by NightWolf2014** [libre-tube/LibreTube#125]
Could the Libretube had a version compatible with Android 4.4.4? I doesn't had any perfect alternatives after YouTube Vanced end, Newpipe doesn't had login and comment feature, and others apps like Puretuber and Gotube works with a lot of problems, making these apps horrible to use. Libretube minimum version requiriment is Android 5.0, why not add Android 4.4.4 too?

**Comment by lilcheti** [comment]
We are using retrofit for the api and it supports android version 5 and up.

**Comment by manilenio** [comment]
What about android 4.3?

**Comment by NightWolf2014** [comment]
If its possible to add Android 4.3 support, will be good.

Em Qua, 27 de abr de 2022 01:47, manilenio ***@***.***>
escreveu:
