### ISSUE TITLE
enable quic

### ISSUE THREAD

**Issue by eladkarako** [libre-tube/LibreTube#1256]
### Describe your suggested feature

might improve stuff.  

([#870](https://github.com/libre-tube/LibreTube/issues/870) [#456](https://github.com/libre-tube/LibreTube/issues/456) [#231](https://github.com/libre-tube/LibreTube/issues/231))

### Other details

- <a href="https://github.com/libre-tube/LibreTube/blob/7bfc1d18eb1db2b14a9dc710b9b4cbf977c0f5ee/app/src/main/java/com/github/libretube/api/CronetHelper.kt?q=brotli#L12-L18">relevant part</a>.

- `.enableHttp2(true).enableQuic(true);` <sup><a href="https://chromium.googlesource.com/chromium/src/+/master/components/cronet/README.md">1</a></sup>

- (optional) increase cache in RAM to 1mb.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thanks for the the suggestion!
I just had a quick look and it seems like Http2 and Quic are already enabled by default according to the docs.
I'll enable them just to be sure but it shouldn't make a difference.

**Comment by FireMasterK** [comment]
> I'm using burp for that,
which is an industry-grade tool most suitable for that purpose,

I'm pretty sure it doesn't support quic, so your test would be limited to http1.1 or http2 depending on what burp supports.

**Comment by FireMasterK** [comment]
Why are you directly connecting to YouTube? Only the Piped server is supposed to do that
