### ISSUE TITLE
[BUG] import broken in CI builds

### ISSUE THREAD

**Issue by FireMasterK** [libre-tube/LibreTube#126]
**Describe the bug**
Use latest CI build.

**To Reproduce**
1. Just import any zip

**Additional context**
This happens because the import retrofit method doesn't include an `override` query parameter. (Which can be true or false)

**Comment by lilcheti** [comment]
Should it be in the header? It used to work.

**Comment by FireMasterK** [comment]
Nope, it should be a query parameter: https://github.com/TeamPiped/Piped-Backend/blob/01023f388ed376421dd64bcd869ed05612f7d5c9/src/main/java/me/kavin/piped/ServerLauncher.java#L273

**Comment by lilcheti** [comment]
would you check the latest ci build?

**Comment by FireMasterK** [comment]
Just tried it, didn't help sadly, I'll take a look at this issue when I can

**Comment by lilcheti** [comment]
I've add the override query and set it to false why it's not working:(
