### ISSUE TITLE
Fat seekbar

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#1260]
### Describe your suggested feature

Make the seekbar fatter such that it is easier to seek.

### Other details

Example of current libretube implementation:

![Screenshot_20220910-171454_LibreTube](https://user-images.githubusercontent.com/50382414/189489825-f5f9495b-ca05-4fc1-b33d-79c2c72ef5cc.png)

Example of a fat seekbar:
![Screenshot_20220910-171546_Fritter](https://user-images.githubusercontent.com/50382414/189489833-09536d53-360f-40ca-9e7d-091fb727b627.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
![image](https://user-images.githubusercontent.com/82752168/189495499-6c997bba-66a7-4cb4-b8b2-aa4f1fb56d7d.png)

Increasing the size would lead to ugly edged corners, I couldn't find any way to make them round.

**Comment by Donkey-Doug** [comment]
@Bnyro Is this helpful info:

https://stackoverflow.com/questions/42646574/progress-bar-with-rounded-corners

**Comment by Bnyro** [comment]
It could, but since ExoPlayer uses a `DefaultTimeBar` instead of a `ProgressBar` it probably requires some addition work.
