### ISSUE TITLE
Unified backup settings

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#1261]
### Describe your suggested feature

Currently I can backup subscriptions (under instance settings) and backup libretube settings (under advanced).

Perhaps place all backup settings under advanced and ask the user what he wants to backup in a popup window. In this windows the user can mark checkboxes such as "subscriptions", "settings".

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
It would be cool, if you could add an option to also save the library.

**Comment by Bnyro** [comment]
Subscriptions are currently backed up in the format NewPipe uses for compatibility reasons, therefore I don't want to mix it up with our own format.
Preferences are currently saved as XML while anything else is JSON, therefore we'll need to find a workaround to be able to backup both in the same file.
What I did so far is adding the possibility to backup the watch history, positions, search history, custom instances and local subscriptions.
