### ISSUE TITLE
Some videos not showing in subscription feed

### ISSUE THREAD

**Issue by SeragMurry** [libre-tube/LibreTube#1265]
### Steps to reproduce

Open subscription feed in libretube and newpipe to compare. Newpipe has every video, libretube doesn't.

### Expected behavior

All videos from subscribed channels should be visible in subscription feed.

### Actual behavior

Some videos don't show up in subscription feed

### LibreTube version

0.5.1

### Android version

Android 12

### Other details

![IMG_20220911_104756](https://user-images.githubusercontent.com/113281131/189517454-bf5de8a5-4a90-4f8c-8fe3-dff3846e969a.jpg)
New pipe 
![Screenshot_2022-09-11-10-47-39-677_com github libretube](https://user-images.githubusercontent.com/113281131/189517460-aec5359a-aab8-4cac-bfeb-0ada1f998648.jpg)
Libretube

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Piped issue, see [TeamPiped/Piped#1130](https://github.com/TeamPiped/Piped/issues/1130)

**Comment by SeragMurry** [comment]
Is there anyway to fix this on Libretube. Lt is honestly perfect for me and I would choose it over newpipe in a heartbeat if there was a way to fix this issue.
