### ISSUE TITLE
Import subscriptions from youtube or newpipe button doesn't work

### ISSUE THREAD

**Issue by Universal-Igloo** [libre-tube/LibreTube#1266]
### Steps to reproduce

1. Login with a piped account.
2. Click settings on libretube -> Instance -> "Import subscriptions from youtube or newpipe" button

### Expected behavior

When I click on the "Import subscriptions from youtube or newpipe" button, it should do something.

### Actual behavior

When I click on the "Import subscriptions from youtube or newpipe" button, it does nothing.

Note that all the other buttons work, including export subscriptions, restore backup etc. Only this import subscriptions button is completely unresponsive.

### LibreTube version

0.5.1

### Android version

Android 13 (GrapheneOS)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Hmm, weird, it works fine for me with the latest version, are you logged in?

**Comment by Universal-Igloo** [comment]
I am logged in AND "Restore Preferences" in settings is responsive, it open the file manager immediately.

The only button not responsive is "Import Subscriptions".

I have tried restarting the app, force stopping and starting etc. Doesn't work.

**Comment by Universal-Igloo** [comment]
Also note - I am able to manually subscribe to channels within LibreTube, but the import button still doesn't work (rechecked after doing a subscribe)

**Comment by rozari0** [comment]
Just import in your piped instance.

**Comment by Bnyro** [comment]
Could you please retry it with the [latest CI build](https://github.com/libre-tube/LibreTube/actions/runs/3031313126)?

**Comment by catdevnull** [comment]
I had the same issue and it is fixed in the latest CI build.
