### ISSUE TITLE
Feature request: Subscription/Channel Groups

### ISSUE THREAD

**Issue by Universal-Igloo** [libre-tube/LibreTube#1267]
### Describe your suggested feature

Newpipe has this excellent feature, under subscriptions you can group channels together for e.g.
1. Tech reviews: MKBHD, Dave2d, MrMobile etc.
2. News: The guardian, The Atlantic etc.

Basically you can create groups of channels as you want, and then when you click on that group, you can view updates from only the channels in that group, so you can see all your news together without other stuff to filter through.

You could also look at this as enabling filters for specific channels.

See below attached screenshot of the UI on Newpipe.

### Other details

![IMG_20220911_161849](https://user-images.githubusercontent.com/95539123/189523498-4c380aee-6422-497b-8cc4-a5917774edff.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
In my eyes, this doesn't make sense without API support for it. Everything would be gone each time you log out. Apart from that I don't really have an idea about how to implement it UI effective.
It can be reconsidered if the Piped API will ever support it, but at least it's not planned for now!
