### ISSUE TITLE
new navigation bar

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#1273]
### Describe your suggested feature

Gmail and soon the other Google material you apps have got a new navigation bar that is thinner than the old one.

![Screenshot_20220912-001931_Gmail](https://user-images.githubusercontent.com/97352673/189551384-1d79d4ad-61af-4aec-82fa-b00aef614ea1.jpg)

Please add this option.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I like the current one more, no plans to change that.

**Comment by xIUPITERx** [comment]
I also don't want to have just the new navigation bar, but you could add an option to the navbar label visibility to minimise it.
