### ISSUE TITLE
hide navigation bar

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#1274]
### Describe your suggested feature

if the keyboard is opened for a search, the navigation bar should be hidden to see more search results. 

![Screenshot_20220912-002724_LibreTube](https://user-images.githubusercontent.com/97352673/189551560-6d7f82f7-c6e3-490d-aa7d-93e442e40dd3.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
Also it would be good, to hide the navbar if you scroll down in your feed.

**Comment by Bnyro** [comment]
That's a really weird behavior that the navigation bar moves when the keyboard is open, it shouldn't in theory.
Just tested with my phone and the emulator and none of them seem to have the issue.

![image](https://user-images.githubusercontent.com/82752168/189658510-66b666fe-85a3-4559-aacc-60277f0be3a9.png)

**Comment by xIUPITERx** [comment]
Even if you close and reopen the keyboard the navbar stays hidden ?

**Comment by xIUPITERx** [comment]
What das CI stand for?

**Comment by Bnyro** [comment]
continuous integration, you can find the build [here](https://github.com/libre-tube/LibreTube/actions/runs/3037516881)

**Comment by xIUPITERx** [comment]
It works now as it should.

**Comment by xIUPITERx** [comment]
Why did you change the design of the on off toggle in the settings?

**Comment by Bnyro** [comment]
Because it's the same now as for preferences in the Android settings on Android 12 and up, it's the official replacement of the old Switches, see https://m3.material.io/components/switch/overview.

**Comment by xIUPITERx** [comment]
That explains it.
Too bad that samsung never sticks to the standard deign.
