### ISSUE TITLE
"newest/oldest/most popular" switch for search result list

### ISSUE THREAD

**Issue by ydqsbfsyi** [libre-tube/LibreTube#1276]
### Describe your suggested feature

Please consider adding a "newest/oldest/most popular" sorting switch for search result list. I don't know if there is such thing like most popular  for search result, but newest is surely needed in most cases. Currently search result looks like in random order.

Thanks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not possible yet due to missing support for it in the NewPipeExtractor (which is used by the Piped API), otherwise I'd already have added support for it.
However, I'll most likely add an implementation as soon as the API supports it natively.

**Comment by ydqsbfsyi** [comment]
> That's not possible yet due to missing support for it in the NewPipeExtractor (which is used by the Piped API), otherwise I'd already have added support for it. However, I'll most likely add an implementation as soon as the API supports it natively.

Roger that. Thanks.
