### ISSUE TITLE
move resolution and speed outside of menu like in old version?

### ISSUE THREAD

**Issue by ydqsbfsyi** [libre-tube/LibreTube#1277]
### Describe your suggested feature

Please consider moving 'resolution' and 'speed' option outside of that triangle menu and show them directly in upper right corner, like in old versions.  I find it more convenient that way  since I need to change these options so so often. Honestly, I roll back to an old version for this.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Donkey-Doug** [comment]
Maybe optionally let users give "quick access" to certain video settings? I would like to set playback speed for example.

**Comment by xIUPITERx** [comment]
I would like to have a little HD icon, to see if the video is streaming in HD or full HD and to make it possible to change the resolution with one or to clicks.

**Comment by Bnyro** [comment]
I'm not really in favor of changing it back since the previous way of doing it took a lot of space, in my opinion the current way has more advantages. I might consider adding an option for it in the future but it's nothing of high priority.

**Comment by ydqsbfsyi** [comment]
> I'm not really in favor of changing it back since the previous way of doing it took a lot of space, in my opinion the current way has more advantages. I might consider adding an option for it in the future but it's nothing of high priority.

Thanks.

**Comment by Bnyro** [comment]
As we got the playing queue on the top right of the player now, we should probably limit it to adding only the resolution there optionally, or any other ideas?

**Comment by Bnyro** [comment]
Closing as not planned now as the space on the top right is used differentlt since the recent update.
