### ISSUE TITLE
Fully Black Theme

### ISSUE THREAD

**Issue by Archeix7** [libre-tube/LibreTube#1279]
### Describe your suggested feature

Make all bars and interface absolutely black

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The current one is black enough for me, no plans to make it "more" black. Making the bottom bar black to doesn't look good at all since it's impossible to differ the navbar from the current fragment.

**Comment by Archeix7** [comment]
![Screenshot_20220912-150605487](https://user-images.githubusercontent.com/51048550/189649138-f2c6d45a-b4bb-4d42-ba31-4cfc62535660.jpg)


It looks even better to me

**Comment by Archeix7** [comment]
U combine couple stuff in 1 container, аnd I can't paint it for myself correctly
