### ISSUE TITLE
Indefinite loading

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#1288]
### Steps to reproduce

1. Open libretube
2. App loads indefinitely.

### Expected behavior

Load content.

### Actual behavior

Indefinite loading.

### LibreTube version

0.5.1

### Android version

12

### Other details

https://user-images.githubusercontent.com/50382414/189768039-8a8cbad4-617c-4785-abb8-c08a01e56e72.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
I have the same error on multiple devices in the normal and debug version.

**Comment by Bnyro** [comment]
I experienced the same thing sometimes, it usually happens when instances go temporary offline (they are not even part of the instances list anymore then) or your authentication token is expired. Usually it should show a toast that reports an error but it got removed due to the feed background loading feature.

**Comment by xIUPITERx** [comment]
That could be, but I can't change the piped instance. It always disconnects from other instances.

**Comment by GabrieleFranca** [comment]
Same problem here

**Comment by Donkey-Doug** [comment]
Can confirm switching instance fixes the issue. The official instance no longer works for me.

Quality of life upgrade suggestion:
Maybe if libretube does not load content quickly, show a message "It seems loading is slow. Would you like to change piped instance?" or something.

**Comment by hamidreza01** [comment]
I have exactly this problem ( Android 12 )

**Comment by Bnyro** [comment]
Update: The official instace (piped.kavin.rocks) and piped-instances.kavin.rocks seem to be down.

piped-instances.kavin.rocks is used to fetch the available instances in the settings, therefore only the hardcoded ones are available which are partly outdated.

For now, the mha.fi seems to be working fine to me, others might work as well!

**Comment by Bnyro** [comment]
I will readd the toast and try to make the instances list more independent.
For now you can either try other instances of the hardcoded ones (no guarantees they're not outdated!) or add a custom one.
