### ISSUE TITLE
for some videos, can not play any resolution except "auto"

### ISSUE THREAD

**Issue by ydqsbfsyi** [libre-tube/LibreTube#1289]
### Steps to reproduce

I've noticed this problem for a long time, at least for some old debug version and a new debug version in recent 5 days, as well as version 0.5.1.
The problem is: for quite some videos, only "auto" plays well, but since the quality is not good (say it shows "auto 240p"), I try to switch to other resolution, say it shows "auto, 1080p, 720p, 480p", there's no 240p at all, and with any resolution (except auto) I see  several seconds' circling wait, then it stops with a black screen with a triangle play button in center (for some version, like 0.5.1, app will quit instead of keeping in video black screen.

### Expected behavior

null

### Actual behavior

null

### LibreTube version

0.5.1

### Android version

Android 10, as well as Android 9 TV

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
There were probably some recent YouTube internal changes that have been changing how and where videos are stored. I'm pretty sure it's not LibreTube-related only since there were no changes to it in the last versions.
Are there any debug logs you can provide?

**Comment by NSTAdventure** [comment]
> There were probably some recent YouTube internal changes that have been changing how and where videos are stored. I'm pretty sure it's not LibreTube-related only since there were no changes to it in the last versions. Are there any debug logs you can provide?

I can confirm this are true app will instantly exit i also on current latest version 0.5.1 i used 360 for reso setting

**Comment by pawa2401** [comment]
A version back (In 0.5.0) I only had the "auto" option in the quality settings. But I found out that Settings > Audio and video > Video format for player was not set by default. I changed it to WEBM and it worked for me. While it's not exactly the problem that you are facing, changing that setting might help.

**Comment by ydqsbfsyi** [comment]
I'm late..... so sorry.

**Comment by ydqsbfsyi** [comment]
> There were probably some recent YouTube internal changes that have been changing how and where videos are stored. I'm pretty sure it's not LibreTube-related only since there were no changes to it in the last versions. Are there any debug logs you can provide?

Sorry I'm late. Don't know how to find debug logs, I'll try.

**Comment by ydqsbfsyi** [comment]
> A version back (In 0.5.0) I only had the "auto" option in the quality settings. But I found out that Settings > Audio and video > Video format for player was not set by default. I changed it to WEBM and it worked for me. While it's not exactly the problem that you are facing, changing that setting might help.

Thanks. I always use "WEBM"......since day 1.

**Comment by Bnyro** [comment]
Such errors get caught with v0.6.0, if a source doesn't work then due to an issue in the NewPipeExtractor that fetches the available stream sources at server side on Piped.
