### ISSUE TITLE
[FEATURE] Add Odysee/Rumble/Bitchute/LBRY support

### ISSUE THREAD

**Issue by therealbluepandabear** [libre-tube/LibreTube#129]
**Describe the feature you'd like to see added**
NewPipe doesn't have support for alt-tech platforms such as Odysee, Rumble, or BitChute (also LBRY). This is because they find the content 'offensive' and 'harmful'. My argument would be that adding support for the platform should have NOTHING to do with the content it allows to host.

Make LibreTube stand out and add support for these alternative platforms. Let's broaden our scope instead of solely focusing on one platform.

YouTube censors speech it finds 'harmful' (basically content that goes against the mainsream agenda on certain topics), and other similar apps aren't offering alternative platforms, I believe you can, and I believe this project has powerful potential if you can support these platforms. 

Right now I like LibreTube but I believe it can be more, since you are only supporting a censored platform. Rise above the alternatives, because they have all disappointed me as well as many other people.

**This app has a powerful potential to become better than the alternatives, and I believe the LibreTube developer team can unlock it.**

**Additional context**
N/A

**Comment by therealbluepandabear** [comment]
To whoever 'disliked' this, if you hate this idea then feel free to use NewPipe, I heard their owners hate free speech platforms there, you'd have a lot in common with them. 😂

To whoever thinks this is a bad idea, not to sound egotistic, but the owners are with me, this will eventually get added. 

Cry me a river.

**Comment by martin-desktops** [comment]
I  am not confident that Odysee, Rumble, Bitchute are in any means more reliable solutions than YouTube for me. They look and work like YouTube before its prime time. 

it's a little bit better with LBRY, but I am especially interested in PeerTube integration, due to not being just a temporary YouTube copy with mild rules, but an actual alternative to that system.

**Comment by FireMasterK** [comment]
> but I am especially interested in PeerTube integration

If you're aware of a way to find YouTube videos in LBRY automatically, let me know.

The API already has support for LBRY/Odysee streams.

**Comment by martin-desktops** [comment]
I don't think I have needed skills to study PeerTube syncing feature (I am supposing you meant PeerTube, not LBRY), but keep in mind that PeerTube highly relies on.peer-to-peer traffic. Massive download-only usage would be harmful for the PeerTube instances, so potential integration with PeerTube would require wider implementation of the protocol.

**Comment by therealbluepandabear** [comment]
> I am not confident that Odysee, Rumble, Bitchute are in any means more reliable solutions than YouTube for me. They look and work like YouTube before its prime time.
> 
> it's a little bit better with LBRY, but I am especially interested in PeerTube integration, due to not being just a temporary YouTube copy with mild rules, but an actual alternative to that system.

Sounds good to me, adding support for anything other than big-tech owned YouTube is great.

**Comment by BobIsMyManager** [comment]
> I don't think I have needed skills to study PeerTube syncing feature (I am supposing you meant PeerTube, not LBRY), but keep in mind that PeerTube highly relies on.peer-to-peer traffic. Massive download-only usage would be harmful for the PeerTube instances, so potential integration with PeerTube would require wider implementation of the protocol.

Peertube just uses webtorrent, and due to the sheer popularity of bittorrent, I would be surprused if there wasnt a bittorrent library that fitted libretube's needs. Plus, newpipe already has peertube support, but im not sure if it just teaches or actually seeds aswell.

**Comment by ericsomto** [comment]
@therealbluepandabear I'd love to get on board if you've started building

**Comment by therealbluepandabear** [comment]
> @therealbluepandabear I'd love to get on board if you've started building

Hey, unfortunately I've stopped with android dev as a whole.

**Comment by erkkimon** [comment]
+1 for diversification. It is very annoying to switch between those platforms. Some of them will live, some of them will die. But the sure thing is that YouTube will live with a few co-habitats because of YouTube's questionable guidelines and random strikes plus bans.
