### ISSUE TITLE
Add more info when loading pages

### ISSUE THREAD

**Issue by giorgosioak** [libre-tube/LibreTube#1290]
### Describe your suggested feature

Hello, loading home page or subs page is sometimes very slow. And even sometimes it won't load. Could you add more info when load so we have a way to know how long it would take or if it even won't load.

### Other details

Example page of subs stuck and not loading without any info on when and if it loads anything
![Screenshot_20220913-094631_LibreTube](https://user-images.githubusercontent.com/8626050/189831244-53654d91-5025-459e-b7cb-4470c32687ef.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's simply not possible, we use Retrofit for API calls and it doesn't provide any information about the current state. 
If a request fails, it will just show a toast message with the error, there's no way to estimate the "time left".
