### ISSUE TITLE
Preloading doesn't work

### ISSUE THREAD

**Issue by nateRiver111** [libre-tube/LibreTube#1291]
### Steps to reproduce

1. Open any video
2. Pause it
3. Wait for the video to buffer

### Expected behavior

The video should buffer the amount of seconds set in preloading and stop when it reach it.

### Actual behavior

The buffer never stop untill the end of video.

### LibreTube version

0.5.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The buffer is handled inside exoPlayer, it's either an exoPlayer bug or an issue with the stream source provided by the Piped API.
