### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by hapashtiepa** [libre-tube/LibreTube#1292]
### Steps to reproduce

I think it stopped work. can not load tothing, can not play nothing since last night. Can you repair it?

### Expected behavior

es describe, no loading, no plaing 

### Actual behavior

as described  th rtjdzjuk ztdj zjejzeejzt deť

### LibreTube version

0.5.1.

### Android version

12

### Other details

miui 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Try a different instance!
