### ISSUE TITLE
"The password you entered is already compromised."

### ISSUE THREAD

**Issue by doonoo** [libre-tube/LibreTube#1294]
### Steps to reproduce

1.) Open Libretube
2.) Click 3 dots
3.) Click settings
4.) Click instance
5.) Click Log in/Register
6.) Type a username and password of your liking
7.) Click the register button

### Expected behavior

It should create a piped account.

### Actual behavior

A dialog with "The password you've entered has been compromised."

![Screenshot_20220913-214146](https://user-images.githubusercontent.com/18385494/190040163-7f968490-29b0-4004-bf2f-7ce727afaef6.png)

### LibreTube version

0.5.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Your password is too insecure, use a different one.
