### ISSUE TITLE
SponsorBlock: skip segment manually.

### ISSUE THREAD

**Issue by NSTAdventure** [libre-tube/LibreTube#1297]
### Describe your suggested feature

Problem:
I don't want all segment on "any categories" skipped automatically sometime segment isn't accurate or have other reason

Solution:
Please consider add option to skip manually like vanced did 🙏

Alternative:
N/A

### Other details
Add option to toggle skip segment button for each type of segment ( pause intro etc²)

How things work?
everytime video timestamp reach the sponsor segment, Skip segment button will appear and if you click on it respective segment will skipped

Screenshot is provided below to make my explanation hopefully clear
![Screenshot_2022-09-15-23-13-57-56_1](https://user-images.githubusercontent.com/50813528/190455602-4bf3b04e-bf03-42bc-80a3-e6f311033a4c.jpg)

(Please see skip segment button and it's placement same like skip ads button)
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't know how it worked on Vanced since I don't use it, please provide more info/details for it being possible to consider!

**Comment by NSTAdventure** [comment]
> I don't know how it worked on Vanced since I don't use it, please provide more info/details for it being possible to consider!

Yes i did 🙏😊
