### ISSUE TITLE
Disable unnecessary element.

### ISSUE THREAD

**Issue by NSTAdventure** [libre-tube/LibreTube#1301]
### Describe your suggested feature

Problem:
As viewer i usually focus on the video not with that like / dislike / subscription / viewer count and such

Solution:
Allow user to disable following:
All counter
Interactive button
(like / dislike / subscription button)

What should remain or can't disabled:
Save, share, CC and download button

Mics:
Idea from newpipe 
Have same ability to disable those counter included comment meanwhile keep the share, and save video button exist or visible to user

### Other details
I will edit this issues again soon to make my explanation clear as possible

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't see any real reasons/use cases for that, sorry!

**Comment by NSTAdventure** [comment]
> I don't see any reasons/use cases for that, sorry!

Reason are:
1. Distraction free
You may want to watch yt without any distraction

2. And of course you also want to watch yt without being addicted to yt

Please consider re open or plan this idea
Thanks 🙏🥴

**Comment by NSTAdventure** [comment]
> I don't see any reasons/use cases for that, sorry!

Hi dev main thread or post has been update by adding reason please re consider to re open or plan this idea 
Thank you 🙏😊

@Bnyro

**Comment by flexxxxer** [comment]
Everyone is welcome to use [FlexTube](https://github.com/flexxxxer/FlexTube) where ability to hide counters (including like & dislike count) is available. FlexTube is LibreTube with few changes, so user experience pretty close.

Notice: Bnyro [allowed](https://github.com/libre-tube/LibreTube/discussions/8168#discussioncomment-16308171) to mention FlexTube in issues being addressed by FlexTube
