### ISSUE TITLE
Filename sanitization of '/' character when downloading videos

### ISSUE THREAD

**Issue by JP-Go** [libre-tube/LibreTube#1305]
### Steps to reproduce

1. Find video that has the `/` character on the name
2. Download the video

### Expected behavior

The downloaded video is one file with the name of the video.

Example: if the name of the video is  `the name / of the video`, it should be created a file like `the name / of the video.mp4`

### Actual behavior

Separates the name of the video in two parts, then it creates a directory named the first part and a file in the created directory named the second part.

Example: if the name of the video is  `the name / of the video`, it creates a directory called `the name` and a file inside it called, `of the video` with no extension.

### LibreTube version

0.5.1

### Android version

10

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FireMasterK** [comment]
We should also check for potential path traversal too 👀
