### ISSUE TITLE
back navigation button is inconsistent

### ISSUE THREAD

**Issue by lucamp** [libre-tube/LibreTube#1306]
### Steps to reproduce

1. From the main pages search for something (eg bbc)
2. Play one of the resulted videos
3. Touch back button on the Android navigation bar

![Screenshot_2022-09-17-08-26-31-43](https://user-images.githubusercontent.com/15078341/190844088-044eb44c-5719-4e21-a651-ad8d072b70b9.jpg)

![Screenshot_2022-09-17-08-28-04-03](https://user-images.githubusercontent.com/15078341/190844108-67fe11dd-6ca7-4a44-aa3a-e7bc66a74f87.jpg)

![Screenshot_2022-09-17-08-28-10-71](https://user-images.githubusercontent.com/15078341/190844117-bf73cce9-f73b-42d4-be33-451355db2efb.jpg)

### Expected behavior

Libretube will return to the list of searched results while video is played at the bottom

### Actual behavior

Libretube shows the search term history 

### LibreTube version

0.5.1

### Android version

10

## workaround
When the video is playing swipes it down to return to the searched videos 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
I think it could have something to do with #1155.

**Comment by xIUPITERx** [comment]
But you dont have to watch a video to experience this bug.
https://user-images.githubusercontent.com/97352673/190879024-4489d5da-21a7-43d1-8cc2-e270e1f1cee1.mp4
