### ISSUE TITLE
Downloaded video files are missing extensions and audio track

### ISSUE THREAD

**Issue by kha84** [libre-tube/LibreTube#1308]
### Steps to reproduce

1. Select any video to playback
2. Hit download button
3. Pick "Video", select any quality / format
4. After a while video will be downloaded to a configured folder but:
- the file will be missing extension, so you have to go to file manager and rename it to add .mp4 or .avi to it manually 
- video file will be missing audio track, no matter what format / quality have you choosen

### Expected behavior

The downloaded file should be having any video-like extension, so you could open it with any video player you have installed without any additional manual hassle in form of renaming it.

Videofile alone, with no audio track in it, doesn't make much sense to vast majority of users. So when user selects "video" as download option he expects it will download video + audio track in the single file

### Actual behavior

Explained above

### LibreTube version

0.5.1

### Android version

12

### Other details

Apart from this bug, the app is awesome. Thanks a lot for it

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not relevant anymore to a refactor of the download behavior, see #1243

**Comment by kha84** [comment]
Cool. So all these things should be fixed in the version next to 0.5.1?

**Comment by kha84** [comment]
Awesome. Thanks a lot - this would be more than enough. If you need any volunteers to test the early builds before making it public - I'll be happy to participate

**Comment by Bnyro** [comment]
Great, indeed testers are always needed!
I didn't have much time for testing it yet so feel free to report abnormal behavior in the latest CI builds, the latest one is [here](https://github.com/libre-tube/LibreTube/actions/runs/3062871582) :)

**Comment by kha84** [comment]
Roger that. Doing it now.

**Comment by kha84** [comment]
Alright. So here are my findings:

1. I downloaded number of videos using different quality settings. 
Most of them were later played back just perfectly fine, but I managed to find the one which was missing soundtrack. 
Give it a try yourself, video is called "Making a DWM Status Bar and Adding the Bing" from "OldTechBloke" channel. 
I downloaded it with using "480 MPEG_4" quality setting, then turned on "Plane mode" on phone, restarted LibreTube and tried to play that video back - it was missing soundtrack. 
Just in case, I checked that twice with the same results. 

2. In a landscape mode, the overlay panel in a player (the one, which is having items "Autoplay", "Repeat mode", "Resize mode" ...) isn't shown correctly. To me it looks like a regression bug: in the 0.5.1 version the panel is shown full-sized and you can click items from it straight away, but in the debug version only some small upper portion of the panel is shown and you have to tap-and-drag it, in order to reveal it entirely, so only then you can actually tap any action item from it. 

3. I noticed that some minor amount of texts are not yet translated to russian. I'm native speaker and if you want, I'll be glad to help you with that. Just point me to a right direction. 

4. Some dodgy behavior of a configuration menu item "Settings" -> "Player" -> "Fullscreen orientation". It's getting grayed out, if I toggle "Auto-fullscreen" to ON. But then, if I rotate the screen from portrait to landscape it becomes enabled again and I can click it. This behavior exists in both the debug version you shared and in the latest stable version 0.5.1. If I understand the idea correctly, it should stay disabled if user has turned on "Auto-fullscreen". 

5. Not a bug, but a small feature request: it would be extremely useful to remember user' last choice of video quality setting he used in the "Download" dialog. So the next time he presses "Download" button on a different video, the quality setting will be pre-filled with what setting he used before. Just for the sake of saving user from doing some extra taps while mass downloading bunch of videos before boarding into the plane in an airport :) 

Let me know if you need a screen recording for items 2 and 4 in this list, if it wasn't clear enough from my description of what was happening.

**Comment by Bnyro** [comment]
Thank you for the very detailed report, I'll definitely have a more detailed look into your issues to more, thanks for all your time spent in testing it <3

2. That's been an intended change but I'm still not sure which one is better: everything expanded by default or only one item visible.

3. Translations can be made via Weblate (which is just a web interface for translating apps), you can add the missing Russian translations [here](https://hosted.weblate.org/projects/libretube/#languages).

4. You're right, some options are not functional in the offline player yet, I will port them over from time to time but I can't guarantee all will be fully functional until the next release.

**Comment by kha84** [comment]
You're very welcome: your app is so amazing, thus it's an honor to help you even in such a small thing.

I love the way you organized i10n with Weblate. I filled few small gaps here and there as anonymous, before I realized I can tie my github account there, lol :) Sorry for that.

FYI: the Weblate is saying now "The translation is temporarily closed for contributions due to maintenance, please come back later" but as I said, I still managed to fill few gaps and correct one translation for the text, that was changed since it was translated last time.

Reg point 2. You're the boss to decide, but IMHO the old version (in 0.5.1) is better from UX perspective, because it saves user from doing some unneeded extra actions, like grabbing and dragging this panel to be shown entirely. Just have a look on how the debug version is rendered on my phone - even the first item of that is not being displayed:

https://user-images.githubusercontent.com/110789576/190873293-4c465319-e80b-459b-a5fa-9f557f9307f9.mp4

Reg point 4 this is what I meant. It's not about offline player, but more about some small glitch with a menu item being enabled after screen rotation (if only that's the intended behavior): 

https://user-images.githubusercontent.com/110789576/190873049-4ca5d4a0-0750-4461-951a-96458c9d22e9.mp4

One last thing for today - I tried to play with the setting "Legacy subscriptions view" on both debug version and on 0.5.1 but I don't see any difference when I turn it on and set some number of columns and turn that off. The subscriptions view looks the same to me.

**Comment by Bnyro** [comment]
2. The issue here was that the corners of the bottom sheet had edges and weren't round when expanding by default, probably a glitch in the Material design library. I decided to leave it as in the latest debug version for now due to the given reason.

4. Misunderstood you before, sorry, got it now :) You're right, that shouldn't happen, I'll try to fix it.

5. I agree, that's a good point, the problem is that every video has different qualities available so the implementation is a bit difficult. I'll keep that in mind but first need to find the best way to handle it before.

Last but not least: a demo of the legacy subscriptions view :)
![image](https://user-images.githubusercontent.com/82752168/190914539-ae4db985-e9e5-4e59-b017-77a2664329c9.png)

**Comment by kha84** [comment]
Gotcha, thx. I think I found another bug, which didn't exist in 0.5.1 but appeared in the very last sebug version (I took the most recent version from CI builds today).
When you subscribe to some channel, it doesn't get reflected on the "Subscriptions" page among your subscriptions immediately. In 0.5.1 it was doing that

**Comment by Bnyro** [comment]
Yep, that has been caused by #1156.
I didn't want to implement it at first but I decided to since many people had issues with long loading times of the feed.
It's probably best to add an option for it to avoid confusion.

**Comment by kha84** [comment]
I think it is kind of bearable, if the most recent videos from the recently subscribed channel won't be shown (until user force refreshes that page). 

But that new channel is even not shown in the list of channels one is subscribed, and this is confusing. Some users might think the subscribe button isn't working properly.

But I see you got the point. Probably some bit more smarter way to refresh that page will do the job - i.e. not just refresh everything, but get recent videos from a new channel and merge that list into what is alredy shown on the page

**Comment by Bnyro** [comment]
Agree, added an option for it that is disabled by default so that users having loading problems can manually enable the preference.
