### ISSUE TITLE
[BUG] The app crashes on android 7.1.2

### ISSUE THREAD

**Issue by alan-ford** [libre-tube/LibreTube#131]
**Describe the bug**

    The app crashes on android 7.1.2

**To Reproduce**

    Open the app
    The app immediately crashes

**Tablet (please complete the following information):**

    Device: Amazon Fire 7
    Android version: 7.1.2

**Additional context**

    Rooted device

**Comment by lilcheti** [comment]
on v0.2.4 right?

**Comment by Bubser** [comment]
Same here on my galaxy grand prime with android 5.1.1

**Comment by alan-ford** [comment]
@lilcheti Yes.

**Comment by lilcheti** [comment]
This has been fixed rn wait for the next release.

**Comment by ildar** [comment]
0.3.1 still crashes while the LibreTubeAlpha does not
