### ISSUE TITLE
The search autofill reappears when search results are clicked.

### ISSUE THREAD

**Issue by pawa2401** [libre-tube/LibreTube#1312]
### Steps to reproduce

1. Search any video
2. Click on one of the results that showed up
3. If you click a video, the player will show up, and if you back out of the player you will see the autofill/recent search prompt.
or
If it is a channel or a playlist, the autofill/recent search prompt overlays the playlist, and you have to back out of it to see the channel or the playlist.

### Expected behavior

-

### Actual behavior

-

### LibreTube version

0.5.1

### Android version

Android 12

### Other details

I don't think this bug was present in 0.5.0
Also, this is probably the same bug as mentioned in #1306, but it's not just in videos, and It's not the problem with the back button.
So please forgive me for creating a related issue, but I wanted to make sure that the bug was described with more accuracy.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Yep, I experienced that too, I might have an idea what it could be caused by but it'll need further investigation :)
