### ISSUE TITLE
Home page doesn't load,  not responding after loading a video

### ISSUE THREAD

**Issue by lowkey186** [libre-tube/LibreTube#1315]
### Steps to reproduce

1. Open the APP does not load home page
2.  Search a video  loading it  
3.  Not responding
4. screen record
https://user-images.githubusercontent.com/16371502/190890938-885231da-8b5c-4b7e-8db9-dc08187254c7.mp4

### Expected behavior

Loading properly

### Actual behavior

Does not load and responding

### LibreTube version

0.5.1

### Android version

android12, [MIUI13]

### Other details

Access from China, no vpn,  Everything works fine  When I was in 0.4.1,  But it doesn't work anymore  When I reinstall the old version 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That seems to be an instance issue, try to change it in the settings (and consider changing your region in the settings too!) :)
