### ISSUE TITLE
Support for submitting sponsor segments

### ISSUE THREAD

**Issue by ghost** [libre-tube/LibreTube#132]
**Describe the feature you'd like to see added**
I would like there to be a way to submit sponsorblock segments through the app, so we can contribute to the segment database
**Additional context**
#18 is obviously a prerequisite to this. I also think this would make more sense to be inside this app rather than through the piped web client, as you would have to either trust the instance hoster to not do anything malicious with your private key or snatch it from localstorage. If kavin wants to have submitting sponsor segments directly into piped though, we can move this issue over there instead.

**Comment by lilcheti** [comment]
Let's see what @FireMasterK has to say

**Comment by SameenAhnaf** [comment]
Note that there should be an option to turn down the player update bar as low as 10 ms. As expected, even a small difference in submission can make a huge difference.

**Comment by Bnyro** [comment]
We currently don't have any plans to implement support for submitting sponsor segements.

**Comment by Bnyro** [comment]
I thought about adding support for this recently - however we should add support for that at the Piped backend first.

**Comment by Bnyro** [comment]
We always need to provide a UUID when submitting a segment that would be client side, however I still prefer if the UUID can't be directly connected to any IP address of the user.
SponsorBlock is Foss as well, yes, but it's not as decentralized as Piped and users can't really choose between different instances according to trust in its maintainers/owners.

**Comment by FireMasterK** [comment]
> I thought about adding support for this recently - however we should add support for that at the Piped backend first.

I don't think we should do that. The UUID is quite valuable, as that is supposed to be a user's secret, and instances may be able to capture and log them.

I think ideally, LibreTube should connect to SponsorBlock directly to avoid the cases of a malicious Piped instance.

**Comment by tiwna16** [comment]
One of the most awaited feature from my side.Libre Tube is simple and cool.But It doesn't have this feature which is very helpful now a days.It will not only helpful for us but also for others.
