### ISSUE TITLE
App Crashes When Trying to Play Age Restricted Content

### ISSUE THREAD

**Issue by akano12** [libre-tube/LibreTube#1336]
### Steps to reproduce

How to reproduce:
1- Open the app.
2- Search for something that's age restricted.
3- Play the video and the app would crash.

### Expected behavior

I don't know honestly, usually on youtube you're supposed to login with your google account to watch age restricted video. So i don't know how is libretube supposed to handle this request.

### Actual behavior

app crashes

### LibreTube version

0.5.1

### Android version

Android 12

### Other details

https://user-images.githubusercontent.com/50032603/191429225-d92ae948-0c3e-437b-9277-2754d3c838d8.mp4

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The video you used works fine for me, are there any logs?

**Comment by Archeix7** [comment]
This video simply does not open (the last stable version)

![Screenshot_20220921-104546493_1](https://user-images.githubusercontent.com/51048550/191446943-53b8c7a1-e3cf-4cfe-b16f-4e73bf2f004b.jpg)

**Comment by akano12** [comment]
> The video you used works fine for me, are there any logs?

Nvm found out what was the issue. I'm using XprivacyLUA and because of blocking dns (using DNS Firewall restriction) the app was crashing. You can close the issue 

![20220923_030246.jpg](https://user-images.githubusercontent.com/50032603/191871392-0928e595-5d0c-458f-9cfb-94195b65fbfb.jpg)
