### ISSUE TITLE
add one resolution choice: "auto but no larger than 1080p" 

### ISSUE THREAD

**Issue by ydqsbfsyi** [libre-tube/LibreTube#1337]
### Describe your suggested feature

Considering all experiences I had, regarding resolution and poor internet connection, I'm thinking about this:

Current resolution system: 
if I choose say 720p, if this video does not have 720p, it will play 480p; if it has 720p, it will stick to 720p. ( Problem is, if connection begins to get poor, playback will get stuck often, that's why Auto is a better choice.)
if I choose Auto, if connection is poor it will use say 360p, if connection is great it will use 2160p. ( Problem is, when it uses 2160p, it sometimes (once or twice for a video) breaks/stops to a black screen, and I have to click play button to continue, I don't know why it does not drop down to 1440p or 1080p instead. And for me I find 1080p is always fluent, when in good connection time of day.)  

How about:
add one setting: good enough resolution, say 1080p;
add one choice in resolution drop down menu: auto but no larger than good enough ?

Thus, not matter connection is poor or good, it will be fluent.  For people who has an excellent connection and 2160p is always easy, "good enough resolution" set to 2160p and nothing will go wrong.

Please consider it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Note to self: https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/trackselection/TrackSelectionParameters.html#maxVideoHeight could be helpful for implementation

**Comment by Bnyro** [comment]
Don't have time today, maybe will look into it in the next days, no promises

**Comment by ydqsbfsyi** [comment]
Great!

**Comment by ydqsbfsyi** [comment]
@Bnyro   "Limit HLS to 1080p"...... works like a charm! Thank you so much.
