### ISSUE TITLE
Wrong Timestamp for shorts

### ISSUE THREAD

**Issue by EdwardLangdon** [libre-tube/LibreTube#1338]
### Steps to reproduce

1. Subscribe to a channel with Shorts
2. See the timestamp in Feed
3. See the timestamp for the same by going to that channel.

### Expected behavior

It should show the timestamp of whole video

### Actual behavior

It shows `00:00` as Timestamp in video thumbnail of shorts in channel.

### LibreTube version

0.5.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I thought it was a NewPipeExtractor issue, could you please try the same thing with Piped or NewPipe?

**Comment by EdwardLangdon** [comment]
You mean in Piped Web ?

**Comment by Bnyro** [comment]
Yep

**Comment by EdwardLangdon** [comment]
In Piped Web, You can see Timestamp in feed or in Search results. But inside the channel, It's tagged as `live' (Instead of shorts, A Known bug).

**Comment by Bnyro** [comment]
So in Piped, it's tagged as live while we don't tag it in any way.
Since the wrong duration is a NPE issue only thing we can do is just show nothing. Having a duration of 0 is usually indicating it's a live stream and not a YT short.

**Comment by Bnyro** [comment]
Closing, API issue
