### ISSUE TITLE
[BUG] - Crashes When try to Import Subscriptions from Exported youtube file

### ISSUE THREAD

**Issue by andercard0** [libre-tube/LibreTube#134]
**Describe the bug**
- Crash when import subscriptions from youtube (whether.csv or .json)
- App theme returning to default (white)

Crash **To Reproduce** 
1. Go to gear option (left slide)
2. Click on 'Import subscriptions from youtube'
3. Choose the file
4. See error! (libretube has stopped)

Theme Change not apply **To Reproduce** 
1. Go to gear option (left slide)
2. Click on app theme
3. Choose dark theme
4. keep using the app
5. Switch or close the app 
6. return to the app, boom, it loads back as white again

Note: could only reproduce this behaviour on my mother's phone which model is a Samsung J5, on my older J7 Prime this does not happen if that info matters.

**Smartphone (please complete the following information):**
 - Device: [Samsung J7 Prime and J5 (for the second issue(Theme) ]
- J5 Android version: [8.0.0]
- J7 Prime Android version: [8.1.0]

**Additional context**
Nothing relevant. 

Thanks for the support

**Comment by lilcheti** [comment]
@FireMasterK tried to fix it in this pr #133 it needs more investigation tho

**Comment by andercard0** [comment]
> @FireMasterK tried to fix it in this pr #133 it needs more investigation tho

Oh, my apologies for the duplicated topic just did test here with the following artifact from this mentioed PR: app-armeabi-v7a-debug and it work correctly now! Thank you!

**Comment by lilcheti** [comment]
Please try the latest version and close the issue if it's solved.
