### ISSUE TITLE
[crash] at ExoPlaybackException

### ISSUE THREAD

**Issue by ildar** [libre-tube/LibreTube#1348]
### Steps to reproduce

open some videos like
https://youtu.be/kVIAlGf_UlA

### Expected behavior

play

### Actual behavior

crash

### LibreTube version

0.5.1

### Android version

Android 12 GSI Phh LA

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ildar** [comment]
[adb.logcat.log.txt](https://github.com/libre-tube/LibreTube/files/9628789/adb.logcat.log.txt)

**Comment by Bnyro** [comment]
Looks like the stream source has some server side issues, I'll work on catching these crashes and notify about it

**Comment by ildar** [comment]
just tested.
LT still crashes though by different reason:
> 09-24 01:48:14.893   359   359 I lowmemorykiller: Kill
'com.github.libretube.debug' (27693), uid 10437, oom_score_adj 955 to free
182464kB rss, 17640kB swap; reason: low watermark is breached and swap is
low (0kB < 427832kB)
Can you please check?

**Comment by ildar** [comment]
[adb.logcat.log](https://github.com/libre-tube/LibreTube/files/9636848/adb.logcat.log)

**Comment by ildar** [comment]
plz reopen
