### ISSUE TITLE
Regarding resolution selection during mobile data communication and wi-fi communication

### ISSUE THREAD

**Issue by sabatachi** [libre-tube/LibreTube#1349]
### Describe your suggested feature

Since the resolution is lowered during mobile data communication, the resolution is set to automatic, but it is almost the same as during wi-fi communication.Therefore, I would like you to be able to set the maximum resolution for mobile data communication and the maximum resolution for wi-fi communication separately.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Already added options, just wait until the next update ;)
