### ISSUE TITLE
WSA Support

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#1350]
### Describe your suggested feature

First of all, I want to say that this app runs well in the Windows Subsystem for Android. However, a few additional features might be useful.
1. better mouse support: until now, to pause the video, you have to click on the video and then press pause. It would be nice if the controls were already visible when you hover the mouse over them.
2. pause and restart with the space bar.
3. dynamic number of grid columns: if the window is maximised, for example, a number of 5 would be nice, and if the width is halved, it should only be 3.
4. depending on the width of the window, the other videos should be displayed next to the current video and comments should be folded out.
A few of the points would also be worthwhile for large tablet screens.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
I also have problems with a bad audio quality and sometimes audio and video lose sync.

**Comment by Bnyro** [comment]
The app is meant to work on Android mobile devices only, support for anything else is **NOT** planned nor the goal of the project. Even if there was support for different systems, WIndows would absolutely be the last one to consider.

Therefore you should use Piped the official way through the web browser on anything that is not Android (or Yattee for iOS)

**Comment by xIUPITERx** [comment]
Some of this features could also be used on android tablets and you can use your keyboard on an android device too.

**Comment by DarkCrypt** [comment]
Sadly, WSA will no longer be supported after March 5, 2025. Learn more at [Microsoft/WSA](https://github.com/microsoft/WSA/discussions/536) (GitHub) and [Microsoft Learn](https://learn.microsoft.com/en-us/windows/android/wsa/).
