### ISSUE TITLE
Strange error.

### ISSUE THREAD

**Issue by Fertanima** [libre-tube/LibreTube#1351]
### Steps to reproduce

1.https://piped.kavin.rocks/watch?v=-hhpE1HPTkA 
open the video.
2.Video is loading.
3.The application closes without opening the video.

### Expected behavior

The video should open without any problems.

### Actual behavior

The video did not open. The application closed.

### LibreTube version

0.5.1

### Android version

Android 12

### Other details

The problem is only in this video, there is no problem in other videos. There is no error report because it does not appear.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Fertanima** [comment]
I posted with the error tag because I don't know what the problem is.

**Comment by Fertanima** [comment]
https://user-images.githubusercontent.com/112704336/191940218-4ae89a39-750c-4cd7-9c80-29dd6fa2424f.mp4

**Comment by Bnyro** [comment]
Tested with debug builds, it's playing fine there.

**Comment by Fertanima** [comment]
But why doesn't it work on my phone?

**Comment by Bnyro** [comment]
2 possibilities:
1. Use a different instance
2. Fixed after the last release
