### ISSUE TITLE
Downloaded videos have no sound

### ISSUE THREAD

**Issue by matchboxbananasynergy** [libre-tube/LibreTube#1353]
### Steps to reproduce

1. Download a video with audio
2. Try to play it, it has no sound

### Expected behavior

It should have audio if you've downloaded audio

### Actual behavior

Only the video plays

### LibreTube version

0.6.0

### Android version

Android 13 (GrapheneOS)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Fertanima** [comment]
I'm watching the download in the notification panel, the video is downloading, but the sound is lowered a little and then stops.

**Comment by ghost** [comment]
This is still a thing.

**Comment by ghost** [comment]
Who thought downloading a video and it audio into thier own separated thing is a good idea?

**Comment by Bnyro** [comment]
> Who thought downloading a video and it audio into thier own separated thing is a good idea?
>
YouTube

**Comment by ghost** [comment]
> > Who thought downloading a video and it audio into thier own separated thing is a good idea?
> 
> YouTube

Can you take a look at ytb-dlp, similar tech or the one that NewPipe is using to implement an actual video downloading feature instead?

**Comment by Bnyro** [comment]
> Can you take a look at ytb-dlp, similar tech or the one that NewPipe is using to implement an actual video downloading feature instead?
>
That's out of scope, use a downloader app like Seal instead.
