### ISSUE TITLE
Display the status bar when tapping on the video in fullscreen mode 

### ISSUE THREAD

**Issue by yhm4ps1jfp67nkv** [libre-tube/LibreTube#1356]
### Describe your suggested feature

When playing a video in fullscreen mode and tapping on it the status bar should be shown together with the controls

### Other details

This leads to a better use experience since the user could easily check the time and battery level without having to make an additional swipe 

Could be made an option in the settings 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
In my opinion it shouldn't, the status bar hides parts of the video player, e.g. the title, therefore it'd rather be sidetracking than more intuitive.

**Comment by yhm4ps1jfp67nkv** [comment]
You could move the video title and other information/buttons further down when the status bar is shown - this way no parts would be hidden
