### ISSUE TITLE
Source error

### ISSUE THREAD

**Issue by Fertanima** [libre-tube/LibreTube#1357]
### Steps to reproduce

1.https://piped.kavin.rocks/watch?v=-hhpE1HPTkA
open the video.
2.Loading...
3.A source error has occurred
4.Try again by clicking the play button, the video often breaks or freezes, but the sound comes out.

### Expected behavior

The video should play without an error.

### Actual behavior

A source error has occurred.

### LibreTube version

0.6.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Fertanima** [comment]
It didn't because there was no bug report.

**Comment by Bnyro** [comment]
That's an instance issue, try to use an other or switch the quality!
