### ISSUE TITLE
Improve downloads.

### ISSUE THREAD

**Issue by Fertanima** [libre-tube/LibreTube#1359]
### Describe your suggested feature

1.Download speed limit
2.Download video limit.
3.Download with mobile data.
4.Pause all, Resume all.
5.Download safe.
6.Download history.
7. Trash can.
8. Show the download process in the application.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not possible with the Android download manager
