### ISSUE TITLE
No time synchronization when going from audio to video mode

### ISSUE THREAD

**Issue by yhm4ps1jfp67nkv** [libre-tube/LibreTube#1362]
### Steps to reproduce

1. Open a video
2. Tap "Audio"
3. Continue listening in audio mode

### Expected behavior

After switching back to video mode, the playback will start from the last playback position in audio mode

### Actual behavior

After switching to video mode, the playback continues from where it stopped in video mode

### LibreTube version

Latest debug build from GitHub actions

### Android version

Android 12

### Other details

When playing as audio in the background, show the thumbnail with a play button in the app instead of a video stream. After tapping the play button, the user should be able to continue watching from the last playback position in audio mode

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by yhm4ps1jfp67nkv** [comment]
Possible dublicate of #1113

**Comment by Bnyro** [comment]
Actually of #1157 ;)
