### ISSUE TITLE
Home page blank, but only on one device, working on the other

### ISSUE THREAD

**Issue by RNavarro3000** [libre-tube/LibreTube#1366]
### Steps to reproduce

1. Start LibreTube on both Phone (LG G8 w. Android 10 ) and Tablet (Samsung Tab S5e w. Android 11), both using LibreTube default settings
2. Home page is working for phone, Home page is blank for tablet
3. Tried multiple piped instances, home is always blank on Tablet
4. See details below for testing results

### Expected behavior

Home should show trending content.

### Actual behavior

Home is blank

### LibreTube version

0.6.0

### Android version

Android 11

### Other details

I've seen the home page working on the Tablet in previous versions of LibreTube, so I installed all previous versions found on Github to see when things broke.

0.6.0 - Home page blank
0.5.1 - Home page blank
0.5.0 - Home page blank
0.6.0 - Home page blank
0.4.2 - Home page blank
0.4.1 - Home page blank
0.3.3 - Home page working
0.3.2 - Home page working
0.3.1 - Home page working
0.2.2 - Home page working
0.2.1 - Home page working
0.2.0 - Home page working

![Tablet ver 0 6 0](https://user-images.githubusercontent.com/121646/192090308-0ff3b70d-bf27-41f9-87ee-a1a314ee03e4.png)
![Tablet ver 0 3 3](https://user-images.githubusercontent.com/121646/192090310-c300873f-3104-4c90-8497-bc7cb4f70f2a.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
With 0.4.1, the region gets automatically picked depending on your Android settings.

Some countries don't work, e.g. because YouTube is blocked in that country.

To change it manually, navigate to Settings -> General -> Region and change it manually :)

**Comment by Bnyro** [comment]
I will add something to prevent future users from running into the same issue by notifying when the region doesn't seem to work ;)

**Comment by RNavarro3000** [comment]
Thanks Bnyro, that fixed my issue.  Cheers.

**Comment by matkoniecz** [comment]
> Some countries don't work, e.g. because YouTube is blocked in that country.

And if someone wants to get rid of atrociously bad videos on startup (but still maliciously optimized to encourage looking at them) - then selecting embargoed Iran works well to get rid of such videos on a startup screen :)
