### ISSUE TITLE
[FEATURE] Allow importing subscriptions and libraries from NewPipe

### ISSUE THREAD

**Issue by Etim-Orb** [libre-tube/LibreTube#137]
**Describe the feature you'd like to see added**
A short description of the feature, and what it would accomplish.

Allow importing libraries like subscriptions or saved videos from a NewPipe backup.

**Additional context**

**Comment by 4JX** [comment]
Made a small patch to add that functionality (https://github.com/4JX/LibreTube/commit/e6c0b3f783308bb69720bc2c315a31562369f75e), though I believe it's probably going to need more than that to be properly worked into the app :eyes:.
