### ISSUE TITLE
No audio on video downloads

### ISSUE THREAD

**Issue by revinco** [libre-tube/LibreTube#1371]
### Steps to reproduce

When downloading videos all are muted. Audio has separate download.

### Expected behavior

Videos should have audio and video muxed.

### Actual behavior

No sound / audio, no file extension.

### LibreTube version

0.5.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Irrelevant due to latest update
