### ISSUE TITLE
sorting lists (languages, instances,..) by A-Z for easier usage

### ISSUE THREAD

**Issue by eladkarako** [libre-tube/LibreTube#1372]
### Describe your suggested feature

sort various lists, A-Z.

<img src="https://user-images.githubusercontent.com/415238/192111679-ee09e591-0a74-457b-b7aa-7fc98248a99b.png"/>

<details><summary>Other details</summary>

noticed https://github.com/libre-tube/LibreTube/blob/b4e8ee5989aec4b70594a67794e3f5befea4e3f5/app/src/main/res/values/array.xml is sorted in the XML, but not rendered in that order for some reason..  

edit:  
oh, it's a fallback.

</details>

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The instances in the array resource are only fallback, instances are fetched from https://piped-instances.kavin.rocks/
