### ISSUE TITLE
download folder missing

### ISSUE THREAD

**Issue by revinco** [libre-tube/LibreTube#1374]
### Steps to reproduce

download folder cannot be defined, nor appearing in local file manager.

### Expected behavior

file downloaded should appear in android's file manager

### Actual behavior

file download not showing in file manager

### LibreTube version

0.6.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Downloads can be found under library -> downloads.
If you need the files, you can find them under `Android/data/com.github.libretube`.
