### ISSUE TITLE
Zoom in to fill the screen.(automatic)

### ISSUE THREAD

**Issue by Fertanima** [libre-tube/LibreTube#1376]
### Describe your suggested feature

Auto-zoom option so videos always fill the full screen.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The option already exists in the player settings

**Comment by Fertanima** [comment]
Auto zoom.

**Comment by Fertanima** [comment]
YouTube has an option to automatically fill the video full screen

**Comment by kubo6472** [comment]
Confusingly called "resize mode" it is there. Found it after looking through the issues. Thanks.
