### ISSUE TITLE
Enable auto-rotation by default

### ISSUE THREAD

**Issue by xmha97** [libre-tube/LibreTube#1382]
### Describe your suggested feature

Please auto-rotation by default (like the official YouTube app)
In some devices that only support landscape, such as car displays, the UI is not displayed well.
I want you to enable this option by default, so if someone doesn't want this feature, they can disable it.
![Screenshot_2022-09-25-15-15-42-530_com github libretube](https://user-images.githubusercontent.com/23485114/192141957-053897e5-9f4b-476a-bdc8-e794fe016cf0.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The app isn't meant to be used in landscape mode natively since there are some issues with it. When users enable it, then on their own risk to experience some bugs that wouldn't have been present without the option.

**Comment by xmha97** [comment]
> The app isn't meant to be used in landscape mode natively since there are some issues with it. When users enable it, then on their own risk to experience some bugs that wouldn't have been present without the option.

If these problems are solved, you will enable this option, right?

**Comment by xmha97** [comment]
> The app isn't meant to be used in landscape mode natively since there are some issues with it. When users enable it, then on their own risk to experience some bugs that wouldn't have been present without the option.

@Bnyro If these problems are solved, you will enable this option, right?

**Comment by xmha97** [comment]
@Bnyro 
Isn't it time to enable auto-rotation by default?
The auto-rotation works fine on my phone without any issues.

**Comment by xmha97** [comment]
@Bnyro
Isn't it time to enable auto-rotation by default?
The auto-rotation works fine on my phone without any issues.

**Comment by xmha97** [comment]
@Bnyro
Isn't it time to enable auto-rotation by default?
The auto-rotation works fine on my phone without any issues.

**Comment by Bnyro** [comment]
Nada
