### ISSUE TITLE
Comment timestamps

### ISSUE THREAD

**Issue by GilesMunn** [libre-tube/LibreTube#1383]
### Describe your suggested feature

It would be nice if comments that mention timestamps could be a link that would jump the player to that time in the video.

### Other details

 It's useful in long videos where people will put unofficial chapter markers in the comments, e.g.

[1:20](#) - X happens
[10:50](#)  - Y happens
[1:02:06](#) - Z happens

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That could be made possible with the help of https://github.com/TeamNewPipe/NewPipeExtractor/pull/928

**Comment by Bnyro** [comment]
Timestamps in the comments are underlined now since the comment text is now using HTML, however it's still not clickable currently for whatever reason.

**Comment by xIUPITERx** [comment]
> Timestamps in the comments are underlined now since the comment text is now using HTML, however it's still not clickable currently for whatever reason.

I think this is in confoict with the function to show replies to comments.
