### ISSUE TITLE
Problem playing video in automatic quality.

### ISSUE THREAD

**Issue by Fertanima** [libre-tube/LibreTube#1384]
### Steps to reproduce

The source error video plays in 720p when the default quality is set to 360p, but it does not play at all in automatic. The source error videos do not want to follow the default quality. However, change the quality from automatic to another quality on the player, there is no problem with the video.This means that the problem is not in the server, the video cannot be played in automatic quality. But Piped does not have this problem.Those videos work fine .Piped's server plays videos flawlessly without changing the quality. Automatic quality. A solution to this problem will be found. Let This issue should be left open and a solution will be found.

### Expected behavior

It should play smoothly.

### Actual behavior

Annoying error!

### LibreTube version

0.6.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Fertanima** [comment]
Sometimes we don't see quality numbers.

**Comment by Fertanima** [comment]
Maybe there is no compatibility with the settings of the player.

**Comment by Bnyro** [comment]
It's either an instance or an ExoPlayer issue: 
Piped on the Web doesn't use the same sources as we do!

**Comment by Fertanima** [comment]
I don't think it's a server problem.

**Comment by Fertanima** [comment]
But how can this problem be solved?
