### ISSUE TITLE
Edge-to-edge

### ISSUE THREAD

**Issue by Naverim** [libre-tube/LibreTube#1385]
### Describe your suggested feature

The navbar background and status bar should be transparent, for example (the navbar and status bar don't have backgrounds on them)
![Screenshot_20220926-184038](https://user-images.githubusercontent.com/103884904/192267488-bbf88e10-f5aa-484b-af4e-89bf557ec1cb.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's already the case, see https://github.com/libre-tube/LibreTube/blob/master/app/src/main/res/values/themes.xml#L5-L8
