### ISSUE TITLE
Open channel from mention.

### ISSUE THREAD

**Issue by rozari0** [libre-tube/LibreTube#1390]
### Describe your suggested feature

When I click on mentioned channel libretube would open channel.
Newpipe do that. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You mean a mentioned channel in the video description?

**Comment by rozari0** [comment]
> You mean a mentioned channel in the video description?

Yes, from description and title. Take this[this](https://www.youtube.com/watch?v=JujkNz3zdvU)  as example.

**Comment by shantanu1k** [comment]
Hi @Bnyro @rozari0 , I guess this can be resolved by the intents. Because, currently the LibreTube is not receiving intents for Youtube video links. What do you think?

**Comment by Bnyro** [comment]
> Hi @Bnyro @rozari0 , I guess this can be resolved by the intents. Because, currently the LibreTube is not receiving intents for Youtube video links. What do you think?

In theory that should work already, not sure why it didn't in that case though (you can see the `RouterActivity.kt` for how it's currently done)

**Comment by Bnyro** [comment]
Unfortunately we can't add that currently as the NewPipe Extractor only returns the plain text, but not the links to the channel at the moment. After that gets changed in the extractor, the app should already handle such links properly :)
