### ISSUE TITLE
15, 25, 60 seconds forward and backward video

### ISSUE THREAD

**Issue by Fertanima** [libre-tube/LibreTube#1396]
### Describe your suggested feature

15,25,60 no search time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Donkey-Doug** [comment]
Just move to continuous adjustability then.
