### ISSUE TITLE
Add time options 1 second, 4 hours, 1 day to notification check frequency.

### ISSUE THREAD

**Issue by Fertanima** [libre-tube/LibreTube#1397]
### Describe your suggested feature

Add time options 1 second, 4 hours, 1 day to notification .Also 1 hour=60 minutes.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I'll add 1 day, 1s is impossible because the minimum is 15min, 4 hours doesn't make sense to me

**Comment by Fertanima** [comment]
Ok
