### ISSUE TITLE
Delete the APK.

### ISSUE THREAD

**Issue by Fertanima** [libre-tube/LibreTube#1399]
### Describe your suggested feature

Automatically uninstall APK after installing.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not possible, installation process is handled by the OS, can't detect it's ended. Work arounds are not worth it
