### ISSUE TITLE
Playlist menu

### ISSUE THREAD

**Issue by heberjeur** [libre-tube/LibreTube#140]
**Describe the feature you'd like to see added**
Hi,

Can you please add the ability to show the playlists inside a YouTube channel ?
At the time being, when one opens a YouTube channel url ([example URL](https://www.youtube.com/channel/UCNb2H0PwlajFSmfjgfDdKvA/?disable_polymer=1)) on the smartphone and shares it to LibreTube, there is actually no way to show the playlists ([example playlists](https://www.youtube.com/channel/UCNb2H0PwlajFSmfjgfDdKvA/playlists?disable_polymer=1)) of that selected channel

**Additional context**
SkyTube for example have this feature, I think is important to add to this application.

**Comment by rakibdev** [comment]
This the first thing I was looking after installing app. There no way to see playlist from channel or searching. Only reason I still have to use NewPipe for now. In NewPipe I can search playlist link copying from YouTube. Then those existing playlist can be added directly. But here I have to create playlist from scratch.

**Comment by Bnyro** [comment]
Piped doesn't support it, so there's currently no way how we could add that.
