### ISSUE TITLE
refresh/re-read playlist when clicking Next button or current video ends

### ISSUE THREAD

**Issue by ydqsbfsyi** [libre-tube/LibreTube#1402]
### Describe your suggested feature

I find playlist very handy interacting between phone and TV  - I could search or randomly surf in my phone, and add any video I'm interested to the playlist, then play them all on Android TV, which shares the same instance account.

One thing though: when watching a video in playlist on TV, if I add a new video to the phone playlist, TV can not automatically refresh the playlist, I have to close the current video, go to library and re-enter the playlist, that will refresh it, then I could scroll down to the end and find the new video and play.

How about some auto refresh? - only at the moment when clicking Next button or current video ends. Or, either of the above two but only for the last video in playlist.  

And I'm also thinking about: when the above refreshing happens, we can not use just a numeric number in playlist to identify which is the current video? since sometimes we delete some videos in former part of playlist when adding new video, which changes numbers.

Please consider.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't think that making an additional request to fetch the playlist again would be a good idea, sorry. It might make sense to add swipe to refresh to it in the future although that probably wouldn't help you on a TV either (TVs are not officially supported by LT though).

**Comment by ydqsbfsyi** [comment]
> I don't think that making an additional request to fetch the playlist again each time a video ends would be a good idea, sorry. It might make sense to add swipe to refresh to it in the future although that probably wouldn't help you on a TV either (TVs are not officially supported by LT though).

Thanks for taking time. For TV,  better than any other function, "pause/resume play by doubling clicking middle area" is a leap.
