### ISSUE TITLE
Words not in translation.

### ISSUE THREAD

**Issue by Fertanima** [libre-tube/LibreTube#1403]
### Describe your suggested feature

![Screenshot_20220929-090133_LibreTube](https://user-images.githubusercontent.com/112704336/192943149-4514e141-1624-4684-ba3d-1007c9888167.jpg)
![Screenshot_20220929-085349_LibreTube](https://user-images.githubusercontent.com/112704336/192943191-e85e7e76-74be-4b0c-a26d-d156c1496b8c.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't think it makes sense to let users translate these
