### ISSUE TITLE
In dark mode, the color accent is displayed incorrectly.

### ISSUE THREAD

**Issue by Fertanima** [libre-tube/LibreTube#1404]
### Describe your suggested feature

https://user-images.githubusercontent.com/112704336/192943840-286cf344-6a36-4fba-8e36-adb30fb72847.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It's just a different accent color...
