### ISSUE TITLE
Option to launch the player in full screen.

### ISSUE THREAD

**Issue by Fertanima** [libre-tube/LibreTube#1409]
### Describe your suggested feature

Option to launch Player in full screen in Settings.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That'd be auto-fullscreen
