### ISSUE TITLE
32-bit ARMv7 support

### ISSUE THREAD

**Issue by MSokar-NU** [libre-tube/LibreTube#141]
Can the app support 32-bit ARMv7 instruction set ? (Android 4.4.4)
![2022-04-21 14 04 15](https://user-images.githubusercontent.com/73124030/164454314-761b9461-e05a-4260-b7ef-d1c16a4bc306.png)

**Comment by MSokar-NU** [comment]
> Libretube doesnt even support kitkat anyways, only lolypop and up

Can't recompile to run on this version of android ?

**Comment by lilcheti** [comment]
No because of Retrofit we can't do that.
