### ISSUE TITLE
can not check navbar item in settings in ANDROID TV

### ISSUE THREAD

**Issue by ydqsbfsyi** [libre-tube/LibreTube#1414]
### Steps to reproduce

 in ANDROID TV (no touch screen), settings --> appearance--> nav bar, can not check/uncheck any item with mouse click (any where around item) , and no reaction with TV's remote control up/down/ok key. (However, I managed to check "History" after some wild clickings, but it's just slim chance.) 

Also, no reaction with mouse dragging.

I don't know what new technique has been used, but old version works fine in TV.

### Expected behavior

drag or click, at least one works.

### Actual behavior

no reaction.

### LibreTube version

1664375575 debug

### Android version

Android 9 TV

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Android TV is not supported officially, the app is not meant to be used on it!
