### ISSUE TITLE
Reminder to take a break while the screen is off.

### ISSUE THREAD

**Issue by Bilingest** [libre-tube/LibreTube#1420]
### Describe your suggested feature
Reminder to take a break while the screen is off. Pause the video and display a notification.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bilingest** [comment]
That would be really nice.

**Comment by Bilingest** [comment]
Why?

**Comment by eclairevoyant** [comment]
@Bilingest most likely because it doesn't make too much sense; the point is to take a break from watching youtube videos, and do something else, but if you're playing it in the background then you are already doing something else.
