### ISSUE TITLE
Search bar preview in player.

### ISSUE THREAD

**Issue by Bilingest** [libre-tube/LibreTube#1423]
### Describe your suggested feature

Search bar preview in player

https://user-images.githubusercontent.com/114754527/193296609-416ce997-bd9e-4c9d-8751-b2325b330348.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
No plans for that at the moment
