### ISSUE TITLE
Some subs only shown after visiting the channel

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#1424]
### Steps to reproduce

1. Go to subscriptions and compare this with the same channel subscriptions in newpipe. You will notice missing videos.
2. Choose a channel of which a video is missing in libretube.
3. Visit the channel in libretube
4. Go back to the subscriptions overview and now the video is shown.

### Expected behavior

Correct subs

### Actual behavior

Missing videos in subs, but can make them show up by visiting the channel

### LibreTube version

0.6.0

### Android version

Android 12

### Other details

Video is too large for github, but can be seen here:

https://www.swisstransfer.com/d/e5207e13-4d32-4515-8a8c-8720cb92aea7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's a known issue at Piped, you can track it or help with additional information at https://github.com/TeamPiped/Piped/issues/1130.

**Comment by xIUPITERx** [comment]
As a temporary solution, could LibreTube be forced to open every subscribed channel when the app is opened for the first time?
Or you can create a list of the most important channels to be opened.

**Comment by Donkey-Doug** [comment]
> As a temporary solution, could LibreTube be forced to open every subscribed channel when the app is opened for the first time? Or you can create a list of the most important channels to be opened.

That sounds like a bad solution. we just have to wait for the piped fix.

**Comment by xIUPITERx** [comment]
"Only new videos uploaded from 6 hours back would be updated in the feed, this is due to the nature of how PubSub works."

So Videos in the subscription feed should always be older than 6 hours?

**Comment by xIUPITERx** [comment]
> That sounds like a bad solution. we just have to wait for the piped fix.

Yes, apparently you would also have to reopen the channels at least every hour.
