### ISSUE TITLE
Do not show buttons if their function is not available

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#1425]
### Describe your suggested feature

![Screenshot_20220930-170204_Lawnchair](https://user-images.githubusercontent.com/50382414/193299359-47a88b49-5863-486c-9ef1-d3b3ba9a9739.png)

In this cropped screenshot from the picture in picture mode, I cannot use next and previous but the buttons are still shown (and greyed out). Maybe hide the buttons if I cannot use their function.

### Other details

-

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
They can't be hidden, other video player apps I saw have the same issue to unfortunately :/
