### ISSUE TITLE
Still auto rotates after disabling auto rotate

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#1426]
### Steps to reproduce

1. Disable auto rotate in android (for example, in quick settings toggle)
2. Libretube still rotates

### Expected behavior

No auto rotate

### Actual behavior

Auto rotate

### LibreTube version

0.6.0

### Android version

12

### Other details

-

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Can't reproduce + try disabling auto rotate from libre tube settings

**Comment by Donkey-Doug** [comment]
I want to have auto rotate in libretube enabled and have the app respect system settings. The enabled auto rotate in libretube overwrites system settings.

**Comment by Bnyro** [comment]
Can't reproduce either, weird.

**Comment by Donkey-Doug** [comment]
I tried again and it actually only happens when watching a video. So in search results auto-rotate does respect system settings but after opening a video rotating it will always move to the fullscreen player.

**Comment by Bnyro** [comment]
There's an extra-option for it, it's called auto-fullscreen in the player settings. Are you sure you disabled that?

**Comment by jake8923948** [comment]
> There's an extra-option for it, it's called auto-fullscreen in the player settings. Are you sure you disabled that?

THANK YOU! I was going mad trying to watch YouTube in bed and could not figure out why it kept rotating... I disabled system rotate, enabled system rotate, locked it to landscape, enabled and disabled in the app (auto rotation) and all the different combinations of these settings..... Your comment saved me!
Settings > player > auto fullscreen

Now I can lay in bed, in landscape mode with the phone perpendicular to my head :D
