### ISSUE TITLE
Block mobile internet usage.

### ISSUE THREAD

**Issue by Bilingest** [libre-tube/LibreTube#1427]
### Describe your suggested feature

Option to turn off mobile data usage. Let the app work only on Wi-Fi.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
I would find this feature quite useful, because my WiFi breaks fairly often und I don't have much mobile data.

There is already an option for mobile data video qualtity, why not add an option to deactivate it?
