### ISSUE TITLE
Bedtime reminder.

### ISSUE THREAD

**Issue by Bilingest** [libre-tube/LibreTube#1429]
### Describe your suggested feature

Remind me when it's time to sleep.
Adjust Start and End time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bilingest** [comment]
As an additional feature, add the option to wait until the end of the video.

**Comment by Bnyro** [comment]
That's something you should use an external app for!
