### ISSUE TITLE
Removal of the community tab

### ISSUE THREAD

**Issue by Bnyro** [libre-tube/LibreTube#1431]
### Describe your suggested feature

The community tab promotes several non-free networks:
* Discord
* Reddit
* Telegram
* Twitter

In my opinion it would make sense to get rid of the community tab and only promote the Matrix room inside the `About` tab of the app.

### Other details

Other opinions or takes on that are very welcome!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by rozari0** [comment]
Maybe you should share link of foss instance. Like libreddit for reddit or nitter for twitter?

**Comment by Bilingest** [comment]
Open the Public section by swiping the About section to the left.

**Comment by Bnyro** [comment]
Well, I personally only use Matrix and sandboxed Discord, the other social media accounts/subs are not affiliated with me. I know that the project is hosted on Github which is not foss either, but I still think it's a good idea to reduce the dependency on such platforms.
