### ISSUE TITLE
Sentence missing from Weblate.

### ISSUE THREAD

**Issue by Bilingest** [libre-tube/LibreTube#1437]
### Describe your suggested feature

Playback download interval size.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
reason: #1436

**Comment by Bilingest** [comment]
> reason: #1436

😁
