### ISSUE TITLE
SponsorBlock upgrade..

### ISSUE THREAD

**Issue by Bilingest** [libre-tube/LibreTube#1438]
### Describe your suggested feature

Option to whitelist the channel.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
In that case you would use the `Skip manually` option.
