### ISSUE TITLE
Buffer settings.

### ISSUE THREAD

**Issue by Bilingest** [libre-tube/LibreTube#1439]
### Describe your suggested feature

1.Maximum buffer.
2.Start playback.
3.Re-buffering.

Change the buffer size.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The ExoPlayer doesn't provide so many options, therefore not possible!
