### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Bilingest** [libre-tube/LibreTube#1441]
### Describe your suggested feature

Why are you removing some features?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I close everything that's useless in my opinion or not possible to add. Since you aren't capable of opening less than two issues per day, I'm closing most of them.
