### ISSUE TITLE
Update from top to bottom.

### ISSUE THREAD

**Issue by Bilingest** [libre-tube/LibreTube#1442]
### Describe your suggested feature

Swipe down to refresh in Playlists and Browsing history.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Sense?

**Comment by Bilingest** [comment]
Good.
