### ISSUE TITLE
Language resets itself

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#1445]
### Steps to reproduce

https://user-images.githubusercontent.com/97352673/193420758-509951a0-4315-4faa-8a65-80a062a58eb7.mp4

### Expected behavior

Language should stay the same

### Actual behavior

Language changes

### LibreTube version

0.6.0

### Android version

Android 12 One UI 4.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't reproduce that one, but since the issue is not really that serious I'll close the issue for now!

**Comment by xIUPITERx** [comment]
But wouldn't it make sense to keep the issue open, since it hasn't been fixed yet?

**Comment by Bnyro** [comment]
> But wouldn't it make sense to keep the issue open, since it hasn't been fixed yet?

Well, if that's really an issue it's Android's and not LibreTube's, I doubt we could do anything about it!

**Comment by xIUPITERx** [comment]
But if I set the language in libretube to English, it's more the app's fault than Android's if the language is still in German.
