### ISSUE TITLE
No screen space left to view results on a smartwatch due to large interface

### ISSUE THREAD

**Issue by mathkkad** [libre-tube/LibreTube#1446]
### Steps to reproduce

No screen space left to view results on a smartwatch due to large interface that can't be hidden - option to hide "navigation bar" or/and "all-videos-channels-playlists" bar

I really love this app on my phone and I also installed it on my Samsung Galaxy Watch 5 smartwatch. It works great but when searching there is no space to display the search results because of the persistent "navigation bar" and the "all-videos-channels-playlists" bar that appears occupy the entire space.
Please add an option to hide the "navigation bar" or/and "all-videos-channels-playlists" bar so I can use the app fully on my watch and migrate from NewPipe that does not have this issue but does not play all the videos all the time like LibreTube does. 

Thank you

### Expected behavior

When searching for videos there the interface top and bottom should not "unite" and leave no space for the video results on a smartwatch like other Youtube clients do. Otherwise the app works great

### Actual behavior

"navigation bar" and "all-videos-channels-playlists" bar unite and there is no space left to see the video results

### LibreTube version

0.6.0

### Android version

Galaxy Wear 3.5 - Samsung Galaxy Watch 5

### Other details

There is an option to hide some tabs from the "navigation bar" but not the bar itself to leave more space for video results. Please add this option

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Hey, thanks for your interest in using the app.
However, the app is meant to support Android phones only, other devices like Android TVs or smart watches might work as well but are not officially supported.
To give you a heads up, there's another issue about being able to disable the navigation bar completely so the compatibility could get improved anyways.
