### ISSUE TITLE
Landscape menu hidden

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#1447]
### Steps to reproduce

1. View video in landscape
2. Click on arrow to reveal settings.
3. The menu is hidden

### Expected behavior

Menu directly visible

### Actual behavior

I need to swipe up to show the menu

### LibreTube version

0.6.0

### Android version

12

### Other details

![Screenshot_20221002-014041_LibreTube](https://user-images.githubusercontent.com/50382414/193432082-3f37de83-5bc5-4762-8ce9-5b96f32477b6.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bilingest** [comment]
This is not an error.

**Comment by Bilingest** [comment]
In fact, it should be fixed or improved.

**Comment by Bnyro** [comment]
It's not expanded by default, right, but it's intended to be like that because otherwise it would fill the whole screen immediately.

**Comment by Donkey-Doug** [comment]
> It's not expanded by default, right, but it's intended to be like that because otherwise it would fill the whole screen immediately.

Well the only reason to go to that menu is to change some settings. Let me ask you the following question: do you think there are scenarios in which a user opens the menu and does not swipe up to reveal its contents?
