### ISSUE TITLE
4k quality not available.

### ISSUE THREAD

**Issue by the4anoni** [libre-tube/LibreTube#1448]
### Steps to reproduce

1. Try to set highest quality possible

### Expected behavior

I can set 4k resolution.

### Actual behavior

I can set resolution up to 1080p

### LibreTube version

0.6.0

### Android version

Android 13

### Other details

Galaxy S10 screen resolution is 1440 x 3040.
There are quite few devices with resolution higher than FHD+
Also this feature may be useful even on devices with FHD resolution, since YT has poor bitrate.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bilingest** [comment]
No quality at all?

**Comment by Bilingest** [comment]
Otherwise, an error occurs when you click on it.

**Comment by the4anoni** [comment]
> No quality at all?

4k is not available on resolution list
![Uploading Screenshot_20221002-085535_LibreTube.png…]()

**Comment by Bilingest** [comment]
Oma is not necessary.

**Comment by Bilingest** [comment]
Because it is illogical to make the default resolution 4K.

**Comment by the4anoni** [comment]
> Because it is illogical to make the default resolution 4K.

Why not, If I have unlimited Wi-Fi?

**Comment by Bilingest** [comment]
You can choose the desired quality in the player.

**Comment by Bilingest** [comment]
> > Because it is illogical to make the default resolution 4K.
> 
> Why not, If I have unlimited Wi-Fi?

Auto video quality is the best for you.

**Comment by Bilingest** [comment]
Maybe they will add.

**Comment by Bilingest** [comment]
This is not an error.
