### ISSUE TITLE
Landscape mode in the downloaded video.

### ISSUE THREAD

**Issue by Bilingest** [libre-tube/LibreTube#1449]
### Describe your suggested feature

The downloaded video cannot be viewed in my landscape mode.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It can?

**Comment by Bilingest** [comment]
Bəli

**Comment by Bilingest** [comment]
You can watch it on YouTube.
