### ISSUE TITLE
First option in navigation bar is always shown ag start even if unchecked

### ISSUE THREAD

**Issue by lucamp** [libre-tube/LibreTube#1451]
### Steps to reproduce

1. Open LibreTube's settings
2. Go to general
3. Navigation bar
4. Uncheck the first item (default is home page but it does not matter which is the first in the list)
5. Restart LibreTube

### Expected behavior

LibreTube first opening page is the first checked in navigation bar option

### Actual behavior

First page shown is the first in the list even if unchecked.
Navigation bar correctly hide the unchecked tab

### LibreTube version

0.6.0

### Android version

10

### Other details

# workaroud
Move the first checked page at the beginning of the navigation bar list

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's already know, thank you!
It's going to be fixed with the next release :)
