### ISSUE TITLE
Movement should be regulated

### ISSUE THREAD

**Issue by Bilingest** [libre-tube/LibreTube#1452]
### Describe your suggested feature

You enter the comments and disclosures section, when you click the back button, you exit the player. When you click the back button, you need to exit that section.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Doesn't make sense imo
