### ISSUE TITLE
Copy

### ISSUE THREAD

**Issue by Bilingest** [libre-tube/LibreTube#1453]
### Describe your suggested feature

Copy the text in the video description.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Already possible!

**Comment by Bilingest** [comment]
But there is no information about Category, License, Privacy in the disclosure section.
