### ISSUE TITLE
[FEATURE] Translation

### ISSUE THREAD

**Issue by hands8142** [libre-tube/LibreTube#146]
**Describe the feature you'd like to see added**
I want to participate in the translation. How can I participate in the translation?

**Comment by Anas-Sherif** [comment]
Me too I can translate for arabic.

**Comment by lilcheti** [comment]
I'll add the weblate soon for translation

**Comment by lilcheti** [comment]
Hey everyone, we just integrated weblate you can start translating here: https://hosted.weblate.org/projects/libretube/libretube/

**Comment by hands8142** [comment]
Many people are happy to add a translation.
