### ISSUE TITLE
The arrow icon is not working properly.

### ISSUE THREAD

**Issue by Bilingest** [libre-tube/LibreTube#1460]
### Describe your suggested feature

The arrow to the right of search queries does not work properly. Clicking on it will search.Not really for searching.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It closes the search view, as it should!
