### ISSUE TITLE
Option to sort playlists

### ISSUE THREAD

**Issue by GilesMunn** [libre-tube/LibreTube#1466]
### Describe your suggested feature

Currently, the playlists seem to change order by most-recently opened. It'd be nice if we could have an option to set this statically (such as by alphabetical order) or a user-defined order, since it can be distracting when the playlists move around.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
This will work fine on self-created playlists, however it won't on YT playlists without API changes because we only get the latest 20 videos of a list at once.
