### ISSUE TITLE
Use normal player with downloaded videos

### ISSUE THREAD

**Issue by GilesMunn** [libre-tube/LibreTube#1467]
### Describe your suggested feature

At present, LibreTube will only use the landscape player with downloaded videos. As mentioned in #1465, it'd be good if we could have a version of the regular player (with portrait mode, the option to switch to audio-only, open in external app, etc.) to use with downloaded videos.

### Other details

Since there would be no comments if the user were offline, this area (and the subscribe button) could be hidden, or shown if the user is online. The related videos section could show video suggestions from the internet if the user is online, other downloaded videos if the user is offline, or hidden if the user has no other downloaded videos.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Closing in favor of #2527
