### ISSUE TITLE
Scrubber bar no longer changes colour

### ISSUE THREAD

**Issue by GilesMunn** [libre-tube/LibreTube#1468]
### Steps to reproduce

The scrubber on the video timeline when watching something no longer changes colour to reflect the current theme.

### Expected behavior

Scrubber would change to blue/red/green/whatever colour is in the main theme.

### Actual behavior

Scrubber always remains white, no matter the theme settings.

### LibreTube version

Current debug

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
I hope it's not an bug, I found the dynamic color being to dark.
And since all the other buttons in the player are white, I looks better, in my opinion.
