### ISSUE TITLE
Show number of comment replies

### ISSUE THREAD

**Issue by GilesMunn** [libre-tube/LibreTube#1469]
### Describe your suggested feature

At the moment, comments are displayed, but to see any replies you have to click on each comment. If there are no replies, you get a toast notification with "This comment has no replies.". It'd be nice if we could get a message icon next to the like button with the number of replies next to it if this is something we know when the comments page is loaded. 

If we don't have this information until the user clicks on the comment, could we perhaps show a "Show replies" button, or even a message icon with no number next to it to indicate that there are child comments, without the user having to click on a comment to find out?

### Other details

Ideal solution:
![image](https://user-images.githubusercontent.com/25082324/193462236-8077bb1f-d6a3-4313-9b10-4c4ac8ef19d7.png)

Acceptable solution:
![image](https://user-images.githubusercontent.com/25082324/193462333-22de8a0d-3452-44f3-b3ef-26d074948fb3.png)

Alternative solution:
![image](https://user-images.githubusercontent.com/25082324/193462249-cf371404-5332-428c-a956-09ffdb225876.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It can't be detected yet unfortunately, I think there was a PR at the extractor for it. The replies need to be fetched seperatly, which happens when the user clicks the comment in our case.
