### ISSUE TITLE
Set download preferences in settings

### ISSUE THREAD

**Issue by GilesMunn** [libre-tube/LibreTube#1471]
### Describe your suggested feature

It'd be good if we could pick preferences for downloads in the settings pages so that we don't need to specify every time we press the "Download" button. I know that there are different streams and so giving the user the choice is the easiest way to get around it, but I'd like it if we could pick something like "download the highest quality video that my device can support, and the highest quality audio" and not have to pick every time.

### Other details

The configuration options and "format selection" sections of the README at https://github.com/ytdl-org/youtube-dl contain some good ideas on how we can give the user powerful options that they can tweak, but not make it so that they have to specify which streams they want every time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bilingest** [comment]
The problem is not solved by your opening an issue here.

**Comment by Bilingest** [comment]
Real problems need to be reported.

**Comment by Bilingest** [comment]
Many of these problems apply to Piped.
