### ISSUE TITLE
Period in some settings descriptions

### ISSUE THREAD

**Issue by DarkCat09** [libre-tube/LibreTube#1472]
### Steps to reproduce

Just open settings and look at the summaries (descriptions).

### Expected behavior

"Adjust the app to your liking" (without period at the end)  
"Quality and format"  
"Use a different instance for authenticated calls" (without period)

### Actual behavior

"Adjust the app to your liking." (with period)  
"Quality and format"  
"Use a different instance for authenticated calls." (with period)

As you can see, some of them has a period ag the end of their description, some of them not.  
Also, Weblate shows a warning when I'm trying to fix this in my language.

### LibreTube version

0.6.0

### Android version

Android 11

### Other details

![Screenshot_20221002-194621](https://user-images.githubusercontent.com/50486086/193463126-23fd46be-779c-4a33-a776-a86414fbd3f5.png)
![Screenshot_20221002-194831](https://user-images.githubusercontent.com/50486086/193463138-129d31ea-6538-471c-993a-22477bd393c9.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Useles report, not an bug. You could've submitted a pull request instead of opening an issue

**Comment by Bnyro** [comment]
Please open a PR for it!
