### ISSUE TITLE
Add 15 second seek

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#1476]
### Describe your suggested feature

1. Add an option for 15 second seek.
2. Add the seconds up, if you have 15 seek and tap multiple times it should display 15s, 30s, 45s, 60s / 1min, 75s / 1min 15s, ... .

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bilingest** [comment]
Added.

**Comment by Bnyro** [comment]
Already added.

**Comment by xIUPITERx** [comment]
In 0.6.0? I can't find it there.

**Comment by Bilingest** [comment]
No!

**Comment by Bilingest** [comment]
It will be in the next update.

**Comment by Bilingest** [comment]
https://github.com/libre-tube/LibreTube/issues/1396#issue-1389783104

**Comment by xIUPITERx** [comment]
Point 2 has also already been added?

**Comment by Bilingest** [comment]
No

**Comment by Bilingest** [comment]
Wait for the next update.

**Comment by xIUPITERx** [comment]
Can you please write more than just No! in one text field. I get a push notification every time and it's getting really annoying.
