### ISSUE TITLE
improved uploaded time

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#1477]
### Describe your suggested feature

In your subscribtion feed is a time when the video was uploaded, but it is only accurate if you manually synced the feed a few second before. Maybe tie it to the clock of the phone.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FireMasterK** [comment]
This is actually a backend issue.
