### ISSUE TITLE
Player Animations 

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#1478]
### Describe your suggested feature

Maybe it's just me, but I'd like it if the animation with which the title and the progress bar appear and disappear were identical and simultaneous. The best thing would be to slide in the progress bar has.

### Other details

https://user-images.githubusercontent.com/97352673/193479133-f0178c52-9cb1-43e1-96d9-3a52b1d1eef0.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
They are handled by the ExoPlayer, there's no official way of changing their behavior!
