### ISSUE TITLE
Alternative Related content layout.

### ISSUE THREAD

**Issue by Bilingest** [libre-tube/LibreTube#1480]
### Describe your suggested feature

Alternative related content layouts such as alternative trend layouts.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Donkey-Doug** [comment]
There exist an alternative layout in libretube. Maybe let the user decide to apply that layout to whichever view he or she wants.

**Comment by Bilingest** [comment]
Cannot apply an alternate view to related streams below the player.

**Comment by Bnyro** [comment]
I don't see use cases/reasons for that. The alternative trending layout exists because of the bad thumbnail resolution there, somewhat to circumvent it. Adding the option everywhere is kinda pointless in my opinion.
