### ISSUE TITLE
Search within channel

### ISSUE THREAD

**Issue by rancidfrog** [libre-tube/LibreTube#1482]
# Describe your suggested feature
Youtube allows user to search within a certain channel, which is useful when trying to find something specific in a channel

Acknowledgements
- [x]  I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.
- [x]  I have written a short but informative title.
- [x]  I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
No API support for it yet!
