### ISSUE TITLE
ExoPlayer V2'də buffer settings

### ISSUE THREAD

**Issue by Bilingest** [libre-tube/LibreTube#1487]
### Describe your suggested feature

1.Start playback.(Default: 2500 millisecond.)
The maximum time to play a video for operations such as rewinding the video.
2.Re-buffering (Default: 5000 milliseconds).
Maximum media duration for video to continue after rebuffering.

3.Maximum buffer(Default is 120000 milliseconds.)
The player will try to buffer the video for a maximum of this time.

To change these options individually.Vanced allowed it.

### Other details

These options are not available in ExoPlayer V1, but can be done if LibreTube is using ExoPlayer V2.YouTube has stopped using ExoPlayer V1. It had better performance.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bilingest** [comment]
I had to open this issue again, because I did not provide detailed information.

**Comment by Bnyro** [comment]
We use V2 and adding these options wouldn't be hard, just don't know where to place them?

**Comment by Bilingest** [comment]
To the player section.

**Comment by Bilingest** [comment]
In fact, it was like a separate unit in Vanced.

**Comment by Bilingest** [comment]
In fact, the V1 was better in terms of performance.

**Comment by Bilingest** [comment]
As V2 is a bit weak, buffer settings are needed.

**Comment by Bilingest** [comment]
Can you add that?

**Comment by Bilingest** [comment]
Yada ki,mənum onunəlavə etməyimi gözləyin.

**Comment by Bnyro** [comment]
I could, but I don't want to.

**Comment by Bilingest** [comment]
Why?

**Comment by Bilingest** [comment]
I would like to do it, but I can't.

**Comment by Bilingest** [comment]
Just because I've given information about a feature doesn't mean I know everything.

**Comment by Bilingest** [comment]
If you don't add, don't close the issue, maybe others can solve it.

**Comment by Bilingest** [comment]
Please

**Comment by Bilingest** [comment]
You said this feature is not possible, I did some research.

**Comment by rozari0** [comment]
Please tell everything in one comment. 

Spamming looks like I'm using Facebook or something, not github.

**Comment by Bilingest** [comment]
Good.
