### ISSUE TITLE
[BUG] Material You accent colours don't apply automatically at app startup

### ISSUE THREAD

**Issue by Bnyro** [libre-tube/LibreTube#149]
**Describe the bug**
When opening the app the first time, the accent colours are the default red and not material you like expected. If you change the theme (for example from system to light and back) it works until the app gets restarted. Tried to fix it myself but failed xD

**To Reproduce**
1. Open the App
2. Watch the accent colours :)

**Smartphone (please complete the following information):**
 - Device: Redmi Note 9s and SDK 32 Emulator in Android Studio
 - Android version: A12L AOSP Rom

**Comment by Bnyro** [comment]
Just figured out that it works if calling this.recreate() on the first startup of the app in MainActivity.kt after calling DynamicColours.applyToActivitiesIfAvailable(), but it doesn't seem like the right solution to me.

**Comment by Bnyro** [comment]
@archroid any idea?

**Comment by archroid** [comment]
Material you is still new to me and I couldn't find solution for this. I gotta read bunch of code and I will figure it out.

**Comment by Bnyro** [comment]
> Material you is still new to me and I couldn't find solution for this. I gotta read bunch of code and I will figure it out.

Ty. I already tried to find the difference to https://github.com/wangerekaharun/ComposeMaterialYou but didn't succeed... Maybe the app there could help you somehow, idk

**Comment by archroid** [comment]
thx. I will see :)

**Comment by nin0-dev** [comment]
I found the solution. I will open a PR with the right fix!

**Comment by nin0-dev** [comment]
I opened the PR here #252

**Comment by Bnyro** [comment]
> I opened the PR here #252

@nin0-dev Wow, thank you :)
You're a legend :DDD
