### ISSUE TITLE
360P is fast.

### ISSUE THREAD

**Issue by Bilingest** [libre-tube/LibreTube#1490]
### Describe your suggested feature

Set the default quality to 360p. 360p is faster than auto quality. Even the longest videos open faster. This is very strange. Auto quality is not working properly. Maybe when the video starts, start with 360p and then play in auto quality.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bilingest** [comment]
It doesn't happen on server error.🤔

**Comment by Bnyro** [comment]
It's a bad resolution, so no!
