### ISSUE TITLE
Download upgrade.

### ISSUE THREAD

**Issue by Bilingest** [libre-tube/LibreTube#1492]
### Describe your suggested feature

When downloading video and audio, show their size next to the quality options.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We can't access the size before the download finished

**Comment by 0-st** [comment]
NewPipe and yt-dl(p) can...
