### ISSUE TITLE
Disable picture-in-picture when making a screenshot

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#1493]
### Describe your suggested feature

1. Watch a video
2. Take a screenshot
3. (press capture more)
4. The initial video now plays in pip mode while I adjust my screenshot.

Maybe the video should be paused instead?

### Other details

Similar to https://github.com/libre-tube/LibreTube/issues/1411

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It might be only me, but in my opinion the video should go on playing in PiP when editing a screenshot. Or is there anything I miss why the PiP player is disturbing?

**Comment by Donkey-Doug** [comment]
I am on android 12 and the option capture more looks as follows:

https://www.swisstransfer.com/d/01179ca1-3df1-49dd-9560-15a4c85482c5

**Comment by Bnyro** [comment]
Okay, there doesn't seem to be a way of us what the reason for minimizing the app was (which means we don't know whether you wanted to go into PiP mode or just made a screenshot). Hence I don't see a way to add this unfortunately.
