### ISSUE TITLE
Playlist sorting

### ISSUE THREAD

**Issue by rozari0** [libre-tube/LibreTube#1494]
### Describe your suggested feature

Libretube don't sort playlist in library in any common style. It's just random every time.

Should have option to sort by A-Z / Z-A or at least one of them by default. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Dude, it's called "Sorting". Misleading title

**Comment by akano12** [comment]
You mean "Sorting"

**Comment by rozari0** [comment]
> You mean "Sorting"

Fixed. :)

**Comment by Bnyro** [comment]
Dupe of #1466
