### ISSUE TITLE
Video Player `Source Error`

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#1496]
### Steps to reproduce

Was reproducible till tomorrow.

### Expected behavior

There shouldn't be any error.

### Actual behavior

It threw `Source Error`

Reference screenshot:

![Screenshot_20221004-083334](https://user-images.githubusercontent.com/87353286/193966740-890154e6-b2dd-4eef-ade7-5fb1261480e2.png)

### LibreTube version

0.6.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That happens when there's an ExoPlayer-internal error, usually because there's a server issue with the stream source!
