### ISSUE TITLE
[Feature request] Download with cover pic

### ISSUE THREAD

**Issue by brnwlshubh** [libre-tube/LibreTube#15]
Libretube will support Audio/Video Download Feature?

**Comment by rimthekid** [comment]
Yes eventually as if right now my focus is on the subscriptions and the player it self but yes after those

**Comment by alefvanoon** [comment]
> Libretube will support Audio/Video Download Feature?

Of course!

But now we are working on other features.
It may take a while to add.

Also, if someone send PR, we will be happy.

**Comment by brnwlshubh** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/5445
Is this Possible to implement in Libretube?

**Comment by rimthekid** [comment]
I'll look in to it for when I want to add the download option

**Comment by brnwlshubh** [comment]
> [TeamNewPipe/NewPipe#5445](https://github.com/TeamNewPipe/NewPipe/issues/5445) Is this Possible to implement in Libretube?

Is this includes the latest release?

**Comment by rimthekid** [comment]
I'll add it in the next release because the download option is not really stable right now but there should be no problem!

**Comment by Bnyro** [comment]
I don't see a way to download with cover pic, I'm sorry

**Comment by Bnyro** [comment]
We already support this for downloads :)
