### ISSUE TITLE
[FEATURE] Plans to add LibreTube Website 

### ISSUE THREAD

**Issue by Bnyro** [libre-tube/LibreTube#150]
Hey there,
are there any plans to host a LibreTube Website (maybe on GitHub.io) or will the Project stay on GitHub.com only?

**Comment by lilcheti** [comment]
Someone was working on it but seems like he had some other work to do.

**Comment by Bnyro** [comment]
I could try to create a simple static Website with Html and CSS if you don't mind (have already some experience with this)

**Comment by lilcheti** [comment]
Oh that'll be great yes please go on!

**Comment by Bnyro** [comment]
Okay, I'll do my best ;)

**Comment by Bnyro** [comment]
Is there any way to reach you apart from GitHub for questions concerning the website?

**Comment by lilcheti** [comment]
On [telegram](https://t.me/dopeassweed) or matrix(@farbod:tokhmi.xyz)
