### ISSUE TITLE
Finer playback speed control at low speeds

### ISSUE THREAD

**Issue by opk12** [libre-tube/LibreTube#1508]
### Describe your suggested feature

Changing 0.7 to 0.6 or 0.8 can make the difference, when hearing a foreign language or a noisy recording, but 4 is perceived the same to the ear than 4.25.

So the lower speeds should have more space and smaller increment intervals, or be truly continuous like VLC, maybe until 2x.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
If think the audible speed control is a good reference.

**Comment by Bnyro** [comment]
Well, I won't download or buy Audible to have a reference :joy: 
A screenshot or detailed description wouldn't be bad :)

**Comment by xIUPITERx** [comment]
Of course, I forgot that the app is not free.
https://user-images.githubusercontent.com/97352673/194703274-fb579bb4-502e-4f21-bba6-dab6398e423c.mp4
So many gradations would probably be a bit exaggerated.

**Comment by opk12** [comment]
Well no, as above, `Changing 0.7 to 0.6 or 0.8 can make the difference, when hearing a foreign language or a noisy recording`
