### ISSUE TITLE
Show version number in `About`

### ISSUE THREAD

**Issue by opk12** [libre-tube/LibreTube#1509]
### Describe your suggested feature

The version number could appear in the `About` panel.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It already appears on the bottom of the settings fragment, don't think we need it twice.

**Comment by opk12** [comment]
Ah thanks. I saw `About` in the hamburger menu so I would have never thought about going into Settings.

**Comment by alpentmilch** [comment]
Please re-open this. 

Usually users may go to ... menu -> About -> and expect to find version number there.

Thanks
