### ISSUE TITLE
Allow to copy the channel URL

### ISSUE THREAD

**Issue by opk12** [libre-tube/LibreTube#1510]
### Describe your suggested feature

I want to take note of the channel URL. The channel page does not have an option to copy. Maybe a long-tap on the channel name (in the video page or in the channel page) could show a popup to copy/share (like Fennec) or copy to clipboard and inform through a toast message (like Element).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Screntinel** [comment]
Click on share, choose from piped or YouTube and click "copy link"

**Comment by Screntinel** [comment]
Not what you wanted, but still works ig?
