### ISSUE TITLE
Ability to refresh recommendations

### ISSUE THREAD

**Issue by KXDJFu** [libre-tube/LibreTube#1511]
### Describe your suggested feature

Just as it says, an ability to refresh the recommended videos on the Home tab by swiping down, which already seems to refresh the page but does not change the videos recommended to you. Especially useful as there are a finite amount you can scroll through.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The videos on the home tab are the trending videos of the region you selected in the settings. They're already refreshed properly when refreshing, they just don't change that often!
