### ISSUE TITLE
Remember your download settings.

### ISSUE THREAD

**Issue by Gencevi** [libre-tube/LibreTube#1518]
### Describe your suggested feature

Option to save your download settings when you hit the download button.Some people don't want to change it every time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Dupe
