### ISSUE TITLE
[BUG] Few bugs

### ISSUE THREAD

**Issue by dhishkyaon** [libre-tube/LibreTube#152]
**Describe the bug**
Written mistakes and need colour correction

![IMG_20220501_165059.jpg](https://user-images.githubusercontent.com/88529066/166143739-17c7a632-00b5-4bd6-a34d-a0f7d8d6aa3b.jpg)
![IMG_20220501_165043.jpg](https://user-images.githubusercontent.com/88529066/166143750-6b487c54-359b-4784-baf3-99d0aefe9ffb.jpg)

**To Reproduce**
N/A

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - Android version: 12.1

**Additional context**
N/A

**Comment by Bnyro** [comment]
What are the written mistakes ("log out" instead of "logout"?) and which colour do you want to see changed?

**Comment by dhishkyaon** [comment]
the () at the end of the sentence
and the + sign is not visible

**Comment by lilcheti** [comment]
The () is for your username just logout and login again to see it!

**Comment by dhishkyaon** [comment]
oh. i didn't know that. sorry.
