### ISSUE TITLE
Hide Shorts videos.

### ISSUE THREAD

**Issue by Gencevi** [libre-tube/LibreTube#1521]
### Describe your suggested feature

Option to hide shorts videos.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by grappas** [comment]
How's that "not planned"? "Subscriptions" tab is swarmed by shorts. It's unusable.
