### ISSUE TITLE
Home tab empty

### ISSUE THREAD

**Issue by Screntinel** [libre-tube/LibreTube#1522]
### Steps to reproduce

Don't know

### Expected behavior

Instead of showing videos on my home tab

### Actual behavior

No videos show up

### LibreTube version

0.6.0

### Android version

Android 12

### Other details

I am logged on a piped account

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please try to change the region in the settings, trending is not available for some countries!

**Comment by Screntinel** [comment]
> Please try to change the region in the settings, trending is not available for some countries!

Thanks

**Comment by Screntinel** [comment]
> Please try to change the region in the settings, trending is not available for some countries!

Is there a way to get recommended videos based from your history like YouTube from your Piped account?

**Comment by Bnyro** [comment]
> Is there a way to get recommended videos based from your history like YouTube from your Piped account?
>

No, that's not possible and there are no plans to add something like that to LibreTube or Piped.
