### ISSUE TITLE
Picture in Picture Error

### ISSUE THREAD

**Issue by Guende** [libre-tube/LibreTube#1523]
### Steps to reproduce

1.Have An Xiaomi Phone
2.Use Open In Picture In The App
3.The Open With Error Appears

### Expected behavior

It Should Only Open The Video In Picture In Picture

### Actual behavior

But it just Opens The Pop Up with Open With

### LibreTube version

V.0.6.0

### Android version

Android 11

### Other details

![Screenshot_2022-10-08-17-31-25-367_com android systemui](https://user-images.githubusercontent.com/85771688/194731297-9a8e263f-558b-4fa9-ab1e-c2c51cd03264.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Guende** [comment]
>

**Comment by Bnyro** [comment]
Picture in Picture works, third party apps are not an issue of LibreTube?!
