### ISSUE TITLE
Add a timestamp feature when you copy link

### ISSUE THREAD

**Issue by Screntinel** [libre-tube/LibreTube#1524]
### Describe your suggested feature

Like YouTube, when you click share it tells you if you want to include a certain timestamp of the video, would be cool if that would be possible from YouTube or Piped links from the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The option to share with a timestamp is already available, it's just called "Share with time code".
