### ISSUE TITLE
Change how unexpected runtime errors are displayed

### ISSUE THREAD

**Issue by GilesMunn** [libre-tube/LibreTube#1525]
### Describe your suggested feature

Often when watching a video, you can get an "Unexpected runtime error" toast if there's a problem. This is unnecessarily complicated ("An error occurred" or even just "Error" would suffice and would give as much information as presently to a technical user, whilst not scaring a non-technical user as much) and from my experience often wouldn't need to be displayed at all. When this error is displayed, the video will pause, but almost always seems to play fine if the play button is pressed or the scrubber is moved to a different point of the video. The player could instead try pausing for a second or two before resuming, or rewinding one second before presenting the user with an error message.

### Other details

My current thinking is that this particular event occurs when a video is playing and the buffer isn't loading fast enough. The video gets to the point where it's got no more video buffered and throws an error. If this is the case, it would make more sense to either pause the video so the buffer can load more, or to show the loading icon.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The toast always shows when there occurs an internal error in the ExoPlayer, usually it indicates that there's either an issue with your network (e.g. you turned it off) or that there was an error fetching the stream source. The toast is meant to inform users that something went wrong and requires manual interaction to become "fixed", therefore I don't really think we should remove it.

**Comment by sant0s12** [comment]
I also frequently see this error message and find it very unnecessary, especially because, as @GilesMunn pointed out, the issue can always be "fixed" by pressing on the play button again.

I see how having an error messages for issues that cannot be resolved could make sense (but in that case, the error should be more precise in my opinion), but the player should retry to solve the issue multiple times before prompting the user.
