### ISSUE TITLE
Sharing link timestamp improvements

### ISSUE THREAD

**Issue by GilesMunn** [libre-tube/LibreTube#1526]
### Describe your suggested feature

Currently, if you go to share a link, the option to include the current timestamp is checked by default. I would suggest that this is changed to not checked by default, as I suspect most people want to share just the video most of the time. Furthermore, it'd be nice if, when the "include timestamp" option _is_ checked, that a text input appear to the right of the toggle, so that a user can manually specify a timestamp rather than having to scrub to that part of the video, hit pause in the right place, and then hit share.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Screntinel** [comment]
I find this unnecessary imo as it's not hard to pause at the right place of the video then click share
