### ISSUE TITLE
Simplify download notification

### ISSUE THREAD

**Issue by GilesMunn** [libre-tube/LibreTube#1528]
### Describe your suggested feature

At present, when downloading a video with audio, the notification shows as "2 files downloading" and has separate entries for both parts of the file. This is arguably unnecessary and over-complicated, it'd be nice if this were simplified to just the name of the video that is downloading.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by shantanu1k** [comment]
@Bnyro @GilesMunn Can I work on this?

**Comment by Bnyro** [comment]
> @Bnyro @GilesMunn Can I work on this?

Of course, I appreciate any help <3
