### ISSUE TITLE
[suggested feature] forcing quic,http2 state from settings for testing

### ISSUE THREAD

**Issue by eladkarako** [libre-tube/LibreTube#1539]
### Describe your suggested feature

when the pipe instance isn't fully proxying,  
apparently downloading directly by the client from g00gle servers is done using quic protocol which is throttled heavily.  

akaik no pipe instance exists with support http/3-quic yet,  
which makes their commination with both the client and google server over http/2,  
quic actually is pretty much never used..

that's all somewhat educated assumptions (please correct me if I'm wrong),  
some testing with forcibly blocking UDP:443 for all communications,  
shown a significant(!) performance boost in Libre-Tube downloading rate.  

ability to control both http/2 and quic independently would be greatly appreciated!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FireMasterK** [comment]
> akaik no pipe instance exists with support http/3-quic yet

The official instance is fully http/3 enabled.

**Comment by Bnyro** [comment]
Gonna close this as not planned as I don't think there would be benefits.
