### ISSUE TITLE
No notifications on Android 13

### ISSUE THREAD

**Issue by vighd** [libre-tube/LibreTube#1540]
### Steps to reproduce

1. Subcribe to a channel
2. Turn on "Notifications for new streams" under LibreTube settings
3. Wait for a content maker uploads a video

### Expected behavior

When a content maker uploads a video, send a notification about the new content

### Actual behavior

No notification at all and notification permission is greyed out in android settings, unable to turn on.
Screenshot: [here](https://ibb.co/Wc4k9G5)

### LibreTube version

0.6.0

### Android version

Android 13

### Other details

I using a Google Pixel 4a.

Or may I get some explanation how notifications should work? I don't see notification permission in LibreTube manifest.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I have the same issue since I updated to Android 13, I assume the new permission framework on Android 13 requires some additional permissions declared in the manifest. I'll need to search their docs for it.

**Comment by Bnyro** [comment]
Oh, yes: https://developer.android.com/develop/ui/views/notifications/notification-permission.
I'll add that until the next release.

**Comment by vighd** [comment]
> Oh, yes: https://developer.android.com/develop/ui/views/notifications/notification-permission. I'll add that until the next release.

Thanks! :)
