### ISSUE TITLE
Volume and screen brightness swipe control in fullscreen

### ISSUE THREAD

**Issue by hydromarc** [libre-tube/LibreTube#1541]
### Describe your suggested feature

When watching videos in fullscreen, it is useful to control volume and screen brightness without having to leave fullscreen mode. In other clients (e.g. the now deprecated Youtube vanced), this can be done by swiping either on the left or right side of the screen vertically to change volume or brightness settings. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Archeix7** [comment]
Good luck https://github.com/libre-tube/LibreTube/issues/545

**Comment by hydromarc** [comment]
The closed status explain why I didn't find the request. Sorry for the double post. Maybe, the then opinion has changed now...

**Comment by Archeix7** [comment]
I really hope that your request will be fulfilled. I still lack these functions, and the author does not even want to give a choice between enabling / disabling this function, in other words, "he doesn't need it - nobody needs it"

**Comment by Bnyro** [comment]
Well, we can keep the issue open, but I won't work on it.
For me, adding it is not worth my time since I wouldn't even use it. I'm adding features I like/I would use mainly since I'm doing all this stuff here in my free time and want to benefit from my work :)

**Comment by Archeix7** [comment]
Like i said

**Comment by hydromarc** [comment]
> I really hope that your request will be fulfilled. I still lack these functions, and the author does not even want to give a choice between enabling / disabling this function, in other words, "he doesn't need it - nobody needs it"

I didn't want to raise any demands. And as Bnyro said, I am happy to benefit from his efforts. If he doesn't consider this necessary, I am fine with it. I was just trying to give some idea as I find this feature very useful.

I am closing the issue. Of course, I am still happy, if this happens to come to life at some time.

**Comment by Archeix7** [comment]
Leave it open, maybe someone will do it (with a choice (on / off function))
