### ISSUE TITLE
Status bar not hide again

### ISSUE THREAD

**Issue by ghost** [libre-tube/LibreTube#1545]
### Steps to reproduce

1. Open Fullscreen
2. Tap to screen
3. Enjoy

### Expected behavior

A window with buttons opens (pauses, etc.) and disappears by itself

### Actual behavior

https://user-images.githubusercontent.com/51048550/195432368-f45c576b-1521-430a-8bd4-e931a373abc9.mp4

### LibreTube version

0.6.0

### Android version

A11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Dude you didn't wait for the video to start playing. It works well 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️

**Comment by akano12** [comment]
Dude, maybe wait for the video to start playing? 😂 🤦‍♂️


https://user-images.githubusercontent.com/50032603/195597118-be074797-15fd-4a7e-aaba-8c86b1fc2a41.mp4

**Comment by Archeix7** [comment]
> Dude, maybe wait for the video to start playing? 😂 🤦‍♂️

As u wish

https://user-images.githubusercontent.com/51048550/195739343-1daa8d81-4767-4f95-8993-f7fad0dec649.mp4
