### ISSUE TITLE
Click the button to open the window

### ISSUE THREAD

**Issue by Archeix7** [libre-tube/LibreTube#1546]
### Steps to reproduce

https://user-images.githubusercontent.com/51048550/195432947-ea6666b3-1e89-4502-9a02-2596ef5b5a14.mp4

### Expected behavior

Click on the button to immediately appear the functionality

### Actual behavior

Idk what to say

### LibreTube version

0.6.0

### Android version

A11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
1- That's not a bug, it's designed that way.
2- Honestly I like it the way it is, it's cool and i appreciate if it's kept as is.
3- You can always clone and modify the build the way you like (in case you don't like it)

**Comment by Bnyro** [comment]
I absolutely agree with @akano12!
If it was shown 100 per cent immediately, it would almost cover the whole screen and therefore the video wouldn't be visible anymore.
As it is currently, you can control its state as you want and apart from that I don't think it looks bad!

PS: @akano12 Thank you for taking care a bit of the issues, appreciate that <3

**Comment by Archeix7** [comment]
1. Bad shit, u use button ↓ to open settings, and u need open settings AGAIN, why? U press ↓, settings open, u do what u want and close, NO, U USE ↓, THEN SWYPE UP, THEN SETTINGS OPEN, U DO WHAT U WANT, THEN SWYPE DOWN CLOSE THIS SHIT, ARE U FUCKIN JOKE? 
2. I'm not a programmer, otherwise I would redo half of the functionality and not write reports. 
I like this app, but i think bryno crappy designer (which even the status bar can't subdue)
