### ISSUE TITLE
Sharing channel doesn't work

### ISSUE THREAD

**Issue by rozari0** [libre-tube/LibreTube#1549]
### Steps to reproduce

1. Go to any channel
2. Share it
3. Done

### Expected behavior

Should open channel

### Actual behavior

Libretube just add firstname of the channel after yt link. For example the channel link is https://piped.kavin.rocks/c/AbhiDattaTushar1510156 but libretube return https://piped.kavin.rocks/c/Abhi

### LibreTube version

1665663465 Debug

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Can you elaborate more? When sharing piped link you're facing this issue or i misunderstood? It seems that it works normally for me
