### ISSUE TITLE
Importing subscription doesn't work on libretube

### ISSUE THREAD

**Issue by rozari0** [libre-tube/LibreTube#1556]
### Steps to reproduce

1. Open Libretube
2. Go to Settings -> Instance -> Import Subscription
3. Select subscriptions.json file
4. Libretube will return 'something went wrong'

### Expected behavior

This should import subscribed channels.

### Actual behavior

Something went wrong.

### LibreTube version

0.6.1

### Android version

Android 9

### Other details

This things happend before, I just ignored and imported in piped web frontend. But I think it should also work in libretube too. 
I tried with and without account, same thing happened.

I can share my subscriptions.json if you want.

And this possibly will be a duplicate issue, sorry for that.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Yes, it would be great if you could share your `subscriptions.json` :)

**Comment by rozari0** [comment]
> Yes, it would be great if you could share your `subscriptions.json` :)

How should I share it?

**Comment by Bnyro** [comment]
Either upload it here or send it privately to me via Matrix (`@bnyro:matrix.org`)

**Comment by rozari0** [comment]
> Either upload it here or send it privately to me via Matrix (`@bnyro:matrix.org`)

Just did. :)

**Comment by m77e4t** [comment]
Yes it fails on my end too. 

From newpipe to libretube. Newpipe creates .zip instead of .json subscription backup. It gives the same error 'Something went wrong'.

I have also sent you my subscription newpipe .zip file to test it out on matrix personal room

**Comment by rozari0** [comment]
> Yes it fails on my end too.
> 
> From newpipe to libretube. Newpipe creates .zip instead of .json subscription backup. It gives the same error 'Something went wrong'.
> 
> I have also sent you my subscription newpipe .zip file to test it out on matrix personal room

Newpipe can export .json. You need to export subscription from Subscription tab, not full backup of newpipe. 😐

**Comment by m77e4t** [comment]
Correct :)

I messed up. I was trying to import the full backup instead of just subscription backup. The export feature for sub backup is hidden inside newpipe.

I have deleted my message on matrix.
My bad.

**Comment by justinfarrelldev** [comment]
I'm also having this issue. I just got my YouTube data from Takeout and when I go to import it, it says "Something went wrong". 

Even if it's a simple mistake, that error message should *definitely* get changed.

**Comment by rozari0** [comment]
> I'm also having this issue. I just got my YouTube data from Takeout and when I go to import it, it says "Something went wrong".
> 
> Even if it's a simple mistake I'm making, that error message should _definitely_ get changed.


Did you extract the zip file that YouTube gives you?

**Comment by justinfarrelldev** [comment]
> > I'm also having this issue. I just got my YouTube data from Takeout and when I go to import it, it says "Something went wrong".
> > 
> > Even if it's a simple mistake I'm making, that error message should _definitely_ get changed.
> 
> 
> Did you extract the zip file that YouTube gives you? 

Nope, I did not, and with that info I am now subbed to my usual creators (I unzipped and found the subscriptions data). Thank you!

**Comment by Kartereo** [comment]
Just wanted to come in and say that I had this happen to me. The way I fixed it was to complete delete data, only login to piped and not important a subscription list. The issue for me was that it let me login to piped and import a subscription list and it shouldn't be allowed to do both because they conflict

**Comment by Bnyro** [comment]
> @Bnyro As LibreTube supports piped, how about supporting piped json import ? This is my exported `json` template from https://pipedapi.kavin.rocks/
> 
Piped and LibreTube use a completely different system for preferences as Piped is a web and not an Android app, I don't think it would make any sense to put efforts in importing those preferences, they're not meant to be 100% compatible with each other.
Local subscriptions from Piped can already be imported by exporting them at the subscriptions tab at Piped so there's no need to support it a second time.

**Comment by akasaka99** [comment]
Error in exporting on Samsung S10+ on Android 11 and LG v30 on Android 8.

**Comment by moriel5** [comment]
I decided to look into this (not yet very deeply) since I had also encountered this bug (on a Razer Phone 2, running stock Android 9).

Regression testing did not help me, since all versions that have the import option actually do anything (without needing to log in) all fall in the same exact way, so I decided to do something else, and export a LibreTube subscription list and then try to re-import it.

The result, the same exact failure.

I believe that there is an issue with the import code in LibreTube, and NewPipe is entirely unrelated to this.

**Comment by FireMasterK** [comment]
> @Bnyro As LibreTube supports piped, how about supporting piped json import ? This is my exported `json` template from https://pipedapi.kavin.rocks/
> 
> ```
> {
> "selectedSkip":"sponsor,intro,outro,preview,interaction,selfpromo,music_offtopic",
> "homepage":"feed",
> "playerAutoPlay":"true",
> "minimizeRecommendations":"true",
> "sponsorblock":"true",
> "searchHistory":"false",
> "enabledCodecs":"vp9",
> "minimizeComments":"true",
> "watchHistory":"false",
> "theme":"dark",
> "showMarkers":"true",
> "hideWatched":"false",
> "bufferGoal":"25",
> "instance":"https://api-piped.mha.fi",
> "auth_instance_url":"https://pipedapi.kavin.rocks",
> "quality":"1080",
> "authToken<xxxxxxxx>":"<xxxxxxxx>",
> "hl":"en",
> "proxyLBRY":"false",
> "minimizeDescription":"false",
> "region":"US",
> "listen":"false",
> "authInstance":"false",
> "disableLBRY":"false",
> "localSubscriptions":"
> [\"UC2eYFnH61tmytImy1mTYvhA\",
> \"UC5UAwBUum7CPN5buc-_N1Fw\",
> \"UC7YOGHUfC1Tb6E4pudI9STA\",
> \"UCBJycsmduvYEL83R_U4JriQ\",
> \"UCMiJRAwDNSNzuYeN2uWa0pA\",
> \"UCl2mFZoRqjw_ELax4Yisf6w\",
> \"UCld68syR8Wi-GY_n4CaoJGA\",
> \"UCmyGZ0689ODyReHw3rsKLtQ\",
> \"UCoryWpk4QVYKFCJul9KBdyw\",
> \"UCs6KfncB4OV6Vug4o_bzijg\",
> \"UCtMVHI3AJD4Qk4hcbZnI9ZQ\"]"
> }
> ```
> 
> Not just local subscriptions, you can also utilize those other fields, that might tweak app settings as per piped web.

You'll have to export it from https://piped.video/subscriptions and click the export button

**Comment by FireMasterK** [comment]
> > You'll have to export it from https://piped.video/subscriptions and click the export button
> 
> @FireMasterK Bruh. That json text you just quoted, is from my piped subscription export...O_o

I don't think so, that format is only sent when you go to the preferences and click on the backup button.

The format of the file from the link I sent is very different.

**Comment by rozari0** [comment]
Tested with new debug, It now says 'Unsupported file format!', but I just exported the subscription file. :(

**Comment by Bnyro** [comment]
> Tested with new debug, It now says 'Unsupported file format!', but I just exported the subscription file. :(
> 
Thanks for testing, I might have an idea then! I'll make it show what it detected as file type as well tomorrow, then we might be able to solve it by just allowing that file type :)

**Comment by Bnyro** [comment]
So it's actually a good message that that's the error message and not something different :)

**Comment by FireMasterK** [comment]
> Tested with new debug, It now says 'Unsupported file format!', but I just exported the subscription file. :(

Where did you export it from?

**Comment by rozari0** [comment]
> > Tested with new debug, It now says 'Unsupported file format!', but I just exported the subscription file. :(
> 
> Where did you export it from?

Both Libretube and Newpipe, It's same. 
Libretube -> Settings -> Instance -> Export Subscriptions
Newpipe -> Subscriptions -> Export To -> File

**Comment by Bnyro** [comment]
It's logging the determined file type now, could you please test the latest debug build (once it's finished) and give feedback what it shows? Thanks!

**Comment by Bnyro** [comment]
Could you please test it now? In theory it should work now, if it doesn't I've no idea ...

**Comment by rozari0** [comment]
> Could you please test it now? In theory it should work now, if it doesn't I've no idea ...

It's working.
Thanks! :p
