### ISSUE TITLE
Force quit, can't start APP.

### ISSUE THREAD

**Issue by nanedi** [libre-tube/LibreTube#1557]
### Steps to reproduce

Force quit, can't start APP. v0.6.1 on Sony 1 III.

### Expected behavior

When I try to open this app and it force quit, can't start APP. v0.6.1 on Sony 1 III.

### Actual behavior

When I try to open this app and it force quit, can't start APP. v0.6.1 on Sony 1 III.

### LibreTube version

0.6.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by rozari0** [comment]
Check pinned issue.

**Comment by Bnyro** [comment]
Please delete the app data!

**Comment by nanedi** [comment]
> Please delete the app data!

Done

Thanks
