### ISSUE TITLE
Network Error after installation and is persistent

### ISSUE THREAD

**Issue by LovecraftianGodsKiller** [libre-tube/LibreTube#1559]
### Steps to reproduce

1. Download and install application
2. Launch the application

### Expected behavior

No connection error and have everything load properly

### Actual behavior

I open up the app and immediately get a toast pop-up saying "Network Error" 

### LibreTube version

0.6.1

### Android version

Android 12(L) (Don't know if the"L" is important or not

### Other details

I have download and installed the app from F-Droid then tried downloading the app from GitHub to see if that would do anything but it didn't, I still got the same error

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Could you please try changing the instance? There were no changes in the code that potentially caused such an issue in the latest update, so I assume the instance you're using has an issue.
