### ISSUE TITLE
[REDESIGN] Playlist tab redesign

### ISSUE THREAD

**Issue by martin-desktops** [libre-tube/LibreTube#157]
![image](https://user-images.githubusercontent.com/64419373/166436006-e7ee511f-50d7-47bb-af0a-502adae2ad22.png)

**Comment by Bnyro** [comment]
Looks nice, good idea. You made the picture with sth like Photoshop?

**Comment by Bnyro** [comment]
Otherwise you could make a pr

**Comment by martin-desktops** [comment]
Yeah, unfortunately I don’t have coding skills, so it’s only a project inside https://www.figma.com/

**Comment by lilcheti** [comment]
could you share the figma link to it

**Comment by martin-desktops** [comment]
Here you are https://www.figma.com/file/9IYgFzyNKITtWxBwYNACqG/Untitled?node-id=1%3A33
Keep in mind that it is just an image with additional layers, not a full, responsive layout.

**Comment by Bnyro** [comment]
Why did you mark it as bug btw? It looks like a feature request to me :)

**Comment by Bnyro** [comment]
I'm gonna try to implement it btw, but can't promise anything :)
Hope I'll get it work

**Comment by martin-desktops** [comment]
> Why did you mark it as bug btw? It looks like a feature request to me :)

Feel free to swap it, It requires the Contributor role

**Comment by martin-desktops** [comment]
> I'm gonna try to implement it btw, but can't promise anything :)
> Hope I'll get it work

Good luck!

**Comment by Bnyro** [comment]
Functionality is done so far, gonna change the design if I find time for it
