### ISSUE TITLE
The settings card is visible in the PiP mode if it was opened before going to the home screen 

### ISSUE THREAD

**Issue by yhm4ps1jfp67nkv** [libre-tube/LibreTube#1570]
### Steps to reproduce

1. Open a video
2. Go to full screen mode
3. Tap the down arrow to open the settings card
4. Go to the system home screen
5. The video will continue playing in the PiP mode

### Expected behavior

The video should be shown normally

### Actual behavior

The settings card is shown in the PiP mode and covers some part of the playing video

### LibreTube version

Latest Debug

### Android version

Android 12

### Other details

The settings from the card cannot be accessed in PiP mode in case that behavior is intended

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Could you please provide a screen recording to make it easier to understand the issue? Thanks!

**Comment by akano12** [comment]
> Could you please provide a screen recording to make it easier to understand the issue? Thanks!

https://user-images.githubusercontent.com/50032603/196058114-978ec058-bdb3-4f94-b15e-7df7cf79bd12.mp4

**Comment by yhm4ps1jfp67nkv** [comment]
Thanks, @akano12, that is what I'm talking about
