### ISSUE TITLE
Navigation buttons get stuck when tapping on fullscreen video on Motorola device

### ISSUE THREAD

**Issue by Pentaphon** [libre-tube/LibreTube#1572]
### Steps to reproduce

1. Play fullscreen video on Moto G Pure device (this is on a clean install of Libretube)
2. Tap the video while it's playing
3. See that navigation buttons get stuck on the video while its playing

### Expected behavior

I expect not to see the navigation buttons while fullscreen video plays until I swipe from that area to expose them.

### Actual behavior

The navigation buttons get stuck while playing fullscreen video and tapping the screen. See the screen recording of the behavior below. This happens on all videos. 

### LibreTube version

0.6.1

### Android version

Android 11 Stock ROM Motorola G Pure

### Other details

https://user-images.githubusercontent.com/49374058/196053512-458e69a8-4452-4beb-8a1d-8d59e73026af.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
@pentaphon can you try switching to full screen view after the video start playing?

**Comment by Pentaphon** [comment]
> can you try switching to full screen view after the video start playing?

The navigation bar gets stuck even when I do that. It just does it no matter how I play the video. Fullscreen is totally ruined by the stuck navigation buttons no matter what i do. As soon as I touch the screen on fullscreen, the buttons appear and get stuck.

**Comment by Pentaphon** [comment]
Where's the latest builds? I can't find anything on the readme.

**Comment by Bnyro** [comment]
Usually [here](https://github.com/libre-tube/LibreTube/actions) but they seem to be broken atm (builds fine on my local machine though)

**Comment by Pentaphon** [comment]
This is still an issue on 0.7.0 where they appear and get stuck until you tap twice or sometimes even 3 times as you can see from my video with taps being shown on the screen.

https://user-images.githubusercontent.com/49374058/198880381-df06afe8-7d32-4595-8734-2cee077fa443.mp4

 This is on a clean install just to make sure.

**Comment by Bnyro** [comment]
It hides now when the player controls hide as well, so it's not a that big issue anymore as it can be hidden ...

**Comment by Pentaphon** [comment]
But we do we really need the navigation buttons to show in fullscreen at all when we can just press the fullscreen button to leave fullscreen mode? I'd prefer not to see the navigation buttons at all no matter how many times I tap the screen because I can just use the fullscreen button.

**Comment by Bnyro** [comment]
Well, we don't show it manually Android does so automatically when you click on the screen. If we forced hiding it immediately after the player controls are shown you would neither be able to access the navigation bar at all anymore nor a clean transition of the navigation bar.

**Comment by Pentaphon** [comment]
Fair enough. It just seems a bit difficult to get rid of now but I guess I have to live with that over not being able to get rid of it at all.
