### ISSUE TITLE
subtitles no longer displayed if a specific resolution is selected

### ISSUE THREAD

**Issue by luca-e075e** [libre-tube/LibreTube#1573]
### Steps to reproduce

1. Set video resolution to anything but auto
2. Set subtitle default language (eg english)
3. Play a video with sub

### Expected behavior

Sub are displayed

### Actual behavior

Sub are not displayed, even if switching them off and on from quick setting or changing to another language

No issue if quality is auto (HLS)

### LibreTube version

0.6.1

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by zkzmba793** [comment]
The same happens on 0.7.1, Android 12.

**Comment by Bnyro** [comment]
fixed by #1867
