### ISSUE TITLE
#Shorts do not play in vertical fullscreen when auto-fullscreen is enabled

### ISSUE THREAD

**Issue by Pentaphon** [libre-tube/LibreTube#1576]
### Steps to reproduce

1. Do a clean install of Libretube
2. Enable "Auto-Fullscreen when the device is turned"
3. Play any Shorts video while holding the phone vertifcally
4. See that the Shorts video doesn't fullscreen and there's no button to fullscreen
5. The Short video is now stuck in the vertical player with with info mode instead of going fullscreen automatically OR with the manual fullscreen button which doesn't exist...

### Expected behavior

I expect shorts to automatically go fullscreen (or at least have the player go into vertical fullscreen mode) when holding the phone vertically after enabling "Auto-Fullscreen when the device is turned". After all, the phone is being held vertically and the short is being recognized as a short so it should be smart enough to go into a fullscreen (or vertical fullscreen player mode) when the short video starts playing.  

### Actual behavior

The Shorts video just gets stuck in vertical player mode instead of going fullscreen when played and it doesn't have a manual fullscreen button either after "Auto-Fullscreen when the device is turned" is enabled. 

### LibreTube version

0.6.1

### Android version

Android 11 Stock ROM Motorola G Pure

### Other details

N/A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's impossible to solve unfortunately. When using the auto-fullscreen option, the app rotates according to your devices orientation. If we force-change the orientation inside the app to be vertical and thus play shorts, auto-fullscreen won't work anymore as the app can't follow your device's rotation anymore since we forced it to be in portrait.
