### ISSUE TITLE
Light version of Default icon for dark backgrounds?

### ISSUE THREAD

**Issue by Pentaphon** [libre-tube/LibreTube#1582]
### Describe your suggested feature

It would be nice to have a light version of the default icon for people with dark wallpapers so the icon looks better and more distinct against a dark background instead of blending in too much. 

### Other details

N/A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We'd need @XelXen to create a light version of the icon then, not sure whether he is interested in doing so though
In my opinion, a light logo wouldn't nearly look as good as the current one so not really sure about that one!

**Comment by Pentaphon** [comment]
> a light logo wouldn't nearly look as good as the current one

Maybe not but at least it would look better on phones with dark wallpaper. I tried using the other icons and none of them really worked as well as the default icon so making a light version would cover all use cases.

**Comment by xIUPITERx** [comment]
Is there already support for the 2-colour app icons from Android 13?

**Comment by Bnyro** [comment]
> Is there already support for the 2-colour app icons from Android 13?

Yes, I already added that as I'm on A13 ;)

**Comment by xIUPITERx** [comment]
Is there a way to download the icons (in .ico format) individually?

**Comment by XelXen** [comment]
Ooh, not a bad idea. Lemme see what can I do

**Comment by Bnyro** [comment]
> Is there a way to download the icons (in .ico format) individually?
Anything I got:
[Icons.zip](https://github.com/libre-tube/LibreTube/files/9844605/Icons.zip)

**Comment by xIUPITERx** [comment]
1. Would it be too difficult to have a white background for all the icons?
2. The new white default icon is just black and white, why was the red color removed? I thought that only the background of the icon should be changed.

**Comment by Bnyro** [comment]
1. That would increase the app size a lot, so yes
2. Just because it looks better than the normal one on a light background.

**Comment by xIUPITERx** [comment]
1. Could they be downloaded from GitHub or somethink like that if they are selected?

**Comment by xIUPITERx** [comment]
Could the background of this icon be changed? You can't really see the tip because of the black background.

**Comment by Bnyro** [comment]
No, they can't be loaded dynamically unfortunately.
