### ISSUE TITLE
`Source Error`

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#1593]
### Steps to reproduce

Play any video

### Expected behavior

Should play normally

### Actual behavior

Throws `Souce Error` on every single video.

> All the thumbnails are loading fine.

<details><summary>Show Screenshot</summary>

![Screenshot_20221019-095245](https://user-images.githubusercontent.com/87353286/196597449-7ada64b2-74e8-41c8-bade-dfe508d5bb9b.png)

</details>
<details><summary>Another Error</summary>

![Screenshot_20221019-101858~3](https://user-images.githubusercontent.com/87353286/196601049-f0db1d2d-daf2-40df-a91b-b96492ef5ed5.png)

</details>

### LibreTube version

0.6.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's an instance issue obviously!

**Comment by VedxP** [comment]
> That's an instance issue obviously!

@Bnyro I've tried playing the same video on same instance on both Piped and LT. (did this many times whenever I got Source Error on LT)

Piped one is playing perfectly fine, every time I tried.
That's why I'm worried.

And, I encountered one more error.

See [here](https://user-images.githubusercontent.com/87353286/196601049-f0db1d2d-daf2-40df-a91b-b96492ef5ed5.png)

**Comment by Bnyro** [comment]
Are you using the "Auto" resolution?

**Comment by VedxP** [comment]
> Are you using the "Auto" resolution?

No, I've set quality to 144p from settings

**Comment by Bnyro** [comment]
> No, I've set quality to 144p from settings
>
That's probably the issue then, it seems like there are some issues with other resolutions that auto, not sure why though. I recommend using `Auto` for now as it's the most stable one at the moment.

**Comment by VedxP** [comment]
> > No, I've set quality to 144p from settings
> 
> That's probably the issue then, it seems like there are some issues with other resolutions that auto, not sure why though. I recommend using `Auto` for now as it's the most stable one at the moment.

Hmm

Have seen such issue in one more app, didn't remember now.

But the issue was:

- You've set default quality to 480p.
- When you play a video which doesn't have that quality available to be streamed, the player crahses or throws error.

The same is happening with LT.

The solution is, if the video is not streamable at the preferred quality set in the settings, fallback the video to any other resolution, let say at the lowest quality the video is streamable at; or to the highest one.

**Comment by VedxP** [comment]
> > > No, I've set quality to 144p from settings
> > 
> > 
> > That's probably the issue then, it seems like there are some issues with other resolutions that auto, not sure why though. I recommend using `Auto` for now as it's the most stable one at the moment.
> 
> Hmm
> 
> Have seen such issue in one more app, didn't remember the app name now.
> 
> But the issue was:
> 
> * Let say you've set the default quality to 480p.
> * When you play a video which doesn't have that quality available to be streamed, the player crahses or throws error.
> 
> The same is happening with LT.
> 
> The solution is, if the video is not streamable at the preferred quality set in the settings, fallback the video to any other resolution, either to the lowest quality the video is streamable at, or to the highest one.

@Bnyro have a look at it bro ☝️

**Comment by ildar** [comment]
This is indeed the quality setting problem.
End user doesn't understand such behavior. Please fix:
1. Either change to some other nearest quality
2. or at least change the message to: Video is not available in YOUR DESIRED quality.

Also please reopen the issue. @Bnyro
