### ISSUE TITLE
Alternate Subscription Layout

### ISSUE THREAD

**Issue by GET100PERCENT** [libre-tube/LibreTube#1594]
### Describe your suggested feature

There should an alternative subscription layout similar to alternate feeds layout.

### Other details

The current subscription layout contains 2 to 3 videos in a single view.
If an alternate layout is made for subscriptions just as it was recently done for feeds, it would be very helpful.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by VedxP** [comment]
Yeah, that would look better too cuz thumbnails are blurry.

And the same alternate layout for watch page (video page).

**Comment by GET100PERCENT** [comment]
Yes , which will be data friendly, and also be very beautiful.
It will also look better in small mobile screens.

**Comment by GET100PERCENT** [comment]
And the suggestion is not to replace the current layout, it is to provide an alternative layout to choose.

**Comment by Bnyro** [comment]
So rather a toggle to change the layout for everything at once or an option to choose it manually for each layout?

**Comment by GET100PERCENT** [comment]
Toggle to change the layout for every thing at once is better.

**Comment by VedxP** [comment]
> Toggle to change the layout for every thing at once is better.

+
