### ISSUE TITLE
Images not appearing properly

### ISSUE THREAD

**Issue by mjain234** [libre-tube/LibreTube#1595]
### Steps to reproduce

I find most of the image or say all the images blurry while on a home page, also in the bottom while playing video. Is it due to the instance i am using (i have chosen adminforge.de) or is device issye? I dont have anyidea that is why pointing out😅. 

Check this video:
https://user-images.githubusercontent.com/70900505/196677466-a29a5016-99f8-4cca-833f-7db6a0a8d2c5.mp4

### Expected behavior

NIL

### Actual behavior

NIL

### LibreTube version

0.6.1

### Android version

Android 10

### Other details

Device - Realme 2 Pro

Android version - Android 10

ROM - Stock

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
see #1578

**Comment by mjain234** [comment]
Ok, but yaah not a big issue though.
