### ISSUE TITLE
hide channel information

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#1596]
### Describe your suggested feature

You should be able to hide the channel information like the comments.

![signal-2022-10-19-135904_003](https://user-images.githubusercontent.com/97352673/196699324-197702d4-5c6a-4a1a-beea-8209419c32fa.jpeg)

Some channels have an extremely long info text and if you just want to watch the videos, it's getting in the way.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
1. I like the new design very much, but could you add a little arrow or "more..." to indicate that you can expand the text?
2. Since the "Kanäle" tab is empty, it could be hidden (every empty tab could be hidden).

**Comment by Bnyro** [comment]
> 1. I like the new design very much, but could you add a little arrow or "more..." to indicate that you can expand the text?
>
I don't think it would look good, you can already spot when the text ends with `...`

> 2. Since the "Kanäle" tab is empty, it could be hidden (every empty tab could be hidden).
That's a bug in the NewPipe Extractor as channel tabs are still in beta :)

**Comment by xIUPITERx** [comment]
1. Oh, I didn't even notice that there were "...". Could they perhaps have a little more space between them and the text, be bold or a little bigger?
