### ISSUE TITLE
Item Partially Visible

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#1597]
### Steps to reproduce

1. Play any video
2. Open any playlist
3. Scroll down to the end
4. The last video gets beneath the miniplayer and only upper half of the last video can be seen.

### Expected behavior

The last video too should be visible completely.

### Actual behavior

But, it gets covered by the miniplayer.

Reference Image:
![Screenshot_20221019-183658~3](https://user-images.githubusercontent.com/87353286/196701719-744ab2d4-bf9f-4d73-9d1a-6a5eecfbf850.png)

### LibreTube version

0.6.1

### Android version

Android 12

### Other details

The same happens when you visit library tab and scroll down to the end.

> You should have playlists that cover entire screen to see the issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by VedxP** [comment]
@Bnyro 
- Still persists in `0.7.0`

Screenshot:
> ![Screenshot_20221030-183936~2](https://user-images.githubusercontent.com/87353286/198880256-fdee1328-0966-475e-813e-19e1bdf1fb57.png)

**Comment by Bnyro** [comment]
Can't reproduce:
![Screenshot_20221031-213740_LibreTube.png](https://user-images.githubusercontent.com/82752168/199105741-e148d008-5976-4c32-a6cd-e79ea524aec6.png)

**Comment by VedxP** [comment]
> Can't reproduce @Bnyro 

Tried reinstalling, still not solved:

![Screenshot_20221101-083747](https://user-images.githubusercontent.com/87353286/199150459-92bcf395-4c47-4d02-a5e8-f7f2294be60d.png)

**Comment by VedxP** [comment]
@Bnyro Even I can reproduce it in latest debug version:
> ![Screenshot_20221107-104107](https://user-images.githubusercontent.com/87353286/200231230-feb6fd8b-3d93-4a38-a376-3b21bcdd61d8.png)

**Comment by xIUPITERx** [comment]
@Bnyro Still not fixed in the latest debug.
![Screenshot_20221112-224811_LibreTube Debug.jpg](https://user-images.githubusercontent.com/97352673/201495864-84d550e7-53ea-4654-9b77-db5c7d2714ea.jpg)

**Comment by Bnyro** [comment]
Well, for me it is fixed!

**Comment by VedxP** [comment]
> Well, for me it is fixed!

Strange 😶
