### ISSUE TITLE
false "server reports difficulties" notification

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#1598]
### Steps to reproduce

Even if I have perfect internet the app stills displays the notification "server reports difficulties" every time I click on the subscription feed button.

https://user-images.githubusercontent.com/97352673/196703834-2c82f0a0-4453-4310-9839-9bb61f3e59ac.mp4

### Expected behavior

If you have a poor internet connection you should get the notification.

### Actual behavior

You get the notification all the time.

### LibreTube version

0.6.1

### Android version

Android 12 One UI 4.1

### Other details

Maybe add an option to deactivate the notification.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Hmm, no idea why that happens, is there any specific way it can be reproduced? That would make it easier to just disable the notification in that specific case.

**Comment by xIUPITERx** [comment]
For me it is everytime I click on the subcriptuons feed button.
