### ISSUE TITLE
Searchbar problems

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#1599]
### Steps to reproduce

The search is extremely inconsistent.

Sometimes you need 4 back gestures to close the searchbar, which should only be 2 (1. close keyboard, 2. close search)

https://user-images.githubusercontent.com/97352673/196717841-6c011a7d-aa2a-4236-a4ec-76bf50289a1f.mp4

Sometimes the searchbar closes with no reason and doesn't open again if you go back.

https://user-images.githubusercontent.com/97352673/196718320-36c3a082-1618-4b22-917e-30f54b2490b4.mp4

### Expected behavior

The back gesture should close the search history and searchbar simultaneously and if you go back from the search results, you should be on the Homescreen or at the last search result not at the search history.

https://user-images.githubusercontent.com/97352673/196722183-6427ccc8-8992-4b13-a5d4-baf1f300cdf9.mp4

### Actual behavior

As shown above

### LibreTube version

0.6.1

### Android version

Android 12 One UI 4.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
Not yet fixed, if you search multiple tines, you should go to the last search result, but the searchbar closes.
https://user-images.githubusercontent.com/97352673/203166186-3ba8f410-0a4f-48f9-a61c-1e896902d712.mp4

**Comment by xIUPITERx** [comment]
https://user-images.githubusercontent.com/97352673/203166606-d892e1b2-9278-4e32-a2a3-277d7367f5b5.mp4

**Comment by xIUPITERx** [comment]
@Bnyro
Nearly but not yet, if you search multiple times, you should go back to the last search result, instead the searchbar closes.

https://user-images.githubusercontent.com/97352673/203166606-d892e1b2-9278-4e32-a2a3-277d7367f5b5.mp4

**Comment by xIUPITERx** [comment]
@Bnyro 
I found a second situation that is not yet covered, if the search was opened and the app is a few minutes in the background, the searchbar is closed when you return. 
Maybe another case of the genius android recourse management.

**Comment by xIUPITERx** [comment]
> I found a second situation that is not yet covered, if the search was opened and the app is a few minutes in the background, ... 

I'm not sure if all the issues related to certain objects no longer loading in the background should be addressed individually or all related issues at once (, ...).

**Comment by Bnyro** [comment]
Hmm, no clue about that, I don't really have much of an idea of the Android life cycle stuff and all that. I think it's better to just keep things separated and wait for someone with knowledge to notice the `help wanted` label ;)

**Comment by xIUPITERx** [comment]
@Bnyro 
>Nearly but not yet, if you search multiple times, you should go back to the last search result, instead the searchbar closes.

Could you fix this?

> and wait for someone with knowledge to notice the help wanted label ;)

I don't think someone would notice it, if the issue remains closed

**Comment by xIUPITERx** [comment]
If I spam to many Issues post let me know :)

**Comment by Bnyro** [comment]
I think opening a new issue would be good since the current one is not easy to overview for newcomers :)
