### ISSUE TITLE
[BUG] Unexpected behavior in video player

### ISSUE THREAD

**Issue by laraib07** [libre-tube/LibreTube#16]
Whenever I play any video, I encounter following issues:
1. Video plays in portrait mode.
2. If you touch blank area below video in video player, it triggers actions as if there are some hidden elements there. My guess is when you go in portrait mode, it just hides next video suggestions but it is still active and responds to touches.
3. The video player does not acquire wakelock. Hence goes to sleep after some time.

To reproduce the bug:
1. Open any video and tap full screen option on bottom right.
2. Now you are in portrait mode.
3. Tab on the lower white part of screen. Next video will play. If you tab just below video, the channel page will open.
4. Leave video playing for sometime and the screen will go off.

**Comment by rimthekid** [comment]
I suppose there is still some problem with the player layout that it triggers the background elements and for the screen turning off I'll try to fix it in the next commit, the player needs a lot of work as my main focus is on making subscriptions work rn but I'll come back to it after that's finished and build player from ground up.

**Comment by rimthekid** [comment]
Fixed both issues in this [commit](https://github.com/libre-tube/LibreTube/commit/f11e1b276cefb885e5c927b330049529474fd06b)
