### ISSUE TITLE
Material You design changes

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#1600]
### Describe your suggested feature

Why was the Material You design changed?
> Improved Material themes by @Bnyro in https://github.com/libre-tube/LibreTube/pull/1381

Now the subscription button has a different color than all the other buttons and the navbar in the app and is harder to see.
![1635108fe9b5fde758b0b83d67d87cdb5b30b19f0f71ec25872ffd91bd60eb78](https://user-images.githubusercontent.com/97352673/196734138-ff6f1419-c128-4491-b5e7-dc8d64983527.jpg)
New

![651b3667b3dc2558f6dd9783d3c80c0bd591d331aec0193b942a1da424eb9f1e](https://user-images.githubusercontent.com/97352673/196734168-52c79159-5ac9-49f7-93a5-28fcc2f9165e.jpg)
Old

![254ec3176738fb98e1fb6d541b74ac68a9a42e15e28e9f5c32cf65ccd44d214a](https://user-images.githubusercontent.com/97352673/196734380-86dba952-eea4-4956-a9cd-311758106f91.jpg)
New

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The change was actually made in https://github.com/libre-tube/LibreTube/pull/1464 by @GilesMunn because in his opinion the previous elevation was just too much which I agree with.
