### ISSUE TITLE
Notification sometimes gets freezed

### ISSUE THREAD

**Issue by mjain234** [libre-tube/LibreTube#1601]
### Steps to reproduce
I was watching a video and then, i exited from the app for sometime and when i returned back, the video i was playing was gone but the notification was still there and no response then.

But when i start playing the same video, then it back to normal and working fine.

Check this out:
https://drive.google.com/file/d/18H2kwUWbSJctASu50sjfUz3xLnKnrbnO/view

### Expected behavior

nil

### Actual behavior

nil

### LibreTube version

0.6.1

### Android version

Android 10

### Other details

Offtopic: sorry to share via drive as everytime i upload video, it says "low memory". I hope you understand:⁠-⁠)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please provide another source for the video, upload it here or describe the issue further!

**Comment by mjain234** [comment]
> Please provide another source for the video, upload it here or describe the issue further!

Check this: https://user-images.githubusercontent.com/70900505/196790244-cdb97def-afb0-4519-9c23-461420fdf689.mp4

**Comment by mjain234** [comment]
Can you able to access this
 https://user-images.githubusercontent.com/70900505/197011597-a7ea8635-a0b7-4ad6-b8d5-189228b6023e.mp4

**Comment by Bnyro** [comment]
Not either unfortunately, in the worst case I'm just gonna access the video from Drive with Tor...

**Comment by akano12** [comment]
> Not either unfortunately, in the worst case I'm just gonna access the video from Drive with Tor...

Isn't this a duplicate isssue? I remember reading a similar problem when leaving the app for some time then trying to resume playing. Can't find tho, migjt be wrong

**Comment by akano12** [comment]
> Not either unfortunately, in the worst case I'm just gonna access the video from Drive with Tor...

https://user-images.githubusercontent.com/50032603/197068347-31ecf170-d1e8-4850-94d6-b02ecfbb7ed6.mp4

**Comment by Kruna1Pate1** [comment]
### Another way to reproduce this issue,

1. Play any video
2. Go in PiP mode (i.e. by pressing Home button)
3. Remove PiP screen
4. Notification is still there, can't interact with it, as OP said it's freezed
Also, app is not in a recent screen (at least for me)

### Screen recording for the same,

https://user-images.githubusercontent.com/33123061/204289648-45692254-ea22-4f6b-9fab-cecfe654848d.mp4



### Libretube Version
0.8.0 Debug

### Android version
Android 12

**Comment by Bnyro** [comment]
I've had the same issue as well in the last days sometimes. We will probably need to somehow listen for the app to be closed and then kill the notification of the player, but unfortunately I couldn't find a way for that as it doesn't seem to be possible with Android.

**Comment by Kruna1Pate1** [comment]
This is a bit weird after reinstalling I was unable to reproduce this issue. But, once I used `Audio` mode, This issue started again. even after restarting the app.
