### ISSUE TITLE
SponserBlock Not working 

### ISSUE THREAD

**Issue by mjain234** [libre-tube/LibreTube#1602]
### Steps to reproduce

Here, in this video, you can see a person talking about an app, but this segment doesnt get skipped though my all the settings for SponserBlock are enabled. I also saw the other videos, there it can easily skip the videos.  Is this a issue of source?

Check the video:
https://drive.google.com/file/d/18H2kwUWbSJctASu50sjfUz3xLnKnrbnO/view

### Expected behavior

Nil

### Actual behavior

Nil

### LibreTube version

0.6.1

### Android version

Android 10

### Other details

Device - Realme 2 Pro

Android version - Android 10

ROM - Stock

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
True, the app just uses the official SponsorBlock API, that's not our issue then ...
Apart from that please refrain from uploading videos on Google Drive when reporting issues here, at least I won't have a look at them!

**Comment by mjain234** [comment]
Understood, will keep in mind😀
