### ISSUE TITLE
Nav Bar Animation Issue

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#1618]
### Steps to reproduce

1. Play any video
2. Swipe down the player
3. The nav bar first slides down, then slides up to be visible.

### Expected behavior

The navbar should be sliding up as the player slides down, respect to each other.

### Actual behavior

But, the current implementation leads the nav bar to first slide down, then slide up.

### LibreTube version

0.6.1

### Android version

Android 12

### Other details

Reference GIF:
![ezgif-2-71b78e5955](https://user-images.githubusercontent.com/87353286/196874081-c2d196bc-6820-4525-bedd-6184f1c17305.gif)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Those animations are quite hard to handle and I don't think changing that is really possible. Apart from that I don't feel like that's an issue though as it just works fine and doesn't look to bad!

**Comment by VedxP** [comment]
> Those animations are quite hard to handle and I don't think changing that is really possible. Apart from that I don't feel like that's an issue though as it just works fine and doesn't look to bad!

I agree, but it gets me confused sometimes if it's going to be visible or hidden :(

But, thanks for checking it out :)

**Comment by xIUPITERx** [comment]
If yes and it isn't to difficult, I would try to implement it.

**Comment by Bnyro** [comment]
I doubt you would have success with it as the other app is probably written in Jetpack Compose.
If you make it work I'd prefer the code rather to be rewritten or taken as example than copied one by one but for that it'd need to work first anyways.

**Comment by xIUPITERx** [comment]
I will try it even if i almost no chance of success.
Where can I find the package for the NavBar?

The app I want to copy from is: https://github.com/accrescent/accrescent
