### ISSUE TITLE
Skipping Russian Channels

### ISSUE THREAD

**Issue by XenoBIT78** [libre-tube/LibreTube#1621]
### Steps to reproduce

Hi :)
im using Newest Libretube from F-Droid on a OnePlus Nord 5G running Android 11 OxygenOS..
Logged in to piped.garudalinux.org

if i try to watch a channel like Inside Russia it plays for a couple of seconds and then skips..  or it refuses to play video.. 
what is up ??  i can play it on https://piped.garudalinux.org/watch?v=0NOxqwVrYCc no problem.. so i guess it has nothing to do with piped..

Is Libretube banning russian channels ?

### Expected behavior

it should play

### Actual behavior

it skips after a couple of secs or doesn't play at all and just says source error

### LibreTube version

0.6.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
No, I don't mix in into any political stuff, I'd never ban any content from LT ...
The toast either shows you that you lost internet connection or there was an error fetching the video stream source. I'd always recommend using the "Auto" resolution!

**Comment by xIUPITERx** [comment]
Is sponserblock active? Somebody could have false reported it as advertisment.
