### ISSUE TITLE
Duplicate Resolution in Quality Selection

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#1622]
### Steps to reproduce

It appears on random videos.
Can't be reproduced intentionally until you know exactly which video have this duplicate resolution.

### Expected behavior

It should display only a single option for same quality.

I guess it's something related to different FPS quality available for the same resolution.

### Actual behavior

It ahows two options for the same resolution.

### LibreTube version

0.6.1

### Android version

Android 12

### Other details

Screenshot showing two 720p quality:

![Screenshot_20221020-123619](https://user-images.githubusercontent.com/87353286/196912044-defc847b-d6a8-4626-92fc-ceee06b53804.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Yes, there are sometimes different fps available, but why is that an issue though?

**Comment by Bnyro** [comment]
> Hmm, how about moving the two options of same quality together?
> 
You mean just sorting them?

**Comment by VedxP** [comment]
> > Hmm, how about moving the two options of same quality together?
> 
> You mean just sorting them?

Yeah, so that 720p and 720p60 both would be together.

Reference issue: [View](https://github.com/SongTube/SongTube-App/issues/86)
