### ISSUE TITLE
Top Bar Tweak

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#1624]
##### It would be nice to have a `Settings` button beside `Search` button.

> Somewhat like this:

<details><summary>Show</summary>

![Screenshot_20221020-194140~2](https://user-images.githubusercontent.com/87353286/196961713-148bb76b-da7b-4ef9-b1d2-a5c8cafe062d.png)

</details>

##### And `Community` and `About` sections inside settings page after or before version updater button.

<details><summary>Show</summary>

![Screenshot_20221020-194148~2](https://user-images.githubusercontent.com/87353286/196961638-c7ce086c-c207-4f85-af51-e93223fda2dd.png)

</details>

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
> Out of context:
> How did you add those "show" buttons to hide the photos?

With html :)
`<details>
<summary>Show</summary>
<img src="">
</details>
`

**Comment by VedxP** [comment]
> > Out of context:
> > How did you add those "show" buttons to hide the photos?
> 
> With html :)
> 
> ```
> <details>
> <summary>Show</summary>
> <img src="">
> </details>
> ```

What do you think about the suggestion?

**Comment by Bnyro** [comment]
> What do you think about the suggestion?
>
In my opinion it's a bad idea as it doesn't follow the material guidelines and would make accedding the about menu harder!

**Comment by VedxP** [comment]
> > What do you think about the suggestion?
> 
> In my opinion it's a bad idea as it doesn't follow the material guidelines and would make accedding the about menu harder!

Got it :)
