### ISSUE TITLE
Media Codec Video Renderer Error

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#1625]
### Steps to reproduce

I encountered this error 3 times.

Not reproducible since I don't know the reason as I played video as usually I do.

### Expected behavior

.

### Actual behavior

![Screenshot_20221020-182727~2](https://user-images.githubusercontent.com/87353286/196963834-f9b92669-4f5a-4b1a-9a45-eff4efac33be.png)
---
![196601049-f0db1d2d-daf2-40df-a91b-b96492ef5ed5](https://user-images.githubusercontent.com/87353286/196963842-38434a15-227a-4cae-9c8a-7828eebbc085.png)

### LibreTube version

0.6.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Same here, happened after changing the instance. This toast randomly appear but there aren't any issues in my case. So idk

**Comment by VedxP** [comment]
> Same here, happened after changing the instance. This toast randomly appear but there aren't any issues in my case. So idk

Hmm, let's wait for @Bnyro to look after the issue.

**Comment by Bnyro** [comment]
Hmm, which resolution were you using?

**Comment by VedxP** [comment]
> Hmm, which resolution were you using?

Auto

**Comment by Bnyro** [comment]
That looks like an ExoPlayer issue as it's responsible for decoding the streams, but since it's not an issue those toasts just will be removed with the next update to avoid confusion.

**Comment by VedxP** [comment]
> That looks like an ExoPlayer issue as it's responsible for decoding the streams, but since it's not an issue those toasts just will be removed with the next update to avoid confusion.

Really appreciate your work bruh :)
