### ISSUE TITLE
[BUG] App language not changes from English

### ISSUE THREAD

**Issue by daudix-UFO** [libre-tube/LibreTube#163]
**Describe the bug**
Device language is Russian, app is translated to Russian, but interface still in English

**Smartphone**
 - Device: Pixel 3
 - Lineageos 19.1

**Comment by Bnyro** [comment]
Your device language is russian and you use the latest CI build?

**Comment by daudix-UFO** [comment]
@Bnyro Yes, Of Course

**Comment by Bnyro** [comment]
Please try this [CI build](https://github.com/libre-tube/LibreTube/actions/runs/2277959595) and change the language to Russian. Works for me :)

**Comment by Bnyro** [comment]
The Navbar becomes translated in one of my prs, you would just have to wait for it to be translated then
