### ISSUE TITLE
Libretube deletes your subscriptions if you sign into a new piped account

### ISSUE THREAD

**Issue by s1nistr4** [libre-tube/LibreTube#1633]
### Steps to reproduce

1. install Libretube
2. subscribe to youtubers
3. log into a new piped account
4. subscriptions gone

### Expected behavior

1. install Libretube
2. subscribe to youtubers
3. log into a new piped account
4. it transfers over your subscriptions if it's a new account, or asks you whether you want to sync the libretube ones or the piped account ones

### Actual behavior

1. install Libretube
2. subscribe to youtubers
3. log into a new piped account
4. subscriptions gone

### LibreTube version

0.6.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Well, that's not a bug, they're back if you log out again. I'd recommend you to export your subscriptions before logging into Piped and then importing them when logged in!
