### ISSUE TITLE
Updater Broken

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#1635]
### Steps to reproduce

1. Open settings
2. Scroll down to the end 
3. Click on updater option

### Expected behavior

It should check for update and show snackbar whether it's already up to date or there's a newer version available.

### Actual behavior

It always show `Network Error`

### LibreTube version

0.6.1

### Android version

Android 12

### Other details

<details><summary>Show reference image</summary>

![Screenshot_20221022-124949~2](https://user-images.githubusercontent.com/87353286/197326306-6a03c75f-e61f-404c-aab9-ff0457240ff9.png)

</details>

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Damn, Github changed something in their API

**Comment by noClaps** [comment]
Persists in 0.7.0

**Comment by VedxP** [comment]
> Persists in 0.7.0

Fixed already, will be shipped with the next release :)

**Comment by Bnyro** [comment]
It only seems to be broken in release versions, debug version works normal :/

**Comment by VedxP** [comment]
> It only seems to be broken in release versions, debug version works normal :/

Is it? I thought you've fixed it recently as I found it working in latest beta.

**Comment by Bnyro** [comment]
The issue is probably somehow related to the `proguard-rules.pro`, help is appreciated.
