### ISSUE TITLE
issue: Adding to Playlist 

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#1637]
### Steps to reproduce

1. Play any video 
2. Click on save 
3. Choose any playlist to save the video in 
4. Click on `Add to Playlist` button

### Expected behavior

It should close the popup and show a snackbar saying `Added to Playlist` or something like this.

### Actual behavior

But, currently it doesn't do anything to the UI upon clicking `Add to Playlist` button

### LibreTube version

0.6.1

### Android version

Android 12

### Other details

I've clicked on Add to Playlist button, and the popup is still like nothing happened :(

<details><summary>Show reference image</summary>

![Screenshot_20221022-121910~2](https://user-images.githubusercontent.com/87353286/197326884-b48eb228-43a4-4fe6-9755-f4bf33c3542c.png)

</details>

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Already resolved that, currently just too lazy to search the corresponding issue :)

**Comment by VedxP** [comment]
> Already resolved that, currently just too lazy to search the corresponding issue :)

Woah, gr8 :)
