### ISSUE TITLE
Use your subscriptions to make a more accurate homepage

### ISSUE THREAD

**Issue by Radical4ever** [libre-tube/LibreTube#1642]
### Describe your suggested feature

It would use yor subscriptions and with that info your webpage uses it to show videos based on that.
Kinda like youtube does

### Other details

I think if thats not possible to make a option when you choose what things you would like to see (and maybe that could be followed by youtube hashtags or something else)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
see #918
