### ISSUE TITLE
vertical pip is horizantal

### ISSUE THREAD

**Issue by theotheroracle** [libre-tube/LibreTube#1644]
### Steps to reproduce

1. play a vertical video
2. close the app
3. the pip window opens

### Expected behavior

the window should be vertical

### Actual behavior

it's horizontal

### LibreTube version

0.6.1

### Android version

android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by theotheroracle** [comment]
![Screenshot_20221022-180024_Kvæsitso_1](https://user-images.githubusercontent.com/20211219/197355777-0f5e5bab-c67f-453a-b7df-1f4496bb0019.png)

**Comment by xIUPITERx** [comment]
Any news on this?

**Comment by Bnyro** [comment]
Could anyone please provide a screen recording or something similar?
I still don't really get what the issue is, sorry for that :/

**Comment by theotheroracle** [comment]
oh sure, i realize my screenshot isnt the best

**Comment by theotheroracle** [comment]
https://youtube.com/shorts/q28iYljE9eg?feature=share

**Comment by Bnyro** [comment]
So you would like it to be vertical when going into PiP? Wouldn't it be hard to watch then?

**Comment by theotheroracle** [comment]
without the black bars, really, just like, a tall window

**Comment by xIUPITERx** [comment]
Something like that
https://stackoverflow.com/questions/64544792/android-picture-in-picture-potrait-mode
