### ISSUE TITLE
Sharing video or channel via email

### ISSUE THREAD

**Issue by RNavarro3000** [libre-tube/LibreTube#1654]
### Describe your suggested feature

When sharing video or channel via email, include filled in subject field.

### Other details

Pipe title from video or channel to subject field for email.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by shantanu1k** [comment]
@RNavarro3000 Like Autofill the subject field of composing email with video/channel title?

**Comment by RNavarro3000** [comment]
Correct...

**Comment by shantanu1k** [comment]
Hi @Bnyro , we might need to add additional parameter (videoTitle/channelTitle/playlistTitle) to ```ShareDialog``` constructor & to all of its instances. Lots of drilling......What do you think?

**Comment by Bnyro** [comment]
> Hi @Bnyro , we might need to add additional parameter (videoTitle/channelTitle/playlistTitle) to ```ShareDialog``` constructor & to all of its instances. Lots of drilling......What do you think?

We could create a class `ShareData` for that which contains all the different possible information and just null them by default.
I'm on vacation so I won't work on that in the next time but feel free to do so :)

**Comment by shantanu1k** [comment]
Hi @Bnyro , By creating a ```ShareData``` class , you mean Singleton class, right? Or something else? I've tried with Singleton & works for video(after opening the exo player) & channel. It doesn't work when we long press on video in the list & share with context menu.

**Comment by Bnyro** [comment]
> Hi @Bnyro , By creating a ```ShareData``` class , you mean Singleton class, right? Or something else?
> 
No, I just mean creating a data class that is passed to the function with the variables `timeCode`, `channelName`,  etc.
All are nulled by default which means in the ShareDialog we just check whether `shareData.channelName != null` and run the corresponding code then!

**Comment by Bnyro** [comment]
Not sure what you tried but in the end it should work for all the created share dialogs in the same way!
