### ISSUE TITLE
Sharing channel via email: link gets mangled

### ISSUE THREAD

**Issue by RNavarro3000** [libre-tube/LibreTube#1655]
### Steps to reproduce

1. First example, search for the channel "The Guardian"
2. Share it via email, which provides non working link "https://piped.kavin.rocks/c/The Guardian"
3. Second example, search for the channel "Guardian News"
4. Share it via email, which provides non working link "https://piped.kavin.rocks/c/Guardian News"

### Expected behavior

URL should be valid

### Actual behavior

URL is broken

### LibreTube version

0.6.1

### Android version

Android 10

### Other details

Perhaps its better to use channel IDs instead of short links when sharing?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Already fixed in the debug builds :)
