### ISSUE TITLE
Libretube automatically select English subtitle.

### ISSUE THREAD

**Issue by rozari0** [libre-tube/LibreTube#1657]
### Steps to reproduce

1. Open app
2. Go to Settings -> Player -> Subtitle Language and select **None**.
3. Play video that has subtitle.

### Expected behavior

Shouldn't show subtitle automatically.

### Actual behavior

LT select en-US automatically.

### LibreTube version

0.6.1

### Android version

Android 9

### Other details

Checked with both [Latest debug](https://github.com/libre-tube/LibreTube/actions/runs/3316627354) and 0.6.1.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't reproduce, any example video?

**Comment by rozari0** [comment]
> Can't reproduce, any example video?

https://piped.kavin.rocks/watch?v=kXZOIBBEjDI

**Comment by shantanu1k** [comment]
Hi @rozari0 , does v0.7.0 has this bug? I cannot reproduce this...

**Comment by rozari0** [comment]
> Hi @rozari0 , does v0.7.0 has this bug? I cannot reproduce this...

It's still there, but only for me I think. Or this has something to do with my device.

**Comment by shantanu1k** [comment]
> https://piped.kavin.rocks/watch?v=kXZOIBBEjDI

This video you shared shows the `Captions (en-US)` but it shows `Captions (en)` on my device.....does it has to do with locality?
wdyt @Bnyro @rozari0

**Comment by Bnyro** [comment]
> This video you shared shows the `Captions (en-US)` but it shows `Captions (en)` on my device.....does it has to do with locality? wdyt @Bnyro @rozari0
>
Hmm, I don't think so, in theory they should always be disabled when "None" is selected.
@rozari0 Could you please retry it with the latest debug version? Thanks!

**Comment by rozari0** [comment]
> > This video you shared shows the `Captions (en-US)` but it shows `Captions (en)` on my device.....does it has to do with locality? wdyt @Bnyro @rozari0
> 
> Hmm, I don't think so, in theory they should always be disabled when "None" is selected. @rozari0 Could you please retry it with the latest debug version? Thanks!

Tried, same. :'(

**Comment by Bnyro** [comment]
> Tried, same. :'(
>
I merged the PR a minute ago or something so the debug builds for it didn't even build yet, you're too fast ;)

**Comment by rozari0** [comment]
> > Tried, same. :'(
> 
> I merged the PR a minute ago or something so the debug builds for it didn't even build yet, you're too fast ;)

I checked tg channel after your comment, there was nothing new. So I thought you fixed it before. 😶

Tested with new debug. It's gone. :p 
Thanks!

**Comment by Bnyro** [comment]
Awesome, happy we were finally able to fix that annoying bug :)
