### ISSUE TITLE
Playlist would not play from the list for AUDIO option

### ISSUE THREAD

**Issue by rudfol** [libre-tube/LibreTube#1659]
### Steps to reproduce

1. save playlist (e.g Well Crafted Hip-Hop)
2. go to libraries tab
3. open the said playlist
4. tap the first video to play through

5.           Enable Audio option under the video with headphone icon
5.1   or   Set the play list to start with Play In The Background option under 3 dots on the right farside of playlist Title

### Expected behavior

When the selected video finishes it's expected to continually run through the list and play the next.

### Actual behavior

If autoPlay is enabled then it will play the next video from the current video's first recommended video.

If autoPlay is disabled it stops.

### LibreTube version

0.6.1

### Android version

Android 10

### Other details

One UI version 2.0

Samung Galaxy J6 (SM-J610FN)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by rudfol** [comment]
Exciting. I didn't realise pass playlist id to background were synnonymous with this.

Lastly I would love to contribute code wise as well but I just don't know how to or where to start. I don't even understand the folder structure.

**Comment by Bnyro** [comment]
You should probably just get started by building a simple Android app with Kotlin and XML, for example by following [this video](https://piped.kavin.rocks/watch?v=BBWyXo-3JGQ) :)
