### ISSUE TITLE
[FEATURE] Swipe up and down to enter and exit fullscreen

### ISSUE THREAD

**Issue by novocaiin** [libre-tube/LibreTube#166]
First of all thank you for this app.
I was so happy to learn there's finally a snappy and modern YouTube frontend without Gingerbread-era stuff like burger-menus.
Wish I had discovered it earlier.

**Describe the feature you'd like to see added**
Same as in the YouTube app, it would be nice to go fullscreen by swiping up on the vid and exit fullscreen with a swipe down gesture.

**Additional context**
Most Android phones have quite dismal gyros, so I can't rely on that and usually disable it.
It's also nice to able to watch while laying down.

**Comment by CasuallyOrange** [comment]
> First of all thank you for this app.
> I was so happy to learn there's finally a snappy and modern YouTube frontend without Gingerbread-era stuff like burger-menus.
> Wish I had discovered it earlier.
> 
> **Describe the feature you'd like to see added**
> Same as in the YouTube app, it would be nice to go fullscreen by swiping up on the vid and exit fullscreen with a swipe down gesture.
> 
> **Additional context**
> Most Android phones have quite dismal gyros, so I can't rely on that and usually disable it.
> It's also nice to able to watch while laying down.
> 

Yes!
I use this feature a lot on YouTube and would really like it to be added

**Comment by Bnyro** [comment]
This is currently not possible because of some other player features being in conflict with it. Therefore there will be an option to auto rotate to fullscreen now, idk whether that helps you.

**Comment by novocaiin** [comment]
Could you expand on which features conflict with it?

**Comment by Bnyro** [comment]
Double tap to forward/rewind

**Comment by Bnyro** [comment]
Feel free to add it if you find out how :)

**Comment by novocaiin** [comment]
Didn't mean to be rude so I'm sorry if I came off that way!
I just wasn't sure how the swipe up and down gestures interferes with double tap gestures.

Perhaps keep the issue open in case someone with development experience (i.e. not me haha) decides to open a pr?

**Comment by Bnyro** [comment]
I rewrote the double tap logic now, other gestures should now be possible to implement too.
I can't promise I'll add it soon but at least it is now possible and is planned for the future.

**Comment by Nephys222** [comment]
@Bnyro Tried to add fastSeekPlayer (the more tap the more seeking) as in Youtube. Despite successful, it conflicted with minimization of player. Do u think it would be possible to implement that. As in: https://github.com/vkay94/DoubleTapPlayerView

**Comment by Bnyro** [comment]
@Nephys222  The reason why I built double tap from scratch instead of using the library is that it's using an old exoPlayer version and that it doesn't give you much control over the behavior. We won't use it!

**Comment by Nephys222** [comment]
@Bnyro Unrelated to topic. Trying to optimize app for larger screens. Is it possible to solve to constraint CustomExoplayer directly constrained to mainContainer and solved for minimize transition?

**Comment by Bnyro** [comment]
I don't really get your question, sorry, but if you see a possible solution go for it and try it.

PS: We should rather discuss things like that in Github discussions or on Matrix, but not under random issues since people get notified here although they're not affected by the topic.
