### ISSUE TITLE
Playlist play randomized 

### ISSUE THREAD

**Issue by rudfol** [libre-tube/LibreTube#1660]
### Describe your suggested feature

  perhaps a button at the top of each playlist

	- toggleable so one can change it to play from the list order again from current video
	
	- make sure it works under AUDIO option 

### Other details

Thank you I very much appreciate your efforts and wholey the app and where it's going.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's gonna be added to the new playing queue which will make that much easier :)

**Comment by rudfol** [comment]
Wonderful. kudos.
