### ISSUE TITLE
Playback speed wrongly shown as 1x

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#1663]
### Steps to reproduce

1. Set default playback speed to 3x
2. Open video settings
3. Playback speed slider shows 1x instead of 3x.

### Expected behavior

3x.

Slider should match playback speed

### Actual behavior

1x.

Slider shows value not related to playback speed.

### LibreTube version

0.6.1

### Android version

12

### Other details

-

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by eclairevoyant** [comment]
Beat me to it, forgot to file this and the other issue. Also, this issue applies to both playback speed and pitch.

**Comment by Bnyro** [comment]
Already resolved, too lazy to search the corresponding issue x)
