### ISSUE TITLE
Crashes when launching video

### ISSUE THREAD

**Issue by w1n5t3n** [libre-tube/LibreTube#1672]
### Steps to reproduce

Open app
Search videos
Click on video
App crashes

### Expected behavior

Launch video

### Actual behavior

App immediately crashed and closed out

### LibreTube version

0.6.1

### Android version

Android 12

### Other details

No other errors seen app just crashes

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Same as #1667 ig
