### ISSUE TITLE
[feature suggestion] natural sort of the subtitles language for easier navigation

### ISSUE THREAD

**Issue by eladkarako** [libre-tube/LibreTube#1673]
### Describe your suggested feature

<img width="300" src="https://user-images.githubusercontent.com/415238/198681670-3f89171d-0aa7-48fa-94dd-ebc672e23cf4.png"/> <img width="300" src="https://user-images.githubusercontent.com/415238/198687193-60ff898c-4578-4fae-8bcc-8ebe6785370a.png"/>

### Other details

debug apk v1666879300

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You mean alphabetic?
