### ISSUE TITLE
[feature suggestion] allowing changing a sponsorblock server (works- sponsorblock.kavin.rocks fails- sponsor.ajay.app, pipedapi.kavin.rocks/sponsors)

### ISSUE THREAD

**Issue by ghost** [libre-tube/LibreTube#1674]
<img name="label_from_the_app" id="label_from_the_app" src="https://user-images.githubusercontent.com/415238/198691399-76817556-677e-4e70-ba87-c2684ad740f1.png"/>  

### Describe your suggested feature

sponsorblock api end point(s) `sponsor.ajay.app/api` as well as `sponsor.ajay.app/test/api` gets a $h!t ton of 502 and 404 lately (pardon my fr3nch).  

![2022-10-28_193909](https://user-images.githubusercontent.com/415238/198690180-ea2a788c-c9a1-4935-b4be-35d9f4822173.png)

there are very few hosts that clone sponsorblock db <strong>as well its api end point</strong>, but I did managed to came across (two) that seems functional!  

`https://sponsorblock.kavin.rocks`  
(https://github.com/mchangrh/sb-mirror)  

`https://sponsorblock.gleesh.net`  
(https://github.com/TeamPiped/sponsorblock-mirror)  

and `https://sb.doubleuu.win`  
(got it from https://github.com/wereii/gosb)  

their `/api` seems to working.  

![2022-10-28_193710](https://user-images.githubusercontent.com/415238/198690240-56cd5118-09a4-4871-9297-0bff4df77add.png)

<hr/>

..I guess an open "inputbox" would be a better design,  
in case those would fail as well, so users would be able to switch to another mirror that hasn't been broken down..  

note:  
this is just a suggestion, I just wanted to share [this workaround](https://github.com/yt-dlp/yt-dlp/issues/5342#issuecomment-1291585335).

(if you're aware of any other mirrors, pls share..)

### Other details

workaround for sponsorblock 502/404 lately || possible server-down fallback.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
LibreTube doesn't access `sponsor.ajay.app` directly, it sends a request to the Piped instance used which fetches the segments for us, e.g. https://pipedapi.kavin.rocks/sponsors/om7-QhWHwYk?category=[%22sponsor%22,%22interaction%22,%22selfpromo%22,%22music_offtopic%22].

Since a recent commit, Piped also uses https://sponsorblock.kavin.rocks if the official database is down, so I'm not sure whether that would make sense as the Piped Backend should be able to handle it itself now.
