### ISSUE TITLE
crash on share to libretube

### ISSUE THREAD

**Issue by pc00per** [libre-tube/LibreTube#1682]
### Steps to reproduce

1. Open a chrome based Android browser (kiwi in my case)
1. Share a video link from yewtu.be
2. Select libretube

### Expected behavior

Crashes with crashlog shared below
https://pastebin.com/YhRZ3bDm

### Actual behavior

Should play the intended invidious instance.

### LibreTube version

0.6.0

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by pc00per** [comment]
I don't understand. Completed how ? Any link to the fix, or merge ?

**Comment by Bnyro** [comment]
The latest one should have fixed it!

**Comment by pc00per** [comment]
Okay.
