### ISSUE TITLE
Source error on opening 

### ISSUE THREAD

**Issue by CeasarYT** [libre-tube/LibreTube#1683]
### Steps to reproduce

It should open fine  

### Expected behavior

But every time I try to open lt no video is available
Always there is one problem

### Actual behavior

But every time I try to open lt no video is available
Always there is one problem
Source error 
![Screenshot_20221029-064220](https://user-images.githubusercontent.com/112339868/198755278-ae1b9cac-6835-478d-a22d-69bc260626d9.png)

### LibreTube version

0.6.1

### Android version

20

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by rozari0** [comment]
Change instance.

**Comment by xIUPITERx** [comment]
That doesn't help for me.
Since a few days the subscription feed doesn't work at all, tried it on multible devices and instances, but over the search the videos start just fine.

**Comment by xIUPITERx** [comment]
Please don't close issues that fast if its isn't a clear dupe or east of time, let the author answer once.

**Comment by rozari0** [comment]
> That doesn't help for me. Since a few days the subscription feed doesn't work at all, tried it on multible devices and instances, but over the search the videos start just fine.

Are you using alternative auth instance for subscription?

**Comment by xIUPITERx** [comment]
>no, I use the "official" Kavin.rocks (libre) one.

**Comment by xIUPITERx** [comment]
https://user-images.githubusercontent.com/97352673/198826189-e78cfd42-56a9-458d-8ed6-2887a3079092.mp4

**Comment by rozari0** [comment]
> No, I use the "official" Kavin.rocks (libre) one.

I dunno, but it has some problem I think. Export your subscription and import it to another instance. (I prefer whatever.social, but feel free to choose)  Then login with it.

**Comment by xIUPITERx** [comment]
I tried it, but the subscriptions export was just empty.

**Comment by rozari0** [comment]
> I tried it, but the subscriptions export was just empty.

Export from [Here](https://piped.kavin.rocks/subscriptions) .

**Comment by xIUPITERx** [comment]
Thanks it worked,
Does the Kavin.rocks cause the problems (the website works) or Libretube?

**Comment by rozari0** [comment]
> Thanks it worked, Does the Kavin.rocks cause the problems (the website works) or Libretube?

Kavin's instance have problem I think.

**Comment by Bnyro** [comment]
Yes, kavin.rocks has a database issue and therefore subscriptions currently don't load!
