### ISSUE TITLE
Downloaded subtitles can't be played.

### ISSUE THREAD

**Issue by xGrim69** [libre-tube/LibreTube#1700]
### Describe your suggested feature

Including subtitles when downloading a video would be great especially when watching foreign contents.

### Other details

![Screenshot_2022_1030_113841](https://user-images.githubusercontent.com/106541892/198861465-ffe0d8d4-9b14-4e5a-ab68-fcbf21621f02.png)
Offline video with subtitles like in Youtube

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by swarnendumaiti** [comment]
Till then you can use Seal Video downloader that allows downloading of subtitles with the video. https://github.com/JunkFood02/Seal

**Comment by rozari0** [comment]
I think subtitle downloading is available now.

**Comment by Bnyro** [comment]
Yes, but they're not playable for some unknown reason

**Comment by akano12** [comment]
> Yes, but they're not playable for some unknown reason

Tried to reproduce this issue, upon checking the downloaded subtitles, the srt files downloaded were always empty.

Just a blank srt file with nothing inside, tested with multiple videos and multiple subtitle languages, the srt file was always blank in all test

**Comment by Bnyro** [comment]
Hmm, no wonder they don't play then. The issue probably is somewhere when downloading the subtitles, thanks for investigating!
