### ISSUE TITLE
Better Aligned Playlist Strip

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#1704]
### Describe your suggested feature

1. Currently, the count number of videos and playlist icon are aligned from the centre.

- Therefore, the count at the center with x and y axes, but the playlist icon is pushed towards the bottom.

2. The playlist icon isn't aligned with the count number.
- It's pushed left compared to count number.
- - Marked with green in reference screenshot.

### Other details

Reference Screenshot:
![Screenshot_20221030-132325~3](https://user-images.githubusercontent.com/87353286/198869577-a336712e-1288-4b22-ac45-9774cd9dfd3e.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
And please reduce the size of the black box.

**Comment by xIUPITERx** [comment]
Where can you download the latest debug version? I can't find it in the GitHub page.

**Comment by VedxP** [comment]
> Where can you download the latest debug version? I can't find it in the GitHub page.

[Actions](https://github.com/libre-tube/LibreTube/actions)

**Comment by xIUPITERx** [comment]
When I try to open open the file from telegram, it shows the message "No application found to open this file".

**Comment by VedxP** [comment]
> When I try to open open the file from telegram, it shows the message "No application found to open this file".

Means you aren't able to install APK?

Have you tried installing any APK outside of Telegram?

If you're able to install APK outside of Telegram, then tap on the APK file on Telegram Channel and click on Save to Downloads and install the APK from file manager as you do :)

**Comment by xIUPITERx** [comment]
Looks like the telegram x app can't handle files correctly, it worked just fine in the normal Telegram app.
In the latest debug realize there are all the changes from the merches before right?

**Comment by VedxP** [comment]
> In the latest debug realize there are all the changes from the merches before right?

Yup

**Comment by xIUPITERx** [comment]
![Screenshot_20221105-141005_LibreTube Debug.jpg](https://user-images.githubusercontent.com/97352673/200121678-9c7aa8a7-77ec-42bb-a7d6-ad9751df9483.jpg)

Looks like it hasn't been fixed yet

**Comment by Bnyro** [comment]
Damn, I've been fixing it in the layout I replaced afterwards ...
Fixed now, thanks for the catch!

**Comment by xIUPITERx** [comment]
@Bnyro It works now, but could you shrink the black box to a third of the thumbnail, it uses a bit too much space.

**Comment by Bnyro** [comment]
> @Bnyro It works now, but could you shrink the black box to a third of the thumbnail, it uses a bit too much space. 
>
I already shrinked it though, I feel like it needs to fill at least the half of the thumbnail

**Comment by VedxP** [comment]
@Bnyro the icons still aren't aligned to centre with thumbnail vertically.

> ![Screenshot_20221106-173540~2](https://user-images.githubusercontent.com/87353286/200169738-fbf5343c-673d-4289-aeb8-a2698459aa61.png)

**Comment by Bnyro** [comment]
Fair, that's also been part of the changes I've been overriding 🤦‍♂️
