### ISSUE TITLE
Align video options

### ISSUE THREAD

**Issue by heberjeur** [libre-tube/LibreTube#1705]
### Steps to reproduce

Try to open any video and see options in French language, you will find that "save" option not aligned like others

### Expected behavior

Download option,"enregistrer" could be aligned
![Screenshot_20221030-092248_LibreTube](https://user-images.githubusercontent.com/11852634/198869602-70a692a3-3c5d-46cf-be83-663b8ea16214.jpg)

### Actual behavior

There are a text that's not hided like "open", " ouvrir" button

![Screenshot_20221030-092311_LibreTube](https://user-images.githubusercontent.com/11852634/198869612-8ebed4fc-c40d-428a-82cb-7649e74e6d9a.jpg)

### LibreTube version

0.7.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by shantanu1k** [comment]
Hi @Bnyro , the words are loong in some languages......

Auto-sizing the textview gives inconsistent results in _video options_ **:**

![photo_2022-10-31_16-38-44](https://user-images.githubusercontent.com/57897297/198995484-8602c84b-8ea1-49fd-8ae2-73083917327e.jpg)

I can make a PR if it is working for the users :)

**Comment by Bnyro** [comment]
@shantanu1k Yes, seems like that's the only way to fix that unfortunately, feel free to create a PR to just add auto-sizing to all of the remaining option buttons :)
