### ISSUE TITLE
Channel name doesn't aligned correctly

### ISSUE THREAD

**Issue by heberjeur** [libre-tube/LibreTube#1707]
### Steps to reproduce

Try to open any video on Arabic language

### Expected behavior

Channel name must be right aligned

### Actual behavior

There are no space between subscribe button and channel name 
![Screenshot_20221030-093606_LibreTube](https://user-images.githubusercontent.com/11852634/198869993-de71c8f6-f718-4378-9bba-25630b84f5bb.jpg)

### LibreTube version

0.7.0

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by shantanu1k** [comment]
Hi @Bnyro , do we need to add the **extra** support for the RTL languages here?
Like creating a variant of `PlayerFragment.xml` because it is partially following RTL order..

![image](https://user-images.githubusercontent.com/57897297/199432463-8b83a5c6-fba2-4228-9257-71a33d6c53c2.png)

**Comment by Bnyro** [comment]
I'll have to take back my previous statement, at least for the channel row. I had a look, but no idea why it doesn't align to the start properly.
However, I want to avoid having multiple layouts for the same thing as that would make maintaining it harder.
There has to be a solution without creating a layout, I currently don't know how unfortunately :/
