### ISSUE TITLE
Open Channel from logo ft. Alternative Videos Layout

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#1708]
### Describe your suggested feature

> Add the ability to open channel from channel logo when `alternative videos layout` is turned on.

#### Explaining the current implementation, when *alternative videos layout* is turned on:

- Turn on `alternative videos layout`
- Search for anything 
- Tap on any channel logo 
- It'll open that channel 
---
- Now, move to home/subscription tab 
- Tap on any channel logo 
- It won't open the channel, rather it plays the video

### Other details

Reference screenshots:
<details><summary>Can be opened from search page</summary>

![Screenshot_20221030-140844~2](https://user-images.githubusercontent.com/87353286/198870072-7bb506e7-f255-41b6-8fa7-29cfcd709961.png)

</details>

<details><summary>Can't be opened either from home tab or subscription tab</summary>

![Screenshot_20221030-140911~2](https://user-images.githubusercontent.com/87353286/198870103-4ba4bb01-a3db-4064-9f14-12906ee9f0c2.png)

</details>

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by shantanu1k** [comment]
Hi @VedxP , in v0.7.0 (latest) we are able to open channel directly from the above screens....Can you try it on the latest version? and pls share a screen recording, if it doesn't work :)

**Comment by VedxP** [comment]
> Hi @VedxP , in v0.7.0 (latest) we are able to open channel directly from the above screens....Can you try it on the latest version? and pls share a screen recording, if it doesn't work :)

I'm on latest version `0.7.0` and can't open channel from channel logo in either home tab or subscription tab

**Comment by VedxP** [comment]
Update:
- Tried even reinstalling, still the same :(

**Comment by VedxP** [comment]
> Hi @VedxP , in v0.7.0 (latest) we are able to open channel directly from the above screens....Can you try it on the latest version? and pls share a screen recording, if it doesn't work :)


@shantanu1k Can you please perform the same action and send a recording of it?

**Comment by shantanu1k** [comment]
@VedxP Sure **:)**

**Comment by shantanu1k** [comment]
https://user-images.githubusercontent.com/57897297/199258454-764421df-edbd-415b-9404-538b316bf573.mp4

**Comment by VedxP** [comment]
> 2022_11_01_19_56_40.mp4

Lol, got the point 👍

Thanks for confirming :)

**Comment by xIUPITERx** [comment]
@Bnyro please extendend the field you can tab on to open the channel to the name of the channel, the picture alone is very small.
![Screenshot_20221107-001823_LibreTube Debug.jpg](https://user-images.githubusercontent.com/97352673/200200995-2cf6e402-3570-4711-9479-1c81c99285bf.jpg)

**Comment by VedxP** [comment]
> @Bnyro please extendend the field you can tab on to open the channel to the name of the channel, the picture alone is very small. ![Screenshot_20221107-001823_LibreTube Debug.jpg](https://user-images.githubusercontent.com/97352673/200200995-2cf6e402-3570-4711-9479-1c81c99285bf.jpg)

If doing so, implement the same throughout the app from home tab to subscription tab to search page; both when `alternative videos layout` is off and when it's on.

**Comment by shantanu1k** [comment]
Hi @Bnyro , have you merged a PR for this? or working on this? I can make a PR  :)

**Comment by Bnyro** [comment]
> Hi @Bnyro , have you merged a PR for this? or working on this? I can make a PR  :)
>
I fixed that channel avatars aren't clickable but not the thing with the channel name, feel free to open a PR for that ;)
