### ISSUE TITLE
Share link to libretube doesn't work for yt desktop video links where ?v= is not first url param

### ISSUE THREAD

**Issue by distbit0** [libre-tube/LibreTube#1711]
### Steps to reproduce

I have found when I share a YouTube link to libretube from the desktop version of YouTube, it is not opened by libretube. An example is the following: https://www.youtube.com/watch?app=desktop&v=YjPW8-eKkUY I am guessing it is a result of the order of the parameters in the url. 

### Expected behavior

The url should open in the app when shared via sharing menu from browser. 

### Actual behavior

The app just opens but doesn't play any video. 

### LibreTube version

0.6.0

### Android version

Android 11

### Other details

Would be awesome to have this fixed. Also great job on the app. I remember checking it out after the first release and realising it was missing a few important features. It has now matured in such a short amount of time to a level such that it is better than all other YouTube clients, and I use it every day. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by GilesMunn** [comment]
This seems to work for me - have you got LibreTube set to open YouTube links in the app settings?

**Comment by shantanu1k** [comment]
@GilesMunn I can't find that option in the app settings....where is it?

**Comment by Bnyro** [comment]
It works fine for me as well, I'm pretty sure it's been fixed by some changes made between 0.6.0 and 0.6.1 that changed the way of how links are handled! Please make sure to upgrade the app, 0.7.0 is already available since two weeks :)
