### ISSUE TITLE
All recent videos from subscribed channel not showing in subscription feed 

### ISSUE THREAD

**Issue by Dhangofa** [libre-tube/LibreTube#1714]
### Steps to reproduce

After refreshing the subscription feed all the videos not loading (not showing in the feed)
But if I go to specific channel page then the video is there. Only kevin rocks instance load most of the video but not all the video

### Expected behavior

All the recent videos from all the subscribed channel should show in the subscription feed

### Actual behavior

After refreshing the subscription feed all the videos not loading (not showing in the feed)
But if I go to specific channel page then the video is there. Only kevin rocks instance load most of the video but not all the video

### LibreTube version

0.7.0

### Android version

Android 11

### Other details

I checked the subscription feed from newpipe and libretube with same subscribed channel, but newpipe showing all the videos in subscription feed and libretube not showing all the videos.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by VedxP** [comment]
Yup, it doesn't load latest video upon refreshing.

But if you visit the channel and come back, it'll show the latest content.
Even closing and reopening LT does the work.

Although it should load the latest videos upon refreshing only, let @Bnyro check it out first :)
