### ISSUE TITLE
Better Design ft. Playing Queue

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#1718]
### Describe your suggested feature

In the playing queue, there's currently a chip saying, `More from this channel for you` using the same design as videos use.

Instead, the design for the latter feature can be improved so that it stands out as it should, from the rest of the **videos** in the playing queue.

#### Ex: 
- Use channel logo instead of video thumbnail 
- Remove duration text at the right end 

### Other details

Reference Screenshot:
![Screenshot_20221031-183959~2](https://user-images.githubusercontent.com/87353286/199156919-7fa003c7-4ae1-4a72-916b-3a0284b3c5d7.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That item is not meant to be there, in fact that was an issue at Piped which resulted in some malicious items in the response.

**Comment by FireMasterK** [comment]
Malicious items?

**Comment by Bnyro** [comment]
> Malicious items?
>
The playlists that were part of the related streams as I told you :)
