### ISSUE TITLE
Shorts' Duration Not Showing in Videos Tab

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#1719]
### Steps to reproduce

- Search for Blackpink or any channel having shorts in videos tab.
- Open the channel.
- The shorts shown on the videos tab doesn't show the duration.

### Expected behavior

It should show the duration as other videos do.

### Actual behavior

It doesn't show up.

It's okay to have shorts badge on shorts in `shorts` tab; but in `videos` tab, it should show the duration.

### LibreTube version

0.6.1

### Android version

Android 12

### Other details

Reference image:
![Screenshot_20221101-095034](https://user-images.githubusercontent.com/87353286/199158441-a5987a77-90e8-473e-875f-8850771810c4.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's an issue at the NewPipe Extractor, nothing we can do about it unless waiting for the fix!
