### ISSUE TITLE
[FEATURE] Monero donations support (XMR)

### ISSUE THREAD

**Issue by sonalder-darlene** [libre-tube/LibreTube#172]
**Describe the feature you'd like to see added**
I wish you supported XMR donations, way more private than BTC, cheaper fees and an overall better product.

**Additional context**
Monero is 8 years old so pretty OG, pretty well adopted in the privacy sphere (the same public as your app), has super small fees and fast transactions !
It's private so don't worry about people analysing your public key for informations.
Learn more on https://getmonero.org and https://masteringmonero.com/

**Comment by lilcheti** [comment]
The best issue we had so far :)

**Comment by lilcheti** [comment]
Done check readme :)
