### ISSUE TITLE
Confirmation message before unsubscribing a channel 

### ISSUE THREAD

**Issue by GET100PERCENT** [libre-tube/LibreTube#1720]
### Describe your suggested feature

Each time when the unsubscribe button will be pressed, there will be a confirmation message asking "Are you sure to unsubscribe this channel ?" with two options to choose"yes" and "no".

### Other details
1. If this feature is implemented, then it will protect from accidental click on the unsubscribe button.
2. Also since the subscriptions are very important for people, there should be two steps before clicking the button as once it is clicked, there will be no video updates from that channel. (In YouTube after unsubscribing a channel, still there are videos from that channel on the feed , from which the channel can be found out and resubscribed.)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
This might be subjective, but I don't think that adding an extra confirmation prompt, for example as a dialog, does make sense for the following reasons:
1. It'll require the user always one more step to unsubscribe a channel which will probably become annoying over time.
2. I doubt that anyone would accidentally click the unsubscribe button as only swiping over it wouldn't even trigger it.
3. I don't really get the argument why subscriptions are really important for people, if you're really interested in a content creator you know their channel name, so one can just resubscribe when noticing no new videos.

**Comment by akano12** [comment]
@bnyro
Maybe make unsubscribing a long press functionality? Like long press unsubscribe for 2 second to unsubscribe (with a progress indicator over the unsubscribe button). Will definitely require more code but i personally f8nd it better than a dialog box

**Comment by GET100PERCENT** [comment]
But I think confirmation message is better, because this possible to keeping the finger on the unsubscribe button while scrolling very slowly.

**Comment by akano12** [comment]
> But I think confirmation message is better, because this is possible to keeping the finger on the unsubscribe button while scrolling very slowly.

Whole idea of confirmation dialog isn't necessary, long pressing -if implemented- would be somehow a fair solution for those who wouldn't like to see a confirmation dialog nor want to *accidentally* unsubscribe.

And if it's up to me, wouldn't implement any of them cz both aren't necessary as Bnyro said.

Another suggestion (not sure if exist because i don't have any subscriptions) is to show a Toast when unsubscribing, this will notify the user about his action. Other than that, it's totally unnecessary and everyone is free to clone and edit source to suit his needs.

**Comment by GET100PERCENT** [comment]
Ok then , the long press time can be a little more (3seconds).
