### ISSUE TITLE
libretube video notification doesn't go away.

### ISSUE THREAD

**Issue by rozari0** [libre-tube/LibreTube#1722]
### Steps to reproduce

No sure how to reproduce. I was just playing video and now it doesn't go away. Happend before, not rarely.

### Expected behavior

Should close video and notification.

### Actual behavior

Here is an example https://piped.kavin.rocks/shorts/O-eXvX27JaM

### LibreTube version

0.7.0

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Mrnofish** [comment]
Same on LOS 18.1 (A11). Tap'n'hold on the player results in the following message:

```
Media

Current session cannot be hidden
```

The Dismiss button is greyed out and inactive.

@rozari0 as a workaround, Force Stop LibreTube.

**Comment by rozari0** [comment]
> Same on LOS 18.1 (A11). Tap'n'hold on the player results in the following message:
> 
> ```
> Media
> 
> Current session cannot be hidden
> ```
> 
> The Dismiss button is greyed out and inactive.
> 
> @rozari0 as a workaround, Force Stop LibreTube.

I did that, but need a permanent solution.

**Comment by R715B** [comment]
The problem is still occurring on Android 13 (GrapheneOS).  The only way I've found to unstick the media notification is to clear LibreTube from the recent apps, relaunch the app and clear it again from the recents.
