### ISSUE TITLE
Currently-live streams do not appear in Subscriptions

### ISSUE THREAD

**Issue by ehea617** [libre-tube/LibreTube#1726]
### Steps to reproduce

1. Subscribe to a channel that is currently live or be already subscribed to a channel that goes live
2. Refresh the Subscriptions feed
3. The livestream will not appear in the Subscriptions feed
4. Go to the channel page
5. The stream will appear on the channel page under livestreams with an indicator showing it's live

### Expected behavior

Currently-live streams will appear in the Subscription feed like uploaded videos, shorts, and livestream VODs already do.

### Actual behavior

Currently-live streams do not appear in the Subscriptions feed

### LibreTube version

0.7.0

### Android version

Android 11

### Other details

I wasn't sure if I should file this as a bug or feature request. I ultimately went for a bug as NewPipe displays livestreams immediately in the feed once a stream is live. Please feel free to move this to a feature request if it's not a bug and currently working as intended.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The content of the feed is not being controled by LibreTube itself, its being generated by the Piped instance you're using. Therefore you will have to oprn an issue at https://github.com/TeamPiped/Piped!

**Comment by ehea617** [comment]
Submitted to https://github.com/TeamPiped/Piped/issues/1730

**Comment by Mrnofish** [comment]
This has been an outstanding issue for a couple months now, and there doesn't seem to be any answer on the TeamPiped side.

Would it be feasible to implement a workaround specifically in LibreTube?

**Comment by Bnyro** [comment]
1. Please don't tag me (which is also mentioned in our Code of conduct)!
2. No, for a proper implementation server side changes are required!

**Comment by Mrnofish** [comment]
1. Whoops, apologies! Perhaps that wasn't yet in the last time I checked the CoC, will keep it in mind for the future.
2. After further investigation, I'm having this problem while accessing an official Piped instance (kavin.rocks), which should not be experiencing the problem as far as I understand

I've cleared the login in LibreTube's settings, selected the instance again, then logged in, and I'm still missing livestreams.

If I access the same instance with an account through Firefox on PC, the livestreams are there instead.

What gives?

**Comment by Bnyro** [comment]
Piped doesn't support livestreams in the feed yet, so they won't show, no matter which instance you're using iirc.

**Comment by Mrnofish** [comment]
To be fully clear, what I have been talking all along here, is not live streams that are currently live, but rather those which have finished and should be showing shoulder to shoulder with regular, uploaded videos.

When I said livestreams, I meant
