### ISSUE TITLE
Add a option to hide subscribe button from video player page

### ISSUE THREAD

**Issue by tvnmguy** [libre-tube/LibreTube#1729]
### Describe your suggested feature

For avoiding accidental touches which leads to unsubscribe

### Other details

![IMG_20221102_161346](https://user-images.githubusercontent.com/116799295/199470278-64c61f57-50b8-4265-8f1a-5c6b4dd9cb02.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
To be honest, I never heard from anyone that accidentally unsubscribed a channel, might it be in the videos page or a normal channel tab.
Hiding the button would remove some functionality and would look weird as there would just be a huge block with nothing ...

**Comment by IkelAtomig** [comment]
Maybe add a confirmation dialog then ?

**Comment by Bnyro** [comment]
#1720
