### ISSUE TITLE
Can't register

### ISSUE THREAD

**Issue by stemy2** [libre-tube/LibreTube#1735]
### Steps to reproduce

1. Select an instance.
2. Try to register.

### Expected behavior

Registration succeeds.

### Actual behavior

Error message: "there is a problem with the server. Try another instance ?", even on instances that actually work.

### LibreTube version

0.7.0

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
see https://github.com/TeamPiped/Piped/issues/1670
