### ISSUE TITLE
Captions don't work

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [libre-tube/LibreTube#1737]
### Steps to reproduce

Beginning with 0.6.1 captions don't work anymore (English) (all necessary settings enabled)

### Expected behavior

?

### Actual behavior

not working 

### LibreTube version

0.7.0

### Android version

android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
see #1698

**Comment by Bnyro** [comment]
Whoops, I wanted to target your previous issue

**Comment by Bnyro** [comment]
Tested, can't be reproduced!
