### ISSUE TITLE
Shortcuts for LibreTube 

### ISSUE THREAD

**Issue by ARBoyGo** [libre-tube/LibreTube#1738]
### Describe your suggested feature

We need shortcuts for LibreTube, For Quick access to the dedicated tab/page. In YouTube we have shortcuts for Explore, Shorts, Search and Subscribe 

### Other details

A screenshot of shortcuts and you can pin it also. 
<img src="https://user-images.githubusercontent.com/69381592/199708072-9a48afa0-47b6-40bf-9b98-3a95cfd55906.jpg" width="40%"/>

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
https://user-images.githubusercontent.com/97352673/200200408-fd303aeb-97f3-488e-8189-0f9cc5c89ed7.mp4
They don't work as planed.

**Comment by Bnyro** [comment]
For me it even says `app not installed`, probably related to the application suffix, @GilesMunn any idea?

**Comment by GilesMunn** [comment]
I'll take a look

**Comment by GilesMunn** [comment]
As @Bnyro correctly guessed, it's because the application package name needs to be specified in XML and can only be hardcoded. This means it'll work correctly on a release build, but not on the debug version.
