### ISSUE TITLE
Better contrast for SponsorBlock segments on the time bar

### ISSUE THREAD

**Issue by GET100PERCENT** [libre-tube/LibreTube#1739]
### Describe your suggested feature

The sponsor segments are shown in the player with their default colours. There can be a option to choose colours for each type of sponsor segments.

### Other details

1. This feature is essential as many people on the trend use blue light filters. So it's not easy to identify the segments. 

2. Normally people don't skip small segments, but skip them when they are large. But if there is difficulty in seeing the segments on the player, they also get difficulty in deciding whether to skip a segment or not.
![Screenshot_20221103-180329](https://user-images.githubusercontent.com/116144024/199723874-aa60964c-5cdd-4d21-a877-147067ef7224.jpg)
              In the screenshot you can see the segments and the normal bar both look almost same and difficult to distinguish, when the blue light filter is turned on.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by GET100PERCENT** [comment]
With blue light filter turned on, the white and the orange looks almost same.

**Comment by Bnyro** [comment]
Letting users choose it manually won't be possible as for now as there's no color picker library available that follows the Material Design 3, a text input for hex colors doesn't seem to be a good solution to me! Maybe we can just use the official SponsorBlock colors as Piped does it!

**Comment by GET100PERCENT** [comment]
Okay then.
Can a dedicated blue light filter be added to libretube by default?

**Comment by Bnyro** [comment]
> Can a dedicated blue light filter be added to libretube by default?
>
No?

**Comment by GET100PERCENT** [comment]
Okay, then any other solution you can think to solve this ?

**Comment by GET100PERCENT** [comment]
Or if the width of the sponsors segments can be a little more, it will be easier to distinguish even in the default colour.

**Comment by Bnyro** [comment]
Too be honest I don't think the blue filter is really an issue, in my opinion the segments are still visible enough even with a blue filter.
But still we can just use another theme color that has a higher contrast instead of the current one.

**Comment by GET100PERCENT** [comment]
Yes, a high contrast theme is really a good idea.
