### ISSUE TITLE
Search Bar Issue When Switching From Recents

### ISSUE THREAD

**Issue by akano12** [libre-tube/LibreTube#1740]
### Steps to reproduce

1. Open Libretube and click on search. 
2. Press home button or switch to another app.
3. Switch back to Libretube

### Expected behavior

Open search bar

### Actual behavior

Bugged.

https://user-images.githubusercontent.com/50032603/199789686-d56c621c-bce4-4c08-ab72-3a6d2aab8b88.mp4

### LibreTube version

0.7.0

### Android version

Android 12

### Other details

Found this bug when i opened Libretube to search for something but i forgot what was it, switched back to gallery to check then back to Libretube to search and found it. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by VedxP** [comment]
Same as #1599

**Comment by akano12** [comment]
> Same as #1599 

Nope 😬

**Comment by VedxP** [comment]
Another way of reproducing the same:

- Search for anything
- Click back, once more so that search bar disappears 
- Click back once more, you'll end up with `No History Yet` page. 
- Now click search box, it'll force close the search bar the same way as this issue describes.

**Comment by akano12** [comment]
> Another way of reproducing the same:
> 
> - Search for anything
> - Click back, once more so that search bar disappears 
> - Click back once more, you'll end up with `No History Yet` page. 
> - Now click search box, it'll force close the search bar the same way as this issue describes.
> 

Oh you mean it can be reproduced in other ways. But can you confirm that all mentioned issues are caused by same bug?

**Comment by VedxP** [comment]
@akano12 here's the recording:



https://user-images.githubusercontent.com/87353286/200161824-1fad12da-ac01-484a-ba83-3bacc66523da.mp4

**Comment by VedxP** [comment]
#1809 brought another misbehaviour now 😆
Will upload recording soon :)

**Comment by Bnyro** [comment]
> @Bnyro , #1809 brought another misbehaviour now 😆
> #### Steps to reproduce:
> - Open LT 
> - Open search bar
> - Dismiss keyboard 
> - Tap any navigation tab
> - **The search bar never goes away**
> 
> <details><summary>Reference screenshot:</summary>
> 
> > ![Screenshot_20221112-183852](https://user-images.githubusercontent.com/87353286/201475580-a4bbc983-e860-41bc-989e-55feb56ef2c0.png)
> ![Screenshot_20221112-183858](https://user-images.githubusercontent.com/87353286/201475603-1cafb488-9738-4e88-a426-bf29c10583ea.png)
> ![Screenshot_20221112-183901](https://user-images.githubusercontent.com/87353286/201475607-5af87eda-67b9-42a7-992e-9667a7ce354d.png)
> ![Screenshot_20221112-183908](https://user-images.githubusercontent.com/87353286/201475608-c842c0ed-1db2-4f32-b884-bfa93a62fc35.png)
> ![Screenshot_20221112-183911](https://user-images.githubusercontent.com/87353286/201475654-b35606f9-73da-4335-8778-7bf3f1a61ec2.png)
> 
> </details>
>
Oh, right, I already wondered why the code that I renoved even existed, I probably should have wrote some comments there ...
I hate working on that, but it looks like I need to go on investigating :/

**Comment by VedxP** [comment]
> Oh, right, I already wondered why the code that I renoved even existed, I probably should have wrote some comments there ... I hate working on that, but it looks like I need to go on investigating :/

Still persists :(

- The behaviour should be to close the search bar when any navigation tab is tapped

**Comment by Bnyro** [comment]
That should already be done in theory :/

**Comment by Bnyro** [comment]
Could you please try the new build once it has finished? I couldn't reproduce it anymore now :)

**Comment by VedxP** [comment]
> Could you please try the new build once it has finished? I couldn't reproduce it anymore now :)

Fixed with #1823 🎉
