### ISSUE TITLE
Videos start playing even though autoplay is off

### ISSUE THREAD

**Issue by Mrnofish** [libre-tube/LibreTube#1741]
### Steps to reproduce

Tap on a video from the Subscriptions view.

### Expected behavior

Playback shouldn't start automatically if Autoplay is set to Off

### Actual behavior

Playback starts as soon as the video page is opened in the app.

### LibreTube version

0.7.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Autoplay option has nothing to do with your issue, simply if you're watching something and the video ends, it will automatically play next/upcoming videos. 

Disabling Autoplay will disable playing anything after rhe current video 



![20221103_191956.jpg](https://user-images.githubusercontent.com/50032603/199790766-ea8aac92-6ec0-412c-b4c6-7150f2355e03.jpg)

**Comment by Mrnofish** [comment]
Yeah, I just realized that, I thought there were two different auto-play options. Why is this not planned, though?

Having videos playback start whenever one is opened wastes resources and is extremely annoying.

Needless to say NewPipe has that option.

**Comment by Bnyro** [comment]
Nobody said it wouldn't be planned.
Your issue was a bug report, the issue was closed because there's no bug obviously!

If you want to request such an option please open a new issue!

**Comment by Mrnofish** [comment]
Your 'issue closed' message said "not planned", that's where the misunderstanding came from.

Will open a FR, thank you.
