### ISSUE TITLE
App crash on startup since 0.7.0 update

### ISSUE THREAD

**Issue by Hate9** [libre-tube/LibreTube#1744]
### Steps to reproduce

1. Launch app
2. Launch app
3. Launch app
4. "LibreTube keeps stopping"

### Expected behavior

The app should launch

### Actual behavior

The app crashes

### LibreTube version

0.7.0

### Android version

Android 13

### Other details

I have no idea where to find an error log or anything. The app just crashes on launch.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Mrnofish** [comment]
Take a looksee at the pinned issue #1551

**Comment by akano12** [comment]
Clear app data

**Comment by Hate9** [comment]
Oh weird. I reinstalled the app, but I guess it didn't clear the appdata when I did.
