### ISSUE TITLE
Feature: Add timestamps to video chapters

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#1747]
### Describe your suggested feature

As of current implementation, LT shows video chapters very well, but it don't have timestamps for which users need to jump to the part of the description to check which chapter is at which timeline.

It would be a good addition to have timestamps on/beside chapters itself, both in portrait and landscape layout :)

### Other details

Reference image:
> ![Screenshot_20221104-091317](https://user-images.githubusercontent.com/87353286/199880931-1a888bb0-7a4f-4765-8043-2d5f856c6040.png)
---
> ![Screenshot_20221104-091306](https://user-images.githubusercontent.com/87353286/199880944-310c83c5-9e5a-4099-8701-1eaa264dea38.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by shantanu1k** [comment]
The issue #1383 may have the same solution 🙃

**Comment by VedxP** [comment]
> The issue #1383 may have the same solution 🙃

+ ➕ Make timestamps in description clickable too :)
