### ISSUE TITLE
Library Tab: Display Count of Videos in Playlists

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#1748]
### Describe your suggested feature

Display the count of videos in playlists (cloned) in Library tab as it's there in Channel Playlists Tab.

Preferably, use the same layout for Playlists in **Library Tab** as it's there in **Channel Playlists Tab**.

### Other details

Reference image:

### Channel Playlists Tab having count
> ![Screenshot_20221104-092334~2](https://user-images.githubusercontent.com/87353286/199882616-2cdc4500-53c2-459c-abd7-eb7f4eebd98a.png)
---
### Playlists in Library tab without count of videos
> ![Screenshot_20221104-092443~2](https://user-images.githubusercontent.com/87353286/199883039-680c1472-e1fc-4cac-a1ae-9193ac548407.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The API doesn't support it.

**Comment by VedxP** [comment]
@Bnyro but, it's there on Piped:
> ![Screenshot_20221104-130650](https://user-images.githubusercontent.com/87353286/199918414-360af5e9-1e87-42e2-aab3-dd27d0d80977.png)

**Comment by Bnyro** [comment]
Oh, right, I forgot there was a recent commit that added support for it!

**Comment by VedxP** [comment]
👍
