### ISSUE TITLE
Show Success Toast ft. Cloning Playlist

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#1749]
### Describe your suggested feature

Currently, the UI does nothing when **Clone Playlist** button is tapped.

### Other details

Reference Image:
> ![Screenshot_20221104-092634](https://user-images.githubusercontent.com/87353286/199883322-7f6b1d24-5073-435e-9116-0e66165bc0c4.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by shantanu1k** [comment]
Hi @VedxP , can you please tell me which instance you are using? I am not able to login & tried many instances to replicate `clone playlist` 😅

**Comment by VedxP** [comment]
> Hi @VedxP , can you please tell me which instance you are using? I am not able to login & tried many instances to replicate `clone playlist` 😅

😆

Btw, I'm using `kavin.rocks`

**Comment by Bnyro** [comment]
> Hi @VedxP , can you please tell me which instance you are using? I am not able to login & tried many instances to replicate `clone playlist` sweat_smile
>
Should work for any playlist if you're logged in!
