### ISSUE TITLE
Hide videos from subscription tab

### ISSUE THREAD

**Issue by fpue** [libre-tube/LibreTube#1751]
### Describe your suggested feature

Problem:
By default, the subscription tab gets filled up with new videos. If not watched in order, it gets quite messy to keep track which videos are not yet watched.

Solution:
Make it possible to hide videos from the subscription tab. 

Bonus:
Hide watched videos by default.

### Other details

This kind of feature does already exist in NewPipe, maybe the implementation there can be "inspiring"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
One idea (I'm not a fan of different thumbnails or hidden videos from a visual point of view):
Reduce the size of the thumbnail of already watched videos, maybe when the remembered position is at 95% of the time, then the video can also be marked as finished.

**Comment by dimqua** [comment]
Ideally the progress should be synchronized with Piped when the first option is enabled in users' accounts
![](https://user-images.githubusercontent.com/540898/208221748-54c37da0-c76b-444e-bae7-3450b19069fd.png)
