### ISSUE TITLE
Save subscription feed and library

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#1753]
### Describe your suggested feature

Save subscription feed and library after closing the app (force stop, smartphone restart, etc.).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That'd require to store the data in the App's database which doesn't make sense for data that could be changed after a reboot as the feed and the library could!

**Comment by xIUPITERx** [comment]
Then could you add an load in the background EU too for.the library, so it doesn't always refresh if you open the library tab?
