### ISSUE TITLE
Fully open the settings sheets in fullscreen mode

### ISSUE THREAD

**Issue by yhm4ps1jfp67nkv** [libre-tube/LibreTube#1756]
### Describe your suggested feature

Currently if you are in the fullscreen mode, after tapping the down arrow to open the settings sheet you have to swipe it up to use it. If it fully opened from the start, the user wouldn't have to make an additional swipe

### Other details

The same thing happens with the menus inside the sheet (like the Playback speed menu) - after tapping them, you have to make an additional swipe to use them

In non-fullscreen mode the sheets open as they should

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by VedxP** [comment]
Yup, bottom sheeets in landscape mode could be expanded by either 50% or 80% of the screen height by default.

So, users don't have to swipe the sheet every time to access anything :)

**Comment by Bnyro** [comment]
I'm still a fan of how it is at the moment as one's still able to see most of the video but I'm probably alone with that :/

**Comment by yhm4ps1jfp67nkv** [comment]
Thanks for implementing it, however now if you swipe the sheet down it will go to the "opened but unexpanded" state which is pretty much useless now, could you please make it so that it just closes when swiped down?

**Comment by Bnyro** [comment]
> Thanks for implementing it, however now if you swipe the sheet down it will go to the "opened but unexpanded" state which is pretty much useless now, could you please make it so that it just closes when swiped down?
> 
That's not possible afaik, the behavior is provided by the Material design library, we don't have influence on it.

> Edit: also, the settings menus inside the main sheet still open unexpanded
>
Mb, added it to those as well now!

**Comment by VedxP** [comment]
@Bnyro 

- Play video in full-screen
- Open Video Settings Sheet 
- The sheet doesn't cover the entire height, a little strip remains uncovered at the top until you swipe up the sheet.
- Irony is, Playing Queue Sheet doesn't have any such issue.

Here's recording:

https://user-images.githubusercontent.com/87353286/200170417-8c942829-4881-4673-bc65-bdd5cd3a7374.mp4

**Comment by Bnyro** [comment]
Can't reproduce, it might depend on the screen size. However, it shouldn't be an issue though

**Comment by VedxP** [comment]
Hmm, @yhm4ps1jfp67nkv can you confirm the above issue I reported?

**Comment by Bnyro** [comment]
We can't just expand it to a height of 80 per cent though, we only got three states to choose from programmatically: invisible, minified and 100% expanded

**Comment by VedxP** [comment]
> We can't just expand it to a height of 80 per cent though, we only got three states to choose from programmatically: invisible, minified and 100% expanded

Hmm, got it.

Just worried that the Playing Queue sheet doesn't show the same behaviour video settings sheet does, as reported above.

**Comment by yhm4ps1jfp67nkv** [comment]
> Hmm, @yhm4ps1jfp67nkv can you confirm the above issue I reported?

Nope, works fine for me on the latest Debug build (I tried the resolution submenu since I'm using a larger screen and the main menu is not "touching" the top of it at all)

**Comment by VedxP** [comment]
It's working as expected, but @Bnyro is it possible to set the sheet for Playing Queue to `minified` in vertical mode only?

Cuz, if it's set to expand, it fills the entire height and is not easy to do actions with one hand.

**Comment by Bnyro** [comment]
> It's working as expected, but @Bnyro is it possible to set the sheet for Playing Queue to `minified` in vertical mode only?
>
Yeah, of course that's possible!
Please open a new issue for it, otherwise I'll just forget that!

**Comment by akano12** [comment]
> > It's working as expected, but @Bnyro is it possible to set the sheet for Playing Queue to `minified` in vertical mode only?
> >
> Yeah, of course that's possible!
> Please open a new issue for it, otherwise I'll just forget that!
> 

Hands down the most annoying change ever made, really liked the previous one and wish you could bring it back :(

**Comment by akano12** [comment]
> @Bnyro 
> 
> - Play video in full-screen
> - Open Video Settings Sheet 
> - The sheet doesn't cover the entire height, a little strip remains uncovered at the top until you swipe up the sheet.
> - Irony is, Playing Queue Sheet doesn't have any such issue.
> 
> #### I would recommend not to expand bottom sheets taking entire height, instead make it expand to 80% of the available height.
> 
> #### Here's screenshot, see at the top:
> >  ![Screenshot_20221106-175351](https://user-images.githubusercontent.com/87353286/200170584-f06d2a46-aa17-4f4f-b33f-a983cc96c9e7.png)
> 
> 
> #### Here's recording:
> 
> https://user-images.githubusercontent.com/87353286/200170417-8c942829-4881-4673-bc65-bdd5cd3a7374.mp4
> 
> 

Ye same here, there's a small part in the screen that is uncovered

**Comment by Bnyro** [comment]
> Hands down the most annoying change ever made, really liked the previous one and wish you could bring it back :(
>
I agree with you, I'll probably add an option somewhere to restore the old behavior ;)
