### ISSUE TITLE
Move Channel Description to `About Tab`

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#1779]
### Describe your suggested feature

Add another tab in channel page of `About` section, giving more space to videos and would be consistent to the channel page having Tabs for navigation :)

### Other details

![Screenshot_20221106-181237](https://user-images.githubusercontent.com/87353286/200171597-7ad77d5c-58d4-4f4e-ab26-ee71d5090e1b.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I'm not of that opinion for two reasons
1. The description sometimes can be only one or two lines so having an extra tab for it would be worthless
2. The description is already shrinked to two lines by default and thus shouldn't be annoying or disturbing in any way.

**Comment by VedxP** [comment]
> I'm not of that opinion for two reasons
> 
> 1. The description sometimes can be only one or two lines so having an extra tab for it would be worthless
> 2. The description is already shrinked to two lines by default and thus shouldn't be annoying or disturbing in any way.

You've a valid point, leaving it as it is for now would be better then :)
