### ISSUE TITLE
Playlist: Trim Long Text

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#1780]
### Describe your suggested feature

Trim long text of playlists, having a visual hierarchy and consistent design :)

### Other details

> ![Screenshot_20221106-180245](https://user-images.githubusercontent.com/87353286/200171796-4e870e8c-87b2-457e-8316-6fba95e41549.png)

> ![Screenshot_20221106-182038](https://user-images.githubusercontent.com/87353286/200171819-fe22de36-5ca3-495b-b208-a7db7b7f35a0.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by VedxP** [comment]
@Bnyro text still overflowing

- And, in released version 0.7.0, channel name is below the Playlist title which is better.
- But in latest debug version, channel name is at the top, which doesn't look that good :(
---
> Screenshot from debug version showing text overflow highlighted with red

> And the channel name is at the top, current one in v0.7.0 is better having the channel name below the title.

![Screenshot_20221106-203132~2](https://user-images.githubusercontent.com/87353286/200178394-5ada24f5-5aeb-410e-88ff-6eaa5d7b75e7.png)

**Comment by Bnyro** [comment]
The question is what I actually changed then, hmm

**Comment by Bnyro** [comment]
I fell a bit lost today ...

**Comment by VedxP** [comment]
> The question is what I actually changed then, hmm

😆

**Comment by VedxP** [comment]
@Bnyro Above mentioned issue solved :)

But, the title is trimmed when playlist is opened too, so the complete title can't be seen by any way.

Can you make it to not trim the title when playlist is opened?

Screenshot:
![Screenshot_20221107-103230](https://user-images.githubusercontent.com/87353286/200230502-548e4cdd-fb89-4095-beb8-79651bd19805.png)

**Comment by FireMasterK** [comment]
What I would suggest instead would be able to tap to expand the whole title.

**Comment by Bnyro** [comment]
Should work as Kavin suggested now :P
