### ISSUE TITLE
Alternative Videos Layout: Items Overflowing

### ISSUE THREAD

**Issue by vedxp** [libre-tube/LibreTube#1786]
### Steps to reproduce

- Play any video 
- Scroll through the recommended videos 
- Some items seems overflowing

- Same can be seen in home and subscription tab too

### Expected behavior

It should not overflow.

#### Screenshot from latest debug version:
---
- Video Page
>  ![20221107_105025](https://user-images.githubusercontent.com/87353286/200232416-136390de-6dae-4c91-828a-884ceea7ce7a.jpg)

- Home Tab
> ![Screenshot_20221107-105534~2](https://user-images.githubusercontent.com/87353286/200232899-e7fd3728-36ce-48cd-aa23-9523c51d4251.png)

### LibreTube version

1667749835 Debug

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
So what would you suggest?

**Comment by VedxP** [comment]
> So what would you suggest?

1. Reducing the font size of `View Count`  `Upload Date` `Channel Name` and reducing the size of `Channel Logo` would free up some space preventing the items at the bottom from overflowing; but I'm not sure if it'll look that good.
2. Limiting the `Video Title` to single line only would too do the job done, but doing so will result in having white spaces throughout the UI.
3. Last one, increasing the size of video thumbnails a little bit only, so that it gets aligned with the items currently overflowing, solving the problem.

**Comment by VedxP** [comment]
@Bnyro Update, lol I missed it:

- Just make the thumbnail align with the items at right, outlined with green:
>  
![20221107_202323](https://user-images.githubusercontent.com/87353286/200341182-090f0b30-0da2-455d-b56c-db0e89fd6950.jpg)

**Comment by VedxP** [comment]
@Bnyro still same :(
 - Above approach is better ☝️

>  ![Screenshot_20221108-073040~2](https://user-images.githubusercontent.com/87353286/200460893-c6bfe50d-a458-4685-804a-490d708785da.png)

**Comment by Bnyro** [comment]
Damn, I decreased the avatar size but obviously not enough...

**Comment by VedxP** [comment]
> Damn, I decreased the avatar size but obviously not enough...

Don't decrease the Avatar size, instead align the items as I showed in above comments.

It'll fix the overflowing, cuz currently, the items at right start a little down that of thumbnail and that's why they get overflowed at bottom.

**Comment by VedxP** [comment]
> @Bnyro Update, lol I missed it:
> 
> * Just make the thumbnail align with the items at right, outlined with green:
> 
> > 
> 
> ![20221107_202323](https://user-images.githubusercontent.com/87353286/200341182-090f0b30-0da2-455d-b56c-db0e89fd6950.jpg)

@Bnyro like this

**Comment by Bnyro** [comment]
No, not doing so was my intention as center-aligning them makes it look inconsistent, we need to align the thumbnail and the title to the top in my opinion!

**Comment by VedxP** [comment]
> No, not doing so was my intention as center-aligning them makes it look inconsistent, we need to align the thumbnail and the title to the top in my opinion!

That is what I meant to say :)
Seems you misunderstood cuz of below lines I added, my bad :(

**Comment by Bnyro** [comment]
Fair, we can try that 👍

**Comment by Bnyro** [comment]
Closing this for now as it already got improved by decreasing the channel icon size, no plans to do anything else currently.
