### ISSUE TITLE
When you are logged in and you tap on the Login/Register button it  shows  () at the end 

### ISSUE THREAD

**Issue by jeffdumcum** [libre-tube/LibreTube#179]
### Steps to reproduce

First, log in, then, tap on the button to log in again

### Expected behavior

The sentence should be like this 'Already logged in. You may log out of your account.'

### Actual behavior

At the end of the sentence it shows ()

### LibreTube version

Latest

### Android version

Android 13 Tiramisu

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [ ] I will fill out all of the requested information in this form.

**Comment by lilcheti** [comment]
Logout and login again it shows your username
