### ISSUE TITLE
It doesn't show the thumbnails

### ISSUE THREAD

**Issue by rzasharifi** [libre-tube/LibreTube#1790]
### Steps to reproduce

1. open the app
2. go to the middle tab
3. there are videos with infos, but there is no thumbnail

### Expected behavior

Show a preview or if "data saver" is being "on" it just shows a thumbnail.

### Actual behavior

It just shows a blank view!

### LibreTube version

0.7.0

### Android version

and 12/ xiaomi note 11, 2201117TG

### Other details

![image](https://user-images.githubusercontent.com/64254187/200386996-bfa5bfbf-f58d-421d-a745-56767163e7f8.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
When in data saver mode, no thumbnails will be loaded and hence it looks as in your screenshot. If the data saver mode is disabled it's either an issue of the Piped proxy or with a higher probability your internet.
