### ISSUE TITLE
Proxy Socks 5 or http

### ISSUE THREAD

**Issue by rzasharifi** [libre-tube/LibreTube#1791]
### Describe your suggested feature

Because of the censorship in some countries, could you please add proxy feature? 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by rozari0** [comment]
> ### Describe your suggested feature
> 
> Because of the censorship in some countries, could you please add proxy feature?
> ### Other details
> 
> _No response_
> ### Acknowledgements
> 
>     * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> 
>     * [x]  I have written a short but informative title.
> 
>     * [x]  I will fill out all of the requested information in this form.

Bruh, you are already you are already using piped. 😐

**Comment by FireMasterK** [comment]
Some instances, such as `kavin.rocks` are unfortunately blocked in some countries unfortunately.

**Comment by rozari0** [comment]
> Some instances, such as `kavin.rocks` are unfortunately blocked in some countries unfortunately.

Oh wow, w-tf. 🤦‍♂
My imagination is limited I think.

**Comment by Bnyro** [comment]
Proxying would have to be implemented for three different parts of the app:

1. General requests, done via Retrofit, fan be proxied via OkHttp
2. Image Requests, done via Coil
3. The player, namely the `ExoPlayer`

As we're using Cronet for all of them other additional steps might be needed to make it work properly as well.

As there should be at least one not-blocked instance everywhere available around the word, at least I think so, I don't think it'd be worth it now as it'd have to be spread over too many individual components, thus giving it a low priority and adding the help wanted label.
