### ISSUE TITLE
SponsorBlock Support

### ISSUE THREAD

**Issue by FireMasterK** [libre-tube/LibreTube#18]
This is a nice to have, Piped's API supports proxying this (the K-Anonymity model is followed when requesting data from sponsor.ajay.app).
For example: https://pipedapi.kavin.rocks/sponsors/EE4OCYOLjBc?category=%5B%22sponsor%22%2C%22interaction%22%2C%22selfpromo%22%2C%22music_offtopic%22%5D

**Comment by rimthekid** [comment]
I'll add to projects
