### ISSUE TITLE
Separate auto play option for playlists

### ISSUE THREAD

**Issue by terminal-cs** [libre-tube/LibreTube#1810]
### Describe your suggested feature

It would be nice to be able to have a separate option for autoplay in playlists. YouTube will automatically play the next video in the current playlist

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I'm not really sure about that since users can add new videos to the queue, shuffle or clear it after starting to play a playlist and thus it's not really clear what counts as playlist and what doesn't.

**Comment by terminal-cs** [comment]
> I'm not really sure about that since users can add new videos to the queue, shuffle or clear it after starting to play a playlist and thus it's not really clear what counts as playlist and what doesn't.

When I open a playlist and click a video from it, the player shows it as being from a playlist via a button in the top right corner

**Comment by Bnyro** [comment]
> When I open a playlist and click a video from it, the player shows it as being from a playlist via a button in the top right corner
>
Did you already try it with a normal video as well? :joy:

**Comment by terminal-cs** [comment]
> > When I open a playlist and click a video from it, the player shows it as being from a playlist via a button in the top right corner
> 
> Did you already try it with a normal video as well? joy

yes? why would it show a completly unrelated playlist

**Comment by Bnyro** [comment]
It adds related videos to the queue...

**Comment by terminal-cs** [comment]
> It adds related videos to the queue...

i am not talking about related videos. i am talking about the playlist

**Comment by Bnyro** [comment]
Well, the user can modify the queue after starting to play a playlist so when is it still a playlist and when is it already a normal queue?
In the end we can only determine whether a video got started from inside a playlist, but if the queue got modified should it still count as playlist or as video then?

**Comment by terminal-cs** [comment]
> Well, the user can modify the queue after starting to play a playlist so when is it still a playlist and when is it already a normal queue? In the end we can only determine whether a video got started from inside a playlist, but if the queue got modified should it still count as playlist or as video then?

yep, but really it shouldn't update the playlist if it's already playing like in youtube

**Comment by xIUPITERx** [comment]
Spotify implements this by having two separate lists.
1. the queue (the songs that you add manually. They are not changed by shuffling).
2. the playlist (the order of the songs is changed by shuffling).
When the playlist is finished, it's refilled with the recommended songs.

![Screenshot_20221126-165256_Spotify.jpg](https://user-images.githubusercontent.com/97352673/204097448-57447799-6a57-4ef3-92d5-5277c950bd77.jpg)

It could be implemented with 3 dynamic lists.
(0. Current video)
1. the queue (play next, add to queue) -> first separate autoplay setting
2. the playlist -> second separate autoplay setting
3. featured videos -> third separate autoplay setting
Shuffling etc. should only affect 2. and 3.

**Comment by Bnyro** [comment]
Not planned currently, simply because users can modify the queue while viewing a playlist.
