### ISSUE TITLE
Descargador

### ISSUE THREAD

**Issue by Jose14** [libre-tube/LibreTube#1813]
### Describe your suggested feature

I wish the app could download multiple videos, that is many at once

### Other details

How to download albums, playlists, etc

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FireMasterK** [comment]
English, please. We don't understand Spanish, sorry.

**Comment by Bnyro** [comment]
Unfortunately, downloads are currently not stable enough to consider allowing to download multiple videos at once.
