### ISSUE TITLE
YouTube 

### ISSUE THREAD

**Issue by 5678aaaA** [libre-tube/LibreTube#1814]
### Describe your suggested feature

https://github.com/libre-tube/LibreTube/blob/de7f3b2fba5579782b066c4591d6bcb4245f3b34/.gitattributes

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [ ] I will fill out all of the requested information in this form.

**Comment by FireMasterK** [comment]
???
