### ISSUE TITLE
New Player UI View

### ISSUE THREAD

**Issue by salvatoref99** [libre-tube/LibreTube#1815]
### Describe your suggested feature

Having a few alternative Player UI Views would be awesome, It will also be a massive workaround for the blurry thumbnails that come up under the current playing video. I created two alternative UI views which look real nice, keeping with the overall UI of the app the same and you can find my mockups attached. Again by doing this it does also fix a current issue that has been mentioned before in previous tickets so its kinda a win win work around. Hopefully something like this can be implemented because it will hugely improve the current player UI.  Also could we please get a full screen button in the player when we have auto full screen active as sometimes it doesn't work. 

![LibreTube Alternative View 1](https://user-images.githubusercontent.com/118034225/201453867-262338fa-dc43-4e00-b314-3fc8c3a8c7ca.png)
![LibreTube Alternative View 2](https://user-images.githubusercontent.com/118034225/201453872-b84785cd-2d14-484c-b96e-440a5a074b71.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thanks for your work on those drafts, they are both really awesome!
The second suggestion can now be achieved by changing the amount of grid columns in the appearance settings, I'll work on the first one as an option before the next release (that'll probably arrive soon) as I would probably use it myself then :)
I'm not sure whether your drafts were implemented in code or just design drafts, if you already implemented the first layout a pull request would be appreciated, if not it's fine as well, implementation won't be hard.
Cheers

**Comment by salvatoref99** [comment]
Hey Bnyro, Unfortunately these mockups were just design drafts. Thanks so much for implementing this, the app is Awesome!
