### ISSUE TITLE
Duplicate Upload Date in Channel Page

### ISSUE THREAD

**Issue by vedxp** [libre-tube/LibreTube#1818]
### Steps to reproduce

- Open any channel, which gets video uploaded at least weekly 
- Scroll through videos 
- Many videos' upload date is same, while in actual, if you play the video then it'll show the correct date.

### Expected behavior

.

### Actual behavior

Seems, upload date gets cloned to videos.

### LibreTube version

0.7.0 & Latest Debug

### Android version

Android 12

### Reference screenshots:
> ![Screenshot_20221112-185059](https://user-images.githubusercontent.com/87353286/201476589-ca892929-b48c-4867-b60e-d5ad245c1227.png)
![Screenshot_20221112-185115](https://user-images.githubusercontent.com/87353286/201476634-d5270d58-c76f-4653-a891-0286d8d84cc2.png)
![Screenshot_20221112-185130](https://user-images.githubusercontent.com/87353286/201476661-4dcd4f86-c57a-4f29-a0d9-d5967b54500b.png)
![Screenshot_20221112-185152](https://user-images.githubusercontent.com/87353286/201476675-a36965c8-12ad-427a-80c7-26804ee20595.png)
![Screenshot_20221112-185205](https://user-images.githubusercontent.com/87353286/201476683-5a72ee95-8760-464f-bb27-f617d9c0d66a.png)
![Screenshot_20221112-185214](https://user-images.githubusercontent.com/87353286/201476702-a6e7a628-6bea-4a93-aeab-1c89721f48c1.png)
![Screenshot_20221112-185221](https://user-images.githubusercontent.com/87353286/201476741-e4be0d5a-5b6c-48bf-b59d-d955405902a0.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Seems to be a bug in the NewPipe Extractor, Piped solves it by showing the time since it was uploaded, e.g. "2 years ago" instead of the date, maybe we should do so as well!

**Comment by VedxP** [comment]
> Seems to be a bug in the NewPipe Extractor, Piped solves it by showing the time since it was uploaded, e.g. "2 years ago" instead of the date, maybe we should do so as well!

Yup, that would be better in my opinion :)

Screenshot from YT web showing the same:
> ![Screenshot_20221112-192031](https://user-images.githubusercontent.com/87353286/201477308-94b8a9c4-4ad3-46f1-b5c9-f78a2702e770.png)

**Comment by Bnyro** [comment]
Hmm, the Java `DateUtils.getRelativeTimeSpanString()` seem to format it as a full date when the time difference is greater than a week, I can't find a way to force it to always use a relative time span.
@FireMasterK Any idea what we could do to prevent that behavior?

**Comment by farline99** [comment]
Same here, frustrating thing.

**Comment by eightyy8** [comment]
@Bnyro the date is still not indicating the right time, and it sometimes gets the month wrong even. (GrapheneOS A13, running the latest 0.12.0)

**Comment by Bnyro** [comment]
By latest you mean the latest release? Please compare the date of the PR and the date of the latest release. Apart from that, please don't tage me (as mentioned in our code of conduct).

**Comment by eightyy8** [comment]
> Compare the date
> Code of Conduct

I missed that, sorry for wasting your time. and I'll look over the rules next.

But also could you make a pre-release of sorts? So users can test these changes, instead of waiting for the next release - because if you add features, bugs are bound to come along and prolong each version.
