### ISSUE TITLE
Suggestion: Sharing With Time Code 

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#1819]
### Describe your suggested feature

As of current implementation, LT shows an option to `Share with time code` with the ability to edit the time code.

Which in practical, isn't productive/friendly, as the user has to convert the time code from `Hours` `Minutes` and `Seconds` to **Seconds** only.

#### Suggestion:
- There's no such need to have that option to change the time code while sharing as if someone wants to share a video starting with 2 minutes and 30 seconds, he'll definitely tap the share button from that particular time only, if I'm not wrong.
- So, there should be no any crucial reason to have that feature.

### Other details

Reference screenshot:
> ![Screenshot_20221110-190553](https://user-images.githubusercontent.com/87353286/201477864-191e66bc-6a10-4cae-a3da-0240eade3ba6.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Well, in my opinion, if somebody doesn't need it the person just shouldn't use it.
There's no reason to remove a feature others potentially use. It was added after a feature request, so there's at least one other person than me that uses the feature :)

**Comment by VedxP** [comment]
> Well, in my opinion, if somebody doesn't need it the person just shouldn't use it. There's no reason to remove a feature others potentially use. It was added after a feature request, so there's at least one other person than me that uses the feature :)

Hmm, that's what I was not much aware of, thanks for the reply :)

Btw, can you make the latter feature use more friendly words?

Like instead of `Share with time code`, something like `Start the video with`

And `Seconds` instead of `Time Code` at the top of text input area.

**Comment by Bnyro** [comment]
> And `Seconds` instead of `Time Code` at the top of text input area.
>
I'm not really a fan of changing the strings as I think that the current ones are self-explanatory. Maybe we can change `Time code` to `Time code (seconds)`, but I wouldn't want to change it more.
