### ISSUE TITLE
Use cronet for API requests too

### ISSUE THREAD

**Issue by FireMasterK** [libre-tube/LibreTube#182]
https://github.com/google/cronet-transport-for-okhttp/blob/master/README.md

**Comment by lilcheti** [comment]
That's why we are slower than the web version?

**Comment by FireMasterK** [comment]
It should make a good difference on slow connections. We can also use this for loading images, which should make them load faster

**Comment by lilcheti** [comment]
Can we make thumbnail images quality better too?
