### ISSUE TITLE
Quick shortcuts not working

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#1825]
### Steps to reproduce

- Long press LT from app drawer
- Tap subscription/library tab 
- It'll open home tab only

### Expected behavior

It should open the respected tabs when clicked from shortcuts.

### Actual behavior

No matter which tab you choose to open from shortcuts, it always opens the home tab.

### LibreTube version

Latest Debug

### Android version

Android 12

### Other details

![Screenshot_20221112-230931](https://user-images.githubusercontent.com/87353286/201487485-797a4d62-0eee-4556-8919-947cec6f1474.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
see https://github.com/libre-tube/LibreTube/issues/1738#issuecomment-1305967868
