### ISSUE TITLE
Videos & Playlists tabs only are there in channel page

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#1830]
### Steps to reproduce

.

### Expected behavior

It should show all the tabs available including `channels` and `shorts` tab, as it was there in version 0.7.0.

### Actual behavior

After the update 0.7.1, it shows `videos` and `playlists` tabs only :(

### LibreTube version

0.7.1

### Android version

Android 12

### Other details

![Screenshot_20221113-091507](https://user-images.githubusercontent.com/87353286/201504730-9571d439-a281-4a17-ada2-b94496a5edeb.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by VedxP** [comment]
#### Edit: LT displays `playlists` tab even if the channel don't have any playlists.
#### Not sure if it was the same in 0.7.0
---
Reference screenshot:
> ![Screenshot_20221113-095046](https://user-images.githubusercontent.com/87353286/201505601-4e3b63f9-6c90-4aa3-8be3-e1b32f6f088e.png)
![Screenshot_20221113-095052](https://user-images.githubusercontent.com/87353286/201505606-8b81efdc-8957-4f5d-a97e-8e65b7327486.png)

**Comment by Bnyro** [comment]
#1829
