### ISSUE TITLE
Search icon gets invisible

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#1834]
### Steps to reproduce

- Open LT 
- Open search bar
- Tap on three dots menu
- Tap on `search` from the available options 
- Come back to home tab/close the search bar 
- The search icon won't show up now, until you close and reopen LT

### Expected behavior

There should be no `search` option in menu.

### Actual behavior

The menu adds an extra item `search` which is causing the issue.

### LibreTube version

0.7.1

### Android version

Android 12

#### Reference screenshots, put sequentially as written in the steps above:
---
## Open LT
> ![Screenshot_20221113-185932](https://user-images.githubusercontent.com/87353286/201524428-e45c6800-66ae-441e-a9b7-49daa4a4497f.png)
## Open search bar
> ![Screenshot_20221113-185936](https://user-images.githubusercontent.com/87353286/201524440-78eb9e66-8946-4203-bebb-3f5a0fa36245.png)
## Tap on three dots menu and click on search
> ![Screenshot_20221113-185939](https://user-images.githubusercontent.com/87353286/201524441-8cf3bc64-b14d-4d5b-bdb1-b0fe2bffc8f4.png)
## Go to home tab/close the search bar
>![Screenshot_20221113-185947](https://user-images.githubusercontent.com/87353286/201524444-ff3604a8-9bc2-4be2-b941-c83dcf05d362.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Tap the back button 2-3 times and it'll appear
