### ISSUE TITLE
limit thumbnail cache to runtime

### ISSUE THREAD

**Issue by asklow** [libre-tube/LibreTube#1838]
### Describe your suggested feature

I've made `@APPDATA@/files/coil` read only through root explorer to block thumbnail generation & the app became super snappy.

Thumbnail caching on storage media affects app performance a lot. Providing an option to limit thumb cache to runtime (memory), would be great. Because physical memory is always 10x faster than internal storage.

I'm sure thumb cache isn't necessary, as most users never revisit the older timeline multiple times. Even if they do, it wouldn't take much data & processing to reload those.

### Other details
I've researched a little bit about runtime mounts (tmpfs) on Android. But it's not possible although the Android file system is similar to Linux.

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
If you didn't know yet debug builds can be found at https://github.com/libre-tube/LibreTube/actions/runs/3489779649.
To be honest I doubt it makes much of a difference haha
