### ISSUE TITLE
Can't change audio track

### ISSUE THREAD

**Issue by 2468-13579** [libre-tube/LibreTube#1841]
### Steps to reproduce

Play video with multiple audio tracks. For example MrBeast's newest video https://www.youtube.com/watch?v=kX3nB4PpJko.

### Expected behavior

Play English track by default and give option to change the audio track.

### Actual behavior

It plays the Arabic track (presumably because it's the first alphanumerically), with no option to change it.

### LibreTube version

0.7.0

### Android version

Android 11

### Other details

I know I'm not using the most recent version, but it's not on F-Droid yet and this is not mentioned in the patch notes.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by C0D3D3V** [comment]
I also noticed this a while ago with old videos from MrBeast that got additional Arabic audio tracks, but I didn't care too much about it, but now new videos are getting multiple audio tracks too, so it's important to me as well. A menu with which you could select the audio tracks would be amazing.

**Comment by FireMasterK** [comment]
https://github.com/TeamNewPipe/NewPipeExtractor/pull/973
