### ISSUE TITLE
Sort videos by upload date

### ISSUE THREAD

**Issue by popogomo** [libre-tube/LibreTube#1843]
### Describe your suggested feature

When app displays search results, we should have an option to sort the results by upload date, relevance and popularity, just like in original Youtube app or Vanced.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
No API support currently and therefore not possible at the moment!
