### ISSUE TITLE
No more shorts

### ISSUE THREAD

**Issue by ARBoyGo** [libre-tube/LibreTube#1846]
### Steps to reproduce

Before we had shorts in channel as a sort but it's no more visible, Hope it was a mistake or something.
If it's intended, There is no difference with Newpipe, It was a plus feature over Newpipe. I'm not saying like competition, I watch shorts in LibreTube mainly. I use both, They are best in their ways. 

### LibreTube version

0.7.1

### Android version

12

### Before this update

![IMG_20221114_231109](https://user-images.githubusercontent.com/69381592/201729615-025bebae-3086-4aed-a3d7-f222e62c091b.jpg)

### New update
![IMG_20221114_231152](https://user-images.githubusercontent.com/69381592/201729853-cb7ef707-9a83-4e1b-9fe0-fd76ddfda62a.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
fixed with #1829
