### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by MJYusefi** [libre-tube/LibreTube#185]
### Steps to reproduce

1. Open the app 
2. see the home page is empty

### Expected behavior

Home page should  show trend videos

### Actual behavior

This doesn't show anything!
![Screenshot_20220507-224951_LibreTube](https://user-images.githubusercontent.com/92368017/167267611-da4738d9-f639-4e5f-9864-1e3cc94e0e8a.jpg)

### LibreTube version

0.2.7

### Android version

Android 11

### Other details

Device model : Galaxy A71

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Which region and which instance are you using?

**Comment by MJYusefi** [comment]
Iran, tokhmi.xyz

**Comment by lilcheti** [comment]
Yea Iran won't work change the region to somewhere that Youtube is not banned :)
