### ISSUE TITLE
Timestamp doesn't work in any videos

### ISSUE THREAD

**Issue by MithNo1** [libre-tube/LibreTube#1865]
### Steps to reproduce

Timestamp isn't click able so is not working. If I'm not sure if this is a bug or this feature does not exists. As I have moved recently from NewPipe to LibreTube but I think this is very important feature that should be present or fixed for any YouTube client. 

### Expected behavior

Timestamp should work

### Actual behavior

Fix it thank you :)

### LibreTube version

0.7.1

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by VedxP** [comment]
LibreTube does have video chapters feature already.

You probably meant the timestamps in description and comments, which isn't clickable as of now :)

**Comment by MithNo1** [comment]
Fixed thank you. I stick using chapters feature for now! Cheers!

**Comment by VedxP** [comment]
> Yes that @VedxP please add that :) should not be that hard. But a very useful feature indeed

I'm not the dev lol :)

- You can keep the issue opened so that the progress of the same can be tracked :)
