### ISSUE TITLE
Missing tabs (e.g. livestreams) on channel page

### ISSUE THREAD

**Issue by kovdan01** [libre-tube/LibreTube#1869]
### Steps to reproduce

Go to a page of a channel which is known to have some livestreams, playlists, etc. For me the issue reproduces on all the channels.

### Expected behavior

Above the video list, we expect to see some tabs like videos, livestreams, playlists. That is how it worked before.

### Actual behavior

Only some tabs are shown (see the screenshot attached).

![Screenshot_20221117-002123_LibreTube_1](https://user-images.githubusercontent.com/23102040/202298558-41cd4cc7-6050-4b26-84bd-533bccd8b7a5.png)

For some instances (including kavin.rocks), only Videos tab is shown. For others, Playlists is shown as well. I was unable to find an instance with Livestreams tab displaying. The issue looks LibreTube-related (not Piped-related) because in a browser the tabs work perfectly (for different instances and with cookies cleared, so it's not because of the browser cache).

### LibreTube version

0.7.1

### Android version

Android 11 (LineageOS 18.1)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
There was a recent change in the NewPipeExtractor and thus also the Piped API which caused them to break in LibreTube.
However, the latest debug builds already contain support for the latest API changes.

**Comment by kovdan01** [comment]
Thanks!
