### ISSUE TITLE
watch history not synced with other android instances

### ISSUE THREAD

**Issue by slhx99** [libre-tube/LibreTube#1872]
### Steps to reproduce

Added LibreTube on two android devices and synced to the same Piped account.

### Expected behavior

Watch history to sync between the two when watching videos after logging into Piped.

### Actual behavior

Watch History is only saved in the local devices and not synced across one another

### LibreTube version

0.7.1

### Android version

Android 9, Android 12

### Other details

Don't know whether it's an issue with Piped or LibreTube, but does anyone know how to sync watch history?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not possible yet as there's no API support at Piped for it currently.

**Comment by slhx99** [comment]
Ah I see, thanks so much!
