### ISSUE TITLE
Allow to save playlist without logging in

### ISSUE THREAD

**Issue by popogomo** [libre-tube/LibreTube#1874]
### Describe your suggested feature

Currently the app requires us to log in order to create playlists.
Can you please allow us to do so without logging in? Thanks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Dupe of #969
