### ISSUE TITLE
Zoom gesture

### ISSUE THREAD

**Issue by Pentaphon** [libre-tube/LibreTube#188]
### Describe your suggested feature

Would be nice to double tap the center of the player to zoom the video player when you have a widescreen video, for example. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by rakibdev** [comment]
Or pinch to zoom. Double tap gesture for going fast forward, backward. And showing video widescreen by default (can be added as option in settings).
