### ISSUE TITLE
Libretube is loding even my network is working

### ISSUE THREAD

**Issue by Miszellleq** [libre-tube/LibreTube#1881]
### Steps to reproduce

1. Wifi is working
2. Open libretube
3. Then libretube is loading for infinity

### Expected behavior

Libre tube should show videos

### Actual behavior

Instead there is shoeing loading animation

### LibreTube version

There is showing com.github.libretube_21.apk

### Android version

Android 11

### Other details

There isnt other detalis

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please change the instance in the settings!
