### ISSUE TITLE
Add a repeat button in the notification panel

### ISSUE THREAD

**Issue by Ismail970** [libre-tube/LibreTube#1891]
### Describe your suggested feature

Exactly like the one in Newpipe, a shortcut in the video's notification, clicking on it should make the video replay itself over and over again automatically.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not planned in favor of #2624
