### ISSUE TITLE
Playlist Network Error

### ISSUE THREAD

**Issue by swarnendumaiti** [libre-tube/LibreTube#1892]
### Steps to reproduce

1. Watch video
2. Save to playlist
![Uploading Screenshot_20221118-143320.png…]()

### Expected behavior

Video should be saved to the selected playlist.

### Actual behavior

Fails to add video to playlist
Error as shown : "Network Error"
![Uploading Screenshot_20221118-143326.png…]()

### LibreTube version

0.7.1

### Android version

Android 12

### Other details

The playlist shown above has been created in the LibreTube app itself.
Piped account(registered in "kavin.rocks") was logged in (at the time of playlist creation and while adding the video).
The instance selected was also "kavin.rocks".

![Screenshot_20221118-143349](https://user-images.githubusercontent.com/86847643/202664548-eadcec19-073e-4115-b8d0-f0f09ac11a59.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by swarnendumaiti** [comment]
![Screenshot_20221118-143320](https://user-images.githubusercontent.com/86847643/202665419-3eb1036a-a27c-44b6-8780-9eff6f83eca7.png)

![Screenshot_20221118-143326](https://user-images.githubusercontent.com/86847643/202665436-23762729-ee74-44f3-ba1a-78461ab87f1c.png)
Screenshots shared above didn't upload properly so shared again

**Comment by Bnyro** [comment]
Could you please test it on the Piped web frontend of the instance you're using (e.g. piped.video for pipedapi.kavin.rocks) or try switching the instance?
It might be an instance/backend issue and not LibreTube internally!

**Comment by Bnyro** [comment]
see https://github.com/TeamPiped/Piped/issues/1771

**Comment by swarnendumaiti** [comment]
So it's a server side issue?

**Comment by Bnyro** [comment]
> So it's a server side issue?
>
Yes!

**Comment by swarnendumaiti** [comment]
Ok thanks
