### ISSUE TITLE
Number of views in the watch history

### ISSUE THREAD

**Issue by Binleti** [libre-tube/LibreTube#1900]
### Describe your suggested feature

Show how many times I've watched each video in my watch history.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Doesn't make sense imo
