### ISSUE TITLE
Videos in the playlist do not have video views number or upload date.

### ISSUE THREAD

**Issue by Binleti** [libre-tube/LibreTube#1903]
### Describe your suggested feature

![Screenshot_20221118-221247_LibreTube](https://user-images.githubusercontent.com/118555547/202775139-07c855ba-df7b-4f21-8f8d-38b51fbdaac8.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not supported by the API
