### ISSUE TITLE
View the downloaded video in portrait mode

### ISSUE THREAD

**Issue by Binleti** [libre-tube/LibreTube#1905]
### Describe your suggested feature

The downloaded video must be viewed in portrait mode.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It follows the player orientation preferences.
