### ISSUE TITLE
Scroll to hide toolbar

### ISSUE THREAD

**Issue by Drangonfly30** [libre-tube/LibreTube#1912]
### Describe your suggested feature

As the bottom toolbar in libretube is stagnant. It takes way too much space from the screen. So, it'll be better if we can have scroll to hide toolbar (at least bottom toolbar, idk you can imagine it better).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I've already been trying that once but couldn't make it work properly, open for PRs.

**Comment by Bnyro** [comment]
> Hey @Bnyro, I would love to work on this issue.
>
Awesome, go ahead :)

**Comment by Bnyro** [comment]
Closing as not planned as there doesn't seem a good way to do it and apart from that the benefit would be minimal.
