### ISSUE TITLE
color of sub and unsub text

### ISSUE THREAD

**Issue by Triplesweet** [libre-tube/LibreTube#1916]
### Steps to reproduce

When searching a channel name, the color of the subscribe text does change when you press it, as same as when you are looking at a chanell page and press subscribe.
![IMG_20221119_181410](https://user-images.githubusercontent.com/77248142/202856571-1930bd71-73e3-41a9-8463-48ddbad34ff7.jpg)
![IMG_20221119_181348](https://user-images.githubusercontent.com/77248142/202856574-2f0fe4af-0056-4810-a107-c116cc459751.jpg)
![IMG_20221119_181242](https://user-images.githubusercontent.com/77248142/202856575-d8d2709f-313f-4de8-a17d-150431f150bb.jpg)
![IMG_20221119_181225](https://user-images.githubusercontent.com/77248142/202856576-018e9080-1439-430f-9d7e-a015acb9fd71.jpg)

### Expected behavior

Imo the unsubscribe and subscribe text color Should be a little different specially for channel search one,

### Actual behavior

Look the same expect the actual text

### LibreTube version

0.7.1

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't feel like that would go well with our current UI approach, sorry!
