### ISSUE TITLE
Add Bookmarks in Navigation Bar

### ISSUE THREAD

**Issue by swarnenduu** [libre-tube/LibreTube#1920]
### Describe your suggested feature

Bookmarks are available as an option in the Library section. Since some people might want to save the entire playlist that keeps on updating, they currently have to take a double step to reach the playlist - Library > Bookmarks.

Creating a option to enable it in the Navigation bar from (Settings > Appearance > Navigation Bar > Order) will be much handy.

### Other details

If playlists in Bookmarks (dynamic) and Library Playlists (static) can be merged in Library itself without such distinctions, then that will be great.

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
They can be found at the bottom of the home tab, and thus are just one click away.
Therefore I don't see a reason to mess up with the navigation bar which is not designed to be dynamic!

**Comment by swarnenduu** [comment]
Oo right. Actually I usually keep the Home tab turned off and so I missed that. Fine 👍
