### ISSUE TITLE
When searching a channel, it shows -1 subscribers

### ISSUE THREAD

**Issue by Drangonfly30** [libre-tube/LibreTube#1921]
### Steps to reproduce

1. Search a channel

### Expected behavior

It should show the actual no. of subscribers in feed.

### Actual behavior

It shows subscribers count as -1 
![IMG-20221119-WA0015](https://user-images.githubusercontent.com/113085944/202865275-b69b0982-5c25-497e-8f38-8c9c9541bff9.jpg)

### LibreTube version

Latest version

### Android version

Android 7.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's an API issue, it shows fine for some channels!
