### ISSUE TITLE
Libretube doesn't show search result based on country.

### ISSUE THREAD

**Issue by Drangonfly30** [libre-tube/LibreTube#1923]
### Steps to reproduce

1. Search for channel that show videos based on country (eg: muse Asia)

### Expected behavior

It should same result as YouTube shows locally.

### Actual behavior

It shows results based on US(assuming).

### LibreTube version

Latest version

### Android version

Android 7.0

### Other details

It should show the same result as YouTube shows locally. Like in India muse Asia allows to watch anime but they are restricted to some country. So I'm still not able to access their videos as they do not serve in US.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The NewPipe Extractor and the Piped API don't support search results per region, thus we can't support it either!

**Comment by Drangonfly30** [comment]
Oh np if not possible but on newpipe, I can see these videos.
