### ISSUE TITLE
Reintroduce dedicated history tab

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#1924]
### Describe your suggested feature

Version 0.7.1 had a dedicated history tab, but it was removed immn version 0.8.0. Please bring it back.

### Other details

I know history can be found under library, but the dedicated tab is more useful to me.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by NeeRaj-2401** [comment]
Or else Make the history section similar to YT ....
<img src="https://user-images.githubusercontent.com/88180887/202889306-1a7905cc-caf7-410c-9bd0-0c7b535e230c.png" width="25%">

**Comment by Bnyro** [comment]
We can't readd the tab unfortunately because the material library limits the navigation bar to 5 items at maximum. Otherwise we would need to remove an other one!

**Comment by Donkey-Doug** [comment]
But people can disable/enable tabs. I do not want 6 tabs, I want 3. However, I want one of them to be history. Another person also opened an issue for making a bookmarks tab. It is perfectly fine to allow no more than 5 tabs.
