### ISSUE TITLE
[Feature] Import Playlists from Youtube

### ISSUE THREAD

**Issue by Heus-Sueh** [libre-tube/LibreTube#1926]
### Describe your suggested feature

it should import playlist from the csv file

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Any example of an exported file?

**Comment by Heus-Sueh** [comment]
google lets you export your playlists into multiple csv files
https://takeout.google.com/
![image](https://user-images.githubusercontent.com/98482469/202908153-7984219b-e7ce-4e73-9814-04eacf60b6cc.png)
I don't know if libre tube could read these files and create the playlist

**Comment by Bnyro** [comment]
> google lets you export your playlists into multiple csv files
> https://takeout.google.com/
> ![image](https://user-images.githubusercontent.com/98482469/202908153-7984219b-e7ce-4e73-9814-04eacf60b6cc.png)
> I don't know if libre tube could read these files and create the playlist
> 
>
I'm aware of that but I don't have an account to get one myself ...

**Comment by NoEnd-yt** [comment]
This is a feature that probably needs to be implemented in Piped first so it can be compatible with the accounts and synchronization.

**Comment by Bnyro** [comment]
No, that's not required in that case!

**Comment by rohandebsarkar** [comment]
Here is an example YouTube subscription export: [subscriptions.csv](https://github.com/libre-tube/LibreTube/files/10187791/subscriptions.csv).

Hope, this will help the developers in implementing this feature.
