### ISSUE TITLE
Some improvements for player page

### ISSUE THREAD

**Issue by tvnmguy** [libre-tube/LibreTube#1929]
### Describe your suggested feature

•Progress bar indication
•New comments button
•Autoplay on/off button

Screenshot is given below👇

### Other details

![img_2022_11_20_12_19_46](https://user-images.githubusercontent.com/116799295/202889902-6e869b10-ce5e-47a7-9e4d-1659d6999627.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ARBoyGo** [comment]
Oh my god, Veedum malayali poli 🤩

**Comment by ARBoyGo** [comment]
Machu those are available already.

**Comment by ARBoyGo** [comment]
Enthina new comments button?

**Comment by ARBoyGo** [comment]
Settings > player 
There you can see many options to change default player settings etc....

**Comment by Bnyro** [comment]
I agree that the time bar would be a good addition but I'm not a fan of the other changes, where's the subscription button gone?!

**Comment by ARBoyGo** [comment]
Yes, As Bnyro said progress bar is great, But changing comments button to Subscription button is not worth it, Also we need subscription button right? Lol
With the features Autoplay off/on no need a particular button for that, In my opinion (Who cares lol), So better change it on the player build-in settings or change app default settings of the player. So you don't need to change it everytime, I'm not a fan of Autoplay, I usually off it in default.

**Comment by rozari0** [comment]
I like this one. :p

**Comment by Archeix7** [comment]
![Screenshot_20221122-155431378](https://user-images.githubusercontent.com/51048550/203331561-dbc4dd64-b0b7-4ec2-8243-dee0b9429a1b.jpg)

(All this with a full black theme ;)

**Comment by ARBoyGo** [comment]
@Archeix7 Mmm, I like this theme 🔥🤩. I'm a lover of Black theme over Material UI.

**Comment by ARBoyGo** [comment]
I need this theme as soon as possible 😜. Haha

**Comment by xIUPITERx** [comment]
1. I would like a full black and white theme for devices that don't support material you (please open another issue for that).
2. But the autoplay button seems a waste of space and the subscriptions button is pretty necessary.

**Comment by xIUPITERx** [comment]
> I agree that the time bar would be a good addition but I'm not a fan of the other changes,

Would it not disturb the minimalistic material you look?

**Comment by Archeix7** [comment]
> @Archeix7 Mmm, I like this theme 🔥🤩. I'm a lover of Black theme over Material UI.

Then spam Bryno to add it ;)

**Comment by Archeix7** [comment]
> 1. I would like a full black and white theme for devices that don't support material you (please open another issue for that).
> 2. But the autoplay button seems a waste of space and the subscriptions button is pretty necessary.

https://github.com/libre-tube/LibreTube/issues/1279

**Comment by Bnyro** [comment]
> Then spam Bryno to add it ;)
>
It would be faster if you learn how to do it yourself instead :)

**Comment by xIUPITERx** [comment]
> It would be faster if you learn how to do it yourself instead :)

How difficult would it be?

**Comment by Bnyro** [comment]
> 
> > It would be faster if you learn how to do it yourself instead :)
> 
> How difficult would it be?
> 
> 
>
A pure black theme? I could assist by creating a theme for it and explaining which file to change, your task would be to choose the right colours then :)
In the end you won't need to know coding, you only need time for testing and choosing colors :p

**Comment by xIUPITERx** [comment]
About how many colours are we talking?

**Comment by Archeix7** [comment]
> About how many colours are we talking?

Text links, buttons, and some interface stuff maybe more idk because , as far as I understand, a lot is tied to the "colorPrimary" parameter, which made my entire interface black, but at the same time made it black and texts of links, buttons and a couple more pieces from the interface

**Comment by Bnyro** [comment]
> About how many colours are we talking?
>
30 for the light theme and 30 for the dark one, although light theme could be skipped for that theme I guess

**Comment by Bnyro** [comment]
Otherwise you could try to use the Material Theme Builder, but I doubt it's able to create pure black themes.

**Comment by xIUPITERx** [comment]
>30 for the light theme and 30 for the dark one, although light theme could be skipped for that theme I guess

I should be able to manage that, at the latest the next time I am procrastinating before an exam :)

**Comment by Bnyro** [comment]
Awesome, I'm gonna create a new branch with an empty theme inside later and tell you what to modify :)

**Comment by Bnyro** [comment]
In the end I decided to not include any of the suggestions above by the OP inside the app as I think that they're all not really needed or fitting the style of the app. However, thanks for the suggestion!

**Comment by xIUPITERx** [comment]
> In the end I decided to not include any of the suggestions above by the OP inside the app as I think that they're all not really needed or fitting the style of the app. However, thanks for the suggestion!

What about the PR for the black and white theme?

**Comment by xIUPITERx** [comment]
@Bnyro 

> In the end I decided to not include any of the suggestions above by the OP inside the app as I think that they're all not really needed or fitting the style of the app. However, thanks for the suggestion!

What about the PR for the black and white theme?

**Comment by Bnyro** [comment]
> What about the PR for the black and white theme?
>
My bad, sorry! I'll create a new branch for it in around an hour when I'm done with some IRL stuff and write some intructions then :)

**Comment by Bnyro** [comment]
Oh, and you'll need a PC running Android Studio or IntelliJ, otherwise it'll be nearly impossible since you need to build the app in order to test the theme!

**Comment by xIUPITERx** [comment]
I have installed Intellij, but do I have to download an addon or something similar?

**Comment by Bnyro** [comment]
Hmm, not sure as I use Android Studio but I think I heard that the Android plugin is preinstalled. Otherwise you'll probably figure it out by searching the web for how to build Android apps with IntellliJ :)

**Comment by Bnyro** [comment]
Two things/questions:
1. How do we call the theme?
2. What are we doing when the user selects light as theme mode? I'd suggest that we just inverse the theme for that, which means a pure white theme with a black font.
