### ISSUE TITLE
Update subscription tab.

### ISSUE THREAD

**Issue by rakibdev** [libre-tube/LibreTube#193]
### Describe your suggested feature

Subscribed channels icons are displayed in single row. Hard to see those items scrolling horizontally. Make it collapse/expand by clicking arrow on right which will display 3 column grid when expanded.

Also a unread notification dot can be shown over icons to indicate channel uploaded new unwatched video (this available in YouTube).

Remove home tab. This tab showing completely unrelated videos (same experience when looking at ads). Doubtful if people even click any. And set subscription tab as default as this showing actual videos from subscribed channels.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by daudix-UFO** [comment]
Accept everything, except removing home page

**Comment by Bnyro** [comment]
Looks like a good idea, thank you for suggesting. I'll try to add it :)
