### ISSUE TITLE
App Shortcuts Not Available when using Different Icons

### ISSUE THREAD

**Issue by NeeRaj-2401** [libre-tube/LibreTube#1930]
### Steps to reproduce

1. Install the App
2. Go To Settings and change app icon

### Expected behavior

App Shortcuts should be Available.

### Actual behavior

App Shortcuts are absent

### LibreTube version

v0.8.0

### Android version

Android 12

### Other details

[Screen Recoding ](https://github.com/libre-tube/LibreTube/issues/1919#issuecomment-1321063143) Of the same

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ARBoyGo** [comment]
Wow nice catch 😁, Yes it is not working for other logos
