### ISSUE TITLE
Can't Open App from Notification

### ISSUE THREAD

**Issue by NeeRaj-2401** [libre-tube/LibreTube#1931]
### Steps to reproduce

1. Open app play any video
2. Back to home
3. try opening app via notification of playing video

### Expected behavior

Opening app with Player screen

### Actual behavior

Doesn't do Anything

### LibreTube version

v0.8.0

### Android version

Android 12

### Other details

[Screen Recording](https://github.com/libre-tube/LibreTube/issues/1919#issuecomment-1321063143) for the same

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ARBoyGo** [comment]
I think it's because of pop up.

**Comment by ARBoyGo** [comment]
No, It's not because of pop up, It's a bug..

**Comment by rozari0** [comment]
AFAR this bug was fixed a long time ago.

It's working fine for me.

**Comment by Bnyro** [comment]
Works fine for me as well

**Comment by NeeRaj-2401** [comment]
> was fixed a long time ago.
> It's working fine for me.

Watch attached screen recording

**Comment by Bnyro** [comment]
It somehow seems to be device-specific which is really weird, I remember it worked fine for me on Android 12 :/

**Comment by akano12** [comment]
- Buy a new phone, problem solved
