### ISSUE TITLE
How to access subscription list?

### ISSUE THREAD

**Issue by popogomo** [libre-tube/LibreTube#1936]
### Steps to reproduce

Hi guys,

Thanks for such a great update!

However, I am struggling to find my subscription list: so I tap to Subscribe button on a video which means I am subscribing to the channel. However, I cannot find the list of all channels I am subscribed in the app (unless I am not looking carefully). Where should I look to find these?

### Expected behavior

There should be a dedicated space showing all our subscriptions so we can manage them.

### Actual behavior

It does subscribe fine, however, impossible to find the list of all channels I am subscribed to in order to manage them (unsubscribe, for example).

### LibreTube version

0.8.0

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
There's a dedicated tab for it at the bottom navigation. If that's not the case for you, you might need to go to settings -> appearance -> navigation bar -> order and allow it there :)

**Comment by Bnyro** [comment]
The list of channels can be found when clicking `Subscriptions` at the to of the `Subscriptions` tab.
![Screenshot_20221120-114502_LibreTube.png](https://user-images.githubusercontent.com/82752168/202898015-34b22e30-2521-46d4-8679-c4d022e79365.png)
