### ISSUE TITLE
How to bookmark a page?

### ISSUE THREAD

**Issue by TheoKlizz** [libre-tube/LibreTube#1937]
### Steps to reproduce

Hi there. I am migrating from NewPipe and LibreTube looks good, so far.

This might not be a bug but I can't see an option to bookmark a video so it is a bit unclear why we need the Bookmarks tab for. 

Can you please shed some light on this? Thx.

### Expected behavior

Possibility to bookmark videos.

### Actual behavior

Cant see an option to add a video to bookmark.

### LibreTube version

0.8.0

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You can only bookmark playlists, videos are not supported for that. If you want to bookmark videos, please create a `Watch later` playlist or something similar and add videos you still want to watch to it :)
