### ISSUE TITLE
Add a button to rotate/play videos in full screen

### ISSUE THREAD

**Issue by TheoKlizz** [libre-tube/LibreTube#1938]
### Describe your suggested feature

It seems the only way to rotate videos (play in full screen) is enabling Auto-Rotate feature and then rotating the phone.

This is not always convenient as sometimes phone sensors do not react properly, etc.

Will it be possible to add a button both in normal and full-screen modes, that will switch playback from normal to full-screen and vice versa?

Something like this:

![Capture](https://user-images.githubusercontent.com/118317474/202899645-58611a60-5ced-43b1-883a-8bbf4f89cb17.PNG)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Binleti** [comment]
It exists.

**Comment by Binleti** [comment]
To see this button in the player, turn off auto-rotation in LibreTube settingsIf auto-rotation is on, no button is needed.

**Comment by Bnyro** [comment]
Making both (auto-rotation and the fullscreen button) work at the same time is impossible, see https://github.com/libre-tube/LibreTube/issues/1576#issuecomment-1311993029
