### ISSUE TITLE
Rounded corners

### ISSUE THREAD

**Issue by rakibdev** [libre-tube/LibreTube#194]
### Describe your suggested feature

Rounded corners in dialog, search according to Material 3 guide. And removing LibreTube Red banner from dialogs like login/register, create playlist, unnecessary and distracting.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by martin-desktops** [comment]
With the whole UI powered by Material U, I think it makes sense to improve consistency with the rest of the app and system by making dialogs looking native

**Comment by Bnyro** [comment]
I think so too but it's not easy
