### ISSUE TITLE
Can't see Subscriptions

### ISSUE THREAD

**Issue by akasaka99** [libre-tube/LibreTube#1940]
### Steps to reproduce

1. Check the Subscription Tab
2. No susbscription appear

### Expected behavior

Should see my subscripton list but nothing shows up. 
However, when I get out of the Subscription section and type a channel that I have subscribed, it correcty only gives me a choice to "unsubscribe" which means that my subscription is taken into account but it is not showing up.

### Actual behavior

Nothing shows up

### LibreTube version

0.8.0

### Android version

Android 11

### Other details

Mobile: Samsung S10+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by rozari0** [comment]
Close app, open again. If nothing happens then change instance and try again.

**Comment by Binleti** [comment]
Please send a screenshot.

**Comment by akasaka99** [comment]
It was indeed an instance issue, it is working now. 
Thank you for your quick response !!!
