### ISSUE TITLE
No information whether the video has high frame rate in the quality settings 

### ISSUE THREAD

**Issue by yhm4ps1jfp67nkv** [libre-tube/LibreTube#1945]
### Steps to reproduce

1. Open a 60FPS video
2. Open the main Settings sheet (or the resolution submenu)

### Expected behavior

60FPS video resolutions should be listed as such (2160p60, 1440p60, 1080p60 etc.)

### Actual behavior

Video resolutions are listed without the 60FPS mark (2160p, 1440p, 1080p etc.)

### LibreTube version

Latest Debug

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
As we're using DASH now, the way how resolutions are chosen changed and thus we don't list the qualities with frame rates anymore, hence it's not a bug. However, we'd be able to at a control or a preference to allow setting the preferred framerate, if you really need it you can consider opening a new issue with a suggestion where to add such an option.
