### ISSUE TITLE
Faster fade-out of the video overlay

### ISSUE THREAD

**Issue by MatsG23** [libre-tube/LibreTube#1953]
### Describe your suggested feature

When clicking on a playing video, the video controls and title shows. I would appreciate if these controls/title (whole overlay) would fade out faster.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not possible because
1. We can't hide/show it instantly because the double tap to seek wouldn't work then
2. The time the player controls take to fully appear/vanish is controlled by the `ExoPlayer` and can't be changed.
