### ISSUE TITLE
Fade out video title overlay together with video controls

### ISSUE THREAD

**Issue by MatsG23** [libre-tube/LibreTube#1954]
### Describe your suggested feature

The video title overlay should not be faded out with a delay after the video controls faded out. You should see the video title overlay and the video controls as *one overlay* and fade out both at once.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We can't control that, the behavior is controled by the `ExoPlayer` which is a third party library.
