### ISSUE TITLE
Dracula Theme as a replacement for purple theme in dark mode

### ISSUE THREAD

**Issue by NoEnd-yt** [libre-tube/LibreTube#1968]
### Describe your suggested feature

I would really like to see the [Dracula Theme](https://draculatheme.com/) added to LibreTube and replacing the purple theme in dark mode currently in use. For me, the purple theme looks more pink than purple (but this is personal opinion). If it doesn't replace the purple theme, could it be added as a new one?

### Other details

Dracula Theme's site:
https://draculatheme.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We're using the [Material Theme Builder](https://m3.material.io/theme-builder#/dynamic) for all themes, hence it would need to be a completely new theme.

Each theme contains 30 different colors, picking all them from their website as well as testing them in the end costs a lot of efforts, therefore I won't work on it.

However, I could assist with it and guide you here if you want to create a PR for it.

Cheers

**Comment by NoEnd-yt** [comment]
Thanks for your answer! I'll try to create a theme there and make a PR.

**Comment by Bnyro** [comment]
You won't be able to create a Dracula theme with the Material Theme Builder as it only allows you to insert one color and generates a Material Design 3 theme from it. In the end you'll probably need to add the theme manually by creating a `style` in the [themes.xml](https://github.com/libre-tube/LibreTube/blob/master/app/src/main/res/values/themes.xml) and the corresponding colors in the [styles.xml](https://github.com/libre-tube/LibreTube/blob/master/app/src/main/res/values/themes.xml).
I could creaye a separate branch with a Dracula theme which is using the colors of an other theme then, then you would be able to modify the newly created theme's colors and test them.

**Comment by NoEnd-yt** [comment]
Then if creating a custom theme like that is tedious, would it be possible to set the purple theme to look more purple than pink?
A good example would be Tachiyomi's Lavender theme (Tachiyomi is an open source manga reader for Android):
![Tachiyomi Screenshot](https://user-images.githubusercontent.com/76617157/204017316-bfbb5d25-f45c-473c-a0dc-ebd69308f84e.png)

**Comment by Bnyro** [comment]
Well, when creating a new theme you can choose the colors as you want to!

**Comment by Bnyro** [comment]
Tell me when you want to start working on it, I'll create a new branch for it then with an empty dracula theme you can then update with a PR! :)

**Comment by NoEnd-yt** [comment]
> Then if creating a custom theme like that is tedious, would it be possible to set the purple theme to look more purple than pink?
> A good example would be Tachiyomi's Lavender theme (Tachiyomi is an open source manga reader for Android):
> ![Tachiyomi Screenshot](https://user-images.githubusercontent.com/76617157/204017316-bfbb5d25-f45c-473c-a0dc-ebd69308f84e.png)

I meant making a theme like this using material builder.

**Comment by Bnyro** [comment]
No, that's not possible with the Material Theme Builder, you would need to choose all the colours manually!

**Comment by NoEnd-yt** [comment]
Isn't it possible to make a theme that looks more purple? I'll check that.

**Comment by Bnyro** [comment]
> Isn't it possible to make a theme that looks more purple? I'll check that.
>
It is possible, but not with the Material Theme Builder, as I said ...

**Comment by NoEnd-yt** [comment]
Oh ok, sorry for misunderstanding 😅

**Comment by Bnyro** [comment]
Sorry to annoy with that, are you planning to work on it then (you'll need to have a working Android Studio installation as well as some time to choose the colors, 58 in total although you can reuse most of them multiple times)? 
If not, I would close the issue as not planned, but if you're interested I could assist similar to #2111

**Comment by NoEnd-yt** [comment]
No, sorry. I still really like this project and will support it 🙂

**Comment by NoEnd-yt** [comment]
Hi, sorry to reopen the issue,
I made a purple theme in Material Theme Builder using Dracula Theme's purple (#bd93f9), and it turned out to look more purple-ish than the one currently in use. It probably needs some rework, but this is a good base for a more purple theme.
![image](https://user-images.githubusercontent.com/76617157/205850347-7e33a51b-2fa6-4315-8e70-2154119fc476.png)

**Comment by Bnyro** [comment]
That's awesome, didn't know that would be possible :)
I can create a new branch with an empty Dracula theme later in the day and you can then just paste in the generated XML code from the Material Theme Builder.

**Comment by NoEnd-yt** [comment]
Thank you :)

**Comment by Bnyro** [comment]
I've created a new branch `dracula` at the repo now (which is currently the purple theme).
To change that you'll need to replace https://github.com/libre-tube/LibreTube/blob/dracula/app/src/main/res/values/colors.xml#L361-L418 with the theme generated by the Material Theme Builder at your fork (pay attention to keep the attribute names as they`re currently!). Then you should be able to build the app via Android Studio and build it.
Further advice can also be found at #2111

**Comment by NoEnd-yt** [comment]
I have replaced the colors and imported the project in Android Studio. I'm probably have to continue tomorrow but I think I'm almost done :)

**Comment by NoEnd-yt** [comment]
I'm getting an issue with Gradle version as my Android Studio version isn't up-to-date (2021.3.1.17)
![image](https://user-images.githubusercontent.com/76617157/206304652-1ed1863f-6772-4de6-96ae-e9230ccba136.png)

**Comment by xIUPITERx** [comment]
Oh, when i made the monochrome theme there was already a warning that the support might expire soon.

**Comment by Bnyro** [comment]
> I'm getting an issue with Gradle version as my Android Studio version isn't up-to-date (2021.3.1.17). I'm using the flatpak version on EndeavourOS (Arch Linux). Oh and btw i contributed to the French translation 😄
> ![image](https://user-images.githubusercontent.com/76617157/206304652-1ed1863f-6772-4de6-96ae-e9230ccba136.png)                                                               
>
You should use the Android studio beta version from the AUR, that should run it without issues!

**Comment by NoEnd-yt** [comment]
Yes, I'm doing that asap :)

**Comment by NoEnd-yt** [comment]
Yes, I'm doing that asap :)

**Comment by NoEnd-yt** [comment]
Yes, I'm doing that asap :)

**Comment by Bnyro** [comment]
Now you can create a PR to the repo here (for that you'll need to fork the repo first and copy your changes into your fork).

**Comment by NoEnd-yt** [comment]
Done :)

**Comment by NoEnd-yt** [comment]
>I think it would be better called "deeper purple" (or "violet profond" in French, I will make sure to translate it :D) or something like that, because it doesn't really match Dracula's palette.

So, what do you think about renaming it?

**Comment by Bnyro** [comment]
Sure we can do that. As we currently use alliterations for all the names, we should think about a name containing two words starting with the same char. If not, `Deeper Purple` would be my preferred one out of your two suggestions

**Comment by NoEnd-yt** [comment]
What about Pagoda Purple?
![image](https://user-images.githubusercontent.com/76617157/206528373-6a3a02aa-cfb4-4e22-b022-49226406002e.png)

**Comment by Bnyro** [comment]
Maybe we should actually go with something related to Violet since there's already a purple theme (makes it easier to distinguish the themes from each other for users).
I could think of something like Versatile, Vital or Vast Violet for example.

**Comment by NickTheOnlyNeko** [comment]
> Versatile Violet sounds good for me :grinning: 

Can we get more color versions in addition to Versatile Violet? Like Versatile Green, Versatile Blue and Versatile Red. I'm asking because the Default themes are an eye sore to me and make my eyes hurt even in light mode the default themes just suck, the only theme that looks good is the Versatile Violet in Dark mode

**Comment by Bnyro** [comment]
Feel free to create a pull request.
