### ISSUE TITLE
Exclude recommended videos from queue

### ISSUE THREAD

**Issue by RetroAbstract** [libre-tube/LibreTube#1969]
### Describe your suggested feature

This feature would allow the user to exclude a video's recommended videos from the play queue.

I might have missed an obvious setting somewhere but currently when I add a video to the queue/play next, there's always the first video's recommended videos mixed in with the videos I enqueue to be played in the queue.

### Other details

None

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You're right, that's not possible yet. For now you'll need to clear the queue manually unfortunately, I'm going to add an option for it before the next update as I agree that it doesn't make sense to add all the related videos to the queue all the time.

**Comment by RetroAbstract** [comment]
> You're right, that's not possible yet. For now you'll need to clear the queue manually unfortunately, I'm going to add an option for it before the next update as I agree that it doesn't make sense to add all the related videos to the queue all the time.

Cool, looking forward to it. Appreciate all the great work you're doing with LibreTube it's vastly improved since the first time I used it
