### ISSUE TITLE
Search button in bottom navigation.

### ISSUE THREAD

**Issue by rakibdev** [libre-tube/LibreTube#197]
### Describe your suggested feature

Most used button is placed in the corner. Hard to reach every time when using with one hand.
Chrome has this search, autocomplete everything bottom. Looks better when home tab is removed (according to previous feature requests) and keeping only 3 tab subscriptions, search, library.

![chrome](https://user-images.githubusercontent.com/60188988/167750105-10665fee-8c6b-4d57-9ba5-f1dee0720c0e.jpeg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't think that it's a good idea since we would have four items in the bottom nav then. Which is one too much :D
