### ISSUE TITLE
LibreTube disapears in recents screen.

### ISSUE THREAD

**Issue by Medd3h** [libre-tube/LibreTube#1970]
### Steps to reproduce

1. Open LibreTube.
2. Go to recents/app switch.
Sme happens if you go home then go to recents.

### Expected behavior

I can go to another app and easily get back to LibreTube.

### Actual behavior

App disapears from recents.

### LibreTube version

0.8.0

### Android version

Android 9

### Other details

Has happened on older versions of the app for me.

If it disapears, I can still get into the app from my home screen and get right back where I was, but that means the app is always running.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by swarnenduu** [comment]
I'm on Android 12. I don't face this issue.

**Comment by Bnyro** [comment]
Same for on different devices on A13 and A12 and the emulator, hence closing it as not reproduceable.
You might want to try changing battery restriction settings for the app.
