### ISSUE TITLE
Login to multiple Piped accounts

### ISSUE THREAD

**Issue by trymeouteh** [libre-tube/LibreTube#1971]
### Describe your suggested feature

The ability to login to one or more piped accounts and access your subsciption, feed and history.

[Piped](https://piped.kavin.rocks/)  is a front end which allows users to have a subscription feed for YouTube videos without a google account and have privacy. Users can also choosw their Piped instance or self host their own instance.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FireMasterK** [comment]
Why would anyone need such a feature? You only really need one account for everything...

**Comment by trymeouteh** [comment]
> Why would anyone need such a feature? You only really need one account for everything...

For Android TV, where multiple users share the device

**Comment by FireMasterK** [comment]
I don't think Libretube supports Android TV to begin with
