### ISSUE TITLE
Incomplete YouTube Links 

### ISSUE THREAD

**Issue by swarnenduu** [libre-tube/LibreTube#1975]
### Steps to reproduce

1. Open a video on LibreTube that has a YouTube video or playlist link on it's description. ⬇️
e.g. https://piped.video/watch?v=7zqNL-nzYfI

2. Click on that link

### Expected behavior

The link should open.

### Actual behavior

Video Link: The video stops(video screen turns black) and minimises to PIP mode.⬇️
![Screenshot_20221122-104913](https://user-images.githubusercontent.com/86847643/203228274-870e2031-65aa-4f7b-ab43-4f488c031a55.png)
On clicking on PIP:⬇️
![Screenshot_20221122-104949](https://user-images.githubusercontent.com/86847643/203228332-a74212f1-5baa-439c-8a4f-6c97f036b438.png)

Playlist Link: The video stops and minimises to PIP mode. Video player doesn't turn black.⬇️
![Screenshot_20221122-105057](https://user-images.githubusercontent.com/86847643/203228540-79e2707b-ec6b-4cf4-8cf7-01ccd0ba674a.png)
On clicking on PIP:⬇️
![Screenshot_20221122-105104](https://user-images.githubusercontent.com/86847643/203228579-f01d6dc9-5da5-4848-818e-eafe84ef74f1.png)

### LibreTube version

0.8.0

### Android version

Android 12

### Other details

Supposed reason for the issue:
![Screenshot_20221122-104354-625](https://user-images.githubusercontent.com/86847643/203228856-2ab21ab4-3953-4be2-8032-af87cf1c6069.png)

Look in the above picture ⬆️
The video link has long url and is continued with '...' where the '...' is not hyperlinked and so url ends with 'mxE'. Same with playlist ⬇️
![Screenshot_20221120-081543-905](https://user-images.githubusercontent.com/86847643/203229562-64e977e5-9b61-4279-852e-6c0694af9d7f.png)
But in YouTube website or app even the '...' is hyperlinked so we can open the complete link. Like YouTube website screenshot ⬇️
![Screenshot_20221120-081717-372](https://user-images.githubusercontent.com/86847643/203229914-d070c0db-d186-4129-8793-a0f9e06b4db2.png)

But the links are completely hyperlinked in the comments section and so that works fine.⬇️
![Screenshot_20221122-105805~2](https://user-images.githubusercontent.com/86847643/203230357-2ed691b1-9aa4-44eb-8a6f-c32413b49723.png)

These links also works completely fine in the piped.video website.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Hmm, it seems to work fine for Piped, I've no idea why it doesn't for us :/

**Comment by swarnenduu** [comment]
Exactly. The remaining part of the link is not hyperlinked.

**Comment by ARBoyGo** [comment]
Yup I always use newpipe for this to work. Sadly

**Comment by swarnenduu** [comment]
Awesome. Thanks. This took off a lot of my headache.
