### ISSUE TITLE
don't auto-queue random videos

### ISSUE THREAD

**Issue by asklow** [libre-tube/LibreTube#1978]
### Steps to reproduce

1. Play a single video
2. Look at your playlist queue

### Expected behavior

Only the selected video should be in the playlist

### Actual behavior

Random videos get queued on top of each other.

### LibreTube version

0.8.0

### Android version

Android 12

### Other details

This can be a feature, or a bug, depending on the user's conveniency.
Atleast give us an option to not auto-queue random recommended videos while playing a single video.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#1969 :p
