### ISSUE TITLE
[FEATURE] Remove playlist videos

### ISSUE THREAD

**Issue by IceDBorn** [libre-tube/LibreTube#198]
### Describe your suggested feature

Currently you have to use the web version of piped to delete videos from your piped playlists.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by lilcheti** [comment]
The option is available right now in the app

**Comment by lilcheti** [comment]
Oh seems like there was a bug
