### ISSUE TITLE
Add an option to backup local playlists

### ISSUE THREAD

**Issue by yhm4ps1jfp67nkv** [libre-tube/LibreTube#1982]
### Describe your suggested feature

There should be an option in Settings -> Advanced -> Backup to backup local playlists

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by rozari0** [comment]
Is bookmarks and local playlist are same thing?

**Comment by swarnenduu** [comment]
You can backup your playlists and sync them using a Piped Account. For Bookmarks, backup option has been enabled in the debug build.

**Comment by Bnyro** [comment]
> Is bookmarks and local playlist are same thing?
>
see https://github.com/libre-tube/LibreTube/pull/1944 :p

**Comment by rozari0** [comment]
> > Is bookmarks and local playlist are same thing?
> 
> see #1944 :p

Oh, cool. That was really needed.
