### ISSUE TITLE
Double tap to stop playback

### ISSUE THREAD

**Issue by limonovthesecond2** [libre-tube/LibreTube#1988]
### Describe your suggested feature

Double tap on the center of the player (±1/3 of the player) stops playback.

### Other details

![Untitled](https://user-images.githubusercontent.com/118817903/203373255-56bc8f3e-1541-415f-8805-f3be3d315ec2.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by limonovthesecond2** [comment]
> LibreTube already have this feature. First tap makes the pause btn visible and the 2nd one pauses the video Just saying 😂😂😂😂
, but a user should to tap a small pause button for that.

**Comment by limonovthesecond2** [comment]
> LibreTube already have this feature. First tap makes the pause btn visible and the 2nd one pauses the video Just saying 😂😂😂😂

In this case, a user needs to tap on the small pause button to do so.  It will be much easier to double tap somewhere in the center of the player (not necessary tap the button).

**Comment by Bnyro** [comment]
But that requires you to wait until the button becomes abailable, maybe the OP hasn't enough time to wait for that 😅

Anyways this should be really easy to implement so why not :)

**Comment by VedxP** [comment]
> But that requires you to wait until the button becomes abailable, maybe the OP hasn't enough time to wait for that 😅
> 
> Anyways this should be really easy to implement so why not :)

Consider implementing `pinch to zoom` gesture too, plox :)
