### ISSUE TITLE
Load playlist in background.

### ISSUE THREAD

**Issue by rozari0** [libre-tube/LibreTube#1992]
### Describe your suggested feature

It's just like load feed in the background, but for playlists.

My Internet speed isn't that much good, sometimes it takes too much time to fetch playlists. Also, I don't want to send a request to the server every time I visit the playlist tab

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
It should probably still be limited to a certain number of videos. If you have a playlist with 100 videos, it would probably take quite a while otherwise.
If you only load the first 3 videos from each playlist and the rest only when the playlist is opened, it could work.

**Comment by xIUPITERx** [comment]
in the same move you could also load the 'featured' category on the home feed in the background (but only if the home feed is also displayed in the navbar).

**Comment by rozari0** [comment]
> It should probably still be limited to a certain number of videos. If you have a playlist with 100 videos, it would probably take quite a while otherwise. If you only load the first 3 videos from each playlist and the rest only when the playlist is opened, it could work.

You didn't understand my issue, I want this feature for the playlists tab in the nav bar. Not in the playlist itself. 
Also what you want in the playlist is already implemented (piped api doesn't return the whole playlist at once).

**Comment by rozari0** [comment]
> in the same move you could also load the 'featured' category on the home feed in the background (but only if the home feed is also displayed in the navbar).

Agreed.

**Comment by Bnyro** [comment]
No plans for that currently, sorry!
