### ISSUE TITLE
Misalignment of icon in no network screen

### ISSUE THREAD

**Issue by MatsG23** [libre-tube/LibreTube#1993]
### Steps to reproduce

1. Turn off network (WiFi, cellular data)
2. Start LibreTube
3. You see a screen indicating that there is no internet connection

### Expected behavior

The wifi icon in that Activity should be centered.

### Actual behavior

The wifi icon is out of place, as you can see below.
![screenshot_libretube](https://user-images.githubusercontent.com/60609373/203505204-82363ada-955f-4cf2-9462-3e8470d9a5c2.png)

### LibreTube version

0.8.0

### Android version

Android 13

### Other details

I run GrapheneOS.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
![Screenshot_20221123-163146_LibreTube.png](https://user-images.githubusercontent.com/82752168/203585920-c59ef150-cf6b-4b06-95db-9ff24e65daab.png)
That's weird, looks as intended for me :/
