### ISSUE TITLE
Allow to switch tabs of bottom navbar using a swipe

### ISSUE THREAD

**Issue by MatsG23** [libre-tube/LibreTube#1994]
### Describe your suggested feature

You should be able to switch to other tabs of the bottom navigation bar by swiping to the left/right.

### Other details

I noticed that this was already requested ~2 months ago (https://github.com/libre-tube/LibreTube/issues/1342).

You answered that
> Android doesn't support it

but I doubt that. It should be possible to make the tabs of the bottom navbar swipeable.
See [here](https://stackoverflow.com/questions/67546640/how-to-make-swipeable-bottom-navigation-view-in-android-studio-with-java). Alternatively, it should be possible to listen for a swipe to the left/right and switch the tab programmatically.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The StackOverflow answer is actually not related to the OPs question in any way. Apart from that the swiping nav bar is not part of the Material guide lines and I'm not aware of any app using it.
