### ISSUE TITLE
Auto rotation doesn't work

### ISSUE THREAD

**Issue by Abu-Khulzat** [libre-tube/LibreTube#1995]
### Steps to reproduce

When video is played on Galaxy s22 ultra sm-s908e auto rotation doesn't work when you put the phone in landscape.

### Expected behavior

The picture should change to landscape

### Actual behavior

The portrait orientation doesn't change

### LibreTube version

0.8.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Abu-Khulzat** [comment]
Yes I tried the toggle on and off then on again. I checked Newpipe and it
works properly.

**Comment by Bnyro** [comment]
Can't reproduce, it's rather something wrong with your device or settings than with the app.

**Comment by Bnyro** [comment]
> Does that make sense? Can that be achieved with the app today? I haven't been able to find a configuration that makes it work thus far, unlike NewPipe.
>
Playing a video is independent from the normal auto-rotation. For that you'll have to enable the `Auto-fullscreen` option in the player settings and it should work fine.

**Comment by Bnyro** [comment]
You mean forcing it to keep one orientation all the time? That's what's usually being done when the settings aren't enabled for portrait mode, for landscape that's not possible!

**Comment by simonkrauter** [comment]
I have the same issue. The player screen always changes to portrait mode. 
Auto-rotation of Android is enabled. I tried setting the "Fullscreen roation" to "Auto-Rotation" and "Landscape". Did not help.
My Device: Lenovo Yoga Tab 3 Plus, Android 11, LineageOS 18.1

**Comment by Abu-Khulzat** [comment]
I found the issue. It turns out that there are 2 auto rotation toggles: 1
in general section of the settings, 2 in player section under Auto full
screen. So that was misleading. Now everything works fine

**Comment by Bnyro** [comment]
> > Does that make sense? Can that be achieved with the app today? I haven't been able to find a configuration that makes it work thus far, unlike NewPipe.
> >
> Playing a video is independent from the normal auto-rotation. For that you'll have to enable the `Auto-fullscreen` option in the player settings and it should work fine.
> 
>
That's what I already wrote here multiple times :)
