### ISSUE TITLE
Remove "Open in app" button

### ISSUE THREAD

**Issue by MatsG23** [libre-tube/LibreTube#1996]
### Describe your suggested feature

I do not see a reason why you would need to open a playing video in like a video player. This functionality does not even seem to work with VLC.

### Other details

If you find a good reason to keep the functionality, I would still appreciate to be able to turn off seeing this button.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I agree on that. The button was initially added because our own player lacked features, but since it's more matured now we can definitely get rid of the button!

**Comment by rozari0** [comment]
I still use it for downloading video with download manager. :/ 
Don't remove it, make it optional.

**Comment by rozari0** [comment]
> Why don't you use the download feature for that?

For unknown reason It doesn't work everytime. So I have to use this or YTdl.
