### ISSUE TITLE
Landscape mode switching

### ISSUE THREAD

**Issue by saurabhinabys** [libre-tube/LibreTube#20]
After going Fullscreen in a video,  it stays in portrait mode depsite of any type of content. I dont if it's a feature yet to be implemented or just a bug.

**Comment by laraib07** [comment]
@rimthekid I tried latest build. It still plays video in portrait mode.

OS : Android 12 arrow os
Phone: Realme 2 pro

**Comment by rimthekid** [comment]
You should turn on rotation and rotate the phone after going in to full screen mode

**Comment by saurabhinabys** [comment]
will auto-rotation not be implemented for now?

**Comment by rimthekid** [comment]
I think I can get the ratio and check hmm
