### ISSUE TITLE
Highlight the current active chapter in full-screen mode

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#2000]
### Describe your suggested feature

Currently when you play a video having chapters, the chapter which is being played now gets highlighted in portrait mode.

But in landscape mode, there's no such implementation.

#### The chapter being highlighted in portrait mode:

> ![Screenshot_20221123-181239~2](https://user-images.githubusercontent.com/87353286/203563923-e575c961-cab3-4d71-9b88-7ed290c2715a.png)
---
#### No indication of the chapter being played in landscape mode:
> ![Screenshot_20221123-181232](https://user-images.githubusercontent.com/87353286/203564156-98a3ab3a-f742-4fb3-a092-54c2fe181bda.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We currently use the `MaterialAlertDialogBuilder` inbuilt `setItems()` function for adding the chapters to a list there. Highlighting would require writing our own layout for it which wouldn't be worth the time.
