### ISSUE TITLE
`-1 subscribers` count in search page

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#2003]
### Steps to reproduce

- Open LibreTube 
- Search for any channel 

### Expected behavior

.

### Actual behavior

It'll show `-1 subscribers`, not always but it shows many of the times.

### LibreTube version

0.8.0

### Android version

Android 12

### Other details

Reference screenshots:
>  ![Screenshot_20221123-195838~2](https://user-images.githubusercontent.com/87353286/203572822-db24eea3-ab87-4810-9b42-bcd75c95cf1c.png)
---
>![Screenshot_20221123-195703~2](https://user-images.githubusercontent.com/87353286/203572840-81c77ca1-de6e-472b-9596-e48b4187e51f.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/TeamNewPipe/NewPipeExtractor/issues/976
