### ISSUE TITLE
`CronetTimeoutException`

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#2004]
### Steps to reproduce

Not sure how to reproduce it as it appeared randomly :)

### LibreTube version

0.8.0

### Android version

Android 12

### Other details

<kbd>![Screenshot_20221123-195942~2](https://user-images.githubusercontent.com/87353286/203573855-d105c752-8140-4157-bf46-be40c8d4de0f.png)</kbd>

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Cronet is used for making requests, hence it's probably a network issue!
