### ISSUE TITLE
Some resolutions don't work for specific videos

### ISSUE THREAD

**Issue by luca-e075e** [libre-tube/LibreTube#2005]
### Steps to reproduce

First of all, these videos https://github.com/libre-tube/LibreTube/issues/1132 now with proper DASH support are playing, thanks!

However, could you please:

1. open audio and video settings
2. set up 480p as fixed resolution (both wifi and mobile data)
3. turn off "Use HLS"
4. play https://www.youtube.com/watch?v=Q5ESzNFQEqg
5. open video options ( V icon)
6. check video quality written on the menu

### Expected behavior

quality should be 480

### Actual behavior

quality is 360

### LibreTube version

0.8.0 fdroid

### Android version

10

### Other details

if you enable "Use HLS" the video is played at 480

yt-dlp also confirm that 480p formats are available in DASH

135      mp4   854x480     30    │ ~33.27MiB 1155k dash  │ avc1.4d4014 1155k video only          DASH video, mp4_dash
**244      webm  854x480     30    │ ~21.68MiB  753k dash  │ vp9          753k video only          DASH video, webm_dash**

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Hmm, it seems like when selecting 720p or 480p it always uses 360p instead of changing the quality for that video, however when choosing 1080p it's working fine again.
I tried some other videos too but wasn't able to find an other video with the same behavior.

**Comment by Bnyro** [comment]
Fixed by #2656
