### ISSUE TITLE
YT links don't load when opened from LT itself

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#2006]
### Steps to reproduce

- Play any video having a link of a YouTube video in description 
- Click that link from the description 

### Expected behavior

It should play the video upon clicking the video link from the description.

### Actual behavior

It doesn't play the video or can say it doesn't parse the link to be able to play ig :)

### LibreTube version

0.8.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by swarnenduu** [comment]
Yes I've already posted this issue. @VedxP  Kindly close this.
