### ISSUE TITLE
Sync Preferences from Piped Account with App

### ISSUE THREAD

**Issue by trymeouteh** [libre-tube/LibreTube#2014]
### Describe your suggested feature

When logged into a Piped account, the preferences used from that Piped account should be used in the app.

Some exceptions should be made such as Video resolution which can be overwritten by the app. A list of settings that should be used from the Piped account are...

General->Region (Country Selection)
General->Language (Language Selection)
Player->Autoplay (Autoplay Video)
Player->Preloading (Buffering Goals)
History->Search History (Store Search History)
History->Watch History (Store Watch History)
SponsorBlock settings

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The settings at Piped are only stored in your browser and not linked to your account, hence that's not possible. Apart from that they work too different that it would make sense.
