### ISSUE TITLE
Add the tablet mini player

### ISSUE THREAD

**Issue by Deathemonic** [libre-tube/LibreTube#2017]
### Describe your suggested feature

I've used YouTube Revanced and I like the tablet mini player because it big and you see most of the content. It would be cool to have the tablet mini player as an option

![Screenshot_20221124_081458](https://user-images.githubusercontent.com/65948476/203667586-5e085433-b6c3-48ef-afd7-48c65cc99038.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Making both available is nearly impossible from a dev perspective. I prefer the current mini player with all the items in a row, there are no plans to change that.
