### ISSUE TITLE
FPS, HDR Labels missing in Quality Options

### ISSUE THREAD

**Issue by swarnenduu** [libre-tube/LibreTube#2019]
### Steps to reproduce

Change quality of a video that maybe 60fps, HDR.

### Expected behavior

e.g.

720p 60fps HDR
1080p 60fps

### Actual behavior

720p
1080p

### LibreTube version

0.8.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Since 0.8.0 the backend for playing videos changed, hence the issue would rather be a request for being able to change the frame rate independently from the quality than a bug.

**Comment by swarnenduu** [comment]
Actually Let me clarify my request. The video with 720p 60fps HDR is changing to such quality. But in the optione it's just showing 720p instead of 720p 60fps HDR. So it's a visual change request.

**Comment by Bnyro** [comment]
But how would that look better than having the current `720p` only? Don't other video players only show the resolutions and not things like HDR or the frame rate? For me as user it would be more intuitive to only have to choose between resolutions and not getting confused by the other info.

**Comment by swarnenduu** [comment]
YouTube app has that. The reason it has that, is for the user to differentiate between a higher fps video than a lower. Also it makes us being sure that the video I'm watching is actually HDR, is actually 60fps, sometimes with naked eyes we can't see the difference but labels bring assurance.

**Comment by xIUPITERx** [comment]
I think it's just nice to have for most and since some devices don't work well with HDR it could be usefull for them.
Behind the resolution is more than enough space without it then looking crowded

**Comment by Bnyro** [comment]
That's what I said previously, as we're using Dash now we can't differ between those when changing the quality, it automatically selects the best depending on the internet connection.
We can only allow changing the frame rate now, but independently from the actual quality. If the frame rate is not available for the quality it would still play fine but with the available frame rate.

**Comment by swarnenduu** [comment]
Sorry @Bnyro but the new title is not appropriate as per the issue I explained

**Comment by Bnyro** [comment]
Even if we added these labels back, it wouldn't control the frame rate or whether it's HDR. If there's 720p 60fps available, there's usually the same resolution (e.g. 720p) available with 60fps ad well. Without a separate option it's not guaranteed that clicking on it even uses the framerate, it's a 50:50 chance. Hence I really doubt that makes any sense with a separate option!

**Comment by swarnenduu** [comment]
Oo I get it. It's fine. I just gave a suggestion. 🙂👍
