### ISSUE TITLE
Swipe down to close miniplayer

### ISSUE THREAD

**Issue by swarnenduu** [libre-tube/LibreTube#2020]
### Describe your suggested feature

When the video player is minimised on the app, one can close the video by further swiping down the player just like YouTube and NewPipe.

![Screenshot_20221124-114602~2](https://user-images.githubusercontent.com/86847643/203708274-5ca02554-5c13-4be3-ba2a-4c7d38b16c58.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I've no clue how to implement that with the motion layout, hence I'm open for PRs but won't work on it myself as I've already tried to.

**Comment by swarnenduu** [comment]
Alright
