### ISSUE TITLE
Smooth transition to PIP mode.

### ISSUE THREAD

**Issue by swarnenduu** [libre-tube/LibreTube#2023]
### Describe your suggested feature

In Android 12 and above YouTube and many other video player apps have a smooth transition to PIP mode.
Sample transition video: https://piped.video/watch?v=4QLPuWK40w8

In LibreTube the animation is sudden and not smooth. Kindly bring this smooth animation.

I'm using Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Note: they got added with Android 12 and hence are not available for Android 11 and lower!

**Comment by swarnenduu** [comment]
Thanks for the fix. But there is a little delay of white screen between the PIP mode getting activated and the video coming to picture in the PIP mode. Can that be eliminated like in the YT app where that's seamless.
![Screenshot_20221124-213010](https://user-images.githubusercontent.com/86847643/203828187-9ff21104-479d-406d-bda9-4ca149f3da79.png)

**Comment by Bnyro** [comment]
As far as I know other apps have the same issue too, idk how it could be fixed.

**Comment by xIUPITERx** [comment]
What I find interesting is that the PiP is sometimes hidden behind other objects (sponsorBlock skip button, other flyouts like the queue, ...) and very rarely also behind the navigation bar, could it be an animation of some object that hides the PiP?

**Comment by xIUPITERx** [comment]
That's the Animation in Slowmotion

https://user-images.githubusercontent.com/97352673/203839410-5caf5947-2d57-4556-b5e9-001b664a5362.mp4

**Comment by Bnyro** [comment]
Yes, that's the animation, but still there's a black screen for like a second although the transition inside the PiP window has already ended 🤔

**Comment by swarnenduu** [comment]
Exactly. It's weird. This doesn't occur with the YouTube app

**Comment by xIUPITERx** [comment]
That's the Animation in Slowmotion from YouTube

https://user-images.githubusercontent.com/97352673/203844699-cae5bde5-3d46-467c-ac47-bf77ae0de04d.mp4

**Comment by Bnyro** [comment]
So pretty much the same except for the black screen :(((

**Comment by swarnenduu** [comment]
Yup. That's seamless

**Comment by xIUPITERx** [comment]
In youtube the aspect ratio from the player never changes, in Libretube the exoplayer gets is compressed.
