### ISSUE TITLE
There is no button to go to the previous video

### ISSUE THREAD

**Issue by Binleti** [libre-tube/LibreTube#2024]
### Describe your suggested feature

There is no button to go to the previous video.
https://user-images.githubusercontent.com/118555547/203722288-f2e18a00-7131-4d82-ae2e-91b994dff951.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by rozari0** [comment]
It's Also fixed.

**Comment by Binleti** [comment]
Is it resolved?

**Comment by rozari0** [comment]
> 

![Screenshot_20221124-140443](https://user-images.githubusercontent.com/61970262/203727645-b6b82e43-f83c-49da-ae99-ac903b34d05c.jpeg)
Yes it is. Screenshot from latest debug.

**Comment by xIUPITERx** [comment]
> Yes it is. Screenshot from latest debug.

Not in my debug version.

**Comment by Bnyro** [comment]
You have to enable the buttons in the player settings!

**Comment by xIUPITERx** [comment]
I have enabled it in the settings and the `skip to next video button` works without problems.

**Comment by Bnyro** [comment]
Just tested, seems like it's really broken. I'll have a look!

**Comment by rozari0** [comment]
> Just tested, seems like it's really broken. I'll have a look!

Now it's broken for playlists. :(

**Comment by Bnyro** [comment]
Works fine for me :eyes:

**Comment by xIUPITERx** [comment]
It's true, if you select ```Play all``` in the playlist overview, no skip forward/back buttons appear, even if the queue is full of videos.
But it only affects the first video, when the next video is played via ```Autoplay```, the buttons appear again, and when you go back, the first video also has the buttons again.

**Comment by Bnyro** [comment]
Oh, right. That's because the videos are loaded asynchronously into the playing queue, which means when the player gets created and checks for videos in the queue there are no videos inside yet. Please open a new issue for it if you want to :joy:
