### ISSUE TITLE
Create playlist button is not working.

### ISSUE THREAD

**Issue by Binleti** [libre-tube/LibreTube#2025]
### Describe your suggested feature

The button for creating a playlist does not work.

https://user-images.githubusercontent.com/118555547/203725393-31df6f11-4e5c-4910-92cf-d522d8b0233e.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by rozari0** [comment]
It's fixed, wait till next update.
