### ISSUE TITLE
Cannot delete playlist.

### ISSUE THREAD

**Issue by Binleti** [libre-tube/LibreTube#2026]
### Describe your suggested feature

Unable to delete playlist.

https://user-images.githubusercontent.com/118555547/203727795-2aaa2b86-bb4a-48a7-87b1-d528ba71ca51.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
this is a bug, not an enhancement.

**Comment by Binleti** [comment]
Since there is no error report, this is what I did.

**Comment by Binleti** [comment]
Simply delete the playlist.

**Comment by xIUPITERx** [comment]
If there is a certain function that does not work because of a bug, it is still a bug report, even if there is no error report.
Enhancement is used for new ideas

**Comment by Bnyro** [comment]
It got deleted, just refresh!
