### ISSUE TITLE
Disable SponsorBlock temporarily while watching

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#2030]
### Describe your suggested feature

Still have the standard SponsorBlock settings, but add the possibility to set SponsorBlock individually for subscribed channels. 
(Best on the corresponding channel page, or the Subscription view.)
Also have a button to delete every costum setting

For example:
automatically skip all sponsor segments, but for a few channels you can manually skip sponsor and self promotion segments.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I feel like that'd be really pointless efforts, I don't really get why you want to enable SponsorBlock only for some channels to be honest. Anyways the time of implementation wouldn't be worth it imo.
Therefore no plans for that.

**Comment by Bnyro** [comment]
Though, if you only want to skip from specific channels I suggest you use the `Skip manually` option and then only skip segments from channels you want to.

**Comment by xIUPITERx** [comment]
The problem is, that I like the auto skip funtion very much, but on some channels the advertisment is so well integrated into the video, that I would like to watch it.

**Comment by Bnyro** [comment]
Maybe it would be better to have an option to temporarily disable it while watching a video?

**Comment by xIUPITERx** [comment]
I find the new button extremely useful, but could it perhaps be made smaller (and perhaps use a more minimalistic shield icon - the detached border around it doesn't quite fit in with the app's design language -)?
Also, it should only be displayed if the current video contains any skippable segments.

**Comment by xIUPITERx** [comment]
Whether the button should switch between on and off or between auto skip and manual is probably again a matter of opinion.
