### ISSUE TITLE
Custom folder for downloaded videos/audios

### ISSUE THREAD

**Issue by MatsG23** [libre-tube/LibreTube#2041]
### Describe your suggested feature

It would be cool if you could choose the folders where videos and audios (both in different folders) would be downloaded to. 

### Other details

You should also either
1. tell people where the downloader saves the file
2. require to set the folders I am requesting on first download

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That would require to add storage permissions to LibreTube which is not going to happen.
I've putting quite some efforts to get rid of these, as I think that a video player app shouldn't require any storage permissions. Apart from that not using such permissions makes it easier for users to trust the app :)

**Comment by Bnyro** [comment]
Fair enough, I'll keep it open but probably won't have a look soon.

Please stop tagging me, I read any issues or comments anyways!

**Comment by ModcoLocko** [comment]
I would like to add to this, I am sorry if this comes off as spam.

I already trust LibreTube, its open source. But I do want to be able to simply download my videos to a folder as a normal mp4 file with audio and video in one. Not being able to do this is a major turnoff, and is making me consider switching back to newpipe, even with the piped account features, sponsor block integration, and great design, all which is use/appreciate, I think that being able to download videos is more important.

I also think this a common opinion, the type of people to use alternative Youtube clients, are also the type of people who like having large local media collections.

**Comment by Bnyro** [comment]
No plans for that currently since it would require selecting the folder each time starting a new download.
Apart from that these permissions granted to a folder are only temporary, thus the directory would have to be re-chosen after an app restart or when attempting to continue/resume a paused download.
LibreTube doesn't aim to be a fully featured downloader that can be used with other apps, please look for alternatives if you're searching for a video downloader that supports being used by other apps.
I also wanted to mention that downloaded files are stored at `Android/data/com.github.libretube/files`, so you can copy them from there manually if you wanted to.

**Comment by ThomasLeigh** [comment]
It would be very useful (especially for not so technical users who may not know where the videos are saved by default) to be able to define custom download path. It would be fantastic if it would be set up in two ways for a user to choose:

1. Define a custom download path and don't ask for it again.

or

2. Ask to choose a custom path every time a user wants to download something. 

Besides, I download various things to separate dedicated folders for better data organizing - and in such a case the option 2 described above would be very useful.

**Comment by deepadmax** [comment]
There is a third option. The path that is currently being used to store downloaded content could be made the default. You could be allowed to configure a custom path in the settings. Whenever you download a video, if a custom path has been set, it'll ask for permissions to that directory for that one time, every time anew. That way you wouldn't need to re-enter the path, you'd only need to say yes.

**Comment by MiShared** [comment]
Why is this closed?
This is obviously an extremely important and valuable concept. 
We all want to be able to use different app to play in background on loop etc.
So simply saying nup seems incredibly shortsighted.
If you need donations to cover time or really get annoyed about it people would jump to help.
They trust you. They think you're an amazingly good programmer.
Everyone supports you and thinks you've created a valuable app and thinks you have brought a big up finger to nasty youtube policies

**Comment by quadroli** [comment]
I am also grateful for LibreTube and would like for this feature to be reconsidered please, it would be very handy. Also, on Android 12 I can not access ``Android/data/`` via my file manager unless I root my device

**Comment by quadroli** [comment]
Tbh, I have used LibreTube a little more and I'm loving it honestly, I think as it is, its just perfect as in if you think bout the UX, its just fitting, yes you can download videos, however LibreTube wasn't aiming to be a youtube video downloader. As alternatives exist for that purpose already. What LibreTube us is a media player, and it excels at that phenomenally
Thank you, LibreTube starter and contributers.

**Comment by moolight-seashell** [comment]
this is closed ? for a download folder ? and for a permission thing ? very confusing
a download feature with only private file is kinda useless
