### ISSUE TITLE
Brightness doesn't return to normal after changing it from swipe control.

### ISSUE THREAD

**Issue by rozari0** [libre-tube/LibreTube#2046]
### Steps to reproduce

1. Open a video
2. Change it's brightness with swipe control
3. Close it and go back to LibreTubes home

### Expected behavior

Should return to default brightness that is set in device.

### Actual behavior

It remains the same. 

### LibreTube version

#2040

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Kruna1Pate1** [comment]
Initially, I thought making brightness consistent throughout the app is a better idea. But, I think it would be better if changes only affect when the player is in full-screen (i.e. landscape) that's how most of the apps work. Anyways, will try to implement this.
