### ISSUE TITLE
Implement various subtitle font sizes

### ISSUE THREAD

**Issue by luca-e075e** [libre-tube/LibreTube#2051]
### Describe your suggested feature

If LibreTube is not going to use the default Android subtitles setting, then consider implementing its own subtitle sizes such as small, normal and big or a px value

Thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We could just make that a slider preference allowing to choose it, that's probably the easiest way to implement it.
