### ISSUE TITLE
Subtitles incorrect position

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [libre-tube/LibreTube#2054]
### Steps to reproduce

Subtitles are cropped in zoom mode. But in NewPipe zoom mode all good (same player).

### Expected behavior

![Screenshot_2022-11-25-23-57-48-608_org polymorphicshade newpipe](https://user-images.githubusercontent.com/52075465/204054975-651cbd37-9ee7-4206-b6c5-528ed5c07cc5.jpg)

### Actual behavior

![Screenshot_2022-11-25-23-53-01-164_com github libretube](https://user-images.githubusercontent.com/52075465/204054989-bfac3d66-7dd5-4eb5-93fc-82b0c12e6385.jpg)

### LibreTube version

0.8

### Android version

android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Kruna1Pate1** [comment]
fixed in #2263
