### ISSUE TITLE
Support for subscription notifications via unifiedpush. 

### ISSUE THREAD

**Issue by Anas-Sherif** [libre-tube/LibreTube#2055]
### Describe your suggested feature

Add support for unifiedpush.
https://unifiedpush.org/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We already have notifications that are independent from UnifiedPush and GMS.

**Comment by Anas-Sherif** [comment]
Sure, but libretube would need to have another process in the background, using more power. But if it uses UnifiedPush then the only service in the background would be UnifiedPush therefore saving power.

**Comment by d4f5409d** [comment]
I agree with @Anas-Sherif, this is question about power managemant, and / or power consumption. I'd love to see UnifiedPush afterall, but I can understand, why you don't want to work on it.

**Comment by ghost** [comment]
Applications like IronFox (web browser) have introduced it for similar reasons as @d4f5409d has stated.

**Comment by Bnyro** [comment]
LibreTube doesn't have a server component, so this can't work anyways...

UnifiedPush requires a server that sends the notifications, but currently all the data is loaded inside LibreTube.
