### ISSUE TITLE
Can't download video/audio on android 5.1

### ISSUE THREAD

**Issue by Nidal-Bakir** [libre-tube/LibreTube#2059]
### Steps to reproduce

Download any video/audio will reproduce the bug on `Android 5.1`

### Expected behavior

The video been downloaded.

### Actual behavior

The app crashes.

### LibreTube version

0.8.0

### Android version

Android 5.1

### Other details

> java.lang.RuntimeException: Unable to start service com.github.libretube.services.DownloadService@21f5ddfc with Intent { cmp=com.github.libretube/.services.DownloadService (has extras) }: java.lang.SecurityException: need WRITE_EXTERNAL_STORAGE permission to use DESTINATION_FILE_URI: uid 10121 does not have android.permission.WRITE_EXTERNAL_STORAGE.
> 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3975)
> 	at android.app.ActivityThread.access$2300(ActivityThread.java:218)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1842)
> 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 	at android.os.Looper.loop(Looper.java:145)
> 	at android.app.ActivityThread.main(ActivityThread.java:7007)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at java.lang.reflect.Method.invoke(Method.java:372)
> 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
> Caused by: java.lang.SecurityException: need WRITE_EXTERNAL_STORAGE permission to use DESTINATION_FILE_URI: uid 10121 does not have android.permission.WRITE_EXTERNAL_STORAGE.
> 	at android.os.Parcel.readException(Parcel.java:1546)
> 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:185)
> 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
> 	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:476)
> 	at android.content.ContentResolver.insert(ContentResolver.java:1260)
> 	at android.app.DownloadManager.enqueue(DownloadManager.java:1336)
> 	at com.github.libretube.services.DownloadService.downloadManagerRequest(DownloadService.kt:53)
> 	at com.github.libretube.services.DownloadService.onStartCommand(DownloadService.kt:223)
> 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3958)
> 	... 9 more
>     

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The issue is gone since we use our own download manager implementation
