### ISSUE TITLE
Make comment section appearance as a popup

### ISSUE THREAD

**Issue by tvnmguy** [libre-tube/LibreTube#2061]
### Describe your suggested feature

Make comment section appearance as a popup manner

### Other details

![img_2022_11_26_10_35_26](https://user-images.githubusercontent.com/116799295/204077462-fa0b18d9-1178-4ab1-bb17-6ee4422a7f7c.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ARBoyGo** [comment]
Da athe vanoo? Pop up is horrible da.

**Comment by tvnmguy** [comment]
> Da athe vanoo? Pop up is horrible da. 

I think popup looks better just like youtube

**Comment by ARBoyGo** [comment]
It's been months without YouTube, I don't know how tis work. Let me check in a minute. The Dev is asking opinion on users in matrix.

**Comment by ARBoyGo** [comment]
Mmm, I tired it, This doesn't work on vertical. Just horizontal.

**Comment by tvnmguy** [comment]
> Mmm, I tired it, This doesn't work on vertical. Just horizontal. 

Shey...!, How YT implemented that?

**Comment by ARBoyGo** [comment]
Macha don't worry, Nammle idhna korachi discuss chaynund.

**Comment by tvnmguy** [comment]
> Macha don't worry, Nammle idhna korachi discuss chaynund. 

Good

**Comment by tvnmguy** [comment]
1:

•Highlight mother comment/main comment's background.

If we select dark theme from settings, then highlight with black tint/gradient.
If we select black theme, then highlight with dark tint/gradient.

•Make comment authors name size small from comments and dimmed for avoiding mind distraction and better readability.

•Make mother comment/main comment's icon/avatar little bit larger from comment replies account icon/avatar (Reduce size of comment replies account icon/avatar).


![img_2022_11_26_20_52_21.jpg](https://user-images.githubusercontent.com/116799295/204096797-ce248905-56fa-4063-a947-296fd9fd6d4e.jpg)

![img_2022_11_26_20_51_11.jpg](https://user-images.githubusercontent.com/116799295/204096804-5fb649d1-4e2a-4389-94a3-b496f17149dd.jpg)

![img_2022_11_26_20_53_42.jpg](https://user-images.githubusercontent.com/116799295/204096811-9047f8ca-aefb-4c46-8630-42249213a03f.jpg)


YT Mobile app👇

![201574211-aef7248c-4f65-44b4-8d48-7ea070daf179.jpg](https://user-images.githubusercontent.com/116799295/204096831-1064e115-22a8-406e-9af1-30118594f504.jpg)

![201574238-10dab378-e397-4642-8b33-e43633d855d6.jpg](https://user-images.githubusercontent.com/116799295/204096839-4be1c00a-e4f8-4acd-8420-e7e729da7636.jpg)


2:

Adjustment of Replies texts, Mother comment/Main comment, Comment replies, Account icon/avatar for better visual experience and readability 👇

![IMG_20221126_210205.jpg](https://user-images.githubusercontent.com/116799295/204096856-c50680e6-09c8-4578-8534-bc3eae3eb160.jpg)


![IMG_20221126_210151.jpg](https://user-images.githubusercontent.com/116799295/204096860-d48f23f7-f1c6-4c77-a3a7-3a452f923f27.jpg)


![IMG_20221126_210137.jpg](https://user-images.githubusercontent.com/116799295/204096876-3bb6c3f6-6a00-453a-ac8d-651746ad4b84.jpg)


Advantage: We can eliminate scattered feeling. All (Replies, Mother/Main comment, Comment replies) are in single line.

![IMG_20221126_205627.jpg](https://user-images.githubusercontent.com/116799295/204096888-c6607025-8aef-472f-954e-b33f856f435d.jpg)
