### ISSUE TITLE
Make subscription list appearance as a popup

### ISSUE THREAD

**Issue by tvnmguy** [libre-tube/LibreTube#2062]
### Describe your suggested feature

Make subscription list appearance as a popup manner

### Other details

![img_2022_11_26_12_51_19](https://user-images.githubusercontent.com/116799295/204077564-c2f5a148-09a5-4647-a10f-45e6aa56dd6b.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't see a use case for listing subscriptions as a bottom sheet. I agree that it might make sense for comments but for subscriptions it would be pretty much useless imo!

**Comment by tvnmguy** [comment]
@Bnyro 

I know in the case of subscription list that's useless

I suggested because the two bars (subscription and comments) looks similar. So I think same functional visual appearance for two bars would be nice and also helps to maintain uniformity in visual behavior.

![IMG_20221126_133808.jpg](https://user-images.githubusercontent.com/116799295/204080775-66c3c27e-c5e1-41eb-acbd-ec6a5a534c60.jpg)
