### ISSUE TITLE
Add option to hide comment section.

### ISSUE THREAD

**Issue by rozari0** [libre-tube/LibreTube#2066]
### Describe your suggested feature

LT may show comments by default, But user should have ability to hide the comment section.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Feature already exists, click on this to show/collapse comments section 
! [20221126_114825.jpg](https://user-images.githubusercontent.com/50032603/204082656-f97c0f71-c38d-4f1c-a238-79f19a24018d.jpg)

**Comment by akano12** [comment]
![20221126_114825.jpg](https://user-images.githubusercontent.com/50032603/204082686-94105593-098b-44cd-a2b2-56d3c41f734d.jpg)

Feature already exists 
Click to show/collapse comments sections

**Comment by Bnyro** [comment]
That's an argument, they're not expanded by default and thus it requires manual interaction to "enable"/show them.
However, adding an option to hide the button would not be that hard, the question is how useful it'd be.

**Comment by xIUPITERx** [comment]
Maybe add an option to the ``` Alternative player layout``` to have the comments not auto expanded.
But hiding the button, what use would it bring?

**Comment by Bnyro** [comment]
> Maybe add an option to the ` Alternative player layout` to have the comments not auto expanded. But hiding the button, what use would it bring?
>
With #2061 they wouldn't even show anymore by default, so that wouldn't be a thing anymore.

**Comment by rozari0** [comment]
> That's an argument, they're not expanded by default and thus it requires manual interaction to "enable"/show them. However, adding an option to hide the button would not be that hard, the question is how useful it'd be.

Yeah, that's what I meant. I was trying to get an option to hide that button.

**Comment by akano12** [comment]
@Bnyro sorry for hijacking this report, i was about to open an enhancement request but my internet is acting up.

Just want to ask if it's possible to tell when comments are disabled on a video or if video have no comments (in both cases the show comments btn is visible) . I was watching a video and kept tapping show comments but nothing happened, checked youtube and saw that comments were disabled lol.

**Comment by xIUPITERx** [comment]
See #2093, that could solve it.

**Comment by akano12** [comment]
> See #2093, that could solve it.

Add "Show if comments are disabled on video" in your suggestion

**Comment by xIUPITERx** [comment]
>Add "Show if comments are disabled on video" in your suggestion

Done

**Comment by Bnyro** [comment]
Closing as not planned with https://github.com/libre-tube/LibreTube/issues/2206#issuecomment-1336186749 in mind

**Comment by MintMain21** [comment]
I'm sorry that people have been giving you a hard time about different cosmetic choices. 

I myself prefer to have the comments button disabled, but I understand that there are bigger concerns for the project than that. 

If I could offer a simple suggestion (and I emphasize that this is a suggestion and not a demand), I feel like most users who would rather hide the reccomended feed would also rather hide the comments by default, so maybe a sub option to hide the reccomendations with the comments (rather than the comments independent of the reccomendations) would be nice?

In any case, the core functionality of the app is excellent, and addressing actual bugs should be the first priority of course, and there's always Newpipe as an option as well.

**Comment by flexxxxer** [comment]
Everyone is welcome to use [FlexTube](https://github.com/flexxxxer/FlexTube) where ability to hide comment section is available. FlexTube is LibreTube with few changes, so user experience pretty close.

Notice: Bnyro [allowed](https://github.com/libre-tube/LibreTube/discussions/8168#discussioncomment-16308171) to mention FlexTube in issues being addressed by FlexTube
