### ISSUE TITLE
Making captions an optional feature in popup player

### ISSUE THREAD

**Issue by happyeggchen** [libre-tube/LibreTube#2067]
### Describe your suggested feature

![IMG_20221126_161559_280](https://user-images.githubusercontent.com/38799701/204079396-46b38d19-717b-4384-8232-30c1d4a32f2b.jpg)

Libretube display captions on popup player by default.
But sometimes the caption is too big to be displayed and they fill up the window

Maybe we can make this an optional feature, like "Captions in popup (ON/OFF)"?

### Other details

Thank you guys for bringing us this awesome app...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I will fill out all of the requested information in this form.

**Comment by rohandebsarkar** [comment]
This also happens when the player is minimized.
