### ISSUE TITLE
Enter/Exit fullscreen gesture

### ISSUE THREAD

**Issue by swarnenduu** [libre-tube/LibreTube#2070]
### Describe your suggested feature

Swipe up to enter fullscreen ⬇️
![Screenshot_20221126-135939-823](https://user-images.githubusercontent.com/86847643/204080130-c0280363-462c-49ca-b9af-724a6b13cba6.png)

Swipe down to exit fullscreen ⬇️
![Screenshot_20221126-140140-070](https://user-images.githubusercontent.com/86847643/204080147-a6cc0cae-581e-4453-98b3-e85060cc4665.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by swarnenduu** [comment]
The swiping if implemented should happen on the middle of the screen to stop any conflict between this gesture and the volume/brightness gesture.

**Comment by xIUPITERx** [comment]
In combination with #2020 it could become pretty useful E.g. for one-hand control

**Comment by swarnenduu** [comment]
Exactly.

**Comment by Bnyro** [comment]
How should the swipe down to leave fullscreen be possible though? Doesn't it conflict with the gestures for volume and brightness?

**Comment by Monirzadeh** [comment]
@Bnyro 

It could be in three-way that use can select one or more in settings
1. a long press than swipe down.
2. it can be in the middle section of video (I don't like that chance of conflict)
4. back function (like gesture navigation) swipe right or left side of video to the center exit full screen.

I personally prefer number 3, but it is better, user can choose them in settings.
What do you think?

**Comment by Monirzadeh** [comment]
> nter the
I think it is good.
About back gesture, it should be done twice, or after you tap video (show status bar) to exit full-screen. A little annoying, but it is good enough.
