### ISSUE TITLE
autoplay 5s Countdown

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#2074]
### Describe your suggested feature

Add an 5 second countdown before autoplay starts the next video. (Like YouTube does it)
Dimm current the video in the background and have flyout buttons:

1. to replay the current video, 
2. cancel the countdown
3. skip the countdown and player the next video instantly

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Fidannyan** [comment]
Rather than adding this feature, warn the user 1 minute before the next video is played. This option will be more useful because it will turn off autoplay from the player if the user wants.

Warning:1 minute left to play the next video, turn off autoplay to cancel.

**Comment by xIUPITERx** [comment]
I think with the manuell SponorBlock button we have enough flyouts (I'm not sure if that's the right term).
And the the countdown would allow a smoother transition between videos. (I'm not sure if you would want it always active, while listing to music it could be contraprodactiv)
