### ISSUE TITLE
long press version to copy

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#2077]
### Describe your suggested feature

Long press the LibreTube version number in the settings to copy it (would he useful for the long debug version numbers).

### Other details

![Screenshot_20221126-115208_LibreTube Debug](https://user-images.githubusercontent.com/97352673/204085254-d9a4ce1d-2845-49f4-9a5b-1de141cc9328.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't think that makes sense as the version code is only there for constantly increasing the version number to allow updating the app. For bug reports, one should always reference the corresponding PR instead.
