### ISSUE TITLE
Implement 'You are all caught up' in subscription feeds

### ISSUE THREAD

**Issue by tvnmguy** [libre-tube/LibreTube#2078]
### Describe your suggested feature

Add 'You have seen all new posts' like reminder when scrolling through subscription feeds.

### Other details

![img_2022_11_26_15_01_35](https://user-images.githubusercontent.com/116799295/204085370-8838134e-ec63-481e-bb23-e4d3acf0ef1c.jpg)

![IMG_20221126_150919](https://user-images.githubusercontent.com/116799295/204085375-85be2bbd-36af-46cb-988a-9a058f1ffcd6.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by tvnmguy** [comment]
![img_2022_11_26_21_34_34.jpg](https://user-images.githubusercontent.com/116799295/204098031-b30b881d-fee3-4d29-9567-25af1a74296a.jpg)

**Comment by Bnyro** [comment]
Do you have an SVG file for the check arrow with the circle that you could share here? That'd save anyone who'll work on it time searching for one :)

**Comment by tvnmguy** [comment]
@Bnyro 

Sorry, I don't have it. The first one is from Instagram mobile app (screenshot - crop - overlay edit). The last one maded with using MIUI gallery. I'm not a professional and all of my sketch maded with the combination of MIUI gallery and IMG.LY editor mobile app.

**Comment by Bnyro** [comment]
No worries, thanks anyways :)

**Comment by xIUPITERx** [comment]
Could you either reduce the size of the icon (make it dependent of the video layout and grid columns, so it's not bigger than then thumbnail a video), allow us to deactivate it, or maybe even make both.

**Comment by Bnyro** [comment]
Oh, I didn't think about how it looks when using a grid layout, I don't think there are issues when having only one video per row. 
Making the icon size depend on the space available is not really possible as it's in a different view. I don't think the size needs to be decreased though as it's not that big.

**Comment by xIUPITERx** [comment]
I mean the icon is as big as two thumbnails, isn't that to much ?
![Screenshot_20221128-200305_LibreTube Debug.jpg](https://user-images.githubusercontent.com/97352673/204403401-bc909e0d-df2d-4c16-acbf-71fdf8126254.jpg)
![Screenshot_20221129-003630_LibreTube Debug.jpg](https://user-images.githubusercontent.com/97352673/204403516-2c379920-24be-4e7f-b359-6793eda3ffc8.jpg)
With the big thumbnails it looks okay.
![20221129_003714.jpg](https://user-images.githubusercontent.com/97352673/204403617-d3ec5269-e5fb-4d4c-b3c3-e3725473ccc8.jpg)
![Screenshot_20221129-003658_LibreTube Debug.jpg](https://user-images.githubusercontent.com/97352673/204403630-4de0cf1f-b283-4c7e-a316-1dbdb234395a.jpg)
But compared to the "2 grid columns" size it's to high again.

If it was dynamically based on the height of one row of thumbnails (as many as will fit next to each other), I think it would look better.
