### ISSUE TITLE
Pinch Zoom displays buttons

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#2085]
### Steps to reproduce

If you use Pinch Zoom (which works great) the player buttons appear after the video was zoomed in or out

### Expected behavior

Pinch Zoom should only change the resize mode

### Actual behavior

the player buttons appear as if you had tapped on the screen to pause the video (the swipe gestures work just fine)

### LibreTube version

latest debug

### Android version

Android 12 One UI 4.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
Also have an option to disable ``Pinch to Zoom``.

**Comment by Bnyro** [comment]
Read the version provided in the issue template, added with #2072

**Comment by Bnyro** [comment]
That's not true, it's easier to keep an overview when discussing under open issues as closed ones can be forgotten quite fast.

**Comment by Bnyro** [comment]
That doesn't make any sense because it would
1. result in lots of merge conflicts
2. would reduce the time alpha testers have to find bugs and regressions
3. there wouldn't really be discussion as almost nobody would test it before merging

**Comment by Bnyro** [comment]
Well, Linux has way more devs and testers involved than LibreTube has so I don't think they can be compared really.
