### ISSUE TITLE
Searchbar problems v2

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#2086]
### Steps to reproduce

(For more context see #1599.)

1. Search multiple times.

2. If the search was opened and the app is a few minutes in the background, the searchbar is closed when you return.

### Expected behavior

 You should go back to the last search result.

### Actual behavior

The searchbar closes.

### LibreTube version

0.8.0

### Android version

Android 12 One UI 4.1

### Other details

https://user-images.githubusercontent.com/97352673/203166606-d892e1b2-9278-4e32-a2a3-277d7367f5b5.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SajalRG** [comment]
Hi @Bnyro , With the new pull request https://github.com/libre-tube/LibreTube/pull/3831, search-bar closing issue is fixed as reported here. However, the query string won't reset to previous one.

[search-page-back-press.webm](https://github.com/libre-tube/LibreTube/assets/17106096/84eb50f6-ef4c-423b-9507-6357f8d6deff)

Do we expect search text also to be previous one?
I feel when pressing back the search text also should be replaced. Same behaviour is there in Youtube as well.
Let me know your thoughts.

**Comment by Bnyro** [comment]
@SajalRG 
Yes, that could be a valuable improvement, but I think the current way works well enough for now.
However since it's not part of this issue, I'll be closing this one now since your previous PR already fixed that!
