### ISSUE TITLE
Change Resize mode for PiP

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#2092]
### Describe your suggested feature

Change the Resize mode to Zoom or Fill (who uses Fill) if PiP is used.
It prevents the Pip having black bars on the side and so looking way cleaner.
~~You could also change the aspect ratio of the PiP, but one for horizontal and one for vertical videos ~~(shorts #1644)~~ is enough.~~

### Other details

![Screenshot_20221126-192229_One UI Home.jpg](https://user-images.githubusercontent.com/97352673/204103527-dbe88b4a-8735-4151-a876-3265e910124a.jpg)
![Screenshot_20221126-192041_One UI Home.jpg](https://user-images.githubusercontent.com/97352673/204103532-6c342fde-f466-49fa-811c-01eceece8ee2.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Shorts videos wouldn't be viewable in PiP at all then since zooming into them is useless due to their aspect ratio. We should probably only do that if the width of the video is greater than its height!

**Comment by xIUPITERx** [comment]
The example was actually only there for ilustration, but it probably confuses more.

**Comment by xIUPITERx** [comment]
> We should probably only do that if the width of the video is greater than its height!

Maybe from an aspect ratio of 3:2?

**Comment by xIUPITERx** [comment]
For me it is stuck in an aspect ratio of shorts

https://user-images.githubusercontent.com/97352673/204142936-22b29ef6-2cdf-481e-bf58-40f71bd1f3ff.mp4

**Comment by xIUPITERx** [comment]
@Bnyro 
For me it is stuck in an aspect ratio of shorts.

https://user-images.githubusercontent.com/97352673/204142936-22b29ef6-2cdf-481e-bf58-40f71bd1f3ff.mp4

**Comment by Bnyro** [comment]
Weird, I don't have that issue :/

**Comment by xIUPITERx** [comment]
I wasn't able to reproduce it either, if it comes again I'll get back to you.
