### ISSUE TITLE
New comments sheet: empty message 

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#2093]
### Describe your suggested feature

1. If the video has no comments, show a message like: ``No comments found for this video``
2. If the comments are disabled, show a message like: ``Comments are disabled for this video`` 

An empty sheet doesn't look that great.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
Also add an message if the comments are disabled.

**Comment by xIUPITERx** [comment]
Also add the message ``Comments are disabled for this video`` if the comments are disabled.

**Comment by xIUPITERx** [comment]
Looks like #2093 and #2094 are in conflict
 ![Screenshot_20221127-143425_LibreTube Debug.jpg](https://user-images.githubusercontent.com/97352673/204138222-eb6889c7-03f2-4618-bc84-a45979845ade.jpg)

**Comment by xIUPITERx** [comment]
@Bnyro 
Looks like #2093 and #2094 are in conflict.
 ![Screenshot_20221127-143425_LibreTube Debug.jpg](https://user-images.githubusercontent.com/97352673/204138222-eb6889c7-03f2-4618-bc84-a45979845ade.jpg

**Comment by Bnyro** [comment]
Oh, true. And I just realized that the error message should be `disabled by the uploader` and not `author` ...
