### ISSUE TITLE
Switching from fullscreen view to PIP makes launcher UI disappear

### ISSUE THREAD

**Issue by Sir-Photch** [libre-tube/LibreTube#2097]
### Steps to reproduce

1. Use a custom launcher (Kvaesitso, Lawnchair)
2. Open a video in fullscreen view
3. Switch to home screen

### Expected behavior

The PIP overlay should be shown on top of the Launcher UI.

### Actual behavior

The Launcher UI disappears, PIP is only visible on top of wallpaper.
Only returning to home-screen once more makes the UI come back.

### LibreTube version

0.8.0

### Android version

Android 13

### Other details

I could not reproduce this with other PIP apps, like Netflix. And I suspect that this is not an issue of the launcher, since this has also occurred to me when using Lawnchair.

Here is a video showing the issue:

https://www.veed.io/view/cae339c9-56e9-4b3c-a76e-ca8dd3e91b46?sharingWidget=true&panel=share
(apparently, this link will get invalid after 24hrs. In that case, try this one: https://ufile.io/5hpdyo8g)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
Have you tested it with other apps which use pip?

**Comment by Sir-Photch** [comment]
> I could not reproduce this with other PIP apps, like Netflix.

**Comment by Bnyro** [comment]
Could you please retry that with the latest debug version?

**Comment by Sir-Photch** [comment]
Where can I get the debug-versions from? I can't find them under the release-tags / in my fdroid-client.

**Comment by Bnyro** [comment]
You can find them by searching for the `CI` label under the `actions` tab of the repo (https://github.com/libre-tube/LibreTube/actions), for example [this build here](https://github.com/libre-tube/LibreTube/actions/runs/3554764026).

**Comment by Sir-Photch** [comment]
Thanks for the link. I have tried the arm64-v8a build, and the issue persists.

**Comment by Sir-Photch** [comment]
Seems like this got fixed in the last update.
