### ISSUE TITLE
[Feature] Media player notification

### ISSUE THREAD

**Issue by saurabhinabys** [libre-tube/LibreTube#21]
I hope this is in your plans to implement, but when video is playing in background a notification with controls will be helpful.

**Comment by rimthekid** [comment]
Yes I'll add it to the projects

**Comment by Alexandero89** [comment]
@lilcheti 
did you had any progress with this feature?
I would otherwise start to implement this and provide a PR

**Comment by lilcheti** [comment]
nope go ahead will be happy!
