### ISSUE TITLE
Monochrome theme

### ISSUE THREAD

**Issue by Bnyro** [libre-tube/LibreTube#2111]
### Describe your suggested feature

Continuation of the discussion at #1929 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
@xIUPITERx
We're going to continue it here.
Two things/questions:
1. How do we call the theme?
2. What are we doing when the user selects light as theme mode? I'd suggest that we just inverse the theme for that, which means a pure white theme with a black font.

**Comment by xIUPITERx** [comment]
We could call it it something like ``minimalistic monochrome / grey``.

**Comment by Bnyro** [comment]
Okay, I've created a theme for it now, see #2113 

What you'd need to do now is
1. Fork the project if you didn't yet and clone your fork to your PC (would be good if you already have GitHub access via SSH set up)
2. Checkout to the `themes` branch
3. Build the app with Android Studio and select `Black and White` as accent color in the settings
4. Edit the [`values/colors.xml`](https://github.com/libre-tube/LibreTube/blob/themes/app/src/main/res/values/colors.xml#L301-L358) as well as [`values-night/colors.xml`](https://github.com/libre-tube/LibreTube/blob/themes/app/src/main/res/values-night/colors.xml#L301-L358) as you want to and test it from time to time by rebuilding the app
5. Once you're done, commit and push your changes
6. Finally open a PR :)

**Comment by Bnyro** [comment]
> We could call it it something like `minimalistic monochrome` or `minimalistic grey`.
>
True, sounds good :)
Currently it's called `Black & White`, but we can just change that before merging it into the master branch.

**Comment by Bnyro** [comment]
As every theme also needs a light version, for the monochrome theme the light version should probably just pure white with dark grey / black accents, not sure about that though

**Comment by xIUPITERx** [comment]
Thank you,
I'll start as soon as I have time.

**Comment by xIUPITERx** [comment]
![image](https://user-images.githubusercontent.com/97352673/204336876-b4f0b6ce-3ace-4956-8db0-ce28bcdf6108.png)
Is this the right place?

**Comment by xIUPITERx** [comment]
> 3\. and select `Black and White` as accent color in the settings

How can i do that?

**Comment by xIUPITERx** [comment]
How can I see my design in the emulator?

**Comment by Bnyro** [comment]
> > 3. and select `Black and White` as accent color in the settings
> 
> How can I do that?
>
Just inside the app in the emulator :)

> How can I see my design in the emulator?
>
Should appear when you select the correct theme in the app's  settings. Note: You have to rebuild the app each time before testing a change.

**Comment by Bnyro** [comment]
> ![image](https://user-images.githubusercontent.com/97352673/204336876-b4f0b6ce-3ace-4956-8db0-ce28bcdf6108.png) Is this the right place?
>
Yes, the new theme is the one most at the bottom

**Comment by xIUPITERx** [comment]
![image](https://user-images.githubusercontent.com/97352673/204349325-ca7bb49c-6e05-4fdf-9620-cfe345ff163d.png)
I can select the new Theme in the appearance_settings.xml but not in the emulated app.

**Comment by Bnyro** [comment]
Just tested, works fine for me if building from the correct branch!

**Comment by xIUPITERx** [comment]
I used the wrong branch, will try it again with the correct one.

**Comment by xIUPITERx** [comment]
How can I change the branch?

**Comment by Bnyro** [comment]
On the bottom right of android studio there's a button for it :)

**Comment by xIUPITERx** [comment]
> Should appear when you select the correct theme in the app's settings. Note: You have to rebuild the app each time before testing a change.

![image](https://user-images.githubusercontent.com/97352673/204356748-485c253f-b04f-45e0-833f-45ff921df1fd.png)

With the marked button?

**Comment by Bnyro** [comment]
> > Should appear when you select the correct theme in the app's settings. Note: You have to rebuild the app each time before testing a change.
> 
> ![image](https://user-images.githubusercontent.com/97352673/204356748-485c253f-b04f-45e0-833f-45ff921df1fd.png)
> 
> With the marked button?
> 

>
Yes :)

**Comment by xIUPITERx** [comment]
What exactly does the color of the Navbar depend on?
I have not found a way to influence it directly.

**Comment by xIUPITERx** [comment]
I have found a few colour elements that do not seem to have any influence on the app.

`    <color name="black_white_theme_dark_primaryContainer">#FFFFFF</color>`
`    <color name="black_white_theme_dark_tertiary">#D50000</color>`
`    <color name="black_white_theme_dark_onTertiary">#00C853</color>`
`    <color name="black_white_theme_dark_tertiaryContainer">#FFBF00</color>`
`    <color name="black_white_theme_dark_onTertiaryContainer">#DD6700</color>`
`    <color name="black_white_theme_dark_error">#5C0053</color>`
`    <color name="black_white_theme_dark_errorContainer">#CA00FF</color>`
`    <color name="black_white_theme_dark_onErrorContainer">#00FFFF</color>`
`    <color name="black_white_theme_dark_onBackground">#2962FF</color>`
`    <color name="black_white_theme_dark_inverseOnSurface">#EA8AFF</color>`
`    <color name="black_white_theme_dark_inverseSurface">#677EBD</color>`
`    <color name="black_white_theme_dark_inversePrimary">#9A9448</color>`
`    <color name="black_white_theme_dark_shadow">#8000FF</color>`
`    <color name="black_white_theme_dark_surfaceTint">#200059</color>`
`    <color name="black_white_theme_dark_surfaceTintColor">#FF7474</color>`

I even gave them really distinctive colours, but it didn't help.
If you don't mind, it would be cool if you could mention where the colours are used, or how I can find out for myself.

**Comment by Bnyro** [comment]
That's possible, all themes inside the app currently are built with the [Material Theme Builder](https://m3.material.io/theme-builder#/dynamic), which generates all these colors by default as those are all the colors Material Design 3 can potentially use. However, we don't use all of these colors inside the app but might use more of them in the future. Hence there's no way for you to find out where the colors are used (except searching the code for their names). I've had a look and I don't think we use any of them currently. I'd recommend you just pick the colors for them according to their names:
Colors with `on` inside, e.g. onSurface are usually used for something like text or accents while the container colors are used rather for the background for example. Anyways they shouldn't be too important for the moment, in the worst case there'll be some small modifications needed to be made to the theme in the future eventually but that wouldn't be that of a problem.

**Comment by xIUPITERx** [comment]
I think there is an bug in the debug version I use in Android Studio, because the pure theme settings just changes the background of the settings page to black even in the "old" themes.

**Comment by Bnyro** [comment]
> I think there is an bug in the debug version I use in Android Studio, because the pure theme settings just changes the background of the settings page to black even in the "old" themes.
>
Well, what the pure theme does is making the background totally black in the dark and totally white in the light theme, so I don't think there's a bug

**Comment by Bnyro** [comment]
> As I am almost done with the first test version, what should I do next?
>
First one question, what's the current state of the light version? Did you create one too or only the dark one?
Second you can just create a PR against the `themes` branch of the LT repo after you pushed them to your fork. If you don't know how I'd recommend reading the GitHub docs for SSH connections via keys and how to commit/push changes with git.

**Comment by xIUPITERx** [comment]
>Well, what the pure theme does is making the background totally black in the dark and totally white in the light theme, so I don't think there's a bug

Should the settings page and the and the normal background have the same background?
But since it isn't in the normal version it's not really important.

**Comment by Bnyro** [comment]
> Should the settings page and the and the normal background have the same background?
> Would you mind sending a screenshot?

**Comment by xIUPITERx** [comment]
> First one question, what's the current state of the light version? Did you create one too or only the dark one? 

I did the light and dark theme. 
What about the minimalist monochrome rename?

> Second you can just create a PR against the `themes` branch of the LT repo after you pushed them to your fork. If you don't know how I'd recommend reading the GitHub docs for SSH connections via keys and how to commit/push changes with git.

Somehow I will make it work.

**Comment by xIUPITERx** [comment]
> Would you mind sending a screenshot?

<details>
<summary>My new Black & White theme</summary>
<img src="https://user-images.githubusercontent.com/97352673/205283708-e4d2d8b3-5dfe-4b92-8b98-a09e31398be7.png">
<img src="https://user-images.githubusercontent.com/97352673/205283717-1da7accf-2af3-45e9-a3ed-f618e32946b6.png">
</details>

<details>
<summary>The pleasurable purple theme</summary>

![Screenshot_20221202_123154](https://user-images.githubusercontent.com/97352673/205283729-1c5868e9-7015-438a-a62b-8741473625a2.png)
![Screenshot_20221202_123211](https://user-images.githubusercontent.com/97352673/205283734-977b30eb-9b37-462c-9ca2-c5d7d423e2d9.png)

**Comment by Bnyro** [comment]
> I did the light and dark theme. What about the minimalist monochrome rename?
> 
I will do that before merging it into the master branch :)

**Comment by Bnyro** [comment]
> 
>
Oh, right, I noticed that too in the emulator but it seems to work fine when running it on my phone, so I think it's only an issue of the emulator

**Comment by Bnyro** [comment]
No, I quite enjoy it as well as some users on [Matrix](https://matrix.to/#/#LibreTube:matrix.org). Hence it's already merged into master now :)

**Comment by Archeix7** [comment]
Not a fully black :(

**Comment by Bnyro** [comment]
> Not a fully black :(
>
Just use the`Pure Theme` Option?

**Comment by Archeix7** [comment]
Always enabled

**Comment by Archeix7** [comment]
I changed a couple of settings, especially ***_theme_dark_primary , and now I have +- a normal black theme

![Screenshot_20221203-093411478](https://user-images.githubusercontent.com/51048550/205430337-b39c9c10-0613-4a2b-ae37-d09df59775b8.jpg)
![Screenshot_20221203-093512430](https://user-images.githubusercontent.com/51048550/205430343-07d2107f-c3df-48ec-b581-a1340ac49221.jpg)

**Comment by Bnyro** [comment]
Why is the logo on the top left red? :o

**Comment by Archeix7** [comment]
Because you tied to ***_ theme_dark_primary several parameters and not only title color breaks

**Comment by Archeix7** [comment]
Links, buttons breaks too

**Comment by Archeix7** [comment]
If you do *** _ theme_dark_primary completely black, you will not see the buttons and links, but if you make red and very transparent, then the color will be a little visible in this case the interface will be black - magic

**Comment by xIUPITERx** [comment]
How does your non ``pure`` version looks like?

**Comment by Archeix7** [comment]
1. No

https://user-images.githubusercontent.com/51048550/205434728-2d12544c-ffae-4831-a3ec-b898fe090c47.mp4

**Comment by Archeix7** [comment]
2. Non pure (but i realy like My broken full black version) 

https://user-images.githubusercontent.com/51048550/205434843-09194685-20cd-4037-9e10-b57f73290cad.mp4

**Comment by Bnyro** [comment]
I won't mix in here, if you both agree on how you want to change it (or not change it) in the end feel free to make a PR then :)

**Comment by Archeix7** [comment]
I do not know how, and I have no computer. Moreover, I can’t imagine how the 1 parameter ***_theme_dark_primary is divided into several parts so that links, buttons and panels can be painted separately from each other
