### ISSUE TITLE
Add support for 360° and VR180 videos

### ISSUE THREAD

**Issue by ghost** [libre-tube/LibreTube#2126]
### Describe your suggested feature

Support properly playing back 360° and VR180 videos. The user should be able to move the video around using swipe gestures when in full screen mode with playback interface hidden. Swipe controls should be automatically disabled for these types of videos.

### Other details

ExoPlayer supports both formats

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
ExoPlayer might support them but the NewPipeExtractor and thus Piped as well don't!

**Comment by yhm4ps1jfp67nkv** [comment]
> ExoPlayer might support them but the NewPipeExtractor and thus Piped as well don't!

I see, so then I should wait until https://github.com/TeamNewPipe/NewPipeExtractor/pull/488 gets merged, right?

**Comment by Bnyro** [comment]
Yes!

**Comment by yhm4ps1jfp67nkv** [comment]
> Yes!

Got it. @FireMasterK are there currently any problems with the code so that it's not merged?

**Comment by FireMasterK** [comment]
It's already in Piped tho, even though that PR is not merged yet.

That's how we currently support 8k

**Comment by yhm4ps1jfp67nkv** [comment]
> It's already in Piped tho, even though that PR is not merged yet (It's in my fork).
> 
> That's how we currently support 8k

@Bnyro maybe you should reopen it then?

**Comment by Bnyro** [comment]
Currently out of scope for the project.
