### ISSUE TITLE
Popup upgrade.

### ISSUE THREAD

**Issue by Dertyiula** [libre-tube/LibreTube#2131]
### Describe your suggested feature

There is an option to turn off the Popup mode in the settings. If you turn on this option, you can use the button on the player for popup, and if you turn it off, you can play the video in an external player.Also, when you close this option, the popup should be closed.

### Other details

No

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't want to add the `Open with` button back. Our own player is good and stable enough to be used, third party players are not recommended anymore since most of the logic is happening inside the app now and external players lack compatibility in some cases.

**Comment by Dertyiula** [comment]
Remove the popup option from settings.Because, if you disable the option, it is possible to play in popup mode from the player with a button.
