### ISSUE TITLE
Hide age-restricted content.

### ISSUE THREAD

**Issue by Dertyiula** [libre-tube/LibreTube#2132]
### Describe your suggested feature

YouTube has a limited mode to hide adult content from kids.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The API doesn't return whether a video is age-restricted, hence there's no way to implement that!

**Comment by heartlog** [comment]
@Bnyro Well you can apply filter in search query
Like, if **h*t girl** searched, then results will be none or instead get filtered out..
