### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by Dertyiula** [libre-tube/LibreTube#2135]
### Describe your suggested feature

Update screenshots name and themselves. I shared it here.Also, names are misspelled in the Readme.md.

![Screenshot_20221128-214713_LibreTube Debug](https://user-images.githubusercontent.com/119277871/204351166-00765b93-c980-4340-8d0d-82bb2060d210.jpg)
![Screenshot_20221128-214657_LibreTube Debug](https://user-images.githubusercontent.com/119277871/204351178-b0aee0e1-85ec-4e93-900a-6af33c18d157.jpg)
![Screenshot_20221128-214636_LibreTube Debug](https://user-images.githubusercontent.com/119277871/204351192-d7bbf97a-ec9c-4651-8d2f-ad2c54961bc5.jpg)
![Screenshot_20221128-214629_LibreTube Debug](https://user-images.githubusercontent.com/119277871/204351197-d484d04b-da2e-4c79-bcc9-b689636e48f6.jpg)
![Screenshot_20221128-214620_LibreTube Debug](https://user-images.githubusercontent.com/119277871/204351205-51a4e5bc-5c1d-4e6d-ae6f-65d87acd3a35.jpg)
![Screenshot_20221128-214610_LibreTube Debug](https://user-images.githubusercontent.com/119277871/204351223-069ce097-302d-4713-8d4a-4d256eb88ee7.jpg)

### Other details

I could not change.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You can change them by making a PR containing the changed screenshots. However, I'd prefer using different dark and light themes for the screenshots.
