### ISSUE TITLE
Tricky like button.

### ISSUE THREAD

**Issue by Dertyiula** [libre-tube/LibreTube#2136]
### Describe your suggested feature

It would be nice if you could add a fake like button. A private button that has nothing to do with YouTube.Because I'm sick of liking my favorite video😁

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Dertyiula** [comment]
Clicking the like button makes it even more awesome.

**Comment by Bnyro** [comment]
I doubt that makes sense. If you want to save videos for watching them later, create a playlist, I don't get why there should be a fake like button.
