### ISSUE TITLE
A compact mode option and/or options to resize video thumbnails and text with a custom percent size. 

### ISSUE THREAD

**Issue by C0nfusion1** [libre-tube/LibreTube#2137]
### Describe your suggested feature

NewPipe has a compact UI for everything and NewPipe is what I have been using for a few years. I have gotten pretty comfortable with compact UIs that it's what I will use in all my installed apps should the option be provided. I love being able to see more information, especially on bigger devices, without having to change DPI density/screen zoom.

Here is an example of NewPipe's compact UI.

### Other details

![Screenshot_20221128_074213_NewPipe SponsorBlock](https://user-images.githubusercontent.com/108069137/204320370-b948e45f-c368-4334-9a56-70693dcd5131.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
No plans for such a minimalistic layout at the moment as there are already two different layouts users can choose from. Apart from that such a layout would suck in terms of accessibility and doesn't go well with the design principles of the app and Material Design 3.
