### ISSUE TITLE
Add an option to show exact view count

### ISSUE THREAD

**Issue by yhm3ps1jfp76nkd** [libre-tube/LibreTube#2138]
### Describe your suggested feature

An option that makes the view count change from e.g. 1M views to 1,234,567 views

### Other details

Probably should be enabled by default or even be the only way of showing the data. Exact view count is already present in Piped

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Dertyiula** [comment]
The total number of views can be shown in the description section.
