### ISSUE TITLE
Provide option to skip to previous/next video in notifications

### ISSUE THREAD

**Issue by VarLad** [libre-tube/LibreTube#2139]
### Describe your suggested feature

While listening to a music from a playlist, I want to jump to the next song in the playlist
There are two buttons for seeking from notifications. It'd be nice to have buttons jump to previous/next video as well.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
closing in favor of #2624
