### ISSUE TITLE
Improve the auto-rotation option.

### ISSUE THREAD

**Issue by Dertyiula** [libre-tube/LibreTube#2142]
### Describe your suggested feature

You don't need the auto-rotate option in the settings.Because this option should be adjusted according to android settings.In NewPipe and YouTube, you enable this option from the android settings and the video and the app rotate automatically.Or, you can use the auto-rotate button on the player.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Dertyiula** [comment]
#1576 / #1938

**Comment by akano12** [comment]
If you don't like auto full-screen in LT then don't enable it 🙄😕

**Comment by xIUPITERx** [comment]
As I am not a programmer, I don't really understand why the whole thing is so difficult to implement.
You "only" have to consider the changes from horizontal to vertical. If it changes from portrait mode (vertical) to landscape mode (horizontal) and at the same time the full screen mode is not activated, the full screen mode should be activated and vice versa: ((landscape -> portrait) & (full screen mode = on)) -> full screen mode off.

**Comment by Dertyiula** [comment]
I can solve the issues, but I don't have time!

**Comment by xIUPITERx** [comment]
Since I don't want supscription feed and the settings to rotate, it should only happen when a video is running in the foreground (not in the miniplayer).

**Comment by Dertyiula** [comment]
This can only be adjusted according to android settings.

**Comment by Bnyro** [comment]
I disagree, the app is meant to be used in portrait and optimized for it, hence enabling auto rotation is the user's risk.
