### ISSUE TITLE
Unexpected redirection after visiting someone profile through comment section 

### ISSUE THREAD

**Issue by Tillo7** [libre-tube/LibreTube#2145]
### Steps to reproduce

1. Open Libretube and play and video.
2. Go to comment section of that video and click on any user profile of any comment.
3. Press the back button.
![Screenshot_20221129-184907_LibreTube](https://user-images.githubusercontent.com/113629954/204540618-d7866afe-b7a0-4986-9b23-48618c8ddaed.jpg)
![Screenshot_20221129-184913_LibreTube](https://user-images.githubusercontent.com/113629954/204540697-4f6ff964-f859-4ff3-86ef-4f378cae59eb.jpg)
![Screenshot_20221129-184927_LibreTube](https://user-images.githubusercontent.com/113629954/204540723-b68a55a9-33b7-47cc-a601-79b01991e76c.jpg)

### Expected behavior

After clicking the back button, I should be redirected to the comment section and on the same comment where I was before clicking on the user's profile (i.e. not at the very start of comment section, but where I left).

### Actual behavior

After clicking the back button, I get redirected to the subscription page if that's my first profile visit or to the previous profile if I've visited multiple profiles.

### LibreTube version

0.8.0

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not a bug, the concept behind it is the following:
When clicking the channel icon you decide to put the video into the background (giving it a lower priority), for example to browse different channels or playlists. Returning to the video by pressing the back button would somehow hinder that "workflow". Apart from that you can return to the previous state (reading the comments) by just clicking the miniplayer, hence it's not an UX issue.

**Comment by Tillo7** [comment]
Oh, didn't knew it was intentional. Thanks for the info.
