### ISSUE TITLE
Video progress not updated when watching in audio-only/picture-in-picture (PIP) mode

### ISSUE THREAD

**Issue by MatsG23** [libre-tube/LibreTube#2147]
### Steps to reproduce

1. Start a video
2. Open the video in PIP or audio-only mode
3. Close the PIP player or stop the audio and app

### Expected behavior

The video progress in the subscription list should be at the end (if you ended the PIP/audio-only player at the end).

### Actual behavior

If you open the app again, the video progress in the history (subscriptions) is stuck at the point where you started PIP/audio-only mode.
I know that it works if you come in the app again and e.g. start the regular video player again.

### LibreTube version

0.8.0

### Android version

Android 13

### Other details

Running GrapheneOS.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You'll probably just need to reload the subscriptions tab or whatever you started the video from in order for it to update? Making the process auto-refresh in the background all the time wouldn't be a good choice in terms of performance of the app.
