### ISSUE TITLE
Allow moving video progress forward/backward in a video in PIP mode

### ISSUE THREAD

**Issue by MatsG23** [libre-tube/LibreTube#2149]
### Describe your suggested feature

You currently cannot move the video progress if you are watching from PIP mode.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I doubt that would be possible, even if it was I wouldn't see a reason to add it to the PiP window because other controls would be way more important then.
