### ISSUE TITLE
Allow to skip sponsered segment manually in PIP mode

### ISSUE THREAD

**Issue by MatsG23** [libre-tube/LibreTube#2150]
### Describe your suggested feature

It would be nice if you could skip a sponsered segment manually in PIP mode.

### Other details

I think this is important because you do not always want to skip any sponsored segments automatically.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I think we should rather use the place for more important controls at the PiP window than for SponsorBlock (we already have enough open issues for that though)
