### ISSUE TITLE
Option to share the channel

### ISSUE THREAD

**Issue by Dertyiula** [libre-tube/LibreTube#2152]
### Describe your suggested feature

![Screenshot_20221130-124752_LibreTube Debug](https://user-images.githubusercontent.com/119277871/204750429-9f268bdb-0b87-4ca2-9e5f-dab881094fb6.jpg)
Option to share the channel without entering the channel. It can also be applied to the home page. It is possible with the option to press and hold

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The channel sheet would only have one option then, in order for it to make sense we would probably need to add more functionality to it as for example playing the latest videos from the channel or turning notifications from it on/off. However, I think this might be quite a good idea.

**Comment by xIUPITERx** [comment]
I can't get it to work in the latest debug version.
