### ISSUE TITLE
Speed settings improvements!

### ISSUE THREAD

**Issue by Dertyiula** [libre-tube/LibreTube#2153]
### Describe your suggested feature

![Screenshot_20221130-182005_NewPipe SponsorBlock](https://user-images.githubusercontent.com/119277871/204820228-ba7654bc-d50e-47cd-9ab4-5e9fca452201.jpg)
Some improvements in sound settings!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's way too complex, apart from that it doesn't fit with the Material guidelines.
