### ISSUE TITLE
Unable to view replies to comments.

### ISSUE THREAD

**Issue by Dertyiula** [libre-tube/LibreTube#2158]
### Steps to reproduce

1.https://piped.video/watch?v=RTvDRh8IvPE&t=0 (watch this video)
2.Unable to view replies to some comments.

### Expected behavior

Replies to comments should be displayed smoothly.

### Actual behavior

https://user-images.githubusercontent.com/119277871/204991560-e53bf041-f083-4f7a-ab70-fe89731054e2.mp4

### LibreTube version

0.8.0 Debug

### Android version

Android 12

### Other details

No

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Works fine for most comments and the behavior is the same in the release version 0.8.0, so I assume that the reply count is just returned wrong sometimes by the NewPipe Extractor, e.g. when comment replies got deleted.

**Comment by Dertyiula** [comment]
Yes, I looked at those comments on YouTube, the replies have been deleted.
