### ISSUE TITLE
Sharing video to libretube should queue if video is playing, or ask

### ISSUE THREAD

**Issue by rancidfrog** [libre-tube/LibreTube#2164]
### Describe your suggested feature

Share video to Libretube should either queue the video if there is audio/video playing
Or, a dialog/pop-up should be displayed asking user if they would like to queue or play shared video

Other details

### Acknowledgements
- [x]  I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.
- [x]  I have written a short but informative title.
- [x]  I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The issue sounded more friendly if you replaced `should` with `could`.
I don't think the app `should` do anything, anyways the issue template wasn't filled completely and even got modified by you.
