### ISSUE TITLE
Quality format selection

### ISSUE THREAD

**Issue by asklow** [libre-tube/LibreTube#2166]
### Describe your suggested feature

Like on Piped website allow playback format selections
Auto / AVC / VP9 / AV1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
May I ask what having the option for it would change? It automatically picks the best one for you in fact so why would you need the choice?
