### ISSUE TITLE
Download percentage

### ISSUE THREAD

**Issue by asklow** [libre-tube/LibreTube#2167]
### Describe your suggested feature

Stream sizes are fixed & static. So having a notification for download percentage based on how much is downloaded wouldn't be difficult I guess.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We're using the Android inbuilt download manager, the behavior of it can't really be controlled. For me, the percentage is already shown as a progress bar but it might depend on the ROM. Anything else would require us to write a custom download manager for the app which is quite challenging and wouldn't be really worth the trouble as it would probably be less reliable!
