### ISSUE TITLE
Improvements in landscape mode

### ISSUE THREAD

**Issue by Dertyiula** [libre-tube/LibreTube#2169]
### Describe your suggested feature

Improvements in landscape mode:
1.Button to view comments
2.Share button
3.Add to playlist button
4.Download button.
5.See description section

### Other details

https://user-images.githubusercontent.com/119277871/205226186-ace854e2-d325-46d2-b56b-43bf3f8ce18a.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
All those actions should be done inside the portrait mode, I don't see any reason for introducing a new, different layout for the landscape mode to add some functionality to it that already exists. Apart from that I don't get why you would want to view the description or the comments from the fullscreen mode because you usually want to watch the video when going to fullscreen and not get sidetracked with any other info...

**Comment by sxe** [comment]
I came here to request something similar as well, so I am making a comment here to hopefully get some clarification and maybe later make a proper feature request.

Right now there is no proper landscape mode of the "player view" in the app. The only way to achieve a somewhat working solution is to enable "auto rotate" and "auto fullscreen". In this mode you have no way to see comments, suggestions or any other information you have in the normal "player page". This is crucial when you use the app on a tablet. You never should have to rotate your tablet into portrait mode, so personally I consider this a bug/missing feature. 

This is also a pretty common feature in other youtube apps. The official app and website and newpipe both allow the player page to be visible in landscape mode.

Here is a screenshot of newpipe to make is absolutely clear what I am talking about: https://raw.githubusercontent.com/TeamNewPipe/NewPipe/dev/fastlane/metadata/android/en-US/images/tenInchScreenshots/shot_12.png

Would love to get your thoughts on this. 

Cheers and thanks for the great work you guys do with libretube!

**Comment by Bnyro** [comment]
> Right now there is no proper landscape mode of the "player view" in the app. The only way to achieve a somewhat working solution is to enable "auto rotate" and "auto fullscreen". In this mode you have no way to see comments, suggestions or any other information you have in the normal "player page". This is crucial when you use the app on a tablet. You never should have to rotate your tablet into portrait mode, so personally I consider this a bug/missing feature.
> 
From a development perspective the reason why I personally didn't add it yet is that it would require use to create a new layout for the whole player view for the landscape mode only, which would in the end cause us to have two different layouts that new features or general changes need to get added to individually each time. Another possibility would be to modify the portrait layout on rotation change but that could quickly become really messy. No clue which approach NewPipe uses, probably the first one.
The second potential issue with it would be the miniplayer which would probably behave really weird in the landscape mode then (but that could be worked around somehow probably).
So to end up it might be possible and there's no reason for you to not open a new issue for it, however it won't be a priority for me (but potentially someone else might be interested in working on it) as I don't own a large screen device that would benefit from it. Apart from that one should always keep in mind that the main target of the app are still Android phones.
Have a good one!

**Comment by sxe** [comment]
Thanks for the honest feedback.
At least now we know what the official stance one the issue is. 

Have a good on as well!
