### ISSUE TITLE
No Videos plays during a phone call

### ISSUE THREAD

**Issue by MithNo1** [libre-tube/LibreTube#2182]
### Steps to reproduce

Like I'm on a normal or VOIP phone call basically. And whenever I try to play Any video on LibreTube it doesn't work. I don't understand why is this happening its has become a big issue to me. This doesn't happen in NewPipe Please look into this.

### Expected behavior

Videos should play during phone calls normally

### Actual behavior

Videos should play during phone calls 

### LibreTube version

0.8.0

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Well, I don't think videos should continue playing normally during phone calls since you don't want to get distracted while being in a phone call?
