### ISSUE TITLE
Notification bar is not visible in light theme.

### ISSUE THREAD

**Issue by teja3go** [libre-tube/LibreTube#2183]
### Steps to reproduce

After playing a video go to full screen mode then come back to normal player now all icons from notification bar will be vanished. Android 8.1 (device - moto g5s plus) in light theme.

### Expected behavior

Notification bar should be visible

### Actual behavior

Complete white and all icons are not visible in light theme

### LibreTube version

0.8.0

### Android version

8.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Any screenshots?

**Comment by teja3go** [comment]
Of course here are some in the same order of reproducing the bug.
I thing this is due to MaterialU and Android 8.1 doesn't support that.
![Screenshot_20221204-171418](https://user-images.githubusercontent.com/119127486/205488666-3c3825a2-3cb5-4721-8a47-01b7ef8a0b07.png)
![Screenshot_20221204-171425](https://user-images.githubusercontent.com/119127486/205488690-d075b003-b424-40be-9b71-f1643a95d1be.png)
![Screenshot_20221204-171443](https://user-images.githubusercontent.com/119127486/205488700-3d22e86a-4c40-4f35-9a22-fc4f01d6af81.png)
![Screenshot_20221204-171451](https://user-images.githubusercontent.com/119127486/205488709-bf778445-2bcd-4021-a668-45e199ffc0c2.png)
![Screenshot_20221204-171458](https://user-images.githubusercontent.com/119127486/205488719-854bc817-380e-4404-85a4-83f5f8fda7a5.png)
![Screenshot_20221204-171526](https://user-images.githubusercontent.com/119127486/205488740-389e0abb-7805-4519-9172-2c2881d59451.png)

**Comment by teja3go** [comment]
After that icons won't come back until i close the app and remove it from recent apps and again lanching it.

**Comment by teja3go** [comment]
I was thinking about that.
But I don't have done it before, so I think I and ok with that bug.

**Comment by Bnyro** [comment]
Still can't reproduce and no clue what the issue could be but it's probably device related.
