### ISSUE TITLE
Skip track/video previous/ next by Bluetooth 

### ISSUE THREAD

**Issue by Tetzuya75** [libre-tube/LibreTube#2185]
### Describe your suggested feature

Hi,
This app is fantastic, but I found that is not possible to to skip to next/previous track/video when I play a playlist using Bluetooth command (ex when it was used in a car).
Other bug I found:
While I played a playlist, the app stop play after ending a song/video, and not continue 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Unfortunately we have to wait for https://github.com/androidx/media/issues/12 :/
