### ISSUE TITLE
Volume Booster in the player

### ISSUE THREAD

**Issue by GET100PERCENT** [libre-tube/LibreTube#2186]
### Describe your suggested feature

Some of the YouTube videos have a very low intensity sound. So it will be very useful if libretube supports volume Booster just like VLC, in which volume can be boosted upto 200%.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Why I don't think it should be added to the app:
1. I doubt it would be used a lot as the uses cases are only very few
2. It decreases the quality of the audio, hence it wouldn't be too useful anyways
3. There's currently really no space for new controls anywhere at the player.
I'd recommend using a 3rd party app instead which should work fine too.

**Comment by GET100PERCENT** [comment]
1. It decreases the quality of the audio, but not enough to be not understandable.
2. VLC has not any dedicated icon or indicator for volume Booster in the player interface.
![Screenshot_20221206-141927](https://user-images.githubusercontent.com/116144024/205864149-9630e1a9-53c7-4f20-bc6d-62c379d525a8.jpg)
It uses the same volume indicator instead of a dedicated one.

**Comment by GET100PERCENT** [comment]
Okay 👍

**Comment by ildar** [comment]
+1 to the topic starter
> 1. I doubt it would be used a lot as the uses cases are only very few

Unfortunatelly no. YouTube videos diverge a lot. The most troublesome in the wild are videos of old live conferences recorded with awful crappy sound. :-(

> 2. It decreases the quality of the audio, hence it wouldn't be too useful anyways

Nope if you turn it on for volumes >100%
> 3. There's currently really no space for new controls anywhere at the player.

No need for that. Please take a look how it's done in VLC. It's a masterpiece.
> I'd recommend using a 3rd party app instead which should work fine too.

Mostly very uncomfortable. Using 2 apps in the situation is a bad user experience.
Please re-triage.
And yes, thanks a lot for the app. It is really close to perfect and best in its class.
