### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by AR-Home** [libre-tube/LibreTube#2188]
### Steps to reproduce

The navigation bar, in the first tap, pops in the video.
Then, the gesture controls and forward and backward gestures and seeking works, on the second taps.🥲

### Expected behavior

It should not pop out the navigation bar in the first time, so that the video moves like that of YouTube.😊

### Actual behavior

The navigation bar should stay out.

### LibreTube version

0.9.0 - latest

### Android version

Android 11

### Other details

I have video proof.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Archeix7** [comment]
I confirm, https://github.com/libre-tube/LibreTube/issues/1947 not fixed

**Comment by Bnyro** [comment]
#2541
