### ISSUE TITLE
Material You system color scheme theme

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [libre-tube/LibreTube#2189]
### Describe your suggested feature

Loving the app, the only visual enhancement that the app could really use is automatically setting the app theme to the system color scheme based on the device wallpaper that was introduced in Android 12. I'm sure you're aware of it, it's called Material You and I think it would be a welcome addition to the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's already possible, just select Material You as accent in the appearance settings :)

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
> That's already possible, just select Material You as accent in the appearance settings :)

I don't seem to be able to see this option. Is this feature in 0.8.0?

**Comment by Bnyro** [comment]
Yes, it should in theory!

![Screenshot_20221202-221418_LibreTube.png](https://user-images.githubusercontent.com/82752168/205387179-b74b2fb4-8057-49a9-b1cd-671356877c10.png)

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
> That's already possible, just select Material You as accent in the appearance settings :)

I don't seem to be able to see this option. Is it in 0.8.0?

> Yes, it should in theory!
> 
> ![Screenshot_20221202-221418_LibreTube.png](https://user-images.githubusercontent.com/82752168/205387179-b74b2fb4-8057-49a9-b1cd-671356877c10.png)

That's strange, it's not showing up in the Accents menu on my installation. I'm on Android 12. The option just isn't there.

**Comment by Bnyro** [comment]
Hmm, that's weird. The app checks whether dynamic colors are available using the official Android API for it and hides the option if it's not available for the phone. Would you mind providing some details about your device?

**Comment by Bnyro** [comment]
Hmm, that's weird. The app checks whether dynamic colors are available using the official Android API for it and hides the option if it's not available for the phone. Would you mind providing some details about your device? And are you aware of other apps Material You works with?

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
> Hmm, that's weird. The app checks whether dynamic colors are available using the official Android API for it and hides the option if it's not available for the phone. Would you mind providing some details about your device? And are you aware of other apps Material You works with?

Sure, I'm using a Samsung Note 9 with iodéOS 3.3 / Android 12, and as far as I can tell all of my other apps that support Material You use the scheme correctly. "Wall You" wallpaper picker is one of my favorite implementations of it and it is working on that app.

**Comment by Bnyro** [comment]
Could you please also share the info when going to LibreTube -> About -> Device Info?
We might be able to just make the option Android version dependent instead of relying on the API.

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
Here it is:
![eq3666k00lnm7qp6](https://user-images.githubusercontent.com/76442625/205396875-0bfd7f16-d749-4250-992c-1d9bb2e4cd3d.jpg)

**Comment by Bnyro** [comment]
Okay, then we'll just check whether the SDK is greater or equal than 32 in the future ;)

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
Just installed the latest update and see that the Material You option is showing up on my device, but after selecting it the theme is purple when my system theme is orange based on my red wallpaper.

**Comment by Bnyro** [comment]
Well, then your device doesn't support it properly!

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
As I said before all my other apps that use Material You work correctly, I don't think my device is the issue.
