### ISSUE TITLE
Appbar search, menu design.

### ISSUE THREAD

**Issue by rakibdev** [libre-tube/LibreTube#219]
### Describe your suggested feature
Remove the LibreTube logo at top to save space. 
![home](https://i.ibb.co/xmcYrWV/Group-1.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

**Comment by lilcheti** [comment]
We should add the option to use this in the settings then would u like to create a pr

**Comment by rakibdev** [comment]
@lilcheti Ah yes this just only image designed in Figma copied from Material 3 design kit. Haven't implemented myself by coding as I'm not an Android dev.

**Comment by Bnyro** [comment]
Good that you didn't add it so far, it would probably be a huge merge conflict with the search filter :)

**Comment by Bnyro** [comment]
I don't think a searchbar on the top would fit the app design tbh. It might work for other apps but I feel like it looks way better with the logo on top.

**Comment by rakibdev** [comment]
> I feel like it looks way better with the logo on top.

Looks way better is subjective. Putting logo in appbar area is trademark of bad design. No popular app does this. That represents those ugly government, educational websites showing huge red banner, no space left for buttons.

There must be reason behind everything. Nobody going to click or stare at logo, no need for reminding user how logo looks like. User use touch device, needs larger tap target for the search and now it's just a small icon.

In appbar options (settings, filters) are displayed as icons, eventually adding few more icons will turn to mess. Dropdown menu was invented for this. UI elements here not utilized properly.

**Comment by Bnyro** [comment]
I agree that you might have a different opinion, but it would probably require some hours to rewrite it since the search fragment would have to be moved into the topbar. I just don't want to spend time with things I don't even really agree with.
If you really want to see it changed you'll have to try it on your own (if you had any knowlede about android development) or wait for somebody who is convinced by it and is okay with investing his/her time to make it work as you want it. 
In my opinion we currently should have other focuses to improve the app.
Greetings

**Comment by Bnyro** [comment]
we decided to stay with the current look of the topnav

**Comment by Nephys222** [comment]
@Bnyro In Search suggestions, when there is no history of search, clearing textfield does not clear suggestions list (after writing some text). Seems inconvenient.

**Comment by Bnyro** [comment]
@Nephys222 Oh, right, fixed now :p

**Comment by Nephys222** [comment]
@Bnyro Yes it is. Would that be possible to fix also that after writing sth then when cleared via backspace the suggestions stay.

**Comment by Nephys222** [comment]
@Bnyro One last thing. When clearing textfield with holding backspace instead of pressing repeatedly, the suggestions appear at the end.

**Comment by Nephys222** [comment]
@Bnyro Did you notice?

**Comment by Bnyro** [comment]
@Nephys222 now, yes, fixed

**Comment by Nephys222** [comment]
@Bnyro Yes it is. Just curios. Is this app written with MVC architecture. What about using ViewModels or MVVM architecture?

**Comment by Nephys222** [comment]
@Bnyro Also when filtered to 'video' in search this(below) apears
![image](https://user-images.githubusercontent.com/59939839/181753136-01187a43-d207-4764-8a73-f3dc267265c3.png)

**Comment by Bnyro** [comment]
> @Bnyro Yes it is. Just curios. Is this app written with MVC architecture. What about using ViewModels or MVVM architecture?

1. Using viewmodels etc is rather something that's done with Jetpack Compose which I don't have much experience with yet.
2. The project is meant to be open for contributions of anyone who wants to: Most people are more familiar with MVC than MVVM and it's easier for people that want to start with Android development.

**Comment by Bnyro** [comment]
> @Bnyro Also when filtered to 'video' in search without writing anything, this(below) appears:
> 
> ![Screenshot_20220729_190332](https://user-images.githubusercontent.com/59939839/181777220-7e3dd526-8375-4b36-b9ec-acb477fcdad4.png)

That's a Piped API thing or something, I don't know. It's obviously possible to fetch search results with an empty query. I don't think we have to disable this behavior, it's quite funny :p
