### ISSUE TITLE
Fix download progress

### ISSUE THREAD

**Issue by popogomo** [libre-tube/LibreTube#2193]
### Describe your suggested feature

Apologies for so many requests today.

I believe the download manager is kinda broken - it loops indefinitely when downloading a video or audio, without showing any progress. It then disappears suddenly and reappears whenever it wants to. Videos and audios do not download properly as a result.

Is it possible to fix it please? Also, maybe it will be possible to download videos and audios in their original extension so that we could open them in 3rd party apps? Also, if we could choose where to download these, e.g. in Downloads folder not in LibreTube folder.

Hope this makes sense. Thanks!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by GET100PERCENT** [comment]
> ### Describe your suggested feature
> Apologies for so many requests today.
> 
> I believe the download manager is kinda broken - it loops indefinitely when downloading a video or audio, without showing any progress. It then disappears suddenly and reappears whenever it wants to. Videos and audios do not download properly as a result.
> 
> Is it possible to fix it please? Also, maybe it will be possible to download videos and audios in their original extension so that we could open them in 3rd party apps? Also, if we could choose where to download these, e.g. in Downloads folder not in LibreTube folder.
> 
> Hope this makes sense. Thanks!
> 
> ### Other details
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I will fill out all of the requested information in this form.

I am also waiting for the newpipe style downloading to be implemented in libretube.

**Comment by Bnyro** [comment]
For fixing that we would need to create our own download manager. The current inconsistency is an issue of the Android inbuilt download manager we don't have an influence on.
