### ISSUE TITLE
Notification disappeares

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#2194]
### Steps to reproduce

1. Play a video
2. Minimize the app
3. PiP will appear
4. Close PiP (video is still playing)
5. Video stops playing and the LibreTube Media-control Notification disappears 

### Expected behavior

Video should still be playing in the background independent from the PiP
The notification shouldn't disappear

### Actual behavior

Video stops playing and the LibreTube Media-control Notification disappears 

### LibreTube version

0.9.0

### Android version

Android 13 One UI 5.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Yes, works as intended!
