### ISSUE TITLE
Kids Mode - Toggle To Disable Elements

### ISSUE THREAD

**Issue by tufkal** [libre-tube/LibreTube#2195]
### Describe your suggested feature

In what I believe would be a simple toggle protected by a 4 digit pin, you would bypass all the problems of the official/horrible  'YouTube Kids' app, and give parents like myself a way to share videos with their kids safely.  

-Acts like a whitelist, I can subscribe to only channels I deem appropriate and playlist only videos as well
-Simply turn off most of the app when in kids mode, no settings menu, no comments, etc.
-No ads for me to worry about them seeing inappropriate content or tempt them with apps/toys/etc

There are already lots of ways to lockdown launchers and devices themselves, you only have to do it in the app.  All the hard work is already done with what you've done so far, like I said you just need to add a toggle with a passcode and when that is active turn some elements off.

Hope this idea finds you well, and thank you for all your hard work!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Hello, thanks for the suggestion.
However
1. There are a lot of ways to navigate to another page (e.g. from a video to a channel and from there to related channels, etc), so it would be quite some work to implement
2. I doubt there would be a lot of users using the app for their kids so it would really be a niche feature
3. I don't like the idea of adding different ways to treat users (kids, normal users) to the app, I'm not a fan of promoting restrictions inside the app
For the given reasons no plans for adding it.
