### ISSUE TITLE
Outdated F-Droid repo, update app from 0.2.6 to 0.2.7

### ISSUE THREAD

**Issue by krypciak** [libre-tube/LibreTube#220]
### Describe your suggested feature

The current F-Droid apllication version is 0.2.6, but 0.2.7 can be downloaded through github release page.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We're aware of that but F-Droid Devs have to update the app there, we can't.
