### ISSUE TITLE
Add smooth transition while zooming

### ISSUE THREAD

**Issue by vedxp** [libre-tube/LibreTube#2200]
### Describe your suggested feature

Currently when you pinch to zoom in/out, there is no transition. The video just changes its state of zoom instantly.

Rather, it would be really better if zooming in/out take place with a nice transition between both the zoom states.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It doesn't seem to be possible unfortunately as the `ExoPlayer` doesn't support states between fit, fill and zoom.
Apart from that I do agree with asklow concerning the usage of animations in the app.
