### ISSUE TITLE
Option to hide Sponsorblock button from the player

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#2201]
### Describe your suggested feature

![Screenshot_20221203-084630~2](https://user-images.githubusercontent.com/87353286/205419852-964140e4-a700-4f93-8287-981991147422.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thanks for using the issue template by providing reasons why you would want to hide it ...

**Comment by VedxP** [comment]
> Thanks for using the issue template by providing reasons why you would want to hide it ...

Oops, updated :)

**Comment by Bnyro** [comment]
I think we should continue with #2206 :)
