### ISSUE TITLE
Remove `Resize Mode` option in favour of pinch to zoom gesture

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#2202]
### Describe your suggested feature

![Screenshot_20221203-084840~2](https://user-images.githubusercontent.com/87353286/205419927-f99a9cb5-7a9a-4ff2-819b-71c0d1293830.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It can be disabled so some users might still use it I guess.
