### ISSUE TITLE
Move the delete icon right to the playlisted videos to a long tap action

### ISSUE THREAD

**Issue by GET100PERCENT** [libre-tube/LibreTube#2203]
### Describe your suggested feature

Move the delete icon right to the playlisted videos to a long tap action.
It is essential for preventing accidental deletion of playlisted videos.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The button is small enough to not accidentally hit it, I doubt this would make sense.

**Comment by GET100PERCENT** [comment]
Okay, then add an undo button for 5 seconds before deleting a video from local playlists.

**Comment by Bnyro** [comment]
Wouldn't that be distracting when deleting multiple at once?

**Comment by GET100PERCENT** [comment]
No, it won't distract, because it's position is just above the bottom edge.

**Comment by GET100PERCENT** [comment]
And if one doesn't want to undo a deletion , he needn't interact with the bottom dialog.

**Comment by GET100PERCENT** [comment]
https://user-images.githubusercontent.com/116144024/205430942-d7a299d3-8658-4d8b-8922-0e587381bf4d.mp4

**Comment by GET100PERCENT** [comment]
The above video is from newpipe.
I want a similar undo option in the case of playlisted videos.

**Comment by GET100PERCENT** [comment]
Swiping left or right to delete the playlisted videos can be done alternative to it, as swiping is not bothering at all, similar to email applications in which swiping left deletes the email.

Swiping is not a complex task rather it is pleasent.

And many applications use it to reduce crowd in the main interface.

**Comment by Bnyro** [comment]
Swiping is already possible for them?!

**Comment by GET100PERCENT** [comment]
Okay, then the undo option is the best.

**Comment by GET100PERCENT** [comment]
Other Solutions:
1. A recyclebin
2. Irrespective of delete icons right to all playlisted videos, marking can be implemented ie;
Press and hold any playlisted video to activate marking, then select (mark) the videos to delete and then on a single click on the delete button all marked videos will be deleted.

**Comment by GET100PERCENT** [comment]
Marking is the easiest way to perform such operations, that's why even file explorers use this for delete items.

It can also be possible in future for other file operations such as moving a video from one playlist to the other.

**Comment by ARBoyGo** [comment]
Brother, I don't understand why you need to get rid of delete icon, Are you dancing with your phone? To accidentally deleted playlist? 🤦

**Comment by GET100PERCENT** [comment]
No, but in small screen devices, the accidental deletion is quite possible.

**Comment by GET100PERCENT** [comment]
Also people add only those videos to playlist which they want to be added. That means they are somehow important to  them, that's why they make collection of those videos in a playlist.


When you want to make a collection of videos in a playlist, normally don't  want to delete them. In that case a lot of delete icons are not looked pleasent.

**Comment by Bnyro** [comment]
To be honest that doesn't make sense to me, I doubt it's worth changing something here ...
