### ISSUE TITLE
Merge the video and audio file after downloading 

### ISSUE THREAD

**Issue by GET100PERCENT** [libre-tube/LibreTube#2204]
### Describe your suggested feature

The current downloads in libretube can be played only in libretube.

If the video and audio file can be merged after downloading them it can be played in any media player, which would be a good function.

Also if the feature is implemented the downloaded videos can be sent to others' mobiles. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by yhm3ps1jfp76nkd** [comment]
#2151?

**Comment by GET100PERCENT** [comment]
Yes, but only merging

**Comment by GET100PERCENT** [comment]
How did newpipe implement it even in the smaller sized apk?

**Comment by GET100PERCENT** [comment]
Ffmpeg is not required i think

**Comment by GET100PERCENT** [comment]
When MP3 downloading is requested for newpipe, they said it wouldn't be implemented because it needs ffmpeg library.

That means without ffmpeg library, there is some other way which newpipe uses.

Can't it be implemented in libretube?

**Comment by Bnyro** [comment]
They wrote a MP4 Muxer from scratch,
1. It lacks compatibility with video and audio formats
2. We won't copy their magic code
3. Again, there are no plans for it as downloads are meant to be watched **inside** the app!

**Comment by GET100PERCENT** [comment]
But if the downloaded videos can be shared to others' mobiles it will be very useful.
