### ISSUE TITLE
Grid view for the owned playlists

### ISSUE THREAD

**Issue by GET100PERCENT** [libre-tube/LibreTube#2205]
### Describe your suggested feature

![Screenshot_20221203-111935](https://user-images.githubusercontent.com/116144024/205426592-a1e5be00-3aa1-4b76-8d35-f8616c9dfffc.jpg)

If the local playlists can be arranged in two columns, it will look very nice.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
No plans for that due to the redesign of the library tab which reduced the available space for it.
