### ISSUE TITLE
Donation links at IzzyOnDroid

### ISSUE THREAD

**Issue by Bnyro** [libre-tube/LibreTube#2208]
### Describe your suggested feature

Hey @IzzySoft,
the donation links at your repo are by the previous maintainer (who maintained it until this year's April). As they didn't touch the project for a while, I would be thankful if you could remove the donation website link as well as Bitcoin from the donation metadata of the app.
Cheers :)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by yhm3ps1jfp76nkd** [comment]
Not directly related but the link at the F-Droid LibreTube page to buy you a coffee leads nowhere

**Comment by Bnyro** [comment]
> Not directly related but the link at the F-Droid LibreTube page to buy you a coffee leads nowhere 
>
You mean the one from IzzyOnDroid? I thoguht I already removed all those links from F-Droid (should be updated with their next sync), but they didn't even include the donation link I think, only BTC.

**Comment by yhm3ps1jfp76nkd** [comment]
> > Not directly related but the link at the F-Droid LibreTube page to buy you a coffee leads nowhere
> 
> You mean the one from IzzyOnDroid? I thoguht I already removed all those links from F-Droid (should be updated with their next sync), but they didn't even include the donation link I think, only BTC.

No, on the normal F-Droid page (latest F-Droid build and synced the repos just now). I probably should wait for the update to see your changes

**Comment by Bnyro** [comment]
Oh, I thought it was only present on the IzzyOnDroid repo but apparently it's the same at F-Droid. I'll probably need to make a new PR at their Gitlab repo to remove it 🤦

**Comment by IzzySoft** [comment]
OK, I've removed the Bitcoin address (as it's no longer referenced here). Current donation details should thus be taken from [`FUNDING.yml`](https://github.com/libre-tube/LibreTube/blob/master/.github/FUNDING.yml) only. Note that the `custom:` address listed there goes to a section of your Readme which no longer exists.

As for why the app is in both repos, [see here](https://github.com/libre-tube/LibreTube/issues/433#issuecomment-1152899320) (and look who asked for it, @Bnyro :see_no_evil:); should you have changed your mind on that, just let me know.

**Comment by Bnyro** [comment]
> OK, I've removed the Bitcoin address (as it's no longer referenced here). Current donation details should thus be taken from [`FUNDING.yml`](https://github.com/libre-tube/LibreTube/blob/master/.github/FUNDING.yml) only. Note that the `custom:` address listed there goes to a section of your Readme which no longer exists.
> 
Oh, thanks for the hint, I forgot the file even existed. I've removed the `FUNDING.yml` completely now as there are no plans to take donations from my side :)
Thanks for removing the Bitcoin address from your repo as well, now all donation links should have vanished hopefully so that nobody donates somewhere where the app development wouldn't even benefit from!
> As for why the app is in both repos, [see here](https://github.com/libre-tube/LibreTube/issues/433#issuecomment-1152899320) (and look who asked for it, @Bnyro see_no_evil); should you have changed your mind on that, just let me know.
>
Sorry, I might have been unclear with that. I wondered about that the donation url from the `FUNDING.yml` is mentioned at your repo as well as at the F-Droid repo because I recently edited the `com.github.libretube.yaml` at the F-Droid data repo and wasn't able to find it anywhere. Of course we still want to benefit from blazingly fast updates via your repo, thanks for giving us the possibility to do so <3

**Comment by IzzySoft** [comment]
> I've removed the `FUNDING.yml` completely

Oh… OK, removed it here as well then (not sure if I've set up auto-removal on disappearance, need to check that).

>  because I recently edited the `com.github.libretube.yaml` at the F-Droid data repo

That only affects F-Droid.org – and yes, both (F-Droid & my repo) pull the `FUNDING.yml` if found.

> Of course we still want to benefit from blazingly fast updates via your repo, thanks for giving us the possibility to do so <3

Gladly! Then indeed this issue here is solved now, thanks!
