### ISSUE TITLE
An option to hide navigation bar

### ISSUE THREAD

**Issue by heberjeur** [libre-tube/LibreTube#2209]
### Describe your suggested feature

When we have the new Home Page UI LT 0.8.0, we can enter to the featured videos and bookmarks from the home page, so how to hide the navigation bar ?
![Screenshot_20221203-105251_LibreTube](https://user-images.githubusercontent.com/11852634/205435340-bd1eceb1-d183-4f76-b166-c19518a21338.jpg)

I tried to do that from the appearance setting but I can't do that

![Screenshot_20221203-110439_LibreTube](https://user-images.githubusercontent.com/11852634/205435447-8f6c7902-b94e-4a13-87c6-a4402b387070.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
I personally don't user anything except for home page. So i second this, hide navigation bar when just home page is selected.
Would be great if implemented <3
