### ISSUE TITLE
Request to increase resolution 

### ISSUE THREAD

**Issue by Ramanand11** [libre-tube/LibreTube#221]
### Describe your suggested feature

Improve the resolution of thumbnail and one most important thing home feed showing only trending videos not user interested video

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We can't, its an issue of the NewPipeExtractor which is used by the Piped API

**Comment by lucamp** [comment]
Thumbnail quality on home feed are fine, but the ones under a video you are playing are pretty bad. Is this still a newpipe extractor issue?

for instance https://piped.kavin.rocks/watch?v=mM7aBjWeMnc

**Home feed**
![Screenshot_2022-06-09-19-55-42-16_1](https://user-images.githubusercontent.com/15078341/172914131-2fd4c7f2-8bf0-402e-a35a-4dbf682bf478.jpg)

**Under a playing video**
![Screenshot_2022-06-09-19-29-18-70_1](https://user-images.githubusercontent.com/15078341/172914393-2235ef40-9b31-41cd-9925-b8fc3770d35f.jpg)
