### ISSUE TITLE
Automatically lock the player

### ISSUE THREAD

**Issue by Dertyiula** [libre-tube/LibreTube#2212]
### Describe your suggested feature

Auto-lock the player while scrolling to scroll down, ignoring the buttons on the player.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/issues/2206#issuecomment-1336186749
