### ISSUE TITLE
Playlists improvements

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#2213]
### Describe your suggested feature

Some Ideas:
1. Add an ``shuffle`` option to private and public playlists next to ``play all``.
2. Add an description to ``Bookmarks`` (or rename them to ``public playlists``).
3. Change the design of bookmarks so it looks like playlists (use the bookmark icon instead of the bin icon for deletion).
4. Use the ``Create new Playlist`` button to import public playlist via their URL.
5. Show public playlist directly on the library tab.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
1. will only be possible for private playlists since we only get 20 playlist items per API call, thus it would result in a very bad UX if we had to fetch all of them first before the first, random video starts loading.
2. I don't think that's needed, self-explanatory in my opinion. If not, users can still ask in the public rooms/groups on social media.
3. Sounds like a good idea.
4. Agreed.
5. That's not planned since mixing up to different ways of where data is stored as well as how (and how long) it's being fetched is not a good idea.

**Comment by xIUPITERx** [comment]
5. what if you keep bookmarks in a separate list?
![Idee 13](https://user-images.githubusercontent.com/97352673/209689210-caba6ccb-9858-4de8-8761-ac41a49fd992.png)

**Comment by xIUPITERx** [comment]
![Screenshot_20221227_165450_LibreTube Debug.png](https://user-images.githubusercontent.com/97352673/209691217-c6141098-26b5-4618-9d4f-6f17dc6ac812.png)

Please do not take my artistic skills too badly ;)

**Comment by Bnyro** [comment]
> 3. The indicator how many videos are in the playlist are still missing
> 
Yes, I decided to not add save that to the database back then, changing that now would result in all your bookmarked playlists having to be resetted because auto-migrations won't work for that I think (or I just don't know how, but anyways).

**Comment by Bnyro** [comment]
> 5. what if you keep bookmarks in a separate list?
> 
> 
> ![Idee 13](https://user-images.githubusercontent.com/97352673/209689210-caba6ccb-9858-4de8-8761-ac41a49fd992.png)
> 
> Could you also add an icon in front of `Playlists` and indent it a bit?
>
I really like the idea, but I think we would have accessibility issues on smaller devices then.

**Comment by xIUPITERx** [comment]
> Yes, I decided to not add save that to the database back then, changing that now would result in all your bookmarked playlists having to be resetted because auto-migrations won't work for that I think (or I just don't know how, but anyways).

And if it would apply only to new bookmarks playlists?

**Comment by Bnyro** [comment]
That won't change anything unfortunately. I can try to find a way to make it work properly, but anyways generating new migrations before #2469 is merged would destroy everything, so we might have a look afterwards.

**Comment by xIUPITERx** [comment]
> I really like the idea, but I think we would have accessibility issues on smaller devices then.

I think my modified screenshot was a little bit misleading.
What I really meant was one big list divided into two sections, Playlist on top and Bookmarks beneath it. 

<details>
<summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/97352673/209871046-256149bc-3378-4e7f-9a79-8de822a501e3.png">
</details>

**Comment by Bnyro** [comment]
Oh, that makes more sense, probably more intuitive for users than the current solution I guess.

**Comment by xIUPITERx** [comment]
4. Why did you use to differnt designs for the ```add playlist``` and ```create playlist``` button?

![Screenshot_20221229_124834_LibreTube Debug.png](https://user-images.githubusercontent.com/97352673/209947350-5c80175e-ccbb-4bb4-bbcd-56a6c14b5078.png)

**Comment by xIUPITERx** [comment]
> Oh, that makes more sense, probably more intuitive for users than the current solution I guess.

The question is how to allocate the space when there is only one or no playlist/bookmark.

**Comment by Bnyro** [comment]
> 4. Why did you use to differnt designs for the ```add playlist``` and ```create playlist``` button?
> 
> ![Screenshot_20221229_124834_LibreTube Debug.png](https://user-images.githubusercontent.com/97352673/209947350-5c80175e-ccbb-4bb4-bbcd-56a6c14b5078.png)
>
We should probably use the same for both, the filled one would be the better choice since the text buttons are only for dialogs. However, then we would have to change the design of the cancel button too or removeit entirely.

**Comment by xIUPITERx** [comment]
I am really not sure what looks better.
<details>
<summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/97352673/209961371-1c594714-56b2-48bb-8f28-fcf76df022e1.png">
<img src="https://user-images.githubusercontent.com/97352673/209961410-acdb4dd2-ffda-4581-b661-d9890510a43c.png">
</details>

Maybe have an combined button (1) or combined text field (2).
Then it can be decided dynamically:
(1) depending on whether one of the two fields is empty, it becomes a playlist/copy 
(2) or if a link is inserted into a combined field, the playlist is copied.

**Comment by xIUPITERx** [comment]
> will only be possible for private playlists since we only get 20 playlist items per API call, 

What about a fake shuffle fumktion, where not all videos are shuffled, but only the first 20+ and when they are finished, the next ones are shuffled.
So it works with the normal api and you have a partially random order.

**Comment by Bnyro** [comment]
> What about a fake shuffle function, where not all videos are shuffled, but only the first 20+ and when they are finished, the next ones are shuffled. So it works with the normal api and you have a partially random order.
> 
I don't really like the idea as it would imply users that the playlist is really shuffled although that's not the case, users will see the first 20 videos way more often than all the others. If that's how my playlists worked, I'd go crazy rapidly :)
I recommend to just start playing the playlist and then press the shuffle button of the queue after some seconds, since the queue then loaded more videos of the playlist in the background.

> And maybe (very very maybe) you can get the API to return the videos in a slightly different order.
>
That doesn't work unfortunately, we don't have an API query to modify the sort order.
