### ISSUE TITLE
New design for card view mode

### ISSUE THREAD

**Issue by tvnmguy** [libre-tube/LibreTube#2214]
### Describe your suggested feature

![IMG_20221203_214241](https://user-images.githubusercontent.com/116799295/205450853-0d540a14-d32c-4fc2-96c5-bf1c3c8f6e3e.jpg)

![IMG_20221203_214207](https://user-images.githubusercontent.com/116799295/205450866-0ed4edd9-a7ab-44ff-a2e4-9606dde01091.jpg)

### Other details

This is also applicable for other view mode like list and grid with respective design.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thanks for the suggestion, however I don't think we should use cards everywhere and rather keep the current design as it's more minimal which fits the current UI better.
