### ISSUE TITLE
Progress bar indication colour with selected theme accent colour

### ISSUE THREAD

**Issue by tvnmguy** [libre-tube/LibreTube#2215]
### Describe your suggested feature

![IMG_20221203_214830](https://user-images.githubusercontent.com/116799295/205451080-82cba611-7131-4936-abff-b34402363a0e.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ARBoyGo** [comment]
Can you explain fully why you need this?

**Comment by tvnmguy** [comment]
> Can you explain fully why you need this? 

For grabing full potential of every different theme.

For example look into CloudStream.

![IMG_20221205_203859.jpg](https://user-images.githubusercontent.com/116799295/205671889-6f145bd1-d7cb-44e0-8c13-9e16667dd3d2.jpg)
