### ISSUE TITLE
Maintain same level of curvature for all thumbnail and duration card

### ISSUE THREAD

**Issue by tvnmguy** [libre-tube/LibreTube#2216]
### Describe your suggested feature

![IMG_20221203_220243](https://user-images.githubusercontent.com/116799295/205451412-3e9d6aaa-a285-4fb3-9d15-a134751f414d.jpg)

![IMG_20221203_220057](https://user-images.githubusercontent.com/116799295/205451434-a8426f58-ddf4-4797-a5cf-8b449ac25730.jpg)

![IMG_20221203_220200.jpg](https://user-images.githubusercontent.com/116799295/205451556-eb6992c9-8c0f-485d-8940-24c5f09b9a3b.jpg)

### Other details

Take curvature from the picture 'A' as the base.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ARBoyGo** [comment]
Please explain why?

**Comment by tvnmguy** [comment]
> Please explain why? 

For maintaining uniformity

![IMG_20221205_203548.jpg](https://user-images.githubusercontent.com/116799295/205670865-cb246d9b-68df-4ce3-9003-49070cf7a0e8.jpg)

**Comment by ARBoyGo** [comment]
Appolum issue create chayiumb ath enthannne parayanum oru detail information vanum, allakil aa issue reject avum nee verrum screenshot mattram share chaydutullo...

**Comment by tvnmguy** [comment]
> Appolum issue create chayiumb ath enthannne parayanum oru detail information vanum, allakil aa issue reject avum nee verrum screenshot mattram share chaydutullo... 

Issue create cheytha samayath njan vijarichu athu self explanatory aanennum screenshot maathram mathi ennu. Ethayalum adutha pravishyam ingane aavarthikkilla🙂

**Comment by ARBoyGo** [comment]
Very good ☺️

**Comment by ARBoyGo** [comment]
Do you know better malayalam words? Can you help it to translate to Malayalam fully?

**Comment by ARBoyGo** [comment]
Njan link share chaiyum

**Comment by ARBoyGo** [comment]
Do you use matrix or telegram, So that we don't distrub others on this issue...

**Comment by tvnmguy** [comment]
> Do you know better malayalam words? Can you help it to translate to Malayalam fully? 

Ee month 14 university exam und. So athu kazhinjittu njan shramikkaam🙂

**Comment by tvnmguy** [comment]
> Do you use matrix or telegram, So that we don't distrub others on this issue... 

Telegram only
