### ISSUE TITLE
Maybe a better naming scheme.

### ISSUE THREAD

**Issue by jbwfu** [libre-tube/LibreTube#2217]
### Describe your suggested feature

Occasionally, we need to download multiple audio and video files with different resolutions. When we want to keep the same file name, we will add `-number` after the original file name because the file name is repeated.  But the resolution is enough to distinguish different files, so `filename_resolution.suffix` is ​​a feasible and better solution than the current solution.

### Other details

E.g: 
  A 720p MPEG_4 video with 126 kbps WEBMA_OPUS audio.

When downloading to a local file save as `examplename_720p_MPEG4.mp4` and `examplename_126_WEBMA-OPUS.mp3`.

Filenames can be parsed directly when displayed in the app.

The title is the examplename, and the resolution and format are indicated in small font where appropriate.  It is even possible to display only a preview, but choose the resolution during video playback.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
First of all, sorry for the late response.
The issue has been depending on the custom download manager implementation which has been added with the last update, thus file extensions are already appended to the filename now as you suggested.
I agree that it makes sense to also include the quality in the filename, therefore I'll close the issues as soon as that is being implemented as well!
