### ISSUE TITLE
A better solution for the current comments layout

### ISSUE THREAD

**Issue by Tillo7** [libre-tube/LibreTube#2218]
### Describe your suggested feature

The current comment section's UX is good but many are unable to read comments while watching a video. I personally don't like to read comments while watching the video but many do like. So, I've an idea in which there's no need to alter the new UI and viewers can read comments while watching the video. This is similar to how YouTube does this. Inorder to do so, first we need to reduce the current length of the comment section interface so that the entire video is visible, and make it as default. After that if any user wants to read the comment while watching the video, he/she can scroll the comment section without the comment section being expanded to full-screen (and without the video getting out of sight) and they have option to make the comment section full-screen in case they only want to read comments or listen the audio while reading comments (Screenshots attached). I've included video of how it's implemented in the YouTube app.

Also, the devs can make the UI aesthetically pleasing by reducing the width of the corner in the comments section UX.

Nb: The devs can chose whether they want to play/pause the video when the comment section is expanded to full-screen.
![Screenshot_20221203-232852_LibreTube](https://user-images.githubusercontent.com/113629954/205455963-78987949-b8b4-4eff-98d7-2c5e51f505b2.jpg)
![Screenshot_20221203-232905_LibreTube](https://user-images.githubusercontent.com/113629954/205455966-12ab9bc9-7579-4638-8702-1c8d9160c730.jpg)
![Screenshot_20221203-232915_LibreTube](https://user-images.githubusercontent.com/113629954/205455970-55f9bc64-a248-400d-baa5-24ecc9f4e8ab.jpg)

https://user-images.githubusercontent.com/113629954/205455971-f37d75b7-ca83-4171-b202-e3898f8af0c5.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by teamblubee** [comment]
please do something like this, the new comments covering the video is disappointing.

**Comment by ahaone** [comment]
The previous comments section was less distracting. inline with the description looks uniform. Sometime less is better. For me classic comments section worked better.

**Comment by Bnyro** [comment]
> please do something like this, the new comments covering the video is disappointing. 
>
To not get disappointed I'd recommend you to fork the project and make it better.

**Comment by xIUPITERx** [comment]
I like the new comment sheet design and if we would limit the hight of the sheet, wouldn't we also have to change the hight of every similar object (like the queue) to have a homogeneous design?

**Comment by NeeRaj-2401** [comment]
@Bnyro can u please limit the max height of playing queue too
same problem as comment's height

<img src="https://user-images.githubusercontent.com/88180887/208226188-f63cbe2f-53c6-4a0d-9b26-78f1cce65c7f.png" width="30%">
scrolling between playing queue this hides the player

**Comment by Bnyro** [comment]
Tbh, I don't think anyone watches the queue and the video at the same time.
