### ISSUE TITLE
bookmarks at the navigation bar

### ISSUE THREAD

**Issue by heberjeur** [libre-tube/LibreTube#2220]
### Describe your suggested feature

Is there any chance to see bookmarks contents and the"watch history" at the navigation bar ?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We can't add more than 5 items to the navigation bar so adding new entries is not really possible.
