### ISSUE TITLE
the video titles are in the wrong language

### ISSUE THREAD

**Issue by Darkempire78** [libre-tube/LibreTube#2224]
### Steps to reproduce

1. Set your language fo French for example
2. Go to a french channel like "Inoxtag"
3. See that video titles are in english
4. Go to the "misterbest" channel
5. See that titles are in english too

### Expected behavior

French videos should displays the French title and the english videos that have french titles should be displayed in french too (on YouTube, misterbeast videos have a translated title)

### Actual behavior

Titles are always in english even if there is a translation in your device language

### LibreTube version

0.9.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The language of the titles is based on the region of the instance you're using, without support by the NewPipe Extractor for it there's no way to get localized titles.
