### ISSUE TITLE
Background playback stops randomly after turning screen off

### ISSUE THREAD

**Issue by RetroAbstract** [libre-tube/LibreTube#2231]
### Steps to reproduce

1. Pick a video
2. Play it normally with screen on
3. Lock your screen
4. Wait for the playback to suddenly stop

### Expected behavior

The expected behaviour is LibreTube to contine the playing video's playback with no interruption after locking the phone.

### Actual behavior

The playback stops anywhere between 2 to 15 minutes after locking the phone.

### LibreTube version

0.9.0

### Android version

Android 11 (Lineage OS)

### Other details

I have disabled the battery optimizations for LibreTube as recommended [here](https://github.com/libre-tube/LibreTube/issues/1847), but that doesn't change anything.

Playback cannot be resumed through the notification. It has to be resumed by going back into LibreTube & watching the video. 

Sometimes when going back into LibreTube to resume the playback, the player UI doesn't appear, resulting in having to play another video for it to reappear.

This does not happen on NewPipe.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by RetroAbstract** [comment]
Appears to be fixed when installing the universal release instead of arm64-v8a.

**Comment by farline99** [comment]
Same here, but both universal apk and arm64 had this bug, player is killed after 2-4 minutes. Battery optimization is disabled at all :(

**Comment by farline99** [comment]
Fix this please, very annoying :(
