### ISSUE TITLE
forward / rewind in notification

### ISSUE THREAD

**Issue by asklow** [libre-tube/LibreTube#2235]
### Describe your suggested feature

Playing in the background (audio only) has no forward / backward controls as there's no UI like video playback has.

Having these buttons `<<` `>>` under notification will at least mitigate this.

### Other details

A use case for this, is to play a video podcast in background, but with fine controlled +5 & -5 skipping along with seekbar.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It's available with Android versions lower than Android 13 as far as I know since the new media notification layout broke compatibility with the previous API for it I guess.

**Comment by Bnyro** [comment]
Yes, but I fear that we lose the Material 3 design of the play/pause button on the right if doing so as that's what many other apps with player notifications struggle with.

**Comment by Bnyro** [comment]
closing in favor of #2624
