### ISSUE TITLE
Ambient mode

### ISSUE THREAD

**Issue by ThatOneCalculator** [libre-tube/LibreTube#2236]
### Describe your suggested feature

Much like the new official YouTube app/website, adding ambient mode would be a nice addition.

### Other details

It seems to work by 
1) Grabbing a low resolution thumbnail of the frame ~1 second ahead of the current position
2) Splitting it into 12 sections (6 on the top, 6 on the bottom)
3) Extracting the primary color from each section
4) Blending a radial gradient the colors from all positions, letting them expand to the top/bottom of the video player
5) Repeating this until the end of the video, making smooth linear transitions between the colors (hue-shift)

Video demo:

https://user-images.githubusercontent.com/44733677/205542383-8300a024-c960-4818-baa2-2fffef7a18aa.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
I dont think that this is compatible with the material you design.

**Comment by ThatOneCalculator** [comment]
Material You is extendable. The whole point of it to express both the user's "style" and the content they're viewing in colorful, unique, and expressive ways.

**Comment by Bnyro** [comment]
Thanks for the suggestion!
First of all, as we use traditional XML and no Compose, it would be pain to get any sort of dynamic gradient working.
Second, extracting colors from the player might need either some external libraries (which might not exist) or our own way to extract them (which would be a PITA), as the player doesn't support it by default.
Third, I'm of the opinion that such a change wouldn't integrate well into the app's general design principles as it's targeted against the MD3 guidelines.
Hence I don't see a way to add this to the app, sorry.
