### ISSUE TITLE
comment count

### ISSUE THREAD

**Issue by asklow** [libre-tube/LibreTube#2237]
### Describe your suggested feature

Comments count I think it's possible to extract somewhere from YouTube's API.
Just put the number in brackets aside Comments button.

### Other details

Helps to judge a video on how much traction it got (also helpful to potentially avoid controversial videos or fake ones)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
There's no support for it at the NewPipe Extractor currently, so Piped doesn't support it either.

**Comment by Bnyro** [comment]
It'll be added as soon as the NewPipe Extractor supports it anyways so there's no reason to keep such issues open until then. If we did, it would be harder to overview current issues.
