### ISSUE TITLE
Hide 2K/4K quality options.

### ISSUE THREAD

**Issue by Dertyiula** [libre-tube/LibreTube#2242]
### Describe your suggested feature

Add option to hide 2K/4K quality options.Not all devices support these options and this creates a problem

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
There are no plans to remove functionality from the app ...

**Comment by Dertyiula** [comment]
There should be an option in the settings to hide it

**Comment by Dertyiula** [comment]
You don't need to delete it.
