### ISSUE TITLE
Not all channels are refreshed

### ISSUE THREAD

**Issue by fw190d13** [libre-tube/LibreTube#2245]
### Steps to reproduce

When I open the app all channels are refreshed automatically, when I pull down it also forces to refresh the subscriptions but when I have compared it with NewPipe (I have recently jumped ships) I can see that NewPipe grabs all of the channels but LibreTube misses a few now and then and I can't tell anything specific but these are random ones. When NewPipe missed some it informed me which (it showed the number of not refreshed ones), and offered to refresh those stuck and it was OK form then.

As mentioned earlier I'm new to this app so there is a chance that I'm doing something wrong or I should change something in the settings. if that is the case please assist me with fixing my problem

### Expected behavior

The app is refreshing all of the channels

### Actual behavior

It is refreshing only some channels and some (randome ones) are not refreshed and I have found the problem while watching on my laptop and using piped.video to go to a specific channel. Then I have spotted that I have missed a few episodes.

### LibreTube version

0.9.0

### Android version

Android 11 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
See https://github.com/TeamPiped/Piped/issues/1130
