### ISSUE TITLE
live time display during background playing

### ISSUE THREAD

**Issue by fw190d13** [libre-tube/LibreTube#2246]
### Describe your suggested feature

Hi!

Just jumped ship from NewPipe. That app allowed to play clips in the background and the player would still show me where I am in a certain clip. When It crashed, got stuck etc. i than could start from that specific point or when wanting to move a bit forward I could know where I am. I could also easily check how many seconds is left in that specific clip.

With LibeTube when starting the background player I dont't know where I am, how much is left etc. I sometimes pause or stop the background play and not always can get back to that specific moment. I might be operating the app in an unproper way and this can be my fault but I have tried to fiddle with the options and somehow get to understand the ins and outs and failed to find a solution.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The background playback is currently independent from the normal player which means they're not in sync, so you can only control it with the notification.
The issue for it is #1157.
