### ISSUE TITLE
There were no gear buttons.

### ISSUE THREAD

**Issue by Dertyiula** [libre-tube/LibreTube#2247]
### Steps to reproduce

1.Press and hold the channel.
2.Play the latest videos.
3.There are no next and previous video buttons.

### Expected behavior

It should have been.

### Actual behavior

https://user-images.githubusercontent.com/119277871/205708670-f6a7fd8d-3ab8-49c1-9498-d7ae48a3bad3.mp4

### LibreTube version

0.9.0

### Android version

Android 12

### Other details

No

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
In fact it's the same issue but #2257 describes it better.
