### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by therealbluepandabear** [libre-tube/LibreTube#225]
### Describe your suggested feature

You currently have no android tests or unit tests, I would recommend you add some.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That’s a good idea, would you mind making a pr to add some?

**Comment by therealbluepandabear** [comment]
> That’s a good idea, would you mind making a pr to add some?

OK, what type of unit tests do you want specifically?

I am good with Espresso, Room databases, and model tests.
