### ISSUE TITLE
Player upgrade.

### ISSUE THREAD

**Issue by Dertyiula** [libre-tube/LibreTube#2252]
### Describe your suggested feature

Additional functions by pressing and holding the channel.

![Screenshot_20221205-222655_LibreTube](https://user-images.githubusercontent.com/119277871/205713965-085a5adb-c655-4254-bb32-f35579095b3a.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ARBoyGo** [comment]
Explain.... What all functions....

**Comment by Dertyiula** [comment]
![Screenshot_20221205-225608_LibreTube](https://user-images.githubusercontent.com/119277871/205719948-fc4a36a9-a7f6-4e2a-b668-cebcd4671743.jpg)
