### ISSUE TITLE
Google Login

### ISSUE THREAD

**Issue by Drangonfly30** [libre-tube/LibreTube#2255]
### Describe your suggested feature

Hello, I know that libretube is privacy orientated and based on piped. But can it also have Google login simultaneously? Like there'll be pulled account but also Google login like Tubular(NewpipeXSponserblock) or something like Translate you. I love how fast this app grew. And I'm using it full time for replacement of YouTube vanced. But  I still miss having a home screen. I know it'll be tough to implement too. But I love how responsive Devs are to improve this app. And it's just a suggestion. I know what libretube's niche is. But still thought of asking it once if possible. And again I love how beautiful this app is, and how creative the Devs are.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please read https://github.com/libre-tube/LibreTube/blob/master/README.md#-about and https://github.com/libre-tube/LibreTube/blob/master/ROADMAP.md
