### ISSUE TITLE
Arrow sign.

### ISSUE THREAD

**Issue by Dertyiula** [libre-tube/LibreTube#2259]
### Describe your suggested feature

Add an arrow to populate the search from history.

### Other details

![Screenshot_20221206-085603_LibreTube](https://user-images.githubusercontent.com/119277871/205819840-b3726c96-77ee-4e18-8963-81d82e33b5eb.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Why?

**Comment by xIUPITERx** [comment]
> Why?

I think it was meant more as a bug report, as the search suggestions in 0.9.0 seem to be broken.

**Comment by adam-devel** [comment]
> Why?

To reach the search results what fewer typing, this feature is part of most search engines

**Comment by xIUPITERx** [comment]
> To reach the search results with fewer typing, this feature is part of most search engines

It's also part of LibreTube.

![Screenshot_20221207_160429_LibreTube Debug.png](https://user-images.githubusercontent.com/97352673/206214867-0b66aad8-db00-44c1-9830-4e02d00dcf78.png)

With the only difference that some search engines have an combined search (search through the history on the top and new search results beneath that) and libretube shows the history only before you entered somethung in the search field and after that only new results are shown, even if you had something matching in the history.
