### ISSUE TITLE
Horizontal spacing to seek bar/options dropdown

### ISSUE THREAD

**Issue by Arkhtek** [libre-tube/LibreTube#2261]
### Describe your suggested feature

Right now, in landscape mode, notches/holepunch cameras block the options dropdown or part of the seek bar. I suggest that you add some form of dynamic adjustment so that this doesn't happen. 

### Other details

this is really minor but its been bugging me for a bit lmao
![Screenshot_20221205-222711](https://user-images.githubusercontent.com/89922603/205824406-dd9e5d7a-2a55-4854-aad2-58a96df8f070.png)

if it helps at all, i use a google pixel 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
Can't you detect if a smartphone has a notch etc.

**Comment by Bnyro** [comment]
What difference would that make? I feel like that margin is a good idea for landscape mode in general because the corners of the phone are not that comfortable to reach.

**Comment by xIUPITERx** [comment]
It's more of a thing you're used to from other apps, the spacing is just pretty drastic (over half a centimeter) and I'm missing something design-wise in the empty space.

**Comment by xIUPITERx** [comment]
![Screenshot_20230120_194531_LibreTube Debug.png](https://user-images.githubusercontent.com/97352673/213780959-9076a6af-545b-4487-92f3-456f65ed1eb7.png)
