### ISSUE TITLE
Labels under icons are not visible

### ISSUE THREAD

**Issue by Nasrotunsi** [libre-tube/LibreTube#2275]
### Steps to reproduce

Chose a language other then english (ex: french) and some labels under the icons in the main player are missing

### Expected behavior

Labels should be visible under the icons

### Actual behavior

Labels are missing and the font size is different on each label
![Screenshot_2022-12-05-17-11-03-40_54f92cd6866f5233ab0db4392b806878](https://user-images.githubusercontent.com/119879161/206012596-65a19d7a-45c4-4273-b1e6-6795d370717a.jpg)

### LibreTube version

0.9.0

### Android version

Abdroud 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Any changes to that with the recent debug builds?

**Comment by shantanu1k** [comment]
@Nasrotunsi  try reducing the device font size to **default**.....

**Comment by Nasrotunsi** [comment]
@shantanu1k its already on default, even if I reduce it to small I still get the same issue. What about getting rid if the labels all together and keeping onky the icons?

**Comment by shantanu1k** [comment]
>What about getting rid if the labels all together and keeping onky the icons?
@Bnyro 

The cause of labels shrinking **after expanding PiP and going back to player** is the `autoSizeMinTextSize` (which is `10sp` for **big** words). I don't know why that could be triggering 🤔

**Comment by shantanu1k** [comment]
@Bnyro

**Comment by shantanu1k** [comment]
@FireMasterK

**Comment by FireMasterK** [comment]
> @FireMasterK 

Why did you tag me?

**Comment by shantanu1k** [comment]
> > @FireMasterK
> 
> Why did you tag me?

I just wanted to make sure if I am on the right track to fix this issue 😅

**Comment by Bnyro** [comment]
> The cause of labels shrinking **after expanding PiP and going back to player** is the `autoSizeMinTextSize` (which is `10sp` for **big** words). I don't know why that could be triggering thinking
>
Yes, that's the issue, but I've no clue how to fix it either.

> What about getting rid if the labels all together and keeping onky the icons?
@Bnyro
> 
That's not a good idea in my opinion, not all of the buttons are 100% self-explaining and they look better with a label.

**Comment by farline99** [comment]
I am also affected by this problem. It happens for me with Russian language. Look bad :)
