### ISSUE TITLE
Open button gone?

### ISSUE THREAD

**Issue by BlackLight** [libre-tube/LibreTube#2277]
### Steps to reproduce

Upgrade to any version >= 0.9.0

### Expected behavior

The Open/Open With button should be present in the player

### Actual behavior

The button has been replaced by "Pop-up"

### LibreTube version

0.9.0

### Android version

11

### Other details

The Open button has been replaced by Pop-up in [0.9.0](https://github.com/libre-tube/LibreTube/releases/tag/v0.9.0) - [associated PR](https://github.com/libre-tube/LibreTube/pull/2089).

Why this choice?

I used to use the Open feature to open videos in an external player (VLC), which in turn allowed me to do things like sharing the raw video link to other devices or cast it to Kodi/Chromecast.

Instead, the popup button simply moves the video player in a popup window. This makes this app completely pointless for my use cases, since all I get now is the ability to watch a video without ads inside of the app and nowhere else. This is as good opening a YouTube link in Brave or Firefox Mobile + uBlock.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Our own player has now pretty much all features a video player needs. The button has only been there previously to allow users using players like VLC for example for features like gesture controls which now isn't needed anymore.
If that's really why and how you use the app then don't hesitate to use something different, there are no plans to ever add the button again.

**Comment by DeWir3** [comment]
I used the "Open with" function for chromecasting to my TV through WebCast and it was working great. I don't know of any alternative I'd like to use that supports that unfortunately. So I would really appreciate it, if you'd reconsider putting it back in somewhere in the app, even if hidden.

**Comment by Bnyro** [comment]
If that's really something needed I would be okay with adding it as a smaller, lower prioritized button somewhere. However, 
1. that should be discussed in a new issue as an enhancement
2. I can't really think of a place for it currently so suggestions would be in your own interest (under a new issue)
