### ISSUE TITLE
Crash on inbuilt Update Checker 

### ISSUE THREAD

**Issue by teja3go** [libre-tube/LibreTube#2279]
### Steps to reproduce

Go to settings and then tap on check for updates.
It ask to update or cancel.
When pressed ok app crashed.

### Expected behavior

Download update from GitHub and prompt to install it.

### Actual behavior

App crash and ask to restart app.

### LibreTube version

0.8.0

### Android version

8.1

### Other details

Maybe still available in 0.9.0 I have to check when 0.9.x or 0.10.x comes out.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by rozari0** [comment]
It's fixed, download and install latest build from github this time. : )

**Comment by teja3go** [comment]
Thangs, I have updated it from GitHub.
