### ISSUE TITLE
Downloads are getting replaced

### ISSUE THREAD

**Issue by divi0001** [libre-tube/LibreTube#2281]
### Steps to reproduce

Open Libre Tube
Search any Video
Click Download with Audio only in 126kbps
Go to downloads folder
If you had previously downloaded a song, it is now replaced with the one currently downloading.

### Expected behavior

The downloads should add up and not geht replaced i guess?

### Actual behavior

The downloads replace each other making it impossible to download Mord than 1 audio.

### LibreTube version

Newest

### Android version

Graphene OS/newest

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Are you sure it's a different issue than #1943? I didn't yet experience any replacements of the downloaded video/audio, they're saved by the file name you give to them and hence it doesn't really make sense tbh
