### ISSUE TITLE
Clone playlist without sign in

### ISSUE THREAD

**Issue by tampos4** [libre-tube/LibreTube#2282]
### Steps to reproduce

clone a playlist

### Expected behavior

It should clone the playlist and the said playlist should show up in playlist section just like newpipe

### Actual behavior

It asks for sign in

### LibreTube version

0.9.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by rozari0** [comment]
If you want Newpipe like feel you should use bookmark.

**Comment by Donkey-Doug** [comment]
> If you want Newpipe like feel you should use bookmark.

How do I bookmark a video? I have never seen a bookmark button anywhere in libretube!

**Comment by rozari0** [comment]
> > If you want Newpipe like feel you should use bookmark.
> 
> How do I bookmark a video? I have never seen a bookmark button anywhere in libretube!

You can't bookmark a video, It's for playlists.

**Comment by Donkey-Doug** [comment]
![Screenshot_20221217-110919_LibreTube](https://user-images.githubusercontent.com/50382414/208236753-0e1fe1bc-7069-4a27-a65c-86e7190dd488.png)

But we have playlists and bookmarks. What is the difference? And how to bookmark a video?
