### ISSUE TITLE
Can't clone large playlists (600 videos and up)

### ISSUE THREAD

**Issue by C-c-combobreak** [libre-tube/LibreTube#2285]
### Steps to reproduce

1. Open LibreTube
2. Find a large playlist 
3. Try to clone it via a button

### Expected behavior

Of course, it should work

### Actual behavior

There was no error, but playlist didn't appear in my 'playlists' folder

### LibreTube version

0.9.0

### Android version

Android 12

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please open an issue at the Piped repo as the issue is not client side.
