### ISSUE TITLE
Having too much videos in saved playlist causes a crash

### ISSUE THREAD

**Issue by C-c-combobreak** [libre-tube/LibreTube#2289]
### Steps to reproduce

1. Have a Piped playlist with ~500+ videos (IMPORTANT: Not a bookmarked playlist)
2. Try to open it from an app

### Expected behavior

After some time playlist should load without problems

### Actual behavior

Loading takes too much time, app then crashes.

### LibreTube version

0.9.0

### Android version

Android 12

### Other details

I believe it's happening because app is trying to load all videos in a playlist at once. It doesn't matter when there are 100 videos present, but when it's 1000, everything breaks. I think that loading only a part of playlist at a time would help (like bookmarked and public playlists do that)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
In theory it shouldn't crash when there are a lot of videos in a playlist, it should just be really slow.

**Comment by C-c-combobreak** [comment]
(Whoops, wrong button) I believe that it happens only when trying to interact with a screen during loading

**Comment by Bnyro** [comment]
Any example playlist for reproducing?
