### ISSUE TITLE
New position for "Open with" button

### ISSUE THREAD

**Issue by DeWir3** [libre-tube/LibreTube#2292]
### Describe your suggested feature

With update 0.9.0 the "Open with" button was replaced with PiP. While I understand that it was a very prominent placement for a niche feature, I was using it regularly for chromecasting videos through WebCast. Therefore I would appreciate it, if that function could be added back in a less prominent position. Possible placements I could think of are:

1. as a long-press action on the Share button
2. in a drop-down next to the row of buttons
3. as an option in the long-press menu when selecting a video from a list
4. in the top-right drop-down menu of the video

Those are the ones I could think of, there are probably other options as well. It could also be hidden behind an opt-in in the settings to have the button at all to avoid clutter for people who don't need it. I just think it's a really cool feature and I'd be sad to see it gone for good.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by StanleyBonhomme** [comment]
I second this. The open with option would be a good feature to have back.

**Comment by Solidwire99** [comment]
Yes Please... Re-adding the OPEN function would be greatly appreciated! 
I don't understand the need for the current use of the POP button as PIP functioned perfectly in the previous versions ?
