### ISSUE TITLE
Full screen vertical video

### ISSUE THREAD

**Issue by Nasrotunsi** [libre-tube/LibreTube#2293]
### Describe your suggested feature

Add an option to watch vertical videos (ex shorts) in full screen without turning the phone, like how newpipe implements it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
Why don't you use the normal fullscreen button?

**Comment by Nasrotunsi** [comment]
@xIUPITERx I do but I think it would be nice to have the button to make vertical videos full screen while also being able to rotate the phone and enter full screen for horizontal videos.

**Comment by Bnyro** [comment]
Set the player fullscreen orientation to auto rotation, adding an extra option doesn't make sense.

**Comment by Nasrotunsi** [comment]
@Bnyro yes but then you can't see the vertical video full screen and when you rotate the phone the video looks small

**Comment by awebeer256** [comment]
> Why don't you use the normal fullscreen button?

…Because there isn't one? 🤨

> Set the player fullscreen orientation to auto rotation

Then you're watching a portrait video on a landscape screen with enormous black bars on the sides.

![Screenshot_20221230-025210](https://user-images.githubusercontent.com/26385859/210047622-0baeae1a-e3c7-4b65-bbad-51bcb18d84b7.png)

**Comment by xIUPITERx** [comment]
I think this is more like an bug, normally it recognizes Shorts and if you activate fullscreen, the fullscreen is also vertical, but very rare the fullscreen opens horizontal.

**Comment by awebeer256** [comment]
I'm pretty new to this app but that "very rare" behaviour is the only one I've ever experienced.

**Comment by Nasrotunsi** [comment]
> I think this is more like an bug, normally it recognizes Shorts and if you activate fullscreen, the fullscreen is also vertical, but very rare the fullscreen opens horizontal.

I dont think its rare at all, all the short videos open 8n horizontal full screen
