### ISSUE TITLE
odds and ends template

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#2294]
### Describe your suggested feature

I don't know exactly how many issue templates you can have on GiHub, but maybe there should be a third option where suggestions for improvements that are only small adjustments or additions can be made, perhaps automatically with a low priority label. 
So that the user is not too irritated if nothing happens for a long time, but more importantly, the developers are not annoyed by small things. You could then add a field in the template where similar and related suggestions can be linked.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't think we should add such templates, feature requests can be labeled as low priority anyways if they're useless.
