### ISSUE TITLE
Live stream player occasionally freezes when there is buffering

### ISSUE THREAD

**Issue by RoonMoonlight** [libre-tube/LibreTube#2295]
### Steps to reproduce

1. Play any livestreams
2. When there is any buffering for livestream it freezes the player instead

### Expected behavior

It should resume normally like YouTube.

### Actual behavior

![Screenshot_20221208_160921_LibreTube](https://user-images.githubusercontent.com/25527589/206382312-4a5355ee-6da0-4214-9895-575017635404.jpg)
The screen freezes, no buffering indicators, play button in player does not work at all (Other buttons seems to be working fine like 'Add to Playlist', 'Audio')

When it happened I thought it was my network-side issue but found out to be bug related to buffering handling from the app.

### LibreTube version

0.9.0

### Android version

Android 13 / Samsung S22+ One UI 5

### Other details

I've also tested on my PC with Piped but it worked well on that side.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by vedxp** [comment]
It seems to happen with me with regular videos too. I thought it's my network issue, but probably it's not.

Specs:
- Android 12
- Realme UI 3

**Comment by RoonMoonlight** [comment]
Well the web version from Piped has same issue, gotta report there as well

**Comment by vedxp** [comment]
> It seems to happen with me with regular videos too. I thought it's my network issue, but probably it's not.
> 
> Specs:
> 
> * Android 12
> * Realme UI 3

Update: It's happening more frequently as compared to older versions before `0.9.1`.

**Comment by DerpTheDark** [comment]
I've never used github before

An improvement I'd like to see, is livestreams sent to the subscriptions tab on the APK version. They dont show up right now.

**Comment by Bnyro** [comment]
That's either an issue of the ExoPlayer or the server load of the currently used instance's proxy, nothing we could do about it at client side currently.
