### ISSUE TITLE
Previously played video button

### ISSUE THREAD

**Issue by pawa2401** [libre-tube/LibreTube#2309]
### Describe your suggested feature

I sometimes accidentally click on one of the recommended videos and I have to go to watch history to go back to the video I was watching.
Since there is a next video button, there should be one to go back to the previous one.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by pawa2401** [comment]
Accidents happen because humans as a race isn't perfect. You can't entirely eliminate these accidents by doing software changes. And this feature could be handy for anyone, not only the clumsy people that accidentally click one of the recommended videos.

Also, replaying history is basically what this button should do imo. Right now I have to exit the video, go to watch history and manually click the video that I watched before.

**Comment by Bnyro** [comment]
A back button is already existent but for the queue. When clicking a video, a new queue gets generated so it's not possible to get back to the old queue.
