### ISSUE TITLE
Videos take a long time to start playing

### ISSUE THREAD

**Issue by novocaiin** [libre-tube/LibreTube#231]
### Steps to reproduce

Open any video or scrub through a video.

### Expected behavior

Video plays instantly.

### Actual behavior

Takes a while for the video to start playing, sometimes longer than an ad would've taken to finish in the YouTube app or the mobile web version.
Jumping to some other timestamp also causes it to buffer for a long time before it can play again.

Both the YouTube app and the web version start playing instantly at the highest res, no matter whether opening a video or scrubbing to some timestamp.

### LibreTube version

0.2.7

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by mishailovic** [comment]
Wanted to open same issue several weeks ago, but thought that it's something with my internet connection. Seems like I'm not only the one

**Comment by Bnyro** [comment]
Yes, we're aware of it. We're trying our best to reduce loading times.

**Comment by mishailovic** [comment]
What the reason of it? I compared the app behaviour with the piped website, and it seems like website has no issues with loading videos, why for the app it takes so much time?

**Comment by novocaiin** [comment]
No actually Piped is also slower than YouTube (albeit still faster than LibreTube), so some of the overhead probably does come from Piped's end.

**Comment by mishailovic** [comment]
Seems like the only way to deal with that is to deploy instance of piped which will work only for LibreTube users. Or use the local instance which will work right on the user's device as mentioned in another issue

**Comment by huk9000** [comment]
At least in my case, using the "play using VLC" button seems to make the loading times much better, I've tried using the default server and also privacy.com.de

**Comment by mishailovic** [comment]
> 

This requires local server because YouTube gives link which will work only on the ip from which video was requested

**Comment by mishailovic** [comment]
> Would giving an option to stream the videos directly from YouTube be possible? Akin to feeding a video link to mpv or vlc and playing from there (but without all the manual work).

This requires local server because YouTube gives link which will work only on the ip from which video was requested

**Comment by uuuussseer** [comment]
Hey, I found a way to (temporarily) fix this issue.

Go to Settings->Default Video Resolution and select HLS.

Videos load almost instantly for me now, although the issue should still be fixed.

**Comment by Bnyro** [comment]
> Hey, I found a way to (temporarily) fix this issue.
> 
> Go to Settings->Default Video Resolution and select HLS.
> 
> Videos load almost instantly for me now, although the issue should still be fixed.

@uuuussseer Thank you for telling, didn't know it's only an issue with default resolutions set. So there's probably something wrong with the default resolution setting.

**Comment by novocaiin** [comment]
Can confirm HLS is noticeably faster.
Kinda feeling dumb now :D

HLS = variable res with separate audio and video?
Or is it the DASH format?

**Comment by archroid** [comment]
Some reports say that the loading time depends on the video length and the longer it is, the slower it loads. Still trying to find the fix.

**Comment by FireMasterK** [comment]
> Still trying to find the fix. 

I suggested that DASH could be a potential fix in the matrix room. I will try implementing a prototype if I have time.

**Comment by novocaiin** [comment]
>I suggested that DASH could be a potential fix in the matrix room. I will try implementing a prototype if I have time.

Would that allow support for audio only during background play?
That can save a decent amount of battery life and data.

**Comment by FireMasterK** [comment]
> Would that allow support for audio only during background play?
> That can save a decent amount of battery life and data.

No, that's actually irrelevant to this issue.

**Comment by novocaiin** [comment]
Well, since DASH allows separate audio and video streams, wouldn't that allow it?
I realize it's kinda off-topic.
I can open a separate issue for that.

**Comment by Nizami20052022** [comment]
To do this, Auto Video Quality must be added.

**Comment by Bnyro** [comment]
Could anyone test it again on the latest CI builds? (ik it's not 100 per cent fixed but it might be better now)

**Comment by xIUPITERx** [comment]
I think the buffering doesn't start immediately. If you rewind once or twice by a few seconds the buffering starts like it should and you are overall faster than if you do nothing.

**Comment by Bnyro** [comment]
Closing this for now as there's nothing that can be changed about it at the frontend-side currently. Using HLS is recommended for the best loading speed!
