### ISSUE TITLE
When using play all option in playlist, autoplay set to on shouldn't have to be enabled.

### ISSUE THREAD

**Issue by pawa2401** [libre-tube/LibreTube#2310]
### Steps to reproduce

1. Click the play all button in any local playlist containing a few videos
2. If the autoplay option is OFF, only one video will play

### Expected behavior

It should play all of them, no matter what the autoplay setting is set to

### Actual behavior

Plays only the first video in the playlist 

### LibreTube version

0.9.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by pawa2401** [comment]
> The recommended configuration is to enable Autoplay & disable insert related videos. Implementing your FR would rather complicate things.

I don't think you should have to set something against your liking, just so that the feature works properly.

Also, I'm pretty sure related videos aren't the issue. It is just autoplay. It plays the playlist just fine with autoplay on, no matter if there are related videos enabled or not.

**Comment by Bnyro** [comment]
There's an issue to separate autoplay for playlists and for normal queues, hence it's either a dupe or working as intended.
