### ISSUE TITLE
Option to disable playback positions for (specific) playlists

### ISSUE THREAD

**Issue by pawa2401** [libre-tube/LibreTube#2312]
### Describe your suggested feature

I have a music playlist, and it's annoying that each time I finish listening in the middle of the song, I have to rewind it back to the beginning for each track. I would like this feature on all the other videos, so disabling it entirely isn't ideal.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by pawa2401** [comment]
That's unnecessary. Just make it so when the switch/option is active for a playlist, it ignores the saved position for the video that is accessed from the playlist (or automatically played by the play all function), or make it automatically set the playback timer for the video (in the player) to 0 sec.

**Comment by Bnyro** [comment]
Well, it's still not clear when a video is a playlist and when it's not as people can just modify the queue as they want. Suggestions here?

**Comment by Bnyro** [comment]
#3020 and #3035 now allows you to disable watch positions for the audio only / background mode, so you probably just want to do that and listen to your music in the background mode.
