### ISSUE TITLE
Add ability to create a playlist/collection of subscriptions (subscription categories)

### ISSUE THREAD

**Issue by Mhandis** [libre-tube/LibreTube#2313]
### Describe your suggested feature

Adding this feature would allow the user to organize their subscriptions into custom categories. Navigating to a specific category would then only show videos from the subscribed channels in this category.
e.g.
-> Categories:
       |- Sports                   (user created)
                |-- ESPN            (subscribed channel)
                |-- Fox Sports    (subscribed channel)
       |- News                    (user created)
                |-- BBC             (subscribed channel)
                |-- CNN            (subscribed channel)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That won't be possible until the API supports it unfortunately.
