### ISSUE TITLE
Customize the order of elements on the new home page

### ISSUE THREAD

**Issue by Warden20** [libre-tube/LibreTube#2314]
### Describe your suggested feature

The new home page is useful to use but I would like to be able to place the playlists to my preference and not at the end. Maybe there is the possibility to change the order of the elements?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by NeeRaj-2401** [comment]
The way it is implemented is already  amazing... I don't think its necessary to everything in app should be customisable.

**Comment by Bnyro** [comment]
> The way it is implemented is already amazing... I don't think its necessary to make **everything** in app should be >
customisable.
>
I agree on that, not everything needs to be customizable. If you want to have control over what you see use the bottom navigation instead of the home page.
