### ISSUE TITLE
Ability to perform searches through the phone launcher as a custom search

### ISSUE THREAD

**Issue by Warden20** [libre-tube/LibreTube#2315]
### Describe your suggested feature

Many times I just want to do a quick search from the launcher in my case KISS Launcher. It would be convenient to be able to search directly to save time.
Kiss launcher has the option to create custom searches from different search engines I wanted to know if libretube plans to implement some search compatibility with that mode

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't know how the KISS API for that works and without some docs for it it won't be possible.
Anyways, support for that would probably be a niche feature mostly, hence no plans for adding it, PRs for it would most likely get accepted.
