### ISSUE TITLE
search suggestion reversal

### ISSUE THREAD

**Issue by asklow** [libre-tube/LibreTube#2316]
### Steps to reproduce

Searching some word halfway should get the suggestion of that word completion. But instead, only the suggestions with the next word autocompletes are shown.

### Expected behavior

Here's an example...
"Unbox th" should show "Unbox therapy" first, then further auto completions next...
Here's how piped shows
![Screenshot_20221209-035105_Kiwi Browser](https://user-images.githubusercontent.com/117489882/206618151-4748279b-49ae-40ff-a479-961282726699.png)

### Actual behavior

But what LibreTube shows is

![Screenshot_20221209-035026_LibreTube](https://user-images.githubusercontent.com/117489882/206618385-678f2e77-f386-47ef-972b-e763f25cb6d9.png)

There is no "Unbox Therapy". LT skips that & directly shows "Unbox Therapy (completions)"
I had to append one of below suggestions first, & then remove a word to get my desired phrase.

You can also try other phrases too. You wouldn't get the completion of the word you type. Instead, you get the auto completions that involve that word.

### LibreTube version

0.9.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by tampos4** [comment]
Thanks for posting. This is very irritating.

**Comment by akano12** [comment]
If you could change the title to "Search Suggestions Don't Include Channel Name".


Also it's not really a big deal, 

1- You can click on any related search item then from the results you can visit the channel by tapping on channel name.

2- Let's assume this issue didn't exist and "Unboxing Therapy" was suggested, tapping on the search suggestion wouldn't open the channel anyway and you'd still have to tap on channel name to view the Channel.

**Comment by Bnyro** [comment]
What our actual issue here is is that we reverse the layout for the search history but then show the search suggestions in the same reverse order which makes the usually last suggestion become the first and vice versa. Sometimes, the input of the user, if it's a channel name for example, is suggested, but as it's revered (unintended), it appears to be the last one.

**Comment by akano12** [comment]
> @akano12 It's not just the channel name. It affects the regular phrases too, like "how to" "why is this", "which country", etc... Instead of the most desired result first, you'd get the least desired first.
> 
> As bnyro said that it's just a reversal view issue, the favored results just sit under the keyboard you type. Just had to remove that keyboard & there you go.
> Hope that this suggestion view get reversed.

Thanks for clarification, honestly i didn't notice before you opened this issue. My searches on YouTube are straight up direct searches (not following/subscribing to anybody, no Playlists, nothing at all), just use LT to search for football match summaries and programming related things. I basically use the minimal features this app offers lol
