### ISSUE TITLE
Temporary Change of Piped Instance

### ISSUE THREAD

**Issue by Tanmandal** [libre-tube/LibreTube#2319]
### Describe your suggested feature

If a video has issue playing from an instance , a toggle can be included in the video page to select any other instance only for that video

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
No plans to allow temporarily changing the instance.
