### ISSUE TITLE
Add an option to show colored SponsorBlock markers

### ISSUE THREAD

**Issue by yhm3ps1jfp76nkd** [libre-tube/LibreTube#2323]
### Describe your suggested feature

Colored SponsorBlock markers show the user what type of segment is about to be skipped

### Other details

Make it disabled by default?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Dupe of #2276
