### ISSUE TITLE
Lastest Update no longer Allows the Ability to Share to other Apps

### ISSUE THREAD

**Issue by StanleyBonhomme** [libre-tube/LibreTube#2327]
### Steps to reproduce

The latest update to the app does not allow the ability to share to other apps. 

![Screenshot_20221209-160459](https://user-images.githubusercontent.com/30869347/206796254-173fd653-9ebc-43ee-b68a-a743bfc2e08e.png)

For example if I wanted to share the video to VLC player app on my phone that way I can cast it to me TV I can no longer do so. 

### Expected behavior

The expected behavior would be the share video the video to other apps. For example VLC app.

### Actual behavior

It brings up options for YouTube and Piped. 

### LibreTube version

Latest 

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
What you're describing here never actually existed, what you mean is probably a dupe of #2292
