### ISSUE TITLE
0.9.0 - Broken

### ISSUE THREAD

**Issue by r-uss1** [libre-tube/LibreTube#2345]
### Steps to reproduce

Install & open you will see what I show in screenshot below.

https://1drv.ms/u/s!AsI_IqNXG_t2hCfXfmipfSAK14Hh

### Expected behavior

I expect it to load but instead it errors. 

### Actual behavior

Endless loading.

### LibreTube version

0.9.0

### Android version

Android 12

### Other details

Stock No Root Samsung Galaxy A13 5G.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
You haven't uploaded a screenshot yet.

**Comment by r-uss1** [comment]
> You haven't uploaded a screenshot yet.

Yeah, sorry I am new to this but can't figure out how to add one.

**Comment by Bnyro** [comment]
Try choosing a different instance or adding and using a custom instance you added manually to the app from https://github.com/TeamPiped/Piped/wiki/Instances if the instances list it empty.

**Comment by r-uss1** [comment]
I did that but it just endlessly loads. The official one just gives the
same error. But yet, on first install LibreTube is missing any instance at
all.

**Comment by akano12** [comment]
Test on Mobile data/VPN/Different Network/Different Device

**Comment by Bnyro** [comment]
kavin.rocks is probably blocked in your region/country and can't be accessed, hence no instances show up. That's why I recommended to add an other, custom instance.

**Comment by Bnyro** [comment]
No, that's only for the frontend, it's irrelevant for the API (which is the only thing LT uses)
