### ISSUE TITLE
Add Bookmarks as a seperate tab

### ISSUE THREAD

**Issue by tampos4** [libre-tube/LibreTube#2350]
### Describe your suggested feature

Add an option to set Bookmarks section also as a seperate tab in Navigation bar in 
Settings > Appearance > Order > [x] [Bookmarks]

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
There's an Android limit that prevents us from having more than 5 different entries in the navigation bar, hence adding a new one is currently not possible.

**Comment by tampos4** [comment]
Currently I have only 2 entries (Subscriptions and Library),
and I want to have the third one i.e. Bookmarks

I think it will be very useful for people like me who do not want any distraction, suggestions etc. (Trends and Home tab)
