### ISSUE TITLE
Video progress skip gesture broken since 0.9.0

### ISSUE THREAD

**Issue by MatsG23** [libre-tube/LibreTube#2352]
### Steps to reproduce

1. Play any video
2. Try to move the video progress forward/backward by double-tapping on the left/right side

### Expected behavior

The video should skip 10s forward/backward. This was how it worked in the previous version of LibreTube. I do not think this was removed intentionally because it have not been in the changelog and is a perfect, very intuitive feature.

### Actual behavior

Nothing happens.

### LibreTube version

0.9.0

### Android version

Android 13 QPR1

### Other details

Using GrapheneOS.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It's called double tap to seek in the player settings.
