### ISSUE TITLE
fuck the trends tab

### ISSUE THREAD

**Issue by fftcc** [libre-tube/LibreTube#2353]
### Steps to reproduce

why can't you disable the "trends" tab in the new update?

### Expected behavior

why can't you disable the "trends" tab in the new update?

### Actual behavior

why can't you disable the "trends" tab in the new update?

### LibreTube version

0.9.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by rozari0** [comment]
Pretty much sure you can.

**Comment by fftcc** [comment]
does not work https://ufile.io/joq7rmbt

**Comment by fftcc** [comment]
ok, I admit, I dumb!

**Comment by fftcc** [comment]
but the trends still suck

**Comment by rozari0** [comment]
> @fftcc Agreed. But it's user's issue. Can't remove the functionality for everyone just caz one doesn't like it.

Just select Iran. Won't see trends anymore.

**Comment by fftcc** [comment]
ok👍the issue is closed
