### ISSUE TITLE
filter list

### ISSUE THREAD

**Issue by asklow** [libre-tube/LibreTube#2355]
### Describe your suggested feature

Before listing the timelines, go through a set of userland filter list configuration that blacklists videos of certain words from the list.

### Other details

For ex, I don't wanna see anything "gaming" related from tech YouTubers. I can just filter buzzwords like "gaming", "game", "steamdeck", etc... & completely get rid of them. That's how I avoid some nonsense toots on Mastodon too.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
Could this be achieved by manually tagging channels?

**Comment by Bnyro** [comment]
Would probably cause the same issues as discussed in #1173

**Comment by Bnyro** [comment]
Closing because the potential use cases are quite small and there's no API support.
