### ISSUE TITLE
increase OSD button size

### ISSUE THREAD

**Issue by asklow** [libre-tube/LibreTube#2362]
### Describe your suggested feature

1. It's little uncomfortable to operate seek buttons that exist close to the center of the screen. A better position for seek buttons would be in the middle of the either side of screen.

![Screenshot_20221213](https://user-images.githubusercontent.com/117489882/207212630-d0e381ec-66d8-4b49-9a19-4f00db02cdd5.png)

2. OSD buttons are quite small tbh. Increasing size/radius of OSD buttons for better reach. For reference, this is how big the radius of buttons in NewPipe.

![Screenshot_20221213_NewPipe](https://user-images.githubusercontent.com/117489882/207214872-70ddd551-48d0-4856-a8aa-a8863377ea49.png)

This itself should fix 1 inherently, by increasing button size, hence pushing seek buttons to the middle of both halves of the screen.

### Other details

This is to improve the accessibility of OSD buttons for better reach.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I'm not of the opinion that the buttons are too small, with their padding they almost feel too big.
I'm not a fan of the NP play/pause button here, it feels way too big.
The thing with the seek buttons is that it's possible to enable the previous/next buttons too and hence we can't move other buttons to that position.

**Comment by Bnyro** [comment]
No changes planned here currently.
