### ISSUE TITLE
Backup all App data (using without sign in)

### ISSUE THREAD

**Issue by tampos4** [libre-tube/LibreTube#2363]
### Describe your suggested feature

Could we get the feature to backup all the data of the app

1. Settings > Backup & restore > App backup > (all) or
2. a "select all" option above the entries or
3. at least remember my last selection (what entries I last time exported)

I think last option is the best one

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
They're all checked by default now, I don't think something like a backup all button or remembering is needed/would be worth the efforts as users probably only do backups when they're planning to change their phone or OS which isn't the case that often.
