### ISSUE TITLE
Feels like i have poor connection

### ISSUE THREAD

**Issue by DavidMugisha** [libre-tube/LibreTube#2365]
### Steps to reproduce

1. open libretube app
2. Click to play any video
3. Issue on player, it feels like there is poor connection

### Expected behavior

Video should be keep on playing without loading unless there is connection related issue

### Actual behavior

Video plays 2 to 3 seconds and loads, as if there is poor connection

### LibreTube version

0.9.0

### Android version

Android 10

### Other details

Video quality remain unchanged mostly. I changed region multiple times but issue remains.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Loading speed depends on the instance!
