### ISSUE TITLE
[Feature Request] Player seekbar thumbnail preview

### ISSUE THREAD

**Issue by Generator** [libre-tube/LibreTube#2366]
### Describe your suggested feature

Show thumbnail preview on seek bar.

Similar to Youtube and NewPipe, show a preview during seek.

### Other details

From Newpipe:
![120906070-b02a9580-c656-11eb-9d1b-6631ab2bb080](https://user-images.githubusercontent.com/44146/207356738-7be8a491-74c0-499a-88ce-12b5d19a458e.png)

NewPipe PR
TeamNewPipe/NewPipe/pull/6434

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FireMasterK** [comment]
> I don't think it's possible caz even piped does not do thumbnail preview extraction ([TeamPiped/Piped#105](https://github.com/TeamPiped/Piped/issues/105))

Piped's API supports it, but not the frontend.

**Comment by Fidannyan** [comment]
YouTube also has the addition of Accurate search support and full screen support

https://user-images.githubusercontent.com/120574401/208036736-133fb578-6e61-4995-ae35-6bd2a9251f5c.mp4

YouTube supports all three of these features.

**Comment by Fidannyan** [comment]
#2376 , #2070 How are all these gestures added?
