### ISSUE TITLE
Remember playback speed.

### ISSUE THREAD

**Issue by Lemon-in-Suspense** [libre-tube/LibreTube#2370]
### Describe your suggested feature

I watch videos at 2x. So, I have to set each and every video I play, to 2x individually. Kindly add the feature to remember the playback speed from the last played video (like in NewPipe) so that all the videos play at 2x (or whatever speed I choose) automatically.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That has already been added (not released yet though).

**Comment by Lemon-in-Suspense** [comment]
> That has already been added (not released yet though).

Ok thanks. Waiting for the release eagerly!
