### ISSUE TITLE
[Feture] inbuilt Debug apk update

### ISSUE THREAD

**Issue by NeeRaj-2401** [libre-tube/LibreTube#2372]
### Describe your suggested feature

As the stable version have inbuilt updater in app.
Would be good if we can get the same in debug version too.

all commits to "main" branch would be considered as debug new update.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by NeeRaj-2401** [comment]
to achieve this making every build as **pre-release**
then fetch that build  and its version would work ?

**Comment by Bnyro** [comment]
Debug versions can often be unstable, that's why I wouldn't want to use pre-releases for them.
Apart from that I'm not of the opinion that it'd be worth it as the latest builds can be found at https://github.com/LibreTubeAlpha/Archive.

**Comment by NeeRaj-2401** [comment]
> Debug versions can often be unstable,

mostly Debug versions are used by testers. So, they can expect these unstable bugs etc also in app updater will help them to be updated with commits and report you. :)

also, you better if its worth it to implement or not.
