### ISSUE TITLE
Scroll to the top of the page.

### ISSUE THREAD

**Issue by NaN-Sz** [libre-tube/LibreTube#2374]
### Describe your suggested feature

Scroll up when the Navigation Bar icons is pressed, similar to the YouTube application.[translated]

![Screenshot_example_YouTube](https://user-images.githubusercontent.com/120607988/207740816-395a4a56-11da-4d49-b163-781f2e9d4e2b.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We can't scroll to its top programmatically like so because each fragment works differently. The only viable way would be to reload the tab which is what we were trying to avoid for UX reasons.
