### ISSUE TITLE
Pin comments below the video.

### ISSUE THREAD

**Issue by Fidannyan** [libre-tube/LibreTube#2375]
### Describe your suggested feature

To display comments while watching a video, pin comments below the video.

https://user-images.githubusercontent.com/120574401/207779807-a05e7a1d-8ccd-45dd-a399-f586cc5afbb2.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Loading them requires a separate API call so previewing is only possible if we load the comments (longer loading times in worst case) although the user didn't ask for it.
