### ISSUE TITLE
Change Page by swiping left and right.

### ISSUE THREAD

**Issue by Fidannyan** [libre-tube/LibreTube#2377]
### Describe your suggested feature

Swipe right to left to change page in the channel.(<>)

### Other details

https://user-images.githubusercontent.com/120574401/207783645-3d09a67b-d4fb-4293-86f7-04be109b39f1.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
No real framework, traditional XML. We would need to add a third party dependency for it probably which I want to avoid in fact.
