### ISSUE TITLE
Change the video by swiping left and right

### ISSUE THREAD

**Issue by Fidannyan** [libre-tube/LibreTube#2378]
### Describe your suggested feature

https://user-images.githubusercontent.com/120574401/207788434-b99e7126-dc70-4662-a349-f0ff1498642f.mp4

### Other details

This can be useful in landscape mode.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
As already mentioned it conflicts with the current gesture support.
