### ISSUE TITLE
Privacy Policy.

### ISSUE THREAD

**Issue by Fidannyan** [libre-tube/LibreTube#2379]
### Describe your suggested feature

Add a Privacy Policy to the app.Also, translators should translate it into their own languages.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by yhm3ps1jfp76nkd** [comment]
Also I think the privacy policy in the readme should be updated to clarify that the app doesn't collect any data at all by itself and the data collection is handled by the Piped instances (correct me if I'm wrong)

**Comment by Bnyro** [comment]
No plans to add such a section inside the app (I'm not aware of any other app that does it), PRs for changing the README are accepted.
Though, as long as you don't log in with a Piped account no data is stored at all.

**Comment by tampos4** [comment]
> No plans to add such a section inside the app (I'm not aware of any other app that does it),

Newpipe 
![IMG_20221216_013009](https://user-images.githubusercontent.com/103326242/207955953-882d54b8-b9df-4671-904d-96e4c160a152.jpg)

**Comment by tampos4** [comment]
> No plans to add such a section inside the app (I'm not aware of any other app that does it)

NewPipe

![IMG_20221216_013009](https://user-images.githubusercontent.com/103326242/207956606-60f9a970-130d-4ea8-8c48-7fb9b5e5b805.jpg)


[Infinity For Reddit](https://github.com/Docile-Alligator/Infinity-For-Reddit) 

![IMG_20221216_013428](https://user-images.githubusercontent.com/103326242/207956698-246d4fc5-502e-4d04-8d48-dc9368d1d8cb.jpg)


All [Simple Mobile apps](https://www.simplemobiletools.com)  ( Gallery, File Manager, Calendar, Notes etc)

![IMG_20221216_014030](https://user-images.githubusercontent.com/103326242/207957550-fd9a8a52-fc04-4032-b5fd-6de5f84ea866.jpg)


[Syncthing](https://github.com/syncthing/syncthing-android)

![IMG_20221216_014355](https://user-images.githubusercontent.com/103326242/207958034-4f38e91e-b374-4eda-8281-831dc93fb271.jpg)
 

[Translate You](https://github.com/Bnyro/TranslateYou) 

![IMG_20221216_014542](https://user-images.githubusercontent.com/103326242/207958264-b008111e-4dc4-428d-8b18-33ac50148775.jpg)

**Comment by tampos4** [comment]
> PRs for changing the README are accepted. 

Could you please reopen this issue.

**Comment by Fidannyan** [comment]
> > PRs for changing the README are accepted.
> 
> Could you please reopen this issue.

If necessary, he will write an answer, don't waste time.

**Comment by Bnyro** [comment]
Well, thanks for searching for examples but that still doesn't change my opinion on it. Such a "text" would probably be really long and I'm not a fan of adding too many new, long strings as that causes extra efforts for any trabslators.
