### ISSUE TITLE
Unable to use app without network

### ISSUE THREAD

**Issue by tampos4** [libre-tube/LibreTube#2385]
### Steps to reproduce

1. Turn off network connection
2. Open app

### Expected behavior

I am using the app **without signing in.**

If I am not signed in and storing all my playlists [and Subscriptions] locally then I should be able to add, delete or modify them without needing any network connection.

### Actual behavior

If I open the app with data on
and then turn off the data
now if I add any video to any local playlist or try to make a local playlist, I am unable to do. (Network error)

### LibreTube version

0.9.0

### Android version

Android 12

### Other details

**1.** Why a network connection is needed to make a local playlist?
**2.** Why a network connection is needed to add any  video of a local playlist to another local playlist?
**3.**. Why can't I see my locally stored [assuming they are stored locally] Subscriptions without a network connection?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
1. It's not needed, but creating a playlist without being able to add videos to it doesn't make sense.
2. Because the video info needs to get fetched/updated.
3. Because the feed is generated by Piped, only the channel IDs are stored locally.
