### ISSUE TITLE
Google Cast output switcher

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#2386]
### Describe your suggested feature

I don't know if it uses proprietary software, but Android 13 (beta) supports Google Cast devices in the media output switcher (audio only, not a stream to Chromecast implementation), but it has to be supportet by each app.
I don't want this feature implemented asap, more like a placeholder for when the feature is official and ready (One UI 5.0 already has it in the official changelogs, but it doesn't work yet).

for more context:
https://9to5google.com/2022/12/12/android-13-chromecast-output-switcher/
https://www.androidpolice.com/youtube-music-android-13-output-switcher-cast-devices/
https://www.googlewatchblog.de/2022/12/android13-google-cast-audiowechsler/

### Other details

Related to #799.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
At least I wasn't able to find any developer API to interact with it, so I neither think it's a free dependency nor really supported across different ROMs.

**Comment by xIUPITERx** [comment]
Maybe they will come when the feature is fully released.

**Comment by Bnyro** [comment]
Maybe we should shift that discussion until there is support and documentation for it instead of worrying about it now?

**Comment by Bnyro** [comment]
Or just discuss it under #799 then as it's pretty similar to that issue.
