### ISSUE TITLE
Place the search bar at the very bottom of the player.

### ISSUE THREAD

**Issue by Fidannyan** [libre-tube/LibreTube#2387]
### Describe your suggested feature

Change the size and position of the search bar.Because it is not in the right place in the player.

![Screenshot_20221216-111530_YouTube](https://user-images.githubusercontent.com/120574401/208044124-91a36b9a-6c5d-4327-bfd8-fdadf40a3838.jpg)
![Screenshot_20221216-111140_LibreTube Debug](https://user-images.githubusercontent.com/120574401/208044129-2da814ce-e1c2-4b21-8ff4-ef78ba2cff85.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I will fill out all of the requested information in this form.

**Comment by rozari0** [comment]
I don't see any search bar in your screenshot.

**Comment by Fidannyan** [comment]
![Screenshot_20221216-112314_LibreTube Debug](https://user-images.githubusercontent.com/120574401/208045128-a46fb51a-169f-44f4-82c4-252334e0c835.jpg)

**Comment by Fidannyan** [comment]
The search bar should be at the bottom, because it takes up too much space at the top.

**Comment by rozari0** [comment]
That's progress bar.

> The search bar should be at the bottom, because it takes up too much space at the top.

Why exactly? Progressbar hide automatically. 
Newpipe's progressbar looks same.

**Comment by Fidannyan** [comment]
This place is not correct at all, because the large volume below allows better movement.

**Comment by Bnyro** [comment]
True, there are no arguments for changing it ...
