### ISSUE TITLE
All caught up - Even though not seen the new Videos

### ISSUE THREAD

**Issue by RMStyle** [libre-tube/LibreTube#2388]
### Steps to reproduce

1. Subscribe to some channels
2. Watch Videos via the "Subscriptions"-Tab
3. Open the App, but don't watch new videos
4. Close the App

Result: Sometimes, the unseen videos that were present in 3. will now be recognized as seen and the check mark with "You're all caught up"

### Expected behavior

The Checkmark should only appear after videos have been watched.

### Actual behavior

The checkmark sometimes appears after videos that have not been watched.

### LibreTube version

0.9.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
All caught up only indicates which new videos got added to your feed since you watched your subscriptions tab the last time, it's not related to which videos you actually watched actively.
