### ISSUE TITLE
Download formats are repeated.

### ISSUE THREAD

**Issue by Fidannyan** [libre-tube/LibreTube#2392]
### Steps to reproduce

No

### Expected behavior

No need to repeat.

### Actual behavior

![Screenshot_20221216-154600_LibreTube Debug](https://user-images.githubusercontent.com/120574401/208091845-7427496d-91f7-4ceb-ba0b-71efefd6b649.jpg)
![Screenshot_20221216-154533_LibreTube Debug](https://user-images.githubusercontent.com/120574401/208091854-deb228bc-7308-4f55-88bb-22acad71e8ef.jpg)

### LibreTube version

0.9.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Fidannyan** [comment]
360p MPEG-4 and 720p MPEG-4  has been rewritten

**Comment by Bnyro** [comment]
Different formats behave differently, don't get the issue.
