### ISSUE TITLE
Duration of videos without sponsor segments 

### ISSUE THREAD

**Issue by GET100PERCENT** [libre-tube/LibreTube#2401]
### Describe your suggested feature

It will be more informative if libretube shows the duration of the videos excluding the sum of total durations of sponsor segments right to the original duration within the parentheses.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
In the video preview or next to the player seek bar?

**Comment by GET100PERCENT** [comment]
In both.
![20221216_213514](https://user-images.githubusercontent.com/116144024/208139934-39a512fb-08fe-4e1e-a55c-5862f24ac7d6.jpg)
![20221216_213352](https://user-images.githubusercontent.com/116144024/208139944-6cc3b812-ace4-4ba0-837b-6e6de2d2ee9c.jpg)

**Comment by Bnyro** [comment]
It's impossible for the preview as we would need to make one separate API call per previewed video to access the sponsor segments. For the player I don't really see a way to make it look at least somewhat good ...

**Comment by GET100PERCENT** [comment]
Can't the original duration be moved to the right side of the player followed by this(the duration with out sponsor segments) just like YouTube Vanced had done.

**Comment by Bnyro** [comment]
Any example screenshots?

**Comment by GET100PERCENT** [comment]
![Screenshot_20221216-221201](https://user-images.githubusercontent.com/116144024/208147161-b100a4c8-e19c-4bde-b1b9-00ea48e90ad2.jpg)
I don't have YouTube Vanced anymore.
But you can see in this screenshot that the elapsed time is on the right and the total time (here remaining time on the right side of the player).
I want the total time followed by the duration without segments [eg. here 7:33 (xx:yy)], where xx:yy is the duration without segments.

**Comment by GET100PERCENT** [comment]
![20221217_141435](https://user-images.githubusercontent.com/116144024/208233918-b80b28bd-3d20-4233-8c37-fe42bf6b1557.jpg)

**Comment by GET100PERCENT** [comment]
![43372722-f978-45b9-b42b-08c9fa50e209](https://user-images.githubusercontent.com/116144024/208234829-f7b7838a-0f8c-42ee-984a-1388cf34329e.jpg)
This screenshot has been taken from the below link https://www.youtube.com/watch?v=-k4gbqJmFYc&t=18 (from the official YouTube channel of YouTube Vanced).
