### ISSUE TITLE
[F-R] Import NewPipe Playlists

### ISSUE THREAD

**Issue by RickyM7** [libre-tube/LibreTube#2403]
### Describe your suggested feature

Would be nice if LibreTube can import newpipe's playlists from the newpipe's backup file.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
NewPipe's backup file is only the database and not a json or csv file, right? It's not possible for us to extract data from a NewPipe database, hence I would recommend you to consider asking at the NewPipe repo for support for exporting playlists to a json or csv file so that it's possible for us to parse it.

**Comment by RickyM7** [comment]
> NewPipe's backup file is only the database and not a json or csv file, right? It's not possible for us to extract data from a NewPipe database, hence I would recommend you to consider asking at the NewPipe repo for support for exporting playlists to a json or csv file so that it's possible for us to parse it.

Oh, I got it. Thank you for explaining to me.

**Comment by RickyM7** [comment]
[Simple NewPipe Playlist to Piped Supported Json File](https://rickym7.github.io/meus-estudos-e-testes/projetos/newpipe-playlist-to-piped-json/index.html)

**Comment by FireMasterK** [comment]
> [Simple NewPipe Playlist to Piped Supported Json File](https://rickym7.github.io/meus-estudos-e-testes/projetos/newpipe-playlist-to-piped-json/index.html) 

This link seems to 404 for me 😕

**Comment by RickyM7** [comment]
> > [Simple NewPipe Playlist to Piped Supported Json File](https://rickym7.github.io/meus-estudos-e-testes/projetos/newpipe-playlist-to-piped-json/index.html)
> 
> This link seems to 404 for me confused

I'm sorry, i'll fix an issue and reupload it.

**Comment by RickyM7** [comment]
> > [Simple NewPipe Playlist to Piped Supported Json File](https://rickym7.github.io/meus-estudos-e-testes/projetos/newpipe-playlist-to-piped-json/index.html)
> 
> This link seems to 404 for me confused

Done! It took me a long time because I was learning to use the GH CLI, hahaha
