### ISSUE TITLE
"Network error" when adding a video to a playlist

### ISSUE THREAD

**Issue by berryes** [libre-tube/LibreTube#2404]
### Steps to reproduce

1. Play a video
2. Try to add it to a playlist

### Expected behavior

The video should be put inside the playlist.

### Actual behavior

Pop up on the bottom of the screen
"Network error"
![ezgif-3-9846c2ac8b](https://user-images.githubusercontent.com/73071529/208184557-196e0817-0cdf-4e26-bda2-3a50890db6fc.gif)

### LibreTube version

0.9.1

### Android version

Android 12

### Other details

About my phone:
Model: JNY-LX1
EMUI: ver 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Is that still an issue? I guess it's been a backend issue.

**Comment by berryes** [comment]
Yes its still present. Not sure it migth be my instance thats causing it. I'll try it with another one

**Comment by Bnyro** [comment]
You're logged in?

**Comment by berryes** [comment]
Created a new account on a another instance, works fine. Maybe I should update mine then. Because it seems like thats whats cousing the problem.
