### ISSUE TITLE
Lag When Opening Subscriptions List

### ISSUE THREAD

**Issue by RickyM7** [libre-tube/LibreTube#2405]
### Steps to reproduce

1. Go to the Subscriptions Tab
2. Open the Subscriptions List

### Expected behavior

The list should be open without lag.

### Actual behavior

If you have many subscriptions the list takes time to open.

### LibreTube version

0.9.1

### Android version

Android 11 (ArrowOS)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by RickyM7** [comment]
> Can't reproduce here (25 channels) The loading time for me rather exists with subscription timeline itself. Then the sub list opens fairly quickly.

I've 180+ channels here. The lag is not that big, but it exists.

**Comment by RickyM7** [comment]
I got it, but the lag occours after the content is loaded.

**Comment by Bnyro** [comment]
Loading times are not a lag, storing the subscriptions inside the app instead of reloading them is not a good idea in term of UX when the Piped account is being used in the browser or on other devices simultaneously.
