### ISSUE TITLE
Can't see the video in the channel topic

### ISSUE THREAD

**Issue by Wjxfi** [libre-tube/LibreTube#2407]
It just doesn't see the video in the channel topic

playlists only

proof:
https://www.youtube.com/channel/UCO0x8dKCy9Je6aPg2Q4cbKw

https://www.youtube.com/channel/UCHf0OITw-dknDkWTn90-6hA

### LibreTube version

0.9.1

### Android version

android 13

**Comment by Bnyro** [comment]
That's a NewPipe extractor issue.
