### ISSUE TITLE
Download from timestamp to timestamp

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#2419]
### Describe your suggested feature

I would like to download parts of a youtube video.

### Other details

-

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
1. Please use the template
2. Not possible
