### ISSUE TITLE
Subscription page reload delay.

### ISSUE THREAD

**Issue by muhammadabdullah007git** [libre-tube/LibreTube#2421]
### Describe your suggested feature

It would be great if there would be option to delay reload of subscription page. Now it reloads immediately after clicking every time on subscription page button on navigation bar. It would be great if it don't update immediately. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Settings -> Advanced -> Load feed in background
