### ISSUE TITLE
Missing Fullscreen icon?

### ISSUE THREAD

**Issue by xGrim69** [libre-tube/LibreTube#2422]
### Steps to reproduce

1. Open Libretube
2. Click on any video
3. Single tap the player to see player buttons
4. Find fullscreen icon at the bottom right
5. Missing icon

### Expected behavior

The player must show the fullscreen icon

### Actual behavior

The said icon is missing

### LibreTube version

0.9.1

### Android version

Android 8.1

### Other details

Screenshot picture of proof
![IMG_20221217_221533](https://user-images.githubusercontent.com/106541892/208246416-40fca7d1-12f6-4355-93ad-2a730cac8e3f.JPG)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I assume you have the "Auto fullscreen" option in the player settings enabled? It's not possible to have both at the same time, you can find more details in some already closed issues.
