### ISSUE TITLE
Comments sheet sometimes exceeds the maximum height

### ISSUE THREAD

**Issue by MatsG23** [libre-tube/LibreTube#2425]
### Steps to reproduce

1. Open the following video in LibreTube: https://piped.video/watch?v=3PcUzzpkHMk
2. Open the comments sheet
3. Click on the first comment with 21 replies 

### Expected behavior

The comments sheet should unfold the replies and stay at the same size.

### Actual behavior

The comments sheet somehow gets fullscreen.
I have no clue what could be causing this. Probably the huge amount of replies and the fact that it is the first comment??

### LibreTube version

0.9.1

### Android version

Android 13 QPR1

### Other details

I use GrapheneOS.
If you have issues reproducing this, I am open to sending a video or logs.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Hmm, it seems to keep its fixed height but move itself to the top instead of staying at the bottom.

**Comment by xIUPITERx** [comment]
https://user-images.githubusercontent.com/97352673/210430982-62b5a28c-8fd9-4fa2-96a6-3272f64ceab1.mp4

**Comment by E0697** [comment]
I can still reproduce this in 0.11.1
Anyone else?

**Comment by E0697** [comment]
I see. Thanks for the clarification.
