### ISSUE TITLE
Linked info and videos in the player

### ISSUE THREAD

**Issue by MatsG23** [libre-tube/LibreTube#2426]
### Describe your suggested feature

It would be very cool if you could see what a YouTuber what information (those short info buttons in the player at the corner) or videos (end card with additional, clickable videos often fitting to the current video) is linking.

### Other details

I am unsure if Piped supports this.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's currently not supported by Piped, I think the NewPipe Extractor and thus NewPipe don't support it either, please feel free to open an issue at the extractor repo.
