### ISSUE TITLE
Picture in picture mode for Android 7 

### ISSUE THREAD

**Issue by GET100PERCENT** [libre-tube/LibreTube#2430]
### Describe your suggested feature

It will be very useful if libretube provides picture in picture mode for Android 7 Nougat, so that the users can watch the videos while doing some other work on their phones.

Libretube provides picture in picture mode for higher versions of Android, So why not for Android 7.

Newpipe and VLC provide picture in picture mode for Android 7 Nougat.

### Other details

Newpipe and VLC provide picture in picture mode for Android 7 Nougat.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It's not supported for lower versions than Android 8, that means that we would need to code a completely new way of floating windows for Android versions that honestly nobody uses anymore and which are deprecated since years. For the given reasons: not planned.
