### ISSUE TITLE
Liking videos

### ISSUE THREAD

**Issue by SpyderThingy** [libre-tube/LibreTube#2431]
### Describe your suggested feature

Having liked videos (or a playlist of videos you have "liked" or "disliked") would be a great addition or a way to import YT history to LibreTube.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
Having dedicated playlist for favorits and a watchlist would be preety cool.

**Comment by Bnyro** [comment]
I'd recommend you create playlists for that, there are no plans to add something like that as it already exist in form of user playlists. Import of the YT history is not planned either.
