### ISSUE TITLE
Remove the black layer on the video while reading comments 

### ISSUE THREAD

**Issue by GET100PERCENT** [libre-tube/LibreTube#2433]
### Steps to reproduce

1. Open any video.
2.  Press the comment button.

### Expected behavior

The video should play as usual.

### Actual behavior

A black layer on the player comes which hinders the watching as with the black layer the videos are not clearly visible.

### LibreTube version

9.1

### Android version

Android 7.1 Nougat

### Other details

![Screenshot_20221218-104346](https://user-images.githubusercontent.com/116144024/208282593-da4832ee-2dfe-4da6-8001-ae572a194e50.jpg)
![Screenshot_20221218-104339](https://user-images.githubusercontent.com/116144024/208282594-6790fb8b-873d-4586-950f-9a6589ee612a.jpg)
In the two photos the difference can be seen.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
To add to this, if you try to pause the video the comments close, because you clicked outside the sheet.

Hide the round corners if the the sheet is maximised under the video.



Save there you the last reading position after you closed the comments sheet.

**Comment by Bnyro** [comment]
The bottom sheet behavior can't be changed in that terms as we use the prebuilt components from the Material 3 library.

**Comment by xIUPITERx** [comment]
But then I am of the opinion to continue the old comment view as a legacy component (like the legacy subscription view ...) and to implement the full screen sheet again. 

If this is another one of those petty requests, I can understand and please ignore this message.

**Comment by xIUPITERx** [comment]
> But then I am of the opinion to continue the old comment view as a legacy component

Because now the people who wanted this feature are not satisfied with it either.
