### ISSUE TITLE
Scrolling down the playlists refreshes the library contents

### ISSUE THREAD

**Issue by GET100PERCENT** [libre-tube/LibreTube#2434]
### Steps to reproduce

1. Make a number of playlists (local playlists)
2. Swipe up on the playlist section , it will be scrolled from top to bottom
3. Now swipe down 

### Expected behavior

It should scroll the playlists from bottom to top.

### Actual behavior

Instead of scrolling the playlists from bottom to top, it refreshes the library contents.

### LibreTube version

9.1

### Android version

Android 7.1 Nougat

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Gabs-Unk** [comment]
Confirmed! same 9.1 version, android 10,
When scroll down the app acts like refreshing and can't scroll from the bottom to top "unless you scroll from top to bottom first and keep holding to scroll to top again".
