### ISSUE TITLE
Tablet mini player.

### ISSUE THREAD

**Issue by Qersoqa** [libre-tube/LibreTube#2436]
### Describe your suggested feature

Option to use tablet mini player.

### Other details

https://user-images.githubusercontent.com/120909960/208289367-632db81c-ad81-4872-b60f-613988db4851.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Dupe

**Comment by xIUPITERx** [comment]
You mean activate pip without leaving the app?
