### ISSUE TITLE
Show `Seekbar Thumb` in portrait mode

### ISSUE THREAD

**Issue by vedxp** [libre-tube/LibreTube#2437]
### Describe your suggested feature

Until version `0.9.1`,  the seekbar thumb was there as expected, but after the new update (0.9.1), the latter has gone in portrait mode.

It's quite hard to notice the video progress without the seekbar thumb, reverting it back as it was before version `0.9.1` would be better regarding UX :)

### Seekbar Thumb present in landscape mode
> ![Screenshot_2022-12-17-20-18-13-81_54f92cd6866f5233ab0db4392b806878~2](https://user-images.githubusercontent.com/87353286/208298780-4d0934e1-5aa1-4876-8e3e-06a8f9ba7a90.jpg)

### Seekbar Thumb absent in portrait mode
> ![Screenshot_2022-12-17-20-18-07-35_54f92cd6866f5233ab0db4392b806878~2](https://user-images.githubusercontent.com/87353286/208298793-19eeaf13-5fac-4d31-bb70-1bb052d5b49c.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't either, it's not an intended behavior.

**Comment by Gabs-Unk** [comment]
Same here.

**Comment by Bnyro** [comment]
I guess it's a bug caused by the ExoPlayer update, at least there's no way for us to really change it.

**Comment by NaN-Sz** [comment]
The same here...
