### ISSUE TITLE
Support on Android 4.2.2

### ISSUE THREAD

**Issue by TheMercenary333** [libre-tube/LibreTube#2438]
### Describe your suggested feature

Please bring compatibility with android 4.2.2 (API 17)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We're using Retrofit which requires Android 5, hence not possible.
