### ISSUE TITLE
speed test all instances

### ISSUE THREAD

**Issue by ydqsbfsyi** [libre-tube/LibreTube#2440]
### Describe your suggested feature

In some regions, internet connection abroad is bad and only one or two instances work well, problem is, which one works well often changes. When it changes, I'll have to try at least half of all instances to find a working one( I find CDN or not doesn't influence much to speed), if lucky, that'll hold for a week. 
I've been wondering, how about adding a speed test function? That'll be so handy.
There does not have to be a sorting after speed test, since there aren't that much instances, the result should be clear at a glance.
Please consider.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FireMasterK** [comment]
I wouldn't say I like this idea since there's no sure-shot way/method to measure an instance's performance.

**Comment by Bnyro** [comment]
I agree with Kavin, all we could do is check whether the health check passes and the host is reachable but that doesn't guarantee the instance is really working for you and/or fast. I'd recommend deciding based on the instance list of the Piped wiki, depending on the region as well as the user count (more users might be a sign for the instance being stable although that doesn't always have to be the case)

**Comment by ydqsbfsyi** [comment]
@FireMasterK @Bnyro Thanks, guys, I appreciate it.
