### ISSUE TITLE
sponsor block segment markers are less precise 

### ISSUE THREAD

**Issue by Gamefire238** [libre-tube/LibreTube#2441]
### Steps to reproduce

![IMG_20221219_162039](https://user-images.githubusercontent.com/78879425/208380601-f98df168-051f-4de2-b47d-9e99e6eeb294.jpg)
the sponsor block color segment looks imprecise and looks higher than the timeline

### Expected behavior

.

### Actual behavior

.

### LibreTube version

0.9.1

### Android version

android 11, vivo y12

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
What exactly is the problem?

**Comment by Gamefire238** [comment]
the problem is this
![IMG_20221220_075757](https://user-images.githubusercontent.com/78879425/208551225-7f568cdc-95e4-4c6a-9b91-e21c0d7dc24d.jpg)

I made it because the screenshot above is not clear enough.

**Comment by Bnyro** [comment]
Seems to depend on the device density.

**Comment by xIUPITERx** [comment]
![Screenshot_20221221_111218_LibreTube Debug.png](https://user-images.githubusercontent.com/97352673/208880240-58dd1ebc-9e6d-4bbf-b152-94d82afcf7b6.png)
On my Samsung A52s I can see it, but even though I know about it, I hardly notice it in everyday life.

**Comment by xIUPITERx** [comment]
https://user-images.githubusercontent.com/97352673/212500847-e50c764a-b343-418d-90be-fcbf6e8daf52.mp4

The position of the marker is now wrong, it starts too far to the right and is too wide.

![Screenshot_20230114_234220_Video Player.png](https://user-images.githubusercontent.com/97352673/212500845-052c039a-e21b-422d-a0d2-2aa2cda29301.png)

The marker is also minimally too deep, but you can hardly see it.
