### ISSUE TITLE
Reset the Sponorblock button

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#2458]
### Describe your suggested feature

Reset the SponsorBlock button after each video so that it can be used properly in the next video.
Until now, the heart symbol is displayed in the next video, although SponsorBlock is activated again.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
In fact the icons were just swapped since #2271 which made it feel like it doesn't work properly although it does.

**Comment by xIUPITERx** [comment]
SponsorBlock is still deactivated in the next video, although the button is now displayed correctly.

**Comment by Bnyro** [comment]
Yes, that's intended, SponsorBlock is meant to stay disabled for the whole session/queue when disabled temporarily once.

**Comment by xIUPITERx** [comment]
Didn't know that.

Depending on whether #1810 is implimented, it would be cool to activate SponorBlock again after the playlist ends and the featured section starts
