### ISSUE TITLE
Shorts on LibreTube

### ISSUE THREAD

**Issue by TBNRDev** [libre-tube/LibreTube#2460]
### Describe your suggested feature

If LibreTube is an alternative for Vanced/... then the app should have YT Shorts, it would be cool with no ads right?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
No API/extractor support.

**Comment by Bnyro** [comment]
Anyways LibreTube is not meant to be an alternative to Vanced.
