### ISSUE TITLE
Slow download speeds

### ISSUE THREAD

**Issue by pawa2401** [libre-tube/LibreTube#2468]
### Steps to reproduce

1. Download any video's audio

### Expected behavior

Should download quickly

### Actual behavior

The download speed is only ~30kb/s, no matter if it's downloaded with LTE or WiFi.

### LibreTube version

0.9.1

### Android version

Android 10, MIUI 12

### Other details

I haven't tested this with videos. But the audio download speeds are painfully slow.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Fyi, in order to get better speed we would need to write our own download manager and use multiple parallel range requests.

**Comment by Bnyro** [comment]
resolved by #2469
