### ISSUE TITLE
Autoplay doesn't work when screen is off unless playing from a playlist

### ISSUE THREAD

**Issue by terminal-cs** [libre-tube/LibreTube#2470]
### Steps to reproduce

1. Play a video
2. Turn off device
3. See results

### Expected behavior

Videos should continue to play if autoplay is enabled

### Actual behavior

Video pauses at the end and nothing happens.

### LibreTube version

0.9.1

### Android version

Android 12L

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Gabs-Unk** [comment]
I tried but can't reproduce
android 10 (aosp)
version: 0.9.1 (latest)
even enabling pip option or disabling it still working for me (normal videos or playlists)

**Comment by terminal-cs** [comment]
> I tried but can't reproduce android 10 (aosp) version: 0.9.1 (latest) even enabling pip option or disabling it still working for me (normal videos or playlists)

Might be an issue with my crappy device rom, there are no other alternatives for it and the manufacturer has a ton of bugs that they takes months to fix

**Comment by Bnyro** [comment]
Can't reproduce either.
Please make sure to disable all battery optimization stuff, that's the only thing that might improve its behavior.
