### ISSUE TITLE
Lower used AGP plugin version

### ISSUE THREAD

**Issue by MatsG23** [libre-tube/LibreTube#2474]
### Describe your suggested feature

You are currently using Android Gradle Plugin (AGP) `7.4.0-rc02` in the project. This version of the plugin is not compatible with the current, stable release version of Android Studio. I suggest that you lower the version of AGP to the latest compatible version for the stable release (Dolphin right now -> 7.3.1). This makes it easier for contributors to this project because they must not switch to a less stable release channel of Android Studio and potentially experience bugs.

### Other details

See compatability notes [here](https://developer.android.com/studio/releases/gradle-plugin#android_gradle_plugin_and_android_studio_compatibility).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The AGP version 7.3.1 got released more than a year ago so in fact it is outdated (although the current Android Studio release doesn't support it). In the AUR, there's the `android-studio-beta` package (version: Electric Eel), which is compatible with the AGP 7.4.0 and I'm pretty sure other distros allow you to use the beta version of Android Studio as well.

**Comment by Bnyro** [comment]
@FireMasterK @Kruna1Pate1 opinions?

**Comment by Kruna1Pate1** [comment]
I think we can stick with 7.4.0 since beta version is supporting it. When i faced this issue i changed version locally (because probably we don't have 7.4.0 specific usage) which can be used as workaround for time being.
