### ISSUE TITLE
Capital letters are sorted before lowercase in subscriptions

### ISSUE THREAD

**Issue by CrazyStevenz** [libre-tube/LibreTube#248]
### Steps to reproduce

1. Subscribe to a channel starting with a capital letter (Vsauce).
2. Subscribe to a channel with only lowercase letters (bill wurtz).
3. Expand the subscription list.

### Expected behavior

Capital and lowercase letter should be treated the same when sorting.

### Actual behavior

Capital letters are sorted before lowercase ones.

![image](https://user-images.githubusercontent.com/40207026/169139002-c8de7e92-939c-4d1e-9563-d41e3d5ec955.png)

### LibreTube version

0.2.7

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That seems to be a Piped issue since they are in the wrong order on piped.kavin.rocks too

**Comment by Bnyro** [comment]
closing because it's a piped issue
