### ISSUE TITLE
[Android TV] navigation via remote-control (has some benefits for accessibility/ease-of-use as well).

### ISSUE THREAD

**Issue by ghost** [libre-tube/LibreTube#2487]
### Steps to reproduce / Expected behavior

navigate via smart-TV's remote-control. at least a bit..

### Actual behavior

must use USB mouse for anything.

### LibreTube version

action's artifact bleeding edge to current date

### Android version

Android 12

### Other details

Ps.
I know Android TV (I.E. touchless-screen),  
isn't an officially targeted platform,  
..but maybe in the future..  

<hr/>

https://developer.android.com/training/tv/start/navigation

<sub>

<table>
<thead>
  <tr>
     <th>it doesn't look like 100% top navigation</th>
     <th>nor 100% left navigation (which I personally prefer)</th>
   </tr>
</thead>
<tbody>
  <tr>
     <td><img src="https://developer.android.com/static/training/tv/images/tv-nav-top.png" width="200"/></td>
     <td><img src="https://developer.android.com/static/training/tv/images/tv-nav-left.png" width="200" /></td>
   </tr>
</tbody>
</table>

</sub>

note (..to self): in additional to navigation route,  
it is also very important to provide highlighting of the currently active  
as well as currently focused elements, it helps to make d-pad movement  
much more clear (a lot of apps simply ignore it..).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
As you already said, Android TV isn't a target platform and thus there are no plans to spend efforts into it. However, I'll leave the issue open for now if an external contributor wants to have a look at it.

**Comment by samip5** [comment]
I'm willing to offer a bounty of 50€ to anyone who gets proper Android TV navigation implemented using the remote alone (as in w/o a USB mouse). :)

**Comment by Johnnii360** [comment]
I join this feature request. Also want this. I don't want to use NewPipe or SmartTube. I want LibreTube on my Android TV as well! :)

**Comment by amirbokaei** [comment]
I have the same problem and I'm really looking forward to this feature !

**Comment by mdbraber** [comment]
@cbiere you might want to check out https://github.com/libre-tube/LibreTube/issues/6978
