### ISSUE TITLE
Sometimes Commentary scroll down not possible

### ISSUE THREAD

**Issue by HomemadeAdvanced** [libre-tube/LibreTube#2488]
### Steps to reproduce

1. Open Video in LibreTube https://piped.adminforge.de/watch?v=kxbtz7J0pYQ
2. Tab on comment
3. Scroll down

### Expected behavior

Scroll down till the end of the comments.

### Actual behavior

It is not possible to scroll down till the end like there is an invisible barrier.

### LibreTube version

0.9.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
Can confirm, in the linked video the last 2 comments are not loaded.
