### ISSUE TITLE
Search filters

### ISSUE THREAD

**Issue by HomemadeAdvanced** [libre-tube/LibreTube#2492]
### Describe your suggested feature

Possibilty to filter search results like in YT.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Requires NewPipe Extractor changes.
