### ISSUE TITLE
Age Rating Setting

### ISSUE THREAD

**Issue by HomemadeAdvanced** [libre-tube/LibreTube#2493]
### Describe your suggested feature

Setting to enable or disable circumvention of age rating like in NewPipe

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Requires API changes.
