### ISSUE TITLE
Startpage endless scroll and suggestion enhancement

### ISSUE THREAD

**Issue by HomemadeAdvanced** [libre-tube/LibreTube#2495]
### Describe your suggested feature

- There should be the possibility of unlimited scrolling on the home page
- The home page should be more customizable regarding which elements should be seen there (e.g. no bookmarks)
- The start page should be more customized to your own subscriptions and search results

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
For only seeing specific parts (e.g. subscriptions) you should use the dedicated tabs for it instead of the home page (Settings -> Appearance -> Navigation Bar -> Order)
