### ISSUE TITLE
Watch Later list

### ISSUE THREAD

**Issue by HomemadeAdvanced** [libre-tube/LibreTube#2496]
### Describe your suggested feature

Possibility to add a Video to 'Watch Later' (predefined)

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Dupe of #1710
