### ISSUE TITLE
German date

### ISSUE THREAD

**Issue by HomemadeAdvanced** [libre-tube/LibreTube#2497]
### Describe your suggested feature

The German date should be written the other way round. (DD/MM/YYYY)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
In fact it should be DD.MM.YYYY, but we would probably need to depend on a third party library for it as we're currently using the Java inbuilt methods for it which don't seem to be localized.
