### ISSUE TITLE
Mark if the publisher of the video has commented or stared the comment

### ISSUE THREAD

**Issue by HomemadeAdvanced** [libre-tube/LibreTube#2498]
### Describe your suggested feature

Shows before clicking on a comment if the publisher has commented on this comment or has stared a comment.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not possible without changes in the NewPipe Extractor.
