### ISSUE TITLE
Possibility to report a sponsor element

### ISSUE THREAD

**Issue by HomemadeAdvanced** [libre-tube/LibreTube#2499]
### Describe your suggested feature

Possibility to report a sponsor element

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please use the template properly!
