### ISSUE TITLE
Possibility to shuffle playlists

### ISSUE THREAD

**Issue by HomemadeAdvanced** [libre-tube/LibreTube#2500]
### Describe your suggested feature

Possibility to shuffle playlists

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please use the issue templates properly.

**Comment by xIUPITERx** [comment]
And dupe of #2213
