### ISSUE TITLE
expanded comment

### ISSUE THREAD

**Issue by HomemadeAdvanced** [libre-tube/LibreTube#2501]
### Describe your suggested feature

visual marking of expanded comment: tree structure, colored or popup

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please use the issue templates properly.

**Comment by HomemadeAdvanced** [comment]
> Please use the issue templates properly.

Sorry, I don't do this very often. What should I add? I thought it was understandable. I meant that it would be a cool feature to have visual feedback when you click on a comment and now the comments related to that comment are visually highlighted.

**Comment by Bnyro** [comment]
A good issue should contain
- a description of the suggested feature
- arguments why it's useful/needed and eventually why it's currently not working
- examples of apps providing that feature
- optionally design drafts or edited screenshots from the app showing how it could look

**Comment by Bnyro** [comment]
Nobody will spend work (up to hours of their time eventually) in issues that contain only 10 words and don't provide really useful information.
