### ISSUE TITLE
New Download: Receiving Network Error and Can't Register

### ISSUE THREAD

**Issue by mirchimango** [libre-tube/LibreTube#251]
### Steps to reproduce

I have downloaded the app from F-Droid, and am receiving a "Network Error" message once opening the app. When I try to register an account, the same "Network Error" message pops up. I can't use the app. 

### Expected behavior

I should be able to use the app/ register an account.

### Actual behavior

"Network Error" message occurs

### LibreTube version

0.2.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
should work if you have internet connection

**Comment by Chriskinda509** [comment]
Hi, I had the same issue just now. I changed the instance and it worked.

**Comment by lilcheti** [comment]
Please change the instance in the settings

**Comment by mirchimango** [comment]
I changed the instance and it began to work, however the quality of the video thumbnails was really low. I don't know if that's the intended effect, but I decided to use a different app. Thanks for your help.
