### ISSUE TITLE
Ability to pause the video when reading comments

### ISSUE THREAD

**Issue by yhm3ps1jfp76nkd** [libre-tube/LibreTube#2522]
### Describe your suggested feature

Currently you should close the comments sheet to pause the video. Would be nice if you could pause it instantly

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please do so via the notification instead, supporting that is not possible as we're using a bottom sheet which is sort of an overlay over the player.
