### ISSUE TITLE
 Option to add 'Channel page' and 'Playlist page'.

### ISSUE THREAD

**Issue by Lemon-in-Suspense** [libre-tube/LibreTube#2524]
### Describe your suggested feature

Kindly add the  Option to add 'Channel page' and 'Playlist page' (similar feature exists in 'Content of Main page' section of NewPipe app).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't really get what you're suggesting but we're already supporting everything the Piped API allows us to.
