### ISSUE TITLE
Confirm to delete.

### ISSUE THREAD

**Issue by Aqwuty** [libre-tube/LibreTube#2531]
### Describe your suggested feature

Display a confirmation dialog before deleting a video from your watch history and playlist.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Dupe of #2203
