### ISSUE TITLE
Autoplay button

### ISSUE THREAD

**Issue by tampos4** [libre-tube/LibreTube#2539]
### Describe your suggested feature

Can we get an Autoplay on/off button somewhere just like official YouTube app or NewPipe.

It literally takes 3 clicks to turn on/off Autoplay.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I agree with the idea of making it more accessible, but please provide a more detailed description/suggestion of where to place a button for it and how it should look. Not everybody uses NewPipe and the official YouTube app and thus can refer to your sayings.

**Comment by tampos4** [comment]
[NewPipe](https://github.com/TeamNewPipe/NewPipe) 

![IMG_20221229_102844](https://user-images.githubusercontent.com/103326242/209905617-10b620eb-3b42-4036-a0af-177260afc17b.jpg)

**Comment by Aqwuty** [comment]
YouTube 

![Screenshot_20221229-091506_YouTube](https://user-images.githubusercontent.com/121397503/209906433-33c98e37-0c51-4707-8350-19fedcf82cf0.jpg)

**Comment by Aqwuty** [comment]
It is more useful to have it in the player.

**Comment by NeeRaj-2401** [comment]
for in-player buttons
eveyone have their individual choices for one click away buttons
so how about giving them an option to customizable  4/5 option in player and rest under the more options section

![image](https://user-images.githubusercontent.com/88180887/209908489-c6ae176b-1c48-4149-b3fe-bb477ed5d45d.png)
lot of space to fit them

**Comment by NeeRaj-2401** [comment]
<img src="https://user-images.githubusercontent.com/88180887/209908775-38a80846-ea01-4b6d-97e4-638122af6baa.png" width="30%%">

just like we have option for nav bar
similarly **in player buttons** and selected buttons would be visible in player
and rest would be under **more option**

**Comment by repparw** [comment]
I had to check changelog to understand what that switch is. Maybe add the play arrow like in YouTube?

**Comment by Bnyro** [comment]
Agreed, see #2592

**Comment by ThomasLeigh** [comment]
> The option already exists

Do you mean I can disable autoplay completely by enabling data saving mode? I'd like to do this without a need to use data saving because it hides video covers which are important to me.
