### ISSUE TITLE
Theme selection on the home page.

### ISSUE THREAD

**Issue by Aqwuty** [libre-tube/LibreTube#2545]
### Describe your suggested feature

Some phones cannot change the theme from the notification panel.For this purpose, next to the search bar in LibreTube, you can put an option to change the theme. Changing the theme from the settings takes some time.

### Other details

![Screenshot_20221230-212859_LibreTube](https://user-images.githubusercontent.com/121397503/210097657-26396f2d-3b52-4184-b627-62cc4fc5cc11.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not planned.

**Comment by Aqwuty** [comment]
However, this was useful for some devices. I respect your decision.

**Comment by Bnyro** [comment]
There are actions that are way more important that aren't even part of the top bar, why should we add a rather unimportant settings to it then? (rhetorical question)

**Comment by Aqwuty** [comment]
app-armeabi-v7a-release.apk
It should be done for this.
