### ISSUE TITLE
Play videos on the channel.

### ISSUE THREAD

**Issue by Aqwuty** [libre-tube/LibreTube#2547]
### Describe your suggested feature

Option to play all videos belonging to a channel.

### Other details

![Screenshot_20221230-225124_LibreTube](https://user-images.githubusercontent.com/121397503/210103350-1b5d4f09-fdce-49f1-a761-337f9762b24e.jpg)
![Screenshot_20221230-225401_NewPipe](https://user-images.githubusercontent.com/121397503/210103601-af1cdac5-360d-4e8a-a74f-1be132509eee.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Already possible by long-pressing the channel in the search.
