### ISSUE TITLE
Allow Player controls while comments are open

### ISSUE THREAD

**Issue by iAmAGitUser5** [libre-tube/LibreTube#2549]
### Problem

Currently we cannot use player controls when the new comments layout is open. It is a downgrade from the previous comments layout. 

### Solution

A good way to fix this would be chaging focus from comments to player when the player is clicked so we could use the player controls. Clicking the comments again would make the focus go back to comments. The back button would close the comments.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not possible unfortunately, see #2522
