### ISSUE TITLE
Allow vertical fullscreen videos

### ISSUE THREAD

**Issue by Araly** [libre-tube/LibreTube#2553]
### Describe your suggested feature

Currently, if I want to go fullscreen when watching a video, I should turn the app horizontally. When the video is vertical though, that doesn't make sense.

There should be a button or action to make the player go fullscreen, without needing the phone to be vertical or horizontal.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't really get the issue, but you can probably change that behavior at player -> auto-fullscreen and player -> video aspect ratio

**Comment by Araly** [comment]
oh yeah, I looked in the settings previously but I must have missed it somehow. I've found it now, I had to disable the gesture based auto fullscreen, and then I could fullscreen with a button both vertical and horizontal.

Sorry ^^ I'll close this now
