### ISSUE TITLE
Option to filter search

### ISSUE THREAD

**Issue by Gabs-Unk** [libre-tube/LibreTube#2560]
### Describe your suggested feature

It would be interesting to have an option to filter searches by upload date, long or short duration, 4K and etc.

### Other details

![Screenshot_20230102-073320652](https://user-images.githubusercontent.com/87625033/210220200-63bdcff1-a137-4802-a7f8-7f1adfbd50d8.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not possible without changes in the NewPipe Extractor.
