### ISSUE TITLE
Auto Fullscreen on shorts videos

### ISSUE THREAD

**Issue by XelXen** [libre-tube/LibreTube#2564]
### Describe your suggested feature

This issue is similar to #1228 but not a duplicate issue. Right now, Libretube can detect whether a video is a short but does start that short like a usual video. We can use that shorts detection API to auto full-screen the short the user clicks on. This is a quick solution to the portrait videos problem.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Pentaphon** [comment]
I agree this is a must have for auto fullscreen. We already hold our phones in portrait for shorts.

**Comment by Gottarocket** [comment]
I still have issue. Doesnt fullscreen shorts. Need to scroll up to make it fullscreen. Android 12. Pixel device. Grapheneos

**Comment by Bnyro** [comment]
Enable the option in the settings ...

**Comment by Gottarocket** [comment]
Thanks didnt check it. Better keep it on by default because majority will love it to be fullscreen.
