### ISSUE TITLE
Show replies in the comments section

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#2571]
### Describe your suggested feature

Ability to expand a comment by clicking on it to show replies of the comment.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
It's propably more a bug report.

**Comment by NeeRaj-2401** [comment]
> It's propably more a bug report.

It is already implemented? Whats the bug?

**Comment by xIUPITERx** [comment]
It just didn't work
