### ISSUE TITLE
Move current playing video at top when shuffled queue 

### ISSUE THREAD

**Issue by NeeRaj-2401** [libre-tube/LibreTube#2572]
### Steps to reproduce

1. Play any video
2. Go to queue 
3. Skip/view 4,5 videos
4. Shuffle the queue 

### Expected behavior

Current playing video should be on top & rest should be shuffled 

### Actual behavior

Current playing video stays on its position & queue above the video as well as below the video gets shuffled

Hence sometimes upcoming unwatched videos goes above the current one in queue 

https://user-images.githubusercontent.com/88180887/210440667-74618275-4e9e-4ee7-b618-21583340ed3c.mp4

### LibreTube version

0.9.1 

### Android version

Android 12

### Other details

How about we could shuffle only upcoming videos not already watched in queue ....

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't think it makes sense to shuffle videos that already got played too, so now the position of the current video stays the same while only the videos after the current get shuffled.
