### ISSUE TITLE
Small design changes

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#2578]
### Describe your suggested feature

1. Autoplay button
Change the look of the button from a filled in to an outlined design, to fit in with the over icons (and maybe make it smaller).
<details>
<summary>Autoplay button</summary>
<img src="https://user-images.githubusercontent.com/97352673/210537898-c2060662-5f62-4452-8bb3-e8fa0d70935c.png">
<img src="https://cdn-icons-png.flaticon.com/512/6715/6715598.png">
</details>

2. Library filter
Swap the icon and text, so it looks more symmetrical und the icon doesn't move if you change from all to video etc (and maybe make the icon smaller). 
<details>
<summary>Library filter</summary>
<img src="https://user-images.githubusercontent.com/97352673/210540212-5c433385-6876-4738-a418-316ce6cfd9c2.png">
</details>

3. Playlist order
Show the bookmarks above the Playlist, so that everything does not shift when the playlist reloads
<details>
<summary>Playlist order</summary>
<video src="https://user-images.githubusercontent.com/97352673/210543038-3432ecf8-c5dd-4501-a0a7-655e1c1c5011.mp4">
</details>

4. Bookmark option
Add an Bookmark option to the long press menu of a public playlist.
<details>
<summary>Bookmark option</summary>
<img src="https://user-images.githubusercontent.com/97352673/210543944-c5e7cba8-c157-48d3-90df-accde3d09f62.png">
</details>

5. Color Changes
In the monochrome design, I wasn't able to find the color that the "new video indicator" uses and therefore the indicator is barely visible when the subscription tab is selected.
<details>
<summary>Color changes</summary>
<img src="https://user-images.githubusercontent.com/97352673/210546937-c3cfe646-fd10-4f98-9502-023a6eecbce3.png">
</details>

6. Bookmark Font Size (Edit)
enlarge the font of the bookmark title to that of the playlist title
<details>
<summary>Bookmark Font Size</summary>
<img src="https://user-images.githubusercontent.com/97352673/210584711-5cf21652-616d-4fdd-816b-f3e0e75cf3e0.png">
</details>

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I'm not really a fan of 3. since user playlists are way more important than bookmarks, so we should keep them ordered by priority as currently.
2. will be a bit challenging because we'll need to create custom layer drawables for that which is not that straight-forward, I doubt I'll work on that.
Anything else seems reasonable.

**Comment by xIUPITERx** [comment]
Added 6.

**Comment by Bnyro** [comment]
6. can be solved the same way the black circle at the thumbnail gets removed/fixed.

**Comment by Bnyro** [comment]
> I'm not really a fan of 3. myself. Could you save how many playlist you have, and show an empty space until they are loaded, so that the bookmarks are not pushed down when the playlists are loaded?
>
I doubt that's a good idea since they can be changed by the Piped account, the best way for us is probably to leave it as it is :)

**Comment by Bnyro** [comment]
Talking about 2., I think that it looks better if we keep the icons at the right for both options because making it symmetrical "mirrors" the two which makes it look a bit weird to me.

**Comment by Bnyro** [comment]
The notification badge uses color primary now, but we can switch it to any other color you want (as long as it would still look fine with the other themes) (I just realized `colorPrimary` was probably a bad choice as the highlighted navigation item has the same color maybe, not sure, needs to be tested).
The only remaining thing would be the autoplay button, but I'd prefer having a separate issue for it which we leave open for external contributors and not me.

**Comment by xIUPITERx** [comment]
> I doubt that's a good idea since they can be changed by the Piped account

I would say the most people use only the app and if a different number of playlists is loaded fron piped the predefined empty spaces can be overwritten.

**Comment by xIUPITERx** [comment]
> The notification badge uses color primary now, but we can switch it to any other color you want (as long as it would still look fine with the other themes) (I just realized `colorPrimary` was probably a bad choice as the highlighted navigation item has the same color maybe, not sure, needs to be tested).

I'll see if I can find a better color palette for the monochrome theme, but it might take a while.

> The only remaining thing would be the autoplay button, but I'd prefer having a separate issue for it which we leave open for external contributors and not me.

I will open one soon.
