### ISSUE TITLE
Clicking on Subscriptions Icon should Jump to Top

### ISSUE THREAD

**Issue by tampos4** [libre-tube/LibreTube#2590]
### Describe your suggested feature

On the subscriptions tab if I have scrolled enough and I am way down on the Subscriptions page, then clicking on the Subscriptions Icon should take me to the top of the page.

### Other details

It can be implemented for the Home and Trending tabs also.
I don't have any of those tabs enabled, so can't say how that will feel.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by NeeRaj-2401** [comment]
Navigate between tabs once and u will achieve what u want

**Comment by Bnyro** [comment]
The solution I came up with now is a bit hacky but it should work well for most fragments now, at least it does for home page, subscriptions and library (didn't test watch history and downloads).
