### ISSUE TITLE
Autoplay design changes

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#2591]
### Describe your suggested feature

As proposed in #2578, we will discuss the design changes for the Autoplay button here.

> Change the look of the button from a filled in to an outlined design, to fit in with the over icons (and maybe make it smaller).
><details>
><summary>Autoplay button</summary>
><img src="https://user-images.githubusercontent.com/97352673/210537898-c2060662-5f62-4452-8bb3-e8fa0d70935c.png">
><img src="https://cdn-icons-png.flaticon.com/512/6715/6715598.png">
></details>

Problem:
>[ It ] will be a bit challenging because we'll need to create custom layer drawables for that which is not that straight-forward, [ ... ]

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
![Screenshot_20230109_221827_LibreTube Debug.png](https://user-images.githubusercontent.com/97352673/211913443-e467eeec-87ee-4144-b892-47969c510fa6.png)

Thanks for the changes, but now the color of the text is to bright.

**Comment by Bnyro** [comment]
> ![Screenshot_20230109_221827_LibreTube Debug.png](https://user-images.githubusercontent.com/97352673/211913443-e467eeec-87ee-4144-b892-47969c510fa6.png)
> 
Interesting, than I'll need to figure out whether it's possible to change its text color as well!

**Comment by Bnyro** [comment]
Is the contrast better now?

**Comment by xIUPITERx** [comment]
Yes, you can see the number clearly now.
