### ISSUE TITLE
Background playback button

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#2592]
### Describe your suggested feature

Add an option to put the app in the background without closing the player.

Use case:
If you want to use the app for basic music playback there is no other option until #1157 is implemented.

To make it similar to #2292 you could add a long press function on the pip button.
If implemented add a documentation so new user will know about this and #2292.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
What's the difference to pressing the "audio" button in the player menu?

**Comment by xIUPITERx** [comment]
You can reopen the app, rewind and fast forward, watch the music video etc.

**Comment by Bnyro** [comment]
Then why don't you turn off PiP and just leave the app normally? Do you need both available at the same time? :thinking:

**Comment by xIUPITERx** [comment]
Pretty often, music etc. I just want to hear im the Background, but most entertaiment related videos I watch in PiP while surfing the web.

**Comment by Bnyro** [comment]
No plans for that, I'm pretty sure that it's not really useful, apart from that #2682 should be the way to go instead.
