### ISSUE TITLE
Seekbar dot is not appeaering

### ISSUE THREAD

**Issue by d4f5409d** [libre-tube/LibreTube#2604]
### Steps to reproduce

1. Load a video
2. Tap on the player
3. Experience it

### Expected behavior

Wa dot should appear like in previous releases

### Actual behavior

There is only a seekbar, not a dot in it.

### LibreTube version

0.10.0

### Android version

13

### Other details

![IMG_20230106_003032](https://user-images.githubusercontent.com/76624594/210900542-fb5dd4d3-2164-4fcc-8174-97da14a9b9c2.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Gabs-Unk** [comment]
![Screenshot_20230105-210751948.jpg](https://user-images.githubusercontent.com/87625033/210903534-c56f8354-3992-4d08-8a3c-3c17a8f9a131.jpg)

**Comment by Bnyro** [comment]
No clue what it's caused by but it's of course not the intended behavior

**Comment by akano12** [comment]
@Bnyro it seems that this issue doesn't exist in full screen. The seek dot appears in full screen

**Comment by Bnyro** [comment]
> @Bnyro it seems that this issue doesn't exist in full screen. The seek dot appears in full screen
>
True, even when watching a shorts video (fullscreen in portrait mode), which makes it even weirder
