### ISSUE TITLE
Ability to re-order playlists

### ISSUE THREAD

**Issue by Kazevic** [libre-tube/LibreTube#2605]
### Describe your suggested feature

There should be an option to re-order user-created playlists, like on NewPipe.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Piped doesn't support that yet, so an implementation at client side is not possible atm.
