### ISSUE TITLE
Home page cleanup and new interface

### ISSUE THREAD

**Issue by Ilhamiii** [libre-tube/LibreTube#2606]
### Describe your suggested feature

Bookmarks and Playlists section is in the library. It makes no sense to have this option on the home page.Also, we can watch the subscription videos in the subscriptions section. It is not necessary for the videos to appear at the top.However, a new home page can be applied by showing the videos in the viewing history, playlist videos, and subscription videos without sorting, that is, in a mixed manner.

### Other details

In my opinion, this is the best choice for the application interface.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
You can just deactivate the start page and show trends instead.

**Comment by Bnyro** [comment]
The home page exists to give you an overview and quickly navigate to important things, if you don't like it disable and don't use it.
Showing things from watch history (you already watched) doesn't make sense, nor does only showing random playlists.
