### ISSUE TITLE
Add Donate button

### ISSUE THREAD

**Issue by loststone2** [libre-tube/LibreTube#2607]
### Describe your suggested feature

Dear Devs,

I really appreciate the work that has gone into this project and want to support by donating. However, I was unable to find a donation button in the Android app or on GitHub. Is it possible to add a donation button to the app, perhaps under the settings menu, so that users can easily and confidently contribute to the project? Thank you for considering this request.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Hey,
thanks for your interest in supporting the project.
As for now, LibreTube doesn't accept any donations, but if you want to feel free to support the owner of the Piped instance you're using as they have running costs keeping the server up (you can find the donation button of the instance at the bottom of the web frontend, e.g. https://watch.whatever.social).
However, any contributions to LibreTube that are not monetary are very welcome, e.g. helping in the community forums or writing some sort of "documentation" or help for new users to get started, e.g. with importing subscriptions.
Cheers
