### ISSUE TITLE
Home page videos continues loading

### ISSUE THREAD

**Issue by mativiters** [libre-tube/LibreTube#2609]
### Steps to reproduce

On version 0.10.0 (GitHub version), simply open LibreTube.

### Expected behavior

Videos on home paage should be shown, as they did till 0.9.1.

### Actual behavior

Continues loading, not  showing any videos. I have tried with several instances. Although searching works perfectly and you can watch videos you have searcheed for.

### LibreTube version

0.10.0

### Android version

Android 11

### Other details

I must add I had version 0.9.1 from Fdroid, but I downloaded 0.10.0 from GitHub (removed the previous app, did a clean install)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by mativiters** [comment]
Was fixed when I changed region in settings. Though no error was shown.

**Comment by Bnyro** [comment]
Yes, the error message is currently only shown when using the trending tab and not the home tab, should be changed in the future probably.
