### ISSUE TITLE
Mobile data alert.

### ISSUE THREAD

**Issue by Ilhamiii** [libre-tube/LibreTube#2610]
### Describe your suggested feature

Option to set mobile data limit. Stop mobile data usage and alert when specific limit is reached.

### Other details

I think it will be useful for mobile data users.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please use the mobile data limit in the Android settings instead, no plans to implement that into LibreTube as Android supports it natively anyways.
