### ISSUE TITLE
Video not released yet (Premiere)

### ISSUE THREAD

**Issue by Ilhamiii** [libre-tube/LibreTube#2611]
### Describe your suggested feature

Some videos have not been released yet.For example, you can watch them after 7 days. Click on this video to report that it is not live.Tell me when this video will be available. Also notify me when this video is available.
https://youtu.be/F1XY31BKjjs

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
As far as I know the NewPipe Extractor doesn't support premieres properly yet, if so it's not yet been added to Piped, so it'll require changes by one of those projects anyways and can't be added to LibreTube without.
