### ISSUE TITLE
Markings (1x, 2x, 3x, 4x) on the Playback speed dialog box

### ISSUE THREAD

**Issue by tampos4** [libre-tube/LibreTube#2615]
### Describe your suggested feature

There should be markings of 1x, 2x, 3x and 4x on the playback speed dialog box.
And small dots on the 1.5x, 2.5x, 3.5x ( (between the bigger dots of 1x, 2x, 3x and 4x).
![eb601497-8236-414e-a43a-fbd4b7f51654](https://user-images.githubusercontent.com/103326242/211083644-3669fe4a-a380-4180-958b-7c1462c7181b.jpg)

Or to avoid hotchpotch (if any), there can be either dots or number markings.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't think there's a good way for us to add that, we could place an independent layout with all these values added manually above the slider, but that would break as soon as we decide to change the amount of steps as well as not be placed very precise (exactly where the point on the line is).

**Comment by tampos4** [comment]
What about only making some of the dots bigger on some places.

**Comment by Bnyro** [comment]
That's not possible either, they're provided by the Material design library and can't be changed.
