### ISSUE TITLE
Remember scroll position on Library tab

### ISSUE THREAD

**Issue by tampos4** [libre-tube/LibreTube#2628]
### Describe your suggested feature

[ Using without account ]

On the Library tab, when I open any local or bookmarked playlist and come back from it, it scrolls back to the top every time.

It would be helpful if it remembers the last position so that I don't have to scroll every time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Unfortunately that's not possible because we're reloading the playlists each time you navigate back to the library tab.

**Comment by Bnyro** [comment]
Could be possible, however I'm not sure how to deal with it when users use an account and thus it has to get refreshed with an API call.

**Comment by Bnyro** [comment]
Not going to work on this as it's not worth it imo, also see https://github.com/libre-tube/LibreTube/issues/2206#issuecomment-1336186749. Thanks for understanding.
