### ISSUE TITLE
Navigation bar shows while video playing

### ISSUE THREAD

**Issue by demirdegerli** [libre-tube/LibreTube#2631]
### Steps to reproduce

1. Open a video
2. Tap screen
3. The issue
![Screenshot_2023-01-08-13-40-47-314_com github libretube](https://user-images.githubusercontent.com/67432156/211326472-61792dad-ebf0-4659-8e70-c96d5f5abf63.jpg)
![Screenshot_2023-01-08-13-40-54-866_com github libretube](https://user-images.githubusercontent.com/67432156/211326486-60ec5a65-063b-4ef8-bcb7-a08dae5c234d.jpg)

### Expected behavior

Navigation bar should hide.

### Actual behavior

Navigation bar shows.

### LibreTube version

0.10.0

### Android version

Android 11

### Other details

I'm using MIUI Global 12.5.2 Stable and the "gesture navigation bar". It's like the iOS navigation bar. Also, if I touch screen two times (release and hide the OSD), navigation bar hides.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't reproduce.

**Comment by demirdegerli** [comment]
Have you tried tried changing Settings > Home screen > System navigation to gestures?

**Comment by faisalcodes** [comment]
I tried to reproduce your issue but wasn't able to. The gesture guide bar is only shown when the status bar is visible otherwise it automatically hides.

![Screenshot_2023-01-14-19-29-08-59_54f92cd6866f5233ab0db4392b806878.jpg](https://user-images.githubusercontent.com/62804272/212475647-06c4d87b-aa76-4dd3-b1f8-07cacad41276.jpg)

![Screenshot_2023-01-14-19-30-54-07_54f92cd6866f5233ab0db4392b806878.jpg](https://user-images.githubusercontent.com/62804272/212475807-983c9407-aefc-4ae7-8739-70d1f1248ef3.jpg)

**Comment by demirdegerli** [comment]
It's a MIUI bug then. Also what's your MIUI version?

**Comment by faisalcodes** [comment]
> It's a MIUI bug then. Also what's your MIUI version?

I am using ColorOS 12.1

**Comment by Caua77** [comment]
The same thing happens to me, it must have something to do with the gesture navigation

**Comment by demirdegerli** [comment]
@Bnyro, I couldn't find the code which hides the navigation bar. Can you send where is it? I decided debugging it, I don't know Kotlin but if I find a bug I'll inform you to get your help on code side.

**Comment by demirdegerli** [comment]
> @Bnyro, I couldn't find the code which hides the navigation bar. Can you send where is it? I decided debugging it, I don't know Kotlin but if I find a bug I'll inform you to get your help on code side.

I found them
- https://github.com/libre-tube/LibreTube/blob/3a4a0b1809908711ede3f1a019fb003f93fbafce/app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt#L489
- https://github.com/libre-tube/LibreTube/blob/18190c33b07c8b5abf4cc21e07df6a22806a2ce7/app/src/main/java/com/github/libretube/ui/activities/OfflinePlayerActivity.kt#L184
- https://github.com/libre-tube/LibreTube/blob/3a4a0b1809908711ede3f1a019fb003f93fbafce/app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt#L530

**Comment by demirdegerli** [comment]
@Bnyro Also, can you look at this: https://stackoverflow.com/questions/62577645/android-view-view-systemuivisibility-deprecated-what-is-the-replacement

**Comment by demirdegerli** [comment]
@Bnyro, can you implement the hide system UI functions like this? There is `@Suppress("DEPRECATION")` on them and this is a deprecation which affects this type of navigation bars.

We are using SDK 33 so there will be no problem I think.
```kotlin
private fun hideSystemUI() {
    WindowCompat.setDecorFitsSystemWindows(window, false)
    WindowInsetsControllerCompat(window, mainContainer).let { controller ->
        controller.hide(WindowInsetsCompat.Type.systemBars())
        controller.systemBarsBehavior = WindowInsetsControllerCompat.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE
    }
}

private fun showSystemUI() {
    WindowCompat.setDecorFitsSystemWindows(window, true)
    WindowInsetsControllerCompat(window, mainContainer).show(WindowInsetsCompat.Type.systemBars())
}
```

**Comment by Bnyro** [comment]
Just try whether you can make it work locally and create a PR then, using compats should be fine though (or even the best way to guarantee backwards compatibility). 
Honestly I don't have the issue personally so I don't see a reason for myself to try fixing that as I wouldn't even know when it's fixed as the behavior on my phone stays the same ...

**Comment by demirdegerli** [comment]
#2727 solves the issue.
