### ISSUE TITLE
Determine "watched" state of a video based on SponsorBlock segments

### ISSUE THREAD

**Issue by Ojd2000** [libre-tube/LibreTube#2632]
### Describe your suggested feature

With #2464, one can already hide watched videos, but soon after enabling the feature I found a video that remained in my feed due to a long segment I had skipped, although I had watched the entirety of the rest of the video.

After looking at the PR linked above, I reckon that the method to calculate the watched percentage uses the total video duration as the total duration, without considering SB segments (pls correct me if I'm wrong), but for someone who often skips them (manually) it would be more reasonable to exclude them prior to calculation.

### Other details

I guess the segments to skip would be those selected in the settings only.

In manual skipping mode, one may have only partially watched some segments of a video, but I personally don't think keeping track of them (even in some approximate way) would be of great use to the user.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Fetching SponsorBlock segments requires an additional API call. Thus we would need to fetch the SponsorBlock segments for all the videos only for the watch position state and thus cause server load for quite nothing.
(The duration we use is the one returned by the API and is not saved inside the app.)
Therefore not planned.

**Comment by Bnyro** [comment]
Well, I get your idea, but I'm not of the opinion the efforts would be worth it. I don't mind if you want to take the efforts and create a PR, however it's not something that I would consider as needed for every user and really worth investing time into it. Any code contributions are welcome.
