### ISSUE TITLE
Background playback is not useful

### ISSUE THREAD

**Issue by rsssxd** [libre-tube/LibreTube#2635]
### Steps to reproduce

There is no watch or listen history for content that is not played as video and is only played as Background audio.

It is not possible to access the video and comment sections (Home page) for content that only plays audio in the background.

Newpipe accomplishes both of these tasks successfully.

**Comment by Bnyro** [comment]
1. it's not a bug
2. there are other issues for background mode improvements open
3. issue doesn't follow template

**Comment by rsssxd** [comment]
Are there any other bug reports that list the problems I mentioned?

**Comment by rsssxd** [comment]
@Bnyro 

This bug completely blocks access to the content of videos playing in the background. This is very disturbing. Newpipe does this successfully.

Please fix this.
