### ISSUE TITLE
Images are stored as User Data instead of Cache

### ISSUE THREAD

**Issue by ehea617** [libre-tube/LibreTube#2641]
### Steps to reproduce

1. View the storage and cache page for the app in Android's settings to get a baseline
2. Browse around the app to pages that are image heavy. (Endless scrolling down on the Subscriptions feed is a good way to do this)
3. View the storage and cache page for the app in Android's settings again
4. You will notice that the cache used has barely increased while the "User data" has increased by megabytes, indicating images are stored as User Data instead of as cached data

### Expected behavior

Images are stored in cache as they are all temporary files that can be retrieved again from the internet if necessary. Users can clear the cache of the app from Android's settings without erasing any user settings, subscriptions, etc.

### Actual behavior

Images are stored in User Data. To clear cache require wiping the app's persistent storage which would also erase any user settings, subscriptions, etc.

### LibreTube version

0.10.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You're right, thanks for the catch!
