### ISSUE TITLE
background playback for audio mode

### ISSUE THREAD

**Issue by omd10** [libre-tube/LibreTube#2642]
### Steps to reproduce

play audio only does not work as expected

### Expected behavior

Expected behaviour on audio playback should be to always play even in background. After changing related options in settings this happens, but not always, sometimes playback is stopped when navigating out of the application window. Another problem is that video playback does not stop with these options enabled. 

### Actual behavior

Video should stop always in background similar to newpipe.
Audio should always play in backgroud similar to backround in newpipe.

### LibreTube version

0.10.0

### Android version

Android 12

### Other details

Great app, better ui than the rest great apps ;) Thank you!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Should be fixed with #2678 if I got it correctly
