### ISSUE TITLE
Sponsor block improvement

### ISSUE THREAD

**Issue by GET100PERCENT** [libre-tube/LibreTube#2643]
### Describe your suggested feature

Instead of a single option to skip the segments manually, there can be "Skip Manually" and "Autoskip" options for each type of segments.

### Other details

This is required as one can want to skip the sponsors automatically, but the fillers and non music segments manually.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
No plans for that, it would make it complicated although I doubt many users would use it.

**Comment by Bnyro** [comment]
Added in #4021
