### ISSUE TITLE
Watch History does not save.

### ISSUE THREAD

**Issue by Flam3z** [libre-tube/LibreTube#2645]
### Steps to reproduce

-Set any amount of saved videos to your history.
-watch around 5-7 videos for a couple seconds.

### Expected behavior

Being able to scroll down to see all my watched videos.

### Actual behavior

Only 5 videos are saved at a time.

### LibreTube version

0.10.0

### Android version

Android 12

### Other details

The history only saves 5 videos maxed and if i watch anymore it just removes the oldest ones. I've tried setting it to 200 instead of unlimited and the same issue persists.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
They're all saved, unfortunately the PR that added the play all and clear button caused an issue that only the first few are shown. Fixed in debug builds.

**Comment by Flam3z** [comment]
Thank you for the response.
