### ISSUE TITLE
Modify `default video speed` to `save video speed`

### ISSUE THREAD

**Issue by NeeRaj-2401** [libre-tube/LibreTube#2655]
### Describe your suggested feature

The current `default video speed`  option should be modified to work  as `save video speed`

This modified feature will works the same as current option does but some twist i.e. the current video speed(set from player) will be remembered untill its changed (via player only)

As in some scenarios like watching **video songs** or other scenarios like this when i dont want the higher speed and changing speed manually **Everytime** is quite annoying.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't have an opinion on that myself, it'll likely be added if more people agree to the suggestion than the current way, otherwise not.

**Comment by RickyM7** [comment]
Just like NewPipe? I like the NewPipe behavior, so, it's should be nice, but way not have the two options on the app? Maybe an option to choose the expected behavior should be nice.

**Comment by tampos4** [comment]
Former NewPipe user here, I like LT approach.

I normally watch videos at 2x so I have set playback speed in settings to 2x .

Sometimes when I watch any **video song** or any **podcast**, I change it to 1x or 2.5x respectively.

And when I start watching normal videos, it automatically changes the playback speed to original speed (2x) at which I normally watch videos.

**Comment by Bnyro** [comment]
> Just like NewPipe? I like the NewPipe behavior, so, it's should be nice, but way not have the two options on the app? Maybe an option to choose the expected behavior should be nice.
>
I really don't want to add yet another option for such a small thing honestly, we should choose one behavior that will apply for everyone.

**Comment by NeeRaj-2401** [comment]
agreeing with u all, even i rarely hear video songs via libretube.. so in that rare cases small adjustments can be done 👍 thanx :)
