### ISSUE TITLE
Title overlaps description arrow button

### ISSUE THREAD

**Issue by IceDBorn** [libre-tube/LibreTube#266]
### Steps to reproduce

1. Open a video with a long title

### Expected behavior

The title of the video should not overlap the arrow button.

### Actual behavior

The title of the video overlaps the arrow button.

### LibreTube version

Up to date with Git

### Android version

12.1

### Other details

![image](https://user-images.githubusercontent.com/51162078/169544845-e06701cf-82c4-431e-83f8-d47ac31f9a1f.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by IceDBorn** [comment]
The title and the button are not on the same height too.

**Comment by Bnyro** [comment]
Ty for reporting, I'll look into it now

**Comment by IceDBorn** [comment]
[Video Link](https://piped.kavin.rocks/watch?v=stI3UL6_ToU)

**Comment by IceDBorn** [comment]
@Bnyro I don't know where to contact you guys and I'm not sure if you're aware, but accent colors do not work on OLED.

**Comment by Bnyro** [comment]
Yes, I'm aware of it but don't know how it could be fixed since OLED Mode isn't officially supported by Android. So all the accent color stuff is kinda tricky.

**Comment by Bnyro** [comment]
And all the links to contact us are in the reader :)

**Comment by Bnyro** [comment]
The arrow next to the player title should be fixed now
