### ISSUE TITLE
Lirbetube app is not loading my subscriptions and home page 

### ISSUE THREAD

**Issue by Missingtexture-idoit** [libre-tube/LibreTube#2661]
### Steps to reproduce

I have been using lirbetube for a few days when I went back to open it my stuff won't appear I have been using the universal version and somehow its stop working.

### Expected behavior

Shows me with my subscriptions to the people I subscribed to.

### Actual behavior

when reopening the app and a error pops up saying "unrecognized token 'NO': was expecting (JSON string number...)"

### LibreTube version

0.10.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by tokenwizard** [comment]
I'm seeing this today as well. As soon as I launch the app, it shows a toast message at the bottom that says "unrecognized token 'NO': was expecting (JSON string number...)" and repeats several times.
