### ISSUE TITLE
Another way to update subscriptions

### ISSUE THREAD

**Issue by Archeix7** [libre-tube/LibreTube#2664]
### Describe your suggested feature

Is it possible to do something with subscriptions, why their display depends only on instances, can not come up with something that will be normally updated and displayed in the subscriptions, because a lot, a lot of channels are simply useless

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not a client side issue.
You should instead try to come up with suggestions how to improve it on the Piped backend side.

**Comment by Archeix7** [comment]
Yes, yes, I know that it depends on Instances, but why? I have a subscription, and if the video of which is not in subscriptions is displayed in it, this video itself works, it is simply not displayed, so why cannot you come up with a way where the application itself will push this into a display in subscriptions? Does the way to get around this have this?
