### ISSUE TITLE
Strange Behavior When Clicking on Timestamps

### ISSUE THREAD

**Issue by akano12** [libre-tube/LibreTube#2670]
### Steps to reproduce

1. Open a video that has timestamps for different parts. (like [this](https://piped.video/watch?v=l6fVZ0GRbhQ)) 
2.  Click on a timestamp from description 

### Expected behavior

Smooth transition when attempting to play the video from a timestamp

### Actual behavior

https://user-images.githubusercontent.com/50032603/212070703-42c8037e-5a33-4a33-90cf-191fb517f7e8.mp4

### LibreTube version

0.10. 0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The links in the descriptions are just URLs with a timestamp (`<a href="https://youtube.com/watch?v={videoId}&t={timeStamp}">{timeStamp}</a>`), so when clicking them LibreTube loads the link as if you opened it from a browser or something and thus it looks as you described.
In order to improve that, we need to inspect the links in the description and modify the text displayed there to directly load in the current video, should be doable.

**Comment by akano12** [comment]
> The links in the descriptions are just URLs with a timestamp (`<a href="https://youtube.com/watch?v={videoId}&t={timeStamp}">{timeStamp}</a>`), so when clicking them LibreTube loads the link as if you opened it from a browser or something and thus it looks as you described.
> In order to improve that, we need to inspect the links in the description and modify the text displayed there to directly load in the current video, should be doable.

I understand what's the issue but i couldn't reproduce what i initially wanted to report for some reason.

Basically it's the same issue as above but it was throwing exceptions left and right and then freeze on this screen. 

![Screenshot_20230112-220337_LibreTube.jpg](https://user-images.githubusercontent.com/50032603/212169341-543224bb-ed47-4255-8d27-a6a3833416ce.jpg)

Also what happened to the issue of seekbar dot? Was it fixed? Couldn't find it neither in opened nor in closed issues. 
(using github beta so could be an issue on my side cz it happened before, some issues were missing)

**Comment by Bnyro** [comment]
Good question, I can't find it either anymore. I'm sure I didn't close it yet because it's not fixed, but the issue somehow vanished, very weird :thinking:

**Comment by akano12** [comment]
> Good question, I can't find it either anymore. I'm sure I didn't close it yet because it's not fixed, but the issue somehow vanished, very weird :thinking:

It seems it got deleted, tried opening the link to the issue from github email notifications, leads to nowhere.

https://github.com/libre-tube/LibreTube/issues/2604

**Comment by faisalcodes** [comment]
For me, when I click on a time stamp, it takes me to the official YouTube app at the specific time. 

I may work to fix this issue.

**Comment by Bnyro** [comment]
> For me, when I click on a time stamp, it takes me to the official YouTube app at the specific time.
> 
You may resolve that by enabling some YT links in the Android settings under LibreTube -> Open by Default
> I may work to fix this issue.
That'd be awesome!
