### ISSUE TITLE
Opening youtube link in the app

### ISSUE THREAD

**Issue by HitenBhadra** [libre-tube/LibreTube#2675]
### Describe your suggested feature

If we click youtube link in the app it shouldn't redirect to brower rather show video in the app

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Related: #2670
Apart from that make sure to enable the youtube links in the "open by default" category in your Android settings for LibreTube.
