### ISSUE TITLE
Disable preloading for sponsored segments, preload video after segment

### ISSUE THREAD

**Issue by firefoxlover** [libre-tube/LibreTube#2677]
### Describe your suggested feature

A problem is, that when using sponsorblock, the playback stutters, as the preloaded sponsored segment is skipped and the part after the segment is not preloaded.

A solution would be, to manipulate the preloading somehow, to skip the sponsorblock segment.

### Other details

Only relevant using sponsorblock

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I'm not aware of a way to "manipulate" preloading, the player we're using can only preload the next few seconds but not skip any parts of the video when loading.

**Comment by xIUPITERx** [comment]
If the Piped Extractor itself would cut the Sponsor segments out?
 
That would probably lead to more new problems than it is worth.
