### ISSUE TITLE
Error message at startup

### ISSUE THREAD

**Issue by JavMatz** [libre-tube/LibreTube#2680]
### Steps to reproduce

1. Open app
2. Message automatically shows

![imagen](https://user-images.githubusercontent.com/53586214/212419566-c9703fca-5c25-41a9-b351-cf158560aa69.png)

The message reads:
`Unrecognized token 'No': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false') at [Source:(okhttp3.ResponseBody$BomAwareReader); line: 1, column: 3]`

### Expected behavior

Don't show the message

### Actual behavior

The message is shown

### LibreTube version

0.10.0

### Android version

Android 7.1.2

### Other details

I downloaded the app from F-Droid.

The problem also appears on versions 0.9.1 and 0.9.0.

The message snackbar appears the be rendered multiple times, (always with the same message).

The app works apparently fine despite that error showing up.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's only an issue of the official instance and not an issue of LibreTube, please try using another instance, e.g. kavin.rocks libre.
