### ISSUE TITLE
No videos in the queue in Audio Mode

### ISSUE THREAD

**Issue by tampos4** [libre-tube/LibreTube#2681]
### Steps to reproduce

1. Play any video.
2. Click on Audio.
3. Audio mode opens. Click on the thumbnail to open queue.

### Expected behavior

The queue should show the related videos which were there in Video Mode.

### Actual behavior

The queue is empty.

### LibreTube version

0.10.0 Latest Debug

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by tampos4** [comment]
The queue in Audio mode shows related videos when the Audio mode is opened directly by long pressing on the thumbnail and selecting "Play in the background" option.

**Comment by NeeRaj-2401** [comment]
try 
settings > player > under Queue > toggle "insert related videos" ON

**Comment by NeeRaj-2401** [comment]
was this issue present with queues before the new audio mode ?
