### ISSUE TITLE
An option in Audio mode to go to the Video mode

### ISSUE THREAD

**Issue by tampos4** [libre-tube/LibreTube#2682]
### Describe your suggested feature

There is no way to go back to Video mode from Audio mode.
There should be a button to do that.

As there will be many more changes that will be coming in the Audio mode (i guess) so I really can't think the placement of that button.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Not sure if i correctly understood what you mean. But in case you were talking about returning to video after switching to audio only, all what you have to do is click play (just go back to the video and click play icon from the player).

**Comment by xIUPITERx** [comment]
> Not sure if i correctly understood what you mean. But in case you were talking about returning to video after switching to audio only, all what you have to do is click play (just go back to the video and click play icon from the player).

Are you using the new audio mode in the debug version?

**Comment by akano12** [comment]
> > Not sure if i correctly understood what you mean. But in case you were talking about returning to video after switching to audio only, all what you have to do is click play (just go back to the video and click play icon from the player).
> 
> Are you using the new audio mode in the debug version?

Nope, stable 0.10

**Comment by xIUPITERx** [comment]
There was audio mode added in the latest debug version, where you can't click on the play button to go back.

**Comment by Bnyro** [comment]
I can't think of a placement for that button either, we could make it some sort of hidden action which I like, e.g. when long pressing the title, but probably no user will find that out on their own realistically.

**Comment by xIUPITERx** [comment]
Can't we have some kind of top row?

I mean the queue is already hidden and there is no way to minimize the player to continue searching for videos in the app.

![Screenshot_20230114_113547_Spotify.png](https://user-images.githubusercontent.com/97352673/212467878-2441b956-4d81-4f05-b263-f4619a6ed484.png)

Over apps also show more buttons.

**Comment by xIUPITERx** [comment]
If we have an option to minimize the player, we could hide the navbar and show some buttons there.

**Comment by Bnyro** [comment]
There are no plans to make the music player available as a mini player, the main target of LibreTube is still playing videos.
The best thing is probably to show the buttons for additional actions in a row below the play/pause button as the share button is positioned in the screenshot above.
I think not showing the navbar for the music player makes sense when adding a back button to the top of the fragment, just as at the top left on the screenshot. However, it'll only close it but not start a mini player!

**Comment by xIUPITERx** [comment]
>  it'll only close it but not start a mini player!

Why not use the normal Miniplayer from the video mode?
Without having a Miniplayer you can't search for new videos to add to the queue, etc.

**Comment by Bnyro** [comment]
You can, just dismiss the player fragment, the music continues in the background. You can resume the audio player fragment by clicking the notification.

**Comment by tampos4** [comment]
I think this "a separate player tab [for New Audio Mode]" will make things more complicated and less intuitive for future.

Like what settings (buttons) of the Video Mode will be made available to the Audio Mode.

I'm talking about playback speed button, queue icon, forward and backward buttons, share button [in the Audio Mode] etc. etc.

If someone wants to download that video/audio, then will he have to switch to video mode and then download that video or there will be a download button in Audio mode also.
Same goes for sharing that video.

I'm sure there will be multiple FRs to add these buttons in the New Audio Mode after the release.

**Comment by tampos4** [comment]
Why not change this Video mode itself to Audio mode
![IMG_20230114_180820](https://user-images.githubusercontent.com/103326242/212474114-6ac31004-d702-448c-a7e6-36390e7bca86.jpg)

(NewPipe)
![IMG_20230114_181933](https://user-images.githubusercontent.com/103326242/212474129-7941832b-9cd1-4f3f-8815-9ad5288649ad.jpg)

Which could look like this 
![40da6afa-ca5c-4b25-86c2-8172a4acea07](https://user-images.githubusercontent.com/103326242/212474144-8b7dbbb8-51e6-4e2f-829a-d3d6a4088915.jpg)

**Comment by Bnyro** [comment]
> Why not change this Video mode itself to Audio mode
>
We already have an audio player now so reverting that doesn't make sense.

**Comment by Bnyro** [comment]
If you don't like it, don't use it, I have no problem with disabling it for public use and only enabling it for myself.

**Comment by xIUPITERx** [comment]
The new audio mode is great.
Revert it only because is has less features and some buggs (yet), why?
Because of things like that the app is still in beta, so you can make changes not every one is happy with at first.

**Comment by NeeRaj-2401** [comment]
> The best thing is probably to show the buttons for additional actions in a row below the play/pause button as the share button is positioned in the screenshot above.

Swipe down to dismiss player

**Comment by NeeRaj-2401** [comment]
> Revert it only because is has less features and some buggs (yet), why?
> Because of things like that the app is still in beta, so you can make changes not every one is happy with at first.

@xIUPITERx  The app was already fulfilling almost every need. and everything was going smooth, it wasn't feeling like that it is in beta. 
But now this audio mode which is some sort of very unique feature among all of the alternatives is worth the efforts.
also Bnyro is aware about the bugs and bad UX. so eventually he will come up with flawless experience for audio mode too.

**Comment by xIUPITERx** [comment]
> He is aware about the bugs and bad UX.

I think you misunderstood me, that was not a criticism of Byrno.

**Comment by NeeRaj-2401** [comment]
When switching back to video from audio mode. Starts the video from the very start i.e 0. 
Is that intended?  Cause  switching from video to audio is seamless.. audio starts where video pauses before switching.

**Comment by xIUPITERx** [comment]
For me, it remembers the progress.

Is there a way to make the whole thing seamless? So with an animation to crossfade the time it takes to buffer and maybe let the audio mode continue to play for a second until the video mode has loaded.

**Comment by NeeRaj-2401** [comment]
> When switching back to video from audio mode. Starts the video from the very start i.e 0.


https://user-images.githubusercontent.com/88180887/213866282-020df6b3-b893-47c5-a9a2-08416eff7be0.mp4

**Comment by Bnyro** [comment]
Keeping the position was not mentioned in the issue, so it's not yet implemented...

**Comment by Bleuzen** [comment]
> > Why not change this Video mode itself to Audio mode
> 
> We already have an audio player now so reverting that doesn't make sense.

Think about podcasts. Usually it is fine to only listen to them (audio only) and disable the video stream to reduce data usage.
However, it would be still useful to be able to read comments, add to playlist...
In the new audio player this is not possible. For example to read comments we have to first go back to video mode, which is annoying and also wastes data (since it loads the video stream again, which should be not needed to read comments).

Keeping the video player as is and implementing an audio mode which does only this:
- disable loading the video stream (only load audio stream to reduce data usage)
- freeze the video (or display the thumbnail under the controls) since video stream is not loaded anymore

... would be very useful.

**Comment by Bnyro** [comment]
The audio mode is there to use LibreTube sort of like a music player (at least for me), adding things like an add to playlist button or might be considered in the future, although I'm not of the opinion that it would be useful.
Anyways keep in mind that the audio player is very bleeding edge and night still not be 100% finished.

**Comment by NeeRaj-2401** [comment]
i have two suggestion right now for better UX
1. **keeping the position** from audio to video
2. **keeping the video speed** from video to audio
 (cause default background playback speed is removed so atleast it should be controlled and remembered via video player)

**Comment by Bleuzen** [comment]
> The audio mode is there to use LibreTube sort of like a music player

There are good music players already, for example: ViMusic & InnerTune.
Both are open source and also use a nice modern design specialized for music.

Having yet another app implementing exactly the same functionality seems like wasted effort and time.
There is no need for LibreTube to have a music player.

(in my opinion, but I also respect in case you want to build an all-in-one app)

> adding things like an add to playlist button or might be considered in the future, although I'm not of the opinion that it would be useful.

I consider `add to playlist` and `read comments` to be essential (for music and podcasts).

Without those, the audio mode is pretty useless to me.
If one wants just a music player, there are at least two good apps already out there doing exactly this. Again, having yet another one seems to be wasted effort.

However, especially the "reading comments" feature while only listening to a video is something the music player apps do not implement, this is why I hope to see it in LibreTube.
(something like I wrote above to keep the video mode UI in audio mode would solve this)

---

Btw. this is not meant to be mean, I still really appreciate your work.
Just trying to use facts to avoid wasting effort and possibly save you some time, if you want to go this route :)

**Comment by Bnyro** [comment]
> We already have good music players, for example: ViMusic & InnerTune.
> Both are open source and use a nice modern design specialized for music.
> Having yet another app implementing exactly the same functionality seems like wasted effort and time.
> There is no need for LibreTube to have a music player.
> 
I'm a former user of both of them, ViMusic and InnerTune (also contributed to both). There were two reasons why I decided to add an audio player UI to LibreTube:
1. Neither with InnerTune nor with ViMusic I was able to sync by music playlists between different devices, which is essential for me.
2. Both connect directly to the YouTube servers, so using a VPN for those is mandatory. I know InnerTune has a proxy feature, but I had some serious issues while using it that way.

In the end, I only added it because I had issues with all the available alternatives. I don't aim for it to replace other YT music players for the average user, in fact it was only an experiment for myself to see whether I can do something to get rid of my issues with other clients.
Before the release, I wasn't even really sure whether it's a good idea to allow users access to it or instead only keep it for myself. There are no real plans on expanding it from my side as it already covers all the use cases I need it for.
I hope you understand that.

**Comment by Bleuzen** [comment]
Yeah makes sense, thanks for the explanation.

Would a PR implementing an audio only mode which uses the video player UI be accepted?
There could be an option in settings, toggling the behaviour when tapping on the "Audio" button under a video.
If the option "use music player" is on, it will switch to the new music player you implemented.
If the option is off, it could just display the thumbnail instead of the video and only load the audio but otherwise keep the same UI.

I can't promise anything, I'm not an Android dev so maybe it will never happen.
But just in case I (or someone else) get it working, would this be a welcome addition?
