### ISSUE TITLE
I have all notifications disabled in my application, but I want to go to the "subscriptions" section and see there all the new videos from all the channels that I subscribe to.

### ISSUE THREAD

**Issue by Dima1n1** [libre-tube/LibreTube#2683]
### Steps to reproduce

Go to the subscription section and watch new videos

### Expected behavior

I have all notifications disabled in my application, but I want to go to the "subscriptions" section and see there all the new videos from all the channels that I subscribe to.

### Actual behavior

In the "Subscriptions" section, new videos are shown not from all the channels to which I subscribed, but only a small part.

### LibreTube version

0.10.0

### Android version

android 13 oxygen os

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
See https://github.com/TeamPiped/Piped/issues/1130
