### ISSUE TITLE
audio mode doesn't buffer

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#2689]
### Steps to reproduce

The new audio mode does not seem to buffer, songs interrupt all the time because of this.

### Expected behavior

Music should play without interruptions

### Actual behavior

Music pauses every 20-30s for a few seconds.

### LibreTube version

latest debug

### Android version

Android 13 One UI 5.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The new audio mode uses the background mode as it's also been before, the issue can't be caused by that as it only got an interface, but no internal changes.

**Comment by Bnyro** [comment]
And can't reproduce, so maybe instance related.
