### ISSUE TITLE
Live video is tagged as Shorts.

### ISSUE THREAD

**Issue by Ilhamiii** [libre-tube/LibreTube#2693]
### Steps to reproduce

1.Watch live video.
2.Access your watch history.
3.Live video is tagged as Shorts.

### Expected behavior

Live video should be tagged as live.

### Actual behavior

https://user-images.githubusercontent.com/121803062/212480930-4da55920-3922-41b1-98c6-8baa566e271f.mp4

### LibreTube version

0.10.0

### Android version

Android 5/13

### Other details

This is so.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
https://www.youtube.com/watch?v=ZQY8j7-pa5o
Some shorts arn't recognized as shorts anymore.
