### ISSUE TITLE
Update channel page

### ISSUE THREAD

**Issue by dhishkyaon** [libre-tube/LibreTube#27]
like this to use blank area better -

![Picsart_22-02-14_20-03-22-504.png](https://user-images.githubusercontent.com/88529066/153884263-c9a21cd6-154f-4160-924e-f22d3bb84f02.png)

**Comment by dhishkyaon** [comment]
man i don't know c of coding. Just edited a screenshot. If you don't have enough time then its completly fine.

**Comment by rimthekid** [comment]
No I have the rime thought you modified the code lol

**Comment by dhishkyaon** [comment]
also please reduce the bottom navigation bar height.
