### ISSUE TITLE
Export the downloaded video.

### ISSUE THREAD

**Issue by Ilhamiii** [libre-tube/LibreTube#2701]
### Describe your suggested feature

Option to export the downloaded video to the device.

### Other details

Let's watch the video without logging into LibreTube.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not planned as already stated out in many other issues, it doesn't make sense as downloaded audio and video are not muxed.
