### ISSUE TITLE
Improve image quality of thumbnails in the suggestions.

### ISSUE THREAD

**Issue by JohnBetaro** [libre-tube/LibreTube#2706]
### Describe your suggested feature

the thumnail quality in the subscriptions page was bad in earlier versions of the app, then it was fixed and that's a huge improvement for me.

but i hope you will consider also improving the quality of the thumbnails in the suggestions part (when we're watching a video and scrolling down)

the quality in the subscriptions:

![Screenshot_20230115-164018.png](https://user-images.githubusercontent.com/114379310/212551056-5732883f-da5a-45f5-af77-edfde6e139ec.png)

the quality in the suggestions when watching:

![Screenshot_20230115-164037.png](https://user-images.githubusercontent.com/114379310/212551131-3e157d96-eab7-473e-bc09-325c88b5ad15.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not a client side issue, there's already an open PR at the NewPipe Extractor repo that will allow us choosing between different resolutions, but it's not merged yet.

**Comment by JohnBetaro** [comment]
i took a look and did not find the PR but from what i saw they are not accepting any change that messes with the thumbnail resolution, we hope they will give it a second thought.

**Comment by Bnyro** [comment]
https://github.com/TeamNewPipe/NewPipeExtractor/pull/889
