### ISSUE TITLE
Playlists do not get sorted by "Recently Updated"

### ISSUE THREAD

**Issue by tampos4** [libre-tube/LibreTube#2707]
### Steps to reproduce

[ Using without account ]

1. Create some playlists.
2. Settings > Appearance > Playlists order > Recently Updated (reversed)
3. Now update (add/delete some videos) some playlists which were created earlier than the last newly created playlist.

### Expected behavior

All the updated playlists should show at the top [ get sorted according to selected option i.e. "Recently updated (reversed) ].

### Actual behavior

Instead playlists get sorted according to Creation date (reversed).

### LibreTube version

0.10.0 Latest Debug

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That sorting is not yet implemented for local playlists, and I don't think it ever will as I don't want to save the time stamps of changes.
