### ISSUE TITLE
[debug builds] Audio Mode Queue behaves unexpected

### ISSUE THREAD

**Issue by RickyM7** [libre-tube/LibreTube#2715]
### Steps to reproduce

1. Put a playlist in audio mode or put some videos in a queue
2. Just let the playlist plays or move a song in the queue, etc

### Expected behavior

The queue should play normally, going to the next sound and stopping after playing the last video or something.

### Actual behavior

There's some behaviors:
1. The current video repeats in a looping
2. The current video duplicate in the queue
3. If you move the current video in the queue, the next video will play once, after that the queue will reset, and duplicate the played videos
4. If you click on a video in the queue, this video will play once, but ii will be moved to the top of the queue then the 3. behavior will happen

### LibreTube version

Libretube a34e113 (Telegram Build)

But apparently this bug started in the first build with audio mode.

### Android version

Android 11 (ArrowOS)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by RickyM7** [comment]
I just tested Libretube 1718380 (Latest Telegram Build) and two of the weird behaviors still persist, which is the first video in looping and duplicated. This only stops happening if you open the queue and remove the duplicate of the first video that always appears, or click on another video for the queue to follow from there.

**Comment by Bnyro** [comment]
Oh, you're right, I didn't notice that because it only happens when playing a playlist and not a normal video in the audio mode.

**Comment by RickyM7** [comment]
> Oh, you're right, I didn't notice that because it only happens when playing a playlist and not a normal video in the audio mode.

Yeah, I didn't even realize that this only happened with playlists too

**Comment by NeeRaj-2401** [comment]
@Bnyro there one more unexpected/ strange behaviour

I will just share a recording to explain

**Comment by NeeRaj-2401** [comment]
https://user-images.githubusercontent.com/88180887/212751761-6c1045ce-e749-4c18-ba98-a2a1b68a64ca.mp4

As i  dragged a song and tapped on it.. instead of Playing selected song... It plays the song which is at previous position of that song

**Comment by Bnyro** [comment]
Interesting, the same behavior is at the release v0.10.0 too apparently, so it's not related to the new audio mode.

**Comment by NeeRaj-2401** [comment]
@Bnyro u will reopen this thread to consider that issue.. or i have to create a new thread for it?

**Comment by Bnyro** [comment]
It's not related to that issue here, so yes
