### ISSUE TITLE
Add newly opened links to current queue if currently playing video

### ISSUE THREAD

**Issue by pinembour** [libre-tube/LibreTube#2716]
### Describe your suggested feature

Currently, when playing a video in the background or in PiP, and opening a YouTube link with LibreTube, the current playing video gets discarded for the new one. I would like to be able to add the new video to queue instead of it taking over the one that is currently playing.

My idea to make it work would be to add a second share option in the Android share menu that would be called “Add to queue”, and maybe calling the current option “Open”, like so.
![LibreTube2ndShare](https://user-images.githubusercontent.com/15938873/212715763-4c665f02-0280-49c3-9114-970f089c8658.jpeg)

Pressing the “Open” button would have the same behavior as currently, and pressing the “Add to queue” button would only add the video to the queue without touching the current video.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by NeeRaj-2401** [comment]
**tap & hold on video** and click on either "play next" or "add to queue"

**Comment by Bnyro** [comment]
But the issue is about adding to queue from links, which is not possible currently as only video items can get added.

**Comment by NeeRaj-2401** [comment]
Oops my bad

**Comment by Bnyro** [comment]
@NeeRaj-2401 please don't delete messages like that,
1. they could still be helpful to others in the meantime
2. others can't follow the discussion when some messages got deleted

**Comment by NeeRaj-2401** [comment]
i apologise for that.  i thought the message was irrelevant cause i misunderstood the issue at first

**Comment by pinembour** [comment]
Wow, that was incredibly fast, thank you. I just tested and it's working well.
Just one thing, is it possible to make it so that when you press the Add to Queue button it doesn't open the app ? Or maybe resume the last player status once the new link is added to the queue ?
For example if I'm in PiP using another app, I share a link to LibreTube to add to my queue, and I can keep using my other app without having to manually go back into PiP.

**Comment by Bnyro** [comment]
I'm not sure whether Android allows us to start background services from a share intent, at least I've never seen any other app that doesn't start when you share something to it.
However, I can have a look in the next days and see whether it's possible.

**Comment by Bnyro** [comment]
As I already supposed, we have to start an activity (with UI) when users share a link to the app, so I'm pretty sure there's no way to not open the app when adding a video to the queue like that.

**Comment by pinembour** [comment]
I see, and it wouldn't be a good UX to open the activity and then close it.. I can live with it like this, thank you for your help
