### ISSUE TITLE
Make comments expanded by default. Remove similar videos section.

### ISSUE THREAD

**Issue by rakibdev** [libre-tube/LibreTube#272]
### Describe your suggested feature

In my many years of YouTube experience as far I remember I never intentionally clicked any similar recommendations inside a video. Video specific contents such as comments are higher priority, first thing I immediately look after clicking video but comments collapsed/hidden by default in every video. There no time for aimlessly scrolling in similar videos below comments to find what I need. I type in search bar myself with an aim what to watch.

NewPipe displays comments, video description and similar videos in 3 tab bottom navigation. Design could be this way.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Hmm, I don't think so. We could add an option to the settings to hide trending and expand comments by default but I don't really think we should add an option for it since settings are already fulfilled.

**Comment by martin-desktops** [comment]
I would love to see yhe option to hide Recommended Content, since it would support youngs/kids to consciously select content they are going to watch, instead of being indirectly fed by some algorithm.
