### ISSUE TITLE
Player disappears when entered in app from media notification 

### ISSUE THREAD

**Issue by NeeRaj-2401** [libre-tube/LibreTube#2723]
### Steps to reproduce

1. Play any video
2. Back to home or switch app
3. Tap on player notification 

### Expected behavior

App should open in either player screen or with mini player 

### Actual behavior

Player screen completely disappears 

### LibreTube version

Latest debug

### Android version

Android 12

### Other details

https://user-images.githubusercontent.com/88180887/212749007-9802fe17-837c-4b5f-9f8c-b9ba89d0497c.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by faisalcodes** [comment]
This issue seems to be of the PendingIntent which is not being handled correctly.

Clicking on the notification is creating a new instance of MainActivity, which is not expected.

**Comment by Bnyro** [comment]
We had been using `launchMode="singleTop"` previously for the `MainActivity`, but that had the negative consequence that when clicking the app icon while being in PiP mode, the app restarted.

**Comment by faisalcodes** [comment]
I think I have fixed this issue.
I have used `launchMode="singleTop"` and tweaked some code in `loadIntentData` function in the `MainActivity.kt`.

What I found to be fixed?

- Clicking on notification resumes the activity with player (Even if it is in PiP mode)
- Clicking on the app icon also resumes the activity (with or without PiP mode)

**Comment by Bnyro** [comment]
> I think I have fixed this issue.
> I have used `launchMode="singleTask` and tweaked some code in `loadIntentData` function in the `MainActivity.kt`.
> 
> What I found to be fixed?
> 
> - Clicking on notification resumes the activity with player (Even if it is in PiP mode)
> - Clicking on the app icon also resumes the activity (with or without PiP mode)
> 
> None of the actions above recreates the activity.
>
That's awesome, would be great if you can do a PR on it!
Sorry that I did not yet review your other PR, I'll do my best to find time for it tomorrow :)

**Comment by faisalcodes** [comment]
I will do a PR after I am done testing on a few more devices.
