### ISSUE TITLE
Option/Changes for queue and sleep time. 

### ISSUE THREAD

**Issue by ARBoyGo** [libre-tube/LibreTube#2728]
### Describe your suggested feature

These are some of the features, I think should have been in the app. 

1. Sleep timer, Unlike reminder, Sleep timer should stop working the task it was doing.. force stop.
2. When we use add to queue, The video usually under the whole queue playlist.... I need them as next video to be played.
3. An option to generate new queue playlist, As we are playing next video from the playlist... It's good to take a recommended queue generate. 

As usual my final words, Only do it if you can do it(I know you can still, Don't waste your time) ☺️🥰. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
1. You mean replacing the currently available sleep timer with one that closes the app once it's over?
2. That's already possible, it's called "Play next"
3. You mean regenerating the queue each time a new video from the queue is played? Don't really get how that would be useful.

**Comment by ARBoyGo** [comment]
1. Yes, Indeed just like ViMusic it force stop the application. 
2. Nah, I'm talking about our latest debug Apk does the job to add to queue by using share option right? I want the added to queue video automatic plays next instead of at the end of the queue playlist. 
3. Not to generate each time, But an option to generate when we want to change the prefer video category..

**Comment by Bnyro** [comment]
1. The break reminder got replaced with a sleep timer now
2. I don't think that adding yet another share intent action is a good idea, instead you should add it to the queue and then manually reorder it
3. I'm of the opinion that that is kind of pointless, just select a video from the search or related streams to generate a new queue.

**Comment by ARBoyGo** [comment]
Thanks @Bnyro for sleep timer 😊, It is much better... Unlike reminder, Reminders are going to be ignored 😜.

I understand 2 & 3 unnecessary. Thanks
