### ISSUE TITLE
Add sort by popularity search filter.

### ISSUE THREAD

**Issue by rakibdev** [libre-tube/LibreTube#273]
### Describe your suggested feature

And no clue what YT Music Albums, Playlist filters are for. Seems unnecessary.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not supported by the Piped API, therefore you would have to open an issue on Piped on GitHub
