### ISSUE TITLE
Add silent skip to skip silent part of video..

### ISSUE THREAD

**Issue by heartlog** [libre-tube/LibreTube#2731]
### Describe your suggested feature

Skip silence is life saver, when you want to complete a lecture of hours and have less time. And comes handy when watching music.
It is available in [Newpipe](https://github.com/TeamNewPipe/NewPipe/).. And works smoothly...

Newpipe is seems to rely on ExoPlayer for this feature... I am leaving [This ExoPlayer GitHub code](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/audio/SilenceSkippingAudioProcessor.java) For reference...

[Newpipe skip silent discussion](https://github.com/TeamNewPipe/NewPipe/issues/9251)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We can just use https://github.com/google/ExoPlayer/issues/2635

**Comment by heartlog** [comment]
> We can just use [google/ExoPlayer#2635](https://github.com/google/ExoPlayer/issues/2635)

@Bnyro..
Seems like your code is merged in ! 
Thanks, I Appreciate it a lot...
Wish I would have learned Java so, i can also be able to contribute to open src project like this....

**Comment by heartlog** [comment]
> I did not understand this feature.

This feature skips the sailent part of like video..
Kind of like sponcerblock but for quite parts are begig skipped..

**Comment by heartlog** [comment]
> Kotlin

I know.. 
But, it's required to learn the Java to understand the functionality of kotlin..

**Comment by heartlog** [comment]
> We can just use [google/ExoPlayer#2635](https://github.com/google/ExoPlayer/issues/2635)

Hope this suggestion can help
https://github.com/libre-tube/LibreTube/issues/2744#issuecomment-1386597597
