### ISSUE TITLE
Password lost

### ISSUE THREAD

**Issue by Tommy-01** [libre-tube/LibreTube#274]
### Steps to reproduce

Hi,
i have a question and find no other place to ask.
I have lost my password for my Libretube Account. 
Is there a way to get the password or to reset it?

The app is still logged in. Maybe the i can export it from the app?

Thank you!

### Expected behavior

a

### Actual behavior

b

### LibreTube version

0.2.6

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You would have to ask someone on [Piped](https://github.com/TeamPiped/Piped) for it, we don't have access to your password.

**Comment by FireMasterK** [comment]
On the official instance, we don't offer password resets, sorry.

**Comment by Tommy-01** [comment]
Ok thank you.
