### ISSUE TITLE
Skip silence is ON by default

### ISSUE THREAD

**Issue by tampos4** [libre-tube/LibreTube#2744]
### Steps to reproduce

1. Open the app.
2. Play [this](https://www.youtube.com/watch?v=g4mHPeMGTJM&t=0) video to check if "Skip silence" is on by default or not.

However the toggle switch shows that it's OFF.
You need to toggle it ON then OFF to turn it off.

### Expected behavior

It should be OFF by default.

### Actual behavior

It's ON by default.

### LibreTube version

0.10.0 Latest Debug

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by heartlog** [comment]
Well, there should be checkbox in playback speed section..
Eg.
![Screenshot_20230118_124427_LibreTube](https://user-images.githubusercontent.com/76758776/213107909-9b7bc557-73fb-4f6d-ad1f-ea02b7d0faac.jpg)

And sorry my suggestion #2731 caused some problems in code conduct....

**Comment by Bnyro** [comment]
There already is one?
