### ISSUE TITLE
Latest test version quickly skips silent sections

### ISSUE THREAD

**Issue by rsssxd** [libre-tube/LibreTube#2748]
Latest test version quickly skips silent sections. There is no setting to disable this feature

**Comment by Bnyro** [comment]
It's contained in the playback speed options when playing a video, dupe of #2744

**Comment by rsssxd** [comment]
@Bnyro 

I know, but it won't do any good. Please check if there is a strange disorder.

The video and audio are suddenly progressing.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/blob/master/CODE_OF_CONDUCT.md#our-standards

**Comment by rsssxd** [comment]
The settings you mentioned won't do anything. This is giving false information to the user and not accepting responsibility.

This is more against the rules.

**Comment by Bnyro** [comment]
I already redirected you to the proper issue for it, tagging or blaming me doesn't make it better.
