### ISSUE TITLE
Switch to sound settings in queue

### ISSUE THREAD

**Issue by Ilhamiii** [libre-tube/LibreTube#2752]
### Describe your suggested feature

Option to open device sound settings from queue like in NewPipe.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Neither space currently nor really that useful as you can access it easily in other ways as your Android settings or as a separate app.
