### ISSUE TITLE
LibreTube isn't showing thumbnail in notification anymore.

### ISSUE THREAD

**Issue by rozari0** [libre-tube/LibreTube#2754]
### Steps to reproduce

1. Open app
2. Play any video
3. Check notification

### Expected behavior

![Screenshot_20230118-172313](https://user-images.githubusercontent.com/61970262/213159797-a8862894-d3b3-46c6-a3a9-e2fb3880465d.jpeg)
Should show thumbnail like LT 0.10.0 is showing.

### Actual behavior

Nothing happens. :)

### LibreTube version

https://github.com/libre-tube/LibreTube/actions/runs/3947173301 this debug

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't reproduce on A13, does anyone have a similar issue in the debug builds?

**Comment by xIUPITERx** [comment]
I can't reproduce it either.

**Comment by rozari0** [comment]
https://piped.kavin.rocks/shorts/_XH-XuDfSr0?feature=share Screen Record. : )

**Comment by Bnyro** [comment]
> Dupe of #2722 ?
>
Seems so
