### ISSUE TITLE
Will this app be distributed through Accrescent?

### ISSUE THREAD

**Issue by Grkrz** [libre-tube/LibreTube#2756]
### Describe your suggested feature

Will this app be distributed through Accrescent?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
Yes, but only when accrescent is more stable and a good developer API exists.
I think those were the reasons.

**Comment by Bnyro** [comment]
Yes, when I tested it last time it didn't feel really stable, apart from that the developer console is still in alpha or beta stage currently if I remember correctly.
Another thing I dislike about it is that (from what I know), every update/release has to become uploaded to it by myself manually, which is why I prefer the atomization of F-Droid in that manner.
As soon as Accrescent is more matured, I may try to publish LibreTube there as well, but that's approximately not going to happen too soon.

**Comment by Grkrz** [comment]
Apprciate your time to answer my question. I understand the hindrance with updating it manually if that is the current state at the moment, in the future this will be automated. Thank you for doing great job!

**Comment by Grkrz** [comment]
> Yes, but only when accrescent is more stable and a good developer API exists. I think those were the reasons.

@xIUPITERx can you explain what you mean by "and a good developer API exists"?

**Comment by Grkrz** [comment]
Hi Guys,
I saw that Connect You is in Accrescent. Can we also expect Libre Tube in the near future?

**Comment by ghost** [comment]
Is this reconsidered yet, specially when Accrescent is almost back on track and better than ever with their latest call for support?

**Comment by Bnyro** [comment]
> Is this reconsidered yet, specially when Accrescent is almost back on track and better than ever with their latest call for support?
>
No.

**Comment by Bnyro** [comment]
I also don't see why financial support to Accrescent should help with the issues I mentioned above. That probably doesn't grant me more free time to go through the release process to publish LibreTube there on each update.

The release process on Accrescent is too complicated in my opinion and I don't like where that project is heading, even though I once contributed to it.

**Comment by ghost** [comment]
Why is the issue closed as solved if it will be reconsidered when Accrescent matures and has a good developer API. Should it not be set as open for now, not only for discoverability reasons to prevent duplicate issues?

**Comment by Bnyro** [comment]
We decided to never put LibreTube on Accrescent.
