### ISSUE TITLE
Smooth scrolling over buttons.

### ISSUE THREAD

**Issue by Ilhamiii** [libre-tube/LibreTube#2757]
### Describe your suggested feature

On YouTube, scrolling down is possible via the buttons in the player.However, it is not possible in LibreTube.It should slide down without hiding the buttons.

### Other details

https://user-images.githubusercontent.com/121803062/213370809-b3b23295-4762-48aa-acfa-b295c608ca82.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not really possible without much efforts because the player controls would hide and show randomly while swiping then.  
Of course there is some work around, but spending time with it is not worth it for anyone.
