### ISSUE TITLE
Strange Behavior After Bookmarking A Playlist

### ISSUE THREAD

**Issue by akano12** [libre-tube/LibreTube#2759]
### Steps to reproduce

1. Bookmark a Playlist.
2. Close LT
3. Open LT

Or
1. Bookmark a Playlist
2. Go to bookmarks page
3. Tap back btn or click on any item from navigation bar

### Expected behavior

Not showing bookmarks when opening LT or tapping back button from bookmarks page. 

### Actual behavior

After bookmarking a playlist, each time LT is opened the bookmarks page is briefly displayed before moving to home.

Also when in bookmarks page, if you click back button or move to home by tapping on home icon ftom nav bar, again the bookmarks page is briefly displayed before moving to home

### LibreTube version

0.10. 0

### Android version

Android 12

### Other details

https://user-images.githubusercontent.com/50032603/213489656-bf867e9c-e651-49f0-8cc4-c1444dd9420e.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by faisalcodes** [comment]
This is not an issue. Bookmarks are also available on the homepage. So when you visit the homepage and videos are not loaded yet then the bookmarks are the only contents which are visible. When videos are loaded then bookmarks go below the videos. 

We may add a progress bar while videos on the homepage are loading.

**Comment by akano12** [comment]
@Bnyro sorry for the ping but can you please remove this from the home screen?
It serves no purpose other than making home screen takes too much to load especially on slow networks.

It serves no purposes as Bookmarks and Playlists already have a dedicated page for both of them.

**Comment by Bnyro** [comment]
The homepage would be almost empty then, wouldn't it? Also, why can't you just disable the home tab then?

**Comment by Bnyro** [comment]
Please let us track that under a different, new issue.
