### ISSUE TITLE
Controls almost overlap Status Bar, hard to operate while in full screen

### ISSUE THREAD

**Issue by Mrnofish** [libre-tube/LibreTube#2760]
### Steps to reproduce

1. Start playing a video
2. Switch to full screen
3. Tap on the screen until controls appear
4. The Android Status Bar will also appear almost overlapping LibreTube's controls

### Expected behavior

There should no need to pixel hunt in order to activate LibreTube's controls while in full screen mode

### Actual behavior

Activating the controls may require multiple taps to find a spot that is low enough to trigger the intended action, instead of the interactions being intercepted by the System Status Bar

### LibreTube version

0.10.0

### Android version

Android 11

### Other details

![Screenshot_20230119-171635_LibreTube](https://user-images.githubusercontent.com/28036193/213497263-ce01bd24-3bbd-4cc0-aa08-42a6065a4a20.png)

Contrast NewPipe, where Video Controls are rendered slightly lower down to avoid this issue:

![Screenshot_20230120-060145_NewPipe](https://user-images.githubusercontent.com/28036193/213621233-1e4f8d18-5008-416e-967a-050118318324.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Archeix7** [comment]
https://github.com/libre-tube/LibreTube/issues/2541

**Comment by xIUPITERx** [comment]
> https://github.com/libre-tube/LibreTube/issues/2541

?
