### ISSUE TITLE
Minimising to pip even with pip disabled 

### ISSUE THREAD

**Issue by NeeRaj-2401** [libre-tube/LibreTube#2762]
### Steps to reproduce

1. Play any video
2. Select pop-up once
3. Again switch to full screen Player
4. Press home button 

### Expected behavior

Video should be played in background as normal

### Actual behavior

After one manual pop-up mode.. next time it keeps the video in pip when pressed home button.

### LibreTube version

Latest debug

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please share a screen recording in order to make it easier to understand. Thanks in advance.

**Comment by NeeRaj-2401** [comment]
https://user-images.githubusercontent.com/88180887/213591790-785368d9-1b6f-4152-b2ea-d467100a0238.mp4

@Bnyro as u can see , in first time tapping on home screen does not make app to enter in pip.. thats Indicates i have disabled pip mode.
And after one manual pop-up, it starts to keep in pip everytime.
