### ISSUE TITLE
Higher video quality when fullscreen

### ISSUE THREAD

**Issue by Grkrz** [libre-tube/LibreTube#2764]
### automatical higher quality video when rotating 

I was thinking that perhaps would be nice to implement higher quality video when the screen is rotated and is full screen.
This could save some data and battery since one normal size video the quality set up to 480 is OK.
This change could appear after certain amount of seconds to avoid accidental rotating the picture. This would perhaps also avoid the video to stop when rotating.

### Other details

Example
Normal small size watching wideo 480
Full size video 1280

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
No plans for that, sorry.

**Comment by Grkrz** [comment]
Thank you for the reply.
