### ISSUE TITLE
Video becomes broken after pressing "Stop" button

### ISSUE THREAD

**Issue by SuperJumpBros** [libre-tube/LibreTube#2765]
### Steps to reproduce

1. open video
2. go to player controls on phone's OS
3. click the square "Stop" button (or wait for the OS to do it, it seems this happens almost randomly for me)

### Expected behavior

video should pause, and player should probably close from within the app, preserving the current time of the video in history

### Actual behavior

video becomes broken, time becomes 0:00 and watch length too, video becomes black and play button does nothing, original watch time is lost from history

### LibreTube version

0.8.0

### Android version

Android 13

### Other details

https://user-images.githubusercontent.com/54546501/213549607-d4df2a4a-e983-44de-80a6-c1896c45755d.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
The stop button has been removed in the latest debug version.
![Screenshot_20230119_224810_GitHub.png](https://user-images.githubusercontent.com/97352673/213569632-de407306-b13e-4b62-afdb-801ff625578f.png)

**Comment by xIUPITERx** [comment]
And your app version is outdated.
The latest stable release is 0.10.0.

**Comment by Bnyro** [comment]
As already stated out, the issue is not relevant anymore for the latest builds.
