### ISSUE TITLE
Clicking on Notification Doesn't Open the Queue

### ISSUE THREAD

**Issue by RickyM7** [libre-tube/LibreTube#2768]
### Steps to reproduce

1. Play a playlist in the background
 2. Click on the notification

### Expected behavior

The queue/audio mode interface opens

### Actual behavior

Nothing happens

### LibreTube version

Libretube e5a3701 (Telegram Build)

### Android version

Android 11 (ArrowOS)

### Other details

It would be nice to have another way to open the audio mode / queue. Maybe an option in the 3 dots menu.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It does open the audio player in the latest debug version when clicking the notification. From there, you can click the thumbnail of the video in order to show the queue.

**Comment by RickyM7** [comment]
> It does open the audio player in the latest debug version when clicking the notification. From there, you can click the thumbnail of the video in order to show the queue.

I'm using the latest debug version (from Telegram), but nothing happens when I click on the notification, even the app doesn't open as usually did.

Now I'm downloading the latest debug build generated in the Actions to test it.
