### ISSUE TITLE
[F-R] 'Play All In Audio Mode' Button in Playlists

### ISSUE THREAD

**Issue by RickyM7** [libre-tube/LibreTube#2769]
### Describe your suggested feature

Just a simple button (maybe next to the 'play all' button) to play the entire playlist in Audio Mode.

### Other details

Actually the LT have the 'Play in the Background' option, but it doesn't play the songs in Audio Mode, atlast in the Libretube e5a3701 (Telegram Build) version.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Press the 3 dots next to the playlist title, then choose "play in background".

**Comment by RickyM7** [comment]
> Press the 3 dots next to the playlist title, then choose "play in background".

Yes, that's what I wanted and I already knew that, but it wasn't working correctly in the last version sent to telegram, but I just tested the last version in Actions and it worked perfectly.
