### ISSUE TITLE
be able to download an audio file from a YouTube video

### ISSUE THREAD

**Issue by franco27** [libre-tube/LibreTube#277]
### Describe your suggested feature

Hello

We can download the videos but we cannot download only an audio file from a video.  that's a shame.  I would like to have this possibility.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by martin-desktops** [comment]
Technically we are able to download just an audio even now, but I guess .mkv format isn't so obvious and well supported among audio players.
