### ISSUE TITLE
[Cosmetic] Seekbar slides off-screen but only partly, while full screen

### ISSUE THREAD

**Issue by Mrnofish** [libre-tube/LibreTube#2770]
### Steps to reproduce

Check the steps and screenshot in #2760 

Wait a few moments with no interaction.

### Expected behavior

The seekbar should IMO either remain visible while the controls are, too, or slide out of the viewport completely.

### Actual behavior

The seekbar slides downwards and supposedly out of view, but doesn't completely leave the viewport, the upper part of the text is still visible.

### LibreTube version

0.10.0

### Android version

Android 11

### Other details

See screenshot in #2760

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
https://user-images.githubusercontent.com/97352673/213693543-83067888-a0bf-4987-9d0f-d7c878e40bf0.mp4

**Comment by Bnyro** [comment]
Yes, that's an ExoPlayer issue, we can maybe work around that by making the bottom bar not use the ExoPlayer view ID.
