### ISSUE TITLE
Navigation Bar Color

### ISSUE THREAD

**Issue by electr1fy0** [libre-tube/LibreTube#2781]
### Describe your suggested feature

The Navigation bar is some off color and would look much better if it's transparent and blends in with the UI.
![Screenshot_20230121-080123](https://user-images.githubusercontent.com/87616300/213840020-c1398dc0-ac45-47d3-91b5-d1cd8d60ffdb.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It is meant to have the same color as the navigation bar, when setting in transparent it would have the same as the app background which would be even worse.

**Comment by electr1fy0** [comment]
As you can see, it's not the same color as the navigation bar. It's off.
