### ISSUE TITLE
[Bug] Audio mode breaks subscriptions tab

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#2791]
### Steps to reproduce

1. Refresh subscriptions tab
2. Start a video
3. Change to audio mode
4. Change back
5. Reload subscriptions tab

https://user-images.githubusercontent.com/97352673/213867168-bf39c2c3-1dc0-4840-bfbc-295725297891.mp4

### Expected behavior

Tab should work as expected

### Actual behavior

Tab is now empty

### LibreTube version

latest debug version

### Android version

Android 13 One UI 5.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://user-images.githubusercontent.com/82752168/213869356-c968c49f-4c2c-4ee3-882e-7c7c6da4bc98.mp4

Can't reproduce, either device or debug build specific.
