### ISSUE TITLE
[F-R] 'Close Audio Mode' Button

### ISSUE THREAD

**Issue by RickyM7** [libre-tube/LibreTube#2792]
### Describe your suggested feature

Currently, even in debug builds isn't possible to close the notification after the background reproduction ends, so, it would be nice to have a button to stop the reproduction in audio mode, just like the 'X' button in video mode.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We're already using the maximum of possible controls in the notification, if we wanted to add a close button we would need to get rid of one of them. I think the currently available controls are more important as a close button since you can just close the app from recents instead.

**Comment by RickyM7** [comment]
Yes, but it doesn't have to be a button, it can be a swipe gesture or simply the notification automatically closes when leaving video or audio mode.
