### ISSUE TITLE
Apply pure black theme everywhere

### ISSUE THREAD

**Issue by jojobozo** [libre-tube/LibreTube#2794]
### Describe your suggested feature

Adding the possibility to apply the pure black theme everywhere like for example, comments, playlists and video option. I think it would look better especially for devices with green tint.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't really understand the issue, the current pure theme already applies for everything (comments, etc.)

**Comment by jojobozo** [comment]
> I don't really understand the issue, the current pure theme already applies for everything (comments, etc.)

It's not black like #000000 so it's showing on devices with green tint

**Comment by Bnyro** [comment]
Use the monochrome theme?
