### ISSUE TITLE
Remove dock on single panel

### ISSUE THREAD

**Issue by asklow** [libre-tube/LibreTube#2795]
### Describe your suggested feature

When configured to have only one panel, remove the dock completely.

![Screenshot_20230121_221825](https://user-images.githubusercontent.com/117489882/213877688-1fe9b4c7-0ba5-486e-b43e-f20f13e590eb.png)

### Other details

Should free up the bottom space for those who enjoy a single panel.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Already possible, uncheck all tabs and set the home tab you want to (with the home icon).

**Comment by akano12** [comment]
> Looks half baked btw. There's gap in the dock after minimizing player.
> 
> https://user-images.githubusercontent.com/117489882/213879227-06855cb0-7506-42bb-9bcb-e50b80b1a48a.mp4
> 
> 

https://github.com/libre-tube/LibreTube/issues/2548
