### ISSUE TITLE
No portrait for verticals

### ISSUE THREAD

**Issue by asklow** [libre-tube/LibreTube#2798]
### Steps to reproduce

Keep auto rotation on

https://user-images.githubusercontent.com/117489882/213878966-16fe46a7-e31c-4914-ba1e-c31837582fe2.mp4

### Expected behavior

Shorts even though are vertical format, follow landscape orientation

### Actual behavior

Should be portrait.

### LibreTube version

0.10.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I already explained that multiple times in other issues, I won't do it again here
