### ISSUE TITLE
An option for a youtube URL instead of piped URL when sharing

### ISSUE THREAD

**Issue by Ddeityy** [libre-tube/LibreTube#280]
### Describe your suggested feature

Would be nice to have an option of a normal youtube link when sharing. 

### Other details

Could add that to settings so you don't have to mess around with UI

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by jplie** [comment]
I agree, I also wanted to suggest, it will be very convenient.

**Comment by martin-desktops** [comment]
It also would benefit friends we share link with, if they use different Youtube clients, that aren't based on Piped.

**Comment by Bnyro** [comment]
@margin-desktops It would be possible but I don't know how we should make at regarding to the UI. Should we make a Dialog where you have to select between YouTube and Piped that appears when you click the share button? Or how should it be implemented?

**Comment by martin-desktops** [comment]
When I see users sharing video links they probably don’t want to stick with one type for all the time. They use different sorts for different occasions. For example not many want to bother friends with custom Piped links. Original YouTube links can also be required by apps that support for instance embedding Youtube videos, or just add new features, but weren’t created with Piped in mind. On the other hand if users want to share the link for their personal use - to a note/computer they probably aren’t going to leave the Piped ecosystem. That’s why I think the hidden toggle in the settings solution wouldn’t really work for us.

I suggests following path: 
- User selects the Share option
- Piped or YouTube original URL question dialog
        - It triggers Android ShareSheet

It would be probably even shorter path with some gesture, but I doubt this would work with the current layout/widgets.
