### ISSUE TITLE
Seek accessibility buttons in queue

### ISSUE THREAD

**Issue by asklow** [libre-tube/LibreTube#2801]
### Describe your suggested feature

Buttons for skip/back 10 seconds inside queue interface would be great. Since they'll be useful while listening to podcasts.

![Screenshot_20230121_230023](https://user-images.githubusercontent.com/117489882/213879507-a4bac745-35c0-453c-971a-0cbd3fca294b.png)

Instead of that drop down button in the center, seek buttons would be utilitarian.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
No plans for that, we already have controls for that in the video player, audio player and notofication (and PiP)

**Comment by Bnyro** [comment]
When in audio only/background mode, press the notification. Second possibility is to click the `audio` button while playing a video.

**Comment by Bnyro** [comment]
No, it's in 0.11.0 which got released one day ago.
