### ISSUE TITLE
Unwatched videos marked as watched

### ISSUE THREAD

**Issue by noClaps** [libre-tube/LibreTube#2815]
### Steps to reproduce

1. search for a video
2. scroll through the list of result

### Expected behavior

The watched video thumbnails should have the duration played bar at the bottom while the unwatched video thumbnails shouldn't.

### Actual behavior

some of the unwatched video thumbnails have the duration played bars

### LibreTube version

0.11.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't reproduce, also tested it on a fresh installation but can't reproduce either.

**Comment by akano12** [comment]
Faced same issue multiple time, some videos that I've never watched would have watch progress marker.
However, i don't recall facing this on recent version of LT

**Comment by akano12** [comment]
> Can't reproduce, also tested it on a fresh installation but can't reproduce either.

Found out how to reproduce:

1. Search for something
2. Play first video from results (just move the seekbar to anywhere u want)
3. Now every ninth video from below the played video will have the same watch marker as the video you have played
