### ISSUE TITLE
A bug on the pop-up video

### ISSUE THREAD

**Issue by LostCat123** [libre-tube/LibreTube#2817]
### Steps to reproduce

1.find a video that have a caption/subtitles
1.play that video on pop-up mode

### Expected behavior

The subtitles/caption should stay on the video pop-up

### Actual behavior

The subtitles/caption disappear on pop-up mode

### LibreTube version

0.11.0

### Android version

Android 12L

### Other details

![Screenshot_20230122-111722_LibreTube](https://user-images.githubusercontent.com/91554842/213899072-75fc64c0-8690-48b8-887d-8a61ef5b15b6.png)
![Screenshot_20230122-111715_LibreTube](https://user-images.githubusercontent.com/91554842/213899073-d7851d1b-c0e7-499c-ae5a-aac6ef588995.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Intended, see #2067
