### ISSUE TITLE
Unresponsive when opening history

### ISSUE THREAD

**Issue by name-tar-xz** [libre-tube/LibreTube#2819]
### Steps to reproduce

1. Open LibreTube
2. Go to the library tab
3. Tap on Watch History

### Expected behavior

Open History

### Actual behavior

App becomes unresponsive and History does not open

### LibreTube version

0.11.0

### Android version

Android 13

### Other details

History button stays highlighted and video keeps playing in the mini player but the app becomes completely unresponsive and can only be closed from either using force stop from the app info screen or from an app not responding dialog

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by demirdegerli** [comment]
Have the same issue.

**Comment by akano12** [comment]
Can't reproduce, s20 A12
