### ISSUE TITLE
An option to get back to playback mode after clicking home button in audio mode.

### ISSUE THREAD

**Issue by Surbbd** [libre-tube/LibreTube#2820]
### Describe your suggested feature

1. Play anything on audio mode
2. Press home button
3.  An option to get back to playback mode in audio mode rather than the notification

### Other details

![Screenshot_20230122-151652_LibreTube](https://user-images.githubusercontent.com/113291579/213909604-004880c0-465d-4622-9d08-5ccb668165df.png)
Btw it is playing a music, an option rather than in the notification is needed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by RickyM7** [comment]
Yes, this is something LT needs. Before having the audio mode, the queue was opened by the 3 dots menu, so I think that putting there the option to reopen the audio mode is an interesting option, since it doesn't change the current UI much.
