### ISSUE TITLE
force short mode

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#2823]
### Describe your suggested feature

Some youtubers don't seem to be able to upload shorts properly. Instead of portrait videos, they use landscape videos with black bars or similar on the sides and the short in the middle.
It would therefore be usefull if there were would be a mode that cropped the videos to approximately the aspect ratio of the short. If you want to be more precise, you could use edge detection to see the exact proportion of the shorts, but that would probably be overkill.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
When the format the video got uploaded in isn't correct, not even YouTube will display it correctly. I don't believe there is an easy way for us to do that, apart from it not many videos are affected. Thus, not planned.
