### ISSUE TITLE
in player upper right corner, add one more button for custom settings item

### ISSUE THREAD

**Issue by ydqsbfsyi** [libre-tube/LibreTube#2824]
### Describe your suggested feature

User offen has some settings item that he wants to change most frequently, but reaching that item often needs multiple clicks. For me this frequent item is to change instance, for someone else it could be changing captions size. So, is it possible to add another button to the upper right corner of the player interface, which brings a specific settings item from deep down to surface, with one click the user can reach it.  

For example: 
in settings I can configure my own custom button:  bring "settings->instance->CHOOSE" to surface. Then, in player interface, there will show a text icon "C" or "CH", or any fixed icon if text icon is not possible. With one press of this button, I'll directly see all instances for me to choose. 

This feature also could save one click for options that already exist in the upper right corner buttons, e.g. playback speed, or quality, or captions.

Please consider.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
When we added that once, other users would come up with a lot of different actions they want to see possible there.
Apart from that I doubt it would be useful for many users, at least probably not too many would use it, me neither.
Last but not least adding yet another action will cause us to end up with five actions there, which is too much without doubt.
For the given reasons, not planned.

**Comment by ydqsbfsyi** [comment]
I see. Thanks.
