### ISSUE TITLE
Video auto skipping 

### ISSUE THREAD

**Issue by NeeRaj-2401** [libre-tube/LibreTube#2826]
### Steps to reproduce

1. Play any video
2. Open description link

### Expected behavior

Link should get opened in browser along with video playing in background.

### Actual behavior

Current Video gets skipped and starts playing next one.

https://user-images.githubusercontent.com/88180887/213921869-ba06e171-a222-4e1c-8f03-942ecdffb2b7.mp4

### LibreTube version

Latest debug

### Android version

Android 12

### Other details

can u please limit the links tapping area to links only.
Cause tapping away from links also opens the link.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Fixed with #2829
