### ISSUE TITLE
Kavin.rocs official server 502 error

### ISSUE THREAD

**Issue by Chex07** [libre-tube/LibreTube#2832]
### Steps to reproduce

If i select Kavin.rocs (official) from app settings, app givün server 502 error and videos nor working. it will fix later? 

### Expected behavior

Videos not working

### Actual behavior

Videos 
![Screenshot_20230122_234412_VideoTube](https://user-images.githubusercontent.com/6298184/213939441-82dfd377-e186-4a4f-a5ee-48c1abfe3242.jpg)
problem

### LibreTube version

0.9.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not an issue of the app.

**Comment by Chex07** [comment]
![image](https://user-images.githubusercontent.com/6298184/213991684-28999fe8-0618-401b-95cb-7ad0f4fc05bc.png)

https://piped.kavin.rocks/watch?v=Nyaw0mF5ikc not opening videos ?

**Comment by SuperJumpBros** [comment]
@Chex07 this isn't LibreTube's fault, you are on the LibreTube repository. kavin.rocks is hosted by Kavin. use another instance if you're having issues.
