### ISSUE TITLE
Improvement @Bnyro

### ISSUE THREAD

**Issue by Snams98** [libre-tube/LibreTube#2852]
### Describe your suggested feature

Exigo, ut progressio tempi infinitus neque modo in gradus quinque deligere potendum est.

### Other details

That's all I can do

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Mais non, ce n'est pas possible!
