### ISSUE TITLE
Seeking in audio mode

### ISSUE THREAD

**Issue by asklow** [libre-tube/LibreTube#2854]
### Describe your suggested feature

Audio mode is great. But there's no way to skip or go back 10 seconds.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I'm not aware of any other music player that supports that feature natively in the UI, albeit it is already possible in the notification.

**Comment by Bnyro** [comment]
Since the last update, seeking in the notification is supported for all Android versions.

**Comment by Bnyro** [comment]
The two buttons on the bottom right?

**Comment by SuperJumpBros** [comment]
![image](https://user-images.githubusercontent.com/54546501/214893394-1b1a32ba-3c8f-4233-92d5-b49955164c9b.png)
these are left/right seek buttons... idk what you're asking
![image](https://user-images.githubusercontent.com/54546501/214893790-1e46dae1-3564-4a01-b325-d28e1bef7e09.png)
these ones are the next/previous buttons (seek bar is in the middle)


so they already exist? what is your suggestion, it's already in your screenshot
