### ISSUE TITLE
Show position at seekbar preview

### ISSUE THREAD

**Issue by MatsG23** [libre-tube/LibreTube#2855]
### Describe your suggested feature

If you move the video progress slider in the default player, it would be very helpful to see the timestamp you will skip to and the video frame at that point as a preview.

### Other details

I do not think there is an setting for that. Am I missing something? I am wondering that there has not been an issue about that yet (could not find one using my search terms).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Archeix7** [comment]
I also only noticed, it seemed to work before
![IMG_20230125_170856_762](https://user-images.githubusercontent.com/51048550/214603949-a4e4f14c-879e-4867-a651-a44275467982.jpg)

**Comment by NeeRaj-2401** [comment]
> I also only noticed, it seemed to work before !

Update to latest debug/version

**Comment by Bnyro** [comment]
The video preview is already working though?!

**Comment by NeeRaj-2401** [comment]
Basically preview is hiding along with player controls,
So when user is sliding over progress bar controls should not be disappeared

**Comment by NeeRaj-2401** [comment]
To be solved:
1. Add Timestamp in preview
2. Preview disappearing after 2-3 seconds
