### ISSUE TITLE
Rank old videos just turned visible for general public high like a newly uploaded one

### ISSUE THREAD

**Issue by MatsG23** [libre-tube/LibreTube#2856]
### Describe your suggested feature

If an creator chooses to upload a video as private or only visible for the channel subscribers (YouTube Premium), the general public will, of course, not see the video at the time it is uploaded.
When that video is turned visible for everyone later, the video keeps it upload date and shows as e.g. "uploaded 3 days ago" even tho the video was not available for everyone 3 days ago. That video will pop up in the timeline of LibreTube but the user will often not notice it because it appears at the timeline of e.g. 3 days before.

I suggest showing this specific type of videos as if they was just uploaded.

### Other details

I have no clue if this is doable. You could probably compare the videos back in the timeline with the newly fetched list from Piped but that could be inexact.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The NewPipe Extractor doesn't support it, thus there's no way for us to implement that.
