### ISSUE TITLE
Caching subscriptions & one usability feature

### ISSUE THREAD

**Issue by berryes** [libre-tube/LibreTube#2857]
### Describe your suggested feature

Since there's no recommendation due to no algorithm being in Piped I like to browse around in my subscriptions.

I hate that its a dropdown menu and when I get back from visiting a channel it drops me back into the Feed instead of the open tab. And since theres no caching on that data I have to wait about a minute or so for the tab to open back down. (I have 300+ subscriptions)

Fix #1
Making it so when I swipe back from a channel, it drops me back to the subscriptions instead of the feed.
Fix #2
I feel like caching all the images for the channels would solve this loading/freezing issue. 

Gifs explaining the issue;

Fix #1 (The swipe back problem)
![ezgif com-gif-maker(3)](https://user-images.githubusercontent.com/73071529/214240436-3c7523ec-0f69-47d9-a1db-80559d1e400d.gif)

Fix #2 (The horrible loading time/freezing due to data not being cached. Its sped up 10x)
![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/73071529/214239995-7c156421-ac78-457f-bb38-a88adad262d3.gif)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by RickyM7** [comment]
I don't like the dropdown approach to much too, but I can't imagine a good alternative to this, maybe a separate tab? But I believe that the subscriptions tab will have to be rethought in the near future if the group subscriptions feature is implemented.

**Comment by Bnyro** [comment]
Funny thing about subscriptions grouping, I thought about adding it locally before I received the following comment: https://github.com/libre-tube/LibreTube/issues/2029#issuecomment-1416265861. That one minimized my motivation to work on that to zero.
Though I agree it could solve the issue.

**Comment by RickyM7** [comment]
> Funny thing about subscriptions grouping, I thought about adding it locally before I received the following comment: [#2029 (comment)](https://github.com/libre-tube/LibreTube/issues/2029#issuecomment-1416265861). That one minimized my motivation to work on that to zero. Though I agree it could solve the issue.

Observing the discussion of this issue (#2029) I realize that it would not be possible to have groups subscribed consistently without piped itself having this feature, because when we subscribed to a channel through piped it would be left out of the groups. It would only be possible to make something functional if the subscriptions were saved locally, but I don't know how feasible this would be, it's a pity.

**Comment by Bnyro** [comment]
What I would have done is to display all subscriptions, that are not part of a group, in a new dynamically generated group called something like "Uncategorized". It's not a perfect solution, but it would probably the best until syncing it via the API is possible.

**Comment by berryes** [comment]
> 

i have no problem with it being a dropdown, it looks great. its the fact when I swipe back to browse my other subscriptions the tab closes.
Seems like an easy fix but I know 0 Kotlin or Java so I might be wrong.

**Comment by Bnyro** [comment]
Closing in favor of #4082
