### ISSUE TITLE
Player freezed when using music mode

### ISSUE THREAD

**Issue by buddhi-deep** [libre-tube/LibreTube#2861]
### Steps to reproduce

1. Play a video and switch into music mode
2. Player freezes for a while then it starts to play

### Expected behavior

The player should not freeze when loading resources 

### Actual behavior

It freezes while loading resources 

### LibreTube version

0.11.1

### Android version

Android 11, Realme UI

### Other details

Device: Realme 3 pro. 4GB RAM 64GB internal.
![IMG_20230125_001230_907](https://user-images.githubusercontent.com/38799701/214347122-a5b9263d-cc72-44e4-9244-83b2d9a65127.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
Can reproduce, 
I think it has something to do with the buffering.

**Comment by xIUPITERx** [comment]
https://user-images.githubusercontent.com/97352673/214951810-e48f35e9-563c-4c70-89e3-0be9b616321c.mp4

**Comment by faisalcodes** [comment]
Sometimes it stays frozen forever. Also, for me, the thumbnail in the audio mode is not loading, even if I have a good Wi-Fi connection.

**Comment by soymadip** [comment]
> Can reproduce, 
> I think it has something to do with the buffering.

Hello sir, it's happening too me too. 

And also i wanna say, the same video of play in video mode, it's plays without any buffering, it audio player is freezing and not playing the audio.

**Comment by halfbytecode** [comment]
This happens for me as well, on Android 13 on Pixel 7 Pro, even on LibreTube 0.15.0.

**Comment by Bnyro** [comment]
The audio player is not freezed, it just doesn't work as long as the video is buffering. There were improvements made since the issue got reported however to fix buffering issues.
