### ISSUE TITLE
Android 13 media player to be solid color

### ISSUE THREAD

**Issue by Grkrz** [libre-tube/LibreTube#2866]
### Describe your suggested feature

It would be nice to  have the possiblily to set Android 13 media player to solid ( best black ) color, or set up your own wallpaper. 
It is more pleasant to eyes when there is solid color compare to the all the time various picture.
![IMG_20230124_210926](https://user-images.githubusercontent.com/107203983/214397968-9cd7aa60-92ed-4bce-b7fc-9dfa4eaccd97.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
When you enable the data saver mode, the background will be a solid color.
However, adding an option for customizing it would be quite useless and therefore is not planned.
