### ISSUE TITLE
Picture in Picture behaviour 

### ISSUE THREAD

**Issue by SashaMcC** [libre-tube/LibreTube#2870]
### Describe your suggested feature

When using Picture in Picture mode and dismissing the window, LibreTube closes the app fully and clears it from the recent apps screen. This is in contrast to the official YouTube app which, upon closing the PiP window, keeps the app open and keeps your progress in the video with the ability to resume it from where you closed it 

It would be great to have LibreTube follow the same behaviour just for familiarity for YouTube users and just as a general UX improvement as you wouldn't need to find the video and open it again 

Telegram link with screen recording for context
https://t.me/LibreTubeChat/19468

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
Please upload the screen recording on github directly, not everybody uses Telegram or wants to open links to external sites.
