### ISSUE TITLE
The app won't let me log in or see videos

### ISSUE THREAD

**Issue by AkAuniverse** [libre-tube/LibreTube#2871]
### Steps to reproduce

Example
1. I opened the app
2. Went to settings
3. Tried logging in
4. Got a message that says "undispatchedCorountine was cancelled"

### Expected behavior

Logging intoy account should happen

### Actual behavior

This happened instead of letting me log in

### LibreTube version

Version 0.10.0

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Either the selected instance is down or not reachable, however that doesn't prevent you from using a different one!
