### ISSUE TITLE
Seek rewind/forward animation does not reflect correct duration immediately after a settings change

### ISSUE THREAD

**Issue by rudderbucky** [libre-tube/LibreTube#2874]
### Steps to reproduce

1. Install the app and open a random video, then rewind/forward it (the default duration is 10)
2. Set the duration to something else through the settings (I set it to 5)
3. Open a video and rewind/forward it again

### Expected behavior

The animation should display in text the correct duration set (in my case, 5)

### Actual behavior

The animation continues to display the previous duration (in my case, 10). However the video actually rewinds the amount I set in settings as expected. It also works fine after a restart. I suspect this is because initRewindAndForward in CustomExoPlayerView.kt or whatever code block that generates the animation is not called again once the setting is changed.

### LibreTube version

0.11.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Yes, the text labels won't change until you restart the player, as it's only being set when starting the player. No plans for spending efforts into improving that behavior.
