### ISSUE TITLE
Do not darken video while reading comments

### ISSUE THREAD

**Issue by atollk** [libre-tube/LibreTube#2876]
### Describe your suggested feature

At the moment, opening the "comments" view below a video darkens everything outside of it. While I see the point of that design, it makes it unnecessarily difficult to read while watching at the same time. The proprietary YouTube app deosn't do this either. It would be very nice if this was at least an option able to be turned off.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by faisalcodes** [comment]
This can be worked on along with #2878.
