### ISSUE TITLE
Unable to import YouTube subscriptions

### ISSUE THREAD

**Issue by dongltron** [libre-tube/LibreTube#288]
YouTube subscriptions are not importing. I import from the file and it pops up a toast that says 'Subscribed' but nothing happens.

**Comment by Bnyro** [comment]
You imported them from the csv file?

**Comment by Norrica** [comment]
I'm facing similar issue, but with playlists. I extracted them from google takeout, subscriptions imported succesfully, but playlists remain empty. Is this a bug?

**Comment by Bnyro** [comment]
@Norrica We don't support importing playlists
