### ISSUE TITLE
constant buffering only in app

### ISSUE THREAD

**Issue by lordkitsuna** [libre-tube/LibreTube#2883]
### Steps to reproduce

I'm using a custom instance i host and have verified i have 700Mbps speeds to the host. playing a video on that instance in the browser on my phone (Firefox) works perfectly, full 4K streams without problems.

the app however on that same instance cannot even do 480p, i get maybe a few secondsof playback before it stops to buffer for a good 30 seconds and I'm not sure what to do

I've tried a different devices I've tried different network connections I've tried to reinstalling the application clearing all of its data I am on the latest from the releases page.

I tried searching both open and closed tickets for something similar but unless I just wasn't using the right keywords I didn't find something that appeared to match the problem I'm having at the moment

### Expected behavior

playback should occur as normal at similar speeds to the instance in a web browser on the same device 

### Actual behavior

streams are unplayable with constant buffering 

### LibreTube version

0.11.1

### Android version

android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Did you attempt using HLS instead of DASH?
Settings -> Audio and video -> Use HLS

**Comment by Bnyro** [comment]
whatever.social has a similar issue that DASH doesn't work properly inside the app, other instances don't have issues with LibreTube and DASH though.

**Comment by Bnyro** [comment]
Unfortunately I neither really have an idea of what the issue could be nor much knowledge about the nginx configuration for Piped.
I hope that either @privacytime101 found a fix for the issue on their instance or @FireMasterK has an idea of what the issue could be.

**Comment by Bnyro** [comment]
Since it can be solved by using HLS, I'll close the issue for now.
If you're sure that you have everything set up properly as described in the Piped docs, feel free to ask in the Piped Matrix room for help.

**Comment by halfbytecode** [comment]
Switching to HLS, and even enabling LBRY HLS, did not help in my case. Running LibreTube 0.15.0 on Android 13 on Pixel 7 Pro.

**However, disabling Piped Proxy worked for me. Since then, I have not had any buffering issues so far.**
