### ISSUE TITLE
Support keyboard input

### ISSUE THREAD

**Issue by timkur** [libre-tube/LibreTube#2887]
### Describe your suggested feature

For Android devices that have keyboards attached, it would be nice to support keyboard commands for pause/forward/rewind and using the arrows to navigate the various playlists/screens.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
No plans for supporting keyboards, the app targets normal touchscreen Android devices.
For such keybindings, use Piped in the browser.
