### ISSUE TITLE
Add repeat to audio only mode

### ISSUE THREAD

**Issue by pawa2401** [libre-tube/LibreTube#2894]
### Describe your suggested feature

Add an audio repeat button that cycles between repeating modes. Currently there is no way to enable repeat mode in audio mode.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
There is a repeat button when clicking the notification and then opening the queue.
