### ISSUE TITLE
Close comments dialog when video changes in autoplay mode.

### ISSUE THREAD

**Issue by faisalcodes** [libre-tube/LibreTube#2898]
### Steps to reproduce

1. Play a video
2. Open comments dialog, click on a comment which has replies and keep it opened 
3. Let the next video play after the current one ends.
4. Try to exit the replies fragment.
5. App crashes.

### Expected behavior

Either autoplay should be paused as long as comments dialog is opened or the dialog should be closed on next video play.

### Actual behavior

Video is changed but the comments still belong to the old video.

### LibreTube version

0.11.1 Debug

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by praveenrajput** [comment]
The crash isn't happening for me. But, the comments section stays open even when autoplay is active.
