### ISSUE TITLE
Show video time duration

### ISSUE THREAD

**Issue by dhishkyaon** [libre-tube/LibreTube#29]
something like this -
![IMG_20220214_233825.jpg](https://user-images.githubusercontent.com/88529066/153921558-ab49972e-5250-4ee3-9053-e5646c4d0485.jpg)

**Comment by rimthekid** [comment]
you mean the video duration?

**Comment by rimthekid** [comment]
I didn't understand could you be more specific?

**Comment by rimthekid** [comment]
Oh you mean just like newpipe right?

**Comment by saurabhinabys** [comment]
yeah, thin red bars at bottom of thumbnail indicating how much of the video has already been watched.

**Comment by dhishkyaon** [comment]
@rimthekid yes video duration.

**Comment by novocaiin** [comment]
@lilcheti any chance to also show durations on the search result page?

**Comment by lilcheti** [comment]
I'll look into it
