### ISSUE TITLE
Sync watch history with logged in Piped account?

### ISSUE THREAD

**Issue by d4f5409d** [libre-tube/LibreTube#2900]
### Describe your suggested feature

To be honest, I don't really know if this is a bug or a feature that has not yet been implemented, but after all, it'd be useful to have the watch history with my piped account synced since I started to use LibreTube and Piped heavily in the last couple of days, and it could help me a lot to check which videos did I already see on desktop and vice versa. I don't know, if this is right for privacy though. Help me out if you can, thanks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Piped doesn't support that yet.

**Comment by d4f5409d** [comment]
Hmu if it does
