### ISSUE TITLE
Video doesn't get resumed after pause

### ISSUE THREAD

**Issue by d4f5409d** [libre-tube/LibreTube#2902]
### Steps to reproduce

1. Watch video
2. Put it background
3. The video stops
4. When you try to resume the video nothing is happening, it does not refetch

### Expected behavior

Refetch the video and resume playing

### Actual behavior

It doesn't refetch and I have to restart the whole video to continue watching

### LibreTube version

0.11.1

### Android version

Android 13

### Other details

Note this can happen also when losing internet connection and after that trying to resume video playing.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by d4f5409d** [comment]
This issue connects to #2901 too in some places.

**Comment by RickyM7** [comment]
You can't resume the video using the buttons in notification?

**Comment by d4f5409d** [comment]
I never tried it.. will do it brb

**Comment by d4f5409d** [comment]
> You can't resume the video using the buttons in notification?

No, does not work

**Comment by Archeix7** [comment]
> You can't resume the video using the buttons in notification?

This is not an option. Moreover, if the video does not load in the PIP, the window will close and the application will close too. And if you turn off the screen and leave the video in the background, the video will stop the same

**Comment by d4f5409d** [comment]
> > You can't resume the video using the buttons in notification?
> 
> This is not an option. Moreover, if the video does not load in the PIP, the window will close and the application will close too. And if you turn off the screen and leave the video in the background, the video will stop the same

Yes, I already told this

**Comment by RickyM7** [comment]
> 

Hmm, I figured he was using the app in the background and not in pip, that way the button in the notification would work.

**Comment by Archeix7** [comment]
> that way the button in the notification would work

For me work too, but 

> This is not an option
