### ISSUE TITLE
Add option to disable Share menu advanced selection

### ISSUE THREAD

**Issue by Joeviocoe** [libre-tube/LibreTube#2906]
### Describe your suggested feature

In settings, add an option to choose the default share link type (piped, YouTube) or to "Ask every time".

If a default is chosen, and the video is at 0 seconds... Do not prompt user during Share menu, and go directly to the Android share API context. 

### Other details

I typically share only to the Kodi/Yatse app.  And it only accepts YouTube url links and ignores timestamps. It'll be nice not to have another click in the sharing process. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Honestly it's only one extra click, adding options for such minor things will make it harder to overview and maintain the apps preferences, thus no plans for that.
