### ISSUE TITLE
My playlist keeps on clearing

### ISSUE THREAD

**Issue by AkAuniverse** [libre-tube/LibreTube#2909]
### Steps to reproduce

Whenever I log out and log back into my account my playlist gets deleted but my bookmark stays

### Expected behavior

The playlist should be there when I open the app

### Actual behavior

But instead it automatically gets deleted whenever I log back into my account

### LibreTube version

Version 0.10.0

### Android version

Samsung

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It doesn't get deleted, when logged in the app uses the playlists from tour Piped account, if not your local ones.
