### ISSUE TITLE
LT showing same Avatar for everyone in comments.

### ISSUE THREAD

**Issue by rozari0** [libre-tube/LibreTube#2917]
### Steps to reproduce

1. Play any video that has comment

### Expected behavior

Should show unique profile picture for everyone.

### Actual behavior

![Screenshot_20230131-012535](https://user-images.githubusercontent.com/61970262/215576534-22eb6455-4b10-4af6-ace9-478570d6559c.jpeg)

### LibreTube version

0.11.0 debug

### Android version

Android 9

### Other details

@faisalcodes This happened after your last . 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't reproduce

**Comment by rozari0** [comment]
> Can't reproduce

Dunno what happened, working fine for me now.
