### ISSUE TITLE
Allow video playing while call in progress.

### ISSUE THREAD

**Issue by faisalcodes** [libre-tube/LibreTube#2931]
### Describe your suggested feature

- LibreTube doesn't play video when there is a call in progress or audio output is busy unlike other apps such as YouTube. 
- It should play the video.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
Shouldn't it be that way?
I would find it quite distracting to watch a video while a call is running.

**Comment by faisalcodes** [comment]
In some areas in India where network connectivity is weak people get on call to obtain good connection. If someone wants to watch LibreTube while staying on call (because it provides good connection), then they can't.

If you find it distracting, then you naturally will not watch video.

**Comment by xIUPITERx** [comment]
How is making phone calls supposed to improve your Internet? These are two different networks (VoLTE excluded).

**Comment by faisalcodes** [comment]
It does. It's a very common hack where I live.

**Comment by NeeRaj-2401** [comment]
> It does. It's a very common hack where I live.

198

**Comment by actuallyabhi** [comment]
> It does. It's a very common hack where I live.

Yeah it does in most remote areas
