### ISSUE TITLE
Save comments progress

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#2934]
### Describe your suggested feature

After the pull request #2878 has been implemented, we need the function to save the current reading progress in the comments when you close and reopen the popup.

And please add a button to get to the latest comments.
![Screenshot_20230201_122052_LibreTube Debug](https://user-images.githubusercontent.com/97352673/216029755-4ade7763-1ed6-4d55-949d-245bfac6a65a.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by faisalcodes** [comment]
Yes, that should definitely happen. It's annoying when the progress is lost.
