### ISSUE TITLE
Player behavior when leaving app through back presses

### ISSUE THREAD

**Issue by timkur** [libre-tube/LibreTube#2940]
### Steps to reproduce

Scenario #1

Start playing a video
Navigate away from the app by pressing the back key

Scenario #2
In settings, under Player, disable PiP and select Pause on quit
Start playing a video
Navigate away from the app by pressing the back key

### Expected behavior

Scenario #1 - PIP shows up
Scenario #2 - Video stops playing

### Actual behavior

Scenario #1 - PIP does not show up
Scenario #2 - Video continues to play (can hear audio)

### LibreTube version

Built from head on 1/30/2023

### Android version

Android 13

### Other details

Looks to be that the app is subscribing to onUserLeaveHint() to invoke the logic necessary for the above scenarios. A couple things to keep in mind...

* onUserLeaveHint doesn't get invoked from back key presses
* I don't believe ChromeOS delivers that notification as well
* Keying off of this will give you incorrect behavior in multi-window mode

Consider subscribing to onStop instead,

https://developer.android.com/guide/components/activities/activity-lifecycle#onstop

From reading the Android documentation, onStop seems to be a better event to use for this and will cover the above scenarios and make this work well on ChromeOS.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
`onStop` would be an even worse solution for that, some examples why:
* When opening the settings, the video would pause, because the `MainActivity` got stopped
* When turning the screen off, PiP would start, because `onStop` is called

The Android documentation does mention everywhere to use `onUserLeaveHint`, thus we shouldn't do that differently. Instead we should search for an other solution.

**Comment by timkur** [comment]
Those are good points. I've seen other suggestions online about hooking the back press key and calling onUserLeaveHint yourself....

https://stackoverflow.com/questions/65732641/android-onuserleavehint-in-not-called-when-back-button-is-pressed

but I don't think things are broken in multi-window mode.
