### ISSUE TITLE
There are no badges

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#2949]
### Steps to reproduce

1.Play the video
2.Go to options
3.There are no icons in front of features.

### Expected behavior

They should be😥

### Actual behavior

![Screenshot_20230203-023759_LibreTube Debug](https://user-images.githubusercontent.com/124310688/216465687-e9b97343-05d1-42c0-96bc-829f8034e6b1.jpg)

### LibreTube version

0.11.1 Debug

### Android version

Android all

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by faisalcodes** [comment]
@Bnyro `can't reproduce` is not the right label. The OP wants icons along with labels in the menus which is obviously not present.

**Comment by Bnyro** [comment]
@faisalcodes No, `can't reproduce` is the correct label since we do have icons there. I don't mind sharing a screenshot if you have the same issue.

**Comment by faisalcodes** [comment]
@Bnyro I thought it was not implemented yet.

**Comment by Bnyro** [comment]
@faisalcodes 
![Screenshot_20230203-170031_LibreTube.png](https://user-images.githubusercontent.com/82752168/216649419-016e4344-f7e8-4e6a-a2f9-a52a29acd046.png)
