### ISSUE TITLE
Subscription Groups

### ISSUE THREAD

**Issue by jdmcguire** [libre-tube/LibreTube#2955]
### Describe your suggested feature

Hi there, I absolutely LOVE this app!! Only one feature is missing:

The ability to create and assign channels to groups for easier viewing! Right now we have to scroll through dozens of assorted videos to find a genre we like to check in the morning before work as an example. A groupingcfeature would would make it easy to find the content you are looking for. All videos could be the default view.
A "play all" button, or "play all new" button could be part of the interface when viewing by group.

Anyway, thank you for your amazing work!

All the best!

JD

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by rozari0** [comment]
The "Only one feature is missing" issue. 🤖
