### ISSUE TITLE
Blank page option in the navigation bar.

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#2967]
### Describe your suggested feature

Blank page option in navigation bar as in NewPipe. I like it.😊

### Other details

Add it if you have time.Thank you.🙂

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
Why do you want a blank page?

**Comment by Bnyro** [comment]
This is out of scope for the project.
Anyways you can achieve something similar by setting the trends tab as home tab and selecting a country whwre YouTube is blocked, e.g. Iran, as region.

**Comment by Qaz-7** [comment]
> Why do you want a blank page?

I intended the blank page as an opportunity to personalize.
