### ISSUE TITLE
blank buttons

### ISSUE THREAD

**Issue by Mrcubix** [libre-tube/LibreTube#297]
### Steps to reproduce

1. Install the app
2. Go to settings
3. Tap on the Connect / Register button
4. Buttons are blank
5. Go offline
6. Retry button is blank
7. Do some other stuff that display that same kind of button
8. Blank

### Expected behavior

Buttons should not be blank

### Actual behavior

- Types of buttons used by register/login & retry should have text

### LibreTube version

0.3.0

### Android version

Android 8.0

### Other details

32 bit Android ver

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Already fixed in #285

**Comment by mkikets99** [comment]
fixed, but not published yet.
