### ISSUE TITLE
Swiping down video player to miniplayer is laggy

### ISSUE THREAD

**Issue by Drangonfly30** [libre-tube/LibreTube#2971]
### Steps to reproduce

1. Play a video
2.  Swipe down to minimize it

### Expected behavior

Swiping down should be smooth

### Actual behavior

It feels a little laggy and jittery while minimizing

### LibreTube version

Latest version

### Android version

Android 7.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
Can you upload a screenrecording?

**Comment by Bnyro** [comment]
That looks like your device has issues rendering it, that's not a wonder with a device still running Android 7.
There are no such animation issues on more recent Android devices, thus it's most likely a device compatibility issue of the libraries we're using and not our issue.

**Comment by Drangonfly30** [comment]
Oh, thanks for clarifying it. I love this app.
