### ISSUE TITLE
Zoom within fullscreen video

### ISSUE THREAD

**Issue by blacktowel** [libre-tube/LibreTube#2978]
### Describe your suggested feature

Please add the ability to zoom within a video, even after it is already in fullscreen, so that a specific area could be further zoomed in. The zoomed area should be movable.
This functionality is very useful for small text in videos, like coding tutorials and others.
For an example how this would work, just pinch zoom in fullscreen with two fingers in the original YT android app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not planned, out of scope for the project. Take a screenshot and zoom into it.
