### ISSUE TITLE
Libretube crashes 

### ISSUE THREAD

**Issue by ansarimohammed422** [libre-tube/LibreTube#298]
### Steps to reproduce

When i play any videos the video starts and libretube crashes i dont know what is happening

I am on android 12.1 redmi note 4

Crash log URL 

https://paste.evolution-x.org/5JgO13

please solve this issue i cant use libretube at all because of this 

Its unusable 

In previous versions there was no issue 

But when i upgraded it to 0.3.0

It started crashing every time a video plays

Here is an video sample of it

Check it out

Do check it out

### Expected behavior

Open libretube play any video it crashes suddenly

### Actual behavior

Whenever i play any videos it crashes

### LibreTube version

0.3.0

### Android version

Android 12.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FireMasterK** [comment]
In the settings, can you try enabling sponsorblock and enabling one or more category?

**Comment by ansarimohammed422** [comment]
I will try and revert to you

**Comment by ansarimohammed422** [comment]
Yaa that solved the issue


Thanks
