### ISSUE TITLE
Download Problem

### ISSUE THREAD

**Issue by Chex07** [libre-tube/LibreTube#2982]
### Steps to reproduce

When I want to download music or video, it says the download is complete, but no files are downloaded to the phone.

### Expected behavior

When I want to download music or video, it says the download is complete, but no files are downloaded to the phone.

### Actual behavior

When I want to download music or video, it says the download is complete, but no files are downloaded to the phone.

### LibreTube version

0.11.1

### Android version

13

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [ ] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Follow the issue template.
Downloads are only accessible within the app.
