### ISSUE TITLE
Back button problem.

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#2985]
### Steps to reproduce

1.Open the app
2.Then press the back button.
3.The device should quit the application.
4.But it doesn't happen
5.It is possible by double clicking.

### Expected behavior

Click the back button to exit the application.

### Actual behavior

I press twice to exit.

### LibreTube version

0.11.1

### Android version

Android 12

### Other details

https://user-images.githubusercontent.com/124310688/217132460-61b926c3-e62a-44ef-9743-742dab151665.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by rozari0** [comment]
I think that's a feature, not a bug. 🫡
