### ISSUE TITLE
Save the most recent activity.🙂

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#2986]
### Describe your suggested feature

Keep your most recent activity in the app unchanged.
Watch the video.Repeating the same activity every time is annoying.Thanks in advance.The application should return to the order from the most recent activity on return

### Other details

https://user-images.githubusercontent.com/124310688/217134183-3241891a-c877-4d7a-aaa8-0e69963f5475.mp4

https://user-images.githubusercontent.com/124310688/217135494-4a683caa-8450-4ab2-ae8d-c9af9c5f6e92.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Don't get you, but we already store the bacstack.
