### ISSUE TITLE
Autoplay enqueued / "play next" videos but not else

### ISSUE THREAD

**Issue by d4f5409d** [libre-tube/LibreTube#3000]
### Describe your suggested feature

When we enqueue Libretube should automatically play the videos we selected but no other suggested videos

I want to reference NewPipe here, as it does a pretty good job doing this, it's kind of useful to have.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
For that, turn off `Insert related videos` in the player settings.
With that being disabled, suggested videos won't be added to the queue automatically and thus only the ones you added manually will be played.
