### ISSUE TITLE
`Alternate player layout` improvements

### ISSUE THREAD

**Issue by NeeRaj-2401** [libre-tube/LibreTube#3001]
### Describe your suggested feature

In Alternate player layout, there is **unnecessary blank space** below comments button
the blank space can be utilized by
either showing **2 rows** of recommended videos 
or using default height and width of frame but in horizontal scroll manner

implementing first option will also be helpful in going through more recommended videos at once.

### Other details

<img src="https://user-images.githubusercontent.com/88180887/217579453-d2ab60ac-9120-4952-932a-0cfcfdbcaa42.jpg" width="20%"> 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by NeeRaj-2401** [comment]
<img src="https://user-images.githubusercontent.com/88180887/217586203-9c3f8ea3-252f-4797-ac77-6cb380dacdb2.png" width="20%">  OR  <img src="https://user-images.githubusercontent.com/88180887/217586173-9b21beab-16e6-4df1-b719-36f66dff91b3.png" width="20%">

**Comment by NeeRaj-2401** [comment]
Bnyro, there is one more issue regarding alternative player layout

https://user-images.githubusercontent.com/88180887/217613459-495e94f8-0d2a-4a56-a312-61b684bd079f.mp4


This should also be fixed while layout enhancement

**Comment by xIUPITERx** [comment]
![Screenshot_20230209_104339_LibreTube Debug.png](https://user-images.githubusercontent.com/97352673/217776700-b9590919-86a7-44ce-8e0b-1b7e67a16e62.png)

I don't really see the problem.

**Comment by NeeRaj-2401** [comment]
> I don't really see the problem

Hmm, i think that might be caused by my screen size and display settings 
[Screenshot](https://user-images.githubusercontent.com/88180887/217579453-d2ab60ac-9120-4952-932a-0cfcfdbcaa42.jpg)

**Comment by Bnyro** [comment]
Actually, I think that using two rows or increasing the thumbnail size wouldn't look too good, thus I think we should keep it as it is for now, also because there are no real issues with a bit of blank space.
