### ISSUE TITLE
Remove from playlist option when playing a video that's already in a palylist

### ISSUE THREAD

**Issue by d4f5409d** [libre-tube/LibreTube#3002]
### Describe your suggested feature

I think the title describes it.
When we want to add a video to a playlist we go to the menu. When we want to remove it, we have to go to the playlist first. I want this feature to make playlist managing more convenient, so we could remove videos exactly from the player page with the playlist button.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That wouldn't be possible for usage with a Piped account since we would need to fetch all playlists and their content first in order for it to work, which is a waste of bandwidth.

**Comment by d4f5409d** [comment]
> That wouldn't be possible for usage with a Piped account since we would need to fetch all playlists and their content first in order for it to work, which is a waste of bandwidth.

I'm sure it would be possible, we just need to find out how. Please keep this issue open.
