### ISSUE TITLE
Local accounts

### ISSUE THREAD

**Issue by VidalGB** [libre-tube/LibreTube#3009]
### Describe your suggested feature

Create and add local accounts, for use on shared devices with multiple users, where each account's subscriptions and playlists are stored.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You already have two options to do that:
* Use Piped accounts (online)
* Use the Android built-in user accounts feature
I don't see a reason to add yet another possibility to achieve the same thing.
