### ISSUE TITLE
Option to manage and sort Playlists

### ISSUE THREAD

**Issue by r1klz** [libre-tube/LibreTube#3014]
### Describe your suggested feature

like on YouTube, we could have a "drag n' drop" feat. to manage our playlists how we would like; and a sort button too (e.g. Date added).

### Other details

also, i saw that the playlist's header background not changed when i removed a video from it.
it will be cool too if that background render while we move a video to the top or when it's deleted.

thanks!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Reordering videos in a playlist is currently not planned, mostly for the simple reason that the Piped API doesn't allow it.
What would be possible is to sort the videos inside a playlist by their upload date or alphabetically, though that probably wouldn't be that useful.
The playlist's thumbnail changes as soon as you remove the video, whose thumbnail has been used previously.

**Comment by r1klz** [comment]
ok... for some reason the thumbnail now synced good, it's working. but, even if Piped's API doesn't allows it, you can't implement that feature? i mean, the LibreTube playlists is stored in "offline mode", right? isn't an UI/UX problem you can handle? thanks @Bnyro!

**Comment by Bnyro** [comment]
Yes, that's implementable, however I don't want to make a difference between usage with and without accounts for the reasons below:
* it would confuse users when usage with and without account would behave differently
* it simply wouldn't be worth it since most users use the app with an account
