### ISSUE TITLE
Consider making Playback Speed and Video Resolution options more easily accessible

### ISSUE THREAD

**Issue by jaswinder77** [libre-tube/LibreTube#3023]
### Describe your suggested feature

Please consider placing the playback speed option over the video as we have in NewPipe.

I feel playback speed option is used a lot by students (and by most of the people who value their time and want to make the best use of it). At least, I personally keep changing the playback speed a lot esp. while watching longer tutorial and discussion videos. As the option is currently available in the dropdown, it requires an additional tap in LibreTube than it takes in NewPipe  each time the speed change is required.

Additionally, it would also be great to have the video resolution option more easily accessible as this option is also used a lot esp. by people who are on metered networks or even in case of people with unlimited internet plans where the internet service provider slows down the internet speed after the usage reaches a prescribed "fair usage limit".

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by RickyM7** [comment]
Yes, that would be really nice. I change the speed of the videos all the time, but I can't save a speed in the settings because I always go back to 1.0x when I listen to music through LT.

**Comment by o0nd7ots** [comment]
I see no good (clean) way to implement this in the GUI.
@jaswinder77 @RickyM7 could you please explain how you picture this?

**Comment by Bnyro** [comment]
Due to the fact that we already have way too many preferences right now, I'm closing this one as not planned to not clutter the settings interface more, and since we don't in fact have any free space left there, and it would only save one single click.
