### ISSUE TITLE
option to make brightness control in landscape be global

### ISSUE THREAD

**Issue by SuperJumpBros** [libre-tube/LibreTube#3024]
### Describe your suggested feature

There could be a switch to make it only be in landscape (could be the default) or be device-wide. My reasoning is because I often change the brightness this way expecting it to change globally and when i flip my device, it is no longer this way.

If required (i'm not sure how android's innards work), ask for the required device control permission.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
For that, we would need to add the permission `android.permission.WRITE_SETTINGS` to the app.
However, that seems to be quite unreasonable since the only thing of the settings we would change is the screen brightness, thus I don't think adding the permission is worth it as it grants as much more power than we need and might not be understandable for users why the app would need that permission.

**Comment by SuperJumpBros** [comment]
> For that, we would need to add the permission `android.permission.WRITE_SETTINGS` to the app. However, that seems to be quite unreasonable since the only thing of the settings we would change is the screen brightness, thus I don't think adding the permission is worth it as it grants as much more power than we need and might not be understandable for users why the app would need that permission.

I understand your reasoning behind this. It makes sense, but I thought android apps only had to ask for permissions at the time of needing them. "Allow **AppName** to manage files stored on your device?"

I would assume that this permission would only be asked when it is required, not at the moment of downloading the app.

Is it not this way for this one specific permission? Or is there a global "permissions" section of things it *might* need but not necessarily *will* that users may look at?

**Comment by Bnyro** [comment]
> Or is there a global "permissions" section of things it might need but not necessarily will that users may look at?
>
The permission always need to become declared in the `AndroidManifest.xml`, so F-Droid detects it and lists it within the permissions required by the app, which we definitely want to avoid.

> I would assume that this permission would only be asked when it is required, not at the moment of downloading the app.
>
I'm not sure how it would be with that permission, some need to be asked for at runtime while others are granted without prompting. However, most F-Droid clients show the needed permissions, apart from that users can look at it in their Android settings.

**Comment by SuperJumpBros** [comment]
Ah, I see. Thank you! :)
