### ISSUE TITLE
rotation auto when a video is playing

### ISSUE THREAD

**Issue by wiiznokes** [libre-tube/LibreTube#3028]
### Steps to reproduce

Click on a video
Rotate the screen

### Expected behavior

The screen should not turn automatically if rotation auto in Android and/or rotation auto in the app is disabled

### Actual behavior

The screen rotate

### LibreTube version

0.11.1

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Disable auto-fullscreen in the player settings.
