### ISSUE TITLE
Manage Playback Speed ​​of Audio and Video Mode Separately

### ISSUE THREAD

**Issue by RickyM7** [libre-tube/LibreTube#3030]
### Describe your suggested feature

Currently there is an option to default playback speed, but this is used in both audio and video mode. My idea is to be able to choose between synchronizing the speed of the modes (current behavior), or managing the speed of each of the modes separately.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by NeeRaj-2401** [comment]
> managing the speed of each of the modes separately.

This was case earlier, idk why the dev removed it
