### ISSUE TITLE
No video duration displayed on searches

### ISSUE THREAD

**Issue by teamspoad** [libre-tube/LibreTube#304]
In the home screen and the subscription tab,  the length of the video is displayed in the lower right corner.   This is not showing up for keyword searched videos,  even though your preview screenshots on github show that there are.   
![Screenshot_20220523-230925](https://user-images.githubusercontent.com/29628356/169961788-67870188-670a-4100-8341-6ef4225be55a.png)

**Comment by Bnyro** [comment]
That's because you're using an old app version, probably from F-Droid. Use the GitHub version instead.

**Comment by teamspoad** [comment]
Correct you are.   Thanks
