### ISSUE TITLE
Bottom bar moves incorrectly

### ISSUE THREAD

**Issue by enessgokalp** [libre-tube/LibreTube#3048]
### Steps to reproduce

When you are opening video from mini player bottom bar is closing and opening

### Expected behavior

bottom bar moves incorrectly

Uploading SVID_20230212_211736_1.mp4…

### Actual behavior

bottom bar should be stationary

### LibreTube version

From first version to last version

### Android version

Android 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
>

The screenrecording was not uploaded correctly.

**Comment by enessgokalp** [comment]
https://drive.google.com/file/d/14Oh3TlqlES3wahIkk7MPGZ0hBufwIAqO/view?usp=share_link
sorryyy

**Comment by Bnyro** [comment]
Honestly, I don't get the issue. Apart from that please don't expect us to view recordings from Gdrive.

**Comment by enessgokalp** [comment]
> Honestly, I don't get the issue. Apart from that please don't expect us to view recordings from Gdrive.

The file size is too big, so github doesn't upload it.
The issue is about bottom bar. When you are opening the mini player bottom bar closing and opening in the same time

**Comment by xIUPITERx** [comment]
Then it's probably a dupe of #1618.
