### ISSUE TITLE
download does not work on 13 android samsung A23 - One Ui 5.0 is possible on all samsung models with 13 android

### ISSUE THREAD

**Issue by korgot797** [libre-tube/LibreTube#3049]
### Steps to reproduce

1. Let's say I choose a video
2. I press download, I choose a bitrate and press download, nothing happens
3. I'm from Russia and I want to download the audio from the link : (But it doesn't work)

https://www.youtube.com/watch?v=oVtaJmNGC54&t=0

### Expected behavior

it should start loading as in NewPipe (it works there and this is not an advertisement)

### Actual behavior

nothing happened after clicking on the download:
 there was no notification in the curtain and it also did not ask LibreTube for a save location - also after 1 hour I checked downloads and found that nothing had been downloaded

### LibreTube version

0.12.0

### Android version

Android 13

### Other details

![Screenshot_20230212_193408_LibreTube](https://user-images.githubusercontent.com/125215171/218333081-3ba88321-a275-4c30-b891-410c6028c44e.jpg)

I wrote with the help of a translator because I don't know English 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please enable notifications in the Android settings of the app. Downloads are only stored inside the app, therefore you can find them under library -> downloads. It won't be downloaded to the Downloads folder of your phone.
