### ISSUE TITLE
server error... Extractor doesn't work

### ISSUE THREAD

**Issue by Rstment25** [libre-tube/LibreTube#3050]
### Steps to reproduce

![Screenshot_20230213-005100_LibreTube](https://user-images.githubusercontent.com/32986283/218344710-2b76c71d-daa7-41fa-8ff4-6c5f0a57e3d2.png)
![Screenshot_20230213-005044_LibreTube](https://user-images.githubusercontent.com/32986283/218344712-db11746d-4a37-4141-9baf-2835f4a30b5e.png)
![Screenshot_20230213-005037_LibreTube](https://user-images.githubusercontent.com/32986283/218344713-46ace21d-389b-4454-a309-c3602386a88f.png)

### Expected behavior

.

### Actual behavior

Nothing works... Subscriptions don't load ( Sometimes after multiple restarts they show up but clicking on any video shows server error message ... )

I can play like maybe 2,3 videos from the home screen, all other videos don't play

Search returns nothing...

I'd love to send more detailed logs but app doesn't report anything back to user? 

Newpipe at least gives you full error message when something breaks... 

### LibreTube version

0.12.0 github version

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by rozari0** [comment]
Change instance and try again

**Comment by Rstment25** [comment]
@Bnyro Not planned?

Is it not desirable for app to automatically change instance once video fails to load?


> Change instance and try again

Ty, I didn't know you could do that...
