### ISSUE TITLE
Can't play some video after update unless HLS is enabled.

### ISSUE THREAD

**Issue by rozari0** [libre-tube/LibreTube#3051]
### Steps to reproduce

1. Open https://www.youtube.com/watch?v=Wgw5ers5jA4

### Expected behavior

Should play the video.

### Actual behavior

Player doesn't do anything.

### LibreTube version

0.12.0

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
Works for me without problems

**Comment by rozari0** [comment]
> Works for me without problems

It has something to do with DASH/HLS I think, works fine when I enable DASH from **Audio & Video**.

**Comment by Qaz-7** [comment]
This video does not open when using DASH.Opens when using HLS.

**Comment by Qaz-7** [comment]
> > Works for me without problems
> 
> It has something to do with DASH/HLS I think, works fine when I enable DASH from **Audio & Video**.

Works with HLS. Does not open with DASH.

**Comment by Qaz-7** [comment]
https://user-images.githubusercontent.com/124310688/219323800-8ec95b23-d96f-495f-af82-a1875c453d46.mp4

Tested on Android 12.🤗

Please change the title.😊

**Comment by rozari0** [comment]
> Tested on Android 12

I think I wrote that before. But you missed somehow.

**Comment by rozari0** [comment]
> {"cplatform":"mobile","cbr":"app.revanced.android.youtube","cff":"SMALL_FORM_FACTOR","c":"android","cplayer":"ANDROID_EXOPLAYER_V2","cmodel":"SM-A217F","cos":"Android","csdk":"31","cbrver":"18.03.36","cver":"18.03.36","cosver":"12.SP1A.210812.016.A217FXXU8DVK1","cbrand":"samsung","videoid":"Wgw5ers5jA4","cpn":"9Doxh37T3m0ZbbxT","fmt":"134 avc1 640x360@30","afmt":"251 opus","bh":97009,"conn":3,"volume":26,"loudness":"-5.140","bat":"0.540:0","df":"10/933","time":"2023-02-16T16:25:27.262Z","glmode":"RECTANGULAR_2D","drm":"","mtext":"","error":"No errors","logged_in":"1","e":"1714250,23918597,23946420,23964928,23966208,23983296,23998056,24004644,24007246,24034168,24036947,24077241,24078649,24080738,24117491,24120820,24123943,24132305,24135310,24140247,24143331,24159074,24161116,24162919,24164186,24166867,24169501,24181174,24187043,24187377,24195035,24209350,24211178,24216201,24219713,24221292,24227054,24230811,24232551,24240251,24241378,24255165,24255543,24255545,24260378,24262346,24263796,24264343,24265964,24267186,24267564,24268142,24271689,24272786,24281897,24283015,24283093,24285788,24288047,24288664,24290971,24291857,24296354,24390674,24391539,24391709,24397801,24397985,24401544,24404640,24405623,24406327,24407191,24409682,24410023,24411252,24415866,24419823,24426636,24428619,24428902,24429093,24429652,24429850,24430520,24436009,24436800,24438073,24439483,24440132,24441240,24444960,24448383,24449913,24450027,24450367,24451033,24451289,24451771,24453129,24453840,24455312,24455741,24457198,24457333,24457884,24457969,24458100,24458566,24458684,24458839,24463785,24465011,24465099,24466462,24466509,24466835,24468350,24468724,24469888,24473091,24473652,24476021,24476250,39321511,39322111,39322615,39322730"}

Wtf is this dude?

**Comment by Qaz-7** [comment]
YouTube video debugging information.

**Comment by Bnyro** [comment]
Logs from other YT clients aren't helpful here ...
