### ISSUE TITLE
Landscape non full screen playback

### ISSUE THREAD

**Issue by radarcorr** [libre-tube/LibreTube#3054]
### Describe your suggested feature

I use a tablet when using libretube and when I don't play a video on full screen it only does portrait mode

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That would conflict with the existing auto-fullscreen option, using that is recommended.
