### ISSUE TITLE
Can't change brightness in full screen mode.

### ISSUE THREAD

**Issue by Giger22** [libre-tube/LibreTube#3055]
### Steps to reproduce

1. Start video.
2. Turn to full screen.
3. Try to change brightness in the quick panel or with swipe gesture.

### Expected behavior

1. Possibility to change brightness in full screen mode.

### Actual behavior

**Quick panel:**
"Can't change brightness in the quick panel right now because it's being controlled by the currently running app."
**Gesture**
I can change a volume by going up and down with finger and I assume you change brightness swiping left to right? It has no effect.

### LibreTube version

0.11.1

### Android version

Android 11

### Other details

Samsung A10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Try tapping on screen once (to show player buttons) then try to adjust brightness.

**Comment by Bnyro** [comment]
The brightness is controlled by swiping from bottom to top (or vice versa) at the left side of the screen.

**Comment by Giger22** [comment]
> Try tapping on screen once (to show player buttons) then try to adjust brightness.

Unfortunately this did not work in the quick panel.

> The brightness is controlled by swiping from bottom to top (or vice versa) at the left side of the screen.

Ok, this actually works.
