### ISSUE TITLE
[feature reqest] option to respect system rotation

### ISSUE THREAD

**Issue by Quantenzitrone** [libre-tube/LibreTube#3056]
Even with:
- Auto-fullscreen disabled
- Fullscreen orientation on not Auto-rotation

When in Landscape mode LibreTube rotates the video so the bottom of the video is the side of the phone facing down.
I don't want that to happen.
What if i wan't to watch a video upside down?

I think the simplest solution would be to just respect the system rotation.
I have a keyboard shortcut set up with KeyMapper to rotate my screen, because i absolutely hate auto-rotation. This way i can rotate the screen however i want it, but apps that for some, for me unclear, reason need to handle their own screen rotation, always induce anxiety.

**Comment by Bnyro** [comment]
Next time, please use an issue template!

**Comment by Quantenzitrone** [comment]
sorry, this has happend for me before
i use the octodroid github mobile app and i shouldn't write issues from there

**Comment by Bnyro** [comment]
There are no plans for that currently, I don't see a reason to watch videos upside down!
