### ISSUE TITLE
Add caption button in video player

### ISSUE THREAD

**Issue by swarnenduu** [libre-tube/LibreTube#3058]
### Describe your suggested feature

Give the option to add a button like the Autoplay button on the video player, on clicking which the caption will be turned on or off.

This will help in easy access to caption instead of 3 clicks needed to do the same currently.

### Other details

The button can be placed beside the autoplay button.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Moving this to #3058
