### ISSUE TITLE
App not opening from notification.

### ISSUE THREAD

**Issue by swarnenduu** [libre-tube/LibreTube#3059]
### Steps to reproduce

1. Play any video
2. Return to home screen or any other app
3. Slide down notification panel
4. Click on LibreTube player notification 
5. Tap the player notification 
![Screenshot_20230213-222932-347](https://user-images.githubusercontent.com/86847643/218522556-ae0e605e-cad0-4c0e-a411-842ffd802ce9.png)

### Expected behavior

App/video player should open 

### Actual behavior

The notification planel just slides up and the app remains in the background. If the video is playing, it remains playing in the background but the app doesn't open.

### LibreTube version

0.12.0

### Android version

Android 12

### Other details

The player notification and it's buttons like play/pause and seek bar itself are working. It's just that the app is not opening on tapping.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by faisalcodes** [comment]
Can't reproduce.

**Comment by swarnenduu** [comment]
Is there anything that I can do so that you can find the issue?

**Comment by faisalcodes** [comment]
You can upload a recording.

**Comment by swarnenduu** [comment]
> You can upload a recording.

https://drive.google.com/file/d/1S5jPhxyuzfbSUHPZ1feiXsOSBm07hMcK/view?usp=drivesdk

**Comment by ThomasLeigh** [comment]
I can confirm this issue. Besides, notifications about new videos: once touched, the notification just disappears, while (I suppose) it should result in opening the video within the app.

LibreTube 0.12.1
Android 10
MIUI 12.5.1

**Comment by eliwss0** [comment]
I have this same issue with 0.14.0 on a rooted Sony Xperia 5 IV running android 12. In case anyone else finds this helpful: the current workaround I made is using Tasker to open the Libretube app on `START u0 {cmp=com.github.libretube/.ui.activities.MainActivity}` logcat entry.
