### ISSUE TITLE
Player controller layout is shrinked

### ISSUE THREAD

**Issue by faisalcodes** [libre-tube/LibreTube#3068]
### Steps to reproduce

Similar to #3057, When switching back from PiP, the player controller layout is shrinked as shown in the following screenshots.

1. Play a video
2. Switch to PiP
3. Switch back

### Expected behavior

-

### Actual behavior

-

### LibreTube version

0.12.0

### Android version

Android 12

### Before
![IMG_20230214_013209](https://user-images.githubusercontent.com/62804272/218563692-eeffd246-4789-403e-b6aa-3acded2b3bcb.jpg)

### After
![IMG_20230214_013157](https://user-images.githubusercontent.com/62804272/218563756-ebff1af0-bfc1-4400-9514-c177f2f6ee7f.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by swarnenduu** [comment]
Yes this happens to me as well. But the controller layout returns to normal once the video is made to full screen, but again shrinks when switched back from PIP mode.
