### ISSUE TITLE
Navigation buttons get in the way of player UI element

### ISSUE THREAD

**Issue by Pentaphon** [libre-tube/LibreTube#3069]
### Steps to reproduce

See screenshot. The last player UI element on the top right is covered by the navigation button bar. 
![Screenshot_20230213-115754](https://user-images.githubusercontent.com/49374058/218563270-383fbd26-2043-4cb7-8788-0412af5de86c.png)

### Expected behavior

Navigation button bar should not get in the way of the player UI.

### Actual behavior

Navigation button bar overlaps the player UI. When the navigation buttons go away, so does the player UI, which reduces functionalily. 

### LibreTube version

0.12

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Pentaphon** [comment]
> Shouldn't the navigationbar be hidden in fullscreen mode?

It shows up when you tap once.

**Comment by KrychuTM** [comment]
https://user-images.githubusercontent.com/79592592/218858905-8e85a4d2-b014-4c6c-a43c-5291d73199f0.mp4

https://user-images.githubusercontent.com/79592592/218858904-36bcbbc8-1ba3-43af-a80b-6016d1d90f30.mp4

**Comment by socynx** [comment]
https://user-images.githubusercontent.com/125415316/218890228-9129bc33-5831-484f-bc88-a7314bfd68ac.mp4

**Comment by xipe-totek** [comment]
I have this problem on tablet (HTC a101, Android 11). system navigation bar completely hides player buttons. but if you tap on the triangle, it become like on the second screenshot. so it is more inconvinience than a problem. because you need tap on that triangle button every time. ![Screenshot_20230228-094745.png](https://user-images.githubusercontent.com/81915152/221777873-271e35f0-fd47-480d-9aa8-b1e5d8325448.png)
![Screenshot_20230228-094830.png](https://user-images.githubusercontent.com/81915152/221778375-0db7c0f3-6600-46bc-ad5d-b25365d56759.png)

**Comment by Bnyro** [comment]
Has the latest release fixed that?

**Comment by Pentaphon** [comment]
> Has the latest release fixed that?

The buttons don't show up anymore in fullscreen so technically it has. I'd wait to hear what other people think.

**Comment by CactiChameleon9** [comment]
> If nobody responds in a week, I'll close this issue as fixed.
Would you possibly waiting until the f-droid update (if it is longer than a week)? I have it installed from there, so it can take a bit of time until the latest updates arrive.

**Comment by Pentaphon** [comment]
> Would you possibly waiting until the f-droid update (if it is longer than a week)? I have it installed from there, so it can take a bit of time until the latest updates arrive.

No, I use the Izzydroid repo which is already up-to-date. I am just waiting a few days for at least 1 other person to confirm the issue is fixed. Have you confirmed this is fixed?

**Comment by CactiChameleon9** [comment]
**I am** using f-droid, so I cannot test yet (hence me asking)

**Comment by Pentaphon** [comment]
> **I am** using f-droid, so I cannot test yet (hence me asking)

Ah yes. I see. Another reason to wait then.

**Comment by xipe-totek** [comment]
I've installed last version from github and now system buttons don't show up in fullscreen mode, so everything is fine. thanks to the man who fixed it.
