### ISSUE TITLE
Clicking comment text doesn't open the replies

### ISSUE THREAD

**Issue by d4f5409d** [libre-tube/LibreTube#3070]
### Steps to reproduce

Watch a video
Check comments
Try to check reply on the first comment by tapping on the text
Experience it only works when clicking near the replies icon

### Expected behavior

It should open replies even when clicking texts like on other comments do.

### Actual behavior

It doesn't open it via clicking the text part only the icon

### LibreTube version

0.12.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by swarnenduu** [comment]
I am on Android 12. Tapping on full first comment works fine for me while opening replies.

**Comment by faisalcodes** [comment]
This issue is reproducible. The issue is because of HTML links in the comment text. If a comment has links then the touch will never be sent to the TextView. This also applies to other places.

**Comment by swarnenduu** [comment]
Yes, you're right.
