### ISSUE TITLE
Options to remove certain video player buttons.

### ISSUE THREAD

**Issue by swarnenduu** [libre-tube/LibreTube#3072]
### Describe your suggested feature

![Screenshot_20230213-225414-048](https://user-images.githubusercontent.com/86847643/218627202-a882604e-af20-4404-b8c8-f0d27c0262c1.png)
To give an option to hide these buttons, like the Autoplay button.

Sometimes the sponsorblock button comes in which I don't like to be here.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
So an option to disable the SponsorBlock button would be sufficient?

**Comment by NeeRaj-2401** [comment]
> So an option to disable the SponsorBlock button would be sufficient?

i think i have mentioned this earlier too, Every have different choices for video player buttons, 
some wants their specific(quality,speed,captions) & some wants it clean(no optins or limited)

**Comment by Bnyro** [comment]
Moving this to #3058

**Comment by swarnenduu** [comment]
> So an option to disable the SponsorBlock button would be sufficient?

Yeah it would be great.
