### ISSUE TITLE
Navigation issue in fullscreen

### ISSUE THREAD

**Issue by KrychuTM** [libre-tube/LibreTube#3075]
### Steps to reproduce

1. Open any video.
2. Switch to landscape fullscreen
3. Tap to bring up media controls

### Expected behavior

When tapping during fullscreen the phone's navigation system shouldn't be shown. Because of this it takes two taps just to pause, seek the video, etc.

### Actual behavior

Instead when the video is tapped the navigation bar covers the video. It also happens when using gesture navigation.

### LibreTube version

Version 0.12.0

### Android version

Android 11

### Other details

https://user-images.githubusercontent.com/79592592/218767092-e3fadd84-37e7-4ec8-b394-dd260901a8e1.mp4

https://user-images.githubusercontent.com/79592592/218767104-3fc59093-b239-4ac7-a0f2-635d0037fea0.mp4

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by KrychuTM** [comment]
Just noticed that this night be a duplicate of #3069. Sorry. Added videos for more clarity.

**Comment by xIUPITERx** [comment]
Please add your videos in #3069 and close this issue.
