### ISSUE TITLE
Download playlist and list whole playlist under download

### ISSUE THREAD

**Issue by Dan-Sun** [libre-tube/LibreTube#3080]
### Describe your suggested feature

Hi!

I also use libretube for bluetooth to listen to music. 

At the moment you can only download a video/audio one at a time. It would be great if you could click (hold) on a playlist and get the option to download the entire playlist. Once downloaded, it would be good to list the playlist in the download section and not each video at once. 

Via bluetooth, there is no skip function for the video/audio file at the moment. At least I can't skip to the next clip. I always have to go back and start the next one manually.

Thanks! It's a really great app! 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by go2null** [comment]
key one is download a playlist, the others are seconday (for me)
