### ISSUE TITLE
Please add Google login option 

### ISSUE THREAD

**Issue by fisforfaheem** [libre-tube/LibreTube#3083]
### Describe your suggested feature

Its pretty much useless without my account and current method is crazy difficult 

### Other details

Please enable 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by faisalcodes** [comment]
Kindly read this [Roadmap](https://github.com/libre-tube/LibreTube/blob/master/ROADMAP.md)

**Comment by fisforfaheem** [comment]
how to get my subs and recomendatirosn?



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
02/15/23,
04:13:58 PM

**Comment by fisforfaheem** [comment]
useless app u cant even login
