### ISSUE TITLE
Convert the downloaded video to audio.

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3084]
### Describe your suggested feature

Option to convert downloaded video to audio without internet connection. For this there are converter apps like Mp3 etc. But in LibreTube this option is important because the video is stored in the app.❤

### Other details

Thanks in advance

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by rozari0** [comment]
Just use Seal or something like that. 
This feature will just make LT a bloatware.

**Comment by Bnyro** [comment]
True, apart from that it's a duplicate.
