### ISSUE TITLE
Disable video progress seekbar tapping🤠

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3085]
### Describe your suggested feature

Option to disable single tap on video progress seekbar in player.This is useful for me.Because accidental touching can be prevented

### Other details

ON/ Off

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by NeeRaj-2401** [comment]
> Because accidental touching can be prevented

Lock the player controls 😂

**Comment by Qaz-7** [comment]
But I would like to close this option only.

**Comment by Bnyro** [comment]
No plans for that.
