### ISSUE TITLE
Lower quality when video isn't full screen

### ISSUE THREAD

**Issue by Seb3thehacker** [libre-tube/LibreTube#3088]
### Describe your suggested feature

The official YouTube app has an option to decrease video quality when a video it is not in full screen (usually this is portrait mode). This would be a worth while feature since it significantly reduces stress on Piped instances and users' personal data usage.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please share some ideas how this should be implemented?
Should we make a new preference for that in the settings called `Lower quality when not fullscreen` and automatically use a 30% or 40% lower resolution in portrait when the preference is enabled?

**Comment by Seb3thehacker** [comment]
> Please share some ideas how this should be implemented?
> Should we make a new preference for that in the settings called `Lower quality when not fullscreen` and automatically use a 30% or 40% lower resolution in portrait when the preference is enabled?

That would work. You could call it "Portrait mode quality." Although I was thinking the user could set the specific quality they want when in portrait mode. This seems to be 480p in the official YT app, which seems like a good balance. A percentage could definitely be an option too. It might also be worthwhile to consider screen size.

If we detect when the popup player is used, we could also implement this there as a separate config.

This could also be taken further, and LibreTube could ask the instance just for audio when the screen is off. Once the screen is back on it  should probably immediately request video again though. 

Ideally I'd like to be able to set the quality I want when in portrait mode, and configure if it will immediately (or wait until its caught up) render the landscape quality when rotated.

Thanks!!!

**Comment by Seb3thehacker** [comment]
@Bnyro Also, the vertical player for Shorts is probably considered portrait but full screen. Maybe a better way of doing this would be to set full screen quality and then separately set non-fullscreen quality. Possibly differentiating the pop up player quality from fullscreen and normal portrait mode. 

Also, for some reason when watching Shorts the video quality is somewhere around 840p instead of 1080p, could this be because of the different dimensions of vertical videos? This would ideally be factored in as well.

Thanks!!

**Comment by Bnyro** [comment]
> This could also be taken further, and LibreTube could ask the instance just for audio when the screen is off. Once the screen is back on it should probably immediately request video again though.
>
This has been implemented with the latest release :)

> Also, for some reason when watching Shorts the video quality is somewhere around 840p instead of 1080p, could this be because of the different dimensions of vertical videos?
>
That might be possible, but I don't really see any reason to apply changes to the video dimensions there.
