### ISSUE TITLE
To update from a new version to an old version

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3089]
### Describe your suggested feature

A chance to update to an old version without any problems even if the application is in a new version. This is possible in the Seal application.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Apart from it not making sense, create backup, uninstall the app and then import the backup in the old installation.
