### ISSUE TITLE
Register and login button result in network error

### ISSUE THREAD

**Issue by RiccardoBarbieri** [libre-tube/LibreTube#309]
### Steps to reproduce

Try to register a new account or login to an existing one

### Expected behavior

Register or login 

### Actual behavior

Network error message

### LibreTube version

8

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That is probably a issue of the instance you are using, try another.

**Comment by Bnyro** [comment]
closing because it's probably an instance issue (if it's really an issue)
