### ISSUE TITLE
Icon when a new version is available

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3090]
### Describe your suggested feature

When a new version is available, mark it as a Point in the update check section.Also above the 3-dot menu.🤗

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That would require us to check for new releases on every app start, in fact that should only be done when the user manually asks for it because it will connect the user with the GitHub servers. Thus, not planned.
