### ISSUE TITLE
Error creating playlist.

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3102]
### Steps to reproduce

1.Enter a playlist name.
2.Create a playlist
3.Error

### Expected behavior

The playlist should be created without any problems.

### Actual behavior

https://user-images.githubusercontent.com/124310688/219585754-1aab7b75-ea39-4ceb-9aa1-278b4772f1ab.mp4

### LibreTube version

0.12.0 Latest Debug

### Android version

Android 12

### Other details

I couldn't access the app after the error occurred. That's why there is no error report

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Seems to happen only when using without an account, though I can't remember any related commit recently.
