### ISSUE TITLE
Clearer sound quality.

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3105]
### Describe your suggested feature

On LibreTube, the video sound is noisy. On YouTube, the video sound is clean and clear. That's what he says at home.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's most likely due to your network connection, it automatically chooses the best for you.
