### ISSUE TITLE
Default playback speed setting not rounded to one decimal place

### ISSUE THREAD

**Issue by canac** [libre-tube/LibreTube#3107]
### Steps to reproduce

1. Go to the Settings > Player page
2. Set the default playback speed to 1.6

### Expected behavior

The Playback speed should show 1.6

### Actual behavior

The Playback speed shows 1.5999998

### LibreTube version

0.12.0

### Android version

Android 13

### Other details

This is a beautiful app! I've loved using it so far.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by canac** [comment]
@Bnyro I believe the linked PR added rounding for the sheet that pops up in the video player, but it still isn't rounded in the settings page under Settings > Player > Playback speed. Can you re-open this issue?

**Comment by Bnyro** [comment]
For me it's rounded properly there too, please make sure to use the latest version. Otherwise feel free to create a new issue with a screen recordning.

**Comment by canac** [comment]
Sure thing. Here's the new issue report, which includes a screen recording: #3447
