### ISSUE TITLE
Any chance to add newpipe like functionality where videos are directly taken from youtube

### ISSUE THREAD

**Issue by lthedetective** [libre-tube/LibreTube#3108]
### Describe your suggested feature

So basically UI and UX of libretube is much better than newpipe but the piped instances are almost always down and not reliable so it would be great if videos could also be directly sourced from youtube.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
No plans for that.
