### ISSUE TITLE
Not added to Weblate.

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3114]
### Describe your suggested feature

![Screenshot_20230218-160431_LibreTube Debug](https://user-images.githubusercontent.com/124310688/219864882-8390fded-1566-4454-9208-e77454f0d35d.jpg)
![Screenshot_20230218-160312_LibreTube Debug](https://user-images.githubusercontent.com/124310688/219864884-03e4b2d6-29e4-4b2e-9fcd-96542fda7ad7.jpg)

### Other details

🤷‍♂️

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Those are provided by Piped.
