### ISSUE TITLE
Sleep timer time limit

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3115]
### Describe your suggested feature

Limit the sleep timer to 1440 minutes.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by tusharhero** [comment]
I don't understand, is the sleep timer (Playing the video for 15 minutes and then asking the user if they want to continue and if they do not respond just close the video) already available in `LibreTube`?

**Comment by Bnyro** [comment]
> I don't understand, is the sleep timer (Playing the video for 15 minutes and then asking the user if they want to continue and if they do not respond just close the video) already available in `LibreTube`?
>
Yes, it is. Settings -> General -> Sleep timer.
