### ISSUE TITLE
Warnings.

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3117]
### Describe your suggested feature

1.Warning when adding to bookmarks on channel page

2.If there is no playlist, a warning when you click the Add to playlist button

### Other details

https://user-images.githubusercontent.com/124310688/219871802-5365b9a9-430a-47c1-a6db-8eb13110ca84.mp4

https://user-images.githubusercontent.com/124310688/219871964-0c5a9c8c-9733-49c8-9a33-62d29d4f958b.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
1. Adding a bookmark is not a destructive action and thus should not require a warning.
2. They get fetched dynamically, when you click the add to playlist button the app does not yet know if there are any playlists available.
