### ISSUE TITLE
Player buttons don't show on small phones

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#312]
I don't see the buttons on the Video player on LibreTube. My device is Android 5.1. Display Size-10.16 cm (4 inch)
See screenshot for more details!
![IMG-20220525-WA0000](https://user-images.githubusercontent.com/104249296/170202063-349df9aa-6845-49e0-8acd-408059ab101d.jpg)
![Screenshot_20220525-110352_Chrome](https://user-images.githubusercontent.com/104249296/170202067-356a963a-2ae0-4964-998a-e4df16cda605.jpg)
As you can see, it only sees two buttons.

**Comment by Bnyro** [comment]
How is it in 0.2.7?

**Comment by Legoks** [comment]
It's the same!

**Comment by Bnyro** [comment]
I currently have no idea how that could be resolved

**Comment by Legoks** [comment]
In fact it appears and then disappears

**Comment by Legoks** [comment]
Suddenly it appears.

**Comment by Bnyro** [comment]
workaround: use latest ci builds, lock and unlock the video after starting to play it

**Comment by Nizami20052022** [comment]
How do I do that?

**Comment by Nizami20052022** [comment]
Can't you fix this problem?

**Comment by Nizami20052022** [comment]
I think you need to add a locking function.

**Comment by Nizami20052022** [comment]
![Screenshot_20220625-163120_Video](https://user-images.githubusercontent.com/104249296/175773558-76079079-d8f9-4042-b2db-e7e47f2ab726.jpg)

**Comment by Bnyro** [comment]
I added it... Please turn on your brain

**Comment by Nizami20052022** [comment]
Will it be resolved in the new update?

**Comment by Nizami20052022** [comment]
If you have solved it, you will close this issue.

**Comment by Nizami20052022** [comment]
But the answer is in the spring.

**Comment by Nizami20052022** [comment]
Write answer.
