### ISSUE TITLE
Delete one of the same button.

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3125]
### Describe your suggested feature

Delete one of the same buttons that perform the same function

### Other details

https://user-images.githubusercontent.com/124310688/219958906-25ca3fcc-edcd-40e2-9f75-f9bd5f72d12b.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The bottom sheet is also used in other places, therefore adding an extra parameter that disables it doesn't seem worth it to me.
