### ISSUE TITLE
Automatic switching between servers.

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3137]
### Describe your suggested feature

Direct switching function from one server to another by automatically selecting a supported and fast server.This will be helpful.

### Other details

A similarity like automatic video quality selection function. Choosing a server manually is difficult. Thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That has already been discussed in other issues and is not planned.
