### ISSUE TITLE
Network Error!

### ISSUE THREAD

**Issue by Legoks** [libre-tube/LibreTube#314]
Network error occurs a lot after the last update!

**Comment by Bnyro** [comment]
Did you try to use another instance?

**Comment by Legoks** [comment]
Yes!

**Comment by Legoks** [comment]
I do not know why it happened!

**Comment by Legoks** [comment]
When leaving the application, the application crashes

**Comment by Legoks** [comment]
![Screenshot_20220525-115917_Device care](https://user-images.githubusercontent.com/104249296/170212508-d2725476-4211-4e86-bc9f-72fbe7e29888.jpg)

As you can see, there is information about application crashes in the Device Care section!

**Comment by Bnyro** [comment]
Can you send the debug logs then?

**Comment by Legoks** [comment]
How do I do that?

**Comment by Bnyro** [comment]
https://help.testlio.com/en/articles/129738-how-to-get-logs-from-your-android-device

**Comment by Legoks** [comment]
I can't do that!

**Comment by Legoks** [comment]
Thank you very much

**Comment by Legoks** [comment]
Pay attention to the other problem I mentioned
