### ISSUE TITLE
Add option for Auto Backup

### ISSUE THREAD

**Issue by JohnBetaro** [libre-tube/LibreTube#3144]
### Describe your suggested feature

I'm someone from many people who use the app to subscribe locally without creating an account on the instance, mainly because you will not be able to access your things when an instance goes down (and it happens a lot), please consider adding an option for auto backup to settings and everything, it is a pain to make backups every time we add a new playlist, bookmark or just subscribe to a new channel.

And also deleting the previous backup when a new one is created (like Signal does).

Thank you for your time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by yoguut** [comment]
@JohnBetaro can you go into more details in terms of how the UI is going be presented? such as
- where do you want to expose this feature as a button?? under settings??
- what happen in a scenario where the user has explicitly created a backup on a specific date. Then when the app detects it's time for backup and then generates a backup file, then proceed to delete that file the user had explicitly created, because that file is technically a older backup. How should we handle edge case like this?

**Comment by yoguut** [comment]
@JohnBetaro yah i think the different name strategy should work ok to avoid unintended deletions.

so far here what i imagine the flow goes:

```mermaid
flowchart LR
A[tap auto backup btn] --> B{present options for which files to backup}
B -- found existing backup --> C[save backup to selected file directory]
C -- deletion success --> D{delete existing backup}
B -- didn't find existing backup --> C
```

**Comment by yoguut** [comment]
@Bnyro I think I can take a look at this issue. no promise though. because I haven't learnt how to allow the Android app to schedule background jobs when the app lifecycle is not initialized. :)

**Comment by yoguut** [comment]
@JohnBetaro  yes that's actually what I think I would fallback to if I get into a hard time of trying to make things work with background job scheduling. :)

**Comment by Bnyro** [comment]
@yoguut You can take a look at the NotificationWorker, you likewise want to use a `CoroutineWorker` too! For getting permanent permissions on and choosing a directory to be able to create backups, see https://github.com/Bnyro/WallYou/blob/main/app/src/main/java/com/bnyro/wallpaper/util/PickFolderContract.kt. You can use that just like you would call other `rememberActivityForResult` calls in the BackupSettings.

**Comment by Reinachan** [comment]
I'd suggest having an option for how far back you want to keep backups. Sometimes when I open the app and the instance is having issues, backups of subscriptions don't seem to work. And when this happened today, I ended up losing all but three of them when changing instance. If that was backed up then, the backup would be kinda useless. I'd want to keep around the last 5 days or so at the very least.

(am looking for an existing issue of the other stuff mentioned above. Will create one later if I can't find any)

**Comment by JohnBetaro** [comment]
Seedvault does the job pretty well of backing up everything, I'm closing the issue because I don't need this feature, will reopen it if anything changes in the future.
