### ISSUE TITLE
Number of servers

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3147]
### Steps to reproduce

1.Go to the instance section and see instances immediately.
2.The instance number is small
3.Wait a minute.
4.The number of instances has increased

### Expected behavior

The number of instance should be large.

### Actual behavior

https://user-images.githubusercontent.com/124310688/220339016-03101338-e105-4f18-b608-9bb214baa191.mp4

### LibreTube version

0.12.0 Latest Debug

### Android version

Android 12

### Other details

Also, when the instance number is small, there is a problem when choosing a server

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's because the instances get loaded dynamically, which requires some time to process the request.
