### ISSUE TITLE
`in-app` instances status

### ISSUE THREAD

**Issue by NeeRaj-2401** [libre-tube/LibreTube#3152]
### Describe your suggested feature

Just a question.
is it any way possible  to add in-app instance status ?. [status.piped.video](https://status.piped.video/)

If so, choosing the best instance working at time will become easy and convenient based on its response time. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It's recommended to use the Piped uptime (there's a GitHub repo), if we did something like that on our own, that would just be a lot of server traffic (since every client would ping each server) which is not really needed.

**Comment by ehea617** [comment]
> It's recommended to use the Piped uptime (there's a GitHub repo), if we did something like that on our own, that would just be a lot of server traffic (since every client would ping each server) which is not really needed.

Why not parse https://github.com/TeamPiped/piped-uptime/blob/master/README.md for the instance status and response time information so the servers are not being pinged by individual devices?
