### ISSUE TITLE
New UI concept at adding playlists

### ISSUE THREAD

**Issue by d4f5409d** [libre-tube/LibreTube#3161]
### Describe your suggested feature

I made a fast concept art, this is how I think the playlist adding and cloning UI should look in the future. I took inspiration from the Seal FOSS youtube-dlp application.

![IMG_20230222_125754](https://user-images.githubusercontent.com/76624594/220616116-3cf088cb-51f2-4d3f-acf6-1f604df73375.jpg)

The Seal FOSS app:
![Screenshot_2023-02-22-12-58-20-22_2b0c70832456616f1f794bb05bb8d2fa](https://user-images.githubusercontent.com/76624594/220616156-603e2632-e4c6-42b0-af23-b18e15aafba6.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thanks for the UI suggestions, however, that dialog already got redesigned recently and there currently are no plans to change its UI once again.
