### ISSUE TITLE
Small problem with the home page.

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3162]
### Describe your suggested feature

Incorrect display when touching home page.The color is visible shortly after opening the application.

### Other details

https://user-images.githubusercontent.com/124310688/220645744-d7814734-aa8e-49ca-b347-937759732093.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
I don't really see the bug.

**Comment by Bnyro** [comment]
I can't see an issue here either.
