### ISSUE TITLE
Trends page become home page

### ISSUE THREAD

**Issue by Eliya-Manoj** [libre-tube/LibreTube#3163]
### Steps to reproduce

1. Enable trends and disable home 
2. Restart application
3. Trends page become home page (issue)

### Expected behavior

Only show trending videos

### Actual behavior

Trends page become home page (show home page contents like featured, bookmark, playlist)

### LibreTube version

0.12.0 Latest Debug

### Android version

Android 12

### Other details

https://user-images.githubusercontent.com/90308888/220725086-b40a45d3-01a0-48dd-953a-2da4241f48d0.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
See #3121, you need to select a different home tab by pressing the home icon in the nav bar settings.
