### ISSUE TITLE
Comment Tweaks

### ISSUE THREAD

**Issue by akano12** [libre-tube/LibreTube#3166]
### Describe your suggested feature

[First]
When copying a comment that's written on multiple lines (using break lines) the copied text will have `<br>` tag and the text won't be copied as previewed (instead of copying the text as posted, everything will be on same line separated by `<br>`tag) 

[Second] 
There's a small issue when trying to copy a pinned comment, long pressing on pinned comment won't do anything, you'll have to long press either above or below it to copy. 

[Third] 

Make it possible to mark text from a comment to copy instead of copying the entire comment on long press. 

### Other details

1.**For the `<br>` issue**

For example, when copying text from the image below 

![Screenshot_20230223_110731_LibreTube](https://user-images.githubusercontent.com/50032603/220865280-c4ca24cd-db4c-416c-967a-a6dd759d0dbc.jpg) 

You'll get this:

Thou art gone, thy life hast fled`<br>`All shall now bewail the dead`<br>`No more flesh and no more bone`<br>`No more trouble to bemoan`<br>`Like a wave along the shore`<br>`You have passed, you will complain nevermore`<br>``<br>`The late, late lamented`<br>`For death can’t be prevented<br>Nevermore tormented`<br>`The late, late lamented`<br>``<br>`No more feast`<br>`Now rest in peace`<br>`o more pain`<br>`You can’t complain`<br>`No more sighs and no more cries`<br>`No more fears, no more tears`<br>`No more laughs

2.**For pinned comment issue:**

https://user-images.githubusercontent.com/50032603/220867278-45f14969-808e-4380-bd2c-380945aceb68.mp4 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
2. is a duplicate of #3070, everything else should work now.

**Comment by Snailhail** [comment]
1: Open comment popup
2. Short hold on comment to begin copy
3. Drag to desired amount
4. Touch prompt to copy

When pulling up a comment you should be able to copy by short pressing It then dragging the selector to the personal amount. Follow by the prompt to copy

Android 14

On 0.21.0 selectable comments from the popup don't work, but description works as intended.

**Comment by akano12** [comment]
> 1: Open comment popup
> 2. Short hold on comment to begin copy
> 3. Drag to desired amount
> 4. Touch prompt to copy
> 
> When pulling up a comment you should be able to copy by short pressing It then dragging the selector to the personal amount. Follow by the prompt to copy
> 
> Android 14
> 
> On 0.21.0 selectable comments from the popup don't work, but description works as intended.
> 

Ye i noticed this too, not sure why it was changed.
Open a new issue
