### ISSUE TITLE
`Sponsorblock markers` not visible 

### ISSUE THREAD

**Issue by NeeRaj-2401** [libre-tube/LibreTube#3170]
### Steps to reproduce

Enable sponsorblock and toggle **markers** on

### Expected behavior

Sponsored segment timeline should be highlighted on seekbar.

### Actual behavior

Marker absent.

https://user-images.githubusercontent.com/88180887/220988738-4a5b729e-b00e-4ea2-a435-4d8b79f62ce1.mp4

### LibreTube version

0.12.0 and Latest debug

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
And often the position of the marker is not precise.
I thought I alreade made an issue for that, but wasn't able to find it 🤔.

**Comment by Bnyro** [comment]
Can't reproduce.

**Comment by NeeRaj-2401** [comment]
> Can't reproduce.

@Bnyro 

<img src="https://user-images.githubusercontent.com/88180887/222793240-3ba6e926-d9de-4701-ae71-6f7982e89d5a.jpeg" width="30%">

===

<img src="https://user-images.githubusercontent.com/88180887/222793246-f939dd5a-634b-4fa2-885d-ab36219aec30.jpeg" width="30%">

**Comment by xIUPITERx** [comment]
https://user-images.githubusercontent.com/97352673/222794590-806065a6-d5c2-4f11-adc8-6dc138b6c3c2.mp4

https://www.youtube.com/watch?v=oe_oANMZOa4
