### ISSUE TITLE
Option to show dislikes as percentage 

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3176]
### Describe your suggested feature

Added an option to show ReturnYouTubeDislikes as a percentage of all votes.

### Other details

Thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by rozari0** [comment]
Isn't that really unnecessary?

**Comment by Bnyro** [comment]
I agree with @rozari0, this would be really useless since even when you know the percentage, that doesn't tell you much about the video's quality.
