### ISSUE TITLE
Something Isn't Handled Properly 

### ISSUE THREAD

**Issue by akano12** [libre-tube/LibreTube#3177]
### Steps to reproduce

Sorry for the ambiguity in the title as i don't know why LT is acting like this. 

1. Play [this](https://piped.video/watch?v=JDIbjcOSqyk) video. 
2. Skip to the end of the video while having autoplay button toggled from player.

https://user-images.githubusercontent.com/50032603/221215424-e9d26e6d-2208-4587-9693-0bfa7c977e98.mp4

### Expected behavior

Play next video

### Actual behavior

1. Get an error. (There's an error with the current server, try another instance?)

2. Comments get disabled on current video. 

### LibreTube version

0.12

### Android version

Android 13

### Other details

Tried playing some other videos after encountering this issue and all played fine (except where the next video has 0 duration), noticed that if autoplay next video is disabled, error won't happen.
So i checked the upcoming videos and saw that the next vidoe has 0 duration. 

![Screenshot_20230224_170130_LibreTube](https://user-images.githubusercontent.com/50032603/221214765-5ff2f102-6f3f-429b-b990-d5a3579cd0e8.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Apparently Piped returns playlists as related streams.

**Comment by Bnyro** [comment]
That might be an issue in the NewPipe Extractor that those videos can't get fetched properly? Not sure.

**Comment by akano12** [comment]
> That might be an issue in the NewPipe Extractor that those videos can't get fetched properly? Not sure.

Tried playing the same video on Piped web, toggled "Auto Play Next Video",
after the video ended Piped redirected me to the playlist page ([link](https://piped.video/playlist?list=PLGYIVquUuqV1poPN0zEcRMAkpuWhIjljW&fullscreen=false)) and didn't play anything.
Also there wasn't any issue with video duration.

**Comment by zerowu49** [comment]
Checked this [playlist link](https://piped.video/playlist?list=PLGYIVquUuqV1poPN0zEcRMAkpuWhIjljW&fullscreen=false) on Piped and Youtube, perfectly sorted playlist. The issue right now is that @akano12 looks like using local playlist which maybe he/she already add public video and upon the time of playing the playlist, the video already turns into unlisted/private video. Correct me if I'm wrong.

**Comment by akano12** [comment]
> Checked this [playlist link](https://piped.video/playlist?list=PLGYIVquUuqV1poPN0zEcRMAkpuWhIjljW&fullscreen=false) on Piped and Youtube, perfectly sorted playlist. The issue right now is that @akano12 looks like using local playlist which maybe he/she already add public video and upon the time of playing the playlist, the video already turns into unlisted/private video. Correct me if I'm wrong.

I don't have any playlists, in the screenshot above i just tapped on playlist icon from the player to see what it does and saw that some videos have 0 duration.

Also try playing [this](https://piped.video/watch?v=JDIbjcOSqyk) video on Piped while having auto play toggled.

**Comment by akano12** [comment]
Check this

https://user-images.githubusercontent.com/50032603/221367530-5bf86089-d24e-4862-89e3-bafe709a50d1.mp4
