### ISSUE TITLE
Hide exposed Delete button in custom playlists or introduce Undo function?

### ISSUE THREAD

**Issue by U-Gautam** [libre-tube/LibreTube#3180]
### Describe your suggested feature

How does everyone else feel about this? The delete button/UI being exposed all the time for custom playlists and even individual videos. I would say,
- it doesn't look good visually,
- prone to user mistake- where I can delete videos by tapping on it once and it will be gone....
- no undo button if i hit the delete button by mistake. 

My suggestion would be to hide the delete function under Long tap or even iOS-y design.. I don't know but that delete button is a trouble waiting to happen.

### Other details

![Screenshot_20230225-123457](https://user-images.githubusercontent.com/92106554/221329081-a05b6b01-06ca-4b61-b673-d81c9b1382fb.png)
![Screenshot_20230225-123512](https://user-images.githubusercontent.com/92106554/221329106-23998cf2-9716-4dd9-8aef-6cb3efc559ce.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by chriskangr** [comment]
the same from me!
