### ISSUE TITLE
Playback resumes old video on app resume

### ISSUE THREAD

**Issue by newhinton** [libre-tube/LibreTube#3187]
### Steps to reproduce

Example:
 1. Start App, watch any video
 2. Stop Video in the middle, close app

Wait for a while

 3. Open App

### Expected behavior

The app opens, and the old video is minimized, but not playing.

### Actual behavior

The app opens, and the old video is minimized. The video immediately resumes playing.

#### Reasoning behind this:

Usually, after not using libretube for a while, i either want to look for what's new, or want to watch a specific video. What i dont want is to immediately continue watching the OLD video, which may even be completely useless (This is often the case if another app opened a video in libretube) because the user-context why this video was open is lost by then.

Also, immediately beeing confronted with the noise of a video can be startling, or distracting if you are in a place where noise can be detrimental.

### LibreTube version

0.12.0

### Android version

Android 11, LineageOS

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by gbieging** [comment]
I have a feeling this might be related to #3245

Depending on elapsed time, if it hasn't been too long,  this happens, with more time #3245 happens

At least for me

**Comment by Bnyro** [comment]
Please test the latest debug builds with "Pause on quit" in the player settings enabled.

**Comment by Bnyro** [comment]
Assuming this fixes the issue.

**Comment by newhinton** [comment]
@Bnyro Sorry, i was just today able to test the latest 0.20.1
The behaviour is still there. I started a video roughly an hour or two, but then paused it and left the app back to the homescreen. When i opened libretube just now, it immediately started autoplaying that video.

Can you please reopen this ticket?

**Comment by newhinton** [comment]
You can reproduce the issue the following way:

1. Start libretube, and any video. 
2. Pause the video
3. Close the app (Eg go back to the homescreen, DONT remove it from the backstack)
4. Enable hibernation:

`adb shell device_config put app_hibernation app_hibernation_enabled true`

5. Put app to sleep:

`adb shell cmd jobscheduler run -u 0 -f com.github.libretube.debug 2`

6. Open app via laucher, wait for video to auto-play

**Comment by akano12** [comment]
> You can reproduce the issue the following way:
> 
> 1. Start libretube, and any video. 
> 2. Pause the video
> 3. Close the app (Eg go back to the homescreen, DONT remove it from the backstack)
> 4. Enable hibernation:
> 
> `adb shell device_config put app_hibernation app_hibernation_enabled true`
> 
> 5. Put app to sleep:
> 
> `adb shell cmd jobscheduler run -u 0 -f com.github.libretube.debug 2`
> 
> 6. Open app via laucher, wait for video to auto-play
> 

https://github.com/libre-tube/LibreTube/issues/5272
