### ISSUE TITLE
Duplicate Download Data 

### ISSUE THREAD

**Issue by zerowu49** [libre-tube/LibreTube#3190]
### Steps to reproduce

1. Download first video
2. Download second video
3. Open "Downloads" Tab (Picture 1)
4. Navigate to another Tab, e.g. "Library"
5. Come back to "Downloads" Tab (Picture 2)

Picture 1
![image](https://user-images.githubusercontent.com/22422143/221363842-7fd104ec-30d5-4016-8074-f99b21a7ddd8.png)
Picture 2
![image](https://user-images.githubusercontent.com/22422143/221363883-9efc471c-3c4f-45d5-92c5-58f4901f10b4.png)

### Expected behavior

Upon come back to "Downloads" Tab, data **doesn't get** added to List of downloaded data. I think this because lack of data & condition checking. 

### Actual behavior

Upon come back to "Downloads" Tab, data **get** added to List of downloaded data.

### LibreTube version

0.12.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't reproduce on different devices, tried downloading multiple videos too.
Thus, I believe it's been fixed recently.
