### ISSUE TITLE
Low quality thumbnails

### ISSUE THREAD

**Issue by eightyy8** [libre-tube/LibreTube#3192]
### Steps to reproduce

1. Either view current video recommendation or the currently playing on your operating system
2. Low quality thumbnails

### Expected behavior

Normal quality thumbnails

### Actual behavior

Shit quality thumbnails

### LibreTube version

0.12.0

### Android version

Graphene OS Android 13

### Other details

**Here are screenshots**

Video recommendation thumbnails:
![Screenshot_20230225-193400_1](https://user-images.githubusercontent.com/64216434/221381361-5d6f8699-0793-4cde-886f-7ada1cac87bd.png)

Currently playing thumbnails:
![Screenshot_20230225-214831_1](https://user-images.githubusercontent.com/64216434/221381362-7c4a17fb-6c54-4e95-916d-7766118f1785.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by eightyy8** [comment]
They are also low quality on the homescreen or any other similar view, but much less of a priority. It seems like they all use the same resolution

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/2274#issuecomment-1339835067
