### ISSUE TITLE
Make downloads accessable outside of app

### ISSUE THREAD

**Issue by ViktorKahu** [libre-tube/LibreTube#3193]
### Describe your suggested feature

Currently, downloads are accessable in-app only.

This makes no sence for multiple reasons, mainly:

1) If I need to access the downloaded file through Libre Tube, there is no point of downloading it in the first place because I can just open your app and stream it at any time.

2) anyone can still go to /Android/Data/LibreTube and copy/move the downloaded file to any desired location - so the ability is there to begin with, just implemented in an extremely inconvenient way.

The download feature should have an option to pick the desired folder eg: Music so people can easily access the file with a music player.

Regards 

### Other details

Please consider an implementation of the feature similar to NewPipe.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Not sure if this going to happen. If i recall correctly, Bnyro made it clear (in old issue) that downloads are only meant to be accessible from inside the app only.

**Comment by Bnyro** [comment]
There are no plans for that, if you need more information why feel free to search the closed issues.
