### ISSUE TITLE
header stretch like edge browser on downward scroll 

### ISSUE THREAD

**Issue by Surbbd** [libre-tube/LibreTube#3195]
### Describe your suggested feature

https://user-images.githubusercontent.com/113291579/221393690-fcd04f90-be64-47bb-9525-41eb49aa35cb.mp4

### Other details

btw this is also present in firefox nightly.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please open the issue on the correct repo, which is **NOT** LibreTube's.
