### ISSUE TITLE
Add the legacy theme "Pixel Blue"

### ISSUE THREAD

**Issue by Surbbd** [libre-tube/LibreTube#3196]
### Describe your suggested feature

![Screenshot_20230226-110033_LibreTube](https://user-images.githubusercontent.com/113291579/221394233-c581d498-2bf3-42f5-85a6-81bc93963bea.png)

### Other details

Colour codes :-
![Screenshot 2023-02-26 110721](https://user-images.githubusercontent.com/113291579/221394266-745000a8-6037-48b8-ba37-4c6f9586e361.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please create a PR if you want to see it added, there won't be work spent on it from our side.

**Comment by Surbbd** [comment]
Only if i knew any coding language

**Comment by Bnyro** [comment]
See https://github.com/libre-tube/LibreTube/issues/2111

**Comment by Surbbd** [comment]
Yeah i do respect your decision the app looks great either way tho thanks for investing your time on an open source app.
