### ISSUE TITLE
Landscape layout for player page

### ISSUE THREAD

**Issue by xmha97** [libre-tube/LibreTube#3198]
### Describe your suggested feature

Hi, I want to use this app on landscape mode.

Settings page support the landscape mode.

Main page support the landscape mode.

Full-screen player page support the landscape mode.

But description page not support the landscape mode.

Please enable landscape mode on description page.

![Screenshot_2023-02-27-01-28-28-854_com github libretube](https://user-images.githubusercontent.com/23485114/221440300-ef77b4e1-eefe-4093-9bb7-0d70b8009134.jpg)

Thanks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xmha97** [comment]
Landscape mode is essential for tablets.

**Comment by Baardi** [comment]
No landscape mode makes Libretube unusable on a tablet. It's a shame, as the app is otherwise great

**Comment by DarremMolko** [comment]
Is this planned anytime soon? I feel like I have waited for years, this is the only thing that prevents me from using LibreTube.

**Comment by EscherMoore** [comment]
I too would like to see this added. Given Google's new support for the Android tablet ecosystem through the Pixel tablet, and with GrapheneOS also extending support to the Pixel tablet, I think this enhancement could significantly benefit a growing user base joining the Android tablet ecosystem.

**Comment by pluja** [comment]
Hi, I'm having the same issue. I'm just showing interest on the fix.

Thank you for such a great app!
