### ISSUE TITLE
Pause while looking at comments 

### ISSUE THREAD

**Issue by paerbac** [libre-tube/LibreTube#3200]
### Describe your suggested feature

Would like to be able to pause/skip while readeing comments 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Duplicate of #2922
