### ISSUE TITLE
The video title is displayed in English

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3208]
### Steps to reproduce

1.The language and location of the device is set to Turkey
2.The video title is in Turkish.(on YouTube)
3.LibreTube translates the title into English
4.The player is in Turkish

### Expected behavior

The video title should be displayed in Turkish on the home page

### Actual behavior

Translated into English.

### LibreTube version

0.12.0 Latest debug

### Android version

Android 12

### Other details

https://user-images.githubusercontent.com/124310688/221776952-951a4853-8147-4114-9dfb-a2607bbca904.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Titles are based on the instance's location.
