### ISSUE TITLE
[BUG] Channels video count is incorrect

### ISSUE THREAD

**Issue by LTMX** [libre-tube/LibreTube#3219]
### Steps to reproduce

1. Search for anything
2. Go to "Search" tab
3. View channels video counts

### Expected behavior

The channels video counts are displayed with their actual number

### Actual behavior

The channels videos counts are all set to -1 

### LibreTube version

0.12.0

### Android version

Android 12

### Other details

Running Miui.EU on a Mi10T

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LTMX** [comment]
![Screenshot_2023-03-02-16-19-26-371_com github libretube](https://user-images.githubusercontent.com/47640688/222472791-797f28e9-0aac-4858-bb3b-4a10037a5135.jpg)

**Comment by Bnyro** [comment]
In fact that's a NewPipe extractor issue, we're hiding it now instead of showing -1.
