### ISSUE TITLE
Debug builds

### ISSUE THREAD

**Issue by jakeogh** [libre-tube/LibreTube#3221]
### Steps to reproduce

Where do I find the debug builds? I see references to them being auto-compiled by github actions, but I haven't been able to find any auto-generated apk's under the actions section or releases.

### Expected behavior

Link to debug builds

### Actual behavior

No link to debug builds

### LibreTube version

debug

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Either at github.com/LibreTubeAlpha/Archive, @LibreTubeAlpha on Telegram, or under the actions tab on GitHub.

**Comment by jakeogh** [comment]
Updated location:
https://github.com/libre-tube/NightlyBuilds
(use the universal apk if you dont know which one to pick)
