### ISSUE TITLE
Subscription Tab slow loading

### ISSUE THREAD

**Issue by Silther** [libre-tube/LibreTube#3240]
### Steps to reproduce

1. Switch to the trends or home tab
2. Switch back to the subscription tab

### Expected behavior

Should switch switch back without delay.

### Actual behavior

Switches back after 2-5s

### LibreTube version

latest Debug

### Android version

Android 13

### Other details

https://user-images.githubusercontent.com/97352673/222954426-ce184675-bd7d-4591-b72b-7c9a04d17221.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Any updates on this?
