### ISSUE TITLE
Make download faster

### ISSUE THREAD

**Issue by Archeix7** [libre-tube/LibreTube#3244]
### Describe your suggested feature

It should work like NewPipe

https://user-images.githubusercontent.com/51048550/222960328-a284a322-934b-4e08-b06f-28fdc3abb0a1.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Download speeds can be slow due to YT throttling and Piped instance proxying.
