### ISSUE TITLE
Automatic selection does not select the quality correctly.So the video stops and so on

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3249]
### Describe your suggested feature

Set the default quality to 2160p.I watched the 1-hour video easily.Set the default quality to Auto.Application cannot display Video in 144p

### Other details

https://user-images.githubusercontent.com/124310688/222984800-323a0103-a36b-4b4f-a23d-c565c088815a.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
In fact that's being handled by the `ExoPlayer`, so if there was an issue we'd need to wait for them to fix it.
