### ISSUE TITLE
Audio only mode: local cache and offline mode

### ISSUE THREAD

**Issue by jkumeboshi** [libre-tube/LibreTube#3256]
### Describe your suggested feature

I like very much a Subsonic client's (such as DSub) feature: offline mode.
DSub caches any song it plays, up to a max storage size specified in settings. User can also manually cache a song or an entire playlist or an album.
Cached songs are not downloaded again (unless his metadata changes).
Many Subsonic clients also implements a full offline mode: it shows only songs that are in local cache and doesn't require to conenct to remote server at all to works.

It would be nice to have such a cache also in LibreTube, specifying in settings if audio streams shall be cached (and cache size) when "Audio only" mode is enabled.

This feature could reduce traffic to the (Piped) backend and would transform LibreTube app in something similar to YT-Music and other similar apps.

While a full offline mode maybe requires a very large modification of LibreTube, implementing just a local user sizable cache would improve significantly the application (such as reducing traffic in mobile networks and reduce load on the backend) with much less effort. Full offline mode may comes later.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thank you for the suggestion, however there are currently no plans to expand the app with a caching feature since the efforts are not worth it as we already have a built-in download feature and an offline player, so caching is kind of not needed.
And against what you suppose, caching would probably not be less effort than extending the offline mode with a music player feature.
