### ISSUE TITLE
glich letters

### ISSUE THREAD

**Issue by rzasharifi** [libre-tube/LibreTube#3257]
### Steps to reproduce

I have no idea!

### Expected behavior

Showing the correct letters 

### Actual behavior

Glich letters

### LibreTube version

0.12.1

### Android version

12

### Other details

![Screenshot_2023-03-06-19-59-57-853_com github libretube](https://user-images.githubusercontent.com/64254187/223173896-a7514d70-c7d8-4113-84d4-9f88ada0e1d3.jpg)

The regione is Italy
Language is Italian

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Big chance this issue is on your side, try installing some emoji pack on your device (if possible) .
These "glitched letters" are actually emojis your device failed to display and ended up showing strange characters.

**Comment by rzasharifi** [comment]
Actually, I checked it and yes, there are two flags. The thing is, I have no this problem with other apps, such as YT official app and FF.

**Comment by Bnyro** [comment]
The issue is not reproducible for me, so it has to be an issue with the device font you're using.
Some apps (e.g. YouTube) use their own font inside the app, e.g. Roboto, while we use the device one, which might explain why it works on YT.
