### ISSUE TITLE
The subscription list is broken

### ISSUE THREAD

**Issue by terminal-cs** [libre-tube/LibreTube#3258]
### Steps to reproduce

1. Open app
2. Go to subscription list

### Expected behavior

Videos should populate the list

### Actual behavior

Constantly getting network error, videos played from history work fine

### LibreTube version

0.12.0

### Android version

Android 12

### Other details

None

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not a LibreTube issue but an issue of the instance you're using.

**Comment by terminal-cs** [comment]
> That's not a LibreTube issue but an issue of the instance you're using.

What does that mean, and you didn't even provide a solution to fix it

**Comment by Bnyro** [comment]
The solution is to understand how LibreTube works: by using Piped instances.

**Comment by terminal-cs** [comment]
> The solution is to understand how LibreTube works: by using Piped instances.

Could have said that, thank you. I am using the official instance, is there any reason why it goes down for days at a time?

**Comment by terminal-cs** [comment]
> You can ask that at the Piped matrix room which is linked at the Piped README. I think there were some memory leaking issues, not sure.

Ah, that's no good. Hope they can get that fixed up soon
