### ISSUE TITLE
Player minimized when opening video via link

### ISSUE THREAD

**Issue by mmkthecoolest** [libre-tube/LibreTube#3260]
### Steps to reproduce

Step 0: Make sure LibreTube is default for opening YouTube links. 
Step 1: click on a YouTube link from another app

### Expected behavior

The app should automatically open with the player on top like so

![Screenshot_20230306_162256_LibreTube](https://user-images.githubusercontent.com/27556124/223233956-1a8ae1c8-c8dc-4f1f-9bda-64d3e957d884.png)

### Actual behavior

The app opens with the player minimized regardless of what tabs are selected by default

![Screenshot_20230306_162434_LibreTube](https://user-images.githubusercontent.com/27556124/223234327-6a8d10b3-40c8-40ad-a03d-f7be117faaae.png)

### LibreTube version

0.12.1

### Android version

Samsung OneUI 5 (Android 13)

### Other details

I am unable to find a setting to stop this behavior. If there is a setting to change it, it's not obvious.

This was tested with the app open and closed beforehand. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by mmkthecoolest** [comment]
Recorded a video


https://user-images.githubusercontent.com/27556124/223430768-5208a088-e114-4eff-ac65-c85030df08d3.mp4

**Comment by techgamers2** [comment]
yes i m also still facing this issue on 0.14.1

**Comment by varaki** [comment]
Also happens on crDroid 8.12 (Android 12) using version 0.16.1

**Comment by dAtA-TRoN** [comment]
I have the bug too, and it's very annoying.

**Comment by Draky50110** [comment]
Subscribing here, in case of solution.

Xiaomi Redmi Note 6 Pro with Android 9 / MIUI 12 here.
