### ISSUE TITLE
Libretube just doesn't work with French cellular data

### ISSUE THREAD

**Issue by yurizgohan** [libre-tube/LibreTube#3267]
### Steps to reproduce

How to reproduce this issue :
1. Just disable your WiFi
2. Let your celullar data on
3. Open LibreTube
4. See the issue 

### Expected behavior

So, normally it should work as the WiFi.
I expected that the app work, that videos load so I can watch videos.

### Actual behavior

But, with celullar data, it is not loading. The playlists, trending area, videos and etc. It just doesn't work.

![Screenshot_2023-03-06-21-54-42-315_com github libretube](https://user-images.githubusercontent.com/105591137/223534734-0a34627d-634a-407a-80d1-351b018627f2.jpg)
![Screenshot_2023-03-06-21-54-45-513_com github libretube](https://user-images.githubusercontent.com/105591137/223534787-9c1ef02c-fb68-4412-bd19-8485a3670183.jpg)

https://www.veed.io/view/b8ca2382-971b-415b-9c44-51945844bc6c?panel=share

### LibreTube version

0.12.1

### Android version

Android 13 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by rozari0** [comment]
Change instance and try again.

**Comment by yurizgohan** [comment]
> Change instance and try again.

Already did it

**Comment by Bnyro** [comment]
As long as something actually loads and the "No internet connection" screen doesn't show I doubt it's an issue of the app itself as the app behaves exactly the same on WiFi and cellular data (apart from the initial resolution preference).

**Comment by yurizgohan** [comment]
I really don't understand so

**Comment by Bnyro** [comment]
Works fine for German cellular data so I don't think the issue is LibreTube specific.
