### ISSUE TITLE
Video Update Error

### ISSUE THREAD

**Issue by Legoks** [libre-tube/LibreTube#327]
Top-down videos cannot be updated!

**Comment by FireMasterK** [comment]
What are top-down videos?

**Comment by Legoks** [comment]
Video update on the home page

**Comment by IceDBorn** [comment]
@FireMasterK I think that's he's trying to say the pull down gesture.

**Comment by Legoks** [comment]
Bəli

**Comment by Legoks** [comment]
Yes

**Comment by Bnyro** [comment]
Looks like Android 5 has lots of issues but it's really hard to help there tbh since Android 5 devices don't really fit todays standards anymore...

**Comment by Legoks** [comment]
No, I have this Android 11 device, that's it!

**Comment by Legoks** [comment]
This is a common problem of the program!

**Comment by Legoks** [comment]
Samsung A21s(Android 11)

**Comment by Bnyro** [comment]
We can only help you then if you provide a screen recording or the debug logs, since I never had that issue on my test devices...

**Comment by Legoks** [comment]
You login to the application, scroll down, there is no video change.

**Comment by Legoks** [comment]
I will send a screen recording

**Comment by Legoks** [comment]
Uploading XRecorder_29052022_222941.mp4…
