### ISSUE TITLE
Improve video cover definition

### ISSUE THREAD

**Issue by amokiel** [libre-tube/LibreTube#3270]
### Describe your suggested feature

Currently, only the video cover of the subscription list works well. Other parts of the video cover, such as related videos, recommended videos, and channel avatars. None of these images are sharp enough. Is it possible to improve the quality of these images? If possible, please try it. Because the definition of the video cover is too low, it does not look perfect on the device. If you can improve some video cover clarity, the experience will be better. Thank you for your hard work.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Unfortunately that first requires changes in the NewPipe extractor, though they already work on it.
