### ISSUE TITLE
Add ability to not proxy through Piped

### ISSUE THREAD

**Issue by Leichesters** [libre-tube/LibreTube#3274]
### Describe your suggested feature

Hey there LibreTube team,

I have a feature request that I believe would benefit many users of the app. As you know, LibreTube currently proxies YouTube videos through instances. However, I think it would be great to have the option for users to not proxy videos through instances, for a few reasons.

Firstly, many privacy-focused users of LibreTube are likely already using services like VPNs to hide their IP addresses. For those users, adding an additional proxy like Piped may not be necessary, and may even be redundant. By giving users the option to bypass Piped, you could free up server resources and potentially save users money on proxy costs.
I'm for example using LibreTube because it looks so much better than NewPipe and I'm using a VPN - I would be very open to only use that VPN and not use any of Piped resources.

Additionally, as the name "LibreTube" suggests, the app is focused on user freedom and choice. Allowing users to choose how they connect to Google and YouTube would align with this principle and give users more control over their network traffic.

I know this may sound a bit strange at first, but I hope you'll consider this feature request. Thank you for all the hard work you've put into the app so far!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I agree that this might be a good idea for some users as there also have been some recent issues with loading times using the proxy and if also using a VPN things probably are really slow. The implementation is not hard either.
However, we should really make sure any user enabling the option is aware they're connecting directly to Google servers by showing an explicit warning when the user enables it.

**Comment by Leichesters** [comment]
I personally had no troubles yet, but this will surely help some users.

Out of curiosity, except for the IP address - is there anything else Google can see? I was thinking maybe the user agent could be suspicious, maybe we should perhaps randomize it then (to Firefox / Chrome for example) - What do you think @Bnyro ?

**Comment by Bnyro** [comment]
Currently, the user agent should be "okhttp/{version}" by default according to [this](https://github.com/square/okhttp/pull/1063/files#diff-ef5cbb7ba395e1c9e7ce56c0c8758486ce3b0dd98323dea7d9c5423c159d2197R20), however I've not yet looked up how easy it would be to change it since that would probably need to be done on multiple different layers inside the app. 
As far as I'm concerned the user agent should be the only critical info (apart from the IP if you fail to use a VPN).

**Comment by FireMasterK** [comment]
Also music videos won't work like this.

**Comment by FireMasterK** [comment]
Another thing is YouTube is rate limiting requests, it's not a fault of the proxy or instances/servers.

The thing is it happens randomly, similar to an A/B test. It's hard to reproduce the behavior all the time, and hence also difficult to fix.

**Comment by FireMasterK** [comment]
> Currently, the user agent should be "okhttp/{version}" by default according to [this](https://github.com/square/okhttp/pull/1063/files#diff-ef5cbb7ba395e1c9e7ce56c0c8758486ce3b0dd98323dea7d9c5423c159d2197R20), however I've not yet looked up how easy it would be to change it since that would probably need to be done on multiple different layers inside the app. As far as I'm concerned the user agent should be the only critical info (apart from the IP if you fail to use a VPN).

Cronet alters it, we have a different User-Agent by default, which I think might include device information.

**Comment by faisalcodes** [comment]
Does YouTube return the response in the same json format as instances? If not, then would it be easier to make implementation of direct requests from the LibreTube. Like it will have to manage the responses accordingly.

**Comment by Bnyro** [comment]
> Does YouTube return the response in the same json format as instances? If not, then would it be easier to make implementation of direct requests from the LibreTube. Like it will have to manage the responses accordingly.
>
No, we would still use Piped as backend, only the images and videos wouldn't be proxied anymore.

**Comment by faisalcodes** [comment]
OP has requested "full freedom" which probably is not possible in LibreTube. Anyway, as I have previously mentioned in the Matrix chatroom, giving users an option to not proxy some of the resources will also allow them to fetch high-resolution thumbnails. And probably it is be doable.

**Comment by Leichesters** [comment]
@faisalcodes This is correct, however, I think @Bnyro's approach would probably be a better solution, as I still want to fetch my feed through Piped (I think this is a good balance between completely removing Google from my life vs having a super dedicated feed adapted for me)

**Comment by faisalcodes** [comment]
Yes. That would be great.

**Comment by FireMasterK** [comment]
What I think might be feasible is supporting not proxying thumbnail, and video streams. But using Piped for everything else, like videos, channels, feeds, etc.

**Comment by Bnyro** [comment]
> What I think might be feasible is supporting not proxying thumbnail, and video streams. But using Piped for everything else, like videos, channels, feeds, etc.
>
That's what I thought of too and anything else wouldn't really be possible anyways, that might have not been clear earlier.

**Comment by NeeRaj-2401** [comment]
> giving users an option to not proxy some of the resources will also allow them to fetch high-resolution thumbnails.

does newpipe proxy the requests too? 
cause i have blurred thumbnails in newpipe but NOT IN libretube. strange :)

**Comment by Leichesters** [comment]
@eledkarako :+1:  (idk why but I can't react to your comment)

**Comment by FireMasterK** [comment]
Not sure why there's any reason to disable http/3. It should fall back to http/1.1 (since Google's servers don't support http/2 for video streaming). http/3 should almost always be faster than http/1.1.
