### ISSUE TITLE
The button is bent.

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3277]
### Steps to reproduce

1.Play the video.
2.The rewind button is bent.

### Expected behavior

Shouldn't have bent.

### Actual behavior

![IMG-20230307-WA0008](https://user-images.githubusercontent.com/124310688/224248336-c936c7da-8893-4395-841f-64d3b49191e1.jpg)

### LibreTube version

0.12.1

### Android version

Android 5.1

### Other details

🤔Small screen phone

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's an issue of legacy Android versions and not LT itself.
