### ISSUE TITLE
UA Language update

### ISSUE THREAD

**Issue by mkikets99** [libre-tube/LibreTube#329]
### Describe your suggested feature

Ukrainian language translation is added on weblate (97%)
Need some context for 3 translations to close it fully:
- `importsuccess` - when this is showed? ending can be different...
- `all` - have more than 2 translations (context). Is it from filter?
- `piped` - this mostly translated the same, but this may be different on context

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thank you for helping with translations :)
Importsuccess shows when you successfully i.ported subscriptions from YouTube or NewPipe in the settings. All is for the search filter, yes. And Piped is for GitHub.com/teamPiped/Piped, I don't know why I added it to translations xD

**Comment by mkikets99** [comment]
Done. All strings are ready.
