### ISSUE TITLE
regression, some videos are not played

### ISSUE THREAD

**Issue by luca-e075e** [libre-tube/LibreTube#3294]
### Steps to reproduce

maybe regression of bugs [1132](https://github.com/libre-tube/LibreTube/issues/1132) and [2005](https://github.com/libre-tube/LibreTube/issues/2005) since it affects the same videos

1. set to not use HLS
2. quality and codecs are not important
3. play https://www.youtube.com/watch?v=Q5ESzNFQEqg

### Expected behavior

the video wil play

### Actual behavior

the video does not play

### LibreTube version

0.12.0

### Android version

10

### Other details

no issue if HLS is enabled

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please update the app to version 0.12.1.
