### ISSUE TITLE
Collapseable bottom navigation bar

### ISSUE THREAD

**Issue by ViktorKahu** [libre-tube/LibreTube#3297]
### Describe your suggested feature

As excellently implemented in the Bnyro Connect You app. :)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Unfortunately Connect You and LibreTube use different UI libraries/frameworks, and there doesn't seem to be a good way to implement it the same way.

Duplicate of #1912
