### ISSUE TITLE
Playback closes when you enter the settings 

### ISSUE THREAD

**Issue by Zemekith** [libre-tube/LibreTube#330]
### Steps to reproduce

1. Start playing a video
2. Enter the settings menu
3. The video closes

### Expected behavior

The playback should pause

### Actual behavior

The playback is closes

### LibreTube version

0.3.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't know how we should change that since settings wouldn't update if the player continues playing...
For example if you change the grid column number and press back from the settings, it would still be the old number of grids...

**Comment by Zemekith** [comment]
> I don't know how we should change that since settings wouldn't update if the player continues playing... For example if you change the grid column number and press back from the settings, it would still be the old number of grids...

Is it possible that it stays paused at least until some setting is changed? I pressed settings with no intention a few times and I had to search for the videos again

**Comment by Bnyro** [comment]
Maybe, I'll look into it when I have time
