### ISSUE TITLE
Text fix for the Russian language

### ISSUE THREAD

**Issue by Archeix7** [libre-tube/LibreTube#3302]
### Steps to reproduce

-

### Expected behavior

It would be better if it were like this (Just copy and paste and problem solved "В окне")

![IMG_20230313_094203_938](https://user-images.githubusercontent.com/51048550/224637776-d818a784-87dd-4d21-b98a-d199f44e9d4c.jpg)
![Screenshot_20230313-093851_LibreTube](https://user-images.githubusercontent.com/51048550/224637815-181934f5-889f-4fa6-b85a-c1347ecb09ee.png)

### Actual behavior

Now we have this

![IMG_20230313_094200_914](https://user-images.githubusercontent.com/51048550/224637510-62efb787-939a-4bd4-8fc1-4e045faa47f1.jpg)
![Screenshot_20230313-093942_LibreTube](https://user-images.githubusercontent.com/51048550/224637585-b9750ecd-f642-4455-b9ea-c94781ed9281.png)

### LibreTube version

0.12.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please do these changes via Weblate, incorrect translations should not be marked as an issue.

**Comment by Archeix7** [comment]
I outlined the problem, threw a solution, too lazy to create a new query, sorry
