### ISSUE TITLE
make "import playlist" also work with cross auth instances

### ISSUE THREAD

**Issue by ydqsbfsyi** [libre-tube/LibreTube#3304]
### Describe your suggested feature

Quite often in my area instances get blocked (some of them just disappear from instances list, days later they may come back) and I have to change instance. When changing an authentication instance, it's easy to export then import subscriptions (but it's not perfect, since when old auth instance disappear, I have no access in order to export, so I could only use an export maybe days ago, there could be some discrepency. ), but regarding playlists export and import, it doesn't work with cross instances cases - after import, I could see playlists but content is 0. (I did a subscriptions import before playlists import.)

So, I hope import playlist can cross auth instances. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by rozari0** [comment]
No Really a solution, but I suggest you to use local playlist & subscription.

**Comment by ydqsbfsyi** [comment]
> No Really a solution, but I suggest you to use local playlist & subscription.

Thanks for your help. Subscription? I guess that can not replace what playlist could do. As for local playlist, I heard about it and want to try it, but I never could find it in this app, is it "bookmarks"?

**Comment by rozari0** [comment]
It's the same thing. But data stored in your device instead of your auth instance.
Just log-out and do what you do always.

**Comment by ydqsbfsyi** [comment]
> however in order for the imports and exports to work, both instances (the selected auth and the selected normal instance) must be reachable.

Thanks, I'll test more.

**Comment by Bnyro** [comment]
Closing as not reproducible.
