### ISSUE TITLE
Flickering issue when opening sections in landscape mode.

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3306]
### Steps to reproduce

1,2,3🤗 Flickering problem when playing video in landscape mode

### Expected behavior

Stop flickering

### Actual behavior

https://user-images.githubusercontent.com/124310688/225059523-f75930d0-3dcd-4da2-83e6-aca8238decef.mp4

### LibreTube version

0.12.1

### Android version

Android 12

### Other details

😊

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's an issue of the MD3 library in combination with older Android devices, thus we can't do anything about it unfortunately.
