### ISSUE TITLE
Crashing all the time..

### ISSUE THREAD

**Issue by Aaniket7** [libre-tube/LibreTube#3309]
### Steps to reproduce

Whenever i search for videos.

### Expected behavior

Error should be resolved.

### Actual behavior

Shows error

### LibreTube version

0.12.1

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please follow the issue template and provide the error log.
