### ISSUE TITLE
Chapters support

### ISSUE THREAD

**Issue by ansarimohammed422** [libre-tube/LibreTube#331]
### Describe your suggested feature

It should be great if you implement support for chapters or time-stamp 

Because i use it all the time 

It is very use full

Newpipe does support that and dongtube also support that

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't think Piped supports it, @FireMasterK ?

**Comment by FireMasterK** [comment]
It does, it's already there in the API

**Comment by devstra** [comment]
+1 this would be super helpful. I don't mind helping out with this btw

**Comment by Bnyro** [comment]
@devstra Feel free to try it and create a pr if you succeed :)
