### ISSUE TITLE
Notification for Backup, Import/Export Playlists/Subscriptions

### ISSUE THREAD

**Issue by silentTeee** [libre-tube/LibreTube#3310]
### Describe your suggested feature

When importing/exporting playlists or backups, if the process involves server communication or massive lists of entries, the amount of time it takes for the migration to complete can be hard to predict.

The currently implemented toast that notifies the user when the process completes is a nice start towards good UX, but it would be better to provide some sort of persistent feedback that the process has started at all. Without that, a user may get confused as to the state of the app's background processes. This would also allow the user to back out of the application while they wait for the process to finish, and still feel confident that they will know when the app is ready to use again. 

### Other details

The notification ideally would indicate progress like below, but it could also just be an un-removable bar that would say "Backup/Import of _____ in progress..."

![Screenshot_20230315-090720~2](https://user-images.githubusercontent.com/20748060/225318187-649ca1a0-e265-4a06-984e-5f9c139ee7e0.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by silentTeee** [comment]
Interesting, okay if most of the work is done server-side then it makes
sense to avoid an explicit "progress" indicator. But if that's the case,
would it be possible to simply implement a notification on backup/upload
completion?

As in, for backups, a persistent notification saying "Backup saved to
'Path/to/file'", and for uploads from a .CSV, a "upload of
'/path/to/file.csv' complete".

The reason I ask is because it can be quite confusing to users when they
submit a request to an app and it offers limited feedback that the task was
actually completed or even running.

For example, if I kick off a request to upload a playlist to an instance
from a CSV, the only indication that it's even occurring is that when I go
into the library view and refresh, there is now an entry for that playlist,
but at first it shows up as being empty. The problem is that this is the
same behavior as what happens when the upload fails, so how do I know
whether it finished and failed, or whether it's still running? IIRC there
is a toast, but it doesnt stick around for long, so if you miss it, you
have no clue.

If you want, I can even take a stab at it sometime. I'm definitely not a
Kotlin guru, but I can at least try.

**Comment by Bnyro** [comment]
Feel free to create a PR, however that's nothing that would be worth keeping an issue open in my opinion.
Any kind of code contributions are welcome though!

**Comment by silentTeee** [comment]
@Bnyro just thought I would circle back to this, albeit for a slightly different reason: when you had mentioned that the server queries should only take a few seconds I was really surprised, because in my experience playlist uploads and queries had been _really_ slow, despite using the default server, and often straight up refused to work after a while.

Curious about that, I tried switching to the kavin.rocks _libre_ instance, and suddenly all queries were lighting fast! And oddly it seemed all my playlists associated with my account on the regular kavin.rocks instance somehow were available on the libre instance.

Is it possible that the maintainer of those instances deprecated the non-libre instance...?

**Comment by Bnyro** [comment]
No, it's more commonly used and running behind Cloudflare which can cause increased loading times. The non-libre instance is not discontinued by any means and in fact has locations in more than 5 countries!
