### ISSUE TITLE
Tapping on the app icon's menu on the Android desktop results in nothing. 

### ISSUE THREAD

**Issue by ThomasLeigh** [libre-tube/LibreTube#3314]
### Steps to reproduce

Tap on any option from the app icon menu ("Library, Subscriptions, Trends, Home").

### Expected behavior

It should open a corresponding window within the app.

### Actual behavior

It results in no action but the message: "App isn't installed" (Nova Launcher Prime 7.0.57) or nothing at all (the menu itself even remains displayed - in MIUI native launcher).

### LibreTube version

0.12.1

### Android version

10

### Other details

MIUI 12.5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't reproduce on any of my devices, thus I believe it's probably device related.
