### ISSUE TITLE
Instance Selection for log-in and fetching

### ISSUE THREAD

**Issue by EdwardLangdon** [libre-tube/LibreTube#332]
### Describe your suggested feature

It would be great if we use the Instance registered to Log-in and use a Different Instance for watching videos.

### Other details

The above can be found in Piped Web App. You load the frontend via a Instance domain change the Instance that fetches the video as you want such as choosing an instance near you.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't think that's possible. I don't even know what you could need this for tbh

**Comment by EdwardLangdon** [comment]
@Bnyro Just go a Piped Instance, See it's preference. There will be instance selection for using those instances near your location to load video. That's it.

In my Case, I have an account on Piped.kavin.rocks, I logged into the account in libretube, If it feels slower for me, In case if its. I can switch the Instance to the one that's near me for faster video loading like in Web Frontend.

**Comment by Bnyro** [comment]
Then you could just make an account on the other instance instead of using two at the same time...
Adding this feature is not worth the time it would cost.

**Comment by EdwardLangdon** [comment]
Well, I prefer having account on one such as that last longer like using official one and using instances which aren't certain but for reliability.

Atleast put this on hold and ask other team members and their opinion.

**Comment by Bnyro** [comment]
There are currently no real other team members, one got suspended and the others are afk :/

**Comment by Bnyro** [comment]
But maybe I have an idea how it could work without much work, I'll reopen it.

**Comment by EdwardLangdon** [comment]
I get the thing.

**Comment by archroid** [comment]
@FireMasterK You have any idea?

**Comment by FireMasterK** [comment]
> @FireMasterK You have any idea?

The API was actually designed in a way to allow this. Fetching unauthenticated data never requires authorization.

This could potentially be used to allow users to self-host their subscriptions. (while using another instance to watch videos)

It's not too difficult to implement, I could make a PR for the API changes (without the UI changes).

**Comment by EdwardLangdon** [comment]
Thanks, Kavin.

**Comment by archroid** [comment]
> > @FireMasterK You have any idea?
> 
> The API was actually designed in a way to allow this. Fetching unauthenticated data never requires authorization.
> 
> This could potentially be used to allow users to self-host their subscriptions. (while using another instance to watch videos)
> 
> It's not too difficult to implement, I could make a PR for the API changes (without the UI changes).

We appreciate that <3
