### ISSUE TITLE
Add options for full-screen brightness controls

### ISSUE THREAD

**Issue by MoonfirePDX** [libre-tube/LibreTube#3323]
### Describe your suggested feature

When viewing videos in full-screen, brightness is locked by the app to maximum, or at least very bright.
I would like to see options for allowing the OS brightness controls to be used, or at least user control over brightness when in full-screen mode.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Well, they can be controlled with swipe gestures. Or you just disable them in the settings.

**Comment by MoonfirePDX** [comment]
My mistake! I'd somehow overlooked that setting about a dozen times.
The swipe brightness control is intuitive now that I know it exists.
