### ISSUE TITLE
Does not load subscriptions

### ISSUE THREAD

**Issue by 99thim** [libre-tube/LibreTube#3325]
### Steps to reproduce

1. Click "Subscriptions"

### Expected behavior

Subscriptions should update

### Actual behavior

Nothing is happening, the app seems to be "searching undefinitely" for subscriptions

### LibreTube version

0.12.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please try using an other instance.
