### ISSUE TITLE
Changing wallpaper crashes picture-in-picture mode

### ISSUE THREAD

**Issue by Nadim147c** [libre-tube/LibreTube#3329]
### Steps to reproduce

1. Play a video in picture-in-picture mode.
2. Change the wallpaper of your device. 

### Expected behavior

Continue playing with or without changing the accent color. If the accent doesn't change instantly, change the accent on restart or something.

### Actual behavior

The app completely crushes and reopening the app shows error messages.

### LibreTube version

0.12.1

### Android version

Android 12

### Other details

This problem only occurs in picture-in-picture mode meaning audio mode isn't affected. This issue still occurs after changing the accent color from "Material You" to other accent colors.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not an issue of LibreTube, you can observe the same behavior on multiple other apps supporting PiP or even more trivial ones that behave unexpectedly when changing the wallpaper.
