### ISSUE TITLE
Playlist watch progress

### ISSUE THREAD

**Issue by Silther** [libre-tube/LibreTube#3330]
### Describe your suggested feature

If you have a long playlist (100+) for learning etc. a few functions could make life easier:

1. Add a second button to only play non-watched videos if.
2. Hide already watched videos.
   -> the ``play all``-button would only play non-hidden videos

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Cubicle13** [comment]
It would be nice if this automatically worked when restarting a playlist video from history. This is how this feature is implemented in many other YouTube alternative apps

**Comment by Bnyro** [comment]
To achieve the described behavior, you can now:
1. Start playing the playlist as you would normally
2. Open the current playing queue
3. Click the `eye icon` at the bottom of the playing queue sheet
4. Select "Remove watched videos"
