### ISSUE TITLE
Videos stops and doesn't come back

### ISSUE THREAD

**Issue by break999** [libre-tube/LibreTube#3353]
### Steps to reproduce

1. Play random video
2. Wait some minutes

### Expected behavior

Video should not stop, or at least continue automatically after whatever reason made it stop has passed by.

### Actual behavior

Video stops randomly. Play button doesn't make the video continue playing. Work around to make the video continue playing is to enter audio player, which makes it continue playing automatically and after going back to video player everything is playing normal again.

Same can occour in audio player. Audio suddently stops and doesn't come back until changed to video player.

### LibreTube version

0.12.1 app-universal-release.apk

### Android version

Android 12

### Other details

Otherwise great app and astonishing progression.
I'm eager to see it grow and is already my personal favorite, even with this bug, imagine then without.
Wish you well.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by erazemk** [comment]
This sounds more like a bandwidth issue, happens to me on slow wifi as well.

**Comment by break999** [comment]
Indeed my connection gets unstable sometimes and turns off and on. I know nothing about code but seems that whatever happens when switching between audio and video players is the solution. If the program can detect when the problem occours, say connection fails, it could automatically do the same that happens when switching players to restore it.

**Comment by break999** [comment]
After the video stopped and got the play button stuck, i tried do change do audio player to unstuck it and the app crashed.

java.lang.NullPointerException
	at com.github.libretube.ui.fragments.PlayerFragment.setCurrentChapterName(PlayerFragment.kt:17)
	at androidx.room.MultiInstanceInvalidationClient$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:91)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7881)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by break999** [comment]
I had just updated to the new version so might be that. After a fresh install seems to be more stable.

Also, great option to disable piped proxy. Connection seems to be faster now. =)

**Comment by Poilaucul** [comment]
I have 10Gb fiber connection, phone connected to WiFi 5GHZ band lands around 400Mbps on speedtests, yet I have this issue as well, tried using 5G also got this issue.

**Comment by lordkitsuna** [comment]
this happens all the time to me, i literally cant use the app for anything longer than maybe 10min because its always going to happen at some point on longer media and its super annoying. does not matter what kind of connection i am using. from my 2gig fiber at home (645mbps verified over wifi) to random other wifi or 5G this just will happen at some point in longform content especially if its just audio in the background

**Comment by Bnyro** [comment]
That's not a client side issue, it's likely caused by buffering by the instance. Disable the Piped Proxy in the options and use a VPN or change the instance in the settings.
