### ISSUE TITLE
Sound is not clear at high playback speed

### ISSUE THREAD

**Issue by hrshtein** [libre-tube/LibreTube#3354]
### Steps to reproduce

Go to any video and hear it at high playback speed like 3x

### Expected behavior

Only the speakers sound should be come but a throttling sound comes with it

### Actual behavior

Only the speaker sound should be come

### LibreTube version

0.12.0

### Android version

Every android version

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's an issue by the upstream ExoPlayer data source and not of LibreTube itself.
