### ISSUE TITLE
Videos not loading 

### ISSUE THREAD

**Issue by Adithyan007hack** [libre-tube/LibreTube#336]
### Steps to reproduce

1. Just play any video it just keeps loading and the app closes itself

### Expected behavior

The video should play

### Actual behavior

The video won't play and the app closes 

### LibreTube version

0.3.0

### Android version

Android 10

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [ ] I will fill out all of the requested information in this form.

**Comment by FireMasterK** [comment]
Do you have any logs via logcat? If the app closed itself, it likely crashed and should have a stack trace.

**Comment by Adithyan007hack** [comment]
Bro the issue was solved after disabling the sponsor block, But the videos take a long time to play
