### ISSUE TITLE
Video playback problem!

### ISSUE THREAD

**Issue by Legoks** [libre-tube/LibreTube#337]
Another problem is that the video stops when you exit the application while playing the video, the video does not continue when you return to the application and hit the Play button.

**Comment by Bnyro** [comment]
dupe

**Comment by Legoks** [comment]
Why?

**Comment by Bnyro** [comment]
because I already fixed it and there was another issue for it too, it's closed

**Comment by Legoks** [comment]
The play button does not work!

**Comment by Legoks** [comment]
I understood!
