### ISSUE TITLE
[BUG] <brief bug description>

### ISSUE THREAD

**Issue by shom13** [libre-tube/LibreTube#34]
**Describe the bug**
Cannot subscribe to any channel

**To Reproduce**
1. Go to any random video and try to press the subscribe button

Using the latest version of LibreTube from Fdroid

**Smartphone (please complete the following information):**
 - Device: [Samsung galaxy f41]
 - Android version: [11]

**Comment by rimthekid** [comment]
I should show a toast to tell you that you are not logged in
