### ISSUE TITLE
[Audio player] Autoplay doesn't update displayed info

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3402]
### Steps to reproduce

1.Play background music.
2.Wait for the next one.
3.The music has changed, the miniature has not.

### Expected behavior

It has to change.

### Actual behavior

https://user-images.githubusercontent.com/124310688/227770143-8056e66a-2705-48ae-b08b-47450e4522ec.mp4

### LibreTube version

0.13.1

### Android version

Android 12

### Other details

It changes when you click the play next or previous button.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#3874
