### ISSUE TITLE
Some videos do not open when Piped proxy is closed.

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3404]
### Steps to reproduce

1.Close the Piped proxy.
2.Some videos did not open.(not YT music content).
3.Even if I use VPN it doesn't open.

### Expected behavior

Let it open.

### Actual behavior

https://user-images.githubusercontent.com/124310688/227777097-7dce4c65-3189-4359-8ed5-157353229a0c.mp4

### LibreTube version

0.13.1

### Android version

Android 12

### Other details

Additional question: Does this option only work with VPN?

ALSO THUMBNAILS ARE BLURRY!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's due to YouTube restrictions and nothing we could do something about.
