### ISSUE TITLE
Poster quality 

### ISSUE THREAD

**Issue by knightmob** [libre-tube/LibreTube#3405]
### Describe your suggested feature

Hi! Just a concern user here, I just want to request a feature, please make the poster quality high and better, or even better, add settings to custom the poster quality. That's all, I hope you'll listen to my request.
![Screenshot_2023_0326_214726](https://user-images.githubusercontent.com/76065610/227780466-5bf13038-c0f2-4d7e-8c88-1474e7857f43.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not possible without NewPipe extractor changes.
