### ISSUE TITLE
The build on F-Droid failed

### ISSUE THREAD

**Issue by zhongkechen** [libre-tube/LibreTube#3414]
### Steps to reproduce

https://f-droid.org/repo/com.github.libretube_30.log.gz

Version 1.20.1 and later has not been released to F-Droid

### Expected behavior

Versions released in F-Droid

### Actual behavior

No release on F-droid

### LibreTube version

1.12.1

### Android version

All

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's known, 0.13.0 and 0.13.1 should build properly.

**Comment by zhongkechen** [comment]
@Bnyro It's still not building
