### ISSUE TITLE
enable the use of the video player while in the comments

### ISSUE THREAD

**Issue by Elkellympia** [libre-tube/LibreTube#3415]
### Describe your suggested feature

First of all, I do not know if this is expected behaviour, i have no reason to believe it is not.
![Screenshot_20230327-080918](https://user-images.githubusercontent.com/87786716/227926450-e7470f9c-ab39-40c2-88c4-5b9045d505c1.jpg)
While in the tab comments inside a video (shown upwards) i cannot access the video player to for example change the quality or skip some part of the video, the feeling is like an invisible div. 
![Screenshot_20230327-080929](https://user-images.githubusercontent.com/87786716/227927180-defbdb2c-bf20-40d2-8595-845420533c46.jpg)
Now, if im not in the comments tab, i can control the video as always, as i would like, like shown upwards

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Qaz-7** [comment]
Dupe
