### ISSUE TITLE
Avoid pause when switching to audio tab

### ISSUE THREAD

**Issue by Grkrz** [libre-tube/LibreTube#3441]
### Describe your suggested feature

Not if this was requested before but it would be nice to do not have the pause of audio while switching from video to audio. 

### Other details

-

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not possible unfortunately.
