### ISSUE TITLE
Disable sending of typing data / search suggestions

### ISSUE THREAD

**Issue by Mrnofish** [libre-tube/LibreTube#3442]
### Describe your suggested feature

I wish there was an option to disable sending typing data to the instance.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please use the issue template properly and provide reasons why. I currently don't see any, thus not planned for now.

**Comment by Mrnofish** [comment]
Some of the main reasons people switch to alternative clients like LibreTube, are privacy and escaping manipulation from the attention economy's major players.

Minimizing leakage of personally identifying data, such as typing data, increases privacy. There are already incentives for instance admins to join the fray not so much to provide this service to the community, but for their own personal profit, such as collecting valuable data for whatever purpose, something that may or may not be properly exposed in their privacy policies: they are, after all, under a tiny fraction of what little scrutiny is reserved to industry giants like Google.

In addition to providing sensitive data to the platform owners/instance admins, suggestions disguise as a benign-looking convenience.

However, they also play a role in increasing using retention and extending time spent on the site, by exposing users to content they weren't looking for in the first place.

There is a pretty sizable impulse to reclaim one's time and attention, and to escape attempts from social networks to push the users' buttons more or less overtly.

I would argue increasing privacy and reducing the potential for overuse and addiction, are actions that are fully in line with the project's goal.

**Comment by Bnyro** [comment]
Decided to add this now due to the reasons of https://github.com/TeamPiped/Piped/issues/2533

**Comment by Mrnofish** [comment]
Oh well, gift horse, mouths and all that.
