### ISSUE TITLE
Preventing automatic play when selecting/opening a video

### ISSUE THREAD

**Issue by Mrnofish** [libre-tube/LibreTube#3443]
### Describe your suggested feature

While browsing my subscriptions, I do often check some videos' details to decide whether they are worth my time, information that isn't exposed right away in the feed.

However, tapping on any video immediately results in playback beginning, pausing (and disrupting) whatever's happening in the background, like audio from LibreTube itself or a different app.

I wish there was a way to tap on a video for inspection without playback starting automatically every time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's the behavior when the data saver mode is enabled (settings -> advanced). There's currently no obvious reason to separate these.

**Comment by Mrnofish** [comment]
Enabling Data Saver would not only defeat the stated objective, that is to increase the knowledge about the content before initiating its consumption, but actively impair the ability to tell a video apart from another, identifying at a glance the uploader, content type etc, all of which are tasks carried out by video thumbnails.

(As a side note, for those who have otherwise no reason to enable Data Saver, there is no way to figure out that that switch has other effects, as the UI only mentions restrictions on "thumbnails and other images".)

If you'd rather not add another switch to the settings, perhaps another accommodation could be found ?

For instance, the effect of the AutoPlay switch could be extended to prevent not just playback of the next video but autoplay altogether.

Alternatively, the chained menu activated by long pressing could have an extra item (e.g. "Display video info") without starting playback.

**Comment by Bnyro** [comment]
Fair enough, I agree that these might be valid points, hence reopening.
