### ISSUE TITLE
Add YouTube Mixes in related items

### ISSUE THREAD

**Issue by ghost** [libre-tube/LibreTube#345]
### Describe your suggested feature

For reference;

https://github.com/TeamNewPipe/NewPipeExtractor/pull/788

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by adiadil** [comment]
> Maybe explain what you want and why instead of referencing NewPipe issues with thousands of lines of conversations

https://user-images.githubusercontent.com/101723451/171455736-89c488d5-77e9-4511-8965-9e20929d4565.mp4


Note that this has already been broken by YouTube in the EU.
