### ISSUE TITLE
Global playback speed

### ISSUE THREAD

**Issue by Vapstare1** [libre-tube/LibreTube#3453]
### Describe your suggested feature

It would be great if you could set a global playback speed for all the videos in settings

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Player -> Playback speed
