### ISSUE TITLE
home tab

### ISSUE THREAD

**Issue by Deiabsons** [libre-tube/LibreTube#3458]
### Steps to reproduce

I DON'T WANT TRENDING VIDEO TO SHOW AT APPLICATION START SO DEACTIVATE HOME TAB AND RESORT TABS AS FIRST ONE IS SUBSCRIPTIONS

### Expected behavior

When start, it then shoud show sbscriptions videos

### Actual behavior

But it still show home with trending videos,
I must click on subscription again to get it in view

### LibreTube version

0.13.1

### Android version

android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
See #3121 and read the code of conduct
