### ISSUE TITLE
Notification for new streams

### ISSUE THREAD

**Issue by ghost** [libre-tube/LibreTube#346]
### Describe your suggested feature

For reference;

https://github.com/TeamNewPipe/NewPipe/pull/2335

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FireMasterK** [comment]
I'm interested in supporting this via https://unifiedpush.org/.

**Comment by adiadil** [comment]
> I'm interested in supporting this via https://unifiedpush.org/.

Thanks! 👍
