### ISSUE TITLE
save the queue automatically just like the watch history

### ISSUE THREAD

**Issue by break999** [libre-tube/LibreTube#3466]
### Describe your suggested feature

I would like to suggest to save the queue automatically just like the watch history is saved. That way, if the app crashes, the manually made queue woudn't be lost.
Thank you.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thanks for the suggestion, however a persistent queue is currently not planned.

**Comment by break999** [comment]
not persistent, it would reset once a new queue is made. It's just a way to protect the queue against crashes.
