### ISSUE TITLE
Background playback seems to get killed easily

### ISSUE THREAD

**Issue by gaining** [libre-tube/LibreTube#3467]
### Steps to reproduce

Close all apps, open libretube start playing some chillhop lofi music: https://youtu.be/gwDoRPcPxtc then minimize it. Open a gps app like amigo, osmAnd, google maps or basically any other app like amazon and after a few seconds of using the other app, music from libretube stops playing in the background. Same thing happens in audio only mode

note: The notification control doesn't disappear when the music stops playing when using another app.

### Expected behavior

Should continue playing chill lofi music

### Actual behavior

background playback stops and I have to open the app again and continue playing

### LibreTube version

0.13.1

### Android version

Android 10

### Other details

On a moto g8 plus phone. 
4GB ram

Disabled battery optimizations so that app could continue running in background but no change.

I also tried this with youtube revanced v18.05.40 by j-hc, youtube revanced doesn't quit background playback when another app is running.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please use the "Play in background"/"Audio mode" for such purposes.
