### ISSUE TITLE
[BUG] Video options dialog does not work on playlist videos

### ISSUE THREAD

**Issue by IceDBorn** [libre-tube/LibreTube#347]
### Steps to reproduce

1. Go to library
2. Select a playlist
3. Long press a video

### Expected behavior

The options dialog should popup.

### Actual behavior

The options dialog does not popup.

### LibreTube version

Up to date with Git

### Android version

12.1

### Other details

LineageOS 19.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It’s not a bug, I’m aware and wanted to add it there too, just had no time yet. I’ll add it this evening.
