### ISSUE TITLE
The pure theme does not work perfectly, and …

### ISSUE THREAD

**Issue by Official-Mlx** [libre-tube/LibreTube#3473]
### Steps to reproduce

number 1:
pure theme
Open Settings > Appearance > Turn on Pure Theme,
It only works on the settings page

Number 2:
Audio player
Open a video, click on the sound icon, a page with an ugly animation opens and The app's navigation buttons 
on bottom doesn't work anymore

number 3:
Search bar
When you search for something and press the Go button on the keyboard, this box will not be closed, and if a channel is opened, it will be displayed as well.

number4:
 It is not possible to see the most viewed or oldest videos in the channels

number 5:
Freezing while scrolling a list view
When scrolling through the video list of a channel, the phone freezes

### Expected behavior

number 1:
pure theme
Open Settings > Appearance > Turn on Pure Theme,
It only works on the settings page

Number 2:
Audio player
Open a video, click on the sound icon, a page with an ugly animation opens and The app's navigation buttons don't work anymore

number 3:
Search bar
When you search for something and press the Go button on the keyboard, this box will not be closed, and if a channel is opened, it will be displayed as well.

number4:
 It is not possible to see the most viewed or oldest videos in the channels

number 5:
Freezing while scrolling a list view
When scrolling through the video list of a channel, the phone freezes

### Actual behavior

number 1:
pure theme
Open Settings > Appearance > Turn on Pure Theme,
It only works on the settings page

Number 2:
Audio player
Open a video, click on the sound icon, a page with an ugly animation opens and The app's navigation buttons don't work anymore

number 3:
Search bar
When you search for something and press the Go button on the keyboard, this box will not be closed, and if a channel is opened, it will be displayed as well.

number4:
 It is not possible to see the most viewed or oldest videos in the channels

number 5:
Freezing while scrolling a list view
When scrolling through the video list of a channel, the phone freezes

### LibreTube version

0.13.1

### Android version

10

### Other details

I wish these initial problems would be fixed, this app is even better than YouTube itself!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please keep things in separate issues and make sure things are supported at the Piped API/NewPipe extractor side. This one is being closed as bulked issues are not good to deal with.
