### ISSUE TITLE
Can't view vertical video in full screen again 

### ISSUE THREAD

**Issue by zoroya1** [libre-tube/LibreTube#3477]
### Steps to reproduce

1. Open any youtube video which is shot in vertical or portrait mode
2. Video will open in full screen in vertical mode
3. After usign back gesture from screen, when user wants to see full screen verical video again, there is no option for that

### Expected behavior

After user presses back button, and again he want to view video in full vertical screen, video should play in verical full screen as it played first time when user opened that video

### Actual behavior

Instead of playing in full vertical screen it plays in normal screen without any button or gesture for verical full screen play

### LibreTube version

0.13.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Disable `Auto fullscreen` in the player settings.
