### ISSUE TITLE
can't switch to dubbed audio

### ISSUE THREAD

**Issue by dhuschde** [libre-tube/LibreTube#3483]
### Steps to reproduce

1. Open a Video with normal and dubbed Audio
Example: https://piped.video/watch?v=voYdl7IFZsM

2. Try to switch between the tracks in the Language Menu

### Expected behavior

It should switch between the Audio Track

### Actual behavior

It just play's the one it opened the Video in

### LibreTube version

0.13.1

### Android version

Android 12

### Other details

Piped doesn't even show me the other options, just Languages. May be related.
https://github.com/TeamPiped/Piped/issues/2240

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
As you can see at https://pipedapi.kavin.rocks/streams/voYdl7IFZsM, multiple tracks here have the same `audioTrackId`, thus LibreTube can't differentiate between them. I don't see a proper way for us to fix that without backend changes to guarantee unique track IDs.
