### ISSUE TITLE
No new versions on F-Droid

### ISSUE THREAD

**Issue by zhongkechen** [libre-tube/LibreTube#3486]
### Steps to reproduce

Check F-Droid https://f-droid.org/en/packages/com.github.libretube

New versions after 1.12 are not on it. 

### Expected behavior

New versions available on F-droid

### Actual behavior

No new versions found on f-droid

### LibreTube version

1.12.1 and later

### Android version

All 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#3484
