### ISSUE TITLE
Instance list changes during selection

### ISSUE THREAD

**Issue by BHydden** [libre-tube/LibreTube#3494]
### Steps to reproduce

Close libretube
Open libretube
Choose instance
Choose top option kavin.rocks (official)
See that it automatically changes to 777.tf

### Expected behavior

The instance you choose should the one it selects

### Actual behavior

The instance is automatically changed during selection

### LibreTube version

0.13.1

### Android version

Android 13

### Other details

![Screenshot_20230406-054013](https://user-images.githubusercontent.com/28991649/230188783-009efb1b-f972-45ab-bc9a-392450c4e1e6.png)
![Screenshot_20230406-054037](https://user-images.githubusercontent.com/28991649/230188811-00fb1a7d-a3ca-44f2-8b67-17e81b2d0581.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
should be fixed with #4175
