### ISSUE TITLE
Shorts full screen behaviour 

### ISSUE THREAD

**Issue by NeeRaj-2401** [libre-tube/LibreTube#3497]
### Steps to reproduce

1. Open any short video in full screen
2. Tap on screen to see player controls 

### Expected behavior

Player controls should be visible without any effect on video

### Actual behavior

Not only Video gets a bit zoomed but also the player controls also gets shifted a bit towards top i.e bit merged to my status bar

https://user-images.githubusercontent.com/88180887/230430394-6e3a4751-8626-4895-923c-457fec689b05.mp4

### LibreTube version

Latest debug

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by abdo99000000000000000000000000000000000** [comment]
im having the same problem on android 11, and not only on shorts, im having this issue on normal videos too
