### ISSUE TITLE
Videos load at dial-up speeds

### ISSUE THREAD

**Issue by ViktorKahu** [libre-tube/LibreTube#3499]
### Steps to reproduce

Every now and again, the videos become so slow at loading, the streaming experience becomes fragmented (watch a couple of seconds, then wait for some time for the next couple of seconds to load). Other times, they (or the channel list), don't load at all. Problem seems to be intermittent but way more frequent than desired.

Steps to reproduce:

Use Libretube for a couple of months, at different times of the day and observe.

### Expected behavior

For the app to start fulfilling it's main purpose and video streaming to just work.

### Actual behavior

Described above.

### LibreTube version

0.13.1

### Android version

A13 GrapheneOS

### Other details

Excluded factors:

1) Internet connection fast and reliable.
2) Battery optimization turned off.
3) Chosing another instance has no affect.
4) Turning off the piped proxy stops any video from loading alltogether.
5) There is nothing wrong with my phone or my setup.
6) Watching the same videos in Newpipe (for testing purposes) = seamless experience.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I'm sorry for your experience with LibreTube, however neither me nor anyone else I'm aware of is facing such issues.
Your issues must be either device or instance related as per my understanding.
I'm afraid, there's nothing that could be done against that out of my point of view.
