### ISSUE TITLE
[FEATURE] Publish to F-Droid

### ISSUE THREAD

**Issue by FireMasterK** [libre-tube/LibreTube#35]
**Describe the feature you'd like to see added**
If possible, we should publish the application to F-Droid

**Additional context**
https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/

**Comment by rimthekid** [comment]
@alefvanoon was working on it but he had some work to do and he's not online for a while.

**Comment by rimthekid** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10694

**Comment by alefvanoon** [comment]
It's available now:
https://f-droid.org/en/packages/com.github.libretube/
