### ISSUE TITLE
Minimising animation smoother

### ISSUE THREAD

**Issue by amrmrni** [libre-tube/LibreTube#3505]
### Describe your suggested feature

Making the minimising player/video animation  smoother would make the app feel more polished and just smoother.

### Other details

https://linksharing.samsungcloud.com/69lQVFfJ1gpS

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
No plans for animation changes here.
