### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#3508]
### Steps to reproduce

Start app
App crashes

### Expected behavior

App should start as expected

### Actual behavior

App crashes

### LibreTube version

latest debug Libretube 32b130b // Alpha  Merge pull request #3502 from Isira-Seneviratne/Fragment_bindings  Free fragment view bindings when their fragments are destroyed.

### Android version

android 13

### Other details

![Screenshot_20230409_111132_One UI Home](https://user-images.githubusercontent.com/97352673/230764711-6accd463-d1c0-4b01-9909-61b486df8cd3.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't reproduce from my side.
