### ISSUE TITLE
Player enhancements

### ISSUE THREAD

**Issue by jaromeyer** [libre-tube/LibreTube#351]
### Describe your suggested feature

First of all thank you for this awesome project!
I have used the app for a bit and have found a few minor things that in my opinion would improve the user experience:
• I would expect that clicking on the minimized player fragment in the bottom would make it fill the screen again (as swiping up does)
• Double tapping to skip/go back x seconds is a feature that I use quite a lot in other video players
• The thumb of the slider in the video player is (at least on my device) a bit smaller than in the official YT app. Its really a tiny amount, but Ive found myself missing the thumb and having to try a second time a lot more than in the official app.
Unfortunately I havent done native Android development (especially Kotlin) in quite some time, so Id highly appreciate if someone who already knows the codebase could quickly implement those things before I spend hours learning Kotlin :)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I'll look into it when I find time for it, thank you for using the app :)

**Comment by jaromeyer** [comment]
also from what ive seen the XML formatting its kinda all over the place right now. maybe it would be worth picking some standard and then automatically reformat all files.

**Comment by Bnyro** [comment]
yeah, that's true.
I'm currently trying to structure the project a bit, will do that too :)

**Comment by Bnyro** [comment]
1 & 2 are also present in other issues now, 3 got implemented
