### ISSUE TITLE
Allow PIP while in the app.

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3513]
### Describe your suggested feature

Can't view PIP while in app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
PiP is already supported.

**Comment by akano12** [comment]
> PiP is already supported.

I might be wrong but i think he's referring to floating player (pop up the video while inside LT)
