### ISSUE TITLE
Protect the queue against crashes

### ISSUE THREAD

**Issue by break999** [libre-tube/LibreTube#3515]
### Describe your suggested feature

When the app crashes, it remembers the last video i was watching before the crash, but doesn't remember my queue. I manually make my queue (and usually big ones), when the app crashes, loosing it is definely the worse thing that happens. I know i could save the videos into a playlist but it is a slower alternative, i usually don't do it if i pretend to watch all videos now, unless i'm afraid of loosing my queue by a crash. I lost so many queues i lost the count. Which would be simple to solve, if the app saves the last video watched before a crash it can also save the last queue. Thank you.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Our plan is to fix the crashes instead of adding backups to prevent temporary data from being lost.
The solution to save important queues to a playlist seems like a good to me though.
