### ISSUE TITLE
block mobile data

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#3522]
### Describe your suggested feature

In #1249 separate quality settings for wifi and mobile data have been introduced.
After the quick settings were changed in Android 12 (13) and wifi and mobile data were merged, there are many people who no longer turn off mobile data.
If the wifi is interrupted or you simply forgot to change the settings, it would be nice to be able to block mobile data completely, so you don't get an expensive surprise at the end of the month.
Similar feature requests:
- #2610
- #1427

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
There are some awesome apps, for example `NetGuard`, which do exactly what you're talking about: Blocking usage with certain internet connection types. Apart from that, later Android versions have such a version inbuilt, too.

I don't see a reason why every app should implement that on their own if there are already much better alternatives to it. Apart from that the implementation inside LibreTube wouldn't be too easy as changes would be required for each network request made.

**Comment by akano12** [comment]
**If you have a rooted phone**, you could use AFWall+ which gives you control over VPN/wifi/lan/tor/mobile data connections. (iptables firewall, you can run VPN with it) 

2nd option isn't optimal, not everyone have problems and don't mind running streaming apps on mobile data.

Ofc unless the maintainer wants to add an option in settings to check if mobile data is active on startup
