### ISSUE TITLE
LT doesn't loads Video with their original audio track

### ISSUE THREAD

**Issue by IndusAryan** [libre-tube/LibreTube#3529]
### Steps to reproduce

Watch any video that has multiple audio tracks

### Expected behavior

The Video should be played with its original audio that was set default when Uploading

![photo_2023-04-11_12-16-46](https://user-images.githubusercontent.com/125901294/231079098-99074713-ea18-42ea-827e-7a6207c31fb4.jpg)

here the uploader has set hindi as original 

### Actual behavior

![photo_2023-04-11_12-16-39](https://user-images.githubusercontent.com/125901294/231079282-73b3dd1a-5a08-4a63-98cf-245b396ccc32.jpg)

But LT plays the audio track which is present at number 1 in the Audio Track Sheet.

I am unsure if this is a bug or a Feature Enhancement

### LibreTube version

0.13.1

### Android version

A13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We don't have information returned by the API which one the original audio track is, thus we're trying to use the language the app's set to and otherwise fall back to English.
Thus, not possible without API changes.

**Comment by Bnyro** [comment]
Now possible due to API changes.
