### ISSUE TITLE
[Feature request] Peertube support

### ISSUE THREAD

**Issue by pabloscloud** [libre-tube/LibreTube#3537]
### Describe your suggested feature

One could subscribe to peertube channels and search for peertube videos at least by url

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Support for other platforms is out of scope.
