### ISSUE TITLE
Sort options for custom playlists

### ISSUE THREAD

**Issue by ivanbistrovic** [libre-tube/LibreTube#3540]
### Describe your suggested feature

Hi, I would like LibreTube to have the option of sorting the videos in custom playlists. Added video goes to the bottom of the list and that becomes a pain to scroll once one has hundreds of videos on a list so having an option to sort by date added would be nice.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by luckkmaxx** [comment]
> This option sorts the playlists order, but not their content. I thought about an option within a playlist where I can select sorting method for the videos in that playlist.

I think this option is for playlists view, not for videos inside a playlist (wich should be set for each one)

**Comment by luckkmaxx** [comment]
btw, it could be fine that videos inside a playlist to be ordered manually by dragging the videos up or down
