### ISSUE TITLE
going backward cause the video cache to be removed and downloaded again

### ISSUE THREAD

**Issue by lucamp** [libre-tube/LibreTube#355]
### Steps to reproduce

- play any video
- wait until a part has been downloaded (time bar after the current time becomes white) and some time has passed (for instance 20 seconds)
![Screenshot_2022-06-02-22-56-36-01](https://user-images.githubusercontent.com/15078341/171737168-f00a3628-bfa7-4626-956e-0b9b8c7cb1c4.jpg)
- press "back 5 sec" button, one or two times or slide the time bar backward

### Expected behavior

the part of the video that has been downloaded is conserved in the cache and going back will use this, so going back will be a smooth process

### Actual behavior

the cache is removed and a new download starts, play will resume after a while and not immediately

this will waste bandwidth and stops the video until it is downloaded again

### LibreTube version

0.3.0 fdroid

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by lucamp** [comment]
thanks, almost resolved except when you seek backward till the beginning (00:00). In this case, libretube starts a new download

**Comment by Bnyro** [comment]
Hmm, that's weird, I'll look into it.

**Comment by lucamp** [comment]
Found another circumstance that removes cached video

1. Set default video resolution to auto
2. Play a [video](https://youtube.com/watch?v=FJVlBHx7ZlM) that has subtitles
3. Wait until a part has been downloaded and some time has passed (for instance 20 seconds)
4. Turn off subtitles
5. Now the cached video is removed and the download starts again
6. Turn on subtitle and cached video is removed again

**Comment by Bnyro** [comment]
In this case that's probably an exoplayer issue, all the resolutions are set the same way inside the app, there shouldn't be any difference (we use HLS for automatic resolutions so it's set in the same way).
