### ISSUE TITLE
Improve channel group UI

### ISSUE THREAD

**Issue by SameenAhnaf** [libre-tube/LibreTube#3558]
### Describe your suggested feature

- [x] 1. Place ✏️ icon (group manager menu accessible at the very beginning, not channel addition menu) on the left of all channel groups, not right.
- [x] 2. Within group manager menu, allow reordering groups similar to navigation tabs by replacing the pencil column with sliders' column within green box. See the screenshot for reference.
- [x] 3. Edit a channel group. Making changes to the name field and tapping "Cancel" button will not save the changes. But if you add or remove channels from the group, the changes are saved anyway after cancelling.
- ~[ rejected ] 4. For group manager menu,  there's no need for an entire column of pencil icons. Instead, long press on any group to open channel addition menu.~

- [x] 5. Place switcher between channel list and feed under groups, not above. Browse both channels and feed within any specific group. Only show unselected channels in channel addition menu. While showing channel list from any specific group, long press on the channel to show `Remove from group` option.
- ~[ rejected ] 6. Show `Feed` and `Channels` instead of kinda ambiguous *Subscriptions* headline. Show number of channels as per selected group.~
- [x] 7. Show a warning if no group name has been set for or no channel is added to any group while creation.
- ~[ rejected ] 8. `Play latest videos` should only load new videos found after each reload, not the entire list of videos.~

- ~[ rejected ] 9. For `All` channel group, filter channels by number of added groups. The options should be available in radio buttons for `0`, `1`, `2` and `More than 2` number of groups.~
- ~[ rejected ] 10. Instead of `Unsubscribe` button after subscribing channels, show `SUBSCRIBED` button to show an all-in-one menu to unsubscribe, add to groups and enable notifications for the channel. This new menu should be available for legacy subscriptions layout by long press on the channel.~
- [x] 11. [BUG] Although notification for new streams is disabled, notification bell is shown after unsubscribing from subscriptions' list and subscribing again.
- [x] 12. Allow setting a default group that shows initially when opening the subscriptions tab or remember the last used channel group and restore it when opening the app the next time.

### Other details

![Screenshot_20230416-004456](https://user-images.githubusercontent.com/79245641/232247891-6d8038de-5db0-4a29-aebe-a3bf590f77d7.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Reinachan** [comment]
I'd additionally suggest adding the ability to navigate between subscription groups by swiping left/right in the subscriptions tab.

Another would be marking a channel as hidden from the "all" group. This is mostly useful when you're subscribing to a channel that very frequently uploads and you'd like to only see it in the groups you've added it to.

(I'm putting the suggestions here as it felt more relevant than creating separate issues for it when there's a tasklist here, I can move them to separate issues if preferred tho)

**Comment by Bnyro** [comment]
Everything planned from that list is implemented now.

> I'd additionally suggest adding the ability to navigate between subscription groups by swiping left/right in the subscriptions tab.
>
I'm not really convinced by the necessity for this, it's easy enough to click the chip with the group you want and you usually just want to look at one specific group, and not search through all of them.

> Another would be marking a channel as hidden from the "all" group. This is mostly useful when you're subscribing to a channel that very frequently uploads and you'd like to only see it in the groups you've added it to.
>
I see why this could be useful, but I'm not really sure about a good way to implement this UI-wise. Please feel free to create a new issue to discuss that.

**Comment by shuvashish76** [comment]
Hello, I'm testing v0.24.0 Nightly the requests I mentioned in #5313 are missing.
1, 2 missing & for 3 it says "Delete from Downloads" while the confirmation dialog should show "Delete the Channel group" or "Delete from Channel groups".
