### ISSUE TITLE
Show Error message instead of crashing app.

### ISSUE THREAD

**Issue by rozari0** [libre-tube/LibreTube#3560]
### Steps to reproduce

1. Open https://m.youtube.com/channel/UCgacdsZYnWVaz3K55LfdAHg (This is a valid channel URL)

### Expected behavior

This should show an error message instead of crashing the whole app.

### Actual behavior

Libre tube Crashed.

### LibreTube version

0.14.0

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The description of the channel is null which we currently don't handle properly.

**Comment by Bnyro** [comment]
The chanel seems to have a restricted visibility, looks like a NewPipe Extractor issue.
