### ISSUE TITLE
Videos are no longer full screen on devices with camera cutouts

### ISSUE THREAD

**Issue by terminal-cs** [libre-tube/LibreTube#3561]
### Steps to reproduce

Libretube no longer allows videos to go in regions where camera cutouts are. This shouldn't be the case and videos should continue to be full screen 

### Expected behavior

Videos should go around camera cutouts

### Actual behavior

Adds a large black border making the whole area not viewable 

### LibreTube version

14.0, works ok in 13.1

### Android version

13

### Other details

![Screenshot_20230415-101146](https://user-images.githubusercontent.com/76945439/232241910-e2cd651d-f36c-4d03-afa2-ba2cb63f57fc.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#3544

**Comment by terminal-cs** [comment]
> #3544

Ah. Thanks, do you plan to do a release soon for this? I don't have a build environment set up ATM and I don't really have time to get it all ready. Just whenever you are available to make it ofc, no pressure

**Comment by Bnyro** [comment]
No, the bug isn't serious enough to require a new "hotfix" release.
