### ISSUE TITLE
Add use a external player 

### ISSUE THREAD

**Issue by iZel345** [libre-tube/LibreTube#3563]
### Describe your suggested feature

Everything in the title. I want to use a external player with libretube such as MPV.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Long press the share button when playing a video.
