### ISSUE TITLE
Create Playlist button in Library changes position when any Video is played

### ISSUE THREAD

**Issue by IndusAryan** [libre-tube/LibreTube#3564]
### Steps to reproduce

NEW REPRODUCE METHOD - see position of plus button in library,then play any video from anywhere,the button changes position because it makes space for the miniplayer.

OLD ISSUE - clone or copy a playlist or create one and add a video.

then play a video from the playlist 
come back to library frag either by closing the video or with a miniplayer

### Expected behavior

the create playlist button should come back to its position when miniplayer is closed

### Actual behavior

But the create playlist button gets Elevated from its original Position.

### LibreTube version

0.14

### Android version

A13

### Other details

https://user-images.githubusercontent.com/125901294/232249226-5b71cbb4-2e7e-442e-868d-e74019c612db.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by yoguut** [comment]
@IndusAryan I can't seem to reproduce by following the steps. i want to take a look at your video, but link to the video didn't seem to work. do you mind reposting the video?
