### ISSUE TITLE
Multi default caption language

### ISSUE THREAD

**Issue by MarkChan0225** [libre-tube/LibreTube#3569]
### Describe your suggested feature

I request to add a support to multi caption language selection. It should be work like selecting the most prefer language caption and the remaining prefer language.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't think that'd be really useful, either you always want to have subtitles in your native language or if there are none, you either choose the caption language manually or don't use any. Thus, not planned, as the benefits would be very minimal and only few users would actually use it.

**Comment by slashdevslashurandom** [comment]
I would also like that feature to be added someday.

Personally, I am learning Esperanto and I would ideally want to see Esperanto subtitles for whichever videos happen to have them, but if they're not available (which is very likely), then English and Russian would also be good.

I can also imagine multilingual users benefiting from this feature in general.
