### ISSUE TITLE
Download directory 

### ISSUE THREAD

**Issue by david-hot** [libre-tube/LibreTube#3570]
### Steps to reproduce

Step one, download file
Step two. Look for file 
Step three look in every subdirectory 

### Expected behavior

The downloaded file should've sent to the download subdirectory 

### Actual behavior

I could not find the file even after going into every subdirectory

### LibreTube version

0.13.1 (latest as of April 15)

### Android version

Android 12 (go edition)

### Other details

No additional info. I have search for a similar topic but did not find.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Downloads are stored within LT data folder as they're meant to be watched inside the app (you won't find them in Downloada folder).
Not sure if this answers your question.

Also 0.14 is the latest version

**Comment by david-hot** [comment]
So I need to use a different app. I need to break up a downloaded video into different music videos.
Thank you
Dave
-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



Apr 16, 2023, 16:58 by ***@***.***:

**Comment by Bnyro** [comment]
As supposed, downloads are meant to only be playable inside the app.
