### ISSUE TITLE
Export downloads

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#3572]
### Describe your suggested feature

Right now all downloaded media is under Android/data/
Wich is unreachable to other players or apps, and AFAIK cannot be deleted because the app crashes trying to go to "downloads" section.

So maybe the best solution is a new button just like "Download" but "Export", wich will place the selected media in:
  - A folder set under settings.
  - Or a folder selected during the export action.

My case is I want to download music and move to my personal music folder in my device.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by luckkmaxx** [comment]
> NewPipe allows you to set the Download location. I have mine set to `/Podcasts`.

Hi! Thanks for your reply. Im not searching for an app capable to do it. I figure out there are apps that does it, but Im just suggesting implement this here, because is my preferred system right now (to have my own server instance is a must).
But as I said, thanks for your time and help.

**Comment by Bnyro** [comment]
The thing is that downloads are separated into video, audio and subtitles. These are all different files, hence I don't think you would really benefit from having a different location as video and audio can only get played together inside the app. For audio files only, it might make sense, I agree, however it'd probably be confusing for some users and end up in issues being raised that downloaded videos don't have audio.

**Comment by luckkmaxx** [comment]
Ok I understand. I didnt noticed that everything is dowloaded separately since I only downloaded audios until now.

So maybe to be able to export content there has to be another tool (integrated or not) to merge all parts in one file (just like "Tubemate" does, if you know it).

Well, here is my idea, that for sure isnt a priority right now, cuz there are many other relevant fixes and improvements to do.

Thanks!

**Comment by dhammel** [comment]
@Bnyro Is there a reason why audio/video seperated in different files? I can use a different tool on pc to join them, but it would actually be easier to just use yt-dlp, or newpipe to download since it does this automatically. Libretube can replace both the official youtube app and newpipe for me if downloads could save to a folder of my choosing and be joined together.

The downloads feature in libretube is for the most part useless in its current state, and still would need a 2nd app to handle downloading. (Especially the speeds are way too slow over piped proxy, that alone may be worth using another downloader)

Is there some reason you don't seem interested in implementing this?

**Comment by Bnyro** [comment]
Don't ping me and read closed issues.

**Comment by Bnyro** [comment]
I'll stay with my previous decision that downloads are meant to be playable within the app only. I recommend using tools like Seal or yt-dlp for downloading videos for other use cases, they can be used with a VPN or Proxy.

**Comment by Bnyro** [comment]
Well, I think that it's rather downloading than caching because caching refers to temporarily keeping media stored and automatically deleted after some time, while downloads are permanently stored until the user manually deletes it.

**Comment by Pranav-Goel** [comment]
I also completely agree with @TechD123 and @luckkmaxx -- would be great to have a feature to download to my phone device itself.
