### ISSUE TITLE
Add to playlist > Playlists ordered only by added date

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#3573]
### Steps to reproduce

Add something to playlist and the first time the list of playlists to use are shown, its ordered by added date.
Should be it ordered by the same option selected on playlists view?
And btw, the playlist order in the playlists view is maybe wrong too, because you select "Recently updated" as order but it never considers new additions, deletes or renames of them. In fact it actually keeps the order as "Added date" (wich doesnt exists as option) so the last playlist is always the last created one.

### Expected behavior

Re-order playlist with the selected option in both cases (playlists vew and playlist selection after "add to playlist")

### Actual behavior

Explained above

### LibreTube version

0.14.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I guess you're using the app without an account? That's currently only implemented for playlists from Piped accounts, and not for local playlists.

**Comment by luckkmaxx** [comment]
All my playlists are inside my piped user account, wich is self hosted.
