### ISSUE TITLE
The searching text is unavailable, but the results is still

### ISSUE THREAD

**Issue by gracie95** [libre-tube/LibreTube#3575]
### Describe your suggested feature

https://user-images.githubusercontent.com/107738923/232329024-4ee752e8-0dd7-4ad0-a1f8-0eb550e34fe0.mp4

I am not removing text yet. Just want to type other keywords.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by luckkmaxx** [comment]
Hi there, if you have search history enbled, there you can tap the up-left arrow for the last search keywords to place it in the search bar and then add that you want.
But yes, maybe is more practical to remember the last search until you go to other tab.

**Comment by gracie95** [comment]
Hi. Thanks for your response. I know, but I won't do that by enabling searching history. 
I think official YT app has no problem with this even searching history disabled.


Apr 17, 2023, 03:35 by ***@***.***:
