### ISSUE TITLE
Background player issues 

### ISSUE THREAD

**Issue by SameenAhnaf** [libre-tube/LibreTube#3578]
### Steps to reproduce

- [x] Bug A:
1. Play any media on main player
2. Add a few more videos to the queue
3. Click on "Audio"
4. Minimize the player

- [x] Bug B:
1. Play any media on background
2. Go to audio player from notifications or three dots menu
3. Minimize the player before the buffering ends

- [x] Bug C:
1. Play any media on background.
2. Go to audio player.
3. Click on *Back* button of device.

- [x] Bug D:
1. Play any media on background 
2. Minimize the player.
3. Start playing another media on background.

- [x] Bug E:
1. Play any media on background

### Expected behavior

Bug A & B: Mini player should be above the bottom bar.

Bug C: Audio player should be minimized at first.

Bug D: Currently playing video's video name and thumbnail should get updated.

Bug E: Mini player should appear above the bottom bar. 

### Actual behavior

Bug A & B: Mini player gets smudged with bottom bar.

Bug C: Player never gets minimized but pages behind the audio player gets updated. For example, search any media and play it on background and go to audio player. Clicking on *Back* will do nothing at first, then it will go to the first navigation tab, then it will close the app.

Bug D: Currently playing video's video name and thumbnail doesn't get updated. 

Bug E: Mini player never appears. We don't need additional options in three dots menu.

### LibreTube version

0.14.0

### Android version

Android 12

### Other details

Bug A & B:
![Screenshot_20230417-044813](https://user-images.githubusercontent.com/79245641/232348266-8b15c448-d148-4470-8c26-bb76f2e14e8e.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#594 and #3402 are related
