### ISSUE TITLE
Left option of navigation bar gets selected if default tab is unchecked in settings 

### ISSUE THREAD

**Issue by SameenAhnaf** [libre-tube/LibreTube#3579]
### Steps to reproduce

1. Check `Downloads`, `Subscriptions` and `Playlists` from navigation tabs' settings.
2. Reorder them according to step 1 respectively.
3. Select `Home` as default tab.
4. Restart the app.

### Expected behavior

No tab on navigation bar should get selected.

### Actual behavior

`Downloads` tab gets selected.

### LibreTube version

0.14.0

### Android version

Android 12

### Other details

![Screenshot_20230417-103834](https://user-images.githubusercontent.com/79245641/232379496-b2ee8fa2-8c98-4f9a-819a-db4b85ac7b20.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
> Rather, no navigation tab should remain selected.
> 
I doubt we can deselect all navigation bar items at once, however I agree on that.
Though I don't get why you want to show a toast here?
