### ISSUE TITLE
Make watch history an option to put on the nav bar.

### ISSUE THREAD

**Issue by Toiletmason** [libre-tube/LibreTube#3581]
### Describe your suggested feature

Put a clock icon down there And tapping it once should own your watch history. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I just want to mention the last point of [this section](https://github.com/libre-tube/LibreTube/blob/master/CODE_OF_CONDUCT.md#our-standards) in our Code of conduct.

That should be discussed via GitHub discussions imo, but that's nothing I'd personally agree on.
