### ISSUE TITLE
Add a right-handed mode and make it the default (channel too easy to click on accident)

### ISSUE THREAD

**Issue by RobbyCBennett** [libre-tube/LibreTube#3584]
### Describe your suggested feature

When a list of video shows up, it's far too easy to accidently tap on the channel. I click on channels about 25% of the time when I try to click on videos. This makes sense, because the channel button is about 25% of the height of the clickable link to the video.

The channel is an invisible button (the part to the right of the text is clickable), and it is half of the width of the screen.

The common case (clicking on a video) should be emphasized by being on the main side of the device and the less-common case (clicking on a channel) should be on the other side.

## Here's what it could look like:

![right](https://user-images.githubusercontent.com/22121365/232629530-e0f1f34b-6926-4ec9-a32e-7527832f6c0a.png)

## What it looks like now:

![left](https://user-images.githubusercontent.com/22121365/232629557-65005c8c-b589-4534-ad00-208fb5f892d8.png)

## What it looks like now, with borders to visualize the channel button:

![leftWithBounds](https://user-images.githubusercontent.com/22121365/232629651-46afbef9-1496-4556-b176-5f510c9d333e.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thank you for the suggestion, however there currently are no plans to change the layout here, simply because most apps use a layout that is oriented the same way and doing it differently might be inconvenient for users.
