### ISSUE TITLE
Fullscreen crash before video buffers

### ISSUE THREAD

**Issue by RyzenWarrior** [libre-tube/LibreTube#3588]
### Steps to reproduce

Click on a video and immediately swipe up to go into full screen

### Expected behavior

Should go into full screen while the video buffers

### Actual behavior

It crashes the entire app, leaving the app entirely.

### LibreTube version

0.14.0

### Android version

Android 13

### Other details

kotlin.UninitalizedPropertyAccessException: lateinit property steams has not been initialized.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't reproduce, please share a crash log.

**Comment by Bnyro** [comment]
Closing due to no response.
