### ISSUE TITLE
Add swipe gesture in channel page

### ISSUE THREAD

**Issue by Drangonfly30** [libre-tube/LibreTube#3590]
### Describe your suggested feature

YouTube and newpipe-channel tab  PR has swipe gesture to move between tabs. Libretube also support channel tabs. It'll be really good if it can also have this gesture support.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not planned because it wouldn't work and feel well since each tab needs to be fetched from the API individually.
