### ISSUE TITLE
LibreTube ignores auto rotation preferences

### ISSUE THREAD

**Issue by xplshn** [libre-tube/LibreTube#3595]
### Steps to reproduce

Disable Auto rotation
Rotate your device

### Expected behavior

The content should not rotate

### Actual behavior

The content ignores auto rotation and enters full screen, or exits it.

### LibreTube version

Latest

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
What you're probably referring to is in the player fragment, make sure to disable auto fullscreen in the player settings.

**Comment by xplshn** [comment]
Yeah but it should not work while AutoRotation is turned off, the same behavior as Newpipe, Newpipe does the same but only if Rotation is enabled.

**Comment by ardrag0n** [comment]
You should add an option that follows the system auto rotation. If the system auto rotation is on, then the player should rotate.
Currently, Even if the system auto rotation is off, the player rotates.
