### ISSUE TITLE
Unsupported file format for importing subscriptions.

### ISSUE THREAD

**Issue by solimm4sks** [libre-tube/LibreTube#3598]
### Steps to reproduce

1. Download and extract the subscriptions.csv file of youtube subscriptions from youtubes official "Your Data in YouTube" page.
2. Open Libretube
3. Settings -> Backup & restore -> Import subscriptions
4. Select subscriptions.csv

### Expected behavior

The subscription data gets imported.

### Actual behavior

The subscription data does not get imported.
An error toast message pops up: "Unsupported file format: */*" (without quotes)

### LibreTube version

0.14.0

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by aleksasiriski** [comment]
Is it required for the instance to allow registration for this functionality? Have you tried on an instance with an account made?

**Comment by solimm4sks** [comment]
I havent tried with an account

**Comment by solimm4sks** [comment]
To my knowlage, an account shouldnt be required, but I may be wrong.

**Comment by Bnyro** [comment]
Which file manager are you using? The error message indicates that it doesn't recognize the file type properly!

**Comment by solimm4sks** [comment]
Androids default one? Although I do have another File Explorer installed (ES File explorer), I don't think it's the one being opened automatically by LibreTube. I'm not sure if theres even a way to change that? 
In any case, going through the file explorer with: 's Galaxy J6 -> Downloads -> subscriptions.cvs actually loads the file correctly. What I have been doing is selecting it from the Recent tab. It also doesn't work when selecting through the Downloads tab (which should be the exact same as going 's Galaxy J6 -> Downloads, but I guess not). I've never had this problem before so I figured it's on LibreTubes end.
All in all, the subscriptions are imported, and the bug is probably on the file explorers end, so I will be closing this issue.

![image](https://user-images.githubusercontent.com/56252371/233680737-f33f4b33-4a33-44c2-a40f-e3ba8ee10388.jpg)
