### ISSUE TITLE
Low quality thumbnail in Android 13 background play notification

### ISSUE THREAD

**Issue by Fxsch** [libre-tube/LibreTube#3600]
### Steps to reproduce

Play a video and look at the notifaction for controling background play

### Expected behavior

Thumbnail should be high resolution

### Actual behavior

Thumbnail has a very low resolution

### LibreTube version

0.14.0

### Android version

Android 13

### Other details

Screenshot of what I mean: 
![Screenshot_20230421-123412_LibreTube](https://user-images.githubusercontent.com/77849217/233616266-7e8ac9f8-1765-4cbe-b4b7-cb7511bee0d1.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xz-dev** [comment]
Seems what we need to do is simply update exoplyer to 3 as https://developer.android.com/guide/topics/media/media3/getting-started/migration-guide

**Comment by Bnyro** [comment]
Yes, I think so too!
However, this probably well be some work since the ExoPlayer APIs have changed a bit in Media3 in comparison to the current API's we're using, so it's not as simple as changing the dependency.
