### ISSUE TITLE
Pure theme doesn't work

### ISSUE THREAD

**Issue by Official-Mlx** [libre-tube/LibreTube#3601]
### Steps to reproduce

1)Open Setting 
2) Appearance

3) first turn on dark mode and than Turn ON Pure Theme

### Expected behavior

The accent must be removed

### Actual behavior

The actual behavior happens only in the settings section itself and nothing happens in the main interface of the program

### LibreTube version

0.14.0

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
As it prompts you, an app restart is required.
