### ISSUE TITLE
Unable to restore Backups

### ISSUE THREAD

**Issue by muhammad-ans** [libre-tube/LibreTube#3616]
### Steps to reproduce

go to settings 
go to backup and restore 
click on restore

### Expected behavior

It should open document UI to select json file.

### Actual behavior

It does open documents ui but unable to select json file like they are not selectable 

### LibreTube version

0.14

### Android version

Android 6 (Color OS or Android 5 (color OS)

### Other details

It does work for playlists.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I assume ColorOS doesn't use the normal Android file picker app (com.android.documentsui)? I've tested this on lower Android versions too and didn't have issues. The error message basically says that we don't have privileges to read the fie you selected, however they should normally be granted automatically when selecting the file with the normal Android file picker. Hence, I doubt we can do something about it.
