### ISSUE TITLE
Auto play cool down when video ends

### ISSUE THREAD

**Issue by terminal-cs** [libre-tube/LibreTube#3622]
### Describe your suggested feature

When a video ends and auto play is enabled, there should be a short prompt that allows the user to cancel the next item to play, and just play the next video either after a few seconds or when the user presses the next button.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Settings -> Player -> Autoplay countdown

1. Use the app and THEN file issues

**Comment by terminal-cs** [comment]
> Settings -> Player -> Autoplay countdown
> 
> 1. Use the app and THEN file issues

I've got seen that in the entire time using the app, sorry
