### ISSUE TITLE
Provide citation for "They store a lot of your personal data - ranging from ideas, music taste, content, political opinions, and much more than you think." in readme

### ISSUE THREAD

**Issue by matkoniecz** [libre-tube/LibreTube#3623]
### Describe your suggested feature

I do not doubt that Google is doing this in general (though other may doubt) but I am interested what is covered by "much more" part

Would it be possible to turn "much more than you think" part into a link to some page/docs listing support for this claims?

I think that is a good hygiene to provide support for such claims, as it puts some pressure to avoid claims completely detached from reality.

### Other details

search for https://github.com/libre-tube/LibreTube/issues?q=is%3Aissue+is%3Aopen+They+store+a+lot+of+your+personal+data+-+ranging+from+ideas%2C+music+taste%2C+content%2C+political+opinions%2C+and+much+more+than+you+think. and https://github.com/libre-tube/LibreTube/issues?q=readme+citation and https://github.com/libre-tube/LibreTube/issues?q=readme+source+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It's mostly taken from https://piped-docs.kavin.rocks/docs/why/ and the Readme of https://github.com/TeamPiped/Piped, PRs on improving it are welcome!

**Comment by Bnyro** [comment]
Closing this, feel free to create a PR to improve the README or ask further questions on our Matrix room (see README).
