### ISSUE TITLE
Sort options for searching results

### ISSUE THREAD

**Issue by gracie95** [libre-tube/LibreTube#3627]
### Describe your suggested feature

The video results are randomly. 
Probably, with sort options user can easily find video.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Piped API / NewPipe extractor don't support that yet.
