### ISSUE TITLE
Can't control video if comments are opening

### ISSUE THREAD

**Issue by gracie95** [libre-tube/LibreTube#3628]
### Steps to reproduce

Steps:

1. Play a video
2. Open comments
3. Try to control video (play, pause, etc.)

### Expected behavior

You should able to control video even comments were opened.

### Actual behavior

You can't click at all in the video window. To do so, you must close comments to control video.

### LibreTube version

0.14.0

### Android version

Android 13

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#2922
