### ISSUE TITLE
Travel without internet

### ISSUE THREAD

**Issue by Legoks** [libre-tube/LibreTube#363]
Add a function to change some settings in the application when there is no internet. We can change some settings without internet.Newpipe and YouTube applications have this feature.An error occurs when exiting the application because this function does not exist.

https://user-images.githubusercontent.com/104249296/171994847-3ae7bef7-4c26-4803-b590-87c944e38f6d.mp4

**Comment by Legoks** [comment]
Will it be resolved in the next update?

**Comment by Bnyro** [comment]
Yes :)
