### ISSUE TITLE
Advanced search options

### ISSUE THREAD

**Issue by sagervrma** [libre-tube/LibreTube#3635]
### Describe your suggested feature

Currently, LibreTube allows users to search for videos on YouTube using keywords. However, this feature is limited in that it only returns videos that match the exact search terms entered by the user.

The "Advanced search options" feature would expand on this functionality by allowing users to filter search results based on additional criteria such as the date of upload, video length, or view count. For example, a user could search for all videos uploaded in the last week, or all videos longer than 30 minutes.

These additional filters would provide users with more precise and relevant search results, making it easier to find the content they are looking for. The feature could be implemented as a set of checkboxes or dropdown menus that allow users to select the desired search criteria.

Overall, this feature would improve the user experience of LibreTube and make it a more powerful and useful tool for discovering YouTube content

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Unfortunately, the NewPipe Extractor which is used by Piped doesn't yet support that.

**Comment by sagervrma** [comment]
okay got it
