### ISSUE TITLE
Playback speed notation

### ISSUE THREAD

**Issue by solimm4sks** [libre-tube/LibreTube#3636]
### Describe your suggested feature

I think the playback speed (and probably pitch too, though i don't really use it) sliders should have labels above them for common playback speeds, so that it's easier to locate them on the meter. This would probably include speeds like 0.5x, 1x, 1.2x, 1.5x, 1.7x, 2x, 2.5x, 3x, 4x (these would make sense for my personal usage, but I assume something similar applies generally). 

### Other details

I know around what speed I need to set the video to when changing the playback speed, but I don't know where that speed is located on the meter, so every time I have to hold the slider for the number to pop up to be able to locate it. I think it would be much more convenient if there were some numbers that were always visible above the slider, which would improve the experience of changing the playback drastically (I personally change it a lot, and am sure a lot of other people do as well).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
From #3691: Resetting the speed should return to the default playback speed from the settings, not to 1x.
