### ISSUE TITLE
Settings Reorganization

### ISSUE THREAD

**Issue by SameenAhnaf** [libre-tube/LibreTube#3654]
### Describe your suggested feature

- General
   - Location
     - Region
     - Language
   - Misc
     - Auto-rotation
     - Sleep timer
       - Minutes before being reminded*

- Player
  - Defaults
    - Playback speed
    - Custom speed for background: Include `Same as Main` button into that popup menu.
    - Resize mode
    - Start playback on
       - Main player
       - Audio player
       - Fullscreen player
    - Fullscreen orientation*
  - Behavior
    - Seek increment
    - Preloading
    - Skip buttons
  - Captions
    - Caption language
    - Caption size
    - System caption style
  - Gestures
    - Swipe controls
    - Enter/exit full screen
    - Pinch control
    - Double tap to seek
  - Misc
    - Minimize on app switch
       - Pause
       - Background 
       - PiP
    - Alternative PiP controls*
    - Auto-pause on screen off

- Appearence
   - Appearence
   - Navigation Bar
   - Layout
     - Legacy subscriptions view
       - Grid columns*
     - Alternative feed layout 
       - Grid columns*
     - Related content layout
       - None
       - Single Row
       - Same as Feed
   - Misc

*Grey out these options if not applicable. Hiding several options in some cases is kinda misleading.

Add `Autoplay Countdown` and `Insert to Queue` toggles right above related content, not in settings. These options are irrelevant unless related content is shown. Also, auto-play toggle is already in player.

All other settings will remain as usual.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I think some points of the restructuring are reasonable, however as it's very easy but takes some time that's something external/new contributors are invited to work on.

**Comment by n1snt** [comment]
If no one is working on this I would love to have a try at it.

**Comment by Bnyro** [comment]
Sure, have fun!

**Comment by clicky6** [comment]
It would also be good to have a search option in the settings so that we can find what we want easily and effortlessly.

**Comment by Bnyro** [comment]
> Add Autoplay Countdown and Insert to Queue toggles right above related content, not in settings. These options are irrelevant unless related content is shown.
>
Since that would change the current behavior, this should be discussed about in other issues please. I don't think it would look nice to have it there, so I'm not currently touching this.
