### ISSUE TITLE
Android 5.1 software problem

### ISSUE THREAD

**Issue by Logomotif** [libre-tube/LibreTube#366]
I installed Libre Tube on my Android 5.1 device. After installation, the program logo does not appear and closes by mistake when you open the application.Please fix this!

**Comment by Bnyro** [comment]
yes, ty for reporting, already got the fix :)
you would know that if you were on [telegram](https://t.me/libretubechat/) :DD

**Comment by Logomotif** [comment]
Will it be resolved in the next update?

**Comment by Logomotif** [comment]
Because I can't use the application!

**Comment by Bnyro** [comment]
The latest apks here on Github got updated, just install the latest versions there again
