### ISSUE TITLE
Video not playing.

### ISSUE THREAD

**Issue by rsssxd** [libre-tube/LibreTube#3661]
### Steps to reproduce

The video in the link below will not open. Only a black image appears.

https://piped.video/watch?v=zQ05QiAd_Js

**Comment by Bnyro** [comment]
Can't reproduce, most likely the video is geo restricted.
Also, please use the issue template properly next time!

**Comment by FireMasterK** [comment]
I was able to reproduce this on the 0.14.0 release but didn't check the latest debug build.
It's weird that the same video works great on Piped :confused: (It's an OTF video, so it uses the DASH manifest from YouTube)

**Comment by rsssxd** [comment]
The video works fine in the browser. There is a bug in the app.

**Comment by Bnyro** [comment]
Werd, but how can turning on "Use HLS" fix it then?

**Comment by rsssxd** [comment]
The HLS format did not solve the problem for me. The application gives a connection error.
