### ISSUE TITLE
Can't import a youtube Playlist csv file

### ISSUE THREAD

**Issue by mohamed591195** [libre-tube/LibreTube#3662]
### Steps to reproduce

1. by opening app settings
2. tap Backup & restore
3. import palylists 
4. choose the csv playlist file (which I have exported from youtube)
5. the playlist created in the app is empty

### Expected behavior

The playlist should get the full list of videos

### Actual behavior

It only gets the title right, but the list is empty

### LibreTube version

0.14.0

### Android version

11

### Other details

I have done some research to find out whether it 
1. can parse (expect ) csv files or not (I don't know)
2. the format (layout) of the csv file is suitable or not (also don't know)
which I think should be supported as I have extracted it from google takeout 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
In theory it's supported, feel free to send me the CSV file or a modified version of it (you can replace some video ids or remove some, just the general layout should be kept), so that I can debug it. Otherwise I can only say that I've already been successfully importing a playlist that way.

**Comment by mohamed591195** [comment]
here is the file link
https://drive.google.com/file/d/1RrSll1eunHGnpWMiqrgGo4R_3d7nIcQc/view?usp=sharing
