### ISSUE TITLE
Stick all popup menu at the bottom and fit to width

### ISSUE THREAD

**Issue by SameenAhnaf** [libre-tube/LibreTube#3663]
### Describe your suggested feature

Sticking menu at the bottom will ensure one-hand usability. Fitting all menus to width provide bigger slider and better access to information.

### Other details

Playback speed dials feel inconsistent. The one in the settings is inconvenient to reach.

| Settings | Player |
| --- | --- |
| ![Screenshot_20230429-102600](https://user-images.githubusercontent.com/79245641/235283362-3447a02f-90d6-40f7-abc7-3a642d4813c8.jpg) | ![Screenshot_20230429-102638](https://user-images.githubusercontent.com/79245641/235283366-9e6344cf-b8ea-4dcc-b491-4744a3be5d48.jpg) |

While adding channels to any group, channel names get cut off. Adding reorder options will make the UI overcrowded.

![Screenshot_20230429-102951](https://user-images.githubusercontent.com/79245641/235283457-2128dae5-1f41-4bb9-bc7a-7e4570785a7d.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
So your proposal is to use bottom sheets instead of normal dialogs?

**Comment by Bnyro** [comment]
We have got our own helper classes and views that can be reused, so changing it should be possible without rebuilding all layouts.

**Comment by Bnyro** [comment]
This is not planned for the playback speed dialog because all preferences use dialogs (either list, slider or text dialogs), so making an exception here for the playback speed would be inconsistent.
