### ISSUE TITLE
RSS for Podcast Readers

### ISSUE THREAD

**Issue by 91rl** [libre-tube/LibreTube#3665]
### Describe your suggested feature

Hey everyone, first of all thankyou to everyone who has put work into this project, I really love it, never going back to YouTube again.

I'd love to be able to generate an RSS for podcasting apps so that the podcasting apps can download the YouTube videos for local playback. Not sure how tricky this would be to implement though.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Piped has RSS feeds for subscriptions and for playlists, you can find 'em by using the frontend of your choice (e.g. piped.video) and navigate to your feed or the playlist. I don't think integration into LibreTube really makes sense.
