### ISSUE TITLE
audio stop when minimized

### ISSUE THREAD

**Issue by wiiznokes** [libre-tube/LibreTube#3666]
### Steps to reproduce

- Launch a video
- minimize app

### Expected behavior

Music should continue

### Actual behavior

After some second, the music stop. The player notification seems to have no connexion (play button is loading). When I click on the notification to open the app, it works. It's seems to be a foreground service issue.

### LibreTube version

0.14

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by itsmmt305** [comment]
needs elaboration. does minimizing the app show a pip of the video on the screen? or is the audio only playing
if its audio only then this is ideal behaviour (additionally, the notification should not linger). and if u wish to continue playing the audio select (audio) from the five options displayed on the player screen

![Screenshot_2023-05-05-13-21-59-181_com github libretube](https://user-images.githubusercontent.com/94820934/236404200-c30f0e64-fbda-4bb6-b472-81625f98c7f2.png)

**Comment by Bnyro** [comment]
If playing in the background, you should use the `Audio` mode which can be seen in the screenshot above.
