### ISSUE TITLE
Broken Layout in Subscriptions (first occurrence) then Trends and related videos.

### ISSUE THREAD

**Issue by IndusAryan** [libre-tube/LibreTube#3672]
### Steps to reproduce

Cannot be reproduced
This happened when i turned off legacy subscriptions view and alternative videos layout

also when these 2 options were turned on i faced this broken layout in Trends

### Expected behavior

stable layout

### Actual behavior

Somethings wrong with these alternate layouts
If i remember properly i encountered this after subscription groups update.

### LibreTube version

Latest Alpha

### Android version

A13

### Other details

https://user-images.githubusercontent.com/125901294/235355135-4c2f1e62-d103-4c1b-944b-a5dbc08c4a3c.mp4

![Screenshot_20230430-184144_VLC](https://user-images.githubusercontent.com/125901294/235355187-3bcf0fb7-4bd1-4ccb-91b8-4963ae4ddb24.png)
![Screenshot_20230430-184152_VLC](https://user-images.githubusercontent.com/125901294/235355200-ce2d6ae5-babe-4f29-b781-d88d34a15916.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It's not broken, you just changed the amount of grid columns to five which should only be done on large screen devices like tablets.
