### ISSUE TITLE
This channels videos are not working

### ISSUE THREAD

**Issue by IndusAryan** [libre-tube/LibreTube#3673]
### Steps to reproduce

Play any video from this channel

https://www.youtube.com/channel/UCBIT1FSJW6yTlzqK-31FDWg

### Expected behavior

video should play

### Actual behavior

after opening the progress bar appears and the playback is paused on black screen withput even starting

### LibreTube version

Latest Alpha

### Android version

A13

### Other details

video is working on piped website

piped proxy preference switch is on

tested on 3 phones,none working

official instance

network is fine

video is not geoblocked

before closing this issue,ask someone else to reproduce it,somethings definitely wrong with player

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Works fine for me.

**Comment by FireMasterK** [comment]
I could not replicate this issue either, maybe try getting logs from logcat? That would help find out the cause in case the player is facing problems loading streams.

**Comment by FireMasterK** [comment]
Let me reiterate - Please get logs from logcat, as that would find the source of the issue. (hopefully)

I couldn't reproduce this issue even on my Indian ip address either.

**Comment by FireMasterK** [comment]
To use the logcat, download the Android SDK tools to download adb, then run this on a terminal or command prompt if windows:
```
adb logcat > logcat.txt
```
Once you perform the actions to reproduce a crash, press Ctrl + C.

Hope this helps in the future!
