### ISSUE TITLE
Rewrite media player for MY(material you) and better visuals

### ISSUE THREAD

**Issue by jeffdumcum** [libre-tube/LibreTube#368]
Currently in the media player all items are not material you.  Also, I think (my personal opinion) it would be better if you could change the media player buttons to the Action buttons(such as the like button or the VLC button. Also, (if this is possible) maybe you could make it so the only time the VLC button is if you have the app installed. Keep working hard on this awesome app! Also maybe a donate button in the app would be nice for you guys

**Comment by jeffdumcum** [comment]
I forgot how to label it as a "suggestion" so sorry

**Comment by Bnyro** [comment]
We're planning to rewrite the player but it requires a lot of time that I currently don't have

**Comment by Bnyro** [comment]
And it would be possible to show the VLC button only if it's installed, but people who don't have it installed wouldn't know that it's possible then.

**Comment by fikrillah** [comment]
> And it would be possible to show the VLC button only if it's installed, but people who don't have it installed wouldn't know that it's possible then.

Why do you expect people to know it? Just make it simple 'open with...' button because not everyone is using VLC, like me and many foss-loving people are using MPV. It's weird to see vlc icon specifically in the first place anyway

**Comment by fikrillah** [comment]
And talking about design, I'm bothered by these three rectangles. These three are too distracting for the users. When you watch a video, you want your attention to the video, you don't want other visual element to stand out. Like the three are popping out for no good reason. Make it flat, and let the video playing become the only focus. 

![image1](https://user-images.githubusercontent.com/48489341/173214034-6a732115-0a79-41f2-ac79-88f94cfbd4bc.png)

Thank you for your work by the way. This app solves some of my complains about newpipe. I'm looking forward to see this project matures

**Comment by jeffdumcum** [comment]
What I meant was that the buttons below do not look pleasing compared to the rest of the program. I also agree with @fikrillah about the buttons looking distracting. Also in another topic, why not have a "Open with" or use the share menu like said by @fikrillah. I do have VLC and I have never used the button ever. Awesome work
![Screenshot_20220612-091131](https://user-images.githubusercontent.com/105110025/173237361-7a90aa24-37e1-4463-94d2-d39ee0bb7e32.png)
