### ISSUE TITLE
Show current instance name in title

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#3680]
### Describe your suggested feature

It coul be fine to see in wich instance are you browsing. See example.
Maybe possible enabling ir on settings.
![Screenshot_20230501-000702_LibreTube](https://user-images.githubusercontent.com/14180594/235378579-81a0c377-0987-43ed-befa-46ae8f204514.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Just looks very ugly in my opinion, not planned.
