### ISSUE TITLE
Add an option to disable remember track playing position

### ISSUE THREAD

**Issue by Flashwalker** [libre-tube/LibreTube#3688]
### Describe your suggested feature

An option to disable/enable the remembering of the track playing position

### Other details

(not playlist or history)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's already possible: Settings -> Watch positions -> Remember watch positions.

**Comment by Flashwalker** [comment]
> That's already possible: Settings -> Watch positions -> Remember watch positions.

I really can't find it. Could you take a screenshot so I can find it visually by the icon?
It may have a different name in different localizations

**Comment by Bnyro** [comment]
You should always run the latest version. It's called Remember position under the history tab, seems like I've renamed it some time ago.
