### ISSUE TITLE
Audio player ignores the settings of gesture control of the volume

### ISSUE THREAD

**Issue by Flashwalker** [libre-tube/LibreTube#3689]
### Steps to reproduce

1. disable the gesture control of the volume and rewind in player settings
2. go to audio play mode
3. make down/up gesture

### Expected behavior

In audio mode player respects the gesture option from player settings

### Actual behavior

In audio mode player ignores the gesture option from player settings

### LibreTube version

0.13.1

### Android version

Android 7

### Other details

arm64-v8a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's the intended behaviour, the gestures on the thumbnail can't really be hit accidentally like the player gestures so there's no reason to disable them. The option you mentioned is only meant for the video player.

**Comment by Flashwalker** [comment]
> the gestures on the thumbnail can't really be hit accidentally like the player gestures

Sorry, but i can't really understand why?
The position of the thumbnail in audio mode is the same as the video

**Comment by Mixcraftio** [comment]
I think like FlashWalker that it would make more sense to disable it, like I said in #4212.
