### ISSUE TITLE
Icon change not applying in Smart Launcher

### ISSUE THREAD

**Issue by jeffdumcum** [libre-tube/LibreTube#369]
### Steps to reproduce

1.Download Smart Launcher.
2.Launch it.
3.Change LibreTube icon from settings
4.Check in Smart Launcher
(I dont know if this is also in other launchers

### Expected behavior

It should change in Smart Launcher

### Actual behavior

It stays at default

### LibreTube version

 version 0.3.1

### Android version

Android 13

### Other details

![Screenshot_20220604-092500](https://user-images.githubusercontent.com/105110025/172006433-9d1b5787-7108-474c-beeb-b406786b3f81.png)
![Screenshot_20220604-092455](https://user-images.githubusercontent.com/105110025/172006435-f18572c9-cf2a-46a3-96b8-1344bfd832ad.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We can't do anything about it if your launcher doesn't follow android standards concerning icons. It works well for Lawnchair.

**Comment by jeffdumcum** [comment]
Thanks for telling me about it
