### ISSUE TITLE
Easy way (button) to reset playback speed

### ISSUE THREAD

**Issue by Archeix7** [libre-tube/LibreTube#3691]
### Describe your suggested feature

I propose to put somewhere here a button that will either reset or return the preset speed of video playback, so as not to go to the settings and not to change every time the video speed or to reset this speed to the default values

![IMG_20230501_204820_230](https://user-images.githubusercontent.com/51048550/235500715-3185ed62-10e7-492a-9497-e15fe8042d0c.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by vvkdev** [comment]
Speedchanger is used very often and should be available closer than 3 taps. It's very uncomfortable now...

**Comment by Bnyro** [comment]
Closing in favor of https://github.com/libre-tube/LibreTube/issues/3636
