### ISSUE TITLE
Add geo-block check

### ISSUE THREAD

**Issue by Myzel394** [libre-tube/LibreTube#3692]
### Describe your suggested feature

Currently, when you watch a geo-blocked video outside of either your selected piped instance, or, when accessing YouTube directly and you're watching a video outside of your location, the video does not play. Title, description, duration etc. everything gets loaded, but the video itself is just black and doesn't play.

I'd suggest to check for geo-blocked videos and show an alert if the user tries to play them, and also show like a small globe next to the timestamp in the videos list.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Myzel394** [comment]
I'm sorry I just found out about #2056, but this still seems to be an issue

**Comment by Bnyro** [comment]
That might be due to the Piped federation via Matrix.
If a video is geo blocked, usually there shouldn't be anything returned by the instance except for an error, so neither the title nor the description. In such cases, we already show proper error messages.
