### ISSUE TITLE
Implement support for the new upcoming feed pagination in API

### ISSUE THREAD

**Issue by FireMasterK** [libre-tube/LibreTube#3693]
### Describe your suggested feature

See https://github.com/TeamPiped/Piped/pull/2353

We need to take the last video's `uploaded` timestamp and use that as the `start` query parameter.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Closing to keep the issue tracker clean.
