### ISSUE TITLE
Add support for Invidious as a video source

### ISSUE THREAD

**Issue by sagervrma** [libre-tube/LibreTube#3695]
### Describe your suggested feature

LibreTube is an excellent open-source alternative to YouTube, but I believe it would be even better if it could support Invidious as a video source. Invidious https://github.com/iv-org/invidious is a privacy-focused front-end for YouTube that does not send any identifying information to YouTube, making it an ideal video source for LibreTube users who value their privacy.

Adding support for Invidious would bring several benefits to LibreTube users, including:

 1.   Increased privacy: Invidious is designed to protect users' privacy by not sending any identifying information to YouTube, which means that LibreTube users can watch YouTube videos without compromising their privacy.

2.    Reduced reliance on YouTube: By supporting Invidious as a video source, LibreTube can reduce its reliance on YouTube's infrastructure and algorithms, making it a more decentralized and independent platform.

3.    Improved performance: Invidious uses a proxy to request and stream YouTube videos, which can reduce the latency and buffering time. Additionally, Invidious caches frequently accessed videos, which can further improve its performance. like this app does https://github.com/lamarios/clipious

I believe that adding support for Invidious as a video source would be a valuable addition to LibreTube, and I hope that the development team will consider implementing this feature. Thank you for your consideration.

### Other details

By adding Invidious as a video source, LibreTube could provide users with an even more private and decentralized video streaming experience. Invidious acts as a proxy for YouTube, which means that users can watch YouTube videos without sending any identifying information to Google. This can help to protect users' privacy and reduce the risk of tracking and profiling.

In addition, Invidious has some unique features that are not available on PeerTube, such as the ability to search for and play YouTube videos directly within the application. By integrating Invidious into LibreTube, users could enjoy these features without sacrificing their privacy or decentralization.

Attachment:

Technical Requirements:

   ☄️ Integration of Invidious API into LibreTube codebase
   ☄️ Implementation of Invidious search and video playback functionality within LibreTube
    ☄️Testing and debugging of Invidious integration in a variety of network and device configurations

Examples of Implementation:

   ☄️ Invidious search bar and video playback option in LibreTube sidebar
  ☄️  Invidious as an option in LibreTube's video source menu
   ☄️ Integration of Invidious caching and video recommendation features into LibreTube's video feed

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
There are no plans to support any other platforms or APIs than Piped. I myself am one of the maintainers of Piped, therefore LibreTube has always been meant to be only the Android client for Piped and nothing else. Piped proxies all requests and anonymizes all your traffic, in my opinion even more than Invidious. I doubt you really read the README of this project and the one of Piped, so please do so to get a deeper understanding. We do **not** connect to YouTube's servers directly, LibreTube hence does **not** send any personal/IP data to YouTube's servers.
(Please also keep in mind that this would cost a lot of efforts and refactoring which is not possible with the current amount of resources and contributors to the code.)

Anyways, thanks for the suggestion.
