### ISSUE TITLE
Support for AV1 when the device supports it

### ISSUE THREAD

**Issue by FireMasterK** [libre-tube/LibreTube#3700]
### Describe your suggested feature

We can support AV1, on devices that support it. (Only a few flagship phones released in the past 2-3 years seem to support it currently)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
This would require us to depend on this module locally in the project as per https://github.com/google/ExoPlayer/blob/dev-v2/extensions/av1/README.md - there's no prebuilt library, which I don't want to do.
