### ISSUE TITLE
Spanish translation error

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#3701]
### Steps to reproduce

There is a mistake, probably due to keyboard predictions while translating strings.
It is "Settings > Audio and Video > Disable Piped proxy".
While in spanish says "Deshabilitar el próximo de Piped",
it should be "Deshabilitar el proxy de Piped".
"Proxy" doesnt have literal translation in spanish, and we say it as is, in english. But here the translator was using corrections in his keyboard, then "proxy" was corrected as "próximo", wich has no sense in the sentence.

### Expected behavior

Simply say "Deshabilitar el proxy de Piped" in the option.

### Actual behavior

It says "Deshabilitar el próximo de Piped"

### LibreTube version

any

### Android version

any

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FireMasterK** [comment]
Please fix it here: https://hosted.weblate.org/projects/libretube/libretube/es/
