### ISSUE TITLE
Use Current Brightness When Switching To Fullscreen

### ISSUE THREAD

**Issue by akano12** [libre-tube/LibreTube#3707]
### Describe your suggested feature

As the title say, make LT use current brightness level when switching to fullscreen. 

### Other details

It would be great if this can be done because LT currently use previous brightness level when switching to fullscreen, which is blinding at night.

Let's say I'm watching a video in portrait at 25% brightness level at night, when switching to fullscreen I'll be hit with blinding outdoor mode brightness level which i used earlier. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by UrsulaTheWitch** [comment]
Swipe on the left side of the fullscreen to adjust brightnes. Down for darker, up for brighter and all the way down for auto. 
If the control is not there go into settings, player, then turn on swipe controls

**Comment by akano12** [comment]
> Swipe on the left side of the fullscreen to adjust brightnes. Down for darker, up for brighter and all the way down for auto. 
> If the control is not there go into settings, player, then turn on swipe controls
> 

![9k=.jpg](https://github.com/libre-tube/LibreTube/assets/50032603/15f56b4c-602a-4c66-9d38-254be7ac9d21)

**Comment by akano12** [comment]
> Swipe on the left side of the fullscreen to adjust brightnes. Down for darker, up for brighter and all the way down for auto. 
> If the control is not there go into settings, player, then turn on swipe controls
> 

🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️
