### ISSUE TITLE
`Bookmark` & `Download` buttons for playlists 

### ISSUE THREAD

**Issue by SameenAhnaf** [libre-tube/LibreTube#371]
### Describe your suggested feature

Add these two buttons for better experience while downloading playlists. Also, consider implementing YouTube app behavior (like saving playlist info, auto-syncing if a new video is added to that playlist etc.) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by martin-desktops** [comment]
Being able to bookmark "official youtube" users' playlists to the playlist tab, (aka Library) would be so useful, but I think it would require implementation across the whole Piped, not only inside the app for keeping parity

**Comment by Bnyro** [comment]
> Being able to bookmark "official youtube" users' playlists to the playlist tab, (aka Library) would be so useful, but I think it would require implementation across the whole Piped, not only inside the app for keeping parity

Yes, I agree!

**Comment by SameenAhnaf** [comment]
@Bnyro Is it required to close issues if maintainers don't have time to implement? These issues could have caught attention of other devs.

**Comment by Bnyro** [comment]
Bookmarking isn't required since you can now just clone playlists from YouTube to your library and making them downloadable is planned but we have to fix some issues with downloads first.

**Comment by Bnyro** [comment]
We're just closing them to keep an overview about what's most important rn

**Comment by SameenAhnaf** [comment]
You could have used labels like `High Priority`, `Important` or `Help wanted`.  Issues should be closed if they are completely rejected or relevant PR is merged.

**Comment by SameenAhnaf** [comment]
@drishal I think, we might be a little more patient. @Bnyro was keeping open a few issues to solve them at first. It's be pain in the a** to reopen all issues and label the important ones.
