### ISSUE TITLE
No button Shorts in NavPanel

### ISSUE THREAD

**Issue by adu-lab** [libre-tube/LibreTube#3710]
### Steps to reproduce

Just open the app and notice that there is No button Shorts in NavPanel.

### Expected behavior

Shorts button exists by default in NavPanel.
And option for its hiding can exist in main Settings for those, who don't want to see it.

### Actual behavior

No button Shorts in NavPanel

### LibreTube version

0.14.1 debug

### Android version

Android 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by adu-lab** [comment]
I don't get it. How is that related? I am not asking to show 5/6/7..... Tabs simultaneously. Only by choice: 2 tabs. Home (and btw not in its current state with 12 const Trend videos only! This should be endless list of suggested videos based on my local history of watching. Like stock YouTube does) and Shorts (also with simple endless list of suggested videos). I will not login in account. Will mot follow any channels. Will not do any subscriptions.

**Comment by Bnyro** [comment]
There's no APU support for a shorts tab.
