### ISSUE TITLE
Not respected one Setting

### ISSUE THREAD

**Issue by adu-lab** [libre-tube/LibreTube#3711]
### Steps to reproduce

Open main settings, go to Appearance - Layout. Set alternative player layout. And set 1 grid column.

### Expected behavior

After that when i will switch to the main application screen i will see Single-column endless video output. Just like it was by default in the stock YouTube player. I am talking about its first "tab" Home? Don't know its name, just know it before its Shorts tab.

### Actual behavior

I see 2column of something named What's trending now. I don't know what it is and even do not want to see it at all here. Especially when this "something" shows only constant 12 videos. And only.

### LibreTube version

0.14.1 debug

### Android version

Android 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The setting doesn't apply for the home tab. Go to Settings -> Appearance -> Navigation Bar -> Order, disable the home tab and enable trends.
