### ISSUE TITLE
No download playlists 

### ISSUE THREAD

**Issue by markandgavin** [libre-tube/LibreTube#3721]
### Describe your suggested feature

When I download music it would be nice to have a playlist so it auto plays 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Duplicate of #3080
