### ISSUE TITLE
Exit gesture in fullscreen mode on a Short opens mini player

### ISSUE THREAD

**Issue by powermaker450** [libre-tube/LibreTube#3722]
### Steps to reproduce

1. Make sure the "Enter/exit fullscreen gestures" setting is enabled
2. Play any YT Short content
3. Enter fullscreen mode
4. Swipe down to exit the fullscreen content, where it will exit the content but consequently the app as well.

### Expected behavior

The app should exit fullscreen after executing the exit gesture on a Short and resume playing the video content in normal, non-fullscreen mode.

### Actual behavior

The app upon executing the exit gesture on a Short exits fullscreen mode but also exits the app, bringing a minor annoyance.

### LibreTube version

0.14.1

### Android version

Android 13

### Other details

-Upon exiting the app due to this bug, it does not fully quit (not a crash) and the video/Short content that was playing is not interuppted.
-This bug does not happen on non-Short, normal video content and the enter/exit fullscreen gestures work as expected.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by luckkmaxx** [comment]
I tested this and it happen in normal videos too.

**Comment by E0697** [comment]
> I tested this and it happen in normal videos too.

Yes, intermittently.
