### ISSUE TITLE
Use a different instance for each video

### ISSUE THREAD

**Issue by isuseterful** [libre-tube/LibreTube#3725]
### Describe your suggested feature

I would like to be able to use a different instance for each video I watch on LibreTube. This would improve load balancing and would also make your traffic more fuzzy if an instance decides to suddenly track it's users. This might involve switching the instance automatically if a video freezes or an instance goes down temporarily.

### Other details

In the instance chooser menu, I would like to be able to have an option that says "Random" instead of setting a fixed instance. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
I don't know, but in my opinion the problems of such implementation are more than the benefits.

>make your traffic more fuzzy if an instance decides to suddenly track it's users

Doesn't make any sense, if you're being tracked by an instance, once you switch to another one it won't be able to know anything about you.
And even by randomly switching between instances, LT will always select between instances including the tracking one. Ye this will minimize the information collected but you're still being tracked. 

>switching the instance automatically if a video freezes or an instance goes down temporarily

This is extremely terrible approach, not everyone have fast internet. 
If LT is loading a video on a slow network and the video is taking too much to load, let's assume LT switches to another instance, LT would have to attempt to load thr video from beginning, which again will take too much time to load.
This will result in an endless loop of LT switching back and forth between instances

**Comment by Bnyro** [comment]
I agree with akano12, hence closing.
