### ISSUE TITLE
Playback gets paused when app is bot in focus on galaxy s22+

### ISSUE THREAD

**Issue by justAguy321** [libre-tube/LibreTube#3734]
### Steps to reproduce

1 play any video / stream
2 turn device into sleep mode /or/ go to home page
3 let video play for a bit untill undesired effect appears (around 1 to 3 minutes / verries depending on conection speed?, ram?, possable error with how the app is handleing being run as a background task.)

### Expected behavior

1 open any video / stream
2 do anything that would put the app to run as a background app. Examples would be hitting the power button or opening a diffrent app without closing LibreTube.
3 enjoy the video without interruptions whilst you do what your heart desires.

### Actual behavior

Playback interupted when app is run in background.

### LibreTube version

0.14.1

### Android version

Android 13

### Other details

Samsung galaxy s22+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The solution described above is probably the best way. Certain devices restrict the app's battery usage which can cause such issues, but they're not the app's fault but rather due to weird battery management in the manufacturers ROM.
