### ISSUE TITLE
Display icons next to their names in App Icon settings tab

### ISSUE THREAD

**Issue by martin-desktops** [libre-tube/LibreTube#374]
### Describe your suggested feature

Every icon should be presented next to its name, allowing for easier getting acquainted with all possibilities and choosing favorite one. After all, icons are icons, not text, names.

E.g:
![IMG_1235](https://user-images.githubusercontent.com/64419373/172018106-8580b84c-3c46-4699-93e0-11b7d71aac03.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's true but it would require much work. I currently don't think it's worth changing it since you can just try all of them in less than 30 seconds

**Comment by martin-desktops** [comment]
Understandable, I am aware it's only a sitter, but if you ever will be out of important issues at some point feel free to come back here ^^
