### ISSUE TITLE
Allow to reorder entries on playlist

### ISSUE THREAD

**Issue by matkoniecz** [libre-tube/LibreTube#3740]
### Describe your suggested feature

Allow to drag items on playlist to reorder them

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not possible without API support.
