### ISSUE TITLE
exit fullscreen gesture boundaries 

### ISSUE THREAD

**Issue by sakgoyal** [libre-tube/LibreTube#3744]
### Describe your suggested feature

The gesture to swipe out works fine, But I also want to be able to swipe down from any part of the screen. 
Currently I think it only works from the middle of the screen but not on the sides. Can there be a toggle so you can swipe down from anywhere?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That would conflict with the other swipe controls, we can make it work everywhere on the screen only if swipe gestures for volume and brightness are disabled.

**Comment by Bnyro** [comment]
A preference for it doesn't make sense imo since it just won't work when other swipe gestures are enabled. And when they're disabled, there's no reason to not let the full screen gestures work on the whole screen.
