### ISSUE TITLE
Use Android built-in caption style

### ISSUE THREAD

**Issue by noClaps** [libre-tube/LibreTube#375]
### Describe your suggested feature

I'd like the caption/subtitle style to match my caption settings in Android.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't think we can access your system subtitle settings

**Comment by noClaps** [comment]
Just tested and Newpipe is able to do it. Maybe you can look at their implementation?
