### ISSUE TITLE
Start in the tendancies even if the tab is disabled

### ISSUE THREAD

**Issue by stemy2** [libre-tube/LibreTube#3756]
### Steps to reproduce

1. Go to settings.
2. Disable "tendancies" in the navigation bar settings.
3. Restart the app.

### Expected behavior

The tab actually showed must match with the tab actually selected.

### Actual behavior

The selected tab is -in my case- "subscriptions" but the app shows "tendancies".
![Screenshot_20230511-165721_LibreTube](https://github.com/libre-tube/LibreTube/assets/22192600/b2d4712a-291f-4cf6-86b3-c50f40f43c98)
I clicked on the "subscriptions" tab, and now, it shows the subscriptions.
![Screenshot_20230511-165742_LibreTube](https://github.com/libre-tube/LibreTube/assets/22192600/0086eb37-ff85-4a79-a0e2-6c41c1936a4c)

### LibreTube version

0.14.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Set the home tab by clicking the home icon in the preference dialog you mentioned above (navigation bar settings).

**Comment by r1klz** [comment]
> I enabled the home tab, it still starts on the same page, and i want it start in the subscriptions tab.

Mine is working perfectly. Are you sure that you selected the Home icon to which one you want? @stemy2

**Comment by stemy2** [comment]
Sorry for the PEBKAC, i didn't understood until right now. So problem solved.
