### ISSUE TITLE
Video compressor for bad internet please.

### ISSUE THREAD

**Issue by HageFale** [libre-tube/LibreTube#3760]
### Describe your suggested feature

I dont know if you have this already i didnt watch the source code but for bad internet can you add some type of video compression for lower data file that you can watch video if you have good cpu with bad internet. 
i though about something like that: https://github.com/natario1/Transcoder
or:
https://github.com/adnortje/deepvideo

### Other details

Make viseo watchable with terrible internet in terrible countries with terrible connection thanks if thats possible.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FireMasterK** [comment]
This is not really possible as you are served the exact video from YouTube. Compressing videos a second time doesn't make sense since YouTube already compresses videos great (using vp9 on most videos).
