### ISSUE TITLE
Add a confirmation dialogue before deleting a channel group

### ISSUE THREAD

**Issue by GET100PERCENT** [libre-tube/LibreTube#3763]
### Describe your suggested feature

Add a confirmation dialogue before deleting a channel group.

1.An extra step wil not bother anyone because no one frequently deletes the channel groups and also don't  use multiple channels groups at once.

2. Once the group is deleted , you have to choose all the channels for that group which is more complex.

3. The delete button is very near to the edit button, so oftenly it gets deleted when trying to edit (add more channels to the channel groups).

### Other details

![Screenshot_20230513-120929](https://github.com/libre-tube/LibreTube/assets/116144024/6e457f64-b2e4-4b42-a1b6-7feca9c23b42)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by shuvashish76** [comment]
Request to add a message "Are you sure you want to delete xyz?" just like we've "confirm unsubscribing" dialog. Currently the edit & delete options are too close that it's too easy to misclick delete option. It takes really long time to create channel groups & 1 misclick & you've to do it all over again.
