### ISSUE TITLE
When i try to play something with my screen off it crashes 

### ISSUE THREAD

**Issue by markandgavin** [libre-tube/LibreTube#3764]
### Steps to reproduce

1. I Plat something 
2. I turn screen off
3. It play for like 20 sec
4. It says something along the lines of "there seems to be a problem with the server....."
5. 

### Expected behavior

It should just keep playing 

### Actual behavior

It pauses 

### LibreTube version

. 14.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please use the audio / background node for playing with the screen off.
