### ISSUE TITLE
Add option to not apply Material You color accent to playbar

### ISSUE THREAD

**Issue by ticklemyIP** [libre-tube/LibreTube#3765]
### Describe your suggested feature

Some material You color palettes make the playbar vary hard to read with Sponsor Block bars and other elements, especially light and mute colors. A feature to disable this and to use some kind of default color would be nice. Maybe the default YouTube or LibreTube red. Additionally custom colors may be set as well.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not planned, the app strictly follows the themes color's.
