### ISSUE TITLE
Remove bookmarks/playlists from home page

### ISSUE THREAD

**Issue by akano12** [libre-tube/LibreTube#3766]
### Describe your suggested feature

To continue the discussion from https://github.com/libre-tube/LibreTube/issues/2759 

I do hope you remove bookmarks/playlists from home page because 

1. They're available on the library page (where they belong). 

2. They make the home page take more time to load especially on slow networks, home page won't load until subscriptions/bookmarks are fetched first.

3. On each tab transition from any tab to the home tab they're fetched, and again, home page won't show any content till bookmarks/Playlists are fetched.

### Other details

Bookmarks and playlists already exist on subscriptions page

https://user-images.githubusercontent.com/50032603/238021457-b3aed73c-de1a-4e39-a846-bf6b860b4477.jpg

This how home page looks if LT fails to fetch for whatever reason

https://user-images.githubusercontent.com/50032603/238021590-d76d1987-0a59-4891-8433-aa47690fc692.jpg

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
> Use the trend page if you want.

Reminds me of the time i went to an optometrist 5 years ago because i had vision problems, he told me to change the shampoo I'm using and charged me 50$ when I needed glasses for my problem.

**Comment by Bnyro** [comment]
The home page would only consist of featured/subscribed videos and trends then. Wouldn't it be pointless to have a dedicated home page only for these two?

**Comment by akano12** [comment]
> The home page would only consist of featured/subscribed videos and trends then. Wouldn't it be pointless to have a dedicated home page only for these two?

It's not like i have personal problems with playlists/bookmarks.
They're already available in the library tab (again, right where they belong)

I have 16Mbps internet speed, but the isp I'm subscribed to throttles the internet during peak times and night, rn the speed is less than 1Mbps. 

If you'd like to keep it as is, it's fine, it's up to you after all. But i hope you'd at least disable the fetching of bookmarks and playlists after each tab change, only fetch them on app launch and if the home tab is explicitly refreshed using the swipe down to refresh, i believe that's a fair solution. 

Also here's this recording, this is how it loads on slow network, on each switch from whatever tab to home it behaves like this, takes 3-4 seconds load.

https://github.com/libre-tube/LibreTube/assets/50032603/d9ccac5d-1212-42e0-a2b5-24ddb404c946

And in case the request time out it hangs like this

https://user-images.githubusercontent.com/50032603/238021590-d76d1987-0a59-4891-8433-aa47690fc692.jpg

**Comment by Bnyro** [comment]
I don't think that would be an ideal solution.
My idea would be to create a preference in the settings, which has 4 checkboxes to enable/disable
1. Featured videos
2. Trends
3. Bookmarks
4. Playlists
in the home page.
