### ISSUE TITLE
"Currently playing" notification video information

### ISSUE THREAD

**Issue by mkikets99** [libre-tube/LibreTube#377]
### Steps to reproduce

1. Play something
2. Close app in background
3. Open notification

### Expected behavior

Notification must show at least currently playing video, but video preview image could be good too.

### Actual behavior

No text applied

### LibreTube version

0.3.1

### Android version

Android 12

### Other details

Using it on Samsung Galaxy Note 10+
Image of issue (Ukrainian language on phone, but video is with Latin characters only)
![Screenshot_20220604-235231_Nova7](https://user-images.githubusercontent.com/22869811/172025302-ecc05ef1-e2a5-4948-80ef-1bfbcae835cd.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It's not broken, it's just in beta?

**Comment by mkikets99** [comment]
Also, if open "Output media" section on samsung, it outputs as "Without name" or "No name"
![Screenshot_20220605-000019_Media and devices](https://user-images.githubusercontent.com/22869811/172025351-4bd40565-a7d8-4f46-91ed-a3b28268515d.jpg)

**Comment by mkikets99** [comment]
> It's not broken, it's just in beta?

So its just not ready yet, right?
 😏 Interesting

**Comment by Bnyro** [comment]
It's not low priority, I'm just the only Dev atm and I also have other stuff to do...
There are so many open issues but I can't handle all of them at the same time, I'm not almighty

**Comment by mkikets99** [comment]
Ok. take your time.
This is a small bug that just can bother someone.
It is working good with `Next` `Previous` and `Play/Pause` buttons. just an issue with name.
Maybe I will look if I can find where it is...
