### ISSUE TITLE
The page displays errors and cannot be displayed. I hope to add customizable options to solve this problem.(頁面顯示錯誤、無法顯示的問題，希望增加可自訂選項解決此問題)

### ISSUE THREAD

**Issue by yiont** [libre-tube/LibreTube#3777]
### Steps to reproduce

當開啓App時顯示「現正熱門」和「精選影片」，而不是訂閱的畫面，如圖中圈起來的部分。
When the app is opened, "Now Popular" and "Featured Videos" are displayed instead of the subscription screen, as circled in the picture.
![Screenshot_20230515-204824_LibreTube_1](https://github.com/libre-tube/LibreTube/assets/127585991/528b8922-b3fe-4c82-9355-a699e9cee656)
我希望這個錯誤能被解決，就是開啓App時可以自訂自己想要顯示的畫面，而不是上面那張圖的畫面，可以自訂不要讓「現正熱門」的畫面出現，而顯示訂閱列表的畫面等等，希望這個錯誤儘快解決，NewPipe這點做的比較好，可以自定義。...這是個錯誤，可能需要開發者來解決，我會非常感激你的。
I hope this error can be resolved, that is, when you open the app, you can customize the screen you want to display, instead of the screen in the picture above, you can customize the screen that does not show the "hot now" screen, but display the subscription list Screens, etc., I hope this error will be resolved as soon as possible. NewPipe does this better and can be customized. ...this is a bug and may need to be fixed by the developers, I would be very grateful to you.
![Screenshot_20230515-211120_LibreTube](https://github.com/libre-tube/LibreTube/assets/127585991/04015be1-ba3c-40c0-b246-e174634a4aa6)

### Expected behavior

I think this should be fixed.
It may be caused by not having this option.

### Actual behavior

hope to be resolved

### LibreTube version

版本 Version 0.14.1

### Android version

LineageOS Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
And don't write Chinese here.
