### ISSUE TITLE
Playlist thumbnail not changing until gets fully empty

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#3783]
### Steps to reproduce

Hi, I reported this issue in piped-frontend too. Because it happens also there.
Here is the issue: https://github.com/TeamPiped/Piped/issues/2406

Maybe yo need to know and see how do Libretube fetches playlist thumbnails.

### Expected behavior

Change the playlist thumbnail if it related video was removed from it.

### Actual behavior

Keeps the same until you empty the playlist and add a new video, from wich takes its thumbnail

### LibreTube version

any

### Android version

any

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FireMasterK** [comment]
It's a backend issue, you've already opened an issue at the Piped repository.

**Comment by luckkmaxx** [comment]
Yes I did but under frontend page, does it matter?

**Comment by FireMasterK** [comment]
> Yes I did but under frontend page, does it matter?

That's okay, the backend issues are tracked there as well!
