### ISSUE TITLE
Option for app to automatically select best-performing/working instance.

### ISSUE THREAD

**Issue by ghost** [libre-tube/LibreTube#3784]
### Describe your suggested feature

As the title says.

### Other details

A check could be performed each time the app is started and a selection made automatically based on the results. Also this process should be initiated when connectivity issues are experienced mid-way through a video.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Duplicate of #3269
