### ISSUE TITLE
Auto-exit fullscreen when video or latest item in playlist finishes.

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#3786]
### Describe your suggested feature

An option in settings to enable auto-exit from fullscreen mode.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Doesn't seem useful at all, leaving full screen is just a single tap so why should we make an option for such a minor unimportant thing? Hence, not planned.

**Comment by luckkmaxx** [comment]
well, maybe its equal important than auto-fullscreen on shorts, or swipe to enter/exit fullscreen, wich can be done with a single tap too.
But heres my idea if some other people wants to support it.
