### ISSUE TITLE
Some videos don't work

### ISSUE THREAD

**Issue by Red-lar** [libre-tube/LibreTube#3787]
### Steps to reproduce

1. I search for the video i want... even though there's no filter of search
2. Some videos that I want no appear in the results, but I do search again on my browser and found it then share it with libretube to watch it as I do normally with all videos.
3. The problem is that some videos no works with libretube by searching on it neither by sharing it from my browser.

### Expected behavior

I think there are an old problem with the code because this issue happened with all previous versions.... I guess one of 13 versions not happened! 

### Actual behavior

Just appears libretube GUI with words subscribe and comments

### LibreTube version

0.14.1

### Android version

Android 9

### Other details

 Searching filter and search in history are important 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Looks like Geo blocking on the instance's region.

**Comment by Red-lar** [comment]
> Looks like Geo blocking on the instance's region.

What do you mean ?
