### ISSUE TITLE
adding a video to a playlist is very slow

### ISSUE THREAD

**Issue by voidplayer** [libre-tube/LibreTube#3789]
### Steps to reproduce

1. click to save video to playlist
2. wait 10 seconds for playlist combobox to load
3. click on a second video
4. wait 10 seconds for same playlist combobox to load

### Expected behavior

Even if undesirable, I understand the first load time even tho is just 1 playlist and is only showing the name

But not the second, i just added a video to a playlist a second ago!

### Actual behavior

long waits every time that the playlist combo box is showing

### LibreTube version

0.14.1

### Android version

Android 8.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by rozari0** [comment]
I think this depends on your piped auth instance. 
For me it takes less then 2 seconds.

**Comment by voidplayer** [comment]
Im using the default one

**Comment by Bnyro** [comment]
Not a client side issue.

**Comment by voidplayer** [comment]
Id argue this info should be cached. Being snappy even is the clients responsibility

The webpage of that same instance is instantaneous when showing the playlists to add a video
