### ISSUE TITLE
Subtitles (translation)

### ISSUE THREAD

**Issue by South-Rowlet** [libre-tube/LibreTube#379]
### Describe your suggested feature

Hello, thank you for your app.
I wonder if I can add the ability to translate subtitles? 
I am really not good at English, and it caused a lot of trouble when watching videos. 
(Just like Videoder)
Thank you:)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
How should that be possible? We just use the subtitles generated by YouTube...

**Comment by South-Rowlet** [comment]
Oh, I'm sorry, because I once saw that Videoder has this function.

**Comment by South-Rowlet** [comment]
Anyway, thank you for your great weight.

**Comment by South-Rowlet** [comment]
Anyway, thank you.

**Comment by trizen** [comment]
> How should that be possible? We just use the subtitles generated by YouTube...

See https://github.com/TeamNewPipe/NewPipe/issues/8023 for how this can be done.
