### ISSUE TITLE
Background play not stable

### ISSUE THREAD

**Issue by JohnBetaro** [libre-tube/LibreTube#3794]
### Steps to reproduce

Exit the app and leaving it in the background to continue listening (picture in picture disabled) or turning off the screen when the video is playing.

### Expected behavior

Continue playing the audio in the background and loading it automatically.

### Actual behavior

It will continue playing the audio for sometime then it stops suddenly until I enter the app again, same thing when turning off the screen, it will play for a while then it stops, until I turn on the screen and unlock the phone. 

It's not pausing the video, it's loading it.

### LibreTube version

14.1

### Android version

13 GrapheneOS

### Other details

It seems like when exiting it will not continue loading the video (its audio in this case), it will just play the remaining cached part.

This problem does not happen when using picture in picture, only when just playing the audio.

I hope you'll take a look because the problem is not solved yet as I'm using the latest version 14.1, thank you for your time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FireMasterK** [comment]
I think another solution is to automatically enter audio-only mode when turning off your screen. This could save bandwidth too I think.

**Comment by Bnyro** [comment]
> I think another solution is to automatically enter audio-only mode when turning off your screen. This could save bandwidth too I think.
>
That would probably be very inconvenient for users because the two players wouldn't be synced and the video player with UI might be killed / destroyed by Android shortly.

**Comment by FireMasterK** [comment]
> That would probably be very inconvenient for users because the two players wouldn't be synced and the video player with UI might be killed / destroyed by Android shortly.

Can't we destroy the video player when background mode is enabled, and switch to only the audio player there? When the activity is resumed again, the video player could be recreated then with and the position to start from could be taken from the audio player. The audio player would be destroyed there.

I'm not sure how easy that would be, considering I haven't really seen the code for the player ever :sweat_smile:

**Comment by Bnyro** [comment]
And that's what you'd consider the easier solution than disabling battery optimization? :joy:

**Comment by FireMasterK** [comment]
> So @Bnyro, will you consider my suggestion ?

Please see the last point in https://github.com/libre-tube/LibreTube/blob/master/CODE_OF_CONDUCT.md#our-standards

**Comment by JacenBridger** [comment]
Newpipe has "Display pop-up" permission which is not in Libretube. Can it be the reason?( I don't know btw).
For context :
![IMG_20230518_194909](https://github.com/libre-tube/LibreTube/assets/110893579/980b7e21-465a-4472-baa3-047eaa5f12d2)
![IMG_20230518_194852](https://github.com/libre-tube/LibreTube/assets/110893579/fa4bf8ca-36b7-4ce8-8716-c6c5ab838c92)

**Comment by frmayall1978** [comment]
> duplicate of existing,this is a serious annoying issue probably bcos of Android 13's foreground restrictions ,using audio mode byppasses it but its more annoying watching that audio screen

I am on Android 12 and still facing this problem. 'Unrestricted battery usage' is of no help.

**Comment by Red-lar** [comment]
I had this problem with previous versions until now, i see version 15.0 is the worst, because there is no results appear when searching for a vedio

**Comment by XEmpty** [comment]
Looks like in audio mode work without problem.

**Comment by Bnyro** [comment]
I still suppose to just use the audio mode for that purpose to circumvent any Android battery restrictions. Currently, there's not really a good way or much of a reason to deal with that on the normal video player.

**Comment by Red-lar** [comment]
> I still suppose to just use the audio mode for that purpose to circumvent any Android battery restrictions. Currently, there's not really a good way or much of a reason to deal with that on the normal video player.

Thank you

**Comment by XEmpty** [comment]
Maybe it is another way like auto switch when the app is on the background, let's say to audio, and if it is on the screen, then switch back to videos.  There are possibilities like this ?
