### ISSUE TITLE
Arbitrary channel pages will not load

### ISSUE THREAD

**Issue by mivuzu** [libre-tube/LibreTube#3796]
### Steps to reproduce

While trying to look channels to subscribe to, some do not appear with the subscribe button in the search results and after prompting to open those in specific they will get stuck at loading

Reinstall, network change and app storage wiping do not seem to fix the issue

Selection of channels under this issue appear to be arbitrary and examples, for me at least, include asianometry, vapor memory, losprimerosVIIVI, the friday checkout and many more, actually id go as far to say that it's most channels I happen to try to open.

Please do feel free to tell me if you can reproduce it while opening these channels

### Expected behavior

Channels loads and displays contents 

### Actual behavior

Channels gets stuck at loading

### LibreTube version

0.14.1

### Android version

Android 13

### Other details

Hardware is Pixel 6
Software is the latest release as of posting under GrapheneOS with standard Android memory allocator

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by mivuzu** [comment]
just wanted add video reference.

https://github.com/libre-tube/LibreTube/assets/38266461/aa944aad-87ca-46a6-91f0-5722f7ac1455

**Comment by mivuzu** [comment]
Issue is fixed when accesing without piped account, or accesing in an instance other than kavin.rocks

**Comment by Bnyro** [comment]
Have you tried using a different instance?

**Comment by Bnyro** [comment]
Oh, fair enough.
