### ISSUE TITLE
Some comments incorrectly marked as hearted/pinned by creator

### ISSUE THREAD

**Issue by AdiPathak97** [libre-tube/LibreTube#3797]
### Steps to reproduce

1. View comment in video comments section

### Expected behavior

Comment should appear as pinned/hearted by creator only if actually done so by creator (can be checked on website version)

### Actual behavior

Comments which are not hearted/pinned by creator (as seen on website) appear so on LibreTube.

### LibreTube version

0.14.1

### Android version

Android 13

### Other details

Comment appearing as pinned/hearted in Libretube:
![Screenshot_20230519-223511](https://github.com/libre-tube/LibreTube/assets/36631927/8d491fdc-b2e1-41e5-b80c-55eed06e897b)

Same comment not seen as pinned/hearted in website:
![Screenshot_20230519-223734](https://github.com/libre-tube/LibreTube/assets/36631927/323378a8-d6ab-46b1-8292-b92bd3ecf9d2)

Note: this only seems to happen in comment replies, not top level comments on a video.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That looks like an issue of the NewPipe Extractor since we simply use the extracted data to mark comments as hearted. Please open an issue at their repo and also provide steps to reproduce!
