### ISSUE TITLE
Auto play button!

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#380]
Automatic video playback function.Also auto-play videos in the playlist (open / close)

**Comment by Legoks** [comment]
Will this be a feature?

**Comment by Bnyro** [comment]
Somebody already started to work on it but he stopped because he was busy.

**Comment by Legoks** [comment]
Will this feature not be available then?

**Comment by Bnyro** [comment]
I hope he will find the time to finish it, if so yes.

**Comment by Legoks** [comment]
Can't anyone else?

**Comment by Bnyro** [comment]
Anyone else would be me and I won't steal his work

**Comment by Bnyro** [comment]
His pull request is still open :)

**Comment by ydqsbfsyi** [comment]
Yeah, please enhance this, it does not have to be a button, in playlist play next should be auto.
