### ISSUE TITLE
Crash while downloading video

### ISSUE THREAD

**Issue by whwdzg** [libre-tube/LibreTube#3800]
### Steps to reproduce

1.download a video
2.wait for minutes, then it crash

### Expected behavior

should go well

### Actual behavior

crash

### LibreTube version

0.14.1

### Android version

android 10-13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please provide a crash log, looks like a duplicate though, so closing.
