### ISSUE TITLE
Swipe down gesture for miniplayer !

### ISSUE THREAD

**Issue by IndusAryan** [libre-tube/LibreTube#3801]
### Describe your suggested feature

like og YT,when player is in miniplayer mode and instead of tapping cross we swipe it down and it closes.
will be very useful imo

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#2020
