### ISSUE TITLE
Endless video buffering after forwarding or rewinding player position

### ISSUE THREAD

**Issue by frmayall1978** [libre-tube/LibreTube#3803]
### Steps to reproduce

1. Play any video
2. Double-tap left or right side of player to forward or rewind, or seek
3. It lets you skip without any issue at first, but when you push it too far (e.g. skip 45 seconds) it gets stuck in buffering and never exits from it
4. Kill app, launch it again, and reopen the video to be able to keep watching the video

### Expected behavior

The video should buffer after skip, but then actually let the video play.

### Actual behavior

The video gets stuck in an infinite buffering, so that only by restarting the app you can keep watching it.

### LibreTube version

0.14.1

### Android version

Android 12

### Other details

Sometimes I am able to reproduce it, sometimes not. I just tried to reproduce it, but as of right now it skips without fail.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Edit:

Syntax and grammar

**Comment by akano12** [comment]
Maybe network problems? Instance problems? Does it happen with all videos? What's the preloading value set in settings -> player? 

There isn't much info here to tackled the issue. So you) I'll suggest few things to try perhaps it would limit the causes. 

Few things to try:

- Checking your internet speed on speedtest or fast. 
- Changing instance.
- Testing with VPN. 
- Testing on another videos.
- Changing your default dns server (I'm personally using quad9)

**Comment by frmayall1978** [comment]
> Maybe network problems? Instance problems? Does it happen with all videos? Does LT behave the same on other devices? What's the preloading value set in settings -> player?
> 
> There isn't much info here to tackle down the issue. I'll suggest few things to try perhaps it would limit the causes:
> 
>     * Checking your internet speed on speedtest or fast.
> 
>     * Changing instance.
> 
>     * Testing with VPN.
> 
>     * Try playing another video.
> 
>     * Test on another device.
> 
>     * Changing your default dns server (I'm personally using quad9)

My internet speed is average, to the point of not being a problem with any other element of my phone; although it does seem sometimes that the issue may lay in my connection speed, but then the "infinite buffering" happens when my reception is good and the video starts at 720p no problemo, in a fraction of a second. Then I put the video in the background, then put it back in foreground after some time and first thing that happens is the "infinite buffering".
I switched instance and just as I start thinking it's allz good - it hits me with the infamous "infinite buffering" (on any video). I do not posses any other device to test it, but other than that would be willing to provide additional info if pointed in right direction. It also seems that no one else has the problem, hence this is not a duplicate of any other issue.

**Comment by Bnyro** [comment]
Since other users don't seem to have the same issue, it's either caused by your network, instance or device.
