### ISSUE TITLE
removing wrong video from playlists after sorting it by newest

### ISSUE THREAD

**Issue by mohamed591195** [libre-tube/LibreTube#3807]
### Steps to reproduce

1. add a video to any playlist you created
2. change the sorting from default (oldest) to newest
3. try removing video by swiping it out of the screen
4. Now refresh the playlist to find out that the video is still exist and another video is deleted! 

### Expected behavior

the swiped video should be deleted correctly if I changed the sort method of the playlist

### Actual behavior

It deletes different video, may be it's random 

### LibreTube version

0.14.1

### Android version

Android 11

### Other details

Additionally when a video is removed from a playlist, the thumbnail at the top of the playlist should be updated to the thumbnail of the next video in the list.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Already fixed in debug builds.
