### ISSUE TITLE
Audio playback issues when transitioning from video to audio modes.

### ISSUE THREAD

**Issue by mohamed591195** [libre-tube/LibreTube#3808]
### Steps to reproduce

1. Select a random video to play.
2. From the menu below, choose the audio mode option.
3. In most cases, the audio will stop playing even if the internet connection is strong.
4. Move back to video mode and playback should function correctly.
5. Returning to audio mode, audio playback may resume, but it is not guaranteed.
6. It may be necessary to repeat steps 4 and 5 to achieve smooth playback, as the behavior is unpredictable.

### Expected behavior

the audio should play smoothly 

### Actual behavior

random stops in play and it could last for several minutes!

### LibreTube version

0.14.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Fixed in #3878

**Comment by mohamed591195** [comment]
Great Work, keep it up 💪
