### ISSUE TITLE
Volume and Brightness gestures

### ISSUE THREAD

**Issue by Legoks** [libre-tube/LibreTube#381]
Gesture control function of volume and brightness.

**Comment by Logomotif** [comment]
Will it be added?

**Comment by Bnyro** [comment]
No, I don't think it would improve the app.

**Comment by FarisZR** [comment]
Its one of the biggest features I miss from NewPipe when using Libretube, it makes it easy to change the brightness and volume when in full screen.

**Comment by Donkey-Doug** [comment]
If this ever gets added, in my opinion Cloudstream (which is open source) has the best implementation for these gestures. Better than VLC and NewPipe.

Gesture example:

https://user-images.githubusercontent.com/50382414/193138111-4517db1d-ea17-43ab-9edf-01121aff1685.mp4
