### ISSUE TITLE
Pressing now playing notification doesnt open app after media3 migration!

### ISSUE THREAD

**Issue by IndusAryan** [libre-tube/LibreTube#3811]
### Steps to reproduce

play any video and throw the app to background by tapping home screen or the audio button
pull quick switch and tap now playing notification

### Expected behavior

the app should open

### Actual behavior

but the notification panel gets closed and app is not launched

### LibreTube version

Latest Alpha

### Android version

A13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by rozari0** [comment]
Works fine for me.  (Android 9)

**Comment by FireMasterK** [comment]
I couldn't reproduce this either. What device and os is this?
