### ISSUE TITLE
option to select custom downloader app

### ISSUE THREAD

**Issue by soymadip** [libre-tube/LibreTube#3826]
### Describe your suggested feature

If we can select custom downloader to download videos (like if we press download button, it will down with the selected app instead of app's in-built downloader).

- As example, in revanced YouTube:-

https://github.com/libre-tube/LibreTube/assets/84225810/6e12ed10-044d-4a18-8fb5-34d7e70c41db

i used an app called **YTdlnis** to download and in setting i added the package name of the app.
there are many useful downloader  apps like seal or powerTube........

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't you just share the URL to the app (with the share button in the player page)? I don't really see the point of this honestly.

**Comment by soymadip** [comment]
> Can't you just share the URL to the app (with the share button in the player page)? I don't really see the point of this honestly.

yeah i can, but for some reason the in-app downloader doesn't work for me in any of my device so for people like me it will be better if we can just download with external app with the downloader app.

and besides, if apps in our device works with one another, this will make life life easier😅 (like without the complications of going through first pressing the share then selecting piped/yt link to share and then finally downloading with external app, we can just press download button and the external app's download screen will appear ) .

**Comment by Bnyro** [comment]
Currently not planned since it's already possible by sharing a link to the downloaded app. Thanks for the suggestion anyways.

**Comment by shuvashish76** [comment]
Duplicate #6073
The feature is available for v[0.24.0](https://github.com/libre-tube/LibreTube/releases/tag/v0.24.0)
