### ISSUE TITLE
Yt music home page

### ISSUE THREAD

**Issue by owencz1998** [libre-tube/LibreTube#3829]
### Describe your suggested feature

Can we get yt music home screen with the option to make it default to as would be awsome to be able to just use it as a music app to 😄

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The NewPipe Extractor Piped uses currently doesn't support YT music specific content.
