### ISSUE TITLE
An option to use YouTube API

### ISSUE THREAD

**Issue by matt873** [libre-tube/LibreTube#3834]
### Describe your suggested feature

It would be helpful for those who don't care much about fetching data directly from YouTube servers (have the "Disable Piped proxy" option enabled) and will improve the loading of videos significantly.
It will also make it possible to fetch the correct video download size for different formats before downloading it.

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by rozari0** [comment]
👎

Also, I'm pretty much sure youtube API doesn't return download size.

**Comment by Bnyro** [comment]
Out of scope for the project.
