### ISSUE TITLE
下載影片失敗

### ISSUE THREAD

**Issue by songpinray** [libre-tube/LibreTube#3835]
### Describe your suggested feature

影片下方按下載
下載中
一段時間後出現null錯誤

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please only use English!
