### ISSUE TITLE
Improve type filter with buttons instead dropdown

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#3845]
### Describe your suggested feature

Hello.
Right now in video types we can choose between Videos, Shorts or All. Wich is selectable in a dropdown. But I think this could be improved with buttons (like channels page) and there could be multi-selectable, so you can tap both "Videos" and "Shorts" button (maybe "Lives" in a future).
This makes easier to filter and see what is exactly showing, with a more visible method than a dropdown.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I think that would look confusing since we would have filters for the channel tabs and the video type then right next to each other, which makes it hard to distinguish them.

**Comment by luckkmaxx** [comment]
Yes I tought about it. Maybe this have to have different color scheme or shape. Something that can distinguish them.

**Comment by Bnyro** [comment]
In my opinion, there's currently no reason to change the behavior and appearance of the filters. Changing the appearance of something always causes user inconvenience, and I don't see a reason why that should be worth it here.
Thanks for the suggestion anyways!
