### ISSUE TITLE
Notification Settings

### ISSUE THREAD

**Issue by Logomotif** [libre-tube/LibreTube#385]
### Describe your suggested feature

Settings that contain all notification settings

### Other details

Settings that contain all notification settings

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
there are no notification settings?

**Comment by Logomotif** [comment]
No, only Sponsorblock has a Notification section

**Comment by Logomotif** [comment]
This is for SponsorBlock only.

**Comment by Bnyro** [comment]
I don't think we need it

**Comment by Bnyro** [comment]
So you want to have a setting for each sponsor segment to turn off notifications of it?

**Comment by Legoks** [comment]
Bəli,Also new notifications from the channels I subscribe to.

**Comment by Logomotif** [comment]
Yes, as well as new notifications from the channels I subscribe to.

**Comment by Bnyro** [comment]
A notification setting will probably be added with #346, therefore I'll close this as a duplicate
