### ISSUE TITLE
Mic button beside 3 dots to do Voice Search instead of typing.

### ISSUE THREAD

**Issue by IndusAryan** [libre-tube/LibreTube#3855]
### Describe your suggested feature

Voice search is very useful ,most people use it instead of typing.

### Other details

can be looked upon if implementation is not hard or complicated.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not planned since it would only work on devices using Google services, since the logic behind voice input on Android is not foss.
