### ISSUE TITLE
Delete button is not visible in local playlist.

### ISSUE THREAD

**Issue by rozari0** [libre-tube/LibreTube#3857]
### Steps to reproduce

1. Open LT
2. Create or clone a playlist
3. Open that playlist

### Expected behavior

Should show a delete button or a delete option when I click on a video for some time.

### Actual behavior

There isn't anything to perform the delete action.

### LibreTube version

0.14.1 (Both beta and latest alpha)

### Android version

Android 9

### Other details

I'm using it without any account, not sure if this is reproducible with logged-in. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Videos can get removed by swiping to the right.

**Comment by d4f5409d** [comment]
> Videos can get removed by swiping to the right.

It'd be useful to somehow indicate that, I couldn't remove any video from playlist until now, but thanks for explaining.
