### ISSUE TITLE
Error logging out of the application without the Internet!

### ISSUE THREAD

**Issue by Logomotif** [libre-tube/LibreTube#386]
An error occurs when exiting the program when there is no Internet.

**Comment by Bnyro** [comment]
screen recording?

**Comment by Logomotif** [comment]
https://user-images.githubusercontent.com/104307543/172058209-72afbca1-1931-41df-b78f-3b0c50b1fc0c.mp4

**Comment by Logomotif** [comment]
As you can see, an error occurs when exiting the application when there is no internet.

**Comment by Bnyro** [comment]
Weird, which Android Version?

**Comment by Logomotif** [comment]
All Android version

**Comment by Logomotif** [comment]
This is the Android 11 version you are currently looking at.However, this is the case with my Android 5 device.

**Comment by Logomotif** [comment]
In the version released for Android 11, it is not possible to change the settings without the Internet, in the version released for Android 5 version phones.

**Comment by Logomotif** [comment]
But the error exists in both.

**Comment by Logomotif** [comment]
![Screenshot_20220605-200112_LibreTube](https://user-images.githubusercontent.com/104307543/172059482-6d2c23f6-7bfc-4bdc-a85e-202b78580f9d.jpg)

app-armeabi-v7a-release.apk

**Comment by Logomotif** [comment]
This error occurs when you press the back button.

**Comment by Bnyro** [comment]
oh yeah, I pressed the home button before xD
I'll look into it :D

**Comment by Logomotif** [comment]
Will it be solved?

**Comment by Bnyro** [comment]
yes, ty for reporting

**Comment by Logomotif** [comment]
Thank you and I hope this update will not be a mistake.

**Comment by Bnyro** [comment]
why should the update become a mistake?

**Comment by Bnyro** [comment]
we just need some people to really test the app before we release updates

**Comment by Logomotif** [comment]
I wrote the comment incorrectly
