### ISSUE TITLE
Request to add TV projection function

### ISSUE THREAD

**Issue by 2835954229** [libre-tube/LibreTube#3862]
### Describe your suggested feature

Request to add TV projection function

### Other details

You can watch it on TV

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/discussions/3493
