### ISSUE TITLE
After the downloaded file is moved, the software blinks out

### ISSUE THREAD

**Issue by 2835954229** [libre-tube/LibreTube#3863]
### Steps to reproduce

After downloading the video, move the source file in the file management office and then flash back

### Expected behavior

The file can be opened again normally after it has been moved

### Actual behavior

After the video is downloaded, the software blinks back when the file is moved

### LibreTube version

0.15.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#3612
