### ISSUE TITLE
Unable to create/edit groups

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#3864]
### Steps to reproduce

Creating o editing groups, when the channels list is shown, there is no way to apply (all) changes. If you edit a group content then this will be saved by navigating back, but not for group name.
And if you create a new one, it isnt saved because it has not name saved.

### Expected behavior

show "Apply" button

### Actual behavior

No way to apply changes

### LibreTube version

0.15

### Android version

v13

### Other details

This issue was yet advised in the commit, by me.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Temporary workaround: Search for something like some random characters, so that no channel is found. Then the "Okay" button appears on the bottom.
