### ISSUE TITLE
Miniplayer cant be expanded in landscape if was opened in portrait

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#3873]
### Steps to reproduce

1. play some video in normal player in vertical orientation.
2. swipe down or go back to continue playing in miniplayer.
3. turn your device in horizontal
4. try to expand miniplayer to go back to normal player (nothing happens)

in point 2, If you go continue in miniplayer while yet on horizontal mode, there is no problem, and can be expanded there or changing to vertical before expanding.

### Expected behavior

expand the player as expected

### Actual behavior

nothing happen when tapping miniplayer

### LibreTube version

0.15

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
This should be fixed with 0.20.0. If not, please comment here and I'll re-open the issue.
