### ISSUE TITLE
Set a "Pull down to setup and view filters" in feed.

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#3879]
### Describe your suggested feature

As the title says, this feature could handle two problems:

1. This zone is taking too much screen, and could be thankful start seeing videos from upper.
2.  Redesigning this zone could be limited to not take more screen space, and dont break the aesthetic.

So maybe a clean feed page, with a centered little text at top: "Pull down to setup and view filters", could be great.
Then, the same filters zone should appear after pulling down, and re-hide when you slide up the feed.

### Other details

This could permit to feel free to redesign filters/groups/sorts.
And the subscripted channels too.

Pull to refresh shouldnt be affected.

Maybe the hint should appear when you try to pull down, and show the filters with a long-pull-down.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Currently, there are no plans to redesign this part of the app.
I don't see an issue with the current solution.
