### ISSUE TITLE
Screen dims when watching full screen

### ISSUE THREAD

**Issue by Digitalhell666** [libre-tube/LibreTube#3881]
### Steps to reproduce

When transitioning to full-screen the entire screen dims automatically then reverts back when I minimize the screen. 
When I try to adjust it on the dropdown menu it gives a message saying that the screen brightness is being controlled by the app that's running.

### Expected behavior

The screen should be displayed with original brightness setting

### Actual behavior

Full screen results in a dimmer display

### LibreTube version

0.14.1

### Android version

Android 10

### Other details

Galaxy s10+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please update to the latest version.
