### ISSUE TITLE
The video title is "video not available" and the channel name is "YouTube Viewers"

### ISSUE THREAD

**Issue by DoraTee** [libre-tube/LibreTube#3882]
### Steps to reproduce

1. Open the app and click on a video. (Some of the thumbnails of the video are normal and so is all of the information of the videos and YouTube channels.)
The video title is "Video not available" and the video that plays says "This content isn't available" and the YouTube channel name is "YouTube Viewers".
![Screenshot_20230602-003354](https://github.com/libre-tube/LibreTube/assets/135300068/05c382f6-4350-489c-a5a6-0f2a7eea180c)

### Expected behavior

The video should play normally and the channel should have their name. 

### Actual behavior

The video plays the "video is not available" and the name of the YouTube channel is "YouTube Viewers"

### LibreTube version

0.15.0

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by atollk** [comment]
Can confirm, but it seems to be related to the Piped instance. Switching might fix it.

Problematic are: mha.fi and adminforge.de
Ok: privacydev.net

**Comment by KrukWeekend** [comment]
I also got this today.  YouTube up to its usual shenanigans.  I am not fond of the YouTube controllers at all.

**Comment by Rstment25** [comment]
> Can confirm, but it seems to be related to the Piped instance. Switching might fix it.
> 
> Problematic are: mha.fi and adminforge.de Ok: privacydev.net

Is it though? Some videos work ( 1 in every 10 works )

But some don't - either message "this content is not available" shows up, or the longer version attached below
![Screenshot_20230602-072533_LibreTube_1](https://github.com/libre-tube/LibreTube/assets/32986283/dd0384a1-56c1-481a-9a61-0cbdb4dfe012)

**Comment by C0deViewer** [comment]
Hi. I can also confirm that this bug exists.
It also happens if you try to watch it via web browser. It works sometimes in the web browser though, and sometimes not.

**Comment by Bnyro** [comment]
YouTube is A/B testing breaking changes, we hope that the NewPipe Extractor team can find a solution for it. Nothing we could do at LibreTube's side unfortunately.
If the issue gets fixed on the backend side, the app should work fine again without an update.

**Comment by somerand0mcat** [comment]
> 

and also projectsegfau.lt seems to work too

**Comment by franco27** [comment]
Me too, same problem. LibreTube has become unusable. On all videos, which I try to watch, I have that or the other (see screenshot)

![IMG_20230602_134622](https://github.com/libre-tube/LibreTube/assets/31793920/741ec436-da71-4847-a216-8a68b1426db9)


![IMG_20230602_134851](https://github.com/libre-tube/LibreTube/assets/31793920/59418839-e5ca-44f1-ab75-ea887f861374)

**Comment by Bnyro** [comment]
That'd be possible in theory, but it would really be the last option to consider if nothing else works out on Piped's side.
It would be connected to a lot of work and awful for the user's privacy :/

**Comment by luckkmaxx** [comment]
Im facing this today too, but in my case I only see "Video not avaliable" with the correct channel name.
If I enter to these videos then the title is updated with the correct name and can be watched well.
Also after this, going back to feed and refreshing shows the video name correctly.
