### ISSUE TITLE
search options

### ISSUE THREAD

**Issue by Ere-the-Weekend-comes** [libre-tube/LibreTube#3883]
### Describe your suggested feature

I would really be able to use the app if it would let me search via youtube's 'last week' last month last day last year options.  I don't want their default search results at all.  It's just the same stuff it was a week, a month, a year ago.  !  Please add this feature in.   Thank you for listening to my little request.  I searched but didn't see this in other enhancements requests, and also didn't see it on the app though I clicked every last thing I could click everywhere.  I frankly find it hard to believe no one else would notice this glaring discrepancy from YouTube's available capabilities.  In fact I noticed that not one 2nd party client youtube frontend app has this, I downloaded several of them from UpToDown, though I got Libretube on FDroid.  Interesting to note that Google's proprietary repository of apps has seemed to all but eliminate competitor 3rd party YouTube frontends.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not possible without Piped API / NewPipe Extractor support, unfortunately.
