### ISSUE TITLE
Sort by date - for videos and comments

### ISSUE THREAD

**Issue by Rstment25** [libre-tube/LibreTube#3884]
### Describe your suggested feature

There should be an option like in regular YouTube to sort stuff by date ( I am not sure if newpipe has it already )

Helps tremendously in finding more recent videos or comments... App tends to show few years old content first

Also , can you add a live stream filter? Just like on regular youtube , set the tag to "live" and the app will show only live videos in your search . When you're trying to find live content it's outright impossible - you're offered videos first, even when I know exact keywords and I try searching I still can't get it to show livestream in the search results ! ( Only way to view them is by clicking directly on the channel name, click "content" and if they are streaming you'll find live streams there... Impossible to find any other way  ) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Without Piped API / NewPipe Extractor support, that's not possible unfortunately.
