### ISSUE TITLE
what is this?

### ISSUE THREAD

**Issue by Official-Mlx** [libre-tube/LibreTube#3886]
### Steps to reproduce

![Screenshot_2023-06-02-15-34-55-671_com github libretube](https://github.com/libre-tube/LibreTube/assets/74877307/b44ebd31-c5e5-41c4-b98f-d3724ee3e23b)

### Expected behavior

It should be like before

### Actual behavior

It should be like before

### LibreTube version

0.15

### Android version

10 ten

### Other details

meow!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#3861
