### ISSUE TITLE
#3868, in other views. 

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#3887]
### Steps to reproduce
As in #3868 the issue is in other views:
1. set the old desing for video lists (little thumbnails)
2. In "Trending" and "Feed" tabs, the uploaded time text is truncated and needs an additional line. At least in spanish
3. In a **search result**, is truncated too, but **in this case the text remains in english** (wich is truncated) and I can imagine if the translation is fixed, ther will be truncated in other languages too.
4.  (ADDITION) also is truncated in related videos below player.

### Expected behavior

1. Continue upload time in next line
2. In search results also translate upload time

### Actual behavior

1. Text is truncated
2. Upload time in search results remains in english when using spanish

### LibreTube version

0.15.0

### Android version

13

### Other details

I will open a new issue for the translation

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by luckkmaxx** [comment]
Here is it. Sorry
![Screenshot_20230602-191456_LibreTube](https://github.com/libre-tube/LibreTube/assets/14180594/a36098e2-ff21-4ae9-bd4a-c591a2ecfdc0)

**Comment by luckkmaxx** [comment]
Here is for trending. (Didnt take a screenshoot of feed bit its the same)
![Uploading Screenshot_20230601-222131_LibreTube.jpg…]()

**Comment by Bnyro** [comment]
We can't add an extra line here, otherwise it would overflow at the bottom (and wouldn't fit the thumbnail's size anymore.)
We're now at least cutting the word, so it now is `15 hou...` instead of `15     ` for "15 hours ago" if it gets cut off.

**Comment by luckkmaxx** [comment]
Another idea: Pictograms
3M views > 👁️ 3M
15 hours ago > 🕒 15h
so:
 👁️ 3M • 🕒 15h

Of course is better monochromatic pictograms.
