### ISSUE TITLE
Self-Updater from Github releases since F-Droid is slow to update 

### ISSUE THREAD

**Issue by Pentaphon** [libre-tube/LibreTube#389]
### Describe your suggested feature

We need a simple updater to check for and download the latest version from Github as soon as it goes up and update the app, similar to how Newpipe does it. 

F-Droid is really slow to update this app. Last time it took 7 days for the 0.3.0 version to get on F-Droid. That's a really long delay that could be worked around with a simple Github updater. 

### Other details

N/A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FireMasterK** [comment]
Alternatively, create a custom F-Droid repo like how NewPipe does.

**Comment by Bnyro** [comment]
An in-app-updater will be very hard, I think a custom F-Droid repo would be better because root installation works and it's easier to create than an in-app-updater.

**Comment by Pentaphon** [comment]
@Bnyro @FireMasterK I'll take either one. We just need something that keeps up with the Github releases.

**Comment by FireMasterK** [comment]
Also, we can sign F-Droid repo with the same keystore as github, so we can

**Comment by Bnyro** [comment]
Where can we host the F-Droid repo?

**Comment by rancidfrog** [comment]
Why you do not do like FairEmail and NewPipe,
Notification on new release which links you to github releases,
https://github.com/M66B/FairEmail/releases
It should be enough for user to be notified and linked to new update.
I believe app auto updates are restricted, as android is trying to be more secure, limiting what apps could do.

**Comment by Pentaphon** [comment]
> It should be enough for user to be notified and linked to new update.

They could use the Newpipe code that does it this but maybe its too much work compared to a repo. However, I'm not sure who is going to pay for the repo hosting...

**Comment by rancidfrog** [comment]
@Pentaphon 
Why the extra cost when gitub hosts for free? 🙆🤷

Alternatively you can use the fairemail code:
https://github.com/M66B/FairEmail/commit/055f16368755031280e4a626059eef2e70570ef9

It should not be too difficult.

**Comment by Bnyro** [comment]
@rancidfrog That looks like I could make it possible, I'm gonna try that later. Ty for mentionining it <3
