### ISSUE TITLE
Video not available

### ISSUE THREAD

**Issue by JohnBetaro** [libre-tube/LibreTube#3896]
### Steps to reproduce

it seems like no one is talking about it but may I ask why almost none if the instances is working ? I tried to change for different instances many times but only one or two are working.

![Screenshot_20230602-181830](https://github.com/libre-tube/LibreTube/assets/114379310/645f296f-47b1-4ce0-8da8-a64c2ceaa49a)
![Screenshot_20230602-181835](https://github.com/libre-tube/LibreTube/assets/114379310/3bc912db-3217-4d38-968d-868b5ebe4e87)

### Expected behavior

The videos will load and play

### Actual behavior

Video not available

### LibreTube version

15.0

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#3882
