### ISSUE TITLE
Wrong videos get removed from local playlists with custom sorting

### ISSUE THREAD

**Issue by PrivacyDevel** [libre-tube/LibreTube#3897]
### Steps to reproduce

1. create a new local playlist
2. add videos to that playlist
3. set sorting to "newest" for example
4. swipe away a video from that playlist
5. change view
6. go back to the playlist
7. the wrong video has been removed

### Expected behavior

The video that gets swiped away should be the one that actually gets removed from the playlist.

### Actual behavior

The wrong video gets removed from the local playlist.

### LibreTube version

0.15.0

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by luckkmaxx** [comment]
Here is working as expected. The items go away immediatelly after swipe to remove, so no matter if I change the view and go back to playlist, the item was correctly removed in the moment.

**Comment by luckkmaxx** [comment]
Try backing up and reinstall the app, to see if the issue is still there. Also try without restoring backup, with a fresh install

**Comment by akano12** [comment]
Can't reproduce either. 
And i honestly think it's better to start closing stale issues (issues where there's no response from authors on unreproducible bug reports)
