### ISSUE TITLE
Livestreams: wrong upload time

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#3898]
### Steps to reproduce

All livestreams (at least in search results) has a wrong upload time: **53 years ago**

### Expected behavior

Show "Live now", "Streaming since X hours ago" or nothing.

### Actual behavior

It shows "53 years ago"

### LibreTube version

0.15.0

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by luckkmaxx** [comment]
![Screenshot_20230603-000343_LibreTube Debug](https://github.com/libre-tube/LibreTube/assets/14180594/56c87650-9c77-49b0-8898-7f8ef17787ff)

**Comment by FireMasterK** [comment]
Open an issue in the Piped repository instead.

**Comment by FireMasterK** [comment]
I'm a bit unsure what's causing this - Libretube parsing the time incorrectly (maybe it's -1?) or Piped parsing times incorrectly.

**Comment by luckkmaxx** [comment]
> I'm a bit unsure what's causing this - Libretube parsing the time incorrectly (maybe it's -1?) or Piped parsing times incorrectly.

Piped frontend doesnt show time in livestreams until is finished.
![Screenshot_20230603-013049_Bromite](https://github.com/libre-tube/LibreTube/assets/14180594/7548b7db-8014-4166-a337-f6989b294ecf)

**Comment by FireMasterK** [comment]
Okay, could you see what happens on YouTube? If it shows up on YouTube, it's likely a NewPipeExtractor issue.

**Comment by FireMasterK** [comment]
This could be https://github.com/TeamNewPipe/NewPipeExtractor/issues/1067

**Comment by luckkmaxx** [comment]
This is official YouTube web for mobile.
They neither show the time until a livestream is finished.
The main difference is they count "users" not "views" for livestreams.
![Screenshot_20230603-084308_Bromite](https://github.com/libre-tube/LibreTube/assets/14180594/d1ba125c-dffe-45b3-b4f0-3775d1207389)

**Comment by Bnyro** [comment]
The issue is the -1 as timestamp. The time calculation started 1970, so 53 years have passed since -1 of Unix time.
So it's not a Piped issue.

**Comment by akano12** [comment]
There's also an issue with some recently uploaded videos, the number of views when playing a video is different from what's shown in the channel page or search results.
Also there are some channels showing different number of subscribers on channel page than that when playing a video

**Comment by Bnyro** [comment]
(That's not a LibreTube issue)
