### ISSUE TITLE
Livestreams: show filter in search results

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#3899]
### Describe your suggested feature

Just add livestreams button to be able to filter ir search results.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
No API support.
