### ISSUE TITLE
[BUG] Keyboard pops up

### ISSUE THREAD

**Issue by dhishkyaon** [libre-tube/LibreTube#39]
**Describe the bug**
Keyboard automatically pops up while playing video.

**To Reproduce**
1. _Search_ for a video & play it in fullscreen mode (landscape)
2. change app from recent apps
3. Get back to LibreTube
4. Keyboard pops up

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - Android version: 12

**Additional context**
Only for searched videos.

**Comment by Flam3z** [comment]
@dhishkyaon are you able to provide video of the bug happening?

**Comment by dhishkyaon** [comment]
https://user-images.githubusercontent.com/88529066/154664931-bd98d88a-f310-411a-8f5b-46dc05815890.mp4

**Comment by rimthekid** [comment]
I'm a bit clueless here

**Comment by rimthekid** [comment]
fixed in this [commit](https://github.com/libre-tube/LibreTube/commit/466cbb40198060f33e5809be64ac56bfe92b5ac5)

**Comment by dhishkyaon** [comment]
works fine. i will report if anything happens.

**Comment by rimthekid** [comment]
Should I close this issue too?

**Comment by dhishkyaon** [comment]
yes
