### ISSUE TITLE
does not show in task view/task manager on samsung tablet (sm-t290) android 9

### ISSUE THREAD

**Issue by thiccelf83** [libre-tube/LibreTube#390]
### Steps to reproduce

On my samsung tablet, an sm-t290 tablet currently running android 9. Open libre tube

Minimize it or switch to another app. Open task view/task manager, libretube does not appear in the list 

Samsung tablet (sm-t290) android 9 one ui core 1.1 

### Expected behavior

Libretube should appear in task view as normal.

### Actual behavior

Libretube does not appear in task view, as if it's not running at all. And can onl ybe reopened from notifications or the app launcher.

### LibreTube version

0.3.1

### Android version

Android 9

### Other details

I have only encountered this issue so far on an android tablet running android 9 w/ One UI 1.1

I have not encountered it on my phone, agoogle pixel xl2 running android 11 and quickstep launcher.

the only inconvenience this presents is making it a pain to re-open the app

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Is picture in picture active while the app is cloesed?

**Comment by thiccelf83** [comment]
Hi there. Thanks for replying, and thanks for the portrait commit. I appreciate it, and I really love your project, it is great and I frequently use  & prefer it over noobpipe and vanced


Second, No. The permission for it is disabled on account of being annoyed.

However, I did just upgrade the app, so I will toggle the permission on & off tosee if it was just a mismatch of the internal setting and whatever the android settings was showing

**Comment by Bnyro** [comment]
Hi, any update on the issue?

**Comment by Bnyro** [comment]
closing it, it can't really be a LibreTube issue since it's working fine for anybody else, probably device/os related

**Comment by thiccelf83** [comment]
No. I have it disabled under app permissions.
