### ISSUE TITLE
Content Not Available

### ISSUE THREAD

**Issue by MushroomGecko** [libre-tube/LibreTube#3900]
### Steps to reproduce

Load LibreTube and notice the titles and click on any video.

### Expected behavior

The titles will be their normal uploaded titles and the video plays as normal.

### Actual behavior

For almost every video the titles say "Video not available," and for every video when I click on a video, there will be a black screen with the message "This content isn't available."

### LibreTube version

0.15.0 (IzzySoft Neo Store repo)

### Android version

Android 13 (OneUI 5.1)

### Other details
No response

### Acknowledgements
- [x] I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

**Comment by luckkmaxx** [comment]
copy of #3882

**Comment by MushroomGecko** [comment]
Thank you!
