### ISSUE TITLE
Livestreams: Set "Live" stamp with red background

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#3901]
### Describe your suggested feature

Just set more visible livestreams, with a red stamp instead black as the rest of items.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not planned since we don't hardcode colors because it doesn't fit Material Design 3.
