### ISSUE TITLE
add automatic load balancing between instances

### ISSUE THREAD

**Issue by Darin755** [libre-tube/LibreTube#3903]
### Describe your suggested feature

I think it would be really cool and useful to have libretube automaticly choose the instance it pulls a video from. If a instance goes down libretube should automatically jump to another instance.

The primary benefit to this would be load balancing. Currently the servers with the most human readable names get favored because people see them as more trustworthly.

Another benefit to this would be resistance to censorship. If one instance gets blocked libretube can just jump to another.

### Other details

I am honestly not quite sure how the algorithm should work when selecting instances. I think it should have a random seed so that it isn't predictable and it should take into account speeds and latencies of the various instances.

Other than that I have no idea

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's already been discussed multiple times in other issue and is not planned (if you're interested, just browse the closed issues).
The only thing I could imagine is to not set kavin.rocks as the default instance when the user opens the app for the first time, but instead show a instance selection page at first startup or instead use a random one.
