### ISSUE TITLE
can not install libretube apk 

### ISSUE THREAD

**Issue by DrSami1** [libre-tube/LibreTube#3904]
### Steps to reproduce

downloading 
any apk 14.1
or 
v15
on huwaie p30pro sdk29 android 10
which is identified by libretube as arm64_v8a  

### Expected behavior

complete installation similar to v14

### Actual behavior

  after install apk  the process
end by message """app not installed """
the aplication in actual get installed 
but the message is not installed

tryed all supplied apks
v7a and others all same message
 currentally v14 is installed
but more recent versions could not be installed
 

### LibreTube version

14.1   and 15

### Android version

10

### Other details

on huwaie p30pro sdk29 android 10
which is identified by libretube as arm64_v8a

tryed all supplied apks
v7a and others all same message
 currentally v14 is installed
but more recent versions could not be installed
 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You installed the app from F-Droid before, F-Droid apks and normal apks can't get installed over each other.

**Comment by DrSami1** [comment]
no i never used f droid

**Comment by DrSami1** [comment]
i never used f droid
