### ISSUE TITLE
Instance overwrite

### ISSUE THREAD

**Issue by maboroshin** [libre-tube/LibreTube#3909]
### Steps to reproduce

1. add custom instances
2. name your preferred string, frontend URL : https://piped.kavin.rocks/, API URL : https://pipedapi.kavin.rocks/. I initially entered the API for https://pipedtestingapi.kavin.rocks and this problem occurred.
3. "kavin.rocks (Official)" will be overwritten by this new registration
4. Clear this with "Clear added".
5. There is no "kavin.rocks (Official)".

### Expected behavior

Add duplicate instances rather than overwrite them. You will see both "kavin.rocks (Official)" and the instance you added.

### Actual behavior

~~If there is neither the original instance (kavin.rocks (Official)) nor the added instance, The original instance is added automatically.~~  (Incorrectly filled in an alternative solution).

### LibreTube version

0.15.0

### Android version

Android 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That doesn't really make sense. Are you sure kavin.rocks didn't just have a downtime and thus hasn't been part of the instance's list?

**Comment by Bnyro** [comment]
Custom instances are saved independently from public ones.

**Comment by maboroshin** [comment]
Since then, The "kavin.rocks (Official)" that was present from the beginning does not exist after reset of the settings or reinstalling. Currently I am using kavin.rocks as custom instances.

I just pressed "clear added" again. The added kavin.rocks will disappear. The instance selection will be empty.

**Comment by maboroshin** [comment]
![Uploading 2F2E1DE3-A3F5-4B15-B505-10205A89302B.jpeg…]()

**Comment by maboroshin** [comment]
![2F2E1DE3-A3F5-4B15-B505-10205A89302B](https://github.com/libre-tube/LibreTube/assets/41102508/7cc112cd-3eb8-485c-a1fd-cae922f97243)

**Comment by maboroshin** [comment]
Now I see both "kavin.rocks (Official)" and the one I added. "kavin.rocks (Official)" is still displayed after pressing "clear added".

> Are you sure kavin.rocks didn't just have a downtime
I didn't quite understand what this meant. But, If it is back to normal, Pleaes close this issue.

**Comment by luckkmaxx** [comment]
kavin.rocks (Official) is not listed maybe because it isnt working well in latest hours.
But there is kavin.rocks **libre** (Official)

So I think this was an unfortunate coincidence.

**Comment by maboroshin** [comment]
Yeah, okay.
