### ISSUE TITLE
Hide button to manually skip SponsporBlock sections in player controls

### ISSUE THREAD

**Issue by MatsG23** [libre-tube/LibreTube#3914]
### Describe your suggested feature

If you enabled to manually skip sections of a video listed in SponsorBlock (like an advertisement in a video), you will see a button over the video saying "Skip section" as long as you are in a SponsorBlock section. The thing is that if you open the player controls to e.g. leave fullscreen mode, the button to skip a SponsorBlock section you are currently in does not hide.
The player controls are placed in a layer above the "Skip section" button (you will always hit e.g. the fullscreen button instead of the other button overlaying the video). 
I think it would make sense to hide the "Skip section" button if the player controls are open because the button is not functional in that moment anyways.

### Other details

A probably better option would be to change the UI of the "Skip section" button by, for example, making it a small but clear-to-understand icon button at the top right of the video. I think that, like this, the button to skip a section could stay in place, would fit in the player controls well and remain functional.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please share a screenshot or recording to make it easier to understand your current issue.

**Comment by Bnyro** [comment]
Oh, I see. I think the easiest way to fix it is to just dynamically update the bottom margin when going into full screen mode. Making the button less present is not convenient for users in my eyes.
