### ISSUE TITLE
Adding custom instance: Checkbox to set as current, and optional login

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#3918]
### Describe your suggested feature

When you add a new custom instance, usually is the one you want to use, but sometimes not.
Adding a check box "Set as current instance" could be nice.

Also could be nice adding there a User and Password fields, that can be optionally filled.

So you will have a ready to use app in only one step.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Only a minority of users even use a custom instance, I'm not of the opinion that it makes sense to really improve how setting it up works.
