### ISSUE TITLE
Is it possible to add a little switch in feed to show/hide watched?

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#3920]
### Describe your suggested feature

Personally, sometimes I want to hide watched, but sometimes need to be shown and watched again, show it to somebody...
Is annoying to go settings, find the option, enable/disable, go back to feed, and later again switch the option accordingly your need.

So, many other apps based on viewed or not viewed content has this feature.
Where? maybe near the search icon, A simple switch with an eye icon. Or only the eye, wich switches between an eye icon and a crossed out eye

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It's possible, but it's not planned.
1. There's no place in the feed left where it could be placed and it wouldn't fit there.
2. In general most users either enable or disable the option forever, but don't change it temporarily.

**Comment by luckkmaxx** [comment]
> 2. In general most users either enable or disable the option forever, but don't change it temporarily.

How do you know this? Did you made a poll about it?

**Comment by Bnyro** [comment]
As long as you don't create pull requests for them, smaller features are likely going to be rejected. My time is not unlimited, and if you open 5 issues per day I won't work on all of them, it's an open source, voluntary project. Refer to https://github.com/libre-tube/LibreTube/issues/2206#issuecomment-1336193310

**Comment by luckkmaxx** [comment]
Well you are right, I understand this project limitations, and most of issues I open are bugs. Feature requests does not have to be priority but they are needed to know user limitations and wishes.

Said this I will do FR on discussions page, but bugs will continue appearing. There you will have to set a fixing priority. I never will demand priority over other bug reports, I dont care how much time they are open.

**Comment by luckkmaxx** [comment]
BTW, I have noticed you are paying too much attention to me and my issues, I think over other older ones, what I have to thank you, but makes me feel... you know, there are other people before me.
