### ISSUE TITLE
Initial player response is not valid

### ISSUE THREAD

**Issue by IsriusQQ** [libre-tube/LibreTube#3921]
### Steps to reproduce

1. Open any video or short
2. Receive the error message: "Initial player response not valid", and the video will not play

![Screenshot_20230603-235807](https://github.com/libre-tube/LibreTube/assets/122330988/509678ff-ffe0-48a1-89ce-3dda3b3d0a75)

### Expected behavior

The video or short should play. 

### Actual behavior

The screen stays black, the video will not play. 

### LibreTube version

0.15.0

### Android version

13

### Other details

This error persisted even after restoring to default app settings. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by silentTeee** [comment]
I have also experienced this bug, tried reinstalling and deleting storage and cache, with no luck.

**Comment by akano12** [comment]
Change the instance you're using

**Comment by IsriusQQ** [comment]
> Change the instance you're using

That seems to have fixed the issue! Thanks for letting me know. It looks like the issue only happens when I use the kavin.rocks libre (Official) instance, regardless of the "disable piped proxy" option. 

Since the issue still persists on that instance, should I wait to mark this thread as closed?
