### ISSUE TITLE
Extremely buggy downloads.

### ISSUE THREAD

**Issue by BlazeJatin** [libre-tube/LibreTube#3922]
### Steps to reproduce

Downloads are buggy!
They stop downloading in the middle of the process and get stuck. Then you can't do anything about them. Tapping the resume button only crashes the app.

### Expected behavior

The downloads should countinue/resume.

### Actual behavior

The app crashes when resuming the download.

### LibreTube version

0.15.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#3426
