### ISSUE TITLE
Handle the Video Not Available in Feed

### ISSUE THREAD

**Issue by RuthlessRuler** [libre-tube/LibreTube#3923]
### Steps to reproduce

So, basically due to the recent issue, where Piped stopped working for me, some videos in my feed (subscription) show as video not available. Even if I watch them or mark them as watched, they re-appear back in the feed.

### Expected behavior

The video's nams gets corrected in the feed once it's actually loaded and hides after being marked as watched.

### Actual behavior

There are now two different entries, one in watch history with Correct name and one in subscription tab with video title as Video Not available.
Marking it again as watched hides it but when we switch to other tab and go back to subscription tab, it re-appears 

### LibreTube version

0.15.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's an unfortunate situation, however when the next release is published it'd already be too late for fixing that.
Due to some Piped changes, the chance of a reoccurrence of the issue is very unlikely, so there's no reason to take any further action here.

**Comment by RuthlessRuler** [comment]
Hmm. Weird, then how should I remove those videos from my Subs tab then?
