### ISSUE TITLE
Notify/Auto Switch Instances When An Instance Isn't Available

### ISSUE THREAD

**Issue by akano12** [libre-tube/LibreTube#3924]
### Describe your suggested feature

This has been suggested before but in different ways, I'm looking at this from a different angle so here's how it should work: (This is just to check if an instance is available or not, not to detect connectivity issues with the instance)

1- Allow a user to bookmark/add instances of choice to a list.
2- On LT launch, check if the currently selected instance is available in the fetched piped instances.
3- If not, set the current active instance to one of the available instances in the instance bookmarks list.

OR (easier approach which is better than nothing)

If this could cause some performance issues, another solution is to check if the currently active instance is available in the fetched piped instances, if yes -> do nothing, else -> show a toast notification saying instance unavailable

### Other details

The bookmarking scenario:

Pros:
1- It won't spam instances with requests 
2- Auto switch without user interaction
3- Handles things locally

Downsides:

1- Delay on LT launch
2- Needs to check if the new selected instance is available (aka repeat the process for newly selected instance)

Second scenario:

Pros: 
Notifies the user of instance issues right after LT launch, so it's better than nothing 
Easier to implement

Downsides: none 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
There are still no plans for something like that from my side.
I'd like to know what @FireMasterK has to say about it, but in general Piped instances are meant to not be cycled frequently, but instead you choose one instance and use that forever.

**Comment by akano12** [comment]
No need to complicate things, a simple toast warning is more than enough to be honest.

**Comment by Bnyro** [comment]
1. In my opinion, all solutions would just cause unneeded server traffic
2. The solution needs to be independent from the user's start tab. That means we would need to implement it for all different start tabs (apart from downloads) which would be some efforts.
3. There already are toasts when something goes wrong (except for the home page), so users know when their instance is down
4. Automatically switching the instance conflicts with Piped accounts, and generally only using one or two instances you trust is much better for personal privacy than using some you've never heard of before
5. Most instances have uptimes of 95% or more, so this would be kind of useless
6. If an instance is down, it's often not only an instance side issue but instead a general breakage from YouTube or an issue in Piped's backend, so we would iterate over different instances that are all down
