### ISSUE TITLE
Video Player errs on selecting video 

### ISSUE THREAD

**Issue by pranavsetpal** [libre-tube/LibreTube#3928]
### Steps to reproduce

Assume all app data is cleared / fresh install

1. Watch 1 video
2. Try to play another video

### Expected behavior

2nd video should play

### Actual behavior

I get an error toast notification: Initial player response is not valid.
Earlier (after the update), when I tried to play any video, the below appeared
![Screenshot_20230605-021341](https://github.com/libre-tube/LibreTube/assets/68775426/11922fd4-4fa4-437f-a6a0-c5fbc2252d56)

I am unfortunately unsure why or how to the response error changed.

### LibreTube version

0.15.0

### Android version

Android 13

### Other details

I have tried downgrading the application but that hasn't proven successful unfortunately. I'm unsure what exactly may be the cause. I would think it's the API that may have changed but it should've affected everyone then.
If you need any more information, I will try to provide it at the earliest.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/TeamPiped/Piped/issues/2487
