### ISSUE TITLE
Suggest to restart after restoring a backup

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#3930]
### Steps to reproduce

1. Restore a backup
2. There are things like the tabs that will not be updated after restoring until you restart the app.

### Expected behavior

Show the restart suggestion

### Actual behavior

After selecting the backup file to be restored, nothing in the app tells about the restoring successfully done (neither a toast message).

### LibreTube version

0.15.0

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Shouldn't this be labeled as enhancement instead of a bug 🤔

**Comment by luckkmaxx** [comment]
> Shouldn't this be labeled as enhancement instead of a bug 🤔

Well Im not sure. This could be a "bug" since you restore but dont get restored at all. 🤔

**Comment by luckkmaxx** [comment]
Now looks like a bug 😅

**Comment by akano12** [comment]
If LT used to suggest a restart on previous versions but not on this one, then ye it's a bug.

If this "suggestion" was never implemented/found on old versions, then it's a suggestion 😏

**Comment by luckkmaxx** [comment]
That could be a point of view. However the restart suggestions are implemented in other settings (see changing the tabs).
So is a feature is there, but not in all necessary actions.
