### ISSUE TITLE
Feed doesn't change

### ISSUE THREAD

**Issue by 0xrxL** [libre-tube/LibreTube#3936]
### Steps to reproduce

https://github.com/libre-tube/LibreTube/assets/127248639/b9a14045-bab7-4c0b-9a6e-5ce498a080df

### Expected behavior

A new feed at every refresh.

### Actual behavior

Feed doesn't change.

### LibreTube version

0.15 Debug

### Android version

Android 13 One Ui 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not the feed, that are the current trending videos on YouTube for the region you selected in the settings.

**Comment by 0xrxL** [comment]
> That's not the feed, that are the current trending videos on YouTube for the region you selected in the settings.

Sorry for the misunderstanding, but in any case this is what happens on Google YouTube client for trending videos.


https://github.com/libre-tube/LibreTube/assets/127248639/952d6e2b-aed2-48b4-a1b7-071c4b91f606

**Comment by Bnyro** [comment]
LT doesn't work like YT

**Comment by 0xrxL** [comment]
> LT doesn't work like YT

So this feature absolutely cannot be implemented in any way?

**Comment by Bnyro** [comment]
It will not be implemented
