### ISSUE TITLE
Make auto-play button style more explanatory

### ISSUE THREAD

**Issue by 0xrxL** [libre-tube/LibreTube#3937]
### Steps to reproduce

Open a video and change the auto-play button state from ON to OFF and vice versa

### Expected behavior

Make the button more similar to the one of Google YouTube client

![Screenshot_20230605_210745_Samsung Internet Beta](https://github.com/libre-tube/LibreTube/assets/127248639/2bfb7649-9c0d-4f0c-8dfd-070ba8fe9b95)
![Screenshot_20230605_210737_Samsung Internet Beta](https://github.com/libre-tube/LibreTube/assets/127248639/32b95ced-0a84-478f-aff7-d25f2a66d3ce)

### Actual behavior

There's practically no difference between OFF and ON state.

![Screenshot_20230605_210100_LibreTube Debug](https://github.com/libre-tube/LibreTube/assets/127248639/3c77c931-7d7d-4354-bc5a-2af866aa3a61)
![Screenshot_20230605_210053_LibreTube Debug](https://github.com/libre-tube/LibreTube/assets/127248639/324f225b-1b06-4be9-a805-c5bedf5058f5)

### LibreTube version

0.15 Debug

### Android version

Android 13 One Ui 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Also please make it override the autoplay option in settings (or make it changeable using this button)
