### ISSUE TITLE
Single line homepage feed

### ISSUE THREAD

**Issue by 0xrxL** [libre-tube/LibreTube#3938]
### Describe your suggested feature

Add an option to make the homepage feed style more similar to the one of Google Client

![Screenshot_20230605_205612](https://github.com/libre-tube/LibreTube/assets/127248639/3e16ec03-5dd0-438c-ad88-9bad9d968487)

Instead to keep only this

![Screenshot_20230605_205534_LibreTube Debug](https://github.com/libre-tube/LibreTube/assets/127248639/01210e62-106a-4924-8938-6da1ea35c1f2)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Appearance -> Navigation Bar -> order -> click the home icon next to "trends" -> okay

**Comment by Bnyro** [comment]
Because you enabled the alternative videos layout in the appearance settings

**Comment by 0xrxL** [comment]
> Because you enabled the alternative videos layout in the appearance settings

Thanks! Now it works.

**Comment by shellheim** [comment]
Is it not possible to have the featured videos in a card layout like trend?

**Comment by shellheim** [comment]
Is it not possible to have the featured videos in a card layout like trend?
