### ISSUE TITLE
Please add a tutuorial on Google sign in or atleast how to bring our all subsscriptions to this app

### ISSUE THREAD

**Issue by fisforfaheem** [libre-tube/LibreTube#3939]
### Describe your suggested feature

let users enjoy this app with personalized feed from sub

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
All the info you're asking for is available on the [project's website](https://libre-tube.github.io/)

**Comment by fisforfaheem** [comment]
it;s not easy and not at all simple for new people or mon tech people,
please think about. person who is not smart as we devs are


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
06/07/23,
02:05:18 AM

**Comment by FireMasterK** [comment]
Instructions from Piped:

> Importing Subscriptions from YouTube
> Open [takeout.google.com/takeout/custom/youtube](https://takeout.google.com/takeout/custom/youtube)
> In "Select data to include", click on "All YouTube data included" and select only "subscriptions".
> Create the export and download the zip file.
> Extract subscriptions.csv from the zip file.
> Select and import the file above.

They're applicable to Libretube too, you can import subscriptions from a file in the settings!

Hope this helps.

**Comment by fisforfaheem** [comment]
Glad to hear it!



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
06/07/23,
02:16:33 AM

**Comment by fisforfaheem** [comment]
how to export and thne imporT?
