### ISSUE TITLE
Upload time not localized in channel page > shorts

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#3948]
### Steps to reproduce

0. Change the language to other different than english 
1. Go to a channel with shirts published
2. Go to "Shorts" filter
3. You see upload time in english 

### Expected behavior

Show upload time in the selected language 

### Actual behavior

Upload time is in english 

### LibreTube version

0.15.0 

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
![Screenshot_20230608-090238_LibreTube Debug](https://github.com/libre-tube/LibreTube/assets/82752168/47cf891b-281a-46ec-9f36-f8f984b42cbc)

**Comment by luckkmaxx** [comment]
Hi! I dont see related merged commits. Does it work as expected for you?

**Comment by Bnyro** [comment]
It was fixed with the same commit that fixed it for search results
