### ISSUE TITLE
Buggy fullscreen 

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#3958]
### Steps to reproduce

1. Click on the 3 dots in the top right corner
2. open setings

https://github.com/libre-tube/LibreTube/assets/97352673/19286704-d8e4-47f8-a7af-234d76aa9a27

### Expected behavior

Fullscreen shouldn't activate

### Actual behavior

1. Fullscreen activates after you opened the menu, after you clicked on the 3 dots
2. Fullscreen deactivates after you opened the settings

### LibreTube version

latest debug

### Android version

One UI 5.1 Android 13

### Other details

I have seen similar behaviour like that in a few other apps (like Firefox) and it could also be caused by One UI managing the punch hole camera.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't reproduce here, maybe it's a device issue?

**Comment by akano12** [comment]
Have s20 with android 13 and one ui 5.1 and can't reproduce, issue on your side considering this behavior is visible in other apps
