### ISSUE TITLE
Add Clear Text Input button to search field

### ISSUE THREAD

**Issue by martin-desktops** [libre-tube/LibreTube#396]
### Describe your suggested feature

With no key shortcuts we know from desktop it takes much longer on mobile devices to remove a whole text from a search field. It requires holding, clicking Select all, and finally you can remove it,  while the Clear Text Input button, or easier - the "X" makes it instantly
![f29f0615cd76be3f7548e0c671a356e7034a4f11](https://user-images.githubusercontent.com/64419373/172190315-8d18dc96-c7fc-4d06-af96-ae159a2586a3.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SameenAhnaf** [comment]
You can still long press on `Backspace` button on your keyboard. Isn't that more convenient for one handed use over a button on top bar? 🤔

**Comment by Bnyro** [comment]
doesn't matter anymore, I already coded it xD

**Comment by Bnyro** [comment]
btw ty for all your suggestions @martin-desktops, really love them :)

**Comment by martin-desktops** [comment]
My pleasure!
