### ISSUE TITLE
Chromecast support

### ISSUE THREAD

**Issue by Jerico324** [libre-tube/LibreTube#3963]
### Describe your suggested feature

A Chromecast support would be great for watching on the tv.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Duplicate of https://github.com/libre-tube/LibreTube/discussions/3493
