### ISSUE TITLE
Warning if the volume is too high

### ISSUE THREAD

**Issue by Fish25op** [libre-tube/LibreTube#3966]
### Describe your suggested feature

Warning if the volume is too high when using headphones (or bluetooth audio devices).This warning should be displayed when the volume is too high when playing video or music, as sudden loud noise can cause serious damage to the ears.We sometimes forget to turn down the volume

### Other details

Some devices have this function.Samsung has this feature. Not sure about other brands.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Fish25op** [comment]
How Loud and How Long Should You Wear Your Headphones? Experts recommend keeping sound levels at somewhere between 60 and 85 decibels to minimize the damage your ears are exposed to.

**Comment by Fish25op** [comment]
> Is it possible to measure if audio is within this range of decibels? Most volume warnings are shown based on volume percentage. If the latter one is the only feasible option, colouring too high volume as red on volume bar could be done.

Knowing the intensity of a sound wave allows one to calculate the deciBel (dB) level of that sound. Use the DeciBel Calculator widget to determine the deciBel rating from any intensity in Watt/meter2. Enter intensities using scientific notation - for example, enter 5e-5 for 5.0x10-5.

As mentioned in the previous paragraph, even the frequency will affect our perception of the loudness of a sound. For instance, a 100 Hz sound at 60 dB will not sound as loud as a 1000 Hz sound at 60 deciBel. Fletcher–Munson curves or equal loudness curves are often used to demonstrate the perceived loudness of a sound for a given frequency. Use the widget to investigate the effect of the frequency upon the perceived loudness and to view the equal loudness curves.

**Comment by Bnyro** [comment]
I guess this is pretty much out of scope for the project? We're not responsible for how you consume the content, and since most people know what they're doing when plugging headphones in this would mostly just be a very annoying feature. Also, each headphones have a different maximum loudness, so 65% could be too quiet on some of them while it could be too loud on others...
