### ISSUE TITLE
Weird error message i get every tlme this error message its in the picture

### ISSUE THREAD

**Issue by HageFale** [libre-tube/LibreTube#3967]
### Steps to reproduce

click on video error message appears

### Expected behavior

should play video if i click om

### Actual behavior

video does not plax

### LibreTube version

0.15.0

### Android version

Android 12 MIUI Mi 11

### Other details

here a picture
![Screenshot_2023-06-09-19-11-27-777_com github libretube](https://github.com/libre-tube/LibreTube/assets/10869371/a0759a43-11bf-49b8-a7a7-123388e8ba20)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/3928#issuecomment-1575707664

**Comment by Bnyro** [comment]
Change the instance in the settings and tell your instance's hoster they should follow the steps at the Piped issue linked in the comment above.

**Comment by Bnyro** [comment]
Or if it's the official instance, skip step two.
