### ISSUE TITLE
Can't add new channel groups

### ISSUE THREAD

**Issue by Reinachan** [libre-tube/LibreTube#3969]
### Steps to reproduce

1. Have no channel groups
2. Tap the edit pen icon in the subscriptions tab
3. Tap "new"
4. Write a name and select some channels

There are now no buttons to create this channel group and exiting out of the bottom sheet and tapping "ok" doesn't create it either.

### Expected behavior

When done filling in details there should either be a button to commit or exiting out should create the channel group.

### Actual behavior

You're unable to create a channel group, at the very least if you don't already have any. I'm not sure if you can if you have some already.

### LibreTube version

0.15.0 (F-Droid)

### Android version

Android 13 (AOSP, LineageOS)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
see https://github.com/libre-tube/LibreTube/issues/3864#issuecomment-1570728890 for a temporary workaround
