### ISSUE TITLE
Status bar visibility toggling when entering video

### ISSUE THREAD

**Issue by Fish25op** [libre-tube/LibreTube#3970]
### Steps to reproduce

1.Play video.
2.The status bar is not visible, when entering video.

### Actual behavior

The status bar is not visible

### Expected behavior

It should be visible

### LibreTube version

0.15.0 Debug

### Android version

Android 12

### Other details

https://github.com/libre-tube/LibreTube/assets/136016095/e5dc11cc-ebcf-4234-aaef-d4f7797fdf7a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please choose a proper title and description of the issue next time ...
