### ISSUE TITLE
Thumbnails below the playing video are in low resolution and blurred

### ISSUE THREAD

**Issue by halfbytecode** [libre-tube/LibreTube#3972]
### Steps to reproduce

1. Play a video
2. Check out the thumbnails below the playing video

### Expected behavior

Thumbnails below the playing video should be clear.

### Actual behavior

Thumbnails below the playing video are blurred and in low resolution.

### LibreTube version

0.15.0

### Android version

Android 13

### Other details

![Screenshot](https://github.com/libre-tube/LibreTube/assets/17142444/164ec67f-d7de-4a2b-af28-c0fb6cd21f8b)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
NewPipe Extractor issue.

**Comment by Bnyro** [comment]
Can be addressed after https://github.com/TeamNewPipe/NewPipeExtractor/pull/889 is merged.

**Comment by halfbytecode** [comment]
Strangely, while using the NewPipe app, the issue does not occur, as far as I can remember. Could it be addressed by looking into how NewPipe handles it and handling it similarly in LibreTube?

**Comment by Bnyro** [comment]
NewPipe has the same issue.

**Comment by halfbytecode** [comment]
For now, I switched to the Alternate videos layout, and restarted LibreTube. The thumbnails are small now, and the issue is not too noticeable now. I think NewPipe has this layout by default.

**Comment by Bnyro** [comment]
Yes, that's right.
