### ISSUE TITLE
Playlist video starts in the middle

### ISSUE THREAD

**Issue by doonoo** [libre-tube/LibreTube#3985]
### Steps to reproduce

#3079 so as this issue states, the first video in a playlist will start normal, then after that, the second one and ongoing will start in the middle. Makes it hard to listen to music.

### Expected behavior

Should start in the beginning.

### Actual behavior

Starts in the middle.

### LibreTube version

0.15

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by terminal-cs** [comment]
I still seem to have an issue with this @Bnyro 
It's seemingly only some specific videos, but even after watching them all the way, some seem to just start somewhere near the end.

**Comment by E0697** [comment]
Same here. I still have it in 0.16.1.
I think I've only encountered it in shorts so far.
