### ISSUE TITLE
 Piped Material

### ISSUE THREAD

**Issue by Legoks** [libre-tube/LibreTube#399]
### Describe your suggested feature

This is a forked project from Piped and offers better performance.

### Other details

https://piped-material.xn--17b.net/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Legoks** [comment]
I know it's better than the Piped project.

**Comment by Bnyro** [comment]
Umm, and I know that I don't know what this issue should be about.
