### ISSUE TITLE
ethical suggested video and tournesol.app

### ISSUE THREAD

**Issue by moolight-seashell** [libre-tube/LibreTube#3993]
### Describe your suggested feature

because we d'ont really have ia to suggest video

it will be a wonderful idea if we can have a native integration of tournesol app in this

tournesol is a open source safe and ethical system based on a voting system

https://tournesol.app/
https://github.com/tournesol-app/tournesol
https://addons.mozilla.org/fr/firefox/addon/tournesol-extension/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
There are no plans to add support for that directly without a middleman at LibreTube's side, if there's interest it should be suggested to become implemented at the Piped backend side.
