### ISSUE TITLE
Don't play the next video while reading the comments

### ISSUE THREAD

**Issue by Fish25op** [libre-tube/LibreTube#3998]
### Describe your suggested feature

Playing the next video while reading interesting comments becomes annoying.

### Other details

It would be good if there was such an option in the settings. I don't want to stop the video. Let the video repeat while reading the comments

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
I was going to suggest to bring back an old feature, which is full screen comment sheet.

When comments are opened, they're displayed as is but users would have the option to pull up the comment sheet to display more comments on screen and the video would be paused, not sure if this can be done but it's really useful.


![20230612_214653.jpg](https://github.com/libre-tube/LibreTube/assets/50032603/a2cad399-6eec-4600-a4e0-b87a440ae32f)

**Comment by Fish25op** [comment]
Do you disagree with my opinion?

**Comment by Gabs-Unk** [comment]
A option is good
but why don't you try those options:![Screenshot_20230612-194019080 (1).jpg](https://github.com/libre-tube/LibreTube/assets/87625033/ff456217-b9be-49f0-9b7c-9dfc67d25c11)

![Screenshot_20230612-194113279 (1).jpg](https://github.com/libre-tube/LibreTube/assets/87625033/37127fd9-7b47-4eb9-939f-f527c31f1430)

**Comment by Fish25op** [comment]
Because I only need this feature when reading comments
