### ISSUE TITLE
[FEATURE] A setting to select a resolution for all videos

### ISSUE THREAD

**Issue by CasuallyOrange** [libre-tube/LibreTube#40]

**Comment by rimthekid** [comment]
This is already on the projects list will be implemented eventually.

**Comment by CasuallyOrange** [comment]
> This is already on the projects list will be implemented eventually.

Oh nice!

**Comment by CasuallyOrange** [comment]
> This is already on the projects list will be implemented eventually.

Any ETA? This feature is really important to me since I have limited data, I really like the app and want to use it but I can't really use it properly till then..

**Comment by rimthekid** [comment]
Oh I was waiting till we go on player issues but if that's really important I will do it first np!

**Comment by CasuallyOrange** [comment]
> Oh I was waiting till we go on player issues but if that's really important I will do it first np!

Thank you! :D

**Comment by CasuallyOrange** [comment]
> Oh I was waiting till we go on player issues but if that's really important I will do it first np!

Will this be there in the next update?  Just asking

**Comment by rimthekid** [comment]
Yes!

**Comment by CasuallyOrange** [comment]
> Yes!

Nice! Ty
