### ISSUE TITLE
Remove the gray outline from playlist thumbnails

### ISSUE THREAD

**Issue by martin-desktops** [libre-tube/LibreTube#400]
### Describe your suggested feature

Though we have several ways of displaying items inside the app, none of them adds the gray outline to the thumbnails, except inside the Library tab. I would suggest not using this effect with the aim of improving design coherence

![grayoutline](https://user-images.githubusercontent.com/64419373/172208220-8fe5b2d8-830b-4db0-98d2-c1f86e7e78b4.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I removed all the grey borders except the one for playlists because it looks ugly when playlists are empty

**Comment by Bnyro** [comment]
But I'll try to find a solution

**Comment by martin-desktops** [comment]
I see what's the problem. We could display an image for empty playlists, but maybe a better one than this from desktop Piped.
![image](https://user-images.githubusercontent.com/64419373/172213911-f2110484-1a8c-476a-876d-aa33ed359d64.png)

**Comment by Bnyro** [comment]
That's a good idea, we could maybe use the same overlay as for playlists in the search too. But idk which image to use as place holder

**Comment by Bnyro** [comment]
I tried to find an image we could use as place holder but I couldn't find anything :(

**Comment by martin-desktops** [comment]
Seeing how the issue is solved by Spotify, I decided to mix their solution with the current official YouTube playlist tab. I think the second variant fits with these empty state icons a bit better. Any thoughts about the redesign, icon selection?

Spotify:
![Screenshot from 2022-06-07 13-18-45](https://user-images.githubusercontent.com/64419373/172367263-7d766889-5198-4dc7-853d-1167bd1e396d.png)

YouTube:
![IMG_1236](https://user-images.githubusercontent.com/64419373/172373716-67677324-b3a0-43c5-917f-c0dae638b493.png)

Playlist redesign:

![image](https://user-images.githubusercontent.com/64419373/172374358-a9e3c34d-76cd-43c4-b13a-4719c3871ab0.png)

**Comment by Bnyro** [comment]
both look great, thank you for your efforts <3
I think the second variant doesn't really fit the size of normal youtube thumbnails so I think variant 1 would be better.
And I feel like the icon with the three squares/ shaped square fits better than the other one.
Could you send me the image file maybe?

**Comment by martin-desktops** [comment]
Yea, I see where are you coming from. Though empty state icons don't lay that well in rectangular shape, since they are in a square frame, the equal playlist miniatures from the official YouTube app aren't as practical as the rectangular, and I think that aspect is the most important. I think can abandon the idea of changing the shape for now.

Replacing the trash icon with the 3 dots, or more precisely "More Vert" icon will also benefit, if we will assign to it the current 
Hold dialog. It would allow us to provide a more intuitive path to actions like Play on background / Add to Playlist / Share (and in this case we would have to add "Remove from playlist" action to that menu, since the trash icon would disappear).

Note that in the second variant, I added some basic information about playlists, allowing us to fill that huge empty field with some useful data. Nothing to prevent this from being introduced into variant 1.

As you can see, I also replaced the gray from fonts with color text relating to the current theme, but I am gonna open a new issue for that, since it occurs in many other elements of the app.

I'll send you on Matrix a link to the Figma file with editing permissions, while here I'll send a link for spectators.
Keep in mind it's full masking and "make shifting"

Public link:
https://www.figma.com/file/GKjh3ivXgigdVB8OnRxlyv/Playlist-redesign

**Comment by martin-desktops** [comment]
PS. The icons I've used for this design come from http://fonts.google.com/icons
Seems some icons in our UI  are a bit outdated, like the [Download](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Adownload%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048) icon. 
Maybe it's time for small improvement in this field?
