### ISSUE TITLE
I can't change video quality on this video

### ISSUE THREAD

**Issue by olfek** [libre-tube/LibreTube#4006]
### Steps to reproduce

https://www.youtube.com/watch?v=c7K2TA0bBpY

### Expected behavior

Video quality changes as requested

### Actual behavior

Video quality does not change

### LibreTube version

0.15.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Works 100% fine here, doesn't seem like a client side issue.
