### ISSUE TITLE
App shows Wrong Images of some Channels and changes them on different fragments.

### ISSUE THREAD

**Issue by IndusAryan** [libre-tube/LibreTube#4008]
### Steps to reproduce

Search " Ubisoft "
channel has 36 lakh subs.

### Expected behavior

Should show real profile image that is Purple in colour.

### Actual behavior

when searched the channel shows real image but videos show a different channel image and when you watch video of it the recommended videos below exoplayer again show current Image.

![photo_2023-06-14_20-08-19](https://github.com/libre-tube/LibreTube/assets/125901294/213be007-57da-4c29-b3bb-482a73fd2e8a)

![photo_2023-06-14_20-08-15](https://github.com/libre-tube/LibreTube/assets/125901294/a47a45b1-1ea3-49a7-ae76-92346b420037)

### LibreTube version

Latest Alpha

### Android version

A13

### Other details

few days ago on a channel it was also showing wrong image of channel called Zee Music Company but now it shows their real image.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Likely an issue in the NewPipe Extractor. Looks the same way in the browser via Piped.
