### ISSUE TITLE
Answers to Comments

### ISSUE THREAD

**Issue by Legoks** [libre-tube/LibreTube#401]
### Describe your suggested feature

This feature is available in the Piped project, should be here. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by martin-desktops** [comment]
Duplicate of https://github.com/libre-tube/LibreTube/issues/303

**Comment by Legoks** [comment]
It will be solved ?

**Comment by martin-desktops** [comment]
We'll see. You can close the issue since we have the previous one
