### ISSUE TITLE
Show playlist description in Library view

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#4010]
### Describe your suggested feature

Now the playlists view only shows their title. It could be fine to show the playlist description below each playlist title.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't really think we have any space for that left? And even if we did, we could only display the first line of the description. And I think that would only work for local playlists because the normal search result playlist items don't provide that info (iirc).

**Comment by luckkmaxx** [comment]
Yes I mean own playlists. Bookmarks has the corresponding channel name as subtitle, and it could be fine have some extra info in my playlists library.

**Comment by Bnyro** [comment]
Not planned currently, Piped doesn't do it either in the web.
