### ISSUE TITLE
Font size player buttons not aligned on default theme

### ISSUE THREAD

**Issue by 0xrxL** [libre-tube/LibreTube#4011]
### Steps to reproduce

![Screenshot_20230616_025120_LibreTube Debug](https://github.com/libre-tube/LibreTube/assets/127248639/343ed063-728f-4e50-9f83-9ce362ea54c9)

### Expected behavior

Same font size for every button name

### Actual behavior

Not all button names are equally sized

### LibreTube version

0.15.1 Debug

### Android version

Android 13 One Ui 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's in order to make all the text visible properly.
