### ISSUE TITLE
Zoom animation for fullscreen gesture

### ISSUE THREAD

**Issue by 0xrxL** [libre-tube/LibreTube#4012]
### Describe your suggested feature

Add a stock like animation during "down to up" gesture to enter in fullscreen mode

https://github.com/libre-tube/LibreTube/assets/127248639/839925ce-a908-48a4-85dc-6444f330421e

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not possible with the ExoPlayer unfortunately.
