### ISSUE TITLE
Override global autoplay preference directly from player

### ISSUE THREAD

**Issue by 0xrxL** [libre-tube/LibreTube#4013]
### Describe your suggested feature

Currently autoplay can be disabled for every video only from settings. Instead it would be better if this feature could be turned off for all videos like on the stock client: directly from the video player.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by 0xrxL** [comment]
> u mean the autoplay button in the player should also override the autoplay preference in setting

Exactly.

**Comment by akano12** [comment]
I totally agree and I've asked for this before in a different issue https://github.com/libre-tube/LibreTube/issues/3937#issuecomment-1577351582

**Comment by akano12** [comment]
> If implemented, the toggle in settings should be removed. Repetitive options with exact same functionality carry no extra value.


Nope, either remove the autoplay toggle from the player or make it override the one in the settings because when users open LibreTube for the first time, they go to the settings to customize the app and not seeing this option under the player settings would be confusing.

**Comment by Bnyro** [comment]
I don't think this makes sense then. Preferences in the settings are meant to be permanent, anything else would confuse users. Hence the option in the player is only temporary, as it would otherwise defeat the point of a setting.
So: either remember the one in the video and remove the preference
Or: keep everything as is

**Comment by 0xrxL** [comment]
> I don't think this makes sense then. Preferences in the settings are meant to be permanent, anything else would confuse users. Hence the option in the player is only temporary, as it would otherwise defeat the point of a setting. So: either remember the one in the video and remove the preference Or: keep everything as is

Just keep the override from the player, which is seems to be more comfortable (and fast to reach) for users

**Comment by Bnyro** [comment]
Okay, so far so good.
The only concern I have is how we should handle it in the audio player then? Since if there's no preference anymore then, we should probably add an autoplay control to the audio player UI too? Any suggestions?

**Comment by 0xrxL** [comment]
> Okay, so far so good. The only concern I have is how we should handle it in the audio player then? Since if there's no preference anymore then, we should probably add an autoplay control to the audio player UI too? Any suggestions?

Create a "cloned" toggle with the same preference of video player, in this way you can enable or disable the autoplay as if you were dealing with the same player.
