### ISSUE TITLE
Swipe to close miniplayer

### ISSUE THREAD

**Issue by 0xrxL** [libre-tube/LibreTube#4014]
### Describe your suggested feature

Currently miniplayer can't be closed with an "up to down" gesture such on stock client. This implementation would improve overall usability.

https://github.com/libre-tube/LibreTube/assets/127248639/0effd976-ba68-4376-9ba1-52d28536dbb5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Duplicate of #2020
