### ISSUE TITLE
Show number of comments on button to open comments section

### ISSUE THREAD

**Issue by 0xrxL** [libre-tube/LibreTube#4015]
### Describe your suggested feature

It would be a good idea (imho) to add a comment counter on the button to open the comment section, under the video player.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
There's no API support for that.
