### ISSUE TITLE
Timebar at the bottom edge of player and miniplayer

### ISSUE THREAD

**Issue by 0xrxL** [libre-tube/LibreTube#4016]
### Describe your suggested feature

It would be useful to quantify the duration of the video, if a timebar were added to the bottom edge of miniplayer and normal player when the controls are hidden, as already happens on the stock YouTube client.

![Screenshot_20230616_033503](https://github.com/libre-tube/LibreTube/assets/127248639/8c0111bc-8b82-44d0-a4cb-a71c97a1c81d)
![Screenshot_20230616_033608](https://github.com/libre-tube/LibreTube/assets/127248639/25c219dd-2014-4b4a-bb2c-46e110512532)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
This has already been rejected in previous issues, and it's still not planned.
