### ISSUE TITLE
Subscribe button doesn't match UI (Low priority)

### ISSUE THREAD

**Issue by unityastronaut** [libre-tube/LibreTube#4017]
### Describe your suggested feature

I've noticed that the "subscribe" button doesn't match the rest of the UI. The corner radius is much lower and the font is thicker and lighter. I think it would would look more coherent, if the button was pill-shaped,  like the "comments" button below. Also the font should be the same as the rest. To create a visual difference between "subscribe" and "unsubscribe" it would make sense to use the primary system color for the former and the secondary color for the latter. I've created mockups in Figma to highlight the suggested changes.

![Mockup 1](https://github.com/libre-tube/LibreTube/assets/82398591/c98cf419-6e93-4619-a5ed-33fcb5cec42e)
![Mockup 2](https://github.com/libre-tube/LibreTube/assets/82398591/d0e1ed25-cd41-4d96-8ad2-7728e7ebd113)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
In order to give the button a different color, we would probably need to create two separate buttons (one for subscribed, and one for unsubscribed) and always hide one of them, because we can't change the style programmatically. Not a fan of the idea.

**Comment by unityastronaut** [comment]
> In order to give the button a different color, we would probably need to create two separate buttons (one for subscribed, and one for unsubscribed) and always hide one of them, because we can't change the style programmatically. Not a fan of the idea.

I have very little experience in coding. I experimented with C# a couple of years ago but aboned it because of time reasons. However I looked into this and I think this can be done in Kotlin using "onClickListener". I found some stackoverflow posts about changing button colour on click and it seems pretty straight forward. I don't think a second button would be needed. But then again you're much more knowledgeable than me in this matter.

**Comment by Bnyro** [comment]
No, that's not possible because we use Material Design 3 button styles.
We could indeed change the color of the button at runtime, but that would break all its styling.

**Comment by Bnyro** [comment]
Believe me, if there was an easy way, I would be aware of it :)

**Comment by unityastronaut** [comment]
I see. Thanks for explaining. So there's no way to do this programmatically. What about using an interactable component like the toggle switches in the settings menu? So if I were to create an interactable component with two states (subbed/unsubed) in something like figma, that changes state when pressed, what are your thoughts on that approach?

**Comment by Bnyro** [comment]
Unfortunately I don't think that would look well here

**Comment by unityastronaut** [comment]
Sorry I should have been more precise. I don't mean using a toggle switch. I mean using a button like in the mockups, but making that button an interactable component with two states, like whats used for switches. This could be done in design software like figma.

**Comment by unityastronaut** [comment]
Actually, there is a relatively new plug-in for Figma called "Relay" wich generates jetpack compose components from figma components. However I haven't tried it and don't know if it works with interactable components. I'll link a video about it in case you find this interesting.
https://piped.video/watch?v=byOmrmXG4yQ

**Comment by Bnyro** [comment]
Looks interesting! However, we don't use Compose unfortunately and should stick to Material Design 3 mostly. Closing this as not planned for now, what has been fixed till date are the corner radius and the text color of the button to match the others.

**Comment by unityastronaut** [comment]
Sounds good. I just assumed you use Compose because you do for your other apps. Nice changes though!

**Comment by d4f5409d** [comment]
This sounds like a really good idea
