### ISSUE TITLE
A few GUI related suggestions 

### ISSUE THREAD

**Issue by SameenAhnaf** [libre-tube/LibreTube#4019]
### Describe your suggested feature

- [ ] Improve playlist thumbnail design.

| Before | After |
| --- | --- |
|![Screenshot_20230616-211428](https://github.com/libre-tube/LibreTube/assets/79245641/fdf7d09e-98d0-4287-bdd3-dc9f70856829)|![Screenshot_20230616-211345](https://github.com/libre-tube/LibreTube/assets/79245641/66f09f7e-47df-48b3-b203-2d188b784e6f)|

- [ ] Channel button is already hidden while accessing videos within that channel feed. The same should be the case for Shorts and Live tab
- [x] Follow order of tabs similar to YouTube website. They should be aligned as Home, Videos, Shorts, Live, Playlists, Channels and Community respectively.

Not possible currently:
* include a search bar in the middle of About and Tabs` list within the channel feed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I disagree with reordering the tabs in the channel page, in my opinion the current order (sorted by priority imo), is more convenient. We don't aim to copy YouTube , we're just doing our own thing that's the most user friendly.

And could you please elaborate on 4. (the search bar thing)? I currently don't really understand it unfortunately.

**Comment by Bnyro** [comment]
That's not API supported.

**Comment by Bnyro** [comment]
Is the playlist card design from some other app or from Figma?

**Comment by Bnyro** [comment]
@IndusAryan As already said, please do not tag me.
You can create a PR yourself by applying your changes from Android Studio in the browser with GitHub's text editor, read about creating pull requests [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).
