### ISSUE TITLE
Firebase Analytics

### ISSUE THREAD

**Issue by Legoks** [libre-tube/LibreTube#402]
### Describe your suggested feature

This will help you gather information about application performance and crash log.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FireMasterK** [comment]
No, it's basically adding trackers to your app with proprietary APIs :/
