### ISSUE TITLE
Chapters in audio mode too

### ISSUE THREAD

**Issue by NeeRaj-2401** [libre-tube/LibreTube#4024]
### Describe your suggested feature

Useful when listening to podcasts or something that have chapters. 

### Other details

UI suggestion: we can close the audio mode via mini player close option, 
so may be replacing the cross icon with chapters(if exists) in audio mode options bar will help. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TidalMist** [comment]
Chapters not working if enable audio in options which horizontal scrollable, but work if enable audio only mode in settings general
