### ISSUE TITLE
Stop redirecting to YouTube

### ISSUE THREAD

**Issue by Gamefire238** [libre-tube/LibreTube#4028]
### Describe your suggested feature

It would be better for the application to directly open a video on libretube when pressing the video link in another video description, because every time I click on a video link it goes straight to YouTube :(

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's already how it works.
