### ISSUE TITLE
Option to unsubscribe from a channel through options long pressing in Legacy subscription view

### ISSUE THREAD

**Issue by StrangeSam99** [libre-tube/LibreTube#4031]
### Describe your suggested feature

The reason of this request depends on the fact that this could be the only way to unsubscribe from a channel that have been closed. At the moment there are no ways to do that and closed/removed/banned channels are simultaneously not reachable and not removable from the subscription list. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You can simply do that by not using the legacy subscription view. The legacy one only got re-added since some users fell in love with it when it was the default/only layout, but it's not meant to be able to subscribe or unsubscribe by design.
