### ISSUE TITLE
Downloads

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#404]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Legoks** [comment]
You can enter the discounts in the Library section.Even if there is no internet, let's go to the downloads and watch the videos.
![Screenshot_20220607-091800_NewPipe SponsorBlock](https://user-images.githubusercontent.com/104249296/172302733-beb3ad0d-3038-4fa3-a188-006693d3717a.jpg)
![Screenshot_20220607-092015](https://user-images.githubusercontent.com/104249296/172302736-0f17a211-41f3-419f-ab1b-df364cae24b2.jpg)

**Comment by Legoks** [comment]
Also, the download speed is slow and the notification does not indicate how much is loaded or when.

**Comment by Nizami20052022** [comment]
Take a look here.

**Comment by Bnyro** [comment]
At the current state there won't be a section with your downloaded videos, I'll add that you can choose the download directory.

**Comment by Bnyro** [comment]
When will what happen?

**Comment by Nizami20052022** [comment]
The section where we downloaded the videos

**Comment by Bnyro** [comment]
maybe never, idk
I won't add it, you would have to wait for somebody else to do it

**Comment by ahmadraniri1994** [comment]
Can confirm that the download speed is slow. I'm using libretube cause newpipe sometimes fails to open link.

**Comment by Bnyro** [comment]
I can confirm it too but that's probably because of the servers
