### ISSUE TITLE
where are the Bookmarks?

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#4049]
### Steps to reproduce

...

### Expected behavior

...

### Actual behavior

...

### LibreTube version

latest Debug

### Android version

Android 13

### Other details

![Screenshot_20230619_153346_LibreTube Debug](https://github.com/libre-tube/LibreTube/assets/97352673/27832f00-df6d-436d-a8f3-bddd1bdd4c26)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Still work as expected for me.

**Comment by akano12** [comment]
Works properly on my side too, tested on latest debug

**Comment by ChuckBartowski91** [comment]
I have the same problem too, both on xiaomi smartphone and android TV. I tried to add a bookmark of a playlist from piped website (i logged in to my account on all instances obviously) but it doesn't show anywhere in the app, only on the piped site.

**Comment by ChuckBartowski91** [comment]
> I think I just mixed up my instance with with my auth instance.

For me syncs anything in a matter of 1 second for the playlists but bookmarks are nowhere to be found in app.
