### ISSUE TITLE
SponsorBlock / Seek bar colors

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#405]
### Describe your suggested feature

Color selection according to the sponsor category.
![Screenshot_20220606-224840_NewPipe SponsorBlock](https://user-images.githubusercontent.com/104249296/172226743-e4fd9c23-f1cb-4cb2-9de5-7abc5b5ca050.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Legoks** [comment]
SponsorBlock categories are few.

**Comment by Bnyro** [comment]
Currently not planned

**Comment by Nizami20052022** [comment]
This is already available in the Piped project.
