### ISSUE TITLE
Show MUSIC IN VIDEO in description

### ISSUE THREAD

**Issue by heartlog** [libre-tube/LibreTube#4057]
### Describe your suggested feature

YouTube have feature that shows music in video below description box. Maybe if it is added in Libretube then it'll be great.

I know piped don't have this feature yet. But, you can add this when user disable piped proxy.(LT extract img and source from YT site directly) So, it'll be great.

Thanks.

### Other details

![Musiv in video](https://github.com/libre-tube/LibreTube/assets/76758776/f12d4121-66e3-4114-a90f-ec5fc0a3e2ad)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not true, see https://github.com/libre-tube/LibreTube/pull/4023#issuecomment-1595825611
