### ISSUE TITLE
Add highlight from Sponsorblock

### ISSUE THREAD

**Issue by Myzel394** [libre-tube/LibreTube#4059]
### Describe your suggested feature

Currently, LibreTube previews chapters:

![20230620_132553_temp](https://github.com/libre-tube/LibreTube/assets/50424412/b0254674-c6d6-4304-8ba7-45701fa0f48b)

It would be cool if the highlight from Sponsorblock would also be shown there.

### Other details

If it's no problem, I'd be more than happy to implement this myself - this would help me learn Kotlin better and add a new awesome feature :D

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Myzel394** [comment]
Highlights are only a single time in the video. I would extract them, and if one exists, show a preview just like in the screenshot. Maybe add like some purple background to emphasize it.

**Comment by Bnyro** [comment]
Sounds good to me!
However I am not sure whether we can get the highlights directly by using the Piped API (is it just a category like other sponsors?). We aim to not connect to any other services than the Piped instance the user chooses. If it works using Piped, I think this would be a pretty nice addition.

**Comment by Myzel394** [comment]
I _think_ it is a category, but let me check that quickly...

**Comment by Myzel394** [comment]
I checked it now and yes, it's a category! It's actually _not_ called "highlight", but rather "poi_highlight" - just something I need to keep in mind when implementing it. Did I understand you correctly though, Piped also proxies the Sponsorblock requests? That's cool! :D

**Comment by Bnyro** [comment]
Yes, exactly! You can just look at the existing code for SponsorBlock for that.
