### ISSUE TITLE
in-app Upgradable Debug Builds

### ISSUE THREAD

**Issue by NeeRaj-2401** [libre-tube/LibreTube#4067]
### Describe your suggested feature

NOTE :: continuation of #2372 

As we have official [nightly-builds repo](https://github.com/libre-tube/NightlyBuilds) now.
& its possible to make pre-releases on nightly's repo.

These releases can be used to  make debug builds in app up gradable.
in app debug upgrades are useful for poeple like us, please look into this if possible.

### Other details

cloudstream have implemented it & it makes upgrading pre-release version hassale free.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Still not planned.

**Comment by NeeRaj-2401** [comment]
But bnyro, debug users are smart enough that they can understand it would not always be stable, 
still a warning would be enough.
