### ISSUE TITLE
Sometimes the notification bar stays and no mini floatable player aviable.

### ISSUE THREAD

**Issue by HageFale** [libre-tube/LibreTube#4069]
### Steps to reproduce

1. 1 from 100 times open video
2. Notification bar doesnt disapear it stays there i mean.

### Expected behavior

rotate display you get fullscreen without notfication bar

### Actual behavior

notfication bar stays in fullscreen and no mini floating player only audio is in background it was different in 0.15.0 i am using 0.15.1

### LibreTube version

0.15.1

### Android version

MIUI Mi 11 Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please share a screen recording.

**Comment by Bnyro** [comment]
Closing due to no response.
