### ISSUE TITLE
Enhance Recommendation System

### ISSUE THREAD

**Issue by MohamedAtef321** [libre-tube/LibreTube#4070]
### Describe your suggested feature

Enhance your recommendation system (whether for video/Audio) to match personal data like youtube's recommendation system

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#2612
