### ISSUE TITLE
Enhance color picker with material you system palette

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#4075]
### Describe your suggested feature

Follow material design would be better.
Here is a screenshoot of Nova Launcher 8 color picker as an example. You can see there is choice to use system palette colors (and will be updated when the system colors are changed), or select fixed colors, or manually select hex color.

![Screenshot_20230623-134535_Nova Launcher](https://github.com/libre-tube/LibreTube/assets/14180594/edfb250f-4b28-462a-8fda-72d7bcccf6b9)
![Screenshot_20230623-135147_Nova Launcher](https://github.com/libre-tube/LibreTube/assets/14180594/44b76a28-b03b-44f0-bf1e-0b9b216feafb)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That is out of scope for the color picker, since accent colors can change often when changing the wallpaper it wouldn't make much sense either.
