### ISSUE TITLE
Hidden navigation bar 

### ISSUE THREAD

**Issue by Uranusek** [libre-tube/LibreTube#4079]
### Steps to reproduce

When minimized, the playbar partially covers the navigation bar. 
![Screenshot_20230623-194124~2](https://github.com/libre-tube/LibreTube/assets/135356908/9ad8a2aa-ef6f-4f3e-943f-7532166279a1)

### Expected behavior

Minimize above or below the navigation bar.

### Actual behavior

Partially covers the navigation bar. 

### LibreTube version

0.15.1

### Android version

Android 10/11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
See the pinned issue.
