### ISSUE TITLE
Enabled Codecs (Multiple)

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#408]
It is available in the official Piped project.

**Comment by Bnyro** [comment]
1. Why would you need it?
2. Where is it available on piped.kavin.rocks?

**Comment by Legoks** [comment]
Preferences
![Screenshot_20220607-090217_Chrome](https://user-images.githubusercontent.com/104249296/172299834-c37f6679-71a4-43d1-9d9f-47c36b24b92b.jpg)

**Comment by nateRiver111** [comment]
I would also like this feature

**Comment by Bnyro** [comment]
The player we use chooses automatically the best codec for your device, we can't influence that process.
