### ISSUE TITLE
DeArrow support

### ISSUE THREAD

**Issue by Terkyz** [libre-tube/LibreTube#4080]
### Describe your suggested feature

Sponsorblock developers created a new tool or browser extension called [DeArrow](https://dearrow.ajay.app/) to filter out misleading content and clickbait thumbnails, it would be great if this tool was integrated into Libretube, I think overall the Libretube experience can be improved by filtering out all that junk Youtube content with DeArrow.

### Other details

> Titles can be any arbitrary text. Thumbnails are screenshots from specific timestamps in the video. These are user submitted and voted on. By default, if there are no submissions, it will format the original title to the user-specified format, and set a screenshot from a random timestamp as the thumbnail. This can be configured in the options to disable formatting, or show the original thumbnail by default.

If it is possible to integrate this capability within LibreTube so that the user can also support the development of DeArrow and add more videos to the list of submissions.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Same answer as for https://github.com/libre-tube/LibreTube/issues/3993#issuecomment-1587727547

**Comment by sauerbread** [comment]
Hi there, it seems like Piped [added server side Dearrow](https://github.com/TeamPiped/Piped/issues/2575#issuecomment-1641269041) support now. Maybe this issue could be reopened. Here is an [example thumbnail](https://pipedproxy.kavin.rocks/api/v1/getThumbnail?videoID=yhB3BgJyGl8&time=1.0984946666666666&host=dearrow-thumb.ajay.app) for reference.

**Comment by FireMasterK** [comment]
> Hi there, it seems like Piped [added server side Dearrow](https://github.com/TeamPiped/Piped/issues/2575#issuecomment-1641269041) support now. Maybe this issue could be reopened. Here is an [example thumbnail](https://pipedproxy.kavin.rocks/api/v1/getThumbnail?videoID=yhB3BgJyGl8&time=1.0984946666666666&host=dearrow-thumb.ajay.app) for reference.

Libretube also has DeArrow support in the latest debug/alpha builds.
