### ISSUE TITLE
Player opens in minimized mode when opening video from external link

### ISSUE THREAD

**Issue by ticklemyIP** [libre-tube/LibreTube#4081]
### Steps to reproduce

1. Open external link
2. App handles it
3. Opens stream in minimized view

### Expected behavior

The stream is opened in the regular size.

### Actual behavior

It opens as a mini player and has to be maximized

### LibreTube version

0.15.1

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#3260
