### ISSUE TITLE
Remember scroll placement and other features when switching tabs/interfaces

### ISSUE THREAD

**Issue by ticklemyIP** [libre-tube/LibreTube#4082]
### Steps to reproduce

1. Open Subscriptions tab
2. Tap on a channel
3. App opens channel page
4. Go back
5. Subscritons tab unnecessarily reloads and loses scroll height and other attributes

1. Scroll on Sub tab
2. Switch to other tab
3. Switch back
4. Attribures are lost

### Expected behavior

The app remembers scroll positions and other crucial stuff, doesn't reload the feed.

### Actual behavior

It reloads the feed and thus loses attributes.

### LibreTube version

0.15.1

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by terminal-cs** [comment]
+1

**Comment by thornySoap** [comment]
Is this fixed? It's quite strange in my case (latest f-droid version):

Basically if I just scroll up to one screen height down then the scroll position persists after returning to the subscription screen. If I scroll up to two screen heights it resets to about one screen height scrolled. If I scroll more than two screen heights then after returning the scroll is completeley reset.

Similarly, the scroll position of any video list resets after going into full screen mode, which is kind of annoying. Imagine watching some Ted-Eds from a couple of years ago and having to scroll down hundred of videos every 4 minutes.
