### ISSUE TITLE
Add a shorts tab and/or reel at the top

### ISSUE THREAD

**Issue by ticklemyIP** [libre-tube/LibreTube#4085]
### Describe your suggested feature

The feed can sometimes become a bit clunky when a bunch of Shorts get published and the vertical thumnails applied to a horizontal canvas doesn't look pretty either imo. I would envision some kind of swipable shorts reel (much like in the regular YT app) and/or a separate tab just for Shorts. One main thing is, it needs to be historical (so a user could go back in time, search and list the Shorts). Maybe an icon above the reel could enter a separate menu or tab (only accessible through this icon by default) that shows all the shorts in a grid-like fashion with titles underneeth or in a list view but with proper matching thumbnail sizes.

Maybe both could be doable. By default there is a regular Reel with an icon above or opposite to the reel's title, which enters this separate (by default hidden menu or tab). If there is no space for this icon, then after swiping let's say 10 Shorts in the reel instead of an 11th Short, there could be an empty card in it's place with an icon and text that enters to this hidden Shorts tab. If the user devcides to add this tab to the bottom, next to Subscriptions etc. the icon (if we went with this idea) would disappear because it would be unneeded, but the reel card could stay. I don't know if this reel is scrollable to infinity in the regular YT app or not. Maybe the icon or the separate tab could be interchangable parts.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Currently, there are no plans to add a specific different layout for shorts videos only. Maintaining such a shorts relm additionally to the normal player would be a ton of work, apart from that initially building one would not be worth the time in my eyes. Feel free to browse other closed issues on that topic too.
