### ISSUE TITLE
Add elements to and improve Library tab

### ISSUE THREAD

**Issue by ticklemyIP** [libre-tube/LibreTube#4086]
### Describe your suggested feature

The user created Playlists doesn't show an uploader's profile image next to the videos in the playlist view (should be like in the subsribtion tab), there is only a name. Same applies to Bookmarked playlists:

If the Bookmarked playlists (made by an uploader) can only include videos from the uploader itself (idk this one) and the uploader can't include another channels' videos' in their playlists, than a profile image (and name which currently exists) next to the titles may be unneeded. But in playlist view, in the plaxlist header, a profile image is still needed (theres only a name currently).

If there can be other videos in these playlists, then an image is needed as well (there is only a name right now) next to the title. This is also applicable the Library (not playlist) view. Even if other videos, other than the uploaders are present in the playlist the icon and name who the playlist belongs to should always be displayed next to the playlist name in the Library view (currently there is only a name) as well as the playlist header (already mentioned).

There is also no views counter and elapsed time in this tab next to the videos both in the user Playlists and Bookmarked ones.

The darkening overlay over the video's thumnails that shows a playlist icon and the number of videos is unnecessarily wide I think.

Also the Bookmarked playlists doesn't show the number of videos in the playlists.

Confirm the deletion of a playlist entry when swiping to delete. I get why this is there (to make deleting in bulk quicker) but this makes accidentally deleting stuff way too easy. I suggest a confirm deletion popup at first with a "Don't ask again in this session" checkbox in it, that would disable that popup in the current session.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
1./2. There's no such info returned by the API returned for every playlist.
4./6. The video count can change for bookmarks and therefore is not stored. We don't fetch them all the time, we store them in the in app database.
5. Changed in debug builds.
7. Removing a video from a playlist is meant to be a quick action, and the threshold is large enough to not accidentally remove a video.

**Comment by ticklemyIP** [comment]
Are the other points getting considered?
