### ISSUE TITLE
Add region switching to Trending tab

### ISSUE THREAD

**Issue by ticklemyIP** [libre-tube/LibreTube#4087]
### Describe your suggested feature

The region setting in the settings menu is great and all but if someone wants to browse different region's Trends they have to go back and forth between the setting and the tab. I suggest moving this setting to the top of the trending page as a form of an icon, much like the Subsriptions menu in at the top of the Subsricptions tab, that triggers a region menu. This could have the list of all regions (maybe a search bar), and a user could favorite or pin some regions to the top of this list.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Sounds useless as nobody would switch to a region with a totally different language that the user don't  really understand.

**Comment by ticklemyIP** [comment]
Disagree, I know many polylingual people who speak and use 2 or 3 languages BESIDE the jack of all trades english. Some people may just want to search around what searches where. Maybe it's rarely changed because it's hardly accessible. I see no negatives if this would be added. More consistent UI elements (I mean the neighbouring Subscribtions menu), more direct, more reachable.

**Comment by akano12** [comment]
> Disagree, I know many polylingual people who speak and use 2 or 3 languages BESIDE the jack of all trades english. Some people may just want to search around what is trending where, no reason to dismiss a suggestion because you wouldn't (or couldn't )use something. Maybe it's rarely changed because it's hardly accessible. I see no negatives if this would be added. More consistent UI elements (I mean the neighbouring Subscribtions menu), more direct, more reachable.

How is this option hardly accessible? The app is well designed and documented and everything is where it should be, your point is invalid.

Those people you're talking about **in case they use this project** have been using YouTube for over a decade without this feature and again, **IN CASE THEY USE THIS PROJECT**, they could've requested for this feature themselves instead of you speaking on their behalf to show that there are quite some people requesting this not just a single individual. 
This app been out for over a year and you're the first one to bring out such suggestion, which means that you **and your supposed friends of course** who represent a little over 0% of the project users are the sole users who find this feature useful.

**Comment by ticklemyIP** [comment]
You're trying to justify gatekeeping this suggestion based on the idea of yours that theoretically people "won't use it". Meanwhile you are just projecting your own ideas and wants on other people (much like you accused me of). You said who would find it useful? My friends would. Doesnt mean they use the app, doesnt mean they would make such a proportional userbase of the app. I would like to see your research and statistics that proves that the use of this feature would be marginal, which requires ACTUALLY IMPLEMENTING the feature first to begin with. I don't get you dude, this the second issue you feel the right to gatekeep my suggestions and you made it quite obvious you don't have anything actually useful to add to this conversation (that actually helps this project) and don't even have the slight desire to do so, so now i'll just plain ignore you. Have a nice day, night whatever it is for you.

**Comment by akano12** [comment]
> You're trying to justify gatekeeping this suggestion based on the idea of yours that theoretically people "won't use it". Meanwhile you are just projecting your own ideas and wants on other imaginary people and userbases (much like you accused me of). You asked me who would find it useful? My friends would. Plain and simple answer. Doesnt mean they use the app, doesnt mean they would make such a proportional userbase of the app. I would like to see your research and statistics that proves that the use of this feature would be marginal, which requires ACTUALLY IMPLEMENTING the feature first to begin with. I don't get you dude, this the second issue that you feel the right to gatekeep my suggestions under and you made it quite obvious you don't have anything actually useful to add to this conversation (that actually helps this project) and don't even have the slight desire to do so, so now i'll just plain ignore you. Have a nice day, night whatever it is for you.

I ain't reading what you said because i truly don't care  neither about nor about your friends. And hopefully this answers your question (same request but different feature, this was the response) 
https://github.com/libre-tube/LibreTube/issues/4013#issuecomment-1595376594

**Comment by ticklemyIP** [comment]
I care too much about the peace of this project that I'm not even gonna allow you to reply to me anymore. You can play ignorant in my blocked list.

**Comment by Bnyro** [comment]
Not planned, there's no clear purpose of switching the region the fly. Either you use the trending of the region you live in or care about, or you don't use it at all. I'm certain you would be the only person using that feature, and as already stated out in https://github.com/libre-tube/LibreTube/issues/2206#issuecomment-1336193310, such features won't get implemented.

**Comment by flexxxxer** [comment]
This is implemented btw. Idk how long ago, but you can change region on the fly from Trending and Home tab.

@Bnyro maybe close that as implemented?

**Comment by Bnyro** [comment]
True, ty
