### ISSUE TITLE
Allow copying video title

### ISSUE THREAD

**Issue by ticklemyIP** [libre-tube/LibreTube#4088]
### Describe your suggested feature

I don't know how this could work out best, because the title also works as the description drop down trigger. Maybe long pressing this title field could copy the title. I think that's that best option.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Just out of curiosity, can you explain to me how would this be useful or in what way would improve the user experience? 

The reason I'm asking is because i really can't think of uses cases other than for saving/sharing purposes. But if I want to share a video with someone, i can directly share the link, if i want to save a video, i can bookmark or copy link (which are all better than copying title) 

I don't really see a benefit of this, just my opinion

**Comment by ticklemyIP** [comment]
Just because you don't see a benefit doesn't mean there aren't. You want to copy the title? And I mean JUST the title? Sucks for you, you either have to open the video with the crappy youtube website, wait until all the grabage loads, then copy. Or if you don't mind having the URL with you title, sure share the video, click on Youtube or Piped or whatever, then copy the shared text (with the URL which you later have to manually delete). Not to mention older Android versions and some other OEM ROMs doesn't even allow yoi to copy from the share API. This isn't even a hard feature to implement. Again there is no negative to this feature.

**Comment by akano12** [comment]
You had the time to write a whole article on how I'm wrong but couldn't afford few lines to tell the use cases of this suggestion?

And if i replied, that doesn't mean the project owner is obliged to follow my words, not sure why you said "hardcore gatekeeping"

**Comment by ticklemyIP** [comment]
But that's the thing, I DID actually tell you the usecase. Don't worry I made a quote for you so you can check it out :) ↓

> You want to copy the title? And I mean JUST the title? Sucks for you, you either have to open the video with the crappy youtube website, wait until all the grabage loads, then copy. Or if you don't mind having the URL with you title, sure share the video, click on Youtube or Piped or whatever, then copy the shared text (with the URL which you later have to manually delete). Not to mention older Android versions and some other OEM ROMs doesn't even allow you to copy from the share API. This isn't even a hard feature to implement

As I said in one of my previous issues from now on I'll ignore you cause you do not contribute anything to these conversations.

**Comment by Bnyro** [comment]
Not planned, https://github.com/libre-tube/LibreTube/issues/2206#issuecomment-1336193310

**Comment by ticklemyIP** [comment]
I think copying the title is something more than 0.1% the userbase would want to do.

**Comment by Bnyro** [comment]
Create a PR then.
