### ISSUE TITLE
Option to disable/hide shorts

### ISSUE THREAD

**Issue by iwannet** [libre-tube/LibreTube#4089]
### Describe your suggested feature

An option in the settings were you can disable/hide all shorts from showing up on your subs and home page.

This feature would be really usefull, thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
duplicate of #4065

**Comment by iwannet** [comment]
Lol i could find the duplicate
