### ISSUE TITLE
Memorize the playback speed

### ISSUE THREAD

**Issue by devstra** [libre-tube/LibreTube#410]
### Describe your suggested feature

When I change the playback speed on a video, if I open another video, the playback speed is reset to its default. I think it would be more useful if that setting was memorized, much like youtube.com does.

What do you think ?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't think so because I only watch videos with a different speed after I started it and realized how fast I want it to be.
But I could add a setting to set the default speed if that is okay for you
