### ISSUE TITLE
Removing 25% watched video from the feed is going to create a new problem

### ISSUE THREAD

**Issue by StrangeSam99** [libre-tube/LibreTube#4105]
### Describe your suggested feature

Change the 90% value to 25% (#4103) is going to create the problem of closing a video in the middle of the watch and seeing it disappear from the feed page.
I suggest to make the value pickable from a range and not fixed.
#4013 doesn't solve #4032, IMO the way to solve it, is to allow users to mark videos watched and not watched simultaneously while they are partially viewed in the feed page, in order to allow to choose which videos are interesting and have to stay in feed page until completely complete (over 90%), and which are not (marking as watched in any moment, also if it is partially watched, to remove them from feed).
Another solution could be to create a new option in the menu of long pressing to a video in feed page which allow simply to remove a not interesting video without the need of marking the video as watched (the 25% of #4013 would still remain a relevant problem). 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Allowing users to choose the border themselves is pointless for such a minor thing, the easiest solution is to keep the "Mark as watched" button visible forever and only show the "Mark as unwatched" button when the video is already partially watched. The limit has now been reverted back to 90%

**Comment by StrangeSam99** [comment]
I think this is the simplest and best solution for the problem
