### ISSUE TITLE
Animate thumbnail into bottom sheet

### ISSUE THREAD

**Issue by Myzel394** [libre-tube/LibreTube#4107]
### Describe your suggested feature

So if an user long presses on a video a bottom sheet opens. It would be absolutely cool if the thumbnail could move from its current position into the bottom sheet (if I wasn't clear enough I can create a small demonstration).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
First of all, that's not possible since we use the Material Design 3 bottom sheet, and no motion layouts for it.
Secondly, it would look very weird in my opinion and the thumbnail wouldn't match the design of the bottom sheet at all.

**Comment by Myzel394** [comment]
I see, could we still show the thumbnail without an animation? I think it would make the sheet a bit clearer what it is referencing to.
