### ISSUE TITLE
Broken aspect ratio after shorts switching

### ISSUE THREAD

**Issue by 0xrxL** [libre-tube/LibreTube#4111]
### Steps to reproduce

1. Open a video marked as short.
2. Minimize the player with gesture but don't close it.
3. Tap on another video marked as short.
4. Now the video aspect ratio appears to be stretched and video player controls are not shown after a tap.

### Expected behavior

Not broken aspect ratio and working video player controls.

### Actual behavior

Broken aspect ratio:
https://github.com/libre-tube/LibreTube/assets/127248639/ac106167-9038-4651-a09e-df7f3a5cc148

Not visible video player controls after a tap:

https://github.com/libre-tube/LibreTube/assets/127248639/8596717c-16c4-4e6b-8fc5-1bee6c636513

### LibreTube version

Last 0.15.1 Debug

### Android version

Android 13 One Ui 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by 0xrxL** [comment]
P.S: If nothing happens, switch between two shorts more than 1/2 times. 👍

**Comment by Bnyro** [comment]
Since nobody else seems to have the issue and it's not reproducible, I either assume it's already fixed or a device side issue.
