### ISSUE TITLE
Like/dislike on videos with both counters disabled

### ISSUE THREAD

**Issue by 0xrxL** [libre-tube/LibreTube#4112]
### Steps to reproduce

1. Open [this video](https://youtube.com/watch?v=KGTVC3Nffc0&t=13).
2. Likes or dislikes are not allowed on this video.
3. LibreTube will show -1 as likes/dislikes count.

### Expected behavior

LibreTube should show 0 (or NaN, or Disabled) as likes/dislikes count.

### Actual behavior

-1 is show

### LibreTube version

Last 0.15.1 Debug

### Android version

Android 13 One Ui 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
-1 is shown because that's what the API returns. I don't see a reason for changing that behavior.

**Comment by 0xrxL** [comment]
> -1 is shown because that's what the API returns. I don't see a reason for changing that behavior.

Maybe "Disabled/Disabled" could be more explanatory for users.
