### ISSUE TITLE
Low video cards preview image quality

### ISSUE THREAD

**Issue by 0xrxL** [libre-tube/LibreTube#4113]
### Steps to reproduce

1. Tap on Trends tab
2. Give a look the the video cards preview

### Expected behavior

Preview video cards image quality should be increased, like on stock YouTube client.

### Actual behavior

Current image quality is low.

![Screenshot_20230626_003109_LibreTube Debug](https://github.com/libre-tube/LibreTube/assets/127248639/20f583ba-d0e9-4f9a-a6b5-b5aaf0901283)

### LibreTube version

Last 0.15.1 Debug

### Android version

Android 13 One Ui 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Duplicates, search the closed issues yourself
