### ISSUE TITLE
Contextual menu

### ISSUE THREAD

**Issue by devstra** [libre-tube/LibreTube#412]
### Describe your suggested feature

As of this writing you have to open a video to access share, download and playlist functions.
What would be more useful in my opinion would be to have a contextual menu that opens when you right-click/hold click on a video in the search results. NewPipe has this feature, and I for one would really like to have it implemented in LibreTube. This would make accesing the previously mentionned features more straightforward.

What do you think ?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We already have this feature, it appears when you long click on a video. It's there since the latest version.

**Comment by devstra** [comment]
> We already have this feature, it appears when you long click on a video. It's there since the latest version.

My bad, it seems I wasn't using the latest version of the app.
