### ISSUE TITLE
Fetch latest play position from Piped

### ISSUE THREAD

**Issue by Myzel394** [libre-tube/LibreTube#4121]
### Describe your suggested feature

When you watch a video locally, LibreTube will remember its latest play position. Watching a video on the linked piped instance doesn't do that. I'd like to see this in LibreTube as well.

### Other details

I can open a PR.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not yet supported by the Piped backend, there's an open issue at the Piped repo iirc.

**Comment by Myzel394** [comment]
It does work for me on Piped. If I watch a video there and reload the page, it'll jump back to where I was. Strangely, I could not find where this is implemented. There's nothing in the localStorage nor in a cookie, and I couldn't find this on the backend either - but I'm also not a Java expert so I might overlooked something.

**Comment by Bnyro** [comment]
It's saved in IndexedDB. LibreTube has that too called watch positions, but it's not synced with Piped.
