### ISSUE TITLE
Featured Videos Arranged in a Column

### ISSUE THREAD

**Issue by devbytemehedi** [libre-tube/LibreTube#4124]
### Describe your suggested feature

I want the featured videos arranged in a column when other content is unselected
![Screenshot_2023-06-27-05-09-20-77_54f92cd6866f5233ab0db4392b806878](https://github.com/libre-tube/LibreTube/assets/89072438/e8b1f057-6fa5-43d4-8cbc-1bbb0e35ab0e)

### Other details

**It should look something like this**
![Screenshot_2023-06-27-05-11-46-50_cc114bec087609c93733eb02d5393759](https://github.com/libre-tube/LibreTube/assets/89072438/02f222d5-b6c5-4515-a63b-2b89b32096d8)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by devbytemehedi** [comment]
It looks like this now
![Screenshot_2023-06-27-05-18-23-80_54f92cd6866f5233ab0db4392b806878](https://github.com/libre-tube/LibreTube/assets/89072438/bf30a29c-ea0b-4b7f-9bd3-4d2df7501b2b)

**Comment by Bnyro** [comment]
For that purpose, set the subscriptions tab as home tab. Settings -> Appearance -> Navigation Bar -> Order -> click one of the home icons in the left.
