### ISSUE TITLE
Seek bar doesn't follow material you theme

### ISSUE THREAD

**Issue by terminal-cs** [libre-tube/LibreTube#4129]
### Steps to reproduce

1) Set a theme in Android
2) see that seek bar only uses the DS default libretube color

### Expected behavior

The seek bar should be colored according to the system when system theming is enabled in the app

### Actual behavior

The color of the seek bar does not change

### LibreTube version

Latest (1.15.1)

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It does follow the theme, just not the primary color.

**Comment by terminal-cs** [comment]
> It does follow the theme, just not the primary color.

You should add a screen to customize what uses what color
