### ISSUE TITLE
Seek bar is infuriating to grab

### ISSUE THREAD

**Issue by terminal-cs** [libre-tube/LibreTube#4130]
### Steps to reproduce

1) try to move seek bar
2) see that it dismisses the controls overlay even after 7+ attempts 

### Expected behavior

Should seek properly

### Actual behavior

Seek bar does not detect dragging

### LibreTube version

Latest (0.15.1)

### Android version

Android 13

### Other details

Solution: increase "hitbox" of the seek bar without changing it's visual size, possibly make it an option.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please share a recording.

**Comment by terminal-cs** [comment]
> Please share a recording.

It is intermittent, doesn't happen commonly but does happen

**Comment by unityastronaut** [comment]
I've noticed this too. Also sometimes taping the playing video doesn't show the controls (Pause, Skip, Seekbar) at all. It seems that occasionally touch controls in the normal player (haven't noticed it in fullscreen) aren't registered. I'll try to get it on video next time it happens.

**Comment by luckkmaxx** [comment]
I suscribe @terminal-cs and @unityastronaut described bugs.
1. The seek bar should have a thicker responsive zone, because you have to be too accure to grab it.
2. HUD controls not always is shown, rather normal and fullscreen . In normal mode I have to swipe down to move the video square a little, then the hud appears.

**Comment by Appel-flappen** [comment]
Here's a screen recording of me experiencing the issue. With the show taps enabled, it seems to me that when I try and tap on the bar I am often tapping below it. (Due to angle of finger maybe?) Perhaps the area can be expanded to include underneath the bar too?

**Comment by alpentmilch** [comment]
This is one reason I still use NewPipe. It needs to be made thick.

**Comment by Donkey-Doug** [comment]
Related: https://github.com/libre-tube/LibreTube/issues/1260

**Comment by Donkey-Doug** [comment]
I can also have this issue. Sometimes it is like the seekbar refuses to register touch input.
