### ISSUE TITLE
initial player respsonse not valid

### ISSUE THREAD

**Issue by itsmmt305** [libre-tube/LibreTube#4134]
### Steps to reproduce

open any video either in libretube or piped

### Expected behavior

the video shud play

### Actual behavior

a popup appears stating "initial player respsonse not valid"

![Screenshot_2023-06-28-11-26-36-045_com github libretube](https://github.com/libre-tube/LibreTube/assets/94820934/2fdde3f7-4b85-4764-af0f-6c1a61f308a8)
![Screenshot_2023-06-28-11-26-49-016_com brave browser](https://github.com/libre-tube/LibreTube/assets/94820934/781a4113-524b-4f94-ae56-634229e20ad6)

### LibreTube version

0.15.1

### Android version

Android 12 | MIUI 13.0.5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/TeamPiped/Piped/issues/2487

**Comment by XSuperMeteorX** [comment]
the same problem

**Comment by XSuperMeteorX** [comment]
![Uploading IMG_20230630_185711.jpg…](omg)
pic below

**Comment by XSuperMeteorX** [comment]
![IMG_20230630_185711](https://github.com/libre-tube/LibreTube/assets/69909444/c3197a9a-b3a3-400f-9bde-358dea66a5fa)
pic below
