### ISSUE TITLE
Bug: "initial player response not valid"

### ISSUE THREAD

**Issue by Golukumar00** [libre-tube/LibreTube#4135]
### Steps to reproduce

https://github.com/libre-tube/LibreTube/assets/119071430/f72aecbf-4647-4a7b-ac3c-e898de964b61

### Expected behavior

No response 

### Actual behavior

No response 

### LibreTube version

Nighty build ( downloaded today)

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/TeamPiped/Piped/issues/2605
