### ISSUE TITLE
An Option to Disable Piped Proxy Completely

### ISSUE THREAD

**Issue by matt873** [libre-tube/LibreTube#4137]
### Describe your suggested feature

Though piped proxy can be disabled to load video and images directly from Google servers but the app still connects to piped proxy for the initial loading of user data, subscriptions, etc and there are two main reasons for an option to disable piped proxy completely:
1. Those who have already disabled piped proxy for loading video and images can benefit from this because piped proxy sometimes gives errors and it's not perfect and so there is an unnecessarily bad user experience with the app.
2. Initial loading of videos and images will be faster on the app launch for the reason that the app will not have to contact piped servers to obtain user data.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
This would be a ton of work, and hence is out of scope for the project as long as Piped exists.

**Comment by matt873** [comment]
I think this will make a lot of sense now because of what is happening with Piped for some time.
