### ISSUE TITLE
"Initial player response is not valid" error when trying to play any video

### ISSUE THREAD

**Issue by arshajib** [libre-tube/LibreTube#4138]
### Steps to reproduce

Just play any video

### Expected behavior

Play the video

### Actual behavior

Video player screen remains dark and this message shows up

### LibreTube version

Latest. 0.15.1

### Android version

12

### Other details

![Screenshot_2023-06-29-00-41-09-185-edit_com github libretube](https://github.com/libre-tube/LibreTube/assets/6566553/71f02ff1-9e8c-464b-9057-47323d015782)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/TeamPiped/Piped/issues/2605
