### ISSUE TITLE
Space for new stream notifications.

### ISSUE THREAD

**Issue by Legoks** [libre-tube/LibreTube#414]
### Describe your suggested feature

It would be a good idea to place the Incoming Notifications button next to the Search bar.
![Screenshot_20220607-132637_YouTube](https://user-images.githubusercontent.com/104249296/172346179-221e6cbb-5595-4ae8-94e8-33f05ed6bad4.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Legoks** [comment]
That would be great in terms of design.

**Comment by Bnyro** [comment]
please comment it under #346 because it refers to it
