### ISSUE TITLE
Show "default" Instead of "en" In Audio Track

### ISSUE THREAD

**Issue by akano12** [libre-tube/LibreTube#4142]
### Describe your suggested feature

Show "default" instead of "en" in audio track. 

### Other details

Currently LT shows "en" as the default audio track of a video, for example I'm watching a video in Polish language and LT is showing "en" as the audio track.

A simple workaround for this is to show "default" in audio track unless it's explicitly changed by the user. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We should wait until the PR for #3576 gets merged first to avoid unneeded merge conflicts (@AudricV already has a working implementation for that, but he's currently busy with other things unfortunately)

**Comment by Bnyro** [comment]
Hey @akano12,

Since you have been quite active and helpful by commenting and providing help under other issues, I would like to ask you whether you'd be okay to become "triage" permissions on this repository, to be able to close issues (e.g. duplicates), and help a bit with maintaining the issue tracker (not much different to what you do already). The help would be really appreciated!

Cheers
Bnyro

**Comment by akano12** [comment]
> Hey @akano12,
> 
> Since you have been quite active and helpful by commenting and providing help under other issues, I would like to ask you whether you'd be okay to become "triage" permissions on this repository, to be able to close issues (e.g. duplicates), and help a bit with maintaining the issue tracker (not much different to what you do already). The help would be really appreciated!
> 
> Cheers
> Bnyro

Hey (and sorry for late reply, idk why but I'm not receiving any notifications on github mobile, just saw this while checking my email).

I don't mind at all (if the position is still available). Since I'm unable to contribute with code (sadly I'm not familiar with kotlin) , I've been contributing by replying and assisting in issues as you've mentioned.

**Comment by Bnyro** [comment]
Cool, you should have received an invitation just now.
