### ISSUE TITLE
Thumbnails are not cached

### ISSUE THREAD

**Issue by terminal-cs** [libre-tube/LibreTube#4143]
### Steps to reproduce

1. Scroll down  a playlist after scrolling it amany times
2. See that thumbnails still create lag and reload

### Expected behavior

Thumbnails should be cached, clearable by the android cache clear button 

### Actual behavior

Thumbnails do not get temporarily cached

### LibreTube version

Latest (1.15.1)

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by terminal-cs** [comment]
Forgot to add: cache stays in the list only until the app is closed. Cache should be saved on storage, not ram

**Comment by Bnyro** [comment]
Settings -> Advanced -> Max image cache size.

**Comment by terminal-cs** [comment]
> Settings -> Advanced -> Max image cache size.

It still does not keep cache after restarting the app with no cache limit set

**Comment by Bnyro** [comment]
Yes, because that's the default behavior...

**Comment by terminal-cs** [comment]
> Yes, because that's the default behavior...

It should be cached on device storage instead, reloading every thumbnail wastes bandwith un-neccisarrily and causes UI lag every time they load
