### ISSUE TITLE
Add support for local IPFS video storage

### ISSUE THREAD

**Issue by KonoromiHimaries** [libre-tube/LibreTube#4145]
### Describe your suggested feature

YouTube deleted many videos, to safe back my favorite video i want to host it myself without use other platform.

### Other details

Should work on this
```
https://github.com/danbrough/kipfs
```

To reduce bandwidth usage, video can be streamed via public gateways
```
https://ipfs.github.io/public-gateway-checker/
```

For more information about this idea, see
```
https://github.com/Chocobozzz/PeerTube/issues/494
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not planned from LibreTube's side.
