### ISSUE TITLE
Option in appearance to hide play all & ease history inside watch history.

### ISSUE THREAD

**Issue by Snailhail** [libre-tube/LibreTube#4155]
### Describe your suggested feature

Have there be an option in appearance to hide play all & ease history located in watch history due to times where I press them by mistake. 
The confirm prompt  does help avoid disaster, but I would appreciate the option.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's currently not planned.
