### ISSUE TITLE
Wrong user/password after restoring backup from welcome screen

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#4157]
### Steps to reproduce

Clean install:
1. Tap "Restore" in welcome screen
2. Goto settings > Instance > Login (Here I have pre-selected my own instance recovered from backup)
3. Fill login data and got wrong user/password
4. Try to login again. Wrong credentials again.

### Expected behavior

Login the selected instance with that user.

### Actual behavior

Login error (toast message)

### LibreTube version

0.15.1 debug

### Android version

13

### Other details

5. Tap to choose an instance
6. Select the same pre-selected one.
7. Try to login. Bingo!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
So the issue is, that the backup doesn't restore the instance?

**Comment by luckkmaxx** [comment]
No. You can still see videos, search and trending are working, but cant login until I re-select the instance.

**Comment by Bnyro** [comment]
So it shows the "logout" button?

**Comment by luckkmaxx** [comment]
> So it shows the "logout" button?

Yes, when finally logged in of course.

The fact that after restoring a backup, lets me see videos, Im not sure if the app is getting them from a default instance, or actually is getting from the instance that was restored (and I can see as selected).
Maybe the wrong login is because even if I see that the selected instance is mine, the app is actually using another one

**Comment by Bnyro** [comment]
No, it always uses the instance shown in the settings.

**Comment by luckkmaxx** [comment]
Cant you reproduce it?

**Comment by Bnyro** [comment]
I will let you know when I tested it.

**Comment by luckkmaxx** [comment]
Additionally, 
Tested in 0.15.1 stable, since there you first select a default instance (no restore button yet) and then you go to restore a backup. Then you can login without issues.
So I tested again in debug version, with the same procedure of stable version. It works! So the issue comes when restoring from welcome screen.
