### ISSUE TITLE
Player bar is clipped over the navigation bar

### ISSUE THREAD

**Issue by celldra** [libre-tube/LibreTube#4159]
### Steps to reproduce

1. Open a video
2. Swipe the video down to show the player bar
3. You should see that the player bar is clipped over the navigation bar

### Expected behavior

It should appear above the navigation bar

### Actual behavior

The player bar is clipped over the navigation bar

### LibreTube version

0.15.1

### Android version

Android 14 Beta 3.1

### Other details

Running on a Pixel 7
Android 14 Beta 3.1 (stock release)
Installed from F-Droid

Find attached a screenshot of the problem.
![Screenshot_20230704-092157](https://github.com/libre-tube/LibreTube/assets/124086032/161d8ab9-bdcc-4252-9a90-a71a0d0c68c0)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by luckkmaxx** [comment]
Duplicated. See #3861 (btw its a pinned issue)
This is a known and fixed issue. Not yet in stable. So next stable update will come with this fixed.
