### ISSUE TITLE
Bookmarks shows count 0

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#4160]
### Steps to reproduce

Go to library and see that bookmarks shows item count but all with 0. 
Playlists are working as expected.

### Expected behavior

Show the real amount of items per bookmark

### Actual behavior

all are 0

### LibreTube version

0.15.1 debug

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by luckkmaxx** [comment]
Not at all. Counting is implemented but it shows count zero
![Screenshot_20230704-122046_LibreTube Debug](https://github.com/libre-tube/LibreTube/assets/14180594/f4d48ab8-c3f6-4460-b14c-078a1e1e607a)

**Comment by Bnyro** [comment]
Open the bookmark once and it will be updated. The video count field got added recently, so there's no data yet for playlists that were bookmarked before that.

**Comment by luckkmaxx** [comment]
Will the Bookmarks be updated if the owner add/remove content, without having to open them?

**Comment by Bnyro** [comment]
No
