### ISSUE TITLE
Video control overlay invisible after switching back from audio mode

### ISSUE THREAD

**Issue by M00NJ** [libre-tube/LibreTube#4161]
### Steps to reproduce

1. Start playing a video
2. Switch to audio only mode
3. Switch back to video mode. 

Now the control overlay is not showing up anymore. It's still possible to pause and skip when touching the screen in the right spot, but the seekbar and control buttons are no longer visible. The touch indicators in the recording shows multiple taps in different spots of the player, but the controlls don't show up. Minimizing and then maximizing the video "wakes up" the control overlay again.

https://github.com/libre-tube/LibreTube/assets/82398591/316a46eb-0d97-44c0-b0f2-be0988246688

### Expected behavior

When taping the playing video in half-screen mode, the control overlay should pop up.

### Actual behavior

Sometimes the controlls stay hidden.

### LibreTube version

0.15.1

### Android version

Android 13 (GrapheneOS)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by luckkmaxx** [comment]
that is the behavior explained in #4130 (apart of main titled bug).
When you are in that situation, does swipiping down a litte and back (as if you were going to minimize) help to show the overlay?

**Comment by luckkmaxx** [comment]
My guess is that the interface stucks waiting for the video player being positioned at top, in the transition animation between feed/list > player. So when I move the player it gets fixed at top finally, and allows interaction with it.
This happens completelly randomly.

**Comment by Bnyro** [comment]
I'm aware of the issue, it's been around for a while.
However, I don't have a way to continuously reproduce it, so it's still unclear where the issue comes from.

**Comment by M00NJ** [comment]
> that is the behavior explained in #4130 (apart of main titled bug). When you are in that situation, does swipiping down a litte and back (as if you were going to minimize) help to show the overlay?

I will try this, when it happens next time. But so far I haven't experienced the bug in the new release.

I opened a separate Issue because I think these a separate problems. The bug described in #4130 also happens, when the control overlay is already displayed, at least for me that is...

**Comment by luckkmaxx** [comment]
related? #4436

**Comment by luckkmaxx** [comment]
Uploading YouCut_20230813_132314808.mp4…

**Comment by M00NJ** [comment]
> related? #4436

Yes, that's it! I switch between andio only and video mode a lot, because of the "pausing background playback bug". I didn't think that this was causing it, but I just tested it and it happened again. That means it's reproducible now. Great news!

**Comment by M00NJ** [comment]
I have updated the Issue title and description accordingly.

**Comment by M00NJ** [comment]
I haven't encountered this issue lately, so I did some quick tests and I couldn't reproduce it anymore. Does anybody else still have this? Otherwise we can close this.

**Comment by M00NJ** [comment]
I will reopen this if the issue reappears
