### ISSUE TITLE
Allow re-organization of playlists and show undo button for recent changes

### ISSUE THREAD

**Issue by terminal-cs** [libre-tube/LibreTube#4163]
### Describe your suggested feature

For sorting, there should be an edit button that brings up vertical "scrubbers" that allow video orders to be shifted around.

As for the undo button, it should show for however many seconds the user specifies in settings, and show fo 5 seconds by default. It would undo the last change incase of accidentally swiping videos away from the playlist,which is very easy to accidentally do.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
1. is not possible without API support.
2. an undo button is not planned, already got rejected in previous issues

**Comment by terminal-cs** [comment]
> 1. is not possible without API support.
> 
>     2. an undo button is not planned, already got rejected in previous issues

No, local playlists.
Also, why would you not add an undo button? It should at least be an option if somebody wants it. i would have used it numerous times myself

**Comment by terminal-cs** [comment]
Would an undo button be something you'd accept in a PR, or do you flat out just not want an undo button?
