### ISSUE TITLE
App crashes when selecting "Import subscriptions / Youtube (CSV)"

### ISSUE THREAD

**Issue by schuebel** [libre-tube/LibreTube#4168]
### Steps to reproduce

1. Settings
2. Backup & restore
3. Import subscriptions
4. Select "YouTube (CSV)"

### Expected behavior

I should be able to select a file to import.

### Actual behavior

It loads for about 5 secs, then the menu and everything disappears.
Navigating back does not work anymore, all I can do is close the app and reopen. 

### LibreTube version

0.15.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Could you please provide a crash log?

**Comment by schuebel** [comment]
Maybe freezing would be a better description. The app stays open but nothing is displayed, nor can I navigate back. So I guess there is no crash log.

**Comment by schuebel** [comment]
Apparently it just took some minutes.  I left it as it was (black screen) and opened another app. Half an hour later I'm going through my open apps an see, that it I can now select files. Don't know what caused this...
