### ISSUE TITLE
Fallback to piped proxy not working for music videos

### ISSUE THREAD

**Issue by Myzel394** [libre-tube/LibreTube#4183]
### Steps to reproduce

1. Enable "Disable Piped Proxy" and enable "Fallback to Piped proxy"
2. Try watching a music video

### Expected behavior

Should fallback to piped. If I disable "Disable Piped proxy" (aka force LibreTube to use the Piped Proxy), it works flawlessly.

### Actual behavior

Only a black screen is shown

### LibreTube version

0.16.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by rozari0** [comment]
Cann't reproduce. Works fine for me with default instance set as fallback.
