### ISSUE TITLE
Fallback to random Piped instance

### ISSUE THREAD

**Issue by Myzel394** [libre-tube/LibreTube#4184]
### Describe your suggested feature

During my use of LibreTube, some Piped instances would be down for some time - I always had to manually switch the Piped proxy during that time. It would be nice to have an option to automatically fallback to a random piped instance when the main selected one can't be reached. (Only for videos and images though, switching the auth instance obviously won't work so easily).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
This has already been talked about in previous issues and I still don't like the idea of letting users connect to random instances, of which they don't know the admin. Also that might end up in a lot of people getting moved to one certain instance (which might then get overloaded), while others might be operational again shortly.

**Comment by dtolia** [comment]
@Bnyro The enhancement suggested by Myzel394 seems agreeable with YouTube's recent crusade against downloader utilities and Google militarizing access controls for the final goal of collecting & warehousing user data.

LibreTube (v0.24.0) has indeed become comparably inefficient these past weeks. I had to change 6 instances to watch videos which took me around 2 minutes. But the average length of a YouTube ad is 15 to 30 seconds. This makes YouTube more convenient.

Now, the problem wouldn't be worth noting if one instance kept working continuously throughout the app session. But users get hit with a double whammy as the instance they chose stops working and they must cycle through all the available instances again to find a working one.

This mildly infuriating situation might be the reason why #6116 got locked as "too heated."

**Comment by Bnyro** [comment]
No instance works currently, so such an instance picker wouldn't work in this case anyways.

Pinging me is not appreciated as explained in the project's [Code of Conduct](https://github.com/libre-tube/LibreTube/blob/master/CODE_OF_CONDUCT.md), I'd like you to acknowledge that I disrespect that.

**Comment by dtolia** [comment]
> No instance works currently, so such an instance picker wouldn't work in this case anyways.
> 
> Pinging me is not appreciated as explained in the project's [Code of Conduct](https://github.com/libre-tube/LibreTube/blob/master/CODE_OF_CONDUCT.md), I'd like you to acknowledge that I disrespect that.

I apologize, Mr. Bnyro.
You're doing great work for the community.
