### ISSUE TITLE
When not able to get a channel’s videos list like usual, fallback to the RSS feed

### ISSUE THREAD

**Issue by hollownights** [libre-tube/LibreTube#4188]
### Describe your suggested feature

Any time YouTube makes some change to the channel’s videos page/tab, the NewPipeExtractor and, by extension, Piped and LibreTube can be affected by not being able to retrieve a list of videos. This problem also occurs if there is some restriction to the user’s IP address (in this case, a Piped’s instance). To alleviate this problem, when not able to get a channel’s videos list like usual, fallback to the channel’s RSS feed provided by the Piped instance in use. The RSS feed is limited to the latest 10 videos, but that is 10 videos better than nothing.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FireMasterK** [comment]
I feel like this is an extreme use case, we haven't had breaking channel page issues in a long time, and even if we did, getting an update on NewPipeExtactor and Piped should be easier than implementing this.

**Comment by hollownights** [comment]
Well, last time this happened with NewPipe was less than a year ago: https://github.com/TeamNewPipe/NewPipe/issues/9223

**Comment by FireMasterK** [comment]
> Well, last time this happened with NewPipe was less than a year ago: [TeamNewPipe/NewPipe#9223](https://github.com/TeamNewPipe/NewPipe/issues/9223)

Piped wasn't affected at all throughout that time, as although we use NewPipeExtractor, I maintained a fork that included the addition of support for channel tabs through merging some PRs that haven't been merged upstream.

NewPipe still to this day doesn't have support for channel tabs, [although it has been in Piped since October 27th, 2022](https://github.com/TeamPiped/Piped-Backend/pull/400). (before which, only the videos tab was accessible, unlike the issue you link above happened)

**Comment by hollownights** [comment]
@FireMasterK That is very good to know, but I think such case and measure still apply, specially from a NewPipeExtractor/Piped instance point of view, so maybe I should rewrite my suggestion:

Any time YouTube makes some change to the channel’s videos page/tab, the NewPipeExtractor and, by extension, Piped and LibreTube can be affected by not being able to retrieve a list of videos. This problem also occurs if there is some restriction to the user’s IP address (in this case, a Piped’s instance). To keep users' anger at bay when something like this inevitably happens, I propose:

1) **When the NewPipeExtractor/Piped instance** isn't able to get a channel’s videos list through the local API, fallback to the channel’s RSS feed provided by YouTube. The RSS feed is limited to the latest 10 videos, but that is 10 videos better than nothing;
2) **When LibreTube** isn't able to get a channel’s videos list from the Piped's instance in use at the moment, cycle through other instances to get videos from the channel's RSS feed proxied by a Piped instance. Unlike the normal behavior to get all videos, this behavior consumes very few resources.

@FireMasterK What do you say?

@Bnyro Not sure why you already closed this issue, as this still is an ongoing discussion and such a measure would raise both Piped's and LibreTube's potential uptimes.
