### ISSUE TITLE
VOLUME BOOST

### ISSUE THREAD

**Issue by sairam119914** [libre-tube/LibreTube#4194]
### Describe your suggested feature

i have an idea of having audio boost or volume boost just like an extension used in windows for maximizing the volume because whenever i watch lecture videos/online classes the audio level is too low it would be phenomenal if there is an audio boost 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
duplicate of #2186

**Comment by sairam119914** [comment]
> duplicate of #2186

well i dont know i just saw #2186 because i have been listening to some lectures and found out to have volume booster
