### ISSUE TITLE
Can't use newpipe 25.1 export in libretube 0.16 it gives an error "unsupported file format"

### ISSUE THREAD

**Issue by ghazzor** [libre-tube/LibreTube#4197]
### Steps to reproduce

1 ) export database from newpipe 25.1
2) use the data export to sync in libretube

### Expected behavior

It should sync

### Actual behavior

It says unsupported file format

### LibreTube version

0.16

### Android version

Android 12

### Other details

![Screenshot_20230708-235314_LibreTube](https://github.com/libre-tube/LibreTube/assets/127341071/0cb7c715-a130-4a91-bb7a-ca4167c54ae9)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FireMasterK** [comment]
You're supposed to go to the subscriptions tab, click on the three dots, and then the export to option.

**Comment by Bnyro** [comment]
We don't support importing the database, Json is the only supported format for importing from NewPipe.

**Comment by ghazzor** [comment]
> You're supposed to go to the subscriptions tab, click on the three dots, and then the export to option.

But newpipe only exports db file what to do as Google is not helpful

**Comment by FireMasterK** [comment]
> But newpipe only exports db file what to do as Google is not helpful

You're supposed to follow those instructions in the NewPipe app.

**Comment by ghazzor** [comment]
> > But newpipe only exports db file what to do as Google is not helpful
> 
> You're supposed to follow those instructions in the NewPipe app.

Where I can't find them.
I want to export from newpipe to libretube
