### ISSUE TITLE
Player Time Bar touches

### ISSUE THREAD

**Issue by martin-desktops** [libre-tube/LibreTube#421]
### Describe your suggested feature

I think this board explains everything - I tried to improve current Player Time Bar. 
![image](https://user-images.githubusercontent.com/64419373/172432312-9157ed9a-50d0-410f-aa69-01f71eba19ab.png)

Clean view:
![image](https://user-images.githubusercontent.com/64419373/172433396-d97290cc-d510-46f3-be3d-257749d93c78.png)

Additionally, I guess we would have to predefine colors for AMOLED theme for the sake of keeping contrast high enough.
I will be grateful for your feedback

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by martin-desktops** [comment]
Increased bottom margin should be applied also in a horizontal view, since also there the issue - time bar being almost sticked to the edge of the screen occurs.

**Comment by martin-desktops** [comment]
I've just opened the app and noticed that there is no longer issue with contrast. It seems like a bug. Also sometimes the time bar is above full screen, loop mode, captions icons etc, but for the most of the time it's under.

![Screenshot_2022-06-07-20-10-29-862_com.github.libretube.debug.jpg](https://user-images.githubusercontent.com/64419373/172453672-112cd801-af98-477d-b0cb-04c187667095.jpg)

Nevertheless, the rest of my points is still valid.

**Comment by oczt** [comment]
Please give some offset (blue highlight in picture) between the seekbar and icons. For example, while making fullscreen, often one ends up going to the end.
![11](https://user-images.githubusercontent.com/93979766/173772208-6c7a2550-ee15-4f84-b660-9977b44a51fa.png)
