### ISSUE TITLE
Swipe gesture in audio player works even when swipe gestures are disabled in options

### ISSUE THREAD

**Issue by slashdevslashurandom** [libre-tube/LibreTube#4212]
### Steps to reproduce

1. Disable "Swipe Controls" in "Settings" -> "Player"
2. Open a video in audio-only mode
3. Swipe vertically on the player's "album art"/"preview image" area

### Expected behavior

The swipe gesture should be ignored.

### Actual behavior

The player's volume changes.

### LibreTube version

0.16.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's the intended behavior. You can't accidentally use the swipe controls of the audio player because you usually don't touch the thumbnail while listening to music. There's no reason for disabling them hence.

**Comment by Mixcraftio** [comment]
> That's the intended behavior. You can't accidentally use the swipe controls of the audio player because you usually don't touch the thumbnail while listening to music. There's no reason for disabling them hence.

I cant see how that is intended behaviour. When wanting to put to small player it is perfectly logical to swipe over the thumbnail (It is how other music players do it). Moreover the option in settings is quite ambiguous as it seems to imply that it also disables swipe to change volume in music player too.
