### ISSUE TITLE
Tapping on Chapters While Video is Buffering Crashes LT

### ISSUE THREAD

**Issue by akano12** [libre-tube/LibreTube#4214]
### Steps to reproduce

Read the **Other Details** First

1. Play a video with chapters
2. Go to fullscreen
3. Select a chapter
4. Select a chapter again **while the video is still buffering** (this will crash the app)

### Expected behavior

I don't know how selecting a chapter while video is buffering is handled.
So either wait for the video to finish buffering before being able to select another chapter or go the selected chapter.

### Actual behavior

App crashes 

https://github.com/libre-tube/LibreTube/assets/50032603/f711ee8b-d70f-449f-9427-9c2fd55a3f32

### LibreTube version

0.16

### Android version

Android 13

### Other details

This is a dupe of https://github.com/libre-tube/LibreTube/issues/4198, the reason i opened this is because [that user blocked me](https://github.com/libre-tube/LibreTube/issues/4087#issuecomment-1605161297) and i couldn't post information about the bug.

So either close this or that so there won't be duplicate issues, just opened it to give information regarding the bug.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Atharv-Pathak-14** [comment]
Can confirm this happening with me to using Android 11 and libertube version 0.16.0

**Comment by Bnyro** [comment]
Please test if https://github.com/libre-tube/LibreTube/pull/4238 had an impact on that.

**Comment by Bnyro** [comment]
I never have been able to reproduce it so I'm not really sure.

**Comment by akano12** [comment]
> I never have been able to reproduce it so I'm not really sure.

All good, thanks

**Comment by Atharv-Pathak-14** [comment]
> I never have been able to reproduce it so I'm not really sure.

Sry for late reply it's working prefect now..... Thanks!!
