### ISSUE TITLE
Show icon when there is a new comment

### ISSUE THREAD

**Issue by Fish25op** [libre-tube/LibreTube#4215]
### Describe your suggested feature

Show icon when there is a new comment.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not sure if I get you, but no api support.
