### ISSUE TITLE
The reminder position is broken

### ISSUE THREAD

**Issue by Fish25op** [libre-tube/LibreTube#4217]
### Steps to reproduce

1.Open reminder position
2.Watch the video a bit
3.The video started from scratch

### Expected behavior

Restore feature functionality

### Actual behavior

https://github.com/libre-tube/LibreTube/assets/136016095/18c8bdbb-584f-4050-8da0-59833722eaab

### LibreTube version

0.16.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by M00NJ** [comment]
This has been fixed yesterday in #4206

**Comment by Fish25op** [comment]
Not fixed

**Comment by M00NJ** [comment]
> Not fixed

I has been fixed. You just have to wait for the next release for the changes to be applied :)

**Comment by Fish25op** [comment]
I updated to debug version.
