### ISSUE TITLE
Display author avatar in comment section replies

### ISSUE THREAD

**Issue by ukrbugreporter** [libre-tube/LibreTube#4218]
### Describe your suggested feature

![IMG_20230712_180740](https://github.com/libre-tube/LibreTube/assets/66782671/0c5410b6-054d-433e-93d1-d7c0717faa2f)
![Screenshot_2023-07-12-18-04-16-616_com github libretube](https://github.com/libre-tube/LibreTube/assets/66782671/da6b6473-0602-4ea3-9de5-46eebc3c8aa4)

Implement a feature from official YouTube client, that displays authors avatar when they reply to a comment under their own video (shown on first sceeenshot).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Unfortunately the NewPipe Extractor doesn't provide information on whether the video's creator has replied to a comment.
Replied need to get fetched with separate API calls (20 per request), do there's no easy way to figure it out.
Therefore we can't currently add this.
