### ISSUE TITLE
Backup isnt being launched with "Custom Instances" checked

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#4222]
### Steps to reproduce

1. Settings > Backup&Restore > Backup
2. With everything checked try to run a backup.
3. You have to uncheck "Custom Instances" (And "Watch History", that is another yet reported issue) to get it to work.

### Expected behavior

Run the backup as expected (show DocumentsUI to set a place where to save the backup)

### Actual behavior

When continuing after checking al options, nothing happens.

### LibreTube version

0.16.0  versionCode 1689085543

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's the same issue as described in #3427. It just shows us that not only one specific backup category is affected.
