### ISSUE TITLE
Option to Change the UI icons to FluentUI Icons

### ISSUE THREAD

**Issue by devbytemehedi** [libre-tube/LibreTube#4223]
### Describe your suggested feature

An option to change the ui icon to fluenui icon would be nice.
![Screenshot_2023-07-13-13-37-51-95_cc114bec087609c93733eb02d5393759](https://github.com/libre-tube/LibreTube/assets/89072438/d7775a61-adfe-4c27-a6bb-79e450706d5e)
![Screenshot_2023-07-13-13-38-22-98_cc114bec087609c93733eb02d5393759](https://github.com/libre-tube/LibreTube/assets/89072438/060a8078-b19a-4940-ac74-26b02271c5f3)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by devbytemehedi** [comment]
thats what i like about the fluent Icon design, because its more modern looking.

**Comment by Bnyro** [comment]
We use Material Design icons since they fit the Material 3 design we use.
Customizations like that are out of scope.
