### ISSUE TITLE
Don't store video position for music videos

### ISSUE THREAD

**Issue by terminal-cs** [libre-tube/LibreTube#4227]
### Describe your suggested feature

I know the normal YouTube client does this. Add an option to not store the videos playing position if it is detected as a music video.

I don't know if piped would offer an API to detect this automatically, if not, we could have a popup one time to encourage users to post links of music videos, it may take a while but it could be done.

It's quite infuriating when I want to listen to music and it starts out at the end, since sometimes there are silent areas after videos.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
There's no way we can detect consistently whether a video is a music video or not. In theory we could determine it based on the video's category, but "Music" is used for other videos too that are not music-only.
Would be out of scope anyways.
