### ISSUE TITLE
Channel whitelisting (SponsorBlock)

### ISSUE THREAD

**Issue by ghost** [libre-tube/LibreTube#423]
### Describe your suggested feature

Use the segments button under the player to whitelist a channel.
![Screenshot_20220607-225457](https://user-images.githubusercontent.com/104249296/172460571-dcf190fe-ab37-41e2-a4d3-74891f188bfd.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You already have the possibility to temporary whitelist a video from SponsorBlock by pressing the SponsorBlock button on the top right of the player. I think that's sufficient for viewing the SponsorBlock segments by creators you want to support.
