### ISSUE TITLE
Playlist Sync Issue

### ISSUE THREAD

**Issue by Eliya-Manoj** [libre-tube/LibreTube#4231]
### Steps to reproduce

1. Clone ongoing playlist
2. Wait for new video

### Expected behavior

 Sync latest video content

### Actual behavior

The cloned playlist does not sync with the latest video content

### LibreTube version

0.16.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's what playlist bookmarks exist for. Cloned playlists are only copies of the playlist from the point of time you cloned it.
