### ISSUE TITLE
Buggy Skip Segment Button

### ISSUE THREAD

**Issue by IndusAryan** [libre-tube/LibreTube#4241]
### Steps to reproduce

watch video with sponsors and see skip button

### Expected behavior

smol button with some opaqueness

### Actual behavior

button is overly sized and fully transparent now

### LibreTube version

Lates

### Android version

A13

### Other details

![photo_2023-07-16_21-15-12](https://github.com/libre-tube/LibreTube/assets/125901294/49b2bc7e-61d5-4faf-86c3-0f0bcd4d0daf)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It's not buggy, it's intended to look like that.
Feel free to create a Figma design draft (or a PR with an improved design of the button) if you want to, but there's no reason to consider this a bug.

**Comment by Bnyro** [comment]
Yes, that depends on the screen size.
Since you already have been working on other UI changes previously, you can try to improve its appearance if you want :)
