### ISSUE TITLE
Several bugs that make the app crash

### ISSUE THREAD

**Issue by DanielProg39** [libre-tube/LibreTube#4251]
### Steps to reproduce

I have been having some problems with the app lately. When I watch a video to a certain point, leave the phone for a while and try to resume playback, nothing happens, even a button doesn't turn into a "stop" icon. Also, when I close the video in full-screen mode or select a timestamp from the corresponding list in full-screen mode, the app often crashes. After reopening the app it shows a traceback with java.lang.IndexOutOfBoundsException and other stuff in it. I saved two such tracebacks, but I forgot which one corresponds to which problem, so I can try to reproduce them and paste them in the comments if you want. Another problem is that some videos show -1 dislike (which is cool, but not useful :) ).

### Expected behavior

All functions should work as intended and don't crash the app

### Actual behavior

Sorry for not using the form property, this is given under the "Steps for reproduce" section. It was just more convenient for me to explain everything in one section

### LibreTube version

0.16.0 - 0.16.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please open separate issues with crash logs and/or screen recordings for each bug. That makes it easier to track them.
