### ISSUE TITLE
Add "Shorts" in bottom line, like Youtube

### ISSUE THREAD

**Issue by minou2020** [libre-tube/LibreTube#4252]
### Describe your suggested feature

It should be in the bottom, a button between "Home" and "Subscriptions", and allow to access the shorts

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/3710#issuecomment-1535770561
