### ISSUE TITLE
Dislike button shows "-1" on all videos - Like button still works properly

### ISSUE THREAD

**Issue by minou2020** [libre-tube/LibreTube#4253]
### Steps to reproduce

1- Open a video in LibreTube
2- Look at the like/dislike 

### Expected behavior

It should show the actual number of dislikes

### Actual behavior

It keeps showing "-1" in dislikes on all videos.
The likes number still works properly

### LibreTube version

0.16.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Not LibreTube's fault

**Comment by Bnyro** [comment]
RYD seems to have issues atm.
