### ISSUE TITLE
Allow bookmarking channels

### ISSUE THREAD

**Issue by gbieging** [libre-tube/LibreTube#4254]
### Describe your suggested feature

There are channels whose content I'm only sporadically interested in, and I'd like a way to remember them without subscribing and having their videos showing on the feed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not planned, I dont think that's reasonable to add while you can already subscribe to channels.
