### ISSUE TITLE
Video doesn't play after leaving the phone for a while

### ISSUE THREAD

**Issue by DanielProg39** [libre-tube/LibreTube#4258]
### Steps to reproduce

1. Watch and pause a video at any point
2. Leave the phone and do some other stuff for some (pretty long) time
3. Unlock the phone and tap on "play" button
4. It doesn't make the video play or change the icon, grey chunk that shows loaded part of the video is missing

### Expected behavior

The button should change its icon and the video should resume playing

### Actual behavior

Tapping on the "play" button doesn't make the video play or change the icon, grey chunk that shows loaded part of the video is missing

Screen recording: [link](https://drive.filen.io/d/d4efb4d1-0897-46c4-9194-3c2c47e271cb#XUQM0922prziM7tqGwyouzoV1S03shuI) (GitHub says that the file is too big)

### LibreTube version

0.16.0 - 0.16.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's because Android is freeing RAM in order to save battery, which kills the player.
also see #3794
The recommended work around is to disable all battery restrictions for the app, or if it doesn't work enter the audio mode before leaving the app.
