### ISSUE TITLE
"Continue watching" on the Home screen

### ISSUE THREAD

**Issue by NaN-Sz** [libre-tube/LibreTube#4260]
### Describe your suggested feature

Hello, iwould like to request the addition of a new function to the home screen. "Continue watching" in the content of the home screen, which will show the latest videos that the user has not watched completely. This will help the user to resume viewing from where they left off and remember the videos that were not finished watching, without needing to search for them manually again.

### Other details

Illustrative image
![example](https://github.com/libre-tube/LibreTube/assets/120607988/bfeb5240-a862-4560-b79a-a3e4b2c8468c)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Seems like a very good idea to me!
