### ISSUE TITLE
Screen Brightness Randomly Dims

### ISSUE THREAD

**Issue by Kaarai** [libre-tube/LibreTube#4261]
### Steps to reproduce

1. It happens randomly while either minimizing a video or just while watching a video.

### Expected behavior

My phone should be controlling the brightness, not this app.

### Actual behavior

The app randomly dims my screen.

### LibreTube version

0.16.1

### Android version

Android 13

### Other details

I have a few other complaints, such as constant network errors despite having a 1000 Mbps network connection and the official instance almost aways displaying an error or not loading.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Disable swipe gestures in the player settings.

**Comment by Kaarai** [comment]
Why do I keep getting a "there is something wrong with the selected server" error? Is there something wrong/bugged with the official instances atm?
