### ISSUE TITLE
The YouTube link on LibreTube is different and variable

### ISSUE THREAD

**Issue by Fish25op** [libre-tube/LibreTube#4265]
### Steps to reproduce

1.Copy the video link in LibreTube and search on YouTube
2.No result
3.See the link of that video on YouTube.
4.Different

### Expected behavior

The links must be same and the links must open on YouTube

### Actual behavior

LibreTube:    https://www.youtube.com/watch?v=cA-enQgymC4&t=56

YouTube:      https://youtu.be/cA-enQgymC4

And it's always changing

### LibreTube version

0.16.1

### Android version

Android 12

### Other details

Links are constantly changing in LibreTube. They don't change in YouTube and open in LibreTube

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Both links are valid YouTube links.
We need to use the one with youtube.com since the youtu.be urls don't support timestamps.
Thus, working as intended.

**Comment by Fish25op** [comment]
> Both links are valid YouTube links. We need to use the one with youtube.com since the youtu.be urls don't support timestamps. Thus, working as intended.

I checked. youtube.com link is same as in app
