### ISSUE TITLE
Automatic playback on the homepage

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#427]
### Describe your suggested feature

Automatic playback of videos on the main page. This feature also eliminates preview blur.I think it is possible even if the official Piped project does not support it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Nizami20052022** [comment]
Look at this issue.

**Comment by IceDBorn** [comment]
You are really rude. This is an open source project, you are not paying anyone.

**Comment by Nizami20052022** [comment]
Can't add function?

**Comment by Nizami20052022** [comment]
I think it's up to you whether you want to add or not.

**Comment by Bnyro** [comment]
That's sth I would never want to add because it's just useless...
