### ISSUE TITLE
Incognito mode

### ISSUE THREAD

**Issue by Forrestcalm** [libre-tube/LibreTube#4270]
### Describe your suggested feature

Incognito mode to browse videos without having to delete search and watch history plus not messing up the home page feed. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not planned, all it would do is toggling two or three options at once for you, which is useless for most users.
