### ISSUE TITLE
If System is not selected, the pure black theme is not applied

### ISSUE THREAD

**Issue by Fish25op** [libre-tube/LibreTube#4271]
### Steps to reproduce

1.Choose a dark theme.
2.Open the pure black theme
3.The pure black theme is not applied to home, subscriptions, etc., except for the settings section

### Expected behavior

Apply pure black theme

### Actual behavior

A dark theme is displayed.Not pure

### LibreTube version

0.16.1

### Android version

Android 12

### Other details

https://github.com/libre-tube/LibreTube/assets/136016095/a29fc713-3857-4c2a-aa7e-a5343c69c001

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Restarting the app doesn't resolve it either?

**Comment by Bnyro** [comment]
Seems to be a device side issues.
