### ISSUE TITLE
Media Session ID not unique

### ISSUE THREAD

**Issue by Kaarai** [libre-tube/LibreTube#4272]
### Steps to reproduce

1. Exit the app.
2. Go back into the app.
3. Select the video you were watching. (And are still somehow watching without miniplayer.)

### Expected behavior

Video should show in miniplayer when exiting the app with a video on.

### Actual behavior

No miniplayer, and when you go back to the video in the app, it crashes.

### LibreTube version

0.16.1

### Android version

Android 13

### Other details

Image of the error:
https://imgbox.com/xlzbKtld

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Share a recording or a consistent way to reproduce the error.

**Comment by Kaarai** [comment]
![xlzbKtld_o](https://github.com/libre-tube/LibreTube/assets/139952814/4a56486c-4fdd-4ed3-9352-fe89ea9db2b8)
