### ISSUE TITLE
Did not receive notification for new updates

### ISSUE THREAD

**Issue by DecemberGiraffe** [libre-tube/LibreTube#4273]
### Steps to reproduce

1. Open app

### Expected behavior

Popup notification for a new update when opening app

### Actual behavior

No popup appeared regarding an update to version 0.16.1 and 0.16.1

### LibreTube version

0.15.1 (previously)

### Android version

Android 13

### Other details

I just checked for an update from settings and was surprised to see that there was a new update for 0.16.1 when I was on 0.15.1. That means there were two updates (0.16.0 and 0.16.1) that were missed and I use the app on a daily basis. It's been four days since 0.16.1 was released and two weeks for 0.16.0.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The update checker doesn't run automatically, it's intended that you don't get notified about new updates.
That's mostly due to privacy reasons, if we checked for an update at each app startup we'd always need to connect to the GitHub servers.
