### ISSUE TITLE
player gives up on buffering after a connection time out

### ISSUE THREAD

**Issue by janw4ld** [libre-tube/LibreTube#4280]
### Steps to reproduce

1. play a video
2. disconnect from the internet
3. watch the loaded portion of the video
4. reconnect to the internet

### Expected behavior

LibreTube should detect the reconnection and attempt to load the video automatically, or retry to connect every time the ▶️ button is tapped

### Actual behavior

the play button is stuck on ▶️, and the video doesn't load and has to be closed and reopened

### LibreTube version

0.16.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That pretty much looks like an issue of the player library we're using, we actually don't have much control on when the video is buffering/loading.
