### ISSUE TITLE
Intense stuttering when scrolling to the bottom of a video feed several times

### ISSUE THREAD

**Issue by xlash123** [libre-tube/LibreTube#4282]
### Steps to reproduce

When scrolling through a channel, subscription, playlist, etc. feed, after a few instances scrolling to the bottom of the video feed, the app's performance starts to get worse. This can be seen as stuttering effect as more of the feed is loaded. This also causes the video player to take much longer to go into fullscreen mode while the large feed is in the background. All of these problems go away once the video feed is unloaded (going back to the home page, leaving the channel page, etc.).

Reproduction:
1. Open up your subscription feed or a YouTube channel page with many videos in their library
2. Scroll down to the bottom of the feed
3. Wait for the load
4. Repeat 2-3 about 10 times
5. Select a video to play
6. Go to fullscreen

### Expected behavior

1. Hitting the bottom of the feed will trigger a load, and the app is responsive during the loading time
2. Going into fullscreen occurs quickly

### Actual behavior

1. Each additional feed load takes more time than the previous, and during the loading time, the app is unresponsive
2. Going into fullscreen takes much longer, and the video player appears to be in an odd position for a few seconds

I believe that issue 1 can be partial solved with processing the API request asynchronously or on a separate thread from that of the rendering. That would at least allow the user to keep scrolling through the already loaded feed while the request completes. Not sure why the request is taking as long as it is, but I can understand if there are limitations with Piped.

I have no clue what would cause the weird fullscreen bug, so good luck with that.

### LibreTube version

0.16.1

### Android version

Android 11 (/e/ 1.12.3)

### Other details

A video demonstrating the bug has been published here: https://youtu.be/5DVTMFe0AhI

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
API requests are already done on a separate thread and non-blocking.

**Comment by Bnyro** [comment]
Yes, it seems to be a general issue when rendering large lists.

**Comment by xlash123** [comment]
That would make sense. I also notice that it happens when I pull up my list of subscriptions, which is around 200 channels long.

**Comment by Bnyro** [comment]
I think the issue is that we're loading the images with a higher quality than we actually need, which makes it extremely CPU intensive to render all of them. We could try setting a fixed size as described at https://coil-kt.github.io/coil/getting_started/#preloading, or we wait until Piped supports multiple image qualities and use a lower quality for the result rows.

**Comment by xlash123** [comment]
That does appear to be part of the issue. When I activate data saver mode to prevent loading thumbnails in the feed, the loading is much faster. After scrolling far enough though, the loading starts to become gradually longer. I can understand it if the network request is taking longer, but it's odd that the feed rendering appears blocked while it is adding more to it.

I've tried to look into the code to understand the issue, but I must admit I have almost no Android app development experience 😅, so I don't know how much help I can be in figuring it out.

**Comment by Bnyro** [comment]
For channels and playlists, this was fixed at #5607 thanks to @abGit9, for the subscriptions feed, this is already tracked at #3240.

**Comment by abGit9** [comment]
> For channels and playlists, this was fixed at #5607 thanks to @abGit9, for the subscriptions feed, this is already tracked at #3240.

Thanks!
