### ISSUE TITLE
Videos are logged as watched even when they aren’t played

### ISSUE THREAD

**Issue by hollownights** [libre-tube/LibreTube#4283]
### Steps to reproduce

1) Turn off "Play automatically" in the settings
2) Open a video, but don't play it
3) Look at your watch history and see that the video you just opened is there already

### Expected behavior

Only log a video as watched if it is actually played.

### Actual behavior

I have “Play automatically” turned off in settings, but every time I open a video LibreTube immediately logs the video as watched, which, of course, doesn’t make any sense.

### LibreTube version

0.16.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The watch history keeps track of all videos you have been opening. When you open a video, you saw it "exists", so you're aware of it.
The watch progress (also called position) keeps track of how much you have seen of the video so far, that's likely what you're looking for.
Working as expected.

**Comment by hollownights** [comment]
> The watch history keeps track of all videos you have been opening

Is it supposed to be an watch history or an open history? Opening isn't the same as watching, neither is it the same as playing when you have “Play automatically” turned off. 

> The watch progress (also called position) keeps track of how much you have seen of the video so far, that's likely what you're looking for.

I'm actually bamboozled by this.
