### ISSUE TITLE
Play audio-only downloads in music-player interface

### ISSUE THREAD

**Issue by Sir-Photch** [libre-tube/LibreTube#4285]
### Describe your suggested feature

Currently, audio-only downloads show, well, a black screen during playback with the usual video interface. I suggest changing it to the music player interface.

This will be useful for people only downloading audio of music mixes, etc.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
For that, you can long press the download and select "play in background". Adding a UI for it is not planned currently.
