### ISSUE TITLE
Support for AndroidTV

### ISSUE THREAD

**Issue by xplshn** [libre-tube/LibreTube#4287]
### Describe your suggested feature

The app escalates poorly and does not support the Android TV remote, at least, its convoluted, you have to use a mouse, and the scroll wheel, it is not the best experience.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not planned, see ROADMAP.md or search closed issues.

**Comment by the4anoni** [comment]
@xplshn did you found any better way to use Piped on Android TV?
