### ISSUE TITLE
Better AndroidTV support

### ISSUE THREAD

**Issue by xplshn** [libre-tube/LibreTube#4288]
### Describe your suggested feature

The app escalates poorly and does not support the Android TV remote, at least, its convoluted, you have to use a mouse, and the scroll wheel, it is not the best experience.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Your previous issue was answered and closed, what's the point of opening a new one
https://github.com/libre-tube/LibreTube/issues/4287#issuecomment-1646159142

**Comment by xplshn** [comment]
Sorry, I turned off my phone after sending the first one, but when I turned it on again the send button was still there, I thought it didn't send bc my browser always reloads the page
