### ISSUE TITLE
Video options on the main page.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#429]
### Describe your suggested feature

The options icon in the right corner of the video on the main page.
![Screenshot_20220608-122335_YouTube](https://user-images.githubusercontent.com/104249296/172569571-5d5488af-be4f-4629-a362-f9d9b2a54359.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
it's not

**Comment by Nizami20052022** [comment]
Yes

**Comment by Nizami20052022** [comment]
People don't remember to print the video.

**Comment by Nizami20052022** [comment]
There is no download option between these options.

**Comment by Nizami20052022** [comment]
Take a look here.

**Comment by Bnyro** [comment]
no.

**Comment by Nizami20052022** [comment]
Please add in the download option.
