### ISSUE TITLE
Comment section sometimes shows the same comments from previous loads

### ISSUE THREAD

**Issue by ghost** [libre-tube/LibreTube#4291]
### Steps to reproduce

1. After opening the app, load a page of any video that has a lot of comments
2. Open the comment section
3. Scroll the comment section a few times causing comments to load
4. Issue: comment section sometimes shows the same comments from previous loads

### Expected behavior

Comments that were already shown should be excluded from the next loads of comments

### Actual behavior

Comment section sometimes shows the same comments from previous loads

### LibreTube version

0.16.1

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by salahmak** [comment]
I have noticed that this happens after you open the replies of some comment
