### ISSUE TITLE
Download never finished or sometime it never start

### ISSUE THREAD

**Issue by sombresu** [libre-tube/LibreTube#4295]
### Steps to reproduce

Open app
Open any video
Download

### Expected behavior

Finished downloading

### Actual behavior

Stopped at around 98%. No percentage shows in the app of course.

### LibreTube version

0.16.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Already fixed in debug builds.

**Comment by sombresu** [comment]
Is it available for download?
