### ISSUE TITLE
Button not in the player!

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#430]
### Describe your suggested feature

Button to switch to another video.
![Screenshot_20220608-122456_YouTube](https://user-images.githubusercontent.com/104249296/172572096-8d32f781-7a13-402f-84fc-f3078f8d3f3d.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
that would be part of autoplay
