### ISSUE TITLE
Default WiFi Quality is not working on Some Devices

### ISSUE THREAD

**Issue by IndusAryan** [libre-tube/LibreTube#4300]
### Steps to reproduce

set deafult quality on wifi anything except auto and144p
play some videos

### Expected behavior

quality should be fixed as set by user

### Actual behavior

videos play with 144p even you have set diifferent quality.
tested on 2 stock android phones and a 1 OneUI (ScamSung),all Android13

### LibreTube version

Latest Alpha

### Android version

A13

### Other details

note : i have already tried changing instances ,proxy settings,etc.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Tested with latest debug version and can't reproduce.

**Comment by Bnyro** [comment]
If you change the quality for mobile networks as well, does it apply this one then?

**Comment by akano12** [comment]
Works properly on my Samsung device.
Also what did you mean by the first 2 steps in your report? 
You can't toggle the fallback option if proxy is disabled
