### ISSUE TITLE
F-Driod Repo Error: No files found

### ISSUE THREAD

**Issue by Sarath9087** [libre-tube/LibreTube#4301]
### Steps to reproduce

Add the F-Driod repository from https://libre-tube.github.io/.
After adding you get an error no files found 

### Expected behavior

I should be able to add the repo and use it without any errors on F-Droid. 

### Actual behavior

I get no files found error from Libretube repo for F-Droid.

### LibreTube version

0.16.1

### Android version

Android 10

### Other details

![F-Driod_error](https://github.com/libre-tube/LibreTube/assets/71602995/0160d127-b81d-4042-8f31-ed993ff7a859)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
LibreTube is in the official F-Droid repos, adding it doesn't make any sense.
