### ISSUE TITLE
Revanced feature of mini tablet mode that is disabled by default 

### ISSUE THREAD

**Issue by 6250zed** [libre-tube/LibreTube#4302]
### Describe your suggested feature

Revanced feature of mini tablet mode that is disabled by default is really nice. Libre has this feature (not pip) to click and drag down preview window. Its too small though! Please add mini tablet mode so that when you drag down from preview window (not full screen) it slides down to bottom right of screen taking up about 3/16 of the resolution. 

In addition sharing truncated URL like youtube.be doesn't play nice with other apps whether it be sharing or recipient of video share within android. 

Currently running latest bluestacks on windows, but also android on lineage is using pixel 2 and motor 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not easy to implement, the efforts needed wouldn't be worth the actual benefits. Not planned.
