### ISSUE TITLE
"Download" doesn't really download the video or audio, just stores it internally

### ISSUE THREAD

**Issue by nsteinbach** [libre-tube/LibreTube#4303]
### Steps to reproduce

1. Download a video.
2. Try to use it like any normal file you downloaded, i.e. copy it, move it to your PC or NextCloud, edit it, or anything else you can do with a file in your internal storage.

### Expected behavior

There should be a video file (or, if selected audio download only, then an audio file) in a generally accessible folder in my internal storage/file system, i.e. in the "Download" or "Video" or "Music" directory, or wherever I chose to store the files to.

### Actual behavior

The app stores the video in internal storage only which makes it inaccessible for other apps or further usage by the user, except within the LibreTube app. Which means, it isn't really a downloaded file, or it doesn't have the main properties of such a file (read: liberty, which is even in the name of the app).

### LibreTube version

0.16.1

### Android version

Android 11 (/e/OS 1.12)

### Other details

With user freedom in mind as well as user sovereignty over the data stored on my device, I require the data to be freely accessible and not integrated into an app without the means of extracting it. The app and the data written by it are not one and the same thing. Yes, there might not be a "library of downloaded files", but that's what the actual video storage folder is for, but in a device-wide fashion.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by nsteinbach** [comment]
This might be a feature request, but actually it's such a gigantic flaw in this app, which would be better than NewPipe, were it not for this issie, which basically majes the app kind of useless.

**Comment by Bnyro** [comment]
There are tons of closed issues explaining the reasoning behind this, not planned.

**Comment by nsteinbach** [comment]
Meaning this app is great for privacy, but useless for usefullness. Thanks for nothing then.

**Comment by NickTheOnlyNeko** [comment]
I know that this has been closed 3 Years ago but I just want to say that with Android 12 and above by default apps are with blocked permission for accessing files and what none.

So in my opinion the Developer of LibreTube could've made a button and implement it in the download settings section saying "Change Download Location" followed by a warning that this will require access to Local Files on the device and that the user will have to grant permission and access to the application but I'm just guessing that the Developer is just lazy and doesn't want to be bothered with implementing useful features tho to be fair someone could 100% fork this project and add that feature themselves soo yeah tho on a 3rd note the Dev could be trying to avoid lawsuits from Google/YouTube cause Downloading videos/music is kinda illegal tho at that point why bother adding the download feature in first place... Honestly idk I'm personally having a rough time with understanding the Dev's Logic(if there is any logic to this madness to begin with)
