### ISSUE TITLE
being able to minimize video while it loads

### ISSUE THREAD

**Issue by voidplayer** [libre-tube/LibreTube#4310]
### Describe your suggested feature

Sometimes the video takes a while to load. While the video is loading the interface is completely locked. I cant minimize to look something else while

Maybe force it to always start minimized since i noticed its more often than not that videos takes a while to load (yes i tried many instances)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
What are you talking about?
You can swipe down the player and the video will be minimized.

**Comment by voidplayer** [comment]
i click the thumbnail of a video on any of the tabs, the video goes full screen with the loading circle. Swipe down doesnt work until the video starts playing

**Comment by akano12** [comment]
> i click the thumbnail of a video on any of the tabs, the video goes full screen with the loading circle. Swipe down doesnt work until the video starts playing

In case i understood you properly, what you're saying was a bug that was fixed in nightly builds [this](https://github.com/libre-tube/LibreTube/pull/4296#issuecomment-1647903826), download the latest debug if you're using the debug.

**Comment by voidplayer** [comment]
Nice, Thank you!

Sorry to bother you then!
