### ISSUE TITLE
Add folders for playlists on Library tab

### ISSUE THREAD

**Issue by DecemberGiraffe** [libre-tube/LibreTube#4332]
### Describe your suggested feature

On the Library tab, allow user to create folders to drag and drop playlists into.
For example, a folder for 'Sports' can include the 'baseball' and 'basketball' playlists.

I did see some people suggest folders for downloads and subscriptions which were rejected because it was not possible to be implemented, so not sure if it's the same case here.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
This would be possible in theory, however not planned for the following reason:
1. This would require some major rewrites of our playlist logic
2. Piped doesn't support it, so it would only work without account. We generally try to keep the usage with and without account as similar and feature-equal as possible.
3. I don't see the purpose of doing this. Playlists are used for categorizing videos, but why would you want to categorize your category system (=playlists) once again?

**Comment by luckkmaxx** [comment]
That would be usefull for me.
Anyway, I just want to suggest to order and categorize your playlist using the order by name, and playing with it, naming playlists:
[COOKING] Dinner
[COOKING] Dessert
[DOCUMENTARIES] Animal
[DOCUMENTARIES] Space
[MUSIC] Artist 1
[MUSIC] Artist 2
[TV SHOWS] Program 1
....
