### ISSUE TITLE
Add option to copy download link of the video

### ISSUE THREAD

**Issue by Justauser0** [libre-tube/LibreTube#4335]
### Describe your suggested feature

Add option to copy download link of the video

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Gamer750** [comment]
I also support for this feature

**Comment by Gamer750** [comment]
It would be easy to play video in vlc or in some other video player

**Comment by Bnyro** [comment]
Long press the share button for opening via 3rd party video players.

**Comment by Bnyro** [comment]
Not that one, the one in the options row that appears after clicking on a video.

**Comment by Gamer750** [comment]
Explain via screen short or screen recording

**Comment by Gamer750** [comment]
Is there any option to copy that link

**Comment by Gamer750** [comment]
> Not that one, the one in the options row that appears after clicking on a video.

None of the popular video player like MPV vlc

**Comment by Gamer750** [comment]
> Not that one, the one in the options row that appears after clicking on a video.

None of the popular video player like MPV next player does not support that link
