### ISSUE TITLE
Buffer the audio stream

### ISSUE THREAD

**Issue by fw190d13** [libre-tube/LibreTube#4336]
### Describe your suggested feature

We can set up the video max buffer to a given number of seconds. There is no such setting for audio. Recently I was traveling by train and go mixed network coverage and the audio got interrupted. Even for longer videos on YouTube the audio file is around 30mb so a bigger buffer for audio would be handy and it wouldn't take much time to be conducted.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The buffering goal preference applies for both, the audio and video stream.
