### ISSUE TITLE
Add the app to the Accrescent store

### ISSUE THREAD

**Issue by rsssxd** [libre-tube/LibreTube#4343]
### Describe your suggested feature

Safer app upload platform for users

### Other details

The Accrescent app store is an open source app store developed for ultimate security and privacy

https://accrescent.app/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/issues/2756#issuecomment-1396055836
