### ISSUE TITLE
Allow import playlist from newpipe

### ISSUE THREAD

**Issue by GreenGhostForever** [libre-tube/LibreTube#4345]
### Describe your suggested feature

**issues description**
currently libre allow user to import playlist from piped / libretube / YouTube
but i hope dev now consider to add support from newpipe completely

reason:
i want to migrate from newpipe

### Other details
example file:
[Example Newpipe.zip](https://github.com/libre-tube/LibreTube/files/12224672/Example.Newpipe.zip)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's a database file and therefore not possible to import.
