### ISSUE TITLE
Add button to clear queue

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#4347]
### Describe your suggested feature

The idea is to:
1. Only play a video from a playlist that maybe is not meant to be played at once
2. Or create a new queue from a few videos from current and other playlists. 
When nothing is playing you need to start adding the first item to queue. If you just tap it to play, all items from playlist will be added to queue. "Add to queue" option is only avaliable when something is playing.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Not sure if i understood you properly but can't you just play the video and disable autoplay or set repeat to current video?

**Comment by luckkmaxx** [comment]
> Not sure if i understood you properly but can't you just play the video and disable autoplay or set repeat to current video?

Yes, thats fine for point (1.) but not for second escenario, where you need to play an item with a clean queue.

**Comment by Bnyro** [comment]
The expected behavior for most users is that starting a video in a playlist will also start the playlist.
Nevertheless you can just clear the queue after you started the video, so that I really don't see a need for inplenting that.

**Comment by luckkmaxx** [comment]
"Clear the queue after ypu started the video" sounds great! if I had a "Clear queue" option. Because I dont want to swipe away one by one whe there are dozens or hundreed of videos listed.

**Comment by Bnyro** [comment]
Oh damn, I forgot we had removed the button for it :/

**Comment by luckkmaxx** [comment]
Agree
