### ISSUE TITLE
Ability to sort playing queue by params such as view count, upload date, ...

### ISSUE THREAD

**Issue by TK-NC** [libre-tube/LibreTube#4348]
### Describe your suggested feature

Hello!

I tought of two features that could improve queue functionality:

1. Queue sorting (sort by video length, release date...)
2. Queue saving (save to playlist)

### Other details

1. Queue sorting: sometimes I manualy sort my queues based on video topic, length and release date, so sorting by one of these options would be helpful, though I'd still like to be able to sort it manually (for example, sorting a queue with some random videos and a two part video by length could cause the latter to not play in sequence).
2. Queue saving: I've seen this mentioned in other issues as a form of crash protection, but besides that you could also use it to quickly make a music playlist or save the queue if you need to restart the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TK-NC** [comment]
Sorry, seems like saving queues as playlists is already a feature ;(

**Comment by TK-NC** [comment]
To make the title not misleading, there's another issue I have with queues: when adding a video to the queue and switching apps / tabs, the menu reappears, and it can also stack depending on how many videos you added. I could record a video if you can't reproduce the bug.

**Comment by Bnyro** [comment]
2.: it's already possible to save the current queue to a playlist, so I don't see any need for improvements here.
1.: I don't really get the point, why would it make sense to sort your playing queue by the video duration? Sorting by upload date makes a little bit sense, but I'm certain there's not much of a general interest in having such a feature.

**Comment by luckkmaxx** [comment]
queues can be manually ordered long pressing the six dots at right of each item.

**Comment by luckkmaxx** [comment]
By duration: maybe if you play a channel playlist, where you want to play first longer videos avoiding shorts, or vice-versa.

By number of views: same situation of above, trying to see first the most viewed videos from that playlist.

By uploader: when you have your own playlist.

I dont know if some of this order criteria could be implemented in playlist and feed too.

**Comment by Bnyro** [comment]
I decided to implement the 3 following sort options:
- view count
- uploader name
- upload date
Selecting one of these will reorder the whole queue, however new added videos to it will still appear at the bottom (until you use the sort option again).

The reverse options won't be available, since we already have a control to reverse the queue.
