### ISSUE TITLE
Play Button doesn't work after coming from Home Screen

### ISSUE THREAD

**Issue by SJTheGreat06** [libre-tube/LibreTube#435]
### Steps to reproduce

1. When I start playing the video
2. I stop the video with play button and exit the Application and come to Home. 
3. I go back to LibreTube to play the very same video that I paused. 
4. I just see a blank screen and the Play Button don't work no matter how much you press it or how harder.
5. It will only work after you exit the Application and play the video again right from starting.

### Expected behavior

After coming to LibreTube from Home, The Play Button should work instantly.

### Actual behavior

It don't work and I see a Blank Screen.

### LibreTube version

0.3.0

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Fixed in 0.3.1, please update the app
