### ISSUE TITLE
Remember the time where the Video was at the time i stoped watching.

### ISSUE THREAD

**Issue by HageFale** [libre-tube/LibreTube#4350]
### Describe your suggested feature

I watch a long Video i stop watching for any reason then i want to watch futher and i need to find out where i was i the Video at what time have i stoped watching? I dont can remember every Video i watched at where i stoped watching please make a simple script that noitices the current time and then export that value if the ram get cleaned yk? please do that would be very nice i thank yog already

### Other details

Remember your time where you at in the Video best feautre every please add.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by amogusussy** [comment]
That's already a feature.

- Go to settings
- Click history
- Enable watch history
- Click 'Remember Position' and select 'always'.
