### ISSUE TITLE
Can't visit Muse India YouTube channel

### ISSUE THREAD

**Issue by Gamer750** [libre-tube/LibreTube#4352]
### Steps to reproduce

https://piped.video/channel/UCYYhAzgWuxPauRXdPpLAX3Q

https://www.youtube.com/channel/UCYYhAzgWuxPauRXdPpLAX3Q

### Expected behavior

Not loading videos

### Actual behavior

Not loading videos

### LibreTube version

0.16.1

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not a client side issue obviously.
