### ISSUE TITLE
Disable Home tab completely

### ISSUE THREAD

**Issue by shuvashish76** [libre-tube/LibreTube#4359]
### Steps to reproduce

1. Settings > Appearance > Order
2. Navigation bar > Untick "Home"

### Expected behavior

It shouldn't appear in my list, I don't wanna watch home 1st as I always watch the "Subscriptions".

### Actual behavior

Yes its disabled from my Navigation bar but everytime I reopen LibreTube it shows me the Home Tab.

### LibreTube version

0.16.1

### Android version

12

### Other details

I understand disabling from Navigation bar doesn't affect it, there should be an extra option to disable home. Disabling all "Home tab content" makes no difference, on restart it shows me an empty page.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's already possible, see https://github.com/libre-tube/LibreTube/issues/3121#issuecomment-1435989424.
