### ISSUE TITLE
Show subscribed channels count in subcriptions tab

### ISSUE THREAD

**Issue by Gamer750** [libre-tube/LibreTube#4361]
### Describe your suggested feature

![IMG_20230804_143144](https://github.com/libre-tube/LibreTube/assets/141329708/158133f3-bc36-4aa8-8d87-3b3fe667e9ab)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by shuvashish76** [comment]
+1
Additionally show total channel numbers for each groups. (just link NewPipe)

**Comment by Bnyro** [comment]
We currently load the subscriptions when you open the feed, only when you manually switch to them.
Therefore I don't see how this should work out well when using an account? Obviously, fetching the subscriptions without them being needed, would be a waste of resources.

**Comment by Bnyro** [comment]
I agree with @xIUPITERx here

**Comment by Bnyro** [comment]
True, good point.
