### ISSUE TITLE
Chapters dialog redesign

### ISSUE THREAD

**Issue by tvnmguy** [libre-tube/LibreTube#4362]
### Describe your suggested feature

![session-2023-08-04-143531](https://github.com/libre-tube/LibreTube/assets/116799295/87df1826-afed-4641-b910-1088c7c754f4)

•Pay button & Loop button for each chapters (Changing Play button into Loop button when tapping on the play button).

https://github.com/libre-tube/LibreTube/assets/116799295/12bbfa18-15e1-48af-a0ae-a59ff37766d0

•Press and hold on a chapter to share the chapter.

https://github.com/libre-tube/LibreTube/assets/116799295/c1d94abc-7d9f-4fda-af69-052e28d6ec9e

### Other details

Inspired from AntennaPod (Open Source podcast app) & NewPipe

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Gamer750** [comment]
It would be good

**Comment by Bnyro** [comment]
I guess the idea would be to remove the chapters section in the video description and replace the current chapters dialog with the new design?
