### ISSUE TITLE
Videos can't be downloaded properly

### ISSUE THREAD

**Issue by minou2020** [libre-tube/LibreTube#4364]
### Steps to reproduce

1. Open LibreTube
2. Select any video and click download
3. The download will stop progessing when close to the end, resulting in something unusable

### Expected behavior

The download should finish and be downloaded properly

### Actual behavior

The download stops progressing after being close to "the end" and the video can't be viewed offline...

### LibreTube version

0.16.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
I believe that -at least in my case- the download indicator isn't refreshed properly, my downloads always hang on X mb/ X mb and i can't open them even though they're completely downloaded. I usually hit back button and open downloads page again and everything seems to be fine.

**Comment by Bnyro** [comment]
Yes, that's only a visual issue in the notifications

**Comment by DOX007** [comment]
Extremely slow download. My fiber internet download a 1 GB in 1 minute. However into this app it takes me 6.2 hours to download 162 meg. Is there a setting I missed?. I have tested all Instances, without any change in the download speed.
