### ISSUE TITLE
Screen lock features/fixes

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#4375]
### Describe your suggested feature

Lock button not only should lock controls.
1. When you have auto-rotation enabled, the locked screen will exit to normal mode if you hand your phone in portrait. So you can do anything but touch video controls.
2. The statusbar also shouldnt be shown when locker. But it can only be hidden, but not disabled AFAIK due to Android limitations.

The idea is to make the lock screen option more kids-proof.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Concerning 1.: I don't think rotating the phone should unlock the player. Since you can lock the player in fullscreen and in normal portrait mode, it would likely be inconvenient, since the expected behavior is to remember preferences, even when the screen rotates.
