### ISSUE TITLE
fullscreen button displaces in video without chapters.

### ISSUE THREAD

**Issue by IndusAryan** [libre-tube/LibreTube#4376]
### Steps to reproduce

watch video that doesnt have any timestamp or chapter and see fullscreen button 

### Expected behavior

fullscreen button should remain in right side

### Actual behavior

it attachs itself to the timebar on left side

### LibreTube version

Latest Alpha

### Android version

A13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Ss?

**Comment by akano12** [comment]
![th-3437694984.jpg](https://github.com/libre-tube/LibreTube/assets/50032603/a3b23588-d7f3-460d-8a1a-4992b84a0545)
