### ISSUE TITLE
Suscription count need a fix

### ISSUE THREAD

**Issue by Unaiperezdiaz** [libre-tube/LibreTube#4385]
### Steps to reproduce

https://github.com/libre-tube/LibreTube/assets/49728036/4165f60b-c764-49a6-8692-6ada74a99de1

### Expected behavior

Count working

### Actual behavior

Look the video ando test It.

### LibreTube version

Last debug Libretube

### Android version

13

### Other details

Test on a Realme GT Master Edition 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/issues/4361#issuecomment-1666482965

Works as intended
