### ISSUE TITLE
Videos skip seconds or fast forward during playback

### ISSUE THREAD

**Issue by NearestWater262** [libre-tube/LibreTube#4389]
### Steps to reproduce

Play any video for a while

### Expected behavior

Should play at a normal speed

### Actual behavior

It's a bit difficult to be explain. When the video is playing, often it will feel like it is fast forwarding or skipping seconds of time, every other second. It will do this off and on.

### LibreTube version

0.16.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Maybe sponsorblock is set to auto skip all reported segments?

**Comment by Bnyro** [comment]
play a video -> click the arrow at the top right -> playback speed -> disable "skip silence"

**Comment by NearestWater262** [comment]
@Bnyro thank you
