### ISSUE TITLE
Chance to Play or Resume the video(s)

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#4391]
### Describe your suggested feature

This is mostly relevant for music, but also for any video you dont want to continue by default.
Maybe a simple pupup with [PLAY] [RESUME] when the video is half watched.

Yes, I could mark as watched/not watched before play it, but then I have to be aware of it.

In case of playlist, somtimes you want to play all from the begining without resuming any video. I dont know how could this be managed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't think that would be really user friendly and convenient.

Usually if listening to music, you listen until the end of the video, which causes LibreTube to automatically start playing from the beginning the next time when the video is being opened.

As always, we should keep things simple and not overcomplicate them.
