### ISSUE TITLE
Hide group name.

### ISSUE THREAD

**Issue by rozari0** [libre-tube/LibreTube#4399]
### Describe your suggested feature

Hide the group name if there isn't any group. Only the *All* group looks unnecessary. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That way the `edit` button (which is for editing or creating channel groups) wouldn't be self-explaining to users.
Hence, I don't plan to do this.
