### ISSUE TITLE
Nothing happens when I click on login/register

### ISSUE THREAD

**Issue by CasuallyOrange** [libre-tube/LibreTube#44]

**Comment by rimthekid** [comment]
It should show a dialog you can't see it?

**Comment by rimthekid** [comment]
Can I know your android version?

**Comment by felipemaranda** [comment]
I have the same problem. I just installed the apk and when I try to login, I'm able to input my username and password but nothing happens when I touch the login button. It's like the button have no action. I'm using the app on /e/OS, a privacy friendly Android alternative build based on LineageOS/Pie.

**Comment by rimthekid** [comment]
Did you tried to change the instance? see if other instances works.

**Comment by CasuallyOrange** [comment]
> Can I know your android version?

Android 9 pie

**Comment by CasuallyOrange** [comment]
> It should show a dialog you can't see it?

No it doesn't show anything

**Comment by CasuallyOrange** [comment]
> Did you tried to change the instance? see if other instances works.

I changed to silkky.cloud and it worked

**Comment by CasuallyOrange** [comment]
Maybe you can add something saying "if login/register doesn't work try changing the instance" to the login page

**Comment by rimthekid** [comment]
Are you logged in now?

**Comment by FireMasterK** [comment]
There's been a server issue with the main instance, I'm working on trying to profile some SQL queries to find the cause.

**Comment by CasuallyOrange** [comment]
> Are you logged in now?

Yes

**Comment by felipemaranda** [comment]
I'm also logged in on main instance now. Thanks!

**Comment by martin-desktops** [comment]
I had been using the app for a couple days, but today home, subscriptions page and login stopped working on the main instance.

**Comment by rimthekid** [comment]
What about other instances?

**Comment by martin-desktops** [comment]
> What about other instances?

Other instances work flawlessly

**Comment by rimthekid** [comment]
The main instance has way too many users and @FireMasterK is a bit busy at the moment.

**Comment by martin-desktops** [comment]
> The main instance has way too many users and @FireMasterK is a bit busy at the moment.

Oh, I understand. Fortunately open source provides interoperability so switching to an other instance isn't a problem ^^
