### ISSUE TITLE
video upload time and views in playlist and bookmark

### ISSUE THREAD

**Issue by Eliya-Manoj** [libre-tube/LibreTube#4401]
### Describe your suggested feature

Feature that shows video upload time and views in playlist and bookmark. This is very useful for the ongoing playlist.

### Other details

 Almost like this
Before
![6237765975793579777_121](https://github.com/libre-tube/LibreTube/assets/90308888/279d45d8-ed0d-4c94-b3da-2e6d9724a251)
After
![6237765975793579778_121](https://github.com/libre-tube/LibreTube/assets/90308888/582d288e-c4e6-4c1e-8e8c-2196121dd2f0)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Unfortunately, that's not supported by the API.
