### ISSUE TITLE
The video always stops

### ISSUE THREAD

**Issue by Unaiperezdiaz** [libre-tube/LibreTube#4403]
### Steps to reproduce

https://github.com/libre-tube/LibreTube/assets/49728036/74d2902d-b481-4dd2-9a40-138085554339

I have tried at least 5 times opening the same video, and it always stops at second 29 with the kavin.rocks instance (official), I think that when the instance option disappears (when the chosen instance does not appear) the video playback is blocked.
I have no idea honestly if this is part of the problem of video playback, but although it seems strange to me this is a possible clue to this problem.

### Expected behavior

The video stops more than 3 times in a row (with WIFI)

### Actual behavior

No problems

### LibreTube version

0.16.1

### Android version

Android 13

### Other details

Realme GT Master Edition

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Have you tested it in the browser on piped.video?

**Comment by Unaiperezdiaz** [comment]
No but I will try it

**Comment by Unaiperezdiaz** [comment]
Works without problems, any ideas?

**Comment by Bnyro** [comment]
Try `Settings -> Audio and video -> Use HLS`.
Do you have the Piped proxy disabled?

**Comment by Unaiperezdiaz** [comment]
The proxy was enabled when I recorded and without using HLS, now testing with the new settings.

Now testing with HLS active and proxy disabled, no problems (so far).

**Comment by Bnyro** [comment]
That's an issue with the `ExoPlayer` apparently, which we're using for video playback. 
You can try clearing the cache and see if that changes anything, otherwise just use any of the methods I described above.

**Comment by Unaiperezdiaz** [comment]
I have tried clearing the cache, (testing with the described configuration, it does not seem to give problems).)
