### ISSUE TITLE
allow to bookmark youtube playlist or sync with the one added on piped

### ISSUE THREAD

**Issue by ChuckBartowski91** [libre-tube/LibreTube#4404]
### Describe your suggested feature

Hello, as the piped/libretube playlist are synced would be great if it can do that with the bookmarks too or just allow to "subscribe" to the playlist instead of cloning it, thanks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Needs to be supported at Piped's side first - there's already an open issue for it.
