### ISSUE TITLE
 The same page opens again when you double-click the buttons in the application

### ISSUE THREAD

**Issue by Qaz-6** [libre-tube/LibreTube#4406]
### Steps to reproduce

1.Title.
2.The same page opened again.

### Expected behavior

Preventing this problem

### Actual behavior

https://github.com/libre-tube/LibreTube/assets/140435478/b24243cc-f7f6-472c-94a0-a1e60d773b7c

### LibreTube version

0.16.1 Debug

### Android version

12

### Other details

Not a priority, but a problem.🐞
The latest stable version has this problem.There may be a delay.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not reproducible and since nobody else reported a similar issue, it appears to be a device side problem.

**Comment by Qaz-6** [comment]
Tested on 3 devices.

**Comment by Qaz-6** [comment]
Click twice quickly without pulling your hand

**Comment by Bnyro** [comment]
Don't double click then, that's not my fault.
