### ISSUE TITLE
Import NewPipe Playlists

### ISSUE THREAD

**Issue by qfjp** [libre-tube/LibreTube#4408]
### Describe your suggested feature

NewPipe playlists can be imported using information obtained from the sqlite database, parsed into the json format of an already built parser. Simple pseudocode is provided in two steps:
```sql
SELECT name, url, FROM playlists JOIN (SELECT * FROM playlist_stream_join JOIN streams ON id=stream_id) ON playlists.uid = playlist_id ORDER BY name;
-- Other potentially useful fields: title, uploader, upload_date 
```
```python
# This will generate a json string in the "FreeTube" format.
#
# play_dict is a dictionary of the form
# { "playlist": ["vid1", "vid2", ...]
yb_prefix = "https://www.youtube.com/watch?v="
obj_list = []
for key in play_dict.keys():
    vid_list = []
    for val in play_dict[key]:
        vid_dict = {
              "videoId": val[len(yb_prefix):],
              "title": key,
              "author": "",
              "authorId": ""
        }
        vid_list.append(vid_dict)
    playlist_obj = {
        "playlistName": key,
        "videos": vid_list
    }
    obj_list.append(playlist_obj)
print(str(obj_list).replace("'", '"')
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's out of scope for the project. You can convert them to the Piped playlist format using Python and then import them to LibreTube.
