### ISSUE TITLE
The language does not change at all.

### ISSUE THREAD

**Issue by Qaz-6** [libre-tube/LibreTube#4412]
### Steps to reproduce

1.Set the language to Turkish.
2.The application displays some string in English, some in the system language.

### Expected behavior

Show the selected language completely.

### Actual behavior

Title

### LibreTube version

0.16.1 Debug

### Android version

12

### Other details

This is entirely the fault of the application. There was a similar issue in another project

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Device side issue.
