### ISSUE TITLE
Change icon to open video player settings

### ISSUE THREAD

**Issue by x-0D** [libre-tube/LibreTube#4413]
### Steps to reproduce

Open any video in fullscreen. Tap minimize.

### Expected behavior

Minimize button for minimize, video settings for settings.

### Actual behavior

![Screenshot_2023-08-09-12-16-35-996_com github libretube](https://github.com/libre-tube/LibreTube/assets/87000516/14062991-dac0-4027-b4ef-9e928580b4a1)

![Screenshot_2023-08-09-12-16-40-887_com github libretube](https://github.com/libre-tube/LibreTube/assets/87000516/3eaac342-0986-4519-b62b-23a0e0272558)

### LibreTube version

0.16.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
What's the issue here?

**Comment by x-0D** [comment]
> What's the issue here?

Misunderstanding of icon meaning. Icon that looks like "minimize" actually not minimizing video, it open settings. Suggest to replace iconography to settings gear for avoid user misunderstanding.
