### ISSUE TITLE
Chapter UI Scrolling Bug

### ISSUE THREAD

**Issue by justTOBBI** [libre-tube/LibreTube#4427]
### Steps to reproduce

1. Open a video with many chapters.
2. Select a chapter to skip to the time
3. While still in the chapter selection, scroll up and down

### Expected behavior

The selected chapter should be highlighted

### Actual behavior

Due to android thingies (I suppose the state of the recycler view and the position of the selected item beeing rebuild) some random chapters are getting highlighted.

### LibreTube version

0.16.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That has been resolved in the debug builds by the chapters redesign in https://github.com/libre-tube/LibreTube/pull/4372 :)

**Comment by justTOBBI** [comment]
Oh, that explains why I didn't find any active Issue on this. Thanks for fixing and love from Dresden :)

**Comment by Bnyro** [comment]
You're welcome from Stuttgart ;)
