### ISSUE TITLE
Sometimes clicking on comments opens the wrong replies

### ISSUE THREAD

**Issue by salahmak** [libre-tube/LibreTube#4428]
### Steps to reproduce

1. Open the comments section of a video
2. Scroll down few pages
3. Open few comments' replies and notice the content of the parent comment and its author
4. After opening the replies, the wrong comment/author is shown
5. After clicking the "back" button, it will show that the comment you originally clicked on doesn't have any replies

Here is a recorded video to show the issue:

https://github.com/libre-tube/LibreTube/assets/49586511/bcb36ca5-348a-4587-bc7a-f9338d71f45a

### Expected behavior

Show the replies of the comment I clicked

### Actual behavior

Shows the replies of another comment

### LibreTube version

0.14.1, also in Master branch

### Android version

Android 13

### Other details

I'm still not familiar enough with Kotlin and the codebase of the project to figure out why this is happening. I also suspect this has to do with #3676 and #4291 (I did fix #4291 using some workaround but I still suspect that this is the cause somehow).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by malik0011** [comment]
Hi @Bnyro, can you assign this to me? I'd like to work on it. I understand the issue and have already worked on this type of issue previously related to recycleView. Will create a PR for this.

**Comment by Bnyro** [comment]
Sure, assigned you :+1:

**Comment by malik0011** [comment]
@Bnyro have created a PR for this issue. can you please check that PR.
