### ISSUE TITLE
Channel Videos Sort By

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#443]
### Describe your suggested feature

How to sort channel videos.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.
![Screenshot_20220609-151056](https://user-images.githubusercontent.com/104249296/172834173-39f0e9d6-a226-41a5-9af9-12696cab778d.jpg)
![Screenshot_20220609-151247_LibreTube](https://user-images.githubusercontent.com/104249296/172834180-0dc6f966-ed0f-43ea-9dc5-69fa5c8f0ceb.jpg)

**Comment by Bnyro** [comment]
not api supported
