### ISSUE TITLE
Instance.question

### ISSUE THREAD

**Issue by Jiaonikele8** [libre-tube/LibreTube#4435]
### Steps to reproduce

Hello why these. Instance. cannot be used
![Screenshot_2023-08-13-04-51-37-04_54f92cd6866f5233ab0db4392b806878](https://github.com/libre-tube/LibreTube/assets/122111118/4fae87ca-f39e-4b53-8d6f-aca78226ec47)
![Screenshot_2023-08-13-04-56-41-07_54f92cd6866f5233ab0db4392b806878](https://github.com/libre-tube/LibreTube/assets/122111118/de021654-f709-4e0b-ac5f-e9f95a0663e1)

### Expected behavior

have no way...

### Actual behavior

Since the beginning of July......

### LibreTube version

0.16.1

### Android version

android13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not a LibreTube issue. I assume the country you lice in blocks the IPs of Piper's servers.

**Comment by Jiaonikele8** [comment]
Will the later version be improved?
