### ISSUE TITLE
[Unresponsive controls + 4:3 stretched] when switching from audio to video mode

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#4436]
### Steps to reproduce

1. Play the following video and set audio mode: https://piped.video/watch?v=djV11Xbc914
2. go to video mode again.
3. The controls in video are unresponsive
4. the video wich has 4:3 ratio is stretched to full width
5. swipe down a little to move the player
6. the video changes to 4:3 
7. the screen controls are working again

Some others 4:3 videos like this: https://piped.video/watch?v=r0qBaBb1Y-U has the touch bug, but the aspect ratio is kept as 4:3

### Expected behavior

1. video in 4:3 not be streched when switching from audio to video mode
2. the controls should work

### Actual behavior

Explained.
I dont know if there are 2 different bugs to report, but appears in the same action at same time.

### LibreTube version

0.16.1 debug

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Recording?

**Comment by luckkmaxx** [comment]
Here
https://mega.nz/file/pIhHTAYC#JR3Lck6uF8O-clKamfchP40OUeXAg5AwweVeinIGs30

**Comment by luckkmaxx** [comment]
I found that the controls arent shown with others than 4:3 ratio.

**Comment by Bnyro** [comment]
Your uploaded video is not playable for me unfortunately.

**Comment by luckkmaxx** [comment]
> Your uploaded video is not playable for me unfortunately.

do you prefer gdrive?

**Comment by Bnyro** [comment]
No, I don't use Google links without Tor. Could you please try to minimize or cut the video and then upload it here on GitHub.
For minimizing, I can recommend using [Handbrake](https://handbrake.fr/). The resolution is not that important as long as it's possible to see what's happening, so 360px is sufficient.

**Comment by luckkmaxx** [comment]
https://github.com/libre-tube/LibreTube/assets/14180594/dd2bf682-3194-4227-97a9-ea6433c8ceab

**Comment by Bnyro** [comment]
Perfect, thanks!
That seems like the first time we have a proper recording of  #4161, and a way to reproduce it!
Could you please send the video in #4161 and close this issue then?

**Comment by luckkmaxx** [comment]
of course
