### ISSUE TITLE
Refresh after removing bookmark

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#4437]
### Describe your suggested feature

Refresh after removing bookmark in library view
Now if you remove some, doesnt disapear until switching tabs.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's intended. When you accidentally remove one, you still have the possibility to bookmark it again, since there's no confirmation prompt when removing a bookmark. However, it's visually indicated that the bookmark is removed.
