### ISSUE TITLE
Create a dummy playlist/bookmark while is being imported for large playlists.

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#4438]
### Describe your suggested feature

If there are many videos, cloning and bookmarking takes much time. This can be interpreted as a self fail when tring to create the playlist or bookmark and makes to try again.
A dummy playlist with a progress bar o simply an "importing" advice would be very usefull.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not easy to implement and I don't consider this useful for the average user. Apart from that since the progress is running on different threads, there's no way to tell the current progress.

**Comment by luckkmaxx** [comment]
Ok I will give you an easy alternative: A toast message confirming the actions.

**Comment by Bnyro** [comment]
There's already a toast when the cloning progress is done - and the bookmarking process only takes milliseconds, since it's only saving playlist info, and not video info.

**Comment by luckkmaxx** [comment]
Yes, there is a toas for when its done, but not for "Playlist is being cloned...", what is the info the user should get for long processes.

In the other hand, while I was testing the toast, I noticed that playlist with shorts (only shorts, at least) cant be cloned, and it shows a toast saying "There is a problem with the server. Try another instance".
Maybe I should open a new issue.

**Comment by Bnyro** [comment]
With or without account?

**Comment by luckkmaxx** [comment]
> With or without account?

with account

**Comment by Bnyro** [comment]
Then you should open an issue at Piped.

**Comment by luckkmaxx** [comment]
Without account, and official instance, the playlist is cloned empty
