### ISSUE TITLE
Group feed notifications

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#4439]
### Describe your suggested feature

Notifications remains independent and do not group in only one stack.

### Other details

![IMG_20230813_023556](https://github.com/libre-tube/LibreTube/assets/14180594/7f08d161-70f2-4ca9-8a85-4c639dde0b86)
![IMG_20230813_023440](https://github.com/libre-tube/LibreTube/assets/14180594/d046b7dc-5a5c-47c9-b70f-b3fbb52389c8)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Notifications by the same uploader are being grouped already.
