### ISSUE TITLE
Bookmarked youtube playlists don't see their content updated

### ISSUE THREAD

**Issue by Mrcubix** [libre-tube/LibreTube#4441]
### Steps to reproduce

1. Create a playlist on youtube
2. Add some videos to that playlist
3. Open that playlist in libretube
4. Add videos to that playlist on youtube again
5. Playlist cannot be updated manually, nor is it done automatically,
6. Remove bookmark from libretube,
7. Re-Open the playlist on libretube
8. The playlist still has not updated

### Expected behavior

Allow users to manually update content of bookmarked playlist

### Actual behavior

As it is right now, bookmarks is just another duplicate playlist button

### LibreTube version

0.16.1

### Android version

Android 7.1.2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's what the `Clone playlist` feature exists for.

**Comment by Mrcubix** [comment]
There are multiple issues with your statement,

1. Cloning implies a 1 time copy of something
2. When you bookmark something, you can come back to the bookmarked content, which may have updated
3. It still does not update when i add a video

**Comment by Bnyro** [comment]
That's likely just due to server side caching.

**Comment by Mrcubix** [comment]
Guess that server caching only cache for libretube then cause others handle it properly

**Comment by Bnyro** [comment]
You can try to clear the app cache or just wait until the server side caching is done. You probably don't understand LibreTube's architecture, so you should inform yourself about it first before claiming any virtual issues.
