### ISSUE TITLE
Trim spaces from search inputs

### ISSUE THREAD

**Issue by tsiflimagas** [libre-tube/LibreTube#4445]
### Describe your suggested feature

Trim trailing and preceding spaces from search inputs

### Other details

I think there's no reason to keep those extraneous spaces which can lead to, essentially, duplicated entries.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I'd agree on that for the search history, but not for searching in general. So I think we should only trim search history entries.
