### ISSUE TITLE
Sponsorblock segment options keep resetting to their default values

### ISSUE THREAD

**Issue by matchboxbananasynergy** [libre-tube/LibreTube#4450]
### Steps to reproduce

1. Open LibreTube
2. Go to Settings
3. Go to Sponsorblock
4. Scroll down and change the default value of a specific segment (i.e. Music: Non-Music Section) from "Off" to anything else.
5. Scroll up so that this segment is no longer in sight at all
6. Scroll back down to see the setting
7. Observe that the value has been reset to "Off"

### Expected behavior

The setting should remain as the one it's been changed to, not reset.

### Actual behavior

The setting keeps resetting to "Off" or "Automatic" for Sponsor and Unpaid/Self Promotion. Essentially, they keep resetting to their default value

### LibreTube version

0.17.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's a bit unlucky, not sure yet what it's caused by.
Nevertheless I don't think it's serious enough to require a hotfix release.
