### ISSUE TITLE
Option to remove a video from "Continue Watching"

### ISSUE THREAD

**Issue by matchboxbananasynergy** [libre-tube/LibreTube#4452]
### Describe your suggested feature

With the new version and the introduction of https://github.com/libre-tube/LibreTube/pull/4262, I noticed that I usually start watching videos which I never end up finishing.

As a result, my "Continue Watching" tab is comprised of *a lot* of videos I have no intention of getting back to.

It would be great if long-pressing a video that's there presented an option to "Remove from Continue Watching".

This option would remove that video from that tab, but it shouldn't reset the watch timer (it should remember how much of the video you've watched)

Once it is removed, if the user opens that video again (by searching for it etc.) and continues watching it, it should pop back up in "Continue Watching", with the logic there being that the user decided they're still interested in the video and would like to finish it after all.

### Other details

Another option here (which I think would be okay to include in this issue and not a separate one) would be to have a "clear all" option that would remove all current videos from "Continue Watching".

Why would that be useful? Let's say you're doing research on a topic. You're opening dozens of videos (which you might not be finishing) trying to find a specific thing, or getting different perspectives. That means you can end up with *a lot* of videos you'll never get back to.

A "clear all" option (or a screen where you can select videos to remove, along with a "select all" option) would be very helpful and assist in keeping the otherwise very useful "Continue Watching" section clean.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The videos to continue watching are currently just displayed based on your saved watch positions - we can either mark the video as completely unwatched by removing the saved database entry or mark it as watched - which will both prevent the video from be shown, but without keeping the progress.

I recommend you to just disable the `Continue watching` option in Appearance -> Home tab content in that case - I don't think it's reasonable to do fundamental database changes for that, as there also seems to he few interest from that by other people.
