### ISSUE TITLE
Extend DeArrow support

### ISSUE THREAD

**Issue by matchboxbananasynergy** [libre-tube/LibreTube#4455]
### Describe your suggested feature

It would be great if DeArrow support was extended to support the following, which would make it a more complete implementation that comes closer to the functionality of the browser extension:

1. Button on video that has had its thumbnail/title changed which would show the original one
2. Ability for a random thumbnail from within the video to be shown for videos that haven't had a thumbnail submitted yet (might not be possible or result in extreme loading times, not sure) - Issue on Piped's tracker about this https://github.com/TeamPiped/Piped/issues/2713
3. Channel Allowlist (whitelist channels and always see their original thumbnail/titles)

### Other details

The extension has more options such as only replacing thumbnails or titles, the title format etc., but it might be overkill to support *every* setting that the extension does. I do think that having some configuration options, however, would make the integration of DeArrow a lot better/more useful.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by KaiserCalm** [comment]
As someone with ADHD, I'd like an option to just change the titles. 

If I enable the setting currently, I seem to not see new videos as my brain skips them automatically. However the ability to read more what the video will be about, after noticing the video's existence, would be very neat.

**Comment by Bnyro** [comment]
1. and 3. are currently not planned for LibreTube - whitelisting channels has already been rejected for SponsorBlock, and modifying the existing UI to add a button to toggle DeArrow is out of scope - it requires rewriting our DeArrow integration and just wouldn't fit into the UI either.

2. Is okay to be implemented, however it's currently not possible without DeArrow or Piped API changes.

**Comment by Bnyro** [comment]
We will reconsider 2. once https://github.com/ajayyy/DeArrowThumbnailCache/issues/4 is implemented. It's unknown when that will happen - so I'll close the issue for now to keep a better overview of open issues.
