### ISSUE TITLE
Inform logged username in account settings

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#4456]
### Describe your suggested feature

Inform logged username in account settings. Or is yet a way to know It?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You can click Logout in the instance settings, which will show you your username in brackets in the dialog.
