### ISSUE TITLE
Don't autoplay when in comment section 

### ISSUE THREAD

**Issue by M00NJ** [libre-tube/LibreTube#4459]
### Describe your suggested feature

Sometimes while watching a video that's about to end, I will check the comment section to get a feeling for the audience's reception. So I scroll through the comments, but when the video ends I'll get kicked out, which is annoying when you're in the middle of reading something. I know, I could have paused the video before, but I like reading comments WHILE the outro is happening. (Maybe it's a gen Z thing 😅) I remember that YouTube Vanced/Revanced would pause autoplay, when the comment section was opened. So that's what I would propose. This is low priority of course. Just a small quality-of-life improvement. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That already got rejected in https://github.com/libre-tube/LibreTube/issues/3998. You should quickly disable autoplay with the player control at the top right before opening the comments.
I don't think that's worth adding an option.

**Comment by M00NJ** [comment]
Alright. Sorry for the duplicate.
