### ISSUE TITLE
Subscriptions Sort By:

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#446]
### Describe your suggested feature

![Screenshot_20220609-163312_Chrome](https://user-images.githubusercontent.com/104249296/172848855-a0edf76f-533a-4fb2-a076-24acd8015958.jpg)
![Screenshot_20220609-163915_Chrome](https://user-images.githubusercontent.com/104249296/172848996-dd457284-ea44-43f9-a857-be3f641202f6.jpg)
This is how the Subscriptions are sorted.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Nizami20052022** [comment]
It is available in the Piped project.

**Comment by Bnyro** [comment]
not planned because it's not useful
