### ISSUE TITLE
Add compose support

### ISSUE THREAD

**Issue by arijit4** [libre-tube/LibreTube#4461]
### Describe your suggested feature

As this app is built on top of the `Material Design`, it would be a lot more easy to maintain the UI. [Here](https://developer.android.com/codelabs/jetpack-compose-migration#0) are the official instructions to migrate to Compose.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's way too much work for the current amount of maintainers, and therefore not planned. MDC Android is still supported and will be for the next years.

**Comment by deckstose** [comment]
I'd like to revisit this issue.

The discussion at https://github.com/libre-tube/LibreTube/discussions/5991 suggest only rewriting the UI for the sake of new technology, and I don't agree with that. But lately I'm changing to dark mode manually while using the app more often, and therefore having the same issue described in https://github.com/libre-tube/LibreTube/issues/7184.

What I've gathered from other discussions is:

- Lack of maintainer time or interest
- Little value gained at the moment (minus the theming issue)
- Big task
- External contributions unreliable for such a big rewrite
- Anything else?

What I like to know your current opinion about is:

- Would you be open to gradually start a rewrite?
    * As you said, this is a big task, but it's the future of Android development, IMO it is much
      more fun and the tooling around it is really nice. If this is somewhere on the roadmap, we
      need to start somewhere.
- Would binary size be a concern?
    * It's not for me but it's often mentioned as an issue when using both UI frameworks
    * I've tested this in https://github.com/deckstose/LibreTube/tree/push-zuuqswtkvxmx:
      Binary size with compose build feature and libraries added: `9.0MB -> 9.1MB` (minifying
      probably removes most of the code)
    * Porting `AboutActivity` to pure Compose (this is not completely polished, I wouldn't open
      a PR with this right now): `9.0 -> 9.7MB`
- How would this impact current development for you as the maintainers? You mentioned that this
  would add additional burden on you, and if you're short on time this is probably the last thing
  you need.
- Maybe we can start with an experimental branch, see if it's possible to keep it up-to-date
  alongside master while migrating parts and start looking more seriously at it once some bigger
  parts have been migrated?

In the end I respect any outcome to this and if you still think this is not happening any time soon, or maybe ever 🫡

**Comment by Bnyro** [comment]
> External contributions unreliable for such a big rewrite
>
Given the fact that it's now very easy to generate a lot of bullshit code using LLMs, that's nothing we would really trust new contributors on, or it would take a looot of time to review.

Migrating to Compose is like rewriting the app from scratch - it's probably faster to write a new app than to migrate LibreTube to Compose.

> Would binary size be a concern? 
>
No.

> Maybe we can start with an experimental branch, see if it's possible to keep it up-to-date
alongside master while migrating parts and start looking more seriously at it once some bigger
parts have been migrated?
>
Thank you for your interest in helping - but as mentioned, that's nothing we trust new contributors on. We don't accept AI contributions, and the only way for someone to proof that they actually write the code themselves is to have a history of good contributions and interactions.
