### ISSUE TITLE
Indicate if captions are auto generated

### ISSUE THREAD

**Issue by shuvashish76** [libre-tube/LibreTube#4462]
### Describe your suggested feature

Differentiate between auto generated vs normal available captions.

### Other details

LibreTube👇🏿
![Screenshot_20230814-113358_1](https://github.com/libre-tube/LibreTube/assets/48226312/08ffaee4-eaf8-4685-b841-68764eda332a)

NewPipe👇🏿
![newpipe](https://github.com/libre-tube/LibreTube/assets/48226312/4bba82b0-bf06-4f6b-9cfc-ec6087d63fab)

---

BTW  noticed that Captions feature not working at all for any video in v0.17.0 (39). Not sure if it's a known issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Captions work fine here.

**Comment by shuvashish76** [comment]
> Captions work fine here.

I think the issue is LibreTube doesn't remember the language. So everytime you open LT you've to select the language again

Suggestion :
1. If system caption language set to a specific language & that language available for video/audio then LT should switch to that specific one automatically
2. If caption language set to "Default" then LT switch to whatever language wet by the yt channel/video itself.
3. If use pick "auto generated" or "no captions" then LT should remember that & override system caption settings.

**Comment by Bnyro** [comment]
> I think the issue is LibreTube doesn't remember the language. So everytime you open LT you've to select the language again
> 
You can specify a default subtitle language in the settings. Imo, they shouldn't be remembered.

I don't think that the changes are really needed, but you can open a new issue to see if other users would be interested in that too.
