### ISSUE TITLE
Feature Request: Introducing Isolated Spaces for YouTube Channel Subscriptions

### ISSUE THREAD

**Issue by sanathusk** [libre-tube/LibreTube#4463]
### Describe your suggested feature

The "Spaces" app enhancement proposes the integration of an innovative feature that enables users to organize and categorize their subscribed YouTube channels into distinct isolated spaces. Each space will serve as a customized content environment, offering users a personalized and focused browsing experience. The primary objective of this feature is to enhance content relevance and limit distractions by tailoring video recommendations exclusively to the user's selected space.

### Feature Highlights:
- **Isolated Spaces Creation:** Users can create multiple isolated spaces within the app, each centered around a specific theme, interest, or purpose. For instance, a "Study" space could include educational and research-oriented channels, while an "Entertainment" space would contain recreational and leisure-oriented content.
- **Channel Assignment:** Subscribed YouTube channels can be assigned to one or more spaces, allowing users to curate their content precisely according to their preferences. A channel can belong to different spaces based on its thematic relevance.
- **Customized Recommendations**: The "Spaces" app will exclusively suggest videos from channels within the selected space. For example, if a user is currently navigating the "Study" space, the app's recommendation engine will only surface educational content, eliminating distracting and unrelated videos.
- **Content Filtering:** By categorizing channels into spaces, the user can effectively filter out content that does not align with the current space's theme. This filtering mechanism reduces the likelihood of encountering irrelevant or distracting videos.
- **Enhanced Focus:** Users can easily switch between spaces to seamlessly transition between different areas of interest. This feature promotes better focus and minimizes the temptation to deviate from the intended content consumption.
- **Personalized Engagement:** The isolation of spaces allows for more accurate personalization, as the recommendation algorithms consider a narrower scope of user preferences. This leads to a more engaging and satisfying user experience.

### Benefits:
- **Tailored Learning:** Users pursuing educational endeavors can create a dedicated space for studying, ensuring that video recommendations are aligned with their academic goals.
- **Distraction Reduction:** The isolation of content prevents users from stumbling upon unrelated or distracting videos, enabling a more productive and focused online experience.
- **Holistic Entertainment:** By allocating channels to specific spaces, users can enjoy a well-rounded entertainment experience while maintaining a clear boundary between leisure and study content.
- **Effortless Customization:** Organizing subscriptions into spaces empowers users to effortlessly manage their content intake, adapting to changing interests and priorities.
- **Improved Algorithm Accuracy:** The isolation of spaces refines the recommendation algorithms, resulting in more relevant and appealing video suggestions.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Android allows you to create multiple instances of an app by cloning it. That's the best (and only) way how you can create multiple isolated environments.

LibreTube doesn't have any plans for that, it's just not architectured for such a thing, neither is Piped. 

I don't recommend using AI for generating issues - half of the text doesn't apply to how LibreTube works in general.
