### ISSUE TITLE
Show captions in Pop-Up mode

### ISSUE THREAD

**Issue by shuvashish76** [libre-tube/LibreTube#4464]
### Describe your suggested feature

Self explanatory.
Similar to how NewPipe shows captions for their popup mode.

### Other details

App version : 0.17.0 (39)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
![community-kenjeong.gif](https://github.com/libre-tube/LibreTube/assets/50032603/0773c374-cd67-4485-b94c-48dba3e03831)

**Comment by shuvashish76** [comment]
If you think it's unnecessary/irrelevant for the project then give your reasoning behind it.
This is not a reddit or 4chan site to post your random memes.
Admin please hide both comments, thanks.

**Comment by akano12** [comment]
It's quite obvious, people go to PiP because they want to multi-task, they want to listen to the video/ partially watch/take quick looks while doing something else. So makes no sense to implement such feature because you won't be paying attention anyway to the video, let alone the size of subtitles that'll make it even harder for you to focus.

**Comment by akano12** [comment]
And if you're going to say that "oh no i can read them easily", that means you're already focusing in the video and there's no need to go to PiP

**Comment by shuvashish76** [comment]
Now thanks for your opinion on it.

> makes no sense to implement such feature because you won't be paying attention anyway to the video, let alone the size of subtitles that'll make it even harder for you to focus.
> if you're going to say that "oh no i can read them easily", that means you're already focusing on the video.

Agreed on both points but my use case is different,
1. I use LT on my 8 inch Tab (also there are 10inch or more bigger screen size tabs) which is large enough to view subtitles in PIP mode.
2. Now about the productivity/focusing part : There are multiple use case e.g. (i) My native language isn't English but I can understand it well, so subtitles helps incase you miss some spoken words from a News channel. (ii) Watching a documentary in your local audio lang with English subtitles on which helps to improve your vocabulary. In both the cases you don't need to focus on subtitles regularly but just quick look on them helps alot.

We don't support AndroidTVs yet but that's also a use case, NewPipe has this feature for reasons.

**Comment by shuvashish76** [comment]
> _either_ a guy can _see_ **_the video_** or the subtitle _or_ **_the thing in the background_** he is doing.

Interesting, so you're questioning the existence of PIP mode of android?
I believe if you can watch video in PIP mode i.e. while multitasking then it's possible to watch subtitles (with large enough screen)

**Comment by akano12** [comment]
> > _either_ a guy can _see_ **_the video_** or the subtitle _or_ **_the thing in the background_** he is doing.
> 
> Interesting, so you're questioning the existence of PIP mode of android? 

No need to take everything said in a literal way, 
obviously what he means is when in PiP you can either focus on the video or the subtitles (due to pip size) or focus on the thing you switched to PiP because of

**Comment by shuvashish76** [comment]
> my eyes can watch thousands of screen at a time but can only focus on 1 at a time

Exactly, same for me, thanks. We need not to focus on video/subtitle but PIP view helps in other ways.

**Comment by saymanrifat** [comment]
Should we need to work on this or What?

**Comment by Bnyro** [comment]
Closing as not planned, since there don't seem to be many people willing to use it.
