### ISSUE TITLE
Unlimited auto-play

### ISSUE THREAD

**Issue by Bnyro** [libre-tube/LibreTube#4469]
### Describe your suggested feature

We currently create a playing queue with the 20 related streams of a video. However, when those 20 videos have been played, the queue stops. If the queue is not set to repeat itself, we should insert the 20 related streams of the last video in the queue, and continue playing videos seamlessly. That applies for both, the audio and the video player.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FireMasterK** [comment]
Maybe at each video change, we could try to add current related videos to the queue as long as the queue is below 20 related streams.

**Comment by Bnyro** [comment]
True, that'd be possible as well.
