### ISSUE TITLE
Download Error!

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#447]
### Steps to reproduce

1. Play the video.
2.You press the download button.
3.The download continues in the notifications section, and a download error occurs shortly before the end.

### Expected behavior

There should be no download error.

### Actual behavior

It happened instead.

### LibreTube version

"0.3.1

### Android version

"Android 11"

### Other details

This happens every time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It should/could be fixed in the next update.
