### ISSUE TITLE
Incorrect Pause/Play Button State

### ISSUE THREAD

**Issue by akano12** [libre-tube/LibreTube#4470]
### Steps to reproduce

1- Play a video
2- Pause the video from player controls
3- Tap  home button

### Expected behavior

The notification control icon should change to pause

### Actual behavior

The notification control icon changes to loading state

### LibreTube version

0.17

### Android version

Android 13

### Other details

Possibly introduced by https://github.com/libre-tube/LibreTube/pull/4405

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by slimshady045** [comment]
notification buttons fail
