### ISSUE TITLE
Videos Start From Same Position When Skipped From Notification Control

### ISSUE THREAD

**Issue by akano12** [libre-tube/LibreTube#4471]
### Steps to reproduce

1. Play a video and let it play for few seconds
2. Skip the video from notification controls

### Expected behavior

Next video should play from the beginning

### Actual behavior

Videos play from the same position as the previous video

### LibreTube version

0.17

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Audio or video player?

**Comment by akano12** [comment]
> Audio or video player?

Videos, will test for audio

**Comment by akano12** [comment]
works properly in audio mode
