### ISSUE TITLE
Show selected option of "Remember position" in its summary

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#4478]
### Describe your suggested feature

This option should maybe show the current set from de list in the summary.
The current summary doesnt provide any relevant since there is a subtitle.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You're referring to the preferences?

**Comment by luckkmaxx** [comment]
yes, sorry
