### ISSUE TITLE
No video loads

### ISSUE THREAD

**Issue by solimm4sks** [libre-tube/LibreTube#4479]
### Steps to reproduce

1. Choose any instance
2. The feed and subscriptions load as expected
3. Click on any video
4. Wait for the loading circle to finish
5. The video is a black screen and doesnt start playing

### Expected behavior

The video plays.

### Actual behavior

The video doesnt play.

### LibreTube version

0.16.1

### Android version

Android 10

### Other details

F-Droid says the app is fully updated. Libretube itself says that there is a new update 0.17. Downloading the arm and universal packages and installing them leads to a "Not installed" message. Note that its not an update that broke the app for me, it was working fine on this version before.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Tracked at https://github.com/TeamPiped/Piped/issues/2809

**Comment by Bnyro** [comment]
Due to YouTube changes, it appears that Piped video proxies are getting IP banned, and hence videos don't play. 
You can work around that by going to settings -> audio and video -> disable piped proxy.
However, please keep in mind that this will lead your phone to directly connect to YouTube's servers and hence a VPN should always be enabled when doing that for privacy reasons.

**Comment by solimm4sks** [comment]
Ok, thanks for the quick reply.

**Comment by minou2020** [comment]
Why would Piped be IP banned ?

**Comment by minou2020** [comment]
I don't understand what's the problem with Piped
The website version works fine...

**Comment by S7venLights** [comment]
Turning off proxy means less toll on the piped servers. But also less privacy for you since B👀gle will see your IP address

**Comment by AdiPathak97** [comment]
Maybe there is an opportunity to use [Farside](https://github.com/benbusby/farside) to switch to a working proxy? If not automatically, then a button in the "choose instance" menu, will be way more useful and intuitive than picking a proxy at random and hoping it works.

**Comment by S7venLights** [comment]
I give a fook and clearly the developer does too.

**Comment by Seb3thehacker** [comment]
> Maybe there is an opportunity to use [Farside](https://github.com/benbusby/farside) to switch to a working proxy? If not automatically, then a button in the "choose instance" menu, will be way more useful and intuitive than picking a proxy at random and hoping it works.

This is so cool! Load balancing for FOSS front ends. Genius.

**Comment by franco27** [comment]
the previous version, I could play a video. with the current version, black screen. and the error message, network error which is displayed in a loop

**Comment by mpeter50** [comment]
@IndusAryan Me, and I'm quite sure a lot of others too?

Though while it is unavailable, Piped is still very useful without proxying.

**Comment by r1klz** [comment]
You have a good point @IndusAryan, but implementing a dialog for it, won't break the idea of the alternative frontends?

Anyways, at least we still have an option to disable it...

**Comment by GeorgeWL** [comment]
Also having this issue

Honestly, privacy is nice, but I mostly use it for the built-in sponsorblock

**Comment by iSaluki** [comment]
> If these instances cannot be used, there is no point in their existence

The problem is, "these instances" currently includes all of them. The problem isn't something the individual instances are likely to be able to resolve, as for many changing their IP frequently may not be practical or even an option.

**Comment by GeorgeWL** [comment]
Why is this nailed as resolved? Seems to still be an issue

**Comment by iSaluki** [comment]
It is an issue with

-------- Original Message --------

**Comment by Bnyro** [comment]
No, we don't support Invidious.

**Comment by Bnyro** [comment]
No, it doesn't work. You can't run LibreTube with an Invidious instance. Not sure what you're using in order for it to work, but it's not Invidious.

**Comment by mrfaptastic** [comment]
Might be worthwhile implementing a message from the proxy to the client to inform when unable for the proxy to connect to the video server.

I wonder how long it'll be before YouTube ban of use third party clients as well, only a matter of time before they implement some public key in the official client.

**Comment by mpeter50** [comment]
> and YT has even stopped showing home recommendations to those people who have disabled watch history

I don't think thats a problem. If you disable remembering the watch history, how should they know what you prefer?

> why because they want to harvest the data from those people who don't want to share

Do you really think this setting prevents them from doing it?

@mrfaptastic > I wonder how long it'll be before YouTube ban of use third party clients as well, only a matter of time before they implement some public key in the official client.

https://www.bleepingcomputer.com/news/google/browser-developers-push-back-on-googles-web-drm-wei-api/

**Comment by Dex94** [comment]
> https://inv.in.projectsegfau.lt/feed/popular
> 
> i am using this,this is listed as official invidious instance on their website

what  have you put in api section and in istance url? I trided but nothing. Can you make a screenshot?

**Comment by FireMasterK** [comment]
> what have you put in api section and in istance url? I tried but nothing. Can you make a screenshot?

That's just not going to work. LibreTube doesn't support Invidious.

**Comment by Myzel394** [comment]
@IndusAryan I'm also facing this issue for a few days already, even though I enabled the bypass proxy option. It may would have been useful here if we had an option like "Fallback to different instance"....

**Comment by mrfaptastic** [comment]
Even when turning the piped proxy off, I notice that videos are starting to fail to load in libretube.

I think this might be the beginning of the end. It's pretty easy for the official client to send some random seed, value, challenge-response, as part of its request to the YouTube video servers, which the liberal client doesn't do ot isn't aware that it should do.

Therefore that might be enough for them to be able to filter out / detect these alternative apps.

Looks like YouTube's commerical desire to force us to use their official client, and a subject us to continuous b******* adverts about TMEU China slave labor garbage ewaste products, is too strong for them.

**Comment by mpeter50** [comment]
I don't often use Libretube, but just tried with this video and its working fine: https://piped.video/watch?v=4-Xf_vJl_jE
Video loads, and I can also seek in it.

Instance: kavin.rocks (not sure why it is piped.video when I share the link from the video menu)
App version: 0.17.1 (F-droid)
Piped proxy is default-on, not disabled.

I have to admit, sometimes it takes a few seconds for the video menu to load anything, but it is still pretty much usable here.

@IndusAryan which instances did you try that didn't work?

**Comment by mpeter50** [comment]
@mrfaptastic I don't actually know whether this is the case, but it might also be just that the instances are overloaded.

I mean, proxying videos requires quite a lot of bandwidth.
Doing it is not just the default, but it cant even be turned off (I mean, when using the Piped web interface), and its not like there are only a handful users.

**Comment by farline99** [comment]
it seems like official kavin.rocks instance is fine now. works with proxy enabled just fine. issue is closed for me 😄

**Comment by mrfaptastic** [comment]
It'll go up and down as YouTube block the proxy and the proxy changes it's IP. Cat and mouse games.

**Comment by NotYasho** [comment]
> Due to YouTube changes, it appears that Piped video proxies are getting IP banned, and hence videos don't play. You can work around that by going to settings -> audio and video -> disable piped proxy. However, please keep in mind that this will lead your phone to directly connect to YouTube's servers and hence a VPN should always be enabled when doing that for privacy reasons.

That still doesn't fix it ☹️. I still get the "network error" message and I've tried every single instance.

**Comment by r1klz** [comment]
New instances works, could it be your network, @NotYasho? 👀

**Comment by NotYasho** [comment]
Just switched the instance back to kavin.rocks (Official) and now it works 😄
