### ISSUE TITLE
Video won't play

### ISSUE THREAD

**Issue by CryogenicPotato** [libre-tube/LibreTube#4487]
### Steps to reproduce

Open the following video https://piped.video/watch?v=otlYeBH9U6E&t=0 it won't play.
Pressing the play Button just doesn't do anything. 

### Expected behavior

Video should play. 

### Actual behavior

Video doesn't play. 

### LibreTube version

0.17

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/issues/4479
