### ISSUE TITLE
Video playback is a problem in the background. 

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#449]
### Describe your suggested feature

When you play a video in the background, you turn off the screen and the video plays, but then stops.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Turn off battery optimzation
