### ISSUE TITLE
Quality won't load

### ISSUE THREAD

**Issue by Fuzzythegoatq** [libre-tube/LibreTube#4499]
### Steps to reproduce

![Screenshot_20230815_143156_LibreTube](https://github.com/libre-tube/LibreTube/assets/124460008/d6103ec4-fa21-4cea-b107-6cf0d8a9a140)
![Screenshot_20230815_143200_LibreTube](https://github.com/libre-tube/LibreTube/assets/124460008/8d810caf-7592-4630-8ba5-1e5e0b211570)
I have been using libretubesince yesterday and the app is amazing! The only problem I'm having is the quality will not load. Can you fix this?

### Expected behavior

.

### Actual behavior

.

### LibreTube version

New version

### Android version

Android 13

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#4479
