### ISSUE TITLE
[BUG] You can't subscribe to a channel from the search page

### ISSUE THREAD

**Issue by CasuallyOrange** [libre-tube/LibreTube#45]
**Describe the bug**
When you search for a channel although the subscribe button shows up when you click it nothing happens, you need to go to the channel page to be able to subscribe (the page you get to after clicking the channel icon) I'm on the latest version and am logged in.

**To Reproduce**
1. Search for any channel
2. Click on Subscribe

**Smartphone (please complete the following information):**
 - Device: Asus zenfone max pro m1
 - Android version: 9

**Comment by rimthekid** [comment]
Yes I should remove the button I forgot to. It creates some networking problems.

**Comment by CasuallyOrange** [comment]
> Yes I should remove the button I forgot to. It creates some networking problems.

Ah ok

**Comment by rimthekid** [comment]
Should I close this issue?

**Comment by CasuallyOrange** [comment]
> Should I close this issue?

Yes
