### ISSUE TITLE
Log in with Google Account

### ISSUE THREAD

**Issue by SteveeWasTaken** [libre-tube/LibreTube#450]
### Describe your suggested feature

I think it'd be great if I could login with my Google account, so all of my current settings and everything are just imported

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Soup333** [comment]
Thats not possible rn since LibreTube uses piped for videos but you can import subscriptions from settings

**Comment by Bnyro** [comment]
Our focus is on privacy, we will never add Google login since we disagreee with their privacy policy. That's one major reason why this project exists.
