### ISSUE TITLE
Navigation from Watch History to a Channel is sort of Broken

### ISSUE THREAD

**Issue by IndusAryan** [libre-tube/LibreTube#4508]
### Steps to reproduce

watch history should have items from different channels
go to watch history
tap channels
the channels wont open properly

### Expected behavior

all channels should open

### Actual behavior

most of the time these 2 things will happen

 a channel will be opened(very rare)

progress bar will apppear but channel wont load

blank screen(most of the time)

### LibreTube version

Latest Alpha

### Android version

A13

### Other details

this also happens if you watch a video from a watch history and then click the channel below the player,it behaves the same

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
I'm pretty sure this isn't an issue with LT as there are some channels that won't open neither here nor on piped, of course unless those channels can be opened from search results or somewhere else.


And anyway can't reproduce

**Comment by Bnyro** [comment]
There haven't been any changes to that recently - the issue is probably that the Piped instance times out.

And no, it's not easy to not use Piped - the whole app is architectured to work with Piped only.
