### ISSUE TITLE
Autoexit full screen after watching the video

### ISSUE THREAD

**Issue by Gamer750** [libre-tube/LibreTube#4514]
### Describe your suggested feature

Autoexit full screen after watching the video

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not reasonable since you usually want to watch the next video with autoplay.
