### ISSUE TITLE
Allow to remove custom instances individually

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#4520]
### Describe your suggested feature

If you have custom instances added and want to remove old/testing instances, the only way is to remove all of them and re-add the ones you didnt wanted to remove.

### Other details

Maybe show a trashbin along side of custom instances when the list is shown.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Most users have one or two custom instances set at most, so I don't really see a need for that. It would not be possible without rewriting the whole preference unfortunately.
