### ISSUE TITLE
Back to player video settings when an option is changed

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#4522]
### Describe your suggested feature

After changing an option (video quality, captions, repeat...) the options list doesnt go back and you have to tap on settings icon on every change you do.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by luckkmaxx** [comment]
> this one will be uncomfortable actually imo,one will have to dismiss it manually

Yeah, I thought about that too.

**Comment by akano12** [comment]
It's fine as is but the only change I'd like to see is not dismissing it when tapping back from a section.
Let's say i wanted to edit quality and accidentally tapped on subtitles, if i tap back the menu would be dismissed.

**Comment by Bnyro** [comment]
I don't think that's a good idea personally. When I open the menu, I usually just want to quickly change the quality, but not do any other changes.

> Let's say i wanted to edit quality and accidentally tapped on subtitles, if i tap back the menu would be dismissed.
>
I don't think it's possible to accidentally select the wrong option. And you don't need to do many clicks to dismiss and re-open the video options.
