### ISSUE TITLE
Fail to import playlist from piped or freetube format

### ISSUE THREAD

**Issue by katnatek** [libre-tube/LibreTube#4523]
### Steps to reproduce

I manually migrate playlist from other application and export to both formats, delete the play lists, and import again.

All i have as result is all the playlist listed with 0 videos.

I attach the bckup in piped format 
[piped _ libretube-playlists.json.txt](https://github.com/libre-tube/LibreTube/files/12364454/piped._.libretube-playlists.json.txt)

Github don't allow .json so Remove the last .txt

### Expected behavior

All the playlist contain all the videos 

### Actual behavior

All the playlist contain 0 videos 

### LibreTube version

0.17.1

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by katnatek** [comment]
Juts in case is necessary i use whatever social instance

**Comment by Bnyro** [comment]
With, or without account?

**Comment by Bnyro** [comment]
And have you tries it using other instances?

**Comment by katnatek** [comment]
> With, or without account?

Without but i test with a short version (3 list with 3 videos) and the import finish successfully.
Can't test other instance because in almost all the rest the videos don't load (andminforge load but not all videos and more slow for me)

**Comment by Bnyro** [comment]
Other instances still work for everything except playing videos, so please test it with an other instance as well (doesn't matter which one)

**Comment by katnatek** [comment]
> Other instances still work for everything except playing videos, so please test it with an other instance as well (doesn't matter which one)

I test with kavin rocks libre and at begin i think the issue is reproduced, but after some manipulation (switch between main and playlist tab ) the lists begin to be loaded.

**Comment by Bnyro** [comment]
They're imported in the background because each video requires a separate API request, so yes - it takes time.

**Comment by katnatek** [comment]
> They're imported in the background because each video requires a separate API request, so yes - it takes time.

The interesting is i never see the notification of success like withe the short version, well again have issues with the videos, but that is a issue with instances, thank you for the attention

**Comment by Bnyro** [comment]
Yeah, we should maybe add notifications to make clear to users what's happening (if everything was successful or if some videos didn't get imported due to errors).
