### ISSUE TITLE
Please make a localization change

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#4530]
### Describe your suggested feature

Please remove the language "undeterminate (und)" created by me by mistake (I thought could change the name later) , and add "Spanish (latin)"  wich is missing in the language selection when adding a new one, for latin american people.
I want to translate this too, copying all from "Spanish" and doing a few changes to match Latin speakers jargon.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Spanish (Latin) is actually available on Weblate, added here: https://hosted.weblate.org/projects/libretube/libretube/es_419/.

Also deleted the undefined language.

**Comment by luckkmaxx** [comment]
Hmm I didnt noticed. I was reading latin spanish requests as suggestions in "spanish" strings.
Anyway its 1% translated.

I want to set spanish as base and then copy all from the base+do some changes. Im not sure if the copy precess can be done at once or it must be done string by string.

**Comment by luckkmaxx** [comment]
> You can copy the file content over from spanish to spanish latin `values.xml` and create a PR here. Not possible via Weblate.

if he doesnt compose you much, i'll send you the file to add it to the project. Credits do not worry me.

**Comment by Bnyro** [comment]
I'd prefer if you could create a PR, it's easy enough to edit that file via the GitHub UI.
