### ISSUE TITLE
Dismiss button not working in queue

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#4531]
### Steps to reproduce

I think this is to hide the queue list. But it does nothing.

### Expected behavior

Hide queue list?

### Actual behavior

Nothing done

### LibreTube version

0.17.1

### Android version

13

### Other details

![IMG_20230817_145314](https://github.com/libre-tube/LibreTube/assets/14180594/1856495c-61d6-4de6-90c8-60eedcb06129)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Works fine for me, interesting. The PR should fix it anyways.

**Comment by luckkmaxx** [comment]
Its tested in latest debug apk (3hrs ago)

**Comment by luckkmaxx** [comment]
By long tapping it shows the "dismiss" hint, but single tap does nothing

**Comment by Bnyro** [comment]
That's why I love Android development. Every device behaves exactly the same (not)

**Comment by luckkmaxx** [comment]
> That's why I love Android development. Every device behaves exactly the same (not)

I will test in a less modded device. Here Im using Iconify, LSposed, and so... It shouldn interfering but maybe

**Comment by luckkmaxx** [comment]
Tested in a stock device. Not working

**Comment by Bnyro** [comment]
Why did I get I thumbs down when I said that all Android devices behave different @luckkmaxx ?

**Comment by luckkmaxx** [comment]
> Why did I get I thumbs down when I said that all Android devices behave different @luckkmaxx ?

LOL that was a thumbs down for that headaches the android development causes! Not yourself, but I hope this doesnt affect your github profile.

**Comment by luckkmaxx** [comment]
Yeah now is working.

**Comment by Bnyro** [comment]
Oh haha, I thought you didn't agree with me. All fine then ;)
