### ISSUE TITLE
Watch Position Problem

### ISSUE THREAD

**Issue by muhammad-ans** [libre-tube/LibreTube#4535]
### Steps to reproduce

1. Mark a videos as watched.
2. Create backup of watch positions.
3. That Video would have postion 9223372036854775807.

### Expected behavior

The position should be video's length.

### Actual behavior

The videos marked as watched have position 9223372036854775807.

### LibreTube version

0.17

### Android version

Android 6

### Other details

Although it does not cause issues but it could.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's by design, otherwise we'd need to do a new api request to fetch the video duration. Why's that a problem? The UI code handles that properly and there wouldn't be any change in the user experience by doing it different.

**Comment by muhammad-ans** [comment]
Yeah I thought that at first but Then I thought maybe it's a bug.

**Comment by Bnyro** [comment]
Oh okay :)
