### ISSUE TITLE
Alternative Frontend  Suggession

### ISSUE THREAD

**Issue by Eliya-Manoj** [libre-tube/LibreTube#4569]
### Describe your suggested feature

I found an another open source frontend of youtube. I think it is privacy-friendly. Optional or an alternative feature - disabled piped proxy

### Other details

https://github.com/ViewTube/viewtube

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
There are no plans to support anything else than Piped.
