### ISSUE TITLE
video in 60 fps

### ISSUE THREAD

**Issue by person10301** [libre-tube/LibreTube#4570]
### Describe your suggested feature

quality selection in 1080p 60

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The player automatically selects that if your device and internet are good enough.
