### ISSUE TITLE
Search should open links

### ISSUE THREAD

**Issue by lu4p** [libre-tube/LibreTube#4578]
### Describe your suggested feature

If I paste a YouTube link in the search bar it should open that video directly.

### Other details

Newpipe also has this feature, the official YouTube app does not.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Works fine, mind sharing the url tho? 

![Screenshot_20230822_041843_LibreTube.jpg](https://github.com/libre-tube/LibreTube/assets/50032603/5fd5bc8e-7657-4eb5-b12a-2273321e4f9e)

**Comment by Bnyro** [comment]
I think the issuer would like the app to immediately open the video, instead of displaying the results. However, for that you should copy the link and share it to LibreTube.

**Comment by lu4p** [comment]
This doesn't work for unlisted videos, example: https://www.youtube.com/watch?v=JVBnJtzEuI0

(There is a result, but that's just a video containing the link in it's description.)

This also doesn't work for links containing timestamps.
