### ISSUE TITLE
Open YouTube links by default 

### ISSUE THREAD

**Issue by lu4p** [libre-tube/LibreTube#4579]
### Describe your suggested feature

LibreTube should be able to open YouTube links by default, as in I click a YouTube link anywhere and LibreTube opens.

### Other details

This might be impossible because of some android restriction, feel free to close this issue then.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
This is already possible, go to settings and toggle the "supported web addresses"

**Comment by lu4p** [comment]
Thanks, maybe this should be documented somewhere?
