### ISSUE TITLE
Fall back thumbnail for audio mode when data saver enabled.

### ISSUE THREAD

**Issue by NeeRaj-2401** [libre-tube/LibreTube#4587]
### Describe your suggested feature

As title suggests, keep a fallback image for thumbnails when data saver is enabled.

Because currently its complete blank and doesn't look good.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's a reasonable idea, but I don't see any suggestions on how the placeholder should look like here?

**Comment by NeeRaj-2401** [comment]
Ss from auxio

<img src="https://github.com/libre-tube/LibreTube/assets/88180887/c2bc6100-5b27-46df-a962-92e449559f00" width="30%" >

**Comment by Bnyro** [comment]
I don't think that would look well in LibreTube.

**Comment by NeeRaj-2401** [comment]
i would suggest to create our own placeholder, and put our monochrome logo inside there instead of disc
