### ISSUE TITLE
Text briefly changes to different instance when pressing "Clear Added"

### ISSUE THREAD

**Issue by FOSSProponent9436** [libre-tube/LibreTube#4592]
### Steps to reproduce

1. Go to Settings -> Instance
2. Rapidly press clear added

### Expected behavior

Text doesn't change after multiple presses because it is already cleared

### Actual behavior

Below choose an auth instances the text kavin.rocks (official) briefly flashes even when authentication instance is not enabled (and it was not on the list anyway for me).

I can't ascertain why but below choose it briefly shows different instance to the one you chose before you pressed the button but the instance that is flashed is different depending on the instance you chose. For example when I pressed it when I had chosen smnz.de it flashes privacydev.net but when I choose frontendfriendly.xyz it flashes hostux.net (which is not on the list of instances to choose for me)

### LibreTube version

0.17.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's by design - whenever you add a custom instance, the list of instances must be updated, which causes that minor visual bug in the Android preferences library. We can't avoid that unfortunately, but it's not really a serious UX issue anyways.
