### ISSUE TITLE
quick settings media control

### ISSUE THREAD

**Issue by sgabriel-1** [libre-tube/LibreTube#461]
### Steps to reproduce

instead of there being a functional media control panel in the quick settings menu there is a blank pause/play button

### Expected behavior

media controls with skip, pause, play, the video name

![Screenshot_20220611-185051](https://user-images.githubusercontent.com/78331190/173208546-87ea0c3c-296a-4649-a170-fd67d660abee.png)
 ex: Spotify 

### Actual behavior

blank media session with only pause functionality 

![Screenshot_20220611-185106](https://user-images.githubusercontent.com/78331190/173208554-a1d42ef4-24f9-4b01-b040-dc5e70fd417c.png)

### LibreTube version

0.3.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#377
