### ISSUE TITLE
Clickbait remover

### ISSUE THREAD

**Issue by iamgitcat** [libre-tube/LibreTube#4628]
### Describe your suggested feature

Replace video thumbnail with an actual screenshot from the video

### Other details

Here is an extension for browser and it changes YouTube so much better. https://github.com/pietervanheijningen/clickbait-remover-for-youtube

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Isn't this what DeArrow do?

**Comment by Bnyro** [comment]
Yes, exactly.

**Comment by akano12** [comment]
@iamgitcat go to settings => sponsorblock amd toggle "Enable DeArrow"

**Comment by lamyergeier** [comment]
@akano12  @Bnyro  

>  go to settings => sponsorblock amd toggle "Enable DeArrow"

This didn't work, I see that DeArrow requires licence atleast on the birefox browser. Is this the reason?

**Comment by akano12** [comment]
> @akano12 
> 
> 1. In firefox Dearrow needs licence as can be seen below: 
> 
> ![image](https://github.com/libre-tube/LibreTube/assets/42092626/754d8692-4fe8-45bf-9a38-afaf1852c88d)
> 
> 
> 2. Since DeArrow doesn't work in Firefox (as above) without license, and it was not working for me in Libretube. I concluded that perhaps it requires license to be entered in the app.
>  

Here you can see search results with amd without DeArrow

![Screenshot_20240227_012049_LibreTube.jpg](https://github.com/libre-tube/LibreTube/assets/50032603/cf8ad9ba-7285-4f5c-bcf3-a187914f4a2b)

![Screenshot_20240227_012037_LibreTube.jpg](https://github.com/libre-tube/LibreTube/assets/50032603/83ba79e9-147c-4152-aa2f-7a13dad7285d)
