### ISSUE TITLE
Tablet Landscape Mode

### ISSUE THREAD

**Issue by Bluscream** [libre-tube/LibreTube#4629]
### Describe your suggested feature

A tablet mode like the official youtube app/newpipe has. Where it shows the vid on the left side and comments/description to the right

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Duplicate.
