### ISSUE TITLE
Launcher Shortcuts

### ISSUE THREAD

**Issue by Bluscream** [libre-tube/LibreTube#4630]
### Describe your suggested feature

Shortcuts for the Launcher or atleast different activities so you can start the app at different views (Like Whats new?, Subscriptions, etc)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Already implemented.

**Comment by Bluscream** [comment]
![Screenshot_2023-08-26-14-49-40-449](https://github.com/libre-tube/LibreTube/assets/3318223/890e7bca-371a-4430-b352-b7506fbf4a41)
I could not find any activities or launcher shortcuts related to views anywhere
