### ISSUE TITLE
SmartTube integration > Remote Casting

### ISSUE THREAD

**Issue by SecularSteve** [libre-tube/LibreTube#4637]
### Describe your suggested feature

It already is possible to do it on SmartTube with the regular YouTube App, but you need to configure it manually with a code.

Basically, what if it worked out of the box for LibreTube?

No configurations, no codes, just open the app, choose the option, and play from Libre to Smart.

With extra features mind you.

Any opinions?

### Other details

Made a similar ticket on the SmartTube page:
https://github.com/yuliskov/SmartTubeNext/issues/2818

Similar discussion here:
https://github.com/libre-tube/LibreTube/discussions/3493

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I've never been in touch with any SmartTube developer, I don't think it makes sense while they don't use Piped.

**Comment by SecularSteve** [comment]
It is partially built with Kotlin, and they never did specify which API they use to get the videos.

I just presumed they use Piped and/or Invidious. Piped primarily since it's obvious that they're using a form of Dash for quality control, and it's the only other way to watch full 8K videos in AV1, AVC and VP9. I mean, if they're using their own thing, that's impressive in it's own way.

**Comment by FireMasterK** [comment]
This would be possible only if they have some kind of Networking API that LibreTube can use to modify playback on SmartTubeNext.

It also appears that SmartTubeNext uses the YouTube API, which is likely how they have been able to integrate with the proprietary YouTube app.

**Comment by Bnyro** [comment]
The only thing I could imagine is some sort of way to share a qr code with a video link via SmartTube and open it via LibreTube.

I neither have a TV to test this nor any plans to integrate with other apps that are not part of the Piped ecosystem.

Thus not planned from our side.
