### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by Snyret** [libre-tube/LibreTube#4638]
### Describe your suggested feature

I don't like spamming so I will be putting some suggestions together.

1- Make the notifications (without thumbnails) to be able to directly open videos.

2- Add search inside of channels (and maybe playlists in the future?), if posible. 

3- And minimize the "cancel the auto-play of the next video in queue" button to fit the screen frame when in the small player*

As always, thank you for an already functional and, in my view, great app.

### Other details

*
![Screenshot_20230826_170503](https://github.com/libre-tube/LibreTube/assets/139090371/a5e8bf18-ea46-4b23-9c0c-d3ac6806c927)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
1. That's already possible.
2. That's not supported by the API.
3. Please file a new bug report for that.

Generally, please don't list multiple things in one issue.
