### ISSUE TITLE
App not responding when accessing subscription list

### ISSUE THREAD

**Issue by catgangdev** [libre-tube/LibreTube#4640]
### Steps to reproduce

Go to subscription tab
Tap subscriptions
App taking long time to load and throwing not responding error again and again 

### Expected behavior

List should open

### Actual behavior

Not responding error occurred.
![Screenshot_20230827-081502_LibreTube](https://github.com/libre-tube/LibreTube/assets/62982051/5b0c19ca-970c-4c84-92c4-9b74668dabd4)

### LibreTube version

0.17.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by catgangdev** [comment]
I have 700+ subscription maybe because of this?

**Comment by Bnyro** [comment]
Likely.

**Comment by catgangdev** [comment]
> Likely.

So anyway to fix this?

**Comment by Bnyro** [comment]
By adding pagination to the subscription page.

**Comment by catgangdev** [comment]
> By adding pagination to the subscription page.

Great. Can we expect this in future?

**Comment by Bnyro** [comment]
I'm currently I'm vacation, I might look into it after (in 2 weeks).

**Comment by catgangdev** [comment]
> I'm currently I'm vacation, I might look into it after (in 2 weeks).

That's great. Thanks for your assistance.

**Comment by akano12** [comment]
Isn't it the same as https://github.com/libre-tube/LibreTube/issues/3240?

**Comment by Bnyro** [comment]
No, this one is about the channel list while the other one is about the new videos listed.
