### ISSUE TITLE
Notifications don't open the app

### ISSUE THREAD

**Issue by Snyret** [libre-tube/LibreTube#4642]
### Steps to reproduce

1. Disable the thumbnails for incoming notifications.
2. Recieve a notification when the app is not in the background.
3. Tap the text in the notification.
4. The notification closes and the app isn't started.

### Expected behavior

The video should open

### Actual behavior

The notification dissappears

### LibreTube version

0.17.1

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The relevant code is here: 
https://github.com/libre-tube/LibreTube/blob/master/app/src/main/java/com/github/libretube/workers/NotificationWorker.kt#L187.

We're already setting it to open the app when clicking the notification. However, how that's done is up to the Android ROM, and therefore likely a device side issue.
