### ISSUE TITLE
watch progress isnt saved after network changed

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#4645]
### Steps to reproduce

I have set that watched videos to be hidden from feed.

I just was using LibreTube at night, and next morning I turn on my device screen and there is libretube in foreground.

In my feed I set a video as watched, and the progress line at bottom gets full filled, but it doesnt dissapeared. And switching between tabs resets the watch progress of the video to before was set as watched.

The video watch progress isnt saved until I restart the app.

### Expected behavior

Save the watch progress and hide the watched video.

### Actual behavior

Explained

### LibreTube version

0.17.1 

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by luckkmaxx** [comment]
So I will be testing this and try to see if it reproducible

**Comment by Bnyro** [comment]
I guess reloading the tab also does the job? So the issue might be that the fees just doesn't automatically update and remove watched videos?

**Comment by luckkmaxx** [comment]
No. Lets say I have a video watched at 20%. When I set it as watched, the progress bar got full filled (but the video wasnt hidden). After reloading or switching tabs, the progress bar was at 20% again.
In my mind seems as, in that described situation, altough the UI shows a full progress bar, the "watched" flag isnt being informed in the piped db (I guess due to some connection time out, during my sleep hours, and when I hand my phone again, the app is still in RAM, it is not restarted, and the connection to piped db is lost until the app process is restarted)

**Comment by luckkmaxx** [comment]
OK I hunted the bug!
I have a VPN connection. If I have the app opened, then disconnect the VPN, if I try to set some video as watched, then the bug appears.

**Comment by Bnyro** [comment]
So during the time you don't have an internet connection for a short time due to switching the VPN on/off?

**Comment by Bnyro** [comment]
We're currently doing an unneeded network request to fetch video info which could be avoided by some refactoring, which will fix the issue.

**Comment by Bnyro** [comment]
For your information, I'm not at home until September 8th - so I can give some comments here, but can't actually look into fixing it.

**Comment by luckkmaxx** [comment]
> So during the time you don't have an internet connection for a short time due to switching the VPN on/off?

no. the connection is quickly restored connected to my home wifi. there is no chance to try set as watched during the network change.
At nights, my server is off so the vpn is disconected and the device connects to wifi/data.

**Comment by Bnyro** [comment]
Superseded by https://github.com/libre-tube/LibreTube/issues/4662
