### ISSUE TITLE
Add ability to set a default feed group.

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#4646]
### Describe your suggested feature

In the group editting popup, it could show a 📌 icon along side each group name to pin a group as default starting group.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Added as 12. to #3558
