### ISSUE TITLE
Creating Piped account deleted my app data

### ISSUE THREAD

**Issue by S7venLights** [libre-tube/LibreTube#4649]
I had a local account on my phone, decided to sign up to a adminforged.de instance to sync my data. 

1.Signed up in LibreTube
2. Logged into Piped on a browser
3. A few minutes later came to LibreTube, tried to export a playlist, didn't really work… 
4. Clicked back to find that all my playlists and subscriptions were gone. (App had synced down to nothing)
5. Watch history and bookmarks were not affected.

Luckily I had clicked to make a full backup before sign up… But due to a backup issue #3427, the backup hadn't saved. Luckily I could import my subscriptions from FreeTube. And I just had to rebuild what playlists I could from watch history.

Expected behaviour, the LibreTube app data, from where I created the account, would sync to the server, and not vice versa (empty account to app).

**Comment by Bnyro** [comment]
You can just logout and the app data is the same as if you never logged into an account.

In order to take your local data over to the Piped account, it's self explaining that you should export playlists and subscriptions without being logged in and re-import them when logged in.

**Comment by S7venLights** [comment]
Okay that worked thanks. Only thing I can't get to sync is Channel Groups from Piped to App… 
Sorry this issue may have used your time, but I'm sure you can see how this sign up process would confuse people.
LibreTube is fantastic app by the way I always suggest it.

**Comment by Bnyro** [comment]
Piped's API doesn't yet allow to sync channel groups, thus they're always stored locally.
