### ISSUE TITLE
Make mini player and background distinguishable

### ISSUE THREAD

**Issue by NeeRaj-2401** [libre-tube/LibreTube#4653]
### Describe your suggested feature

1. Mini player separator/border ( because sometimes the ui&miniplayer colors got emerged in each other )

2. Unnecessary padding/space around channel name row in expanded player ui

~3. Bit heightened + less corner radius for comments button in expanded player ui~

### Other details

PS: i know Bnyro is the only maintainer & don't have much time for these not much imp feature requests. 

@FineFindus (or any other contributor ) please see if these are worth to improve 

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by NeeRaj-2401** [comment]
<img src='https://github.com/libre-tube/LibreTube/assets/88180887/de22a1cc-a6ef-4b66-a2c6-4a9e1afbd6ba' width='50%'>

1. Apologies for that, recently FineFindus is actively working  on some tweaks, so i thought they might consider it.

2. The chanel row paddings are **unnecessary**, making a bit compact (less spaces ) would be nice.

3. Its not about the consistency, but yeah i agree its doesn't required changes otherwise video and comments button will start looking similar.

**Comment by Bnyro** [comment]
I for myself don't see any reason to change something here
1. A separator would certainly look bad and no otherapp with a miniplayer does that
2. The spaces around the channel were added in order for the ripple effect when you long press the channel name to look good
3. The border radius looks perfectly fine in combination with the other layouts above

**Comment by NeeRaj-2401** [comment]
1.  Look at mini player at such scenarios

<img src='https://github.com/libre-tube/LibreTube/assets/88180887/be14630f-917b-4443-b54c-febfc68c3014' width="50%">

2. Oh, honestly this is the first time i am noticing the ripple effect 😅. But still the space can be reduced,

<img src='https://github.com/libre-tube/LibreTube/assets/88180887/7bbbd301-c4eb-4f67-8745-ee4c43b7e2b2' width="50%">

**Comment by Bnyro** [comment]
1. We might be able to add a small elevation to the miniplayer background color - but it's questionable if it looks good.
2. I still disagree on that.
