### ISSUE TITLE
Thumbnails of videos in a playlist are not displayed; using instance "kavin.rocks libre (Official)"

### ISSUE THREAD

**Issue by Yukai-Qian** [libre-tube/LibreTube#4654]
### Steps to reproduce

1. Log in to instance "kavin.rocks libre (Official)"
2. Open a video
3. Click "save" under the video to the right
4. Pick a playlist
5. Click "add to playlist"
6. Go to the "Library" page of LibreTube. 
7. Click the playlist to see contents.

### Expected behavior

The thumbnails of the playlist and the videos in the playlist should be displayed.

### Actual behavior

The thumbnails of the playlist and videos do not show.

![Screenshot_20230828-164756](https://github.com/libre-tube/LibreTube/assets/100383998/ab792bac-5f39-4995-9fb6-c491036cf9cc)
![Screenshot_20230828-164812~2](https://github.com/libre-tube/LibreTube/assets/100383998/6736c8c5-6ac5-46d9-9629-b51e0e4d3182)

### LibreTube version

0.17.1

### Android version

Android 13 for Sony Xperia 1 III, 61.2.A.0.472 release-keys

### Other details

Solutions tried but failed:

I have set "Max image cache size" to "Limit to Runtime". 

I have tried logging out and back in.

I have tried closing the app and reopening.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Yukai-Qian** [comment]
It is worth remarking that the problem might be instance-specific because it does not occur if I log in to "adminforge.de" (with an account registered separately), and I'm not sure if it's a bug on our end or on kavin.rocks's.

**Comment by FireMasterK** [comment]
Hi, this issue should have been fixed. This was caused by an issue in the instance. Thanks!

**Comment by Yukai-Qian** [comment]
> Hi, this issue should have been fixed. This was caused by an issue in the instance. Thanks!

Indeed it works now! Thank you for the quick fix!
