### ISSUE TITLE
Download on SD card

### ISSUE THREAD

**Issue by MAAB-FW** [libre-tube/LibreTube#4656]
### Describe your suggested feature

Please add download on SD card option. Downloading files to internal storage on a low config phone puts a lot of pressure on the phone.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Duplicate of #2041
