### ISSUE TITLE
Searchbar delay

### ISSUE THREAD

**Issue by MAAB-FW** [libre-tube/LibreTube#4658]
### Steps to reproduce

1. open the app
2. tap on searchbar then search any content.
3. now if i tap again on searchbar then issue here.

### Expected behavior

As soon as you tap on the search bar, the keyboard will appear.

### Actual behavior

After searching once then again when I click on search bar to search something new keyboard doesn't show after 5-7 seconds keyboard shows. It's not a keyboard problem. I have tried with multiple keyboards.

### LibreTube version

0.17.1 (latest) 

### Android version

8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by catgangdev** [comment]
Not able to reproduce here. I am running A13 though

**Comment by Bnyro** [comment]
If so, that's either an Android or device issue. Try using a different keyboard.
