### ISSUE TITLE
Merge in Smoke Messenger Chat for swarming file transfer (Steam Protocol) when sending music to Chat Friends

### ISSUE THREAD

**Issue by bolzobrazil** [libre-tube/LibreTube#4660]
### Describe your suggested feature

Please add the Chat Messenger Smoke to LibreTube.

The messenger is encrypted and has a special file transfer over the Steam Protocol to send files to friends.
The file transfer is swarming, though encrypted, also to friends, I have not shared the key with.
The social sharing of music is the idea to enhance the experience.

You can read some ideas about the messenger here:
https://tarnkappe.info/artikel/english/mceliece-messaging-smoke-crypto-chat-the-first-mobile-mceliece-messenger-published-as-a-stable-prototype-worldwide-279847.html

You find it at Fdroid:
https://f-droid.org/de/packages/org.purple.smoke/

And at Github:
https://textbrowser.github.io/smoke/

### Other details

Sharing the downloaded music file with friends secure over the encrypted chat messenger.
Swarming file transfer - even with other peers getting transfered this file from another friend, which is not a key-shared encrypted friend of mine (Stream Protocol).
An auto-share feature to share a fresh downloaded music file with all my friends in my messenger would create a new sharing community of music, like the samsung app once ago via VK Kontakte offered free music download for the first samsung phones.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's out of scope for the project.

You can share links from LibreTube using the messenger as you like to, but we don't aim to integrate with any 3rd party apps more than others.
