### ISSUE TITLE
Watch progress not reflected in UI after watching a video

### ISSUE THREAD

**Issue by FineFindus** [libre-tube/LibreTube#4662]
### Steps to reproduce

1. Pick a video from the trending page
2. Watch the video
3. Close the video player
4. Notice how the video is still displayed as unwatched until the page is reloaded

### Expected behavior

Once the player is closed (or the watch position is updated) the UI should reflect the change as well.

### Actual behavior

The UI only shows the new watch position once it is recreated, e.g. by refreshing.

### LibreTube version

0.17.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's similar to #4645 maybe?

**Comment by Bnyro** [comment]
And implementing this will be an endless amount of refactoring, I doubt it's worth it.

**Comment by FineFindus** [comment]
> That's similar to https://github.com/libre-tube/LibreTube/issues/4645 maybe?

Looking over it, not really. It seems to be more related to network issues, whereas this is also occurring without a network change.

> And implementing this will be an endless amount of refactoring, I doubt it's worth it.

Honestly, I lack the knowledge of both android app architecture and this specific app to fix the bug, so I created this issue, hoping someone else maybe able to.
