### ISSUE TITLE
Logging into kavin.rocks does not work

### ISSUE THREAD

**Issue by Anti-Apple4life** [libre-tube/LibreTube#4664]
### Steps to reproduce

1. Set instance to kavin.rocks (Official)
2. Try to login with an already created account

### Expected behavior

User should be logged in

### Actual behavior

I get the message `There seems to be a problem with the selected server. Try another instance.`

### LibreTube version

"0.17.1"

### Android version

Android 13 (One UI 5.1)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Not the app's fault, use another instance

**Comment by Anti-Apple4life** [comment]
The instance is online. I am using it logged in on my PC right now

**Comment by FireMasterK** [comment]
We had a partial outage on the instance. (some servers were up, while not all of them) What likely happened is your PC was likely routed to a working server, whereas the app wasn't routed to one. The instance is currently struggling due to some bot attacks, unfortunately. :/ Sorry for the inconvenience caused!

**Comment by g4570n** [comment]
> The instance is online. I am using it logged in on my PC right now
> 
> Edit: The instance also works anonymously in the LibreTube app

The instance still allowed to be used anonymously?
I am getting this error when I try to reproduce a video: 

> Got error: "Sign in to confirm that  you're not a bot"
