### ISSUE TITLE
New video push notification.

### ISSUE THREAD

**Issue by MAAB-FW** [libre-tube/LibreTube#4667]
### Describe your suggested feature

In this app there are no New video push notification. I think this is a huge problem for me. so i have to search all (70+) channels one by one. this so heartbreaking issue. please add notification option.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
There already is a notification option.

**Comment by MAAB-FW** [comment]
I checked all the settings and didn't find any push notification option.
There are 2 options one is for streaming and the other is for stories.
Although these also do not receive notifications. But I need new video
notification.
