### ISSUE TITLE
Add buffer progress bar for audio only

### ISSUE THREAD

**Issue by fw190d13** [libre-tube/LibreTube#4668]
### Describe your suggested feature

When you open a video stream you can observe how the video is being buffered and start to watch after the buffering is complete. This is very  helpful when on the train or in any other place where the network coverage is poor. I think the same would be helpful for audio only. Right now we can't see how much of the file got buffered.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
UI suggestions for that?

**Comment by fw190d13** [comment]
Maybe the same as for the video? On the video playback there is a white indicator showing how much buffering is done.

**Comment by Bnyro** [comment]
I decided against this for two reasons:
1. It's not easy to implement because the player doesn't have a good api for it
2. There's no good way to implement this on a UI side with our currently used progress bar. 
3. Other common audio players don't show the buffer progress either
