### ISSUE TITLE
Allow for sorting lists in library by date of creation

### ISSUE THREAD

**Issue by fw190d13** [libre-tube/LibreTube#4669]
### Describe your suggested feature

Some YouTube channels create playlists that you can subscribe to. If that list is short there is no problem but I'm subscribed to a channel with over 300 recordings in one playlist. As you can imagine I want to listen from the beginning so each time I have to scroll to the end of those over 300 clips pick the next one and switch on the audio only mode. If there would be a possibility to sort such a list (oldest first/newest first) it would be much easier to start from the beginning of such huge collections.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by fw190d13** [comment]
A quick and dirty fix for that which I have just discovered is to clone the list with the three dot menu. After that in the cloned list you can sort the files in different ways.

**Comment by Bnyro** [comment]
Unfortunately, there's no API support for that. Public playlists are paginated, which means that we need to make a new api call to get 20 additional videos.
