### ISSUE TITLE
Error while importing playlist from youtube 

### ISSUE THREAD

**Issue by DerZwergGimli** [libre-tube/LibreTube#4672]
### Steps to reproduce

1. Go to YouTube and export the playlist/'watch later' to a CSV
2. Go to LibreTube and import the file using the playlist import as CSV option

### Expected behavior

Should import the playlist successful

### Actual behavior

I do get the following error:

```
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.get(ArrayList.java:437)
	at okio.Path$Companion.importPlaylists(SourceFile:315)
	at com.github.libretube.ui.preferences.BackupRestoreSettings$getPlaylistsFile$1$1$1.invokeSuspend(SourceFile:39)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
	at androidx.work.Worker$2.run(SourceFile:53)
	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4982c70, Dispatchers.IO]
    
```

### LibreTube version

0.17.1

### Android version

Android 10

### Other details

btw the exported csv file has approx 5000 rows and some videos are private/unavailable but im not sure if thats the issue here

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please share an example CSV file to reproduce the issue.

**Comment by DerZwergGimli** [comment]
[Watch later-Videos.csv](https://github.com/libre-tube/LibreTube/files/12485126/Watch.later-Videos.csv)

**Comment by EisregenHaha** [comment]
Got the same issue

**Comment by rewrib** [comment]
I have the same issue with every csv file, that comes from Google Takeout. Playlist length does not matter. Here is an example with a shorter list:
[perfect videos.csv](https://github.com/libre-tube/LibreTube/files/12566518/perfect.videos.csv)
