### ISSUE TITLE
Error when opening video

### ISSUE THREAD

**Issue by brckd** [libre-tube/LibreTube#4673]
### Steps to reproduce

1. Click a video or open a link

### Expected behavior

The video should load.

### Actual behavior

There is a toast with the error message `Failed to find pattern "signuatureTimestamp[=:](\d+)" inside o...`.

### LibreTube version

0.17.3

### Android version

Android 13

### Other details

The same app version worked fine until today.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Neither 0.17.3 exists nor is this a LibreTube issue.

**Comment by brckd** [comment]
it works again as of today 👍
