### ISSUE TITLE
Disable video track while screen off

### ISSUE THREAD

**Issue by lu4p** [libre-tube/LibreTube#4681]
### Describe your suggested feature

When I lock my phone while playing a video LibreTube should switch the current stream to audio only, Newpipe and the official YouTube app also do this.

I haven't verified that this isn't the case already, just anecdotal experience of audio stopping while locked when on crappy mobile service.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not a good idea - it would be very strange for most users why the video turned into an audio player. Either it should be an option, or you should just take the extra second and press the button to switch to audio mode. It's not that hard.

**Comment by lu4p** [comment]
No it shouldn't turn into an audio player, it should just stop loading the video when the screen is off.

**Comment by Bnyro** [comment]
That sounds like the option "Auto-pause" in the player settings?

**Comment by Bnyro** [comment]
We could do this via https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/trackselection/TrackSelectionParameters.Builder.html#setTrackTypeDisabled(@com.google.android.exoplayer2.C.TrackTypeint,boolean).

**Comment by NeeRaj-2401** [comment]
While screen off or as soon as user leaves app in background.

Afaik official YT does the same asap user leaves app in background ( btw noticed that in revanced )

**Comment by lu4p** [comment]
I don't think this is implemented correctly, when using the audio player I can listen to YouTube videos all day long and with a locked video player it often aborts after only a few minutes.
