### ISSUE TITLE
Being able to do local processing of the videos

### ISSUE THREAD

**Issue by voidplayer** [libre-tube/LibreTube#4686]
### Describe your suggested feature

After using libretube for a few months now i gotta say i must to use newpipe almost daily due to having local processing of the youtube videos

I either ```share video... newpipe``` or export subcriptions and impor them in newpipe. The feed rss takes a lil to load, but it works reliably

I dont know if is because i watch most videos x2 but no instance is able to be reliable while serving the video. Newpipe always works, so is not an issue with youtube or my connection

I dont know if this feature is hard to copy from newpipe, but having the option to do local processing of the video as an option for each video, would alleviate the piped instance in those cases where the user is not concern with loading youtube page directly and indirectly unload the instance for those users really dont want to load youtube

Thanks!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Settings -> Audio and video -> Disable Piped Proxy

**Comment by voidplayer** [comment]
Wow, how long have this been there!

Amazing thank you!!
