### ISSUE TITLE
Keyboard did't poping up!

### ISSUE THREAD

**Issue by KSinghofficial** [libre-tube/LibreTube#4687]
### Steps to reproduce

1. Install libretube from armeabi-v7a
2. search something in searchbar ,  yes the keyboard will pop up.
3. press search
4. now tap searbar now, the keyboard did't pop up on second time. 

### Expected behavior

keyboard should pop up in second time when tabed the searchbar.

### Actual behavior

keyboard did't pop up on second time when tabed the searchbar.

### LibreTube version

0.17.1

### Android version

8.1.0 Go

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by KSinghofficial** [comment]
keyboard did't pop up.

**Comment by akano12** [comment]
1. Share a recording
2. Try with a different keyboard and report back

**Comment by KSinghofficial** [comment]
It's time to go to bed,
I will try tomorrow :)

**Comment by Bnyro** [comment]
We're using a normal Android SearchBar without any modifications, thus it's either a general Android Go issue or something in the library we use, but not our issue.
