### ISSUE TITLE
[FEATURE] Grid video list mode

### ISSUE THREAD

**Issue by martin-desktops** [libre-tube/LibreTube#47]
I would love to see in the future option  that is currently available in NewPipe. Grid video list mode allows becoming acquainted with new videos much faster than if you had to scroll through these big thumbnails.

![Screenshot_2022-03-05-23-47-33-355_org.polymorphicshade.newpipe.jpg](https://user-images.githubusercontent.com/64419373/156902266-54a6c55b-d260-4794-9fef-e7859e74883c.jpg)

**Comment by rimthekid** [comment]
You mean for Home feed only?

**Comment by martin-desktops** [comment]
I think that this layout would work out both on subscriptions and trending page (but I am not yet acknowledged how is going to look "Library" tab). That's how this layout works in NewPipe and I have really good opinion about it. Furthermore, grid would significantly improve experience on big screen tablets.

**Comment by martin-desktops** [comment]
My UI visualization in Figma:
https://www.figma.com/file/4yaxlYqFgFX7CR6Rhnvm6P/Untitled?node-id=0%3A1

**Comment by rimthekid** [comment]
It's already grid layout on bigger tablets I'll add an option in the settings to choose how many in a row

**Comment by martin-desktops** [comment]
Thanks a bunch!

**Comment by martin-desktops** [comment]
Thanks a lot!
