### ISSUE TITLE
How do I download an instance?

### ISSUE THREAD

**Issue by HiddenLeveI** [libre-tube/LibreTube#4703]
Hello so I'm trying to use this application on my Android TV, yet I can't click on any of the instance after I download it obviously because TVs aren't touchscreen. So Imma have to plan B it and download an instance to put on there, where do I find these instances? Thank you in advance

**Comment by Bnyro** [comment]
You can't download an instance?!

**Comment by Bnyro** [comment]
Just use piped.video in a browser on your TV.
