### ISSUE TITLE
App stuck in audio player window

### ISSUE THREAD

**Issue by Manish8580kumar** [libre-tube/LibreTube#4708]
### Steps to reproduce

After shifter from video to audio mood in app to listen to music after some time or songs the window get stuck in the player mood and does not go back to normal video player mood and to get it back to the normal video player mood you have to kill the app and relunch it then it work fine

### Expected behavior

Should easily shift from video to audio player and vice-versa

### Actual behavior

It stuck in the audio player mood after some time playing in audio mood and does not go back to video mood

### LibreTube version

0.17.1

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
You need to tap on this

![20230907_174958.jpg](https://github.com/libre-tube/LibreTube/assets/50032603/d162d86f-9af0-4dea-833d-364b417922ad)
