### ISSUE TITLE
Please add audio repeat feature in the audio only mood

### ISSUE THREAD

**Issue by Manish8580kumar** [libre-tube/LibreTube#4709]
### Describe your suggested feature

SIR PLEASE ADD THE FEATURE TO have repeat of current song or audio on audio  only mood and to select the qualiy of audio played in audio only mood

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Issues in capslock don't follow the Code of conduct.
