### ISSUE TITLE
Remove deprecated/removed videos from feed

### ISSUE THREAD

**Issue by MFlisar** [libre-tube/LibreTube#4713]
### Describe your suggested feature

I do follow a youtube channel that does upload videos with temporary names and than renames them (I at least assume this, because I don't think they are uploading => deleting => reuploading their videos). The effect for me is that I do see invalid new videos in my abo feed which is very annoying because I do keep my feed clean and mark all uninteresting stuff as seen to make it vanish and because I see this problem on a daily basis...

Visually I can instantly spot the invalid videos, they all show a black preview, so even without refreshing the feed there seems to be a point where the app already realises, that the video is missing, as it can't load the preview image as following screenshot shows:

![Screenshot_20230908_105018_LibreTube](https://github.com/libre-tube/LibreTube/assets/2437726/35d1b360-aeee-4224-9595-d505ff5c8c48)

**Suggestion**

Such videos could be filtered out, if possible, instantly or I'd suggest, that when refreshing, already listed videos are checked for their existence and if they are not available anymore they should get removed from the feed...

### Other details

If you want to test this, following channel does have the problematic behaviour with their shorts on a nearly daily basis and is also publishing shorts at least once a day: https://www.youtube.com/c/squatuniversity

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by MFlisar** [comment]
For me, an option to enable head request checks for all listed videos in the feed would be ok, I would not mind about the extra traffic.

But coil does support custom targets and you could listen to the error as well, just for your information.

**Comment by FireMasterK** [comment]
I think we should remove these videos from Piped's feed API directly. We have an open issue at https://github.com/TeamPiped/Piped/issues/1451
