### ISSUE TITLE
Color names

### ISSUE THREAD

**Issue by yarons** [libre-tube/LibreTube#472]
### Steps to reproduce

The colors names are:
Guest green
Boat blue
etc.

I'm not sure how am I supposed to translate these as it makes no sense and it also requires some consistency in terms of first letter of the adjective is the first letter of the color, am I correct? Any suggestions?

### Expected behavior

None

### Actual behavior

None

### LibreTube version

Irrelevant

### Android version

Irrelevant

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It's not a bug lol. Just name them like green, blue, ...

**Comment by Bnyro** [comment]
Or just imagine any funny color names xD
