### ISSUE TITLE
Reduce Tab content loading atleast till Runtime 

### ISSUE THREAD

**Issue by NeeRaj-2401** [libre-tube/LibreTube#4731]
### Describe your suggested feature

whenever we switch between tabs such as home, subscription, library. Everytime we notice that there is a bit loading ( delay ) . Even if we have just switching back to a perticular tab.

Feature: hold the loaded tab contents atleast till the app run time. To make better stability and smoother UX

### Other details

I am not sure, but if its currently making api request everytime on tab switching, then in that case, this issue would reduce the unnecessary hitting of api endpoints as well

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by NeeRaj-2401** [comment]
Addition: even if we have searched something in one tab, and switching to another, it should hold that searched data to that tab so that we can come back to it

**Comment by Bnyro** [comment]
That's what we already do for subscriptions. Most trivial responses are cached at server side, and it would be inconvenient if the playlists for example wouldn't update automatically when you go to the library.

**Comment by NeeRaj-2401** [comment]
@Bnyro , the home tab contents atleast trending / use created playlists
 should be cached, cause it loads same content again and again whenever i am switching to home tab
