### ISSUE TITLE
minimize option on audio player dissapears after sometime when playing in background in playlists

### ISSUE THREAD

**Issue by pokegamer5547** [libre-tube/LibreTube#4733]
### Steps to reproduce

1. Go to playlists
2. Play a video using "play in background"
3. Let it play few seconds and keep maximizing and mimizing the audio player.
4. The minimize button randomly dissapears.

### Expected behavior

It should always be possible to minimize

### Actual behavior

The minimize button dissapears after minimizing and maxiziming the audio player for sometimes.

### LibreTube version

0.17.1

### Android version

android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#4114
