### ISSUE TITLE
allow swiping down in audio player to minimize audio player

### ISSUE THREAD

**Issue by pokegamer5547** [libre-tube/LibreTube#4734]
### Describe your suggested feature

Currently to minimize the audio player, you'll have to use either the back button at top left corner or use the back button/gesture of your phone instead.
I suggest having ability to minimize the audio player by swiping down since we can do that with video player too. Also it feels bit inconsistent when audio player can be brought by swiping up but can't be minimized by swiping down.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#2020

**Comment by dAtA-TRoN** [comment]
I would like that too. It just feels natural.

**Comment by dAtA-TRoN** [comment]
I would like that too. It just feels natural.

**Comment by StevenAlexander44** [comment]
Would be nice to have this if #4114 cannot be fixed easily, but that seems unlikely.

**Comment by akashs056** [comment]
I am On it
