### ISSUE TITLE
Jank when opening subscriptions

### ISSUE THREAD

**Issue by FineFindus** [libre-tube/LibreTube#4751]
### Steps to reproduce

1. Visit the Subsciption tab
2. Expand the subscriptiob list

### Expected behavior

The subscription list should animate to it's open state and show the subscriptions.

### Actual behavior

The app freezes when trying to load a larger amount of subscriptions (200+) leading to a degraded user experience.

### LibreTube version

0.17.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/4640
