### ISSUE TITLE
Add machine translation of subtitles from Google translator

### ISSUE THREAD

**Issue by Official-Mlx** [libre-tube/LibreTube#4761]
### Describe your suggested feature

![Screenshot_2023-09-12-01-26-03-454_com github libretube](https://github.com/libre-tube/LibreTube/assets/74877307/791f21c2-3a3a-419a-93cd-be74c90b6bb7)

If in this part, you can design an interface that can translate subtitles into different languages, you have created a revolution that has been somewhat unprecedented in YouTube.
Also, creating such a feature only requires a Google translator library and is very simple!
Thank you if you add this feature to the app, it will be very, very popular and much needed.

### Other details

Using the library and API of Google translator, which is both fast and easy to work with!

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's out of scope for the project.
