### ISSUE TITLE
Keyboard did't poping up!

### ISSUE THREAD

**Issue by KSinghofficial** [libre-tube/LibreTube#4765]
### Steps to reproduce

    Install libretube from armeabi-v7a-debug-signed.apk
    search something in searchbar , yes the keyboard will pop up.
    press search
    now tap searbar now, the keyboard did't pop up on second time.

video recording at https://github.com/codnap/codnap.github.io/tree/main/public/xw

### Expected behavior

keyboard should pop up in second time when tabed the searchbar.

### Actual behavior

keyboard did't pop up on second time when tabed the searchbar.

### LibreTube version

Nightly builds

### Android version

8.1.0 Go

### Other details

video recording at https://github.com/codnap/codnap.github.io/tree/main/public/xw

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/4687#issuecomment-1707970641


+ try with another keyboard (install any keyboard from whatever source you want and try again)
