### ISSUE TITLE
Show video preview in thumbnails

### ISSUE THREAD

**Issue by Myzel394** [libre-tube/LibreTube#4768]
### Describe your suggested feature

The official YouTube app shows a preview of the video in the thumbnail if you look at it for a few seconds. LibreTube should add that too with the option to disable and enable it in the settings.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Myzel394** [comment]
> IMO, it should be only available if Alternative videos layout is enabled and Grid columns is set to 1. Nobody would like to see tons of previews across the feed.

Yes, agreed. I didn't think of that because I just use the default layout :D I'd also recommend only previewing one video at the time, the most centered one. This isn't TikTok.

**Comment by Bnyro** [comment]
That's not planned.
1. It's hard to implement on a UI level.
2. It requires a lot of changes at the Piped backend or we require multiple API requests to load that video, which would be slow.
3. I myself consider this as one of the most useless features of YouTube.

If you don't want to get clickbaited, enable DeArrow, but that video preview thing is really culprit.
