### ISSUE TITLE
After changing icon on Pixel Launcher, it shows "App not installed

### ISSUE THREAD

**Issue by jeffdumcum** [libre-tube/LibreTube#477]
### Steps to reproduce

Change icon and try to reopen libretubr

### Expected behavior

It should just change icon

### Actual behavior

It shows app not installed

### LibreTube version

Can't check

### Android version

Android 13 beta 3.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Hmm, I don't have an android 13 device. I tried it with the emulator on Android 13 and it worked just fine. Could you send me debug logs maybe?

**Comment by jeffdumcum** [comment]
Never mind, it works after a restart

**Comment by Bnyro** [comment]
Okay, I'll close the issue then, it's probably an android beta issue and not only a LibreTube only issue.
