### ISSUE TITLE
Parse YouTube links in search bar 

### ISSUE THREAD

**Issue by hanimebeast** [libre-tube/LibreTube#4774]
### Describe your suggested feature

While pasting the youtube link into search bar, the video results rendered. but in case of the provided link with arguements(?foo=bar), args should be automatically split and  link should be filter and the resulting result should render because arguement makes the backend error and no result found!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FineFindus** [comment]
This is also how the official YouTube search handles it, adding an unknown parameter to the searched URL, will return no result.
![YouTube Seach wuth no result](https://github.com/libre-tube/LibreTube/assets/63370021/4cce0e15-4957-4c7c-88a7-6830688090b9)

**Comment by vvkdev** [comment]
Not all arguments should be splitted, imo. For example, a time argument (&t=) should not. It would be nice if the app open video at that time. I think we need to know exactly which arguments to proceed and which to remove.

**Comment by FineFindus** [comment]
YouTube parses both `feature=shared` and `t=2` correctly. That's why I said that it only fails for unknown parameters.

![YouTube search searching for a link](https://github.com/libre-tube/LibreTube/assets/63370021/f8e11d1b-57ec-4561-b64b-d08a49a1287f)
