### ISSUE TITLE
After the app is run, no data is displayed

### ISSUE THREAD

**Issue by richfuns** [libre-tube/LibreTube#4780]
### Steps to reproduce

1. First, download app-arm64-v8a-release.apk 
2. Second, Run the app, and select the first option-official CDN
3. Then, nothing is displayed in every page.

### Expected behavior

The app should be running normally and having data displayed. 

### Actual behavior

After the app is run, no data is displayed in any page. 

Please look at the screenshots I just uploaded below. 

Thank you.

### LibreTube version

0.18.0

### Android version

Android 12

### Other details

![WhatsApp Image 2023-09-15 at 06 20 14](https://github.com/libre-tube/LibreTube/assets/1400999/adf4bb4a-8631-45be-a37e-b3c0e33fac37)

![WhatsApp Image 2023-09-15 at 06 20 13](https://github.com/libre-tube/LibreTube/assets/1400999/97845c30-f9ac-4905-88ee-aee8c8df62b9)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Home tab: Settings -> General -> Region: Select a different one.

The library and subscriptions tab are empty while you didn't yet subscribe to channels of create a playlist.

**Comment by richfuns** [comment]
> Home tab: Settings -> General -> Region: Select a different one.
> 
> The library and subscriptions tab are empty while you didn't yet subscribe to channels of create a playlist.

Thank you for your solution, it really works.
