### ISSUE TITLE
Iam not able to backup my data it shows this message

### ISSUE THREAD

**Issue by theerthrajk** [libre-tube/LibreTube#4783]
### Steps to reproduce

Open the app click backup and restore and click on backup under App Backup heading
![Screenshot_20230915_201914](https://github.com/libre-tube/LibreTube/assets/63943672/5a1f55e0-67fa-4c68-bb2e-3b99cd17d80e)

![Screenshot_20230915_201955](https://github.com/libre-tube/LibreTube/assets/63943672/8bd1797d-ce14-49d6-8f5e-3d4dec8fb71e)

### Expected behavior

It should backup data to a folder

### Actual behavior

It shows an error

### LibreTube version

0.18.0

### Android version

Android 13

### Other details

java.lang.IllegalStateException: Fragment BackupDialog{83b682c} (6cc007ed-cad4-49cf-a0b1-0830d610174a) not associated with a fragment manager.
	at androidx.fragment.app.Fragment.getParentFragmentManager(SourceFile:16)
	at androidx.room.Room.setFragmentResult(SourceFile:6)
	at com.github.libretube.ui.dialogs.BackupDialog$onCreateDialog$2$1.invokeSuspend(SourceFile:126)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
	at androidx.work.Worker$2.run(SourceFile:53)
	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7011efb, Dispatchers.IO]
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Eliya-Manoj** [comment]
https://github.com/libre-tube/LibreTube/issues/4779

The same problem reported 6hrs ago become duplicate and closed.

https://github.com/libre-tube/LibreTube/issues/3427

**Comment by theerthrajk** [comment]
Did the devs do something??

**Comment by FireMasterK** [comment]
> Did the devs do something??

#3427

**Comment by theerthrajk** [comment]
It still does not work!
