### ISSUE TITLE
Play button not working.

### ISSUE THREAD

**Issue by Doktor515** [libre-tube/LibreTube#4784]
### Steps to reproduce

1.Play the video and press the stop button
2.Press the Play button. The video does not play

### Expected behavior

Let the play button work immediately.

### Actual behavior

The button does not respond.The previous stable version did not have this problem

https://github.com/libre-tube/LibreTube/assets/145192390/b9d523a3-7065-4bb4-976a-dc548dbc9608

### LibreTube version

0.18.0

### Android version

Android 12

### Other details

A)1.This problem occurs when I return to the player after background playback is interrupted
2.Sometimes the player stops suddenly while in the application.Sometimes the player stops frequently and the quality drops. The button does not work.
B)Other possible wrongs.
1.Sometimes, when opening a video, the player does not show the loading icon
2.The bottom panel sometimes does not load

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by DanielProg39** [comment]
I also came across this bug several times. I came to a conclusion that in my case this problem occurs when the video stops for app to load the next chunk. The play button is inactive during loading and stays inactive after the chunk is loaded, without changing its state when the video is stopped and the button is showed again.
Here's my screen recording showcasing this bug along with #4785 


https://github.com/libre-tube/LibreTube/assets/63293432/4a85b00e-f480-4c4b-b524-3cde010c7295
