### ISSUE TITLE
System Notification Player Displays Loading Icon Instead of Play/Pause Icon for Video Playback

### ISSUE THREAD

**Issue by DanielProg39** [libre-tube/LibreTube#4785]
### Steps to reproduce

1. Open a video
2. You can pause it (not necessary)
3. Open notification panel

### Expected behavior

The system notification player should accurately reflect the playback status of the video by displaying the appropriate play or pause icon.

### Actual behavior

The system notification player incorrectly shows a loading icon instead of a play or pause icon, regardless of the video's playback status.

### LibreTube version

LibreTube Debug for e36656e

### Android version

Android 13

### Other details

This bug occurs almost randomly, I haven't found any traces of what actually causes it, so it's pretty hard to catch. Here are two times I managed to record it:

https://github.com/libre-tube/LibreTube/assets/63293432/0907e9ab-22d2-44f9-8921-320dc083f1c8

https://github.com/libre-tube/LibreTube/assets/63293432/72026d57-4aae-4f8d-96ed-795f68fc355a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/4470
