### ISSUE TITLE
Permanent notification that cannot be killed

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#4787]
### Steps to reproduce

1. Play a video
2. Close the video
3. Close the app

Then there still is a notification for that video. However, the buttons in that notification do not even work. I believe this is a failure to kill the notification.

### Expected behavior

There should be no notification when I manually kill the video.

### Actual behavior

Permanent notification

### LibreTube version

0.18.0

### Android version

Android 12 (lineageOS)

### Other details

Here is a video:

https://www.swisstransfer.com/d/c57bde7a-da69-4a98-8c32-08200909e76a

(video available for only 30 days. too large to share via github)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by mhosem** [comment]
I have the same problem with version 0.19.0 in Android 13 MIUI 14.0.4!

**Comment by mudassirzulfiqar** [comment]
Hi @Donkey-Doug is this still open of fixed?

**Comment by kaibagley** [comment]
I am having this problem on the latest GrapheneOS (AOSP 14) On Pixel 7 Pro

**Comment by Donkey-Doug** [comment]
> Hi @Donkey-Doug is this still open of fixed?

This is still open

**Comment by Donkey-Doug** [comment]
Additional info:

My phone is connected to my laptop with kde connect. This means it is synced, including notifications. When I use libretube on my phone while connected to my laptop, every action creates a new notification message. For example, if I pause the video I get a notification on my windows laptop, if I fast forward I get a notification on my windows pc. I think there is a minor flaw in the notification logic of libretube. No other app does this.

**Comment by mudassirzulfiqar** [comment]
@Donkey-Doug thanks for the additional information, I tested it on my Samsung galaxy s 20, It worked for me. Let me try to review the code.

**Comment by Donkey-Doug** [comment]
I just bought a new phone. It fails on both devices. But please note that I am using lineageOS without google play on both devices. This issue is present on android 11, 12 & 13.

**Comment by Donkey-Doug** [comment]
> I am having this problem on the latest GrapheneOS (AOSP 14) On Pixel 7 Pro

Might be an issue for AOSP based ROMs then.

**Comment by akano12** [comment]
I wish i had your issue XDDD. In my case, the notification controls won't persist lol.
https://github.com/libre-tube/LibreTube/issues/4594
