### ISSUE TITLE
Picture-in-picture/pop up player buttons not functioning.

### ISSUE THREAD

**Issue by Snailhail** [libre-tube/LibreTube#4794]
### Steps to reproduce

Bring any video up.
Touch pop-up to display picture in picture player.
Tap bottom of player to pause video, or double tab either side fast for rewind & forward skip.

### Expected behavior

The PIP player buttons while invisible should allow you to pause the video, rewind & skip 10 seconds.

### Actual behavior

Bottom button visible when tabbed along with rewind & forward not functioning as well with no cues.

### LibreTube version

0.18.0

### Android version

13

### Other details

My memory hazy, but I'm certain enough the PIP buttons worked in prior versions.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Snailhail** [comment]
I did a system restart & enable auto rotation. It fixed my problem completely. If noone else has this problem then this should be manually closed. Since it might be a user issue.

**Comment by ahmedKhalid1** [comment]
It happens to me too on Android 13

**Comment by Bnyro** [comment]
I've only had this issue a while ago when I've been running multiple different apps that support PiP simultaneously or after each other.

It seems like that leads to an issue, that messages are forwarded to the wrong app (e.g. Cloudstream instead of LibreTube).

**Comment by ahmedKhalid1** [comment]
https://github.com/libre-tube/LibreTube/assets/30199198/550b5044-8ae5-4755-999c-3e25c1f8bcff

It happens despite having no other apps open at the same time.

**Comment by Titaniumtown** [comment]
I can reproduce on my pixel 7 running grapheneos and libretube 0.18.1

**Comment by RafaelsRamos** [comment]
Has anyone experienced this issue in the previous couple of months? (I didn't)

If no one has, maybe it's time to close it 🤔

**Comment by ahmedKhalid1** [comment]
they're working fine for me on 0.21.0
