### ISSUE TITLE
Playback cannot be resumed after a pause.

### ISSUE THREAD

**Issue by nanedi** [libre-tube/LibreTube#4803]
### Steps to reproduce

Playback cannot be resumed after a pause.
1. PAUSE,
2. LOCK THE SCREEN,
3. UNLOCK THE SCREEN,
4. Then . 

### Expected behavior

Pause, and play. 

### Actual behavior

Playback cannot be resumed after a pause.

### LibreTube version

0.18.0

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/4784

And fixed in https://github.com/libre-tube/LibreTube/pull/4797

**Comment by nanedi** [comment]
Thanks
