### ISSUE TITLE
SponsorBlock not functioning despite being enabled.

### ISSUE THREAD

**Issue by dAtA-TRoN** [libre-tube/LibreTube#4805]
### Steps to reproduce

Play a video that contains sponsor segments.
Let the video play and wait for sponsor markers.

### Expected behavior

SponsorBlock while active should recognize sponsor markers and skip them.

### Actual behavior

The SponsorBlock extension fails to detect sponsor markers in the video. Sponsor segments are not skipped.

https://github.com/libre-tube/LibreTube/assets/71184627/965bfee6-9e50-4469-997c-42cdb38bafc7

### LibreTube version

0.18.0

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Did you set sponsor block to actually skip those segments not just show them in seekbar?

**Comment by dAtA-TRoN** [comment]
> Did you set sponsor block to actually skip those segments not just show them in seekbar? 

> Could you please recheck your settings to see if `Automatic` skipping is selected from each drop-down menu for all segment types in Sponsorblock settings?

Oh wow, okay now it works again.I must have accidentally set it wrong at some point.Thanks for your quick help.
