### ISSUE TITLE
Returning to channel group from other tabs gets wrong group selected 

### ISSUE THREAD

**Issue by SameenAhnaf** [libre-tube/LibreTube#4806]
### Steps to reproduce

1. Access any channel group other than `All`
2. Search any video or access any tab other than subscriptions.
3. Return to subscriptions.

### Expected behavior

Previously selected channel group should remain selected 

### Actual behavior

`All` channel group gets selected. But feed from only previously selected group is shown.

### LibreTube version

0.18.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I only fixed that it shows the wrong group now, remembering the selected group is already part of your other subscriptions group improvements issue.
