### ISSUE TITLE
SponsorBlock submit java error: Unable to create converter

### ISSUE THREAD

**Issue by unbranched** [libre-tube/LibreTube#4813]
### Steps to reproduce

1- click the SponsorBlock submit button on a paused video
2- insert the details, start time, end time, genre. Click Ok
3 - Error occurs

### Expected behavior

Expected the SponsorBlock segment submission.

### Actual behavior

A Libretube error occurs:
`
Unable to create converter for java.util.List <java.lang:Object> ...`

![bug](https://github.com/libre-tube/LibreTube/assets/39440265/9c5c5a90-4123-4c7d-8f4c-ec19c466260a)

### LibreTube version

0.18.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Fyi, even though there's an error message like that, segments get submitted successfully. The error message will stop appearing with the next release.
