### ISSUE TITLE
Watch history + remember position

### ISSUE THREAD

**Issue by laur89** [libre-tube/LibreTube#482]
### Describe your suggested feature

**As-is:**
There's no effortless way of tracking videos you're watching or have recently seen. For instance, just had a case where I was in a middle of a video, had to stop for some time, and when returning the video was already closed. Now I had to
a) search for the video again
b) figure out where it was left off

**To-be:**
Similar to original Youtube app, it would be great if there was a `History` section under Library tab, showing the last X (TBD exactly how many) videos you've watched. Additionally, those videos' progress should also be stored for easy continuation.

### Other details

Does this imply the work should really be done on the Piped side of things?
_LibreTube 0.3.1, running Android 11._

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Flam3z** [comment]
A must have 🙏

**Comment by lucamp** [comment]
However, please add it to the main page close to feed and library, as NewPipe does.
Option to reorder tabs would also be nice

**Comment by lucamp** [comment]
Could history be synchronised if logged in your piped instance?

**Comment by Bnyro** [comment]
Piped doesnt support it

**Comment by laur89** [comment]
> However, please add it to the main page close to feed and library, as NewPipe does. Option to reorder tabs would also be nice

Haven't used NewPipe so can't comment on it, but I'd be perfectly happy if it's implemented similar to Youtube, ie you'd have a `History` section under the `Library` tab.

Alternatively, it could be an independent tab on its own (ie in addition to the existing `Home`, `Subscriptions` and `Library`). Then make visible tabs configurable (eg I might not care for Library tab, and choose only `Home`, `Subscriptions`, and new `History` tabs to be listed at the bottom bar), and also allow this tab to qualify for the `Default Tab` spot.

**Comment by Nephys222** [comment]
@Bnyro Can Watch history recorder via room library? As well as Search history. Does current solution for storing history with Shared preferences temporary?

**Comment by Bnyro** [comment]
@Nepys222 The watch history is currently stored in the shared preferences as a json string as you can [see here](https://github.com/libre-tube/LibreTube/blob/master/app/src/main/java/com/github/libretube/preferences/PreferenceHelper.kt?plain=1#L155-L198).

**Comment by Nephys222** [comment]
@Bnyro I understand. Thanks for reply. What is your opinion about its usability for long term. Does adding Room lib will make the app robust?

**Comment by Bnyro** [comment]
@Nephys222 Hmm, I don't think we really need to do changes here. Using a database should be about the same in terms of speed as using the shared preferences. Apart from that the watch history is already stored in the shared preferences and I don't want them to lose it.
