### ISSUE TITLE
Test SB segment before submitting

### ISSUE THREAD

**Issue by vvkdev** [libre-tube/LibreTube#4820]
### Describe your suggested feature

Add 'Test' button to the SponsorBlock submitting dialog.
When click play video from 'BeginTime - 3(5) sec' to 'EndTime + 3(5)sec', skipping the estimated segment without closing dialog.
This will allow to view the result before it is finally sent and do some time correction.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please look if #4710 would solve this too, and otherwise suggest it over there.
