### ISSUE TITLE
FR: add version to Settings->About

### ISSUE THREAD

**Issue by laur89** [libre-tube/LibreTube#483]
### Describe your suggested feature

Settings -> About should contain information about the current version of the installed app.
Currently there's no quick&easy way to check which version is installed; might be an issue when users report bugs.

### Other details

LibreTube 0.3.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Will be there in the next update, including a feature to check for new updates :)
