### ISSUE TITLE
Improve long press menu 

### ISSUE THREAD

**Issue by SameenAhnaf** [libre-tube/LibreTube#4831]
### Describe your suggested feature

- [x] 1. Stick `Share`, `Add to Playlist` and `Download` options at the bottom and fit to width.
- [ ] 2. Improve `Add to Playlist` UI by adding checkboxes similar to screenshot instead of a drop-down menu. 
- [ ] 3. Add a checkbox *Detect duplicates* in settings to warn users if the video is already added to any playlist. The warning should be like `1 and 3 duplicate(s) are already added to X and Y playlists respectively` and have four options:
"Keep All", "Replace" and "Cancel"
Note that duplicates should be searched for newly selected playlist(s) as mentioned on previous point.

- [ ] 4. Show `Play Next` only if
(A) Multiple videos are in the queue.
(B) Auto-queue new video is enabled or last video on the queue is not being played.
Show only `Add to Queue` in such cases.
- [ ] 5. Show `Select more` to enable bulk selection.
*Share*: Create an annonymous YouTube playlist (supported upto 50 videos)
*Add to Playlist*
*Download*
- [ ] 6. Show apps, time code and video platform (YouTube/Piped) as radio buttons within a single share page. Btw, SnapTube has the ability to access the option to show such apps.

### Other details

![Screenshot_20230922-084439](https://github.com/libre-tube/LibreTube/assets/79245641/19e68164-f62f-4d9a-be67-68adf2a192d5)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
2., 3. and 5. require changed at the Piped backend first, otherwise this would lead to a very awful performance at client side due to one extra network request per playlist.

6. Please elaborate on that, I'm not really sure what you mean by that.

And **please**, as I've already said earlier, open one issue per suggestion, and not issues with a list of ideas - it just makes it more difficult to track single issues.

**Comment by Bnyro** [comment]
Closing for the given reasons.
