### ISSUE TITLE
Improve This

### ISSUE THREAD

**Issue by imShanty** [libre-tube/LibreTube#4832]
### Describe your suggested feature

1) Video Or Audio Should Be Directly Downloaded On Download Folder....( ISSUE : We Can't Delete All Downloaded Video At Once.)
2) Make A Homepage Videos Layout Like Real Youtube. We Dont Like 2x2 Videos Layout In Front Page Of Libratube.
3) Video Should Be Play When We Are On Call..(Just Like Real Youtube)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
All of the issues are duplicates, just search the open issues yourself.
