### ISSUE TITLE
SponsorBlock segments for downloaded videos

### ISSUE THREAD

**Issue by topminipie** [libre-tube/LibreTube#4835]
### Describe your suggested feature

In the video download menu, add the option "Save SponsorBlock segments"

### Other details

Segments will be saved locally

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Closing due to invalid usage of issue template.

**Comment by Bnyro** [comment]
Lack of explainations.

**Comment by Bnyro** [comment]
You literally added one sentence. Example of a good issue: https://github.com/libre-tube/LibreTube/issues/4575
