### ISSUE TITLE
Adding an option to hide shorts from being displayed

### ISSUE THREAD

**Issue by divi0001** [libre-tube/LibreTube#4837]
### Describe your suggested feature

Something like a button in the main settings where you can specify, that you don't want to see/only want to see YouTube shorts. (For me I don't want to see them or get them as recommendations/shown in subscriptions page)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/3836

+ no api support
