### ISSUE TITLE
Blurry thumbnails on related videos

### ISSUE THREAD

**Issue by MF-Debug** [libre-tube/LibreTube#4838]
### Steps to reproduce

Play any videos, scroll down to see related videos. The thumbnails are not in high-quality like below -
![Screenshot_20230920-211326_LibreTube](https://github.com/libre-tube/LibreTube/assets/6173607/d5347883-b3c1-4d17-a927-8ef6261cb9f6)

### Expected behavior

The thumbnails should be rendered in high-quality.

### Actual behavior

Thumbnails are rendered in such low-quality like this -
![Screenshot_20230920-210949_LibreTube](https://github.com/libre-tube/LibreTube/assets/6173607/2b5e7a67-26d9-47e8-8948-34af7c11095c)
![Screenshot_20230920-211229_LibreTube](https://github.com/libre-tube/LibreTube/assets/6173607/e4f93ca1-8900-4fd6-809a-f95c4c7391d3)

### LibreTube version

0.18.1

### Android version

Official LOS 18.1

### Other details

Device: Samsung Galaxy Note 3 SM-N9005

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/4483
