### ISSUE TITLE
Add sorting to search and channels

### ISSUE THREAD

**Issue by lu4p** [libre-tube/LibreTube#4839]
### Describe your suggested feature

In the offical app search results can be sorted, the same applies to channel pages. (arguably it's even more useful to sort a specific channel)
![Screenshot_20230923_195023_YouTube](https://github.com/libre-tube/LibreTube/assets/46541492/99e14f00-d782-4d13-ba03-990c7a3d76b6)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Not possible atm
