### ISSUE TITLE
Make Export/import without an account

### ISSUE THREAD

**Issue by b1gb0y123** [libre-tube/LibreTube#484]
### Describe your suggested feature

I'm one of those who don't like to save stuff online, do you consider making the app fully usable without the account requirement ?
Btw, I know newpipe exists.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

**Comment by laur89** [comment]
Doubt they'd do it, as they rely heavily on Piped, and your account is also really a Piped account.
Which means the overall architecture of LT would need to change.

**Comment by FireMasterK** [comment]
I created Piped as NewPipe's ways to fetch new videos was too slow. It's more an architectural disadvantage of NewPipe. (I didn't like having to wait 5-10 seconds each time I wanted to refresh my feed.)

**Comment by Bnyro** [comment]
I currently don't see a way for us to do this

**Comment by b1gb0y123** [comment]
Ok then

**Comment by b1gb0y123** [comment]
> I currently don't see a way for us to do this

Ok then
