### ISSUE TITLE
Filter search by Upload date

### ISSUE THREAD

**Issue by lu4p** [libre-tube/LibreTube#4840]
### Describe your suggested feature

I miss filtering out old videos from search, this is useful to get up to date information on a variety of topics.
![Screenshot_20230923_195931_YouTube](https://github.com/libre-tube/LibreTube/assets/46541492/7265252e-adda-4e4f-bfac-4b4d7c90554b)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/3682
