### ISSUE TITLE
"Pause on exit" setting disappears and isn't applied

### ISSUE THREAD

**Issue by Kalytis** [libre-tube/LibreTube#4846]
### Steps to reproduce

1. Activate the "Pause on exit" setting
2. Exit the app
3. Test the setting

### Expected behavior

Video should pause on app exit.

### Actual behavior

Video continues playing. Upon checking the settings, the relevant setting disappeared.

### LibreTube version

0.17.1

### Android version

Android 13

### Other details

![Screenshot_20230925-002722_LibreTube](https://github.com/libre-tube/LibreTube/assets/31107370/fb47c7cc-cc10-4e82-8add-d07505668c9b)
![Screenshot_20230925-002736_LibreTube](https://github.com/libre-tube/LibreTube/assets/31107370/6235e51c-4be6-4e05-b6dc-acaa69874f28)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Can't reproduce + update to latest version and report back

**Comment by Kalytis** [comment]
Didn't know a newer version was available as it wasn't on F-droid.

Seems to have fixed it, thanks.
