### ISSUE TITLE
save music locally pls

### ISSUE THREAD

**Issue by Prohect** [libre-tube/LibreTube#4852]
### Describe your suggested feature

U see that in the Settings -> general, we have a option to set libretube to a music player
when we play music, for most of the time, we might have the screen off, 
and here comes the problem: some phones have a strategy that when the screen is off, It will cut off almost all the network io streams to decrease the energy consuming, and then, the music will only be played for the buffered parts until its pausing.
Since the audio part of one YTB video seems much smaller than the storage of one phone, I suggest that
u can **add a function that can auto download the audio part to a buffered area when playing a vedio in "Audio only mode" with its options like:the boolean of this function, how much storage can this function use,** 
Btw, **_one-click to buffer all audios of one selected playlist would be really cool_**

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It's a one click action to switch to the audio only mode before turning off the screen. That circumvents the battery restrictions and hence should be used for playing with screen off.
