### ISSUE TITLE
In "Audio and Video" Settings page the "Best Quality" option is missing.

### ISSUE THREAD

**Issue by orbitneon** [libre-tube/LibreTube#4855]
### Describe your suggested feature

Currently it only shows 2 options:
1. Auto
2. Worst

How it should be:
1. Best Quality
2. Worst Quality
3. Auto

### Other details

https://matrix.to/#/!ldChLrUEFGyImBrtnv:matrix.org/$dCv2FfYHzrzFYCZC7GEJavRNmOCOYbpee_igWJG1vAg?via=matrix.org&via=envs.net&via=tchncs.de

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Unfortunately, the ExoPlayer currently only allows us to set an upper limit of the bitrate, but it doesn't allow us to set a minimum bitrate which would be needed to always choose the best audio quality.

We could also manually pick audio tracks, but that wouldn't really be easy to implement and maintain.
