### ISSUE TITLE
App hiding entire local subscriptions and playlists after login 

### ISSUE THREAD

**Issue by Eliya-Manoj** [libre-tube/LibreTube#4877]
### Steps to reproduce

1. Create Local playlist and subscribe channels
2. Create account
3. Login 
4. App hides Local Subscription and Playlists

https://github.com/libre-tube/LibreTube/assets/90308888/df4b8af3-c379-48b1-81e6-196fb7e12e7b

### Expected behavior

Show Subscriptions and Playlists

### Actual behavior

Hide Subscriptions and Playlists. After logout - Subscriptions and Playlist appears

### LibreTube version

Latest Debug

### Android version

Android 12

### Other details

Feature Request - Sync with Piped account is good because, Existing Playlist and Subscriptions are difficult to transfer to the account 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Export playlists and subscriptions, log in, import playlists and subscriptions. Done.
