### ISSUE TITLE
Dragable Captions On Full Screen Mode

### ISSUE THREAD

**Issue by KSinghofficial** [libre-tube/LibreTube#4879]
### Describe your suggested feature

Some times captions covers the screen text that I want to view,
YouTube mobile application have a feature to automatically shift captions when text appears behind the captions but implementation of this feature might be different, so
make dragable captions in full screen more , This feature by default should be off 
Users can navigate to settings > Player > Behavior to turn on this feature.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
There are no plans to support this currently - it'd just be a lot of work or not even possible to support properly.
