### ISSUE TITLE
Android 13 button to listen or watch next video in a playlists doesn't work

### ISSUE THREAD

**Issue by gpdevsoft** [libre-tube/LibreTube#4882]
### Steps to reproduce

Create a playlist

Listen in background the playlist

open the screen showing list of videos playing in background

Tap on button to advance to the next video

### Expected behavior

plays next video in the list

### Actual behavior

nothing is happening

### LibreTube version

0.18.1 and earlier

### Android version

Android 13

### Other details

Samsung galaxy smartphone 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please share a screen recording.

**Comment by gpdevsoft** [comment]
https://github.com/libre-tube/LibreTube/assets/14260912/e8807286-e5f5-48a9-af49-e93d2f5bc14f

I have created a playlist test wirh 3 video to listen them in background.

**Comment by Bnyro** [comment]
fixed in #4985
