### ISSUE TITLE
Add a "choose instance" quick button

### ISSUE THREAD

**Issue by andreamagnone** [libre-tube/LibreTube#4888]
### Describe your suggested feature

When an instance stops working you have to click the three dots, then "settings", then "instance" and finally "choose". This entire process can be reduced to a single step by simply adding a quick button near the search lens.

![chooseinstance_quick_button](https://github.com/libre-tube/LibreTube/assets/146837730/6ec41ae4-800e-4ed2-8780-db19643fcd59)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
> Hi @andreamagnone, can you assign this to me? I'd like to work on it.
> 
> Regarding the "new instance" button, should we show the "choose option" on click or the whole instance screen with all options?

Before you work on this I suggest you ask the project maintainer if he wants this feature added, i myself find it useless and there's no point in duplicating options in the app.

And if it's to he added, it's better to add it below 'Settings' in the kebab menu and remove from settings

**Comment by Bnyro** [comment]
You can work on any other open issue if you want to - we have enough of that - but this one is a bit critical in my opinion.

**Comment by MorningNumber2** [comment]
> I'm not really a fan of this honestly, neither are instances meant to be changed by the user every few minutes nor should settings be spread across the app.
> 
> Adding such a button to the top bar basically tells users that instance are unreliable by design and defeats the point of using a Piped account.
> 
> I'd prefer keeping this for discussion before anyone actually spends time working on this.

Instances are unreliable. It doesn't work for me most of the time. Even when I disable piping, the app doesn't even load videos or let me search. This is a terrible design and concept.

**Comment by Bnyro** [comment]
I haven't changed the instance I use a single time within the last month (self-hosted), so generally Piped does not have such issues. Of course, if instances are overloaded, there can be issues, but in such cases that's nothing that needs to be addressed at client side.

**Comment by qokrb2t** [comment]
Clearly there's a mismatch b/w the expectation & the result for different people. Either 1) the how-to-use isn't good-enough or 2) there's an issue with the public-hosts at managing load or reporting it
Agree the dev sees it as a non-issue with the app, but it can't be denied that problem is left unsolved

**Comment by MateusAuri** [comment]
I've been having similar issues to @andreamagnone and @MorningNumber2
I end up having to randomly change instances every once in a while to get things to work. Sometimes specific videos won't play, or any videos at all, or the subscriptions tab will refuse to load... these can come either as a hard crash or as a "_server issue, try another instace_" message. All of this happens even while "disable piped proxy" is turned on.

I've just read this [issue discussion](https://github.com/libre-tube/LibreTube/issues/4491#issuecomment-1679663810), though. I tried switching back to the official kavin rocks instance, and then changing the library sorting order to something else and then back to "newest". Seems to have fixed my problems for now. I'll report back here later if this fix works in the long run.

**Comment by MateusAuri** [comment]
> I don't know if this is just a coincidence but with the new version (0.19.0) I no longer have this issue. All videos work perfectly fine and I don't have to constantly switch instances anymore.

Good point, this made me realise that I thought I had the latest version, but I forgot about the F-Droid delay... I'll try reinstalling from the github releases and see if stuff works again.

**Comment by MateusAuri** [comment]
> "There seems to be a problem with the selected server. Try another instance."

Nope, still getting some "There seems to be a problem with the selected server. Try another instance." errors both in the subscriptions tab and in some videos, Right after reinstalling. 😩
Same scenario as before, fresh start, kavin.rocks, didn't mess with any instance option.

If it helps identify anything, I'm on a Samsung Galaxy A32 running Android 13 (not rooted) and connecting from Brazil.

**Comment by Bnyro** [comment]
> kavin.rocks works perfectly fine for me, has anyone else fixed this issue by simply updating to v. 0.19.0?
>
That's likely a coincidence, the update itself can't improve the server reliability :)

**Comment by Bnyro** [comment]
I don't really think so, the crashes on our side shouldn't impact the server reliability.
