### ISSUE TITLE
Editing channel groups temporarily adds duplicate groups

### ISSUE THREAD

**Issue by MatsG23** [libre-tube/LibreTube#4914]
### Steps to reproduce

1. Open the subscriptions tab
2. Click on the edit button for the channel groups
3. Click on the edit button for any channel group
4. Change something / leave everything as it was
5. Close the sheet using the confirm button

### Expected behavior

The amount of channel groups should stay the same because you just edited an existing channel group.

### Actual behavior

A duplicate group is created. This is shown in the channel group panel and the subscriptions tab header.

### LibreTube version

0.19.0

### Android version

Android 13

### Other details

**Any changes are still made to the actual channel group, not only to its copy.** The duplicate channel groups are removed when restarting the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by E0697** [comment]
The edited group is moved to the bottom as well (after the duplicate is gone on app restart).
