### ISSUE TITLE
Can't install apk from github - conflicting package

### ISSUE THREAD

**Issue by MFlisar** [libre-tube/LibreTube#4920]
### Steps to reproduce

* install apk from f-droid
* try to install newer version from github 

### Expected behavior

Apks should be updatable from all sources...

### Actual behavior

Installation fails with a message telling me that the package is in conflict with an existing package...

Package name of the apks are the same so why does it fail? I know it fails if content providers are different with the same error but as the package names for github and fdroid are the same I wonder if this is a desired behavior and why it is like that...

### LibreTube version

0.18.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
F-Drpid signs apks with a different key than we do, hence you either need to uninstall the app first or wait for F-Droid to pull the update.

**Comment by MFlisar** [comment]
Did not know that they sign the apk themselves...Thanks for the information.

**Comment by shrimprugbysnowowl** [comment]
Apologies for commenting on a somewhat old, closed issue, but thought this might be valuable for future issues - a "conflicting package" error can also be given if the user is attempting to install the github apk in a secondary user profile but the f-droid version is already installed in the primary user profile.
