### ISSUE TITLE
cannot unpause 10 seconds before end

### ISSUE THREAD

**Issue by gojzdar** [libre-tube/LibreTube#4921]
### Steps to reproduce

1. Download latest build from github 0.19 for arm64 v8a
2. Play any video
3. Go near the end of the video <10s till end ~~, default < 10s, changes with seek increment setting~~
4. Pause the video
5. Try to unpause the video through the unpause button on screen
6. Encounter the bug

### Expected behavior

Unpause the video on click

### Actual behavior

Click animation happens but video is not unpaused. The pause button does not change state

### LibreTube version

0.19.0

### Android version

Android 13

### Other details

I have tried restarting the app.
I previously used a few months old fdroid version, which didnt have this issue, but due to crashes after playing almost any video, i changed to latest github version (i had tried latest fdroid versions but they didnt work and i couldnt rollback to my old version)

When posting the issue i thought it is related to seek increment, but Ive tried changing it again with no difference in behaviour. I seem to have miscalculated when testing the issue.

Also, the skip button which i have enabled has a large delay and sometimes fails to trigger.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
The issue isn't as you described, you can reproduce it by pausing the video while it's buffering.
By doing so, it won't be possible to resume the video.

**Comment by gojzdar** [comment]
Buffering should refer to preloading right?
I tried letting the gray bar reach the end, before pausing and the bug still occured. I watched a video start till end with plenty of time to load the content for later and it still happened. Exactly 10 seconds before the end of the video the unpauseis blocker for every single video out of 20 i tried.
