### ISSUE TITLE
empty space 

### ISSUE THREAD

**Issue by person10301** [libre-tube/LibreTube#4928]
### Steps to reproduce

Remove all tabs

### Expected behavior

there should be no empty space

### Actual behavior

![Screenshot_2023-10-07-17-10-27-30_64ef5fc2000c1caa954c114bb372e1d5](https://github.com/libre-tube/LibreTube/assets/105549221/6ea8ff86-95c0-4272-adde-d5a93349c6b8)

### LibreTube version

0.19.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Duplicate of #2548
