### ISSUE TITLE
Filter option to browse videos based on the time of upload/duration/type

### ISSUE THREAD

**Issue by Embassy4016** [libre-tube/LibreTube#4935]
### Describe your suggested feature

Original youtube app and the youtube website has an option to filter videos based on the time they were uploaded. A similar feature in libretube would be much appreciated.

### Other details

These are the filters I am talking about-
![Screenshot_20231008-222548](https://github.com/libre-tube/LibreTube/assets/140226326/28816206-1b44-450b-bca1-e5149e8390d2)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Not possible at the moment https://github.com/libre-tube/LibreTube/issues/3682
