### ISSUE TITLE
Sync channel groups with the new Piped groups

### ISSUE THREAD

**Issue by zhongkechen** [libre-tube/LibreTube#4937]
### Describe your suggested feature

Piped recently added channel groups, and now LibreTube groups can be synced with it.

This is a reopened issue of #3933

### Other details

No response

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Piper's backend does not yet store channel groups at server side.
