### ISSUE TITLE
In-App Messaging 

### ISSUE THREAD

**Issue by akano12** [libre-tube/LibreTube#4942]
### Describe your suggested feature

Implement some sort of in app messaging that would show announcements/updates to users on app startup

### Other details

This would be really helpful and great in terms of issue management and update tracking.
A good example for this feature is this issue https://github.com/libre-tube/LibreTube/issues/4884, same issue has been reported over 20 times at least despite the issue being pinned. If this existed, the project maintainer/anyone with permissions could've sent an immediate announcement saying something like "currently investigating/fixing problem with xyz", this would hugely reduce the volume of duplicate issues. 

Another good example is again, the same issue. A lot of the duplicate issues were reported with old version of the app, i use LSPosed framework, and usually when there's an update it shows a dialog that there's an update on app start along with the changelog on app startup. 

It's extremely useful feature and would be really helpful to have this implemented 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I see why you are willing to do this and I feel the pain without all those duplicate myself, but in order for your suggestion to work the app would need to connect to a server containing the "news" on each app start, which means 
- I'm pretty sure any privacy oriented people would go crazy du to that - the app should still be completely self-hostable
- if we disables it by default to circumvent my previous point, nobody would probably ever enable this feature

It makes much more sense to let app stores do their thing and just attempt to keep chances of a major breakage as low as possible.

And every user must tick "this is not a duplicate" when creating an issue - so I doubt duplicate issues would stop from being opened even though there's a big warning to update the app (and it should be self-explaining to do that anyways). We should consider adding a checkbox to test debug builds first (although I doubt that would change much either).

**Comment by shuvashish76** [comment]
Against this proposal (see #4627 for reasons), I do agree this feature should be opt-in-disabled by default atleast for F-Droid users. Though personally I'd prefer no update checkers at all.

Anyway it's against F-Droid [Inclusion Policy ](https://f-droid.org/en/docs/Inclusion_Policy/)
> The software must not download additional executable binary files (e.g. addons, auto-updates, etc.) without explicit user consent. Consent means it needs to be opt-in (it must not be harder to decline than to accept or presented in a way users are likely to press accept without reading) and structured in a way that clearly explains to users that they’re choosing to bypass F-Droid’s checks if they activate it.

Otherwise it would require a [Tracking](https://f-droid.org/en/docs/Anti-Features/#Tracking) Anti-Feature tag as per their criteria.
> Checking for updates without your knowledge or permission.
