### ISSUE TITLE
Proxy bypass not working

### ISSUE THREAD

**Issue by ViktorKahu** [libre-tube/LibreTube#4953]
### Steps to reproduce

1) Turn on proxy bypass
2) It doesn't matter if fallback is on or off, the result is the same.
3) Try to use the app.

### Expected behavior

Playlists should load, videos should work.

### Actual behavior

Playlists don't load, videos do not work, black screen, nothing loads.

### LibreTube version

0.19.0

### Android version

GrapheneOS A14

### Other details

Any piped instance does not last for longer than a few hours, it's either down or goes extremely slow. Each time, prior to using Libretube, I have to find an instance that: 

1)  Works; and
2) Is useable due to speed.

A few hours later, same process. It's an extremely inconvenient way to live life, Especially, if you are behind the wheel and the little kid is screaming and demanding cartoons in the back seat.

I wish that piped wasn't useless to the point of resorting to other apps to get anything. But at least should be able to bypass it, can't do that either.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The option only disables the video and image proxy, Piped is still needed for all API requests.
