### ISSUE TITLE
Server not available

### ISSUE THREAD

**Issue by JBapt23** [libre-tube/LibreTube#4958]
### Steps to reproduce

Sorry, theres not step by step

### Expected behavior

Watch vídeos every time i want

### Actual behavior

LibreTube claims that the actual server it's not available and need to try another

### LibreTube version

0.19.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Go to settings->instance then select an instance (server) from the available ones

**Comment by JBapt23** [comment]
Please don't close, i know but why i need to do every time or do it every
few days? NP don't need that step but that client don't have the locked
position for the player
