### ISSUE TITLE
Small feature suggestions

### ISSUE THREAD

**Issue by wzry2580** [libre-tube/LibreTube#4959]
### Describe your suggested feature

I hope to add a little more download function, a small function, you can set the path for downloading video storage, I hope to support the SD card path instead of internal storage, because the internal storage space will be used up sooner or later, so it is more convenient to add SD card storage, and then download I hope there will be a progress bar display, just show the percentage symbol. Currently, there is a file, and the download size is displayed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Only one suggestion per issue, and this one is a list of duplicates.
