### ISSUE TITLE
Share link doesn't use current instance 

### ISSUE THREAD

**Issue by lordkitsuna** [libre-tube/LibreTube#496]
### Steps to reproduce

Use latest master
Set a custom instance
Try to share video link

### Expected behavior

Link should be generated using the current instance url

### Actual behavior

Url defaults to kevin.rocks

### LibreTube version

0.3.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
There's no way we can get the url of the piped instance you selected because we only have their api url, that's why it redirects you to the official Piped instance with your instance as query. As result Piped should use your instance to load the video as far as I know. I already thought about removing the option because it's quite confusing for users.

**Comment by Bnyro** [comment]
Sure, but it would only be available for custom instances then :)

**Comment by lordkitsuna** [comment]
Ah I see what you mean the other built-in instances also do this. Well having it for the custom ones would be nice but I guess it doesn't solve the overall problem

**Comment by Bnyro** [comment]
yep

**Comment by Bnyro** [comment]
The easiest thing would be to just disable the option but that's probably the wrong way :)

**Comment by Bnyro** [comment]
@FireMasterK can we somehow access the URL of the Piped frontend of the instance by only having its api url?

**Comment by Bnyro** [comment]
So I think there is actually no way we can access the URL of the Piped frontend.
Two options: Only enabling it for custom instances, completely disabling it or leaving as it is.
You have the choice although no of the possibilities makes me happy :p

**Comment by Bnyro** [comment]
That's just too much work for such a small feature

**Comment by lordkitsuna** [comment]
Understandable, well custom instances would still be nice to have then. If anyone is seriously bothered by it technically nothing would be stopping them from adding a preexisting instance as a custom too right?
