### ISSUE TITLE
Logo issue

### ISSUE THREAD

**Issue by deepakstark01** [libre-tube/LibreTube#4960]
### Describe your suggested feature

when I add icon of app and logo create release apk 
then getting issue it shows unable  universal/android manifiest to find @drwable/logo 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The app builds fine, we're not supporting people willing to create a fork.
