### ISSUE TITLE
Sometimes Video doesn't plays even after disabling piped proxy

### ISSUE THREAD

**Issue by Jobatphysics** [libre-tube/LibreTube#4964]
### Steps to reproduce

1.If a Video not playing or just went into infinity loop of loading
2. Just try changing proxy instances but still will not play (most of times)
3. Just disable proxy even then video will not play. After sometime app will become just useless and stupid, no video can be played
4. But is playing with newpipe official app without any issue. It means there is something wrong in this application

### Expected behavior

Video shouldn't give any kind of issue if you are loading from official YouTube server. Playing well with newpipe too. It means it's something that's not adopted well from newpipe and is buggy

### Actual behavior

This issue is specific to some channels/videos

### LibreTube version

0.19.0

### Android version

Android 13

### Other details

There should be a direct option to use libretube as same as newpipe, just as an material 3 ui alternative. Also issues are pretty much decreased after last update and fix #4827 but yeah it's still buggy 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
> There should be a direct option to use libretube as same as newpipe, just as an material 3 ui alternative
>
No. As already said million times before, that's out of scope. Instance issues are not meant to be fixed at client side ...

**Comment by Bnyro** [comment]
Just use NewPipe if you don't agree with using Piped.

**Comment by Jobatphysics** [comment]
I am not saying that i have any issue with piped but the issue is when it fails this just makes app useless and you can't play even a single video, so there is any issue definitely, above inl just suggested a way if it's not your goal then it's all correct but my duty was to just to report about issue accepting feature request or not is completely your decision

**Comment by Bnyro** [comment]
LibreTube is an Android client for Piped - there are no plans for any other platforms or extractors.
