### ISSUE TITLE
Option to display calculated total/remaining time when not on 1x playback speed

### ISSUE THREAD

**Issue by Morphior** [libre-tube/LibreTube#4971]
### Describe your suggested feature

It would be great if there was an option to display the total and/or remaining time according to which playback speed you're currently on. For example, if the video is 1 hour long and you watch it on 2x speed, it would display 30 minutes length. My solution to this would be to display the original length as-is and the calculated length in parentheses after it. Or you could have options to only show the modified time, show both, or show just the original. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't think it makes much sense to add this either, it's not that hard to guess the remaining time yourself and we don't really aim to add preferences for such small things - the settings are already very unorganized and difficult to use for new users, so we better don't add any options that are not really making an important difference in usage.
