### ISSUE TITLE
LibreTube crashes on wallpaper change

### ISSUE THREAD

**Issue by LClayville** [libre-tube/LibreTube#4972]
### Steps to reproduce

1. Start playing any video
2. Go to home screen (this puts LibreTube into picture-in-picture mode)
3. Change the wallpaper (this can be through an app, the settings, or from the home screen itself)

### Expected behavior

The picture-in-picture player should continue playing as if nothing changed.

### Actual behavior

LibreTube crashes and does not save the current queue. This requires the user to find the video they were watching in their history and start watching it again.

### LibreTube version

0.19.0

### Android version

Android 14

### Other details

I have tried changing the theming options already. From my testing, it seems that having Material You accents does not change the behavior as I originally thought it might. If you need, I can provide a recording of the behavior.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LClayville** [comment]
For extra context, I am currently running GrapheneOS on Android 14 but I have had this issue happen to me on stock android 13 as well.

**Comment by Bnyro** [comment]
I'm aware of the issue, but we can't do anything against it.
For instance, apps like Cloudstream have the same issue. It's simply because Android recomposes the whole app when the wallpaper changes, and therefore kills all existing views and tries to recreate them, which of course kills the PiP player.
