### ISSUE TITLE
cannot select piped instance on android tv

### ISSUE THREAD

**Issue by Joly0** [libre-tube/LibreTube#4977]
### Steps to reproduce

1. Install Libretube on Android TV (Shield TV 2019 in my case)
2. Start libretube
3. Try to select a piped instance

### Expected behavior

Cannot select an instance, i can only scroll down and click both if the buttons with my remote. There is no way for me select anything. Therefore i cannot procede

### Actual behavior

An instance should be selectable

### LibreTube version

0.19.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Android TVs are not supported.
