### ISSUE TITLE
Download as file functionality without FILE PERMISSIONS !!!

### ISSUE THREAD

**Issue by cool-dev-guy** [libre-tube/LibreTube#4982]
### Describe your suggested feature

From previous closed issues i found that the dev's dosen't like `file permission access`,but the `download as file` feature is a pretty good feature.

POSSIBLE SOLUTION:
- why don't use `DownloadManager` from java(don't know about kotlin).
- It can save files at `Downloads` folder without file access permission(As far as i know).
- I think this is more useful than storing it inside android data folders.
- Also `setDestinationInExternalPublicDir` also doesn't need permissions.(So it has optional folders to download)

`from android docs`
> [WRITE_EXTERNAL_STORAGE](https://developer.android.com/reference/android/Manifest.permission#WRITE_EXTERNAL_STORAGE) permission is not needed and the dirType must be one of the known public directories like [Environment#DIRECTORY_DOWNLOADS](https://developer.android.com/reference/android/os/Environment#DIRECTORY_DOWNLOADS), [Environment#DIRECTORY_PICTURES](https://developer.android.com/reference/android/os/Environment#DIRECTORY_PICTURES), [Environment#DIRECTORY_MOVIES](https://developer.android.com/reference/android/os/Environment#DIRECTORY_MOVIES), etc.

NOTE:
- I have searched among many issues about this and i could find anything about the specific topic i am talking about.So i am adding this as a new issue(Sorry if there was any inconvenience)

### Other details

Idea got from : [Geeks for geeks soulution](https://www.geeksforgeeks.org/how-to-download-file-from-url-in-android-programmatically-using-download-manager/)

Additional info:
- I dont know if its possible to get the video file as a `LINK` so that it can work with `DownloadManager`.
- But if it works,then this is a fast and easy to implement feature.(i think).

Thanks...

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
What's your suggestion specifically? If you're asking for downloads to be stored outside of LibreTube's data folder then this isn't planned.

**Comment by cool-dev-guy** [comment]
> What's your suggestion specifically? If you're asking for downloads to be stored outside of LibreTube's data folder then this isn't planned.

Yeah,I would like to have that feature.But according to `Bnyro` in one of the closed issues,he mentions that this feature is not going to be implemented because it requires file permission,but based on the solution i provided there is no requirement of file permission.So i think this feature would be nice.

Thanks...

**Comment by akano12** [comment]
> Yeah,I would like to have that feature.But according to `Bnyro` in one of the closed issues,he mentions that this feature is not going to be implemented because it requires file permission,but based on the solution i provided there is no requirement of file permission.So i think this feature would be nice.
> 
> Thanks... 


https://github.com/libre-tube/LibreTube/issues/3570 & check last comment

**Comment by cool-dev-guy** [comment]
> > Yeah,I would like to have that feature.But according to `Bnyro` in one of the closed issues,he mentions that this feature is not going to be implemented because it requires file permission,but based on the solution i provided there is no requirement of file permission.So i think this feature would be nice.
> > Thanks...
> 
> #3570 & check last comment

What about this : https://github.com/libre-tube/LibreTube/issues/2041#issuecomment-1327503865

**Comment by Bnyro** [comment]
I'm aware that storage permissions are not necessary for supporting this. However, as already explained in other issues, audio and video can only be downloaded separately and hence this wouldn't be good enough to play the video via other players. Many users would complain about that, open issues, ...
If you want to use an external player for downloaded videos, use dedicated downloader apps like Seal.
