### ISSUE TITLE
Subtitles are not displayed in downloaded videos 

### ISSUE THREAD

**Issue by Gullideck** [libre-tube/LibreTube#4990]
### Steps to reproduce

1. Download a video with subtitles. 2. Play the downloaded video. 3. Wait to see what happens 

### Expected behavior

subtitle file is not used 

### Actual behavior

nothing 

### LibreTube version

0.19.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Eliya-Manoj** [comment]
https://github.com/libre-tube/LibreTube/issues/1700
