### ISSUE TITLE
Button Issue

### ISSUE THREAD

**Issue by Eliya-Manoj** [libre-tube/LibreTube#4992]
### Steps to reproduce

https://github.com/libre-tube/LibreTube/assets/90308888/242c1ad9-5ffd-4e0e-91fd-9063ef5896af

### Expected behavior

Work Smoothly

### Actual behavior

Laggy

### LibreTube version

Latest Debug

### Android version

Android 12

### Other details

This issue not in 0.19.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Fill the issue properly with useful information when reporting something

**Comment by Eliya-Manoj** [comment]
Just install latest debug. Then, use.
