### ISSUE TITLE
Utilize the most space on Portrait Main Player 

### ISSUE THREAD

**Issue by SameenAhnaf** [libre-tube/LibreTube#4993]
### Describe your suggested feature

If Fit is selected, play all types of portrait videos (including square 1:1 ones) on 1:1 ratio. For 1:1 videos, this behavior is always applicable regardless of Fit/Zoom/Fill

If Zoom/Fill is selected, play portrait videos on 16:9 or 1:1 ratio for devices above or below 18:9 ratio respectively.

### Other details

Utilize the most space of main player with convenience. Most devices supporting LibreTube have much taller ratio on portrait mode. So, it will be better to take advantage from most of it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Unfortunately this would be hard to implement and potentially break the mini player transition. I think it's sufficient if users can just go to full screen mode if they want a larger video player.
