### ISSUE TITLE
Paused Videos Can Only Be Resumed By Double Tapping 

### ISSUE THREAD

**Issue by akano12** [libre-tube/LibreTube#4996]
### Steps to reproduce

1. Play a video. 
2. Pause the video.
3. Try to resume the paused video. 

### Expected behavior

Player should resume the video without issues.

### Actual behavior

Video remains paused and wouldn't resume when tapping on resum, it would only be resumed when double tapping. 

### LibreTube version

0.19

### Android version

Androids 13

### Other details

https://github.com/libre-tube/LibreTube/assets/50032603/4838e97e-0268-435b-bd4e-62d8969160ab

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
I found out what's causing this but I'm not sure how to properly describe it.

Basically if the next 10-20 seconds aren't preloaded, this issue happens (that small white thing in the time bar).

![Screenshot_20231017_233627_LibreTube.jpg](https://github.com/libre-tube/LibreTube/assets/50032603/eb94aacd-ec14-45d0-a851-d9a14747574f)

**Comment by EmmanuelDav** [comment]
hey @akano12 can I take care of this issue?

**Comment by atollk** [comment]
I think this is the same issue I encountered. It should also work if you tap the video once to close the overlay, open it again, and then tap the "Play" icon normally.

**Comment by Donkey-Doug** [comment]
I noticed that tapping slightly above the play icon also works. Try to tap as high as possible, while still malimg sure your tap get registered by the padding of the play button.
