### ISSUE TITLE
instancequestion！

### ISSUE THREAD

**Issue by Jiaonikele8** [libre-tube/LibreTube#5002]
### Steps to reproduce

In some regions, the following instances are not available at all
![IMG_20231018_230749](https://github.com/libre-tube/LibreTube/assets/122111118/9479f872-c89b-4f04-baa0-ec71c90df543)

### Expected behavior

Solve the problem that it is not available in some areas

### Actual behavior

Solve the problem that it is not available in some areas

### LibreTube version

0.19.0

### Android version

android13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The best thing is to self-host your own instance, see https://docs.piped.video.
