### ISSUE TITLE
Navigation bar isssue

### ISSUE THREAD

**Issue by Eliya-Manoj** [libre-tube/LibreTube#5006]
### Steps to reproduce

1. open LibreTube
2. use Trends, Subscriptions and Library (mainly)
3. Lagging 

https://github.com/libre-tube/LibreTube/issues/4992 ( alreday reported, but closed issue )

### Expected behavior

Navigation bar work without lagging

### Actual behavior

Lagging Navigation bar

https://github.com/libre-tube/LibreTube/assets/90308888/b3e07143-9cd0-4935-8794-46f15fa415c1

### LibreTube version

Latest Debug

### Android version

Android 12

### Other details

No issue in stable version(0.19.0)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/3240

**Comment by Eliya-Manoj** [comment]
3 issue now trends, subscription and library

**Comment by janisslsm** [comment]
The most likely cause of the lag is the app being built in debug mode in CI instead of release mode like when a new release is made. I'd recommend trying to build a release build locally and seeing if it still occurs.

**Comment by Bnyro** [comment]
There haven't been any changes to the navigation bar / tabs since the latest release and it's common that debug builds behave slower than actual release builds.
