### ISSUE TITLE
Can't Use Scrubber In Downloaded Videos

### ISSUE THREAD

**Issue by akano12** [libre-tube/LibreTube#5007]
### Steps to reproduce

1. Download a video. 
2. Go to downloads. 
3. Play the downloaded video. 

### Expected behavior

Be able to adjust time

### Actual behavior

Scrubber missing 

### LibreTube version

Latest debug

### Android version

Android 13

### Other details

https://github.com/libre-tube/LibreTube/assets/50032603/dcc7f897-b1da-4411-9046-42b4ce39c1d7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by janisslsm** [comment]
seems to have been caused by #5004. I'll take a look
