### ISSUE TITLE
Shorts from specific channels are not played on Portrait Player 

### ISSUE THREAD

**Issue by SameenAhnaf** [libre-tube/LibreTube#5015]
### Steps to reproduce

1. Go to https://www.youtube.com/channel/UCWdkdpfxKpfi6aGT8hwFXtA
2. Try to access any of the Shorts.

### Expected behavior

Shorts are expected to play on Portrait Player.

### Actual behavior

None of the Shorts from the selected channel can be played on Portrait Player. All shorts turn to landscape on portrait.

### LibreTube version

0.19.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Could you please test this again in the latest debug builds? (I refactored the full screen player which might or might not have an impact)
