### ISSUE TITLE
Screen orientation setting ignored on video page

### ISSUE THREAD

**Issue by pi99y** [libre-tube/LibreTube#5018]
### Steps to reproduce

In settings choose landscape screen orientation.
Restart the app (to apply the setting).
Try to watch a video (enter its sub page).
The orientation switches back to portrait mode.

### Expected behavior

The orientation should remain landscape in all parts of the app not switch to portrait while on video page.

### Actual behavior

The search results and the rest of the app is correctly displayed in landscape.
The video sub-page (once you click on a specific video) returns to portrait mode.
Once you make the video content full-screen it becomes correctly oriented again (landscape).

### LibreTube version

0.19.0

### Android version

Android 9

### Other details

Since I'm using this on a TV, the rotation to portrait mode rotates everything 90 degrees left, so it lies on its side and is hard to navigate, read and watch.

The workaround to immediately display video in full-screen helps, however this negates access to video comments and the subscription button which is a major problem.

I also tested this on a phone where the behavior was exactly the same but since you can turn the phone physically it's not such a big deal. 

I understand that in order to display the video in landscape on a landscape oriented device would require it to be displayed in less than full screen width so the user can see the "subscribe" button and some comments before the screen fold, however this is to be expected. I wouldn't mind even a full-width video taking up all the screen real-estate, revealing subscribe button and comments by scrolling the page.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#4981, #3198
