### ISSUE TITLE
Fdroid Libretube out of date 

### ISSUE THREAD

**Issue by LowFlyingpan** [libre-tube/LibreTube#5019]
### Steps to reproduce

Install Libre Tube through Fdroid

Version that gets installed is 0.18.1

### Expected behavior

Version 0.19.0 gets installed

### Actual behavior

Version 0.18.1 gets installed 

### LibreTube version

0.18.1

### Android version

Standart Samsung Galaxy S10e Os

### Other details

Just upload the new Packages to Fdroid.

Also i cant update though github since it just throws an error at me

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#4991

**Comment by Bnyro** [comment]
#4991
