### ISSUE TITLE
Allow hiding channels in a group from "All" feed

### ISSUE THREAD

**Issue by MinekPo1** [libre-tube/LibreTube#5020]
### Describe your suggested feature

When editing channel groups the user should have an option to hide channels in the group from the "all" tab. This could be useful for channels which the user is interested in, but considers potential overwhelming (news, heavy political stuff etc).

### Other details

Related to #3558

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The "All" tab shows all subscribed channels. It doesn't make sense to hide channels from that ...

If you want a group excluding some channels, just create one.
