### ISSUE TITLE
[FR/Bug]: Restore queue and watch progress

### ISSUE THREAD

**Issue by Silther** [libre-tube/LibreTube#5024]
### Describe your suggested feature

Watch some videos, add some videos to the queue and than pause and leave the app (without closing it)

If you leave LibreTube in the background for some time and reopen it, it will start with the first video of the queue (not the video you watched last before leaving the app) and the queue gets cleared.

In my opinion it should remember the video wich was played before you left the app and (and also its watch progress) and should restore the queue as sone as the app has been opened again.

If you left the app with an paused video, it should still be paused if you reopen the app after some time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by pokegamer5547** [comment]
> I think this only makes sense for music player apps, but not for LibreTube as it's mostly focusing on video streaming.
> 
> If you have a music queue, you might certainly want to continue where you stopped when opening the app the next time. But when you have watched a video, you probably don't want it to continue again after you closed the app, because you usually already finished it. It should be simple enough to use the "Continue watching" tab at the home page to actually continue watching the previous video. I know this doesn't keep the queue, but you could in theory just save your queue to a playlist before leaving the app.

can we have similar to newpipe where app asks the user when selecting another video that current queue will get removed?

**Comment by Bnyro** [comment]
I've decided against implementing a "persistent queue" - It would not be easy to implement at all (we would need to remember a lot of temporary data from previous sessions to actually make this work), and I honestly don't think it's worth it.
