### ISSUE TITLE
[FR]: play, play next, add to queue popup

### ISSUE THREAD

**Issue by Silther** [libre-tube/LibreTube#5026]
### Describe your suggested feature

If you already have a queue with lots of videos you don't want it cleared, just because you clicked on a new video.
It should show a popup like the YouTube app does, if you stream a video to your Chromecast and click on a new video.

The options for the popup should be something like:
- play _(clears the queue and plays the video)_
- play next _(adds the video to the queue at the first position after the currently playing video)_
- add to queue _(adds the video to the queue at lasst position)_

People who don't use the queue that much, may want it optional.

### Other details

YouTube:

![signal-2023-10-22-152344](https://github.com/libre-tube/LibreTube/assets/97352673/e4c09016-a83d-47e1-b372-f8cbe50e4b14).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You can already achieve that via the long press actions of a video item, I don't really see why we would need any additional, duplicated logic for that?

**Comment by Bnyro** [comment]
No plans for that, sorry.
