### ISSUE TITLE
Support for description and comments for audio player 

### ISSUE THREAD

**Issue by SameenAhnaf** [libre-tube/LibreTube#5037]
### Describe your suggested feature

As the title goes....

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
"Audio player"

**Comment by olsonperrensen** [comment]
Someone could made a fork and implement this if needed.

**Comment by balaraz** [comment]
I don't think it's a good idea to make a fork for the sake of adding two buttons.
I can't understand what the problem is with adding this.
