### ISSUE TITLE
Can't Play Age Restricted Videos With HLS Enabled

### ISSUE THREAD

**Issue by akano12** [libre-tube/LibreTube#5038]
### Steps to reproduce

1. Enable HLS
2. Play any age restricted video

### Expected behavior

Video should play normally.

### Actual behavior

Age restricted videos always return a network error with HLS enabled 

### LibreTube version

0.19

### Android version

Android 13

### Other details

I was watching a series yesterday and one of the episodes had audio only during the first few seconds. Tried watching on https://github.com/FreeTubeApp/FreeTube using invidious instance and it worked just fine (also tried on piped but piped had some issues and kept throwing error 1003 on every single video).

Anw the tl;dr is that using HLS fixed the audio problem but now can't play age restricted videos because a network error will be thrown, disabling HLS fixes the network error. And I don't know if this is to be expected with HLS or just a bug.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
If so, that's not a client side issue but rather something in the Piped proxy.
Nevertheless I don't think age restricted content is really supported at all.

**Comment by akano12** [comment]
> Nevertheless I don't think age restricted content is really supported at all.

Didn't quite catch what you mean by this. LT can play age restricted videos normally with HLS being disabled, error is just thrown with hls being enabled.

**Comment by Bnyro** [comment]
* ... at all when using HLS.
