### ISSUE TITLE
Pressing the screen speeds up the video

### ISSUE THREAD

**Issue by NaN-Sz** [libre-tube/LibreTube#5050]
### Describe your suggested feature

I recently discovered that the YouTube app for Android has the following functionality: when you tap anywhere on the video player screen (for about 2 seconds), the video plays at 2x speed. And when you release it, it returns to the standard playback speed.
I think it would be great to have this functionality in the app.

![Screenshot_20231028-054455_YouTube](https://github.com/libre-tube/LibreTube/assets/120607988/a8aeff33-b563-4213-aeeb-9f6da7dfd600)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Sorry, there are currently no plans for implementing such a feature. You already have the possibility to change the playback speed or skip some seconds via double tapping, so I think that this would be just yet another useless feature that makes using the app more complicated for new users.

**Comment by gojzdar** [comment]
I  think this should be added. I've found the feature very useful when the youtuber goes a bit off topic, or when searching for a specific piece of information in a short video. This feature shouldn't be anything new for anyone coming from youtube app or mobile website.

If paired with a setting for custom speed, it could also slow down the video and help people learning a language (understanding harder phrases or distorted audio)  or people with disabilities. 

It also reduces the friction of having to do it manually just for a few seconds of video and then unset it when watching the next.
