### ISSUE TITLE
Multiple Language subtitles

### ISSUE THREAD

**Issue by Pantyhose-X** [libre-tube/LibreTube#5051]
### Describe your suggested feature

Ever wanted to watch a video with subtitles in two or three languages at the same time, to learn a new language while watching a video, which can help you learn words and grammar

* Pick a font colour for each language

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's out of scope for the project.
