### ISSUE TITLE
Add sorting feature

### ISSUE THREAD

**Issue by Pcslug21** [libre-tube/LibreTube#5052]
### Describe your suggested feature

Please add an option to sort the search results by length of video, really helps to access longer format lectures on YouTube while filtering out the clickbaity short form videos.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Not possible at the moment https://github.com/libre-tube/LibreTube/issues/3635#issuecomment-1524023383
