### ISSUE TITLE
variouse app scalling options for horiz. / vert. device positions [FR]

### ISSUE THREAD

**Issue by DI555** [libre-tube/LibreTube#5078]
### Describe your suggested feature

i’d like to suggest a variouse options for app scalling, separately for horizontal and vertical device positions.

for example:
horizontal position settings: A(max) , B , C , D(med) , E , F , G(min)
vertical position settings: A(max) , B , C , D(med) , E , F , G(min)

so, as for recent adjustment like now, the default setting should be looking smth. like this:
horizontal position settings: C
vertical position settings: E

### Other details

the goal of it is in more comfortable app scalling adjustment for horiz. and vert. positions of device!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Unfortunately, these UI values must be hardcoded in XML code and changing them programmatically is not really possible, as this would cause layout issues when recomputing.
Apart from that it's out of scope. The goal is to have one good layout that works well for all people.
