### ISSUE TITLE
The created playlist is not immediately visible.

### ISSUE THREAD

**Issue by Pamilg8** [libre-tube/LibreTube#5079]
### Steps to reproduce

https://github.com/libre-tube/LibreTube/assets/149590337/17297ffb-fde3-455a-af3c-39e96d745e57

### Expected behavior

After the playlist was created, it should appear on the page

### Actual behavior

The system keyboard does not close and the playlist does not appear.

### LibreTube version

0.19.0 Debug

### Android version

Android 12

### Other details

Title

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Pamilg8** [comment]
It didn't fix

**Comment by akano12** [comment]
> It didn't fix

Did u try nightly builds?

**Comment by Pamilg8** [comment]
> > It didn't fix
> 
> Did u try nightly builds?

Yeah
