### ISSUE TITLE
Adding Other Sources (Suggestion)

### ISSUE THREAD

**Issue by theerthrajk** [libre-tube/LibreTube#5083]
### Describe your suggested feature

I have an suggestion to add an option to switch between bilibili, youtube, twitch, etc... In LibreTube.
When Clicked the LibreTube logo on the home screen to change Sources. (I am dumb so I don't know if it is possible, if possible this feature would be good 😊)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
As already said multiple times before, there are no plans to add other sources.
