### ISSUE TITLE
Can't resume videos after not playing for a long time

### ISSUE THREAD

**Issue by hyperstown** [libre-tube/LibreTube#5087]
### Steps to reproduce

1. Play video or whole playlist
2. Pause playback
3. Turn off the screen and leave it for some time
4. Turn on screen
5. Try to play it again

### Expected behavior

Video resumes without any issues.

### Actual behavior

Video is loading for a few seconds, then play button is displayed. When you click that button it tries to load video again which again fails without any error, only displaying play button.
I managed to resume playback switching to audio mode and then back to video mode but if it's a playlist it won't play next video. Currently best solution is to restart the app.

### LibreTube version

0.19.0

### Android version

Android 13

### Other details

I usually leave phone untouched for 24h and every time I leave it for so long I can't resume playback. 
Battery optimization is disabled.
NewPipe has similar issue ([#8627](https://github.com/TeamNewPipe/NewPipe/issues/8627))

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Try double tapping anywhere in the middle of the screen (except on the play button) to resume the video and report back

**Comment by hyperstown** [comment]
Double tapping also doesn't work. It changes video progress but video won't play. 

> Try double tapping anywhere in the middle of the screen (except on the play button) to resume the video and report back

**Comment by akano12** [comment]
> Double tapping also doesn't work. It changes video progress but video won't play. 
> 


Not asking you to skip/rewind few seconds.
Try tapping in this area ![20231103_131114.jpg](https://github.com/libre-tube/LibreTube/assets/50032603/70adac02-3df6-4031-82d6-10ef29f3e220)

**Comment by hyperstown** [comment]
> > Double tapping also doesn't work. It changes video progress but video won't play.
> 
> Not asking you to skip/rewind few seconds. Try double tapping in these areas ![20231103_131114.jpg](https://user-images.githubusercontent.com/50032603/280259509-70adac02-3df6-4031-82d6-10ef29f3e220.jpg)

Unfortunately that also doesn't work.

**Comment by hyperstown** [comment]
Here is additional video:
https://github.com/libre-tube/LibreTube/assets/64496017/d9b99301-ed5c-4169-ab0e-b53f6bfebbb0

It's important to leave phone untouched. If you start doing other things on the same phone, system will put app to sleep to save resources and video will refresh without an issue. But it also depends on devices. Some system will keep processes in memory for a long time, completely unchanged.
Currently I manged to reduplicate issue on two completely different phones. (Stock samsung Android 13 and, LineageOS based on Android 13)

**Comment by Bnyro** [comment]
Due to the fact that NewPipe has the issue too it's likely an issue in the ExoPlayer library we use that doesn't handle rerendering the player view properly after a long time in idle, hence I don't see a way to improve the situation unfortunately.
