### ISSUE TITLE
Automatic video quality does not work.

### ISSUE THREAD

**Issue by Pamilg8** [libre-tube/LibreTube#5094]
### Steps to reproduce

1.By default, set the quality to auto.
2.Play video
3.While watching the video, it often stops and the quality is not set below 720p.

### Expected behavior

The auto-adjusted video should be displayed at a lower resolution according to the network condition.

### Actual behavior

https://github.com/libre-tube/LibreTube/assets/149590337/5a7c9b43-c563-4ac2-b25a-eb569d01d575

I checked by reducing the network speed. It also causes the video to load late and buffering problems.You set the quality to 360p, the video is played. Automatic quality should have done it

### LibreTube version

0.19.0 Debug

### Android version

Android 12

### Other details

Title

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's handled by the ExoPlayer library.
