### ISSUE TITLE
Automatic Instance choosing

### ISSUE THREAD

**Issue by lu4p** [libre-tube/LibreTube#5097]
### Describe your suggested feature

Instances often go down get slow, can't access specific videos etc, going to the settings to change to another instance sucks.

I don't care whose instance I'm using. Libretube should just select the closest/ fastest one available, or even just select a random one when another one bites the dust. 

I'm fine with this being opt-in, for UX it should be the default tho.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/4184#issuecomment-1626354789
