### ISSUE TITLE
Audio Player can't be closed after swipe up

### ISSUE THREAD

**Issue by lu4p** [libre-tube/LibreTube#5098]
### Steps to reproduce

1. Start video
2. Switch to audio only
3. Minimize the player
4. Swipe up on the minimized player.

### Expected behavior

Player should be able to be minimized again. 

### Actual behavior

Minimize button is off-screen.

The only option to get a usable Libretube app back is to click on the middle button which switches to the video player. Or to close and restart the app.

### LibreTube version

0.19.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/4114
