### ISSUE TITLE
Simplify Download pop-up 

### ISSUE THREAD

**Issue by lu4p** [libre-tube/LibreTube#5099]
### Describe your suggested feature

The downloader has too many features, it's hard to use.

Filename should just be the title of the video, remove the Libretube logo and put the title there instead.

For video quality there should only be the choice between different resolutions, not different Codecs, like in the normal player, so default to the more space efficient VP9 and if that's not supported by the device, or the video isn't encoded for it drop down to AVC.

Audio quality shouldn't be a factor, the difference between shit and HQ is only a couple mb anyways, always use HQ. (If a user really wants to limit this it should go into settings).

Video without audio doesn't really make sense, there's always the option to turn off sound.

So the popup should be:
```
Title

Quality Dropdown:
--- 1080p
...
--- 144p
--- Audio only

Subtitles Dropdown (good already)

Download Button
```

Actually how big can subtitles be, just include all of them for accessibility purposes?

### Other details

I would like the option in the settings to bypass this download popup entirely.

Toggle "Lock current download settings"

Immediately downloads the selected video after clicking the download button with the most recent download quality settings. If the user never downloaded a video just use the default resolution for normal videos.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
> Filename should just be the title of the video, remove the Libretube logo and put the title there instead.
>
Somebody requested being able to rename downloads, so we won't remove that now.
I agree with removing the logo though, that has been adressed in a different PR.

> For video quality there should only be the choice between different resolutions, not different Codecs
>
> Audio quality shouldn't be a factor, the difference between shit and HQ is only a couple mb anyways
>
Again, there's no reason to remove working features.

> I would like the option in the settings to bypass this download popup entirely.
>
I don't see a need for that, downloading a video is only two clicks because all important information is being remembered from the previous download.
