### ISSUE TITLE
[FEATURE] Hide top and bottom bar on scroll

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#51]
Hide top bar on scroll to increase content density.

**Comment by rimthekid** [comment]
It's already on my project list but the lit is so big rn that Idk to start with which one :')

**Comment by rakibdev** [comment]
Surprising to be sure this posted in March 6 and seems not added. 56px appbar + 56px search bar below + 80px bottom bar taking half of the screen. No space left for video list. Highest priority core features like this are getting ignored meanwhile other lowest priority features like search history is getting added as soon as possible.

**Comment by Bnyro** [comment]
We're open source and can do what we want. You shouldn't complain since we're using our free time for doing it.

**Comment by Nephys222** [comment]
@Bnyro Do you think it would be better at least the top bar hides on scroll. Is it worth try in main activity with motion layout?

**Comment by Bnyro** [comment]
@Nephys222 Feel free to try it you want :)

**Comment by Nephys222** [comment]
@Bnyro I tried adding new scenes on mainActivity/Motion layout. But it interferes with already implemented motion scene for player. Also tagging motion scene to fragmentHost is not applicable. 

So, what would be your opinion, or right way to achieve? What about making toolbar in Motion layout while mainActivity is not.

**Comment by Bnyro** [comment]
@Nephys222 That's why I didn't add it: It just conflicts with almost everything...
I'm currently reworking the toolbar on the top so it's probably not a good idea to change sth there.

**Comment by Nephys222** [comment]
@Bnyro **searchResult** appearance fixed in searchView. But it pops up in unexpected locations. Try: open an app, in home view, click on a video and then press back, searchHistory appears. Think it is a result of clearing backQueue or sth?

**Comment by Bnyro** [comment]
Probably, we might have to look for a different solution using viewmodels

**Comment by Nephys222** [comment]
@Bnyro Yes possible. Also viewModels nothing to do with Jetpack compose. It can be integrated to views. I will check on it.

**Comment by Bnyro** [comment]
Do you even know what I want to use view models for? Lol

**Comment by Nephys222** [comment]
@Bnyro No I do not. what is ur plan?

**Comment by Bnyro** [comment]
Nvm, I'll do it xD

**Comment by Nephys222** [comment]
@Bnyro It is done. I found it is well implemented. Thanx. Quick question, would it be viable to reset watch position after finish watching?

**Comment by Bnyro** [comment]
I implemented it so that when the saved watch position is the end, the video starts from the beginning (otherwise autoplay would always skip the video). I don't think we have to reset because it works well like that in my opinion.

**Comment by Nephys222** [comment]
@Bnyro Hello. Thinking of implementing landscape mode for player fragment. So it might be used in larger screens. Do u think playerFragment's motionlayout would complicate that?

**Comment by Bnyro** [comment]
I don't think it conflicts, it probably just looks weird because the bottomnav + miniplayer is too big

**Comment by Nephys222** [comment]
@Bnyro Thanks for solving [#1002](https://github.com/libre-tube/LibreTube/pull/1002) for small devices. But still playerView's height is smaller on some older devices (e.g HTC One M9 with 1080x1920).

**Comment by Nephys222** [comment]
Actually it is possible by increasing constraint L. percentage. Would it be possible to extract playerView in separate activity or view so can be changed/worked easily
