### ISSUE TITLE
Downloaded videos should look like normal videos 

### ISSUE THREAD

**Issue by lu4p** [libre-tube/LibreTube#5100]
### Describe your suggested feature

The downloaded videos Page should look and feel similar to the subscription feed.

Title is there anyway, description could also be downloaded, or omitted and the little arrow for explaining disabled.

Suggestions can just show other download videos.

Comments should be hidden.

Download Button should be replaced with a delete button.

Views likes dislikes can be hidden.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
There are no plans to rewrite the downloads UI.
