### ISSUE TITLE
Download Playlist

### ISSUE THREAD

**Issue by lu4p** [libre-tube/LibreTube#5101]
### Describe your suggested feature

Playlists should have a download button which downloads every video of the playlist, and can then be played offline in playlist form.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/3080
