### ISSUE TITLE
App freezes on load after not using for extended period of time

### ISSUE THREAD

**Issue by ghost-in-the-zsh** [libre-tube/LibreTube#5108]
### Steps to reproduce

1. Do not open app for several hours (e.g. 12)
2. Launch app
3. App remains unresponsive for an extended period (often over a minute)

### Expected behavior

The app should remain responsive and actually work.

### Actual behavior

The app is frozen. I cannot scroll, press buttons, etc. It's unusable at that point and I'm forced to use the "Force stop app" button when it comes up, or kill the app manually and try launching it again.

### LibreTube version

0.19.0

### Android version

Android 10

### Other details

I typically have my phone in Medium Power Saving Mode.

Also, the number of subscriptions may have something to do with this. You get a ton of notifications in an instant after killing and relaunching the app, which is why I think channel subscription count might be related.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ghost-in-the-zsh** [comment]
@Bnyro I must really ask if you really followed the steps I outlined in the report, including setting your phone's power mode to what was described *and* waiting for the extended period of time... because it doesn't look like you could've left the app unused for 8-12 hrs in less than 1 hour. :thinking:

**Comment by ghost-in-the-zsh** [comment]
After trying to reproduce the issue again today, this is what I observed:

1. Froze for <=20 seconds
2. Got several notifications immediately after it became responsive

It seems the issue is caused by the app trying to get all updates from all subscribed channels at once, perhaps in the same thread managing the UI, blocking it in the meantime.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/pull/5655
