### ISSUE TITLE
History Shown Instead of Channel Page When Closing Video

### ISSUE THREAD

**Issue by akano12** [libre-tube/LibreTube#5115]
### Steps to reproduce

1- Search for channel. 
2- Play a video from the channel.
3- Go to fullscreen
4- Exit fullscreen
5- Press back button 

### Expected behavior

After doing the above steps, LibreTube should take the user back to the channel page

### Actual behavior

Search history is shown

### LibreTube version

Stable/Nightly 

### Android version

13

### Other details

https://github.com/libre-tube/LibreTube/assets/50032603/9418c39a-7fba-4474-b4c9-9aff442b92f8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
> unrelated to this but why the vertical layout was removed from related videos, any reason or personal choice. if it's personal choice then why its being enforced on other users, looks ugly tbh

It's an option in the settings 🙄

**Comment by akano12** [comment]
> its removed and we can only scroll related videos horizontally

Didn't notice lol.

And to be honest with you, i truly believe they need to trim down the number of options in the settings.
I've been using the app since its early days and I've barely changed 5-6 options at most including sponsorblock and instance settings. Hell i don't even know what most of the stuff do lol, just my opinion.

**Comment by Bnyro** [comment]
> unrelated to this but why the vertical layout was removed from related videos, any reason or personal choice. if it's personal choice then why its being enforced on other users, looks ugly tbh
>
1. Removing it makes it easier to maintain the new landscape layout for the player page.
2. The resolutions of the thumbnails are ugly, so smaller items look better as you don't see the low resolution that much.
3. I'm of the opinion that we should try to make things easier for users and remove really unnecessary layout preferences.

**Comment by Bnyro** [comment]
> there are lots of setting can be removed
>
That's what I agree on, and I've also been trying to not add any new settings for features that can be implemented differently (e.g. removing the default playback speed setting and just remembering it). However, there's always a bunch of users that start complaining when I change anything, so it's not possible to make everyone happy. And in the end I still decide what I think is best, and that's for a reason...

**Comment by DanielProg39** [comment]
In terms of the number of settings, I don't see much of a problem with it. However, there is a problem with their placement. Sometimes, when I need to change something, I don't know which section to look in. Or I think I know where it should be, but it turns out to be wrong. I think the main problem here is the poor structure of the settings (although I know some work has been done to improve things a bit). Rather than removing features, I think it would be better to redesign the settings structure so that there is no "advanced" settings tab, and so that fairly similar settings are not in two different sections.
