### ISSUE TITLE
Pasting a playlist link from youtube does not work

### ISSUE THREAD

**Issue by oczt** [libre-tube/LibreTube#512]
### Steps to reproduce

1. Go to youtube.com get some playlist
2. example: https://www.youtube.com/playlist?list=PL289C2F9B0E522E23
3. Paste it in the search bar
4. Nothing happens

### Expected behavior

It plays the playlist.

### Actual behavior

Nothing happens. (i.e) playlist does not play.

### LibreTube version

0.3.1

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You can just share the link with LibreTube instead of searching it. We won't add support for searching for links in the search bar.
