### ISSUE TITLE
Add a notifications tab

### ISSUE THREAD

**Issue by GBT7** [libre-tube/LibreTube#5122]
### Describe your suggested feature

Exactly like the current implementation in the YouTube app, I would like a tab (or separate area in general) to scroll through videos from channels with notifications enabled.

### Other details

I personally make frequent use of this feature on the "official app" (*cough* revanced *cough*), because nowadays I like to only check my YouTube notifications when I open the app, and I keep notifications for the YouTube app disabled on my phone. Basically I use notifications as a subset of my subscriptions, where, I watch nearly all the videos I get notified for, but I only watch some of my subscribed videos, and I prefer to check them when I have time instead of getting pinged about them throughout the day.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's out of scope, just use channel groups to organize all your important subscriptions.
