### ISSUE TITLE
Issues with Bluetooth media control buttons

### ISSUE THREAD

**Issue by GBT7** [libre-tube/LibreTube#5123]
### Steps to reproduce

Pair a Bluetooth headset, play a video, tap the pause button on the headset

### Expected behavior

The video pauses

### Actual behavior

The video keeps playing

### LibreTube version

0.1.9

### Android version

Android 13 (OneUI)

### Other details

Beyond play/pause not working for videos, when my Bose QC45 headphones say "battery low, please charge now", most apps pause while the message is playing, then resume. When using this app, on the other hand, my phone plays music from another app when the battery low message on the headphones finishes, pausing the video in the process.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by M00NJ** [comment]
I also have problms with the blutooth controls. I can pause over the headphones, but when I press play again, nothing happens. Had an issue open for that at #5000

**Comment by lu4p** [comment]
> Beyond play/pause not working for videos, when my Bose QC45 headphones say "battery low, please charge now", most apps pause while the message is playing, then resume. When using this app, on the other hand, my phone plays music from another app when the battery low message on the headphones finishes, pausing the video in the process.

Can confirm also Bose QC45, pause button works for me tho.

**Comment by akano12** [comment]
> Sadly I still geht this bug in v.0.20.0. @lu4p, @GBT7 what about you? Is it working for you in the latest release?

I believe this was fixed after the release of 0.20. So it should be fixed in nightly builds, give it a try.

**Comment by lu4p** [comment]
Still the same for me
