### ISSUE TITLE
Network error!

### ISSUE THREAD

**Issue by Adithyan007hack** [libre-tube/LibreTube#513]
### Steps to reproduce

Hello
 when I tried to open the subscription tab, it just buffered and the app closed with a network error message
I have switched to another instance but same issue persists, and then I tried to log back to the default instance it won't let do so 
when I click log in after typing the credential network error pops up, so I pressed log in 20 times then 20 network error pops up 

### Expected behavior

it should log in instead of network error

### Actual behavior

Network error

### LibreTube version

0.3.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Kavin just confirmed it's a Piped issue. It should be fixed now.
