### ISSUE TITLE
Tiling on tablets doesn't work properly

### ISSUE THREAD

**Issue by Baardi** [libre-tube/LibreTube#5131]
### Steps to reproduce

- Use a tablet, e.g. a Samsung Galaxy Tab s5e. 
- Use landscape mode within the app.
- Open a video.
- Open the comments section in the given video.

### Expected behavior

Tiling should work properly, comments shouldn't overlay the video.

### Actual behavior

Very odd tiling as seen in the following images.

![281513683-2afacd14-760a-4cef-8644-f1d613d70692](https://github.com/libre-tube/LibreTube/assets/19634818/d27fa7b9-4b77-48ea-837d-b03cbea2b51f)

![281513662-7825b47e-bc08-4165-8e12-69f656b3a8b7](https://github.com/libre-tube/LibreTube/assets/19634818/9c739dea-4f80-47a0-a71a-d6a49352f1da)

### LibreTube version

0.19.0 Debug

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Baardi** [comment]
@Bnyro Your fix seems to work a lot better

![Screenshot_20231109-185100_LibreTube Debug.jpg](https://github.com/libre-tube/LibreTube/assets/19634818/3ab4f97e-ca07-4fce-b623-885b1e6db8c7)

But the comment section still opens in the middle

![Screenshot_20231109-185111_LibreTube Debug.jpg](https://github.com/libre-tube/LibreTube/assets/19634818/bedf58ac-9367-4855-8c06-e26240015c73)

Would it be an idea to open it to the right?

**Comment by Bnyro** [comment]
> Would it be an idea to open it to the right?
>
Yes, but that would be very difficult to implement with the current logic unfortunately, and I don't want to create a separate UI for the landscape layout of comments.
