### ISSUE TITLE
0 view on Continue Watching tab

### ISSUE THREAD

**Issue by NazcaLine** [libre-tube/LibreTube#5134]
### Steps to reproduce

1. Open the app

### Expected behavior

It shows more than 0 number of views (e.g. 100K views)

### Actual behavior

It shows 0 view on every video on Continue Watching

### LibreTube version

0.19.0

### Android version

Android 12

### Other details

![Screenshot_2023-11-09-14-23-45-157-edit_com github libretube](https://github.com/libre-tube/LibreTube/assets/25423876/a6133536-7ad2-4d23-830d-b90765863528)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's already fixed in debug builds.
