### ISSUE TITLE
Add ability to loop audio while in audio-only/background play mode

### ISSUE THREAD

**Issue by Arctic-Circle-System** [libre-tube/LibreTube#5138]
### Describe your suggested feature

It should work similarly to the way you can currently loop audio and video in the video mode, but in audio-only/background play mode (so no video).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Already implemented on master branch.
