### ISSUE TITLE
Videos stop playing when locked, because Libretube is put to sleep

### ISSUE THREAD

**Issue by lu4p** [libre-tube/LibreTube#5141]
### Steps to reproduce

1. Play any video
2. Lock your screen
3. Wait 5 minutes (This may depend on how aggressive the device is with power management)

### Expected behavior

Video should continue playing.

### Actual behavior

Video stops playing.

### LibreTube version

0.19.0

### Android version

Android 13

### Other details

This is because Libretube needs to acquire a wakelock https://developer.android.com/training/scheduling/wakelock
in order for Android to not put Libretube to sleep after a few minutes.

Exoplayer can acquire this wakelock for us when it makes sense (i.e. video playing while the screen is off), so I thought I had a 10 line fix for this.
```kotlin
// for online usage
player.setWakeMode(WAKE_MODE_NETWORK)
// for offline usage
player.setWakeMode(WAKE_MODE_LOCAL)
```
https://developer.android.com/reference/androidx/media3/exoplayer/ExoPlayer#setWakeMode(int)

However when debugging afterwards I learned that exoplayer can only do this when it runs in a service like is already done in the audio player.

This should probably be implemented by extending the Offline and OnlinePlayerServices to also support video, and offloading all PlayerFragement player interactions to it.

The officially recommended solution is a [mediasessionservice](https://developer.android.com/guide/topics/media/session/mediasessionservice), however that would require a major refactor which is probably not something that can be easily done (I tried and failed miserably, but I also know little about android development).

I will send a PR to fix the audio player, it is less affected because it is already running as a foreground service, but will also be put to sleep after a longer interval or when Battery Saver is active.

I'm also trying to fix the video player but I'm not sure if I will succeed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
PRs welcome, as I already said I don't have interest in working on that since the audio only mode is good enough for the purpose of background playback.

**Comment by Pamilg8** [comment]
I can say that there are the following issues with playback
1.Sometimes when opening a video, the player is locked and the play button does not work. Reopening the video does not fix it
2.The player and related videos section is not loading
3.↻ appears and the player does not open
4.The video stops in the middle and the play does not work.
5.Sometimes the 4th problem occurs when playing video forward and backward.
6.The player restarted,when I came back from the background.Or the playback stopped.

Which ones does this PR fix?🤔

**Comment by lu4p** [comment]
This issue is only about videos stopping after a few minutes, after you lock your device. So 7.

**Comment by Pamilg8** [comment]
> This issue is only about videos stopping after a few minutes, after you lock your device. So 7.

Didn't you just make an audio player?

**Comment by lu4p** [comment]
Yes, but this issue is also about the video player audio was just a lot easier.

**Comment by lu4p** [comment]
@Pamilg8 do all of the issues you found already have github issues?

**Comment by Pamilg8** [comment]
> @Pamilg8 do all of the issues you found already have github issues?

1.You said that I could not fix a video player.
2.I dont know.

**Comment by ksh-b** [comment]
For me the app crashes after a while when I lock the screen. This is the stacktrace shown after starting the app again. Im on android 14.
https://pastebin.com/DGyqziLu

**Comment by ksh-b** [comment]
> this could be fixed adding an exception on the battery settings so i doesn't get closed, and letting it linger under the radar. try that and how it goes
Happens with unrestricted battery usage too

**Comment by alejandro-alzate** [comment]
so i can't suggest anything, may helps giving libretube permissions through adb or root but i don't think that libretube can get advantage of root permissions so well i can't help with that your phone seems be very restrictive on that but in mine was fixed with that.

**Comment by furrydaemon** [comment]
I would recommend that if libretube is able to know if it has been send to the background or not, to convert the current session (video) to audio, it would probably save battery and mobile data
I don't know if it's the default behaviour or not, I think it is for newpipe

**Comment by edmundlaugasson** [comment]
Same happened when screen was on but app played in background. So far turned battery optimization manually off for LibreTube and now seems working.

**Comment by lu4p** [comment]
@Bnyro Thanks for fixing this.
