### ISSUE TITLE
hdr support

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [libre-tube/LibreTube#5147]
### Describe your suggested feature

![Screenshot_2023-11-14-09-15-53-984_com github libretube~2](https://github.com/libre-tube/LibreTube/assets/52075465/c91959b0-7be8-4ed2-943b-f5b0a3ebd1b5)
I don’t know if the difference is visible on your screen, on the left is youtube 2k hdr, on the right is libretube 2k

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
HDR is already supported if the device can handle it.

**Comment by Envel-Nikita-Gutsenkov** [comment]
> HDR is already supported if the device can handle it. The player will automatically use it based on the network conditions.

In my case, for some reason there is no HDR under any circumstances, are there any settings?

**Comment by Envel-Nikita-Gutsenkov** [comment]
hmm 
![Screenshot_2023-11-14-14-27-06-621_com github libretube-edit](https://github.com/libre-tube/LibreTube/assets/52075465/a9e6e418-8b18-434e-8910-788e54568704)

**Comment by akano12** [comment]
> hmm, 720p max on 2k display 
> ![Screenshot_2023-11-14-14-27-06-621_com github libretube-edit](https://github.com/libre-tube/LibreTube/assets/52075465/a9e6e418-8b18-434e-8910-788e54568704)
> 

https://github.com/libre-tube/LibreTube/issues/4255

**Comment by Envel-Nikita-Gutsenkov** [comment]
I still think there is no HDR. Huge difference from YouTube
