### ISSUE TITLE
Include a ROADMAP.md

### ISSUE THREAD

**Issue by laraib07** [libre-tube/LibreTube#515]
### Describe your suggested feature

This is an interesting project. Would like to know where it is headed and what features are being planned. It would be very helpful if you guys could include a ROADMAP.md which contains currently features being worked upon and future plans.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The plan is to close issues ^^

**Comment by Bnyro** [comment]
The only real big thing that still has to be done is to make the player look better.

**Comment by Bnyro** [comment]
see https://github.com/libre-tube/LibreTube/blob/master/ROADMAP.md
