### ISSUE TITLE
automatically change instance

### ISSUE THREAD

**Issue by MXC48** [libre-tube/LibreTube#5153]
### Describe your suggested feature

it regularly happens that an instance is disconnected, so it would be nice if it could change instance automatically to avoid having to do it manually.
And the application could signal this with a pop-up.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/issues/4184#issuecomment-1626354789
