### ISSUE TITLE
If Enter/exit fullscreen gesture is enabled the Fullscreen orientation in the Player settings (Landscape, video aspect ratio) does not work properly

### ISSUE THREAD

**Issue by Eliya-Manoj** [libre-tube/LibreTube#5158]
### Steps to reproduce

1. Open LibreTube
2. Enable Enter/exit fullscreen gestures in Player settings
3. Fullscreen orientaion ( select video aspect ratio or Landscape ) in Player settings
4. Play Video and swipe up to fullscreen

https://github.com/libre-tube/LibreTube/assets/90308888/7349c2a4-6b68-4275-9009-f2e7a3d70744

### Expected behavior

Fullscreen based on aspect ratio. If Landscape, Video plays in landscape.

### Actual behavior

Enter fullscreen in landscape and then suddenly change to portrait. 

### LibreTube version

0.20.0 - 0.23.2

### Android version

Android 12

### Other details

https://github.com/libre-tube/LibreTube/issues/5160 based on this issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Eliya-Manoj** [comment]
Reproducible version 0.20.0. I can't reproduce in Latest Debug.

If i disable Enter/exit fullscreen gesture, no issues in video orientation.

**Comment by xlash123** [comment]
I also have this issue in 0.20.0. Only occurs when using the gesture. Pressing the fullscren button behaves as expected.

**Comment by Surbbd** [comment]
This issue continues with 20.1 release, to reproduce use gestures to fullscreen the video and this happens.

**Comment by Bnyro** [comment]
This should be fixed by now.

**Comment by ymcx** [comment]
I'm still able to reproduce this on a build built from the main branch.
