### ISSUE TITLE
List of recommended videos is truncated

### ISSUE THREAD

**Issue by DanielProg39** [libre-tube/LibreTube#5161]
### Steps to reproduce

1. Watch a video to some point in full screen
2. Exit full screen

### Expected behavior

List of recommended videos should show full thumbnails and titles

### Actual behavior

List of recommended videos is shown not properly

![Screenshot_20231115-215125_Trebuchet](https://github.com/libre-tube/LibreTube/assets/63293432/d44869d8-c2b2-4cd7-9688-c5a14b57c147)

### LibreTube version

LibreTube Debug, commit https://github.com/libre-tube/LibreTube/commit/c86477c32b9907d01db1482e45dc8c0146be35e7

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Works well on my side, are you using latest debug version?

**Comment by DanielProg39** [comment]
Here's a screenshot and a recording of how I reproduce this bug.

![Screenshot_20231115-230048_Trebuchet](https://github.com/libre-tube/LibreTube/assets/63293432/1cd4c583-f9b0-46eb-8957-5185c2e53353)

https://github.com/libre-tube/LibreTube/assets/63293432/b7828440-68a2-4d5b-838e-940083104cb0

**Comment by Bnyro** [comment]
Can also be reproduced by going to full screen, auto playing to the next video and leaving full screen.
