### ISSUE TITLE
Yet another problem with fullscreen video

### ISSUE THREAD

**Issue by DanielProg39** [libre-tube/LibreTube#5162]
### Steps to reproduce

1. Ensure you have auto-fullscreen enabled
2. Open a video
3. Rotate the phone - video turns to full screen
4. Rotate back - video is displayed in the top of the screen
5. Rotate the phone to landscape again

### Expected behavior

Video should turn to full screen

### Actual behavior

Video stays minimized in the top of the screen. To turn it to full screen you should pull the player down a bit and then up (or minimise and re-open it)

### LibreTube version

LibreTube Debug, commit c86477c

### Android version

Android 13

### Other details

I've told about this issue 2 weeks ago: https://github.com/libre-tube/LibreTube/issues/5061#issuecomment-1784935196

Here's a screen recording that shows everything:

https://github.com/libre-tube/LibreTube/assets/63293432/feb2a36a-76c8-4859-b50c-25dbbd696987

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Zoo-M0** [comment]
I'm looking into it, it seems like `TransitionListener` get stuck and re-triggers only when you move something on UI. I can't get why this blocks even the `onConfigurationChanged`, it should listen for orientation changes regardless of the `TransitionListener`.

**Comment by Bnyro** [comment]
Fixed by #5174, thanks @Zoo-M0
