### ISSUE TITLE
add option to be able to view related streams in vertical list again

### ISSUE THREAD

**Issue by pokegamer5547** [libre-tube/LibreTube#5169]
### Describe your suggested feature

On my phone, It's often next to impossible to read related stream's upload date with latest update 0.20.0. I like the new horizontal view but its not convinient for me on my tall phone. Please atleast add the option to see related streams in vertical list again. 
![Screenshot_20231116-214805_LibreTube Debug](https://github.com/libre-tube/LibreTube/assets/65234485/9ce2671e-c23d-4a8c-9041-07f4267e8c22)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/discussions/5118
