### ISSUE TITLE
Background not changing with dark theme

### ISSUE THREAD

**Issue by Zoo-M0** [libre-tube/LibreTube#5182]
### Steps to reproduce

1. Put system on light mode
2. Launch the app
3. Change theme to dark mode in app settings
4. Apps restart and open the home page (background is light)
5. Go to device settings and change device theme to dark
6. Go back to app (background turns dark)

After you put the app on dark mode from the settings try this:
1. Put device in light mode
2. Open the app (home page's background is light)
3. Close the app, and kill from background
4. Put device in dark mode
5. Open the app (home page's background is dark)

### Expected behavior

Background should be dark

### Actual behavior

Background remains dark until you change theme to the device.

### LibreTube version

0.20.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I think that's because we're using a color for the background there that is not part of the overriden theme colors, should he easy to fix.
