### ISSUE TITLE
Do a proper release

### ISSUE THREAD

**Issue by shellheim** [libre-tube/LibreTube#5183]
### Steps to reproduce

N/A

### Expected behavior

A proper release with APKs attached.

### Actual behavior

Uhh... not a propr release with APKs attached?

### LibreTube version

N/A

### Android version

N/A

### Other details

I use [Obtainium](https://github.com/ImranR98/Obtainium/) to install APKs (it's an app to download apks from source e.g. github releases). The app needs a proper release with apks attached to download from github releases as mentioned in [this issue.](https://github.com/ImranR98/Obtainium/issues/1095) The recent v0.20.0 release is just a tag and thus obatainum can't download it. I would like to ask for a proper release as many other people also using obtainium might be facing the same problem. I don't want to come off as entitled (extremely sorry if I do) but please look into doing a proper release for this version and (hopefully) for future versions, thanks! 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FireMasterK** [comment]
I'm not sure what you mean, the release has APKs too, just like other prior releases: https://github.com/libre-tube/LibreTube/releases/tag/v0.20.0

**Comment by shellheim** [comment]
Yeah but it's not a "github release" it's just the tag. Notice how the v0.20.0 release doesn't show up on https://github.com/libre-tube/LibreTube/releases but only on https://github.com/libre-tube/LibreTube/tags

**Comment by FireMasterK** [comment]
Not really, https://github.com/libre-tube/LibreTube/releases/latest takes you to the right release. I can see the latest release in the link you've provided too.

**Comment by shellheim** [comment]
Yeah it does point to v0.20.0 but that's not the point. It's not a github release nonetheless, it's still just pointing to the git tag. I have checked through 3 devices but I can't see the v0.20.0 release in https://github.com/libre-tube/LibreTube/releases/latest I don't know how it's works for you.

**Comment by shellheim** [comment]
On https://github.com/libre-tube/LibreTube/releases/ this is what I get :   

![image](https://github.com/libre-tube/LibreTube/assets/116480892/095883e8-1177-460e-86ff-8d7f90bdcb54)

**Comment by Bnyro** [comment]
That's a current GitHub bug unfortunately and there's nothing we could do about it other than waiting.

**Comment by shellheim** [comment]
Oh, sorry to hear that and thanks for the reply! I have been meaning to say this for a long time now, thank you so much for your work on libretube! The original app with it's clutter was unbearable.

**Comment by maboroshin** [comment]
Adding the information to the lead section of version 0.19.0 would be easy for users to notice. This information is for those who accessed here. https://github.com/libre-tube/LibreTube/releases/
