### ISSUE TITLE
Featured channels tab gone 

### ISSUE THREAD

**Issue by dev-1415** [libre-tube/LibreTube#5184]
### Steps to reproduce

![Screenshot_20231117-220320_LibreTube~2](https://github.com/libre-tube/LibreTube/assets/146163487/5f2ab55b-3ba5-4380-b60c-723ac80c892c)

1. Go to any channel
2. Look for "Channels" tab to find other channels featured by the channel in Step 1.
3. Boom. It's gone. Not there.

### Expected behavior

Channels tab should be present if a channel features other channels.

### Actual behavior

Channels tab gone, lost, turned to dust...

### LibreTube version

0.20.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not a client side issue, apparently there were some breaking YouTube changes that require NewPipe Extractor modifications.
