### ISSUE TITLE
Dark theme is not working properly

### ISSUE THREAD

**Issue by shellheim** [libre-tube/LibreTube#5189]
### Steps to reproduce

1. Open Libretube and go to Settings<Appearence<Theme.  
2. Choose `Dark` and wait for the app to restart. 

### Expected behavior

The app should render all its components according to the dark theme.

### Actual behavior

The app renders everything correctly except for : 

1. Search  
2. Home Page
3. Subscriptions 
4. Library

### LibreTube version

0.20.0

### Android version

8.1.0

## Home Page

![1](https://github.com/libre-tube/LibreTube/assets/116480892/5b551d26-aadc-4674-a40b-b2af9de325f6)   

## Settings

![2](https://github.com/libre-tube/LibreTube/assets/116480892/3cf62af1-9791-44a2-879a-0b3cbc3ee61f)  

## Player

![3](https://github.com/libre-tube/LibreTube/assets/116480892/73d222cf-3100-48a7-b8a8-dbe4b466731f)  

## Search Results

![4](https://github.com/libre-tube/LibreTube/assets/116480892/f37ee348-609f-45c4-a81b-6a229338e94e)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Already fixed in debug builds.
