### ISSUE TITLE
4 changes to better support Android TV?

### ISSUE THREAD

**Issue by ydqsbfsyi** [libre-tube/LibreTube#519]
### Describe your suggested feature

I just tried this app in android phone, and it's amazing! Then I tested within Android TV, I think with several minor changes, it'll be super fluent, too (working with a wireless mouse), there's no need to build a whole new TV version. However, it's just a thought, don't know if it's possible.

1, make interface horizontal, now everything is 90 degree rotated, except in settings and in video full screen mode.

2, mouse double click in video will pause/resume play. (Also, TV remote control's OK key is binded to settings when in video full screen mode, it'll be better if it's pause/resume play as well).

3, mouse triple click in video will toggle full screen mode on and off. 

4, in Subscriptions page, mouse scroll down doesn't work, so I could only see a dozen of videos. Is it possible to fix that?

Thanks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
landscape mode is planned but I won't do it atm

**Comment by ydqsbfsyi** [comment]
> 
Roger that.

**Comment by Bnyro** [comment]
I'm sorry to say that but support for Android TV would require us to make a new different version of the app which would have to be maintained seperatly from the main one which is too time intensive for our current capacities. There are some other alternates for Android TV that aren't bad at all so you maybe want to look into them.
