### ISSUE TITLE
alternative video layout doesn't work

### ISSUE THREAD

**Issue by Tetzuya75** [libre-tube/LibreTube#5190]
### Steps to reproduce

In the new update 0.20.0 the function to switch to alternative video layout doesn't work.
It remains fox to horizontal related video (alternative). Is not possible to return to vertical layout (like youtube).
The function on 0.19.0 release works correctly

### Expected behavior

If I match alternative video layout, I expect to have a big window like in the picture below (big preview, vertical scrolling)
![Uploading Screenshot_2023-11-18-08-34-52-706_com.android.chrome_1.jpg…]()

### Actual behavior

What the program do is show little preview in horizontal scrolling 
![Screenshot_2023-11-18-08-28-23-164_com github libretube](https://github.com/libre-tube/LibreTube/assets/117084508/086a8c0e-e5f7-4aaa-960b-922c7fcfad13)

### LibreTube version

0.20.0

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The option was removed, there's already an open discussion about it. It was called "alternative player latout", not videos layout.

**Comment by Tetzuya75** [comment]
The option to see related video by scrolling vertical than horizontal, was
optimal for feedback and similar to the other YouTube app.....

Il sab 18 nov 2023, 08:59 Bnyro ***@***.***> ha scritto:
