### ISSUE TITLE
Stable volume option

### ISSUE THREAD

**Issue by Pamilg8** [libre-tube/LibreTube#5191]
### Describe your suggested feature

Please add a stable volume option to the player.In some videos, the volume is quite slow. This stabilizes the volume.But in videos with stable volume, this option should be greyed out, because it is not needed.Recently, I saw this feature on YouTube. It worked pretty well.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not planned as the player library we use doesn't natively support it.
