### ISSUE TITLE
Video stops playing when "fullscreen mode" button is clicked

### ISSUE THREAD

**Issue by anaseig** [libre-tube/LibreTube#5193]
### Steps to reproduce

1. Play a video
2. Press the "fullscreen mode" button

### Expected behavior

The video should be playing with little or no pause.

### Actual behavior

The screen goes black and video + audio stops playing. 

I have to press the play button to make the video play again in landscape mode.
It wasn't an issue in previous versions that I have used.

### LibreTube version

0.20.0

### Android version

Android 7.1.2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Post a recording

**Comment by anaseig** [comment]
https://github.com/libre-tube/LibreTube/assets/70536934/b5d65591-7c03-4074-a523-f8bd9d770802

**NOTE:** the fullscreen video player showed in portrait mode because of the screen recorder, not because of the app.

**Comment by Tunsinasro** [comment]
I can confirm that it happens sometimes mainly when the internet is weak

**Comment by Bnyro** [comment]
Should be fixed in debug builds.
