### ISSUE TITLE
Restore Related Videos in Full size

### ISSUE THREAD

**Issue by RuthlessRuler** [libre-tube/LibreTube#5206]
### Steps to reproduce

1. Load any video
2. Scroll down to see recommend next videos list

### Expected behavior

The recommendation videos are displayed in vertical scrolling list with full size thumbnail

### Actual behavior

Recommend videos are shown in horizontal scrolling list.
![Screenshot_20231119-153009_LibreTube](https://github.com/libre-tube/LibreTube/assets/20885012/b3b101df-84bf-4bdd-b58b-fdcc993a31a9)

### LibreTube version

0.20.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/discussions/5118
