### ISSUE TITLE
Fails to handle invidious/piped links

### ISSUE THREAD

**Issue by sybenx** [libre-tube/LibreTube#521]
### Steps to reproduce

Set LibreTube as default
Click https://invidious.snopyta.org/watch?v=3t-EYU10U3o
LibreTube crashes when attempting to open

### Expected behavior

App should open and play video

### Actual behavior

App crashes 

### LibreTube version

0.3.1

### Android version

Android 10

### Other details

Happens with piped links as well

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Fixed with #503
Please make sure there's no other issue for it (also if it's already closed)
