### ISSUE TITLE
Player control missing when in full screen and main player is pulled down

### ISSUE THREAD

**Issue by Tunsinasro** [libre-tube/LibreTube#5216]
### Steps to reproduce

1. Play any video
2. Pull down the video to the bottom
3. Rotate the phone to enter full screen mode

### Expected behavior

Video player controls should be visible

### Actual behavior

Video player controls are missing (only status bar is visible)

### LibreTube version

0.20.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Just create a PR please.

**Comment by Bnyro** [comment]
Seems to be the same issue as https://github.com/libre-tube/LibreTube/issues/4161
