### ISSUE TITLE
Play in background when app is removed from device tasks

### ISSUE THREAD

**Issue by Pamilg8** [libre-tube/LibreTube#5220]
### Describe your suggested feature

Expected function: I saw this feature in the new Harmony Music application.Even if you accidentally close the app, the audio continues to play from the notification bar
YOU MUST ADD THIS AS AN "ON/OFF" OPTION IN THE SETTINGS.Perhaps when the app is closed, there will be no problem playing in the background

Current behavior:When you close the app, the audio stops.

### Other details

https://github.com/libre-tube/LibreTube/assets/149590337/b661a7ff-5781-4c70-953f-f3c2dd67b5c0

### Acknowledgements
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That would cause issues with the notification being dismissable and other current features of the audio player.

As I think this is pointless, not planned.
