### ISSUE TITLE
LibreTube Widget support

### ISSUE THREAD

**Issue by Pamilg8** [libre-tube/LibreTube#5221]
### Describe your suggested feature

Widget like YouTube on the phone's main screen.Wide search bar.

### Other details

No.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's out of scope.
