### ISSUE TITLE
Download entire playlist

### ISSUE THREAD

**Issue by sombresu** [libre-tube/LibreTube#5223]
### Describe your suggested feature

Download all video in the playlist

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/3080
