### ISSUE TITLE
Regressive selectable comments.

### ISSUE THREAD

**Issue by Snailhail** [libre-tube/LibreTube#5224]
### Steps to reproduce

1: Open comment popup.
2. Short hold on comment to begin copy.
3. Drag to desired amount.
4. Touch prompt to copy.

### Expected behavior

When pulling up a comment you should be able to copy by short pressing It then dragging the selector to the personal amount. Follow by the prompt to copy

### Actual behavior

On 0.21.0 selectable comments from the popup don't work, but description works as intended.

### LibreTube version

Android 14

### Android version

0.21.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Snailhail** [comment]
> That's the only way to fix that comments need to be double tapped to become opened (#4963).
> 
> Changing the current behavior is not planned.

There seems to be a communication issue between us. The problem Isn't opening up comments by double tab. Rather, you can't select a individual's comment for certain words to copy.
As you would In the description area.
Maybe I'm forgetful, but wasn't the above a feature?

**Comment by akano12** [comment]
> > That's the only way to fix that comments need to be double tapped to become opened (#4963).
> > 
> > Changing the current behavior is not planned.
> 
> There seems to be a communication issue between us. The problem Isn't opening up comments by double, or single tap. 
> Rather, you can't select a individual's comment for certain words to copy.
> As you would In the description area.
> It seems the above Is, or rather was a feature?
> 
> https://github.com/libre-tube/LibreTube/issues/3166#issuecomment-1826234573

What he's saying is, there was an old bug that was introduced when this feature this added, the bug would make users double tap on a comment to expand it.
Removing the comment selection solved this bug, hence thus feature is not going to be reintroduced anytime soon

**Comment by Snailhail** [comment]
> > > That's the only way to fix that comments need to be double tapped to become opened (#4963).
> > > Changing the current behavior is not planned.
> > 
> > 
> > There seems to be a communication issue between us. The problem Isn't opening up comments by double, or single tap.
> > Rather, you can't select a individual's comment for certain words to copy.
> > As you would In the description area.
> > It seems the above Is, or rather was a feature?
> > [#3166 (comment)](https://github.com/libre-tube/LibreTube/issues/3166#issuecomment-1826234573)
> 
> What he's saying is, there was an old bug that was introduced when this feature was added, the bug would make users double tap on a comment to expand it. Removing the comment selection solved this bug, hence this feature is not going to be reintroduced anytime soon

Understandable. Thanks for clarifying.
