### ISSUE TITLE
Livestream can only be watched a day after it was live

### ISSUE THREAD

**Issue by update-freak** [libre-tube/LibreTube#5226]
### Steps to reproduce

1. Try to start a livestream within the day it was livestreamed e.g. 22min after it was streamed from here: https://www.youtube.com/@KraichtalElsenz/streams
2. You will see that the video will not start

![Screenshot_20231126_112633_LibreTube](https://github.com/libre-tube/LibreTube/assets/40196995/ae57cb39-2110-4928-a90f-f2dc513b42dd)
![Screenshot_20231126_112657_LibreTube](https://github.com/libre-tube/LibreTube/assets/40196995/0660d5e8-8b10-4ed2-849b-d8d831f19ffc)

### Expected behavior

Video will start

### Actual behavior

Video will not start

### LibreTube version

0.20.1

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/2148
