### ISSUE TITLE
Taking very long time in loading contents, still video doesn't start playing

### ISSUE THREAD

**Issue by Vikram0412** [libre-tube/LibreTube#5232]
### Steps to reproduce

Log in with piped account
Trying to play a video of more than 1 hour
Disable proxy setting in off
Still video not playing

### Expected behavior

Video should play

### Actual behavior

Keeps on loading

### LibreTube version

0.

### Android version

0.20.1

### Other details

Just try to play a video on the app, you will automatically get the issue,,,,

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Kalytis** [comment]
Been having this problem for a week too. It resembles the problems of LibreTube proxies being blacklisted by Google, a few months ago.

**Comment by Snailhail** [comment]
Same issue just my normal solution to these issues Is to load a different instance & lower quality settings.  

Result: Swapping to an other one works better now. No long buffers.

On version 0.20.1 as well. I looked at Piped & they're having a similar problem as us. Possible IP banning as suggested by Kalytis.

https://github.com/TeamPiped/Piped/issues/2809

**Comment by Vikram0412** [comment]
@Snailhail how to swap to other one, can you guide me with the steps...
