### ISSUE TITLE
Auto Rotate

### ISSUE THREAD

**Issue by candroid-man** [libre-tube/LibreTube#524]
### Describe your suggested feature

The current build of LibreTube doesn't support auto rotation of any kind. This also means that you can only rotate the display a certain way rather than both ways. 

There is an open issue about this already, but it is outdated and doesn't explain much.

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
"I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue."
Obviously you didn't :)

**Comment by candroid-man** [comment]
To be fair I did uncheck the box after haha. I just wanted to make sure this is a somewhat priority, cause it is kind of annoying to have to orientate my screen a certain way when I'm watching videos
