### ISSUE TITLE
Instance button easier accessible. 

### ISSUE THREAD

**Issue by Grkrz** [libre-tube/LibreTube#5242]
### Describe your suggested feature

It would be nice if the instance choice would be easier accessible.
If the instance breaks you have to click many buttons to restart it. 
It would be nice to also nice if the app automaticly restart itself after changing the instance ass it it is needed anyway to make it work.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/3924
https://github.com/libre-tube/LibreTube/issues/4888
