### ISSUE TITLE
Video playback buffers extremely slowly

### ISSUE THREAD

**Issue by xlash123** [libre-tube/LibreTube#5243]
### Steps to reproduce

I am able to replicate this from a clean install of LibtreTube.
1. Select an instance
2. Click on a video
3. Spend a long time loading the video
4. Watch a few seconds of video
5. Spend a long time buffering
6. Repeat 4-5

### Expected behavior

Video should buffer at the same pace or better than playback.

### Actual behavior

Video buffers extremely slowly, and playback is interrupted constantly.

### LibreTube version

0.20.1

### Android version

Android 13 (/e/ OS 1.17-t)

### Other details

This seems to occur regardless of what instance I choose. I don't think it's demand because I run my own private instance of Piped and it happens on that and the official one too (piped.kavin.rocks). Playing video in the web browser buffers at a normal speed, so I think it's not Piped. Using NewPipe on my phone buffers at great speeds, so I don't think it's my device's bandwidth. I've also tried lowering the quality of the video to 144p, and it still buffers extremely slowly.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xiaomaisuii** [comment]
+1 I also encountered this problem

**Comment by dAtA-TRoN** [comment]
Yup, me too.

**Comment by ethanbarry** [comment]
It's happening for me as well, but it also occurs when using the Piped web app instead of LibreTube, thus, it's an issue with Piped. YouTube is very likely rate-limiting the server IPs.

A possible test is to spin up a new Piped instance, on a new server IP. However, I do not have the time; this is nearly finals week for me.

**Comment by Pamilg8** [comment]
When I close the Piped proxy, the videos don't start playing.

**Comment by ethanbarry** [comment]
> ... But why is it not working now?🤔

Well, not sure how much tech news you keep up with, but Google has been cracking down on adblocking and proxying efforts for some time now, and they're just pushing harder and harder.

I've got no problem with ads, but the ones Google shows are literal cow manure. I've got better things to do with my time than watch that stuff.

**Comment by Pamilg8** [comment]
> When I close the Piped proxy, the videos don't start playing.Very slow buffering or unable to play if proxy is on.There is an option to close the Piped proxy completely. But why is it not working now?🤔

There is an alternative YouTube API, but LibreTube won't want to run it

**Comment by Bnyro** [comment]
That's not a client side issue, YouTube throttling impacts Piped itself.

**Comment by xlash123** [comment]
I was able to find a workaround. My setting "Audio and Video > Use HLS" to on, buffering is greatly improved. Turning it off reverts the behavior back to what was originally reported.

I'm not confident that it's YouTube throttling given how I can still watch videos normally from the Piped browser client. Why is only Libretube affected, and why does using HLS fix it?
