### ISSUE TITLE
Top controls missing in audio player

### ISSUE THREAD

**Issue by opfromthestart** [libre-tube/LibreTube#5252]
### Steps to reproduce

1. Open a video
2. Click the audio button
3. Minimize the video
4. Go to settings
5. Return from settings
6. Click on the audio player bar
![Screenshot_20231128-200855_LibreTube](https://github.com/libre-tube/LibreTube/assets/13816619/5094cac4-bf41-48f2-bd00-37b9d7058124)

### Expected behavior

The top bar should still be visible, while the bottom bar should not.

### Actual behavior

The top controls to minimize the player and go back to video are missing.

### LibreTube version

0.20.1

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#5205
