### ISSUE TITLE
background audio appears to be broken

### ISSUE THREAD

**Issue by lordkitsuna** [libre-tube/LibreTube#5253]
### Steps to reproduce

Load a video
Press Play in background

### Expected behavior

Audio starts playing in background without video

### Actual behavior

If using Dash regardless of piped proxy or not you get Source error. When using hls playback does eventually occur however with frequent and constant buffering pauses

### LibreTube version

0.20.1

### Android version

12

### Other details

I want to say this started about maybe a week ago, background audio just suddenly refuses to work. If you are using the dash protocol you just get Source error. If you switch to hls it is able to eventually start background audio but extremely poor speed with constant buffering.

Video is not affected at all whatsoever, regardless of settings regardless of Dash or proxy or hls video playback is perfectly fine but it's annoying to have to use the extra bandwidth on the video when I'm not going to be watching it.

I've tried a couple instances to rule out the possibility of it being a problem with just my instance but I seem to get this same issue on multiple others

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
See https://github.com/TeamPiped/Piped/issues/3196

**Comment by lordkitsuna** [comment]
> See [TeamPiped/Piped#3196](https://github.com/TeamPiped/Piped/issues/3196)

Damn not sure how I missed that one when looking through the issues. Thank you
