### ISSUE TITLE
The channel page is not displaying featured channels

### ISSUE THREAD

**Issue by ShiroWeaver** [libre-tube/LibreTube#5257]
### Steps to reproduce

1. open the app
2. Open a channel 
![Screenshot_20231130_072437](https://github.com/libre-tube/LibreTube/assets/63943672/0e9eb0aa-219b-4ab3-ba8d-270b2997b272)
![Screenshot_20231130_073123](https://github.com/libre-tube/LibreTube/assets/63943672/da8df374-99d8-4195-abdd-72e68dfa5dd0)

### Expected behavior

It should have displayed an featured channel page
There is no channel button it does not show up it used to be there

### Actual behavior

It should have an channel button which displays featured channels

### LibreTube version

0.20.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/5184
