### ISSUE TITLE
Videos are not loading

### ISSUE THREAD

**Issue by PondelekB** [libre-tube/LibreTube#5258]
### Steps to reproduce

Choose any instance
Play any video

### Expected behavior

Video loading and then playing

### Actual behavior

Video loading for 2 sec and then coming back to not loaded , when pressing play 2nd or any time it just repeats loading dor 2 sec and returning to unloaded``

### LibreTube version

0.20.1

### Android version

Android 12

### Other details

Using some of the instances just straight blows off the app and closes it 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#5256
