### ISSUE TITLE
Video can not will be played

### ISSUE THREAD

**Issue by Pinguin10000** [libre-tube/LibreTube#5262]
### Steps to reproduce

Start any videos

### Expected behavior

Viedo playback

### Actual behavior

Stop loading video

### LibreTube version

0.20.1

### Android version

Android 14

### Other details

Device: Samsung A53 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Learn to follow instructions next time you open a report

**Comment by Pinguin10000** [comment]
https://github.com/libre-tube/LibreTube/assets/152312984/9c6141bd-f9f8-4d02-b440-2f34d50ed69b
