### ISSUE TITLE
Videos are not playing anymore

### ISSUE THREAD

**Issue by Profi420** [libre-tube/LibreTube#5270]
### Steps to reproduce

The Videos are not playing anymore

### Expected behavior

?

### Actual behavior

?

### LibreTube version

0.20.1

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Duplicate (as mentioned above) and learn to follow instructions next time you open an issue
