### ISSUE TITLE
doesn't play any video

### ISSUE THREAD

**Issue by Ehiffi** [libre-tube/LibreTube#5275]
### Steps to reproduce

1:You select a video 
2:It starts loading
3:It stops loading and video not showing, no audio either
4:You press play manually.
5:It starts loading
6:Repeat 3-5 for Infinity

### Expected behavior

It should normaly start playing video as soon as I press the video in my subscription tab. 

### Actual behavior

But it starts to load it and then player tries to load for like 3-4 sec, then it stops and you simply can't watch any video, not only video actually but the audio too

### LibreTube version

latest 0.20.1 fdroid

### Android version

android 12 pixel experience 

### Other details

I have no idea what happened but app is not usable, it started to happen like 3 days ago, thought it was a mere bug that everyone noticed

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Ehiffi** [comment]
I actually tried jumpiness from instance to instance but it didn't solve anything yet I have tried with disabling piped proxy, still no video.

**Comment by Bnyro** [comment]
#5256

**Comment by Ehiffi** [comment]
So you want to say it's because of slow connectivity in Russia?
