### ISSUE TITLE
Video does not play in an old device

### ISSUE THREAD

**Issue by anaseig** [libre-tube/LibreTube#5278]
### Steps to reproduce

No matter what video I select It does't wanna play.

### Expected behavior

Video starts playing normally.

### Actual behavior

Even if I change the server, video does not play, shows blank.
Selecting to some servers even makes the app crash itself (shown in video).

**VIDEO:** [https://drive.google.com/file/d/1jlXEVH-pCZF50vJElRFqxMFSg7qQsXBH/view?usp=sharing](url)

### LibreTube version

0.20.1

### Android version

Android 7.1.2

### Other details

My phone is Galaxy Tab E, which is quite old, but it runs Android 7.1.2 **Custom OS**.
I had no problem running videos from official **Youtube app/website** or even Y**ouTube Vanced** (when it wasn't dead),
I even had no problem playing videos with **LibreTube** until recently.

My internet speed is around **14-19MBPS**.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by 0xyassine** [comment]
I have the same issue
LibreTube version 0.20.1
Android 14 , samsung galaxy s23 offical firmware
Youtube and youtube revanced working 
Reproduced the same steps, re-install the app ...
So i believe it's not a bug in an old device only
