### ISSUE TITLE
Pop up menu

### ISSUE THREAD

**Issue by enessgokalp** [libre-tube/LibreTube#529]
### Describe your suggested feature

Can you align left pop up menu texts and maybe you can make smaller pop up menu?
![Screenshot_20220617-152818](https://user-images.githubusercontent.com/57983747/174298497-513cdc76-f747-497b-9c2b-9c13bf489780.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
![image](https://user-images.githubusercontent.com/82752168/174321784-6bd6691b-eb01-4a56-b3bc-45b3f1e32101.png)
I feel like it looks bad with left-aligned text

**Comment by Bnyro** [comment]
I think we should leave it as it is rn

**Comment by enessgokalp** [comment]
If you can make smaller popup it can be great
