### ISSUE TITLE
More advanced seperate pitch and speed control newpipe.

### ISSUE THREAD

**Issue by ccateni** [libre-tube/LibreTube#5293]
### Describe your suggested feature

Newpipe's best features are the skip silence and pitch / speed control. Though the skip silence and pitch / speed control are there, the later is limited compared to newpipe.
I would love to see the app gain a similar ability to change both the speed and pitch separately with more control of the speed and pitch rsther than the defaults.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You already have the ability to use the slider to change their values.
