### ISSUE TITLE
Pitch not saved, but speed is.

### ISSUE THREAD

**Issue by ccateni** [libre-tube/LibreTube#5295]
### Steps to reproduce

When you try to use the pitch control and speed, when you open another video, the pitch is back to normal, but the speed remains the same.

### Expected behavior

The speed and pitch should both be saved if it's enabled.

### Actual behavior

Only the speed is saved. The pitch reverts to normal.

### LibreTube version

0.20.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's intended, the speed usually makes sense to be kept, but the pitch is usually only changed temporarily to change the sound of the current video.
