### ISSUE TITLE
Time and system bar icons not visible when exiting from full screen

### ISSUE THREAD

**Issue by DecemberGiraffe** [libre-tube/LibreTube#5296]
### Steps to reproduce

This issue only occurs in light mode and does not occur in dark mode.
1. Watch video in full screen mode
2. Exit full screen mode

The issue is corrected by restarting the app.

### Expected behavior

Time and system icons are visible at the top.

### Actual behavior

Time and system icons are not visible at the top. There is just a white background.

### LibreTube version

0.20.1

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Try latest version and report back (share a recording if you're able to reproduce)

**Comment by Bnyro** [comment]
Closing due to no response and not reproducable.
