### ISSUE TITLE
Subscribe button text colour

### ISSUE THREAD

**Issue by enessgokalp** [libre-tube/LibreTube#530]
### Steps to reproduce

In subscriptions menu and when material you selected channel page subscribe button
![Screenshot_20220617-152828](https://user-images.githubusercontent.com/57983747/174299428-91c09a5f-951b-44ef-9603-b33f0d657622.jpg)
![Screenshot_20220617-153628](https://user-images.githubusercontent.com/57983747/174299489-86ae0d2b-058b-4f4c-a69a-c659befc4b72.jpg)

### Expected behavior

.

### Actual behavior

.

### LibreTube version

Last actions version

### Android version

Android 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by enessgokalp** [comment]
This is still nit completed
![Uploading Screenshot_20220617-192619.jpg…]()

**Comment by Bnyro** [comment]
I could swear I changed it. But obviously I didn't

**Comment by enessgokalp** [comment]
Maybe you can add shadow to button and can change subscribe text's colour
