### ISSUE TITLE
Playback issu

### ISSUE THREAD

**Issue by HYPERKid007** [libre-tube/LibreTube#5304]
### Steps to reproduce

![Screenshot_20231206-224254_LibreTube](https://github.com/libre-tube/LibreTube/assets/117347719/b2bf9964-9d3f-40e2-8145-a585eb47ba40)

### Expected behavior

For Indian users some videos are not playable. We have to use vpn to play those videos 

### Actual behavior

For Indian users some videos are not playable. We have to use vpn to play those videos 

### LibreTube version

0.20.1

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#5256
