### ISSUE TITLE
Minor improvements to Channel groups

### ISSUE THREAD

**Issue by shuvashish76** [libre-tube/LibreTube#5313]
### Describe your suggested feature

1. Change it to "(=)" icon as modern design (similar to what we use for sorting in Navigation bar)
2. Show total number of subscriptions used in a group. Reason: Makes easier to recognize when recreating groups. Newpipe show the number for groups so the user can be sure that they picked all their channels for specific group.
3. Add confirmation dialog when deleting a group. Reason: It takes some time to create them & deleting by misclick is annoying.

### Other details

![2023-12-09_14-50](https://github.com/libre-tube/LibreTube/assets/48226312/cb4d1807-0123-44c2-b388-a1340a03e239)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Some oft them were already suggested in #3558, please ask to append the remaining suggestions there.

**Comment by shuvashish76** [comment]
@Bnyro @IndusAryan Request to re-consider suggestion1: The drag handle (similar to #4490). And for suggestion3 it says "**Delete from Downloads**" while the confirmation dialog should show "Delete the Channel group" or "Delete from Channel groups".

Sorry to bring the topic again. 1 looks old design and 3 is just wrong translation to what you're going to do from UI.
