### ISSUE TITLE
Not playing videos

### ISSUE THREAD

**Issue by samij263** [libre-tube/LibreTube#5315]
### Steps to reproduce

1-Open app
2-open a video
3-loading icon starts to circulate
4-no loading sign and video doesn't play

### Expected behavior

Everything except video player loads well. Thumbnails, pages, video sections data.

### Actual behavior

Loading sign ends up with black screen

### LibreTube version

0.20.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#5256
