### ISSUE TITLE
Add channel to group in channel fragment

### ISSUE THREAD

**Issue by iiisak** [libre-tube/LibreTube#5316]
### Describe your suggested feature

When subscribing to a channel, LibreTube should allow the user to quickly add said channel to a folder. This could be done by either a pop-up at the bottom of the screen a la Tiktok's "Added to favorites     <Manage>" or by a button a la the bell icon.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
This can now be achieved by long pressing the subscribe button, but I'd like to find a better visual solution for that.

@M00nj
If you have some time, I'd be very thankful if you could come up with an idea how to re-organize the button in the channel fragment - currently the subscribe button, notification bell and share button are in a single row and there's no further place for the "add to group" button.

**Comment by M00NJ** [comment]
I don't think there's a ideal solution here. I think the best option is to put the three icons in a second row directly unter the subscribe button.
