### ISSUE TITLE
Error message when attempting to play any video

### ISSUE THREAD

**Issue by Raj2032** [libre-tube/LibreTube#5317]
### Steps to reproduce

Play any video

### Expected behavior

Should play video

### Actual behavior

Get an error message: `Initial player response is not valid`

![image](https://github.com/libre-tube/LibreTube/assets/29293830/ac50bea8-4041-4d56-9672-1d562f5d552b)

### LibreTube version

0.20.1

### Android version

Android 9 - Samsung Galaxy S8

### Other details

Tried changing different instances, same issues.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The instance is rate limited.

**Comment by Raj2032** [comment]
@Bnyro Can you tell me what I need to do?
