### ISSUE TITLE
about the issue

### ISSUE THREAD

**Issue by Nghia323223** [libre-tube/LibreTube#5320]
### Steps to reproduce

Open a video
Wait and it does not load

### Expected behavior

The video should load, even if use direct from youtubr it does not work.

### Actual behavior

The video stucked, even if direct option is used

### LibreTube version

0.20.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#5256
