### ISSUE TITLE
Video not playing when selected

### ISSUE THREAD

**Issue by manwiththeplan001** [libre-tube/LibreTube#5322]
### Steps to reproduce

Just go click any video 
In my case, it doesn't play, its stuck at loading for infinity. Further the play button is also not responsive, and yeah I have tried numerous instances.

### Expected behavior

The video has to play, infinite loading should stop.

### Actual behavior

Video doesn't play and loading infinitely.

### LibreTube version

20.1

### Android version

11

### Other details

![Screenshot_20231213-182124](https://github.com/libre-tube/LibreTube/assets/149300175/d8aa1074-8921-4b99-ad72-301e4920a022)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#5256
