### ISSUE TITLE
The Subscribe button does not work well.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#533]
### Steps to reproduce

1. Click the Subscribe button.
2. Subscribe.
3. Then repeat these actions.
4. The button has difficulty working and is delayed 

### Expected behavior

This should not have been the case.

### Actual behavior

There is a delay on the button.

### LibreTube version

0.3.2

### Android version

"Android 11"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I can tell you why it is delayed: Because your device has to communicate with the server, and that's delayed. Who thought that that would be possible :)

**Comment by Nephys222** [comment]
@Bnyro In latest version the subscription works smooth on Player view. But in Subscriptions tab/ in subscriptions menu button behave strange. At first it shows subscribe. After double click it appears Unsubscribe 
![image](https://user-images.githubusercontent.com/59939839/179919411-01edf0b5-7fbc-4f59-ac81-73460e749b11.png)

**Comment by Bnyro** [comment]
Yes, it waits for the API request to subscribe to the channel to finish. Anything else would lead to a subscribe and unsubscribe request running at the same time which is just a waste of server resources...

**Comment by Nephys222** [comment]
Then I think it should be "Unsubscribe" in default in xml value of subscription button on Subscriptions tab.

**Comment by Nephys222** [comment]
@Bnyro Can you check pls?

**Comment by Bnyro** [comment]
It is ...
