### ISSUE TITLE
Audio player stuck when swiping up

### ISSUE THREAD

**Issue by Azuras03** [libre-tube/LibreTube#5338]
### Steps to reproduce

1) Select a video to watch
2) Put it into audio only mode
3) Press the back button at the top left corner to minimise the player
4) Swipe the player up
5) The player is stuck, can't press back or minimize it

Bis) You can escape this stuck mode by pressing on the player notification, which will reset the player state on the UI

### Expected behavior

The player should be able to be swiped like it's the case with the video mode

### Actual behavior

The player is stuck when you swipe it up, and you can't swipe it down like it's possible with the video mode

### LibreTube version

0.20.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/5205
