### ISSUE TITLE
remember speed per channel

### ISSUE THREAD

**Issue by voidplayer** [libre-tube/LibreTube#5346]
### Describe your suggested feature

Being able to set default speed is neat but i have to switch speed almost in every video. Also missing 1.75x button but still too many clicks per video (including having to go back in the video because i missed something)

The most in common i can tell they have is channel. There are channels that i consistently watch at 2x, even 2.5x wouldnt be too crazy

And theres also channels that i consistently watch a 1.75x because 2x is too high. Some other musical channels that i consistently watch a 1x

Every click of a video basically turns into wak-a-mole. At least 6-7 taps. Would it be possible to add this so channels remember speed once i change the default speed?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Out of scope.
