### ISSUE TITLE
Problem returning from audio mode to video mode

### ISSUE THREAD

**Issue by marcossmtp** [libre-tube/LibreTube#5352]
### Steps to reproduce

It happens in my redmi 9c perhaps because screen resolution:
- Select a video
- Press audio mode
- Pull down and minimize the reproducition going to menu
- Pull up the the "video"

Options in the top bar to return to video mode dissapear and no other button works included the botton buttons to navigate to home,  playlists , etc.
Also try to pull down again the reproduotion doesnt work

### Expected behavior

Try to solve the issue

### Actual behavior

Always 

### LibreTube version

0.20.1

### Android version

android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Already fixed in debug builds.
