### ISSUE TITLE
Document spurious connections to the instance

### ISSUE THREAD

**Issue by opk12** [libre-tube/LibreTube#5360]
### Steps to reproduce

I do not open LT since a few weeks, but it still connects 3-5 times a day to `pipedapi.kavin.rocks`, uploading 351or 368 bytes and downloading 5.9 KB. I understand that it is the instance, but what info is being exchanged and why?

### Expected behavior

Clarify the reason for the unwarranted connections.

### Actual behavior

Connects without an apparent reason.

### LibreTube version

0.20.1 from F-droid

### Android version

Android 7.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Settings -> Notifications -> Disable

**Comment by opk12** [comment]
Notifications are already disabled. Issue persists on 0.21.1.
