### ISSUE TITLE
Oldest videos repeatedly displayed when loading channel videos

### ISSUE THREAD

**Issue by DanielProg39** [libre-tube/LibreTube#5361]
### Steps to reproduce

1. Open LibreTube and navigate to a channel page that has not very long (but long enough to scroll) list of videos
2. Scroll down through the video list until you reach the oldest videos
3. Continue scrolling down

### Expected behavior

You should't be able to scroll when you reached the oldest video.

### Actual behavior

After scrolling beyond the beginning of the upload history, more scrolling causes duplicates of the oldest videos to load.

https://github.com/libre-tube/LibreTube/assets/63293432/4e927f0f-0490-4f0d-a973-f37eade00713

### LibreTube version

Nightly 0.12.1 commit a9b58d9

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by RafaelsRamos** [comment]
I was able to reproduce this issue.
