### ISSUE TITLE
[master] Buttons in player page almost have no background

### ISSUE THREAD

**Issue by DanielProg39** [libre-tube/LibreTube#5363]
### Steps to reproduce

1. Open a video
2. Take a look on the buttons below the player (share, download, save, audio, comments)

### Expected behavior

They should be noticeable as buttons with visible outlines.

### Actual behavior

The colour of buttons is the same as the color of surrounding interface.

![Screenshot](https://github.com/libre-tube/LibreTube/assets/63293432/9b36514b-5b32-41fe-aba8-b5a6376265d0)

### LibreTube version

Nightly 0.12.1 commit a9b58d9

### Android version

Android 13

### Other details

I suggest that the buttons should have the same look as the "Subscriptions" button at the top of the "Subscriptions" tab (sorry for the pun).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
> I suggest that the buttons should have the same look as the "Subscriptions" button at the top of the "Subscriptions" tab (sorry for the pun).
>
In fact, they're already exactly the same buttons with exactly the same colours 😂

**Comment by DanielProg39** [comment]
Oh, now I see the problem. Lol, I thought you made the buttons too bright at first, but you overdid it a bit when you tried to fix it 😄

**Comment by RafaelsRamos** [comment]
I can take a look at this one, if available 👍

**Comment by Bnyro** [comment]
I think the best solution would be to use a different background color in the player page, as the current background color just looks too close to elevated material buttons.
