### ISSUE TITLE
Hide bottom bar on scroll

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#537]
### Describe your suggested feature

In order to increase content density, please hide the bottom bar on scroll.

### Other details

The bottom bar is very thick.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I'll combine this with #51
