### ISSUE TITLE
Random part of video automatically skipped fnr

### ISSUE THREAD

**Issue by DanielProg39** [libre-tube/LibreTube#5387]
### Steps to reproduce

Not really easy to reproduce. Happens quite rarely (twice for me (maybe more but I haven't noticed), the second time I recorded), disappears after restarting the app.
Basically, you watch the video and then notice that the frame has suddenly changed and what's said from that moment on doesn't really match what you heard before.
After watching the timeline and going back ~10-20 seconds and replaying from that point, you notice that at some point the player skips ~10 seconds and plays forward.

### Expected behavior

The video should play smoothly without skipping any chunks, with the exception of chunks marked by SponsorBlock.

### Actual behavior

Watch the time indicator.

https://github.com/libre-tube/LibreTube/assets/63293432/f9eeddc7-cb5f-4458-80bd-51e592b7142f

Here, after 10:39, the player jumps to 10:50.

### LibreTube version

Nightly 0.12.1 commit 887d062

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/5351

**Comment by DanielProg39** [comment]
Someone teach me how to find issues, because I always search them thoroughly, find nothing related to the issue, but 30% of the time end up posting a duplicate :joy:

Sorry guys

**Comment by akano12** [comment]
> Someone teach me how to find issues, because I always search them thoroughly, find nothing related to the issue, but 30% of the time end up posting a duplicate :joy:
> 
> Sorry guys

I read issues whenever a new one is opened so I'm always aware of the topics that are already answered/reported.

For this one i didn't remember the title of the original issue so i just searched for "skip" in closed issues and found the original one.

And a small tip, search using keywords not statements (skip, crash, comment, instance...)
