### ISSUE TITLE
Show replies button

### ISSUE THREAD

**Issue by ScrollScape** [libre-tube/LibreTube#539]
### Describe your suggested feature

please add a button to show comment replies as no one can see if someone has replied to a comment on any video in LibreTube.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I didn't add it because it destroys the UI.
