### ISSUE TITLE
Videos cannot be played when "Disable Piped Proxy" is enabled

### ISSUE THREAD

**Issue by person10301** [libre-tube/LibreTube#5391]
### Steps to reproduce

1. Enable "Disable Piped Proxy"
2. Enable VPN
3. Play video

### Expected behavior

Video must play

### Actual behavior

https://github.com/libre-tube/LibreTube/assets/105549221/b9f40a1d-54f3-45a4-8076-333d50e8d4f0

### LibreTube version

0.20.1

### Android version

Android 13

### Other details

Without a VPN, the video also does not play when “Disable Piped Proxy” is enabled, and because of this you have to enable “Use HLS” I would like to fix these problems 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Already fixed.

**Comment by Pamilg8** [comment]
He is right. I remember you fixed it with PR. But I checked again and it doesn't work.But I didn't have time to open a PR

**Comment by person10301** [comment]
This is not fixed, it does not work in both the release and debug versions

**Comment by akano12** [comment]
> Already fixed.

https://github.com/TeamPiped/Piped/issues/3196#issuecomment-1862748895
