### ISSUE TITLE
The pure black theme fails if the system does not allow it

### ISSUE THREAD

**Issue by Pamilg8** [libre-tube/LibreTube#5393]
### Steps to reproduce

1. Make sure dark mode is disabled on the system
2. Select "Dark" as the app theme (Enable the pure white/black option)
3. Pure black theme is not applied after app restart
4. Enable the dark theme on the system and repeat step 2.
5. Shown when you select the dark (pure black) theme

### Expected behavior

Activate pure black theme without system

### Actual behavior

Follow the steps above.A pure black theme is applied to Help, About, Settings.Not applied in the interface

### LibreTube version

0.20.1 Nightly

### Android version

Android 12, 13 (tested on many devices)

### Other details

https://github.com/libre-tube/LibreTube/assets/149590337/e7d42e26-ccd8-46de-b812-9f7309abfe11

https://github.com/libre-tube/LibreTube/assets/149590337/3d8b7521-7ae4-4bdf-a269-f7c1125df31d

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by liviucerchez** [comment]
I can confirm the Pure Theme is applied to Help, About, and Settings, but not applied to the main browsing interface. Android v7.0. LibreTube 0.21.1. Theme > Dark, Accents > Minimalistic Monochrome.
![Screenshot_2024-01-08-11-12-18-143](https://github.com/libre-tube/LibreTube/assets/223238/e360cd80-1a64-4feb-a65c-96579ed2a71d)
![Screenshot_2024-01-08-11-12-42-498](https://github.com/libre-tube/LibreTube/assets/223238/aea20568-b588-4ac9-80b0-59fb00a08b31)

**Comment by Bnyro** [comment]
Seems like a ROM-related issue, unfortunately there's no way to help with that.
