### ISSUE TITLE
Sleep timer not behaving like I'd expect

### ISSUE THREAD

**Issue by gojzdar** [libre-tube/LibreTube#5395]
### Steps to reproduce

1. Use libretube 0.20.1 v8a
2. Go to settings > sleep timer
3. Select it and set the time

### Expected behavior

After N minutes, close the app. Once. Without needing to restart and with a view on how long you have left, with the option to reset the timer.
So more like "N minutes until shutdown timer".
Ideally, it should work like android clock timer applet, which tells you how much longer you have before the app closes. Something you'd use when wanting some white noise to sleep for example. It would be interesting if you could also schedule it, so it would automatically close to app at 3am.

### Actual behavior

More like take a break timer. Every N minutes, it gives you a 5 second timer (which is way too short) to cancel the closing of the app. If this is intended, please rename it to "Break reminder" or "Break timer" instead of sleep timer.

### LibreTube version

0.20.1 v8a

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
This feature has been reworked on the master branch.
