### ISSUE TITLE
Videos do not loop when autoplay is off

### ISSUE THREAD

**Issue by FamiliarBreakfast** [libre-tube/LibreTube#5396]
### Steps to reproduce

1. Play any video
2. Ensure autoplay is off
3. Set video to loop in the dropdown menu
4. Video doesnt loop when completed

### Expected behavior

The video should go back to the start

### Actual behavior

The video ends as if it wasny set to loop

### LibreTube version

0.20.1

### Android version

Android 13

### Other details

Unsure if this is intentional or not.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by RafaelsRamos** [comment]
Hey @FamiliarBreakfast, congrats on the first issue in the repo! 💪 

I am having trouble replicating the issue. Are we talking about the **Gear Icon > Repeat mode > Current** setting?
Additionally, could you confirm if the issue you are experiencing can be related to this other issue - #5173?

Thanks!

**Comment by akano12** [comment]
@FamiliarBreakfast

You should have the autoplay toggle set to on from the player UI for looping to work, hope this fixes your problem

**Comment by FamiliarBreakfast** [comment]
> @FamiliarBreakfast
> 
> You should have the autoplay toggle set to on from the player UI for looping to work, hope this fixes your problem

This did solve it, was this change intentional? It doesn't really make much sense.

**Comment by akano12** [comment]
> This did solve it, was this change intentional? It doesn't really make much sense.

I'm not sure to be honest as i've never looped a video before, i only tried it once while trying to replicate your problem, toggling autoplay fixed the issue. It just seems that the code/logic to handle such scenario isn't implemented or intended behaviour/ designed like this
