### ISSUE TITLE
German Translation 

### ISSUE THREAD

**Issue by BlazeCodeDev** [libre-tube/LibreTube#54]
If possible I would volunteer to translate the app into German.

**Comment by alefvanoon** [comment]
Nice, I will ping you when possible.

**Comment by Stenafo** [comment]
Italian translator here, I'm also available to translate the app :)

**Comment by BlazeCodeDev** [comment]
@alefvanoon I could also fork it and create a pull request when I'm done if you want!

**Comment by lilcheti** [comment]
Hey, we just integrated weblate you can start translating here: https://hosted.weblate.org/projects/libretube/libretube/

**Comment by lilcheti** [comment]
@BlazeCodeDev @Stenafo
