### ISSUE TITLE
option to hide home page (trend) tab

### ISSUE THREAD

**Issue by lucamp** [libre-tube/LibreTube#540]
I already setup feed as default start tab, but It will be nice to have an option that allows the complete disabling of home page tab since it very annoying and videos are always not interesting

**Comment by Bnyro** [comment]
That's not planned, just don't navigate to the home tab if you don't want to use it.

**Comment by Bnyro** [comment]
Or maybe I'll add it, it's not much work, idk

**Comment by lucamp** [comment]
> Or maybe I'll add it, it's not much work, idk

If you can it would be very appreciated 🙂

I can definitely avoid going to home page tab, nevertheless I find that tab as a really bad habit issue for every user, especially new ones that starts to play with libretube or Youtube. Someone could become "addicted" to it, and honestly the recommendation are questionable, but that is a YouTube issue and not a Piped one
