### ISSUE TITLE
Allow users to customise suggested speeds and pitches to be avalible in the playback options sheet.

### ISSUE THREAD

**Issue by MinekPo1** [libre-tube/LibreTube#5411]
### Describe your suggested feature

As of writing the suggested speeds and pitches available are hard coded (see [LibreTube/app/src/main/java/com/github/libretube/ui/sheets/PlaybackOptionsSheet.kt:83-84](https://github.com/libre-tube/LibreTube/blob/5bf65dfcfe5344905866e9960e685e06d0a31a58/app/src/main/java/com/github/libretube/ui/sheets/PlaybackOptionsSheet.kt#L83-L84)).

I believe that due to the nature of playback speed and to a lesser extent playback pitch, the value which a user likes best varies greatly not only between users but also between what content the user is watching (raised in #5346). Furthermore I believe that giving this option to the users would not clutter the UI or otherwise hinder UX for users which don't want it.

### Other details

I believe that this is a separate, though related, topic from #5398.

While my experience with Kotlin and Android app development (or rather lack thereof) does not allow me to have a lot of confidence in my guess, though I presume this is something which is relatively easy to implement.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Adding options for such small customizations is not planned:
1. Adding more settings makes the app less intuitive for new users.
2. There's a slider in the playback sheet for selecting values that are not part of the quick suggestions, there's no reason to not use it.
