### ISSUE TITLE
Scheduled auto-download for audio files 

### ISSUE THREAD

**Issue by MaxVonMustermann** [libre-tube/LibreTube#5412]
### Describe your suggested feature

Since LibreTube features the ability to play videos as "audio only", I decided to use the app for podcasts that are only available on YouTube.
I am wondering, if it was possible to add the ability of LibreTube automatically downloading audio files of specified YouTubers/the subscription list, in order to make the app more convenient.

### Other details

I imagine it like this:
- Start download automatically, if connected to a Wlan network
- Also add the ability to decide when to download files; set a timeframe to prevent downloads at given times
- Add a setting to decide how many episodes are to be kept on the device --> Auto delete episodes that are older than xyz 

Thank you very much and a happy new year!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Sorry, that's out of scope for the app.

First of all, LibreTube is primarily a video streaming and not a downloader app. For a podcast app for instance, I agree that this feature would make sense, but LibreTube just doesn't really intend to be one.

Second, automatic downloads would use a lot of additional bandwidth which could lead to potential performance issues at smaller Piped instances. Auto-downloads will certainly increase the amount of downloaded media, and many of the downloaded videos might not even be of interest for the user and get auto-downloaded but never watched.
