### ISSUE TITLE
Bottom of instance list cut off

### ISSUE THREAD

**Issue by MatsG23** [libre-tube/LibreTube#5416]
### Steps to reproduce

1. Open the settings page
2. Open the instance list (changed in version 0.21.0 to also show e.g. the proxy availability)
3. Scroll to the bottom of the list

### Expected behavior

The padding of the last list item should be the same as the padding between every item.

### Actual behavior

The last list item in the instance list is cut off a little bit. This is fixed temporarily once you select the last list item.

### LibreTube version

0.21.0

### Android version

Android 13 (GrapheneOS)

### Other details

The instance list has to be long enough so that you can scroll a bit until you reach the list bottom. This is no longer the case right now, so I cannot provide a screenshot currently.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by HmidouZaka** [comment]
ok I will fix this issue now

**Comment by Bnyro** [comment]
The list of instances is larger now, but I still can't reproduce the issue.

**Comment by Bnyro** [comment]
Please share a screenshot if it's still reproducible.
