### ISSUE TITLE
Installation fails without an error message 

### ISSUE THREAD

**Issue by Uinsart** [libre-tube/LibreTube#5417]
### Steps to reproduce

Downloading the apk from GitHub or trying to install it via F-Droid.
I have tried all available versions and .apks. Even tho I had it installed and used it for quite a while, if I try to install LibreTube now, the Installer crashes without an error message.

### Expected behavior

It should install.

### Actual behavior

The Installer crashes when I press on "Install".

### LibreTube version

newest and the next 3 older versions 

### Android version

14

### Other details

I am on an Google Pixel 6 with android 14 and the newest updates.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/5406
