### ISSUE TITLE
Option for icon only video options

### ISSUE THREAD

**Issue by gojzdar** [libre-tube/LibreTube#5419]
### Describe your suggested feature

The buttons under the video (share, download, save, audiomode) require more space than is available in portrait orientation. If you add an option to remove the text next to the icons, this problem could be solved.

### Other details

This is low priority but it would be nice to have.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
There are no plans to add new options for such small behavior changes, since it would clutter the settings.
