### ISSUE TITLE
Very slow loading of videos 

### ISSUE THREAD

**Issue by panoskpv** [libre-tube/LibreTube#5423]
### Steps to reproduce

Select whatever instance you want and try to play a video.

### Expected behavior

Load video without stops for buffering

### Actual behavior

During the last one two months, loading of videos has become too slow and videos keep stopping for buffering to a level that it is unbearable to watch a video. 

### LibreTube version

0.21.0

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Public instances experience a lot of traffic, you should host your own instance or disable the proxy and use a vpn.
