### ISSUE TITLE
A option to load unlimited(at least a lot) videos in home feed

### ISSUE THREAD

**Issue by Tanzin01** [libre-tube/LibreTube#5428]
### Describe your suggested feature

The home page only contains 8 around videos. Would be cool to have a tons here for people who watches yt a lot.

Also may be another really really nice option for everyone(even who watches official yt client's) would be to not to show videos ever which a person has watched before.
Cool app

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not supported by Piped. The maximum time difference of the videos depends on the instance you use.
