### ISSUE TITLE
Re-opening app after opening link loads video again

### ISSUE THREAD

**Issue by D3SOX** [libre-tube/LibreTube#543]
### Steps to reproduce

1. Open a link in LibreTube
2. Close the video
3. Switch to another app
4. Switch back to LibreTube

### Expected behavior

Don't load video again

### Actual behavior

Loads video again

### LibreTube version

0.3.2

### Android version

Android 11 LineageOS

### Other details

Not sure if this is expected behavior

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It's not intended but it works fine for me (-_-)

**Comment by Bnyro** [comment]
You have picture in picture disabled?

**Comment by Bnyro** [comment]
Yes, it's intended, it should continue to play in the background (audio only) (if I underszood you right)

**Comment by D3SOX** [comment]
I will send a video once I have time to record it.

**Comment by Bnyro** [comment]
couldn't figure out what the problem is, you can reopen the issue if you can provide more info

**Comment by D3SOX** [comment]
https://user-images.githubusercontent.com/24937357/175366457-ae3dc2d7-c866-4744-b354-cd830f26ec03.mp4

**Comment by Bnyro** [comment]
just send it on telegram or matrix

**Comment by D3SOX** [comment]
I'm not sure if that's even fixable as I have seen this kind of behavior with many apps

**Comment by Bnyro** [comment]
So you think it's an android issue? OK then :)

**Comment by D3SOX** [comment]
As I said, I don't know but I'm sure it could be worked around
