### ISSUE TITLE
dark material you colors on latest

### ISSUE THREAD

**Issue by Henry-Hiles** [libre-tube/LibreTube#5437]
### Steps to reproduce

Update to latest
Use apo

### Expected behavior

Normal material you colors the same as other apps

### Actual behavior

Darker material you colors

### LibreTube version

0.21.0

### Android version

Android 13

### Other details

![Screenshot_20240104-173557_LibreTube](https://github.com/libre-tube/LibreTube/assets/71790868/b525550a-4eee-49cf-99e8-211abf5c489d)
![Screenshot_20240104-173547_QWeather](https://github.com/libre-tube/LibreTube/assets/71790868/b9d31cbf-78af-4960-ba53-5a66ca7d4cdb)
Libretube app and regular m3 app ^^

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Henry-Hiles** [comment]
This only started happening when I recently updated.

**Comment by M00NJ** [comment]
This is the intended behavior. Since LibreTube is a streaming app and the focus should be on the content the decision was made to use darker colors.

**Comment by Henry-Hiles** [comment]
Well this ruins the app for me, the whole reason I use libretube is for material you.

**Comment by Henry-Hiles** [comment]
Could this not be a setting?

**Comment by Henry-Hiles** [comment]
No, I don't.

**Comment by M00NJ** [comment]
The app still follows material you, it just has a darker background color. The primary color is still the same like in your other apps, so I don't see why this would be ruining anything. The background color that was chosen is part of the MD3 guidelines. You might not have seen it often, but it is one of the options you can pick for material you. So far I haven't seen many users complain, so I don't think this will be made optional, but that's not up to me. Imo the app has quite a lot of customisation option already.

**Comment by Bnyro** [comment]
As @M00NJ already said, there are no plans for changes here.
