### ISSUE TITLE
Grey out Subscribe button for already subscribed channels

### ISSUE THREAD

**Issue by Ehab-d** [libre-tube/LibreTube#5438]
### Describe your suggested feature

The Subscribe button should be greyed out when I'm already subscribed to a channel.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
and how do you plan to unsubscribe if it's greyed out?!
