### ISSUE TITLE
Volume swipe alway work in audio only mode despite swipe controls turn off?

### ISSUE THREAD

**Issue by SAOS200X** [libre-tube/LibreTube#5445]
### Steps to reproduce

1. Turn on audio only mode and turn off swipe controls.
2. Play any video and swipe.
3. The Volume swipe alway work despite swipe controls turn on or off.

### Expected behavior

It should able to adjust the brightness and volume like normal when turn on audio only mode.

### Actual behavior

Only the volume adjust work and alway work in audio only mode despite the swipe controls turn off.

### LibreTube version

0.21.0 universal-release

### Android version

Android 10

### Other details

https://github.com/libre-tube/LibreTube/assets/107041820/b7073574-fc84-41a1-bbd2-50a1904f7bc6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's the intended behavior, the preference only impacts the video player as you can't really accidentially trigger that action in the audio player.
