### ISSUE TITLE
Playlists load infinitely

### ISSUE THREAD

**Issue by 12emin34** [libre-tube/LibreTube#5446]
### Steps to reproduce

1. Find a playlist
2. Tap on it

### Expected behavior

The playlist should load and show the list of videos

### Actual behavior

The playlist never loads the video list, instead showing the loading spinner animation infinitely

### LibreTube version

0.21.0

### Android version

Android 9

### Other details

Phone: LG G6
LibreTube is installed from F-Droid

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SAOS200X** [comment]
well, I think it is actually caused by the instance since mass of peoples using it, you could change to the different instance or switch to use VPN if none of them are work.

**Comment by 12emin34** [comment]
I've already tried every instance (fully restarting the app when switching), and it's always the same. I'll try a VPN, but I don't quite see why would that work.

**Comment by akano12** [comment]
> well, I think it is actually caused by the instance since mass of peoples using it, you could change to the different instance or switch to use VPN if none of them are work.

Happens regardless of the instance
