### ISSUE TITLE
Volume / Brightness by swipe

### ISSUE THREAD

**Issue by Archeix7** [libre-tube/LibreTube#545]
### Describe your suggested feature

Brightness and sound adjustment on the left and right sides of the screen, as in YT Vanced

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I'm strictly against it because it's just annoying for me and not useful in any way. You can change the brightness in the control center of Android and the volume with physical buttons. There's no reason to annoy users with changing brightness and volume accidently.

**Comment by Archeix7** [comment]
How about adding this feature for those who need it. Who needs to turn on, who does not need to turn off and everyone can please

**Comment by Bnyro** [comment]
idk, I think Farbod wants to make sth like that when he has time, at least I won't add it. We'll see.

**Comment by Archeix7** [comment]
😔

**Comment by Bnyro** [comment]
As you probably know you have the option to open the video in vlc, I think vlc has sth like that

**Comment by Archeix7** [comment]
I use different video player. And anyway, it would be more convenient to do it on YouTube, you don’t need to pull the curtain once again, interrupt, or reach for the “down” button with your finger to reduce the sound, the phone is big and it’s not convenient

**Comment by Archeix7** [comment]
😐
