### ISSUE TITLE
Adding multiple selection to the subscription feed filter 

### ISSUE THREAD

**Issue by ghost** [libre-tube/LibreTube#5453]
### Describe your suggested feature

Currently in the subscription feed you can filter by selecting only one of the following options: All, Videos, Shorts & Livestreams. As I am only interested in videos and livestreams. I have to switch between those options and sometimes can be annoying. I don't use de "All" option because shorts are included and there are to many of them that it takes time to get to the videos and livestreams.

My suggestion is add a checkbox to each option in the filters, so the user can check the options that he wants to see.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by RafaelsRamos** [comment]
This suggestion sounds great. I would love to work on this one

**Comment by RafaelsRamos** [comment]
A proposal for the UX below, please let me know your thoughts:

https://github.com/libre-tube/LibreTube/assets/40279132/9a49b187-ece0-4707-80b0-f8eb9ef58028

**Comment by RafaelsRamos** [comment]
Do you mean adding these chips to the sort bottomsheet? Thus having sort of a Sort/Filter bottom sheet? 🤔

**Comment by RafaelsRamos** [comment]
Got it! Tomorrow I'll try it out, and update the thread, to compare with the approach above 👍

**Comment by RafaelsRamos** [comment]
Hey @SameenAhnaf  👋  Please let me know what you think. Video sample below.

https://github.com/libre-tube/LibreTube/assets/40279132/e3974e4a-9573-44d0-84cb-b10965992887

**Comment by RafaelsRamos** [comment]
Sounds good!

**Comment by sineptic** [comment]
hello, maybe you require at least 1 option must be selected? ( because I'd thing that it is bag, when  I see empty list of videos)

**Comment by RafaelsRamos** [comment]
Where's the UX with at least 1 option selection

https://github.com/libre-tube/LibreTube/assets/40279132/1679891f-8841-41de-bb1c-7bb93a5620a7
