### ISSUE TITLE
Recurring issue with Bluetooth audio controls

### ISSUE THREAD

**Issue by blindm0use** [libre-tube/LibreTube#5455]
### Steps to reproduce

1. Connect Bluetooth headset/earbuds to your device;
2. Open LibreTube and start playing playlist in the background;
3. Try pausing the video/audio with the controls on your bluetooth headset/earbuds;
4. When video/audio is paused try to resume the playback by single press of the play button on your bluetooth headset/earbuds;
5. When video/audio is resumed and running, try waiting more than 10 seconds and press pause button on your Bluetooth headset/earbuds again.

### Expected behavior

The built-in player in LibreTube should respond to Bluetooth headset/earbuds controls, enabling seamless audio/video playback without the need for repeated pressing of play controls on the Bluetooth headset/earbuds.

### Actual behavior

The LibreTube built-in player fails to respond with a single press/activation on Bluetooth headset/earbuds for playback after the video/audio has been paused or when the video/audio had been running for a specific duration longer than 10 seconds.

### LibreTube version

0.21.0

### Android version

Android 13

### Device Info
Manufacturer: samsung
Model: SM-G996U1 (Galaxy S21+)

### Bluetooth Device Info
Manufacturer: samsung
Model: SM-R175 (Galaxy Buds +)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/pull/5427/files
