### ISSUE TITLE
miniplayer is being dismissed unwxpectedly

### ISSUE THREAD

**Issue by Silther** [libre-tube/LibreTube#5459]
### Steps to reproduce

Minimze the player slowly or very fast

### Expected behavior

It should transition to the miniplayer

### Actual behavior

Animation breakes and miniplayer vanishes + navbar is half or fully hidden

### LibreTube version

0.21.1

### Android version

Android 14

### Other details

![Screenshot_20240108_010208_LibreTube](https://github.com/libre-tube/LibreTube/assets/97352673/19cc6556-d3ba-4a9c-bd18-db373c7363d1)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by IndusAryan** [comment]
yes, happens frequently. one issue more is there that miniplayer dismiss gesture is not robust @RafaelsRamos for example, it should only be dismissed when fully swiped at the bottom + when we lift our fingers, stop touch event, like og youtube app. not very rapid

**Comment by RafaelsRamos** [comment]
Yep, I'm experiencing the same. I'll take a look at this issue.
