### ISSUE TITLE
Clearing watch history doesn't clean watch progress

### ISSUE THREAD

**Issue by arkibax** [libre-tube/LibreTube#5467]
### Steps to reproduce

1. Watch video
2. Clean watch history
3. Go back to the watched video

### Expected behavior

Videos shouldn't have watch progress after cleaning watch history

### Actual behavior

Video still has watch progress line

### LibreTube version

0.21.1

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
There's a separate option to clean watch positions, the behavior is intended.
