### ISSUE TITLE
Many problems in user interface design

### ISSUE THREAD

**Issue by Official-Mlx** [libre-tube/LibreTube#5469]
### Steps to reproduce

One. The color of the navigation bar should be dynamic, like the image below, which does not match the background at all:
![Screenshot_2024-01-10-01-39-38-819_com github libretube](https://github.com/libre-tube/LibreTube/assets/74877307/814a28ea-532a-479b-b51a-02f5c9ef1d89)

Its color should be the same as the background color.

Two.Care has not been taken in choosing the icons, some icons are stroke and some are bold, this messes up the app's fit.

![Screenshot_2024-01-10-01-39-44-020_com github libretube](https://github.com/libre-tube/LibreTube/assets/74877307/5b2544cc-1ca9-4ae3-b354-6e348c155976)

As you can see in this picture, some icons do not match with others, and some are smaller or bigger than others.

### Expected behavior

It is quite clear.

### Actual behavior

It is quite clear.

### LibreTube version

the last version

### Android version

Android 10

### Other details

It is quite clear.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Feel free to create pull requests for these small visual changes, it's far from being a bug however.
