### ISSUE TITLE
Auto-fullscreen on shorts sometimes won't work

### ISSUE THREAD

**Issue by kubo6472** [libre-tube/LibreTube#5470]
### Steps to reproduce

Open a short with auto-fullscreen turned on.

### Expected behavior

It should work all the time.

### Actual behavior

Sometimes it works, sometimes it doesn't.

### LibreTube version

0.21.1

### Android version

14

### Other details

Video I was trying to play: https://youtu.be/nT-JCsZKITY
Screen recording: https://i.imgur.com/iBOQRkh.mp4 (GitHub would not fit it)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by IndusAryan** [comment]
It did open open in full screen automatically for me but i am on A13. and LT currently doesn't target SDK API 34 directly.

**Comment by Bnyro** [comment]
We now target SDK 34 since https://github.com/libre-tube/LibreTube/pull/5663 (not sure if that's related though anyways).

Though it doesn't seem to be reproducible.
