### ISSUE TITLE
Recommended player videos are very small 

### ISSUE THREAD

**Issue by Warden20** [libre-tube/LibreTube#5477]
### Steps to reproduce

1. Adjust the display size dial for the minus symbol.
2. Open any video
3.The recommended videos below the player appear very small, this happens with any display size setting.

### Expected behavior

Normally, recommended videos would use the full width of the screen, with only one recommended video appearing. 

### Actual behavior

I have this problem in the player.  Where the recommended videos appear too small, as in the image. I think it is influenced by the screen size as in the other image. 
My problem is that only if I use the complete opposite configuration where few elements appear on screen there the recommended videos below the player occupy all the horizontal space. 
But this makes my phone unusable by affecting the whole device.
![Settings](https://github.com/libre-tube/LibreTube/assets/64172827/9b147289-7ea5-4626-a470-d1deceef3c6f)
![LibreTube Debug 0](https://github.com/libre-tube/LibreTube/assets/64172827/06bb7d56-a89c-466f-8b68-efe8e98c905b)

### LibreTube version

Nightly and 0.21.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Why should this be making your phone unusable? I don't get the point.

The size of the recommended videos varies based on your screen size - your screen seems to be quite large so the videos are rather taking fewer space in relation to the screen size than on smaller devices.

**Comment by Warden20** [comment]
I understood and readjusted my configuration, you can close the issue.
