### ISSUE TITLE
Stories, community posts and playlists by Creators

### ISSUE THREAD

**Issue by NR8124** [libre-tube/LibreTube#548]
### Describe your suggested feature

Youtube Creators  uploads stories and community posts on their channel for better interaction with their subscribers. So it would be better if these things would be integrated with Libretube also.

### Other details

I love you work and appreciate it...❤🙌 It is daily driver app for me now..

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thank you for your kind words :)
As far as I know the Piped API doesn't support community stories and posts (at least I can't find it on https://piped.kavin.rocks). We'll add it as soon as they add support for it (if they do). You could open an issue on their GitHub repo, maybe they'll implement it.
