### ISSUE TITLE
Where did the popout feature go?

### ISSUE THREAD

**Issue by MrPantherKing** [libre-tube/LibreTube#5485]
### Steps to reproduce

While the video is playing, below description there was popout option! Not anymore?

### Expected behavior

Should be there

### Actual behavior

Isn't there

### LibreTube version

0.21.1

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not anymore, yes.
