### ISSUE TITLE
Add filter for minimum video length

### ISSUE THREAD

**Issue by schneidr** [libre-tube/LibreTube#5487]
### Describe your suggested feature

Please add a filter with a minimum video length to show up in all lists.

### Other details

The YouTube Kodi addon has this and I came to value it very much.
I'm aware that I can filter out shorts in the abo section, but there I constantly have to switch between videos and live streams, and in search results or channel views I still see those dreaded shorts.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/3635

**Comment by schneidr** [comment]
I don't see this as a dupe. The API is not needed for this, filtering can be done when the list is shown. Also, this suggestion is not (only) about search results.

**Comment by akano12** [comment]
> I don't see this as a dupe. The API is not needed for this, filtering can be done when the list is shown. Also, this suggestion is not (only) about search results.

How are you going to add filters if the info needed (video length) for filtering isn't provided by piped api?
