### ISSUE TITLE
Sometimes usage of exit full screen gesture option in fullscreen(Landscape), mini player hides the navbar

### ISSUE THREAD

**Issue by Eliya-Manoj** [libre-tube/LibreTube#5488]
### Steps to reproduce

1. play video in landscape ( only use gestures )
2. exit from landscape using gesture
3. 2 issues - miniplayer hides navbar & https://github.com/libre-tube/LibreTube/issues/5158

https://github.com/libre-tube/LibreTube/assets/90308888/8ddd8e13-b5c0-4681-82a1-bcbbaeb4e790

https://github.com/libre-tube/LibreTube/assets/90308888/1982c9b7-31e3-451d-be9f-59126ac08653

### Expected behavior

Only exit from fullscreen. 

![6134231034594703995_121](https://github.com/libre-tube/LibreTube/assets/90308888/fa6d1b12-4763-4bcf-9710-990133f764ae)
Like this

### Actual behavior

Hides NavBar

### LibreTube version

Latest Debug

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/pull/5694
