### ISSUE TITLE
Share button under video links to wrong Piped instance.

### ISSUE THREAD

**Issue by the4anoni** [libre-tube/LibreTube#5489]
### Steps to reproduce

1. Set your own Piped instance
2. Launch video
3.  Share Piped link to social media.

### Expected behavior

Shared link has currently set up instance domain.

### Actual behavior

Shared link targets to piped.video for some reason

### LibreTube version

0.21.1

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We only have information about the instance backend URL, but backends are not necessarily limked to and requiring to host a frontend.
