### ISSUE TITLE
Problem viewing/editing subscriptions at own piped instance.

### ISSUE THREAD

**Issue by dr0bz** [libre-tube/LibreTube#5496]
### Steps to reproduce

1. Fresh install or wipe app data
2. Open app
3. Add your own instance
4. Restart the app
5. Enter login data
6. Go to subscription page
7. Click on subscription button/dropdown on the top

### Expected behavior

You should see the list of your subscriptions saved in your account

### Actual behavior

1. The videos of your subscriptions show up (subscription page)
2. When you try to view your subscription list (button/dropdown on the top) -> the load indicator runs forever and you get a notification: Problem with selected server, try another one.

### LibreTube version

0.21.1

### Android version

Android 14

### Other details

I'm running my own piped instance (proxy/frontend/api). The web frontend works without problems. I can view/edit/delete my subscriptions. The versions of the proxy/frontend/api are always the latest, watchtower updates it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by dr0bz** [comment]
Are there any ways to debug the stuff as a normal user, without installing the whole environment etc.?

**Comment by Bnyro** [comment]
> Are there any ways to debug the stuff as a normal user, without installing the whole environment etc.?
>
No, not for that purpose.

**Comment by Bnyro** [comment]
Due to the fact that this works fine on all public instances, and LibreTube works similar to the Piped web frontend, I unfortunately don't know any way to help you with that.
