### ISSUE TITLE
add shorter request timeout for dearrow

### ISSUE THREAD

**Issue by pokegamer5547** [libre-tube/LibreTube#5499]
### Describe your suggested feature

I like using dearrow and i'm aware settings page says it increases load time. But i noticed from few days that only when dearrow it's enabled all requests (search,feed, etc) takes almost a minute to load. Maybe dearrow server is down sometimes. 

Rather than trying to wait entire minute, add somekind of timeout of like 5-10 seconds so it doesnt take a entire minute to load.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Unfortunately, it's not possible to change the timeout per request via Cronet. We currently have a timeout of 10 seconds for each request, so opening a channel can take 20 seconds max (10 seconds fetching channel, 10 seconds dearrow).

**Comment by pokegamer5547** [comment]
> Unfortunately, it's not possible to change the timeout per request via Cronet. We currently have a timeout of 10 seconds for each request, so opening a channel can take 20 seconds max (10 seconds fetching channel, 10 seconds dearrow).

I understand. But in my case, only when i have dearrow enabled it's taking even entire minute just to load. Is it really 10 seconds?

**Comment by Bnyro** [comment]
Yes.
