### ISSUE TITLE
Seek button text alignment

### ISSUE THREAD

**Issue by GilesMunn** [libre-tube/LibreTube#550]
### Steps to reproduce

Set seek duration to anything other than 5s

### Expected behavior

The number of seconds that the video will seek by should appear cleanly in the fast-forward/rewind buttons

### Actual behavior

The buttons are too small and causes text wrapping if the duration is greater than single digits
![ffward](https://user-images.githubusercontent.com/25082324/174448039-8685ebed-2f71-45c9-9306-ab77ed1dc9dc.png)

### LibreTube version

0.3.2

### Android version

Android 12

### Other details

Thank you for implementing the seek duration preference so quickly

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I add an option, 2 minutes later the first complains, lmao

**Comment by GilesMunn** [comment]
> I add an option, 2 minutes later the first complains, lmao

I was working on the same bug myself for my own fix, you just beat me to the initial commit so I had to point it out!

**Comment by Bnyro** [comment]
Oh, lmao, if I knew that xD

**Comment by Bnyro** [comment]
You're allowed to fix it :)
