### ISSUE TITLE
Export/Import option for All  settings/preferences/subscription section

### ISSUE THREAD

**Issue by NR8124** [libre-tube/LibreTube#551]
### Describe your suggested feature

It would be more convenient and ease in use if we can export our settings/preferences and subscriptions... Which we can later import later or share with someone else for their ease.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Exporting and importing the settings isn't really possible to code, exporting subscriptions is already another issue.
