### ISSUE TITLE
Fastlane: changelogs too long

### ISSUE THREAD

**Issue by IzzySoft** [libre-tube/LibreTube#5513]
### Steps to reproduce

Count the characters in your changelogs (46.txt & 47.txt)

### Expected behavior

There are no more than 500 characters, as per Fastlane specifications, as all beyond that would be cut off – even mid-word.

### Actual behavior

There are 570 resp. 522 characters, so they will be cut off.

### LibreTube version

n/a

### Android version

n/a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Oh okay, thank you for the information @IzzySoft! :+1:

I'll make sure to shorten them next time, however I think for the previous releases we can live with it.

**Comment by IzzySoft** [comment]
Yes, agreed: the previous one wouldn't be "re-fetched" anyway, so I truncated it here manually (in a more meaningful way then cutting things mid-word).
