### ISSUE TITLE
Wrong channel name and thumbnail of video. 

### ISSUE THREAD

**Issue by VitoItalianGamer** [libre-tube/LibreTube#5519]
### Steps to reproduce

1. Open Libre Tube
2. Scroll through a list of channels or videos by searching or scrolling through the feeds section.

### Expected behavior

Correct one loads instantly

### Actual behavior

Libre Tube some video loads wrong thumbnail and channel name. But finally loads correct one after 1 sec.

### LibreTube version

0.21.1

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
I believe this was fixed in https://github.com/libre-tube/LibreTube/pull/5497
