### ISSUE TITLE
Ability to share a channel group

### ISSUE THREAD

**Issue by Savasdotexe** [libre-tube/LibreTube#5522]
### Describe your suggested feature

Tried searching "share channel groups" and "share groups", but no luck so I am presuming this has not been suggested before.

Basically I'd love to be able to create a group then share it, either a file or link.

### Other details

I'm not sure how this is best done, but I am guessing to be easily compatible it can be exported to an xml format and another player or service just reads it. Or an option if possible fit it all in a link format. Not sure if that would have char limits and thus list limits, maybe a choice of methods.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Savasdotexe** [comment]
Oh, I guess sharing playlists in a similar way would be nice.

**Comment by Bnyro** [comment]
That for itself is not planned.

With the next update, you can export channel groups - That exported file can be shared and imported by others.
