### ISSUE TITLE
Auto translate subtitle 

### ISSUE THREAD

**Issue by damonelena12103** [libre-tube/LibreTube#5549]
![Screenshot_20240125-080255_ReVanced Extended](https://github.com/libre-tube/LibreTube/assets/104594420/eb0fe965-fdaf-41de-85d5-236314dc2bff)
![Screenshot_20240125-080606_ReVanced Extended](https://github.com/libre-tube/LibreTube/assets/104594420/736a5f1f-76fa-4957-a017-0b13ffe23acc)
### Describe your suggested feature

hello dear I hope you are fine I really like libretube iam using in my 2 device's please add auto translate subtitle to English like YouTube please just English I really need it thanks 🙏

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Ehab-d** [comment]
This is out of scope.

**Comment by tempppabx1** [comment]
Actually, this future is provided by youtube itself, such as the implementation of [NewPipeExtractor/pull/997](https://github.com/TeamNewPipe/NewPipeExtractor/pull/997), It would be very useful if you are willing to add it.
