### ISSUE TITLE
Ongoing Chapter name in player after time stamps

### ISSUE THREAD

**Issue by NR8124** [libre-tube/LibreTube#555]
### Describe your suggested feature

can u please implement the on going chapter names Just like official youtube app. Not only this but also i would be better if clicking on that chapter name would lead us to see all the chapters list....

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't really now how it is in the official YouTube App, could you please elaborate on how you want it to be?

**Comment by NR8124** [comment]
![IMG_20220619_003608](https://user-images.githubusercontent.com/88180887/174452909-e48a73c7-cdc5-47ec-ae01-e2a02a415bfe.jpg)


Something like this..
That text after time duration of video is the name of on going chapter of video

And when the user clicks on that it open all the list of chapters in the video

**Comment by Bnyro** [comment]
I don't think that's possible at our current state, we're planning to rewrite the player UI and I don't want to touch it before that's done.

**Comment by NR8124** [comment]
Fine. but think about it in future updates if possible
