### ISSUE TITLE
Again subtitle issue

### ISSUE THREAD

**Issue by Eliya-Manoj** [libre-tube/LibreTube#5550]
### Steps to reproduce

1. Open LibreTube
2. Play Video ( Contain subtitle ) - https://piped.video/watch?v=0UEhu4uWUAM&t=19 , https://piped.video/watch?v=oQVhwMYRgFY&t=0
3. Check subtitle
4. HTML tags

https://github.com/libre-tube/LibreTube/issues/5279 ( Same issue, Some video have no problem )
eg : https://piped.video/watch?v=0UEhu4uWUAM&t=19 ( Some parts have no problem )

![photo_2024-01-25_14-34-27](https://github.com/libre-tube/LibreTube/assets/90308888/05c7882b-f424-4c14-930b-c3b47b08af34)
![photo_2024-01-25_14-34-21](https://github.com/libre-tube/LibreTube/assets/90308888/bf83b976-06af-46ff-8fe1-03d07f658afd)

### Expected behavior

Subtitle without HTML tags and attributes

### Actual behavior

Video subtitles shows tags and attributes

### LibreTube version

Latest Debug

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Turn on rich caption rendering in the player settings.

**Comment by Eliya-Manoj** [comment]
Same issue and strange placement of subtitle.
