### ISSUE TITLE
Clicking on a space changes the search position

### ISSUE THREAD

**Issue by Pamilg8** [libre-tube/LibreTube#5551]
### Steps to reproduce

1.Tap the space above the search bar to hide the buttons. Instead of hiding the player buttons, the scrollbar changes position.It should hide the buttons

### Expected behavior

Increasing the size of the search bar and removing reactions in the space (This will make the touch easier).Like YouTube, the search bar can be between the bottom navigation and the player.Touching the space should be limited. This is annoying. There may also be an option to increase the size of the search bar in the settings.

### Actual behavior

https://github.com/libre-tube/LibreTube/assets/149590337/91908551-d206-4352-8130-2fb90744a1b0

### LibreTube version

0.21.1 Debug

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Intended behavior.
