### ISSUE TITLE
Very hard to press the search bar

### ISSUE THREAD

**Issue by Kalytis** [libre-tube/LibreTube#5554]
### Steps to reproduce

1. Load a video
2. Try to scroll with the search bar

### Expected behavior

Search bar should progress

### Actual behavior

Extremely hard to trigger the search bar, 80% of the time it will miss, leading to HUD hiding, needing to show again, which is very painful with the 0.5s delay between click and HUD behaviour.

### LibreTube version

0.21.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by M00NJ** [comment]
I think you are talking about the Seekbar. See #4130

**Comment by Kalytis** [comment]
Absolutely. Can also relate to your comment : https://github.com/libre-tube/LibreTube/issues/4130#issuecomment-1617590327

**Comment by Bnyro** [comment]
Started the next attempt to try fixing this, subjectively for me it feels way better now than it did before.

Feel free to test https://github.com/libre-tube/NightlyBuilds and report back.

**Comment by Kalytis** [comment]
Thanks! I have to say, I didn't feel the changes when they were implemented.

**Comment by Kalytis** [comment]
I also feel that the problems of taps not being detected by the app (https://github.com/libre-tube/LibreTube/issues/4130#issuecomment-1617590327) hasn't changed in a few months.

**Comment by M00NJ** [comment]
> I also feel that the problems of taps not being detected by the app ([#4130 (comment)](https://github.com/libre-tube/LibreTube/issues/4130#issuecomment-1617590327)) hasn't changed in a few months.

That's tracked at #4161

**Comment by Bnyro** [comment]
> I also feel that the problems of taps not being detected by the app ([#4130 (comment)](https://github.com/libre-tube/LibreTube/issues/4130#issuecomment-1617590327)) hasn't changed in a few months.
>
Well, it's an open source project, nobody contributing here is obligated to work on anything they don't want too...

**Comment by Kalytis** [comment]
Sorry, I didn't mean for it to come out wrong, I just wanted to follow up on the fact that the problem was addressed a first time, and maybe it could be improved again. It was simple feedback, no disrespect intended on volunteer work ✌️
