### ISSUE TITLE
Two sections in Channel Fragment 

### ISSUE THREAD

**Issue by NR8124** [libre-tube/LibreTube#556]
### Describe your suggested feature

It would be better if two different sections will get implemented in each channel fragment. 
Which includes,
1. videos list
2. playlists by the channel/creator
 
it will lead to find more about the channel's best things...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The API doesn't support channel playlists so we can't add it.

**Comment by NR8124** [comment]
there is an alternative Youtube frontend ... https://dev.viewtube.io/ 
which uses Invidious api

see if it can be implemented or not
otherwise it will be fine...

**Comment by Bnyro** [comment]
I'm sorry but we won't use any other API than the Piped API, the project is meant to be an android frontend for Piped. They will probably add it to their API one day, we can rethink about it if/when that's the case.

**Comment by NR8124** [comment]
@Bnyro  You closed this issue and marked it as completed ?
 is it really completed ?

**Comment by Bnyro** [comment]
Nope, I combined it with your other issue, my bad

**Comment by Bnyro** [comment]
because both these things will probably arrive the same time in the API (if they do)

**Comment by Bnyro** [comment]
so it's easier for us to keep an overview
