### ISSUE TITLE
The video title appears, when you unlock the player

### ISSUE THREAD

**Issue by Pamilg8** [libre-tube/LibreTube#5563]
### Steps to reproduce

1.Lock and then unlock the player.(Vertical)
2.The video title is visible. It should not be visible because it is an unnecessary component

### Expected behavior

Do not show the title

### Actual behavior

https://github.com/libre-tube/LibreTube/assets/149590337/2d31b952-d7f9-4659-afe3-9b48b0b06431

### LibreTube version

0.21.1 Debug

### Android version

Android 13

### Other details
#5552
I mentioned in the previous issue, it has not been resolved. But the darkening problem was solved

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Intended behavior.
