### ISSUE TITLE
String is on line

### ISSUE THREAD

**Issue by Pamilg8** [libre-tube/LibreTube#5564]
### Describe your suggested feature

![Screenshot_20240126-202517_LibreTube Debug](https://github.com/libre-tube/LibreTube/assets/149590337/6e10ee34-b928-4475-83f5-a6005247be12)

### Other details

It is better known in long translations

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's an upstream issue in the Material Design library, please move over there.
