### ISSUE TITLE
Sandboxed app downloads

### ISSUE THREAD

**Issue by GilesMunn** [libre-tube/LibreTube#557]
### Describe your suggested feature

It'd be good if we could have a user preference to store downloaded videos within the apps own data folder and display downloaded titles (perhaps in the Library tab?)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Already thought about it too, but we have huge issues to get normal downloads done at the moment. It fails most of the times, it only works rarely for small file sizes. I already spent hours investigating for nothing :(

**Comment by GilesMunn** [comment]
Only if you didn't learn anything :) Is it something we could implement somebody else's solution for? Newpipe or YT-DL/YT-DLP code or something alike?

**Comment by Bnyro** [comment]
I learned that the downloads don't work lol. I already thought about it but yt-dlp wouldn't work in countries where YouTube is geoblocked and I didn't want to copy NewPipe's solution

**Comment by Bnyro** [comment]
Feel free to learn from the download service, I would appreciate it :)

**Comment by Bnyro** [comment]
at least I gave up understanding it

**Comment by lu4p** [comment]
@Bnyro Have you seen this?

https://github.com/libre-tube/LibreTube/discussions/464#discussioncomment-3284753

**Comment by Bnyro** [comment]
I won't be working on something like that. I appreciate if anyone wants to work on it and makes a pr, however, it won't be me.
