### ISSUE TITLE
Cant see the release date of the videos

### ISSUE THREAD

**Issue by Rockbard** [libre-tube/LibreTube#5570]
### Steps to reproduce

![2](https://github.com/libre-tube/LibreTube/assets/39404436/4908852a-1087-4278-b72c-26c0730df709)

Just a standard use, with no significant settings changes, but my Android system font size is set to be slightly bigger, which could be the reason for the issue. 

### Expected behavior

I would like to see the release dates of the videos to understand which videos are newer and which of them are old.

### Actual behavior

I can't see the release dates of the videos in the video search tab

### LibreTube version

0.21.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not a bug - the app is mainly targeting the default font size. If you increase the font size, it's expected that some parts won't be visible. The most important information is still visible and you can see the date when starting video playback, so I don't see an issue here.

**Comment by Rockbard** [comment]
Yeah, moreover the real problem apparently was the language. I have set it to English and now it's okay. The words in ukrainian translation are too long, that is the issue.
