### ISSUE TITLE
App crashes when reopening the app after closing(or minimizing) it in fullscreen mode

### ISSUE THREAD

**Issue by Ranger-NF** [libre-tube/LibreTube#5584]
### Steps to reproduce

1. Play any video full screen (Landscape mode)
2. Pause the video
3. Exit the app to home screen (I do it by pressing the home button on my old phone)
4. Try reopening the app and play the video again

### Expected behavior

The playback of the video and audio should continue as usual on pressing the play/resume button.

### Actual behavior

The video now is shown as portrait mode (Check the image below to get what I said):
![Screenshot_20240201-103053_Gallery](https://github.com/libre-tube/LibreTube/assets/78952725/a505b608-3add-47a2-9780-1ce173aed9a6)

The video playback stops, audio continues where it was left off (NB: I had not pressed the play button)

Upon pressing the 'exit fullscreen' button, the app crashes (ie, the system shows: Libretube stopped working).

Log shown on reopening the app:
```
java.lang.NullPointerException
	at com.github.libretube.ui.fragments.PlayerFragment$$ExternalSyntheticLambda1.onClick(SourceFile:236)
	at android.view.View.performClick(View.java:6897)
	at android.view.View$PerformClick.run(View.java:26103)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6942)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
    
```

### LibreTube version

0.21.1

### Android version

Android 8.0.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by matkoniecz** [comment]
> The video now is shown as portrait mode (Check the image below to get what I said):

it links to an image, not video

**Comment by Ranger-NF** [comment]
Yeah, I guess so. As it doesn't play the video anymore, just the audio.

**Comment by Zoo-M0** [comment]
I'm starting to look into it, maybe I could work a fix.

**Comment by larix45** [comment]
Hi I noticed the same behavior. It only happens when you do it with auto-rotate disabled, and when you fullscreen using swipe gesture (not with a fullscreen button). Probably it relates to how android handles landscape/portrait prefernces on the player activity.

**Comment by Ranger-NF** [comment]
This might sound weird but I have not experienced the issue for the last 2 weeks now. The app is still on v0.21.1

I don't remember if I had changed any settings or not... I might close the issue for now. If anyone else have a problem just like this or if I encounter it again, I open it again with more verbose reproducing steps.
