### ISSUE TITLE
Audioplayer button

### ISSUE THREAD

**Issue by ninosandzak** [libre-tube/LibreTube#5597]
### Describe your suggested feature

option to switch to audio player while watching a video (as in previous versions)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's still there, on small screens you need to scroll the options horizontally to see it.
