### ISSUE TITLE
watch history with date, time and a search option

### ISSUE THREAD

**Issue by ninosandzak** [libre-tube/LibreTube#5598]
### Describe your suggested feature

Watch History with date and time so you know when you watched a video or listened to an audio. So that every video has a date and time.
A search option so you can search the videos you have already watched

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's out of scope for the app.
