### ISSUE TITLE
search filter and sort results (upload date etc.)

### ISSUE THREAD

**Issue by ninosandzak** [libre-tube/LibreTube#5599]
### Describe your suggested feature

Filter search by time, for example: this week, this month or this year (like on YouTube)
A sorting function by number of views, most viewed or least viewed etc.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not API-side supported.
