### ISSUE TITLE
[FEATURE] Android TV

### ISSUE THREAD

**Issue by IceDBorn** [libre-tube/LibreTube#56]
It would be nice to have an android TV version that  you can cast videos to from your android device.

**Comment by rimthekid** [comment]
I would love this too Don't know when I can start building it tho but android tv version is already so much easier to build than the whole app itself

**Comment by billyea** [comment]
Should note that there are apps for Android TV that you can base off of, e.g. SmartTubeNext is very similar

**Comment by vebaev** [comment]
> Should note that there are apps for Android TV that you can base off of, e.g. SmartTubeNext is very similar

I second for Android TV, the Smart YoutubeNext is the only option till now and the interface is a bit ugly :) comparing yo the original app. So any new app in this direction will be a big plus!

**Comment by IceDBorn** [comment]
STN is excellent for me but I can't stand using my google account to watch videos from my subscriptions.

**Comment by mmccn** [comment]
Boosting this!

**Comment by Bnyro** [comment]
> Boosting this!

Adding it instead of boosting it would be bettter.

**Comment by mmccn** [comment]
> > Boosting this!
> 
> Adding it instead of boosting it would be bettter :D

@Bnyro That isn't possible for me currently which is why I boosted it.

**Comment by mmccn** [comment]
> I would have tried it if I had an Android TV, but I don't have one so it's hard

@Bnyro Could you emulate it? I'm sure there's a way

**Comment by vebaev** [comment]
I can test, is there ready app for ATV?

**Comment by archroid** [comment]
We will support Android TV in the future when we had more experience and time. We appreciate any one who can do this and opens a pull request. Thanks for your suggestions <3

**Comment by alexanderadam** [comment]
But can't you leave the issue open then? :thinking: 
This way somebody might see the issue and give it a go.

> he does not own an Android TV

Google has [some decent documentation on how](https://developer.android.com/training/tv) to make apps compatible to Android TV and Nvidia also [provides a bit](https://developer.nvidia.com/android-tv-deployment-checklist). Nvidia also [provides images](https://developer.nvidia.com/gameworksdownload) for their Android TV devices.

**Comment by Vexz00** [comment]
I'd really love a Android TV version of LibreTube. I think there isn't currently any app for Android TVs that uses Piped. Because of this I have to manage my subscriptions extra on my TV which is annoying.
