### ISSUE TITLE
New videos don't appear on the subscription page

### ISSUE THREAD

**Issue by kubo6472** [libre-tube/LibreTube#5600]
### Steps to reproduce

1. Open the app
2. Refresh the feed
3. Check individual channels
4. Observe new videos on channel pages
5. Go back to subscriptions page
6. Refresh again
7. See the videos for the last x days you haven't checked any of those channels.

### Expected behavior

Refreshing the subscription page pulls all new videos without any issue.

### Actual behavior

Until you visit individual channel pages, you won't find any new videos on the subscription page.

### LibreTube version

0.21.1 debug (commit 23256097947b80bed0873e99576866fe4cf3a6e9)

### Android version

Android 14

### Other details

[Screen recording](https://i.imgur.com/fBoCEFo.mp4)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/TeamPiped/Piped/issues/1130
