### ISSUE TITLE
The video does not play in automatic quality. (But the audio format loaded))

### ISSUE THREAD

**Issue by Pamilg8** [libre-tube/LibreTube#5614]
### Steps to reproduce

1. Watch the video.
2. Buffering is delayed
3. Sometimes the player gets locked quickly. Sometimes a little later
4. The audio loads but not the video
5. Set the quality manually to 480p, the video plays immediately 

### Expected behavior

Why am I opening the issue?

Because videos with problems are working without problems in Piped. This problem occurs on my fast Wi-Fi for LibreTube. Not on weak Wi-Fi. I don't know why fast Wi-fi is causing problems on LibreTube. Doesn't seem like a server problem

### Actual behavior

Some videos did not load in automatically quality

### LibreTube version

0.21.1 Debug

### Android version

Android 14

### Other details

https://github.com/libre-tube/LibreTube/assets/149590337/10bf67da-666d-4ec0-80ae-ca4dc1469f6e

https://github.com/libre-tube/LibreTube/assets/149590337/00a8fe1f-0f62-46b4-939f-553015d55478

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Serroda** [comment]
Same problem here, It only happens when the video is recently published. If a few days pass, you can watch the video
<details><summary>proof</summary>

https://github.com/libre-tube/LibreTube/assets/35766979/44a3c66a-cc19-4c60-9170-7dc18c2c7812

</details>

**Comment by Pamilg8** [comment]
The video I showed was published a long time ago.

**Comment by Ehab-d** [comment]
It also happends with me alot of times. I'm not a dev to know what is it but I have to change the quality to make the video work.

**Comment by Bnyro** [comment]
Closing in favor of https://github.com/libre-tube/LibreTube/issues/5855
