### ISSUE TITLE
Remember the video quality changes.

### ISSUE THREAD

**Issue by Pamilg8** [libre-tube/LibreTube#5617]
### Describe your suggested feature

Reminder function of video quality changes. If the previous video was played in 720p, it forces the next video to be. On/off option in settings 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's out of scope, we already have enough preferences.
