### ISSUE TITLE
Swipe down on mini player to close it.

### ISSUE THREAD

**Issue by NeeRaj-2401** [libre-tube/LibreTube#562]
### Describe your suggested feature

![image](https://user-images.githubusercontent.com/88180887/174472316-e7502bef-5a80-4b89-bdcb-28a46e68cae6.png)

we already have swipe up action on this mini player window.
just want an additional feature i.e. SWIPE DOWN on this mini player window to close the player/video

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We already have #2020 open for that :)

**Comment by Bnyro** [comment]
> @Bnyro I think, it's more appropriate to choose `Close as Completed` for duplicate issues. Wdyt?
>
Yes, that's a good idea, indeed! Otherwise it'll be really hard to overview in the end.
