### ISSUE TITLE
LibreTube compatibility with NewPipe backups

### ISSUE THREAD

**Issue by bunget** [libre-tube/LibreTube#5628]
### Describe your suggested feature

You coulda woulda shoulda make LibreTube compatible with the NewPipe app's database backups.

### Other details

LibreTube is basically a descendant of NewPipe, and already has a backup feature very similar to the NewPipe client app's,so it makes all the sense in the world to make LibreTube compatible with the backups that NewPipe generates.

You could also reach out to NewPipe's devs to make one unified backup format for your apps,but those guys are very busy so I don't reccomend it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's out of scope.

We already support NewPipe's Json subscription format and there are no plans for supporting full NewPipe database imports - databases are just not made for being transferred between apps.
