### ISSUE TITLE
APP randomly closes and copies text

### ISSUE THREAD

**Issue by kzhe2059** [libre-tube/LibreTube#5629]
### Steps to reproduce

1. Watch a video in fullscreen

### Expected behavior

Nothing happens and I watch my video.

### Actual behavior

The app closes and text is... Sort of copied to keyboard? I see the pop up of a copy but nothing is copied

### LibreTube version

0.21.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please share a screen recording or a crash log, the provided information isn't sufficient to either understand or attempt reproducing and fixing the issue.
