### ISSUE TITLE
DeArrow only the title, leave the native thumbnail

### ISSUE THREAD

**Issue by WildGenius** [libre-tube/LibreTube#5630]
### Describe your suggested feature

The desktop DeArrow version allows to choose between replacing thumbnails, titles, or both. I'd like to replace only the titles in LibreTube.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I currently don't see the necessity of this, hence concerting to a discussion for now.
