### ISSUE TITLE
Mouseover cursor movement doesn't reveal video overlay controls

### ISSUE THREAD

**Issue by slook** [libre-tube/LibreTube#5639]
### Steps to reproduce

1. Connect a hardware mouse via USB or BT.
2. Play a video.
3. Move the mouse cursor over the video.

### Expected behavior

The overlay controls should become visible whenever the mouse cursor is moved over the video, either while Playing or Paused.

If the video is Paused, then the controls might as well remain visible indefinitely, or at least the Play button should stay visible.

Only one single mouse click should be needed to activate a button widget when using a hardware pointing cursor device.

### Actual behavior

- The overlay controls (Pause, Seek, Options, etc) don't appear until a mouse button is clicked.
- The overlay controls quickly disappear in 500ms, before there is a chance to aim and click on the desired function.

### LibreTube version

0.21.1

### Android version

8.1.0 (AOSP)

### Other details

Display output is a non-touch television screen connected via HDMI.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
1. The app only supports tablets and smartphones. External input devices like a mouse are not supported however.
2. We have gestures for playing/pausing a video, I can't tell if this works for you though. Double clixking in the center of the screen resumes/pauses the video.

**Comment by slook** [comment]
Thank you for your consideration, that is fair enough. Albeit a shame that mouse is not going to be supported, since this app otherwise seems to be well suited to running on televisions that don't have touchscreen input.

It does work for me as I am able to around the issue by clicking it twice, as you suggested, or by using the recently added keyboard support, which you have recently implemented in #5641.

This feature request for improved mouse pointer support was made in consideration of users who may have special accessibility requirements, see links:

https://www.w3.org/WAI/WCAG22/Techniques/general/G216.html
https://www.w3.org/WAI/WCAG22/Techniques/failures/F105.html
