### ISSUE TITLE
Full screen switches to portrait only when using gesture 

### ISSUE THREAD

**Issue by t-e-s-tweb** [libre-tube/LibreTube#5660]
### Steps to reproduce

1. set device autorotation to off
2. enable full screen gesture
3. play a video and use swipe up gesture to goto full screen. 
4. video goes into full screen landscape mode
5. after 2 seconds it goes to portrait mode. 

### Expected behavior

video should stay in landscape mode 

### Actual behavior

video switches to portrait full screen after a few seconds of landscape 

### LibreTube version

0.21 latest debug 

### Android version

android 12

### Other details

If the full screen video rotation is set to autorotate then it goes into portrait and on rotation it goes into landscape however if the device is already in landscape and video is sent into full screen then it goes into full screen but still switches to portrait. 

similarly setting it to landscape and then rotating also puts into landscape but switches to portrait after a few seconds. 

![IMG_20240225_224338](https://github.com/libre-tube/LibreTube/assets/16269572/f84209bf-60cd-40f7-8001-8bf467de9cad)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by jksekai** [comment]
having this same issue, regardless whether my system has auto rotation on or off, swiping to full screen never works
