### ISSUE TITLE
Download Exception

### ISSUE THREAD

**Issue by olsonperrensen** [libre-tube/LibreTube#5661]
### Steps to reproduce

1. Download media (either video && || audio)
2. Encounter error
3. Network error supposedly prevents media from being fully downloaded even though it completed all of the MBs or a tiny kbit is only left (bear in mind the internet connection is always working and stable) 

### Expected behavior

Download should complete as usual since no network issues exist on the wireless connection

### Actual behavior

Download: Exception in CroneUrlRequest: net::ERR_QUIC_P / ERR_HTTP2_

### LibreTube version

0.21.1

### Android version

14

### Other details

Clean installed.... Same issue. 

Ran additionally a nightly build. Same issue. 

Changed instances as well. Same issue. Official instances, those with low ping, those with most retention of uptime.... nothing fixed it. 

Used mobile data, various different WiFi... Seems more like an app issue that randomly started falling into this exception handling since the last build upgrade back in January. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I think we just suppressed this error before, it should be safe to ignore usually. Did you try if the downloaded media is playable?

**Comment by olsonperrensen** [comment]
Sometimes yes sometimes it throws a very large number of hours and simply doesn't play. 

I additionally get 2 toast messages saying network error and there seems to be a problem with this instance (looping though loading my library) even though everything works on the search bar

**Comment by gustav-langer** [comment]
I'm not sure if this is related, but sometimes when I get this error, the download has finished but there is still a notification that something is downloading.
That notification also can't be closed except through restarting, which makes it very annoying.
