### ISSUE TITLE
No loop button 

### ISSUE THREAD

**Issue by FaqatZubair1** [libre-tube/LibreTube#5675]
### Describe your suggested feature

If I'm listening to a song, there is no loop button, so that the same video or song will play in loop, also when I remotely press the replay buttom from Bluetooth device, it gets stuck.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Open the playing queue: There's a repeat button at the bottom left.
