### ISSUE TITLE
 play button produces no result after the video ends

### ISSUE THREAD

**Issue by FaqatZubair1** [libre-tube/LibreTube#5676]
### Steps to reproduce

Play any video (in my case played in background ) after the video is finished, if I want to play it again, clicking on the play button results in no outcome.

### Expected behavior

The video should play from the beginning.

### Actual behavior

The video doesn't play at all, user has to drag the progress bar manually to the start.

### LibreTube version

0.21.1

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
This has already been fixed in the debug builds.

**Comment by FaqatZubair1** [comment]
Where can I download the debug build?
