### ISSUE TITLE
Alternative player 00:00

### ISSUE THREAD

**Issue by olsonperrensen** [libre-tube/LibreTube#5679]
### Steps to reproduce

1. Go to a downloaded video
2. See weird alt player
3. Press play 
4. get stuck at 00:00 -00:00

### Expected behavior

The video should play

### Actual behavior

![Screenshot_20240229-171052](https://github.com/libre-tube/LibreTube/assets/80784184/24d26af3-a206-4a1b-a37a-947c80a27e52)
![Screenshot_20240229-171049](https://github.com/libre-tube/LibreTube/assets/80784184/4bf41f5e-37ba-4318-85e9-7306465eecda)

### LibreTube version

0.21.1

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
This only seems to be the case when the download didn't finish properly - please just make sure the download has finished without interruptions.
