### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by damonelena12103** [libre-tube/LibreTube#5682]
### Steps to reproduce

Hello dear I hope you are fine dear libretube not playing videos these Days not working please fix it and also add auto translation subtitles to English need new update thanks

### Expected behavior

Hello dear I hope you are fine dear libretube not playing videos these Days not working please fix it and also add auto translation subtitles to English need new update thanks

### Actual behavior

Hello dear I hope you are fine dear libretube not playing videos these Days not working please fix it and also add auto translation subtitles to English need new update thanks

### LibreTube version

Latest

### Android version

Android 13

### Other details

Hello dear I hope you are fine dear libretube not playing videos these Days not working please fix it and also add auto translation subtitles to English need new update thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Hello dear I hope you are fine dear libretube not playing videos these Days not working please fix it and also add auto translation subtitles to English need new update thanks
