### ISSUE TITLE
App closes upon clicking some channel links

### ISSUE THREAD

**Issue by MatsG23** [libre-tube/LibreTube#5683]
### Steps to reproduce

1. Open the following video with LibreTube: https://piped.lunar.icu/watch?v=2jRiGOs7tsc
2. Click the link to the YouTube channel @RoomieOfficial in the video description

### Expected behavior

The app should show the page of the clicked channel and not crash.

### Actual behavior

The app closes (it feels like a crash). However, after reopening the app, the channel page is shown. 

### LibreTube version

0.21.1

### Android version

Android 14

### Other details

I could not reproduce this bug with every channel link (in descriptions/comments).
I am running GrapheneOS.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Like this? https://github.com/libre-tube/LibreTube/assets/50032603/88d1743f-4081-4a7e-9421-1dbc286e50af

**Comment by akano12** [comment]
Like this?

https://github.com/libre-tube/LibreTube/assets/50032603/709966ab-08f9-4f8d-8b0b-28e06e07ba1c

**Comment by akano12** [comment]
I attached 2 different recording above.
The first one happens when i opened the link and already had watched part of the video before. 
Second one happens when watching the video for first time.

**Comment by akano12** [comment]
Can you share a video recording?

**Comment by akano12** [comment]
Ehh, try with debug and report back.

**Comment by Bnyro** [comment]
That's probably a similar issue to https://github.com/libre-tube/LibreTube/issues/2022 I think :thinking:
