### ISSUE TITLE
LibreTube is down

### ISSUE THREAD

**Issue by VitoItalianGamer** [libre-tube/LibreTube#5686]
### Steps to reproduce

Opened the app as usual
App not connecting to internet

### Expected behavior

LibreTube loads as before

### Actual behavior

It doesn't connect

### LibreTube version

0.21.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Settings -> Instance -> Change instance.
