### ISSUE TITLE
Video goes back to 00:00 if phone plugged into charging

### ISSUE THREAD

**Issue by olsonperrensen** [libre-tube/LibreTube#5699]
### Steps to reproduce

1. Watch a video
2.  Leave it playing for more than 1 sec
3. Plug phone (charging)
4. Video goes back to 00:00

### Expected behavior

Continued playback

### Actual behavior

Resetting back to begin of video.

### LibreTube version

0.21.1

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please share a screen recording.

@akano12 could you please test this too? :eyes:

**Comment by akano12** [comment]
> Please share a screen recording.
> 
> @akano12 could you please test this too? :eyes:

Can't reproduce (sadly), it'd be funny if i could

**Comment by Bnyro** [comment]
Yeah, indeed that issue doesn't at all seem to be related to LibreTube in any way, but I still want to see if we can get a screen recording of this 😂
