### ISSUE TITLE
[FEATURE] Add Socks5 proxy

### ISSUE THREAD

**Issue by xmha97** [libre-tube/LibreTube#57]
Please add Socks5 proxy option

**Comment by rimthekid** [comment]
I could add it in the settings but what it's used for? If the instance is banned in your country just change the instance?

**Comment by Roki100** [comment]
> Maybe an Orbot mode can be added to add support for .onion instances 🤔
> 
> The official instance has an onionsite at: http://piped2bbch4xslbl2ckr6k62q56kon56ffowxaqzy42ai22a4sash3ad.onion
> 
> Which also uses an onionsite for the API and proxy too

i support that idea and looking forward for this 👀

**Comment by lilcheti** [comment]
We are not connected to youtube servers directly! try the instances and see if it works!

**Comment by xmha97** [comment]
> We are not connected to youtube servers directly! try the instances and see if it works!

Wow, this works well in my country. 😍
Thankful
