### ISSUE TITLE
Add offline library storage support

### ISSUE THREAD

**Issue by Etim-Orb** [libre-tube/LibreTube#570]
### Describe your suggested feature

Some users may prefer a more private way of handling subscriptions and library. An offline storage of these will increase the privacy and simplicity of the app. We should be able to export and import this storage included with the settings. Also a periodic autosave would be useful as well.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We devs already talked about it, we won't add sth like that.

**Comment by Bnyro** [comment]
If you are really concerned about privacy, you can host your own Piped instance: https://piped-docs.kavin.rocks/docs/self-hosting/

**Comment by Etim-Orb** [comment]
@Bnyro Can I ask specifically why? This is probably the only thing preventing me from switching from NewPipe.

**Comment by Etim-Orb** [comment]
Wait @Bnyro when registering, I register to the instance server where the details are stored?

**Comment by Bnyro** [comment]
You're right, that's why it's probably the best solution to host your own Piped instance. We can't guarantee that the instances stay online. The reasons why we won't add offline subs etc is that it is too late at the current state to change the behavior of the app like that. That decision would probably have to be taken earlier if we wanted to.

**Comment by Etim-Orb** [comment]
I still stand by my suggestion btw.

**Comment by Bnyro** [comment]
I still wait for your pull request btw.

**Comment by Etim-Orb** [comment]
I was just saying btw.

**Comment by rozari0** [comment]
> Still standing by. I mean how hard could it be to implement?

I think bnyro is still waiting for your PR.
