### ISSUE TITLE
Going back from a video shows search interface instead of previous interface

### ISSUE THREAD

**Issue by KasraIDK** [libre-tube/LibreTube#5701]
### Steps to reproduce

1. Search a term
2. Open a channel or playlist through the search results
3. Open a video
4. Press back button

### Expected behavior

Going back should show the previous interface

### Actual behavior

https://github.com/libre-tube/LibreTube/assets/41045880/378992d3-ad03-47e6-8521-cc0611f19b98

### LibreTube version

0.21.1

### Android version

Android 14

### Other details

I've been seeing this bug for as long as I can remember but never realized what the exact steps to reproduce it were. Finally figured it out.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Reported in https://github.com/libre-tube/LibreTube/issues/5115 and fixed in https://github.com/libre-tube/LibreTube/pull/5486
Either use debug builds or wait for next release

**Comment by KasraIDK** [comment]
#5486 only fixes for channels. See below with latest debug build.


https://github.com/libre-tube/LibreTube/assets/41045880/1e491acd-5cc4-4a02-a0a9-20967c7f713b

**Comment by KasraIDK** [comment]
Can't reopen
Do I make a new issue?

**Comment by akano12** [comment]
> Can't reopen
> Do I make a new issue?

Sure
