### ISSUE TITLE
Missing Feedback for API Errors (Shaka Error 100X)

### ISSUE THREAD

**Issue by lewxdev** [libre-tube/LibreTube#5703]
### Steps to reproduce

1. Navigate to any video mentioned in this thread in the app: https://github.com/TeamPiped/Piped/issues/2915 (e.g. [this](https://piped.video/watch?v=JGPB_IvmAJI), [this](https://piped.video/watch?v=v_Q6jUo1V0g), [this](https://piped.video/watch?v=xzXDSWz3Nbw), or [this](https://piped.video/watch?v=vBtREyvopgk))
2. Try to play the video

### Expected behavior

Some feedback (toast, alert, etc.) should be shown to the user explaining why the video cannot be played

### Actual behavior

The error `"Failed with error code 100X, see logs for more info"` or any similar error is not shown to the user

### LibreTube version

0.21.1

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Tried all the links you provided, all played without problems.

**Comment by lewxdev** [comment]
> Tried all the links you provided, all played without problems.

@akano12 Can you kindly send your app settings? Perhaps there's a discrepancy between our configurations. After re-testing, only the first video plays for me (on the web as well). But the others fail.

[libretube-backup-2024-03-06-14_15_25.json](https://github.com/libre-tube/LibreTube/files/14514479/libretube-backup-2024-03-06-14_15_25.json)

**Comment by akano12** [comment]
> > Tried all the links you provided, all played without problems.
> 
> @akano12 Can you kindly send your app settings? Perhaps there's a discrepancy between our configurations. After re-testing, only the first video plays for me (on the web as well). But the others fail.
> 
> EDIT: I've attached my preferences, perhaps you can load these and see if you get the same results?
> 
> [libretube-backup-2024-03-06-14_15_25.json](https://github.com/libre-tube/LibreTube/files/14514479/libretube-backup-2024-03-06-14_15_25.json)
> 
> 
> 

I don't have anything specific done in the app settings, just tried with adminforge instance and other instances, videos played fine

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/assets/50032603/b5b9ab92-4309-48d9-a9d5-751e30b9ac7b

**Comment by Bnyro** [comment]
The ExoPlayer oftenly throws some unimportant errors which would also be shown then, no plans for changing the current behavior.
