### ISSUE TITLE
Remember latest selected channel group during app restarts

### ISSUE THREAD

**Issue by lewxdev** [libre-tube/LibreTube#5705]
### Describe your suggested feature

Just as the feed filter (for `"All"`, `"Videos"`, `"Shorts"`, and `"Livestreams"`) persists across app launches, this feature would add an option in settings to also persist either (1) the last selected group (to pick back up where you left off) or (2) a specific group.

Since this may not be desired behavior for everyone, I imagine something like the following in the **Settings** → **Appearance** → **Layout** submenu

**Persist channel group selection**
Keep the selected channel group between sessions
1. Off (default)
2. Last selected
3. Group ...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Adding a preference for such small behaviors is an overkill due to the fact that the current settings UI is already exploding due to too many features, if we add more preferences for very small behaviors that will be even less convenient for new users.

**Comment by Bnyro** [comment]
Since your suggestion is almost the same as point 12 at https://github.com/libre-tube/LibreTube/issues/3558, I'll be closing this issue for now. Feel free to leave your suggestion there.
