### ISSUE TITLE
Youtube shorts

### ISSUE THREAD

**Issue by Adithyan007hack** [libre-tube/LibreTube#571]
### Describe your suggested feature

It would be great if there was a  sperate section for YouTube shorts, then you can swipe up to see the next shorts
What you guys think about it?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#78

**Comment by Adithyan007hack** [comment]
Is this feature already established in app?

**Comment by Bnyro** [comment]
Dupe of #78 ...
