### ISSUE TITLE
Incompatible version

### ISSUE THREAD

**Issue by Adithyan007hack** [libre-tube/LibreTube#572]
### Steps to reproduce

I was not getting the latest version. I was so sad then i gone to droidfy settings and checked the "incompatible version" now i can see the new version but it says incompatible, so how can i install it??
![Screenshot_2022-06-20-14-48-35-279_com looker droidify](https://user-images.githubusercontent.com/87800041/174570452-5eb61ab2-507c-4ef0-967b-9a5a55fbc2e2.jpg)

### Expected behavior

App should update normally 

### Actual behavior

Incompatible version 

### LibreTube version

0.3.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
just install it from Github releases...

**Comment by Adithyan007hack** [comment]
Is there any other way?

**Comment by Bnyro** [comment]
yes, buy a new device

**Comment by Bnyro** [comment]
he changed the build arch I guess. It's not libretube related, please ask there

**Comment by Adithyan007hack** [comment]
Can i install github version over the version from izzyondroid
