### ISSUE TITLE
Syncing watched video time with piped instance

### ISSUE THREAD

**Issue by Grooty12** [libre-tube/LibreTube#5720]
### Describe your suggested feature

For example, if I am viewing video *x* on my phone with Libre Tube, and, halfway through the video, I decide to watch in on my pc on the same Piped-instance with the same account, would it be possible for Libre Tube and Piped to share the watched video time, so I could just pick off where I left?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Piped does not support that.
