### ISSUE TITLE
Subscriptions list in chronological order of registrations.

### ISSUE THREAD

**Issue by GuiSousa135** [libre-tube/LibreTube#5722]
### Describe your suggested feature

It would be very useful to have the option to view the list of subscribed channels in the order of subscription date (the most recent first, and channels longest subscribed later), instead of alphabetical order, and the user can change this choice in the settings.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Umm, but why?

**Comment by Bnyro** [comment]
I have to look it up again, but I'm pretty sure Piped's API returns the subscriptions in alphabetical order only without any way to change the sort order. We don't store any information of the subscription date, so the only way would be to sort by database row creation date at the Piped backend side.

**Comment by Bnyro** [comment]
I've checked the backend code, as I said, the subscriptions are only returned in alphabetical order without any information about the time of subscription. Hence, please open an issue at Piped first.
