### ISSUE TITLE
Settings activity quickly switches to landscape mode before returning to portrait mode.

### ISSUE THREAD

**Issue by imwints** [libre-tube/LibreTube#5723]
### Steps to reproduce

* Enable auto screen rotation on the device
* Open the app
* Set screen orientation to portrait in the app's settings
* Turn the device to the side
* Open settings

### Expected behavior

The settings activity should be in portrait mode from the beginning.

### Actual behavior

The settings page turns to landscape mode before snapping into portrait mode.

https://github.com/libre-tube/LibreTube/assets/76256484/2e3a6d1f-7b3e-425a-b26d-7add87d4cf78

### LibreTube version

0.21.1 and Nightly

### Android version

13, 14

### Other details

~I have searched for places where the `SettingsActivity` sets it's preferred screen rotation but haven't found any.~

~Since it doesn't support landscape mode at the moment I'd lock the screen orientation in the Manifest for now.~

I just realized that I set the app's preferred orientation to portrait mode. I guess it's still a bug.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Unfortunately there's no other way to accomplish the settings that users can choose between landscape, portrait and auto rotation.

We have to hard code the orientation new activities get opened in, which currently is auto rotation for all activities. Once the activity has been created, we can programmatically change the orientation that's used by the activity.

Unfortunately there doesn't seem to be any way to changing that hard coded, default orientation before opening the new activity - at least I've not found any way to accomplish this in Android's documentation.

**Comment by Bnyro** [comment]
Or maybe this here can help us: https://ao.chatoyer.de/questions/10298417/set-screen-orientation-before-activity-become-visible. I'll test if this has any impact in the next days.

**Comment by imwints** [comment]
This actually solves the issue and still allows screen rotation with auto-rotation enabled.
