### ISSUE TITLE
[FEATURES REQUEST] Add Discover Tab

### ISSUE THREAD

**Issue by 1YuvrajS** [libre-tube/LibreTube#5734]
### Describe your suggested feature

Discover Tab are consist of Music, Film, Sports etc . Users wanted to explore different categories as their likes in Discover Tab. Mine mostly explore Music in Discover Tab that where latest Uploaded or Most Played etc.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's what the home tab was added for.
