### ISSUE TITLE
Failed to fetch list of available instances

### ISSUE THREAD

**Issue by dhuschde** [libre-tube/LibreTube#5736]
# temporary fix
> Everything works fine if you set a custom instance, the list of instances is still available at https://github.com/TeamPiped/Piped/wiki/Instances.
-- https://github.com/libre-tube/LibreTube/issues/5736#issuecomment-1995621673

### Steps to reproduce

I watched a Video and it stopped working.

### Expected behavior

It works

### Actual behavior

The App can't load anything, even the Instance List doesn't load. (Some instances are still shown, but i get an error through a toast message.

### LibreTube version

0.21.1

### Android version

Android 13 / e/OS 1.20

### Other details

I am online. I can open and use the Piped instances on my Browser. I also tried resetting the app, using another instance, reinstalling the app and rebooting the phone and using another WiFi and mobile data.

Everything works in the same network with my Tablet. (Edit: it stopped working after connecting my Tablet to my Phones Hotspot. Changing back to my WiFi and rebooting doesn't solve it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by VitoItalianGamer** [comment]
I have the same issue too. Any fixes?

**Comment by Bnyro** [comment]
Everything works fine if you set a custom instance, the list of instances is still available at https://github.com/TeamPiped/Piped/wiki/Instances.

The documentation site is not related to this.

**Comment by Bnyro** [comment]
I will probably start hosting a fallback mirror somewhere at a `libretube.dev` subdomain to avoid such issues in the future, will just have to set it up some time.
