### ISSUE TITLE
App stops working if instance list is offline.

### ISSUE THREAD

**Issue by dhuschde** [libre-tube/LibreTube#5737]
### Steps to reproduce

If https://piped-instances.kavin.rocks and https://instances.tokhmi.xyz (and mirror on libretube.dev in the future) are offline
* Open App
* let the App check the instance list (settings>instance)

Do not use a custom instance

### Expected behavior

The App should work even if the instance was previously selected from the list while the list is offline. The App still knows the instance and could still use it. All Instance API's could go offline at the same time ([today for example](https://github.com/libre-tube/LibreTube/issues/5736)) but the instances are still up and running,

### Actual behavior

The whole app can't connect to anything. Nothing works.
You can still choose an instance from the list, but that won't help and there's an error toast.
Using a custom Instance does still work and fix the problem. You have to use a custom instance on both the general and the auth instance.

### LibreTube version

0.21.1

### Android version

Android 13

### Other details

If this is by design for security or other reasons:
* The App should check if the instance lists are reachable and if not disable the check temporarily

Or there should at least be an error message telling me what's wrong and how to fix it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Have you restarted the app after selecting a different instance? There's been a bug that the app has to be restarted before the new instancd is used (will be fixed with next update).

**Comment by Bnyro** [comment]
> You can still choose an instance from the list, but that won't help and there's an error toast.
>
That's probably just due to the fact that the hardcoded instance list inside LibreTube is very outdated. I've updated it in #5752.

I've also tested the app using an official instance while DNS blacklisting piped-instances.kavin.rocks - and the app continued to work fine as expected (except if you select a dead instance).
