### ISSUE TITLE
Sometimes usage of exit gesture, mini player overlaps navbar

### ISSUE THREAD

**Issue by Eliya-Manoj** [libre-tube/LibreTube#5743]
### Steps to reproduce

1. Play video
2. Enter fullscreen using gesture ( Do not use fullscreen button )
3. Exit from full screen using exit gesture ( Do not use Exit button )
4. 

https://github.com/libre-tube/LibreTube/assets/90308888/df63b055-eaf5-4458-988c-1ea6baa0dfc5

### Expected behavior

Mini player do not overlap NavBar

### Actual behavior

Mini player overlaps NavBar

### LibreTube version

Latest Debug

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Are you still facing this issue? I haven't faced it in a looong time
