### ISSUE TITLE
Display of Comments and Replies is Broken 

### ISSUE THREAD

**Issue by akano12** [libre-tube/LibreTube#5746]
### Steps to reproduce

1. Play a video
2. Expand a comment with replies 

### Expected behavior

1. Display the expanded comment in top and the replies below it
2. When tapping back after expanding a comment from replies, don't close the comments. 

### Actual behavior

1. Expanded comment is shown twice, on top and bottom of the sheet
2. Comments are closed when tapping back from expanded comments

### LibreTube version

Latest debug 

### Android version

13

### Other details

https://github.com/libre-tube/LibreTube/assets/50032603/c3541425-447b-4d86-93ca-de089f6f6f6c

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/pull/5589#pullrequestreview-1874357211

**Comment by akano12** [comment]
This has another annoying problem, sometimes it loads the replies of a previous comment.

Let's say you expand comment A and read the replies, if you close replies and expand comment B, replies of comment A will appear.

**Comment by Bnyro** [comment]
The back button is still broken. Please move that to a new issue, since the major bug with replies is now fixed I want to have that smaller issue at a different place.
