### ISSUE TITLE
Video links do not play

### ISSUE THREAD

**Issue by Ehab-d** [libre-tube/LibreTube#5764]
### Steps to reproduce

1. Open a YouTube video link
2. The player does not appear

### Expected behavior

LiberTube should start playing the video immediately.

### Actual behavior

The video starts playing with sound only. The player does not appear actually.

https://github.com/libre-tube/LibreTube/assets/129071698/2a44b913-3bb9-4133-96ed-7725184f4b06

### LibreTube version

0.22.2

### Android version

Android 10

### Other details

The video actually starts playing (and the media controls can be seen in the notifications), but with only sound, and the player is completely disappeared.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Ehab-d** [comment]
I think this issue is caused by the fix that was made to #5692

**Comment by Bnyro** [comment]
It's caused by https://github.com/libre-tube/LibreTube/pull/5698, but you're the only person that seems to have such an issue.

**Comment by Ehab-d** [comment]
@Bnyro Tell me the information I provide to you from my own so that this will help you solve the issue. I love LibreTube but it really annoys me so much.

**Comment by FineFindus** [comment]
I tested the issue on two different devices, running Android 14 and 10. It's reproducible on the device running Android 10, but not on the one running 14.

**Comment by nathgit** [comment]
I have the same problem. I have the latest version of libretube, on Android 11. Is there a fix? Do I need to go to an older version?

**Comment by Ehab-d** [comment]
> For me, it just opens to the main screen, & shows a toast message saying "initial player response not valid". I have the latest version of libretube, on Android 11. Is there a fix? Do I need to go to an older version?

Maybe this is a different issue? Overall FineFidus has solved it by reverting the change ... You can check whether it is solved or not by trying [Nightly Builds](https://github.com/libre-tube/NightlyBuilds).

**Comment by ZenMar2000** [comment]
> Maybe this is a different issue? Overall FineFindus has solved it by reverting the change ... You can check whether it is solved or not by testing [Nightly Builds](https://github.com/libre-tube/NightlyBuilds).

I tried the latest Nightly build, still same problem. My phone is also running Android 11.

I went back and downloaded previous releases, 0.21.1 does not have that problem but videos are not getting loaded, I'll try even older versions I guess.
