### ISSUE TITLE
Searching in the YT music categories gives strange results

### ISSUE THREAD

**Issue by houyan0111** [libre-tube/LibreTube#5775]
### Describe your suggested feature

Search doesn't work. When searching for someone in channel, playlist, yt music songs and yt music albums, it shows some strange results and I can't get what I want to search for. There is no problem with version 0.21.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by M00NJ** [comment]
I get search results, but they are strange. It's not showing me recent uploads like it used to, but popular old videos, sometimes 10 years old. I can't really find what I'm looking for anymore.

**Comment by Bnyro** [comment]
@Isira-Seneviratne

**Comment by Isira-Seneviratne** [comment]
> @Isira-Seneviratne 

I'll take a look at this issue later today, I'm a bit occupied right now.
