### ISSUE TITLE
Swipe up gesture to access full screen does not work as expected

### ISSUE THREAD

**Issue by Loleman11** [libre-tube/LibreTube#5785]
### Steps to reproduce

expres

### Expected behavior

Users should be able to download videos reliably and without interruptions.
Upon swiping up, the video should smoothly expand to fullscreen mode.

### Actual behavior

Currently, the swipe-up gesture fails to activate fullscreen mode correctly, resulting in a frustrating and unintuitive user experience.
Video downloads can be inconsistent or fail altogether, limiting the utility of this feature and negatively impacting the user experience.

### LibreTube version

0.22.1

### Android version

Android 12

### Other details

I would like to express my gratitude for the valuable work they do, and for that, I leave you these two suggestions that could satisfy users, if not, do not hesitate to ignore them, there is no problem, because they fulfill their main function

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
> Users should be able to download videos reliably and without interruptions.
>
That depends on the instance, not on LibreTube itself. I can only recommend hosting a private instance (as I do), and everything works perfectly fine.

> Upon swiping up, the video should smoothly expand to fullscreen mode.
>
Please share a screen recording.

**Comment by Loleman11** [comment]
https://github.com/libre-tube/LibreTube/assets/151466389/eb83e9c7-bb18-43da-be13-eb1a4eab3bda

It's as if the screen rotates vertically, and when I try to use the downward gesture again, it takes me out of the player.
I've figured out what the issue with slow downloads was, and it's because I disable Piped's proxy. Thanks.

**Comment by Eliya-Manoj** [comment]
https://github.com/libre-tube/LibreTube/issues/5158. I think same issue. If i use swipe up gesture, the player enable full-screen based on player settings. But, Video aspect ratio and landscape not working properly.

**Comment by Bnyro** [comment]
Tracking at https://github.com/libre-tube/LibreTube/issues/5158
