### ISSUE TITLE
Click the up and down arrows in the subscription and it will keep loading.

### ISSUE THREAD

**Issue by houyan0111** [libre-tube/LibreTube#5788]
### Steps to reproduce

Click the up and down arrows in the subscription and it will keep loading

### Expected behavior

Show subscription channels

### Actual behavior

keep loading

### LibreTube version

0.22.1

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please share a screen recording.

**Comment by houyan0111** [comment]
https://github.com/libre-tube/LibreTube/assets/158655653/fb76692f-f80c-4226-b50c-fe9cd61d6499

**Comment by houyan0111** [comment]
https://github.com/libre-tube/LibreTube/assets/158655653/20ca8051-90f6-426d-96c9-6cc04204c329

**Comment by houyan0111** [comment]
> 请分享屏幕录制。


https://github.com/libre-tube/LibreTube/assets/158655653/e0378454-b8d9-402a-8a45-a32f3c2ab771

**Comment by houyan0111** [comment]
> Please share a screen recording.


https://github.com/libre-tube/LibreTube/assets/158655653/c38e7b59-a63d-4670-a42c-4fa1f6de03c8

**Comment by houyan0111** [comment]
Version 0.21 can directly display subscription channels instead of continuously loading

**Comment by houyan0111** [comment]
> Please share a screen recording.

![IMG_20240322_095512](https://github.com/libre-tube/LibreTube/assets/158655653/00f49c1e-8e82-4948-923a-e73633c32360)
Version 0.21 can directly display subscription channels instead of continuously loading

**Comment by akano12** [comment]
Closing in favor of https://github.com/libre-tube/LibreTube/issues/5791
