### ISSUE TITLE
Trash Icon in Download Section - missing settings to make invisible

### ISSUE THREAD

**Issue by LutzDE** [libre-tube/LibreTube#5792]
### Describe your suggested feature

In my last update (Revision 0.22.1) two new button's appear in the downloaded files section.

These are placed on the button of the list. If you scroll down to the end and choose a file,
it's very likely that you hit the "delete" (Trashicon) button. Maybe then the music and so on collection is gone.
Okay, there's a requestor, to confirm this action, but it's too easy to hit this.

I don't find a setting to make the "delete" Trashicon invisible in the download-section.

My request is to add a setting's parameter (and to implement the corresponding (in)visibility-code): 
  
   Download - trashicon visible: true/false.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It's out of scope to add options for such small behavior changes.

There's a confirm dialog so you won't accidentially delete all your downloads - and it's not hard to not touch the button.

**Comment by LutzDE** [comment]
Sorry to read this... then it's time for me to fork.

I don't understand, why this button was added. It's absolute not necessary and blocks the view on small devices.
