### ISSUE TITLE
Problem with full screen image on Android TV

### ISSUE THREAD

**Issue by hni315** [libre-tube/LibreTube#5794]
### Steps to reproduce

Hello, the program is installed on the Android TV, but the image does not play in full screen, and the control itself cannot select the full screen icon. Please provide a version that is optimal with Android TV

### Expected behavior

Play Full screen image in android tv

### Actual behavior

It is not possible to select the full screen icon with the TV remote control, and the control must be of mouse type

### LibreTube version

0.22.1

### Android version

Android tv 11

### Other details

In general, if an optimal version for Android TV is provided, it is better to choose proxies on the start page, there is a problem with TV control.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't plan to support Android TV, as per described in ROADMAP.md.

**Comment by hni315** [comment]
Thank you for your reply
Unfortunately, YouTube is filtered in Iran, and your program is a good
option to solve this problem, although in recent days, your program does
not open with the program's proxies.
Good luck
