### ISSUE TITLE
Sort?

### ISSUE THREAD

**Issue by the-arxyn** [libre-tube/LibreTube#5799]
### Describe your suggested feature

"LibreTube" is the best foss alternative to YouTube but the only feature missing is the "Sort" option while searching a video.

### Other details

Please add it,it's very useful!!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Missing API support from piped
