### ISSUE TITLE
Auto-fullscreen doesn't work after switching to another app

### ISSUE THREAD

**Issue by LavellanDWR** [libre-tube/LibreTube#5800]
### Steps to reproduce

1. Enable the auto-fullscreen setting. Note: the Android auto rotate is off, i.e. it only rotates with the pop-up button. 
2. Play a video and rotate the device to enter fullscreen landscape mode.
3. Pause the video, rotate back to portrait mode.
4. Switch to another application by minimising LibreTube, opening the recents menu or swiping at the bottom of the screen. 
5. Switch back to LibreTube by either method and rotate the device. 

### Expected behavior

The video is supposed to go full-screen automatically, turning to landscape mode.  

### Actual behavior

The orientation does not change until you minimise the video by swiping down, then tapping on the minimised player and rotating the device again. 

### LibreTube version

0.22.1

### Android version

Android 13

### Other details

This issue was introduced in a recent update, either v0.22.1 or v0.22.0.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LavellanDWR** [comment]
It doesn't work if you rotate it more than once, either.

**Comment by jx319** [comment]
This also happens to me (Android 11, LibreTube 0.22.1)
