### ISSUE TITLE
Theming incorrectly resets to "half-Light" theme when switching from audio mode to video mode

### ISSUE THREAD

**Issue by knakamura8** [libre-tube/LibreTube#5804]
### Steps to reproduce

1.)  Set theme to Dark theme
2.)  Play a video
3.)  Press the button to switch to audio mode

[Here the theme switches to Light mode for some reason]

4.)  Press the button to switch back to video mode

[Light theme persists in the comments area below the video, but hitting the Back button to look at the rest of the app, the rest of the app is back into Dark theme.  The Light theme persists in this "half-Light" state even when clicking on other videos, until I completely close the app and restart it.]

### Expected behavior

Behavior should remain in Dark theme throughout the process.	

### Actual behavior

Behavior changes into "half-Light mode" which persists until restart.

### LibreTube version

0.21.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by nik-conder** [comment]
Android 13 can't reproduce.

Version 0.21.1 it is old. Please check on the [latest version](https://github.com/libre-tube/LibreTube/releases).

**Comment by knakamura8** [comment]
Thanks, just pulled the newest version (it only recently appeared on March 24 in F-Droid).  Same issue on Android 10.

**Comment by Bnyro** [comment]
Can you please try installing different APKs from GitHub releases? I remember there was some issue when installing the universal APK instead of the proper one for your architecture.

**Comment by knakamura8** [comment]
OK, I will try that a bit later, thanks!  It is not a huge deal, and if it is already fixed in later Android versions, then that's fine.
