### ISSUE TITLE
Blacklist/whitelist videos with certain keywords in title

### ISSUE THREAD

**Issue by arkydon** [libre-tube/LibreTube#5806]
### Describe your suggested feature

Adding "football" as **blacklist** will hide all videos with "football" in their title.

Adding "minecraft", "Terraria" as **whitelist** will **only** show videos with "minecraft" **OR** "Terraria" in their title.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/5028

**Comment by 2000prasanth** [comment]
Adding this feature will be greatly appreciated like "Blocktube"  web extension
