### ISSUE TITLE
Scroll state reset after rotation change

### ISSUE THREAD

**Issue by E0697** [libre-tube/LibreTube#5808]
### Steps to reproduce

1. Go to subscriptions tab
2. Start playing a video
3. Use the swipe up gesture to enter fullscreen mode
4. Use the swipe down gesture to exit fullscreen mode
5. Swipe down to go to mini-player
6. The first swipe down gesture moved the feed position upwards

### Expected behavior

The position should be unchanged

### Actual behavior

The position is changed as if the swipe down was used in the feed not the fullscreen player

### LibreTube version

0.22.1

### Android version

Android 14

### Other details

The issue was introduced in v0.21, and doesn't seem to affect shorts.

https://github.com/libre-tube/LibreTube/assets/66939100/67690e6d-f46d-4f1e-9f54-72119f69368d

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by E0697** [comment]
It turns out that it's not the gesture itself to blame. I used the fullscreen button amd it still happens. It moves the feed to the top (latest video). Is this intentional? I think the behavior somewhat changed from v0.21, I recall it wouldn't go all the way to the top.

**Comment by xlash123** [comment]
This bug is only expressed when going into landscape mode. When setting the fullscreen mode to portrait, the bug does not occur.

**Comment by xlash123** [comment]
A little more testing shows that **any** screen rotation transition resets the scroll position in all **video feeds**. You can replicate this by setting General > Screen Orientation to "Auto-rotation".

I also noticed that not all scrollable lists were affected, such as subscriptions and settings. I could only get it to occur on the video feed lists.

**Comment by Bnyro** [comment]
I've tracked it down to be this issue: https://github.com/material-components/material-components-android/issues/3473. Not sure if there's any workaround for this :shrug:

**Comment by Bnyro** [comment]
The issue applies for the subscriptions, watch history and the views for looking at a channel or a playlist.

**Comment by xlash123** [comment]
Correction: by "subscriptions", I meant the view that enumerates your channel subscriptions. The subscriptions video feed is indeed affected.
