### ISSUE TITLE
Back on the search page with keyboard open closes search rather than keyboard

### ISSUE THREAD

**Issue by omentic** [libre-tube/LibreTube#5812]
### Steps to reproduce

1. Tap on the search bar. The keyboard should open.
2. Tap the Android back button.
3. Observe that not only does the keyboard collapse, but you are sent back.

### Expected behavior

This is in contrast to how search behaves in other application and systemwide. The expected behavior is for the keyboard to collapse, but the search modal to remain open. This is useful for ex. scrolling through search suggestions.

### Actual behavior

.

### LibreTube version

0.22.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by brnwlshubh** [comment]
@Bnyro This issue is still present.
I'm using latest debug build.
