### ISSUE TITLE
Subtitle button in video player

### ISSUE THREAD

**Issue by SalvadorHondai** [libre-tube/LibreTube#5814]
### Describe your suggested feature

please add button in the video player to activate subtitles with one click like what we have on YouTube 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not planned due to already too many buttons in that interface. You can set a default subtitle language in the settings.
