### ISSUE TITLE
Change overlay icon size & spacing

### ISSUE THREAD

**Issue by laur89** [libre-tube/LibreTube#582]
### Describe your suggested feature

This is an extremely subjective one, so all opinions welcome.

**As-is:**
When the video overlay is active, then the displayed icons are
1. too close together - you need to take care to hit play/pause icon instead of the neighboring rewind/forward.
2. too small - same reason as above - mistakes are easily made with smaller buttons

**To-be:**
1. move back/forward icons further from the central play/pause
2. make all three icons larger.

### Other details

How far apart should be the icons moved and increased in size? Really don't know. Someone with more UX knowledge should make that call.

Personally would make the play button around 1.5x larger; same for the distance - would increase around 1.5x.

If #576 gets implemented, then increasing back/forward button size wouldn't even be necessary, as tap should be registered from a larger screen area than just the icon anyway.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by archroid** [comment]
You are right. We will work on it. Thanks for feedback.
