### ISSUE TITLE
Audio Player Overlapping Navigation Bar When Switching From PiP

### ISSUE THREAD

**Issue by akano12** [libre-tube/LibreTube#5832]
### Steps to reproduce

1. Play a video
2. Go to pip
3. Switch to audio mode
4. Reopen LT from notifications panel 

### Expected behavior

Show audio player UI 

### Actual behavior

Audio player UI overlaps navigation bar

### LibreTube version

0.22.2

### Android version

Android 13

### Other details

https://github.com/libre-tube/LibreTube/assets/50032603/bf7ca4c7-1e42-4c18-b6e0-5bbf0807b60a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Same issue as https://github.com/libre-tube/LibreTube/issues/5743.
