### ISSUE TITLE
Most of the time video comments are not showing 

### ISSUE THREAD

**Issue by Sourav0357** [libre-tube/LibreTube#5838]
### Steps to reproduce

When I click on video, video starts playing, most of the time comments are not showing, sometimes the replies of the comments are not showing too.

### Expected behavior

Video comments should be seen 

### Actual behavior

Video comments are not showing 

### LibreTube version

0.22.2

### Android version

Android 14

### Other details

![Screenshot_20240329_110715](https://github.com/libre-tube/LibreTube/assets/165359639/3d6384ad-ce24-4705-a33c-bf439b6ba5e8)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We use the NewPipeExtractor, see https://github.com/TeamNewPipe/NewPipe/issues/10808
