### ISSUE TITLE
New feature!

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#584]
### Describe your suggested feature

![Screenshot_20220621-000612_SkyTube Extra](https://user-images.githubusercontent.com/104249296/174671408-c972b2df-df3e-4b83-98ef-5c2c4ad873d1.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
that's the opposite of what the project is meant to be for...
