### ISSUE TITLE
repeat video

### ISSUE THREAD

**Issue by jeremy10tie** [libre-tube/LibreTube#5840]
### Steps to reproduce

current repeat still not working

### Expected behavior

must repeat the current video

### Actual behavior

do nothing

### LibreTube version

0.22.2

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by dev-shivam-verma** [comment]
Hi there i ended up wasting my 1 hour on it and found that it is working fine, I think the confusion is there, the video wont repeat automatically if autoplay is off.
