### ISSUE TITLE
Thumbnails are not cached

### ISSUE THREAD

**Issue by Tunsinasro** [libre-tube/LibreTube#5845]
### Steps to reproduce

Open the app and wait until thumbnails load and then exit the app

### Expected behavior

Thumbnails should be cashed and loaded instantly the next time the app is opened

### Actual behavior

The thumbnails are not cached and so the thumbnails are redownload again, which consumes bandwidth and makes the app laggy

### LibreTube version

0.22.2

### Android version

Android 13

### Other details

I changed the max cache size in the advanced settings page but nothing changed

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I've quickly debugged this because it seemed strange to me, but after debugging with #5849 it turned out that it really caches properly and only makes network requests to load the images the first time.

**Comment by Tunsinasro** [comment]
I included this video to show what I mean by thumbnails are not cached, usually when an app caches assets they should load instantly the moment you open the app (like newpipe), in the case  of libretube it takes some time to load images (thumbnails and channels icons), especially if the data connection is bad, and I've noticed that just opening the app, it uses about 5mb, even if there is no new video's.

https://github.com/libre-tube/LibreTube/assets/147873384/2442f482-5c1e-4c24-829f-e0b2e5c13ce6
