### ISSUE TITLE
Adding a view for transcript of video

### ISSUE THREAD

**Issue by shayan15sa** [libre-tube/LibreTube#5847]
### Describe your suggested feature

Hi guys, first of all thank you for amazing app. It really has help me these days.

I sometimes like to read the transcript of a video instead of watching it completely. YouTube itself has this feature but it's not really good for reading.
It would be amazing to see search feature too.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The NewPipe Extractor does not support this yet.
