### ISSUE TITLE
Playlist or Album downloads don't work

### ISSUE THREAD

**Issue by NewManEr** [libre-tube/LibreTube#5848]
### Steps to reproduce

Select Playlist or Album, press Download. Then app will show Dialog video quality, audio, etc. But there's no button to proceed to download. It's only okey with one video or audio. But not with Playlist or Album. Tried with Youtube and Youtube Music Playlists and Albums. Also I Tried 0.22.0, 0.22.1, 0.22.2 versions of app

### Expected behavior

It shoud work since 0.22.0 version.

### Actual behavior

Nothing happened.

### LibreTube version

0.22.2

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please share a recording.

**Comment by NewManEr** [comment]
Screenrecording
https://github.com/libre-tube/LibreTube/assets/165528607/452d0345-2b14-4b21-be70-62f8744dc3cf

**Comment by NewManEr** [comment]
It's only on Android 9.

**Comment by INFINITEKIFF** [comment]
It's not only that you can't download albums or playlists. There is a download button and the dialogue comes up as per the above screenshot/recording but Uber video and/or audio there are no options of bitrate? It just says no video, no audio and that's it. You can't proceed why further????

**Comment by INFINITEKIFF** [comment]
Sorry I don't know what Bnyro's fix means?
Are you saying we have to be apt in writing code in Android command line to fix this?
