### ISSUE TITLE
Do not play any video

### ISSUE THREAD

**Issue by VitaliyAT** [libre-tube/LibreTube#5852]
### Steps to reproduce

Just try play any video from YT

### Expected behavior

Should play

### Actual behavior

Do not play

### LibreTube version

0.22.2

### Android version

14

### Other details

It's don't download and don'd play any video. No VPN used.

https://github.com/libre-tube/LibreTube/assets/1639608/5374ebc8-2a27-4a75-8e76-a9ae7a841f5d

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by nanedi** [comment]
I am not sure if it is related to this issue.

https://github.com/TeamPiped/Piped/issues/2915

Thanks

**Comment by Bnyro** [comment]
#5855
