### ISSUE TITLE
videos can't be downloaded and located

### ISSUE THREAD

**Issue by userforsource** [libre-tube/LibreTube#5854]
### Steps to reproduce

I have installed libre tube when i download a video that video downloads but i could bot find that video anywhere.

### Expected behavior

Like what i was using newpipe if i download something i can find that fine in download folder and also i can find that and choose other locations for download which i really like.

### Actual behavior

I can't find download and use on other devices

### LibreTube version

22.2

### Android version

android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/issues/4292#issuecomment-1646785340
