### ISSUE TITLE
YouTube temporary playlist import support

### ISSUE THREAD

**Issue by nathgit** [libre-tube/LibreTube#5856]
### Describe your suggested feature

I'd like to see the an option to import YouTube temporary playlists, and treat them as regular imported playlists. To create a temporary playlists You use the following url:

`https://www.youtube.com/watch_videos?video_ids=`

Video IDs (the string after the "v=") are added to the end, seperated by a comma. You can also give it a title by adding "&title=" to the end.

For example: https://www.youtube.com/watch_videos?video_ids=X0B333jjiHM,huvysaySBrw,7wnQHNDiA&title=photopea-displacement-map

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
With the next release, you will be able to open such links in  (or share them with)  LibreTube, and it asks and allows you whether you want to import that playlist.
