### ISSUE TITLE
Channel creation error 

### ISSUE THREAD

**Issue by spaceopera** [libre-tube/LibreTube#5857]
### Steps to reproduce

Click on Channel then click on new then click on channel name text box then try to select drop down nothing happens in the okay button is grayed out

### Expected behavior

When clicking on the new button for channel creation I would expect that I would be able to put a name in and then select the channels to associate with this tag

### Actual behavior

When clicking on the new button for channel creation a red explanation point is showing. And you cannot create a channel. The okay button stays grayed out
![Screenshot_20240402-202453 (2)](https://github.com/libre-tube/LibreTube/assets/4389036/aff7aaaf-d61e-4610-bae2-12c42ad9caae)

### LibreTube version

0.22.2

### Android version

Android 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You have to enter a group name first.

**Comment by spaceopera** [comment]
Thanks for the reply.  I have tried putting a name in the field and
something in the search field but it does not allow me  to create a channel
group.

Thank you,
Gene
