### ISSUE TITLE
Audio mode not working using HLS

### ISSUE THREAD

**Issue by opfromthestart** [libre-tube/LibreTube#5861]
### Steps to reproduce

1. Click on any video
2. Go to audio mode
3. Source error

### Expected behavior

The audio should play normally.

### Actual behavior

Source error and nothing plays.

### LibreTube version

0.22.2

### Android version

Android 12

### Other details

Related to #5855, but audio mode should still work when using HLS, since video works fine.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Ehab-d** [comment]
I was experiencing this issue today. I appreciate the LibreTube devs' efforts to solve these issues, especially since some of them are caused by Piped in the first place.
