### ISSUE TITLE
Watching video not working

### ISSUE THREAD

**Issue by user-naa** [libre-tube/LibreTube#5864]
### Steps to reproduce

-

### Expected behavior

-

### Actual behavior

LibreTube always worked very slow on my device, some videos didn't load at all. Now I can't watch any video. But piped.video website work on my device well.

### LibreTube version

0.22.2

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/issues/5855
