### ISSUE TITLE
New version error, player

### ISSUE THREAD

**Issue by ghaffariasar** [libre-tube/LibreTube#5868]
### Steps to reproduce

Error when start playing video : Initial player response is not valid

### Expected behavior

Initial player response is not valid

### Actual behavior

Initial player response is not valid

### LibreTube version

0.22.2

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/TeamPiped/Piped/issues/2487
