### ISSUE TITLE
no playback and source error in audio mode

### ISSUE THREAD

**Issue by VoKi21** [libre-tube/LibreTube#5876]
### Steps to reproduce

instance kavin.rocks libre and others, proxy enabled, use HLS on, audio quality auto, video quality 480p everywhere, codecs all
[prefs.json](https://github.com/libre-tube/LibreTube/files/14911685/prefs.json)

### Expected behavior

videos play in audio only mode

### Actual behavior

dont hear any audio, time doesnt go, see popup with "source error"
![Screenshot_20240409-021352_LibreTube](https://github.com/libre-tube/LibreTube/assets/74360792/7abe1d34-e10c-4aaf-80f5-f6c1acce3638)

### LibreTube version

0.22.2 (50)

### Android version

Android 14, crDroid 10.4 with microg

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Ehab-d** [comment]
The audio player did not respect the `Use HLS` setting and always used DASH. Fixed in #5862. You can expect it to be resolved in the next release or try the [nightly builds](https://github.com/libre-tube/NightlyBuilds).
