### ISSUE TITLE
Pure Theme not applying to the Navation bar

### ISSUE THREAD

**Issue by kokopossum** [libre-tube/LibreTube#5877]
### Steps to reproduce

Step 1 : Enable Pure Theme in Settings> Appearance >Pure Theme

Step 2 : Reload the app as prompted, then look at the main page Navigation bar

### Expected behavior

The Navigation bar should match the pure light or dark theming for a clean look. 

Ex if the app in pure theme mode dark, the Nav bar should be #000000 (black) not #1F1E23 (grey)

### Actual behavior

The Navigation bar does not change with pure theme mode and therefore, does not match with the "pure" themed application.
![Screenshot_20240408_201510_LibreTube](https://github.com/libre-tube/LibreTube/assets/156375607/70e5d798-350c-4604-8be4-2c7489b5f4ef)

### LibreTube version

0.22.2

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by imwints** [comment]
> The Navigation bar should match the pure light or dark theming for a clean look.

I don't think it should. There are some elements that always have a surface tint, like the overflow menu or the navigation bar. I'd rather colorize the title bar on scroll than remove the color on the navigation bar

**Comment by Bnyro** [comment]
I agree with @imwints that it shouldn't be 100% black.

It's now darker than before, but still can be distinguished from the other content due to the fact that it's color is slightly different.

**Comment by imwints** [comment]
Thus just made the overflow menu black, which makes it look really weird

**Comment by imwints** [comment]
![Screenshot_20240410_012837_LibreTube Debug](https://github.com/libre-tube/LibreTube/assets/76256484/554426f9-15ce-4181-ba03-170d893f3fc0)

**Comment by kokopossum** [comment]
> I agree with @imwints that it shouldn't be 100% black.
> 
> It's now darker than before, but still can be distinguished from the other content due to the fact that it's color is slightly different.

 I also agree with @imwints by default there should be some color delineation for menus and navigation. However, maybe a possible middle ground could be either a toggle to force everything to match or implement custom user themes if possible?
