### ISSUE TITLE
Download exeptions

### ISSUE THREAD

**Issue by VitoItalianGamer** [libre-tube/LibreTube#5878]
### Steps to reproduce

1.Go on to any video
2.Download and choose presets
3.Download error popups pausing download.

### Expected behavior

Downloads with no issues

### Actual behavior

Download exceptions occur even if WiFi is working.

### LibreTube version

0.22.2

### Android version

Android 12

### Other details

When download errors occur video might not play properly.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/issues/5661
