### ISSUE TITLE
Videos aren't playing from last week

### ISSUE THREAD

**Issue by nascentphilosopher** [libre-tube/LibreTube#5879]
### Steps to reproduce

Nothing is playing at all

### Expected behavior

Videos should be played

### Actual behavior

Nothing playing at all

### LibreTube version

V0.22.2

### Android version

Android 12 

### Other details

Videos aren't playing 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/5855
