### ISSUE TITLE
Bug: Strange black bubble

### ISSUE THREAD

**Issue by Unaiperezdiaz** [libre-tube/LibreTube#5882]
### Steps to reproduce

In the last nigthly build while you scroll appears a black bubble (like when you are refreshing the feed manualy).

https://github.com/libre-tube/LibreTube/assets/49728036/895385fe-e04f-4e8c-9d60-5304670e45df

### Expected behavior

This bubble appears only when you scroll the feed.

### Actual behavior

No bubbles.

### LibreTube version

Last build

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Does this still happen to you in the latest release?

**Comment by Unaiperezdiaz** [comment]
So far it hasn't happened to me since the last version, maybe it has been fixed.

**Comment by Bnyro** [comment]
I've made some changes to fix other issues with that layout since then which might have been related. Feel free to re-open once it occurs again.

**Comment by ScriptSlayer0** [comment]
I have reopened this issue again but this bug downloading the last nightly release.
When I'm scrolling in the subscription page a strange bubble appears.
