### ISSUE TITLE
Videos not playing from last week

### ISSUE THREAD

**Issue by nascentphilosopher** [libre-tube/LibreTube#5884]
### Steps to reproduce

On touching any video videos not responding!?

### Expected behavior

Video should be played on touching it

### Actual behavior

Videos just showing blackout

### LibreTube version

V0.22.2

### Android version

Android 12 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Ehab-d** [comment]
This issue is related to Piped and is being tracked and resolved in #5855. As a temporary solution, you can switch playback from DASH to HLS from Settings → Audio and video → Quality → Use HLS.
