### ISSUE TITLE
SponsorBlock implementation in LibreTube Nightly is crashing when trying to create new segment

### ISSUE THREAD

**Issue by akashsriramganapathy** [libre-tube/LibreTube#5897]
### Steps to reproduce

I am reporting a bug in the SponsorBlock implementation in the LibreTube Nightly app. I am unable to create new segments in videos because the app crashes every time I try to do so. Steps to reproduce:

    Open the LibreTube Nightly app.
    Navigate to a video with SponsorBlock support.
    Tap the SponsorBlock button to open the SponsorBlock interface.
    Tap the "Create new segment" button.
    The app crashes.

### Expected behavior

The app should allow me to create a new segment without crashing. Actual behavior: The app crashes every time I try to create a new segment. I have tried restarting the app and my device, but the issue persists. I am using the latest version of the LibreTube Nightly app

### Actual behavior

 The app crashes every time I try to create a new segment in a video using the SponsorBlock feature. This happens consistently and I have not been able to create a new segment without the app crashing.

### LibreTube version

0.22.2

### Android version

Android 13

### Other details

https://github.com/libre-tube/LibreTube/assets/39720035/1889d33e-7c32-4c82-8b8f-118ea31d2835

    I have recorded a video of the crash and have attached it to this issue for reference.
    I have searched online for similar issues with LibreTube and SponsorBlock, but have not found any relevant results.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
You mean the dialog opens abd close instantly? Or LibreTube crashes? The recording is just 2 seconds

**Comment by akano12** [comment]
Try with latest debug version as it seems to be working fine on my side

**Comment by Bnyro** [comment]
Thanks for the detailed report - this was a left-over from before the most recent changes, where creating new segments and voting for already existing segments has still been in two different dialogs.
