### ISSUE TITLE
libretub always opens a video when i start it

### ISSUE THREAD

**Issue by teacupmaps** [libre-tube/LibreTube#5898]
### Steps to reproduce

1. reboot
2. open libretube

### Expected behavior

nothing starts, the home page is open

### Actual behavior

it automatically starts playing this video, in this layout that is not meant for phones, even though other videos play in one-column layout
i am not interested in this video and i don't know what is the language in this video and what are they saying
https://piped.video/watch?v=6sRWt9Q9IrA
![Screenshot_20240413-113252_LibreTube](https://github.com/libre-tube/LibreTube/assets/158172547/1a3b6397-0d0d-479b-919e-e57a7fc6f77a)

### LibreTube version

0.22.2

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
This doesn't seem to be reproducible at all, and we don't persist the video queue during reboots.
