### ISSUE TITLE
Videos not playing now from 15 days and I don't get any assistance

### ISSUE THREAD

**Issue by nascentphilosopher** [libre-tube/LibreTube#5899]
### Steps to reproduce

Video not playing from last 15 days

### Expected behavior

Videos should be play 

### Actual behavior

Video not playing from past 15 days 

### LibreTube version

V0.22.2

### Android version

Android 12 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/5855
