### ISSUE TITLE
[FEATURE] Picture-in-picture (PiP) support

### ISSUE THREAD

**Issue by FBIAgent05** [libre-tube/LibreTube#59]
**Describe the feature you'd like to see added**
Like in newpipe and vanced, when you exit the app, a small window of a youtube video pops out

**Additional context**
![Imagepipe_55.jpg](https://user-images.githubusercontent.com/74946397/158224000-682708a6-c1ca-4225-b41c-f07f0d187445.jpg)

**Comment by poligarpi** [comment]
+1
