### ISSUE TITLE
I think there are problems in the entitys

### ISSUE THREAD

**Issue by sonisaltiner** [libre-tube/LibreTube#5900]
### Steps to reproduce

Greetings. I think there are some problems with your app. When I select an entity and click on a youtube music song, it stays loading. When I select another entity, this time my channel subscriptions remain loading. When I select any entity, I have similar problems.

### LibreTube version

0.22.2

### Android version

Android 9

### Other details

Huawei MRD-LX1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
You mean instance?
https://github.com/libre-tube/LibreTube/issues/5855

**Comment by sonisaltiner** [comment]
Is there a problem with entity? Occasionally entitys starting with the prefix Kavin disappear. If I select any other occurrence, there are problems, some things stay loading.
