### ISSUE TITLE
filter by download date

### ISSUE THREAD

**Issue by krolaper** [libre-tube/LibreTube#5901]
### Describe your suggested feature

Are you planning to add a filter by video upload date as a result of a search query?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Yes, but it's not currently supported by NewPipe Extractor.
