### ISSUE TITLE
Videos can't load properly and freezes app

### ISSUE THREAD

**Issue by lue64** [libre-tube/LibreTube#591]
### Steps to reproduce

Tap on any video to play it

### Expected behavior

Video should load and start playing with audio and visuals and app should close just fine

### Actual behavior

Audio loads properly but the video player only shows a stuck loading circle. App will also freeze up and crash when attempting to exit with the home button.

### LibreTube version

0.3.2

### Android version

Android 8.0.0

### Other details

Phone model is "moto E5 cruise"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
probably #568, can you send me the debug logs?
