### ISSUE TITLE
Notification persists even after closing the app

### ISSUE THREAD

**Issue by gloriouspuffy** [libre-tube/LibreTube#5912]
### Steps to reproduce

1. Open any video
2. Close the video or app

### Expected behavior

Media player notification should be gone

### Actual behavior

Media player notification stays there untill you force stop libretube

### LibreTube version

0.22.2

### Android version

Android 13, Superior OS, Redmi 9(cattail)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/issues/5833
