### ISSUE TITLE
Add a "recommended" section in the home page

### ISSUE THREAD

**Issue by Tuquilo9** [libre-tube/LibreTube#5916]
### Describe your suggested feature

This section should show videos based on the recommendations of the videos that are the history.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Already rejected multiple times before, still not planned.
