### ISSUE TITLE
Improved settings!

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#592]
### Describe your suggested feature

![Screenshot_20220621-174928_Snaptube](https://user-images.githubusercontent.com/104249296/174816544-6bdea07e-4146-4db4-866e-c243e4f29cbb.jpg)
![Screenshot_20220621-174810_Snaptube](https://user-images.githubusercontent.com/104249296/174816552-5c78bcb5-fe9e-424f-a8fe-36e56ff28a84.jpg)
![Screenshot_20220621-174736_Snaptube](https://user-images.githubusercontent.com/104249296/174816558-2cada0e6-e84e-4d47-b259-595991dfbb83.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Your current ones are not helpful in any way and only fuck me up. If that's your goal then go on.
