### ISSUE TITLE
Crashes when playing video from channel name with "topic" as a substring and "disable piped proxy" feature turned on

### ISSUE THREAD

**Issue by gaining** [libre-tube/LibreTube#5929]
### Steps to reproduce

I haven't been able to use any piped instances for the past month, I used to use kavin.rocks libre all the time, but when I use it now, nothing at all plays. I tried other piped instances and it's the same thing where nothing plays. So now, my only option is to use disable piped proxy,  most videos play with that feature turned on. However, since I mainly use youtube to play music in the background, a lot of the music channels that I listen to have a "topic" in their channel name as a substring. 

### Expected behavior

play video/audio normally. I was trying to play this [video ](https://www.youtube.com/watch?v=uXrxh3w4Fpo) with "disable piped proxy" feature turned on

### Actual behavior

crashes and get this error message instead: 

`android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{6365151 u0 com.github.libretube/.services.OnlinePlayerService} 	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2005) 	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1979) 	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0) 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2241) 	at android.os.Handler.dispatchMessage(Handler.java:106) 	at android.os.Looper.loopOnce(Looper.java:201) 	at android.os.Looper.loop(Looper.java:288) 	at android.app.ActivityThread.main(ActivityThread.java:7924) 	at java.lang.reflect.Method.invoke(Native Method) 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1915) 	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1870) 	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822) 	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822) 	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(SourceFile:1) 	at androidx.core.content.ContextCompat.startForegroundService(SourceFile:7) 	at com.github.libretube.helpers.BackupHelper.playOnBackground(SourceFile:126) 	at com.github.libretube.helpers.BackupHelper.playOnBackground$default(SourceFile:34) 	at com.github.libretube.helpers.NavigationHelper.navigateVideo$default(SourceFile:73) 	at com.github.libretube.ui.adapters.PlaylistAdapter$$ExternalSyntheticLambda1.onClick(SourceFile:923) 	at android.view.View.performClick(View.java:7542) 	at android.view.View.`

### LibreTube version

0.22.2

### Android version

android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't think that's related to the video being from a `topic` channel, the crash logs say that it just failed to start a background service for playback which could happen with any video that way. Though I don't know why it happens - the video you shared works fine for me.

**Comment by gaining** [comment]
Ok, I'll try to reinstall to see if anything changes.

**Comment by Bnyro** [comment]
When using HLS, yes.

**Comment by gaining** [comment]
This is just a screenrecording of what's happening. I am using the disable piped proxy feature. Will try HLS with the kavin.rocks libre instance.

https://github.com/libre-tube/LibreTube/assets/7690230/48a712b2-ccbc-48ab-b2a6-4cc85f256056

**Comment by gaining** [comment]
Update: So for videos, HLS works but if you turn on "audio only mode" you'll get a "source error" message

**Comment by Bnyro** [comment]
The initial issue you reported is an Android issue, see https://stackoverflow.com/questions/44425584/context-startforegroundservice-did-not-then-call-service-startforeground#answer-49418249.

> Update: So for videos, HLS works but if you turn on "audio only mode" you'll get a "source error" message
>
This will be fixed with the next release.

**Comment by gaining** [comment]
No more crashes on this version at least it hasn't crashed as I used it all day today, and only audio mode works flawlessly on HLS. Thanks for all your work.
