### ISSUE TITLE
Add Video Filtering by keyword (Block videos who's title has a certain keyword)

### ISSUE THREAD

**Issue by 2000prasanth** [libre-tube/LibreTube#5938]
### Describe your suggested feature

Title Keyword Filtering for Videos: It would be greatly beneficial to have a feature that allows users to block videos based on specific keywords in the video title. This would help in filtering out unwanted content, providing a more personalized and user-friendly experience.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/5806
