### ISSUE TITLE
Videos won't play no matter the instance

### ISSUE THREAD

**Issue by akasaka99** [libre-tube/LibreTube#5941]
### Steps to reproduce

1. Clicking on thumbnail to play a video
2. back video player and nothing happens
3. thumbnail and the duration of the video are visible
4. smae issue with all instances

### Expected behavior

the video should play

### Actual behavior

black video player0

### LibreTube version

0.22.2

### Android version

Adnroid 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Scrut1ny** [comment]
I can confirm also, I have been experiencing this issue a ton also. I always use a VPN though so theres no point of me using instances proxies anymore. For some reason though age restricted content doesn't play/load properly, I try to watch Police Activity and others, but the video is just black and won't actually start and play anything. Everything else loads properly though.

**Comment by heartlog** [comment]
I am also facing same problem, but with all videos on all insˢ.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/issues/5855

**Comment by JohnnyBrav0Sr** [comment]
I experience this issue only via VPN. Even when I exclude the app from VPN, the videos still won't play. However, using another user profile that has no VPN, the videos play fine.
