### ISSUE TITLE
Videos doesn't start

### ISSUE THREAD

**Issue by PSFaceLLC** [libre-tube/LibreTube#5942]
### Steps to reproduce

When I click on any video it doesn't start, I even tried uninstalling the app but nothing changed.
![Screenshot_2024-04-30-09-29-02-859_com github libretube](https://github.com/libre-tube/LibreTube/assets/141609033/b873bae8-079b-400a-a257-14728c1fad5b)

### Expected behavior

The videos should start

### Actual behavior

The videos doesn't start

### LibreTube version

0.22.2

### Android version

Android 14

### Other details

If I look at the video quality it says 0p, but it won't let me change it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/5855
