### ISSUE TITLE
SponsorBlock mutes media volume but didn't restore it

### ISSUE THREAD

**Issue by lawson85** [libre-tube/LibreTube#5945]
### Steps to reproduce

Enable all of the SponsorBlock skipper categories.

Open a video that has SponsorBlock segments: https://youtu.be/8H6EoTkm44U or https://youtu.be/E_kZFI1rtn4

See it skip and mute the segments but then there's no sound after because media volume channel is 0%

### Expected behavior

Leave my sound/media volume channel alone

### Actual behavior

My media audio channel goes to 0 0%

### LibreTube version

0.22.2

### Android version

Android 12

### Other details

Tested only on Fairphone 4 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
SponsorBlock segments don't have anything to do with the volume - the segments are only skipped by seeking the player to the time after.
