### ISSUE TITLE
Miniplayer obscures UI elements

### ISSUE THREAD

**Issue by martin-desktops** [libre-tube/LibreTube#595]
### Steps to reproduce

- Play a video
- Minimize video to miniplayer
- Go to Library tab

### Expected behavior

Button should be accessible

### Actual behavior

Button is covered by miniplayer
 
![Screenshot_2022-06-21-16-32-20-140_com github libretube debug](https://user-images.githubusercontent.com/64419373/174825711-ecca2eab-0bf3-4422-99b1-1bddce1e3ff8.jpg)

### LibreTube version

LibreTube 0.3.2

### Android version

Android 11

### Other details

# Possible solution:
Google already solved the same issue in its apps by linking positions of conflicting elements 
Maybe the pictures below will illustrate it in a better way
![Screenshot_2022-06-20-12-14-16-473_com google android apps maps](https://user-images.githubusercontent.com/64419373/174825275-d61be82b-335a-4b28-9ccf-09934a2762c0.jpg)
![Screenshot_2022-06-20-12-14-12-967_com google android apps maps](https://user-images.githubusercontent.com/64419373/174825330-bc31bb18-0ded-437a-9970-a7210924b955.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I already tried to fix it but I couldn't find a way

**Comment by Bnyro** [comment]
I could just move it up a bit so that it's always higher and doesn't conflict with the miniplayer xD

**Comment by martin-desktops** [comment]
Okay, I don't think this is a bad solution
