### ISSUE TITLE
"Broken" welcome screen on first launch in small devices

### ISSUE THREAD

**Issue by ivan-gj** [libre-tube/LibreTube#5959]
### Steps to reproduce

- Open the app for the first time (clean cache and data) on a small device (like a Unihertz Jelly Star). **It is very possible that this could also affect bigger devices with augmented text size (for accessibility)**. 

### Expected behavior

Any user should be able to properly navigate the instances list on the welcome screen. 

### Actual behavior

Only a small scrollable section is available. 

![Screenshot_20240501-212217](https://github.com/libre-tube/LibreTube/assets/122645806/4ffe5251-63e4-4e27-ab3f-ee83b6261d2e)

In fact, when I encountered this error for the first time on version 0.22, it was **impossible** to select any instance. Thankfully I had my older phone, so I could generate a backup and restore it with the restore button (that is amazing that it can be done on the welcome screen, BTW, that's nice UX and I believe should not be changed).

### LibreTube version

0.23.0

### Android version

Android 13

### Other details

I believe this is very easily solvable in many different ways.

 I sadly don't have the Android skills to do it myself, but I believe that if the whole activity (I believe each "screen" is called like that) was scrollable and the list of instances was printed on the "root" itself... that would be fixed, and I don't see any downsides. 
 
 Some more alternatives would be: 
 - Just have a top bar with the LibreTube logo and name for "branding" and make everything else scrollable. 
 - Maybe divide the welcome screen into 2 activities, one for welcoming, the next one for picking the Piped instance.
 - Some fancy scroll animation where the huge logo becomes smaller and smaller as you scroll down and stays on top with "LibreTube" on the side. I don't think this one is worth it, honestly. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thanks for the detailed issue description, I really appreciate the efforts you spent into finding solutions (without using AI to generate the description, that's so much more pleasant to work with for me) :+1:

> Some fancy scroll animation where the huge logo becomes smaller and smaller as you scroll down and stays on top with "LibreTube" on the side. I don't think this one is worth it, honestly.
>
I think that this one sounds pretty interesting and fun to implement (I've already done something similar with Jetpack Compose some times, though LibreTube doesn't use Jetpack Compose unfortunately), so I'll probably see if I can make this work some time :)

**Comment by ivan-gj** [comment]
Thank you very much!! Looking forward to test this out!

**Comment by Bnyro** [comment]
You can test it from the builds here: https://github.com/libre-tube/NightlyBuilds
