### ISSUE TITLE
full screen button does not work when some videos have ended

### ISSUE THREAD

**Issue by lucamp** [libre-tube/LibreTube#596]
### Steps to reproduce

- Play [this video](https://youtu.be/ue2tiBe5UKY)
- Turn on full screen 
- Wait till the end
- Touch full screen button 

### Expected behavior

Libretube exits full screen and goes back to video page (not popup)

### Actual behavior

Nothing, full screen button does not work

### LibreTube version

0.3.1

### Android version

10

### Other details

Not every video is affected by this issue.
Do not seek forward or start playing near the end to reduce watching time, otherwise issue does not show

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I can't reproduce it although I followed your instructions :/

**Comment by laur89** [comment]
Am on Android 11, doesn't reproduce either.

**Comment by lucamp** [comment]
> I can't reproduce it although I followed your instructions :/

I reset the app deleting its data and did not change default settings just to be sure, could you please try:

- Play [this video](https://youtu.be/ue2tiBe5UKY)
- Turn on full screen
- Turn off subtitle (english subititle was turned on as default)
- Touch full screen button

now full screen button is unresponsive

Also:
as the command interface fades after few seconds, a lighter version of the top bar and navigation buttons on the side remains visible

![Screenshot_2022-06-27-00-21-35-27](https://user-images.githubusercontent.com/15078341/175835981-e8139851-d93b-4736-a952-12e3dafa4aec.jpg)
