### ISSUE TITLE
Cannot play without DASH.

### ISSUE THREAD

**Issue by nanedi** [libre-tube/LibreTube#5966]
### Steps to reproduce

Cannot play without DASH.

### Expected behavior

Can play without DASH.

### Actual behavior

Cannot play without DASH.

### LibreTube version

0.23.0

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/issues/5855
