### ISSUE TITLE
The problem of switching tracks

### ISSUE THREAD

**Issue by Jiaonikele8** [libre-tube/LibreTube#5967]
### Steps to reproduce

When I first changed the track, it doesn't work

### Expected behavior

You should switch to the selected track.

### Actual behavior

Click the required audio track.nonresponse

### LibreTube version

0.23.0

### Android version

Android14

### Other details

![Uploading IMG_20240503_203852.jpg…]()
![Uploading Screenshot_2024-05-03-20-31-58-69_54f92cd6866f5233ab0db4392b806878.jpg…]()

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Invalid issue template use.
