### ISSUE TITLE
[Typo]There is a typo in Turkish

### ISSUE THREAD

**Issue by MuhammetEminCakir** [libre-tube/LibreTube#597]
### Steps to reproduce

1. Open the app
2. Select Turkish language
3. Click to Görünüm (Appearance)
4. Select a theme

### Expected behavior

The text there should have been: "Parlak ışık"

### Actual behavior

The text there: "Parlak işık"

### LibreTube version

0.3.2

### Android version

Android 12

### Other details

![IMG_20220623_060337](https://user-images.githubusercontent.com/64583157/175199544-458ec94c-6f0f-42e5-80e5-9bd32b067aef.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please fix it on Weblate, that's not an app issue...

**Comment by Nizami20052022** [comment]
There is no need to turn a letter into a problem.

**Comment by Nizami20052022** [comment]
This word has already been changed. Please wait for the next update.
