### ISSUE TITLE
Auto-generated subtiles not shown

### ISSUE THREAD

**Issue by xn117khdsh** [libre-tube/LibreTube#5975]
### Steps to reproduce

1. Choose any video which has auto-generated subtiles
2. Choose Subtiles in the video settings
3. Choose auto-generated subtiles.

### Expected behavior

The video should show auto-generated subtiles.

### Actual behavior

No auto-generated subtiles shown.

### LibreTube version

0.23.0

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/5511
