### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Hammoudi99** [libre-tube/LibreTube#5977]
### Steps to reproduce

The app crashes when  i open a video.

### Expected behavior

It should open the video?

### Actual behavior

It doesn't open the video.

### LibreTube version

0.23.0

### Android version

 POCO X6 5G -Android 14

### Other details

Log:https://telegra.ph/Log-05-05-7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/5958
