### ISSUE TITLE
Some words that are not in the translation.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#598]
### Describe your suggested feature

![Screenshot_20220623-180214_LibreTube](https://user-images.githubusercontent.com/104249296/175318720-86df440c-7e66-48db-806c-31ef26c37f65.jpg)
![Screenshot_20220623-180136_LibreTube](https://user-images.githubusercontent.com/104249296/175318736-c591ab4f-0f49-4eab-bc30-d67fba746d6f.jpg)
![Screenshot_20220623-175911_LibreTube](https://user-images.githubusercontent.com/104249296/175318754-4fd7f14c-6a14-4a36-b13e-6ba493b6580a.jpg)
![Screenshot_20220623-175728_LibreTube](https://user-images.githubusercontent.com/104249296/175318764-fc4d16b7-8cbd-4250-8015-e7433bd470e1.jpg)
![Screenshot_20220623-175431_LibreTube](https://user-images.githubusercontent.com/104249296/175318773-50f65abe-1bf5-47ea-80ad-466cbc4730ad.jpg)
![Screenshot_20220623-175101_LibreTube](https://user-images.githubusercontent.com/104249296/175318785-9a81cd5c-aa39-40bf-be96-1c57eb7a0271.jpg)
![Screenshot_20220623-174829_LibreTube](https://user-images.githubusercontent.com/104249296/175318792-502f8613-c9d9-489e-b3a9-887a7091ecc6.jpg)

![Screenshot_20220623-174741_LibreTube](https://user-images.githubusercontent.com/104249296/175318805-7346678c-84d1-41c4-b77c-e5307f8b8d0f.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by archroid** [comment]
Unfortunately this text directly pastes from the piped api and there is no option to translate it for now. We will add the option once the api supports it. Thanks for your report!
