### ISSUE TITLE
Changing orientation changes start position of the video

### ISSUE THREAD

**Issue by DanielProg39** [libre-tube/LibreTube#5985]
### Steps to reproduce

1. Open the video
2. Wait 1-3 seconds for it to play
3. Rotate the screen
4. When a video starts playing, tap two times on the left side of player to make it play from the beginning.

### Expected behavior

Video should play from the beginning.

### Actual behavior

Video plays from the point in which the screen was rotated.

### LibreTube version

LibreTube Debug, commit fda352e

### Android version

Android 13

### Other details

The issue persists at least since 51cc630.

Here's the recording, watch with the sound on (you can also see the blank space instead of the bottom panel, which is a bug that as far as I can remember, has its own issue opened, correct me if I'm wrong):

https://github.com/libre-tube/LibreTube/assets/63293432/acbfea16-d3b8-4381-9dc6-95fb5d4e215d

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Should be fixed with https://github.com/libre-tube/LibreTube/pull/6428
