### ISSUE TITLE
Weird player behavior in landscape mode

### ISSUE THREAD

**Issue by DanielProg39** [libre-tube/LibreTube#5986]
### Steps to reproduce

1. Enable autorotation for the app interface and the player
2. When holding phone horizontally, open a video

### Expected behavior

Video should open in full-screen.

### Actual behavior

Video opens in strange layout that stays the same in any orientation.

### LibreTube version

LibreTube Debug, commit 096ab60

### Android version

Android 13

### Other details

Recording:

https://github.com/libre-tube/LibreTube/assets/63293432/8c67c964-947a-466e-af1d-67d0e411a8e6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
> Video opens in strange layout that stays the same in any orientation.
>
That's not a 'strange layout', it's the landscape layout of the player page :)

Though it shouldn't stay when rotating the phone.

**Comment by DanielProg39** [comment]
Autorotation for player disables the button for entering full-screen mode. I think I get it - it's not straight away bug (however, layout not changing for vertical orientation is a bug), but it seems that these two settings break each other. I think the perfect solution would be that when the UI is horizontal and auto full screen is enabled, the video should open in full screen mode but have a button to exit it. And that button should only be missing when the UI layout is strictly vertical.
