### ISSUE TITLE
Improve Preloading 

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#599]
### Describe your suggested feature

If we can add a number less than 50, the videos will open faster.When you reduce this number, the video opens faster.
![Screenshot_20220623-190827_LibreTube](https://user-images.githubusercontent.com/104249296/175333563-ee60660c-9071-4914-b7a9-3dfb969e67ed.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Archeix7** [comment]
As far as I understand, this is done for a reason, because at a low network speed, the video / sound will be constantly interrupted and it is impossible to listen

**Comment by Bnyro** [comment]
It's the buffering goal (=maximum buffer), not the minimum buffer. Making it smaller wouldn't improve the video loading time.
