### ISSUE TITLE
Features that needs to be added immediately 

### ISSUE THREAD

**Issue by Debojit-0** [libre-tube/LibreTube#60]
1- background music play with controls 
2- change the aspect ratio to fill the screen of your device screen size irrespective of the videos aspect ratio
by pinch to zoom in and zoom out 
3- gesture control for volume increase and decrease and increase the brightness
4- micro g support to use Google account to login.
Ignore point 4 as i dint know Google would collect data 

5- ability to stream 4k hdr videos just not 4k
6- addition of explore tab top of the home page
7- Having a bell icon at top to see all the notifications
8- preview view or playback of the thumbnail photo
Just like native youtube.
9- increase the resolution of thumb nails or click bait photo.
Note - take your time to integrate all these features but do it r8 with minimal bugs.

10 - addition of chapters by time stamp in each videos.
11 - playback preview of the videos like the current youtube latest version as of March 20th 2022

**Comment by rimthekid** [comment]
I'll add some thing's I'm working on rn too
8 - open youtube links in the app
9 - complete library and playlist creation
10 - import subscription from youtube

**Comment by MartinMob1** [comment]
Are you planning on adding the ability to comment on videos?

**Comment by Debojit-0** [comment]
> I'll add some thing's I'm working on rn too 8 - open youtube links in the app 9 - complete library and playlist creation 10 - import subscription from youtube

**Comment by Debojit-0** [comment]
Donot import the subscription or data from YouTube.
That's tedious insted integrate micros g and that will get the work done .

**Comment by FireMasterK** [comment]
> ability to stream 4k hdr videos just not 4k

This is something that I need to add from my side, I'll add this soon!

**Comment by IceDBorn** [comment]
@Debojit-0 They won't add google login, the whole point of this project is to use Piped as the backend and prevent Google from stealing your data. This project is not a Vanced clone and you should stop asking the devs about turning it into one.

**Comment by Debojit-0** [comment]
@IceDBorn
Got it 

But what about my other listed features those are very important  i feel to make the experience better.

**Comment by Debojit-0** [comment]
> @Debojit-0 They won't add google login, the whole point of this project is to use Piped as the backend and prevent Google from stealing your data. This project is not a Vanced clone and you should stop asking the devs about turning it into one.

@IceDBorn
Got it 

But what about my other listed features those are very important  i feel to make the experience better.

**Comment by drishal** [comment]
> @Debojit-0 They won't add google login, the whole point of this project is to use Piped as the backend and prevent Google from stealing your data. This project is not a Vanced clone and you should stop asking the devs about turning it into one.

Maybe just keep microg entirely optional, it becomes usful if one wants to. for eg comment on the video 

btw another suggestion: LibreTube music maybe?

**Comment by Killercat103** [comment]
> > @Debojit-0 They won't add google login, the whole point of this project is to use Piped as the backend and prevent Google from stealing your data. This project is not a Vanced clone and you should stop asking the devs about turning it into one.
> 
> Maybe just keep microg entirely optional, it becomes usful if one wants to. for eg comment on the video
> 
> btw another suggestion: LibreTube music maybe?

Second this, while a microG account isn't great for privacy, I believe Libretube with a MicroG account is better than the official app with a Google Account.
Might make it easier to adapt to alternative open-source apps too.

**Comment by Bnyro** [comment]
MicroG is hard, we won't add it for now

**Comment by Bnyro** [comment]
All open parts of its are dupes of other open issues

**Comment by lucamp** [comment]
> MicroG is hard, we won't add it for now

As you said "for now", please consider "never".
Piped is built on top of privacy, and do not use your time to implement something that could be broke in the feature.
Better to find a way to sync with a piped instance

**Comment by Bnyro** [comment]
@lucamp "For now" should mean "never", you're right, we will never add support for Google login (as you can see in Roadmap.md)
