### ISSUE TITLE
Consistent crash on video change

### ISSUE THREAD

**Issue by alejandro-alzate** [libre-tube/LibreTube#6004]
### Steps to reproduce

Open a video,
Choose another video

### Expected behavior

normal playback

### Actual behavior

Consistent chrash just after the second video is choosen

### LibreTube version

0.23.1

### Android version

13

### Other details

The crash consistenly says the following traceback maybe changing the source:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.postDelayed(java.lang.Runnable, long)' on a null object reference
	at com.github.libretube.ui.views.OnlinePlayerView.syncQueueButtons(SourceFile:95)
	at androidx.core.app.ActivityCompat$$ExternalSyntheticLambda0.run(SourceFile:86)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
    
```

First video will always work, second will always crash,
Playlists (when using next and previous) doesn't seem affected. but they'll crash if you click a video, but autoplay also will continue normally.
All crashes can occur in any video feed tested so far including choosing the same video twice:
Share a link to libretube (Play video now)
Highlights
Search
Recommended (Similar videos besides the playing one)
Subscriptions feed
Downloads are not affected.
Share a link to libretube (Add to playlist) Won't crash as well.

# Updates
Closing the playing video will also crash,
my suspect now it's the action of closing the video, not creating the next video object.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by alejandro-alzate** [comment]
God dammit the issue #6003 its the same.
i thought that one was specific to other device.

**Comment by aryaoffixial** [comment]
Keep this open. I'm closing mine. And referring this one. You described very well.

**Comment by alejandro-alzate** [comment]
Oh thanks, i generally get "you explain this well" consistenly, like when i share knowledge of the few things i know, aparently is a trait of mine 🥺

**Comment by Unaiperezdiaz** [comment]
In that issue I have recorded the screen to reproduce it.
Nothing else. 😶‍🌫️

**Comment by alejandro-alzate** [comment]
You know sometimes a image tells more than a thousand words, you can comment your video here.

**Comment by Unaiperezdiaz** [comment]
https://github.com/libre-tube/LibreTube/assets/49728036/4ae26802-e80a-4f4c-b41a-0754c8a6b2e3

**Comment by alejandro-alzate** [comment]
i noticed yours almost makes the ui change mine on the frame i touch the next video let me tell ya the app is GONE.

**Comment by akano12** [comment]
Can't reproduce on my side, what's your device arch?

**Comment by Unaiperezdiaz** [comment]
> Can't reproduce on my side, what's your device arch? 

Realme GT master edition with Android 13

![Screenshot_2024-05-08-19-29-41-36_54f92cd6866f5233ab0db4392b806878.jpg](https://github.com/libre-tube/LibreTube/assets/49728036/af1717ab-00d0-484a-ac7a-74357c4ce6b2)

**Comment by Bnyro** [comment]
I've created a hotfix release https://github.com/libre-tube/LibreTube/releases/tag/v0.23.2 and marked the v0.23.1 release as a pre-release.

Thanks for finding that issue so early before more users will be affected.

**Comment by alejandro-alzate** [comment]
> > Can't reproduce on my side, what's your device arch?
> 
> Realme GT master edition with Android 13
> 
> ![Screenshot_2024-05-08-19-29-41-36_54f92cd6866f5233ab0db4392b806878.jpg](https://private-user-images.githubusercontent.com/49728036/328983177-af1717ab-00d0-484a-ac7a-74357c4ce6b2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxOTkxMTEsIm5iZiI6MTcxNTE5ODgxMSwicGF0aCI6Ii80OTcyODAzNi8zMjg5ODMxNzctYWYxNzE3YWItMDBkMC00ODRhLWFjN2EtNzQzNTdjNGNlNmIyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDIwMDY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMjQxM2MyYTQ5MTcxODMxOTgwMzM3YzI0ZjMwNzAyNmE4YmEzZWEzOWE5MzlkYWQ5ODlkMWEwMzRjNjAwZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H_3TB9QpdqlPoPzZQ-epz6ChmKUWUQDSkpJEePilZ6A)

Manofacturer: samsung
Model: SM-G960F
SDK: 33
Board: exynos9810
OS: Android 13
Arch: arm64-v8a
Product: lineage_starlte

Also ok bnyro i'm downloading it, what produced the issue btw?

**Comment by alejandro-alzate** [comment]
Also shout out to obtanium that makes the chore of updating individual apps less painful

**Comment by Bnyro** [comment]
> Also ok bnyro i'm downloading it, what produced the issue btw?
>
The buttons to player the next / previous video.

Settings -> Player -> Skip buttons -> Enable

I hadn't tested that before the release because I personally don't use these buttons.

**Comment by alejandro-alzate** [comment]
Oh, interesting.
Exists any tool for testing that?
like when you test a library robustness by just yelling at them garbage.
There's any equivalent tool for android apps?

> I personally don't use these buttons.

You may hate me for the following: but remember our beef of me begging to bring the pip button back?
https://xkcd.com/1172/

I mean i understand clearly the mantainability concerns but my god thanks you brought it back.
As you might guess my hot take is there are no perfect piece of sofware and something is going slip through the cracks no matter the attack area, there's always that one bug that slips
i'm not saying test every button since that is very annoying (that is why i'm curious if is there are any tool to improve your workflow in that space) my take is we are here to help with that type of bugs. in my case since i'm not a kotlin/java chad like you that's my small contribution to your project since it provides value to me.

So getting my train of thought back in track i hope this issue didn't disturbed your day.

And while i was writing this i was searching something to help with and i found what apparently are the so called fuzzers but for the android gui.
https://developer.android.com/training/testing/espresso

There are some possible outcomes here:
- You are aware and you are actively using this already.
- You are unaware or your never tried it before.
- Or this is not the correct tool to automating testing. like driving a nail with a knife.

Either way, I hope this suggestion benefits your workflow, or at the very least maintains it like before. With that said, have a wonderful night, and I'm signing off.

**Comment by Bnyro** [comment]
I'm aware of Espresso, but I don't want to spend time using it.

I'm currently the only maintainer of the project and my time is limited, so I rather focus on things that I think would be useful.

Making Espresso work would cost a lot of time - which I don't have.

**Comment by alejandro-alzate** [comment]
well at least we are here to break it in funny ways still, so you can focus only in the spicy stuff.
