### ISSUE TITLE
Video autorepeat without autoplay enabled

### ISSUE THREAD

**Issue by 0xrxL** [libre-tube/LibreTube#6007]
### Describe your suggested feature

There's a reason to force autoplay enabled to make autorepeat working? If I want to stop the reproduction after the video end, I need to disable autoplay and autorepeating instead just disable autorepeating.

Make an indipendent (from autoplay) autorepeating option will reduce the user interactions.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by 0xrxL** [comment]
@Bnyro 

Eventually this feature could be implemented just for current video instead of an entire playlist.

**Comment by Bnyro** [comment]
Don't ping me, as explained in the Code of Conduct. First warning.
