### ISSUE TITLE
Maximize preview on search list

### ISSUE THREAD

**Issue by 0xrxL** [libre-tube/LibreTube#6009]
### Describe your suggested feature

![Screenshot_20240509_032808_LibreTube](https://github.com/libre-tube/LibreTube/assets/127248639/c23a9daf-138c-402f-ac07-e1b90e6ebb65)
![Screenshot_20240509_032819_LibreTube](https://github.com/libre-tube/LibreTube/assets/127248639/f642013f-3655-4503-a376-54aed2f0fd45)

As on the trending video list, it would be useful to keep the same layout on the searched video list as well, so as to improve visibility.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not planned.
