### ISSUE TITLE
 Video playback error when the screen is off.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#601]
### Steps to reproduce

1.Open the program
2.Play the video
3.Turn off the screen.

4.The video is currently playing in the background
5. After about 2 minutes, the video stops and an error occurs.

### Expected behavior

The video must be played without hindrance.

### Actual behavior

The video stops and fails.

### LibreTube version

0.3.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Try to longpress the video and use background play. Should be better.
