### ISSUE TITLE
Use NewPipe Extractor to play restricted videos

### ISSUE THREAD

**Issue by 0xrxL** [libre-tube/LibreTube#6011]
### Describe your suggested feature

I noticed that, despite the blurred preview, the last NewPipe version can play restricted 18+ videos (if the dedicated option from settings is enabled).

I read that LibreTube is based on NewPipe Extractor, so could be theoretically possible to add this feature on it too (when Piped proxy is disabled).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Using NewPipe Extractor directly is out of scope, as already said 100 times before. LibreTube is an android client for Piped.
