### ISSUE TITLE
Auto audio/video switching

### ISSUE THREAD

**Issue by 0xrxL** [libre-tube/LibreTube#6012]
### Describe your suggested feature

Add an experimental feature to switch from video to audio player and viceversa, once LibreTube run in background or foreground.

This is (imho) a good temporary solution, until someone doesn't find a definitive fix to keep the app in background.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Already discussed in https://github.com/libre-tube/LibreTube/issues/5141
