### ISSUE TITLE
Constant source errors

### ISSUE THREAD

**Issue by NoxStellans** [libre-tube/LibreTube#6016]
### Steps to reproduce

1. Open the app.
2. Choose any video.

### Expected behavior

The video should play.

### Actual behavior

I get a source error every single time. This has been happening for weeks now. LibreTube's always been a bit iffy with source errors, in my experience, but now they're constant.

### LibreTube version

0.23.2

### Android version

Android 14

### Other details

I've tried logging in and out of Piped and changing instances, but nothing seems to work. I don't know why none of the videos will play, I'm sorry.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/issues/5855
