### ISSUE TITLE
Negative one subscriber count shown when clicking on channel

### ISSUE THREAD

**Issue by Ich-kann-lesen** [libre-tube/LibreTube#6019]
### Steps to reproduce

1. Click on a channel to view it's page
2. Sometimes you have to refresh

### Expected behavior

Show actual subscriber count

### Actual behavior

"-1"

### LibreTube version

0.22.2 from F-Droid Repo

### Android version

14

### Other details

This only happens for some channels, I don't know why it's inconsistent.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's a NewPipe extractor issue waiting for https://github.com/TeamNewPipe/NewPipeExtractor/pull/1170.
