### ISSUE TITLE
Error: unexpected char when starting app, makes it unusable

### ISSUE THREAD

**Issue by mooreye** [libre-tube/LibreTube#6025]
### Steps to reproduce

As soon as I changed region to United States (it is not my default system one) the attached error appears and makes the app shutdown immediately. The only way to get it working seems to be to delete all app data from system settings.

It appears one of the Trending videos in the US region contains some funny unicode character. So it's likely the issue is temporary (and hard to reproduce...), but may reappear anytime.

### Expected behavior

App loads.

### Actual behavior

App crashes.

### LibreTube version

0.23.0

### Android version

14 (GrapheneOS)

### Other details

![bug](https://github.com/libre-tube/LibreTube/assets/93423596/d3be4b5a-e767-4e7e-881e-89176d374b6f)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by mooreye** [comment]
It appears to be this one: https://youtu.be/aoKL75ns_8c

**Comment by Bnyro** [comment]
Please update to the latest version, this has already been fixed a week ago: https://github.com/libre-tube/LibreTube/issues/5943
