### ISSUE TITLE
Random Timestamp Thumbnail Option for Non-Dearrow Videos

### ISSUE THREAD

**Issue by thequantumcog** [libre-tube/LibreTube#6027]
### Describe your suggested feature

Dearrow (user-submited) thumbnails are not available for majority of videos. Is there a way to display a random frame of video as a thumbnail?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
See https://github.com/libre-tube/LibreTube/issues/4455#issuecomment-1685207875.
