### ISSUE TITLE
Increase DeArrow size

### ISSUE THREAD

**Issue by 0xrxL** [libre-tube/LibreTube#6039]
### Describe your suggested feature

With the new year - as default behaviour for its YouTube client - Google removed the seeking preview thumbnail and moved its content to the entire video player.

This could be an useful way to increase the preview visibility (because the video player it's more big than a small thumbnail).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
No plans for that currently.

Please do NOT create more than one feature request per week - I'm doing all this in my free time and I'm NOT at all excited about seeing new issues / duplicates by the same person each time. If you want to contribute something via pull requests, sure do so, but don't expect me to look into any of your suggestions that you are spamming.

If you continue, I'll consider banning you, just for my mental health.

**Comment by 0xrxL** [comment]
> No plans for that currently.
> 
> Please do NOT create more than one feature request per week - I'm doing all this in my free time and I'm NOT at all excited about seeing new issues / duplicates by the same person each time. If you want to contribute something via pull requests, sure do so, but don't expect me to look into any of your suggestions that you are spamming.
> 
> If you continue, I'll consider banning you, just for my mental health.

I understand your effort and appreciate it (especially for the links related to already opened requests by other users), however I don't understand the point of such an "extreme" solution as the ban, when nobody (not even me) forced you to implement anything of newer by spamming complaints here and there or reading 10/20 requests all together in a row.

I mean: posting 10 requests and answer "not planned" to 1 of it per week, instead of posting 1 of it per week and receiving the same above answer, doesn't make a so huge difference to deserve a ban (imho).
