### ISSUE TITLE
Undo seeking attempt

### ISSUE THREAD

**Issue by 0xrxL** [libre-tube/LibreTube#6040]
### Describe your suggested feature

Another useful solution adopted in the stock YouTube client is the seeking cancellation, once the seeking swipe reach the (previous) point from which the seeking is started.

This also prevent a re-buffer.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not planned. You can cancel the seeking by swiping up top the screen and releasing the screen after dragging and holding.
