### ISSUE TITLE
Skip to previous/next video history

### ISSUE THREAD

**Issue by 0xrxL** [libre-tube/LibreTube#6042]
### Describe your suggested feature

Currently there's no way to skip to a previous/next video, based on the history of current player instance.

For example: I might want to watch a new video from related list, without loose the previous video (reachable by tapping on the "skip to previous" button of the player, which will remember all the history of previous videos opened from related videos list)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Long press the related video and choose `play next`.
