### ISSUE TITLE
Icon on homepage header

### ISSUE THREAD

**Issue by 0xrxL** [libre-tube/LibreTube#6043]
### Describe your suggested feature

To improve the app design, the app icon could be added on the left side of the app name, in the homepage header.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
No plans to revamp the current design.
