### ISSUE TITLE
Audio player for downloaded videos

### ISSUE THREAD

**Issue by CodeDoctorDE** [libre-tube/LibreTube#6047]
### Describe your suggested feature

Currently there is a black video when downloading without video.
It would be better if it starts the audio player instead.
Additionally a switch between audio player and video player isn't there for downloaded media.

### Other details

Thanks for this awesome app. It looks beautiful and I use it everyday!

I'm currently using 0.23.1 since fdroid didn't update yet.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
>Currently there is a black video when downloading without video.
> It would be better if it starts the audio player instead.
>
Long press the video in the downloads that you want to play and choose `Play in background`. That does the job :)

**Comment by CodeDoctorDE** [comment]
But this isnt the audioplayer
