### ISSUE TITLE
Topic/Audio Channels won't play

### ISSUE THREAD

**Issue by SecularSteve** [libre-tube/LibreTube#605]
### Steps to reproduce

1. Open a YouTube Audio Link.
(example: https://piped.kavin.rocks/watch?v=j_nEdStgew0)
2. Attempt to Play.

### Expected behavior

Music/Audio to play when the play button is pressed.

### Actual behavior

![Screenshot_20220624-222437~2](https://user-images.githubusercontent.com/33793273/175662731-1b1b6593-cfb0-41c3-8400-8606e6915f03.png)

It remains black, and won't play, ever. Even after trying various settings.

### LibreTube version

0.3.2

### Android version

Android 12

### Other details

Same/similar issue on Piped. Even with the "Audio Only" mode.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Then it's apparently not a LibreTube issue since we just use their API, you should probably open an issue on the Piped repo ;)

**Comment by SecularSteve** [comment]
Just passed it on.
https://github.com/TeamPiped/Piped/issues/1150
I also realised that this doesn't happen on Invidious, or NewPipe.

**Comment by Bnyro** [comment]
Okay, great, ty :)
Then I'll just close it here for now :D
