### ISSUE TITLE
Media notification playback controls not functioning.

### ISSUE THREAD

**Issue by Nihil901** [libre-tube/LibreTube#6050]
### Steps to reproduce

1. Open the LibreTube app on an Android device.
2. Start playing a video.
3. Minimize the app or switch to another app.
4. Attempt to use the playback controls (play/pause, skip, seek) in the media notification.
5. The controls do not respond or have any effect on the video/audio playback.

### Expected behavior

The playback controls in the media notification should function as expected, allowing to pause/resume, skip to the next/previous video, and seek through the video timeline.

### Actual behavior

the media notification controls are not functional. When I minimize the app and try to use the play/pause, skip controls in the notification, they do not respond or control the video/audio playback. 

### LibreTube version

0.23.2

### Android version

Android 10

### Other details

Note: ignore the lack of audio it's just a recording problem. 

Uploading Record_2024-05-17-17-30-40_54f92cd6866f5233ab0db4392b806878.mp4…

 
As you can see I can only slide through the video timeline, the rest is not functional.. 

Please let me know if you need any additional information to help fixing the issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Nihil901** [comment]
Sorry my bad i didn't upload this correctly previously, here is the actual demonstration:

https://github.com/libre-tube/LibreTube/assets/141766629/e6cd583c-250c-4667-a184-c60a20489f45

**Comment by Bnyro** [comment]
Can you please try re-installing the app?

**Comment by Bnyro** [comment]
see https://github.com/libre-tube/LibreTube/issues/6078#issuecomment-2132278622
