### ISSUE TITLE
Videos will not stream

### ISSUE THREAD

**Issue by fiendUnpleasant** [libre-tube/LibreTube#6051]
### Steps to reproduce

When you open the app and tap on a video it will go to the video page, start the circle animation like it is loading, and then stop after a handful of seconds. 

Videos do play when when one downloads the video so there is a work around but it's not the optimal way to do it.

### Expected behavior

Video should play when clicked on

### Actual behavior

Video stops loading after a handful of seconds

### LibreTube version

0.23.1

### Android version

Android 12

### Other details

Installed from fdroid

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/5855
