### ISSUE TITLE
Recommendation for Shorts. 

### ISSUE THREAD

**Issue by SkyH85** [libre-tube/LibreTube#6052]
### Describe your suggested feature

Hello, sir. I wonder if you can bring such a feature to settings that allows only shorts videos to come up the next time we click the next video button while watching shorts from the shorts section on a channel?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not possible, it's not supported by Piped.
