### ISSUE TITLE
Multiple Features Suggestions

### ISSUE THREAD

**Issue by FarisArabia** [libre-tube/LibreTube#6057]
### Describe your suggested feature

1. **Hide Video Options Titles** as in make it optional to hide the text here above the orange line
![Screenshot_20240519_012545](https://github.com/libre-tube/LibreTube/assets/113720028/77ee7a29-fd6f-43ed-a69d-e1f56d79c490)
2. another one is make an option to **Automatically Mark Video as Watched** if a percentage of it like 90% is watched
3. **Move the Subscribe Button below the channel title** because... Yeah
![Screenshot_20240519_022111](https://github.com/libre-tube/LibreTube/assets/113720028/138d5de1-25d0-4e12-b716-f29397bb5291)
4. **Sort Videos by Oldest/Popularity** Option just like YouTube does
5. **Search Videos in Watch History** because it's good when you want to recall videos
6. **Featured Music** Category in the Home Tab

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
4,6. not supported by Piped.
2. That's already the case
3. That's not planned, see https://github.com/libre-tube/LibreTube/discussions/5247.
5. I don't think that's necessary, if you want to seqrch for a video just use the normal search feature...
3. I think that we need to do some UI improvements there, yes, but I don't think that your suggestion is the right way.

Anyways, please open one issue per suggestion, and not one issue with 6 of them ...

3. can be talked about in a discussion imo, anything else doesn't seem to be reasonable or is not possible
