### ISSUE TITLE
Video resolution is not the same when turning the phone to landscape mode

### ISSUE THREAD

**Issue by Tunsinasro** [libre-tube/LibreTube#6064]
### Steps to reproduce

1. Play a video and chose a resolution other than the default one
2. Turn the phone to landscape mode

### Expected behavior

The resolution in the landscape mode should be the same as in portrait mode

### Actual behavior

The resolution has reverted to the original one

### LibreTube version

0.23.2

### Android version

Android 13

### Other details

https://github.com/libre-tube/LibreTube/assets/147873384/627d829d-cf70-4f3a-892b-bca44b297781

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Settings -> Audio and video -> Wifi -> No-Fullscreen resolution -> Set to "Same as fullscreen"

**Comment by Tunsinasro** [comment]
This works, thank you
