### ISSUE TITLE
Inconsistent Android status bar label color

### ISSUE THREAD

**Issue by Ehab-d** [libre-tube/LibreTube#6072]
### Steps to reproduce

1. Switch to the Light/Dark mode in Android
2. Switch to the Dark/Light mode in LibreTube

### Expected behavior

To have the status bar just like it was in `0.22.2`:
![LibreTube_0 22 2](https://github.com/libre-tube/LibreTube/assets/129071698/99927183-5729-40b7-9a00-4d31c6617c73)

### Actual behavior

This is related to issue #5970 / fix #5978.

The notification bar follows the LibreTube app theme -which is actually fixed-, but the status bar text and labels are black, making them almost unseeable.

> LibreTube_0.23.2 – after the fix

![LibreTube_0 23 2](https://github.com/libre-tube/LibreTube/assets/129071698/b15a7b88-77a0-4021-b992-bdbab8963c0e)

> LibreTube_0.23.0 – before the fix

![LibreTube_0 23 0](https://github.com/libre-tube/LibreTube/assets/129071698/706f3985-3865-4b34-855b-bebc6ff421d6)

### LibreTube version

0.23.0 to 0.23.2

### Android version

Android 10

### Other details

- The issue did not exist in version `0.22.2`.
- The settings page does not have this issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can you please test after https://github.com/libre-tube/LibreTube/pull/6080?

**Comment by Ehab-d** [comment]
certainly. I have tested most of the possible cases, and I can confirm that the problem has been solved. 🚀
However, I wanted to point out a behavior you might want to know about...
When going into full screen mode, the status bar quickly turns light before returning to dark again.

> LibreTube 0.23.3 Debug

https://github.com/libre-tube/LibreTube/assets/129071698/75ced67d-28b5-4f63-a543-5b4d403fc22e

And that was not present in LibreTube 0.22.2.

> LibreTube 0.22.2

https://github.com/libre-tube/LibreTube/assets/129071698/7db536a6-cef7-4c9d-bb58-364f09f026d6

Of course, this "completely" only happens when Android is in light mode & LibreTube in dark mode.

This may not be a problem.. but I thought you might want to know.

**Comment by Bnyro** [comment]
> When exiting full screen mode, the status bar quickly turns light before returning to dark again.
>
That's indeed not that nice, but I don't think that we can fix this on the application side. We don't modify that color when you leave fullscreen, we only change the text color of the status bar.

So this certainly looks like an Android bug unfortunately.
