### ISSUE TITLE
Add Functionality in LibreTube

### ISSUE THREAD

**Issue by 0x3q8e** [libre-tube/LibreTube#6075]
### Describe your suggested feature

Add sort settings in video search

Add here’s video-sound translator that could be included. Source: https://github.com/ilyhalight/voice-over-translation

Add hidding unnecessary channels in search, something like a blacklist.

Here are the sources: https://github.com/amitbl/blocktube

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Both were already rejected multiple times, just browse the closes issues for the reasoning...
