### ISSUE TITLE
Some channels does not show channel banner, profile, subscriber count

### ISSUE THREAD

**Issue by Eliya-Manoj** [libre-tube/LibreTube#6076]
### Steps to reproduce

1. open Libretube
2. Open some channels
3. Some channels shows issues

![photo_2024-05-25_11-42-10](https://github.com/libre-tube/LibreTube/assets/90308888/c82815ef-86d5-4841-90e4-575085d10e56)
![photo_2024-05-25_11-42-09](https://github.com/libre-tube/LibreTube/assets/90308888/26c8436d-b772-494f-b2e7-02d501984bd0)

### Expected behavior

Shows channel banner, Subscriber count, Channel profile picture

### Actual behavior

Does not show real subscriber count, Profile picture and banner image

### LibreTube version

0.23.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/TeamNewPipe/NewPipeExtractor/pull/1170
