### ISSUE TITLE
Option to hide live streams in feed 

### ISSUE THREAD

**Issue by flexagoon** [libre-tube/LibreTube#6077]
### Describe your suggested feature

Half of my subscription feed are livestreams, I'm not interested in them and I'd like to hide them in my feed and only see actual videos.

I know there is a filter in the feed which lets you disable livestreams, but it doesn't work fully, since I still see livestream VODs.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
If the livestream isn't filtered currently, that's due to an API limitation (the information from Piped we get doesn't tell us it's a livestream). Thus not possible, at least for now.

**Comment by flexagoon** [comment]
@Bnyro they are listed on the "channel" page in a separate "livestreams" tab, so I assume there is a way to distinguish them from regular videos

**Comment by Bnyro** [comment]
Warning due to pinging me, that's against our code of conduct.

And no, the way Piped works, there is no way to distinguish it. There's an issue about it at the Piped repo already...
