### ISSUE TITLE
Skip back button skips forward in picture-in-picture mode

### ISSUE THREAD

**Issue by omentic** [libre-tube/LibreTube#6079]
### Steps to reproduce

1. Play a video in picture-in-picture mode.
2. Press the skip back button.

### Expected behavior

The video should skip back ~10 seconds.

### Actual behavior

The video skips forward. This appears to be reproducible.

### LibreTube version

0.23.2

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
see https://github.com/libre-tube/LibreTube/issues/6078#issuecomment-2132278622
