### ISSUE TITLE
fix certain videos timestamps not showing in chapters list

### ISSUE THREAD

**Issue by pokegamer5547** [libre-tube/LibreTube#6087]
### Describe your suggested feature

Certain videos timestamps like [this one](https://piped.video/watch?v=xjUqYHyOJPM) for some reason dont count as chapters in both libretube nor pipes itself. Tho a lot of old videos timestamps dont work due to it.

It would be great if we could have support for these too.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
If it doesn't work at Piped either, it's probay a NewPipe Extractor issue.
