### ISSUE TITLE
VideoPlayer UI element error

### ISSUE THREAD

**Issue by Super12138** [libre-tube/LibreTube#609]
### Steps to reproduce

1. Open **any video**
2. Then there will be this problem, and of course, the problem of program crash will also appear together.
Like this photo:
![Bug](https://user-images.githubusercontent.com/70494801/175759868-04f48468-4a1d-4707-bc1e-6510386a8652.jpg)

### Expected behavior

You'll see the video player buttons show up ahead of time, and the program will become unresponsive.

### Actual behavior

You also probably won't see this error, but the program will crash.

### LibreTube version

0.3.2

### Android version

Android10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Are you using 0.3.2 from releases or a CI build?
