### ISSUE TITLE
Option to disable proxy for downloads only

### ISSUE THREAD

**Issue by aAsm321** [libre-tube/LibreTube#6091]
### Describe your suggested feature

When toggled on, the app should directly download from YouTube servers instead of a proxy, which should result in much faster downloads. However, you should still maintain the perks of using a proxy when streaming content.

### Other details

I think the convenience of fast downloads is very appealing, considering how slow downloading through the proxy is. This is the reason I choose to disable proxy inspite of the privacy risks, especially when I download podcasts on regular basis. It would be awesome to download it in a minute instead of 10 minutes without sacrificing much privacy.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
> without sacrificing much privacy
>
You're downloading stuff from YouTube without a proxy - so how does this not `sacrifice much privacy`. I'm not really convinced by such an option due to the fact that the Piped instance and proxy settings are already hard enough to understand for new users, and the settings interface already has rather too many than too few settings.

**Comment by aAsm321** [comment]
Not the privacy expert, but it intuitively makes sense that revealing your IP once to download a video is certainly better than revealing it all the time. Either way, I would still rather have a much faster downloading speeds.

**Comment by Bnyro** [comment]
Sorry, no plans for that at the moment.
