### ISSUE TITLE
App loading only subscriptions videos newer than a month

### ISSUE THREAD

**Issue by Lppsoeht** [libre-tube/LibreTube#6098]
### Steps to reproduce

1. Open app
2. Go to subscriptions section
3. Swipe to the oldest video

### Expected behavior

Subscriptions videos should keep loading and the user should be able to see much older videos.

### Actual behavior

Subscriptions load until one month

### LibreTube version

0.23.2

### Android version

14

### Other details

I don't know if it's related to the piped instance or it's just app design.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by aAsm321** [comment]
Agreed, it's easy to run out of videos in feed and have to resort to check old videos of each channel instead. Not really convenient.

**Comment by Bnyro** [comment]
That depends on the value set at the Piped backend at https://github.com/TeamPiped/Piped-Backend/blob/master/config.properties#L57. If you run your own instance, you can set it to larger values, or you can ask the person maintaining the instance you use to increase that limit.

**Comment by Bnyro** [comment]
> Do you know a piped instance with higher limit?
>
No, unfortunately not.
