### ISSUE TITLE
Material You Dynamic Theme does not work

### ISSUE THREAD

**Issue by PhilippKosarev** [libre-tube/LibreTube#6099]
### Steps to reproduce

Select the Material You option in accents.

### Expected behavior

The app should follow Material You colours.

### Actual behavior

It uses the default blue accents.

### LibreTube version

v0.23.2

### Android version

14

### Other details

OneUI version: 6.0
SDK: 34

Most other apps on this phone have no issues following the Material You colour scheme.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by technology-maen** [comment]
I can reproduce

**Comment by PhilippKosarev** [comment]
Looks like it's a OneUI bug. It's been discussed further [here](https://github.com/Malopieds/InnerTune/issues/256).
