### ISSUE TITLE
Auto switching videos in a playlist

### ISSUE THREAD

**Issue by KSXGitHub** [libre-tube/LibreTube#610]
### Describe your suggested feature

Open a playlist, play a video in the playlist, after the video end, it should automatically play the next video in the playlist.

Ideally, there should be a configuration open that let the user choose to disable/enable this feature:
* Always autoplay.
* Never autoplay.
* Ask every time user open a playlist.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by joshatt** [comment]
yes, pleeese add this enhancement!
