### ISSUE TITLE
is it possible to integrate the instances that Tubular/newpipe use to libretube

### ISSUE THREAD

**Issue by inolie** [libre-tube/LibreTube#6112]
### Describe your suggested feature

hello, i love the libretube UI but the instances barely work. when I turned off the proxy and use api from youtube directly it works sometimes but still not always (all the streaming will stop after a couple of minutes). So 99% of the time, no matter what instances I choose, I can only see the thumbnail but the video is black and never gets played. At the same time, Tubular/newpipe works smoothly on my phone/internet but the UI is difficult to use. I wonder is it possible to integrate the instances that Tubular/newpipe use to libretube? Thank you.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by towfikomar** [comment]
This is the reason why i have to keep going back to newpipe.

**Comment by Bnyro** [comment]
Tubular/newpipe don't use any third party instances, they use YouTube's API directly which is out of scope for LibreTube.
