### ISSUE TITLE
SponsorBlock for Audio player

### ISSUE THREAD

**Issue by ngminhthanh** [libre-tube/LibreTube#6115]
### Describe your suggested feature

Introduce a SponsorBlock feature in the audio player. This feature would be similar to the existing SponsorBlock feature in video players, but optimized for the audio player since it uses less data.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The audio player already has integrated SponsorBlock, it's skipping segments if you play in the background and SponsorBlock is enabled (you can test it with TheLinuxExperiment videos for example).
