### ISSUE TITLE
360p and 720p quality is shown twice.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#612]
### Describe your suggested feature

![Screenshot_20220625-152842_LibreTube](https://user-images.githubusercontent.com/104249296/175772523-972a073f-600c-4ed7-bc5c-d80988e6e201.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Api issue
