### ISSUE TITLE
F-Droid build is outdated

### ISSUE THREAD

**Issue by CodeDoctorDE** [libre-tube/LibreTube#6128]
### Steps to reproduce

The latest version is 0.23.1 on fdroid.

### Expected behavior

The latest 0.23.2 should be there

### Actual behavior

It isnt there.

### LibreTube version

0.23.1

### Android version

One Ui 6.1

### Other details

I dont want to switch to izzyondroid because i want to keep my offline videos

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/6113#issuecomment-2158158871
