### ISSUE TITLE
use Youtube's API directly mode does not work

### ISSUE THREAD

**Issue by inolie** [libre-tube/LibreTube#6129]
### Steps to reproduce

When I turn on the option to use Youtube's API directly, the video barely goes through and when it does, it stops after a couple of minutes. At the same I can load the videos smoothly using newpipe. Can the "use Youtube's API directly" mode of libretube be improved (perhaps use whatever stream protocol that newpipe uses or simply do whatever newpipe does when the user turns on the "use Youtube's API directly" mode)? I am not a programmer so sorry that I don't understand if both are using Youtube's API directly why libretube failed to work. I really appreciate your UI and hope to be able to use libretube. Thank you. 

### Expected behavior

video should play

### Actual behavior

video did not play

### LibreTube version

0.23.2

### Android version

android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
LibreTube doesn't have such a mode, and it's neither planned to be added.
