### ISSUE TITLE
New settings and features.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#613]
### Describe your suggested feature

Picture in picture (open / close), playback in the background (open / close), Watch history, Show/Hide comments,Tablet mode(auto,on,off),Search suggestions.Download from video URL.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
These are all dupes or already added. I feel like yoz don't even use the app
