### ISSUE TITLE
Unable to play videos on LibreTube

### ISSUE THREAD

**Issue by vikramisdev** [libre-tube/LibreTube#6139]
### Steps to reproduce

1. Open the app & play any video

### Expected behavior

should play the video

### Actual behavior

I get a toast message as "Watch on the latest version of YouTube".

### LibreTube version

0.23.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's an issue of the instance you use.

**Comment by vikramisdev** [comment]
hmm, i see, but I can't wait like 5-10 mins for a video to load or keep changing the instances all the time. btw can you make the trending page or the homepage like the official YouTube app. and a button on the player to change the resolutions.
