### ISSUE TITLE
Automatically generated subtitles does not show up

### ISSUE THREAD

**Issue by tux187** [libre-tube/LibreTube#6144]
### Steps to reproduce

1. select for example english (auto-generated)
2. it doesnt show up in the video

### Expected behavior

subtitles should appear

### Actual behavior

they didnt

### LibreTube version

0.23.2

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by hellishvictor** [comment]
Same here with Android 12 using latest v0.24.0.
