### ISSUE TITLE
Network Error All The Time

### ISSUE THREAD

**Issue by BatDevil** [libre-tube/LibreTube#6145]
### Steps to reproduce

1. play a video
2. "Network Error"

### Expected behavior

the Video actually playing.

### Actual behavior

it says there's a Network Error even when there's not really 

### LibreTube version

0.23.2

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please switch to an other instance.
