### ISSUE TITLE
Share menu should have a copy link along side piped, YouTube.

### ISSUE THREAD

**Issue by mcdz** [libre-tube/LibreTube#6161]
### Describe your suggested feature

Adding copy link to the share menu will allow users to copy the link without switching app, then users can maybe use floating window to share the copied link.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Ehab-d** [comment]
I agree. The share menu in some ROMs doesn't have a copy link option as in my case. I'm having difficulty just copying a video link.

![screenshot](https://github.com/libre-tube/LibreTube/assets/129071698/8307a84f-42ab-41a7-92c4-ae92ed58ff0f)



There is a small problem when implementing this feature. Which links are supposed to be copied: YouTube or Piped? This will require a solution.

**Comment by shuvashish76** [comment]
I use [URLCheck](https://f-droid.org/packages/com.trianguloy.urlchecker/) app for this purpose...not sure this feature is absolute necessary for LibreTube.
With URLCheck you can copy, edit & perform multiple custom actions on it.

**Comment by mcdz** [comment]
Another feature that NewPipe allows is pasting url in search bar and opening that video from link.

**Comment by BatDevil** [comment]
> I use [URLCheck](https://f-droid.org/packages/com.trianguloy.urlchecker/) app for this purpose...not sure this feature is absolute necessary for LibreTube. With URLCheck you can copy, edit & perform multiple custom actions on it.

you can't really make a justification for it not being there because copying links is something we do often and needing third party apps to do it is a bad mark on a great app such as this one

**Comment by mcdz** [comment]
New Pipe does that natively.
That's why I suggested.

> > I use [URLCheck](https://f-droid.org/packages/com.trianguloy.urlchecker/) app for this purpose...not sure this feature is absolute necessary for LibreTube. With URLCheck you can copy, edit & perform multiple custom actions on it.
> 
> you can't really make a justification for it not being there because copying links is something we do often and needing third party apps to do it is a bad mark on a great app such as this one

**Comment by Bnyro** [comment]
> I think it's more about the way share UI is called.
>
No, afaik NewPipe implements its own share UI.

**Comment by Ehab-d** [comment]
> I'm not really sure why it doesn't work on other Android ROMs / versions

Actually the problem is with some manufacturers who make stupid modifications in the Android share menu.

I suggest a solution is that long pressing the "YouTube" or "Piped" button copies the link of YouTube/Piped.

![image](https://github.com/user-attachments/assets/97e76bbe-5985-4629-b6a9-d3d15ad8460f)

**Comment by Bnyro** [comment]
I think long pressing is not really intuitive - I think a dedicated button would be better, that'll require a small redesign of the share dialog though, but I think that's reasonable.

**Comment by shuvashish76** [comment]
> I suggest a solution is that long pressing the "YouTube" or "Piped" button copies the link of YouTube/Piped.

Then it will be like a hidden feature that most people will never notice. +1 for Bnyro design idea.
Dedicated copy buttons for Piped and YouTube separately to the right side aligned with the toggle switch.

**Comment by Ehab-d** [comment]
> I think a dedicated button would be better

sure! I suggested the long presss solution because I assumed that you do not have time for a share menu redesign. But yeah it is reasonable.

**Comment by amandeepsinghjamwal** [comment]
What do you guys think of this design?
If it looks okay, I can raise PR.

![image](https://github.com/user-attachments/assets/31aa0956-1a0e-4f84-884d-5437051f8742)

**Comment by Bnyro** [comment]
I planned to do a larger overhaul of the share dialog and already have some drafts for it, I'll probably work on that when I'm back home next week.

**Comment by mcdz** [comment]
> > I'm not really sure why it doesn't work on other Android ROMs / versions
> 
> Actually the problem is with some manufacturers who make stupid modifications in the Android share menu.
> 
> I suggest a solution is that long pressing the "YouTube" or "Piped" button copies the link of YouTube/Piped.
> 
> ![image](https://private-user-images.githubusercontent.com/129071698/348161133-25d0c1c3-dced-4e5a-9424-328784f56c49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5NTgxMzgsIm5iZiI6MTcyMDk1NzgzOCwicGF0aCI6Ii8xMjkwNzE2OTgvMzQ4MTYxMTMzLTI1ZDBjMWMzLWRjZWQtNGU1YS05NDI0LTMyODc4NGY1NmM0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNFQxMTUwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMmI1ZmRhZmNlODY3YjRjZjRhZWFjZGZhNDc1NmVhYTMyZGFiMDYwZWZhODYzNWM1MzVmZmEwMWM5YWQ3NmE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B0PLap615EnLV6lGRk0W-V9DZBHT6PyD9BQfM1GrD_U)

oh. thanks. that's dope. love it.

**Comment by mcdz** [comment]
> What do you guys think of this design? If it looks okay, I can raise PR.
> 
> ![image](https://private-user-images.githubusercontent.com/57549340/348268884-31aa0956-1a0e-4f84-884d-5437051f8742.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5NTgyNDksIm5iZiI6MTcyMDk1Nzk0OSwicGF0aCI6Ii81NzU0OTM0MC8zNDgyNjg4ODQtMzFhYTA5NTYtMWEwZS00Zjg0LTg4NGQtNTQzNzA1MWY4NzQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDExNTIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyNzkzZjE0YTQ5Y2Y3ZjJlNTZjNmUyNjJmMTdhNGJkNWY2NDFiZjY4YmUzOTllNTZhMzc5MzI5NDg2NmI4NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H7DFphakW8yR69rXmLARoVdipCZXeBXMGwo6zJ7yC8U)

nice. should I close this issue?

**Comment by Ehab-d** [comment]
> should I close this issue?

No. GitHub issues are closed when already done by a PR.
