### ISSUE TITLE
do you think this is how a good app should work??

### ISSUE THREAD

**Issue by dialex07** [libre-tube/LibreTube#618]
if you do, you should stop doing this because you clearly have no idea about how to do it and still decided to do it

https://user-images.githubusercontent.com/105477255/175786103-3a90c2f6-0b4c-4b3a-900f-7d2aabf9b688.mp4

**Comment by Bnyro** [comment]
Yes, I really think so. That's why you should definitely switch back to YouTube and enjoy your Google trackers.

**Comment by Nizami20052022** [comment]
What is this, I do not have this problem.He deceives us

**Comment by Nizami20052022** [comment]
The program is very fast.

**Comment by archroid** [comment]
Kiwi browser stopped working on your phone. Ur phone can't even lunch the latest version of the official yt. THINK before saying things.

**Comment by dialex07** [comment]
> Yes, I really think so. That's why you should definitely switch back to YouTube and enjoy your Google trackers.

I knew you were going to answer that, mediocre

**Comment by dialex07** [comment]
> Kiwi browser stopped working on your phone. Ur phone can't even lunch the latest version of the official yt. THINK before saying things.

and what does Kiwi Browser have to do with it? you are the one who should think nonsense before saying it
