### ISSUE TITLE
Expanded View For All Videos

### ISSUE THREAD

**Issue by BatDevil** [libre-tube/LibreTube#6193]
### Describe your suggested feature

View YouTube videos in expanded form with thumbnails being big, y'know what i mean

### Other details

N/A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Such kinds of UI changes are not planned.
