### ISSUE TITLE
Playlist order "Sort by creation date" inverted

### ISSUE THREAD

**Issue by MatsG23** [libre-tube/LibreTube#6195]
### Steps to reproduce

1. Go to the library tab
2. Create a playlist with name "Old"
3. Create a playlist with name "New"
4. Select "Creation date (newest first)"

### Expected behavior

The playlist with the more recent creation date should appear at the top.

### Actual behavior

The older playlist is the first element in the list.

### LibreTube version

0.24.0 (but also present in 0.23.2)

### Android version

Android 14 (GrapheneOS 2024070201)

### Other details

Same problem for option "Creation date (oldest first)" - it is inverted

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
There's no option called "Creation date (newest first)"? There only is "Creation date" and "Creation date (reversed)".

Can't reproduce, tested with and without account.

**Comment by SK3180** [comment]
@MatsG23 can you provide some screenshots of this issue.

**Comment by Bnyro** [comment]
The order is just as what you would expect it to be.

Sorting by date should be understand as sorting by their UNIX timestamp, so they're sorted in an incremental order.

The old ones at the top, and the new ones at the bottom.

So yes, this is rather a translation issue than an actual issue of the app. Please edit the translations at https://hosted.weblate.org/projects/libretube/#languages to whatever you feel comfortable with for the German language (the `creation_date` and `creation_date_reversed` strings).
