### ISSUE TITLE
Playlist (Video play order) 

### ISSUE THREAD

**Issue by DracX3** [libre-tube/LibreTube#6198]
### Steps to reproduce

Step 1 = Add any 5 or more video in playlist 
Step 2 = Use sort option to desired view
Step 3 = Click Play all button

### Expected behavior

The video should run in the order in which it is seen in the playlist. 

### Actual behavior

It play video in Random order & I tried it many times it doesn't fix. 

### LibreTube version

0.23.2

### Android version

Android 14 

### Other details

• I know there is a option when we select the playlist from the video but there is no option to select by duration of video. 
• It an extra hassle to do. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by DracX3** [comment]
https://github.com/libre-tube/LibreTube/assets/120738858/b7589f0d-721b-409c-9f92-a3e589ac7e48

It doesn't work for me, it doesn't play in the same order as seen on the playlist🥲

**Comment by DracX3** [comment]
Yes I should have added it earlier, but yes it pretty annoying at times, i hope it gets fixed soon ☺️

**Comment by DracX3** [comment]
If was fixed brother ? @Bnyro

**Comment by akano12** [comment]
> If was fixed brother ? @Bnyro 

Try nightly

**Comment by DracX3** [comment]
It works flawlessly you are amazing brother, keep up the good work 💯 
It undoubtedly the best YT client in the web🤩
@Bnyro
