### ISSUE TITLE
(Total time) calculator for playlist 

### ISSUE THREAD

**Issue by DracX3** [libre-tube/LibreTube#6202]
### Describe your suggested feature

• When we multiple videos in the playlist then should be a total time of all the videos combined mentioned somewhere.
• So we know approximately how much time it will take us to finish the playlist. 
• Similar option in already available in "newpipe" 
![Screenshot_20240709_105827_Tubular](https://github.com/libre-tube/LibreTube/assets/120738858/9660f0c7-509e-4bf5-94eb-361c99a907c9)

### Other details

• If there also could be a playback speed for option the playlist, which also show the total time it will take to complete the playlist in that speed, will be so convenient.
![Screenshot_20240709_110011_Samsung Internet](https://github.com/libre-tube/LibreTube/assets/120738858/20d44625-0703-4aee-af33-fa1a9a59d816)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Implemented in https://github.com/libre-tube/LibreTube/pull/6240.

> If there also could be a playback speed for option the playlist, which also show the total time it will take to complete the playlist in that speed, will be so convenient.
>
A dialog to consider the playback speed is not planned, I think that's way too much of an overkill for such a simple feature.

**Comment by DracX3** [comment]
Yes I guess you are right we can still set the playback speed manually ✨
But thankyou so much for the calculation option you are GOAT bro 🔥
