### ISSUE TITLE
Improve the Feature

### ISSUE THREAD

**Issue by Butterfly585411** [libre-tube/LibreTube#6203]
### Describe your suggested feature

Need the vertical scrolling instead of horizontal scrolling below the comment section. Need like the original YouTube related videos vertical scrolling.
![Screenshot_6](https://github.com/libre-tube/LibreTube/assets/175163154/4e6232cd-6b81-422f-8489-7f1f4ed2bfdf)

### Other details

Need the vertical scrolling instead of horizontal scrolling below the comment section. Need like the original YouTube related videos vertical scrolling. It will be helpful for the users if the LibreTube team improves this feature in a new release. Thanks.
![Screenshot_6](https://github.com/libre-tube/LibreTube/assets/175163154/4e6232cd-6b81-422f-8489-7f1f4ed2bfdf)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Tetzuya75** [comment]
Quote it

**Comment by Bnyro** [comment]
That's not planned and has already been rejected before.
