### ISSUE TITLE
Little to no options in instance list

### ISSUE THREAD

**Issue by Darin755** [libre-tube/LibreTube#6208]
### Steps to reproduce

1. Open up Libretube
2. Wait a second
3. All the instances disappear

### Expected behavior

Ideally I should see a long list

### Actual behavior

![Screenshot_20240710-143938_LibreTube](https://github.com/libre-tube/LibreTube/assets/54958995/c8773cce-e258-4aa4-8222-d61a8d2d0522)

### LibreTube version

0.23.1

### Android version

Android 14

### Other details

This could have to do with attacks from YouTube on piped. I notices that Piped isn't working either

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by rafi612** [comment]
I have same issue, self added instances are displaying on list.

**Comment by BatDevil** [comment]
have YouTube just successfully nuked the instances?

**Comment by Bnyro** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/11255
