### ISSUE TITLE
Where's the option to switch to background playback from video view?

### ISSUE THREAD

**Issue by christubuntu** [libre-tube/LibreTube#6210]
### Describe your suggested feature

I see there's an option to long press video (before playing) and choose to play audio only (background playback). I also see an option to go from there to video view. But where's the option to go from Video view to background playback? Can't find any button for that
![Screenshot_20240711_130627_LibreTube](https://github.com/libre-tube/LibreTube/assets/55885756/a4a3bba0-8c77-47e8-8081-e2bc25a1e7c5)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Scroll to the right in the row where the `Share`, `Download`, ... options are.
