### ISSUE TITLE
Improve Player UI with gradient and squiggly progress bar

### ISSUE THREAD

**Issue by GuiSousa135** [libre-tube/LibreTube#6222]
### Describe your suggested feature

Improve the Player UI with a gradient and squiggly progress bar when the video is playing. This function makes the app more elegant and combines with the MaterialYou design, makes it easy to view video playback.

### Other details

![Screenshot_20240710-104720_Cromite_1_1](https://github.com/user-attachments/assets/95934529-e78d-48ab-853a-0ee844deac86)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Kinda unnecessary ~~~~~

**Comment by IndusAryan** [comment]
this sperm like slider is not meant for video players afaik, it suits music apps, so it can be added in audio mode if they like it

> Kinda unnecessary ~~~~~

**Comment by akano12** [comment]
> I think it's beautiful and intuitive, it goes well with the MaterialYou design, there could be an option to disable it in the settings

It's neither beautiful nor intuitive, it's distracting

**Comment by Bnyro** [comment]
The plan is to stick to Material design components provided by the official library, and that library doesn't contain such a wavy slider so it's out of scope.

Additionally, the plan is to only add new dependencies when really necessary, because library updates with bugs could also negatively impact LibreTube.
