### ISSUE TITLE
Does not respect "Autoplay Playlists" toggle

### ISSUE THREAD

**Issue by LavellanDWR** [libre-tube/LibreTube#6224]
### Steps to reproduce

1. Toggle Autoplay Playlists option on
2. Confirm working autoplay in private Piped playlist
3. Toggle Autoplay Playlists option off
4. Play video in private Piped playlist

### Expected behavior

Video playback stops after the selected video ends

### Actual behavior

Video playback stops, then the next video loads, as if the option was still toggled on. This happens both with and without restarting the app between/after the changes in the settings. 

### LibreTube version

v0.24.0

### Android version

13

### Other details

Issue was introduced moderately recently

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
If the `autoplay playlists` option is disabled, the app follows the normal autoplay perference which can be set by toggling the play arrow switch at the top right of the player controls.

Hence you must disable this as well to prevent autoplay of playlists.
