### ISSUE TITLE
Let the app auto open youtube.com links in the app, instead of the browser

### ISSUE THREAD

**Issue by cyber-sec0** [libre-tube/LibreTube#6227]
### Describe your suggested feature

This could also help solve https://github.com/libre-tube/LibreTube/issues/6226 since if the app opened YT links I could just save+copy the link anywhere, and then manually open the link in a single click.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Go to settings=>apps=>libretube then toggle YouTube links in the supported addresses
