### ISSUE TITLE
Autogenerated subtitles do not work

### ISSUE THREAD

**Issue by april4356** [libre-tube/LibreTube#6228]
### Steps to reproduce

1. Play any video
2. Enable autogenerated subtitles
3. Autogenerated subtitles do not show up

### Expected behavior

Play video. Enable autogenerated subtitles. They show up.

### Actual behavior

Play video. Enable autogenerated subtitles. They do not show up.

### LibreTube version

0.24.0

### Android version

Android 14

### Other details

https://github.com/libre-tube/LibreTube/issues/5511#issue-2088504310

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by hellishvictor** [comment]
Same here with Android 12.
