### ISSUE TITLE
[Feature request] Automatically go to video if the url is put into the search bar

### ISSUE THREAD

**Issue by amogusussy** [libre-tube/LibreTube#6230]
### Describe your suggested feature

You should be able to paste the url of any youtube video (youtu.be or youtube.com/watch) into the search bar, and then it automatically goes to that video.

When you press enter when searching, it should check if the text pasted matches a regex statement for a youtube url, and if it matches, then open that video.

### Other details

This is a feature in NewPipe, if you want to see their implementation.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not planned. Pasting the link already gives you the corrext video as result, and you already have the ability to share links directly with LibreTube or open them directly with the app.

**Comment by Bnyro** [comment]
Due to multiple requests about this, I'm reopening this issue.

**Comment by akano12** [comment]
> Due to multiple requests about this, I'm reopening this issue.

I sometimes get multiple results for same link, is this normal?

**Comment by Bnyro** [comment]
> I sometimes get multiple results for same link, is this normal?
>
It's whatever YouTube returns to you when you paste the link in the search bar, LibreTube doesn't modify the link currently.

**Comment by amogusussy** [comment]
Newpipe's implementation is in the `extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/linkHandler/YoutubeStreamLinkHandlerFactory.java` file in the TeamNewPipe/NewPipeExtractor repository.
You can use this to base the feature on,

**Comment by Bnyro** [comment]
That's not necessary, we already have our own logic to detect and handle YouTube links, it's just used in other places of the app currently.
