### ISSUE TITLE
HTTP 400: can't create 00:00-00:19 Intro segments for SponsorBlock

### ISSUE THREAD

**Issue by QuestioningEspecialy** [libre-tube/LibreTube#6231]
### Steps to reproduce

When I try to add an _Intermission/Intro Animation_ segment to Talk Ville Podcast's [SHATTERED (S3E08)](https://www.youtube.com/watch?v=S73ph39f0mE) and [MAGNETIC (S3E07)](https://www.youtube.com/watch?v=sC0TklHGGdw), I get the "HTTP 400" error message at the bottom of the screen. Meanwhile, I was able to add a 00:00-09:00 Intro segment to Jahara Jayde's [3hr Kingdom Hearts 1.5 playthrough](https://www.youtube.com/watch?v=pUy9vVgKivY). 🤷🏿‍♂️

### Expected behavior

The segment should be successfully submitted just like it was for the KH video and has been for Talk Ville Podcast's videos for atleast a month now.

### Actual behavior

I get the "HTTP 400" error message at the bottom of the screen and there's no sign that the submission went through when I reopen the video later.

### LibreTube version

0.24.0 

### Android version

14 (GrapheneOS)

### Other details

Pretty sure I was able to add them prior to updating my [nightly build](https://github.com/libre-tube/NightlyBuilds) on 7/11/24, and it still doesn't work with the build from ~5hrs ago. Also, trying "0 - 00:19" has the same result.

v0.24.0 [Nightly Build](https://github.com/libre-tube/NightlyBuilds) (7/11/24 & 7/13/24)
Pixel 6a
Android 14
GrapheneOS (auto-updates active)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
As a workaround until the next release, you should be able to add a `.` to the end of your input time, e.g. `00:20.` or use the representation in seconds only: `20`.
