### ISSUE TITLE
cant change audio track

### ISSUE THREAD

**Issue by Noahnillion19** [libre-tube/LibreTube#6232]
### Steps to reproduce

1. go to any video with multiple audio tracks (for example a mrbeast video)
2. select an audio track that isnt currently selected

### Expected behavior

it changes the audio track

### Actual behavior

it doesnt change the audio track

### LibreTube version

0.24.0

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't reproduce. The issue description isn't detailed enough to figure out why it does not work.

Try an other instance maybe.
