### ISSUE TITLE
Disable Piped proxies Videos and images are retrieved directly from YouTube's servers. Use only if you use VPN all the time.  Videos will not play unless this option is turned off.

### ISSUE THREAD

**Issue by irukairu** [libre-tube/LibreTube#6234]
### Steps to reproduce

1. Start libretube.
2. Open the settings and select the Instances item.
3. Check Disable piped proxy in the proxy section.
4. Play the video of whatever you want.

### Expected behavior

After loading, the video should play.

### Actual behavior

The video will not play and will not finish loading forever.

### LibreTube version

v0.24.0

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't reproduce, bad issue title.
