### ISSUE TITLE
Im new to using Libretube and Just switched from YouTube for privacy reasons

### ISSUE THREAD

**Issue by Ethernecter** [libre-tube/LibreTube#6243]
### Steps to reproduce

I've created a user account on Libretube, but I've having some issues with watch video because it claims Im not logged in but I am and it does the same thong even when i log out. I also saw that there were some new updates but when I try to update Libretube it says the update is incompatible with my device.  Im also completely new to GitHub but I've been on here a few times.
![Screenshot_20240716-215743](https://github.com/user-attachments/assets/c2d1fe29-cb01-43c3-8ca1-832d9376f58a)
![Screenshot_20240716-215822](https://github.com/user-attachments/assets/4581546a-4e63-4ee2-8bc0-34df64e4cdda)

 

### Expected behavior

After downloading the application from Fdroid and making my user account, I expected the application to run smoothly, I also tried updating the application but it says my device is incompatible with the update. 

### Actual behavior

It's spotty with what videos I can watch, and I have some issues with updating the app. 

### LibreTube version

0.23.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Settings -> Instance -> Choose an other one.

The error message you get indicates that the [Piped](https://github.com/TeamPiped/Piped) instance you use is ratelimited by Google/YouTube, and hence currently doesn't work.

**Comment by Ethernecter** [comment]
Thanks! Lol it works, when it can to looking for a YouTube alternative, it
was hard because I want to access a more secure video platform without
ditching the a some content creators on Youtube. But this is great!
