### ISSUE TITLE
All Subscription is not showing

### ISSUE THREAD

**Issue by brnwlshubh** [libre-tube/LibreTube#6244]
### Steps to reproduce

1.Open App
2.Switch to Subscriptions Tab
3.Tap on Subscriptions

### Expected behavior

It should show all Subscription

### Actual behavior

It shows only some Subscription.
In my case it only shows 74/264 subscriptions only.

It varies with other instances.

### LibreTube version

0.24.0 Nightly

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Have you double checked that the subscriptions are properly shown when you visit the Piped web client of the instance you use (e.g. piped.video)?
