### ISSUE TITLE
Redirect to piped - servers in 0.24.0 cannot be disabled

### ISSUE THREAD

**Issue by Baltazar500** [libre-tube/LibreTube#6246]
### Steps to reproduce

1. Switch the toggle switch "Instance/Disable Piped Proxy"
2. Select piped server pipedapi.r4fo.com
3. Block access to r4fo.com

### Expected behavior

"Disable Piped Proxy" should disable piped-proxy

### Actual behavior

Redirect to piped - servers in 0.24.0 cannot be disabled with toggle switch "Instance/Disable Piped Proxy"

### LibreTube version

0.24.0

### Android version

Android 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The option only disables the proxy for playing video and loading thumbnails, the app still uses Piped's API for anything else.
