### ISSUE TITLE
hls in 0.24.0 is enabled by default and cannot be disabled by the "Use Hls" switch

### ISSUE THREAD

**Issue by Baltazar500** [libre-tube/LibreTube#6247]
### Steps to reproduce

1. Disable hls in the settings with the toggle switch "Audio and Video/Use Hls"
2. Block manifest.googlevideo.com or use mitm-proxy

### Expected behavior

By default, LibreTube should request mp4/webm/etc streams

### Actual behavior

hls in 0.24.0 is enabled by default and cannot be disabled by the "Audio and Video/Use Hls" switch

### LibreTube version

0.24.0

### Android version

Android 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
DASH doesn't work when the Piped proxy is disabled, hence the app forces usage of HLS in that case.

**Comment by mcbelisle** [comment]
yeah videos don't play at all unless hls is selected but with hls on cannot view captions

**Comment by Baltazar500** [comment]
>DASH doesn't work when the Piped proxy is disabled, hence the app forces usage of HLS in that case.

dash only works through pipedapi ? And in versions below 0.24.0, how were things?

But if pipedapi is unavailable or gives the error “Sign in to confirm that you're not a bot”, then through hls similar links (“This video may be inappropriate for some users.”) https://www.youtube.com/watch?v=SDea7laHD4E will not play. hls streams do not return for every youtube - links
