### ISSUE TITLE
Search and add by URL

### ISSUE THREAD

**Issue by edmundlaugasson** [libre-tube/LibreTube#6249]
### Describe your suggested feature

When copied URL from another app or directly from YouTube, search could find the channel, playlist, video and order, add buttons available according what URL it was.
This works e.g. in Newpipe and its based forks.

### Other details

This feature could save lot of time as needed channel, playlist, video is already found in another app or web and would be easy and fast way to find and add it also in LibreTube. Not always possible to copy channel, playlist, video name. Even if you can copy name, there are many findings. But allowing exact URL will find precisely and quickly what we are looking for.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/issues/6230#issuecomment-2227286834

**Comment by edmundlaugasson** [comment]
Sounds like still planned - #6230 
I really hope this feature will be implemented.
