### ISSUE TITLE
Added channel does not appear immediately into list

### ISSUE THREAD

**Issue by edmundlaugasson** [libre-tube/LibreTube#6250]
### Steps to reproduce

1. Search channel
2. Order it either from list or open and then order
3. check ordered channels - this channel does not appear in the ordered channels list immediately 

### Expected behavior

Ordered channel appears in ordered list immediately.

### Actual behavior

Ordered channel appears in list with great delay and usually have to refresh manually the list or even close app completely and open again to see ordered channel in list. Sometimes need to add next channel in order to see previous added channel in list. But lastly added channel still not listed. Quite problematic currently.

### LibreTube version

0.24.0

### Android version

Android 11

### Other details

App version is not possible to see from app. Finally from Android settings could detect app version. Installed directly from app-arm64-v8a-release.apk file.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It's the intended behavior that you have to refresh the subscriptions feed after adding a new channel.

**Comment by edmundlaugasson** [comment]
If you readed, then you see, that even after refresh new channels do not appear into list. I have to add new one to see previous one if I'm lucky. Behaviour is random to get ordered channels listed. After several cycles finally I see. Under cycle I mean refresh list, close app reopen app, add new order to list, etc. Didn't find any fixed pattern to understand, what exactly brings ordered channel to list.
Sounds for me, that 0.24.0 has too many bugs, that we need downgrade app. When upgraded, it didn't use profile what left onto device. I had to reconfigure from scratch.
