### ISSUE TITLE
Subtitle translation

### ISSUE THREAD

**Issue by edmundlaugasson** [libre-tube/LibreTube#6251]
### Describe your suggested feature

Using Google Translate there could be automatic subtitles translation. Under settings there we can choose our mother tongue but if subtitle officially is not available then no subtitle is shown.
In YouTube web we can choose also automatic translation either from available subtitle (better result, preferred) or automatically generated subtitle. Same feature we would expect in LibreTube.
Would propose to add separate subtitle translation choice under mediaplayer settings, where currently also subtitle settings are. There could be subtitle translation preference settings. First place prefer existing subtitle to take as basis for automatic translation because result is better because there is already existing subtitle translated sentence by sentence and therefore translation quality is better. If there is no existing subtitle, then autogenerate it and then translate - this is also better than nothing.

### Other details

Google Translate can translate on the fly. Youtube can generate automatic subtitle using speech to text synthesizer, which in turn can be translated on the fly.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/5549

**Comment by edmundlaugasson** [comment]
But I suggest to plan in order to keep LibreTube in use. Many people need translation. This is why YouTube made such subtitle translation possible.
Besides, why are then these languages in choice, when these don't work and you say: not planned?
