### ISSUE TITLE
Next, previous song buttons broken

### ISSUE THREAD

**Issue by edmundlaugasson** [libre-tube/LibreTube#6253]
### Steps to reproduce

1. Play any song
2. Try to tap on next, previous song button
3. Still current song is playing

### Expected behavior

Either next or previous song starts playing according what button was pressed.

### Actual behavior

Still current song playing.

### LibreTube version

0.24.0

### Android version

Android 11

### Other details

From settings there is needed to allow these buttons. Sometimes these buttons do not appear at all regardless of setting. Also in drawer pulled down from upper edge, there are also previous, next song buttons - also these are broken (do not work).
Then discovered, that this issue appears when playing single songs, not playlist. But even playlist played and on screen previous, next buttons appeared and worked, then buttons in upper edge drawer still not working.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/6100
