### ISSUE TITLE
Random order play button missing

### ISSUE THREAD

**Issue by edmundlaugasson** [libre-tube/LibreTube#6254]
### Steps to reproduce

1. Open certain playlist and play it
2. Open the list of songs
3. Bottom edge, where are buttons to repeat, etc - there is random order button missing 

### Expected behavior

Random order button exist in playlist and also when on video open hexagon button - there are also replay settings.

### Actual behavior

Currently random order play button, option missing.

### LibreTube version

0.24.0

### Android version

Android 11

### Other details

Even no workaround isn't available to play playlist in random order.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not possible, see https://github.com/libre-tube/LibreTube/issues/2213#issuecomment-1364679774
