### ISSUE TITLE
Ordered list in portrait position basically not readable

### ISSUE THREAD

**Issue by edmundlaugasson** [libre-tube/LibreTube#6255]
### Steps to reproduce

1. Order some channels
2. Open ordered channels list in portrait position 
3. Only first word is partially visible. Then in the middle is notification button and then right side is covered with choice button about option to cancel order.

### Expected behavior

These notification and order cancel buttons should not placed on row when portrait position. Hereby propose buttons below. One button, when turned on, makes checkboxes in the beginning of each row. Then there could be possible to select, what needed. Then next buttons could allow apply to selected items either cancel order or some more actions, e.g. rename or edit full details.

### Actual behavior

Currently in portrait position item in list is nearly unreadable as only first word is partially visible.

### LibreTube version

0.24.0

### Android version

Android 11

### Other details

Mediaplayer AIMP has such behaviour and buttons. This is also free and open-source app - you can copy from there as AIMP is also open-source.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please share a screenshot.

**Comment by Bnyro** [comment]
Well, with that screen size you probably will have issues with many apps, and probably many other places in LibreTube too.

You can either reduce the system font size or just live with the fact that you can't expect 100% the same usability with a very-small-screen-device.

On my display everything is readable (6 inches screen) - there's no way to keep all the buttons (as in the screenshot) while increasing the space for the channel name text.

**Comment by edmundlaugasson** [comment]
Sorry but do not have in other apps such issue. E.g. Newpipe and its fork Tubular do not have such issue. It is not a matter of font size but design itself. E.g. in Newpipe is notification and ordering solved in a different way so, that these do not hide playlist name. As Newpipe is open-source app, you can use their source code.
Also if playlist name is too long, it would be useful to allow to scroll the playlist name by dragging its name.
