### ISSUE TITLE
Piped Proxy is not working

### ISSUE THREAD

**Issue by brnwlshubh** [libre-tube/LibreTube#6257]
### Steps to reproduce

Open any video it only buffers.

### Expected behavior

Video should be played.

### Actual behavior

Buffering issue until I disable Piped Proxy.

### LibreTube version

0.24.0 Nightly

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by brnwlshubh** [comment]
I've tried almost all Instances from the libretube listings.

**Comment by Bnyro** [comment]
Not a LibreTube issue.
