### ISSUE TITLE
 Error message " Watch on the latest version of youtube"

### ISSUE THREAD

**Issue by GotGit-Code** [libre-tube/LibreTube#6261]
### Steps to reproduce

1- install LibreTube and use it with proton VPN very well for a week.
2- then install orbot and turn it on with VPN mode (uses tor) instead VPN proton and Libretube App imediatly was not work more.
3- enter in librerube, choose any video and the message "watch on the latest version of youtube"
3- i clean cache, clean data, unstall e install again and Libretube always disblay this error message.
![Screenshot_20240720-102705_LibreTube](https://github.com/user-attachments/assets/5d454c17-d621-4a4f-b9e0-c1d0ca8e31b3)

### Expected behavior

It should display and run the video

### Actual behavior

After enter in libretube and click on any video, got this error message

### LibreTube version

v0.23.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/TeamPiped/Piped/issues/3685
