### ISSUE TITLE
HDR Capable device cannot see hdr streams in the quality meter

### ISSUE THREAD

**Issue by alejandro-alzate** [libre-tube/LibreTube#6262]
### Steps to reproduce

press options
select quality
select best quality

### Expected behavior

720/1080/1440/2160HDR options should be listed

### Actual behavior

hdr never is listed

### LibreTube version

0.24.0

### Android version

LineageOS 20 (Android 13)

### Other details

#4195 and #5147 mentions that when compatible it will enable it, now my phone has an oled panel and for other things like vlc the osk and the aod can successfully show true black while libretube shows gray bars and the black on videos that are hdr never get true darkness.

If this on my side at least it would be cool to have some "shader" overlayed on the video that makes tone mapping to the capabilities of my screen.

Also i noticed the official YT App flickers when the video is being moved while it trasitions from normal, fullscreen, and pip it goes from hdr to sdr then back hdr during it.

But libretube only messes with the brightness, I don't know if that fact matters but at least is worth the mention.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
HDR is only working via DASH, which is broken as of now: https://github.com/libre-tube/LibreTube/issues/5855

**Comment by alejandro-alzate** [comment]
That sucks but alright i'll wait
DO NOT FEEL RUSHED bc im losing like 5% of battery by not having hdr though.
