### ISSUE TITLE
Video Buffer

### ISSUE THREAD

**Issue by brnwlshubh** [libre-tube/LibreTube#6265]
### Describe your suggested feature

An Option to Increase Video Buffer
1.Size
2.Length

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Settings -> Player -> Misc -> Preloading

I don't think it makes sense to specify this in bytes, and it's probably not supported by the ExoPlayer library.
