### ISSUE TITLE
Text invisible in activity_welcome

### ISSUE THREAD

**Issue by getgo-nobugs** [libre-tube/LibreTube#6266]
### Steps to reproduce

1. Install the app
2. Open the app

### Expected behavior

The text below the icon should be visible in the light mode.

### Actual behavior

<img width="255" alt="image" src="https://github.com/user-attachments/assets/ab97ea5a-ed00-452f-bdd3-ef9201d37aa6">

### LibreTube version

0.24.0

### Android version

API level 34

### Other details

I think the issue should be related to 

`<com.google.android.material.appbar.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar">`

In this snippet, the dark theme is always applied to the text color. Instead, the text color should change according to the system settings.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thanks for the detailed report, I can't tell why we forced a dark action bar theme there :shrug:
