### ISSUE TITLE
Background notification is not deleted when I close the mini player

### ISSUE THREAD

**Issue by Pamilg9** [libre-tube/LibreTube#6276]
### Steps to reproduce

1. Close the mini player
2. The background notification is not removed

### Expected behavior

Background notification should be closed

### Actual behavior

https://github.com/user-attachments/assets/d5f9cc3b-aff9-4434-9823-998ab847913b

### LibreTube version

0.24.0 Debug

### Android version

Android 12

### Other details

No

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Seems to be a device/ROM specific issue, can't reproduce.
