### ISSUE TITLE
Device navigation buttons are not visible

### ISSUE THREAD

**Issue by Pamilg9** [libre-tube/LibreTube#6278]
### Steps to reproduce

![Screenshot_20240724-093424_LibreTube](https://github.com/user-attachments/assets/fa11d988-8417-49c3-9ab2-47223b2414ef)

### Expected behavior

Let it be seen

### Actual behavior

Title

### LibreTube version

0.24.0 Debug

### Android version

Android 12

### Other details

No

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't reproduce, youe device apparently doesn't respect https://github.com/search?q=repo%3Alibre-tube%2FLibreTube%20windowLightNavigationBar&type=code, so nothing we can do here.
