### ISSUE TITLE
New Videos Not Showing In Subscriptions Tab

### ISSUE THREAD

**Issue by royaltongue** [libre-tube/LibreTube#6281]
### Steps to reproduce

1. Go to Subscriptions tab
2. Pull to refresh videos

### Expected behavior

Newest videos from subscribed channels should be loaded

### Actual behavior

No new videos are loaded

### LibreTube version

v0.24.0

### Android version

Android 14

### Other details

Subscription feed in YouTube (Revanced): ![Screenshot_20240724_105703_YouTube](https://github.com/user-attachments/assets/af75a31e-0f88-4ded-9b46-a6d58b75fa47)
Subscription feed in LibreTube: ![Screenshot_20240724_105641_LibreTube](https://github.com/user-attachments/assets/9c12ecbf-c03f-4ade-8671-15cc0b823435)

At first, I was using the `drgns.space` instance, but switched to `kavin.rocks` after clearing data and cache, but issue still occurs.

Subscriptions were imported from YouTube csv obtained through Google Takeout

Manually going to specific channel will correctly show latest video

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/TeamPiped/Piped/issues/1130

**Comment by tooilltoheal** [comment]
I'm also experiencing the same issue on the latest version

**Comment by kulothunganug** [comment]
+1 Same issue

Manufacturer: Nothing
Board: Pacman
Arch: arm64-v8a
Android SDK: 34
OS: Android 14
Display: 1084x2230
Font scale: 1.0

Version: 0.25.2 (57)

**Comment by Casseus41** [comment]
I am also experiencing this issue currently. 

V0.25.2

**Comment by Jetterrr** [comment]
I'm experiencing this bug on 0.26.0.
