### ISSUE TITLE
[Feature request] multiaccaunt support

### ISSUE THREAD

**Issue by ralencode** [libre-tube/LibreTube#6287]
### Describe your suggested feature

ability to quickly switch between instances/account without relogin. some instances may stop working sometimes, and then i have to switch to another. fe, sometimes adminforge works better than kavin, sometimes the other way, so i switch between these two pretty much and it would be cool not to have to enter the password every time

### Other details

authentification instance is not what i want as sometimes it makes things even harder when one of the instances hangs and nothing works at all

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's out of scope for the project.

In case you want to switch the instance a lot you should use local subscriptions / playlists without logging into a Piped instance.
