### ISSUE TITLE
An option to filter search 

### ISSUE THREAD

**Issue by Its-Tony** [libre-tube/LibreTube#6288]
### Describe your suggested feature

There should be an option to filter search according to date, relevance,  channel , playlist etc. A closed source app ymusic have this feature 
![Screenshot_2024-07-25-14-19-54-409_com kapp youtube final](https://github.com/user-attachments/assets/2bfc2149-4676-434d-940e-b06b198917dd)
I'm sharing screenshot for reference.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not supported by NewPipe Extractor.
