### ISSUE TITLE
Offline playlists like in newpipe

### ISSUE THREAD

**Issue by User1l0** [libre-tube/LibreTube#629]
Please make able to save videos in playlists without signing in, like it's done in the new pipe app. Also making it able to export and import the playlists.

**Comment by Bnyro** [comment]
Playlist import will be there with the new update. We won't add offline playlists.

**Comment by User1l0** [comment]
> Playlist import will be there with the new update. We won't add offline playlists.

Why? It can help users who won't use YouTube account

**Comment by Akruidenberg** [comment]
Would like this also.
