### ISSUE TITLE
Screen Orientation

### ISSUE THREAD

**Issue by brnwlshubh** [libre-tube/LibreTube#6294]
### Describe your suggested feature

Screen Orientation on Landscape mode it remains to Portait other than video player.
Please add/improve the orientation.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Settings -> General -> Orienation
