### ISSUE TITLE
Got Error: Sign in to confirm you're not a bot on every video

### ISSUE THREAD

**Issue by TFB2024-Official** [libre-tube/LibreTube#6295]
### Steps to reproduce

1. look for any video
2. play the video

### Expected behavior

The video should play like usual

### Actual behavior

The popup showed up and the video did not play at all

### LibreTube version

0.24.0

### Android version

Android 13 (One UI 5.1)

### Other details

the video player remains unloaded and only the pop up shows up

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/6116

**Comment by macerg** [comment]
I am getting this also. Even after signing in. Latest Libretube, android 11.

**Comment by AaaAlias55** [comment]
How to solve this bug??

**Comment by macerg** [comment]
No one seems to be looking at it.

**Comment by jewel109** [comment]
I am also getting the error

**Comment by Dv5n** [comment]
Same. Sometimes (very rare) works.

**Comment by AaaAlias55** [comment]
> Same. Sometimes (very rare) works.

So what should we do now?
😬😬😬

**Comment by Dv5n** [comment]
> > Same. Sometimes (very rare) works.
> 
> So what should we do now? 😬😬😬

Waiting, i think.

**Comment by devbymani** [comment]
I am also getting the same error

**Comment by blublu80** [comment]
It does the same thing to me too. Too bad

**Comment by blublu80** [comment]
I found the solution. You need to register on Settings / Account Instance, anything to register a username and a password possibly long and complex ( but remember it) Then on proxy enable “Disable Piped proxy” then enable Local stream extraction ... That is all now all the videos go to me , I hope it is the same for you too

**Comment by blublu80** [comment]
would be useful in the search filters to search for videos like there is on youtube would be EXCELLENT

**Comment by idiot0426** [comment]
> I found the solution.
> 
> > You need to register on Settings/Istance/Account
> > anything to register a username and a password possibly long and complex (but remember it)
> > Then on proxy enable “Disable Piped proxy” then enable "Local stream extraction" ... That is all now all the videos go to me , I hope it is the same for you too

thanks

**Comment by cesc1989** [comment]
> I found the solution.
> 
> > You need to register on Settings/Istance/Account
> > anything to register a username and a password possibly long and complex (but remember it)
> > Then on proxy enable “Disable Piped proxy” then enable "Local stream extraction" ... That is all now all the videos go to me , I hope it is the same for you too

Thanks. Worked for me.

**Comment by macerg** [comment]
And that's exactly what the original instructions said when the problems started and the circumvention was introduced.

**Comment by macerg** [comment]
> I found the solution.
> 
> > You need to register on Settings/Istance/Account
> > anything to register a username and a password possibly long and complex (but remember it)
> > Then on proxy enable “Disable Piped proxy” then enable "Local stream extraction" ... That is all now all the videos go to me , I hope it is the same for you too
And that's exactly what the original instructions said when the problems started and the circumvention was introduced.

**Comment by macerg** [comment]
> I found the solution.
> 
> > You need to register on Settings/Istance/Account
> > anything to register a username and a password possibly long and complex (but remember it)
> > Then on proxy enable “Disable Piped proxy” then enable "Local stream extraction" ... That is all now all the videos go to me , I hope it is the same for you too


And that's exactly what the original instructions said when the problems started and the circumvention was introduced.

**Comment by superman-enamy** [comment]
> You need to register on Settings/Istance/Account
> 
> anything to register a username and a password possibly long and complex (but remember it)
> 
> Then on proxy enable “Disable Piped proxy” then enable "Local stream extraction" ... That is all now all the videos go to me , I hope it is the same for you too

Is there any video or detail solution?
