### ISSUE TITLE
Channel page loops forever

### ISSUE THREAD

**Issue by FamiliarBreakfast** [libre-tube/LibreTube#6296]
### Steps to reproduce

Go to any channel page
Scroll through the videos tab

### Expected behavior

Videos appear in chronological order

### Actual behavior

The most recent set of videos will be shown, scrolling further will repeat this block forever

### LibreTube version

0.24.0

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FamiliarBreakfast** [comment]
Demonstration: https://youtu.be/qZS2hakZo5I?si=6KPtdhXOb-GuCNh6

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/pull/6273
