### ISSUE TITLE
Getting "Must sign in to view" when already signed in

### ISSUE THREAD

**Issue by silentTeee** [libre-tube/LibreTube#6298]
### Steps to reproduce

1. Attempt to watch video on kavin.rocks
2. Get told to sign in to view video
3. Navigate to sign-in menu and can sign in successfully
4. Attempt to watch video again

### Expected behavior

Plays the video.

### Actual behavior

UI transitions to video watching state (with section for comments and player) but gives up after a few seconds and shows the error message in the attached screenshot
![Screenshot_20240728-211131](https://github.com/user-attachments/assets/99689588-09cc-4f5b-8fd3-77ef4c4a978b)

I am not against the fact that it wants me to sign in, but the fact that it doesn't seem to be letting me view the video even though I _already_ signed in. 

### LibreTube version

0.24.0

### Android version

14

### Other details

Not sure if this is a LibreTube problem or a Piped problem, admittedly. I haven't had the chance to investigate deeper. Just wanted to report it so it doesn't go undocumented.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/issues/6116

**Comment by silentTeee** [comment]
Ah sorry @Bnyro, didn't think to check the "closed" tickets when I reported this. Thanks for linking the other ticket, will try the things suggested in it. 🙂
