### ISSUE TITLE
[FEATURE] Play video in external player

### ISSUE THREAD

**Issue by Mennaruuk** [libre-tube/LibreTube#63]
**Describe the feature you'd like to see added**
The ability to stream videos to external players will make LibreTube very powerful. Here are some things that can be done:

- Videos can be played in [VLC Media Player](https://www.videolan.org/vlc/download-android.html), which offers features such as gestures, audio equalizer, and support for custom subtitles
- Videos can be played in [Web Video Cast](https://play.google.com/store/apps/details?id=com.instantbits.cast.webvideo&hl=en_US&gl=US), which allows casting of any video link to a supported smart TV, Chromecast, Roku, Amazon Fire, and other devices
- Videos can be played in [KMPlayer](https://play.google.com/store/apps/details?id=com.kmplayer), which supports timestamp bookmarking, video inversion, speed control, UPnP connections, and picture in picture

The possibilities are endless!

**Additional context**
This is not to discourage implementing some of the features above natively. Rather, this appeals to power users who want both the ease of accessing Piped _via_ LibreTube and the integration of streaming Piped-proxied videos to external players.

**Comment by rimthekid** [comment]
This is actually a very good idea as the player is not complete yet

**Comment by rimthekid** [comment]
So I checked [this](https://wiki.videolan.org/Android_Player_Intents/) and seems like there is no way to send video and audio together to vlc but you can download the video and watch it on vlc rn

**Comment by Mennaruuk** [comment]
Dang it. I swear I remember casting videos to my TV without downloading the whole things. I see that the page was last edited in 2016, maybe this is outdated?

**Comment by rimthekid** [comment]
Hmm the thing is that the audio and video urls are different idk is there any other doc about this out there?

**Comment by rimthekid** [comment]
It actually only passes the video url in this [line](https://github.com/QuantumBadger/RedReader/blob/bda6f0c22aff93018b00b2774796f3682a572f77/src/main/java/org/quantumbadger/redreader/activities/ImageViewActivity.java#L1134)

**Comment by rimthekid** [comment]
Ok so I've managed to pass an hls url to vlc and play it! in this [commit](https://github.com/libre-tube/LibreTube/commit/c22224d541978effc375192c1ad165810e543dd4)

**Comment by Mennaruuk** [comment]
Wow, you've done did it! I just tested it, loving the "Open in VLC" button right under the video, and how it plays right after pressing it. This is a great step forward for LibreTube!!

**Comment by rimthekid** [comment]
I just love vlc so much I might even start using their sdk instead of exoplayer

**Comment by Bnyro** [comment]
Just press the `Open ...` button when playing a video!
