### ISSUE TITLE
Playlist menu is basically dead

### ISSUE THREAD

**Issue by alejandro-alzate** [libre-tube/LibreTube#6306]
### Steps to reproduce

1. pick a video
2. disable the auto-play button
3. open playlist selector (between) sponsor block and settings
4. click any video

### Expected behavior

Video should change to selected video

### Actual behavior

Video in playlist gets highlighted then nothing happens

### LibreTube version

0.24.0 - Initial version
0.25.2 - Current version with the bug as editing this

### Android version

LineageOS 20 (android 13)

### Other details

Demo video 0.24.0: https://www.youtube.com/watch?v=lKt68uPxehU
Demo video 0.25.2: https://www.youtube.com/watch?v=qAdS_ftzfOQ
Auto-play fix discovery: https://www.youtube.com/watch?v=g84bLMcEdgA

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by alejandro-alzate** [comment]
I noticed that the issue was tagged can't reproduce
so here i attach a video showcasing it: https://www.youtube.com/watch?v=qAdS_ftzfOQ

**Comment by alejandro-alzate** [comment]
I just noticed that turning on the auto play feature fixes it which is weird.
https://www.youtube.com/watch?v=g84bLMcEdgA

**Comment by alejandro-alzate** [comment]
Hello @Bnyro I was curious if I can get the latest apk with this fix applied.
Seems that the github action is still stuck on `0.25.2`

You can use me as cannon meat on the way there. y'know making you aware of any new bugs popping up and such.

**Comment by akano12** [comment]
@alejandro-alzate
https://github.com/libre-tube/NightlyBuilds

**Comment by alejandro-alzate** [comment]
understood, g'night sir.
I'm installing it now.
I'll let you know if I find funny bussiness.

**Comment by alejandro-alzate** [comment]
wh- huh it says that is `0.25.2 (57)`
Also on install it did not kill the pip.

**Comment by akano12** [comment]
> wh- huh it says that is `0.25.2 (57)`
> Also on install it did not kill the pip.

It's a debug build, separate application that contains bug fixes and feature that aren't released in stable build yet

**Comment by alejandro-alzate** [comment]
Understood, just got a bit thrown off.
Also thoughtful touch giving them a different icon hue, otherwise I wouldn't be able to tell them apart.

But as of writing of this, the fix is functional and have not seen any other bug.
