### ISSUE TITLE
Displaying the title in landscape format

### ISSUE THREAD

**Issue by florian-sabonchi** [libre-tube/LibreTube#631]
![Screenshot_20220627-170838](https://user-images.githubusercontent.com/54689374/175973504-75e1b680-34d8-4b37-9237-4192305f7531.png)
Display the title in landscape format as in the original Youtube app

![IMG_20220627_171337_882](https://user-images.githubusercontent.com/54689374/175974541-58627213-29cc-46a2-8319-0b8180154f44.jpg)

**Comment by Bnyro** [comment]
good idea :)
I was sure there's missing sth on the top but I didn't know what xD

**Comment by Florian-Sabonchi** [comment]
Hello, thanks for working on i wanted to do that but perhaps there is another issue to work on it

**Comment by Bnyro** [comment]
Ohh, I'm sorry, I didn't want to steal your job.
Please write next time that you want to do the job :)
Cheers
