### ISSUE TITLE
Buffering bar on downloaded videos not portraying the actual status of download

### ISSUE THREAD

**Issue by CelianGdfrd** [libre-tube/LibreTube#6312]
### Steps to reproduce

1. Download a video to the end
2. Play the video
3. Observe the buffer bar

### Expected behavior

Bar should be coloured to the actual length of downloaded video, not an arbitrary number.

### Actual behavior

Arbitrary amount of buffering is displayed.

### LibreTube version

0.24.0

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Share a recording if possible

**Comment by CelianGdfrd** [comment]
![Screenshot_20240806-141308_LibreTube](https://github.com/user-attachments/assets/79c06c15-518c-452a-87b1-12ad4c60fe0e)
![Screenshot_20240806-141315_LibreTube](https://github.com/user-attachments/assets/3c07da86-d931-4d1f-88c1-3c038a130606)

This video is fully downloaded. Watch the progress bar.
I believe it keeps applying the rule of buffering limitation in the settings (I've set it to 450s)

**Comment by Bnyro** [comment]
What's shown here is the amount of the video that's loaded into the RAM. The player doesn't load the full video from the disk into the RAM obviously, so seeking to a point that's not preloaded might take a short loading time on devices with slow emmc storage. Hence working as expected.
