### ISSUE TITLE
can't play video with my vpn. need to prouve I'm not a bot

### ISSUE THREAD

**Issue by Nours42** [libre-tube/LibreTube#6316]
### Steps to reproduce

If I use the app with my vpn I see "error prouve you're not a..." I suppose bot but can't be sure.
If I use it without, no problem.

### Expected behavior

Play video

### Actual behavior

Doesn't work and display error message 

### LibreTube version

0.24.0

### Android version

android 14

### Other details

Cyberghost vpn

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/6116

And change instance
