### ISSUE TITLE
error: unable to open video

### ISSUE THREAD

**Issue by kazekawa2** [libre-tube/LibreTube#6318]
### Steps to reproduce

1.open the app
2. try to open any video
3. Got error:sign in to confirm that you're not a bot
4. try to log out and log in
5. failed
6. repeat step 4
7. failed repeatedly

### Expected behavior

click the video
what should have happened "video open and play

### Actual behavior

Got error:sign in to confirm you're not a bot

### LibreTube version

0.24.0

### Android version

Android12

### Other details

no other detail

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/6116
And chand instance

**Comment by kazekawa2** [comment]
thx
