### ISSUE TITLE
Kavin Rocks mising

### ISSUE THREAD

**Issue by Lio-gif** [libre-tube/LibreTube#6319]
### Steps to reproduce

1.Go to Instanz
2.Go to Instanz list 
3.kavin Rocks Not there

### Expected behavior

Abel to Chose kavin rocks

### Actual behavior

Not on the list

### LibreTube version

0.24

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Is this a serious issue?
