### ISSUE TITLE
Subscriptions and Playlists Don't Load

### ISSUE THREAD

**Issue by BatDevil** [libre-tube/LibreTube#6322]
### Steps to reproduce

Example :
1. open LibreTube 
2. Loads for a while
3. doesn't open subscriptions/featured tap or playlists i made

i tried every instance for both login and viewership, didn't work

### Expected behavior

Not buffering tor too long and showing me my subscriptions

### Actual behavior

Doesn't do any of that

### LibreTube version

0.24.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Everything works for me, you obviously didn't try all instances.

**Comment by BatDevil** [comment]
i did, which ones work for you?

**Comment by BatDevil** [comment]
i managed to solve the issue but sadly can't access my subscriptions on Kavin Rocks instance.
