### ISSUE TITLE
When playing a downloaded video from Home screen/Subscriptions, offer to play it online or locally

### ISSUE THREAD

**Issue by CelianGdfrd** [libre-tube/LibreTube#6325]
### Describe your suggested feature

I'd like, when I download a video, to be able to play it locally somewhere else than in the Downloaded tab. So I'd like LibreTube to identify when I try to play a video that is downloaded, and offer me to play it locally.

### Other details

There should also be a good sync of watch position within the video, between the local and the online version.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Well, and how shoud this be presented to the user? With a dialog asking you to play the video from downloads instead?

**Comment by CelianGdfrd** [comment]
Yeah, that's what I thought : when you try to play a downloaded video from homepage or subscription tab, get a popup that says "A local version of this video is available", compare the two options, and offer to play it online or locally, with an option to set this choice as default.

**Comment by PhrozenByte** [comment]
@CelianGdfrd Can you think of any reason not to just always play the local copy of the video? The only reason I can think of is audio/video quality, but instead of a popup it could be as simple as LibreTube starting the video with the downloaded audio/video quality, but still allowing the user to switch quality what then causes LibreTube to switch to the online source.

**Comment by slimshady045** [comment]
> @CelianGdfrd Can you think of any reason not to just always play the local copy of the video? The only reason I can think of is audio/video quality, but instead of a popup it could be as simple as LibreTube starting the video with the downloaded audio/video quality, but still allowing the user to switch quality what then causes LibreTube to switch to the online source.

SAME AS GRAYJAY

**Comment by CelianGdfrd** [comment]
> @CelianGdfrd Can you think of any reason not to just always play the local copy of the video? The only reason I can think of is audio/video quality, but instead of a popup it could be as simple as LibreTube starting the video with the downloaded audio/video quality, but still allowing the user to switch quality what then causes LibreTube to switch to the online source.

I was also thinking about different quality, yes.

**Comment by angolo** [comment]
> ### Describe your suggested feature
> I'd like, when I download a video, to be able to play it locally somewhere else than in the Downloaded tab. So I'd like LibreTube to identify when I try to play a video that is downloaded, and offer me to play it locally.
> 
> ### Other details
> There should also be a good sync of watch position within the video, between the local and the online version.
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I will fill out all of the requested information in this form.


Hi, I'm working on this feature.

I think that this shouldn't be enabled by default but by user input, could you tell me where, in the settings screen, this option could be put and the message to show to the user ?

**Comment by CelianGdfrd** [comment]
Probably in Settings > Player > Default settings, add a line "Play downloaded videos from local file". Options would be always/never, and maybe a way to ask the user every time.
