### ISSUE TITLE
Updating app leads to package conflict error

### ISSUE THREAD

**Issue by Valvalvalvalvalvalvl1** [libre-tube/LibreTube#6328]
### Steps to reproduce

1. Open LibreTube
2. Check for updates
3. Click download
4. Download app-arm64-v8a-release.apk or app-armeabi-v7a-release.apk (I tried both just in case)
5. Click Update

### Expected behavior

The app should update. 

### Actual behavior

I received an error message stating "App not installed as package conflicts with an existing 
package."
![Screenshot_20240808_055228_Package installer](https://github.com/user-attachments/assets/4011e542-dc6f-4c82-bd70-75d4bfbfd1f4)

### LibreTube version

0.23.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You probably installed the app from F-Droid. That build has a different signature, so you can only update the app via F-Droid and not from GitHub.
