### ISSUE TITLE
App Version

### ISSUE THREAD

**Issue by brnwlshubh** [libre-tube/LibreTube#6341]
### Describe your suggested feature

Add Update Details like Commit No. In Nightly Build.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/4693#issuecomment-1705586937

https://github.com/libre-tube/LibreTube/issues/4693#issuecomment-1707243265

Not sure if Bnyro have an easy implementation for this

**Comment by brnwlshubh** [comment]
![SmartSelect_20240811_161056_CloudStream Beta](https://github.com/user-attachments/assets/93450e28-ef87-448e-9947-cc5985f1271d)

It is an example of Cloudstream with version,commit and date.

**Comment by Bnyro** [comment]
PRs welcome, but not planned from my side.
