### ISSUE TITLE
looped video list

### ISSUE THREAD

**Issue by sineptic** [libre-tube/LibreTube#6342]
### Steps to reproduce

1. open any channel
2. scroll videos and watch on dates

### Expected behavior

this should list all videos and dont repeat yourself

### Actual behavior

![Screenshot_20240811_193325_LibreTube](https://github.com/user-attachments/assets/6d835229-fd91-489a-a732-8b6ec6cf5e17)
![Screenshot_20240811_193254_LibreTube](https://github.com/user-attachments/assets/40be83fa-bd4b-4dbf-b5f4-08d4108e2126)

and its loops in only one place, but infinitely(or how write it)

### LibreTube version

0.24.0

### Android version

13, samsung

### Other details

This bug occurs on all channels and all sources

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Already fixed in debug builds
