### ISSUE TITLE
Loop scrolling problems with video feed on any channel

### ISSUE THREAD

**Issue by agevlakh** [libre-tube/LibreTube#6345]
### Steps to reproduce

1. Open any channel page
2. Choose videos
3. Start fast scrolling
4. See infinity loop same video scrolling 

### Expected behavior

Videos are loaded in order, and the same videos are not played over and over again

### Actual behavior

The videos that have already loaded start to repeat cyclically when scrolling quickly, until at some point the scrolling goes down and the next batch of videos loads.

### LibreTube version

0.24.0

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/pull/6273
