### ISSUE TITLE
Getting issue "log in to confirm you're not a bot" 

### ISSUE THREAD

**Issue by Tintin232** [libre-tube/LibreTube#6348]
### Steps to reproduce

Trying to watch any video, and I get this error 
![Screenshot_20240813_000558_LibreTube](https://github.com/user-attachments/assets/c68adbb2-6f41-49b5-9105-098fd91493d9)

### Expected behavior

Be able to watch the video 

### Actual behavior

Can't watch the video 

### LibreTube version

v0.24.0

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/6116
