### ISSUE TITLE
Can't play any video

### ISSUE THREAD

**Issue by Tunsinasro** [libre-tube/LibreTube#6349]
### Steps to reproduce

Open the app and choose any video

### Expected behavior

The video should start playing normally 

### Actual behavior

A message saying "got error you should sign in to confirm that you are not a robot" appears and nothing happens

### LibreTube version

0.24.0

### Android version

Android 13

### Other details

I tried every instance on the list, no luck, I should also add that this problem used to occur previously but goes aways in a few minutes or if i changed the instance, this times it been more then 12 hours.

https://github.com/user-attachments/assets/a5dd5f0c-64ad-4ab8-81d3-5d01e7d663b3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/issues/6116
