### ISSUE TITLE
An error "Sign in to confirm that you're not a bot" shows all the time

### ISSUE THREAD

**Issue by KostiukI** [libre-tube/LibreTube#6350]
### Steps to reproduce

1. Open LibreTube, last available version
2. Use any instance available in the list, neither of them work
3. Play any video, neither works
![photo_2024-08-13_17-11-47](https://github.com/user-attachments/assets/86d9bd7f-c7fa-44d6-853c-8d2a0e45984f)

### Expected behavior

Videos should be played normally

### Actual behavior

Impossible to use youtube at all

### LibreTube version

0.24.0

### Android version

12

### Other details

Earlier it was happening only on some instances, mostly kavin.rocks , and switching the instance helped. Now for several days already I can't start a video on at least one instance from the list. I tried clearing data of the app, totally reinstalling it as well, nothing helps.
Please don't just link another issues about this problem, like [#6116](https://github.com/libre-tube/LibreTube/issues/6116), I had to create this one, because the previous one was closed without any info of how to resolve the problem.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#6116 basically says everything: you can't fix it, the instance you chose is blockrd by YouTube.

Host your own Piped instances or try to find one that's not blocked.

**Comment by KostiukI** [comment]
I've tried it on PC, and suddenly the same instances work through the web. So it's a question why they're not working through LibreTube

**Comment by Bytezz** [comment]
> I've tried it on PC, and suddenly the same instances work through the web. So it's a question why they're not working through LibreTube

Came here to say the same thing: on the web those instances work but on LibreTube none of them works even with piped proxy disabled.  
In audio only mode there's an infinite loading, while by opening as a video it says "sign in to confirm you are not a bot" or "IOS player error". I've tried every listed instance both logged out and signed in.

**Comment by wipedlifepotato** [comment]
Try to disable proxy piped

**Comment by LuMaF5** [comment]
Having the same problem now. Tried different settings but nothing seems to work.

**Comment by MatteoAlberghini** [comment]
This seems to be a issue with libretube specifically, I have my own selfhosted piped and I connect it to libretube without issues but sometimes I get the bot error message.

if I access my own instance via browser that never happens, even trough the same device, on the same network.
