### ISSUE TITLE
Implement Automatic Instance Switching for Video Playback Failures

### ISSUE THREAD

**Issue by dhuschde** [libre-tube/LibreTube#6353]
### Describe your suggested feature

If we are not logged in or use another instance for authentication, we should have the option to automatically use other instances if the current one fails.

For example, if we are using the official instance and encounter an error while loading a video (e.g., "Log in to confirm you're not a bot"), LibreTube should automatically try to fetch the video from another instance. This process should repeat until we can play the video or we reach the end of the list of instances.

### Other details

To reduce stress on the first instance on the list, you should randomize the list before going through it.

I think this feature would be very useful right now, considering how often instances currently fail to load Videos due to #6116.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/issues/4184#issuecomment-1626354789
