### ISSUE TITLE
Besides aren't playing 

### ISSUE THREAD

**Issue by nascentphilosopher** [libre-tube/LibreTube#6354]
### Steps to reproduce

Non of the instances are responding 
![Screenshot_20240814-145644](https://github.com/user-attachments/assets/d20ab503-1b89-4b0f-9cab-9ddbed47aebc)
![Screenshot_20240814-145715](https://github.com/user-attachments/assets/6a481b67-6e8e-4f0b-a395-15d46c5b1d91)

### Expected behavior

Videos should play properly
![Screenshot_20240814-150115](https://github.com/user-attachments/assets/f12ca993-3730-4c6c-8069-56eb59486587)

### Actual behavior

Nothing is playing evening after changing instances!!

### LibreTube version

V0.24.0

### Android version

Android 12 

### Other details

![Screenshot_20240814-150115](https://github.com/user-attachments/assets/c9088f21-ee10-416f-8e69-9502da52b459)
![Uploading Screenshot_20240814-145715.png…]()

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/issues/6116
