### ISSUE TITLE
Video not playing 

### ISSUE THREAD

**Issue by taharimbadhon** [libre-tube/LibreTube#6358]
### Steps to reproduce

1.Click any video
2.Not playing
3.showing "sign to confirm that you are not a bot"  

### Expected behavior

I live in Bangladesh.I can't play Videos.I tried all instances but failed.it shows sign to confirmyou are not a bot   

### Actual behavior

When i click on any video it says "Sign in to confirm that you are not a bot"

### LibreTube version

0.24.0

### Android version

11

### Other details

It happens with the older versions 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by MadMan247** [comment]
See #6116 
Not a libretube error. Maybe piped? For now, just blame youtube.
Sometimes, if I spam a video long enough it'll decide to just work. Sometimes takes a long time.

**Comment by Tunsinasro** [comment]
I have the same problem for about a week now, changing the instance didn't help
Piped in the browser works fine and NewPipe also works fine
