### ISSUE TITLE
AAP isn't working!?

### ISSUE THREAD

**Issue by nascentphilosopher** [libre-tube/LibreTube#6359]
### Steps to reproduce

Non of the videos are playing!!

### Expected behavior

Video should play seemlessly

### Actual behavior

Nothing is playing 

### LibreTube version

v0.24.0

### Android version

Android 12 

### Other details

Prompting sign in again!?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
#6116
