### ISSUE TITLE
Bug: Strange black bubble appears on the last build

### ISSUE THREAD

**Issue by ScriptSlayer0** [libre-tube/LibreTube#6368]
### Steps to reproduce

When I'm scrolling in the subscription page a strange bubble appears.
(Switching instances still shows)

### Expected behavior

Normal visualization without a black bubble

### Actual behavior

A black bubble appears on the subscription page

https://github.com/user-attachments/assets/5018d6b1-43f2-46c8-aa7b-0247af952f2c

### LibreTube version

Last build

### Android version

Android 13 Realme GT master Edition

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ScriptSlayer0** [comment]
It's like #5882

**Comment by Bnyro** [comment]
Now tracked at https://github.com/libre-tube/LibreTube/issues/6313
