### ISSUE TITLE
Are there any custom instances that bypasses "sign-in to confirm you are not a robot" crap?

### ISSUE THREAD

**Issue by ogipaki1** [libre-tube/LibreTube#6369]
### Steps to reproduce

Step 1: Choose any Piped instance that is offered on list.
Step 2: Choose any video.
Step 3: "sign-in to confirm you are not a robot" error appears.

### Expected behavior

Video should play.

### Actual behavior

Shows "sign-in to confirm you are not a robot" error and doesn't play video

### LibreTube version

0.24.0

### Android version

Android 10

### Other details

Every once in an while, it plays video or two and then same error appears.
I know there's already an issue similar to this one: #6116
I just want to know are there any custom instances that bypasses that error because i heard it isn't app's fault but server's.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Likely all instances are affected after a certain amount of users uses it at the same time.

I know an instance that's still working (which is not public and I won't share) that still works, so self-hosting Piped for yourself will likely still work.

**Comment by ogipaki1** [comment]
Ok i will see thanks.
