### ISSUE TITLE
Change option to open with vlc to open with external player

### ISSUE THREAD

**Issue by DNDEBUG** [libre-tube/LibreTube#637]
### Describe your suggested feature

Change the option to open the video with VLC to be able to open the video with any media player

### Other details

VLC isn't the only video player for android that supports youtube
limiting it to vlc is a bad idea

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Any idea what we could rename the option to?

**Comment by GilesMunn** [comment]
Perhaps "Open..."? With a matching generic icon of a video?
