### ISSUE TITLE
Disable piped proxy setting turned on, but still tries to fetch videos from instance instead of Youtube

### ISSUE THREAD

**Issue by Hujair** [libre-tube/LibreTube#6372]
### Steps to reproduce

1. go to settings
2. select instance
3. turn on "Disable piped proxy"
4. try to play a video
5. gets error: "Sign in to confirm that you're not a bot"

### Expected behavior

fetch video from YouTube directly instead of yt piped instances.

### Actual behavior

tries to load video from the instance and gets error in return.

### LibreTube version

0.24.0

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/6366#issuecomment-2294846881
