### ISSUE TITLE
Got error: "Sign in to confirm that you're not a bot" when watching videos

### ISSUE THREAD

**Issue by Raj2032** [libre-tube/LibreTube#6376]
### Steps to reproduce

Load any video using any instance and I keep getting the error:

"Got error: "Sign in to confirm that you're not a bot" when watching videos"

### Expected behavior

Should load video

### Actual behavior

![image](https://github.com/user-attachments/assets/2233dca4-bcef-40a1-8585-06251edfbf2f)

### LibreTube version

0.24.0

### Android version

Android 9 - Samsung Galaxy S8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by slimshady045** [comment]
no apparent solution

**Comment by Raj2032** [comment]
Is this happening to everyone or is it just me?

Does this happen all the time to others or sometimes?

**Comment by slimshady045** [comment]
a lot of people are complaining.
makes the app unusable.
i posted about newpipe option.
but turned down.

**Comment by Raj2032** [comment]
@slimshady045 why is that?

**Comment by SyCoREAPER** [comment]
Seeing as this hasn't been fixed in over two weeks. I see no use for this app. Facing the same issue. Non-Funtional. Not to mention I learned the hard way that registering a piped account wipes out the local subscriptions. Idiotic design.
