### ISSUE TITLE
Move to invidious

### ISSUE THREAD

**Issue by Raj2032** [libre-tube/LibreTube#6392]
### Describe your suggested feature

piped network seems to no longer work due to Google prompting user to sign in to prove you are not a bot issue.

[Invidious](https://docs.invidious.io/instances/) on my browser seems to work without any issues. Is it possible LibreTube can move to invidious or give a different option to use invidious over piped network?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Raj2032** [comment]
@1sopropanol What is this?

**Comment by Raj2032** [comment]
@Bnyro Yes I understand but your suggestion also reduces privacy, hence my suggestion for invidious.

**Comment by Totallynotmwa** [comment]
Clipious is what your prob looking for.

**Comment by waifucon** [comment]
Please support it!
