### ISSUE TITLE
[FEATURE] Google Account Sign in.

### ISSUE THREAD

**Issue by Killercat103** [libre-tube/LibreTube#64]
**Optional ability to sign in with your Google accounts.**
I know it may sound contradictory to the ibtebtions of the app. However, I think having the features you would get would attract a larger user base who wants to improve their privacy by removing client side trackers instead of the official app.

Maybe add a warning which says logging into Google will compromise their privacy.

**Comment by rimthekid** [comment]
We were adding import subscription from youtube account just like how [newpipe does it](https://newpipe.net/FAQ/tutorials/import-export-data/#import-youtube)

**Comment by Killercat103** [comment]
> We were adding import subscription from youtube account just like how [newpipe does it](https://newpipe.net/FAQ/tutorials/import-export-data/#import-youtube)

Well I wasn't talking about importing but actaually using your Google account. As much as I value privacy it's hard giving up recommended content because the populare videos are in most cases garbage. There's also the ability to comment which I would guess some people value.
I know using an unofficial client wont help much when you're logged in. However, I still think small steps in the right direction would be beneficial. At least users of Libretube won't be affected by Googles Firebase Analytics client side.

**Comment by IceDBorn** [comment]
@Killercat103 You just don't get the goal of this project, this is not a Vanced clone and it won't turn into one.

**Comment by Killercat103** [comment]
@IceDBorn
If I wanted it to be a vanced clone I would have mentioned advanced adblock or sponsorblock. My problem is that I'm hmquite frankly addicted to the recommendations of youtube but I can't find any clients which are open-source or does not contain client side trackers on top of the tracking Youtube has server side.

**Comment by IceDBorn** [comment]
@Killercat103 Actually they will be implementing these at some point, the google login is out of the question though. The whole point of this project is to have a de-googled youtube experience as close to the original experience.

**Comment by Killercat103** [comment]
Apparently not going to happen :(

**Comment by Killercat103** [comment]
I can't mark this as not going to be implemented so I'll just close it. :/

**Comment by rimthekid** [comment]
We could do a LibreTube extended version that add these stuff too for the average users

**Comment by VexfulNiko** [comment]
Would be good lmao (I pay for premium in YouTube so it would be pretty nice to take advantage of that in some way)

**Comment by NiffirgkcaJ** [comment]
This looks better than most open-source clients of YouTube, and it's such a shame that it doesn't support Google accounts. MicroG could help, but I'm not sure.
