### ISSUE TITLE
Downloads not working with the new local extractor 

### ISSUE THREAD

**Issue by lu4p** [libre-tube/LibreTube#6402]
### Steps to reproduce

1. Enable the new workaround to play videos
2. Try to download any video

### Expected behavior

Video should download 

### Actual behavior

![Screenshot_20240823_221325_LibreTube](https://github.com/user-attachments/assets/4a12ae5a-5472-4923-bbf8-f10857274bf1)

Video can't be downloaded because no download quality can be chosen.

### LibreTube version

0.25.1

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Ehab-d** [comment]
I can confirm the same behavior. The download window can load the video name, but fails to load the video and audio. Anyway we now have the external download function :D

**Comment by CodeDoctorDE** [comment]
I also can confirm it, no audio, no video, but playback works.
What do you mean with external download function?

**Comment by Ehab-d** [comment]
> What do you mean with external download function?

You can set LibreTube to download videos using an external download provider like [Seal](https://github.com/JunkFood02/Seal).
The option can be found in Settings -> Advanced -> Downloads - and enter `com.junkfood.seal`

**Comment by slimshady045** [comment]
> > What do you mean with external download function?
> 
> You can set LibreTube to download videos using an external download provider like [Seal](https://github.com/JunkFood02/Seal). The option can be found in Settings -> Advanced -> Downloads - and enter `com.junkfood.seal`

seal supports pause/play?

**Comment by Rahulrzx** [comment]
Downloads are still not working

**Comment by Ehab-d** [comment]
> Internal Downloader is still not working

Lol. You have to wait the next release or try the unstable [Nightly Builds](https://github.com/libre-tube/NightlyBuilds).

**Comment by GitAlexToTheGreek** [comment]
> > What do you mean with external download function?
> 
> You can set LibreTube to download videos using an external download provider like [Seal](https://github.com/JunkFood02/Seal). The option can be found in Settings -> Advanced -> Downloads - and enter `com.junkfood.seal`

Thank you! 🫡
