### ISSUE TITLE
System share menu lags due to LibreTube shortcuts (Xiaomi 14)

### ISSUE THREAD

**Issue by aaasajsldfjsladkfj** [libre-tube/LibreTube#6404]
### Steps to reproduce

1. Install the app (Xiaomi 14).
2. Open the share menu in any app.
3. Scroll to the LibreTube shortcuts.

### Expected behavior

The list of applications in the share menu should scroll smoothly.

### Actual behavior

The app list in the share menu lags when LibreTube shortcuts appear.

### LibreTube version

0.25.1

### Android version

Android 14 (HyperOS 1.0.12.0)

### Other details

I apologize for my bad English.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by aaasajsldfjsladkfj** [comment]
Can you add the ability to customize the share menu shortcuts to the settings? With the ability to leave only the necessary shortcuts or completely disable shortcuts from the system share menu?

**Comment by Bnyro** [comment]
That's not LibreTube's fault, we don't control the share menu.

> Can you add the ability to customize the share menu shortcuts to the settings? With the ability to leave only the necessary shortcuts or completely disable shortcuts from the system share menu?
>
That's unnecessary and out of scope.

**Comment by aaasajsldfjsladkfj** [comment]
The main problem is not in setting up shortcuts in the share menu. The problem is that on MIUI/HyperOS, because of the LibreTube shortcuts, the system share menu lags a lot. I checked on other phones with MIUI/HyperOS, the problem repeated. Xiaomi 14, Poco F3, Redmi 10 Pro, Poco X3 Pro. This is a serious bug that affects the smoothness of operation outside of the application.

**Comment by Bnyro** [comment]
Report it to Xiaomi then, it's absoutely not LibreTube's fault if Xiaomi fails to implement the share dialog properly.

**Comment by aaasajsldfjsladkfj** [comment]
> Report it to Xiaomi then, it's absoutely not LibreTube's fault if Xiaomi fails to implement the share dialog properly.

«Share menu» stops lagging if you remove these resources from the apk.
![Share](https://github.com/user-attachments/assets/eabe8434-1285-4e47-ae79-d6d53a4cc46b)
