### ISSUE TITLE
Subscriptions without piped instances

### ISSUE THREAD

**Issue by aaasajsldfjsladkfj** [libre-tube/LibreTube#6406]
### Describe your suggested feature

I apologize in advance for my bad English.
Currently, not all videos are displayed in the subscription feed. This is due to instances. Is it possible to make the videos in the subscription feed take directly from YouTube? So that all new videos in the feed are displayed, like in NewPipe.
I understand that this will have a negative impact on anonymity, but is it possible to add such an optional setting?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's currently not planned even though it would be possible in theory.

In case you want to have that feature, please use NewPipe.

**Comment by aaasajsldfjsladkfj** [comment]
Is there any way to have all current subscriptions displayed in the LibreTube feed?

**Comment by FarisZR** [comment]
Piped has been struggling for a long time, IMO the way to go is just to do everything locally.
I like to use Libretube because it has the best UI/UX in the space.

**Comment by aaasajsldfjsladkfj** [comment]
> In case you want to have that feature, please use NewPipe.

I miss the functionality in NewPipe, and LibreTube has everything I need, but the only thing missing is the correct display of subscriptions. I really want to go back to LibreTube, but the correct display of subscriptions in the feed is very important to me. Maybe there is another way to check new videos on channels independently of piped servers?
