### ISSUE TITLE
Import watch history from Youtube.

### ISSUE THREAD

**Issue by PapiJalopy** [libre-tube/LibreTube#6408]
### Describe your suggested feature

Not sure if this has been discussed before, I searched for it in closed and open issues and didn't find any mention of it. Sorry if i missed it.

Feature request for importing Youtube watch history.

I see the current in app watch history implementation has certain "keys" such as "uploadDate", "uploader", "uploaderUrl", "uploaderAvatar", "thumbnailUrl" and "duration watched" 

The Youtube .csv only contains some basic "keys" - "header", "url", "titleURL", "title" and "name". 

Idk if certain parts can be omitted and still have a functional watch history or if this would require refactoring the entire watch history feature.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Could you please share an example file? (It's sufficient if you remove anything but a single video)

**Comment by Familex** [comment]
@Bnyro json option looks like this:

```json
[{
  "header": "YouTube",
  "title": "Watched MASTER BOOT RECORD - CPU",
  "titleUrl": "https://www.youtube.com/watch?v\u003dRNOUJZlR0p4",
  "subtitles": [{
    "name": "MASTER BOOT RECORD",
    "url": "https://www.youtube.com/channel/UCEVndLRqBDNcZhBdWo5oepg"
  }],
  "time": "2024-09-03T17:58:45.124Z",
  "products": ["YouTube"],
  "activityControls": ["YouTube watch history"]
},{
  "header": "YouTube",
  "title": "Watched ​",
  "titleUrl": "https://www.youtube.com/watch?v\u003daUG--f5qZjo",
  "subtitles": [{
    "name": "made from dreams",
    "url": "https://www.youtube.com/channel/UCI7ZJqTa3KZ_BzU24O3ex8w"
  }],
  "time": "2024-09-03T16:14:01.445Z",
  "products": ["YouTube"],
  "activityControls": ["YouTube watch history"]
}]
```

**Comment by Bnyro** [comment]
That export would be importable without any thumbnails just fine, but if we want the thumbnails we would need to do one API request per video to get additional info such as the thumbnail, duration and channel avatar which will make the import very slow and unreliable.

Alternatively, we can "guess" the thumbnail URLs such as `https://img.youtube.com/vi/{videoId}/mqdefault.jpg` which will probably work for 99% of the videos.

That way everything would be there except for
- channel avatars
- video duration

If that's okay for you, I'll probably implement that before the next release - otherwise I think we should drop this feature because I doubt that doing one API request per video import will work well and would be worth it, we've already had several issues doing so when importing playlists.

**Comment by PapiJalopy** [comment]
Honestly that sounds fine, if you wanna give it the green light I feel like that should be sufficient.

**Comment by Bnyro** [comment]
The timestamp YouTube provides is the time you watched the video - not the time it got uploaded, so we're missing that field too :/

So we can import (tested with your sample)
- videoId
- video title
- uploader name
- uploader channel url
- thumbnail (by guessing)

**Comment by Bnyro** [comment]
When importing what?

**Comment by Bnyro** [comment]
I've successfully tested the file above.

**Comment by Familex** [comment]
@Notesure did you change the format before exporting?

![image](https://github.com/user-attachments/assets/d2cd15dd-0a74-4e9f-bab3-456fd5befd38)

**Comment by Bnyro** [comment]
It only supports JSON imports, not HTML.

**Comment by Bnyro** [comment]
> JSON input: <title>Fəaliyyət T...
>
That's HTML what you inserted there ...

**Comment by Familex** [comment]
@Bnyro I just tried it and I have the same error... It turns out, that for private videos the scheme is like this. Sorry for misleading

```json
{
  "header": "YouTube",
  "title": "Watched https://www.youtube.com/watch?v\u003d2TXxQQ9ImKU",
  "titleUrl": "https://www.youtube.com/watch?v\u003d2TXxQQ9ImKU",
  "time": "2023-02-10T21:58:42.390Z",
  "products": ["YouTube"],
  "activityControls": ["YouTube watch history"]
}
```

**Comment by Familex** [comment]
I used [genson](https://pypi.org/project/genson/) on my watch-history.json file and it produced this json schema: [schema.json](https://github.com/user-attachments/files/17160930/schema.json)

**Comment by Bnyro** [comment]
>  I just tried it and I have the same error... It turns out, that for private videos the scheme is like this. Sorry for misleading
>
I assume we should just skip all private videos? They can't be watched via LibreTube anyways.

**Comment by Familex** [comment]
> I assume we should just skip all private videos

I think so, anyway, there is no information about them in the file except for the link

**Comment by Familex** [comment]
cool, I successfully imported my watch history
