### ISSUE TITLE
Personalized home feed

### ISSUE THREAD

**Issue by Adithyan007hack** [libre-tube/LibreTube#641]
### Describe your suggested feature

It would be nice if the home tab will suggest personalized video based on your watched videos and searches insted of the trending video based on the region 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We will never collect any user data, so showing personalized content will never be possible.
