### ISSUE TITLE
Unable to Download Private Playlist with Third-Party Downloaders in LibreTube Nightly Build

### ISSUE THREAD

**Issue by akashsriramganapathy** [libre-tube/LibreTube#6410]
In the LibreTube nightly build, attempting to download a playlist using third-party downloaders like Seal and YTDLnis fails. While downloading a single video works fine, trying to download an entire playlist results in an invalid link being passed to the downloader, such as https://www.youtube.com/playlist?list=6. This causes the downloader to throw an error. The stable version handles this smoothly by passing each video link individually to the downloader.

### Steps to reproduce

1. Open LibreTube nightly build.
2. Attempt to download a playlist using a third-party downloader like Seal or YTDLnis.
3. Observe the invalid link that is generated and passed to the downloader.
![Screenshot_20240826-013052_YTDLnis](https://github.com/user-attachments/assets/dc02f9a9-880a-418a-9c57-dc76cc288642)

### Expected behavior

The playlist should be processed correctly, and each video's link should be passed individually to the downloader, similar to how it functions in the stable version.

### Actual behavior

An invalid link (e.g., https://www.youtube.com/playlist?list=6) is passed to the downloader, causing it to fail.
```
WARNING: [youtube:tab] HTTP Error 404: Not Found. Retrying (1/3)...
WARNING: [youtube:tab] HTTP Error 404: Not Found. Retrying (2/3)...
WARNING: [youtube:tab] HTTP Error 404: Not Found. Retrying (3/3)...
WARNING: [youtube:tab] Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>). Giving up after 3 retries
WARNING: [youtube:tab] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube:tab] HTTP Error 400: Bad Request. Retrying (1/3)...
WARNING: [youtube:tab] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube:tab] HTTP Error 400: Bad Request. Retrying (2/3)...
WARNING: [youtube:tab] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube:tab] HTTP Error 400: Bad Request. Retrying (3/3)...
WARNING: [youtube:tab] YouTube said: ERROR - Request contains an invalid argument.
ERROR: [youtube:tab] 6: Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
```

### LibreTube version

Nightly build version

### Android version

Android 14

### Other details

This issue does not occur in the stable version of LibreTube, where playlist downloads work correctly with third-party downloaders.
![Screenshot_20240826-013015_YTDLnis](https://github.com/user-attachments/assets/6ee48d55-d31e-47df-ba3c-83d9f43815ba)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The issue you describe is about playlists you created yourself (private ones), not public ones.

We now support the `watch_videos` route for that (so does youtube), e.g. https://www.youtube.com/watch_videos?video_ids=KEwxr8I4Gl8,OrjM48L-n6I.

Seal doesn't seem to support this, so you should ask them to support it.
