### ISSUE TITLE
downloaded videos play only in full screen

### ISSUE THREAD

**Issue by agevlakh** [libre-tube/LibreTube#6426]
### Steps to reproduce

1 download video via libretube
2 play the video

### Expected behavior

the video not go in full screen automatically

### Actual behavior

the video in full screen only

### LibreTube version

0.25.1

### Android version

Android 14

### Other details

Hello. The videos I download via libretube only play in full screen. I would like it to be similar to normal playback from the network.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's the intended behavior.
