### ISSUE TITLE
two slashes in url when share video with custom server

### ISSUE THREAD

**Issue by agevlakh** [libre-tube/LibreTube#6427]
### Steps to reproduce

add custom piped server in settings and choose it
go to random video
push share button and choose your custom server

### Expected behavior

correct url 

### Actual behavior

incorrect url with // after domain name

### LibreTube version

0.25.1

### Android version

Android 14

### Other details

![Screenshot_20240830-172753](https://github.com/user-attachments/assets/61fac1df-d910-4a82-a7fd-50daf529290a)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by j-lakeman** [comment]
Hey I’m experiencing this in the most recent version again. Did the fix make it into the releases?

**Comment by Bnyro** [comment]
Are you sure? You're certain you got the most recent version and not the **most recent version F-Droid provides**?

**Comment by j-lakeman** [comment]
Sorry you're right. Installed the actual latest version and it's fixed.
BTW why is the F-Droid version outdated? Whose "responsibility" is that?

**Comment by Bnyro** [comment]
> Sorry you're right. Installed the actual latest version and it's fixed. BTW why is the F-Droid version outdated? Whose "responsibility" is that?
>
see https://github.com/libre-tube/LibreTube/issues/6867 and https://github.com/libre-tube/LibreTube/issues/6455#issuecomment-2482982475
