### ISSUE TITLE
flipping pages back and forth

### ISSUE THREAD

**Issue by slimshady045** [libre-tube/LibreTube#6429]
### Describe your suggested feature

After watching a few videos one after another, pressing the back button moves directly back to the home page.
Similar to browser pages, it should be able to flip back and forth.

### Other details

newpipe has it.
adding tabs feature can also help.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not planned, Android apps don't work like a browser...

**Comment by slimshady045** [comment]
but newpipe allows moving back through prev pages
