### ISSUE TITLE
Can't save videos to playlists 

### ISSUE THREAD

**Issue by MohamedEmary** [libre-tube/LibreTube#6431]
### Steps to reproduce

1. Login into piped account
2. Open a video and try to save it into existing or new playlist

### Expected behavior

The video should be added to the playlist

### Actual behavior

A toast appears saying `Failed :(`

https://github.com/user-attachments/assets/06ab707c-7b52-4c84-b0a9-bbd99ae1c9f2

### LibreTube version

0.25.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Read https://github.com/libre-tube/LibreTube/issues/6389

**Comment by MohamedEmary** [comment]
Thank you!
