### ISSUE TITLE
remember login and password

### ISSUE THREAD

**Issue by joshatt** [libre-tube/LibreTube#644]
### Describe your suggested feature

I realize there's no perfect instance, or a great instance does not excel forever. So I often switch instance. And every time I do this, I'll have to input login and password. I guess it'll be much convenient if login and password are remembered, I mean, it does not have to be "auto login", an "auto fill" will be wonderful as well.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We won't do that, we would have to save your password for it in the app which isn't secure because it can be accessed by other apps.
