### ISSUE TITLE
lag when using back gesture/button while video is playing

### ISSUE THREAD

**Issue by pokegamer5547** [libre-tube/LibreTube#6441]
### Steps to reproduce

1. Click on any video
2. Wait for it to play (dont enter full screen of video)
3. Use back button/gesture

### Expected behavior

It should minimize the player similarly to how swipe down on video player would.

### Actual behavior

When using back gesture/button it's having a weird lag before it miminizes the video player. It doesn't happen when using swipe down on video player.

### LibreTube version

0.25.1

### Android version

Android 14 Lineage OS 21

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Facing similar issue here and it's hard to reproduce, when exiting full-screen LT lags and search bar disappears.

**Comment by pokegamer5547** [comment]
Even in latest debug release, i'm still experiencing this issue, especially when i open any channel page and then play a video.
