### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [libre-tube/LibreTube#6455]
### Describe your suggested feature

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/7760790503#L379

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/f3e76bdabb388c9a7a197388af5222bb01d8a91c

**Comment by Bnyro** [comment]
According to https://github.com/TeamNewPipe/NewPipeExtractor/issues/1066, the dependency might need to be lowercased to `...teamnewpipe:NewPipeExtractor...` instead of `...TeamNewpipe:NewPipeExtractor...`, although it worked fine for me the other way yesterday, probably due to dependency caching.

In CI (gh actions) of this repository, it sometimes passes and sometimes fails with the error you mentioned, I love deterministic build failures...

**Comment by Bnyro** [comment]
Can you please try building from the latest commit (https://github.com/libre-tube/LibreTube/commit/34228f8493e3fec93f2ac24cf760c40ae2f3d862)?

This works for me now after clearing the IDEA caches.

**Comment by licaon-kter** [comment]
@Bnyro 1d4304ce13a12be6ccc0200df6b281fd93ae8354 builds fine locally

**Comment by licaon-kter** [comment]
hmmm https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/8396839770#L229

**Comment by licaon-kter** [comment]
New scanner code picked it up.

Just `exclude` does not make that dep FOSS, when it was build from non-FOSS code.

**Comment by IzzySoft** [comment]
@Bnyro for what it's worth, I try to build the versions since 1.25.1 and fail with the same error. With v0.26.0 it is

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeReleaseNativeLibs'.
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
   > Could not find com.github.teamnewpipe:NewPipeExtractor:6e3a4a6d9de61eafb73e7eb1b714847b5077856d.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/teamnewpipe/NewPipeExtractor/6e3a4a6d9de61eafb73e7eb1b714847b5077856d/NewPipeExtractor-6e3a4a6d9de61eafb73e7eb1b714847b5077856d.pom
       - https://repo.maven.apache.org/maven2/com/github/teamnewpipe/NewPipeExtractor/6e3a4a6d9de61eafb73e7eb1b714847b5077856d/NewPipeExtractor-6e3a4a6d9de61eafb73e7eb1b714847b5077856d.pom
       - https://jitpack.io/com/github/teamnewpipe/NewPipeExtractor/6e3a4a6d9de61eafb73e7eb1b714847b5077856d/NewPipeExtractor-6e3a4a6d9de61eafb73e7eb1b714847b5077856d.pom
     Required by:
         project :app
```

Not sure if maybe switching to the latest release including that commit (v0.24.3 was release 3 days ago) might solve that issue?

**Comment by Bnyro** [comment]
> Not sure if maybe switching to the latest release including that commit (v0.24.3 was release 3 days ago) might solve that issue?
>
Indeed it might be a good idea to switch to their latest stable release now, we previously required an unreleased version due to breaking changes from YouTube.

**Comment by Bnyro** [comment]
> New scanner code picked it up.
> 
> Just `exclude` does not make that dep FOSS, when it was built from non-FOSS code.
>
Thus we either need to drop that dependency or get the `Upstream Non-Free` anti-feature, right?

**Comment by IzzySoft** [comment]
> switch to their latest stable release

If you have a commit with that, and an APK built from that commit, feel free to give me a ping to check for RB again (that was why I tried to build, see [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients) – currently 354 apps (29.1%) are RB here already).

**Comment by licaon-kter** [comment]
@Bnyro drop ye

UpstreamNonFree means that _upstream has non free_ but F-Droid has all free because _it cleans up the non-free before building_

There's never a non-free to build from.

**Comment by Bnyro** [comment]
@IzzySoft https://github.com/libre-tube/LibreTube/commit/2d66a6abe9907080a7e1593fd006b9651fa1dd7c

**Comment by IzzySoft** [comment]
Thanks @Bnyro! If you have an APK built from that commit with your workflow, I can check if it's RB if you want (so we're prepared for the next release and can have the "green shield up").

**Comment by Bnyro** [comment]
Sure, I'll send you a build this evening :+1:

**Comment by Bnyro** [comment]
The universal apk: [app-universal-release.zip](https://github.com/user-attachments/files/17949813/app-universal-release.zip), built from https://github.com/libre-tube/LibreTube/commit/2d66a6abe9907080a7e1593fd006b9651fa1dd7c.

**Comment by IzzySoft** [comment]
That was not build from the commit you specified, @Bnyro :wink: 

```diff
  -rw-r--r--  0.0 unx       56 b-       51 defN 1981-01-01 01:01:02 a18242e2 META-INF/com/android/build/gradle/app-metadata.properties
- -rw-r--r--  0.0 unx      120 b-      118 defN 1981-01-01 01:01:02 fd28c097 META-INF/version-control-info.textproto
- -rw-r--r--  0.0 unx    11663 b-    11663 stor 1981-01-01 01:01:02 eaa2c9cd assets/dexopt/baseline.prof
+ -rw-r--r--  0.0 unx      120 b-      118 defN 1981-01-01 01:01:02 d47bfabf META-INF/version-control-info.textproto
+ -rw-r--r--  0.0 unx    11656 b-    11656 stor 1981-01-01 01:01:02 ee9c069c assets/dexopt/baseline.prof
  -rw-r--r--  0.0 unx      292 b-      292 stor 1981-01-01 01:01:02 227b7cba assets/dexopt/baseline.profm
  -rw-r--r--  0.0 unx  2422680 b-  1141281 defN 1981-01-01 01:01:02 57021890 classes.dex
  -rw-r--r--  0.0 unx   673128 b-   286620 defN 1981-01-01 01:01:02 58f32d66 classes2.dex
- -rw-r--r--  0.0 unx  5822264 b-  2621671 defN 1981-01-01 01:01:02 4f352f35 classes3.dex
+ -rw-r--r--  0.0 unx  5822272 b-  2621689 defN 1981-01-01 01:01:02 230e9716 classes3.dex
  -rw-r--r--  0.0 unx  5019616 b-  2382937 defN 1981-01-01 01:01:02 c9aacb69 lib/arm64-v8a/libcronet.119.0.6045.31.so
```

it was built from 9458b5597b4d2a1a0a6e9f506137aa8367479e1d according to `META-INF/version-control-info.textproto`. But I'm flexible, so let me try with that commit again…

```diff
  -rw-r--r--  0.0 unx      120 b-      118 defN 1981-01-01 01:01:02 fd28c097 META-INF/version-control-info.textproto
- -rw-r--r--  0.0 unx    11663 b-    11663 stor 1981-01-01 01:01:02 eaa2c9cd assets/dexopt/baseline.prof
+ -rw-r--r--  0.0 unx    11656 b-    11656 stor 1981-01-01 01:01:02 ee9c069c assets/dexopt/baseline.prof
  -rw-r--r--  0.0 unx      292 b-      292 stor 1981-01-01 01:01:02 227b7cba assets/dexopt/baseline.profm
  -rw-r--r--  0.0 unx  2422680 b-  1141281 defN 1981-01-01 01:01:02 57021890 classes.dex
  -rw-r--r--  0.0 unx   673128 b-   286620 defN 1981-01-01 01:01:02 58f32d66 classes2.dex
- -rw-r--r--  0.0 unx  5822264 b-  2621671 defN 1981-01-01 01:01:02 4f352f35 classes3.dex
+ -rw-r--r--  0.0 unx  5822272 b-  2621689 defN 1981-01-01 01:01:02 230e9716 classes3.dex
  -rw-r--r--  0.0 unx  5019616 b-  2382937 defN 1981-01-01 01:01:02 c9aacb69 lib/arm64-v8a/libcronet.119.0.6045.31.so
```

Marginally better. Let's check the Dex… Hm, strange. OK, according to your Github workflows you build on Ubuntu 24 using JDK-17. I've been building on Debian bookworm with JDK-17. Should be close enough, but wouldn't be the first time this made a difference – so let me make another run on Ubuntu. We have 22.04 here (`ubuntu:jammy`), giving the same results as the Debian Bookworm run. Let me try `ubuntu:noble` (same results), then I'm out asking if you maybe use something other than your workflow says, e.g. JDK-21? OK, no dice either, gives the same hash.

Looking closer at the dex diff, it doesn't really look like something related to a specific JDK or OS mismatch. I'm attaching it here for you, maybe it gives you a better idea than it gives me: [dex.diff.gz](https://github.com/user-attachments/files/17951030/dex.diff.gz)

**Comment by IzzySoft** [comment]
PS: a guess would be a "dirty tree" (local changes) or left-over artifacts from previous build. Can we exclude those here?

**Comment by Bnyro** [comment]
> That was not build from the commit you specified, @Bnyro 😉
>
Oh, I didn't think a merge commit would matter 😌

I'm building releases on my machine locally, not via workflows, but still I'm using OpenJDK 17.

Possibly, as you said, there might be some leftovers from previous builds,  I'll try my luck again when I get to have time (sorry for possible delays).

**Comment by IzzySoft** [comment]
No prob. When building locally, it's a good idea to insert `clean` for "release builds" (and those I shall test for RB), e.g. `./gradlew clean assembleRelease` – or hitting "clean" before "build" in Studio if you're a cat chasing your mouse :stuck_out_tongue_winking_eye: As it sometimes matters, maybe also mention which JDK (OpenJDK preferred) you're using and on which OS you're building. Plus of course any other "specific" things there might be (e.g. using a different NDK or whatever).

**Comment by Bnyro** [comment]
@IzzySoft same commit as before (https://github.com/libre-tube/LibreTube/commit/9458b5597b4d2a1a0a6e9f506137aa8367479e1d), built on Void Linux using OpenJDK 17 and a "cleaned" build environment.
[app-universal-release.zip](https://github.com/user-attachments/files/17982742/app-universal-release.zip)

**Comment by Bnyro** [comment]
> That means RB 🥳 Congrats!
>
Awesome, thanks for your guidance!

**Comment by FireMasterK** [comment]
> New scanner code picked it up.
> 
> Just `exclude` does not make that dep FOSS, when it was built from non-FOSS code.

There are alternative cronet implementations that are ABI compatible and FOSS. This is the [cronet-embedded](https://chromium.googlesource.com/chromium/src/+/HEAD/components/cronet/android) dependency. Why does this matter when the resulting binary doesn't use any non-free code? The non-free code is used at compile-time and never at runtime.

https://github.com/androidx/media/blob/1a7da45dd9c6419a43fab95132ed0aa0999300aa/libraries/datasource_cronet/build.gradle#L27
I'm sure this line patched to use the `cronet-embedded` dependency and the resulting binary would still be the same, so why do we have this limitation?

**Comment by licaon-kter** [comment]
Ask yourself this: can you build that lib without that non-FOSS code? If not... it's not FOSS

**Comment by FireMasterK** [comment]
> Ask yourself this: can you build that lib without that non-FOSS code? If not... it's not FOSS

Yes you can, I just did this in my fork to test this: https://github.com/FireMasterK/LibreTube/tree/media3-cronet

**Comment by licaon-kter** [comment]
@FireMasterK that's not what I've asked :shrug: 

but thanks for providing a solution maybe :+1:

**Comment by Bnyro** [comment]
@IzzySoft v0.27.0 was released just now: https://github.com/libre-tube/LibreTube/releases/tag/v0.27.0 🎉 
I really hope everything is still reproducible, that'd be awesome!

@licaon-kter Cronet was released with v0.27.0 (https://github.com/libre-tube/LibreTube/pull/7015), I assume the F-Droid builders will automatically continue updating the app now?

**Comment by IzzySoft** [comment]
@Bnyro thanks! RB confirmed for all 3 APKs, update pulled in manually already (well, triggered manually, framework took care for the rest). But… could you please take care for that blob?

![Image](https://github.com/user-attachments/assets/3814faf8-7c1b-4a58-9568-cc8ed104cad9)

Easily achieved with a minor addition to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

Thanks in advance!

**Comment by IzzySoft** [comment]
> for all 3 APKs

What's the difference between them, now that the native libs have been dropped? Hint: None it seems. There I was wondering why I only found 2 APK files when expecting 6 (2 for each ABI, your build and ours). Cannot tell for the x86 as we've skipped them here, but both ARM + universal are identical.

**Comment by Bnyro** [comment]
> What's the difference between them, now that the native libs have been dropped? Hint: None it seems. There I was wondering why I only found 2 APK files when expecting 6 (2 for each ABI, your build and ours). Cannot tell for the x86 as we've skipped them here, but both ARM + universal are identical.
>
Yes, chances are high that they're the same now that Cronet has been dropped.

However I know some people that have their Obtainium configured to download APKs from GitHub releases and probably some of them picked specific architectures, thus I'd prefer to continue publishing all the individual APKs for user convenience.

**Comment by Bnyro** [comment]
> For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).
> 
It's crazy that Google includes such blobs by default in your APKs, I couldn't have guessed that (but yeah, it's Google...).
Thanks for the hint, I've done as you supposed 👍 
I assume it's enough to just include this change in the next release, or do you want me to build new APKs?

**Comment by Bnyro** [comment]
> They are byte-identical. Run sha256sum, all 5 give the same. So I'll add a note to the recipe in my builder (FIXME, which prevents it from being automatically updated but instead "yells for adjustments") to drop the "additional ABIs", just keeping the universal one. As matching is done on the sha256sum, that would still cover all builds – while avoiding unnecessary additional builds on our end, thus saving resources. I guess that should be OK with you (as nobody would notice any difference anyhow except for the "missing" blocks when looking at our recipes/logs)?
>
Yes, of course!
> Let me answer that with one of "my standard rules": "Never replace what has already been distributed." The current APKs are already "out in the wild": in the IoD repo, and also in multiple of our builders. None of those would fetch APKs from the same release again, as that's already marked as "we have this". So whenever an urgent replacement is needed, rather make a new (maintenance) release. Only if there are security implications (or similar strong reasons), remove the APKs from the affected release and make a new one.
>
Sure, I didn't mean to replace the current APKs :)
I was just wondering if you needed some new builds for proofing reproducibility of the builds now that these blobs are removed, or whether your apk diff tool can live with it until the next release :)
That doesn't seem to be the case though :wink:

Thanks for all your help, especially with reproducible builds, very much appreciated ❤

**Comment by IzzySoft** [comment]
I'd say we just wait for the next release, @Bnyro – feel free to give me a ping then to confirm all is fine. And thanks for your help, too! 🤗

**Comment by licaon-kter** [comment]
I'm a bit confused at the "drop cronet" text

because I see cronet here: https://github.com/libre-tube/LibreTube/blob/v0.27.0/app/build.gradle.kts#L118-L120

I see cronet here: https://github.com/libre-tube/LibreTube/blob/v0.27.0/gradle/libs.versions.toml#L60C48-L60C99

and I see cronet inside the APK: https://gitlab.com/fdroid/fdroiddata/-/jobs/8962545952#L248

and cronet is build from non-FOSS libs: https://mvnrepository.com/artifact/androidx.media3/media3-datasource-cronet/1.4.1

**Comment by licaon-kter** [comment]
can we reopen?

**Comment by Bnyro** [comment]
> So you say I can sed these lines as not needed so we can proceed with this version too?
>
Yeah, true

**Comment by Frmd-git** [comment]
> > So you say I can sed these lines as not needed so we can proceed with this version too?
> 
> Yeah, true

Is LibreTube no reproducible build any more?

**Comment by IzzySoft** [comment]
@Frmd-git before you ask that in all repos around here (btw, what makes you asking? what gives you the idea it might no longer be RB?), it might be worth checking for yourself first:

<img width="317" height="49" alt="Image" src="https://github.com/user-attachments/assets/c43f496b-f906-4c30-94f0-122eb8da975d" />

Confirmed by 2 builders independently even. https://apt.izzysoft.de/packages/com.github.libretube

**Comment by Frmd-git** [comment]
When the app was updated (2 days ago), the green symbol inside Neostore was missing.
Now it's there; not sure if it was a cacheing or a different type of error.
But it's fine now.

**Comment by IzzySoft** [comment]
> When the app was updated (2 days ago), the green symbol inside Neostore was missing.

RB happens on a separate track here, so the shield can be delayed by a few hours.
