### ISSUE TITLE
[Not an issue] 

### ISSUE THREAD

**Issue by alejandro-alzate** [libre-tube/LibreTube#6457]
### Steps to reproduce

- Open your browser of choice
- Open this [video](https://odysee.com/@bounz:1/De-Google-Your-Life-Part-2:8)
- Go to minute [17:26](https://odysee.com/@bounz:1/De-Google-Your-Life-Part-2:8?t=1046) or more exactly to [18:03](https://odysee.com/@bounz:1/De-Google-Your-Life-Part-2:8?t=1083)

### Expected behavior

This would have been a youtube link but the video was _suspiciously_ taken down by google.
(We all know why)

### Actual behavior

This is not an issue just that I want to make you aware (if you haven't already) that your project got a shout out front and center place on a Linus Tech Tips Video.

Of course this made google mad ([proof](https://www.youtube.com/watch?v=GsjHMzGl-VY)).

This is to tell you Don't give up you'll win this battle!

### LibreTube version

0.26.2 (57)

### Android version

LineageOS 20 (Android 13)

### Other details

So was just that, you can close once read.
I hope this did not disturbed your day, I would actually made you aware more early, but for sake of not bothering I did not do it.

But since google is intentionally beaming this type of videos. It's good to make you aware.
Just think about it as the **_"Mom! I'm on the news!"_** but a bit more serious.
Keep it up! You can beat those soulless corporatives!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's nice to hear, thank you!

**Comment by alejandro-alzate** [comment]
> That's nice to hear, thank you for telling about it!

Glad you liked it.
Also new [beef](https://www.youtube.com/watch?v=apdZ7xmytiQ) just dropped watch it before is took down.
