### ISSUE TITLE
Autoplay countdown appears even when autoplay is turned off

### ISSUE THREAD

**Issue by Philippe-Choquette** [libre-tube/LibreTube#6461]
### Steps to reproduce

1. Close the video player (if opened)
2. Enable the following option:
_Settings > Player > Defaults > **Autoplay countdown**_
3. Start playing a video
4. Turn off autoplay with the relevant toggle
5. Reach the end of the video

### Expected behavior

The video ends. A replay button could be displayed, and possibly another for "Play next".

### Actual behavior

The autoplay countdown of 5 seconds appears immediately, implying that the next video will play after the time is elapsed. However, since autoplay is disabled, nothing happens afterwards.

_The description of the "Autoplay countdown" setting explicitly states that it should appear before **auto-playing** the next video. However, when autoplay is off, the next video is not scheduled to be auto-played, and so if you follow the logic, the autoplay countdown shouldn't appear in the first place._

### LibreTube version

0.25.2

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thanks for the detailed report :+1:
