### ISSUE TITLE
Show overlay with replay button when video is over

### ISSUE THREAD

**Issue by Philippe-Choquette** [libre-tube/LibreTube#6462]
### Describe your suggested feature

Maybe it's a habit from my time using the main YouTube app, but I find it natural that the overlay automatically appears once a video ends, with the replay button easily reachable at the center. This would obviously only apply when autoplay is turned off.

### Other details

Currently, the overlay doesn't appear automatically; it shows the last frame of the video with no fading to indicate that the video is over. If you switch to another app and comes back, the player changes to black. It might be a bug from a recent version too; I'm not sure, as I'm a new user of LibreTube.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by alexandre-eliot** [comment]
The last frame does not seem to be displayed for me.
The controller does not appear either
