### ISSUE TITLE
Single button share menu with options

### ISSUE THREAD

**Issue by aaasajsldfjsladkfj** [libre-tube/LibreTube#6465]
### Describe your suggested feature

I apologize for my bad English.
Please add the ability to leave a single share button, which, when selected, would cause a pop-up menu to appear with different share menu options.

### Other details

Currently the app creates four different buttons in the share menu. That's a lot. It would be nice to be able to replace the many buttons with a pop-up menu with different options.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Since the share dialog just got redesigned recently, it's currently not planned to change it again.

**Comment by aaasajsldfjsladkfj** [comment]
Please add the ability to disable LibreTube from the share menu. The share menu lags a lot after installing this app.
