### ISSUE TITLE
Highlight selection within player options lists (captions, audio track, etc.)

### ISSUE THREAD

**Issue by Philippe-Choquette** [libre-tube/LibreTube#6466]
### Describe your suggested feature

When you tap the cogwheel within the overlay during a video playback, a sheet appears with multiple options.

![2024_09_08_02 02 38](https://github.com/user-attachments/assets/d87f9298-81c1-473d-8fab-b5043b489b30)

The selection for each option is shown in parentheses, as expected.

![Screenshot_20240908_015745](https://github.com/user-attachments/assets/825382d3-a7cc-4d0d-b97a-41a4774815fe)

However, once you tap on one of these options, the selection is not highlighted within the list of choices, at least for many of the options.

---

Here are the options that do highlight the selection within their list:
- Sleep timer
- Quality

> "Quality" option list:
![2024_09_08_02 08 52](https://github.com/user-attachments/assets/47faf7d9-a20f-428c-b048-212c57a45869)

---

And here are those that don't:
- Repeat Mode
- Resize mode
- Playback speed
- Audio track
- Captions

> "Repeat Mode" option list:
![Repeat Mode](https://github.com/user-attachments/assets/5cd9726e-c2ea-4df0-a6df-6f63fbb3d3fd)

---

It would be more intuitive and consistent if the selection was highlighted within the list for all available options.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
> Playback speed
>
That's not true, the playback speed is displayed correctly at its own bottom sheet.
