### ISSUE TITLE
Private Playlist Download Limit

### ISSUE THREAD

**Issue by akashsriramganapathy** [libre-tube/LibreTube#6467]
### Steps to reproduce

1. Open LibreTube and log in to your YouTube account.
2. Access a private playlist with more than 50 videos.
3. Attempt to download the entire playlist.

https://github.com/user-attachments/assets/474ad131-142f-4e9f-947e-d15680233e1d

### Expected behavior

All videos from the private playlist should be available for download without any restrictions.

### Actual behavior

Only 50 videos are available for download, even though the playlist contains more than 50 videos.

### LibreTube version

0.25.1

### Android version

Android 13

### Other details

1. I am using both LibreTube Nightly and Stable versions to confirm the issue; both exhibit the same behavior.
2. I have attached a screen recording for a better understanding of the issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's a YouYube limitation, not LibreTube's. There's no way to fix that.
