### ISSUE TITLE
UI Tweakers

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#647]
### Describe your suggested feature

UI radius adjustment setting.
![Screenshot_20220629-235639_VueTube](https://user-images.githubusercontent.com/104249296/176533711-781e62c5-3370-4c45-a342-b3ce99fba68c.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not possible in native Android development, such things would require other coding languages.
