### ISSUE TITLE
Failure to Update Subscribed Feed 

### ISSUE THREAD

**Issue by Repressed8077** [libre-tube/LibreTube#6474]
### Steps to reproduce

1. Opening the app does not automatically fetch latest videos
2. Open the app and manually refresh the feed 

### Expected behavior

Automatic or manual feed update should work normally

### Actual behavior

No latest feed updates and you have to click the channel to watch latest videos

### LibreTube version

0.25.2

### Android version

Android 13

### Other details

https://github.com/user-attachments/assets/8838e043-8adf-4e81-8c6a-60a3d3779c34

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The feed is provided by Piped.

**Comment by Repressed8077** [comment]
Okay got it
