### ISSUE TITLE
forward tap scrolling does not work for videos on a tablet when not in full screen mode

### ISSUE THREAD

**Issue by agevlakh** [libre-tube/LibreTube#6477]
### Steps to reproduce

1. Open video on TABLET. On phone all ok
2. Try tap scrolling not in full screen

### Expected behavior

Tap scrolling working

### Actual behavior

Tap scrolling not working

### LibreTube version

0.25.2

### Android version

Android 12

### Other details

[

https://github.com/user-attachments/assets/73ff5339-a6f6-45cf-a92c-8816c4dc0d59

](url)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thanks for the detailed report :+1:
