### ISSUE TITLE
Add option to disable "Continue Watching" section on the homepage

### ISSUE THREAD

**Issue by ogipaki1** [libre-tube/LibreTube#6479]
### Describe your suggested feature

I would like to see an option where you can disable "Continue Watching" section on the homepage because it's sometimes annoying to see it.

### Other details

Here's example:
![Screenshot_2024-09-10-08-57-27-340](https://github.com/user-attachments/assets/be12485c-5a4e-40d2-93e1-c2ddeb29f6ea)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Ehab-d** [comment]
The option already exists. Go to Settings → Appearance - Find the _Layout_ section choose _Home tab content_ and uncheck _Continue watching_.

**Comment by ogipaki1** [comment]
Thanks i forgot about it.

**Comment by ogipaki1** [comment]
T

**Comment by ogipaki1** [comment]
Thanks, i forgot about it.
