### ISSUE TITLE
Unable to play any video (captcha needed)

### ISSUE THREAD

**Issue by Moostek** [libre-tube/LibreTube#6492]
### Steps to reproduce

I expect to play any video.

### Expected behavior

Can not play any video.

### Actual behavior

The list of videos with miniatures is visible, but after´I tap on any video, this video can not be played. Instead, I get this message: "Got error: Sign in to confirm that you're not a bot." 

### LibreTube version

0.25.1

### Android version

Android 12, Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/issues/6389

**Comment by NilsHere** [comment]
Having this issue right now.
