### ISSUE TITLE
Some filters on the videos in the playlist

### ISSUE THREAD

**Issue by Notesure** [libre-tube/LibreTube#6495]
### Describe your suggested feature

Filtr
1. Video
2. Shorts
Can prevent shorts video from playing when playing a playlist. It's not good to have them playing in the background.

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Unfortunately, Piped's API does not support that.
