### ISSUE TITLE
[FEATURE]  Time Stamp or Chapters support and many more

### ISSUE THREAD

**Issue by ansarimohammed422** [libre-tube/LibreTube#65]
This app is very impressive and it have many great features but there some missing features like

1. Time stamp or time line or chapters support
2. Youtube subscription import
3. Better alignment of discription
4. Comment section implimentation
5. Youtube dislike button api
6. E.C.T

**Comment by rimthekid** [comment]
We are working on Youtube subscription rn

**Comment by Bnyro** [comment]
All left-open suggestions are dupes
