### ISSUE TITLE
Get formats in online player without piped proxy.

### ISSUE THREAD

**Issue by Notesure** [libre-tube/LibreTube#6515]
### Describe your suggested feature

Currently, video formats are still accessed via piped proxy.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
They're not when local stream extraction is enabled.
