### ISSUE TITLE
Local Playlists and Subscriptions

### ISSUE THREAD

**Issue by Hughmunguzz** [libre-tube/LibreTube#652]
### Describe your suggested feature

As the piped instances are run by volunteers, when a instance goes offline, all the playlist and subscriptions are inaccessible. Situation is worse if it's a long term outage or permanent shutdown. You loose all your data. Also, many a times instances face problem when logged in (video doesn't load or super slow, etc.)

When a instance is having problem, the app is still very much usable by just changing instance. So, ability to have all the data saved in app gives a huge advantage. The app can still be used with all the playlists and subscriptions, almost seamlessly. Even from privacy perspective, it's better, as no data leaves the device.

### Other details

Newpipe implements similar feature, for reference. SS, from the project's github page,

[Subscription in Newpipe]( https://github.com/TeamNewPipe/NewPipe/raw/dev/fastlane/metadata/android/en-US/images/phoneScreenshots/shot_02.png) 

[Playlist in Newpipe]( https://github.com/TeamNewPipe/NewPipe/raw/dev/fastlane/metadata/android/en-US/images/phoneScreenshots/shot_03.png) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Local subscriptions or playlists aren't really possible because there is no real way we could make that work by using the Piped API but we're planning to allow users to export their playlists and subscriptions to become more independent.
