### ISSUE TITLE
Distinction between autoplaying my queue vs recommended videos

### ISSUE THREAD

**Issue by ms866** [libre-tube/LibreTube#6522]
### Describe your suggested feature

I should be able to toggle autoplay off, add videos to the queue, and still expect the app to autoplay the next video I explicitly added to the queue. Where the autoplay toggle should just control whether or not **recommended videos** get to autoplay

### Other details

I don't mind having 2 separate toggles if other users feel like it's useful to build a queueof videos and still not have them autoplay until they click next.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You can disable `Insert related items to queue`, I don't think that videos should autoplay (even when you manually created the queue) while autoplay is disabled.
