### ISSUE TITLE
Barbie size video 

### ISSUE THREAD

**Issue by RendeRR** [libre-tube/LibreTube#6525]
### Steps to reproduce

Sometimes when watching a video it shows up in Barbie size.

### Expected behavior

.

### Actual behavior

.
![Screenshot_20240922-120022](https://github.com/user-attachments/assets/e323f836-dcc3-469c-ad1e-c64218299187)

### LibreTube version

0.25.2 (57)

### Android version

Android 15 beta

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by RendeRR** [comment]
> Why did you delete the video title? I see this for the first time

In Soviet Russia it is not safe to watch any video. 
This can happen with literally any video.

https://github.com/user-attachments/assets/4c8610ed-8985-47d9-b98f-fc4e90bf926d

**Comment by RendeRR** [comment]
UPD: This fixes it when I expand the video to full screen and collapse it back.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/issues/5816
