### ISSUE TITLE
Show the player's controller permanently at the end of a video

### ISSUE THREAD

**Issue by alexandre-eliot** [libre-tube/LibreTube#6535]
### Describe your suggested feature

It is hard to know wether the phone has its screen on or off at the end of a video.
As of today, when a video ends while it was in fullscreen and the phone's screen was turned off, when trying to turn on the screen,  the player is plain black even if the screen is turned on.

The idea is it to set the controller permanently visible at the end, showing all its features, to show a difference.

I believe this might be achieved by modifying the function [showControllerPermanently](https://github.com/FineFindus/LibreTube/blob/94fe54e6ef7d18ddd9dd584c6b5a8dd5afad4e66/app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt#L323) inside of `CustomExoPlayerView.kt` such as :

```diff
    fun showControllerPermanently() {
+       this.useController = true
+       this.controllerShowTimeoutMs = 0 // Set to 0 to show the controller indefinitely
        cancelHideControllerTask()  // remove the previous callback from the queue to prevent a flashing behavior
        super.showController()
    }
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please feel free to create a pull request with the proposed change if you tested it.

**Comment by Bnyro** [comment]
It works fine on the latest debug version after https://github.com/libre-tube/LibreTube/pull/6481, I assume you didn't actually test the debug builds.
