### ISSUE TITLE
Audio codec selection

### ISSUE THREAD

**Issue by foxjaw** [libre-tube/LibreTube#6537]
### Describe your suggested feature

Currently there's an option to select video codec between VP9 & AVC. Provide the same for audio, i.e OPUS & AAC.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Why though? Is there any real benefit from choosing a different codec? The bandwidth difference should be minimal and the player already automatically chooses what's best for you.

**Comment by Bnyro** [comment]
Please note that HLS only provides mp4a audio streams, choosing opus only works reliably when using DASH.
