### ISSUE TITLE
Audio player does not open for downloaded video

### ISSUE THREAD

**Issue by Notesure** [libre-tube/LibreTube#6539]
### Steps to reproduce

1. Click "play in the background" on the downloaded video. Also Shuffle button
2. The audio player does not open and cannot again the audio player from the notification

### Expected behavior

Switch on and off the audio player

### Actual behavior

https://github.com/user-attachments/assets/b9d29eec-a022-4d65-83be-2e8689e2f297

### LibreTube version

0.25.2 (57)

### Android version

Misc

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not a bug, there's no audio player for downloaded videos currently.
