### ISSUE TITLE
Allow to filter the subscription feed by unread

### ISSUE THREAD

**Issue by Chepycou** [libre-tube/LibreTube#6545]
### Describe your suggested feature

Not much to add, don't hesitate to ask questions if it's not clear enough !

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You're aware that you can filtee the feed by unwatched already? I don'r think unread would be too useful as it's empty if you go to your subscriptions the second time in a row.
