### ISSUE TITLE
Downloaded video is not running failed 

### ISSUE THREAD

**Issue by harshkai** [libre-tube/LibreTube#6547]
### Steps to reproduce

Downloaded a video and when I tried to watch the video but it's not showing anything 

https://github.com/user-attachments/assets/6565fa51-d8e1-4ce4-958e-8a4e353b850d

### Expected behavior

Just upper video is downloaded now and 
Whe i tried to open it the n it's not working 
![Screenshot_20240927_081912](https://github.com/user-attachments/assets/ef48dd5e-fa1e-461a-9e22-a01fb61cb00a)
 
![Screenshot_20240927_081925](https://github.com/user-attachments/assets/a16ecccf-3070-4a4c-a79c-342897eb82ca)

### Actual behavior

I didn't know about that  your project is always best 😉🙂

### LibreTube version

0.25.2

### Android version

Android 14

### Other details

I didn't know about that 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
This might happen when your internet oftenly disconnects during the download and unfortunately I don't think we can avoid that.

The other possibility is that you downloaded a HDR stream while your phone doesn't support HDR.

**Comment by harshkai** [comment]
It is my mistake, I had downloaded it. When I did not do this, the video started playing fine 😞 I am sorry
