### ISSUE TITLE
Background  seekbar position is unstable

### ISSUE THREAD

**Issue by Notesure** [libre-tube/LibreTube#6549]
### Steps to reproduce

Video link: https://youtu.be/MQM7CNoAsBI
Look at the  seekbar in the background. Froze and suddenly changed position

### Expected behavior

 Seekbar position should move stably

### Actual behavior

Seekbar lost its position and stability was disturbed

### LibreTube version

0.25.2 (57)

### Android version

Android 12

### Other details

My devices keep repeating the same bug. If you test, use this video link.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't reproduce, and hard to debug without any crash log or something.
