### ISSUE TITLE
Newest videos in my subscription feed are 4 weeks old.

### ISSUE THREAD

**Issue by frozencatnew** [libre-tube/LibreTube#6551]
### Steps to reproduce

Don't really know why this is the case but I'll list info that could help
I have 407 Subscriptions but used to be a 1000
My instance is piped.yt
My phone is a moto g84 5G
![Screenshot_20240927-223631](https://github.com/user-attachments/assets/49a587f0-b48c-4c50-b851-4521f57eb0e7)

### Expected behavior

It shows videos from newest to oldest from my subscriptions

### Actual behavior

The newest videos it shows are 4 weeks old

### LibreTube version

0.25.2

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/TeamPiped/Piped/issues/1130
