### ISSUE TITLE
Some channels on the app are not shown properly and their videos are also not available 

### ISSUE THREAD

**Issue by shobhitparvan** [libre-tube/LibreTube#6552]
### Steps to reproduce

Step 1 - open the app
Step 2 - search muse asia and go to channel.

### Expected behavior

On page videos from channel should be shown but page remains empty

### Actual behavior

Page remains empty.
![Screenshot_2024-09-27-20-01-19-030_com github libretube](https://github.com/user-attachments/assets/87e20a7d-2353-474f-b02b-625a4a8a7189)

### LibreTube version

0.25.1

### Android version

Android 13

### Other details

I downloaded the app from f droid and is currently using the with disabled piped proxy as without it, it showed bot error message and asked to sign in

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Could you please test the channels that ain't working with NewPipe?

**Comment by harshkai** [comment]
yes this is happening to me too

**Comment by shobhitparvan** [comment]
https://github.com/user-attachments/assets/1d68e949-3439-4f6a-8cfe-fafc4476a0be


https://github.com/user-attachments/assets/b4d454bb-2e00-459e-ac78-e3818fff0f81

This channel appears to be fine in youtube app and new pipe app.

**Comment by shobhitparvan** [comment]
@Bnyro can you please reopen the issue and fix it?

**Comment by shobhitparvan** [comment]
I am not cheating. @Notesure try changing app language and using vpn (location India ) maybe then it will load in your device.
