### ISSUE TITLE
Please: Warning on the Welcome page

### ISSUE THREAD

**Issue by Notesure** [libre-tube/LibreTube#6554]
### Describe your suggested feature

Suggest changing certain settings for users experiencing video playback issues.

String: Settings: "Instance/Proxy" options to solve YT blocking problems. You can enable "Audio and Video/DASH" because there is no playback problem in the Local Extractor

### Other details

Many users download LibreTube from sites like Uptodown. Useful for users

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
> Many users download LibreTube from sites like Uptodown.
>
The APKs from Uptodown potentially includes malware, what they do i neither official nor permitted.

> Suggest changing certain settings for users experiencing video playback issues.
>
I disagree on that, the situation about that changes frequently and thus it doesn't make sense to hardcode such info in the app.
