### ISSUE TITLE
Live streams for the local extractor do not play on DASH.

### ISSUE THREAD

**Issue by Notesure** [libre-tube/LibreTube#6555]
### Steps to reproduce

New issue: Live streams not playing on DASH for Local Extractor. Plays on NewPipe
1. Please disable Piped Proxy
2. Enable Local Sream Extractor.
3. Enable DASH (no problem with HLS)

### Expected behavior

Fix live streams playback

### Actual behavior

Live streams not playing on DASH for Local Extractor. Plays on NewPipe

https://github.com/user-attachments/assets/4ac32c0d-f89d-4724-9cb3-ef1a34d8cb83

### LibreTube version

0.25.2 (57)

### Android version

Misc

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/issues/5855
