### ISSUE TITLE
Change the icon in the «share menu» along with the main application icon.

### ISSUE THREAD

**Issue by aaasajsldfjsladkfj** [libre-tube/LibreTube#6560]
### Describe your suggested feature

I apologize for my bad English.
The app has a function to change the main icon. But when you change the main icon, the icon in the «share menu» does not change. Please make the icon change everywhere.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not possible because we don't have SVG files for all icons, some are PNG.
