### ISSUE TITLE
"Failed :(" when  YT music save to playlist 

### ISSUE THREAD

**Issue by finBitorg** [libre-tube/LibreTube#6568]
### Steps to reproduce

Open YT music track, select add to playlist and add to any playlist..

### Expected behavior

The track gets added to playlist

### Actual behavior

Get an error message at the bottom of the screen "Failed :("

How ever if I import the the playlist url the playlist seem ok but cannot add anything to in via libretube app. Also tried to create a new playlist which also fails to add

### LibreTube version

0.25.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please read https://github.com/libre-tube/LibreTube/issues/6389
