### ISSUE TITLE
Clear data function.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#658]
### Describe your suggested feature

Clear watch history,Clear search history.Cache clear.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
already there lmao

**Comment by Nizami20052022** [comment]
Add words for translation.
