### ISSUE TITLE
Subscription feed is not the same depending on the instance chosen

### ISSUE THREAD

**Issue by BlueStarOne** [libre-tube/LibreTube#6590]
### Steps to reproduce

Step 1 : get some subscriptions
Step 2 : choose a random instance
Step 3 : refresh the subscription feed
Step 4 : change instance
Step 5 : refresh subscription feed
The feed is not the same

### Expected behavior

The feed should always be the same and load ALL vids from your subscription instead of some only

### Actual behavior

The subscription feed is not the same depending of the instance 

### LibreTube version

0.25.2

### Android version

Android 14

### Other details

https://github.com/user-attachments/assets/2b2d332f-8038-42c3-8865-8c940dcc7016

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Piped issue.
