### ISSUE TITLE
Use Individual Links for Private Playlists Instead of "Watch Videos"

### ISSUE THREAD

**Issue by akashsriramganapathy** [libre-tube/LibreTube#6594]
### Describe your suggested feature

**Description:**

I would like to propose an enhancement for the LibreTube application to improve access to private playlists.

### Proposal:
- **Implement Individual Links for Private Playlists**: Instead of relying on the "Watch Videos" feature to access private playlists, please consider supporting the use of individual links. This change is especially important due to the current limitation of 50 videos per playlist, which can cause issues for users with larger playlists.

### Justification:
1. **Limitations on Video Count**: The 50-video limitation in the "Watch Videos" feature can hinder users with extensive private playlists, making it difficult to access all desired content at once. Using individual links would allow for full access to larger playlists without these restrictions.
2. **Offline Accessibility**: As someone who prefers offline viewing, being able to access private playlists through direct links would greatly enhance my ability to download and manage content for offline use without the constraints of video limits.
3. **Support from 3rd Party Downloaders**: Many third-party downloaders already facilitate accessing private playlists through individual links. Incorporating this feature in LibreTube would align with existing practices and improve usability.

I believe this enhancement will significantly improve the LibreTube experience for users who need better access to private playlists, particularly those with larger collections.

Thank you for considering this feature request!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't get that, what's the difference from just downloading all videos manually?

**Comment by Bnyro** [comment]
Okay, I wasn't aware that Seal does support that. I however need to figure out how we can pass all the video ids to seal by looking at their source code, as the data we usually pass ia Andeoid intents only consists of one single uri, not multiple.

**Comment by Bnyro** [comment]
Looking at https://github.com/JunkFood02/Seal/blob/main/app/src/main/java/com/junkfood/seal/MainActivity.kt#L60-L83, it seems that Seal only supports one single URL at a time.

Why do you think Seal would support it, does any other app allow you to share multiple videos to Seal at a time that could be taken for reference?

**Comment by Bnyro** [comment]
In that case, we can certainly find a way to allow the user to **copy** the playlist contents as a list of YouTube urls, such as
```
https://www.youtube.com/watch?v=DrF5ST4W-zU,https://www.youtube.com/watch?v=Wnt5XAooDjo,https://www.youtube.com/watch?v=ib8FunNzsg0
```
for using them inside **yt-dlp** or **Seal** with a custom command. That might not be the most user experience friendly solution in the end, but it's apparently the only way to bypass the 50 videos limit.

I'm currently wondering if that link should be shown in a new dialog if a custom **package id** for handling downloads is set, or if we should add a small copy button to the current download dialog that's handling downloads when using LibreTube's inbuilt downloader.

I'm hoping for your input on that!

**Comment by Bnyro** [comment]
There now is an option to export a single playlist by using the three dot / long press menu on a playlist.

One of these options is to export as `List of URLs or video IDs` (it's only named like that because you can also import that format), which is what you're looking for.
