### ISSUE TITLE
Shuffle Control for Offline Downloads

### ISSUE THREAD

**Issue by akashsriramganapathy** [libre-tube/LibreTube#6597]
**Description:**

First of all, I want to express my appreciation for the recent updates in the nightly release. The offline download functionality has seen a significant improvement, and the enhanced UI offers much better control than before. However, I have a suggestion that could further enhance the offline experience.

**Feature Suggestion:**

- **Add Shuffle Control for Offline Downloads:** Currently, there is no option to shuffle offline downloaded videos, which would be a great feature for users who primarily listen to music playlists. Adding shuffle functionality to the offline player would enhance the experience, especially for those who prefer listening to songs in a random order.

**Why This Would Be Beneficial:**

- **Enhanced Control:** Adding shuffle for offline files would give users the same flexibility they enjoy when they are online, making the experience seamless for music lovers.

**Comment by Bnyro** [comment]
Could you please split the two points into tqo different issues? Thank you!

**Comment by Bnyro** [comment]
You can shuffle downloaded videos by starting to play a video and then press shuffle button in the playing queue menu, I don't think there's really a need to add a button for it tbh since you usually don't shuffle videos.
