### ISSUE TITLE
SponsorBlock(Show Markers on Player)

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#660]
### Describe your suggested feature

![Screenshot_20220702-122659_Chrome](https://user-images.githubusercontent.com/104249296/176993098-8d4f40a7-9169-40ba-8482-b0c996bc8cae.jpg)
![Screenshot_20220702-122752_Chrome](https://user-images.githubusercontent.com/104249296/176993101-b3495d36-b01e-4e74-86c1-6c1a5864fb26.jpg)

### Other details

This is already available in the Piped project.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Skyost** [comment]
Would it also be possible not to automatically pass the marked segments ? I'd love to have the choice not to pass some of them 👍

**Comment by NSTAdventure** [comment]
> Would it also be possible to have the choice to not automatically pass the marked segments ? I'd love to have the choice to not pass some of them 👍
> 
> Something like that :
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/3882599/181584416-eb220191-a232-4711-b41b-cc4a04bb7d1a.png">

Yeps you right i also suggest same thing for sponsorblock in libretube:
https://github.com/libre-tube/LibreTube/issues/1297

**Comment by Bnyro** [comment]
> Would it also be possible to have the choice to not automatically pass the marked segments ? I'd love to have the choice to not pass some of them 👍
> 
> Something like that :
> 
> <img width="300" src="https://user-images.githubusercontent.com/3882599/181584416-eb220191-a232-4711-b41b-cc4a04bb7d1a.png">

Sorry for the late response, I completely missed your comment.
It would be better for me to have a several issue for it next time!
I'll consider adding such a feature until the next update, however I'm a bit busy at the moment and therefore can't promise it.
