### ISSUE TITLE
Add setting to choose how many columns to display on home screen

### ISSUE THREAD

**Issue by NguyenTrongThinh** [libre-tube/LibreTube#6603]
### Describe your suggested feature

The default is 2 columns on the main screen. I think there should be an option to set the number of columns to 1. Some people want to display the video thumbnail clearly and the full title. If more columns are displayed, the title will be cut off and the video thumbnail is too small.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not planned, there already are too many settings for small things.
