### ISSUE TITLE
Shorts not loading inside the channel

### ISSUE THREAD

**Issue by brnwlshubh** [libre-tube/LibreTube#6604]
### Steps to reproduce

Open any Channel from Subscription
Switch to " Shorts " tab

### Expected behavior

Shorts to be loaded as usual

### Actual behavior

Shorts tab is totally blank

### LibreTube version

Latest debug(08/10/24) 0.25.2

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
This has been fixed at the NewPipe Extractor but Piped hasn't pulled the fix yet. Not a LibreTube issue.
