### ISSUE TITLE
Enhanced Download Management and Custom Folder Support

### ISSUE THREAD

**Issue by akashsriramganapathy** [libre-tube/LibreTube#6606]
### Describe your suggested feature

**Description:**

The built-in mechanism for downloading offline content works perfectly, organizing downloads by **audio**, **video**, **thumbnails**, and **subtitles** into separate folders within the default Android data directory. However, to improve flexibility and ease of use, I propose two enhancements that would significantly improve the offline download experience:

1. **Embedded Data Output:**
   - Currently, the downloader saves content in a segmented format (audio, video, etc.) into individual folders. If we implement a mechanism to embed all the downloaded data into one **final output file**, users could directly access and manage their downloaded content more efficiently.
   - This would be especially useful for users looking to use the tool as a complete downloader, offering an all-in-one solution without the need for third-party tools. With built-in **piped** functionality, it helps bypass region restrictions, making the built-in downloader a compelling option compared to external downloaders.

2. **Custom Download Folder Support:**
   - Allow users to define their own **custom download folder** where offline files are stored. This feature would give users the flexibility to organize their files in preferred locations (e.g., external storage) and manage storage more efficiently.
   - By letting users choose the download destination, it will be easier for those with limited internal storage to store large media files elsewhere, such as on an external SD card.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
My reasonings are still the same as https://github.com/libre-tube/LibreTube/issues/3572#issuecomment-1518614176 and they likely won't ever change.
