### ISSUE TITLE
Feature to hide comments and video description.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#661]
### Describe your suggested feature

Function to hide comments and video description. 

### Other details

Available in the Piped project.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Description and comments are already hidden by default
