### ISSUE TITLE
Searching for videos gives a blank page

### ISSUE THREAD

**Issue by heliole** [libre-tube/LibreTube#6643]
### Steps to reproduce

I'm not using any proxy or piped instance:
"Disable Piped proxy" and "Local stream extraction" settings are turned on.

### Expected behavior

Typing something in search returns a blank page, other parts of the app work normally: I'm able to watch videos from the "watch history" section.

### Actual behavior

For search to work normally like it did before, it was the same version too.

### LibreTube version

0.25.2

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't reproduce on my end, as supposed by @Notesuree this is 99% an instance issue.
