### ISSUE TITLE
"Play recent videos" button leads to player lagging more and more until crash

### ISSUE THREAD

**Issue by CelianGdfrd** [libre-tube/LibreTube#6651]
### Steps to reproduce

1. Go on a channel
2. Press "Play recent videos"

### Expected behavior

Videos should play smoothly.

### Actual behavior

After a minute, video starts lagging a bit, then more and more, until it's a litteral powerpoint. App may crash. A restart fixes the bug.

### LibreTube version

0.25.1

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Fixed in debug builds.
