### ISSUE TITLE
LibreTube Playlist -> FreeTube?

### ISSUE THREAD

**Issue by Bnyro** [libre-tube/LibreTube#6659]
### Discussed in https://github.com/libre-tube/LibreTube/discussions/6637

<div type='discussions-op-text'>

<sup>Originally posted by **GitAlexToTheGreek** October 18, 2024</sup>
Hi there 👋 

(Tried requesting feedback in the subreddit & Discord groups but no luck so far.)

👉 I'd like to open playlists from the LibreTube mobile app in the FreeTube desktop app...

When I export from LT, it's saved as a json file...

![1000019755](https://github.com/user-attachments/assets/9a2aaaea-2c7c-43c0-a9f0-d29d7dc8277f)

![1000019757](https://github.com/user-attachments/assets/0b133b9d-9ab8-4401-8a80-acfad8cc371a)

**...however the FT app only accepts db files...**

![1000019758](https://github.com/user-attachments/assets/f471e2f1-1027-408f-8b9a-750e2e45ded3) 

**...and if I try right-clicking the json file and selecting 'Open With' FT, it displays this error message:**

![Screenshot_20241018_130442_Chrome](https://github.com/user-attachments/assets/36e87979-0a1d-4642-90f5-d1cff2b82a64)

Tried changing the file extension of the freetube-playlists file to db as well, but didn't work either. 

Any suggestions?</div>

**Comment by TheodorSmall** [comment]
I think this issue addresses importing LT playlists to FT. However, https://github.com/FreeTubeApp/FreeTube/pull/5900 (and the respective issue) only address(es) the process of saving playlists in FT internally, which is not relevant when importing a playlist to FT. If I understand this issue correctly, the file exported by LT is not the correct format that FT can parse.

I might fix this issue as soon as I have the time.

**Comment by Bnyro** [comment]
Yes, it would be great if you could download and test the latest builds from https://github.com/libre-tube/NightlyBuilds to see if the export is now importable at FreeTube :)

**Comment by GitAlexToTheGreek** [comment]
> Yes, it would be great if you could download and test the latest builds from https://github.com/libre-tube/NightlyBuilds to see if the export is now importable at FreeTube :)

Hey Bnyro 🙂

Installed "app-arm64-v8a-debug-signed.apk" but the exported playlist is still the same json file that's incompatible with FT...

Should I be trying a different nightly?
(Samsung S23 Ultra (SM-S918U) - Android 14)

**Comment by Bnyro** [comment]
If it's still exactly the same file as before, it's 

Otherwise you might want to rename the exported file to the `.db` extension, I'm not sure if that matters to FreeTube.

The format is taken from the discussion in https://github.com/libre-tube/LibreTube/discussions/6640#discussion-7343366 and thus should match the format FreeTube expects. Or elsewise, are there any resources about the file format you need to export?

**Comment by Bnyro** [comment]
Could you please give it an other try? :)

**Comment by GitAlexToTheGreek** [comment]
> Could you please give it an other try (import and export)? :)

Hey Bnyro 🙂

While there's a noticeable change on the FT app for pc side...

![Screenshot 2024-10-28 163555](https://github.com/user-attachments/assets/a99ac4c3-776d-4c3c-bde4-7b7255abbe8e)

...(and I updated it) the same reported scenario as before remains; exporting the json file from LT on mobile is incompatible with the db-format-requiring FT import functionality. (And right-clicking the json file and using 'Open with' FT still leads to the "Unknown YouTube url type, cannot be opened in app" error message.)
