### ISSUE TITLE
Add Search Option for Local Private Playlists in LibreTube

### ISSUE THREAD

**Issue by Akash-Sriram** [libre-tube/LibreTube#6667]
### Describe your suggested feature

LibreTube currently lacks a search function for playlists, as it requires full playlist links and metadata to perform searches. This feature request proposes adding the ability to search within *local private playlists*, which are not listed as public playlists. 

The search functionality would use locally stored metadata within the `Android/data` directory, ensuring privacy without requiring additional storage permissions and remaining aligned with LibreTube’s strict privacy standards.

**Feature Details:**

1. **Local Private Playlist Search**:
   - Add a search option for local private playlists to allow users to filter and organize personal playlists directly within the app.

2. **Local Metadata Storage**:
   - Store playlist metadata locally within the app’s directory (`Android/data`), allowing secure searches without changing current storage permission protocols.

### Other details

Adding this feature would enable LibreTube users to manage and navigate their playlists more efficiently while maintaining privacy compliance.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I'm personally not convinced that such a feature is in scope of the project, thus converting to a discussion.
