### ISSUE TITLE
Back button goes to home tab before closing

### ISSUE THREAD

**Issue by OJ7** [libre-tube/LibreTube#669]
### Steps to reproduce

1. Set "Subscriptions" as default tab in settings
2. Close app fully (clear from recents)
3. Open app from launcher (observe app opens to Subscriptions tab)
4. Press Android back button to exit app
5. Reopen app from launcher

### Expected behavior

App exits properly and reopens to Subscriptions tab. 

### Actual behavior

Instead, when pressing the back button, it navigates to the Home tab quickly before exiting the app. When reopening, it opens to the Home tab. 

### LibreTube version

0.3.2

### Android version

Android 12

### Other details

Slightly related, I see in the [code](https://github.com/libre-tube/LibreTube/pull/541/files#diff-b8cdd5aa56a3a160637d4ec5c515454d28d1911a83bd85efdc6b22ffb897897fR50) there is an option in settings to disable Home/Trending tab, but I don't see it

![Screenshot_20220702-155435_LibreTube](https://user-images.githubusercontent.com/5333243/177014594-e2fe8e90-3843-4585-9030-ae1dc53717e2.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You don't see the option because it's not in the official released version yet :)
But I like that you checked the code :)

**Comment by Bnyro** [comment]
You can try to solve the issue on your own and pr or I'll just do it tomorrow, as you want  ;)

**Comment by OJ7** [comment]
Oh whoops, I should've checked that out. 😅

I haven't messed with Android development for a while and probably won't be able to get to it anytime soon. However, just wanted to say that the code does look pretty clean and easy to follow, even without understanding Kotlin. :)

**Comment by najodleglejszy** [comment]
I'm still experiencing that issue on 0.3.3. even if I disable the Home tab in settings, it shows up when following the steps from the issue report.

**Comment by Bnyro** [comment]
@najodleglejszy You have to change the default home tab to sth else than trending

**Comment by OJ7** [comment]
I'm actually still seeing this on 0.3.3 as well. I've tried the following:
- fresh install of app
- change default tab to Subscriptions (same issue)
- change default tab to Library (same issue) 
- hide Trending page with either of above options (same issue)

**Comment by OJ7** [comment]
Oh nice, I didn't know you had CI builds. 👏 

I'm still seeing a similar issue with that. If setting default to Subscriptions and opening the app (on fresh open), I end up on there. When pressing back once, it looks like it re-navigates to Subscriptions based on the animation. Pressing back again does the old behavior of navigating to Trending and then closing the app. Re-opening the app starts off on Trending tab again. 

A few extra behaviors observed that may help narrow the issue:
- I am unable to exit the app via back button once on that Trending page.
- If I navigate to another tab from there (e.g. Subscriptions) and then press back, this time it closes the app without going to Trending
- Re-opening the app, it starts off on Subscriptions, but I am unable to exit with back button until I tap on the Subscriptions tab again, and then pressing back.
- same behavior as last point repeats when re-opening until fully exiting the app
- tapping the Trending tab many times seems to keep pushing the same page to the navigation stack (and pressing back keeps popping off the stack)

**Comment by Bnyro** [comment]
Thank you for your detailed description of the bug. Could you please try the latest debug builds once again? :)

**Comment by OJ7** [comment]
@Bnyro tested and all of the above issues look like they're fixed, thanks!

**Comment by Nephys222** [comment]
@Bnyro @OJ7  In latest version back stack fixed. But in the case of restarting app for theme change, login etc. the back pressing goes to dialogs about restarting. Is there any way pop off these restarting from back stack?

**Comment by OJ7** [comment]
@Bnyro this same bug is back. I have the Home and Trending tabs disabled. When exiting the app fully, the app starts on the Trending tab with no tabs highlighted.

**Comment by Bnyro** [comment]
@OJ7 Make sure to select a different start tab by pressing the home icon at settings -> appearance -> navigation bar
