### ISSUE TITLE
Release 0.26.0

### ISSUE THREAD

**Issue by Bnyro** [libre-tube/LibreTube#6696]
## Beta-Testers searched for upcoming 0.26.0 release

The app is on a feature freeze now until the next release, so it's important to test it to avoid any major bugs and the necessity of hotfix releases.

Please test the app builds from https://github.com/libre-tube/NightlyBuilds and report any regressions here or in a new issue.

Thank you!

## New features
* feat: ask user to play downloaded version if video already downloaded by @angolo in https://github.com/libre-tube/LibreTube/pull/6599
* feat: audio player support for no internet activity by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6641
* feat: delete indicator when dismissing videos/items by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6673
* feat: downloads fragment rework, playing queue and audio player support by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6596
* feat: highlight current selection in player options sheets (audio lan… by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6482
* feat: RYD support for local stream extraction by @janisslsm in https://github.com/libre-tube/LibreTube/pull/6483
* feat: support for importing watch history from YouTube by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6543
* feat: support for selecting audio codec by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6578
* feat: support for shuffling downloaded audio content by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6623
* feat: allow dash without piped proxy by @janisslsm in https://github.com/libre-tube/LibreTube/pull/6485
* feat: allow user to set custom preloading amount by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6504

## Bug fixes
* fix: autoplay countdown showing even if autoplay disabled by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6481
* fix: back gesture handling in no internet activity by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6646
* fix: background service stops when using add to queue/playlist/downlo… by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6577
* fix: can't open audio player via notification in downloads by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6626
* fix: can't paste channel/playlist urls to search bar by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6575
* fix: click on video playlist won't load if autoplay is off by @Relwi in https://github.com/libre-tube/LibreTube/pull/6588
* fix: click on video playlist won't load if autoplay is off on background mode by @Relwi in https://github.com/libre-tube/LibreTube/pull/6589
* fix: crash in add to playlist dialog upon api error by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6663
* fix: crash viewing live video in playlist by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6689
* fix: crash when adding/removing channel to group by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6529
* fix: crash when importing private videos in watch history by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6571
* fix: display comments count (again) by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6501
* fix: don't allow empty input in EditNumberPreference by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6669
* fix: double click gesture inaccurate in landscape player by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6480
* fix: hide download buttons when current video is live by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6694
* fix: hide go to video action when in no internet mode by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6611
* fix: import and export of FreeTube newline format by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6674
* fix: import of new FreeTube playlist format by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6639
* fix: incorrect FreeTube playlist export by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6664
* fix: live videos shown as uploaded in 1970 in watch history by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6695
* fix: missing separator in video info text by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6621
* fix: missing top bar padding in portrait for downloaded video playback by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6534
* fix: no chapters button shown if video highlight is the only chapter by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6530
* fix: no horizontal padding in fullscreen player by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6572
* fix: pip controls don't work if auto-PiP is disabled by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6542
* fix: pip-to-audio action does not close pip window by @janisslsm in https://github.com/libre-tube/LibreTube/pull/6476
* fix: queue refill jobs don't finish when video session ended by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6533
* fix: scroll position not remembered when closing comments sheet by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6687
* fix: shuffle button crash when playlist is empty by @Relwi in https://github.com/libre-tube/LibreTube/pull/6561
* fix: uncaught local streams extractor exceptions by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6532
* fix: unexpected behavior in offline audio player fragment by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6645
* fix: video fails to play when shared to app with zero navbar tabs by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6573
* fix: wrong chapter name shown if following video has only SB highlight by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6531

## Refactor
* refactor: also respect codec preference in audio mode by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6579
* refactor: cleanup DashHelper.kt by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6489
* refactor: click on video playlist won't load if autoplay is off by @Relwi in https://github.com/libre-tube/LibreTube/pull/6593
* refactor: error handling for stream extractor responses by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6541
* refactor: improve performance when starting background shuffle mode by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6627
* refactor: simplify swipe/drag listeners for recycler views by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6672
* refactor: unify views string formatting logic to avoid bugs by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6609

## Chore
* chore: correct typos detected by typos-cli by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6602
* chore: fix missing string resource by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6671
* chore: fix unescaped escape sequence in username_email string by @Bnyro in https://github.com/libre-tube/LibreTube/pull/6472

**Comment by Bnyro** [comment]
Well, this thread is about regressions introduced since the latest release, not issues that've been around already before.

**Comment by hajogell** [comment]
I'm getting since two or threw months the following error when i klick on almost any video:

"sign in to confirm that you are not a bot"

This error was also with the latest release 0.25.2 and it is also existing with this nightly build. 

It is happening if use the piped proxy or if i deactivate it trough the options. The error keeps the same. I'm using a google pixel 3 with lineageos 19.2(android 12) and i installed the arm-64-8a-debhg version. 

If you need more information, i'm very willing to contribute.

**Comment by Bnyro** [comment]
@hajogell You should read the pinned issue.

**Comment by maxalmonte14** [comment]
Regarding https://github.com/libre-tube/LibreTube/pull/6694 (hide download button when current video is live), I'm using the latest arm64-v8a-debug.apk on Android 12 and it doesn't seem to be working, I tried with multiple livestreams from ANNnewsCH and the button still appears.

I apologize if this is not the place to report this, but since a bug fix was made to correct this in the next version I thought I'd make sense. The rest of my device info for reference purposes:

Manufacturer: Xiaomi
Board: curtana
Arch: arm64-v8a
Android SDK: 31
OS: Android 12
Display: 1080x2168
Font scale: 1.0

**Comment by Bnyro** [comment]
> Regarding https://github.com/libre-tube/LibreTube/pull/6694 (hide download button when current video is live), I'm using the latest arm64-v8a-debug.apk on Android 12 and it doesn't seem to be working, I tried with multiple livestreams from ANNnewsCH and the button still appears.
>
Indeed, apparently some livestreams are not marked as live by the NewPipe Extractor, we can work around that by checking if the video has a duration.
