### ISSUE TITLE
Automatically switch video to audio only playback while in the background

### ISSUE THREAD

**Issue by owosoup** [libre-tube/LibreTube#6697]
### Describe your suggested feature

It would be great to cut off the video stream when the video is in the background, if it's not already done, to save data. You'd enable the audio-only mode automatically, and maybe load back the video feed after coming back to the app.

Alternatively, since the app can change resolution depending on its fullscreen state, I was thinking it'd be possible to lower the resolution to something very low in the background. Same benefits, a little less efficient, but simpler. 

### Other details

Mayne this could be a fix for #5141 too! 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's already been discussed in #5141 and previous similar issues as well, thus I'd like to keep the discussion about it in that issue.
