### ISSUE TITLE
Advise: Support Ech

### ISSUE THREAD

**Issue by psi-z** [libre-tube/LibreTube#6701]
### Describe your suggested feature

Ech introduction:https://developers.cloudflare.com/ssl/edge-certificates/ech/
Components available for implementation:https://github.com/guardianproject/conscrypt

### Other details

Some websites already support ech,like https://piped.video,but it can not use in this app

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Sorry, that's out of scope.
