### ISSUE TITLE
More options related to managing downloaded videos

### ISSUE THREAD

**Issue by berrmount** [libre-tube/LibreTube#6706]
### Describe your suggested feature

1. Option to delete downloaded videos from feed/playlist
- Currently, after watching videos, one has to go to Downloads tab and look for specific video to delete it. If there are many downloaded videos, it's a bit hard to find the video. It would be more convenient to be able to delete downloaded videos from feed or playlist. 

2. Option to delete watched videos
- Having a button to "Delete watched videos" in Downloads tab to delete watched videos at once. 

3. Option to check multiple videos and delete all together
- Having to swipe or long click to delete videos takes too long to delete multiple videos. Would be better to have a checkbox to check multiple videos and press delete button to delete them all together.

4. Not related to deleting downloaded videos, but maybe show watched progress also on Downloads tab?

5. Show a badge in feed/playlist that this video is already downloaded

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
2, 4 and 5 seem realistic, 1 and 3 would be a lot of effort compared to its actual usefulness and thus are out of scope.

Please open one separate issue per point (2,4,5) to keep it easier to overview, I'm closing this issue now because it's hard to keep track of lists of suggestions in a single issue.
