### ISSUE TITLE
Hide Shorts from Trends

### ISSUE THREAD

**Issue by aaasajsldfjsladkfj** [libre-tube/LibreTube#6713]
### Describe your suggested feature

Please make the setting to hide Shorts from Trends on the main page. Most of the trending videos right now are Shorts. I would like to disable or separate Shorts from regular videos.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not planned such as https://github.com/libre-tube/LibreTube/issues?q=is%3Aissue+hide+shorts+is%3Aclosed.
