### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by Jomyy** [libre-tube/LibreTube#672]
### Describe your suggested feature

there should be an animation for the comments and description folding out 

also the comments need a way to be closed without scrolling up again to click on the comments button again

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
already added, will be there in the next update
