### ISSUE TITLE
Watch history duplicates

### ISSUE THREAD

**Issue by Eliya-Manoj** [libre-tube/LibreTube#6720]
### Steps to reproduce

1. Watch a video multiple times
2. go to watch history
3. you can see watch history duplicate videos

![Screenshot_20241112-181235_LibreTube Debug](https://github.com/user-attachments/assets/7728d156-7e86-4f9f-8ca5-5eda95ac6975)

### Expected behavior

Watch history without duplicates

### Actual behavior

Watch history shows duplicates of watched videos

### LibreTube version

Latest Debug

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by meradeveloper** [comment]
I watched the video multiple times, but it didn't reproduce.

### LibreTube version

Latest Debug

### Android version

Android 12
Red Note 9 Pro

**Comment by Eliya-Manoj** [comment]
Try 2 video multiple times ( watch a video, then close player, then watch same video )

**Comment by Bnyro** [comment]
Not reproducible with the provided steps, please re-open if you find a consistent way to reproduce (including a video).
