### ISSUE TITLE
Not able to see recent video from my subscription 

### ISSUE THREAD

**Issue by birmehto** [libre-tube/LibreTube#6733]
### Steps to reproduce

Open subscription feed

### Expected behavior

All the recent video show on subscription feed 

### Actual behavior

But its not shown in subscription feed cueent video like newpipe 
![Uploading Screenshot_20241117-221908_LibreTube.jpg…]()

### LibreTube version

0.26.0

### Android version

14

### Other details

H3j3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/issues/6717
