### ISSUE TITLE
Old Skip Buttons are duplicated in notification player

### ISSUE THREAD

**Issue by Figim** [libre-tube/LibreTube#6736]
### Steps to reproduce

1. The seekbar works in the notification player
2. But of the new skip buttons
3. But duplicate new buttons work

### Expected behavior

Fix duplicates (ə) and delete the previous buttons. Because duplicates work

### Actual behavior

Title

### LibreTube version

0.26.0 Debug

### Android version

All

### Other details

![Screenshot_20241117-212530_LibreTube Debug](https://github.com/user-attachments/assets/2aa234cc-3b5f-4a44-bae2-9b98932774c2)
![Screenshot_20241117-212557_LibreTube Debug](https://github.com/user-attachments/assets/b546a624-8926-4407-b074-94bcf768d143)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't reproduce on Android 14, seems to be ROM specific.

**Comment by Bnyro** [comment]
The duplicate buttons are caused by the Media3 library we use, we can't control that.

Same applies for the timebar.
