### ISSUE TITLE
Due to screen timeout, the next video does not play in the background when the screen turns off

### ISSUE THREAD

**Issue by Figim** [libre-tube/LibreTube#6751]
### Steps to reproduce
Battery optimization is disabled. This problem is due to screen timeout

1. Play a 5-minute video
2. Then exit the app
3. Turn off the screen
4. Wait for the video to end
5. Wait a little longer
6. But it won't be played. The player has stopped

### Expected behavior

As of Android 12, the screen must be left on in the background for the invincible service option to work.

You need to prevent the screen break in the background

### Actual behavior

Does not interfere with the screen break in the background

### LibreTube version

0.26.0 Debug

### Android version

Android 12+

### Other details

You must prevent background screen pause

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
If so, that's media3 library bug.
