### ISSUE TITLE
Sleep timer doesn't work on downloads

### ISSUE THREAD

**Issue by hgjd** [libre-tube/LibreTube#6760]
### Steps to reproduce

1. Download a video
2. Start playing downloaded video 
3. Set sleep timer to 1 minute
4. Observe that playback does not stop after 1 minute
5. Set sleep timer again
6. Observe that timer now counts down twice as fast
7. Set sleep timer again 
8. Observe that timer now counts down in 3-second increments

### Expected behavior

Playback stops after the time set in the sleep timer has passed.

### Actual behavior

Playback does not stop when expected. Additionally, further attempts to set a sleep timer cause the timer to count down faster.

### LibreTube version

0.26.0

### Android version

Android 14

### Other details

Also reproduced on Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by hgjd** [comment]
That was very fast, thank you!

**Comment by Bnyro** [comment]
Thanks for the detailed report :+1:
