### ISSUE TITLE
Login/Register error

### ISSUE THREAD

**Issue by LolekLiam** [libre-tube/LibreTube#678]
### Steps to reproduce

1. Open LibreTube
2. Open settings menu
3. Go to Instance settings
4. Press Login/Register
5. Input the username and password
6. Press Register

### Expected behavior

Should register me.

### Actual behavior

I got a kind of like a pop up notification on the bottom saying "Network error." Even tho my internet works just fine.

### LibreTube version

0.3.2

### Android version

Android 6.0

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Currently the feed of kavin.rocks is down. You can either wait until it works again or use a different instance.
