### ISSUE TITLE
Cannot import watch history (Nightly version)

### ISSUE THREAD

**Issue by Ahmey1400** [libre-tube/LibreTube#6793]
### Steps to reproduce

1. Select the import watch history
2. Select the watch history file
3. It imports empty

### Expected behavior

Imports the watch history

### Actual behavior

App crashes and watch history shows blank
(No error popup shows)

### LibreTube version

Nightly version

### Android version

Android 14

### Other details

Its the same watch history as #6731

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Try again with the latest debug version and copy the crashlog from the bottom of the settings.

**Comment by Ahmey1400** [comment]
https://github.com/user-attachments/assets/6bfd8030-95dd-40ec-9b2d-9df66894a9d6

**Comment by Ahmey1400** [comment]
[watch-history.json](https://github.com/user-attachments/files/17847704/watch-history.json)
I tried it with deleting half of my watch history and worked but here is the json file

**Comment by Bnyro** [comment]
> [watch-history.json](https://github.com/user-attachments/files/17847704/watch-history.json) I tried it with deleting half of my watch history and worked but here is the json file
>
Your file is not valid JSON, there's a `}]` in the end that you need to remove. The validity can be tested with `jq` or online tools for example.

After that change your watch history imports fine for me.
