### ISSUE TITLE
Downloaded videos cause phone to become unusable after ending

### ISSUE THREAD

**Issue by Handrail9** [libre-tube/LibreTube#6794]
### Steps to reproduce

1. Download a video
2. Play the video
3. Wait for the video to end, and the app shows a black screen above all other apps, making navigation and use impossible

### Expected behavior

the video player shouldn't cause a giant black screen on top of all apps

### Actual behavior

the video player causes a giant black screen on top of all apps

### LibreTube version

0.25.1

### Android version

CalyxOS 6.1.0, Android 15

### Other details

This didn't happen until I got Android 15 on cOS. If it's suspected this is a Calyx issue I will open my bug report with them instead.

I can see the notification bar when calls are initiated during the black bar but I can not swipe the notification shade down, nor answer the phone call. The screen remains black other than the notification bar when that happens. I can see the Privacy indicator if it is currently active at all times. I tried using Dicio to switch apps via voice commands but the black screen remained. If theres any other info I can provide please let me know.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
This got refactored with the 0.26.0 release, please update to the latest version as @Figim suggested.

**Comment by Handrail9** [comment]
Updating fixed my issue. It looks like the F-Droid build hasn't been compiled since August (hence why I was on 0.25 1) Is there a reason for that?

**Comment by Handrail9** [comment]
> > Updating fixed my issue. It looks like the F-Droid build hasn't been compiled since August (hence why I was on 0.25 1) Is there a reason for that?
> 
> F droid is always late

3 months late is unusual though. Its usually less than 2 weeks between updates and I saw there was a LibreTube update in September that never got pushed to F-Droid

**Comment by Bnyro** [comment]
> Updating fixed my issue. It looks like the F-Droid build hasn't been compiled since August (hence why I was on 0.25 1) Is there a reason for that?
>
Apparently they have one of LibreTube's dependencies on their list of suspicious libraries, but I ain't motivated to deal with it. IzzyOnDroid and GitHub releases should be used instead for now.

**Comment by Handrail9** [comment]
> > Updating fixed my issue. It looks like the F-Droid build hasn't been compiled since August (hence why I was on 0.25 1) Is there a reason for that?
> 
> Apparently they have one of LibreTube's dependencies on their new list of "suspicious" libraries, but I ain't motivated to deal with it. IzzyOnDroid and GitHub releases should be used instead for now.

Disappointing but understandable. I know FOSS development is a thankless job so I appreciate your (and the contributors) work none the less

**Comment by Handrail9** [comment]
Actually, this issue still happens in 0.26.0. Should I open a new issue for it?
