### ISSUE TITLE
Can't click login/register button in android 11

### ISSUE THREAD

**Issue by mascraft** [libre-tube/LibreTube#68]
-phone details:
Poco F3
Android 11
Miui 12.5.6
Using the latest version of liber tube: 0.2.3

Login and register buttons are not working at all, nothing happens when I write my username and password and click register.

**Comment by rimthekid** [comment]
Try with another instance

**Comment by stevenfelix505** [comment]
Try to enter the username, but leave the password blank

**Comment by stevenfelix505** [comment]
https://user-images.githubusercontent.com/57618009/158600575-65ee2788-3f7c-4f42-b92a-d90e8789a5f6.mp4

**Comment by FireMasterK** [comment]
It's fixed in https://github.com/TeamPiped/Piped-Backend/pull/225, which will disallow registrations with an empty username/password.
