### ISSUE TITLE
Background Play Next Button not working

### ISSUE THREAD

**Issue by brnwlshubh** [libre-tube/LibreTube#6811]
### Steps to reproduce

Play Any Video in Background (As Audio)
Press Next button from Notification

### Expected behavior

Should change to next video 

### Actual behavior

No change

### LibreTube version

0.26.0 Nightly

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please test things again using the latest debug build (which will be done building in some minutes).

**Comment by brnwlshubh** [comment]
Now working fine
