### ISSUE TITLE
Add whole channel in playlist 

### ISSUE THREAD

**Issue by DracX3** [libre-tube/LibreTube#6812]
### Describe your suggested feature

There should be option to add whole channel to a playlist, it would be so convenient to binge a channel.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not planned, some channels have more than a few thousand videos which would just cause a lot of API traffic.

**Comment by DracX3** [comment]
I see, so we can put cap on it like 1000 video only or something like this.
Option is actually available in the newpipe so I got the idea from there.
