### ISSUE TITLE
Add support to stream to external devices.

### ISSUE THREAD

**Issue by Dv5n** [libre-tube/LibreTube#6815]
### Describe your suggested feature

It would be nice to stream to external devices (e.g. Chromecast) similar to how VLC works.

This feature will allow users to easily view YouTube content ad-free on a big screen. 

### Other details

I am using the F-droid build (0.25.1)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not planned as it would require closed-source Google dependencies, also see LibreTube's ROADMAP.

**Comment by Dv5n** [comment]
However, there may be some open-source implementations that could work. How does VLC handle this? Does it rely on Google dependencies?

**Comment by Bnyro** [comment]
I can't tell that, there are however some discussions about it in the GitHub Discussions tab that you might want to check out.

I'd probably accept pull requests for casting support, however I won't work on it myself.
