### ISSUE TITLE
Making playlist From Links (Text) 

### ISSUE THREAD

**Issue by DracX3** [libre-tube/LibreTube#6828]
### Describe your suggested feature

• From a list of YouTube video links in text format, can create a playlist of those videos.
• Can be a import feature to add the text or text  file, it will be so convenient to binge a channel.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You can still change the playlist name after importing, that's not a lot of additional clicks.

I can reproduce that the list is empty, thus please file a new issue for that.
