### ISSUE TITLE
Playlists do not appear in search or on channels 

### ISSUE THREAD

**Issue by dimike96** [libre-tube/LibreTube#6830]
### Steps to reproduce

1. Search any string
2. Select the "Playlists" filter below the search box
3. Observe no results 

1. Navigate to any YouTube channel known to have playlists 
2. Click the playlists tab
3. Observe no playlists appearing.

### Expected behavior

Playlists should be included in search results normally but especially when the playlist filter is selected. Channels with playlists should appear to have playlists on their channel.

### Actual behavior

No playlists ever appear in search results on on any YouTube channel.

### LibreTube version

0.26.0

### Android version

Android 15

### Other details

Im not 100% on this but I was using the version on f-droid (0.25 presumably) two days ago and think I was able to search playlists just fine, then the next day this issue started where I could not find any. I uninstalled that version and got the newest one from GitHub and the issue continues to persist. 

Screenshots:
Searching for playlists having no results
![Screenshot_20241126-155511](https://github.com/user-attachments/assets/baa34bbb-1784-4c18-9d9f-dc6434baa84d)

A channel I know has playlists not showing any
![Screenshot_20241126-160612](https://github.com/user-attachments/assets/045a146b-a0f5-484a-bb98-1764cb26eb86)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's however a Piped issue, not LibreTube-exclusive.
