### ISSUE TITLE
Pause button in Notification Player not working 

### ISSUE THREAD

**Issue by exefile2** [libre-tube/LibreTube#6831]
### Steps to reproduce

Play a video 

Pause button not working in notification player

### Expected behavior

Button should work 

### Actual behavior

Pause button in notification not working 

### LibreTube version

0.26.0

### Android version

Android 10 miui 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Already fixed in debug builds.
