### ISSUE TITLE
The main player froze when the notification player was deleted

### ISSUE THREAD

**Issue by Figim** [libre-tube/LibreTube#6847]
### Steps to reproduce

1. Play video
2. Stop the notification player and swipe to delete
3. Back to main player and previous and forward, 10 seconds, play button and seek bar not working
4. The video cannot be replayed

### Expected behavior

As in the stable version, if the notification player is deleted, save your main player activity

### Actual behavior

https://github.com/user-attachments/assets/c32f285b-5fdc-4aca-b53d-b84f36d87afb

### LibreTube version

0.26.0 Debug

### Android version

All

### Other details

This bug is not present in the stable version

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's expected (on some Android versions only however as it seems).

Killing the notification kills the player, and thus also the player for the video. You usually don't want to continue playback after killing the notification, so I don't consider this a bug.

**Comment by Bnyro** [comment]
> The stable version did not have this problem
>
Because it kept the player in memory instead of destroying it which is even worse for your battery.
