### ISSUE TITLE
Notification pannel error

### ISSUE THREAD

**Issue by PlayerRS21** [libre-tube/LibreTube#6849]
### Steps to reproduce

We can't control playback from notification pannel and 2. I am a linux user which I use kde connect to sinc my devices and to control my playback from both devices but it is not showing as a player in linux please fix this 

### Expected behavior

According to me we can control the playback from notification pannel and the kde connect also detects it as a player.

### Actual behavior

But now it is not controlled by notification pannel we have to go to app then change it

### LibreTube version

0.26.0

### Android version

Android 11 

### Other details

Everything looks good only notification pannel changes

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Should be fixed in debug builds.
