### ISSUE TITLE
Playlist Import from Text File Not Working on LibreTube

### ISSUE THREAD

**Issue by akashsriramganapathy** [libre-tube/LibreTube#6860]
#### Description
When attempting to import a playlist from a text file containing video links in LibreTube, the operation completes, but the playlist remains empty. None of the links from the file are added to the playlist.

#### Steps to Reproduce
1. Create a `.txt` file containing valid YouTube video links, one per line.
2. Open LibreTube and navigate to the playlist import option.
3. Select the text file and confirm the import.
4. Check the imported playlist.

### Expected behavior

The links from the text file should be added to the new playlist in LibreTube.

### Actual behavior

The playlist is created but remains empty, with none of the links from the file included.

### LibreTube version

nightly build

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We exported using `https://youtu.be/watch?v=...` links, it however should've been `https://youtube.com/watch?v=...`.

Thus it now works when you re-export the playlist and try it again.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/issues/5928

**Comment by Bnyro** [comment]
Your playlist works fine for me, https://github.com/libre-tube/LibreTube/pull/6865 allows you to see the progress of the import directly by refreshing the library page.
