### ISSUE TITLE
'Export playlists to FreeTube' creates file incompatible with FreeTube

### ISSUE THREAD

**Issue by Moonstone3010** [libre-tube/LibreTube#6876]
### Steps to reproduce

1. Go to Settings>Backup and restore
2. Click export playlists> FreeTube>Save

### Expected behavior

Exported file can be easily imported to FreeTube.

### Actual behavior

File has .json extension and Freetube can import only .db files. Also structure of the file is slightly different. After changing extension empty playlists are created in FreeTube.

### LibreTube version

0.25.1

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Already fixed since 0.26.0, see https://github.com/libre-tube/LibreTube/issues/6628 and https://github.com/libre-tube/LibreTube/issues/6659

**Comment by Moonstone3010** [comment]
> Already fixed since 0.26.0, see #6628 and #6659

No, it's not fixed. 
#6628 applies to imports, not exports.
Did you even read the last post in #6659?

**Comment by LovingNumbers** [comment]
still the same problem tbh kinda wild that it's marked as fixed extension is now the right one (db) but still it's exporting nothing
