### ISSUE TITLE
Libretube not up to date in F-droid

### ISSUE THREAD

**Issue by maxalmonte14** [libre-tube/LibreTube#6884]
### Steps to reproduce

1. Go to https://f-droid.org/en/packages/com.github.libretube/
2. Scroll to versions
3. Notice the last version available

### Expected behavior

Last version should be 0.26.0

### Actual behavior

Last version is 0.25.1, added on 8/31/2024.

### LibreTube version

0.25.1

### Android version

N/A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
see https://github.com/libre-tube/LibreTube/issues/6867 and https://github.com/libre-tube/LibreTube/issues/6455#issuecomment-2482982475
