### ISSUE TITLE
Negative amount of songs in playlist

### ISSUE THREAD

**Issue by Joni8829** [libre-tube/LibreTube#6886]
### Steps to reproduce

1. Open LibreTube
2. Find a playlist where this happens (it only happens with some of them)

### Expected behavior

It should show the correct number of songs in all playlists

### Actual behavior

For some of my playlists it shows "-2" where it says the amount of songs in a playlist
![Screenshot_20241218_184347_LibreTube](https://github.com/user-attachments/assets/8ec9234f-f5aa-41aa-948f-de25c3b9052e)

### LibreTube version

0.2.6

### Android version

Android 13

### Other details

This is a very good app, compared to others I've tried, but this tiny issue is fairly annoying.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
> Find a playlist where this happens (it only happens with some of them)
>
For example?

Nevertheless that's likely a Piped issue, not a LibreTube one.

**Comment by Joni8829** [comment]
Alright then, Thanks, can you either forward it to them, or give me a link to their GitHub page?

**Comment by Bnyro** [comment]
It might also possibly be a NewPipe Extractor issue, it would help to have a playlist to reproduce it.

**Comment by Joni8829** [comment]
> It might also possibly be a NewPipe Extractor issue, it would help to have a playlist to reproduce it.

Here's the playlist shown in the picture:
https://music.youtube.com/playlist?list=RDCLAK5uy_nwLjTxbhH7Ng3q4pCbUdtxascis5Adj5g&playnext=1&si=fDWtOoQhzWP7M8Xd

**Comment by Bnyro** [comment]
Indeed, same behavior at Piped (https://piped.video/playlist?list=RDCLAK5uy_nwLjTxbhH7Ng3q4pCbUdtxascis5Adj5g), and NewPipe just shows that there would be an infinite amount of videos (which is of course not the case either).

Please open an issue at https://github.com/TeamNewPipe/NewPipeExtractor.

LibreTube just hides negative video counts now and shows nothing instead.
