### ISSUE TITLE
Queue System

### ISSUE THREAD

**Issue by Joni8829** [libre-tube/LibreTube#6890]
### Describe your suggested feature

It would be amazing if there was a feature to add songs to the top of the queue. a Play Next option is also necessary.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's already possible by long pressing videos.

**Comment by Joni8829** [comment]
> That's already possible by long pressing videos.

Not songs apparently
