### ISSUE TITLE
[FEATURE] auto-generated subtitles

### ISSUE THREAD

**Issue by Artur16211** [libre-tube/LibreTube#69]
**Describe the feature you'd like to see added**
Add youtube subtitles autotranslation

**Additional context**
![Captura de pantalla 2022-03-16 001121](https://user-images.githubusercontent.com/66655201/158527623-c729c74a-e12b-4c5a-9059-b322bc960c21.png)

**Comment by alefvanoon** [comment]
This feature is already on the LibreTube.

**Comment by trizen** [comment]
Support for auto-translated captions do not seem to be available in LibreTube.

This can be achieved by adding the `tlang=LANG` parameter to the close-caption URLs provided by YouTube (including the auto-generated ones).

For more info, see also: https://github.com/TeamNewPipe/NewPipe/issues/8023
