### ISSUE TITLE
Queue Downloaded Songs

### ISSUE THREAD

**Issue by Joni8829** [libre-tube/LibreTube#6902]
### Describe your suggested feature

When listening offline it would be amazing if we could queue up songs, Currently we can only do it for songs when we're online :(

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
When you play offline, all downloads are automatically added to the queue and you cab reorder them in the queue.
