### ISSUE TITLE
[Enhancement] Publish on Google Play

### ISSUE THREAD

**Issue by grapheneloverdev** [libre-tube/LibreTube#6904]
### Describe your suggested feature

Since Accrescent doesn't fit the Dev's needs atm as stated in #2756, would it be possible to publish LibreTube on Google Play, the only App Store other than Accrescent which employs verification of downloads and certificate pinning, so the APK doesn't have to be manually verified by the user and in therefore doesn't break the AOSP security model, or is that impossible due to LibreTube violating YouTube's TOS?

Having to rely on Appverifier means that anyone not using GrapheneOS doesn't have a trust chain all the way to the OS signing keys. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The aim of the project is to be a viable YouTube client for privacy focused users, who likely won't ever use Google apps such as the play store.

Apart from that, this would certainly be against Google's TOS.
