### ISSUE TITLE
Showing region blocked channels 

### ISSUE THREAD

**Issue by DracX3** [libre-tube/LibreTube#6908]
### Steps to reproduce

Step 1 = Search "Taarak mehta ka ooltah chashmah episode 1000 " 
Step 2 = It shows results from a channel name " Tarak mehta ka ooltah chashmah" which is a region blocked channel in india.
Step 3 = it is showing sign in error if I try to play the video.

![Screenshot_20241227_212555_LibreTube](https://github.com/user-attachments/assets/11a12d06-911c-4971-89a4-c3a044ad2555)

### Expected behavior

It should show results from channel that work india.
Here is a screenshot from newpipe channel name "sony pal" shows the result.
![Screenshot_20241227_213016_NewPipe](https://github.com/user-attachments/assets/90a5d20c-16eb-4d94-a3d3-3569e25ee553)

### Actual behavior

It showed results from channel that is region blocked and showing sign in error if I try to open the video ( region blocked one ) 
![Screenshot_20241227_213325_LibreTube](https://github.com/user-attachments/assets/956ffe37-723a-49d6-a52a-c9b3e1de4abf)

### LibreTube version

0.26.0

### Android version

Android 14 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Whether a channel is displayed or not depends on the Piped instance, LibreTube doesn't decide that.
