### ISSUE TITLE
Playlist Sharing

### ISSUE THREAD

**Issue by Revan335** [libre-tube/LibreTube#6911]
### Describe your suggested feature

I can't find an Option to sharing a Playlist. Sharing from Bookmarks, Playlists from other YouTubern, Videos, ... have a YouTube or Piped URL for sharing. Or is this only working with a login on a Piped Account?

### Other details

This what helpful for sharing with others or Download Media with the TubeSync Docker Container.
An extra benefit was sharing with timecode for example started share at 1:25 min and/or end at 1:30 min.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Revan335** [comment]
Maybe exist this Option but i'm to blind to see/find than: https://github.com/TeamPiped/Piped/issues/3888

Maybe anyone can help me.

**Comment by Bnyro** [comment]
You can't share private playlists with other users by Piped's design.

LibreTube allows you to share public playlists via the long press menu on playlist items and exporting private playlists via the backup and restore settings for downloading the playlist with third party tools.
