### ISSUE TITLE
Libre tube dont fetch any instance

### ISSUE THREAD

**Issue by MoamenElahmdy** [libre-tube/LibreTube#6912]
### Steps to reproduce

1.I choose kavin instance and libretube say could not fetch the available instance
2. Change rhe instance 

### Expected behavior

I changed the instance and should the error gone 

### Actual behavior

All the instance give the same error could not fetch The available instance
![Screenshot_20241229-112726](https://github.com/user-attachments/assets/3c0d5078-279d-4382-9eb6-c3fb94f09ff1)

### LibreTube version

0.26.0(58)

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://piped-instances.kavin.rocks/ is down, nothing LibreTube could do there.
