### ISSUE TITLE
The back click button is not working in the app.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#698]
### Steps to reproduce

1.Enter the application.
2.Click on Subscriptions, Library, etc
3.Press the back button.
4.Unable to exit the application.. 

### Expected behavior

This should not have been an error.

https://user-images.githubusercontent.com/104249296/177402449-c0e58229-6fe4-483c-9da2-ff16791821f3.mp4

### Actual behavior

There should have been no error. 

### LibreTube version

0.3.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Fixed in the latest debug builds
