### ISSUE TITLE
RSS feed implementation

### ISSUE THREAD

**Issue by Tommy-00-** [libre-tube/LibreTube#699]
### Describe your suggested feature

Hi, i'm a new user, coming from NewPipe. I'm having lots of issues with the instances servers these days. And also it's very confusing having to choose a server to link to for a new user. 

I would like to have the ability to choose from using those servers and just getting a direct rss feed from youtube servers by checking every subscription channel like newpipe does (at least i guess so i'm totally an end user so sorry if i misunderstood the mechanism of your app)

Btw good job on the ui

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by lilcheti** [comment]
Newpipe subscriptions so slow

**Comment by Bnyro** [comment]
As far as I understand you, you want the client to connect directly with the YouTube servers to fetch the RSS. But we won't ever fetch it directly, we will always have a Piped server between the client and the YouTube servers.
