### ISSUE TITLE
Live chat

### ISSUE THREAD

**Issue by silikeite** [libre-tube/LibreTube#701]
### Describe your suggested feature

Is it technically feasible as of right now to implement live chat in the app for streams?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It's not possible atm, the API doesn't support it yet. Maybe in the future, we don't know.

**Comment by Trung0246** [comment]
Is this still an issue? Looks like Youtube V3 API support this:

https://gist.github.com/w3cj/4f1fa02b26303ae1e0b1660f2349e705

**Comment by FireMasterK** [comment]
We need support for it in NewPipeExtractor, then in the Piped API. We do not use the YouTube API.
