### ISSUE TITLE
App doesn't work with VPN

### ISSUE THREAD

**Issue by some1onLSD** [libre-tube/LibreTube#708]
### Steps to reproduce

1- Activate mobile data or Wifi
2- Connect to a VPN 
3- Enter the app

### Expected behavior

Work

### Actual behavior

Instantly detects that there is no internet (but there is)
![Screenshot_2022-07-06-23-14-31-1611109222](https://user-images.githubusercontent.com/74503778/177652833-4abd7d1a-d5c8-49ba-85a2-96627003b757.png)

### LibreTube version

0.3.3

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Should be fixed in the debug builds.

**Comment by DoYouNotice** [comment]
yep still not working for me.
