### ISSUE TITLE
Youtube links

### ISSUE THREAD

**Issue by Adithyan007hack** [libre-tube/LibreTube#714]
### Describe your suggested feature

How to make youtube links open in libretube by default is there a way to do this?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Go to android settings -> apps -> LibreTube -> open by default -> enable what you want the app to open

**Comment by Bnyro** [comment]
Maybe it works different on MIUI, idk. It works for stock android. There should also be sth similar in android settings under default apps.
