### ISSUE TITLE
Slow Video Downloading

### ISSUE THREAD

**Issue by adarshxiv** [libre-tube/LibreTube#719]
### Describe your suggested feature

I don't know why video downloading is so slow. It almost takes an hour to download a 7-8 minutes video. I am new to LibreTube and I absolutely love it. Just this one thing is bothering me. Can anyone tell me how to download videos?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Yes, I know. Downloads are a big issue at the moment but I couldn't find out yet what the reason for it is.

**Comment by Bnyro** [comment]
I close this because it's related to #456
