### ISSUE TITLE
Allow cloning a playlist while within one 

### ISSUE THREAD

**Issue by FireMasterK** [libre-tube/LibreTube#722]
### Describe your suggested feature

1. You open a playlist through a link
2. You can't clone it currently, you must search for it and clone it manually

Maybe, we can add a button for it somewhere. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Sure, I will just add a three dot button to the playlist fragment
