### ISSUE TITLE
Subscription page keep loading.

### ISSUE THREAD

**Issue by simanchal-45** [libre-tube/LibreTube#726]
### Steps to reproduce

Go to subscription tab.

### Expected behavior

This should show my subscribed channel and video.

### Actual behavior

It's keep loading infinitely.
![Screenshot_2022-07-08-19-00-59-64](https://user-images.githubusercontent.com/71957533/178002522-8b520ee0-65dc-4f83-a10f-3bdcce888087.jpg)

### LibreTube version

0.3.3

### Android version

8.1.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Instance issue, same behavior on the web frontend. Therefore its not a LibreTube bug
