### ISSUE TITLE
PlayerFragment transation not animated onBackPressed

### ISSUE THREAD

**Issue by Jomyy** [libre-tube/LibreTube#731]
### Steps to reproduce

Go to a video in Portrait mode make it big (not fullscreen but also not miniplayer) 

Press back button

### Expected behavior

It should animate into the miniplayer

### Actual behavior

When you press back it just jumps to the position without animation

### LibreTube version

0.3.3

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
ohh, button sizes don't reset either

**Comment by Jomyy** [comment]
No i meant not in full screen mode

**Comment by Jomyy** [comment]
![Screenshot_20220709-131513_LibreTube.png](https://user-images.githubusercontent.com/62953110/178103297-1857aa61-a804-4c42-b16b-64f8306acd14.png)

When you press back from this screen

**Comment by Bnyro** [comment]
Ohhh, okay
