### ISSUE TITLE
Video Quality Button

### ISSUE THREAD

**Issue by Jomyy** [libre-tube/LibreTube#732]
### Steps to reproduce

Press the video quality button in the top right corner on the text instead of the arrow

### Expected behavior

Quality select dialog should appear

### Actual behavior

Nothing 

### LibreTube version

0.3.3

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
already changed that
