### ISSUE TITLE
Fullscreen fill screen stops at punchhole

### ISSUE THREAD

**Issue by Jomyy** [libre-tube/LibreTube#734]
### Steps to reproduce

1. Open a video
2. Fullscren it 
3. Make it fill the screen

### Expected behavior

It should use all space available and go beyond punchhole and notch 

### Actual behavior

It stops at the punchhole and the space is black

### LibreTube version

0.3.3

### Android version

Android 12

### Other details

![Screenshot_20220709-132039_LibreTube](https://user-images.githubusercontent.com/62953110/178103515-52979f85-f4ef-4f3a-a217-2d409c4ee8d4.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Jomyy** [comment]
On the left you can see a black stripe where my punchhole is

**Comment by Bnyro** [comment]
Yes, I know. I already spent hours with XML to fix it but it never wanted to work.

**Comment by Jomyy** [comment]
Wait isn't that what the fullscreen attribute is for?

**Comment by Jomyy** [comment]
<item name="android:windowFullscreen">true</item>

That one

**Comment by Bnyro** [comment]
I thought I tried it but it didn't work

**Comment by Bnyro** [comment]
Maybe I'll have time for it tomorrow when I'm back home

**Comment by Bnyro** [comment]
But I would appreciate if you could try it too :)

**Comment by Jomyy** [comment]
Yeah when im home on monday i can try
