### ISSUE TITLE
When connection is lost while video playes app freezes 

### ISSUE THREAD

**Issue by Jomyy** [libre-tube/LibreTube#735]
### Steps to reproduce

1. Play video 
2. Disable internet while playing 

### Expected behavior

Nothing

### Actual behavior

App freezes 

### LibreTube version

0.3.3

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Joaquin0apps** [comment]
@Jomyy you use the latest version or the betas in beta that does not happen I tried it

**Comment by Jomyy** [comment]
I didn't build it myself but used the latest version

**Comment by Bnyro** [comment]
I tried it too, there is no crash for me either (in debug builds and in 0.3.3 release)

**Comment by Jomyy** [comment]
Maybe it just freezes when connection is lost unintenionally

**Comment by Joaquin0apps** [comment]
> No lo construí yo mismo, pero usé la última versión.

well now the problem is in your version
