### ISSUE TITLE
Unable to import subscriptions locally

### ISSUE THREAD

**Issue by Terkyz** [libre-tube/LibreTube#739]
### Steps to reproduce

1. Open Libretube.
2. Press Settings.
3. Enter the Instance option.
4. Go to "Import subscriptions".
5. Allow access to device files.
6. When you press again after allowing access to device files, a message appears saying "Please log-in and try again."

### Expected behavior

Pressing again on "import subscriptions" the default file manager on the device should automatically open, then the user must look for the local file of subscriptions exported from Youtube or Newpipe some format like "opml." or ".json", and when clicking on said file the subscriptions should be added to Libretube automatically.

### Actual behavior

When pressing again the "import suscriptions" option, a message appears saying "Please log-in and try again."

### LibreTube version

0.3.3

### Android version

Android 12

### Other details

All the subscriptions that I had before updating were automatically deleted when updating, try to start the section using the LibreTube account and it gives me an error although I am sure that the data is correct. I tried to install version 0.3.2 and my subscriptions are still missing and the LibreTube option doesn't work either.

Try to reinstall the application several times and the result is always the same

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That is a server issue. Because of a bug, user accounts got deleted there and some parts still don't work. Please ask on [Piped](https://github.com/teampiped/piped) for more information.

**Comment by Terkyz** [comment]
Sorry if I misexplained myself, but locally I can't import using a file that I already have on my device exported from Youtube, and when I try I get this message that does not have the slightest relationship with the option to import, because that is local, as if I tried to log in to Piped but I don't use Piped

Btw, thank you very much for the development of LibreTube, it's wonderful app

**Comment by Bnyro** [comment]
Importing subscriptions relies on the Piped instances, subscriptions are not stored locally. Do normal subscriptions work (without importing)?

**Comment by Terkyz** [comment]
Ahhh, I thought it was local, sorry, thanks for the clarification
