### ISSUE TITLE
The app will not close

### ISSUE THREAD

**Issue by Chungaa** [libre-tube/LibreTube#742]
### Steps to reproduce

The app will not close.
If you press the back button several times.

### Expected behavior

,

### Actual behavior

,

### LibreTube version

0.3.3

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
already fixed in debug builds
