### ISSUE TITLE
Suggestion: Adding Thread design to distinguish comments & replies

### ISSUE THREAD

**Issue by 5lttrz** [libre-tube/LibreTube#748]
Currently the Comments and Replies section cannot be distinguished

Comments Section- https://ibb.co/8bzKj9Y

Reply Section - https://ibb.co/tmJ2mGF

So I suggest adding a threads design to make replies more distinguishable

Suggestion Image- https://ibb.co/nC87XFR

**Comment by Bnyro** [comment]
I agree that they should be sperated more clearly but I don't think that your suggestion would fit the app UI.

**Comment by 5lttrz** [comment]
How about adding seperators and a tiny arrow button?

**Comment by Bnyro** [comment]
I tried it with an arrow button once, for the comments, it looks annoying because every comment just has one then. So just a wasture of space.

**Comment by Bnyro** [comment]
Maybe we can just make the avatar images of the replies smaller and move them more to the right

**Comment by Bnyro** [comment]
> Maybe we can just make the avatar images of the replies smaller and move them more to the right

I applied that know, opinion?
