### ISSUE TITLE
[FEATURE] Default YouTube Player

### ISSUE THREAD

**Issue by OshekharO** [libre-tube/LibreTube#75]
**features i had like to see added**
Hii, Is it possible to implement YouTube video player instead of the one which is currently being used? If not, then can you please make the initialisation of video's faster? When I click on any video which i wanna watch it takes good amount of Seconds to initialise the player.

**Additional context**
![Screenshot_20220317-061027_YouTube](https://user-images.githubusercontent.com/95137948/158714077-125fc06f-3c71-4782-ada2-960df38190aa.png)

**Comment by lilcheti** [comment]
I'm trying to make it better
