### ISSUE TITLE
App crashes when trying to view specific video

### ISSUE THREAD

**Issue by brunnerm4x** [libre-tube/LibreTube#762]
### Steps to reproduce

Search for this video (Josef Jandrisits Campersong) and try to play it or open it via "open in App" feature of Firefox mobile: 

https://m.youtube.com/watch?v=ElPMbGl4MqA

### Expected behavior

Video should play, app should not crash

### Actual behavior

For both methods the app crashes instantly (every time for me - haven't been able to whatch the video even once) 

### LibreTube version

0.3.3

### Android version

Android 12/ lineage 19.1 (lineage_beryllium-userdebug 12 SP2A.220505.002 4957d9e9f4)

### Other details

On Xiaomi Pocophone F1;
other videos work just fine - great App in general

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by brunnerm4x** [comment]
Playback works fine with the debug build - thanks!

Out of interest I tried downloading the video - this crashes the app (perhaps this is also a related issue ...)

**Comment by Bnyro** [comment]
I will fix it later
