### ISSUE TITLE
ANR in slow networks

### ISSUE THREAD

**Issue by ildar** [libre-tube/LibreTube#769]
### Steps to reproduce

get yourself a slow internet

### Expected behavior

interface responsive

### Actual behavior

ANR quite often

### LibreTube version

0.3.3

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ildar** [comment]
Lucky you :-)
I've found this, may be helpful:
https://stackoverflow.com/questions/38136013/simulate-slow-network-on-android-simulator

**Comment by Bnyro** [comment]
We'll continue with the discussion about it in #870
