### ISSUE TITLE
After fullscreen video view the BottomNavigationLayout shrinks horizontally.

### ISSUE THREAD

**Issue by Nephys222** [libre-tube/LibreTube#770]
### Steps to reproduce

In order to reproduce
1. Open app
2. Open any video in player
3. Enter to fullscreen
4. Go back or close video
5. BottomNavigation view shrank to left
 

### Expected behavior

It is expected to view similar layout to one when app launched.
![Screenshot_20220713-114128](https://user-images.githubusercontent.com/59939839/178667908-85d491cc-a561-4ce4-b408-1c31496c18a0.png)
 

### Actual behavior

The shrank BottomNavigattion. It occurs on Android 7, Nougat
Note: I checked on Simulator (Pixel 5, Android 12). It does not happen.
![Screenshot_20220713-101338](https://user-images.githubusercontent.com/59939839/178667024-ad9a13ac-ff24-4935-9986-f1e3939b26ef.png)

### LibreTube version

0.3.3

### Android version

Android 7

### Other details

Tested device: HTC One M9.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We don't have an impact on that, it seems a bug of the material design library we're using. It appears only a very few android versions that aren't the main focus of the library so I guess that there is nothing we can do.
