### ISSUE TITLE
crash when play video in any playlist

### ISSUE THREAD

**Issue by ydqsbfsyi** [libre-tube/LibreTube#771]
### Steps to reproduce

1, in search tool, search and find any playlist, long press, clone playlist.
2, find that playlist in library, press it.
3, app just crashes/quits.

### Expected behavior

null

### Actual behavior

null

### LibreTube version

0.3.3

### Android version

Android 10, as well as Android 9 TV

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Could you retry with the latest CI builds?

**Comment by ydqsbfsyi** [comment]
> Could you retry with the latest CI builds?

Perfect! Debug version works totally fine. I also noticed, in debug version the remember position function works, too!

**Comment by Bnyro** [comment]
Yeah, I finally got the stuff fixed that I messed up before :p
