### ISSUE TITLE
Downloaded videos in the app.

### ISSUE THREAD

**Issue by Broniy** [libre-tube/LibreTube#773]
### Describe your suggested feature

In-app access to downloaded videos. (With or without internet)NewPipe has this feature.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
dupe
