### ISSUE TITLE
The app shows no internet connection window when launched with VPN 

### ISSUE THREAD

**Issue by Nephys222** [libre-tube/LibreTube#775]
### Steps to reproduce

1. Connect to any VPN downloaded from Google Play store
2. Open the app
3. Prompts "No Internet connection"

### Expected behavior

The app should open in any network connections such as Wifi, Cellular, VPN etc.

### Actual behavior

The does not start but prompts no connection window.

### LibreTube version

0.3.3

### Android version

Android 7

### Other details

Tested on latest debug build too.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Could you retry it with the latest CI build pls?

**Comment by Nephys222** [comment]
Pulled the latest version. The issue persists.

**Comment by Bnyro** [comment]
Hmm, maybe I should roll back some changes then

**Comment by Nephys222** [comment]
May be here is not the place. How can I change versions of dependencies. Where this lib located? 
`implementation libs.material`
`implementation libs.exoplayer`
