### ISSUE TITLE
Import subscriptions option is not working

### ISSUE THREAD

**Issue by Harsh97x** [libre-tube/LibreTube#776]
### Steps to reproduce

1. Click on the import subscriptions option
2. Select the CSV or JSON file
3. It'll take some time and show a prompt of subscribed 
4. Open the subscription tab to check the updated list

### Expected behavior

Click the import option and select the CSV or JSON file. The subscription tab shows the updated list of subscriptions

### Actual behavior

After clicking the import subscriptions option and selecting the file, a prompt named subscribed comes, But the subscription tab still shows nothing.

### LibreTube version

0.3.3

### Android version

Android 8.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Harsh97x** [comment]
I tried all the other instances apart from the official one, and they all gave me "There is a problem with the server try another instance."

**Comment by Harsh97x** [comment]
Update tried different instances but faced the same issue.

**Comment by Bnyro** [comment]
Could you please try to import your subscriptions on https://piped.kavin.rocks/subscriptions and tell me whether it works?

**Comment by Bnyro** [comment]
Or on any other Piped instance you want to use

**Comment by Harsh97x** [comment]
I uploaded the JSON file and imported the subs, but the feed still shows a blank screen. I think the app is ok. The problem is in the piped website's import functionality.

**Comment by Joaquin0apps** [comment]
> ¿Podría intentar importar sus suscripciones en https://piped.kavin.rocks/subscriptions y decirme si funciona?

No, it does not work

**Comment by daudix-UFO** [comment]
Tested same thing with piped page and in-app, not working

**Comment by Bnyro** [comment]
Well, then it is an API issue since the app uses the Piped API route for importing subscriptions.
