### ISSUE TITLE
Video plays in 480p instead of HLS

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#779]
### Steps to reproduce

1.You have played the video.
2.Video does not play in auto quality.
3.The video is played in 480p quality

### Expected behavior

If automatic quality is selected in the settings, it should play automatically.

### Actual behavior

480p plays

### LibreTube version

0.3.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I can't replicate it. Could you please provide a screen recording?

**Comment by Nizami20052022** [comment]
https://user-images.githubusercontent.com/104249296/179013374-a6f19e08-ee83-4f5f-885e-f398c69be595.mp4
