### ISSUE TITLE
[FEATURE] Section for YouTube Shorts

### ISSUE THREAD

**Issue by sushantbhagat02** [libre-tube/LibreTube#78]
**Describe the feature you'd like to see added**
A short description of the feature, and what it would accomplish.

**Additional context**
Can u guys add a different section for yt shorts 😅. And a feature to lock the video quality preference . U guys doing a very grate job . Thank you for your hard work .

**Comment by archroid** [comment]
Piped still doesn't support this but we will add this when it adds. Since then you can search #shorts and watch them. Thanks for your suggestion <3

**Comment by demirdegerli** [comment]
Since LibreTube only interacts with Piped API, why a Shorts section can't added to the app? It ends in LibreTube; making a Shorts section and make API calls, right? Or is this more complicated than I think?
