### ISSUE TITLE
Auto rotate error.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#781]
### Steps to reproduce

1.Enable auto-rotate from your phone's control panel.
2.Turn on auto-rotate in LibreTube settings.
3.Play the video and rotate the device.
4.Auto rotate does not work.

### Expected behavior

The video should immediately rotate left and right.

### Actual behavior

https://user-images.githubusercontent.com/104249296/179021999-1734ec00-8648-4328-b0a0-315ab25c13a1.mp4

### LibreTube version

0.3.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
feature is only for fullscreen mode
