### ISSUE TITLE
[Meta] Currently missing features when jumping ship from other apps

### ISSUE THREAD

**Issue by kubo6472** [libre-tube/LibreTube#788]
### Describe your suggested feature

I am missing two features that are possible to implement, those being

gesture controls (#381) and

a data saver mode that won't load all the thumbnails (love that in newpipe). 

Having a list of videos instead of a grid would be great, too.

There is kinda problem with the fullscreen option (got a 9:21 device) the part under the notch is black, when in Vanced or NewPipe, there's video under there (the latter being what I'd want). 

And one feature I'm not sure how to implement, or even if could be implemented at all for that matter: YouTube TV Casting. I managed to get adfree youtube app on my smart TV. Casting to it from an app would be great. I know of Kodi workarounds, but I would love to solve it rather this way.

### Other details

I started using the app today, while searching for a YouTube Vanced alternative. I am currently using a version of NewPipe, with the newest extractor, but older 19.x UI. A temporary officially unsupported bodge. I loved using Vanced, I still do, but I have to get prepared for when it'll stop working. I wanted to use NewPipe with sponsorblock, but I can't stand the new UI (still) and backporting all the sponsorblock stuff for the very few people isn't worth it. I love that LibreTube has SB already.

I'm sorry if this is lengthy, these issues aren't a dealbreaker for me at all, but rather a bunch of nice-to-haves.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
1. We decided to not add gesture controls since the main part of the community isn't in favor of them, me included.
2. I'm not sure how a data saver mode should work, does it just not load any images or only with bad quality? Something like that wouldn't be a problem to add.
3. I don't really think that's a good idea, I'm happy with the current grid solution and adding a list as optional would require a lot of work.
4. That's already a known issue.
5. That could be possible but we would probably need help from outside for it since I don't know how it works.

**Comment by kubo6472** [comment]
Sad to hear about the gestures. I'm quite a Java noob, so I personally can't imagine myself helping out on any features, yet. 2. 
![Screenshot_20220715-163513_NewPipe preunified](https://user-images.githubusercontent.com/26146502/179245775-ac3d4a32-5a5e-46e5-9a23-cb2e064b7d2a.jpg)
I like the black squares, even though they just occupy the space, but resizing the contents looks like more work. And it would look weird. I do however want to help with testing. Both the black bars and the casting, if anyone will be willing to implement it.

**Comment by Bnyro** [comment]
Well, I will add a data save mode in the next few days if I find the time for it.
For casting, I don't really think it  would help if someone who doesn't code it since bigger features like that are usually being developed in small steps with a lot of testing in between.

**Comment by Bnyro** [comment]
Added the data saver mode now, would appreciate any feedback :)

**Comment by kubo6472** [comment]
Love it, thank you

**Comment by Bnyro** [comment]
I'll close the issue and open a new one for casting
