### ISSUE TITLE
watching some videos just crashes

### ISSUE THREAD

**Issue by linux-leo** [libre-tube/LibreTube#793]
### Steps to reproduce

1. Search for Anlinux
2. Click on first or second result

### Expected behavior

Not crash

### Actual behavior

Crash

### LibreTube version

0.3.3

### Android version

11

### Other details

I'm using MIUI 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
No worries :)
