### ISSUE TITLE
Add an option to trust user-install CA certificates for custom instances

### ISSUE THREAD

**Issue by kovdan01** [libre-tube/LibreTube#794]
### Describe your suggested feature

Android allows you to add custom CA certificates to user cert store (while default certificates are placed in system cert store). According to documentation, apps targeting API level 24 and newer (after Android 6) do not trust user-installed certificates by default (see https://developer.android.com/training/articles/security-config#TrustingAdditionalCas). But a developer can implement such feature - see Bromite or Firefox browsers for Android, they both have an option to trust user-installed certificates.

As for now, I am able to access my custom Piped instance via https using Bromite browser with corresponding option enabled - and it shows a green lock sign and no security warnings which means that the certificate is trusted. Unlike this, when using LibreTube application, I get endless "Network error" toasts. Would be cool if you could implement an option similar to mentioned browser's one.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't know how this should work, according to [this article](https://httptoolkit.tech/blog/android-11-trust-ca-certificates/), it's not possible anymore if I got it right.

**Comment by kovdan01** [comment]
Looks like the article you provided has a bit different meaning. It tells that now a user **must** add custom CA certificates manually via settings app and there is no way to add a certificate from a 3rd-party app using some API. In my proposal I assume that the certificate is already installed in a user cert storage (manually via settings), and I just suggest to trust such certificates. According to https://developer.android.com/training/articles/security-config#TrustingAdditionalCas, 3rd-party apps do not treat them as trusted by default, but it is possible to change this behavior. A nice examples of that are browsers like Bromite and Firefox - they both provide an option to make user-installed certificates trusted.

**Comment by Bnyro** [comment]
Oh, okay.
Seems like I misunderstood you, sorry.

**Comment by kovdan01** [comment]
Works, thanks!
