### ISSUE TITLE
Name clash with already existing app

### ISSUE THREAD

**Issue by therealbluepandabear** [libre-tube/LibreTube#795]
### Steps to reproduce

1. Go to https://github.com/LibreTubeApp/LibreTube
2. Same name as this app
3. This goes against GitHub's TOS

### Expected behavior

GitHub does not allow copying of names, this app should respect that.

### Actual behavior

If possible the name of this repo should be changed, or I will be filing a report to GitHub. The implications may be that the repo gets removed, permanently. 

### LibreTube version

Latest

### Android version

N/A

### Other details

N/A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by therealbluepandabear** [comment]
You can remove this, I do not mind. Yet the other repo is licensed as follows:

![image](https://user-images.githubusercontent.com/50536495/179250820-59dce188-1b67-4126-b08e-cc3ff81cc03f.png)

The name is copyrighted, this is technically illegal, so I will be filing a lawsuit to the owner of this app or sending an urgent message to GitHub, as this is not allowed.

**Comment by Broniy** [comment]
But is this problem solved now?

**Comment by Bnyro** [comment]
There never was a problem

**Comment by FireMasterK** [comment]
> LibreTube do not mind violating the GNU

I'll remind you that the GNU GPL license has nothing to do with names. Also, you are not the copyright holder of the name "LibreTube", so it would actually be illegal for you to file a DMCA takedown request.

**Comment by FireMasterK** [comment]
> Tell me then why GitHub doesn't allow you to create a new repository with a name of an already existing one? You have obviously 'circumvented' this by creating an organization with the name separated by a dash, so it's quite obvious the original owner has tried to circumvent this behavior of GitHub.

It's quite obvious - since someone else also wanted to use that name? GitHub doesn't require you to register a trademark before you create an account/organization, and rightfully so. Also, according to [USPTO's TESS search system](https://www.uspto.gov/trademarks/search), "LibreTube" is not a trademarked word or name. If you still have a problem with the name, you may go register the trademark yourself.
