### ISSUE TITLE
After exit fullscreen with close button an app stays in landscape mode 

### ISSUE THREAD

**Issue by Nephys222** [libre-tube/LibreTube#797]
### Steps to reproduce

1. Open a video in the app
2. Set fullscreen
3. Close with (x) close button 

### Expected behavior

The main view in portrait mode

### Actual behavior

The main view in landscape mode

### LibreTube version

0.3.3

### Android version

Android 7

### Other details

Tested on android 12 with latest CI build

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Well, auto rotation got enabled so it's not really a bug. I don't know how to handle this an without breaking auto rotation. We should probably add an option to disable auto rotation since it's only meant to be for large screen devices.

**Comment by Nephys222** [comment]
I understand. It could be taking out close button in fullscreen

**Comment by Bnyro** [comment]
Alright, we could just hide it then.

**Comment by Nephys222** [comment]
Ok. Also is it possible to enlarge height of player view in portrait mode. Seems it is smaller compared to other similar apps.

**Comment by Bnyro** [comment]
Not possible programmatically, only works when hard coding the player height to become bigger which is not planned.
