### ISSUE TITLE
App crashed

### ISSUE THREAD

**Issue by Hija45** [libre-tube/LibreTube#798]
### Steps to reproduce

1. Open the app.
2. Search for [lente Ph](https://www.youtube.com/user/lentephils) and click the channel.
3. Click a video to play. (I tried it on the first 10 videos but none of them play)

https://user-images.githubusercontent.com/105953528/179351266-fc7b3d60-d3d3-49aa-b81e-9a638bb98721.mp4

### Expected behavior

The video should be playing. I tried it on https://piped.kavin.rocks/channel/UCJKzfcGcFxxPDld5I7xOPFQ and it did play.

### Actual behavior

The app crashed.

### LibreTube version

0.3.3

### Android version

Android 8

### Other details

Other than the videos of lente Ph, I also found that https://www.youtube.com/watch?v=ZMHiR1Ak9nU will make the app crashed as well

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
dupe, fixed

**Comment by Hija45** [comment]
No, it isn't fixed. Tried it with my other phone and same thing happened, the app crashed

**Comment by Hija45** [comment]
No @Bnyro, it wasn't fixed. I just tried installing it on my other phone and the app still crashed for playing lente ph videos.

https://user-images.githubusercontent.com/105953528/179379171-0d0e336d-4ca4-4ed0-bcf4-513178462ad1.mp4
