### ISSUE TITLE
Brazilian Portuguese translation

### ISSUE THREAD

**Issue by JonatasVi** [libre-tube/LibreTube#8]
if possible I would like to translate the application into Brazilian Portuguese

**Comment by alefvanoon** [comment]
nice! It will be great.
But let a more complete version be released in the next few days.
The application is currently half full.
After that, we try to find a way to translate the software.

**Comment by JonatasVi** [comment]
oh yes, that's fine, will this app have the login system?

Em sáb., 5 de fev. de 2022 03:01, alefvanoon ***@***.***>
escreveu:

**Comment by alefvanoon** [comment]
> oh yes, that's fine, will this app have the login system? Em sáb., 5 de fev. de 2022 03:01, alefvanoon ***@***.***> escreveu:

Of Course!

**Comment by lilcheti** [comment]
Hey, we just integrated weblate you can start translating here: https://hosted.weblate.org/projects/libretube/libretube/

**Comment by Suburbanno** [comment]
Close this
Commits: https://github.com/libre-tube/LibreTube/commit/0200d1fc3c077b06624e68692d746c53912db76d | https://github.com/libre-tube/LibreTube/commit/32d53438b11a5f2be690af75c3705fb3a399a26a
