### ISSUE TITLE
[FEATURE] Support for LBRY's HLS

### ISSUE THREAD

**Issue by FireMasterK** [libre-tube/LibreTube#80]
**Describe the feature you'd like to see added**
Title, just like in Piped, currently it doesn't play when selected.

**Comment by Bnyro** [comment]
Oh, I didn't get that it is about LBRY HLS and not about HLS only, I'm sorry

**Comment by xIUPITERx** [comment]
What is LBRY HLS used for?

**Comment by FireMasterK** [comment]
Adaptive quality, like 1080p, 720p, 360p, etc

**Comment by xIUPITERx** [comment]
But what is the difference to the HLS implementation that is already included?

**Comment by FireMasterK** [comment]
Well, the current HLS implementation uses Google's servers, this would aim to use LBRY's whenever available.

**Comment by lilcheti** [comment]
I wanna work on this any ideas where to start?

**Comment by FireMasterK** [comment]
Yes! You have to send a `HEAD` request to the "LBRY" quality's URL, if the mimetype matches hls (usually they send a 30x response, which you have to follow). If it does, you have to load that followed URL as a HLS manifest.

**Comment by lilcheti** [comment]
What's their url?

**Comment by FireMasterK** [comment]
It's in the API response! https://pipedapi.kavin.rocks/streams/5npl2KCt2ok

See the first object in `videoStreams`
