### ISSUE TITLE
Download music in mp3 sound format.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#802]
### Describe your suggested feature

Download music in mp3 sound format.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Well, I think that Opus and M4A are quite common formats, anything else would require additional libraries.
