### ISSUE TITLE
Accent color error.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#807]
### Steps to reproduce

1.Go to settings.
2.Set the accent color to Mystic Material.
3.Then watch the video.

### Expected behavior

Colors should match each other.

### Actual behavior

https://user-images.githubusercontent.com/104249296/179398982-5f819ba4-35e6-49ea-89e6-709a685cc147.mp4

https://user-images.githubusercontent.com/104249296/179399484-62a9814e-9b03-4b7a-859d-d6bf69fb9c74.mp4

### LibreTube version

0.3.3

### Android version

Android 11

### Other details

Set Mystic Material 3 as default.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Already fixed
