### ISSUE TITLE
Words that are not added to the translation.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#809]
### Describe your suggested feature

![Screenshot_20220717-171152_LibreTube](https://user-images.githubusercontent.com/104249296/179400066-11d9c33d-0287-42ab-9660-91f432f220b0.jpg)
![Screenshot_20220717-171126_LibreTube](https://user-images.githubusercontent.com/104249296/179400069-20f09457-5866-4997-893c-2ebf47ce54a1.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
fixed
