### ISSUE TITLE
[BUG] App force close when playing age restricted video

### ISSUE THREAD

**Issue by mistermaun98** [libre-tube/LibreTube#81]
**Describe the bug**
LibreTube suddenly force closed when playing video that tagged as "Age Restricted"

**To Reproduce**
Play some video that tagged as "Age Restricted" (i play video from "Police Activity" channel because almost every video from that channel can't be played on LibreTube)

I'm Using the latest version of LibreTube (0.2.3)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A8 (2018)
 - Android version: 9

**Comment by lilcheti** [comment]
It's because of it's hls url is null and the app won't check it I'll fix it now.

**Comment by lilcheti** [comment]
It's [fixed](https://github.com/libre-tube/LibreTube/commit/a562083a6ff59b57e7fc62a405625f2aed1e930e) now.
seems like there is no related videos for such videos either
