### ISSUE TITLE
Double tap forward/rewind does not work after locking/unlocking of controls.

### ISSUE THREAD

**Issue by Nephys222** [libre-tube/LibreTube#814]
### Steps to reproduce

1. Open an app
2. Open a video in a player
3. Lock the controls
4. Unlock the controls

### Expected behavior

Should continue to work after unlock

### Actual behavior

Double tap forward/rewind buttons does not work

### LibreTube version

0.3.3

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Nephys222** [comment]
@Bnyro Thanx. It is fixed. A note. Currently app crashes because of array length out of bound in speed array & shows incorrectly.

**Comment by Bnyro** [comment]
Yes, I changed some logic behind it, deleting app data should fix it.
I'll add a workaround so that the old one still works too.
