### ISSUE TITLE
Clear application cache.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#821]
### Describe your suggested feature

A function to clear the cache of the application.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Well, just do it via android settings...

**Comment by ildar** [comment]
@Bnyro , this doesn't fully work. /data/.../files/coil/ should be in cache but it's not there so it isn't cleared by "clear cache". Plz fix.
plz reopen

**Comment by ildar** [comment]
or at least in `no_backup` special folder.
