### ISSUE TITLE
Weblate not up to date

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#822]
On Github, the number of strings shown is 244, on weblate 233

**Comment by Bnyro** [comment]
@lilcheti xD

**Comment by Nephys222** [comment]
@Bnyro I also translated to new language via Weblate with almost complete. Would you be integrating those too?

**Comment by Nephys222** [comment]
Turkmen

**Comment by Nephys222** [comment]
Ok. Thanks
