### ISSUE TITLE
The possibility to write a comment on videos or posts

### ISSUE THREAD

**Issue by Radical4ever** [libre-tube/LibreTube#828]
### Describe your suggested feature

Hi, i love that the app uses material you (it looks like a way ahead version of youtube XD). but im asking if its possible to make able to comment on youtube videos or community posts. thank you

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Well, its not since it would require logging in with Google Accounts.
