### ISSUE TITLE
Return YouTube Dislike

### ISSUE THREAD

**Issue by TheGoldenSun** [libre-tube/LibreTube#834]
### Describe your suggested feature

YouTube Dislike API

### Other details

Hello, 

I was wondering if you could add return YouTube dislike API in your app since I don't see it in version 3.3

(Return YouTube Dislike Link)

https://www.returnyoutubedislike.com/install

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FireMasterK** [comment]
![Screenshot_20220721-084829_LibreTube.png](https://user-images.githubusercontent.com/20838718/180122608-f9aab52f-2a14-4b8b-b052-9fae4e21414c.png)

It should appear though, does it not appear in some videos?

**Comment by FireMasterK** [comment]
Closing this with https://github.com/TeamPiped/Piped-Backend/commit/748235fcbd3e3bdfd10f20bf5bc8342037d77603, which should help for the issue! This happens when the RYD API is slow at responding to requests.
