### ISSUE TITLE
Back Gesture/Navigation-Button not working on second time

### ISSUE THREAD

**Issue by Rotakna** [libre-tube/LibreTube#835]
### Steps to reproduce

1. Launch the app
2. Using Back gesture/navigation-button to exit the app (1st time) note: the app still run in the background
3. Launch app again (click on icon or recent)
4. Error: cannot exit the app using Back Gesture/Navigation-Button

### Expected behavior

It should be able to use Back Gesture/Navigation-Button to exit the app.

### Actual behavior

Unable to exit the app using Back Gesture/Navigation-Button the second time after launch the app back from the background.

### LibreTube version

0.3.3

### Android version

Android 12 and Android 11

### Other details

Test on:
Samsung Galaxy Note10+ Android 12
LG V50S Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Dupe and already fixed
