### ISSUE TITLE
Playing some video will crash the app

### ISSUE THREAD

**Issue by Rotakna** [libre-tube/LibreTube#837]
### Steps to reproduce

1. Launch the app
2. Search for a video
3. Click on one of the search results
4. Error: the app crashed

Note: only some of the video, not sure the reason why.
Example: [Link to the video the crash the app](https://youtube.com/watch?v=qmFtevEJ1Pk)

### Expected behavior

Should be able to play the video just fine.

### Actual behavior

The app crashed.

### LibreTube version

0.3.3

### Android version

Android 12 and Android 11

### Other details

Test on:
Samsung Galaxy Note10+ Android 12
LG V50S Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FireMasterK** [comment]
Seems like this is because this is an OTF stream :thinking: 
In such videos, the `dash` parameter won't be null in the API response, and that is to be used

**Comment by Bnyro** [comment]
I already fixed it in the debug builds: The reason was that some video stream sources had null as URL, which crashed the app.
