### ISSUE TITLE
[FEATURE] Title of video in player

### ISSUE THREAD

**Issue by Stenafo** [libre-tube/LibreTube#85]
**Describe the feature you'd like to see added**
It would be convenient to be able to read the title of the video being played, perhaps under the player or inside the player when selected (as in the official application)

**Comment by martin-desktops** [comment]
@Stenafo the issue can be closed - 0.2.6 has been released

**Comment by Stenafo** [comment]
> @Stenafo the issue can be closed - 0.2.6 has been released

Ok, even if it is not possible to read the title of the video when the video is in full screen (as in the official app)

![Screenshot_2022-04-20-23-15-35-764_com vanced android youtube](https://user-images.githubusercontent.com/15031098/164324521-39ec9087-e4a8-4c4d-a514-fd48b485ca64.jpg)
