### ISSUE TITLE
Notification when a new version is available.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#855]
### Describe your suggested feature

The function of sending a notification to the device when there is a new version of the application.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not planned, use Droid-ify or Neo Store if you want to become notified
