### ISSUE TITLE
[BUG] <brief bug description>

### ISSUE THREAD

**Issue by OldWorldOrdr** [libre-tube/LibreTube#86]
**Describe the bug**

App crashes when I import subscriptions

**To Reproduce**

Go to settings
Click on import subscriptions
Click on the zip u get from the Google takeout site
App crashes

**Smartphone (please complete the following information):**
 - Device: [e.g. Xiamoi Note 10] Samsung z flip 3
 - Android version: [e.g. 10] android 12

**Additional context**

imo you should allow people to import the csv file from inside the zip like newpipe let's you do.  Newpipe also fails to import the file, although it doesn't crash, but it works if I extract the csv and import that.

**Comment by lilcheti** [comment]
Oh ok then I'll do that.
