### ISSUE TITLE
Adjusting the accent color.

### ISSUE THREAD

**Issue by Broniy** [libre-tube/LibreTube#860]
### Describe your suggested feature

![Screenshot_20220723-190503_Vanced Manager](https://user-images.githubusercontent.com/109084455/180610822-398efea5-d3b9-4d90-a2ed-8f714dffe50a.jpg)
This is better.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Broniy** [comment]
Can you add this feature?

**Comment by Bnyro** [comment]
not possible with Kotlin
