### ISSUE TITLE
Crash when I click on a video

### ISSUE THREAD

**Issue by aitronssesin** [libre-tube/LibreTube#861]
### Steps to reproduce

1. I Click on a video or I click the download button
2. Crash

### Expected behavior

Play the video

### Actual behavior

Crash the application

### LibreTube version

0.4.1

### Android version

11

### Other details

I have an OPPO A52

### Video

https://user-images.githubusercontent.com/74368135/180620508-967ebfc6-1673-418e-b5a0-7c255ac36b4e.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Could you please provide a debug log? It could be related to #769
