### ISSUE TITLE
Option to disable autoplay

### ISSUE THREAD

**Issue by HaukaMirai** [libre-tube/LibreTube#868]
### Describe your suggested feature

If possible,I would like to request to an option to disable auto play whenever I click a video, sometimes I just want to read comments or description of videos instead of playing it,or just checking other video comments while watching separate video.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Yes, I agree that it's a good idea. Any ideas where it could be placed and how it should look?
Because we currently lack a bit of space in the player fragment.

**Comment by Nizami20052022** [comment]
![Screenshot_20220726-103301](https://user-images.githubusercontent.com/104249296/180939256-64161f7c-7aea-4bb4-9be5-8ae68be9e4db.jpg)

**Comment by Nizami20052022** [comment]
![Screenshot_20220726-103233](https://user-images.githubusercontent.com/104249296/180939311-25e02e50-9cd3-4c12-a8df-5f83910a2903.jpg)
