### ISSUE TITLE
[BUG] Importing a .json file from youtube crashes LT

### ISSUE THREAD

**Issue by Flam3z** [libre-tube/LibreTube#87]
**Describe the bug**
When i attempt to import my subscriptions json file from my SD card the app just crashes

**To Reproduce**
1. Go to the importing section
2. Click on import and go to your file manager app
3. Scroll down to your json file
4. See crash

**Smartphone (please complete the following information):**
 - Device: Samsung S10
 - Android version: 12

**Additional context**

**Comment by archroid** [comment]
It just supports the zip file you get from google takeout and not json and it had some permission issues we are working on it.

**Comment by Flam3z** [comment]
I even tried it with a zip file and it still crashes

**Comment by rzlamrr** [comment]
@archroid i believe this issue started from Android 11. I  have given permission to access files, but here i get the log

> 03-26 05:33:36.951 E/AndroidRuntime(25614): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1314141272, result=-1, data=Intent { dat=content://com.android.externalstorage.documents/document/primary:APS/takeout-20220320T202932Z-001.zip flg=0x1 }} to activity {com.github.libretube/com.github.libretube.MainActivity}: java.io.FileNotFoundException: /storage/emulated/0/APS/takeout-20220320T202932Z-001.zip (Permission denied)
