### ISSUE TITLE
Swipe down video only work

### ISSUE THREAD

**Issue by Gul7333** [libre-tube/LibreTube#872]
### Describe your suggested feature

When I swipe running video down...from sides it doesn't work...but if you swipe the video down through center of video ...it works....it is very irritating as only some of video screen is used to swipe down the video 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It's because it conflicts with double tap to seek forward/rewind. I couldn't figure out how to make both work. Currently swiping down only works in the center of the player where you can't double tap.

**Comment by Gul7333** [comment]
You should understand two thing...first difference between Draging and tapping .. tapping is only done one area...but drag is little long tapping.....And make these actions time dependent....for example tapping should only work when screen is tapped under 300ms... May be these ideas 💡 are helpful

**Comment by Bnyro** [comment]
Yes, I know that.
I already found a way to make it work but I'm currently focussing on other projects so I'm not sure when I'll do it.
