### ISSUE TITLE
do you have a android TV version

### ISSUE THREAD

**Issue by aaron2wh** [libre-tube/LibreTube#877]
### Describe your suggested feature

if possible, pls support android 4.0+ TV 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Nope, and there are no plans to support Android TV. Consider using Piped in a browser on your Android TV (e.g. piped.kavin.rocks)

**Comment by aaron2wh** [comment]
or could you add a cast to tv feature in the andriod/iOS  app. that will help a lot.
I know in today's version I can share to the phone browser. but what I mean is to have a cast button in the video frame as the native YouTube app do.
