### ISSUE TITLE
in phone, auto fullscreen does not work sometimes

### ISSUE THREAD

**Issue by ydqsbfsyi** [libre-tube/LibreTube#879]
### Steps to reproduce

with Auto Rotate OFF, Auto Fullscreen ON, in a android10 phone, start playing a video and rotate the phone to landscape, I get fullscreen successfully. But if I rotate back to portrait and switch to another video and rotate to landscape, fullscreen does not work. I have to quit and re-run the app, and it will work again.

Tested on some old version and most recent debug version.

### Expected behavior

null

### Actual behavior

null

### LibreTube version

0.4.1 debug

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I tried to reproduce it but I don't have the issue, I tried it multiple times with different phones and android versions.
