### ISSUE TITLE
[FEATURE] Amoled Dark Mode

### ISSUE THREAD

**Issue by CasuallyOrange** [libre-tube/LibreTube#88]

**Comment by lilcheti** [comment]
What's amoled?

**Comment by CasuallyOrange** [comment]
> What's amoled?

Basically black dark mode

**Comment by lilcheti** [comment]
Don't we have it rn?

**Comment by CasuallyOrange** [comment]
> Don't we have it rn?

Well what it currently has is grey-ish dark mode I'm talking about adding another option for totally black dark mode

**Comment by IceDBorn** [comment]
![image](https://user-images.githubusercontent.com/51162078/159660867-cea87c39-a4ae-447a-a386-2486d522866b.png)
Here's what amoled looks like @lilcheti

**Comment by IceDBorn** [comment]
Basically, it consists of pure black background color and dark foreground colors to ensure max battery life using an amoled screen.

**Comment by lilcheti** [comment]
@archroid

**Comment by Soup333** [comment]
> Basically, it consists of pure black background color and dark foreground colors to ensure max battery life using an amoled screen.

Reminder that amoled black and gray have almost the same battery impact so if you like gray more and only using amoled black for battery, then don't.
https://www.xda-developers.com/amoled-black-vs-gray-dark-mode/

**Comment by CasuallyOrange** [comment]
> > Basically, it consists of pure black background color and dark foreground colors to ensure max battery life using an amoled screen.
> 
> Reminder that amoled black and gray have almost the same battery impact so if you like gray more and only using amoled black for battery, then don't.
> https://www.xda-developers.com/amoled-black-vs-gray-dark-mode/

I don't even have an amoled screen lol, I just like black mode more

**Comment by Bnyro** [comment]
added with #253
