### ISSUE TITLE
for phone, force video to landscape fullscreen

### ISSUE THREAD

**Issue by ydqsbfsyi** [libre-tube/LibreTube#880]
### Describe your suggested feature

current Auto Fullscreen option is based on rotation - with auto rotate off and auto fullscreen on, if I rotate the phone back to portrait, the video will quit landscape fullscreen. 

How about another option to force/keep landscape fullscreen, like in Newpipe and Skytube? - watch video in fullscreen, otherwise everything back to portrait, I find it convenient for cell phone.

Please consider this in future version.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You mean that the player starts in landscape fullscreen, no matter whether your phone is in portrait or in landscape mode?
