### ISSUE TITLE
crash when trying to get into any library playlist, happens again

### ISSUE THREAD

**Issue by ydqsbfsyi** [libre-tube/LibreTube#881]
### Steps to reproduce

[#771](https://github.com/libre-tube/LibreTube/issues/771)

the above bug happens again in most recent debug version - in Android 9 TV, try to get into any library playlist, the app quits; in Android 10 phone, try to get into any library playlist, the screen flashes and gets me back to subscriptions, looks like the app re-runs.

### Expected behavior

null

### Actual behavior

null

### LibreTube version

0.4.1 debug

### Android version

Android 10, as well as Android 9 TV

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Already fixed
