### ISSUE TITLE
Show current resolution on Auto

### ISSUE THREAD

**Issue by lu4p** [libre-tube/LibreTube#895]
### Describe your suggested feature

Currently the Auto quality setting doesn't provide any feedback on which quality is actually fetched, it should read "Auto (1080p)" to communicate which resolution is currently used.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not possible

**Comment by lu4p** [comment]
Can you explain why you think this is not possible happy to help

**Comment by Bnyro** [comment]
We're using the HLS manifest for automatic resolutions, we can't access the current resolution of it

**Comment by lu4p** [comment]
I think it's possible 
https://github.com/google/ExoPlayer/issues/646

**Comment by Bnyro** [comment]
Yes, that makes sense, thank you for searching for it!
I honestly didn't think there would be a way

**Comment by Bnyro** [comment]
I shouldn't close issues so fast :^)
