### ISSUE TITLE
Tapping minimized Player should maximize

### ISSUE THREAD

**Issue by lu4p** [libre-tube/LibreTube#896]
### Describe your suggested feature

After the player is minimized by swiping down/ back. It should maximize again when tapping the video title/ thumbnail area, instead of only maximizing when swiping up.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Dupe
