### ISSUE TITLE
Higher Quality Thumbnails 

### ISSUE THREAD

**Issue by lu4p** [libre-tube/LibreTube#897]
### Describe your suggested feature

I can currently count pixels on video thumbnails, the app should fetch higher quality thumbnails.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
NewPipe Extractor issue
