### ISSUE TITLE
Sort Channel

### ISSUE THREAD

**Issue by lu4p** [libre-tube/LibreTube#898]
### Describe your suggested feature

On the channel page there should be a "Sort by" dropdown with the options "Most popular", "Date added (oldest)", and  "Date added (newest)" which is the default.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by lu4p** [comment]
I think you misunderstood me here I was talking about this page 

![Screenshot_20220730-023612.jpg](https://user-images.githubusercontent.com/46541492/181907757-bae553db-6698-4b31-9bed-8e97fd05734f.jpg)

I don't know if it makes sense to sort the subscription feed, probably not.

**Comment by Bnyro** [comment]
That's not possible without API changes. The API response only contains the first 20 videos, the next ones have to be fetched seperate, so we can't access all of them at the same time. The only solution I see is an API-side implementation of sorting here.

**Comment by lu4p** [comment]
Isn't this the same for subscriptions tho?

**Comment by Bnyro** [comment]
No, we get them all at once in subscriptions. We're just don't load them all at the same time because of performance needed by image loading, see https://github.com/libre-tube/LibreTube/blob/master/app/src/main/java/com/github/libretube/adapters/TrendingAdapter.kt#L32-#L38
