### ISSUE TITLE
Miniplayer shouldn't overlay main action

### ISSUE THREAD

**Issue by lu4p** [libre-tube/LibreTube#899]
### Describe your suggested feature

![Screenshot_20220729-000858](https://user-images.githubusercontent.com/46541492/181645818-dbc647f2-dd20-4652-9212-b200771a2e79.jpg)
The miniplayer cuts off the last video.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
There's no other way to do this...

**Comment by lu4p** [comment]
I think it is possible by putting the main video action and the bar into the same "container".

**Comment by Bnyro** [comment]
So that the bottom navigation is hidden when the miniplayer is active? Now I'm confused.
