### ISSUE TITLE
[FEATURE] Auto-rotate to landscape when video in fullscreen mode

### ISSUE THREAD

**Issue by MF-Debug** [libre-tube/LibreTube#90]
**Describe the feature you'd like to see added**
As the title says, currently it stays on portrait mode (device auto-rotate turned off) when I go into fullscreen mode while playing any videos. It would be nice if it automatically goes into landscape mode.

**Comment by lilcheti** [comment]
Is it ok to rotate even if it's a short video?

**Comment by MF-Debug** [comment]
I personally have no problems with rotating the short videos.

**Comment by shom13** [comment]
@lilcheti I think its expected behaviour for most people using youtube app. I personally like fullscreen mode, but sometimes landscape mode is more preferred. Having both options would be really helpful in my opinion

**Comment by lilcheti** [comment]
Yes I should add something to the settings

**Comment by Dyras** [comment]
Personally, I wish for almost the complete opposite. I wish that if I flip my phone into landscape mode, the video automatically maximizes. I believe this is the default behavior in the stock YouTube app.

**Comment by lilcheti** [comment]
This is really getting hard I'll do something and then create an issue if you didn't like the way it was.

**Comment by Dyras** [comment]
@lilcheti We believe in you man, you're already doing the world a better place by making this app. I'm sure it will be just fine.

**Comment by lilcheti** [comment]
Now it auto rotates should I close this issue?

**Comment by shom13** [comment]
Yes ofcourse if its fixed, although i cant seem to do it just yet. Is it something we can expect in the upcoming release

**Comment by novocaiin** [comment]
@lilcheti I think it shouldn't rotate on vertical videos, only horizontal ones.
