### ISSUE TITLE
Runtime of shorts is 0:00

### ISSUE THREAD

**Issue by lu4p** [libre-tube/LibreTube#900]
### Steps to reproduce

1. Go to a channel which uploads shorts

### Expected behavior

The real runtime should be shown

### Actual behavior

The runtime is shown as 0:00

### LibreTube version

0.4.1

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Api issue

**Comment by lu4p** [comment]
So I should report this to piped or where?

**Comment by Bnyro** [comment]
Yes
