### ISSUE TITLE
Pinch to zoom on Fullscreen

### ISSUE THREAD

**Issue by lu4p** [libre-tube/LibreTube#901]
### Describe your suggested feature

In Fullscreen mode pinching should switch between the normal viewing mode (Fit) and Zoom.

I would also be for removing the button which achieves the same. 

This would also mean to either:

a) remove the Fill mode completely,  I would be surprised if someone actually enjoys stretched videos

b) have a setting whether the user likes their videos zoomed or stretched.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Dupe

**Comment by lu4p** [comment]
I don't see any other issue like it, which issue did you mean?

**Comment by Bnyro** [comment]
Oh, I thought there was still an open issue for it, I probably messed sth up...
