### ISSUE TITLE
Improve watch history 

### ISSUE THREAD

**Issue by lu4p** [libre-tube/LibreTube#902]
### Describe your suggested feature

- split history by date
- add search to history
- add ability to remove a single entry from history
- clear all button should be removed and only accessible in settings 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Nephys222** [comment]
@Bnyro There is an issue on deleting watch history. Can not delete more than one. Try delete anyone then top one: app crashes

**Comment by Bnyro** [comment]
fixed
