### ISSUE TITLE
most recent debug version stuck after login

### ISSUE THREAD

**Issue by ydqsbfsyi** [libre-tube/LibreTube#904]
### Steps to reproduce

the most recent debug version has this bug, the previous (or maybe previous 3rd or 4th) version is fine.
After I installed this version, I changed settings with frequent re-run when I'm asked:

set Default Tab to be Subscriptions;
activate Authentication instance;
set an Authentication instance then an instance;
login;
after login, it stucks trying to enter Subscriptions.
I restarted my phone and it happens again.

### Expected behavior

null

### Actual behavior

null

### LibreTube version

0.4.1 debug

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I'm not able to reproduce. How many channels do you have subscribed too?

**Comment by ydqsbfsyi** [comment]
> I'm not able to reproduce. How many channels do you have subscribed too?

Thank you! About 85 channels.

**Comment by Bnyro** [comment]
You tested it again with the latest debug build?
