### ISSUE TITLE
Submenus should look like settings

### ISSUE THREAD

**Issue by lu4p** [libre-tube/LibreTube#905]
### Describe your suggested feature

I like this:
![Screenshot_20220729-012031](https://user-images.githubusercontent.com/46541492/181653336-89783bcc-4bab-4943-a193-c79be77d558e.jpg)

I don't like confusing submenus like this: 
![Screenshot_20220729-012819](https://user-images.githubusercontent.com/46541492/181654057-351ade62-57d6-4e08-b865-bdddc42127b6.jpg)

I believe submenus such as search and watch history should use the same style as settings.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I agree except with the navigation bar:  I think it is still useful on that state, I won't remove it there. Anything else seems to be a good idea, I'll look into it.
