### ISSUE TITLE
make debug version upgradable or allow overwrite installation

### ISSUE THREAD

**Issue by ydqsbfsyi** [libre-tube/LibreTube#906]
### Describe your suggested feature

I like try new debug versions, but it's a bit difficult to install. Please consider make debug version upgradable or allow overwrite installation (now I can not because of signature....), uninstall then install is fine but in that case I have to set all settings from scratch.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Making it upgradable requires bumping the version each time, which doesn't make sense.

**Comment by lu4p** [comment]
I don't know much about kotlin development but couldn't some kind of hash of the build files be used as a version.

**Comment by Bnyro** [comment]
Hmm, I don't think so
But I might have found another way, will try it tomorrow

**Comment by lu4p** [comment]
@Bnyro Is the debug version published somewhere or are people compiling it themselves?

**Comment by Bnyro** [comment]
@lu4p They are auto compiled by github actions.

**Comment by lu4p** [comment]
I found it thanks 👍

**Comment by Bnyro** [comment]
We're using yyyyMMddHH as version for debug builds now. I wanted to use YYMMddHHMM but it's out of range of Integer but the versionCode has to be an Integer.

**Comment by lu4p** [comment]
I would recommend to just use a Unix timestamp which fits in a normal 64 bit integer.

**Comment by Bnyro** [comment]
@lu4p Yeah, that' a good idea, thank you :)
