### ISSUE TITLE
[FEATURE] Manual subscription categorisation

### ISSUE THREAD

**Issue by ansarimohammed422** [libre-tube/LibreTube#91]
Categorise subscription manually like

Tech chanels in tech category

Linux channels in linux category

Food channel in food category

Give users to configure these options

E.T.C

**Comment by ansarimohammed422** [comment]
Like this
![IMG_20220319_202406](https://user-images.githubusercontent.com/78704469/159126092-1c3be35f-c90c-4319-99c4-135d8a90c67f.jpg)

**Comment by alefvanoon** [comment]
Duplicate of #67
