### ISSUE TITLE
[BUG] Crash Upon Subscription Import

### ISSUE THREAD

**Issue by it-a-me** [libre-tube/LibreTube#92]
**Describe the bug**
Whenever i try to import the subscription.zip the app crashes

**To Reproduce**
1. Download youtube data selecting only subscriptions when it ask what you want included
2. Try to import it
3. See error

 - Device: samsung s20 FE
 - Android 12

When i checked what the zip contained, i found subscription.csv under the subfolder "Youtube and Youtube Music".  Not sure if it matters but youtube music could be messing with stuff

**Comment by lilcheti** [comment]
Is the app crashing completely?

**Comment by it-a-me** [comment]
I think so.  Android 12 is weird but i get completely kicked of the app and it reopens at the home screen

**Comment by Flam3z** [comment]
Same here [#87](https://github.com/libre-tube/LibreTube/issues/87)

**Comment by shom13** [comment]
I can confirm app crashes completely when trying to import on android 11. To add to that, it only recognizes zip files, so google takeout can be imported, currently unsuccessfully, but atleast it shows. Cannot import json files as its greyed out.

**Comment by AadilGillani** [comment]
Describe the bug
Whenever i try to import the subscription.zip the app crashes

To Reproduce
Steps to reproduce the behavior:

Download youtube data selecting only subscriptions when it ask what you want included
Try to import it
See error
Device: Redmi K40 
Android 12 22.3.24

![Screenshot_2022-03-27-01-38-46-501_com.miui.bugreport.jpg](https://user-images.githubusercontent.com/15800642/160256415-93a75894-17b1-4338-afeb-1ad51dfd33ef.jpg)


When i checked what the zip contained, i found subscription.csv under the subfolder "Youtube and Youtube Music". Not sure if it matters but youtube music could be messing with stuff

**Comment by Joeb3** [comment]
The same thing happens to me too (LineageOS 18.1-Android 11)

**Comment by lilcheti** [comment]
It's already fixed and tested will be alright in the next release.
