### ISSUE TITLE
Downloads

### ISSUE THREAD

**Issue by Ekki2015** [libre-tube/LibreTube#928]
### Describe your suggested feature

Sorry for my english. Is there possible to add a future where you can watch your downloads?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That would be #557 ;)
