### ISSUE TITLE
When playing a video, when exiting the application, the video stops. 

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#934]
### Steps to reproduce

1.You have played the video
2.Exit the application with the back button.
3.The video stops.

### Expected behavior

The option for the background in the player is not good.Instead, add an option to the settings to turn this feature on or off.

### Actual behavior

The video cannot be played in the background.

### LibreTube version

0.4.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can't reproduce, if it doesn't work just use the background mode.
