### ISSUE TITLE
Seekbar preview error.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#935]
### Steps to reproduce

1.You have played the video.
2.Take the video back and forth
3.The function does not work.

### Expected behavior

The function does not work.

### Actual behavior

https://user-images.githubusercontent.com/104249296/182044506-d62d613c-1a4a-4175-867b-f2c35349846e.mp4

### LibreTube version

0.4.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The preview is that it seeks to the new position directly. So it works as intended.
