### ISSUE TITLE
A button that is not on the player.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#937]
### Describe your suggested feature

![Screenshot_20220801-005006](https://user-images.githubusercontent.com/104249296/182044888-ce9188fd-a91f-4d55-b2ca-3259b4f7b176.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The next button would do the same as autoplay or heading forward to the next available related video, I don't see a reason to add this.
