### ISSUE TITLE
The app crashes on android 5.1.1

### ISSUE THREAD

**Issue by Menorah** [libre-tube/LibreTube#94]
**Describe the bug**
The app crashes on android 5.1.1

**To Reproduce**
1. Open the app
2. The app immediately crashes

**Smartphone (please complete the following information):**
 - Device: LG 1K20
 - Android version: 5.1.1

**Additional context**
- Rooted device
-  Xposed installed

**Comment by lilcheti** [comment]
Yes please use v0.2.3 as there was some dependency updates and caused this!
