### ISSUE TITLE
Reminder when it's time to sleep

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#943]
### Describe your suggested feature

Alert when it's time to sleep or when you use the app a lot 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Nizami20052022** [comment]
Adding this feature is not difficult.

**Comment by Nizami20052022** [comment]
It would be nice to add.

**Comment by Bnyro** [comment]
There are enough other apps that do something like that and allow you to set reminders or timers.

I don't see any reason why that should be added into a video streaming app...
