### ISSUE TITLE
Move up and down the videos in the playlist.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#945]
### Describe your suggested feature

Change the position of the videos in the playlist by scrolling up and down

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.
- Change the position of the videos in the playlist by scrolling up and down

**Comment by Bnyro** [comment]
Reordering the playlists videos isn't supported by the API
