### ISSUE TITLE
Button next to the search bar to log in to our account. 

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#946]
### Describe your suggested feature

Button next to the search bar to log in to our account. 
![Screenshot_20220802-003857](https://user-images.githubusercontent.com/104249296/182242851-a26c0959-f16a-47d2-b037-0ba06e0c4a20.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't want to add it there because the account depends on the instance you're using. Users should be aware of that when they log in.
