### ISSUE TITLE
[FEATURE]  wallpaper theming

### ISSUE THREAD

**Issue by ansarimohammed422** [libre-tube/LibreTube#95]
Implement monnet theming engine in your app

Wallpaper based colour changing of your app

**Comment by skinatro** [comment]
You mean material you right?

It already exists (or atleast works for me on android 12)

**Comment by ansarimohammed422** [comment]
It doesnt works for me on android 12

**Comment by skinatro** [comment]
Try switching the theme to light mode in the settings and then back to dark mode (this fixes it for me, will open a bug ticket for this)
