### ISSUE TITLE
Default content language

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#952]
### Describe your suggested feature

![Screenshot_20220802-183218_NewPipe](https://user-images.githubusercontent.com/104249296/182400405-6da006ae-4d1e-4d08-b13c-478c024af8fd.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's what we have as region setting I guess.
