### ISSUE TITLE
Copy timecode

### ISSUE THREAD

**Issue by Archeix7** [libre-tube/LibreTube#955]
### Describe your suggested feature

You can add the function of copying timecode when holding a fragment 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't get it :(

**Comment by Archeix7** [comment]
![IMG_20220803_091018_453](https://user-images.githubusercontent.com/51048550/182536445-bae9ca6b-dfbd-4567-a5c8-27652470f606.jpg)

If you click on this fragment, you will go to the place where you watch the video, I suggest adding a copy of the link to the timecode in this area by pressing

**Comment by Archeix7** [comment]
or add the function to copy the timecode anywhere

**Comment by Bnyro** [comment]
Ohh, okay, now I get it :)

**Comment by Bnyro** [comment]
But these are no fragments, these are recyclerview items :p

**Comment by Archeix7** [comment]
Okay, okay ;)

**Comment by Bnyro** [comment]
Maybe it's better if it works for all videos and not only the ones that have video chapters? Maybe we should add time stamps to the share menu?

**Comment by Archeix7** [comment]
U can add into recyclerview items and next to it is the "full screen" button, like in Youtube Vanced

**Comment by Archeix7** [comment]
You can not add items to the recyclerview in this case, but it seems to me that it will save 2 seconds if you click on the window, and it will immediately copy the timecode, rather than go through this window and press the button that will be next to "full screen". Are these 2 seconds worth it or not - decide for yourself

**Comment by Archeix7** [comment]
![IMG_20220803_103545_082](https://user-images.githubusercontent.com/51048550/182550871-01e81835-5f05-443c-9d8d-80321c6c8536.jpg)
Like this

**Comment by Bnyro** [comment]
This button copies the time code only or does it copy the whole link? If it copied the whole link I wouldn't be sure about it cuz you can't choose between Piped and YouTube links then

**Comment by Archeix7** [comment]
Only time code

**Comment by Bnyro** [comment]
Yes, that's the whole link

**Comment by Bnyro** [comment]
I think it's better to add an option for it in the share dialog to allow choosing between Piped and YouTube links

**Comment by Archeix7** [comment]
Well, or you can combine it, next to "full screen" it will copy the video to YouTube (because most people will appear in it), the "share" button will be responsible for the piped time code. Comfortable and multifunctional, in my opinion. Or make a choice in the settings, turn on one thing near the "full screen" button or both buttons at once in the same place (also optional in the settings)

**Comment by Archeix7** [comment]
So "Choose your destiny" *mortal kombat voice*

**Comment by Bnyro** [comment]
I don't want to add a button for it there, I don't think it's important enough to get its own button

**Comment by Bnyro** [comment]
I'll add it to the share dialog, other stuff doesn't make sense to me
