### ISSUE TITLE
Sentences not added to Weblate.

### ISSUE THREAD

**Issue by Broniy** [libre-tube/LibreTube#961]
### Describe your suggested feature

![IMG-20220803-WA0004](https://user-images.githubusercontent.com/109084455/182650764-52cb4ec6-60b5-4b43-a24b-6b3028afa9a0.jpg)
![IMG-20220803-WA0005](https://user-images.githubusercontent.com/109084455/182650794-81bfc261-024e-44ef-8fd6-3c379e3f6d45.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Broniy** [comment]
Words in black frame.

**Comment by Bnyro** [comment]
We get them from Piped, we can't influence them.
