### ISSUE TITLE
Create playlists without an account

### ISSUE THREAD

**Issue by OJ7** [libre-tube/LibreTube#969]
### Describe your suggested feature

Similar to #954, but for being able to create playlists without a Piped account. 

### Other details

There are [some](https://github.com/libre-tube/LibreTube/issues/739) [related](https://github.com/libre-tube/LibreTube/issues/484) [issues](https://github.com/libre-tube/LibreTube/issues/629) that were previously closed. Now that #954 has been implemented, just wanted to see if you're open to it now. If not, feel free to close this issue. :)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Implementing local playlists itself wouldn't be a hard task, that would probably take less than an hour. The issue is that we would have to fetch the information for each video individually and can't get them all at one, which would lead to very bad loading times, probably already more than ten seconds for a small playlist.

**Comment by Bnyro** [comment]
We don't have the issue with local subscriptions anymore thanks to recent API changes by Kavin that allow collecting the subscription info on the server side.

**Comment by OJ7** [comment]
I see, thanks for the explanation. Is this something in the Piped API that would need to be changed/added to make it more performant?

Also, I noticed NewPipe seems to load playlists pretty much instantaneously for me, even with playlists with over a hundred videos. However, I think it only loads certain information (title, thumbnail, video length). Then, clicking on a video does take a second to load full details. I'm not sure how LibreTube does it currently, but maybe that may be an approach (along with caching certain basic details since those don't change often).

**Comment by Bnyro** [comment]
The API doesn't allow us to cherry pick info if we fetch it for each video individually. We would probably need API support for getting the information of several videos by using a list of video IDs as query of the GET request.

**Comment by Bnyro** [comment]
That would result in a performance similar to the one for playlists with account.

**Comment by RetroAbstract** [comment]
> Implementing local playlists itself wouldn't be a hard task, that would probably take less than an hour. The issue is that we would have is that we would have to fetch the information for each video individually and can't get them all at one, which would lead to very bad loading times, probably already more than ten seconds for a small playlist. I just don't think that there will be big benefits from it: It would probably result in more complaints than people who really benefit from it.

@Bnyro I prefer LibreTube overall to NewPipe, however local playlists is what's keeping me from switching over to LibreTube from NewPipe. 

To avoid having more complaints than people who would benefit from them, would the option to enable/disable local playlists be possible?

**Comment by Bnyro** [comment]
> @Bnyro I prefer LibreTube overall to NewPipe, however local playlists is what's keeping me from switching over to LibreTube from NewPipe.
> 
> To avoid having more complaints than people who would benefit from them, would the option to enable/disable local playlists be possible?
>
If it ever gets implemented, then it's gonna be as with the subscriptions: When logged it, it's synced with the Piped account , when not being logged in it's not being synced with the account and hence stored locally!
Anything else wouldn't really make sense in my opinion.

**Comment by Bnyro** [comment]
The PR above my comment implements playlist exactly how I didn't want to implement them at first place because of the reasons mentioned above, however I currently don't see a better solution.
