### ISSUE TITLE
[FEATURE] Add yewtu.be

### ISSUE THREAD

**Issue by Fjuro** [libre-tube/LibreTube#97]
**Describe the feature you'd like to see added**
Hey there, I love the app but it's missing a one (for me) critical thing - yewtu.be support. It's the instance I use, and if it gets added I will finally fully switch to LibreTube from NewPipe - this is the only thing holding me back.

**Additional context**
Probably nothing.

**Comment by lilcheti** [comment]
It already works with opening the links for Invidious too.

**Comment by ZachIndigo** [comment]
I would also appreciate this, so I can log in. I don't really want to make an account with a different instance, but I would like to be able to log in. Alternately, being able to add a custom instance would be a cool feature.

**Comment by FireMasterK** [comment]
Yewtu.be isn't a Piped instance, so you can't really expect support for it currently.

**Comment by Fjuro** [comment]
For some reason i thought it's using invidious, sorry
Closing the issue
