### ISSUE TITLE
Enter fullscreen on device rotation

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#970]
### Describe your suggested feature

If I pressed on a video and it starts playing, I would like to rotate my device to enter fullscreen. Bonus points if there is an option in settings to exit fullscreen on rotation or keep fullscreen (like a lock)

### Other details

The small fullscreen button is small to hit.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We already have that its called Auto-fullscreen in the audio and video settings.
