### ISSUE TITLE
Replace 3-dots menu with settings memu

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#971]
### Describe your suggested feature

In the top right corner there is a 3-dots menu that holds "settings", "about", and "community". I say remove the 3-dots menu, replace it with settings icon and relocate "about" and "community" to the settings.

### Other details

If more entries will be added this menu, you can leave it as is.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We had a community vote about it, more than 80 per cent voted for the new design. We won`t rollback to the old toolbar UI.
