### ISSUE TITLE
Tap on active filter to reset filters

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#972]
### Describe your suggested feature

![Screenshot_20220804-211507_LibreTube](https://user-images.githubusercontent.com/50382414/182934550-7dbb95c2-009e-4349-a775-2d0d7975820d.png)

Make it possible to tap an active filter to switch back to "all". 

### Other details

I am too lazy to scroll back (see screenshot) :)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That would be really confusing for many users, "all" is just a normal option like all the others, why should it switch back to it when double tapping another?
If sth like that got implemented, then it should be for deselecting all filters which doesn't make sense here.
