### ISSUE TITLE
Thumbnails on home are low resolution

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#973]
### Steps to reproduce

Go to home
Look at thumbnails

### Expected behavior

Sharp thumbnail, like everywhere else in the app

### Actual behavior

Blurry thumbnails

### LibreTube version

0.4.2

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by IceDBorn** [comment]
Newpipe extractor issue
