### ISSUE TITLE
Declutter interface

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#974]
### Describe your suggested feature

![Screenshot_20220804-211920_LibreTube](https://user-images.githubusercontent.com/50382414/182935244-d8fd56e6-9c20-4594-8aeb-3095e3e3a1b6.png)

 We see two lines of text for each video. Maybe use a slight grey fomt color for the second line.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Donkey-Doug** [comment]
Btw, also similar issue for the settings page.

**Comment by Bnyro** [comment]
I think it's good as it is right now, using different colors there just makes it look weird.
