### ISSUE TITLE
Better split screen support

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#975]
### Describe your suggested feature

The video is tiny in splitscreen

Screenshots (libretube and newpipe):

Screenshot 1 - 50/50 split
![Screenshot_20220804-212211_NewPipe_SponsorBlock](https://user-images.githubusercontent.com/50382414/182935748-4f2292d6-bfc0-4939-a892-cf92a9f7a41f.png)

Screenshot 2 - small/large split (newpipe large)
![Screenshot_20220804-212350_NewPipe_SponsorBlock](https://user-images.githubusercontent.com/50382414/182935964-8aaf38fa-3be7-4697-bcfd-b0a15be96a86.png)

Screenshot 3 - small/large split (libretube large)
![Screenshot_20220804-212411_LibreTube](https://user-images.githubusercontent.com/50382414/182935976-c7a2d5ad-fb41-4fed-9055-b25f4fa9ba14.png)

### Other details

The video is tiny

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by OJ7** [comment]
I've seen this issue too. When in splitscreen mode, the full-screen button is not visible. 
The workaround is going to full screen first and then doing splitscreen.
