### ISSUE TITLE
Import subscriptions from newpipe not working

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#976]
### Steps to reproduce

Click on import subscriptions
Toast notification: "please login and try again"

### Expected behavior

Import from newpipe

### Actual behavior

error message: Please login and try again message

### LibreTube version

0.4.2

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Maybe you should login an try again?
Importing subscriptions without an account is not yet supported.
