### ISSUE TITLE
Video still shows in Quick Settings Media Controls even after app is closed

### ISSUE THREAD

**Issue by OJ7** [libre-tube/LibreTube#977]
### Steps to reproduce

1. Start playing video
2. Close the app via recents menu or backing out the app to stop video playback
3. Pull down the notification drawer/quick settings

### Expected behavior

Observe empty media controls

### Actual behavior

Observe video showing in media controls

### LibreTube version

0.4.2

### Android version

Android 12

### Other details

Looks similar to #461

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I observed the same behavior with other music players (e.g. Retro Music) too. It got resolved by disabling the "Pin Media Player" option in the settings, see the screenshot.

Regards

![Screenshot_20220809-101801_Settings](https://user-images.githubusercontent.com/82752168/183600696-abc6b7ca-f206-494b-9a2d-9a1d3abbb6a1.png)
