### ISSUE TITLE
Preserve playback speed when switching to audio only

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#978]
### Describe your suggested feature

If I set playback speed to 2x in a video and then decide to move to audio only mode, the playback speed resets to 1.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It now uses the same speed as the normal player
