### ISSUE TITLE
All chapters have the thumbmail image

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#979]
### Steps to reproduce

For some videos, all chapters have the thumbmail image.

![Screenshot_20220804-214723_LibreTube](https://user-images.githubusercontent.com/50382414/182940103-91079517-1f6c-46e8-83bc-74b06e8aa0ae.png)

### Expected behavior

Correct previews

### Actual behavior

Thumbnails shown

### LibreTube version

0.4.2

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We just use the one provided by the API which uses the NewPipeExtractor, so if it is an issue, its theirs

**Comment by FireMasterK** [comment]
![image](https://user-images.githubusercontent.com/20838718/183021370-aecf3921-6c25-4a0b-b36e-05dc09e74f65.png)
It's like that on YouTube...
