### ISSUE TITLE
Change brightness and volume in video player

### ISSUE THREAD

**Issue by DataStream3** [libre-tube/LibreTube#980]
### Describe your suggested feature

When watching a video in fullscreen, you can swipe from the bottom to the top or vice versa (on left or right side of the screen) to change the device's brightness or volume. This feature is the only reason why i haven't switched from NewPipe to LibreTube. It would be great to have in LibreTube! 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We already had more than 3 issues for it, the answer is still the same. There are no plans to add such a feature, there were some discussions about it and most people agreed that it's rather annoying than useful.
