### ISSUE TITLE
Keep at most x entries in watch history

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#985]
### Describe your suggested feature

Let the user choose a number x such that at most x entries are shown in the watch history. 

### Other details

Having complete history might be considered a privacy issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FireMasterK** [comment]
It's literally stored locally on your device 👀
How's that a privacy issue

**Comment by Bnyro** [comment]
The only reason why this could be useful is for storage space reasons, although the watch history entries shouldn't take notable space...
And what does the amount of stored videos in the history change about privacy? You either disable it completely or you have the data on your phone, what's the difference between having 10 or 300 entries there?
