### ISSUE TITLE
Not my Video

### ISSUE THREAD

**Issue by Archeix7** [libre-tube/LibreTube#986]
### Steps to reproduce

1. Watch 2, 3 video
2. Stop at 3 (for example)
3.Turn off the screen so that after a while the application goes to sleep
4. Turn on the screen and instead of video 3 there will be video 2. 
It works almost always, and turning off the screen is necessary for the application to fall asleep for such a bug to occur, you can just pause video3 (I did it in windowed mode) turn it on again and start playing video2

### Expected behavior

.

### Actual behavior

.

### LibreTube version

Latest

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Not able to reproduce and the issue itself doesn't make sense to be honest, information gets overwritten when playing the next video, this bug literally can't occur, no matter what you do.
