### ISSUE TITLE
Upload watched history file

### ISSUE THREAD

**Issue by Kenji-1984** [libre-tube/LibreTube#988]
### Describe your suggested feature

Is it possible to implement a way to define a server URL (self hosted) for Uploading the files that stored localy (like watched history and playlists).
So they can be used on many  Devices.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
No, it's not possible and there are no plans to add it. Important things like the playlists can be synced with the API, doing the same thing with the watch history doesn't make sense in my eyes.
